### ISSUE TITLE
Is it possible to try it somehow?

### ISSUE THREAD

**Issue by priezz** [tekezo/Karabiner-Elements#1]
Is there a way to use kext's from this repo to be used with Karabiner/Seil?

P.S. I had to add
```
#pragma clang diagnostic ignored "-Wnonnull"
```
in the beginning of `src/grabber/grabber/include/human_interface_device.hpp` to build the project.

**Comment by tekezo** [comment]
There is no way at the moment.

The current source code allow you to change the caps lock key to the delete key for demonstration.
But it breaks the modifier flags and the fn key behavior.

I'll release an installer after all problem is fixed. Please wait.

**Comment by priezz** [comment]
Ok, thanks. Waiting :)

25 июля 2016 г. 5:46 пользователь Takayama Fumihiko <notifications@github.com> написал:

There is no way at the moment.

The current source code allow you to change the caps lock key to the delete key for demonstration.
But it breaks the modifier flags and the fn key behavior.

I'll release an installer after all problem is fixed. Please wait.

**Comment by tekezo** [comment]
Now you can try Karabiner-Elements by this way.
https://github.com/tekezo/Karabiner-Elements/blob/master/usage/README.md

**Comment by LucaMarconato** [comment]
I have got the same problem, is there a way to fix it?
