### ISSUE TITLE
Restriction for input source

### ISSUE THREAD

**Issue by unnamed777** [tekezo/Karabiner-Elements#100]
Is it possible to restrict rule by language kind of <inputsource_only> in Karabiner? I want to remap paragraph key (button to the left of "1") in one way for English and another for Russian. Or is there any way to switch profiles when input source has been changed?

**Comment by unnamed777** [comment]
Looks like I was able to catch input source changing via hammerspoon and now I can swap configs depending on language (got idea from [this tutorial)](https://github.com/tekezo/Karabiner-Elements/issues/67). An example - https://gist.github.com/unnamed777/27fe64a1bed0ee9dc52ff84b434fc254
But frequently karabiner server starts with noticeable lag about 3-5 secs and in this time I have unchanged keyboard. Can config be reloaded without killing server?

**Comment by vlsi** [comment]
@unnamed777 , there's `input_source_if` now, see https://github.com/pqrs-org/KE-complex_modifications/pull/205

**Comment by vlsi** [comment]
Just for the reference:
Example 1: https://github.com/tekezo/Karabiner-Elements/blob/1643bdbd49cb7fa84adba44dd0e940b9b8948a63/tests/src/manipulator_conditions/json/input_source.json
Example 2: https://github.com/pqrs-org/KE-complex_modifications/blob/master/src/json/example_input_source.json.erb
