### ISSUE TITLE
How can quit KE through hammerspoon or applescript or shell, please?

### ISSUE THREAD

**Issue by bianbian-org** [tekezo/Karabiner-Elements#1001]
I wanna bind a shortcut key in hammerspoon to start/stop KE.
I have started KE successfully (and kill Preferences Window when lanched), but don't know how to stop it.
Is it possible to quit KE through hammerspoon or applescript or shell?
I tried these:

```
local km = hs.application.get('Karabiner-Menu')
km:kill()
```

Yes, Karabiner-Menu is gone, but these two processes still running:
karabiner_grabber (root)
karabiner_console_user_server

and when try to kill, Karabiner-Menu will start again.

Thanks.

I used the shortcut key to start/stop bluetooth (for keyboard) too.
So my objective is starting bluetooth/KE when keyboard on, kill them when off.

**Comment by bianbian-org** [comment]
If KE has an apt like "Karabiner-Elements -forcequit" ...

**Comment by bianbian-org** [comment]
sudo kill -9  $(pgrep "arabiner")

the above 3 process will go back soon...

**Comment by tekezo** [comment]
```
launchctl bootout gui/`id -u`/org.pqrs.karabiner.karabiner_console_user_server
launchctl disable gui/`id -u`/org.pqrs.karabiner.karabiner_console_user_server
```

**Comment by bianbian-org** [comment]
thanks!
karabiner_console_user_server is gone, but the behavior is not right.
(My pref is: when KE/bluetooth keyboard is active, the Apple keyboard is disabled;
when KE stopped, Apple keyboard should come back but not)
maybe because karabiner_grabber (root) is still running.

**Comment by tekezo** [comment]
If Apple keyboard does not come back, (it's a bug of macOS), please kill karabiner_grabber once.

```
sudo killall karabiner_grabber
```

Then Apple keyboard should be back.

Note:
If you are using this feature, erase the system default configuration to avoid karabiner_grabber modify devices without karabiner_console_user_server.
![170924-0001](https://user-images.githubusercontent.com/659178/30780833-37007ace-a14f-11e7-9e7e-a74f29719a70.png)

**Comment by bianbian-org** [comment]
it's all right, despite karabiner_grabber (root) is still running. thanks!

**Comment by tavurth** [comment]
I really needed this script because KE was interfering with another program, nice to be able to disable it quickly. Here's the script:

1) Save it in a file named `kcontroller.sh`
2) Make that file executable: `chmod u+x kcontroller.sh`
3) Run it as follows:
 - To start the server `./kcontroller.sh start`
 - To stop the server `./kcontroller.sh stop`

```sh
#! /bin/sh

usage() {
    echo "Usage:"
    echo
    echo "$0 start|stop"
    echo
    exit 0
}

if [[ $# -eq 0 ]] ; then
    usage
fi

# How long should we wait for KE to start?
SLEEP_TIMEOUT=1

case "$1" in
    "start")
        echo "Starting server..."
        /Applications/Karabiner-Elements.app/Contents/MacOS/Karabiner-Elements &
        sleep $SLEEP_TIMEOUT
        sudo kill -9 $(pgrep "Karabiner-Menu")
        sudo kill -9 $(pgrep "Karabiner-Elements")
        echo "Done.";;
    "stop")
        echo "Stopping server..."
        sudo launchctl bootout gui/501/org.pqrs.karabiner.karabiner_console_user_server 2>/dev/null
        sudo launchctl disable gui/501/org.pqrs.karabiner.karabiner_console_user_server 2>/dev/null
        echo "Done.";;
    *) usage
esac
```

**Comment by januz** [comment]
I have a similar problem. I use `vim_emu`. As I had problems with the Mac still being in `NORMAL-MODE` after it wakes up, I want to disable and reenable KE whenever the display sleeps using Hammerspoon.

I use the shell command

```
launchctl disable org.pqrs.karabiner.karabiner_console_user_server && launchctl enable org.pqrs.karabiner.karabiner_console_user_server
```

(I used different variations of the above command, specifying `gui/`id -u`` or `user/`id -u``, but none worked...)

This doesn't seem to have any effect. Interestingly enough, the same shell command works in a Keyboard Maestro macro in which I restart KE every time the frontmost application changes.

Does anyone have an idea what I'm doing wrong? Thanks!

**Comment by cvladan** [comment]
Ah, nothing works now :(

**Comment by GenhaoLi** [comment]
> Ah, nothing works now :(

Both start and stop scripts work fine for me with Karabiner-Elements version 14.12.0 on macOS 14.2.1
