### ISSUE TITLE
URL support?

### ISSUE THREAD

**Issue by cmsj** [tekezo/Karabiner-Elements#1006]
Hey @tekezo - as you may remember, I added support in Karabiner for opening URLs as the action of a modification and I am thinking about whether to do the same in Karabiner Elements.

I know you have `shell_command` already, so we could just open URLs with `/usr/bin/open`, but if you're prepared to accept an `open_url` operation type, I'm prepared to write it :)

**Comment by obfischer** [comment]
I would be happy to see your URL support in KE.

**Comment by obfischer** [comment]
This issue is still relevant.

**Comment by andrewferrier** [comment]
I know @cmsj mentioned it above, but just to be crystal clear, I'm using this style of workaround in my `karabiner.json`, and it works just fine. The `-g` runs the URL in the background so it doesn't switch window focus.

```
"from": {
 "key_code": "fn",
},
"to": [
 {
  "shell_command": "open -g hammerspoon://shortcut"
 }
],
"type": "basic"
```

**Comment by nkgm** [comment]
I too would love to see this feature land. `shell_command` is a good workaround but I feel there should be first class support for such an important feature.
