### ISSUE TITLE
How to implement function like __HoldingKeyToKey__ in karabiner?

### ISSUE THREAD

**Issue by babyking** [tekezo/Karabiner-Elements#1008]
```xml
<autogen>__HoldingKeyToKey__ KeyCode::S, ModifierFlag::NONE, KeyCode::S, KeyCode::VK_NONE, KeyCode::CONTROL_L</autogen>
<autogen>__HoldingKeyToKey__ KeyCode::D, ModifierFlag::NONE, KeyCode::D, KeyCode::VK_NONE, KeyCode::OPTION_L</autogen>
<autogen>__HoldingKeyToKey__ KeyCode::F, ModifierFlag::NONE, KeyCode::F, KeyCode::VK_NONE, KeyCode::COMMAND_L</autogen>
<autogen>__HoldingKeyToKey__ KeyCode::L, ModifierFlag::NONE, KeyCode::L, KeyCode::VK_NONE, KeyCode::CONTROL_R</autogen>
<autogen>__HoldingKeyToKey__ KeyCode::K, ModifierFlag::NONE, KeyCode::K, KeyCode::VK_NONE, KeyCode::OPTION_R</autogen>
<autogen>__HoldingKeyToKey__ KeyCode::J, ModifierFlag::NONE, KeyCode::J, KeyCode::VK_NONE, KeyCode::COMMAND_R</autogen>
```
configuration below in karabiner, type s only send s,held down s then send left control.

In karabiner elements,I want use flowing configuration To achieve the same function

```json
{
  "description": "type s to s,held down to control",
  "manipulators": [
    {
      "from": {
        "key_code": "s"
      },
      "to": [
        {
          "key_code": "left_control"
        }
      ],
      "to_if_alone": [
        {
          "key_code": "s"
        }
      ],
      "type": "basic"
    }
  ]
}
```

But it has a problem ,for example, when I type 's' 'k' quickly ,sometimes it will send control+k,in fact I want the result is 's' 'k'!  But there is no such problem in karabiner.

 I also noticed that the same problem occurred on  VI Mode rule. when you type d k quickly, somtimes it send  'up_arrow'!

![image](https://user-images.githubusercontent.com/478250/31019020-ea84974a-a4f3-11e7-8ea2-657e904954af.png)

How to deal with it!

**Comment by eliasbe** [comment]
I have the same problem. It's the only thing now keeping me from upgrading from El capitan.

These are the paramaters I adjust:

<img width="760" alt="screen region 2017-10-02 at 07 41 44" src="https://user-images.githubusercontent.com/14940059/31116528-f97c8dfa-a815-11e7-9ac5-48e9d4050a3e.png">

I was wondering if I could add these paramaters to the json file but I don't know what they would be named

![screen region 2017-10-03 at 08 38 24](https://user-images.githubusercontent.com/14940059/31116687-93846a1c-a816-11e7-952a-e26c5c795154.png)

Is this possible?

**Comment by babyking** [comment]
[#849](https://github.com/tekezo/Karabiner-Elements/issues/849)
