### ISSUE TITLE
Swapping left control and command

### ISSUE THREAD

**Issue by nmaves** [tekezo/Karabiner-Elements#101]
I am using the following configuration and a Microsoft keyboard.

```
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "left_command": "left_option",
                "left_option": "left_command"
            }
        }
    ]
}
```

When I watch the event viewer I see the following when hitting the left windows ket and alt.

```
eventType:FlagsChanged    code:0x37       name:Command_L       flags:Cmd                                misc:characters:    
eventType:FlagsChanged    code:0x37       name:Command_L       flags:                                   misc:characters:    
eventType:FlagsChanged    code:0x3a       name:Option_L        flags:Opt                                misc:characters:    
eventType:FlagsChanged    code:0x3a       name:Option_L        flags:                                   misc:characters:    
```

**Comment by motte** [comment]
left_control
left_command

**Comment by nmaves** [comment]
That did not work either.  The two keys I was to swap are 

```
eventType:FlagsChanged    code:0x3a       name:Option_L        flags:Opt                                misc:characters:    
eventType:FlagsChanged    code:0x3a       name:Option_L        flags:                                   misc:characters:    
eventType:FlagsChanged    code:0x37       name:Command_L       flags:Cmd                                misc:characters:    
eventType:FlagsChanged    code:0x37       name:Command_L       flags:                                   misc:characters:    
```

```
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "left_command": "left_control",
                "left_control": "left_command"
            }
        }
    ]
}
```

**Comment by DanielYJG** [comment]
Well, if i edit the json file with txt Editor of Mac system, the code doesn't work either. Edit the file online or with other professional json editor may help.

**Comment by nmaves** [comment]
This does not seem to be an issue with reading the json config as other key modifications work.  Just not swapping the left control and option.

**Comment by taylorbird** [comment]
I'm having this same problem.  Microsoft keyboard.  The action to swap Option L to Command L works is intended. But the action to swap Command L to Option seems to be ignored, so I currently dont have a function Option L key in this config.

**Comment by nmaves** [comment]
Can you share your config?

**Comment by taylorbird** [comment]
Now it appears to be working, not sure what was going on but after reboot its fine.

`{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
            	"left_option": "left_command",
            	"left_command": "left_option"     
            }
        }
    ]
}`

**Comment by nmaves** [comment]
I just tried your configuration and a restart and nothing.  Did you uninstall the old Karabiner?
