### ISSUE TITLE
Can't boot High Sierra after using "Copy profile to system default"

### ISSUE THREAD

**Issue by yyylny** [tekezo/Karabiner-Elements#1011]
I noticed that every time I click on either the "Copy current profile to system default profile" or "Remove system default profile" buttons in Karabiner's preferences, my Mac can't boot (It shows a "no entry" sign on boot). It started happening after I upgraded to High Sierra. Even a clean install didn't help (It works the first time but the next time I click the aforementioned buttons I can't boot anymore).

**Comment by tekezo** [comment]
Your issue is not Karabiner-Elements's issue.

It's a High Sierra or hardware issue.
Please confirm your machine is stable before install Karabiner-Elements.

**Comment by yyylny** [comment]
You're probably right because last night I couldn't boot even though Karabiner wasn't active at all. Sorry for that.
