### ISSUE TITLE
Caps Lock stops working after I uninstall Karabiner-Elements.

### ISSUE THREAD

**Issue by sesm** [tekezo/Karabiner-Elements#1014]
Currently I have zero mappings in Karabiner-Elements.
When I uninstall it via Misc->Uninstall and restart, Caps Lock stops working. 
After I install Karabiner-Elements again, Caps Lock starts working.

I'm using internal keyboard on MacBook Pro, OS: macOS High Sierra (10.13)

If you need any info to investigate this issue, I'll be happy to help.

**Comment by mdawaffe** [comment]
In System Preferences → Keyboard → Keyboard Tab, click the "Modifier Keys…" button. Is Caps Lock set to "No Action" there?

**Comment by sesm** [comment]
@mdawaffe Yes, that was the issue!
Thank you!
Closing this ticket now.
