### ISSUE TITLE
Launching Karabiner-Elements at login

### ISSUE THREAD

**Issue by NevinBR** [tekezo/Karabiner-Elements#1018]
In System Preferences I added Karabiner-Elements as a login item, and it does indeed launch. However, it also opens the Karabiner window when I log into my computer. This is undesirable, as I don’t want to modify my keyboard settings every login, I just want Karabiner to start functioning in the background.

Is there a way to have Karabiner Elements automatically launch at login, without opening its window every time?

**Comment by isalsberg-mx** [comment]
Same thing.

**Comment by Timidfriendly** [comment]
Same here too. Also looking for a solution.

**Comment by cycle4passion** [comment]
me too

**Comment by tekezo** [comment]
Karabiner-Elements starts automatically at login without login items.
Please remove Karabiner-Elements from login items.

**Comment by NevinBR** [comment]
> Karabiner-Elements starts automatically at login without login items.
> Please remove Karabiner-Elements from login items.

In my experience, Karabiner-Elements will \*restart\* automatically at login, if it was running when I logged off. However, if for any reason it was \*not\* running at the time I logged out, then it will not launch at login. I would rather have it launch at login regardless of whether it was running previously.

Additionally, from a purely user-experience perspective, I greatly prefer to have all my login items listed and managed from one place—namely the Login Items pane for my account. Thus, all else being equal, I \*want\* to put Karabiner-Elements as a login item, and I do \*not\* want it (or any other program I install) to launch automatically if it isn’t there.

**Comment by dzurn** [comment]
Do we still need "Karabiner" as a Login-item with Karabiner Elements? I've removed it but wondering if it was supposed to be uninstalled somehow...

**Comment by isalsberg-mx** [comment]
Takezo's comment from Dec 9th 2017 solved the issue.
Just remove Karabiner-Elements from login items.

**Comment by jmuheim** [comment]
I'm still confused about this. Shouldn't there be an option "Launch on startup" in the GUI?

**Comment by habibalamin** [comment]
AppleScript workaround
----------------------

1. Open a new Script Editor document, set the language to AppleScript if it isn't already, and insert this snippet into the script body:

```applescript
do shell script "launchctl load -w /Library/LaunchAgents/org.pqrs.karabiner.karabiner_console_user_server.plist"
```

2. Save the script into any directory you like; maybe the same directory as Karabiner-Elements and Karabiner- EventViewer, with a name like, “Karabiner-Loader”. I think these options are optimal:

  - “File Format: Application”
  - “Show startup screen” unchecked
  - “Stay open after run handler” unchecked

3. Go to System Preferences → Users & Groups → Login Items, and add Karabiner-Loader to the list.

**Comment by vargaradu** [comment]
> * “File Format: Application”
> * “Show startup screen” unchecked
> * “Stay open after run handler” unchecked

@habibalamin  Where can the above settings be found?
