### ISSUE TITLE
Map the Return key to left_control only when it’s held down?

### ISSUE THREAD

**Issue by kourosh2** [tekezo/Karabiner-Elements#102]
Does anyone know how I can map the Return key to the left_control only when it’s held down on Karabiner-Elements? I used to have it on el-captain and it was pretty useful for me. Any insight is much appreciated. 

Thanks

**Comment by talha131** [comment]
You can't, yet. See #8

**Comment by kourosh2** [comment]
@talha131 Thanks.

**Comment by crazytan** [comment]
It's basically the only reason I use Karabiner as an Emacs user; desperately want to know if there's some other way to achieve this

**Comment by zhengpd** [comment]
This can be done with the `complex_modifications` from latest version. For the example modification rules you can see https://pqrs.org/osx/karabiner/complex_modifications/json/caps_and_return_to_ctrl.json
