### ISSUE TITLE
Hold Command+Q to Quit Application?

### ISSUE THREAD

**Issue by baurmatt** [tekezo/Karabiner-Elements#1020]
I'm missing the "Hold Command+Q to Quit Application" shortcut in Karabiner Elements. Could this please be implemented?

**Comment by cvogt** [comment]
here is an alternative: click cmd+q twice instead of a long press. Use this URL in Safari:
`karabiner://karabiner/assets/complex_modifications/import?url=https%3A%2F%2Fpqrs.org%2Fosx%2Fkarabiner%2Fcomplex_modifications%2Fjson%2Fcommand_q.json`

**Comment by baurmatt** [comment]
Thanks! :) This works great, even though I'm now running into (https://github.com/tekezo/Karabiner-Elements/issues/46) and can't use CTRL+SHIFT+EJECT for locking my screen -.- Its a shame...
