### ISSUE TITLE
please add some function    like under  the iterm2

### ISSUE THREAD

**Issue by qw9002** [tekezo/Karabiner-Elements#1023]
1. ctrl-u  "clear line"
2. ctrl-w "clear the front of line word"

**Comment by nguyenhimself** [comment]
> ctrl-u "clear line"
So:
1. Command + Right Arrow to move to end of line.
2. Command + Delete to delete from end to start of line.

> ctrl-w "clear the front of line word"
In other words: Option + Delete.

Should be easy to add to the JSON.
