### ISSUE TITLE
Apple Spanish keyboard layout

### ISSUE THREAD

**Issue by diegofn** [tekezo/Karabiner-Elements#1025]
Hello Tekezo,

Currently we have a issue with my Apple Keyboard in Spanish.
Before, I solve the issue with Karabiner, using the following rule

```
<item>
      <name>Swap ordinal-indicator(º) and less-than(&lt;)</name>
      <identifier>remap.spanish_swap_ordinal_indicator_lessthan</identifier>
      <autogen>__KeyToKey__ KeyCode::SPANISH_ORDINAL_INDICATOR, KeyCode::SPANISH_LESS_THAN</autogen>
      <autogen>__KeyToKey__ KeyCode::SPANISH_LESS_THAN, KeyCode::SPANISH_ORDINAL_INDICATOR</autogen>
</item>
```

Can you help me explain how can I migrate this rule to Karabiner-Elements in JSON.

Thanks for your help

**Comment by bytesplit** [comment]
Have you set your virtual Keyboard to ISO instead of ANSI? On my German keyboard this fixed the Circumflex (left of 1) with < switch thing.

Preferences > Virtual Keyboard > Keyboard Type : Set to ISO

Related to #1035 and #390?
