### ISSUE TITLE
How do I map an upper case (e.g., F, V)?

### ISSUE THREAD

**Issue by mbabco** [tekezo/Karabiner-Elements#1026]
How do I map to an upper case, such as V? 

I go to add item. In the drop-down menu I see the lower-case alphabet (e.g., v). How do I change that to upper-case (e.g. V)?

I'm actually mapping a Thai keyboard. For instance, when I type what is normally a k, I want it to be an 8 (which would actually be a Thai character). When I type a shift-k (K), I want it to be an open-bracket ( [ ).

Sorry for such an elementary question. It seems I should be able to figure that out but I haven't been able to.

I would have the same question about mapping to "option-v" or "option-V"

Thanks.

**Comment by NevinBR** [comment]
You need to use modifier keys. Don’t think of it as mapping “uppercase K”, but rather as mapping “the K key while holding shift”. You could additionally make one for “the K key while caps lock is active”.

For your second question, think about mapping “option-v” and “option-shift-v”.

**Comment by mbabco** [comment]
Thanks for answering. My problem is that I don't know how to do the mapping.

I click "add item" and am given a drop-down menu with all my options. I can select k but there doesn't seem to be any way to select shift-K or to select anything with modifier keys. Or I can select a modifier key but not the k. How can I select both together? How do I get both left-shift and k in the from field?

Do I need to do this by modifying the .json file.

**Comment by nguyenhimself** [comment]
Yes you need to edit the JSON.

```
"from": {
    "key_code": "V",
    "modifiers": [
        "left_shift"
    ]
},
"to": [
    {
        "key_code": "open_bracket",
    }
],
```

**Comment by mbabco** [comment]
Thank you so much. I can most likely figure it out from here. I appreciate the assistance.

**Comment by mbabco** [comment]
Thanks so much for the help.

Unfortunately, I'm still not able to make it work. When I modify the file ~/.config/karibiner.json –  changes I make to that file do not seem to register with Karibiner-Elements. For instance, I took out one of the simple mappings I did from the .json file but it was not reflected in the keyboard.

Question 1: Once I change the .json file, how do I get Karabiner-Elements to use it.

Also, I'm not exactly certain where in the .json file I should be inserting your code – whether or not I need to specify that it is complex_modification and then whether I need to insert some code to that effect.

I'm going to attach the .json file as I have it so far. If you could insert your code into that file with all the necessary modifications, I think once I saw that one example in place and working, that I could figure out the rest.

Thanks in advance. I'm sorry I'm a little slow on all this stuff!

[karabiner.txt](https://github.com/tekezo/Karabiner-Elements/files/1408208/karabiner.txt)

**Comment by xcode-manolo** [comment]
Hi @mbabco  !!!
Don't worry.  We all started like this.
I recommend to you to **+Add rule** the most simple rule you see, e.g. **_Change escape key_**.
Then look for your file into the karabiner folder to accommodate Complex Modifications, that must be like this: _/Users/MyUserName/.config/karabiner/assets/complex_modifications/1510470140.json_ and edit its code.

````{
  "title": "Change escape key",
  "rules": [
    {
      "description": "Post caps_lock if escape is pressed alone.",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "escape",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "escape"
            }
          ],
          "to_if_alone": [
            {
              "key_code": "caps_lock"
            }
          ]
        }
      ]
    }
  ]
}
````

The edition of this file consists of erasing the **"to_if_alone"** section and overwrite the **"from":** and **"to":** sentences
with a bunch of code similar to the one written by @nguyenhimself.  
Change the text of the title and the description as well and you'll get the following code.

````{
  "title": "Change Shift+v to Open bracket",
  "rules": [
    {
      "description": "Post open bracket if shift+v is pressed.",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "v",
            "modifiers": {
              "mandatory": [
                "left_shift"
              ],
              "optional": [
                "caps_lock"
              ]
            }
          },
          "to": [
            {
              "key_code": "open_bracket"
            }
          ]
        }
      ]
    }
  ]
}
````

Now, delete the rule "Change escape" listed under Karabiner-Elements/Complex Modifications tab and press again "+Add rule", this time looking for "Change Shift+v to Open bracket" from the list offered by Karabiner-Elements.  If your rule doesn't appear (the most frequent thing) is because it has a typo or a syntax error (maybe you miss a comma or something else).  And that's all.  Enjoy your keyboard @mbabco !!!

Have a great day !!!

**Comment by coder054** [comment]
@nguyenhimself can you have me on my problem
I want  close square bracket turn to @
and      close curly bracket turn to ^
I have this code
```
{
                    "from": {
                        "key_code": "close_bracket",
                        "modifiers": [
                            "left_shift"
                        ]
                    },
                    "to": [
                        {
                            "key_code": "6",
                            "modifiers": [
                                "left_shift"
                            ]
                        }
                    ]
                },
                {
                    "from": {
                        "key_code": "close_bracket"
                    },
                    "to": [
                        {
                            "key_code": "2",
                            "modifiers": [
                                "left_shift"
                            ]
                        }
                    ]
                },
```
but when I press the close square bracket with or without the shift modifier, I get "@" in both cases
How can I archive this?
