### ISSUE TITLE
Alt + Shift to Ctrl + Space

### ISSUE THREAD

**Issue by tadeator** [tekezo/Karabiner-Elements#1027]
Hey,

i use Karabiner Elements and i would like to be able to change source input (keyboard language) via Windows shortcut Alt + Shift.

How to do it? It would be nice, if you can implement it, so i can easilly import it, it is very useful function and many people will appreciate it.

Thanks in advance.

**Comment by babyking** [comment]
A better way to change source input :
```json
{
    "description": "Shift switch input method",
    "manipulators": [
        {
            "from": {
                "key_code": "left_shift",
                "modifiers": {
                    "optional": [
                        "any"
                    ]
                }
            },
            "to": [
                {
                    "key_code": "left_shift"
                }
            ],
            "to_if_alone": [
                {
                    "key_code": "0",
                    "modifiers": [
                        "left_control",
                        "left_option",
                        "left_command"
                    ]
                }
            ],
            "type": "basic"
        },
        {
            "from": {
                "key_code": "right_shift",
                "modifiers": {
                    "optional": [
                        "any"
                    ]
                }
            },
            "to": [
                {
                    "key_code": "right_shift"
                }
            ],
            "to_if_alone": [
                {
                    "key_code": "0",
                    "modifiers": [
                        "left_control",
                        "left_option",
                        "left_command"
                    ]
                }
            ],
            "type": "basic"
        }
    ]
}
```

![image](https://user-images.githubusercontent.com/478250/31316199-83c73452-abee-11e7-8b8d-0d67e6ab37a3.png)

**Comment by mskonovalov** [comment]
@babyking
unfortunately it will lead to switch with single Shift instead of Shift+Alt
We need something "to_if_mandatory" in addition to "to_if_alone" or change the behavior of to_if_alone (if "mandatory" is set it should be counted in "to_if_alone")

**Comment by berpcor** [comment]
Hello. I have the same question. I need alt+shift to change switch between languages on Mac OS. Is it possible somehow?

**Comment by mskonovalov** [comment]
@berpcor yes it is.
But alt+shift+something else will also switch the language. So you will not be able to use any other alt+shift+... combinations

**Comment by MOZGIII** [comment]
I based my own solution off of this and created a repo - https://github.com/MOZGIII/karabiner-input-switch
For the future, in case things stop working - Karabiner version at the time I write this is 12.9.0.

**Comment by grimsa** [comment]
I had a similar need (use `Alt`+`Shift` to switch input sources), but I also wanted to retain `Ctrl`+`Space` (which was a shortcut used in other software I needed).

So I changed MacOS input switch shortcut to be `Alt`+`Shift`+`Z`, and then added the following rule:
```
{
    "description": "Windows style input source switch (Alt+Shift to Alt+Shift+Z (custom MacOS shortcut))",
    "manipulators": [
        {
            "from": {
                "key_code": "left_shift",
                "modifiers": { "mandatory": ["left_option"] }
            },
            "to": [
                {
                    "key_code": "left_shift",
                    "lazy": true,
                    "modifiers": ["left_option"]
                }
            ],
            "to_if_alone": [
                {
                    "key_code": "z",
                    "modifiers": ["left_shift", "left_option"]
                }
            ],
            "type": "basic"
        }
    ]
}
```
Note: this works if you first hold `Alt` and then press `Shift`, but not the other way around (if you hold `Shift` and then press `Alt`).
