### ISSUE TITLE
Swap ± with tilde

### ISSUE THREAD

**Issue by galioy** [tekezo/Karabiner-Elements#1028]
In Karabiner it was possible to swap ± (the key above Tab) with tilde (~).  In Karabiner-Elements there's no such option... or at least I cannot find it. Is that possible? Same goes basically for mapping the Bulgarian Phonetic "ч" to "±".

**Comment by nguyenhimself** [comment]
Maybe try this: Open Karabiner-EventViewer, see what keystroke got sent when you type the keys you wish to change, then add new rules to the JSON.

**Comment by kmejka** [comment]
Hi, I needed to do this swapping on my external Mac keyboard, as when I connected it, Karabiner changed the keyboard layout. I managed to do this by configuring the mapping of  `non_us_backslash` with `grave_accent_and_tilde`

**Comment by galioy** [comment]
@kmejka solved it!

**Comment by kmejka** [comment]
Great! Glad I could help you :)

**Comment by jarnot9** [comment]
![screenshot 2018-03-28 17 33 58](https://user-images.githubusercontent.com/25624977/38063487-5278a920-32ae-11e8-8d09-5b98283819d6.png)

doesn't seem to be working for me

**Comment by mickeyperlstein** [comment]
wish they had a "clikc on the key and i'll select it for you" how am i supposed to know that non_us_backslash is +- ??

**Comment by jgclark** [comment]
@mickeyperlstein That's what the Karabiner Event Viewer does for you -- see screenshot in the comment 2 before yours.

**Comment by RobRomijnders** [comment]
NB: for me this was fixed when I switched back from ISO keyboard layout to ANSI keyboard layout. However, that might also incur other changes ofc 
<img width="480" alt="image" src="https://github.com/user-attachments/assets/211f31e2-ee8c-4507-974e-a93917fd148d">
