### ISSUE TITLE
Changing Profiles with shortcut

### ISSUE THREAD

**Issue by dyyybek** [tekezo/Karabiner-Elements#1029]
How can i change profiles with keyboard?

Essentially i want to replicate this behaviour from previous version of Karabiner:

```
  <item>
      <name>Switch Profiles</name>
      <appendix>FN + 1 = "Normal", FN + 2 = "Glyphs"</appendix>
      <identifier>private.switch_profile</identifier>
      <autogen>__KeyToKey__ KeyCode::KEY_1, ModifierFlag::FN, KeyCode::VK_OPEN_URL_APP_Karabiner_Profile0</autogen>
      <autogen>__KeyToKey__ KeyCode::KEY_2, ModifierFlag::FN, KeyCode::VK_OPEN_URL_APP_Karabiner_Profile1</autogen>
  </item>
```

**Comment by ww7** [comment]
https://pqrs.org/osx/karabiner/document.html#command-line-interface

**Comment by dyyybek** [comment]
Thanks!
I figured it out with the help of some downloadable _complex modifications_.
Is there a documentation available for all the different types like "shell_command" etc?

**Comment by xcode-manolo** [comment]
@dyyybek, @ww7, I have read the answer, but I don't know how to make that call to the profile in the command line, from a complex modification.
I made my complex modification like this:


{
  "title": "f3 to change Karabiner profile",
  "rules": [
    {
      "description": "f3 to change Karabiner profile",
      "manipulators": [
        {
          "from": {
            "key_code": "f3",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "VK_OPEN_URL_APP_Karabiner_cli_MyOwnProfile"
            }
          ],
          "type": "basic"
        }
      ]
    }
  ]
}

<img width="497" alt="f3 to change karabiner profile json" src="https://user-images.githubusercontent.com/32187469/31702433-454c25ca-b3d7-11e7-86e4-57ff38e1dcc7.png">



  I guess it may be a sintaxis bug, can you help me, please ?

**Comment by ww7** [comment]
@xcode-manolo 
use [Command line interface](https://pqrs.org/osx/karabiner/document.html#command-line-interface)
`'/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli' --select-profile 'example1'`
`'/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli' --select-profile 'example2'`

```json
"to": [
            {
              "shell_command": "'/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli' --select-profile 'example2'"
            }
          ]
```

**Comment by xcode-manolo** [comment]
@ww7 

Thanks guy !!!
What a powerful feature !!!

I really appreciate your help !!!
A million thanks !!!

**Comment by XstrongMen** [comment]
Ok, but where to type this:

"to": [
  {
    "shell_command": "'/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli' --select-profile 'example2'"
  }
]

And what to click to switch the profile?

Thank you.

**Comment by xcode-manolo** [comment]
Hi XstrongMen !!!

You can see where to type that slice of code in my first post above.

And you can (click) assign that change of profile to whatever key you write at the

 “from” : { 
       “key_code” : “here_you_must_write_the_key_you_must_to_click_to_change_the_profile”,

section.

Regards dude, good luck !!!

**Comment by ldiunyh** [comment]
Hi Some experts here please tell me how to do it from scratch, i know nothing about coding. Or can you just please tell me what to learn in order to understand how to do it? Thanks!

**Comment by wmertens** [comment]
@ldiunyh you need to edit the karabiner json config (look under misc tab to have button that opens finder at its location) and add e.g. this to the complex modifications section of the profile where you want it:

```json
          {
            "description": "Press left-shift+caps_lock to enable default profile",
            "manipulators": [
              {
                "from": {
                  "key_code": "caps_lock",
                  "modifiers": { "mandatory": ["left_shift"] }
                },
                "to": [
                  {
                    "shell_command": "'/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli' --select-profile 'Default profile'"
                  }
                ],
                "type": "basic"
              }
            ]
          }
```

**Comment by chinchin96** [comment]
Thanks @wmertens for that sample. It worked like a charm.  I'd like to create a second one to switch back to the original profile. I tried it and one of the keyboard shortcuts work, the other doesn’t.  Here is what my config file looks like:

The shortcut to switch from Default to Vimium works but to switch back from Vimium to Default does not. Any ideas?

`{
    "global": {
        "check_for_updates_on_startup": true,
        "show_in_menu_bar": true,
        "show_profile_name_in_menu_bar": true
    },
    "profiles": [
        {
            "complex_modifications": {
                "parameters": {
                    "basic.simultaneous_threshold_milliseconds": 50,
                    "basic.to_delayed_action_delay_milliseconds": 500,
                    "basic.to_if_alone_timeout_milliseconds": 1000,
                    "basic.to_if_held_down_threshold_milliseconds": 500,
                    "mouse_motion_to_scroll.speed": 100
                },
                "rules": [
                    {
                        "description": "Press left-option+o to enable Vimium",
                        "manipulators": [
                            {
                                "from": {
                                    "key_code": "o",
                                    "modifiers": {
                                        "mandatory": [
                                            "left_option"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "shell_command": "'/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli' --select-profile 'Vimium'"
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    },
                       {
                        "description": "Press left-option+p to enable Default",
                        "manipulators": [
                            {
                                "from": {
                                    "key_code": "p",
                                    "modifiers": {
                                        "mandatory": [
                                            "left_option"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "shell_command": "'/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli' --select-profile 'Default'"
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    },`

**Comment by earslap** [comment]
@chinchin96 Check the "Profiles" tab of the preferences. Is your default profile really named "Default"? Its name is probably "Default profile" and not "Default".

**Comment by ValeoMooha** [comment]
@chinchin96 To change back to "Default"(or whatever other profile), this code should be in "Default" profile "complex_modifications" rules, because when you changed to "Vimium" profile it will use its own rules, and there is no rule in it to get back ))

```
{
                        "description": "Press left-option+o to enable Vimium",
                        "manipulators": [
                            {
                                "from": {
                                    "key_code": "o",
                                    "modifiers": {
                                        "mandatory": [
                                            "left_option"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "shell_command": "'/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli' --select-profile 'Vimium'"
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    },
```

**Comment by humblehacker** [comment]
I created [this script](https://gist.github.com/humblehacker/06151a3c9b2bd4029b0236c322aacc78) to choose the next profile in the list each time it's run. You should be able to use it in `"shell_command"` above, but I've not tried it.

```sh
#!/usr/bin/env zsh

alias kb="/Library/Application\ Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli"

# Get the list of items
IFS=$'\n' items=($(kb --list-profile-names))

# Get the current item
current_item=$(kb --show-current-profile-name)

# Find the index of the current item
for i in {1..$#items}; do
  if [[ "${items[$i]}" == "$current_item" ]]; then
    current_index=$i
    break
  fi
done

# Determine the next index
if [[ $current_index -eq $#items ]]; then
  next_index=1
else
  next_index=$((current_index + 1))
fi

# Select the next item
next_profile="${items[$next_index]}"
kb --select-profile $next_profile
echo "$next_profile selected"
```

**Comment by AustinCDavis** [comment]
I made a similar design a few days ago after having some issues. I made it so you can cycle through profiles  by clicking the 1 button on my mouse keypad, but if you don’t have a mouse with programmable buttons you can alter the code to work based on your keyboard.

Here is my GitHub issue page:
[Issue #3878](https://github.com/pqrs-org/Karabiner-Elements/issues/3878)

made a step-by-step guide for what I done to make my code work and included some notes to help
