### ISSUE TITLE
[KeyMove] Control_L+hjkl to Left/Down/Up/Right

### ISSUE THREAD

**Issue by RyoIkarashi** [tekezo/Karabiner-Elements#103]
Is there any way to use `Control_L+hjkl to Left/Down/Up/Right` to move cursor?
If it's not possible with Karabiner-Elements yet, do you know any alternatives to achieve the above?

![screen_shot_2016-09-23_at_2_36_19](https://cloud.githubusercontent.com/assets/5750408/18759278/c2493bfa-8136-11e6-9635-93660593eadd.png)

**Comment by ebzlo** [comment]
See #16 :)

**Comment by RyoIkarashi** [comment]
Thanks for the reply!
Now I know it's not supported yet because it's limited to swapping two keys for now.
I've just donated for this awesome app :)

Do you know any alternatives to achieve this?

**Comment by seangaffney** [comment]
@RyoIkarashi I'm eagerly awaiting the same functionality, it's hardcoded into the way I type and navigate now... I've found a temporary solution by using [Keyboard Maestro](https://www.keyboardmaestro.com/main/) (they have a trial, although its length seems to be unspecified) with the following macros set up:

![](https://www.dropbox.com/s/606hky8niuw61le/Screenshot%202016-09-22%2014.14.46.png?dl=1)

**Of note:** Make sure that the hotkey is set for "is down" and not "is pressed" if you want key-repeat to function normally.

Actually, [here's a gist of the xml](https://gist.github.com/seangaffney/6b60bd7a56e4d0e5b402f6bf93329ea3). You can just download the raw.

**Comment by RyoIkarashi** [comment]
Thanks for the quick reply @seangaffney and an awesome workaround!
Here is exactly what I want! 😄

**Comment by seangaffney** [comment]
Ha, yeah, I guess that's one of the benefits of actually _remapping_ (what Karabiner does) vs. _macros_ like Keyboard Maestro. I use vim for editing, so highlighting in this way isn't a big of a deal for me. 😄

**Comment by EvanLovely** [comment]
Thanks for this idea @seangaffney ! I needed what @RyoIkarashi needed, so I just hashed it out further (though I use Diamond Keys instead of Vim keys). I've got my macros up in [this gist](https://gist.github.com/EvanLovely/f0661e30f41655b21f8e4dbb47008e1e) and I'll try to keep it up to date with any bugs I come across in my uses. My keyboard muscle memory is ruined without this!!

![2016-09-22 at 12 29 pm](https://cloud.githubusercontent.com/assets/569699/18762995/38c3c592-80c0-11e6-9fc2-cd6ece1dcde9.png)

**Comment by seangaffney** [comment]
@EvanLovely Nice!

> My keyboard muscle memory is ruined without this!!

Haha, same.

**Comment by RyoIkarashi** [comment]
Thanks for your great ideas @EvanLovely !
I also came up with the same solution and made [a gist](https://gist.github.com/RyoIkarashi/38373481a517b3a61876d9018090e788) which may be the same with @EvanLovely 's one :)

**Comment by mariuslucamarius** [comment]
Do you guys know a way to distinguish between the left and the right CMD keys in the trigger?

**Comment by cicloid** [comment]
I'm also missing this functionality, but for know, I reimplemented the functionality temporally (I hope) in Hammerspoon

```lua
local function keyCode(key)
  return function() hs.eventtap.keyStroke({}, key) end
end

hs.hotkey.bind({"cmd", "alt"}, 'h', keyCode('left') ,  nil,   keyCode('left'))
hs.hotkey.bind({"cmd", "alt"}, 'j', keyCode('down') ,  nil,   keyCode('down') )
hs.hotkey.bind({"cmd", "alt"}, 'k', keyCode('up')   ,  nil,   keyCode('up') )
hs.hotkey.bind({"cmd", "alt"}, 'l', keyCode('right'),  nil,   keyCode('right') )
```

**Comment by greneholt** [comment]
I also just donated for this feature. I've been using Karabiner for years to turn JKIL into arrow keys when semicolon is held down, and I find computers practically unusable when they don't have this setup.

**Comment by watsoncj** [comment]
I've hard-coded the arrows as `fn+hjkl` here: https://github.com/watsoncj/Karabiner-Elements/commit/5531032a309fe99e7e153cb725b9f44a19da69c0

Not quite the same, but you can probably tweak it to match your preferences.

cc: @greneholt @cicloid @ryolkarashi @seangaffney @mariuslucamarius @evanlovely @ebzlo

**Comment by kkamdooong** [comment]
I found another solution by using [Hammerspoon](http://www.hammerspoon.org/).(I inspired from @cicloid)
Here is [hammerspoon configuration](https://github.com/kkamdooong/hammerspoon-control-hjkl-to-arrow/blob/master/init.lua). It just remmaping `contrl + hjkl` to `arrow keys`

**Comment by raulchen** [comment]
@cicloid @kkamdooong: Thanks for your suggestions about hammerspoon, I tried it, but key repeat is super slow (compared with just holding arrow keys), do you have the same problem?

**Comment by kkamdooong** [comment]
@raulchen 
release note on hammerspoon v0.9.49
```
Changed: hs.eventtap.keyStroke() and .keyStrokes() now wait 200ms between the keydown and keyup events, to improve reliability
```

One of Hammerspoon team member comment this issue https://github.com/Hammerspoon/hammerspoon/issues/1011#issuecomment-261114434
So I edited my code [this way](https://github.com/kkamdooong/hammerspoon-control-hjkl-to-arrow/commit/8c12cf46d20bb049c65210a300123120d0bd0a15)

**Comment by raulchen** [comment]
@kkamdooong thanks, it works great

**Comment by cperryk** [comment]
Thank you, @watsoncj! The solution you shared worked like a charm. Made your [code changes](https://github.com/watsoncj/Karabiner-Elements/commit/5531032a309fe99e7e153cb725b9f44a19da69c0) and built manually.

Also tried Hammerspoon first like @kkamdooong and @raulchen but noticed that the key repeat would often suddenly halt after holding the key down for a couple seconds.

**Comment by xiaoheiyohehe** [comment]
hard-coded the arrows as ctrl+hjkl here: 
[ctrl-hjkl-arrows](https://github.com/xiaoheiyohehe/Karabiner-Elements/tree/ctrl-hjkl-arrows)

**Comment by cray0000** [comment]
You can use [⌘英かな](https://ei-kana.appspot.com/) for it and for other simple multikey remaps.

**Comment by briansoule** [comment]
I also made a quick branch implementing left_option+hjkl   
[opt-hjkl-arrows](https://github.com/briansoule/Karabiner-Elements/tree/opt-hjkl-arrows)
