### ISSUE TITLE
Microsoft mouse button 4

### ISSUE THREAD

**Issue by fv62** [tekezo/Karabiner-Elements#1030]
How to remap the button?
In event viewer it shows:
eventType:MouseDown       code:0x3        name:button4         flags:                                   misc:{720,142} 1
eventType:MouseUp         code:0x3        name:button4         flags:                                   misc:{720,142} 1

But through available keys I cant find anything like button4.
Tried to edit config file 
                            "from": {
                                "key_code": "button4"
                            },
                            "to": {
                                "key_code": "open_bracket"
                            }
The same.

**Comment by raczMedia** [comment]
it's "pointing_button" not "key_code" for any mouse buttons
