### ISSUE TITLE
How set environment variables for "shell_command"

### ISSUE THREAD

**Issue by ww7** [tekezo/Karabiner-Elements#1031]
I'm seeking, how set shell variables for "shell_command". 
Where stored config for environment what used in "shell_command"?

Output for `"shell_command": "env > ~/environment.txt" `:
```
SHELL=/bin/zsh
TMPDIR=/var/folders/zm/xc8r24zn3b3btg9t13vmmbvm0000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.1m6IRnxQXh/Render
USER=w
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.P4LuGvISiB/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
PATH=/usr/bin:/bin:/usr/sbin:/sbin
PWD=/
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/w
LOGNAME=w
_=/usr/bin/env
```
Trying to add variable with `launchctl setenv MPD_HOST $HOME/.mpd/socket` does not give results

**Comment by GhostValk** [comment]
Got a similar problem, i want to bind a tmux shell command to a key, but need to inherit the environment :(
