### ISSUE TITLE
Karabiner swapped 'grave_accent_and_tilde' and 'non_us_backslash' on Apple Keyboard

### ISSUE THREAD

**Issue by andybergon** [tekezo/Karabiner-Elements#1032]
I had no problems with Karabiner-Elements while I was using only my laptop (MBP15) keyboard the this morning I attached an external keyboard (Apple Keyboard) and noticed 2 keys were swapped. Those were 'grave_accent_and_tilde' (`\` and `~`) and 'non_us_backslash' (`§` and`±`). 

I had to hard code the back swap to return to normality.
![image](https://user-images.githubusercontent.com/5220825/31339612-56cba042-acfb-11e7-8ce7-8dfe118320e2.png)

Is this a know bug or what?

Not relevant but I was using Karabiner-Elements to use the `caps lock` key as an hyper key (`cmd+alt+ctrl+shift`) following the guide [here](http://brettterpstra.com/2017/06/15/a-hyper-key-with-karabiner-elements-full-instructions/).

**Comment by dreyks** [comment]
same issue here. didn't even think it was because of karabiner, thought that it was a system glitch after connecting a noname bluetooth keyboard.

so I just rebooted my mac and everything went back to normal =)

**Comment by andybergon** [comment]
@dreyks So you didn't need to re-bind to 2 keys? I'll remove those and give restarting a shot.

**Comment by dreyks** [comment]
yeah I didn't. I forgot both that karabiner can affect or fix this so I just rebooted. windows habits die hard :D

**Comment by andybergon** [comment]
Just tried to restart and remove the 2 bindings. The error returned and I had to re bind the 2 keys.

Let's see what @tekezo thinks. :)

**Comment by andybergon** [comment]
It also changes my bind for `shift+Fx`. I need to use `shift+F6` but it isn't recognized.

**Comment by andybergon** [comment]
I get completely different behaviours with the external keyboard or with the MBP keyboard. With the internal one I can't even use the fn buttons. I tried both enabling and disabling the following option.

![image](https://user-images.githubusercontent.com/5220825/31364599-c731b9ea-ad5d-11e7-849f-3447c51dbb51.png)

**Comment by andybergon** [comment]
A recap of the other things I noticed.
On external Apple keyboard:
- `Eject` key stopped working (noticed using the shift+ctrl+Eject shortcut to lock the mac)
On the MBP keyboard:
- `fn` key stopped triggering the touchbar to show the Fx button. Can't use the function button while not connected to an external keyboard.

**Comment by tomislav** [comment]
Eject doesn't work because it's handled deep in the macOS internals where Karabiner can't touch it.

You can get `fn` working by sleeping and waking your MacBook.

**Comment by andybergon** [comment]
@tomislav 
Can't Karabiner just leave the default behaviour for the `eject` button? Does it really need to disable it?

**Comment by tomislav** [comment]
AFAIK it creates a virtual keyboard. I've read that PowerKey enables the key if you need it.

https://github.com/pkamb/PowerKey

**Comment by mkborregaard** [comment]
This is a long-standing issue (the actual issue, not the unrelated comments above)

**Comment by andybergon** [comment]
@mkborregaard 
As it is a long-standing issue do we know if it will be fixed or not?

**Comment by mkborregaard** [comment]
I have no idea but I sincerely hope so. It's annoying to have to change profiles every time I plug in my external keyboard.

**Comment by mkborregaard** [comment]
FWIW I still have this issue.

**Comment by jarnot9** [comment]
thank you! fixed my ~ !!

**Comment by beesperester** [comment]
> For me < and > are swapped with ^ and ° suddenly? Is this related?
> 
> /e: Yeah, I hard-code fixed this by swapping 'grave_accent_and_tilde' and 'non_us_backslash' for my bindings in the Karabiner JSON. System: OSX, Using an ANNE Pro Keyboard with otherwise german layout. Happend some days ago, I think - can't tell why.

I am experiencing the same issue on my 2021 MacBook Pro running macOS 14.5 and karabiner elements on version 14.13.0. I am using an external Magic Keyboard. Both the Magic Keyboard and the internal Keyboard have german layout.

Manually switching both keys works as a workaround.

**Comment by rph8** [comment]
This issue is apparently back with macOS Sequoia 15.1 (24B83) and Karabiner 15.3.0. I updated macOS and Karabiner pretty much at the same today today and then the issue started. Can somebody confirm / let me know what the suggested fix is?

**Comment by flifflof** [comment]
> This issue is apparently back with macOS Sequoia 15.1 (24B83) and Karabiner 15.3.0. I updated macOS and Karabiner pretty much at the same today today and then the issue started. Can somebody confirm / let me know what the suggested fix is?

Yup, i have this issue as well with Karabiner 15.3.0 and Sequoia 15.1.
Dollar sign $ (below Esc key (EU keyboard)) switched places with < (to the right of left shift key)

Fixed with this temporary complex modification rule for now:
<code>{
    "description": "dollar less than switcharoo",
    "manipulators": [
        {
            "from": { "key_code": "non_us_backslash" },
            "to": [{ "key_code": "grave_accent_and_tilde" }],
            "type": "basic"
        },
        {
            "from": { "key_code": "grave_accent_and_tilde" },
            "to": [{ "key_code": "non_us_backslash" }],
            "type": "basic"
        },
        {
            "from": {
                "key_code": "grave_accent_and_tilde",
                "modifiers": { "mandatory": ["shift"] }
            },
            "to": [
                {
                    "key_code": "non_us_backslash",
                    "modifiers": ["shift"]
                }
            ],
            "type": "basic"
        }
    ]
}</code>

**Comment by undefdev** [comment]
I have the same issue with MacOS 15.1.1 (24B91).

**Comment by undefdev** [comment]
I just noticed while setting up another MacBook, that this issue seems to be fixed if I change the Virtual Keyboard -> Keyboard Type to ANSI instead of ISO. 😅
