### ISSUE TITLE
What is the term for the windows break/pause key?

### ISSUE THREAD

**Issue by zeg-io** [tekezo/Karabiner-Elements#104]
This is what I have for my current son file.  I want the `grave_accent_and_tilde` to instead be the windows break/pause key so that I have a power key if using my ergonomic windows keyboard.

``` json
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "grave_accent_and_tilde": "power"
            }
        }
    ]
}
```

**Comment by motte** [comment]
pause

**Comment by zeg-io** [comment]
Ok, so now I have the below karabiner.json file, but I am getting: `[warning] parse error in /Users/tonyarcher/.karabiner.d/configuration/karabiner.json: parse error - unexpected end of input`

```json
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "pause": "power"
            }
        }
    ]
}
```

Ideas?

**Comment by talha131** [comment]
@zeg-io Try this and let e know how it goes.

```json
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "grave_accent_and_tilde": "pause"                
            }
        }
    ]
}
```

This will map `` ` `` to `pause` key. 

> ... so that I have a power key if using my ergonomic windows keyboard.

No idea.
