### ISSUE TITLE
Key repeat speed

### ISSUE THREAD

**Issue by alexandre-g** [tekezo/Karabiner-Elements#1046]
Hi,
Is the key repeat speed setting that was there in Karabiner missing in Karabiner-Elements simply due to lack of hands, or is there some underlying change in Sierra that would require looking for a new approach?

I'm badly missing the custom speed - the standard MacOS KeyRepeat speed of 1 is too slow, and 0 much too fast, and setting a float value seems to default to 0.

**Comment by vfiset** [comment]
bump

**Comment by tekezo** [comment]
Unfortunately, It's impossible since macOS Sierra due to the change of kernel internal architecture.

**Comment by iansinnott** [comment]
For anyone wondering how to set key repeat in Sierra or above: 

```
defaults write -g InitialKeyRepeat -int 10 # normal minimum is 15 (225 ms)
defaults write -g KeyRepeat -int 1 # normal minimum is 2 (30 ms)
```

From this answer: https://apple.stackexchange.com/questions/10467/how-to-increase-keyboard-key-repeat-rate-on-os-x

**Comment by alexandre-g** [comment]
@tekezo 3 years later I'm still struggling with slow key repeat 😄 . I saw there were some big changes in the last update - any chance this now has become possible?

**Comment by tekezo** [comment]
Unfortunately, the speed of the key repeat is not changeable even with v13.0.0.
Karabiner-Elements follows the key-repeat speed of macOS, as it sends key events through a virtual keyboard.

**Comment by MuhammedZakir** [comment]
> Unfortunately, the speed of the key repeat is not changeable even with v13.0.0.
> Karabiner-Elements follows the key-repeat speed of macOS, as it sends key events through a virtual keyboard.

Can KarabinerElements limit key-repeat speed by mimicking key-repeat? For example, by sending multiple key events instead of a single event when a key is held down? This way, we can set fastest possible value in system settings and adjust in KE. However, this will possibly affect user login if system wide configuration is not set. I don't know much about this, so just ignore this if it's sound silly!

**Comment by Nightstrom-NoS** [comment]
> > Unfortunately, the speed of the key repeat is not changeable even with v13.0.0.
> > Karabiner-Elements follows the key-repeat speed of macOS, as it sends key events through a virtual keyboard.
> 
> Can KarabinerElements limit key-repeat speed by mimicking key repeat? For example, by sending multiple key events instead of a single event when a key is held down? This way, we can set fastest possible value in system settings and adjust it in KE. However, this will possibly affect user login if system wide configuration is not set.
> 
> I don't know much about this, so just ignore this if it's sound silly!

I need that feature so badly. Razer Synapse for Mac no longer works. In games that need you to spam buttons my hand hurts so bad after awhile. I need to be able to hold down a key on a Razer Tartarus and it spam the key. I would pay for this feature. I tried the key repeat in Mac, it did nothing.
