### ISSUE TITLE
Problem with external keyboard

### ISSUE THREAD

**Issue by hmeine** [tekezo/Karabiner-Elements#1047]
Unfortunately, I have problems with layer 4 of the Neo2 layout when using an external Microsoft USB keyboard with German layout that is connected indirectly through a roline KVM switch (which assigns a generic USB HID device ID to the keyboard).  The EventViewer shows
```
eventType:KeyDown         code:0xa        name:non_us_backslas flags:                                   misc:
eventType:KeyUp           code:0xa        name:non_us_backslas flags:                                   misc:
```
when pressing the `<>|` key for layer 4, although I have the Neo2 settings enabled.

We discussed this in more depth in https://github.com/jgosmann/Karabiner-Elements-Neo/issues/15  for @jgosmann's fork, but now I gladly switched back to the upstream version.

**Comment by jgosmann** [comment]
Did you try adding a simple modification mapping `non_us_backslash` to `right_command`?

Se also jgosmann/KE-complex_modifications#1.

**Comment by hmeine** [comment]
Thanks.  I seem to have chosen right_control by accident or because I did not know better, now that I tried again that did indeed work!

Can/should that be automated as part of the Neo2 setup?
