### ISSUE TITLE
Change keyboard layout with command+shift

### ISSUE THREAD

**Issue by knutov** [tekezo/Karabiner-Elements#1051]
Is it possible to change keyboard layout with command+shift ?

**Comment by ww7** [comment]
For now exist three ways for this, I recommend to wait version 11.2 for native Karabiner-Elements feature for changing keyboard layout's (input sources)
[NEWS 11.2 beta](https://github.com/tekezo/Karabiner-Elements/blob/94bf0b67a41a7db9d8b083ea1728b84b4bb076b6/NEWS.md)
old methods [1](https://github.com/tekezo/Karabiner-Elements/issues/994), [2](https://github.com/tekezo/Karabiner-Elements/pull/1009)

**Comment by knutov** [comment]
Now 11.3 is available. Where can I find examples for changing keyboard layout with command+shift?

**Comment by ww7** [comment]
I wait examples too

**Comment by ww7** [comment]
#1110

**Comment by vsalex** [comment]
Just configured Karabiner 11.4.0 to map Cmd + Shift to Cmd + e which is previous language source in my Keyboard shortcuts. Write full description here https://apple.stackexchange.com/a/308900/267800

**Comment by kolyambo** [comment]
@rtm-ctrlz @vsalex thank you sooo much 👍 made rotation for 2 languages (en->ru->en), for lazy persons - https://gist.github.com/kolyambo/345b3fa9f5463f136e880e4166636123

**Comment by RuslanIsh** [comment]
Or can just set something like F19 to toggle keyboard layout in System Preferences and then map your shortcut to F19. For two languages it will just toggle back and forth anyway, no need for input_source_if.

**Comment by onemanstartup** [comment]
If you have solved your problems close issues, there is 790 issues. And changing keyboard layout is not one of them :) Many examples exists already

**Comment by Dreamisdead** [comment]
@knutov Using latest karabiner with your gist, but there is problem - can't use screenshot function when holding cmd+shift, pressing 4 or 3  with cmd+shift held down results in cmd+3 or cmd+4.

Any idea how to fix this?
I can go shift then cmd+4
But can't go cmd then shift+4 like I usually able to with punto switcher software for example.

**Comment by knutov** [comment]
@Dreamisdead I did not find the solution, so I have to teach myself to use command+space instead :(

**Comment by mpachin** [comment]
@rtm-ctrlz Thank you so much, your config worked for me! However I've got @Dreamisdead problem with shift+cmd+4. I'll try to look into solving it.

Plus probably I should add that this config works for cmd+shift, but not in other way around. Anyway I'm happy that it works at all, it was a pain to ctrl+space for each language toggling.

**Comment by noma4i** [comment]
If somebody will look for a solution to make old keys behave same as usual when not pressed alone. Check my gist https://gist.github.com/noma4i/91765f432f777c690aa3bddae37cfe3e
Idea is to bypass existing key while having additional rule.

**Comment by xentrax** [comment]
@knutov Solution still works.

Interestingly, I use usual PC Keyboard (A4Tech) and I remapped Option<->Command for "Karabiner VirtualHIDKeyboard".
Still, the Karabiner seems to ignore that and your particular script reacts to physical press to Win+Shift combination.

**Comment by e-tverdokhleb** [comment]
swich with simple press left_shift -> us, right_shift->ua 

`"rules": [
                    {
                        "description": "Right Shift to UA",
                        "manipulators": [
                            {
                                "from": {
                                    "key_code": "right_shift",
                                    "modifiers": {
                                        "optional": [
                                            "any"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "right_shift",
                                        "lazy": true
                                    }
                                ],
                                "to_if_alone": [
                                    {
                                        "select_input_source": {
                                            "language": "uk"
                                        }
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    },
                    {
                        "description": "Right Shift to US",
                        "manipulators": [
                            {
                                "from": {
                                    "key_code": "left_shift",
                                    "modifiers": {
                                        "optional": [
                                            "any"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "left_shift",
                                        "lazy": true
                                    }
                                ],
                                "to_if_alone": [
                                    {
                                        "select_input_source": {
                                            "language": "en"
                                        }
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    }
                ]
            }`

**Comment by ballonura** [comment]
There is any way to alt+shift(left) for changing to the "next" language? (like windows)

**Comment by mortihead** [comment]
> There is any way to alt+shift(left) for changing to the "next" language? (like windows)

4 blocks of rules
1  rule - switch en -> ru by Ctrl+Shift if en input source selected
2  rule - switch ru -> en by Ctrl+Shift if ru input source selected
3, 4 - same but Shift+Control (i can't write one rule with equal Ctrl+Shift = Shift+Ctrl)
		    
```
{
		        "description": "Ctrl+Shift - change input source to ru",
			"manipulators": [
			    {
				"conditions": [ {"type": "input_source_if", "input_sources": [{"language": "en"}]}],
			        "from": {"key_code": "left_shift", "modifiers": {"mandatory": ["left_control"]}},
     		                "to": [{ "key_code": "left_shift","lazy": true, "modifiers": ["left_control" ]  } ],
				"to_if_alone": [  {"select_input_source": { "language": "ru" } } ],
				"type": "basic"
		            }]
		    },
		    {
		        "description": "Ctrl+Shift - change input source to en",
			"manipulators": [
			    {
				"conditions": [ {"type": "input_source_if", "input_sources": [{"language": "ru"}]}],
			        "from": {"key_code": "left_shift", "modifiers": {"mandatory": ["left_control"]}},
     		                "to": [{ "key_code": "left_shift","lazy": true, "modifiers": ["left_control" ]  } ],
				"to_if_alone": [  {"select_input_source": { "language": "en" } } ],
				"type": "basic"
		            }]
		    },
		    {
		        "description": "Ctrl+Shift - change input source to ru",
			"manipulators": [
			    {
				"conditions": [ {"type": "input_source_if", "input_sources": [{"language": "en"}]}],
			        "from": {"key_code": "left_control", "modifiers": {"mandatory": ["shift"]}},
     		                "to": [{ "key_code": "left_shift","lazy": true, "modifiers": ["left_control" ]  } ],
				"to_if_alone": [  {"select_input_source": { "language": "ru" } } ],
				"type": "basic"
		            }]
		    },
		    {
		        "description": "Ctrl+Shift - change input source to en",
			"manipulators": [
			    {
				"conditions": [ {"type": "input_source_if", "input_sources": [{"language": "ru"}]}],
			        "from": {"key_code": "left_control", "modifiers": {"mandatory": ["shift"]}},
     		                "to": [{ "key_code": "left_shift","lazy": true, "modifiers": ["left_control" ]  } ],
				"to_if_alone": [  {"select_input_source": { "language": "en" } } ],
				"type": "basic"
		            }]
		    },

```

My code allow process any Ctrl+Shift+Key pressed in future.

**Comment by Evengard** [comment]
```
"to": [{ "key_code": "left_shift","lazy": true, "modifiers": ["left_command" ]  } ],
"to_if_alone": [  {"select_input_source": { "language": "en" } } ],
```
is the solution for Command+Shift disabling screenshots, thank you!
