### ISSUE TITLE
make backtick like on PC

### ISSUE THREAD

**Issue by knutov** [tekezo/Karabiner-Elements#1052]
How to make backtick key be like on PC keyboard?

I have russian macbook with ANSI keyboard layout.

I want backtick (`) be backtick  (button left from "1") in English keyboar layout and being Ё letter in Russian layout. At the same time I want command command+` be command+` even in russian layout.

Baktick seems to be non_us_pound on ANSI keyboard. 

It it possible?

Switching virtual keyboard to ISO is not exactly the same and some times stopping working at all.

**Comment by aol-nnov** [comment]
here you go!
`karabiner://karabiner/assets/complex_modifications/import?url=https://gist.githubusercontent.com/aol-nnov/fec5674610cc9f686ff00e254ef23da8/raw/da46d19b4df13eef1585736cf4b8dc8b49c6895b/krb-elements-swap-yo.json`
(paste this to your browser location bar)
I thought I'd go nuts before finding info on `input_source_if`

CC: https://github.com/tekezo/Karabiner-Elements/issues/384 @eugenesvk

**Comment by knutov** [comment]
Does not work for me, also I see error

[2017-10-31 02:29:47.637] [error] [grabber] complex_modifications json error: unknown `type` input_source_if in {"input_sources":[{"language":"en"}],"type":"input_source_if"}

in `log` tab

**Comment by aol-nnov** [comment]
@knutov what version do you have? Upgrade at least to Karabiner-Elements 11.1.8.
I have 11.1.11 installed and it works like a charm!
Also, remember to remove your simple modifications of `non_us_backslash` and `grave_accent_and_tilde` as they will no longer be needed. (sure, last statement is not related to your current problem)

**Comment by knutov** [comment]
OS X 10.13

After upgrade to Karabiner-Elements 11.1.11 (I did fresh install and upgrade to latest beta) error is gone, but switching is not working. I already tried to restart Karabiner-Elements.

**Comment by knutov** [comment]
Oh, yes, I switched back to ANSI from ISO and now it works, thanks!

**Comment by aol-nnov** [comment]
@knutov right, ANSI virtual kerboard.. forgot to mention that and did not test it with ISO, to be frank.

**Comment by knutov** [comment]
@aol-nnov the new problem with it - command+` is not remapped in this case, and I suppose other compinations too. How should I modify json rules to fix it?

**Comment by aol-nnov** [comment]
@knutov yeah, faced this today at work too!
check the [updated gist](https://gist.githubusercontent.com/aol-nnov/fec5674610cc9f686ff00e254ef23da8/raw/cb16a08e6860c83690f8e366ca056a4af7e45f1e/krb-elements-swap-yo.json)
works for me, but YMMV! :)

**Comment by knutov** [comment]
@aol-nnov works fine, thanks!

**Comment by knutov** [comment]
How to add this to https://pqrs.org/osx/karabiner/complex_modifications/ ?

It will be easy to setup.
