### ISSUE TITLE
SimultaneousKeyPresses and support for chording

### ISSUE THREAD

**Issue by arialdomartini** [tekezo/Karabiner-Elements#1057]
With Karabiner I remapped `J+K` to `SHIFT_R`, and `D+F` to `SHIFT_L` (that is: index+middle finger = Shift) using the following configuration. 

```
    <item>
      <name>Shift as a key chord</name>
      <appendix>Multiple keys acting as the Shift key</appendix>
      <appendix>(J+K to SHIFT_R)</appendix>
      <appendix>(D+F to SHIFT_L)</appendix>
      <identifier>remap.gould_shift</identifier>
      <autogen>__SimultaneousKeyPresses__ KeyCode::J, KeyCode::K, KeyCode::SHIFT_L</autogen>
      <autogen>__SimultaneousKeyPresses__ KeyCode::D, KeyCode::F, KeyCode::SHIFT_L</autogen>
    </item>
```

I do the same for the other modifiers, and this helps me to move my hands as little as possible away from the home row.

I wasn't able to reproduce anything similar with Karabiner Elements. Is there any change to get the same result?

Actually, the inability to have key chords is the single reason why I'm neither updating El Capitan or buying a new Mac Book.
I'm sincerely willing to pay to get such a feature.

**Comment by ww7** [comment]
+1 for SimultaneousKeyPresses and chording (sequences)

**Comment by xcode-manolo** [comment]
Hi @arialdomartini, What a great idea, simultaneous key presses for the modifiers keys, for keeping your fingers next to the home row.  Would you mind to share with us the keys combination for the rest of the modifiers ?

Did you solve your issue ?
I didn't understood the answer from ww7.  I'm sorry, I'm a newbie to keyboard programming.
But I'm pretty interested in doing the same thing.  "Simultaneous key presses "

Have a great day, guys !

**Comment by gsjackson** [comment]
I would also value a 'simultaneous key press' feature being added to K-elements.  I use it not only for modifier or 'layer invocation' keys, but for substituting functions.   Example: press A+S together (not A first then S, but actually pressed simultaneously) produces TAB key.

**Comment by fredcallaway** [comment]
Bump. Has anyone found another solution? I'm also stuck on OSX 10.11 because of this.

**Comment by arialdomartini** [comment]
I personally ended up buying a keyboard supporting the QMK Firmware, which allows to map a key as a modifier key when held, and as an ordinary key when tapped.

**Comment by anoopemacs** [comment]
Bump. Has anyone found another solution?

**Comment by fredcallaway** [comment]
@anoopemacs Here's an excerpt from my ~/.karabiner.json that makes `k+l` act as Backspace.

```

"rules": [
    {
        "description": "Backspace and Delete",
        "manipulators": [
            {
                "from": {
                    "modifiers": {
                        "optional": [
                            "any"
                        ]
                    },
                    "simultaneous": [
                        {
                            "key_code": "k"
                        },
                        {
                            "key_code": "l"
                        }
                    ]
                },
                "to": [
                    {
                        "key_code": "delete_or_backspace"
                    }
                ],
                "type": "basic"
            },
```
