### ISSUE TITLE
Prevents shortcut of VoiceOver in macOS 13.1Beta and above

### ISSUE THREAD

**Issue by ushiushix** [tekezo/Karabiner-Elements#1058]
Beginning in macOS 13.1Beta, the shortcuts of VoiceOver, built-in screen reader of macOS, is blocked with Karabiner-Elements running.

Reproduction:
1. Enable VoiceOVer by control+option+F5
2. Load Karabiner-Elements.
3. Press control+option+m to set VoiceOver cursor to the menu bar.
 You will hear a sound to indicate invalid keypress.
4. Unload Karabiner-Elements
5. Press control+option+m again.
  You will see VoiceOver cursor set to menu bar as expected.

Now VoiceOver users are not able to focus to menu bar because they are not using pointing device. It means almost unusable Mac.
Hope urgent investigation.

**Comment by garryturk** [comment]
Just to confirm that this is indeed a bit of a showstopper for VoiceOver users like myself who also use Karabiner fulltime. In my case its to control mappings for various OSs running in VMs and indeed, after the upgrade to 10.13.1 VoiceOver is unusable while Karabiner is running.

Happy to provide more info.

**Comment by ushiushix** [comment]
Now my iMac is updated from 10.13.0 to 10.13.1 with Karabiner-Elements loaded.
But VoiceOver key and key mappings of Karabiner-Elements are both working on this machine.

Another machine, which is previously reported to be having problem with 10.13.1 Beta, is now updated to 10.13.2 Beta. On this machine VoiceOver key is not working yet.
I uninstalled and reinstalled Karabiner-Elements 11.1.0 on this machine, and copied .config/karabiner from another machine but with no luck.

So in my site there are two possibilities: there is a problem only with Beta version of High Sierra, or the there is some difference between two machines.

@garryturk Are you running the released version of 10.13.1?

**Comment by garryturk** [comment]
Machine is a MBP that I’ve only used GA releases on,  never betas. 

It was running fine on 10.13 then upgraded to 10.13.1 when issues started.

**Comment by ushiushix** [comment]
Thanks.

So it seems that released version or beta is irrelevant to this issue.
My iMac (Mid 2010) is currently a special case.

The machine I'm facing this issue is a MBA 2013. Connecting external keyboard which I'm using with iMac was not helped.

**Comment by ushiushix** [comment]
Another difference between my MBA which reproduces the problem and iMac which does not is: FileVault2 is enabled for MBA. When FileVault2 is enabled, login screen is skipped because authentication is finished in the beginning of boot process.

I don't think it makes difference of keyboard event processing though...

**Comment by tamaracha** [comment]
I can reproduce this issue on my Mac Mini (late 2012) with Apple wireless keyboard, and Macbook Air (11, early 2014), both running 10.13.1, never betas. None of them has filevault enabled. Voiceover key doesn't work with karabiner elements running. I tried un- and reinstalling karabiner elements. A fresh user or guest user makes no difference.

In this release, Apple fixed an issue related to keyboard input in spotlight. Maybe this is the source of the effect.

**Comment by tamaracha** [comment]
Thank you, 11.2.0 fixed it for me.. I can use karabiner elements with voiceover again and it works fine.

**Comment by ushiushix** [comment]
I've confirmed that 11.2.0 works fine with VoiceOver like before in macOS 10.13.2 Beta2.

Thank you.
