### ISSUE TITLE
Karabiner VirtualHIDKeyboard not outputting visible data. 

### ISSUE THREAD

**Issue by zachmoss1** [tekezo/Karabiner-Elements#1060]
Karabiner Elements 11.1.0, MacOS 10.12.6

I use other applications that access HID keyboard events (Keyboard Maestro, Controllermate, MAX/MSP). All of these can see Karabiner VirtualHIDKeyboard and Karabiner VirtualHIDPointing, but for the Karabiner VirtualHIDKeyboard no events seem to be visible to these applications. 

I have a keyboard key mapped to mousedown left and that _is_ sent correctly to the aforementioned apps via the Karabiner VirtualHIDPointing device, so this certainly seems possible.

This is very important functionality because it affects my ability to automate using these other apps. 

I might be misinterpreting the purpose of the Karabiner VirtualHIDKeyboard, and don't know if my desired functionality works on previous versions (does anyone know whether it did?), but if not, please consider this a feature request. 

Thanks!

**Comment by pfgithub** [comment]
This is also an issue I have. While karabiner elements is running, the only hid device that outputs data is my trackpad. Without it running, the keyboard also outputs data.

**Comment by zachmoss1** [comment]
In response to the "stale" message, bump since this is still an issue and I would hope that it still be addressed in one way or the other. I think this is important because many users of Karabiner (including myself) are often the type who would also want to access HID events. Thanks

**Comment by zachmoss1** [comment]
Well, it looks like the new 12.0.0 release addresses this problem for my MacOS 10.12.6! I have tested with MAX/MSP and Controllermate, and both seem to work great! Thanks @tekezo 👍 .
