### ISSUE TITLE
Ctrl+Tab and Ctrl+Shift+Tab to switch between open applications

### ISSUE THREAD

**Issue by lvhuyen** [tekezo/Karabiner-Elements#1063]
Hi,

First about the original apps switcher, with Cmd+Tab and Cmd+Shift+Tab. When I hold Cmd, then press Tab, a small app switcher bar will appear in the middle of the screen, with list of open apps, and the 2nd app is highlighted. No if I release Cmd, the app switcher bar will disappear, and that 2nd app will be brought to front. If I keep Cmd held down, and press Tab, then 3rd app will be highlighted,... and if I press Shift+Tab (while Cmd is still being held down), then the highlighter will be brought to the previous app in the list. So I can go get the highlighter from 2nd app, to 3rd, to 4th and back to 3rd one.

Now to my requirement - I want to use Control instead of Command for that app switcher.
I found this example https://pqrs.org/osx/karabiner/complex_modifications/#exchange_command_tab_and_control_tab
It works, but doesn't work well.
While I keep Ctrl down, the app switcher bar is visible, and I additionally press Shift, then the app switcher bar will disappear. This means that if I want to switch to 3rd app, but mistakenly bring the highlighter to the 4th one, then there's no way for me to go one step back.

Anyone has solution for this?

Thanks for your time.

**Comment by be9em0t** [comment]
Is this what you need?


{
    "description": "Sticky Alt-Tab to Cmd-Tab",
    "manipulators": [
        {
            "type": "basic",
            "from": {
                "key_code": "tab",
                "modifiers": {
                    "optional": [
                        "any"
                    ]
                }
            },
            "to": [
                {
                    "key_code": "tab"
                }
            ],
            "conditions": [
                {
                    "type": "variable_if",
                    "name": "left_alt pressed",
                    "value": 1
                }
            ]
        }
    ]
},
{
    "description": "Sticky Alt to Cmd Variable",
    "manipulators": [
        {
            "type": "basic",
            "from": {
                "key_code": "left_alt",
                "modifiers": {
                    "optional": [
                        "any"
                    ]
                }
            },
            "to": [
                {
                    "set_variable": {
                        "name": "left_alt pressed",
                        "value": 1
                    }
                },
                {
                    "key_code": "left_command"
                }
            ],
            "to_delayed_action": {
                "to_if_invoked": [
                    {
                        "set_variable": {
                            "name": "left_alt pressed",
                            "value": 0
                        }
                    }
                ],
                "to_if_canceled": [
                    {
                        "set_variable": {
                            "name": "left_alt pressed",
                            "value": 0
                        }
                    }
                ]
            }
        }    
    ]
}

**Comment by maxming2333** [comment]
yes, it's work for me
thanks @be9em0t

**Comment by maxming2333** [comment]
@be9em0t Your method will invalidate my `Alt` button
I used this configuration, it's work for me

```json
{
  "description": "Change Option+Tab to Command+Tab",
  "manipulators": [
    {
      "from": {
        "key_code": "tab",
        "modifiers": {
          "mandatory": [
            "option"
          ],
          "optional": [
            "any"
          ]
        }
      },
      "to": [
        {
          "key_code": "tab",
          "modifiers": [
            "command"
          ]
        }
      ],
      "type": "basic"
    }
  ]
}
```

I tried to move the mouse and found that the button was not released.
It should be officially fixed this problem.

end.

**Comment by 99p** [comment]
This is RightControl-Tab to Command-Tab, but works for me.
enjoy!

    {
      "description": "RControl-Shift-Tab :: Command-Shift-Tab",
      "comment": "Switch between App Backward",
      "manipulators": [
        {
          "type": "basic",
          "from":
          {
            "key_code": "tab",
            "modifiers": { "optional": [ "any" ] }
          },
          "to":
          [
            {
              "key_code": "tab",
              "modifiers": [ "command", "shift" ]
            }
          ],
          "conditions": [
            {
              "type": "variable_if",
              "name": "flag_appswitching",
              "value": 1
            }
          ]
        }
      ]
    },
    {
      "description": "RControl-Tab :: Command-Tab",
      "comment": "Switch between App",
      "manipulators": [
        {
          "type": "basic",
          "from":
          {
            "key_code": "tab"
          },
          "to":
          [
            {
              "key_code": "tab",
              "modifiers": [ "command" ]
            }
          ],
          "conditions": [
            {
              "type": "variable_if",
              "name": "flag_rcontrol",
              "value": 1
            }
          ]
        }
      ]
    },
    {
      "description": "FLAG :: rcontrol",
      "comment": "for Switch between App",
      "manipulators": [
        {
          "type": "basic",
          "from":
          {
            "key_code": "right_control"
          },
          "to":
          [
            { "set_variable":
              {
                "name": "flag_rcontrol",
                "value": 1
              }
            }
          ],
          "to_after_key_up":
          [
            {
            "set_variable":
              {
                "name": "flag_rcontrol",
                "value": 0
              }
            }
          ]
        }
      ]
    },
    {
      "description": "FLAG :: appswitching",
      "comment": "for Switch between App Backward",
      "manipulators": [
        {
          "type": "basic",
          "from":
          {
            "key_code": "left_shift"
          },
          "to":
          [
            { "set_variable":
              {
                "name": "flag_appswitching",
                "value": 1
              }
            }
          ],
          "to_after_key_up":
          [
            {
            "set_variable":
              {
                "name": "flag_appswitching",
                "value": 0
              }
            }
          ],
          "conditions": [
            {
              "type": "variable_if",
              "name": "flag_rcontrol",
              "value": 1
            }
          ]
        }
      ]
    }
