### ISSUE TITLE
Add `§` character to `non_us_backslash` description in keys

### ISSUE THREAD

**Issue by stefanocrosta** [tekezo/Karabiner-Elements#1065]
This would reduce the chance of people adding duplicates of issue: #7 or issue: #30 . Anything that prevents it? Most of the other keys have both a textual description AND the symbol. Also this one is often called `section` which makes it even more difficult to find otherwise...
Otherwise, thanks! I use Karabiner for this only key swapping but it avoids me losing my mind :-)

**Comment by fedde-s** [comment]
This continues to cause confusion, in issues such as #1322.

**Comment by bentayloruk** [comment]
I just got confused by this exact thing, while trying to map the section character on a Microsoft Sculpt UK layout keyboard.  Happy I found the solution here, but thought I would confirm confusion still occurs.

I'm new to Karabiner, but it's already a great help.  Thank you!

**Comment by woahitsraj** [comment]
I was able to figure this out using Karibabiner Event Viewer but I agree, this could be more clear

**Comment by amsoell** [comment]
One more note that this one took me some time to find. American living in Europe, and my international keyboard has the "section" key where I'm used to finding the backtick key. Glad Karabiner supports changing this, but took me some time to find.

**Comment by fedde-s** [comment]
@tekezo, this issue isn't stale.
