### ISSUE TITLE
Auto close pref window after launch on startup

### ISSUE THREAD

**Issue by Steveseg** [tekezo/Karabiner-Elements#1068]
Hello,
I have K-E 11.1 autostarting, in High Sierra 10.13, on my Mac Pro 3,1 (Early 2008). I'd like for the preferences window not to open automatically and for K-E not to remain in the dock after launch. How can I accomplish this.?

Thanks,
Steve

**Comment by tekezo** [comment]
Unlike Karabiner, you don't need to add Karabiner-Elements to Login Items.
(Karabiner-Elements runs automatically after login if it is running at logout.)

Remove Karabiner-Elements from Login Items.
https://support.apple.com/kb/PH25590?locale=en_US
