### ISSUE TITLE
Log continuously reporting errors and misreading keyboard

### ISSUE THREAD

**Issue by droptablestar** [tekezo/Karabiner-Elements#1069]
macOS version: macOS 10.12.6
Karabiner version: Karabiner-Elements 11.1.0
Your Mac hardware: MacBook Air
Your keyboard hardware: Tecware Phantom Backlit Mechanical Keyboard (Red backlight, Brown switch).

When plugging this device in the Target Device list shows: 
No Product name (No manufacturer name)
No Product name (No manufacturer name)
Wireless Device (Chicony)
Apple Internal Keyboard...
Keyboard (Apple)

Remapping keys to any one of this (or all but the Apple Internal Keyboard) doesn't change any of the keybindings on the keyboard. Additionally, the log is continuously reporting the following error:

`[2017-10-26 20:49:51.911] [error] [grabber] IOHIDDeviceOpen error: kIOReturnExclusiveAccess (-536870203) (vendor_id:0x4b4, product_id:0x3003) (device_id:21)`

**Comment by tekezo** [comment]
Thank you for feedback.
I've fixed this issue at v11.1.15. Please confirm the latest beta version.
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by droptablestar** [comment]
I am able to bind the keys to the specific keyboard but there are still the multiple versions listed in the drop down menu and the log is still producing constant errors.

**Comment by tekezo** [comment]
Thank you for confirmation!

The multiple listing devices and one time error log is caused by hardware and device driver.
Unfortunetely, Karabiner-Elements does not have workarounds for these problems.
Please ignore them if there are not other serious problems.
