### ISSUE TITLE
external keyboard problems: "your keyboard cannot be identified" and function/media key problems

### ISSUE THREAD

**Issue by yo3yo3yo3yo3** [tekezo/Karabiner-Elements#107]
Had to uninstall Karabiner-Elements on 10.12 Sierra on my 13-inch rMBP due to lots of problems with the media keys on my external keyboard (Kinesis Freestyle 2 for Mac). Was getting an error in System Preferences>Keyboard>Change Keyboard Type that said my keyboard could not be identified and to stop pressing keys on the MacBook keyboard and to press them on the external keyboard (which is what I had been doing, of course). My external keyboard basically was not being recognized. So my problem was that the media keys on my external keyboards were actually pressing whatever equivalent F-key on my MacBook, thus signaling the wrong F-key. 
<img width="728" alt="screen shot 2016-09-22 at 2 29 40 pm" src="https://cloud.githubusercontent.com/assets/22380423/18765566/860af394-80d3-11e6-818d-c96da5345f5b.png">
<img width="728" alt="screen shot 2016-09-22 at 2 25 02 pm" src="https://cloud.githubusercontent.com/assets/22380423/18765565/86094fa8-80d3-11e6-8fd9-e4da6e6103ae.png">

**Comment by mkborregaard** [comment]
I also have this

**Comment by yo3yo3yo3yo3** [comment]
Alternative to Karabiner-Elements that has been working for me in Sierra: https://m.reddit.com/r/mac/comments/54355w/how_to_remap_keys_in_macos_sierra_1012/?utm_source=mweb_redirect&compact=true
