### ISSUE TITLE
Next word + selection does not work with remapped keys

### ISSUE THREAD

**Issue by jberkel** [tekezo/Karabiner-Elements#1070]
I bought an external keyboard and switched left option and left command:
![schermata 2017-10-27 alle 21 35 20](https://user-images.githubusercontent.com/18891/32121904-cad74150-bb5e-11e7-8a59-06bda4f4561f.png)

This works fine, but jumping between word boundaries (via ⌥+Arrow) while selecting at the same time (by holding ⇧) does not work in all cases. It works for leftwards movements, but not for rightwards movement (⇧⌥→). The cursor does not move at all. Without the mapping everything works fine on the external keyboard.

This is with Karabiner-Elements 11.1.11.

Update: I checked the lowlevel keyboard events and it looks like the hardware does not generate the correct keycodes for this combination of keys, which does seem to be strange. Anyway, closing.

**Comment by PWKad** [comment]
In case anyone else runs in to this every time I set up a new keyboard I have to disable the gaming function or something to get this working again.
