### ISSUE TITLE
Mouse button to scroll

### ISSUE THREAD

**Issue by nathanhornby** [tekezo/Karabiner-Elements#1074]
This was one of the main things I used Karabiner for, but I don't seem to be able to find how to do it with elements, if you even can? I wish I'd never 'upgraded' my OS tbh.

Is there any way to map a mouse button to activate scroll in Elements?

**Comment by v-yarotsky** [comment]
In latest Karabiner-Elements (11.2.0) you can map mouse buttons. I've just mapped `button4` to `page_down` and `button5` to `page_up`.

**Comment by rvesse** [comment]
My own mouse software can do that, what I really want to do is be able to hold a button and then have mouse movement translated into scrolling.  In Karabiner this was `__PointingRelativeToScroll__` but I'm not sure that is supported yet?

**Comment by nathanhornby** [comment]
@rvesse That's exactly what I'm after, push button + move mouse = scroll. Sorry I wasn't clear guys.

**Comment by furey** [comment]
@v-yarotsky Not a bad hack – cheers!

I too would love the return of Karabiner's "button4/button5 + MouseDragged" to scroll.

Fingers crossed! 🤞

**Comment by rvesse** [comment]
Still hoping this feature comes back to Karabiner Elements

**Comment by tekezo** [comment]
![Simple Modifications](https://pqrs.org/osx/karabiner/img/news/v11.6.0_0.png)

Follow this procedure.
https://pqrs.org/osx/karabiner/help.html#mouse-button

**Comment by nathanhornby** [comment]
As mentioned what's being looked for here, and what's missed, is the ability to *activate mouse scroll* via a button. Not 'scroll with a button'.

**Comment by rvesse** [comment]
Exactly, we are after the old `__PointingRelativeToScroll__` behaviour from Karabiner, we want to be able to hold down a button and have our mouse movements translated into scrolling.

Translating a button press to Scroll Up/Scroll Down is a poor substitute because it gives coarse grained movement as opposed to the old functionality that gave very fine grained movement.

**Comment by mansoff** [comment]
We need this feature. 
We wana "click + mouse drag" = mouse scroll

**Comment by newduke** [comment]
I'm using USB Overdrive to solve this in the meantime.

**Comment by psychomugs** [comment]
Hammerspoon works for this:
https://github.com/tekezo/Karabiner/issues/814

To enable natural scroll direction, negate the mouse movement:
`local scroll = hs.eventtap.event.newScrollEvent({dx * scrollmult, dy * scrollmult},{},'pixel')` to `local scroll = hs.eventtap.event.newScrollEvent({-dx * scrollmult, -dy * scrollmult},{},'pixel')`

**Comment by fogg4444** [comment]
I still want this feature!!

**Comment by tekezo** [comment]
The latest beta starts to supporting it.
https://pqrs.org/osx/karabiner/complex_modifications/#mouse_motion_to_scroll

How to upgrade to the latest beta version:
<https://pqrs.org/osx/karabiner/document.html#check-for-updates>


TODO:
- [ ] Momentum Scroll
- [ ] Scroll speed configuration
- [ ] Ignore small horizontal motion when vertical scrolling.

**Comment by rvesse** [comment]
@tekezo Thanks for getting to this, it's still the feature I miss most from the old Karabiner

I have tried out the Beta and couldn't get it to work currently although I may be hitting the TODOs you mention.  I have verified in the Event Viewer that Karabiner Elements is registering the MouseDown on the relevant button and registering the MouseDragged events:

![Screenshot 2019-04-04 at 09 58 25](https://user-images.githubusercontent.com/2104864/55543076-40a86c80-56c0-11e9-91e7-c53aa6969ae8.png)

I use a Trackball (Logitech Trackman Marble) so there is likely inevitably some degree of horizontal scroll due to the nature of the physical device which may be why it doesn't work for me.

**Comment by leadpipe** [comment]
Exactly the same situation as @rvesse, a Logitech Trackman Marble.  Had to revert to a regular mouse :-(

**Comment by tekezo** [comment]
Please choose device in order to use mouse_motion_to_scroll.
https://pqrs.org/osx/karabiner/document.html#configuration-devices

**Comment by rvesse** [comment]
@leadpipe One workaround I’ve been using for a while is to install the Logitech app which then allows you to customise the button functions one of which is called Cruise and allows you to configure a button to scroll up/down. It is unfortunately very coarse grained scrolling but is better than nothing

**Comment by furey** [comment]
Thanks @tekezo for continuing to work on this issue!

Just upgraded to the [latest beta](https://github.com/tekezo/Karabiner-Elements/issues/1074#issuecomment-476035020) and can happily confirm trackball scrolling via button 4/5 works.

> very coarse grained scrolling but is better than nothing

The scrolling is a bit janky, so eagerly anticipating future updates RE: @tekezo's unfinished TODOs:

> - [ ] Scroll speed configuration
> - [ ] Tuning

Cheers!

**Comment by rvesse** [comment]
@tekezo Just to confirm yes my device is enabled under Preferences:

![Screenshot 2019-04-15 at 09 35 03](https://user-images.githubusercontent.com/2104864/56118259-cc908300-5f61-11e9-9e53-9fd415a28500.png)

Updated to latest Beta (12.2.11) and still not working for me

**Comment by leadpipe** [comment]
And FYI it's still not working for me even after I enabled the device.

**Comment by tekezo** [comment]
Please confirm "Change mouse motion to scroll" is not conflicted in complex modifications.
(Please confirm button4 or button5 is not changed before this setting.)


<img width="1000" alt="Screen Shot 2019-04-16 at 0 52 58" src="https://user-images.githubusercontent.com/659178/56146888-1456ef00-5fe2-11e9-8837-0c7630d0b1ad.png">

**Comment by leadpipe** [comment]
It's the only complex modification.

Here's the event log:

eventType:MouseDown       code:0x3        name:button4         misc:{x:749,y:139} click_count:1 
eventType:MouseDragged    code:0x3        name:button4         misc:{x:749,y:138} click_count:1 
eventType:MouseDragged    code:0x3        name:button4         misc:{x:749,y:137} click_count:1 
eventType:MouseDragged    code:0x3        name:button4         misc:{x:749,y:136} click_count:1 
eventType:MouseDragged    code:0x3        name:button4         misc:{x:749,y:136} click_count:1 
eventType:MouseDragged    code:0x3        name:button4         misc:{x:749,y:136} click_count:1 
eventType:MouseDragged    code:0x3        name:button4         misc:{x:749,y:135} click_count:1 
eventType:MouseDragged    code:0x3        name:button4         misc:{x:750,y:135} click_count:1 
eventType:MouseDragged    code:0x3        name:button4         misc:{x:750,y:135} click_count:1 
eventType:MouseDragged    code:0x3        name:button4         misc:{x:750,y:134} click_count:1 
eventType:MouseDragged    code:0x3        name:button4         misc:{x:750,y:134} click_count:1 
eventType:MouseDragged    code:0x3        name:button4         misc:{x:750,y:134} click_count:1 
eventType:MouseDragged    code:0x3        name:button4         misc:{x:750,y:133} click_count:1 
eventType:MouseDragged    code:0x3        name:button4         misc:{x:750,y:133} click_count:1 
eventType:MouseDragged    code:0x3        name:button4         misc:{x:750,y:132} click_count:1 
eventType:MouseDragged    code:0x3        name:button4         misc:{x:750,y:131} click_count:1 
eventType:MouseDragged    code:0x3        name:button4         misc:{x:750,y:131} click_count:1 
eventType:MouseDragged    code:0x3        name:button4         misc:{x:750,y:131} click_count:1 
eventType:MouseDragged    code:0x3        name:button4         misc:{x:751,y:130} click_count:1 
eventType:MouseDragged    code:0x3        name:button4         misc:{x:751,y:130} click_count:1 
eventType:MouseDragged    code:0x3        name:button4         misc:{x:751,y:129} click_count:1 
eventType:MouseDragged    code:0x3        name:button4         misc:{x:751,y:129} click_count:1 
eventType:MouseDragged    code:0x3        name:button4         misc:{x:751,y:130} click_count:1 
eventType:MouseDragged    code:0x3        name:button4         misc:{x:751,y:131} click_count:1 
eventType:MouseDragged    code:0x3        name:button4         misc:{x:752,y:131} click_count:1 
eventType:MouseDragged    code:0x3        name:button4         misc:{x:752,y:131} click_count:1 
eventType:MouseDragged    code:0x3        name:button4         misc:{x:752,y:132} click_count:1 
eventType:MouseUp         code:0x3        name:button4         misc:{x:752,y:133} click_count:0

**Comment by tekezo** [comment]
@leadpipe If you are using third vendor driver, it might be conflicted.
Please confirm log messages in `Karabiner-Elements Preferences > Log tab`.

**Comment by leadpipe** [comment]
Aha, that was it.  I was using the Logitech driver.  Removing that makes the mapping work.  I now see "ScrollWheel" in the event log.  Thank you!

On to the next problem :-)  I want to map button 1 to button 4 and use that as the scroll wheel, because I'm left-handed.  It won't let me choose button 1 in the left ("From key") column of the simple modifications tab, and I don't see a complex modification that does this.

**Comment by rvesse** [comment]
@tekezo @leadpipe Thanks for the driver tip, this does now make the buttons cause scroll

One oddity I've noticed is that button 4 scrolls up while button 5 scrolls down even without actually moving the mouse (moving the mouse increases the scroll speed) but each button only scrolls one direction.  Not sure if that is intentional or not?

![Screenshot 2019-04-17 at 10 01 51](https://user-images.githubusercontent.com/2104864/56275065-e532a180-60f7-11e9-871a-ab25868e2a80.png)

In the above you can see that one button creates a small scroll up and the other a small scroll down.

Ideally I'd like to press one button and have it scroll in the direction of the mouse motion

**Comment by tekezo** [comment]
@leadpipe GUI does not provide button1 modification but you can change button1 by modify karabiner.json directly.

1. Add two simple modifications
  - `button2 -> button1`
  - `button32 -> button4`
2. Open TextEdit.
3. Press Command-O on TextEdit. File choose dialog will be opened.
4. Type `~/.config/karabiner` on the file choose dialog.
5. Open karabiner.json.
6. Search `button32` and replace with `button1`.

**Comment by tekezo** [comment]
@rvesse You enabled other setting that changes button4 and button5.
Please confirm the simple modifications for each devices. 
https://pqrs.org/osx/karabiner/img/karabiner-elements-simple-modifications-1@2x.png

**Comment by rvesse** [comment]
@tekezo Yes you are correct, my mistake. Thanks for all the help. Now got it working, looking forward to further improvements in this feature in the future

**Comment by leadpipe** [comment]
Thanks @tekezo, it's back to fully functional again!

**Comment by tekezo** [comment]
I finished tuning at v12.2.18!

**Comment by leadpipe** [comment]
And with the new version, it's back to working really nicely again.  Thank you, @tekezo.

**Comment by rvesse** [comment]
@tekezo Yes latest Beta is much smoother.  Thanks again for the awesome work!

**Comment by puttin** [comment]
I'm so glad KE have such a feature. 

So If I need the `mouse_motion_to_scroll ` to work properly, I have to uninstall `Logitech Control Center` or anything similar?

It didn't work for me with either button4/5/control. I'm using Logitech M570. I have enabled all mouse devices and no conflict logs seems to appear in KE log tab.

**Comment by puttin** [comment]
> I'm so glad KE have such a feature.
> 
> So If I need the `mouse_motion_to_scroll ` to work properly, I have to uninstall `Logitech Control Center` or anything similar?
> 
> It didn't work for me with either button4/5/control. I'm using Logitech M570. I have enabled all mouse devices and no conflict logs seems to appear in KE log tab.
> 
> And even after I removed Logitech Control Center panel from System Preferences, it still not works.
> 
> But I find it working with my SteelSeries Rival 300. Any idea? @tekezo

I figured it out. Delete the panel from System Preferences does not delete the driver.

Use LCC Uninstaller instead which should be in /Applications/Utilities folder

**Comment by hgijeon** [comment]
I found this karabiner configuration works well with [Mos](https://github.com/tekezo/Karabiner-Elements/issues/1074), which makes scroll smoother. I think the acceleration speed conflicts, but anyway it becomes much more natural.

**Comment by wadimw** [comment]
Is there any option to fine tune simulated scrolling for my taste? I'd like to disable acceleration at least

**Comment by sypl** [comment]
I don't suppose it's possible to set two mouse buttons to `pointing_button`? My mouse has only two buttons, it'd be cool if pressing down both at same time acted as scroll trigger.

**Comment by mathemaudio** [comment]
It doesn't work again. I set up my new M2 machine with Sonoma and the script has no effect. On my previous machine, when I click the middle button, which is button 3, it converted my mouse motion into scrolling motion. Now it doesn't work anymore. Anything new, anything updated, maybe I need to add some permission somewhere or it's just never going to work again. Because that was the main reason why I used Karabiner in the first place.

`{
    "description": "Change button3 + mouse motion to scroll ",
    "manipulators": [
        {
            "from": {
                "modifiers": { "optional": ["any"] },
                "pointing_button": "button3"
            },
            "to": [
                {
                    "set_variable": {
                        "name": "enable_mouse_motion_to_scroll",
                        "value": 1
                    }
                }
            ],
            "to_after_key_up": [
                {
                    "set_variable": {
                        "name": "enable_mouse_motion_to_scroll",
                        "value": 0
                    }
                }
            ],
            "type": "basic"
        },
        {
            "conditions": [
                {
                    "name": "enable_mouse_motion_to_scroll",
                    "type": "variable_if",
                    "value": 1
                }
            ],
            "from": { "modifiers": { "optional": ["any"] } },
            "type": "mouse_motion_to_scroll"
        }
    ]
}`

**Comment by tekezo** [comment]
Is the mouse enabled in the Devices tab?
https://karabiner-elements.pqrs.org/docs/manual/configuration/configure-devices/

**Comment by mathemaudio** [comment]
No, it wasn't. And it really helped! Thank you very much.

**Comment by BlaneWins** [comment]
Is there anyway to use this while set to mouse wheel and still have mouse wheel open links in new windows and close windows?
