### ISSUE TITLE
how to remap grave accent button to left command + space

### ISSUE THREAD

**Issue by karabinr** [tekezo/Karabiner-Elements#1075]
In Windows, you can use a single key (grave accent key) to change input languages. On the Mac you have to use two keys (left command + space).

How can I use Karabina Elements to remap grave accent to left command+space on the Mac?

The grave accent ( ` ) / tilde ( ˜ ) key is at the top left of the keyboard.

**Comment by nguyenhimself** [comment]
```
                        "description": "Grave tilde to Command Space",
                        "manipulators": [
                            {
                                "from": {
                                    "key_code": "grave_accent_and_tilde",
                                    "modifiers": {
                                        "optional": [
                                            "caps_lock"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "spacebar",
                                        "modifiers": [
                                            "left_command"
                                        ]
                                    }
                                ],
                                "type": "basic"
                            },
```

**Comment by karabinr** [comment]
thanks for that, nguyenhimself. now how do i add that to the complex modifications in karabiner elements? when i click "add rule", the only option is "import more rules from the internet (open a web browser). there's no option to import a rule from a local file.

**Comment by nguyenhimself** [comment]
The karabiner.json file should be in ~/.config/karabiner/

You should be able to figure out how to add new rules to the above file. It should be rather straightforward.

**Comment by karabinr** [comment]
so do i just add the code above to the karabiner.json file and it will appear in KE complex modifications?

**Comment by karabinr** [comment]
i've got it working now. thanks
