### ISSUE TITLE
I can't find the documentation of complex modification

### ISSUE THREAD

**Issue by Fig-R** [tekezo/Karabiner-Elements#1078]
Hi, I'm looking for documentation to create a complex modification rule but I haven't found it.
Use only examples files is super limited...

[This](https://pqrs.org/osx/karabiner/document.html) isn't documentation.
There is documentation with all keys, options, etc?

Thanks!

**Comment by nguyenhimself** [comment]
There currently isn't one.
Your best bet is importing a bunch of pre-made rules and edit/add them yourself. They are quite straightforward.
All the keycodes are [here](https://github.com/tekezo/Karabiner-Elements/issues/925#issuecomment-323984568).
