### ISSUE TITLE
While using Vmware Fusion and Karabiner, the mouse only moves horizontally and vertically inside the VM

### ISSUE THREAD

**Issue by kylemart** [tekezo/Karabiner-Elements#1079]
## Issue
While using Vmware Fusion the mouse only moves horizontally and vertically while inside a VM. For example, to move diagonally I first have to move the mouse left or right, then straight up or down. I can't move in both axises simultaneously. I initially thought it might've been something wrong with Vmware Fusion itself, but after disabling Karabiner-Elements the issue disappeared; re-enabling Karabiner-Elements brought the issue back. It doesn't seem to be caused by a particular complex or simple modification, as removing all modifications doesn't resolve the issue. It would seem the only precondition is for Karabiner-Elements to be active.

## Reproducible Steps
1. Ensure Karabiner-Elements is enabled.
2. Launch a VM in Vmware Fusion. (In my case, it was a fresh copy of Windows 10.)
3. Move the mouse while inside the VM.

## Version Information
Karabiner-Elements version: 11.1.11
OSX version: 10.13 (High Sierra)
Vmware Fusion version: 10.0.1

**Comment by kylemart** [comment]
This issue is no longer reproducible on 11.3.

**Comment by jcbertin** [comment]
Problem is still here for me with Karabiner-Elements v11.4… Quite annoying. Tell me if i can help to solve this issue.

Regards
