### ISSUE TITLE
When Karabiner running Shift+Fn+Function key sends Function Key on tMBP

### ISSUE THREAD

**Issue by blackxored** [tekezo/Karabiner-Elements#1080]
When karabiner is running (empty profile), on a touchbar Macbook Pro, typing ex. shift+fn+f6 sends f6 instead of shift+f6. That's whenever Karabiner is running and with no further configuration. As soon as I quit it, the keyboard starts behaving how it should.

**Comment by caa4444** [comment]
this happens to my 2013 macbook pro, but only for my external DAS keyboard and not the built in keyboard in the laptop

**Comment by thisismana** [comment]
It even happens, when the function keys are permanently enabled. So `Shift`+`F6` does not work.

As for a workaround, try using the build-in remapping of MacOS: https://developer.apple.com/library/content/technotes/tn2450/_index.html

**Comment by tekezo** [comment]
Please use this workaround about Touch bar and function keys.
https://pqrs.org/osx/karabiner/help.html#touch-bar-function-keys

**Comment by blackxored** [comment]
This really makes using something like IntelliJ borderline impossible. I don't understand what's the limitation given when Karabiner is not running the keys are registered successfully.

**Comment by ToshB** [comment]
Agree, after getting a touchbar MBP, I can only use Karabiner Elements when I have an external keyboard connected. Shortcuts like shift+f6 not working with the touchbar is problematic.

**Comment by clayreimann** [comment]
@tekezo I've found that `Shift+F6` is broken unless i _enable_ "unknown device" but that means that I am unable to use the `fn` key to switch to the non-`F*` keys. 

Is that the expected behavior?

I'd be happy to help fix this issue if you have an idea of what's causing the problem

**Comment by xpmatteo** [comment]
This still happens and it's July.  Can you please fix it?

**Comment by rzarajczyk** [comment]
Issue still exists and is very annoying. Please reopen and fix :-) MacBook Pro 2018

**Comment by thedomdom** [comment]
How can this be closed? It' super annoying

**Comment by thedomdom** [comment]
Ok I found a solution: https://github.com/tekezo/Karabiner-Elements/issues/1160
