### ISSUE TITLE
Binding a key to grave accent+e

### ISSUE THREAD

**Issue by Rubenstein29** [tekezo/Karabiner-Elements#1087]
Hello I use a german keyboard and I would like to type the é and è by simply pushing ö and ä. I don't understand what's wrong with my code if someone can help please. When I push : 
- equal_sign it gives ´
- shift+equal_sign it gives `
- quote it gives ä
- semicolon it gives ö

```{
  "title": "Change ö and ä to é and è",
  "rules": [
    {
      "description": "Change ö to shift+´+e",
      "manipulators": [
        {
          "from": {
            "key_code": "semicolon"
          },
          "to": [
            {
              "key_code": "equal_sign",
              "modifiers": [
                "shift"
		"e"
              ]
            }
          ],
          "type": "basic"
        }
      ]
    },
    {
      "description": "Change ä to ´+e",
      "manipulators": [
        {
          "from": {
            "key_code": "quote"
          },
          "to": [
            {
              "key_code": "equal_sign",
              "modifiers": [
                "e"
              ]
            }
          ],
          "type": "basic"
        }
      ]
    }
  ]
}
```

**Comment by xcode-manolo** [comment]
Hi, @Rubenstein29 !!!

I'm not sure when you tell what character you get when you push keys if these values are the characters printed over the keycap or they are what appear on Karabiner EventViewer.

You must use Karabiner EventViewer for checking the name of the "keystrokes" on your keyboard.
 
Then, if the key that you push for getting ´ on screen appears in EventViewer with the name: equal sign, you must refer to Karabiner-Elements as equal_sign for getting ´.

In the same way, if the combination of keys that you push for getting ` on screen appears in EventViewer with the names of left_shift (or right_shift) and equal_sign, you must refer to Karabiner-Elements as equal_sign with the modifier left_shift,  and so on. 

If you used Karabiner EventViewer for referring to those keystrokes, then the solution for getting è when you push ö is the following json file.  If not, you only have to change the values of the key_codes in the code for those that you'll get from Karabiner EventViewer.  And you can guess the solution for getting é from ä.

[ö to è.json.txt](https://github.com/tekezo/Karabiner-Elements/files/1463485/o.to.e.json.txt)

Good luck @Rubenstein29 !!!

**Comment by Rubenstein29** [comment]
Hi @xcode-manolo thanks a lot I modified my code and it works, the problem was that I was considering e as a modifier key so I just changed the "to" part. Also to put the into the post like this just put 4 times grave accent ` before your code. Here is the code that worked for me :
````{
"title": "Change ö and ä to é and è",
  "rules": [
    {
      "description": "Change ö to shift+´+e",
      "manipulators": [
        {
          "from": {
            "key_code": "semicolon"
          },
          "to": [
            {
              "key_code": "equal_sign",
              "modifiers": [
                "shift"
              ]
            },
            {
              "key_code": "e"
            }
          ],
          "type": "basic"
        }
      ]
    },
    {
      "description": "Change ä to ´+e",
      "manipulators": [
        {
          "from": {
            "key_code": "quote"
          },
          "to": [
            {
              "key_code": "equal_sign"
            },
            {
              "key_code": "e"
            }
          ],
          "type": "basic"
        }
      ]
    }
  ]
}

**Comment by xcode-manolo** [comment]
Glad !  😉

It was just 4 times grave accent !!!  Thanks !!!

**Comment by diff111** [comment]
Hello everybody, Sorry for bothering you. I have a similar problem, namely I want to bind "command+e" to "ê". The problem is that I don't know how to input the keycode or the combination of keycodes to produce the "ê". Moreover, I tested the configuration above and it gives me "+e" instead of "è" as claimed. I'm using an American QWERTY keyboard. Can somebody help me, please? Thanks in advance.

**Comment by quique-z** [comment]
A while late but I got this to work for me:

Using option + ` for a grave accent, then on key up the actual letter. Use option + e for acute, u for umlaut, etc. Repeat for all the vowels you might need.

```json
  {
  "from": {
      "key_code": "e",
      "modifiers": {
          "mandatory": [
              "right_command",
              "shift"
          ]
      }
  },
  "to": [
      {
          "key_code": "`",
          "modifiers": [
              "option"
          ]
      }
  ],
  "to_after_key_up": [
      {
          "key_code": "e"
      }
  ],
  "type": "basic"
 }
```
