### ISSUE TITLE
"Shake mouse pointer to locate" not working

### ISSUE THREAD

**Issue by adriaanzon** [tekezo/Karabiner-Elements#1088]
Using the latest stable version (11.1.0) and the latest beta version (11.1.17) of Karabiner-Elements, the mouse pointer doesn't grow bigger when shaking it.

**Comment by tekezo** [comment]
Thank you for feedback!
I've fixed this issue at v11.1.18.

**Comment by adriaanzon** [comment]
It works again now. Thanks!
