### ISSUE TITLE
purpose

### ISSUE THREAD

**Issue by geddski** [tekezo/Karabiner-Elements#109]
What is the purpose of this project and how does it relate to karabiner? Just wondering about Sierra support for karabiner and saw the page leading to this repo but the readme doesn't really describe what it's for 

also sorry for no periods or commas in this issue I have them custom mapped in karabiner lol :)

**Comment by talha131** [comment]
You should go through this discussion.

https://github.com/tekezo/Karabiner/issues/660
https://github.com/tekezo/Karabiner/issues/660#issuecomment-226942420

**Comment by seangaffney** [comment]
Please consider closing this issue if your question is answered. Thanks! :)
