### ISSUE TITLE
unexpected behavior

### ISSUE THREAD

**Issue by Fig-R** [tekezo/Karabiner-Elements#1093]
Hello, I try to use space key as fn key for use hjkl as arrow key with fn modifier and it's work well.

But if I push fn key + space (for home, end, etc...) + jkl, this work well too but h key no.
h,g,b key have same behavior.

In EventViewer, when I test fn + space + j,k,l or another key except h,g,b, I see fn, spacebar, and the letter and with h,g,b I see fn, spacebar, fn.

I haven't find explanation, can you explain this to me?
Thanks!

**Comment by vitmy0000** [comment]
I think it's the same reason as this issue. https://github.com/tekezo/Karabiner-Elements/issues/947
