### ISSUE TITLE
11.2.0 doesn't work at all for me

### ISSUE THREAD

**Issue by snarfed** [tekezo/Karabiner-Elements#1097]
first of all, thank you for developing karabiner elements, i couldn't live without it!

i'm on a mid-2014 retina MBP, mac os 10.13.1. karabiner elements 11.1.0 was working great. i upgraded to 11.2.0, approved the kernel module in System Preferences => Security & Privacy, rebooted to install it, and confirmed that Karabiner AXNotifier and Karabiner Elements are checked in System Preferences => Security & Privacy => Accessibility.

karabiner elements starts up and runs fine...but has no effect. simple modifications, complex modifications, device settings, none of them are working.

[here's a full log](https://github.com/tekezo/Karabiner-Elements/files/1459614/karabiner_elements.log), in case it helps. thanks in advance!

**Comment by snarfed** [comment]
i downgraded to 11.1.0, and it's working again.

**Comment by nitodev** [comment]
Same thing here. It tells me to allow the developer within Security & Privacy. And the button is there, but it won't do anything when I click it. The application is running, but none of the settings are valid rendering it completely useless. Downgraded in the mean time.

**Comment by tekezo** [comment]
@snarfed It seems you failed `System Preferences > Security & Privacy`.

Please confirm another apps prevent click.
https://github.com/tekezo/Karabiner-Elements/issues/1017

**Comment by fudanchii** [comment]
Would like to add, I can confirm no app preventing key/mouse from being captured via event viewer, and the mac is already restarted for the upgrade, passed the `Security & Privacy` settings. But karabiner 11.2.0 doesn't work, the previous version still works wonderfully.

in 11.2.0 I see this log repeatedly (all inputs are ignored):

```[2017-11-10 11:27:56.998] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:2) is ignored.
[2017-11-10 11:27:56.998] [warning] [grabber] virtual_hid_device_client is not connected yet. Please wait for a while.
[2017-11-10 11:28:01.303] [info] [grabber] Load karabiner.json...
[2017-11-10 11:28:01.303] [info] [console_user_server] Load karabiner.json...
[2017-11-10 11:28:01.305] [info] [grabber] core_configuration is updated.
[2017-11-10 11:28:01.305] [info] [console_user_server] core_configuration is updated.
[2017-11-10 11:28:01.307] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:2) is ignored.
[2017-11-10 11:28:01.307] [warning] [grabber] virtual_hid_device_client is not connected yet. Please wait for a while.
[2017-11-10 11:28:31.801] [info] [grabber] Load karabiner.json...
[2017-11-10 11:28:31.801] [info] [console_user_server] Load karabiner.json...
[2017-11-10 11:28:31.803] [info] [grabber] core_configuration is updated.
[2017-11-10 11:28:31.803] [info] [console_user_server] core_configuration is updated.
[2017-11-10 11:28:31.805] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:2) is ignored.
[2017-11-10 11:28:31.805] [warning] [grabber] virtual_hid_device_client is not connected yet. Please wait for a while.
[2017-11-10 11:33:09.419] [info] [grabber] pid:1275 is exited
[2017-11-10 11:33:09.420] [info] [grabber] Connected devices are ungrabbed
[2017-11-10 11:33:09.420] [info] [grabber] event_tap_manager terminated
[2017-11-10 11:33:09.420] [info] [grabber] virtual_hid_device_client::close_connection
```

But it successfully grab the input at 11.1:

```
[2017-11-10 11:49:50.158] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:1) is ignored.
[2017-11-10 11:49:50.386] [info] [console_user_server] frontmost_application_observer initialize
[2017-11-10 11:49:50.387] [info] [console_user_server] input_source_observer initialize
[2017-11-10 11:49:51.203] [info] [grabber] (vendor_id:0x5ac, product_id:0x8600) (device_id:3) is grabbed
[2017-11-10 11:49:51.203] [info] [console_user_server] system_preferences::values is updated.
[2017-11-10 11:49:51.206] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:2) is grabbed
[2017-11-10 11:49:51.206] [info] [grabber] system_preferences_values_updated
```

I would also like to thank you @tekezo for starting Karabiner. It's a live saver for me.

**Comment by Horttcore** [comment]
I could confirm, that the latest update broke it.
After downgrade it works immediately.

**Comment by ChristianHamm** [comment]
For me, after accepting in Security & Privacy and hitting reboot the system freezes while showing the boot-up loading bar at about 80%.

**Comment by elbarto132** [comment]
11.2.0 not working, downgrade to 11.1.0 solved it

@ChristianHamm
https://support.apple.com/en-us/HT201262

**Comment by ChristianHamm** [comment]
Safe mode didn't help. I booted in single user and deleted the kext and services from /Library/Extensions and /Library/Application Support. Then I downgraded to 11.1.0.

**Comment by xiaoaojianghu** [comment]
me too. my os version is 10.13.1

**Comment by snarfed** [comment]
thanks @tekezo!

i run one other app that _might_ intercept clicks, [Slate](https://github.com/mattr-/slate). i uninstalled 11.1.0, rebooted, quit Slate, and installed 11.2.0. it didn't ask me to install the kext again, but it immediately worked, even after i started Slate again.

so, since i didn't click Allow for the kext again, maybe #1017 wasn't the cause for me? not sure.

**Comment by JolinM** [comment]
Same here. High Sierra + 11.2.0 won’t boot at all. I’m trying to delete the kernel via Recovery Mode, but have a hard time to learn the correct syntax. Any help would be really great! So far, I'm here, but without any success. It tells me 

> rmdir -r /Volumes/Macintosh\ HD/Library/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.kext`
> rmdir: illegal option -- r

**Comment by JolinM** [comment]
**Finally fixed it**
Just restored from a previous Time Machine backup!

**Comment by drummingdemon** [comment]
Same here, macOS High Sierra 10.13.1
Installed KE update as requested, enabled kext and restarted, now the same log message is repeating:

``[2017-11-10 16:39:33.228] [warning] [grabber] virtual_hid_device_client is not connected yet. Please wait for a while.``

**Comment by al1947** [comment]
Me, too... downgrade to 11.1.0 was necessary

**Comment by ottijp** [comment]
same problem.
on macOS High Sierra (10.13.1).

karabiner-elements 11.2.0 doesn't work.
karabiner-elements 11.1.9 works fine.

I downloaded previous version (11.1.19) from [here](https://github.com/tekezo/pqrs.org/blob/master/webroot/osx/karabiner/files/Karabiner-Elements-11.1.9.dmg).

**Comment by tekezo** [comment]
@snarfed I'm sorry, it's my mistake. #1017 is not related with your issue.
However, I still cannot reproduce this issue.

Could you show me the result of following commands on Terminal.app with Karabiner-Elements 11.2.0 in order to investigate the cause?

```
kextstat | grep pqrs
```

```
ioreg | grep pqrs
```

Here is expected results.
```
$ kextstat | grep pqrs
  142    0 0xffffff7f80cdb000 0x7000     0x7000     org.pqrs.driver.Karabiner.VirtualHIDDevice.v040900 (4.9.0) 015508EB-A3C5-385A-B3D4-681CED7A4352 <45 5 4 3 1>

$ ioreg | grep pqrs

      +-o org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDRoot_v040900  <class org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDRoot_v040900, id 0x1000003fc, registered, matched, active, busy 0 (94 ms), retain 6>
      | +-o org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDRoot_UserClient_v040900  <class org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDRoot_UserClient_v040900, id 0x100001513, !registered, !matched, active, busy 0 (55 ms), retain 8>
      |   +-o org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDKeyboard_v040900  <class org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDKeyboard_v040900, id 0x100001514, registered, matched, active, busy 0 (2 ms), retain 11>
      |   | | +-o org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDEventService_v040900  <class org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDEventService_v040900, id 0x10000151b, registered, matched, active, busy 0 (0 ms), retain 8>
      |   +-o org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDPointing_v040900  <class org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDPointing_v040900, id 0x100001b4c, registered, matched, active, busy 0 (4 ms), retain 13>
```

**Comment by dixius99** [comment]
For me, reinstalling 11.2.0 after the System Preferences => Security & Privacy step fixed it. (i.e., I installed 11.2.0, went through the System Preferences stuff, had the same issues other shared above, then installed 11.2.0 again, which got me back up and running.)

**Comment by drummingdemon** [comment]
@tekezo -san thank you so much for your efforts so far!
Having done what @dixius99 said it now works for me again.

**Comment by snarfed** [comment]
@tekezo sure!

```
$ kextstat | grep pqrs
  152    0 0xffffff7f83573000 0x29000    0x29000    org.pqrs.driver.Karabiner (10.22.0) 75A195F3-FC81-39D0-9040-64D3880249EE <45 5 4 3 1>
  166    0 0xffffff7f8361a000 0x7000     0x7000     org.pqrs.driver.Karabiner.VirtualHIDDevice.v040900 (4.9.0) 015508EB-A3C5-385A-B3D4-681CED7A4352 <45 5 4 3 1>

$ ioreg | grep pqrs
      +-o org_pqrs_driver_Karabiner  <class org_pqrs_driver_Karabiner, id 0x100000440, registered, matched, active, busy 0 (0 ms), retain 5>
      +-o org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDRoot_v040900  <class org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDRoot_v040900, id 0x10000060c, registered, matched, active, busy 0 (4 ms), retain 6>
        +-o org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDRoot_UserClient_v040900  <class org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDRoot_UserClient_v040900, id 0x100000666, !registered, !matched, active, busy 0 (3 ms), retain 7>
          +-o org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDKeyboard_v040900  <class org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDKeyboard_v040900, id 0x100000667, registered, matched, active, busy 0 (3 ms), retain 11>
            | +-o org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDEventService_v040900  <class org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDEventService_v040900, id 0x10000066e, registered, matched, active, busy 0 (0 ms), retain 8>
```

looks similar to yours, but not the same. i have an extra kext and an extra i/o registry. maybe left over from the original karabiner? i used to use it before i switched to elements.

**Comment by tekezo** [comment]
@snarfed Thank you for confirmation!

I think the error state has been changed from the first time.
The following line should be appeared in the log messages. (It does not exists in the first log.)

```
[2017-11-11 08:37:52.031] [info] [grabber] initialize_virtual_hid_keyboard
```

Is Karabiner-Elements 11.2.0 still not working well?
If so, please show me a current log messages again.

**Comment by snarfed** [comment]
@tekezo 11.2.0 is working fine for me after reinstalling! details in https://github.com/tekezo/Karabiner-Elements/issues/1097#issuecomment-343491456.

**Comment by tekezo** [comment]
Thank you for all feedbacks!
I think this issue has gone on Karabiner-Elements 11.3.0.

# Detail

I still cannot reproduce this issue, but I believe this issue is caused by macOS's kext cache problem.
Karabiner-Elements 11.2.0 has been shipped with new kext (Karabiner-VirtualHIDDevice 4.9.0), 
macOS failed to refresh kext cache properly, and old kext was loaded as new from invalid cache.
(Reinstalling updates kext cache properly, and Karabiner-Elements works well.)

I changed the location of kext and kext file name to avoid this problem in Karabiner-Elements 11.3.0.

**Comment by al1947** [comment]
reinstalling after a downgrade worked for me...

**Comment by fiveNinePlusR** [comment]
a bit late to the party but if you have an app that intercepts mouse clicks and forwards them on you need to disable them to click the allow button. (magic prefs, jitouch, etc...)
