### ISSUE TITLE
Complex rule stopped working after updating to macOS High Sierra

### ISSUE THREAD

**Issue by karabinr** [tekezo/Karabiner-Elements#1098]
I just updated to macOS High Sierra (10.13) and Karabiner-Elements 11.2.0, and now my complex modification doesn't work.

Grave Accent to Left Command and Space

**Comment by joshuap** [comment]
+1 I just updated to 11.2.0 and High Sierra 10.13.1 and my complex modifications are no longer working; they were working on the previous versions of Elements/High Sierra (I don't remember exact versions).

**Comment by karabinr** [comment]
I tried the latest update 11.3.0, but my complex mod is still now working. Also tried downgrading to 11.1.0 as joshuap suggested, but that didn't work either.

Grave Accent to Left Control and Space
[https://gist.githubusercontent.com/karabinr/73f4ba312e2fc72f636e1db745175b99/raw/b8c322e25ce6d963c5183a38e35466bca92ff198/grave_accent_to_left_control_space.json](url)

**Comment by NessDan** [comment]
Same boat :(

**Comment by karabinr** [comment]
Updated to KE 11.3.0 and my complex mod is working again. But, I used to be able to just tap the key and the mod would work. Now I have to press and hold the key for 1 second.

**Comment by mhosks** [comment]
KE 11.3 / macOS High Sierra: not working at all, even on a 1-second hold.

**Comment by martinklepsch** [comment]
I uninstalled and reinstalled karabiner-elements (same version) and that fixed the problem.

**Comment by mbjelac** [comment]
Using High Sierra 10.13.1 and KE 12.0.0
Can't get complex mods to work.
Tried uninstalling and installing again. Nothing.
