### ISSUE TITLE
Export old Karabiner prepared setting to use here

### ISSUE THREAD

**Issue by slovenianGooner** [tekezo/Karabiner-Elements#11]
Hi,

I'm probably pushing it here, but is there any chance to export the old prepared settings (for Slovenian in my case) to have as a reference when building karabiner.json?

Thanks for the info.

**Comment by slovenianGooner** [comment]
Never mind, found the files in "Karabiner.app/Resources/include/checkbox/languages/slovenian.xml". Now only hoping the key codes are the same. Hope it helps someone else as well.

**Comment by guycalledseven** [comment]
@slovenianGooner have you managed to make new config out of old one for slovenian? looking to do the same for croatian :)

**Comment by slovenianGooner** [comment]
@guycalledseven Haven't managed to make it, hope there will be some way made to convert the old files to new remaps. Only thing missing for me to update to Sierra basically.
