### ISSUE TITLE
App crashes on open 

### ISSUE THREAD

**Issue by tomlube** [tekezo/Karabiner-Elements#110]
Karabiner-Elements crashes on open immediately and will not let me uninstall.

Exception Name: NSInvalidArgumentException
Description: *** -[NSTextView replaceCharactersInRange:withString:]: nil NSString given.
User Info: (null)

0   CoreFoundation                      0x00007fff9efbd52b __exceptionPreprocess + 171
1   libobjc.A.dylib                     0x00007fffb3695cad objc_exception_throw + 48
2   CoreFoundation                      0x00007fff9f03ba0d +[NSException raise:format:] + 205
3   AppKit                              0x00007fff9cd6a1e2 -[NSTextView replaceCharactersInRange:withString:] + 211
4   Karabiner-Elements                  0x0000000104b097f2 __37-[LogFileTextViewController monitor:]_block_invoke + 636
5   libdispatch.dylib                   0x00007fffb3f3d128 _dispatch_client_callout + 8
6   libdispatch.dylib                   0x00007fffb3f52c10 _dispatch_continuation_pop + 533
7   libdispatch.dylib                   0x00007fffb3f48ad2 _dispatch_source_latch_and_call + 192
8   libdispatch.dylib                   0x00007fffb3f3f966 _dispatch_source_invoke + 1248
9   libdispatch.dylib                   0x00007fffb3f4aa0f _dispatch_main_queue_callback_4CF + 505
10  CoreFoundation                      0x00007fff9ef72c89 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
11  CoreFoundation                      0x00007fff9ef340ad __CFRunLoopRun + 2205
12  CoreFoundation                      0x00007fff9ef335b4 CFRunLoopRunSpecific + 420
13  HIToolbox                           0x00007fff9e4d4f6c RunCurrentEventLoopInMode + 240
14  HIToolbox                           0x00007fff9e4d4ca9 ReceiveNextEventCommon + 184
15  HIToolbox                           0x00007fff9e4d4bd6 _BlockUntilNextEventMatchingListInModeWithFilter + 71
16  AppKit                              0x00007fff9cbcb5f5 _DPSNextEvent + 1093
17  AppKit                              0x00007fff9d2db8eb -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1637
18  AppKit                              0x00007fff9cbbffbd -[NSApplication run] + 926
19  AppKit                              0x00007fff9cb8aa8a NSApplicationMain + 1237
20  libdyld.dylib                       0x00007fffb3f73255 start + 1

**Comment by tekezo** [comment]
Duplicated #69

Please upgrade to the latest version from "Misc > Check for updates" or
https://pqrs.org/latest/karabiner-elements-latest.dmg

**Comment by tomlube** [comment]
Is already updated to that - can't uninstall or update through the app, because it crashes upon opening it.

**Comment by tekezo** [comment]
You can install from the latest package.
https://pqrs.org/latest/karabiner-elements-latest.dmg

**Comment by tomlube** [comment]
I've already reinstalled using that version number and just tried again. Still crashes immediately.

**Comment by tekezo** [comment]
Thank you for confirmation!
The fix in v0.90.37 was not enough.

I've fixed this issue again at v0.90.38.
Please upgrade from this package.
https://pqrs.org/macosx/karabiner/files/Karabiner-Elements-0.90.38.dmg

**Comment by tomlube** [comment]
This did it. Thank you so much.
