### ISSUE TITLE
Problems with OptionR->CommandR remapping

### ISSUE THREAD

**Issue by RicoSky** [tekezo/Karabiner-Elements#1100]
After todays Karabiner update my remapping of Option R to Command R doesn't work. The remapping is defined in the table in Karabiner but is not active

**Comment by RicoSky** [comment]
![zrzut ekranu 2017-11-10 o 15 21 17](https://user-images.githubusercontent.com/24524927/32662442-dbcdc5e8-c62a-11e7-85e8-b0910bcea369.jpg)

**Comment by tysutw** [comment]
same issue

**Comment by RicoSky** [comment]
Works again, after todays update! thanks!
