### ISSUE TITLE
Is it possible to use CAPSLOCK with a different key?

### ISSUE THREAD

**Issue by ramiroaraujo** [tekezo/Karabiner-Elements#1101]
I have the usual Caps Lock -> Esc and Caps Lock + Key  -> Ctrl + Key, but I wonder if it's possible by ANY means to have the ability to toggle Caps Lock somehow, wether it's a different key, key combo, command line, app, whatever. It's not a huge deal, but from time to time you need to write with all caps and it sucks to hold down the shift that much :)

I've tried: 
* setting up a physical function key to caps lock. Didn't work
* a simple modification of a function key to caps lock. Worked, but of course triggers the ESC key.
* a useless media button to caps lock. Didn't work.

Any hint welcome!
Thanks

**Comment by nguyenhimself** [comment]
>setting up a physical function key to caps lock. Didn't work

It works for me just fine, for example: remapping F7 to Capslock. My Capslock light even light up.

**Comment by quintrino** [comment]
While not a solution through Karabiner-elements I have BetterTouchTool set up with a keyboard shortcut for Capslock. Hope you find a solution that works for you.

**Comment by pirj** [comment]
Have you tried swapping it line in the example https://github.com/tekezo/Karabiner-Elements/blob/master/examples/swap_caps_lock_and_escape.json in addition to using that Esc/Ctrl rule?

**Comment by bradhowes** [comment]
This snippet using the right command key for a caps lock works for me:

```
        {
            "description": "Map right_command to caps_lock.",
            "manipulators": [
                {
                    "from": {
                        "key_code": "right_command",
                        "modifiers": {
                            "optional": [
                                "any"
                            ]
                        }
                    },
                    "to": [
                        {
                            "key_code": "caps_lock"
                        }
                    ],
                    "type": "basic"
                }
            ]
        }
```

**Comment by ramiroaraujo** [comment]
Thanks all! I've must have done something wrong the first time :)
I'm using @bradhowes example and It's working great with Opt + F12, rare enough for most apps :D:D:D

Thanks again!
