### ISSUE TITLE
Issue with the "fn" key

### ISSUE THREAD

**Issue by deecypher** [tekezo/Karabiner-Elements#1104]
Greetings, I'm using a Logitech MK235 keyboard/mouse combination with a Mac Mini under MacOS 10.13.1 and using Karabiner-Elements 11.2.0.

Since this is a Windows style keyboard, there is only 1 "Windows" key (left of the space bar) which normally maps to the "Command" function. This works as expected.

However, what I would like to use Karabiner for is to map another key on the right side of the space bar also to "Command". I was hoping to map the "fn" button, but it doesn't to work.

Any help that can be provided would be greatly appreciated.

**Comment by tobiasboyd** [comment]
On most hardware, `fn` keypresses aren't sent to the OS, only the tuple of `fn+other key`. For examples, see https://stackoverflow.com/questions/514781/intercepting-the-fn-key-on-laptops

You might look at Controllermate, though I suspect it will have the same limitations.
