### ISSUE TITLE
The new version 11.2.0 does not work on macOS High Sierra 10.13.1

### ISSUE THREAD

**Issue by gmh14** [tekezo/Karabiner-Elements#1105]
The new version cannot disable the build-in keyboard for MacBook Pro. I have to roll back to 11.0.0.

**Comment by dixius99** [comment]
It wasn't working for me either. I got a message about changing Security & Privacy settings, which I did, which still didn't fix things.

**However:** after all of that, I downloaded 11.2.0 manually and installed again, and it worked. Maybe worth a try

**Comment by thymara** [comment]
went back to 11.0.0 as well

**Comment by HustLion** [comment]
I'm on macOS High Sierra 10.13.1. And 11.2.0 not working, went back to 11.1.0

**Comment by tekezo** [comment]
#1097
