### ISSUE TITLE
How to disable sysdiagnose key combination

### ISSUE THREAD

**Issue by nocLyt** [tekezo/Karabiner-Elements#1107]
I'm turning `Caps Lock` into `Hyper` modifier key. `Hyper` is `Command-Shift-Option-Control`.

However, there is one small problem: you might trigger the sysdiagnose command accidentally. Finder will open the sysdiagnose folder, well, diagnose your system, and zip the log results. Worst, sysdiagnose will drive the CPU performance crazy in order to diagnose your system.

> sysdiagnose can be triggered upon pressing a special key chord; 
this is currently Command-Shift-Option-Control-Period (.).

How can I disable sysdiagnose key combination with Karabiner-Elements? or other ways?

**Comment by wxmtech** [comment]
same problem here, tried other tools and no way to disable the combo.

Plus the cmd+opt+ctrl - . for increase contrast cannot be remapped neither.

**Comment by JakobR** [comment]
I got it to work with the following configuration:

```json
{
  "title": "Change CapsLock to Command-Shift-Option-Control",
  "rules": [
    {
      "description": "Change CapsLock to Command-Shift-Option-Control modifier (or Escape when pressed alone)",
      "manipulators": [
        {
            "from": {
                "key_code": "caps_lock"
            },
            "to": [
                {
                    "set_variable": {
                        "name": "hyper_modifier",
                        "value": 1
                    }
                },
                {
                    "key_code": "left_shift",
                    "modifiers": [
                        "left_command",
                        "left_control",
                        "left_option"
                    ],
                    "lazy": true
                }
            ],
            "to_after_key_up": [
                {
                    "set_variable": {
                        "name": "hyper_modifier",
                        "value": 0
                    }
                }
            ],
            "to_if_alone": [
              {
                "key_code": "escape"
              }
            ],
            "type": "basic"
        }
      ]
    },
    {
      "description": "Disable Command-Shift-Option-Control-Period (.)",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "period",
            "modifiers": {
              "mandatory": [
                "command",
                "shift",
                "option",
                "control"
              ]
            }
          }
        }
      ]
    },
    {
      "description": "Disable Command-Shift-Option-Control-Comma (,)",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "comma",
            "modifiers": {
              "mandatory": [
                "command",
                "shift",
                "option",
                "control"
              ]
            }
          }
        }
      ]
    }
  ]
}
```

**Comment by acnebs** [comment]
I'm having this issue but I'm not even hitting comma or period.

I have caps lock mapped to CMD+CTRL+OPTION+SHIFT and every time I hit that with "w", `sysdiagnose` gets triggered.

**Comment by bnferguson** [comment]
@acnebs Seems in Catalina they added a new Key combo for WiFi Diagnostics. You can see you probably have a bunch of files in `/private/var/tmp` from hitting it. Still trying to find a spot to disable it but I'm guessing this is pretty well wired into OSX if it responds even during system hang like SysDiagnose does.

**Comment by connorcarr** [comment]
For anyone still following this thread, my workaround was to simply change the hyper key to shift+option+control. I had a lot of trouble getting that rule to stick, until I found an app to modify and have pasted my simplistic rule on "https://genesy.github.io/karabiner-complex-rules-generator/#eyJ0aXRsZSI6IkNoYW5nZSBjYXBzX2xvY2sga2V5IChyZXYgNCkiLCJydWxlcyI6W3siZGVzY3JpcHRpb24iOiJDaGFuZ2UgY2Fwc19sb2NrIGtleSB0byBjb250cm9sK29wdGlvbitzaGlmdC4gKFBvc3QgZXNjYXBlIGtleSB3aGVuIHByZXNzZWQgYWxvbmUpIiwibWFuaXB1bGF0b3JzIjpbeyJ0eXBlIjoiYmFzaWMiLCJmcm9tIjp7ImtleV9jb2RlIjoiY2Fwc19sb2NrIiwibW9kaWZpZXJzIjp7Im9wdGlvbmFsIjpbImFueSJdfX0sInRvIjpbeyJrZXlfY29kZSI6ImxlZnRfc2hpZnQiLCJtb2RpZmllcnMiOlsibGVmdF9jb250cm9sIiwibGVmdF9vcHRpb24iXX1dLCJ0b19pZl9hbG9uZSI6W3siaG9sZF9kb3duX21pbGxpc2Vjb25kcyI6MTAwLCJrZXlfY29kZSI6ImNhcHNfbG9jayJ9XX1dfV19". 

I use slate so just edited the 'hyper' key variable to reflect this and now there's no sysdiagnostics happening every 5 mins.

There may be other problems with using this new key combination which I haven't foreseen but it works flawlessly for my use case.

I hope this helps.

**Comment by mdentremont** [comment]
@JakobR Thanks for the snippet, just an FYI: I also needed an ignore for "slash"

**Comment by towry** [comment]
[JakobR](https://github.com/JakobR) 's solution works, but it also make those key combination disabled and can not be used for other app.

**Comment by catouse** [comment]
For disable WiFi logging：

```json

**Comment by NightMachinery** [comment]
I am mapping these `hyper+,`, `hyper+.` to my own hotkeys through Hammerspoon, but sometimes they trigger the OS diagnostics. Can I somehow disable the OS shortcuts?
