### ISSUE TITLE
Use scroll guesture with modifier key to zoom not working after start karabiner-elements

### ISSUE THREAD

**Issue by jay-cheung** [tekezo/Karabiner-Elements#111]
After start karabiner-elements , the titled function will not work and quit it the function will work again.

**Comment by acidix** [comment]
+1 - happens for me as well. All modifier keys affected.

**Comment by tphares1** [comment]
This repeats for me on version 0.90.39

**Comment by KTamas** [comment]
+1 this is a big issue for me because I use screen zoom all the time

**Comment by ZimboBoyd** [comment]
+1
Yes very annoying!  This keeps me from using Karabiner-Elements!

**Comment by gabrielmaldi** [comment]
This is still an issue with version `0.90.48`. I love to Command + scroll to zoom, it would be great if this got fixed 😄  Thanks!

<img width="780" alt="screen shot 2016-10-10 at 5 09 54 pm" src="https://cloud.githubusercontent.com/assets/3728897/19249628/e6aebbe4-8f0c-11e6-964a-bc984f607997.png">

**Comment by scalz8** [comment]
Same for me. I can't work without forward delete... and neither without the scroll zoom..... Thanks for your support!

**Comment by MerliX** [comment]
Confirm this, waiting patiently for fix

**Comment by rdmendo** [comment]
+1

**Comment by Username-Bacon** [comment]
still waiting for this... it's been almost three months after the first issue about this

**Comment by entonio** [comment]
See https://github.com/tekezo/Karabiner-Elements/issues/89

**Comment by scalz8** [comment]
Now it works: both forward_delete and zoom are possible!!! That's great! So happy! many thanks!

**Comment by GregOriol** [comment]
Indeed, 0.90.67 seems to fix the issue!

**Comment by tphares1** [comment]
Confirmed fixed in 0.90.67.  Great work guys!

**Comment by cranmer** [comment]
Yea!!!!!

https://github.com/tekezo/pqrs.org/tree/master/webroot/osx/karabiner/files

**Comment by dr** [comment]
Thank you, @tekezo!
