### ISSUE TITLE
all I want is back button work on my microsoft sculpt ergo mouse.

### ISSUE THREAD

**Issue by medyagh** [tekezo/Karabiner-Elements#1112]
I do NOT undrestand this, how come all the features of my mouse and keyboard work perfectly fine on any version of linux (as old as 13 years old) but none of the buttons of my mouse work on any version of mac, even after installing microsoft's intelli driver.

I have mac os sierra 
I have Microsoft mouse sculpt ergonomic,
I have tried different versions of karabniner, and karabiner element, 
The event listener shows my back button on the mouse as button 4, but I can not make this button 4 to do anything usefull (I want it to be Back Button in the browser)

![screen shot 2017-11-13 at 12 32 07 am](https://user-images.githubusercontent.com/4564227/32712430-24e65d2c-c80a-11e7-8c4e-26f65067d673.png)

can someone for the sake of god help me ? how the heck Apple fan boys call this stupid opreating system an operating system at all ? any version of linux as old as ubuntu 6.04 supports all the features of my mouse that was built after it the linux was released.

after buying a few crap app on app store to make it work and trying diff version of karabara that was meant to only solve this issue, nothing is fixed. 

sorry the ranting part was toward apple. I greatly appreciate the developers of Karabiner-Elements trying to save us !

**Comment by NessDan** [comment]
This worked for me

https://github.com/archagon/sensible-side-buttons

**Comment by medyagh** [comment]
@NessDan you are my today's angel ! seriously, It feels so liberating to have your Back button back.

**Comment by MrDesjardins** [comment]
For those who are looking to have the back button to their Microsoft Sculpt mouse on Mac 10.12 you can use the following configuration:

```
{
                        "manipulators": [
                            {
                                "description": "Mouse back",
                                "from": {
                                    "pointing_button": "button4"
                                },
                                "to": [
                                    {
                                        "key_code": "left_arrow",
                                        "modifiers": [
                                            "left_command"
                                        ]
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    }
``` 
Inside `/Users/YOURNAME/.config/karabiner/karabiner.json`

**Comment by zlodes** [comment]
@MrDesjardins thanks a lot!

**Comment by mirzmaster** [comment]
@MrDesjardins While your solution works for the back button in browser, many text editors use a different key combination for back, since Cmd + Left Arrow will put you at the beginning of a line in a text area.  So you're not getting true back button emulation with Karabiner.

**Comment by arooni** [comment]
I tried restarting karabiner-elements and following @MrDesjardins  's instructions and I couldn't get it working :\

**Comment by nonoroazoro** [comment]
The button4 is not working at all in karabiner-elements, while it's working in karabiner... ???
After I tried everything, I'd say this is totally a bull 💩 brought with the stupid Sierra.

**Comment by aleemb** [comment]
If https://github.com/pqrs-org/KE-complex_modifications/issues/431 gets resolved, this should be installable via `Complex Modifications > Add Rule > (Search for: browser back/forward)`

**Comment by nonoroazoro** [comment]
@aleemb Awesome! Thanks a lot!

**Comment by jakub-g** [comment]
Semi-related to the original question:

I wanted my MS Sculpt Ergonomic Desktop to display Mission Control. The `mouse4` didn't work, but by following [this question](https://superuser.com/a/1636028/97570) I managed to set it up by clicking the back button itself after focusing the shortcut box in system settings (which then makes it display as `ctrl-cmd-d`, curiously)

![image](https://github.com/pqrs-org/Karabiner-Elements/assets/1437027/3c77d982-8828-49c5-9fac-a7c0f4e02c6e)
