### ISSUE TITLE
How can I add a key_code to each press ?

### ISSUE THREAD

**Issue by xcode-manolo** [tekezo/Karabiner-Elements#1117]
Hi guys !!!
I need to set a variable with every keystroke.
For making this issue easier, we'll imagine that my problem is:

I need that with every keystroke, appears a space character after the pressed key.  I use **"any": "key_code"** in the **"from":** section for that, for absorbing all the keystrokes, but I don't know how to refer those keystrokes in the **"to":** section **_without having to do it for every single key._**  I tried the following code.

````  
          {
            "from": {
              "any": "key_code"
            },
            "to": [
              {
                "any": "key_code"
              },
              {
                "key_code": "spacebar"
              }, 
            ],
            "type": "basic"
          }
````
In addition to **"to": [  {  "any": "key_code"  },** I also tried with:
````
              { "key_code": "any" },
              { "key_code": "key_code" },
              { "any": "any" },
````
but none of those expressions works !!!

Any suggestions ?
Any kind of help will be appreciated.

Thanks for your attention !!!
Have a great day !!!

**Comment by thomasjachmann** [comment]
Right now, I think that doesn't work. Modifying a lot of keys in similar ways results in huge config files. In #832, I asked about wildcards. Maybe you could upvote that ticket somehow if this would solve your problem as well. If enough users care about it, this might become a feature request worth handling. Although both this and my ticket are quite old already...

**Comment by xcode-manolo** [comment]
HI @thomasjachmann, I have just upvoted your tickets for making our request somewhat stronger.
Thanks for your answer, your attention and your time !!! 
Have a great day !!!
