### ISSUE TITLE
Documentation of "Complex Modifications"

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [tekezo/Karabiner-Elements#1118]
I did a little searching through the Issues, and I almost can't believe that there isn't already an issue for this; but:

It appears there's no documentation, either in the app, README, or included "Documentation" link, about how to create new "complex" modifications. (My particular use-case at the moment: re-mapping the "application" key to ⌘␣, to invoke Spotlight.)

**Comment by dougglez** [comment]
I've spent nearly my entire day looking for documentation on the complex modifications. What options we have to work with etc. If there is documentation somewhere, please let me know where it is.

**Comment by s-show** [comment]
I also looked for the documentation of "Complex Modifications", but I could not find it. For that reason, I created a [web page](https://qiita.com/s-show/items/a1fd228b04801477729c) that summarized the information I examined. However, this page is written in Japanese.
Therefore, please read using Google Translate etc. I hope that the information I have written will be of any use.

**Comment by pthieu** [comment]
Got this working by parsing through source code and other people's gists. For me, I'd like to find information on every parameter of the `conditions` field, especially the `bundle_identifiers`.

For any english speakers, you can look at @s-show's site and more or less get an idea of what the parameters do.

**Comment by s-show** [comment]
@ELLIOTTCABLE 
@tekezo has created a reference for 'complex_modifications'. The URL is here.
[karabiner.json Reference Manual - Karabiner - Software for mac OS
](https://pqrs.org/osx/karabiner/json.html)
This reference is very useful.

**Comment by ELLIOTTCABLE** [comment]
@s-show awesome! Now we just need to get @tekezo to add a link to that somewhere easier to find! 🤣
