### ISSUE TITLE
Updater is not "uptading" my copy, it just stubbornly installs to /Application

### ISSUE THREAD

**Issue by CodingMarkus** [tekezo/Karabiner-Elements#1119]
When installing Karabiner Elements, it installs itself to /Applications, which is normal and desired behavior. However, when I move the app to a different directory, which always has been a perfectly legal action on macOS (apps don't have to be in /Applications, they never had to) and then install an update, the installer installs again to /Application and doesn't update the moved files in place, so I now have two copies on disk, one in /Applications and one where I moved the previous version to and this is incorrect behavior. 

E.g. the system installer from Apple (the one installing .pkg files) also requires a default install location, which usually is /Applications, however, when it detects an update is being installed (as a previous version of that packet has been installed before), it will first try to find the currently installed app (it uses LaunchServices API to find the current app location by bundle ID) and if found, it will choose this directory as install location and update the app in place (it will not bullheadedly install to /Applications). Or when using the Sparkle updater framework, the app is always updated in-place. This is the desired behavior, as developers are not supposed to tell users where they have to install their apps and macOS apps are supposed to always be location independent.

**Comment by tekezo** [comment]
You should not move applications which are installed by pkg file.
Karabiner-Elements is one of such app.

**Comment by CodingMarkus** [comment]
Did you even read my my text above? If so, please explain, which part of this sentence was unclear, so I can rephrase it for you:

_E.g. the system installer from Apple (**the one installing .pkg files**) also requires a default install location, which usually is /Applications, however, when it detects an update is being installed (as a previous version of that packet has been installed before), it will first try to find the currently installed app (it uses LaunchServices API to find the current app location by bundle ID) and if found, it will choose this directory as install location and update the app in place (it will not bullheadedly install to /Applications)._

This works fine with all installers from Apple (please also explain why Apple implements such a behavior, if they don't allow you to move apps after installing them), it works fine with all installers from 3rd party products I am using and it works fine with all installers I've been creating for products in the past. If it does not work with your pkg, then you are definitely doing something wrong as that is automated behavior. Do I really have to fork that product and offer people a working version of your installer because you somehow destroy automated system behavior? Or do you I first have to pull someone from Apple here (I have those contacts) to explain you that you are dead wrong? Sorry, but you're level of  arrogance is intolerable.
