### ISSUE TITLE
Request: Support ~/.config/ ($XDG_CONFIG_HOME)

### ISSUE THREAD

**Issue by lgarron** [tekezo/Karabiner-Elements#112]
A home folder gets very crowded if every program creates its own config files/folders there.
A standard alternative that is gaining traction is to place config files under `~/.config` instead.
(At least, if you're not an OSX-only app that uses `~/Library/Application Support`.)

For example, the `fish` shell [uses `~/.config/fish/`](https://fishshell.com/docs/current/faq.html) and `git` looks for its config files under `~/.config/git/` [out of the box](https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup).

It would be nice if we could place config files under `~/.config/karabiner/` instead of `~/.karabiner.d/`. Karabiner-Elements could either do this by changing its default config folder, or by searching there if a config is not found at `~/.karabiner.d/`.

**Comment by lgarron** [comment]
Looking at this a bit more, this standard comes from a project called XDG.

> `$XDG_DATA_HOME` defines the base directory relative to which user specific data files should be stored. If `$XDG_DATA_HOME` is either not set or empty, a default equal to `$HOME/.local/share` should be used.
>
> `$XDG_CONFIG_HOME` defines the base directory relative to which user specific configuration files should be stored. If `$XDG_CONFIG_HOME` is either not set or empty, a default equal to `$HOME/.config` should be used.

**Comment by lgarron** [comment]
Looking at the `git` implementation, a simple heuristic [in `constants.cpp`](https://github.com/tekezo/Karabiner-Elements/blob/master/src/share/constants.hpp) should do (assuming you're willing to support it:

https://github.com/git/git/blob/35f6318d44379452d8d33e880d8df0267b4a0cd0/path.c#L1254

    if (!once) {
      once = true;
      if (auto x = std::getenv("XDG_CONFIG_HOME")) {
        directory = x;
        directory += "/karabiner";
      } else if (auto p = std::getenv("HOME")) {
        directory = p;
        directory += "/.karabiner.d";
      }
    }

However, that doesn't cover [`src/apps/PreferencesWindow/PreferencesWindow/Base.lproj/MainMenu.xib`](https://github.com/tekezo/Karabiner-Elements/blob/fa96578ed2d106480c20c849c82c3d10db523022/src/apps/PreferencesWindow/PreferencesWindow/Base.lproj/MainMenu.xib#L573) or [`src/apps/PreferencesWindow/PreferencesWindow/PreferencesWindowController.m`](https://github.com/tekezo/Karabiner-Elements/blob/6f4cb0936bfd7e08042a0ebca2f797f037f3893c/src/apps/PreferencesWindow/PreferencesWindow/PreferencesWindowController.m#L15)

**Comment by talha131** [comment]
Great idea. Besides `git` and `fish`, [`neovim` also uses XDG convention](https://github.com/neovim/neovim/issues/78).

**Comment by sunapi386** [comment]
+1

**Comment by sunapi386** [comment]
I opened PR https://github.com/tekezo/Karabiner-Elements/pull/114 – this should do it.

**Comment by Suprc** [comment]
+1

**Comment by cseelus** [comment]
This seems to be the current standard for modern unixoid software, to unclutter the home directory. More info [here](https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html) and [here](http://unix.stackexchange.com/questions/24347/why-do-some-applications-use-config-appname-for-their-config-data-while-other).

**Comment by alanshutko** [comment]
Is there any chance that Karabiner-Elements will be ported to other Unices? I thought it was highly Mac specific.

**Comment by cseelus** [comment]
@alanshutko this was not my suggestion (I think there is no reason to port it to other Unices), but macOS is a unixoid OS after all and many similar tools use the $XDG_CONFIG_HOME nowadays.

**Comment by sunapi386** [comment]
@lgarron the title should be corrected, "Request: Support `~/.config/ ($XDG_CONFIG_HOME)`" should be changed to "Request: Support `$XDG_CONFIG_HOME`". Because `$XDG_CONFIG_HOME` should default to `$HOME/.config`.

https://wiki.archlinux.org/index.php/XDG_Base_Directory_support

**Comment by nfarrar** [comment]
Quite some time ago I submit a similar request to hammerspoon. Their solution is here: https://github.com/Hammerspoon/hammerspoon/pull/582 (the default path is set in the in the app plist in ~/Library, allowing users to change the value).

**Comment by lgarron** [comment]
The default path has changed, so this bug should be considered fixed. :-D

Others may like to be able to configure the path using `$XDG_CONFIG_HOME` from default shell, but that's a follow-up feature as far as my request was concerned.

**Comment by cseelus** [comment]
Very nice, bc of this feature one is able to cleanly backup the Karabiner-Elements config with his/her other Dotfiles.
Thanks for the great work!
