### ISSUE TITLE
Thanks for implementing input_source_if

### ISSUE THREAD

**Issue by vlsi** [tekezo/Karabiner-Elements#1120]
I just want to thank you for implementing `input_source_if`. ❤️ 

It works like a charm with High Sierra 10.13.1 + Topre Realforce.

Thanks for having a donation button by the way.

**Comment by pirj** [comment]
Mind closing this issue as a sign of appreciation, please?

**Comment by pirj** [comment]
There is a better way to thank author, it's in the bottom of the README file:

> If you would like to contribute financially to the development of Karabiner Elements, donations can be made via https://pqrs.org/osx/karabiner/donation.html
