### ISSUE TITLE
Internal keyboard totally* disabled

### ISSUE THREAD

**Issue by wginsberg** [tekezo/Karabiner-Elements#1121]
The internal keyboard on my MacBook pro is completely unresponsive (the with the exception of the power button). Trackpad is completely unresponsive too. Tried to boot in safe mode and recovery mode but the internal keyboard wouldn't even register while booting.

***AFAIK it's not even possible that karabiner is causing this, but it seems to like too much of a coincidence that it happens right after I installed it.***

Used an external keyboard to boot in recovery mode and reinstalled OS. Problem persists.

Sorry if the issue is irrelevant but I'm stressing out right now, this is my laptop for university.

**Comment by rynonl** [comment]
Sounds like hardware. The keyboard/trackpad are connected to the MB via a single cable. I had mine slip out a while back and showed the same symptoms. You'll likely have to take it in for repair (blah).

**Comment by wginsberg** [comment]
@rynonl thanks for the comment. Took it in to the shop and it was exactly what you described.
