### ISSUE TITLE
Can't Install 11.2 and 11.3 on Mac High Sierra

### ISSUE THREAD

**Issue by martinmts** [tekezo/Karabiner-Elements#1122]
11.2.0 used to work fine. I clicked the updating when I was notified that 11.3.0 was out.
Then the System won't allow me to "Allow" Karabiner to be installed on my computer.
I enabled the "Anywhere" source, and it does no good to it.
clicking "Allow" does nothing...

I tried to install 11.2.0, and the same problem...although I was able to update to 11.2.0 last time.

Downloaded 11.1.0, and it works great!

**Comment by tekezo** [comment]
Disable MagicPrefs or such apps before click Allow button.
https://github.com/tekezo/Karabiner-Elements/issues/1017
