### ISSUE TITLE
Double key press to a shortcut

### ISSUE THREAD

**Issue by ruslaniv** [tekezo/Karabiner-Elements#1123]
In old Karabiner there used to be a very powerful feature of assigning a shortcut to a double key press, where you could even specify the timing between key presses. Something like this:

```
<lastpressedphysicalkey_only>KeyCode::SHIFT_L</lastpressedphysicalkey_only>
<elapsedtimesincelastpressed_lessthan>Millisecond::RawValue::300</elapsedtimesincelastpressed_lessthan>
          <autogen>

  		__KeyToKey__ 
    		KeyCode::SHIFT_L, 
    		KeyCode::VK_OPEN_URL_SHELL_POPUP_POPCLIP,
    	</autogen>

```
Is it already possible in Karabiner Elements?

**Comment by RuslanIsh** [comment]
Has anybody been able to implement this feature with new example provided in Complex Modifications documentation? 
It does not work for me.

**Comment by momomo** [comment]
Nope. Doesn't work. This here did not either. 

https://github.com/tekezo/Karabiner-Elements/issues/1263
