### ISSUE TITLE
Caps Lock LED in 11.2+

### ISSUE THREAD

**Issue by stevefoxon** [tekezo/Karabiner-Elements#1124]
Hi. I realise that the change in 11.2 was to disable manipulation for anything other than Apple keyboards, so have enabled it manually. Can I just check, that is needed for the CAPS lock to work, even if it isn't being remapped? I ask, as since the update to 11.2 (and now 11.3), the LED goes off and on an awful lot when caps is enabled - particularly when tab through fields where it goes off for about a second and then comes back on. This was never an issue in 11.1 with that happening, and I wasn't't aware that Karabiner was controlling it anyway (if it was).

It's not a major issue, just a little annoying at times.

**Comment by pirj** [comment]
With the following, when CapsLock original behavior is kept when presded alone, LED also changes its state accordingly:
```
{
  "title": "Change caps_lock key",
  "rules": [
    {
      "description": "Change caps_lock to Command if pressed with other keys, to escape if pressed alone.",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "caps_lock",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "left_command"
            }
          ],
          "to_if_alone": [
            {
              "key_code": "caps_lock"
            }
          ]
        }
      ]
    }
  ]
}
```

e.g. on single press it works as CapsLock and displays its status on LED, when pressed with other keys - as Command. PS. Karabiner-Elements 11.3.0, MacOS 10.12.6

**Comment by pirj** [comment]
Also check if you have that box ticked:
https://github.com/tekezo/Karabiner-Elements/blob/4248d61459a4caed5655926727c5733bd398ce4a/NEWS.md#version-1120

**Comment by stevefoxon** [comment]
Hi,

Thanks for your reply, but I am unsure how it helps me? I am only using CAPS LOCK as CAPS LOCK and don't have any doe relating to it. IT does work i.e. the light comes on when use, and goes off when not. However the problem is, the light keeps going off and coming back on when CAP LOCK is on and isn't pressed again - on its own or with other key. 

For example, I put it on, the light comes on - I then type something as normal then tab to another field, and at the point the LED goes off for a second and then comes back on. Or hitting enter may do it as well - it's pretty random, but at not point am I pressing the CPAS LOCK key. Prior to the change, this did not happen, all was fine.

**Comment by stevefoxon** [comment]
Yes, I have that box ticked as well.

**Comment by crus1313** [comment]
Same  here. That tick does nothing. Latest Mojave release, latest Karabinier.

**Comment by austrasien** [comment]
Hello, same problem here on MacBook Pro 13-inch (2017) + macOS Mojave 10.14 (18A391) + Karabiner Elements version 12.1.0 and the "Manipulate LED" checked. Thank you for your help.

**Comment by patrykcieszkowski** [comment]
@crus1313  @austrasien hey, I've been struggling with the same issue recently, and I've found out it was potentially fixed in the recent, beta update. I've been testing it for few mins now and seems to be just fine (make sure you tick `manipulate LED` at your devices tab).

https://github.com/tekezo/Karabiner-Elements/blob/4e0b6c45455bb8c93bf21f327ce342e94abc41ca/NEWS.md
