### ISSUE TITLE
Remapping based on input_source_if does not always work

### ISSUE THREAD

**Issue by ruslaniv** [tekezo/Karabiner-Elements#1129]
I tried to implement one of the settings from legacy Karabiner to map RIGHT_OPT + < to a comma and RIGHT_OPT + > to a period when the keyboard layout is set to Russian. Here is my code:
```
                    {
	"description": "Change R_OPT + LT to comma in Russian layout",
        "manipulators": [{
        "conditions": [{"input_sources": [{"language": "ru"}], "type": "input_source_if"}],
            	"from": {
            		"key_code": "comma",
            		"modifiers": {"mandatory": ["right_option"]}},
            	"to": [{
            		"key_code": "keypad_period"}],
		"type": "basic"}]
                    },
                    {
        "description": "Change R_OPT + GT to period in Russian layout",
        "manipulators": [{
        "conditions": [{"input_sources": [{"language": "ru"}], "type": "input_source_if"}],
		"from": {
			"key_code": "period",
			"modifiers": {"mandatory": ["right_option"]}},
                "to": [{
                	"key_code": "keypad_period",
                	"modifiers": ["left_shift"]}],
                "type": "basic"}]
                	},
```
For whatever reason this does not always work, but works sporadically - sometimes it does and sometimes it produces "≤" or "≥" characters. What could be the problem?

**Comment by RuslanIsh** [comment]
I have modified my code to:
```
{
	"description": "Change R_OPT + LT to comma in Russian layout_2",
        "manipulators": [{
        "conditions": [{"input_sources": [{"language": "ru"}], "type": "input_source_if"}],
            	"from": {
            		"key_code": "comma",
            		"modifiers": {"mandatory" : ["right_option"]}},
            	"to": [{
            		"key_code": "6",
            		"modifiers" : ["left_shift"]}],
            	"to_if_alone": [{
                         "key_code": "escape"}],
		"type": "basic"}]
                    },
                   	{
        "description": "Change R_OPT + GT to period in Russian layout_2",
        "manipulators": [{
        "conditions": [{"input_sources": [{"language": "ru"}], "type": "input_source_if"}],
		"from": {
			"key_code": "period",
			"modifiers": {"mandatory": ["right_option"]}},
                "to": [{
                	"key_code": "7",
                	"modifiers": ["left_shift"]}],
                "to_if_alone": [{
                         "key_code": "escape"}],
                "type": "basic"}]
},
```
Still the same problem, once in a while the remapping just disappears and the shortcut produces "≤" or "≥" characters and I have to switch to EN then back to RU and then remapping is active again.

**Comment by RuslanIsh** [comment]
No matter whether I use
`    "input_source_id": "com.apple.keylayout.Russian",`
or        
`"language": "ru"`
There is still no rhyme or reason when this works as expected or when it produces the "original" character. 
Anybody can help?

**Comment by vlsi** [comment]
@ruslaniv , It looks "input source" detection has been broken in Karabiner-Elements (and/or in macOS) recently.

I've been using https://github.com/pqrs-org/KE-complex_modifications/blob/master/src/json/russian.json.erb since November 2017, and it no longer works. Event Viewer always shows English input source no matter what.

**Comment by vlsi** [comment]
@ruslaniv , just to confirm: macOS 10.13.3 + Karabiner-Elements 11.5.0 work as expected, so you might get some luck by downgrading Karabiner-Elements

**Comment by ruslaniv** [comment]
This is still a problem in KE 12.0.0

**Comment by ruslaniv** [comment]
It still does not work in 12.1.0

**Comment by vlsi** [comment]
KE 12.1.0 + macos 10.13.5 combo works for me  (I use `Change grave accent (') to ё in Russian layout`)

**Comment by ruslaniv** [comment]
I'm still getting ≤ or ≥ instead of , or . at random.

**Comment by biletskyy** [comment]
@ruslaniv I'm swapping colon and semicolon just in english and leaving russian as is using code similar to yours and it works just fine. So it recognizes 
`"input_sources": [{ "language": "en" }`

macOS 10.13.5 karabiner-elements 12.1.0

**Comment by toinfty** [comment]
No, it is still an issue as of karabiner-elements 12.1.0 on macOS 10.13.5.
