### ISSUE TITLE
Add a delay to activate Space FN

### ISSUE THREAD

**Issue by ejnagayama** [tekezo/Karabiner-Elements#1130]
How can I add a pause when activating SpaceFN by the spacebar? I did it previously but have now forgotten. I believe I added a delay to the .json file or .xml file? But I don't remember exactly what file and what the syntax was. I would appreciate any help. Thank you

**Comment by wincent** [comment]
I think there's some missing functionality here, which I asked for in #877.

**Comment by wincent** [comment]
#877 is resolved, so I think this one can be closed too.
