### ISSUE TITLE
New Sierra High Sierra has been supported yet?

### ISSUE THREAD

**Issue by lujianmei** [tekezo/Karabiner-Elements#1131]
New version of Sierra has coming to be installed, called High Sierra, it reminds me the last MacOS update from Yoga to Sierra, that i waited Karabiner-Elements coming out for over two month. It was painful. 
So the priority thing to consider is making sure the Karabiner-Elements can be supported in new version, or i would not update it.

**Comment by pirj** [comment]
> The current release works on the following macOS:
  
  macOS High Sierra (10.13)
  macOS Sierra (10.12)
  macOS El Capitan (10.11)

**Comment by drwl** [comment]
@lujianmei looks like your issue has been answered. If you agree, would you mind closing the issue?
