### ISSUE TITLE
Can't Install Karabiner Elements Update 11.3.0

### ISSUE THREAD

**Issue by chepevm** [tekezo/Karabiner-Elements#1132]
At the time that of installing the update 11.3.0 when Mac ask for permission in Security and Privacy nothing happens when I allow the system to install the update, nothing at all. Previous versions of Karabiner worked perfectly but since two weeks ago I haven't found the way to install the update.

**Comment by chepevm** [comment]
Required information
macOS version: macOS 10.13.1
Karabiner version: 
(You can confirm the version in "Misc & Uninstall" tab in Karabiner Preferences.)
Your Mac hardware:
Your keyboard hardware:

**Comment by Rajveer86** [comment]
Yep, same here. This is on a Mac Mini 7,1 and 10.13.1

**Comment by tekezo** [comment]
Disable MagicPrefs or such apps before click Allow button.
#1017

**Comment by tony-o** [comment]
I'm having this issue and MagicPrefs isn't installed.

**Comment by CeesLeijenhorst** [comment]
Same problem here. No MagicPrefs and still allow button does not work on my MacBook Pro with High Sierra

**Comment by tekezo** [comment]
You can press Allow button by starting your Mac in safe mode if you cannot find apps which prevent Allow button click.
https://pqrs.org/osx/karabiner/help.html#kext-allow-button-does-not-work

**Comment by pastudan** [comment]
As [dansanduleac pointed out](https://github.com/tekezo/Karabiner-Elements/issues/1017#issuecomment-357471556) in the above thread, you can use the keyboard to hit the button. I had better touch tool, and not sure if that was the culprit or not, but this worked for me.

> Alternatively you can use the keyboard, if you have full keyboard access enabled:
> ![image](https://user-images.githubusercontent.com/1296162/36773667-93130f80-1c0f-11e8-9b1e-90679d582bd5.png)
> Then just press tab several times until the "Allow" button is highlighted, then press space to activate it.

Seemed easier than booting into safe mode.

**Comment by feuyeux** [comment]
Let Karabiner-Elements running, firstly.
And then Open "System Preferences > Security & Privacy > Click "Allow".
My KE version is `12.1.0` and OS version is Sierra `10.13.6`
