### ISSUE TITLE
Allow Cmd to be used with Vi Style Arrows.

### ISSUE THREAD

**Issue by mthadley** [tekezo/Karabiner-Elements#1133]
I recently upgraded from Karabiner to Karabiner-Elements, and noticed that it still supports vi style arrows:

```
Change Control + h/j/k/l to Arrows
Change Option + h/j/k/l to Arrows
Change Fn + h/j/k/l to Arrows
```

However I don't see a way to enable them using left command. Is this something that currently exists, or can be added in the future? Thanks.

**Comment by mthadley** [comment]
So I ended up finding a "Complex Modification" that maps __right__ command + hjkl to arrow keys. And then I added a "Simple Modification" that maps my left command to right command. It seems pretty hacky, but is working so far.

I'm not sure if this is the expected way to achieve this, but any feedback would be appreciated.

**Comment by nathanshelly** [comment]
I wanted the same Vi style arrow keys (Ctrl, Option and Cmd though with j/k/l/; in my case) and was able to achieve Cmd variants with these configurations [vi_arrows.txt](https://github.com/tekezo/Karabiner-Elements/files/1504548/vi_arrows.txt) . I used the general command modifier and didn't seem to run into the same left command issues you're mentioning so this may help but apologies if I'm suggesting something you've already tried. Here's an example of one of the remappings (the rest are in the txt file linked previously , also note that I disabled the shortcuts in iTerm but that's obviously optional):

{
    "description": "Cmd-J to Cmd-Left Arrow",
    "manipulators": [
        {
            "type": "basic",
            "from": {
                "key_code": "j",
                "modifiers": {
                    "mandatory": [ "command" ],
                    "optional": [ "shift" ]
                }
            },
            "to": [
                {
                    "key_code": "left_arrow",
                    "modifiers": [ "command" ]
                }
            ],
            "conditions": [
                {
                    "type": "frontmost_application_unless",
                    "bundle_identifiers": [ "com.googlecode.iterm2" ]
                }
            ]
        }
    ]
}
