### ISSUE TITLE
Unable to modify fn and menu key

### ISSUE THREAD

**Issue by Joilence** [tekezo/Karabiner-Elements#1136]
macOS 10.13.1
Karabiner 11.3.0
Keyboard: Logitech G Pro

My keyboard is 87-key, with `fn` and `menu` key in the left of arrow key.

![img_4408](https://user-images.githubusercontent.com/14588641/33052823-a0e31a6c-ceab-11e7-9f9c-7dc233998747.JPG)

I'm planning on modifying `fn/menu/right-ctrl/right/shift` to `left/down/right/up arrow`, but find it unable to modify `fn` and `menu` key, what should I do?

Thanks.

**Comment by nguyenhimself** [comment]
You can't remap non-Apple FN keys.

#999

**Comment by marcschulder** [comment]
Unlike the FN key, the menu key can be mapped. Use Karabiner-EventViewer.app to easily check which key name it has. For me it was `application`, rather than `menu`.
