### ISSUE TITLE
FN functions does not work Sierra High with control strip 

### ISSUE THREAD

**Issue by sklepdla** [tekezo/Karabiner-Elements#1139]
there is no option to use FN keys in Sierra HIGH with keyboard with control strip

**Comment by brunoedig** [comment]
Same as here: https://github.com/tekezo/Karabiner-Elements/issues/983

Still happening unfortunately :(

**Comment by zbstof** [comment]
I had this before I updated to High Sierra. So this happens on Mac OS Sierra also.

**Comment by wende** [comment]
Same problem here

**Comment by guitarman** [comment]
I have the same problem as well
