### ISSUE TITLE
no longer working after the last two updates on hackintosh with Drevo keyboard

### ISSUE THREAD

**Issue by JetPorkins** [tekezo/Karabiner-Elements#1140]
was working perfectly before the last two updates, but now it seems that karabiner reads the keys that are set to numpad (7890UIOPJKL;M,./)as numpads by default instead of what it was in the past). Which in theory would be alright, but the 00 (, key) cant be programmed as the list cant see 00 as a key.

**Comment by michalchmura** [comment]
I'm having the same problem, can this be revisited please?
