### ISSUE TITLE
Trying to make app-switch keys, but app switcher closes when pressing/releasing shift

### ISSUE THREAD

**Issue by JarrettBillingsley** [tekezo/Karabiner-Elements#1143]
I want alt+tab to switch apps, and alt+shift+tab to switch in reverse. Basically, just replacing cmd with alt. I've added the following to my `karabiner.json`:

```
"manipulators": [
    {
        "from": {
            "key_code": "tab",
            "modifiers": {
                "mandatory": [
                    "left_option"
                ]
            }
        },
        "to": [
            {
                "key_code": "tab",
                "modifiers": ["left_command"]
            }
        ],
        "type": "basic"
    },
    {
        "from": {
            "key_code": "tab",
            "modifiers": {
                "mandatory": [
                    "left_option",
                    "shift"
                ]
            }
        },
        "to": [
            {
                "key_code": "tab",
                "modifiers": ["left_command", "shift"]
            }
        ],
        "type": "basic"
    }
]   
```

It works, kinda. But there's a really major problem with it.

Try switching apps with Cmd+Tab. While still holding Cmd, press shift and press tab again to switch in reverse. Importantly, **the switcher will not disappear until you release Cmd.**

But with this modification, if I press Alt+Tab, and then press shift, **the switcher disappears as if I had let go of Alt (well, Cmd).**

I guess KE is sending a keyup, but I don't want it to. How can I avoid this? Is it possible?

**Comment by JarrettBillingsley** [comment]
Sorry to "bump" but is there any way to do this? I'm under the impression karabiner has some kind of variable system; maybe that can be used? I just don't know where to find documentation on this stuff.

**Comment by aerobounce** [comment]
I was in the same situation. The `key` is the command key. Declare like below:

```
                                "from": {
                                    "key_code": "tab"
                                },
                                "to": [
                                    {
                                        "key_code": "tab",
                                        "modifiers": ["left_command"]
                                    },
                                    {
                                        "key_code": "left_command"
                                    }
```

Invoke `Cmd+Tab` firstly, then press `Cmd` again. Voila.

**Comment by aqilc** [comment]
this is solved by to_if_pressed or something, here you go: https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to-if-other-key-pressed/
