### ISSUE TITLE
Possible to operate conditionally on overlay (e.g. Contexts, Alfred, etc.)?

### ISSUE THREAD

**Issue by nathanshelly** [tekezo/Karabiner-Elements#1144]
I'd love to be able to disable several keyboard shortcuts while in the Contexts and Alfred overlays. Using EventViewer I can get the bundle identifiers for both apps when I'm working in their settings windows but the overlays themselves don't seem to count as the foremost app. The foremost app appears to be whatever application was active before triggering either overlay. If I disable a keyboard shortcut in say iTerm, switch to iTerm and then activate Alfred or Contexts it leaves the shortcut disabled as iTerm is still counted as the frontmost application.

Is disabling these keyboard shortcuts in overlays possible? Don't even know if the overlays give any indication or set any flags that would make this possible so sorry if I'm wasting time asking for an impossible feature.

**Comment by chikko80** [comment]
2023 and i'd still like to see this 😁

**Comment by kfirfer** [comment]
Would like to see some support on that since its conflicting the foremost applications hotkeys

**Comment by kfirfer** [comment]
How do I reopen ?

**Comment by eeshankeni** [comment]
This is the reason I cant copy paste on overlays on cursor ide :/
