### ISSUE TITLE
Multi-touch extension, trackpad + F/D

### ISSUE THREAD

**Issue by tch399** [tekezo/Karabiner-Elements#1146]
Was the multi-touch functionality specifically, trackpad + F/D, ever solved by karabiner or any other method on mac os sierra?

**Comment by yijia-zhan** [comment]
Any updates on this?

**Comment by cocoahuke** [comment]
@tch399 
@yijia-zhan 

Everyone check out my work! Should be suitable for "multi-touch extension" replacement!
https://github.com/cocoahuke/shrink_trackpad
