### ISSUE TITLE
Can anyone explain something in touchcursor mode to me?

### ISSUE THREAD

**Issue by lwalton-turnto** [tekezo/Karabiner-Elements#1153]
@jeeback or anyone willing to help, 

I'm looking to make my own variation of TouchCursor mode. 
I'm wondering what is the purpose (i.e. why is it necessary) to define all the other keys that you don't want to have as special functioning while holding down spacebar as something like this: 

```
       {
          "type": "basic",
          "from": {
            "key_code": "7",
            "modifiers": {
              "optional": [
                "caps_lock"
              ]
            }
          },
          "to": [
            {
              "key_code": "spacebar"
            },
            {
              "key_code": "7"
            },
            {
              "key_code": "vk_none"
            }
          ],
          "conditions": [
            {
              "type": "variable_if",
              "name": "touchcursor_mode",
              "value": 1
            }
          ]
        }
```

So my guess is "if I hit the 7 while already holding down the spacebar then emit a spacebar and a 7" Not sure what the vk_none does in this case.  And what if it didn't have all those rules?  What happens  then if I hit 7 while space is down? Are these just to help with some timing issue?

Next, I've seen https://pqrs-org.github.io/KE-complex_modifications/json/personal_jeebak.json  but the instruction with it confuses me a little:  It says "use with Change caps_lock to control if pressed with other keys, to escape if pressed alone."  My guess is that it has something to do with whether you want to be able to just hit the spacebar once and let go as in indicator that you want to be in this "mode" until you press space alone again.    But I feel like I'm missing some connection.  Can someone elaborate more what is different if you "use with Change caps_lock to control" or "use Change caps_lock to escape" or if I don't do either?  I was planning on using caps_lock as a hyper key for Ctrl-Cmd-Shift-Opt.   And what I want is to have the special touchcursor functionality ONLY when I am holding down spacebar.  

Finally, what I currently have in Karabiner allows me to do spacebar + s + j/h/k/l etc so the s indicates I also want shift on for selecting.  

I have my private.xml rules based similar to https://gist.github.com/jeebak/92dcbe61527683b92c84 where there is a rule for  

<autogen>__KeyToKey__ KeyCode::E, KeyCode::SHIFT_L</autogen>
in the mytouchcursor stuff.  

I'm assuming that the equivalent now in personal_jeebak.json is :
```
       {
          "type": "basic",
          "from": {
            "key_code": "r",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "vk_none"
            },
            {
              "key_code": "left_shift"
            }
          ],
          "conditions": [
            {
              "type": "variable_if",
              "name": "touchcursor_extended_mode",
              "value": 1
            }
          ]
        }
```
so if I want s to be my shift character for selecting while doing space+jkhl  then I'd just change the r to and s? 

Thanks for all clarifications and sorry to be such a noob. 

Lynn

**Comment by jeebak** [comment]
I didn't get a notification due to the typo in my username (no _"c"_.) I only found this issue when I was google-ing for more/better TouchCursor implementations myself :). 

You should close this issue, check out the actual source for those configs under:
https://github.com/pqrs-org/KE-complex_modifications
and if you still have questions, post questions there.

Good luck!

**Comment by lwalton-turnto** [comment]
Merry Christmas, if Christmas is a holiday you observe.  Either way, I hope
you are well.

I was wondering because I am just too busy to do this myself, if there was
any chance you would take my karabiner private.xml and make a corresponding
karabiner-elements json file (with as much functionality as is possible for
KE) for me for a fee?

I'll attach the xml file here.  If you would be willing, please let me know
how much you'd like to be paid.  I could do it via paypal or however else
you'd like.


Thanks for your consideration,

Lynn
