### ISSUE TITLE
longpress a key to launch apps?

### ISSUE THREAD

**Issue by Jimmy34742** [tekezo/Karabiner-Elements#1157]
I'm looking for a way to, for example, launch Safari by pressing and holding the 's' key. When the 's' key is tapped, it would just type 's' with no side effects. I have not hit on a combination that will do this, so can anyone advise? 

For example, I have used the 's' key as a way to enter a layer of key combinations that will run a shell_command to launch a designated app depending on what key follows the 's'. But to run a shell_command without typing anything after that 's' means that, once the s_pressed condition is fulfilled,  I want to execute a "to": without it requiring a preceding "from":. Is there some kind of null "from": I can use there to have the longpressed 's' just run the shell_command and not leave a typed letter 's' behind at some point?

**Comment by alexey-danilov** [comment]
this is the option from previous version I dearly miss... if fact, because of it's unavailability I still use El Capitan and old Karabiner, lol

**Comment by Jimmy34742** [comment]
https://pqrs.org/osx/karabiner/json.html#to-if-held-down

lol
