### ISSUE TITLE
How to follow open issues? How to help the project?

### ISSUE THREAD

**Issue by e-gaulue** [tekezo/Karabiner-Elements#1158]
Hi community,

I follow this project for a while. I just think we could help the project by sorting issues with labels like https://github.com/tekezo/Karabiner-Elements/labels, but we could add more like 'to confirm', 'confirmed', 'handled'...

Example: non_us_backslash appears in 45 issues. Maybe lots of them could be merged.

Do we need specific rights to do that? Who is ready to help in this way? I've you other ideas of what we could do to help?

**Comment by dixius99** [comment]
I'd also say that a lot of the issues maybe aren't really issues (e.g. problems with the code, expected behaviour didn't happen), but rather people asking for help to accomplish something with app that it already does. Not sure if that matters.

**Comment by drwl** [comment]
There are labels that could help tag the different issues. I believe permissions are needed to do that.

**Comment by e-gaulue** [comment]
Yes, that's what I think. We use 'issues' as a mailing list. It's a 90's 
tool known to work. Here, it's even a little bit better as you can close 
your own issues...

But yes, github offers more. I've never administered a github project, 
so I don't know how far you can grant access specific tools as labelling 
issues. Maybe it's not so easy, just like: on/off.

Anybody that knows and could advise us is welcome.


Le 18/12/2017 à 22:57, Andrew W. Lee a écrit :
