### ISSUE TITLE
cannot get it to work with pc keyboard

### ISSUE THREAD

**Issue by avalla** [tekezo/Karabiner-Elements#116]
It looks like the combinations aren't working.

I did:
- uninstall karabiner
- install karabiner-elements
- start karabiner-elements
- add configuration file
- quit from karabiner-elements
- start karabiner-elements

but the keys are not modified :(

```
$ cat ~/.karabiner.d/configuration/karabiner.json
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
        "caps_lock": "delete",
                "keypad_comma": "dot",
                "right_command": "right_option",
                "right_option": "right_command",
                "keypad_enter": "return"
            }
        }
    ]
}
```

**Comment by adexbn** [comment]
Me too，after upgraded to 0.98，cannot use now

**Comment by avalla** [comment]
I did what @talha131 said to do in #77 and now everything works

> I would uninstall Karabiner-Elements. Remove ~/.karabiner.d folder. Restart system. Install Karabiner-Elements again.
