### ISSUE TITLE
Modifier keys (Cmd, Option / Alt, Shift) aren't registered when used in combination with function keys

### ISSUE THREAD

**Issue by zimmermatt** [tekezo/Karabiner-Elements#1160]
When using IntelliJ IDEA and the built in keyboard, modifier keys aren't registered when used in combination with function keys. I have set the MacOS System Preference to always show function keys when using IntelliJ (System Preferences > Keyboard > Shortcuts > Function Keys).

However, when I attach my external keyboard (a Kinesis Advantage), the modifier keys register and the corresponding feature is activated (e.g., `find usages` on a method).

Many useful keyboard shortcuts make use of modifier keys + function keys, so this severely degrades use.  I've tried this with my custom in addition to with the default `karabiner.json` and it occurs with both.

One way this can be observed is to:
* open the App settings (`Cmd ,`),
* type `keymap`
* click the icon to the right of the search box in the keymap area also on the right to open the `Find Actions by Shortcut`
* Press `cmd`, `option`, or `shift` (or even all three together) + a `function key`
* observe that only the function key shows

Modifier keys in combination with other keys work correctly.

Environment:
* Karabiner Elements 11.3.0
* MacBook Pro with Touchbar
* MacOS Sierra
* IntelliJ 2017.3 Ultimate Edition (though I imagine this will occur with the Community Edition as well)

**Comment by Jeetah** [comment]
I have the same issue - using Eclipe :-)
I tried also to fiddle around with the function keys setting - without any success. Only closing of Karabiner helps to use combinations like ALt+F7. It also doesn't matter which keyboard layout is selected in Karabiner or macOS. 
I have a touchbar - perhaps there is an issue in combination with it?

**Comment by githorse** [comment]
Same here. I can confirm Karabiner is causing the issue. Can't decide which is worse -- living without IntelliJ shortcuts or living without Karabiner shortcuts :(

**Comment by issei-m** [comment]
Same here

**Comment by MyDogTom** [comment]
Same for me. Worked well on MacBook without touch bar. But on MacBook with touch bar modifiers keys are ignored.

**Comment by MyDogTom** [comment]
Ok, after investigating, I've found two ways to fix that.
Fix 1.  enable unknown device
<img width="1112" alt="screen shot 2018-04-20 at 20 22 53" src="https://user-images.githubusercontent.com/5940462/39067467-0a0cbb6c-44d9-11e8-9460-305946b4b60b.png">

Fix 2. (or rather workaround) map function key to number
https://pqrs.org/osx/karabiner/help.html#touch-bar-function-keys

@zimmermatt Does that works for you as well?

**Comment by zimmermatt** [comment]
Nice!  Thanks for digging in @MyDogTom!

Fix 1 works for me.

Fix 2 didn't. I had the config to always show function keys set. I turned that off and tried again with no luck.

**Comment by zimmermatt** [comment]
touch 1160

to keep it open...

**Comment by geowyn** [comment]
In my case enabling the unknown device did not solve, but then I noticed the setting "Use Fn keys as standard function keys was enabled" and when I disabled that, all was good.

**Comment by nils-tekampe** [comment]
Fix #1 worked for me.

**Comment by b-hayes** [comment]
Really annoying. Like how they just close issues because there's nothing more to say about it.

It's still broken. Wish by default it just leave the fkeys alone and just only do what its told.

**Comment by cakraww** [comment]
Fix 1 from @MyDogTom works for me, after quit & reopen Karabiner Elements.

**Comment by bigunyak** [comment]
Fix 1 doesn't work in an apps where you chose to have functional keys in the Touch Bar by default. This is super annoying and is not a proper fix. This issue should really be re-opened!

**Comment by Bonemeijer** [comment]
Only thing that "works" for me is to "User all F1, F2, etc. keys as standard function keys" 
But then I lose the default mac shortcuts like brightness, volume etc. 

The moment I close karabiner, the function keys work exactly like expected. I can change volume, and when I press shift+F6 for example, intellij editors recognize it as a regular shift+F6 press.

**Comment by VVakko** [comment]
> Fix 1. enable unknown device <img alt="screen shot 2018-04-20 at 20 22 53" width="1112" src="https://user-images.githubusercontent.com/5940462/39067467-0a0cbb6c-44d9-11e8-9460-305946b4b60b.png">
> 
Thank you, very much!
