### ISSUE TITLE
Space to Shift_L lag when using Space alone

### ISSUE THREAD

**Issue by ruslaniv** [tekezo/Karabiner-Elements#1161]
When using the builtin "Space" to "Shift_L" remapping I noticed a delay when using this modification. 

When I use spacebar as just a spacebar without pressing any other key there is a very slight but still noticeable delay before producing a whitespace. So when I type fast there could be a few cases where pressing a spacebar and then a key would register as pressing a spacebar together with the key producing a capital letter.

Is it possible to investigate the issue?

**Comment by drwl** [comment]
Have you tried changing the basic parameters in Preferences > Complex Modifications > Parameters.

Play around with both, but I would guess it has to do with `to_if_alone_timeout_miliseconds`.

**Comment by tpj2018** [comment]
Ive tried all settings but spacelauncher is the only one with proper settings to make this work for fast typing types : )
<img width="518" alt="screenshot 2017-12-30 15 37 20" src="https://user-images.githubusercontent.com/34492742/34455074-5d4bd6b4-ed77-11e7-8666-b190197463bc.png">
