### ISSUE TITLE
Keyboard sleep/power button not detected

### ISSUE THREAD

**Issue by JohnClay** [tekezo/Karabiner-Elements#1162]
Hello,

I'm trying to use Karabiner to intercept the power/sleep button on my Das Keyboard. I can set the override for the "power" button in settings under "Keys in PC keyboards", but it doesn't work and the OS still handles the button.

Any suggestions?

I'm on 10.13.2, and Karabiner 11.4.0.

Thanks!

**Comment by nguyenhimself** [comment]
Open Karabiner-EventViewer, press the Power button, see if any keypress event shows up.
If there's nothing, then you cannot remap it. It's tightly paired with the hardware, like the Fn key.

**Comment by JohnClay** [comment]
@nguyenhimself 

It is detected, but Karabiner just doesn't interact with it. It does work with USB Overdrive, and PowerKey. Anyway, I was able to get the behaviour I wanted with PowerKey, which I found in another issue on GitHub.

**Comment by sephie** [comment]
Have the same issue where CTRL-SHIFT-Eject on my Apple USB keyboard no longer works. The key does register, so my question is:

Why should Karabiner negate this key?
From what I'm experiencing it should allow the sleep shortcut to work normally.

**Comment by tekezo** [comment]
Please use this workaround.
https://pqrs.org/osx/karabiner/help.html#control-eject

**Comment by hez** [comment]
This still seems to be an issue, any ideas why it is doing this?

**Comment by linguica** [comment]
I have also tried to remap the power key on my Das Keyboard without success. Is it possible for Karabiner to interact with it? It's unclear from the comments above.

**Comment by felipepsq** [comment]
Faced a similar issue when trying to remap the power button from an external wireless keyboard. I noticed that in the EventViewer the key was being logged as `{"consumer_key_code":"power"}`, and in the Simple Modifications section there was only one "power" option (then it's probably assigning to `key_code`).

I open the karabiner.json file and found out the power key was assigned as `"key_code": "power"`. Just reassigned it to `"consumer_key_code": "power"` and now it is working fine.
