### ISSUE TITLE
Incremental volume adjustments don't work with one of latest updates

### ISSUE THREAD

**Issue by omacranger** [tekezo/Karabiner-Elements#1163]
It looks like the incremental volume adjustment no longer works with one of the latest updates (to either macOS or Karabiner). If I quit Karabiner, holding down shift+option and adjusting volume will change it in small increments (approximately 1/4 the standard volume amount). If karabiner is running (even with the modifiers disabled for the specific input device I'm testing on) then the volume will only adjust in full increments.

**Comment by MindTooth** [comment]
I just noticed the same.  Why did you close?

**Comment by omacranger** [comment]
@MindTooth Something external toggled the 'Disable Windows Key' modifier on my Logitech keyboard. Though disabling karabiner somehow resolved it [originally], toggling that back off fixed the problem for me.

**Comment by MindTooth** [comment]
Hmm.. Not sure what that can be at the moment.  Only modification I've done I belive is using Karabiner to change caps to ctrl/esc and right command/jkli-arrows.

Thank you for replying my post.
