### ISSUE TITLE
Rule Priority ???

### ISSUE THREAD

**Issue by rivaros** [tekezo/Karabiner-Elements#1164]
Is there anything in help how rule priority is working ???
The only thing that can be found in help is ```complex_modifications manipulator priority```,
which explains how modifications work within a rule.

**Comment by tekezo** [comment]
Basically, there are the following rules.
https://pqrs.org/osx/karabiner/document.html#event-modification-chaining
https://pqrs.org/osx/karabiner/json.html#complex_modifications-manipulator-priority
