### ISSUE TITLE
Feature Request: command line to switch profile

### ISSUE THREAD

**Issue by holymonson** [tekezo/Karabiner-Elements#1165]
Karabiner-Elements allows several profiles, but it needs to switch manually. If it can provide a command to switch profile, then it can be great useful to co-operate with scripts or other applications like ControlPlane or Alfred.

**Comment by nguyenhimself** [comment]
You can do that now. The CLI is inside the .app bundle.
For ex, to trigger the profile named "Leopold FC660M":

`/Library/Application\ Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli --select-profile "Leopold FC660M"
`

**Comment by holymonson** [comment]
Thanks @nguyenhimself , found it.

But it's strange placed in `/Library/Application Support` because it should contain files deletable, not part of the App. Compared with other apps (`Atom.app` `Sublime Text.app` `Visual Studio Code.app`), placing the CLI in `/Applications/Karabiner-Elements.app/Contents/MacOS/bin` or `/Applications/Karabiner-Elements.app/Contents/Resources/app/bin` may be a better idea, IMHO.
