### ISSUE TITLE
Changing scroll speed or scroll behaviour in some apps

### ISSUE THREAD

**Issue by pablomedok** [tekezo/Karabiner-Elements#1168]
I use Karabiner Elements to make my Mac behave the same way as Windows in Parallels Desktop and Remote Desktops. And it works almost like I want to. I use Parallels Desktop to run CorelDraw, mostly. 

The only thing that drives me crazy is Magiс Mouse scrolling behaviour in CorelDraw. A small movement of a finger could end up in 1000x zoom out. Such [small finger movement](https://cl.ly/2N2H0z2s0y2z) in Safari, would work in such [crazy way in CorelDraw](https://cl.ly/1j0Z1o0l012g). Sometimes it's even worse. Just clicking a button would end up to maximum zoom. Sometimes it happens when my left finger is even not on the mouse. And it happens dozens times a day.

I have to iMaсs: one old with Magic Mouse, and one new with Magic Mouse 2. They both have the same problem. 

I tried to change Parallels' mouse modes, Virtual Machine's (disabled momentum scrolling), Windows' settings (minimum number of lines to scroll), but nothing changes - looks like CorelDraw works with the mouse directly - in its own way. I could switch from zooming to panning in CorelDraw, it's a bit better, but not great anyway - accidental scrolls still ruin normal workflow. 

Maybe there's a way to:
a) disable mouse scrolling momentum in PD or in CorelDraw;
b) change scrolling speed in these apps;
c) disable mouse scrolling completely in these apps;

I tried, but I could't figure out 'From event' to use. Neither «mouse_key - ScrollWheel», nor «pointing_button - ScrollWheel» worked. 

Please, help

**Comment by tekezo** [comment]
Unfortunately, Karabiner-Elements cannot modify Apple's pointing device events.
Please use another app for this purpose.

**Comment by drwl** [comment]
@pablomedok It looks like your issue was addressed. If you agree, would you mind taking a moment to close it?
