### ISSUE TITLE
Pass through modifiers (fn, option, command, shift, caps)

### ISSUE THREAD

**Issue by rivaros** [tekezo/Karabiner-Elements#1169]
Currently, if one of manipulators does match, all next manipulators do not execute.
It's good to prevent cycles, but makes it impossible to realizing some typical keymap scenarios.

For example:
1.) I need that Ctrl-Shift combination trigger language switch (Cmd-Spacebar).
2.) Simultaneousy I still need combinations like Ctrl+Shift+F work as before.

Example of my manipulator:

```json
                            {
                                "from": {
                                    "key_code": "left_shift",
                                    "modifiers": {
                                        "mandatory": [
                                            "left_control"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "left_shift",
                                        "modifiers": [
                                            "left_control"
                                        ],
                                        "lazy": true
                                    }
                                ],
                                "to_if_alone": [
                                    {
                                        "key_code": "spacebar",
                                        "modifiers": [
                                            "left_command"
                                        ]
                                    }
                                ],
                                "type": "basic"
                            }
```

Here are the 2 problems:
1. As soon as "from" is matched (left_control + left_shift pressed), system does not track any further key presses (for example left_control+left_shift+f will never be tracked).

In my opinion 'from' clauses which contain modifier in "key_code" should propagate down to the system.

2. I use "to_if_alone" here which means that left_command+spacebar will be triggered only if left_shift is pressed alone. Strangely enough it is triggered when left_shift is released (which makes the effect of ctrl-shift in Windows).

**Comment by deitrix** [comment]
This is a good idea that just caught me. I'd love to know if you figured out how to achieve this.
