### ISSUE TITLE
Fast input source switching is broken

### ISSUE THREAD

**Issue by talha131** [tekezo/Karabiner-Elements#117]
OS X 10.12.1 Beta (16B2327e)
Karabiner-Elements 0.90.38

I cannot use my shortcut ⌃Control+⌥Option (alt)+Space to switch input source.
Long pressing the shortcut, just shows US language keyboard. 

Related to #41 and #42

**Comment by noma4i** [comment]
I can recommend to use my hack #33

**Comment by talha131** [comment]
I just switched to the default ⌃Control+Space shortcut and switcher started to work fine.
