### ISSUE TITLE
How can I convert old private.xml code ?

### ISSUE THREAD

**Issue by Sharcoux** [tekezo/Karabiner-Elements#1170]
Hi,

I am trying to make [this example](https://superuser.com/questions/307048/making-the-backspace-key-go-to-the-previous-folder-in-finder) to work (the selected answer), but I can't find the private.xml file. I belive that it has been removed from most recent version.

What should I do to get this code to work?

Thanks!

**Comment by asfaltboy** [comment]
I'd also like to know that.. or at least a list of identifier mappings ... for example I'm trying to get the ol' ["show_desktop" remap][1] to work, but cannot find a proper method.. here's my futile attempt from piecing together examples and from the "complex modifications" docs:

```json
{
    "title": "F9 to show desktop",
    "rules": [
                {
                    "description":"F9 to Show Desktop",
                    "manipulators": [
                        {
                            "type": "basic",
                            "from": {
                                "key_code": "f1",
                                "modifiers": {
                                    "mandatory": [
                                        "fn"
                                    ]
                                }
                            },
                            "to": [
                                {
                                    "key_code":"show_desktop"
                                }
                            ]
                        }
                    ]
                }
            ]
}
```

[1]: https://superuser.com/a/807191/56789

**Comment by prohtex** [comment]
What a mess

**Comment by durka** [comment]
See #1332 for a start.
