### ISSUE TITLE
Current key to use for complex modification on Mac French keyboard

### ISSUE THREAD

**Issue by e-gaulue** [tekezo/Karabiner-Elements#1172]
Configuration
- OSX Version : 10.13.2
- Karabiner-Elements : 11.4.0
- French Keyboard :         
        "manufacturer": "Apple Inc.",
        "product": "Apple Keyboard",
        "product_id": 592,
        "transport": "USB",
        "vendor_id": 1452
- Virtual Keyboard set to be in ISO

With Karabiner-Elements running without any rules:
- `non_us_backslash` works as expected and is reported as is in the EventViewer 
- `backslash` works as expected and is reported as is in the EventViewer

When writing Complex Modifications:
- `grave_accent_and_tilde` needs to be use instead of `non_us_backslash`
- `non_us_pound` needs to be use instead of `backslash`

Regards,

**Comment by lebigot** [comment]
Is this solved now? I did have problems with these two keys with your very helpful configuration file at https://pqrs.org/osx/karabiner/complex_modifications/#international, that may be linked to this issue because actually fixed.

**Comment by e-gaulue** [comment]
Sorry for the delay (one year). I don't think so. At least, it works for me still using those modifiers. Maybe the behaviour is not the same with integrated keyboard like on MacBook and external keyboard, like usb ones. Or maybe, it as been solved but to deal with previous configuration files, it accepts them anyway.

I'll give it a look when I'll have time, so when I'll be stuck.
