### ISSUE TITLE
Is there a way to disable Function Keys by application?

### ISSUE THREAD

**Issue by e-gaulue** [tekezo/Karabiner-Elements#1174]
Hi community,

Does anyone know if it's possible to disable the Function Keys (like the checkbox at the bottom of the `Function Keys` tab) but for a specific application through the configuration?

I'm working on a keyboard configuration for use with Microsoft Remote Desktop. On Windows those keys have another meaning and it would help.

Regards,

**Comment by drwl** [comment]
I don't have the answer to your question but I suggest taking a look at #1109 and see if it provides any insight to what you're trying to achieve.

**Comment by e-gaulue** [comment]
As far as I can understand in this documentation https://pqrs.org/osx/karabiner/json.html#root-data-structure, it's not possible to set rules in the "fn_function_keys" section. I've tried it anyway and my json was not recognise.

I can of course disable all function keys all the time, but it's not what I'm looking for. Thanks anyway.

I think it's a feature request, but it's not a priority yet. Lots are waiting for improvement around the dynamic Touch Bar.

**Comment by divieira** [comment]
In case someone else lands here in the future looking for a similar solution, this extension solves what I needed:
https://ke-complex-modifications.pqrs.org/#function_keys
