### ISSUE TITLE
"left_shift" to "Option+space" does not work in Karabiner-Elements 11.4 

### ISSUE THREAD

**Issue by toinfty** [tekezo/Karabiner-Elements#1175]
I was using Karabiner-Elements beta version (11.3) on macOS High Sierra (10.13.2). I had the following piece of configuration in my `karabiner.json` file:

```json
{
    "description": "Change left_shift to option+space when used alone",
    "manipulators": [
        {
            "from": {
                "key_code": "left_shift",
                "modifiers": {
                    "optional": [
                        "any"
                    ]
                }
            },
            "to": [
                {
                    "key_code": "left_shift"
                }
            ],
            "to_if_alone": [
                {
                    "key_code": "spacebar",
                    "modifiers": [
                        "left_option"
                    ]
                }
            ],
            "type": "basic"
        }
    ]
}
```
This configuration was working normally in 11.3. However, it does not work in 11.4. In version 11.4, I check the key events in the key viewer and find that pressing `left_shift` only gives me `left_option`.

Is there any regression in 11.4? Do I have to update my configuration?

**Comment by CrispinLin** [comment]
Same problem with the "key_code": "spacebar" in new version. I'm changing capslock to left_command + space but it only gives left_command. But in my case modifying into option+space and ctrl+space is working fine.

**Comment by toinfty** [comment]
Thanks for confirming this issue!

I will keep using Karabiner-Elements version 11.3 until this issue is solved.

**Comment by tekezo** [comment]
I think it's not Karabiner-Elements issue.

These shortcuts are not shown in EventViewer due to it's limitation.
https://pqrs.org/osx/karabiner/document.html#eventviewer-limitation

I think you confirmed this issue as a function you assigned to option+space is not called.
Maybe, it's a issue of macOS.
Does restart your system solve the problem?

**Comment by toinfty** [comment]
@tekezo Thanks! I followed your advice and restarted my computer to test the above configuration on both Karabiner 11.4.1 and 11.3.

Yes, you are right about the EventViewer, both versions record the same keyboard events as follows when I pressed `left_shift`: 
```
eventType:FlagsChanged    code:0x38       name:left_shift      flags:Shift                              misc:
eventType:FlagsChanged    code:0x38       name:left_shift      flags:                                   misc:
eventType:FlagsChanged    code:0x3a       name:left_option     flags:Opt                                misc:
eventType:FlagsChanged    code:0x3a       name:left_option     flags:                                   misc:

```
What I want to achieve is described in the following:
In the Keyboard section of macOS System preference, I have assigned the shortcut `option+spacebar` to cycle through the two input methods (English/Chinese). I was able to press a single `left_shift` to change the input method using the `"Change left_shift to option+space when used alone"` configuration in above in version 11.3. 

But the same configuration does not work in version 11.4 and in the beta version 11.4.1. I also try to vary the `basic.to_if_alone_timeout_milliseconds` from 100 to 1000 in 11.4. However, it does not change the behaviour of a single `left_shift` press.

Luckily, the version 11.3 works fine for me. So are there any important code change in 11.4 that might make my configuration invalid?

**Comment by nguyenhimself** [comment]
I found a bug here, but not what you meant:

Your original snippet did work for me in 11.4.0. Prior to this,I already mapped Option + Spacebar to trigger Alfred, and that's what it did: Pressing Shift alone launched Alfred, even though EventViewer didn't show the Spacebar being pressed.

**Comment by toinfty** [comment]
@nguyenhimself Ok, so this means the mapping from "left_shift" to "Option+space" works for Alfred in 11.4. But the mapped "Option+space" does not change the input method in 11.4. 

I am reading the document at the link https://pqrs.org/osx/karabiner/json.html, trying to find a new way to switch the input sources with a single press of left_shift.

**Comment by tekezo** [comment]
Thank you for the detail!
I can confirm the issue and it is caused by a change that reduced waits around modifier key events.

I fixed this issue at v11.4.3. Please confirm the latest beta version.
![Check for beta updates](https://pqrs.org/osx/karabiner/img/karabiner-elements-check-for-updates-beta@2x.png)

**Comment by CrispinLin** [comment]
Just tried out v11.4.3, everything's working again.
@tekezo Thanks for the quick fix & keep up the good work!

**Comment by toinfty** [comment]
My configuration works again in version 11.4.3. Thanks very much!
