### ISSUE TITLE
disable power key

### ISSUE THREAD

**Issue by benng127** [tekezo/Karabiner-Elements#1177]
I'm not a programmer and I know nothing about programming. All I want is to disable the damn Macbook power button. Can anyone help me create a rule so I can import it? It is so frustrating that I cannot create a rule locally.

**Comment by nguyenhimself** [comment]
Nope, you can't. The Power button coupled tightly with the hardware and cannot be remapped.

**Comment by FE-Sakamoto** [comment]
defaults write com.apple.loginwindow DisableScreenLockImmediate -bool yes
