### ISSUE TITLE
How to actually create a complex modification

### ISSUE THREAD

**Issue by NataliePequeno** [tekezo/Karabiner-Elements#1178]
How exactly do you create a complex modification?

Im trying to remap shift+alt+ volume up to be just volume up instead. I want the smaller volume increments by default but the app won't let me create any modifications??

Thanks,
Natalie

**Comment by drwl** [comment]
@NataliePequeno would you mind clarifying what you're trying to achieve? I'm not sure what you mean by "smaller volume increments"
