### ISSUE TITLE
Change help + fn to right_control

### ISSUE THREAD

**Issue by weiweihuanghuang** [tekezo/Karabiner-Elements#1181]
I have a "Insert" key, for which the key code is:

```
eventType:KeyDown         code:0x72       name:help            flags:Fn                                 misc:
eventType:KeyUp           code:0x72       name:help            flags:Fn                                 misc:
```

I want to change this to right_option.

Making a `Simple Modification` doesn't work for changing `help` to `right_control`. It stays the same above.

I tried to make a complex modification that changes help+fn to right_control:

```
         {
            "description": "Change fn + help to right_option",
            "manipulators": [
                {
                    "type": "basic",
                    "from": {
                        "key_code": "help",
                        "modifiers": {
                            "mandatory": ["fn"]
                        }
                    },
                    "to": [
                        {
                          "key_code": "right_option"
                        } 
                    ]
                }
            ]
        },
```

Still doesn't work either. Advice is extremely appreciated.

(Much thanks for upgrading Karabiner to Karabiner Elements and doing so for free. I will be sure to make a donation)

**Comment by nguyenhimself** [comment]
> I have a "Insert" key

>Making a Simple Modification doesn't work for changing help to right_control. It stays the same above.

Apology if this seems obvious, but have you tried just remapping "Insert" to right_control?

**Comment by wviana** [comment]
Very interesting change. 
How does your keyboard looks like ?
Does it sends fn by itself or you will have to hold fn when trying to use this mapping ?

I've never though about using the menu key for anything, but now I see that it's in a interesting place for remapping. 

PS: English is not my first language, please feel free to help me with it. I would be thankful. 

PS2: I know its not about the issue, but reading your issue I thought I was interesting to advocate that [we should have a community](https://github.com/tekezo/Karabiner-Elements/issues/1186) for changing experiences of how we do use the software.

**Comment by Goofy22** [comment]
I have exactly the same issue trying to simulate paste with shift-insert. Happens on Logitech K520 from https://www.logitech.com/en-roeu/product/wireless-combo-mk520, as well as with an old multimedia Dell USB keyboard. Any advice appreciated.

Pressing Insert key:
eventType:KeyDown         code:0x72       name:help            flags:Fn                                 misc:
eventType:KeyUp           code:0x72       name:help            flags:Fn                                 misc:

**Comment by Goofy22** [comment]
Finally replacing "help" with "insert" without any "fn" worked for me:
```
				{
				  "from": {
						"key_code": "insert",
						"modifiers": { "mandatory": ["right_shift"], "optional": ["any"] }
				  },		  
				  "to": [{
						"key_code": "v",
						"modifiers": ["left_command"]
							}],						
				  "type": "basic"
				}
```

**Comment by weiweihuanghuang** [comment]
Thank you very much @Goofy22 that was the trick!
