### ISSUE TITLE
New to Karabiner Element: Key repeat or key delay?

### ISSUE THREAD

**Issue by jw6** [tekezo/Karabiner-Elements#1184]
Hi, I'm new to Karabiner Element and just switch from Karabiner after I updated my mac and using an external Windows Keyboard for a mac, I modified some keys simply such as command as option and option as command(can't find private.xml anymore), I'm not sure how to describe my problem(key repeat or key delay?), when I try command+s, I typed 's' on my text editor and command+tab and other keys combination also acting weird(key delay?)

**Comment by Hacci** [comment]
Add vk_none in the Complex Modifications.
It is a symptomatic treatment, however no repeat.
The easiest way is to modify the example of Dvorak layout .
Fine?
```
        {
          "type": "basic",
          "from": {
            "key_code": "s",
            "modifiers": {
              "optional": [
                "caps_lock",
                "left_command",
                "left_control",
                "left_option",
                "right_command",
                "right_control",
                "right_option"
              ]
            }
          },
          "to": [
            {
              "key_code": "s"
            },
            {
              "key_code": "vk_none"
            }
          ]
        },
```
