### ISSUE TITLE
We should have a community .

### ISSUE THREAD

**Issue by wviana** [tekezo/Karabiner-Elements#1186]
Hello,

I was wondering how good would be to have a community about Karabiner.

I think that something like a Forum or a Reddit would be nice to exchange tips and ways to improve the keyboard workflow of everyone and help the project to track better how to improve the software.

For example I would like to share with other that I use Vi mode 4.2, but the default keys for arrow bind was `s`  or `d`. How the Karabinder takes sometime to know that you are actually pressing and not holding a key. When using `d`, for exmple, I had a many times typed `cd<space_bar>` on terminal but was getting just `c`, cause it was thinking that I was trying to hold `d`.

So I tried with `s` key and got errors with some other things that I use to type, don't remember what to example.

What I've done was search a little, find where does Karabinder saves the downloaded plugins and copy the configurations for `d` key on Vi Mode and change all `d` for `z`. Now I have Vi mode 4.2 with `z`. That I'm not having problems with most of words that I write.

<img width="845" alt="screen shot 2017-12-23 at 9 04 25 am" src="https://user-images.githubusercontent.com/1062631/34319108-4ed8b3e8-e7c0-11e7-8cc9-e57921eff9e8.png">

Karabinder is allowing me to do things like this  [Tiny Keyboard Explanation](https://www.youtube.com/watch?v=AKGXZ1ReU54) on my full-size keyboard (Not actually full, I don't have the numeric keys).

So I think we could have a more active community about the goods of "hacking" the keyboard. Reddit has proven me that there is always a group of people interested in the most crazy things and usually more people than we thought was interested about that.

PS: English is not my first language, please feel free to correct me or suggest improvements. I'll be glad for the help and learning more about the language ("learning more about the language" feels weird, I probably should use "improve my writing" instead)

**Comment by Jimmy34742** [comment]
+1.

A forum with topic subscription, etc. would be most welcome and useful.

**Comment by wviana** [comment]
@Jimmy34742 what do you think about a subreddit ? After creating we could make a PR for adding it into this repo readme, than suggesting discussion to happen there and here just for real issues.

**Comment by tymofij** [comment]
There seem to be one: https://www.reddit.com/r/Karabiner/

**Comment by wviana** [comment]
Could we add a link to the repo readme ? What about suggest discussions in issues to be posted there?
