### ISSUE TITLE
Mouse keys (simple) (rev 1) request

### ISSUE THREAD

**Issue by tpj2018** [tekezo/Karabiner-Elements#1188]
How can i just map the scroll functionality to a button?
Or just left or right?

I wish i could customize this complex rule so it doesnt work with right shift but with another button.

Is there a easy way to edit the rule for a non programmer?

Thanks!

**Comment by jthedwalker** [comment]
The syntax is pretty easy to understand, even for a non-programmer. If you read the documentation [https://pqrs.org/osx/karabiner/json.html#typical-complex_modifications-examples](url), you should be able to make modifications to the template examples. Below is a excerpt from the Mouse Keys template. As you can see, it's mapping the "r" and "v" keys to scroll up and down ONLY if the right shift key is pressed. Hope that helps!

    {
        "title": "Mouse keys (simple) (rev 1)",
        "rules": [
            {
                "description": "Mouse keys (simple) (rev 1)",
                "manipulators": [
                    {
                        "type": "basic",
                        "from": {
                            "key_code": "r",
                            "modifiers": {
                                "mandatory": [
                                    "right_shift"
                                ]
                            }
                        },
                        "to": [
                            {
                                "mouse_key": {
                                    "vertical_wheel": -32
                                }
                            }
                        ]
                    },
                    {
                        "type": "basic",
                        "from": {
                            "key_code": "v",
                            "modifiers": {
                                "mandatory": [
                                    "right_shift"
                                ]
                            }
                        },
                        "to": [
                            {
                                "mouse_key": {
                                    "vertical_wheel": 32
                                }
                            }
                        ]
                    }
                ]
            }
        ]
    }

**Comment by tpj2018** [comment]
thank you! I do understand what you say but i find it hard to understand all the brackets.
What is the best way to edit the text? Is there a json editor app or should i use text edit like im doing now?
I find it hard to understand what brackets i should or should'nt delete to keep it working.

**Comment by jthedwalker** [comment]
I would download Visual Studio Code. [https://code.visualstudio.com/](url) It's a free text editor from Microsoft that has really nice autocomplete and syntax highlighting. You can change the language highlighting on the bottom right hand corner of the editor.
