### ISSUE TITLE
Caps lock LED flashes when focusing/unfocusing text fields

### ISSUE THREAD

**Issue by drifkin** [tekezo/Karabiner-Elements#1189]
Version: 11.4.0

If I focus a text field (either by clicking, or pressing tab, or changing to a window that has a text field active), my caps lock LED quickly flashes.

I remap my caps lock key using `to` and `to_if_alone`, so normally it just keeps the LED off.

I recently upgraded to High Sierra, and I don't think it was happening before that upgrade (it's definitely something that started recently though).

I looked through existing issues, and saw https://github.com/tekezo/Karabiner-Elements/issues/666, which looks similar

**Comment by drifkin** [comment]
I've also noticed that system password fields will show the "caps lock is on" indicator, even though it's not. I suspect this has the same root cause.

**Comment by drifkin** [comment]
As a workaround, since I don't ever use the caps lock for its original purpose, the LED stays off if I go to Keyboard preferences -> "Modifier Keys..." and set Caps Lock to "No Action".

**Comment by agnjkafgh** [comment]
Facing this exact same issue after upgrading Karabiner Elements to version 12.2.0 on my Mojave Macbook (10.14.2)
