### ISSUE TITLE
Simple Vi mode with the old flavour

### ISSUE THREAD

**Issue by visualskyrim** [tekezo/Karabiner-Elements#1193]
Hi, I noticed that [Simple Vi Mode](https://pqrs.org/osx/karabiner/complex_modifications/#vi_mode) is back and I'm pretty excited about.
But there a few differences between this *Vi Mode (rev 4.2)* and the old version that works only on the old OS X version.

For example, *Move to the start of the line* becomes to *Trigger Key + 4* from *Trigger Key + Cmd + H*, which is difficult for the people who set trigger key to *D*.(It would be event more difficult to select to the start of the line)

Also, the *Move the bottom* becomes to *Trigger Key + F + L* from *Trigger Key + Cmd + J*, which makes *Select from current to the end* extremely difficult.

There are some other differences that I came across, but most of them are ok for me. I think I just need to take time to get used to them.

But the two mentioned above seem to make it physically difficult for anyone, so I wonder if there is any possibility to bring the classic Simple Vi Mode back?

**Comment by ynyounuo** [comment]
Try this:
```
"modifiers": {
    "optional": [
        "any"
    ]
}
```

**Comment by apm1467** [comment]
Thank you for your feedback. The Vi Mode has been updated. Please give [Vi Mode (rev 4.3)](https://pqrs.org/osx/karabiner/complex_modifications/#vi_mode) a try.

**Comment by visualskyrim** [comment]
@apm1467 Thanks a lot! I've tried the new version rev 4.3, awesome work!
Now I have all the features I want! Thanks a lot!
