### ISSUE TITLE
Fn key on ThinkPad Keyboard not recognized in EventViewer

### ISSUE THREAD

**Issue by shalgrim** [tekezo/Karabiner-Elements#1196]
macOS version: 10.12.6
Karabiner version: 11.4.0
Your Mac hardware: MacBook Pro
Your keyboard hardware: ThinkPad Compact Bluetooth Keyboard with TrackPoint

The Fn key in the lower left of my keyboard doesn't get recognized by EventViewer. As a result, I can't use function keys on this keyboard and have to switch over to the Mac to use them.

**Comment by nguyenhimself** [comment]
https://github.com/tekezo/Karabiner-Elements/issues/999
