### ISSUE TITLE
[Enhancement] Disable trigger key for some seconds after your last typing.

### ISSUE THREAD

**Issue by Voleking** [tekezo/Karabiner-Elements#1197]
Currently I use `spacebar` as my Vi mode trigger key. However, `spacebar` doesn’t work very well when typing fast like other trigger key. 

In fact, the spacebar shouldn't be treated as trigger key when you type a space quickly after finishing a word.

So I wander if a parameters like `basic.to_if_last_type_milliseconds` which disable trigger key for some seconds after your last typing will be added in the future version.

**Comment by tpj2018** [comment]
I cannot use spacebar as a trigger with my current typing speed. I wish too there was a solution like this.

**Comment by Voleking** [comment]
Activate
