### ISSUE TITLE
Ń -> 1

### ISSUE THREAD

**Issue by GerasDraugas** [tekezo/Karabiner-Elements#1199]
Make:

            "name": "Default profile",
            "selected": true,
            "simple_modifications": [
                {
                    "from": {
                        "key_code": "Ń"
                    },
                    "to": {
                        "key_code": "1"
                    }
                }
            ],

but, this not work :(

**Comment by tekezo** [comment]
You can find properly key_code by EventViewer.
https://pqrs.org/osx/karabiner/document.html#eventviewer

**Comment by GerasDraugas** [comment]
There is a problem.

I'm getting "Ń" when pressing alt+1 on Lithuanian keyboard.
How to change "Ń" to "1"?

eventType:FlagsChanged code:0x3d name:right_option flags:Opt misc:
eventType:KeyDown code:0x12 name:1 flags:Opt misc:
eventType:KeyUp code:0x12 name:1 flags:Opt misc:
eventType:FlagsChanged code:0x3d name:right_option flags: misc:

**Comment by GerasDraugas** [comment]
[2018-01-06 00:29:33.913] [error] [grabber] unknown key_code: "Ń"
[2018-01-06 00:29:33.913] [info] [console_user_server] Load karabiner.json...
[2018-01-06 00:29:33.914] [info] [console_user_server] core_configuration is updated.
[2018-01-06 00:29:33.915] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:1) is ignored.
[2018-01-06 00:29:36.727] [info] [grabber] Load karabiner.json...
[2018-01-06 00:29:36.727] [info] [console_user_server] Load karabiner.json...
[2018-01-06 00:29:36.728] [info] [grabber] core_configuration is updated.
[2018-01-06 00:29:36.728] [error] [grabber] unknown key_code: "Ń"

**Comment by tekezo** [comment]
You should change option+1 like this:
https://pqrs.org/osx/karabiner/json.html#typical-complex_modifications-examples-change-control-h-to-delete

**Comment by GerasDraugas** [comment]
@tekezo I'm not so smart. Can you be more specific, please.

**Comment by michelkoga** [comment]
"name": "Default profile",
        "selected": true,
        "simple_modifications": [
            {
                "from": {
                    "key_code": "1",
                    "modifiers": {
                             "mandatory": [ "left_option"]
			}
                },
                "to": {
                    "key_code": "1"
                }
            }
        ],

**Comment by michelkoga** [comment]
Try this if you want to change option 1 to 1. If the option key is right, you may have to change left_option to right_option in the code above.
