### ISSUE TITLE
'fn' to 'left_control' mapping works only for builtin keyboard

### ISSUE THREAD

**Issue by richardstrnad** [tekezo/Karabiner-Elements#12]
This is my karabiner.json
``` json
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "fn": "left_control"
            }
        }
    ]
}
```
It works perfect for the builtin macbook pro keyboard, but not for the offical wireless mac keyboard...
Any ideas?

**Comment by billstclair** [comment]
I'm using it on the Apple Magic Keyboard, connected via Bluetooth to my iMac. Works good, except for eating shift or command with a mouse click, so I'm not using it until that is fixed.

**Comment by richardstrnad** [comment]
I use the 'classic' Apple Wireless Keyboard.
It's really strange, other key mappings work, it's just the 'fn' that makes trouble.
With this configuration the capslock work as backspace on both keyboards, but the 'fn' just work as control on the builtin keyboard.
``` json
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "fn": "left_control",
                "caps_lock": "delete_or_backspace"
            }
        }
    ]
}
```

**Comment by richardstrnad** [comment]
Issue was related to the Bluetooth 'Not available', all other keys worked on the Wireless Keyboard, but 'Fn' didn't. Did a SMC reset, now everything works as intended.
