### ISSUE TITLE
Weird bugs in some applications

### ISSUE THREAD

**Issue by leshik** [tekezo/Karabiner-Elements#120]
After enabling Karabiner Elements, even with no config, some keys combinations (e.g. L_Shift + Down arrow) stop working in some apps, e.g. [Telegram](https://telegram.org/dl/macos/store), but work in others.

**Comment by leshik** [comment]
Any news/thoughts on that? It's really annoying, I'm seeing similar behavior even in Sublime Text.

**Comment by bayan9** [comment]
I found an easy way to reproduce this:

I've swapped CAPSLOCK and CTRL and CTRL-scroll, no longer zooms (which is set in accessibility as an option).

**Comment by yjlintw** [comment]
@bayan9 I remove the swap, but CTRL-scroll is still not working. It works as soon as I quit Karabiner-Elements

**Comment by leshik** [comment]
In my use case, the bug seems to be fixed in 0.90.69 (beta), VirtualHIDDevice 4.0.0.
