### ISSUE TITLE
Is remapping left-click while a modifier key is held down to another mouse button supported?

### ISSUE THREAD

**Issue by mattbutnot** [tekezo/Karabiner-Elements#1202]
Hi, I have added this JSON as a custom complex modification, but it doesn't appear to do anything using the latest beta (11.5.0).

```
{
  "title": "fn+left-click to middle-click",
  "rules": [
    {
      "description": "When the left mouse button is clicked while fn is held down, post a middle click.",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "pointing_button": "button1",
            "modifiers": {
              "mandatory": [
                "fn"
              ]
            }
          },
          "to": [
            {
              "pointing_button": "button3"
            }
          ]
        }
      ]
    }
  ]
}
```

Is there something wrong with the JSON, or does Karabiner not support doing this yet? If I change the "from" section to just
```
"key_code": "fn"
```
it works, but I'd much rather have the fn key act as a modifier key.

Thanks for any help anyone is able to provide!

**Comment by tekezo** [comment]
Did you enable your mouse on Devices tab?
https://pqrs.org/osx/karabiner/help.html#mouse-button

**Comment by mattbutnot** [comment]
The checkboxes for enabling both my internal trackpad and external Magic Trackpad are disabled. That would be why it's not working! Is there a way to enable button remapping for the Apple trackpads, or is that not possible?
<img width="1112" alt="screen shot" src="https://user-images.githubusercontent.com/33024772/34650910-d4a65012-f41c-11e7-9efb-0ae0611e2a00.png">
