### ISSUE TITLE
Pressing TWO keys together in different order produces different results

### ISSUE THREAD

**Issue by funckdren** [tekezo/Karabiner-Elements#1206]
I’m a longtime Karabiner user who recently upgraded to Karabiner-Elements. I’m trying to just get two important rules working again. Basically this is what I’m trying to do:

Change left_control to right_option
Change left_option + left_control to right_option + right_shift

With the generous help of another github user, we’ve been able to create a set of rules that work. But there’s a big problem with the two-key combo rule (the second rule). It’s nearly impossible to always press both keys at the EXACT same time, and I’m getting different results depending on which key actually gets pressed first.

I’m finding that if I press left_option slightly earlier than left_control, the second rule works perfectly. But if I press left_control slightly earlier than left_option, the second rule does not work. I can actually see the different results in EventViewer. I never had this problem in Karabiner.

Any thoughts on how to solve this problem? Here is the .json file I am using…thanks in advance for any thoughts or advice!

{
  "title": "Personal rules (@funck)",
  "rules": [
    {
      "description": "Map left_control to right_option",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "left_control"
          },
          "to": [
            {
              "key_code": "right_option",
              "modifiers": [

              ]
            }
          ]
        }
      ]
    },
    {
      "description": "Holding both Left Option+Left Control will map to Right Option + Right Shift",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "left_option",
            "modifiers": {
              "mandatory": [
                "left_control"
              ]
            }
          },
          "to": [
            {
              "key_code": "right_shift",
              "modifiers": [
                "right_option"
              ]
            }
          ]
        }
      ]
    },
    {
      "description": "Holding both Left Option+Left Control will map to Right Option + Right Shift, 2 (enable both)",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "left_control",
            "modifiers": {
              "mandatory": [
                "left_option"
              ]
            }
          },
          "to": [
            {
              "key_code": "right_shift",
              "modifiers": [
                "right_option"
              ]
            }
          ]
        }
      ]
    }
  ]
}

**Comment by runar-rkmedia** [comment]
I solved this in the latest rules. It is now available here: https://pqrs.org/osx/karabiner/complex_modifications/#personal_funck You may have to delete your old versions of these rules first @funckdren
