### ISSUE TITLE
Configurable overlap/rollover thresold eg for using spacebar as spacebar (alone) or left_control (held)

### ISSUE THREAD

**Issue by kbdluv** [tekezo/Karabiner-Elements#1207]
Opening an issue for [this comment here](https://github.com/tekezo/Karabiner-Elements/issues/8#issuecomment-329637288) as I face the same problem:

>The implementation of to_if_alone works great as stated, but actually doesn't handle my own use case. I'm trying to map spacebar to left_command when paired with other keys, and to use it as a normal spacebar when alone. I found that even after mapping w/ to_if_alone, the main issue is that spacebar is used very often. Because of this, **it's pretty common to accidentally hit another character while the space key is still pressed, especially when typing quickly.**

>Ideally, I could set **some arbitrary [overlap/rollover] millisecond threshold**. If spacebar is only held for less than that threshold, then it will **always** be treated as a spacebar press (Even if I press another key during that initial spacebar press). However, if I hold spacebar for more than that threshold, it will be treated as left_command[_control/etc]. If anyone's done something like that in a fork, let me know!

One proposed solution to this issue is #877, which solves the case for when the held spacebar is released after the key that is pressed with it, and I'm sure the feature has additional good uses.

I'm opening this as a separate issue because the **overlap/rollover threshold** would also solve the case for when the held spacebar is released before the key that is pressed with it. The order of the keydowns in that case would not be relevant.

**Comment by rubas** [comment]
Same boat as I want to map some modifier to the homerow. Rollover is a big issue and makes it not usable at the moment. :(

**Comment by elasticdog** [comment]
@jonathankau @kbdluv @rubas I think I came up with a working solution (on Karabiner-Elements v12.2.0) to prevent accidental modifier hits via a delay:

```json
{
    "description": "spacebar -> left_command (spacebar if pressed alone)",
    "manipulators": [
        {
            "from": {
                "key_code": "spacebar",
                "modifiers": {
                    "optional": ["any"]
                }
            },
            "parameters": {
                "basic.to_delayed_action_delay_milliseconds": 200,
                "basic.to_if_held_down_threshold_milliseconds": 200
            },
            "to_delayed_action": {
                "to_if_canceled": [
                    {
                        "key_code": "spacebar"
                    }
                ]
            },
            "to_if_alone": [
                {
                    "key_code": "spacebar",
                    "halt": true
                }
            ],
            "to_if_held_down": [
                {
                    "key_code": "left_command"
                }
            ],
            "type": "basic"
        }
    ]
}
```

**Comment by handcoding** [comment]
Big props, @elasticdog! That code works a treat. 💯

**Comment by danielhanold** [comment]
@elasticdog Thanks for sharing that with the community - been trying to make this happen without success for a while until I found your snippet.

**Comment by sinewave** [comment]
@elasticdog, sorry for reviving an old thread, but I've been trying to get this to work for a long time without any luck until I found your post! 🎉🎉

Do you know how I can use this approach to support multiple keys? For example, using your code above, I've mapped "j" to Cmd and "k" to Shift. I'd like to be able press and hold both to trigger "Cmd + Shift."

**Comment by reedbender** [comment]
This is fantastic, homerow mods have been plaguing me with karabiner elements until I came across this. The trick here is to use `to_delayed_action` and `to_if_held_down` instead of just `to`, which is now working wonders.
