### ISSUE TITLE
Allow the virtual keyboard to be different for different keyboards

### ISSUE THREAD

**Issue by sgronblo** [tekezo/Karabiner-Elements#1208]
I use a Japanese keyboard at home and a US keyboard at work. It would be nice if I didn't have to manually switch the virtual keyboard between ANSI and JIS every time I switch keyboards.

**Comment by cero-t** [comment]
+1
I use a JIS internal keyboard and a US external keyboard. I want to modify some keys of both of them without changing their layout.

**Comment by volaix** [comment]
If there was a shortcut for changing the virtual keyboard that might be easier to implement and work great too! 

(Uses ISO internal, and ANSII external)

**Comment by sgronblo** [comment]
Thanks. That works as a workaround for decreasing the amount of clicks required to change ANSI -> JIS. But it also means that any custom stuff you have might have to be duplicated over two different profiles.

**Comment by volaix** [comment]
^Yeah, I have heaps of custom bindings too. So rather than rebind all the keys, what I did was just copy and paste the profile data in the .json file. It was pretty quick to get the other keyboard up and running :) That gave a pretty solid foundation for swapping between the two keyboards.

Good luck! Since I posted before- I'm pretty happy with this workaround for switching keyboards :)

**Comment by sgronblo** [comment]
Is it possible to bring this back to life? I am now using a Macbook M1 with JIS keyboard layout but when I plug it in to a monitor I also plug in an ANSI Magic Keyboard. The workaround I have come up with is to create one "JIS" profile with "Country Code: 0" and an "ANSI" profile with "Country Code: 1". But I switch between the two keyboards quite frequently and it's quite annoying to have to manually switch the profiles.

**Comment by AntonNarkevich** [comment]
Yep. Struggling with the same issue.
Have to switch between ISO and ANSI quite often.

Would be nice to reopen...

**Comment by decomush** [comment]
+1 I have a simialr issue

ANSI external keyboard and iso macbook keyboard.
Sometimes i have to switch between both of them and i need to open karabine just to change the layout
