### ISSUE TITLE
Is it possible to develop an iOS version of Karabiner?

### ISSUE THREAD

**Issue by iwuwu** [tekezo/Karabiner-Elements#1209]
I think iPad is the place where Karabiner is the most needed. The iPad's physical keyboard experience is so bad that it is extremely necessary to customize the keys.

Really want to have an iOS version of Karabiner...

**Comment by Bezosh** [comment]
Agree. Vim needs some configurations for Apple smart keyboard.

**Comment by wende** [comment]
I'm assuming this issue is no longer being considered?

**Comment by cloudle** [comment]
now with iPadOs, this should be re-consider.. I belive.

**Comment by Ehco1996** [comment]
@cloudle  is there any way to solve this problem?

**Comment by superdorage** [comment]
WHYYYYYYYYYYY
I just cant use any other keyboards without the diamond cursor “cmd + ijkl” for text editings.
SOMEBODY PLEASE HELP

**Comment by marchenk0** [comment]
> WHYYYYYYYYYYY
> I just cant use any other keyboards without the diamond cursor “cmd + ijkl” for text editings.
> SOMEBODY PLEASE HELP

just buy programmable keyboard with QMK

**Comment by oOJohn6Oo** [comment]
Any update?

**Comment by roryfahy** [comment]
is this even possible from a programming standpoint? I think it would be tremendously helpful

**Comment by marchank0** [comment]
@johngb I would suggest to look into ZMK. this is a new framework for programmable BT keyboards
you need nice!nano and [r/ergoMech](https://www.reddit.com/r/ErgoMechKeyboards/)
look this [video](https://www.youtube.com/watch?v=CHSh1-dJq24) to have basic understanding what you can achieve 
there is no commercial solution like apple magic keyboard with programmability (or I don't know about it), but you can create one for yourself after some research

**Comment by 44-5-53-6-k** [comment]
right now I am using Universal control from mac to ipad and karabiner works great with that!

I wish it was possible to also change keyboard layout this way. for some reason it isn't working for me
```
"to_if_alone": [
            {
              "select_input_source": {
                "language": "en"
              }
            }          ]
```
