### ISSUE TITLE
Complex Modifications: Need FrontMostWindowName or FrontMostWindowSize

### ISSUE THREAD

**Issue by e-gaulue** [tekezo/Karabiner-Elements#1211]
For remote desktop applications. Sometimes, credentials are required before the connexion is set. So keys are already remapped when you need to type them.

With Karabiner we were used to use the window name that was not always so good. Maybe the window size would be better has those credential request windows are often quite smaller than the remote desktop ones.

Maybe Active would even better than FrontMost. Don't know how hard is it to implement this.

Regards,

**Comment by wagnergerald** [comment]
+1
