### ISSUE TITLE
Is it possible to map 'p' to two 'v's?

### ISSUE THREAD

**Issue by rosingle** [tekezo/Karabiner-Elements#1213]
Hello I've searched around for some time but didn't find anything useful.

Is it possible to map the p so that when I type p it gives me two v ?

I've tried something like this but it didn't work

                            {
                                "from": {
                                    "key_code": "p"
                                },
                                "to": [
                                    {
                                        "key_code": "v",
                                        "2" 
                                    }
                                ],
                                "type": "basic"
                            }

Tks in advance

**Comment by michelkoga** [comment]
``
                        {
                            "from": {
                                "key_code": "p"
                            },
                            "to": [
                                {
                                    "key_code": "v"
                                },
                               {
                                    "key_code": "v"
                                }
                            ],
                            "type": "basic"
                        }

``

**Comment by rosingle** [comment]
tks it works !! many thanks !

**Comment by nguyenhimself** [comment]
You should close this issue then.
