### ISSUE TITLE
Ctrl-W to delete back one word missing from Emacs keybindings

### ISSUE THREAD

**Issue by mrzool** [tekezo/Karabiner-Elements#1215]
Hello and thanks for Karabiner Elements.

One of the main reasons I use Karabiner is to have Emacs-like keybindings available in every application on MacOS. Ctrl-W to delete back one word is among the ones I use most with Karabiner on El Capitan.

I’m stuck with High Sierra and Karabiner Elements at work and found out yesterday that that keybinding is missing from the Emacs keybindings available [here](https://pqrs.org/osx/karabiner/complex_modifications/#emacs_key_bindings):

![screen shot 2018-01-10 at 08 21 29](https://user-images.githubusercontent.com/6874363/34760262-4fe4bc0a-f5df-11e7-9633-9624152f3dde.png)

Is there any reason for this? Any chance it might get added? If not, is there any way I can configure this behavior using Karabiner Elements?

Thanks for any help.

**Comment by jthedwalker** [comment]
@mrzool It would appear that you should be able to make that modification. You'd have to either modify your current json file or create your own and import it. You'd have to bind the "w" key with a mandatory "control" modifier to "backspace" with an "option" modifier. I believe option + backspace deletes the last word. You may need to check the key codes in the event viewer. This is the documentation for the complex modifications. [https://pqrs.org/osx/karabiner/json.html](url)

**Comment by mrzool** [comment]
@jthedwalker Thanks for pointing me in the right direction. I’ll try tomorrow and report back.

**Comment by jthedwalker** [comment]
@mrzool Did you have any luck with your modification? If you have issues I can give it a go, didn't want to leave you hanging.

**Comment by mrzool** [comment]
@jthedwalker wow it’s been 14 days already? Sorry I was very busy at work these days, I’ll definitely give it a shot tomorrow.

**Comment by mrzool** [comment]
That was a bit harder than I thought, but I managed to get it working by adding this snippet to `~/.config/karabiner/karabiner.json`:

```json
{
  "from": {
      "key_code": "w",
      "modifiers": {
          "mandatory": [
              "control"
          ],
          "optional": [
              "caps_lock"
          ]
      }
  },
  "to": [
      {
          "key_code": "delete_or_backspace",
          "modifiers": {
            "mandatory":  "option" 
          }
      }
  ]
```

Thanks a lot for the help!

PS: this should totally be included in the default rules for Emacs keybindings.

**Comment by avatar-lavventura** [comment]
Your code only deletes a single character rather than a word @mrzool
