### ISSUE TITLE
Modifier keys not affecting other keyboard

### ISSUE THREAD

**Issue by dasilvacontin** [tekezo/Karabiner-Elements#1216]
Hi!

By default, in Mac, if I hold shift in one of my keyboards, the letters I type on the other keyboard are not affected. Same for other modifier keys, like command, alt, etc.

Would it be possible to do with Karabiner? Sorry for the question, but I just seems very complicated to find out if you have this feature.

Thanks!

**Comment by ugultopu** [comment]
@tekezo This is a very useful feature request for people that use double keyboards for ergonomics.

**Comment by dasilvacontin** [comment]
I don't get the point of closing stale issues. This is still a valid suggestion afaik.

**Comment by itslenny** [comment]
Still a great feature. I got an 8 key external macro keyboard and am really bummed I can't use it in conjunction with modifiers from my main keyboard.

**Comment by leowu4ever** [comment]
Just got my sec keyboard and ran into the same issue. This feature deserves attention.
