### ISSUE TITLE
"Rotating" keys 

### ISSUE THREAD

**Issue by fluffynuts** [tekezo/Karabiner-Elements#1218]
Please excuse me if this is obvious -- I'm just not finding the key

I'd like to rebind keys to make my macbook and external keyboards (both look like the ISO image in the Virtual Keyboards pane of Karabiner) fit with my muscle memory a little better - in particular, I'd like to have the §/± key become the grave/tilde (`/~) key so I can make the grave/tilde key the backslash, and perhaps make the existing backslash an extended enter key.

So what I have is this:
![image](https://user-images.githubusercontent.com/4669340/34816074-720c66a6-f6bc-11e7-9e3b-c0b15f3f333a.png)

strangely, I've had to reverse the order for the first two from what I would have expected -- but it's working. The last one, though, isn't -- and if i reverse that (`return_or_enter` -> `backslash (\)`) then the enter key produces a backslash (which is kinda what I would expect, however, I've had to reverse the other two to get them to work, so I thought I'd give it a go (: )

Any assistance appreciated.

**Comment by moutis** [comment]
This sounds like the same cause of the problem I've encountered in [issue 1222](https://github.com/tekezo/Karabiner-Elements/issues/1222). Linking them here in case they are, and the info helps figure it out.

**Comment by fluffynuts** [comment]
I've ended up devouring keys via ukelele and some trial-and-much-error with a layout xml file. But it still would be neat if this was fixed.
