### ISSUE TITLE
How to create your own CUSTOM complex modifications? 

### ISSUE THREAD

**Issue by neilpanchal** [tekezo/Karabiner-Elements#1225]
Presumably, I am in the minority here? I can't seem to find out how to create my own custom modification. 

Help file doesn't help: https://pqrs.org/osx/karabiner/document.html#configuration-complex-modifications

It mentions briefly that "or create your own" but doesn't actually tell you. Google search didn't turn up any useful results.

The app only allows me to import from https://pqrs.org/osx/karabiner/complex_modifications/

which again, **doesn't instruct the user about how to create one from scratch**.

I've since modified the .json in ~/.config/karabiner/custom_modifications file by installing something similar off of the official repository.

As a feedback, it is __critical__ to put a note somewhere in the main application that informs the average joe using this app about how to create a new custom modification. I was completely lost and I am still lost, but I managed to modify the .json file and for now this is ok.

**Comment by neilpanchal** [comment]
@tekezo Thank you. This needs to be included somewhere in the GUI or the Karabiner official repository of complex modifications.

**Comment by grrowl** [comment]
Would be great to have that document more prominently linked. Had to reverse engineer adding one from web but substituting for a `file:///` URL instead. It works :)

**Comment by RochelleBS** [comment]
Sorry to be a dolt, Tekezo, but I don't understand how to create a complex modification from scratch. Can you please give some total newbie step-by-steps? I'm guessing this doesn't use the GUI to actually create the modifications, but only to turn them on or off.

**Comment by grrowl** [comment]
1. Read the docs at https://pqrs.org/osx/karabiner/json.html
2. Edit the file at `~/.config/karabiner/karabiner.json`. It will include all currently enabled rules (so it might be a very big file), but you can edit and add new complex modifications there.
3. This file is reloaded by Karabiner Elements on every save, so you can test. It will help to open Karabiner Elements > Log, and check for any red errors (which may indicate incorrect config values or keys, or other problems with your modifications)

**Comment by RochelleBS** [comment]
Thank you.

Tom McKenzie wrote:

**Comment by NPatrakov** [comment]
hello to all! Please help me. i`m going crazy with new version of karabiner. what to insert to json file to do 
Change Option_R+,(≤) to Comma(,) Key for Russian
Change Option_R+,(≥) to Dot(.) Key for Russian

**Comment by prohtex** [comment]
How about bringing this button back so this is a little easier to figure out?

![karabiner-xml1 2x](https://user-images.githubusercontent.com/12946938/37258677-861ced00-2538-11e8-8242-a7d0564d597a.png)

**Comment by michaels3d** [comment]
Hi,
I'm trying to customize a mouse button so it calls a mac shortcut, command H (hide application).  I've gotten into the complex modifier code pretty good, but still can't figure out how to do this.  I believe it's because I need to call command and H simultaneously, but it appear the simultaneous parameter only works under "from", not "to".  I could be wrong, but does anyone have any ideas?  Thanks

**Comment by YayC** [comment]
To make these persist across updates, I tried adding a new file: ~/.config/karabiner/assets/complex_modifications/mine.json (using an imported file as an example). This seems to be working fine after enabling it from the preferences > complex modifications tab, but I have not updated since to test persistence.

Should this be the supported method for adding custom complex modifications?

**Comment by babarrett** [comment]
Yes, YayC's creation / edit of ~/.config/karabiner/assets/complex_modifications/mine.json should be included within: https://pqrs.org/osx/karabiner/json.html

I also noticed that in order to do an edit / run cycle I needed to:

1. edit ...mine.json
2. "remove" the active custom complex_modifcations I'd already enabled for that file in the preferences
3. re-enable those complex_modifcations in the preferences

Without that the edited code seems not be reloaded. :-(

**Comment by llamerr** [comment]
Something like "Import JSON from file" inside "Add rule" would be very useful

**Comment by jordanegstad** [comment]
I'm looking to create a complex modification that converts the `fn + spacebar` keys into a backspace, however i'm not having any luck. I've played around with other `key_codes` and mandatory keys and the rule works great. Have I missed something?

<pre>
{
    "from": {
        "key_code": "spacebar",
        "modifiers": {
            "mandatory": [
                "fn"
            ]
        }
    },
    "to": [
        {
            "key_code": "delete_or_backspace"
        }
    ],
    "type": "basic"
}
</pre>

**Comment by crawfyp1** [comment]
Good evening

Total noob here. I would like to swap @ and " on my keyboard. I assume this is a complex modification as it involves shift and another key?

I have tried simple modification but cant achieve what I'm looking to do. I have read the complex modification instructions but I'm not a coder and it's totally beyond my skill set.

Can anyone help me? I can follow step by step instructions, or could someone upload so I can download from the complex mod import site?

Very grateful for any help

**Comment by revelt** [comment]
@jordanegstad I think there's a rule which prohibits all-function-key combos (like CMD+ALT+CTRL), there has to be a non-functional key in the key combo. As a last resort, try sacrificing F12 for example, remapping it as `fn`, then map `F12`+`spacebar` instead. Maybe that would work? I toggle my terminal using caps lock this way: remapped my caps lock key to press F12 (in Karabiner), then mapped F12 to toggle terminal (in Terminal app).

@crawfyp1 Did you follow https://pqrs.org/osx/karabiner/document.html#configuration-simple-modifications ? If so, where did you get stuck? Please attach screenshots.

@HBinswanger the Karabiner Elements config is located at `~/.config/karabiner/karabiner.json`. If you know where your XML profile is, the task becomes to port it to Elements. I'm not familiar with XML profiles but if they are really in XML, the Elements config is in JSON, so you will have to manually re-create all your customisations in `~/.config/karabiner/karabiner.json`. If profile is in JSON, carefully port them one at the time, making sure JSON key structure is matching Karabiner Elements config (there's `rules` key, it's equal to array, there's object with `manipulators` key which contains array of all customisations...)

**Comment by ianklatzco** [comment]
Sorry for the necropost, but for anyone coming by later:

* If you have a properly formatted JSON file (`pip3 install demjson; jsonlist file.json`) matching the format, you can put it in `~/.config/karabiner/assets/complex_modifications` with whatever name. When you click `Add Rule` in the `Complex Modifications` pane, you should see it in the list.

* Alternatively, You can use a Karabiner link to import configs, using a file URL (as mentioned earlier in this thread).
* Note that it needs to be url-encoded: open `python` and `urllib.parse.quote("file:///...` (or just switch the `:` for a `%3A`)
* Load this in your browser: `karabiner://karabiner/assets/complex_modifications/import?url=file%3A///Users/YOUR_USERNAME/.config/karabiner/assets/complex_modifications/FILENAME.json`

**Comment by HBinswanger** [comment]
I just want to use shifted states to output one or two keystrokes. E. G to have ctrl-y do the few keystrokes that will delete a line. Do I have to jump thru these hoops to do that? Suppose I want ctrl-shift-x to put out Ab followed by the Enter key. What would the JSON look like exactly?

**Comment by AdamWagner** [comment]
@HBinswanger - I recommend using DefaultKeyBindings.dict for that. See https://brettterpstra.com/projects/keybindings/

**Comment by jonasbaraujo** [comment]
Hi everyone! I'm sorry to annoy you all, a complete noob here!

I'm using an AZERTY keyboard and the acute accent mark is quite troublesome to get.

I was looking for a modification like:

[ option + ' ] -> [ option + shift + & ]

Can anybody help me pleeeeeease!

**Comment by euclid1990** [comment]
@jonasbaraujo You can see this example
```
"rules": [
    {
        "description": "Print screen to Cmd+Shift+3",
        "manipulators": [
            {
                "from": {
                    "key_code": "print_screen",
                    "modifiers": {
                        "optional": ["any"]
                    }
                },
                "to": [
                    {
                        "key_code": "3",
                        "modifiers": [
                            "left_command",
                            "left_shift"
                        ]
                    }
                ],
                "type": "basic"
            }
        ]
    }
]
```

**Comment by HBinswanger** [comment]
> @HBinswanger - I recommend using DefaultKeyBindings.dict for that. See https://brettterpstra.com/projects/keybindings/

Thank you. This is just what I wanted (even though it's got a baroque syntax).

**Comment by HBinswanger** [comment]
> @HBinswanger - I recommend using DefaultKeyBindings.dict for that. See https://brettterpstra.com/projects/keybindings/

**Comment by HBinswanger** [comment]
Ignore this please

> @HBinswanger - I recommend using DefaultKeyBindings.dict for that. See https://brettterpstra.com/projects/keybindings/

Thank you. Unfortunately, I don't understand what it is. Is it a set of pre-defined key mappings? If so, how would I adapt them to the mappings I want?

**Comment by HBinswanger** [comment]
> @HBinswanger - I recommend using DefaultKeyBindings.dict for that. See https://brettterpstra.com/projects/keybindings/

Thank you. I found the Karabiner stuff several screenfuls down several. Unfortunately, it's overkill--I just wanted a single example to use as a template. I got that from jonas.

**Comment by HBinswanger** [comment]
> @jonasbaraujo You can see this example
> 
> https://gist.github.com/euclid1990/ee6ed30164c8936f0cecba0194b1b8b4
> 
> Put it into `karabiner.json > profiles > complex_modifications`

Thank you! This is exactly what I need.

**Comment by tilo** [comment]
why is there no way to just provide the JSON from a local file??
Seems unnecessarily complicated to have to go through web-download of rules

**Comment by araa47** [comment]
@tilo , just edit the ~/.config/karabiner/karabiner.json file

**Comment by Ninja73737** [comment]
Ok, either there was an update that changed things or I'm just actually dumb, but I can't find the ~/.config/karabiner/karabiner.json file for the life of me. Can someone tell me where I can find it?

**Comment by linonetwo** [comment]
Can you add a button on GUI to open `~/.config/karabiner/karabiner.json`?

That button can just simply execute `open ~/.config/karabiner/karabiner.json` is enough.

**Comment by benjaminb** [comment]
Hi folks, very new to Karabiner and having trouble getting it to accept complex modifications. I've added the following to `~/.config/karabiner/karabiner.json` under "rules", under "complex_modifications", but it's not taking effect. Is there something else I need to do? The docs say Karabiner should pick up the change on save.

            "rules": [{
                "description": "command-backslash to end",
                "manipulators": [{
                    "from": {
                        "key_code": "backslash"
                        "modifiers": ["left_command"]
                    },
                    "to": [{
                        "key_code": "end"
                    }],
                    "type": "basic"
                }]
            }]

**Comment by chmreid** [comment]
Any updates on [this request](https://github.com/tekezo/Karabiner-Elements/issues/1225#issuecomment-357571634)? After 1.5 years this is still where I end up when searching for "How to implement custom modifications karabiner"

> This needs to be included somewhere in the GUI or the Karabiner official repository of complex modifications.

**Comment by avalanche1** [comment]
Just added several custom bindings, using unsystemated info here. So here is a working instruction:

- create a custom `.json` file in `~/.config/karabiner/assets/complex_modifications`
- fill the file with your instructions (see example below); more examples [here] (https://pqrs.org/osx/karabiner/json.html#typical-complex_modifications-examples-swap-semicolon-and-colon) (but note, that they *don't provide* the exact file structure, only rules - use my structure below
- goto Karabiner -> Preferences -> Complex Modifications -> Add rule
- enable your custom rule(s)
- PROFIT!!

```json
{
  "title": "KAT",
  "rules": [
    {
      "description": "hl to start\\end of line; uo for pgup\\pgdown",
      "manipulators": [
        {
          "from": {
            "key_code": "h",
            "modifiers": {
              "mandatory": ["fn"]
            }
          },
          "to": [
            {
              "key_code": "left_arrow",
              "modifiers": ["command"]
            }
          ],
          "type": "basic"
        },
        {
          "from": {
            "key_code": "semicolon",
            "modifiers": {
              "mandatory": ["fn"]
            }
          },
          "to": [
            {
              "key_code": "right_arrow",
              "modifiers": ["command"]
            }
          ],
          "type": "basic"
        },
        {
          "from": {
            "key_code": "u",
            "modifiers": {
              "mandatory": ["fn"]
            }
          },
          "to": [
            {
              "key_code": "page_up"
            }
          ],
          "type": "basic"
        },
        {
          "from": {
            "key_code": "o",
            "modifiers": {
              "mandatory": ["fn"]
            }
          },
          "to": [
            {
              "key_code": "page_down"
            }
          ],
          "type": "basic"
        }
      ]
    }
  ]
}
```

**Comment by Rainymood** [comment]
As a newcomer, this is still unclear. From [the current manual](https://pqrs.org/osx/karabiner/document.html) it seems that you can **not** make your own custom complex commands, only those that are uploaded to the webpage. I know this is not true, but it appears to be so for the newcomer.

**Comment by matthewblott** [comment]
@Rainymood yep, that's just thrown me

**Comment by ProfBobK** [comment]
To try and get the hang of things I downloaded one of the .json files from the web page opened by 'import more rules from the internet', and copied it into ~/.config/karabiner/assets/complex_modifications' as 'tmp.json'. It does not show up as a rule I can add. Why? What else do I need to do?

**Comment by mhldr** [comment]
I found ~/.config/karabiner/assets/complex_modifications/mine.json wasn't picked up.
If you enable an example complex modification then you'll see it added into ~/.config/karabiner.json then you can just modify the karabiner.json (after taking a copy).
So my karabiner.json goes as
```
{
    "global": {
        "check_for_updates_on_startup": false,
        "show_in_menu_bar": true,
        "show_profile_name_in_menu_bar": false
    },
    "profiles": [
        {
            "complex_modifications": {
                "parameters": {
                    "basic.simultaneous_threshold_milliseconds": 50,
                    "basic.to_delayed_action_delay_milliseconds": 500,
                    "basic.to_if_alone_timeout_milliseconds": 1000,
                    "basic.to_if_held_down_threshold_milliseconds": 500,
                    "mouse_motion_to_scroll.speed": 100
                },
                "rules": [
                {
                  "description": "home to start of line / end to end of line",
                  "manipulators": [
                    {
                      "from": {
                        "key_code": "home"
                      },
                      "to": [
                        {
                          "key_code": "left_arrow",
                          "modifiers": ["command"]
                        }
                      ],
                      "type": "basic"
                    },
                    {
                      "from": {
                        "key_code": "end"
                      },
                      "to": [
                        {
                          "key_code": "right_arrow",
                          "modifiers": ["command"]
                        }
                      ],
                      "type": "basic"
                    }
                  ]
                }
              ]
            },
            "devices": [],
            "fn_function_keys": [
                {
....
```

**Comment by lucask42** [comment]
I was bashing my head on the desk unable to get any complex modifications to work.  Was almost going to give up when I found some checkboxes under Devices > Basic Configuration.  The checkbox next to my bluetooth keyboard was unchecked, after checking this box my complex modifications started working as expected.

**Comment by 0xMH** [comment]
This hasn’t  been properly solved IMHO. For newcomers, Here's the updated link for the docs  https://karabiner-elements.pqrs.org/docs/json/

**Comment by spacesuitdiver** [comment]
I honest't don't think this article solves this as a newcomer, I had to refer to https://github.com/pqrs-org/Karabiner-Elements/issues/1225#issuecomment-571579064 still 🙁

**Comment by colossatr0n** [comment]
> This hasn’t been properly solved IMHO. For newcomers, Here's the updated link for the docs https://karabiner-elements.pqrs.org/docs/json/

I've updated the reference manual a bit to help with adding complex modifications that can be added or disabled through the UI: https://karabiner-elements.pqrs.org/docs/json/root-data-structure/

**Comment by DrNeroCF** [comment]
Would be nice to at least have a link to the json file in the GUI.

I only need to add modifier keys a command, is there a way to do that in the simple modification / GUI that I'm missing?

**Comment by assist726** [comment]
You know there's something seriously wrong with your documentation and GUI when people constantly have to resort to looking through closed issues to find something as basic as this

@tekezo

**Comment by rr1000** [comment]
I purchased a new mechanical keyboard for my mac and need to remap "space + ESC" to "space + `" since this keyboard doesn't have a dedicated tilde key and I don't want to hit three keys "space + fn1 + ESC" to move between multiple windows. Since Karabiner seems all but dead, does anyone have recommendations for replacement software? Even if it's paid.

**Comment by babarrett** [comment]
I still have Karabiner on my system, but also use: Hammerspoon.

**Comment by Rainymood** [comment]
I didn't know how to make a complex modification a year ago ([link])(https://github.com/pqrs-org/Karabiner-Elements/issues/1225#issuecomment-525663812), so I decided to make a short video to as a piece of documentation. I hope you find it useful!

https://www.youtube.com/watch?v=iiSIaMD4vqY

**Comment by djeikyb** [comment]
Why is this closed? There's still no documentation, and it really looks like there's no way to write your own complex modification

**Comment by oakif** [comment]
Just a note for anyone reading this—your modification won't show up if you have syntax errors in your json file. The modification will silently be hidden from the modification list.

**Comment by ericjung** [comment]
> I didn't know how to make a complex modification [a year ago](https://github.com/pqrs-org/Karabiner-Elements/issues/1225#issuecomment-525663812), so I made a short video as a piece of documentation. I hope you find it useful!
> 
> https://www.youtube.com/watch?v=iiSIaMD4vqY

This is great! Here is a text version created from your video.

**As of November 2020**, **Karabiner Elements 13.1.0** and macOS **BigSur 11.0.1**:

1. Create a new file in a text editor.
2. Enter mappings. You might have trouble with this format if you're not a programmer. Use https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/ as  a reference but understand that it only describes the **manipulators** array. The JSON struct must be an object with a **rules** array whose elements are objects with a **manipulators** array.

Here is an example:

```
{
    "title": "windows keyboard for macOS",
    "rules": [
      {
        "description": "application switching",
        "manipulators": [
          {
            "type": "basic",
            "from": {
              "key_code": "tab",
              "modifiers": {
                "mandatory": ["left_option", "shift"],
                "optional": ["caps_lock"]
              }
            },
            "to": [
              {
                "key_code": "tab",
                "modifiers": ["left_command", "shift"]
              }
            ]
          },
          {
            "type": "basic",
            "from": {
              "key_code": "tab",
              "modifiers": {
                "mandatory": ["left_option"],
                "optional": ["caps_lock"]
              }
            },
            "to": [
              {
                "key_code": "tab",
                "modifiers": ["left_command"]
              }
            ]
          }     
        ]
      },
      {
        "description": "Swap Command with Ctrl",
        "manipulators": [
          {
            "type": "basic",
            "from": {
              "key_code": "left_command",
              "modifiers": {
                "optional": [
                  "any"
                ]
              }
            },
            "to": [
              {
                "key_code": "left_control"
              }
            ]
          },
          {
            "type": "basic",
            "from": {
              "key_code": "left_control",
              "modifiers": {
                "optional": [
                  "any"
                ]
              }
            },
            "to": [
              {
                "key_code": "left_command"
              }
            ]
          },
          {
            "type": "basic",
            "from": {
              "key_code": "left_shift",
              "modifiers": {
                "optional": [
                  "any"
                ]
              }
            },
            "to": [
              {
                "key_code": "left_shift",
                "lazy": true
              }
            ]
          },
          {
            "type": "basic",
            "from": {
              "key_code": "right_command",
              "modifiers": {
                "optional": [
                  "any"
                ]
              }
            },
            "to": [
              {
                "key_code": "right_control"
              }
            ]
          },
          {
            "type": "basic",
            "from": {
              "key_code": "right_control",
              "modifiers": {
                "optional": [
                  "any"
                ]
              }
            },
            "to": [
              {
                "key_code": "right_command"
              }
            ]
          },
          {
            "type": "basic",
            "from": {
              "key_code": "right_shift",
              "modifiers": {
                "optional": [
                  "any"
                ]
              }
            },
            "to": [
              {
                "key_code": "right_shift",
                "lazy": true
              }
            ]
          }
        ]
      }      
    ]
  }
  
```
3. Check the syntax of your file by copying/pasting it into a JSON beautifier. If you don't do this and your file has a syntax error, Karabiner won't parse your file and silently ignores it (although the **Log** tab sometimes does display errors, but it was not consistent for me). There are many available on the web, [such as this one](https://jsonbeautifier.org/).

4. Save File to ~/.config/karabiner/assets/complex_modifications/any_filename.json  -- any_filename can be anything you want, but keep the .json extension.

5. In Karabiner Elements, goto the Complex Modifications tab. Click **Add Rule**. Looks for your rules and click **Enable** next to each.

**Comment by damianobarbati** [comment]
@ghost did you find a solution? I'm looking for a remap:
`left_ctrl + left_option + left_command + right arrow ==> trackpad_click` 

I need it to switch focus between displays.

**Comment by MuhammedZakir** [comment]
> @ghost did you find a solution? I'm looking for a remap:
> `left_ctrl + left_option + left_command + right arrow ==> trackpad_click`
> 
> But I can't find example on complex modifications with multiple keys anywhere.
>
> I need it to switch focus between displays

What do you mean by `trackpad_click`? Are you talking about mouse click? There is no trackpad-specific keys, but there are mouse buttons. What exactly is the shortcut for switching focus between displays?

`from` part for your config looks something like this -

```
{
  "type": "basic",
  "from": {
    "key_code": "right_arrow",
    "modifiers": {
      "mandatory": [
        "left_control",
        "left_command",
        "left_option"
      ]
    }
  },
  ...
}
```

**Comment by szobonyatomi** [comment]
I just wanna switch the natural scroll back to 'normal' in the Archicad, i found this old xml to do, but i have no idea how can i make same with a personal json. 
`<?xml version="1.0"?>
<root>
  <item>
    <identifier>remap.samples_flipscrollwheel</identifier>
    <name>Flip Horizontal and Vertical ScrollWheel at Safari</name>
    <only>SAFARI</only>
    <autogen>
      __FlipScrollWheel__
      Option::FLIPSCROLLWHEEL_HORIZONTAL,
      Option::FLIPSCROLLWHEEL_VERTICAL,
    </autogen>
  </item>
</root>`

**Comment by MuhammedZakir** [comment]
@szobonyatomi: Many options in old Karabiner were removed in Karabiner-Elements. For flipping scroll direction, you have to use another app. There is an app for this with a bunch of scroll specific features. I don't remember it's name. If you only want to flip scroll direction, you can use Penc.

**Comment by ActionsPerMinute** [comment]
christ. this is 2010. I expect: button to add rule -> dialogue with options -> choose script -> find script dialogue -> run command -> edit run command -> map to key -> confirm.

you shouldn't need a computer science degree to map a key in 2005.

**Comment by mattiacolombomc** [comment]
Can someone help me automatically make my Mac switch keyboard INPUT LANGUAGE when an external bluetooth keyboard is connected please?

**Comment by MuhammedZakir** [comment]
@dougpagani: https://karabiner-elements.pqrs.org/docs/json/

**Comment by whyboris** [comment]
_Worked example_ about how to create your own complex modifications here:

https://github.com/whyboris/dotfiles/tree/main/keybindings

Basically two steps:
1. Create a _JSON_ file with any name in this directory:
> ~/.config/karabiner/assets/complex_modifications/anything.json
2. Fill it following [this pattern](https://github.com/whyboris/dotfiles/blob/main/keybindings/yboris.json), see [documentation](https://karabiner-elements.pqrs.org/docs/json/typical-complex-modifications-examples/).
3. Go to _Karabiner_ -> _complex modification_ settings and add & enable the new rule!

In my example I bind `F6` to execute `Ctrl` + `c` to kill a process running in the _Terminal_

**Comment by MuhammedZakir** [comment]
@seankim641: Why do you use `strict` for key up and key down order if you want both `jk` and `kj` to emit escape? To continue this, please open a seperate issue.

**Comment by aidan-gibson** [comment]
(For future lurkers)
Consider an [External JSON generator](https://karabiner-elements.pqrs.org/docs/json/external-json-generators/) like [Goku](https://github.com/yqrashawn/GokuRakuJoudo).

**Comment by seankim641** [comment]
@MuhammedZakir 

I have no idea what "strict" means here... I am not exactly sure on how to open a separte issue either. I've been living my life w/o the modification, but one day I'll return to this thread and figure out a way when it is necessary!

**Comment by MuhammedZakir** [comment]
> I have no idea what "strict" means here...

In `simultaneous_options`, change values of `key_down_order` and `key_up_order` to `insensitive`.

ref: https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/from/simultaneous-options/

> I am not exactly sure on how to open a separte issue either. I've been living my life w/o the modification, but one day I'll return to this thread and figure out a way when it is necessary!

Use the "New issue" button situated at somewhere near top-left to open new issues.

**Comment by dolfonzo3** [comment]
> _Worked example_ about how to create your own complex modifications here:
> 
> https://github.com/whyboris/dotfiles/tree/main/keybindings
> 
> Basically two steps:
> 
> 1. Create a _JSON_ file with any name in this directory:
> 
> > ~/.config/karabiner/assets/complex_modifications/anything.json
> 
> 2. Fill it following [this pattern](https://github.com/whyboris/dotfiles/blob/main/keybindings/yboris.json), see [documentation](https://karabiner-elements.pqrs.org/docs/json/typical-complex-modifications-examples/).
> 3. Go to _Karabiner_ -> _complex modification_ settings and add & enable the new rule!
> 
> In my example I bind `F6` to execute `Ctrl` + `c` to kill a process running in the _Terminal_

God bless u Man! :)) Saved my ass...

**Comment by JuanRuizA7x** [comment]
Can someone help me? I have a physical keyboard in English, but the input source is Latin American (I speak Spanish). The problem is that this input source does not have the < and > signs, which I need since I often use them for programming. I have this custom rule, and the first rule works perfectly, but the second one doesn't work for me. How can I make it so that when I press option + period, it returns the > sign?

`{
    "title": "Personalización de símbolos \"<\" y \">\"",
    "rules": [
        {
            "description": "Asignar \"<\" al pulsar Option + \",\"",
            "manipulators": [
                {
                    "type": "basic",
                    "from": {
                        "key_code": "comma",
                        "modifiers": {
                            "mandatory": [
                                "option"
                            ]
                        }
                    },
                    "to": [
                        {
                            "key_code": "non_us_backslash"
                        }
                    ]
                }
            ]
        },
        {
            "description": "Asignar \">\" al pulsar Option + \".\"",
            "manipulators": [
                {
                    "type": "basic",
                    "from": {
                        "key_code": "period",
                        "modifiers": {
                            "mandatory": [
                                "option"
                            ]
                        }
                    },
                    "to": [
                        {
                            "key_code": "non_us_backslash",
                            "modifiers": {
                                "mandatory": [
                                    "shift"
                                ]
                            }
                        }
                    ]
                }
            ]
        }
    ]
}`

**Comment by EasonC13** [comment]
Now you can just use ChatGPT to do it.
For example, try the following prompt:

```
generate config for karabiner:
right option + right shift + slash = ctrl + cmd + H
```

**Comment by tilo** [comment]
> Here: https://pqrs.org/osx/karabiner/json.html

404 Not Found 👎

**Comment by TWiStErRob** [comment]
@tilo https://karabiner-elements.pqrs.org/docs/json/
