### ISSUE TITLE
Condition for specific app, but no when inputting text

### ISSUE THREAD

**Issue by GhostValk** [tekezo/Karabiner-Elements#1226]
Hi,

I'm trying to make a couple of keybinds only when the active window is finder. An example:

    {
      "description": "Delete to Delete File",
      "manipulators": [
        {
          "from": {
            "key_code": "delete_forward"
          },
          "to": [
            {
              "key_code": "delete_or_backspace",
              "modifiers": [
              	"left_command"
              ]
            }
          ],
          "type": "basic",
	  "conditions": [
		{

		"type": "frontmost_application_if",
              	"bundle_identifiers": [ "com.apple.finder" ]	

		}
	   ]
        }
      ]
    }

That, as you can see, basically binds ´delete´ to Cmd-Bcksp. which deletes the current selected file/files in Finder. That binding works perfect; i have a couple of similar ones in Finder, but it has a little downside, if i am changing the name of a file/folder, and press the binded key, it executes the binded action, instead of acting like the normal key in a text input instance.

Now, my question, It's possible to add another condition that disables the keybind when i'm inputting text when changing the name of a file in Finder? I remember in the old karabiner it can be done easily.

Thanks in advance!

**Comment by GhostValk** [comment]
Anybody..?

**Comment by eboye** [comment]
Bump! I would love to have this option too. Also backspace to go up one folder
