### ISSUE TITLE
Fixing $ < swap on MS Natural Keybaord 4000

### ISSUE THREAD

**Issue by djcmike** [tekezo/Karabiner-Elements#123]
I've created my jason file as follows, but the switch with $ and < doesn't work. Any ideas?

{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "application" : "right_option",
				"left_option" : "left_command",
				"left_command" : "left_option",
				"right_option" : "right_command",
				"right_command" : "right_option",
				"<" : "$",
				"$" : "<",
				"§" : ">",
				">" : "§"
            }
        }
    ]
}

**Comment by talha131** [comment]
@djcmike As per the docs

https://github.com/tekezo/Karabiner-Elements/tree/master/usage#an-example-of-karabinerjson
https://github.com/tekezo/Karabiner-Elements/tree/master/usage#the-key-definition

Your key codes are wrong. So instead of `"§"` you have to use `"non_us_backslash"`. 

I suggest you to try,

For `"<"`, `"comma"`
For `">"`, `"period"`
For `"$"`, `"4"`

Do let me know how it goes.

**Comment by djcmike** [comment]
HI.
I am on a DK keyboard layout, so the <> key is located down beside the SHIFT key and the §$ key is located up besides 1. Right now though, they have switched places which is what I am trying to fix.

**Comment by talha131** [comment]
So the key codes I posted, did they help?

**Comment by djcmike** [comment]
No sadly they didn't, but thanks anyway :)

**Comment by talha131** [comment]
This is a your keyboard, right?

![Danish keyboard](http://www.gadgetguy.dk/mbadk.jpg "Danish keyboard")

Try this for me, please

```json
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "non_us_backslash": "grave_accent_and_tilde",
                "grave_accent_and_tilde" : "non_us_backslash"
            }
        }
    ]
}
```

**Comment by djcmike** [comment]
Absolutely brilliant! Works like a charm and fixes all the issues I've had after switching to Sierra. Thanks mate!

**Comment by talha131** [comment]
Great! Glad it worked. Can you please tell me why or when you use § section key? 

Why does Danish keyboard (and other European keyboards) have a separate § key? Do you use it often?

I know it's section/paragraph key but what's the purpose?

**Comment by djcmike** [comment]
I don't use it much, but it's convenient for $ when coding and if I need to refer to a law paragraf, I use §. Beyond that, I don't really use it. For me it was mostly a question of getting < down where it belongs, since I use that one a lot.

Why do the European layouts have it? No clue I must admit.

**Comment by talha131** [comment]
Thank you.

> Why do the European layouts have it? No clue I must admit.

[I have been wondering](https://superuser.com/questions/969579/why-does-mac-uk-keyboard-have-a-key) since I got my hands on a UK keyboard.

--
BTW please close this issue if you think your problem has been resolved.

**Comment by talha131** [comment]
@djcmike Need a small favor. Can you please confirm this map is correct

|     Keyboard | Before | After |
|        ----- |   ---- |  ---- |
|       Danish |      § |     > |
|       Danish |      > |     § |
|       Danish |      $ |     < |
|       Danish |      < |     $ |

**Comment by djcmike** [comment]
Hi :)

Yep that is correct :)

Yours,
Mike Hansen

**Comment by talha131** [comment]
Thank you.
