### ISSUE TITLE
Two magic keyboards listed under the same entry

### ISSUE THREAD

**Issue by twerkmeister** [tekezo/Karabiner-Elements#1232]
First of all thank you for the great work on this awesome project! I've been using it for quite a while for minor modifications and it works like a charm.

Recently, I was experimenting with a quite experimental setup of two external keyboards to model a split keyboard setting. When I had two different keyboards types, Karabiner Elements worked as expected and let me modify each keyboard's keys accordingly. However, after my initial testing phase I got a second magic keyboard 2 and now both are listed under the same entry in Karabiner Elements, so any modification will affect both keyboards. The keyboard settings menu however has a way to distinguish them, so I suppose this should be possible somehow.

Karabiner Elements only recognizing one keyboard
<img width="999" alt="screen shot 2018-01-19 at 22 03 58" src="https://user-images.githubusercontent.com/1107341/35154328-d3b3ab9a-fd64-11e7-9e6c-66a4a2426a55.png">

both keyboards being detected in settings
<img width="655" alt="screen shot 2018-01-19 at 22 04 27" src="https://user-images.githubusercontent.com/1107341/35154336-e092fa96-fd64-11e7-9e3d-c0fec984824a.png">

Do you think it would be possible to let Karabiner Elements distinguish between the two as well?

**Comment by bb2020** [comment]
I have the same problem with a different keyboard couple. A solution is discussed here: https://github.com/tekezo/Karabiner-Elements/issues/1542
