### ISSUE TITLE
Disabling control + left click as right click?

### ISSUE THREAD

**Issue by Muscarv2** [tekezo/Karabiner-Elements#1234]
Hello, I'm wondering if it's possible to disable ctrl + left click as right click?

**Comment by yaroska** [comment]
please reopen this

**Comment by mashhood-pikessoft** [comment]
please reopen or at least tell that what is the way to disable ctrl + click = right click?

**Comment by ijoseph** [comment]
[Import 'Remove ctrl+left click to right click' here:]( https://pqrs.org/osx/karabiner/complex_modifications/#key-specific)

**Comment by genesy** [comment]
@ijoseph that doesnt work.. or doesnt work anymore

**Comment by quantumsheep** [comment]
still doesn't work

**Comment by gmoothart** [comment]
It's not working for me either (MacOS 10.15.7, Karabiner 13.1.0)
