### ISSUE TITLE
mouse2+mouse1 to left_control

### ISSUE THREAD

**Issue by ww7** [tekezo/Karabiner-Elements#1235]
Is a possible to assign mouse2+mouse1 to left_control?

**Comment by jthedwalker** [comment]
@ww7 You can't combine two key_codes as they are exclusive. As mapping mouse1 is risky, I would just map mouse button2 to send left_control if held. This way mouse2 can still function and in most cases there isn't a reason to hold mouse2. Something like this.

```
{
    "type": "basic",
    "from": {
        "pointing_button": "button2",
        "modifiers": {
            "optional": [
                "caps_lock"
            ]
        }
    },
    "parameters": {
        "basic.to_if_alone_timeout_milliseconds": 250,
        "basic.to_if_held_down_threshold_milliseconds": 250
    },
    "to_if_alone": [
        {
            "pointing_button": "button2"
        }
    ],
    "to_if_held_down": [
        {
            "key_code": "left_control"
        }
    ]
}
```

I haven't tested this yet as I'm not on my Mac at the moment. I wouldn't play with mouse1 as you could loose click control.
