### ISSUE TITLE
Why my System-wide Vimium mode can not be used?

### ISSUE THREAD

**Issue by BYTZJB** [tekezo/Karabiner-Elements#1236]
![image](https://user-images.githubusercontent.com/18246027/35204579-1b480dbe-ff6a-11e7-95fc-74d6e91becc5.png)
![image](https://user-images.githubusercontent.com/18246027/35204610-5528ea94-ff6a-11e7-8364-d1f5df8d5652.png)

**Comment by nguyenhimself** [comment]
Press ESC first to set the "vimium" variable to 1.
Press i to switch mode.
Same as normal vim.

**Comment by BYTZJB** [comment]
https://github.com/tekezo/Karabiner-Elements/issues/435

**Comment by BYTZJB** [comment]
I think that's because karabiner can't catch sign which from touch bar

**Comment by nguyenhimself** [comment]
Ah well, you can just map that vim mode trigger key from ESC to some other key. Works just fine on my non-Touchbar Mac.
