### ISSUE TITLE
The Virtual Keyboard pictures might be wrong

### ISSUE THREAD

**Issue by Singletoned** [tekezo/Karabiner-Elements#1237]
On the Virtual Keyboard tab of Karabiner-Elements, when I select ANSI (which has a tick `` ` `` next to the `1`) pressing the key next to the `1` enters `§`.  When I select ISO (which has a `§` next to the `1`) pressing the key next to the `1` enters tick``  ` ``).

This might just be me misunderstanding something, but I wondered if maybe the pictures were just the wrong way around.

**Comment by sebastianf** [comment]
The images are right but the behaviour is as you described

**Comment by tekezo** [comment]
This behavior depends on your input source.
Does this issue happen even in U.S. input source?

**Comment by Singletoned** [comment]
Sorry, this might be my fault.  I have a MacBookPro with a UK keyboard, but I use Canadian input source, because as a developer I prefer to have a `#` above the `3`, rather than the relatively unused `£`.  It's probably that which is causing the issue.

**Comment by sebastianf** [comment]
I have a german macbook keyboard but using u.s. as input source and have the same problem as soon as I start Karabiner-elements with ISO selected

**Comment by kgudka** [comment]
I have a UK MacBook keyboard and am using the British input source and am experiencing this same issue.

**Comment by kgudka** [comment]
I should add though that if I use my UK external keyboard (also using British input source), then it does the right thing (i.e. for the ISO keyboard, pressing the key next to `1` gives `§`. The problem only seems to be for the Apple internal keyboard.
