### ISSUE TITLE
Latest version of Eventviewer is not capturing all from MS Mouse

### ISSUE THREAD

**Issue by brinded** [tekezo/Karabiner-Elements#1238]
I have the Microsoft Sculpt Comfort Bluetooth Mouse (H3S-00001) and in the previous version of Karabiner/Eventviewer all the mouse actions were captures, such as swipe up/down on the Windows symbol, and the clicks on the scroll wheel. In Karabiner Elements/Eventviewer it's just the pressing of the blue Windows button that is captured. I have also disabled "Hide ignorable events."

I see some others have posted JSON with the scroll wheel events so maybe I can recover some of the functionality.

Thanks!

**Comment by xinhuang327** [comment]
I have the same mouse as yours, I tried to remove the mouse from bluetooth and add it back and the side button now works.
