### ISSUE TITLE
How to create variables?

### ISSUE THREAD

**Issue by nikitavoloboev** [tekezo/Karabiner-Elements#1239]
In old Karabiner I could make a variable that called some Applescript code using this syntax:

```Bash
<vkopenurldef>
<name>KeyCode::VK_OPEN_URL_KM_CAPITALISE_WORD</name>
<url type="shell">
osascript -e '
tell application "Keyboard Maestro Engine"
do script "Capitalise word"
end tell
'
</url>
</vkopenurldef>
```

Can I do the same in Karabiner Elements?

**Comment by jthedwalker** [comment]
@nikitavoloboev I believe this is what you're looking for. https://pqrs.org/osx/karabiner/json.html#to-event-definition
