### ISSUE TITLE
Control-Option-Command Eject shortcut for shutdown does not work

### ISSUE THREAD

**Issue by kjoonlee** [tekezo/Karabiner-Elements#124]
No response when I use the shutdown hotkey.

    {
        "profiles": [
            {
                "name": "Default profile",
                "selected": true,
                "simple_modifications": {
                    "caps_lock": "left_command",
                    "escape": "grave_accent_and_tilde",
                    "grave_accent_and_tilde": "escape"
                }
            }
        ]
    }

**Comment by kjoonlee** [comment]
I was pressing the keys to the left of the space bar.

**Comment by talha131** [comment]
> shutdown hotkey

Can you please elaborate? Which key combination is not working?

**Comment by dstillman** [comment]
> Which key combination is not working?

@kjoonlee says in the title: "Control-Option-Command Eject"

Same with Sleep (Cmd-Option-Eject) and Lock Screen (Ctrl-Shift-Eject, https://github.com/tekezo/Karabiner-Elements/issues/89).

(On a laptop it's the Power key instead of Eject.)

**Comment by talha131** [comment]
@dstillman @kjoonlee My apologies. I think I need coffee 😞

**Comment by creinero** [comment]
By using the EventViewer I see that when you press the Shift+Control+Power (on laptop) combination - having Karabiner OFF - you see that an additional KeyDown 0x7f event is added to the combo. Having Karabiner running, the additional KeyDown event is muted even on the laptop keyboard.

**Comment by oderwat** [comment]
Any ETA on a fix for this problem? I simply can't use karabiner(-elements) otherwise :)

**Comment by kubofonista** [comment]
Same here. Please fix, cannot lock mac without this :/

**Comment by kubofonista** [comment]
Sill not working after a fix with shortcut handling

**Comment by aleksandarristic** [comment]
Just checked after the update I got today - still not working. I tend to use hot corners to lock my screen as an alternative, but it's becoming a bit annoying. Any ETA on the fix?

**Comment by deville** [comment]
Cmd+Alt+Eject does not work for me on the Magic Keyboard, neither does Cmd+Alt+Power on the laptop. However, pressing and holding Cmd+Alt+Power for a second seems to work.

**Comment by oderwat** [comment]
In Sierra you need to hold Cmd+Alt+Eject for a short time even without Karabiner-Elements. So that is to be expected.

**Comment by tekezo** [comment]
#46
