### ISSUE TITLE
Simple modifications do not work on macOS 10.13.3

### ISSUE THREAD

**Issue by gl0wa** [tekezo/Karabiner-Elements#1240]
After updating last night from 10.13.1 to 10.13.3 (two minor versions at once, so not sure which one was breaking) none of my keyboard Simple Modifications work any more. Tried to create new ones and they don't work neither for any of keyboards.

**Comment by moku2** [comment]
I'm noticing the same issue after just upgrading to 10.13.3.

**Comment by gl0wa** [comment]
After restarting macOS it's working again. THis issue can be closed

**Comment by jclarktennis** [comment]
I am experiencing this issue for 10.13.4. I can't get any modifications to work at all. Anybody have any advice? Thank you.
