### ISSUE TITLE
Mouse Button 4 to Back/Forward

### ISSUE THREAD

**Issue by ArtemGordinsky** [tekezo/Karabiner-Elements#1241]
Hi,

I'm trying to replica the set up I had with the old Karabiner, namely:
`Mouse Button 4` > `CMD + [`
`Alt + Mouse Button 4` > `CMD + ]`

So far I was only able to get the first one working. Could anyone help me get the second one down?
Here's what I've got:
```json
{
  "rules": [
    {
      "description": "Mouse button4 → command + [",
      "manipulators": [
        {
          "from": {
            "pointing_button": "button4"
          },
          "to": [
            {
              "key_code": "open_bracket",
              "modifiers": [
                "command"
              ]
            }
          ],
          "type": "basic"
        }
      ]
    },
    {
      "description": "Alt + Mouse Button 4 → command + ]",
      "manipulators": [
        {
          "from": {
            "pointing_button": "button4",
            "modifiers": {
              "optional": [
                "left_option"
              ]
            }
          },
          "to": [
            {
              "key_code": "close_bracket",
              "modifiers": [
                "command"
              ]
            }
          ],
          "type": "basic"
        }
      ]
    }
  ]
}
```

I'm using Microsoft Sculpt Comfort Mouse.

**Comment by jthedwalker** [comment]
@ArtemGordinsky I don't have my Mac with me to test the theory but I believe the issue is your "Optional" left_option. The "Optional" modifier condition states that events are manipulated even **IF** the modifier is pressed; meaning that the event would manipulate without the modifier pressed. I would try changing the Optional condition to Mandatory. That would limit the second event to manipulate **ONLY** if left_option is pressed. I think Karabiner is getting confused as you are essentially binding two different events to the same button press.

**Comment by ArtemGordinsky** [comment]
@jthedwalker Thanks! I already gave up and switched to USB Overdrive though.

I still can't set up this shortcut there but at least I don't get repeating keys and sluggish cursor as I did with Karabiner.

**Comment by ArtemGordinsky** [comment]
@jthedwalker Thanks a lot for the suggestion, it actually works!

**Comment by JoeFerrucci** [comment]
Just put in under Simple Modifications and add `modifiers` list:

```
"simple_modifications": [
{
    "from":
    {
        "pointing_button": "button4"
    },
    "to":
    {
        "key_code": "open_bracket",
        "modifiers": [
            "left_command"
        ]
    }
},
{
    "from":
    {
        "pointing_button": "button5"
    },
    "to":
    {
        "key_code": "close_bracket",
        "modifiers": [
            "left_command"
        ]
    }
}]
```

**Comment by shyr** [comment]
@JoeFerrucci It works for me. Thanks a lot!

**Comment by k0ste** [comment]
Just who comes from google: paste snippet to comples_modifications key in `karabiner.json`

<img src="https://user-images.githubusercontent.com/7759548/109269529-a7d3ea80-781d-11eb-8cb3-6a52db700c32.png" width="250" height="250">

**Comment by theonejb** [comment]
Adding to this for the next person looking for this solution, Karabiner does not modify mouse events by default, you'll have to turn this on using the steps here: https://karabiner-elements.pqrs.org/docs/help/how-to/mouse-button/

**Comment by nicoandmee** [comment]
> USB Overdrive

Thank you!!! <3

**Comment by nicoandmee** [comment]
> Karabiner does not modify mouse events by default, you'll have to turn this on using the steps here: [karabiner-elements.pqrs.org/docs/help/how-to/mouse-button](https://karabiner-elements.pqrs.org/docs/help/how-to/mouse-button/)
> 
> I spent some time confused as the modification wasn't working for me by default. Leaving this here for the next person looking for this solution.

🙏🏾

**Comment by eduardgheorghe** [comment]
> Just put in under Simple Modifications and add `modifiers` list:
> 
> ```
> "simple_modifications": [
> {
>     "from":
>     {
>         "pointing_button": "button4"
>     },
>     "to":
>     {
>         "key_code": "open_bracket",
>         "modifiers": [
>             "left_command"
>         ]
>     }
> },
> {
>     "from":
>     {
>         "pointing_button": "button5"
>     },
>     "to":
>     {
>         "key_code": "close_bracket",
>         "modifiers": [
>             "left_command"
>         ]
>     }
> }]
> ```
> 
> Ends up looking this: ![Screen Shot 2019-05-20 at 11 26 31 AM](https://user-images.githubusercontent.com/2114494/58043489-23095800-7af2-11e9-9215-c72c15cc09bc.png)

Just a small update as of November 2024, this still works, however, you need to add the type.

Updated code below:

{
    "description": "Mouse Bttn4 and Bttn5 to Forward and Back",
    "manipulators": [
        {
            "from": {
                "pointing_button": "button4"
            },
            "to": [
                {
                    "key_code": "open_bracket",
                    "modifiers": ["left_command"]
                }
            ],
            "type": "basic"
        },
        {
            "from": {
                "pointing_button": "button5"
            },
            "to": [
                {
                    "key_code": "closed_bracket",
                    "modifiers": ["left_command"]
                }
            ],
            "type": "basic"
        }
    ]
}

**Comment by mashirozx** [comment]
> {
>     "description": "Mouse Bttn4 and Bttn5 to Forward and Back",
>     "manipulators": [
>         {
>             "from": {
>                 "pointing_button": "button4"
>             },
>             "to": [
>                 {
>                     "key_code": "open_bracket",
>                     "modifiers": ["left_command"]
>                 }
>             ],
>             "type": "basic"
>         },
>         {
>             "from": {
>                 "pointing_button": "button5"
>             },
>             "to": [
>                 {
>                     "key_code": "closed_bracket",
>                     "modifiers": ["left_command"]
>                 }
>             ],
>             "type": "basic"
>         }
>     ]
> }

fix close_bracket

```json
{
    "description": "Mouse Bttn4 and Bttn5 to Forward and Back",
    "manipulators": [
        {
            "from": {
                "pointing_button": "button4"
            },
            "to": [
                {
                    "key_code": "open_bracket",
                    "modifiers": ["left_command"]
                }
            ],
            "type": "basic"
        },
        {
            "from": {
                "pointing_button": "button5"
            },
            "to": [
                {
                    "key_code": "close_bracket",
                    "modifiers": ["left_command"]
                }
            ],
            "type": "basic"
        }
    ]
}
```

**Comment by mashirozx** [comment]
> > Just put in under Simple Modifications and add `modifiers` list:
> > ```
> > "simple_modifications": [
> > {
> >     "from":
> >     {
> >         "pointing_button": "button4"
> >     },
> >     "to":
> >     {
> >         "key_code": "open_bracket",
> >         "modifiers": [
> >             "left_command"
> >         ]
> >     }
> > },
> > {
> >     "from":
> >     {
> >         "pointing_button": "button5"
> >     },
> >     "to":
> >     {
> >         "key_code": "close_bracket",
> >         "modifiers": [
> >             "left_command"
> >         ]
> >     }
> > }]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Ends up looking this: ![Screen Shot 2019-05-20 at 11 26 31 AM](https://user-images.githubusercontent.com/2114494/58043489-23095800-7af2-11e9-9215-c72c15cc09bc.png)
> 
> Just a small update as of November 2024, this still works, however, you need to add the type.
> 
> Updated code below:
> 
> ```
> {
>     "description": "Mouse Bttn4 and Bttn5 to Forward and Back",
>     "manipulators": [
>         {
>             "from": {
>                 "pointing_button": "button4"
>             },
>             "to": [
>                 {
>                     "key_code": "open_bracket",
>                     "modifiers": ["left_command"]
>                 }
>             ],
>             "type": "basic"
>         },
>         {
>             "from": {
>                 "pointing_button": "button5"
>             },
>             "to": [
>                 {
>                     "key_code": "closed_bracket",
>                     "modifiers": ["left_command"]
>                 }
>             ],
>             "type": "basic"
>         }
>     ]
> }
> ```

fix closed_bracket

```json
{
    "description": "Mouse Bttn4 and Bttn5 to Forward and Back",
    "manipulators": [
        {
            "from": {
                "pointing_button": "button4"
            },
            "to": [
                {
                    "key_code": "open_bracket",
                    "modifiers": ["left_command"]
                }
            ],
            "type": "basic"
        },
        {
            "from": {
                "pointing_button": "button5"
            },
            "to": [
                {
                    "key_code": "close_bracket",
                    "modifiers": ["left_command"]
                }
            ],
            "type": "basic"
        }
    ]
}
```

**Comment by nagyalex** [comment]
@mashirozx shall your mod work in Finder too? My mouse has "Modify. events" on, but Finder doesn't react to mouse buttons.

**Comment by k0ste** [comment]
> [@mashirozx](https://github.com/mashirozx) shall your mod work in Finder too? My mouse has "Modify. events" on, but Finder doesn't react to mouse buttons.

My Microsoft 1.1A side buttons works in Finder too

**Comment by alextorma** [comment]
This works in Finder for me, but it breaks any application that expects mouse back/forward to be a gesture rather than a hotkey.

I suppose I'll have to go back to using LinearMouse to handle Universal Back/Forward buttons. I'd love it if this feature from LinearMouse could make its way into Karabiner.
