### ISSUE TITLE
Caps-lock does not trigger KeyUp event

### ISSUE THREAD

**Issue by owang** [tekezo/Karabiner-Elements#1253]
I am trying to simply remap caps-lock to command. 

```
            "simple_modifications": [
                {
                    "from": {
                        "key_code": "caps_lock"
                    },
                    "to": {
                        "key_code": "left_command"
                    }
                }
            ],
```

However, when I press caps-lock, it triggers command to be *always on*. I have to press caps-lock again to turn it off. How do I make caps-lock behave like a normal command, such that the command modifier is released when caps-lock is released.

In the event viewer, I see that only one event is fired when I press caps lock, but two are fired when I press command. Thanks!

**Comment by StitiS** [comment]
If you're simply looking for that remap you can use either MacOS's built in Keyboard > Modifier Keys option to change the behavior, or even Karabiner-Elements' "Simple Modifications" window.  I suspect you're building up a base case though for more complicated commands in KE.

CAPS_LOCK has a different behavior from the other modifier keys for some reason.  For example, if you open up the Event Viewer you can see that modifiers like "left_command" have two separate events: one for the press and one for the release.  For "caps_lock" however those two events are split across two separate press iterations.  I wonder if there's a way to change this.

For my own scripts, I've re-bound "caps_lock" to "right_command" and then use "right_command" as the modifier for all my other Complex Modifications.  It's not pretty but it works for my usage so far.

**Comment by owang** [comment]
In case someone else comes across this thread, I found the problem. I had to remove the Microsoft Intellitype drivers manually, reboot, and then the key started functioning correctly.  Now I can use  either the system mappings or Karabiner simple modifications and now it correctly turns the modified off again at KeyUp.
