### ISSUE TITLE
How to remap right option to actual 'enter'

### ISSUE THREAD

**Issue by peterinjapan** [tekezo/Karabiner-Elements#1254]
Hello, all. I am trying to get back my precious enter key which I used to remap the option key to. Now I can only remap it to "return or enter" rather than just "enter." Is there any way to accomplish this? If I could remap to "option + return" it would work, but there's no easy option for this that I can see. 

![screen shot 2018-02-03 at 11 26 30](https://user-images.githubusercontent.com/34758336/35762138-3d5d8e00-08d5-11e8-80d1-d725b906d636.jpg)

**Comment by Hank-Chung** [comment]
if you want to remap 'r_option' to 'option+return',..., wait a minute, do you mean 'return' is the same as 'return or enter' function? 

anyway, if you remap one key to some sort of shortcut then you have to make json file for 'complex modifications'.

`{}`

**Comment by JuliaTruchsess** [comment]
+1, I really want my Enter key back!!!

**Comment by Shnub** [comment]
Try to map to the entry called "keypad_enter". This one works just as the old Enter key for me.

**Comment by JuliaTruchsess** [comment]
Awesome, thanks. I couldn't find it previously, but digging around (in the latest version) I found that it's there in the list. Yay!

**Comment by hbankstoo** [comment]
Just upgraded to Mac Sierra and the new Karabiner Elements, from Yosemite and the previous version of Karabiner. Trying to remap the right_option key to keypad_enter. Put that into Elements, but doesn't show up in EventViewer.

Help! Really want my enter key back.

**Comment by JuliaTruchsess** [comment]
Works for me with MacOS 10.13 and Karabiner Elements 12.1.0. Under Simple Modifications tab, map right_option to keypad_enter.

**Comment by hbankstoo** [comment]
All of a sudden, it started working, as if by magic. So issue resolved.

Thanks for your feedback.
