### ISSUE TITLE
Overlapping Keystrokes With Hold Sequences

### ISSUE THREAD

**Issue by StitiS** [tekezo/Karabiner-Elements#1256]
Hello,

I am migrating over my Karabiner config to KE and am still getting used to the learning curve.  So I appreciate any help here.

The following code works in that the correct keyset is sent when I hold "1".  However, in normal typing if I happen to overlap another key with "1" then the "1" is never sent.  So essentially it's this sequence:

1_pressed
2_pressed
1_released
2_released

Expected Output: "12"
Resulting Output: "2"

Do you know how I can fix my code to avoid this?  Please forgive the formatting, I keep it tight so that it's more readable with all the neighboring commands.

`{`
`          "type": "basic",`
`          "from": {"key_code": "1"},`
`          "to_if_alone": [{"key_code": "1"}],`
`          "to_if_held_down": [{"key_code": "1", "modifiers": ["left_control","left_command"]}]`
`        },`

Thanks!

**Comment by Jimmy34742** [comment]
To solve this problem, I adapted my typing technique to eliminate overlapping. Yes, that's been annoying, kind of like learning to use a fork in the opposite hand. Now that I'm 90% used to it, the staccato style of typing produces significantly fewer--even zero--typos, but your forearms have to be at the correct typing angle above the keyboard, or else it becomes unduly difficult. So you always have to have a proper seat/table combo. I'm still deciding if this is ultimately better typing technique because I'm still gradually recovering my typing speed. I've looked for online comments regarding the two typing styles, and have found nothing at all.

**Comment by handcoding** [comment]
> The following code works in that the correct keyset is sent when I hold "1". However, in normal typing if I happen to overlap another key with "1" then the "1" is never sent.

@StitiS, @Jimmy34742: I think I may have a solution for this:

```
{
    "description": "Hold '1' for Ctrl+Command+1",
    "manipulators": [
        {
            "from": {
                "key_code": "1",
                "modifiers": {
                    "mandatory": [],
                    "optional": [
                        "caps_lock"
                    ]
                }
            },
            "parameters": {
                "basic.to_delayed_action_delay_milliseconds": 200,
                "basic.to_if_held_down_threshold_milliseconds": 200
            },
            "to_delayed_action": {
                "to_if_canceled": [
                    {
                        "key_code": "1",
                        "modifiers": []
                    }
                ]
            },
            "to_if_alone": [
                {
                    "key_code": "1",
                    "modifiers": [],
                    "halt": true
                }
            ],
            "to_if_held_down": [
                {
                    "key_code": "1",
                    "modifiers": [
                    		"left_control",
                    		"left_command"
                    	],
                    "halt": true,
                    "repeat": false
                }
            ],
            "type": "basic"
        }
    ]
},
```

(big props to @elasticdog [for figuring out this technique](https://github.com/tekezo/Karabiner-Elements/issues/1207#issuecomment-476023931))
