### ISSUE TITLE
Controlling Caps Lock LED during Complex Modifications

### ISSUE THREAD

**Issue by etranger** [tekezo/Karabiner-Elements#1257]
Recent addition of `select_input_source` event is a very welcome change for those of us who need to use two keyboard layouts on a regular basis.

Assigning this event to a Caps Lock key is a natural choice since its LED can act as an indicator for the currently selected input source.

However, with this configuration the LED just stays off:

```                                
"to": [
  {
    "select_input_source": {
      "input_source_id": "^org.sil.ukelele.keyboardlayout.t.russian-ilyabirmantypography$"
    }
  }
],
```

And with this one it blinks shortly and still remains off:

```
"to": [
  {
    "key_code": "caps_lock"
  }
 ],
"to_if_alone": [
  {
    "select_input_source": {
      "input_source_id": "^org.sil.ukelele.keyboardlayout.t.russian-ilyabirmantypography$"
    }
  }
],
```

Desired feature: an option to control whether the Caps Lock LED stays on or off after the event;

Relevant Karabiner Elements version: 11.5.4 (beta channel)

**Comment by icanswiftabit** [comment]
I'm in the same situation. caps_lock is my toggle key but I often don't remember in which state I'm. If not controlling led, then maybe some menubar/desktop indicator?

**Comment by etranger** [comment]
Any hope that this issues will be looked into...?

**Comment by icanswiftabit** [comment]
I ended up buying ergodox :)

**Comment by frankyjuang** [comment]
any updates here?

**Comment by levensailor** [comment]
I'm using CAPS LOCK as a Microphone Mute since I'm in a lot of conference calls in a noisy apartment. Would be so happy to have the LED indicate whether i'm on hot mic!

**Comment by levensailor** [comment]
Actually I just fixed my issue by adding the caps_lock back. if you remap keys, the original key is never pressed, which it needs to set the led state.

**Comment by levensailor** [comment]
Actually i'm an idiot, still need led only :)

**Comment by lessing** [comment]
+1 for this, LED as indicator for a certain input source would be awesome

**Comment by olets** [comment]
Bumping to keep @stale from closing. Sorry for the noise

**Comment by olets** [comment]
Ditto

**Comment by etranger** [comment]
Bumping this to attract some attention given other recent fixes for LED support in Mojave.

**Comment by gretel** [comment]
seems to be fixed according to the changelog of the latest beta. but how does it actually gets controlled?

**Comment by olets** [comment]
bump to prevent stalebot closure

**Comment by seaofclouds** [comment]
bump to prevent stalebot closure

**Comment by gretel** [comment]
well i tried again.. and still dont have no clue.

**Comment by olets** [comment]
@tekezo thoughts about reopening this? I admit I haven't tested in a while, but based on the discussion here it doesn't sound like this has been worked on

**Comment by kimslawson** [comment]
I would also love the ability to control indicator status to show which layer of my keyboard is active. Can this be a thing?

**Comment by etranger** [comment]
Managed to get this working: 

```
        "manipulators": [{
            "conditions": [{
              "input_sources": [{
                "language": "ru"
              }],
              "type": "input_source_unless"
            }],
            "from": {
              "key_code": "caps_lock",
              "modifiers": {
                "optional": [
                  "any"
                ]
              }
            },
            "to": [{
              "key_code": "caps_lock"
            }],
            "to_if_alone": [{
                "select_input_source": {
                  "input_source_id": "^org.sil.ukelele.keyboardlayout.t.russian-ilyabirmantypography$"
                }
              },
              {
                "key_code": "caps_lock",
                "hold_down_milliseconds": 100
              },
              {
                "key_code": "vk_none"
              }
            ],
            "type": "basic"
          },
          {
            "conditions": [{
              "input_sources": [{
                "language": "en"
              }],
              "type": "input_source_unless"
            }],
            "from": {
              "key_code": "caps_lock",
              "modifiers": {
                "optional": [
                  "any"
                ]
              }
            },
            "to_if_alone": [{
              "select_input_source": {
                "input_source_id": "^org.sil.ukelele.keyboardlayout.t.english-ilyabirmantypography$"
              }
            }],
            "type": "basic"
          }
        ]
      }]
```

**Comment by carlsmith** [comment]
A lot of people would really appreciate a response on this.

**Comment by Roobxyz** [comment]
bump - not stale - real feature request

**Comment by olets** [comment]
@pqrs-org don't know if you're seeing this since it's closed

**Comment by chrisgrieser** [comment]
I'd also love this feature. LED light to indicate modes oder leader keys would be a really nice addition

**Comment by salahwar0** [comment]
guys its two days now n I am trying to solve this issue but nothing yet omg the leds :(

**Comment by revolter** [comment]
Revived this with #3493.

**Comment by csutora** [comment]
is this planned at all? the caps lock led could be one of the most useful and clean indicators out there for a ton of use cases

**Comment by olets** [comment]
@csutora consider upvoting the open revival issue linked in https://github.com/pqrs-org/Karabiner-Elements/issues/1257#issuecomment-1553298286

**Comment by csutora** [comment]
> [@csutora](https://github.com/csutora) consider upvoting the open revival issue linked in [#1257 (comment)](https://github.com/pqrs-org/Karabiner-Elements/issues/1257#issuecomment-1553298286)

thanks, that was my first thing to do when i found the issue. i commented because i felt that wasn't enough. i'm now looking at the source code but i don't have remotely enough knowledge about low-level apple stuff to even know where to start.

**Comment by fathonix** [comment]
This issue ended up having two duplicates with #3493 and #3173. That said, I settled on relying to [setledsmac](https://github.com/damieng/setledsmac) mentioned on [#3173 (comment)](https://github.com/pqrs-org/Karabiner-Elements/issues/3173#issuecomment-1217407947)
