### ISSUE TITLE
Karabiner Kills Some Touch Bar / Control Strip Functions

### ISSUE THREAD

**Issue by JuliaTruchsess** [tekezo/Karabiner-Elements#1259]
When Karabiner is installed, the keyboard backlight controls (which I need) doesn't work, and the exposé / launchpad stuff (which I don't need) also doesn't work. If you have the screen brightness up/down buttons loaded they don't work either, but the slider does work. The soft keys highlight but they don't perform their functions. The one and only mapping I have set in Karabiner is right Option to Enter. Uninstall Karabiner and these Touch Bar buttons work. Install Karabiner and they don't.

Mac OS 10.13.3, 2018 MacBook Pro, current Karabiner release.

**Comment by Jimmy34742** [comment]
Works with my Touch Bar, no problem.

**Comment by wox** [comment]
Same problem, same setup. I can fix this by disabling some unknown device in the settings.
![screen shot devices](https://user-images.githubusercontent.com/40752/35904948-66dc75f8-0be5-11e8-95b3-58b926925e11.png)

**Comment by JuliaTruchsess** [comment]
Thank you, wox!

**Comment by tkaufmann** [comment]
Hasn't been enabled for me, toggling the checkbox twice didn't help. Stuck.
