### ISSUE TITLE
Karabiner doesnt work for me  + Pressed key log msg

### ISSUE THREAD

**Issue by jacobkaucher** [tekezo/Karabiner-Elements#126]
My key presses show up in karabiner-eventviewer and I think my JSON is setup up correctly.  could this have to do with previously using karabiner or perhaps from my spacebar legitimately being broken? all help is appreciated!

I also have this msg scrolling in the log:
[2016-09-24 00:20:36.057] [grabber] [warning] There are pressed down keys in Apple Internal Keyboard / Trackpad. Please release them.

```
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "right_alt": "spacebar",
                "right_option": "spacebar",
                "right_gui": "spacebar",
                "right_command": "spacebar"

            }
        }
    ]
}
```

**Comment by tekezo** [comment]
I believe this issue has been fixed in the latest version.
