### ISSUE TITLE
karabiner_grabber is flagged as malware by Avast and AVG

### ISSUE THREAD

**Issue by eyemyth** [tekezo/Karabiner-Elements#1270]
I think this is likely erroneous, but I noticed this: https://www.virustotal.com/en/file/2fab838c9774c97bc162a48c7feaaeca1e491879e487a1c0203d005f44dbc804/analysis/

I figured I'd flag it, just in case something nasty actually made it's way into Karabiner.

**Comment by tekezo** [comment]
Thank you for feedback!
It's false alarm.

I reported this false detection to avast and avg.
https://www.avast.com/false-positive-file-form.php
https://secure.avg.com/submit-sample

**Comment by AriaMinaei** [comment]
Still flagged by TrendMicro-HouseCall: https://www.virustotal.com/en/file/2fab838c9774c97bc162a48c7feaaeca1e491879e487a1c0203d005f44dbc804/analysis/

**Comment by tekezo** [comment]
@AriaMinaei 
Thank you for feedback!
I reported as a false alarm to TrendMicro-HouseCall.

**Comment by ujetjeremy** [comment]
This is also flagged as malware by Cortex XDR. https://docs.paloaltonetworks.com/cortex/cortex-xdr/7-0/cortex-xdr-agent-admin/cortex-xdr-agent-for-mac.html
