### ISSUE TITLE
how to adjust timing that's considered simultaneous?

### ISSUE THREAD

**Issue by Jimmy34742** [tekezo/Karabiner-Elements#1272]
I'm getting a lot of missed simultaneous keypresses. In other words, they feel reasonably simultaneous to me when typed, but Karabiner isn't detecting the two keys as simultaneous. Is there some sort of parameter available to adjust the timing of what K-E will detect as simultaneous?

**Comment by tekezo** [comment]
You can adjust on Preferences > Complex Modifications > Parameters in the latest beta version.

![180216-0001](https://user-images.githubusercontent.com/659178/36293764-03ea2134-131f-11e8-9de3-ebb4337cb21f.png)

**Comment by Jimmy34742** [comment]
Thanks. I've now messed around with the threshold parameter, but I still get a lot of missed 2-key chords, even when I'm careful to type the same way. I can't seem to hit on a combination of technique and threshold parameter that will enable me to reproduce chords reliably.

**Comment by tekezo** [comment]
I've improved `simultaneous` behavior at the latest beta version (v11.5.10).
You can use the larger threshold value with least input events delay.

**Comment by Jimmy34742** [comment]
Thanks. Here's what I'm experimenting with in case you have any comments. My launcher launches 81 different things (files, URL's, apps, Alfred workflows) using the 15 combinations of the a, s, d, and f keys to specify one of 15 modes with the left hand, then choosing what I want to launch with the right hand. For example:

`                            {
                                "conditions": [
                                    {
                                        "name": "a_modifier",
                                        "type": "variable_if",
                                        "value": 0
                                    },
                                    {
                                        "name": "s_modifier",
                                        "type": "variable_if",
                                        "value": 0
                                    },
                                    {
                                        "name": "d_modifier",
                                        "type": "variable_if",
                                        "value": 0
                                    },
                                    {
                                        "name": "f_modifier",
                                        "type": "variable_if",
                                        "value": 1
                                    }
                                ],
                                "from": {
                                    "key_code": "i"
                                },
                                "to": [
                                    {
                                        "shell_command": "open '/Applications/MyApp.app'"
                                    }
                                ],
                                "type": "basic"
                            }
`
Using simultaneous, that code would be:
			    {
                                "description": "fi",
				"from": {
				    "simultaneous": [
					{
					    "key_code": "f"
					},
					{
					    "key_code": "i"
					}
				    ]
				},
				"to": [
				    {
                                        "shell_command": "open '/Applications/MyApp.app'"
				    }
				],
				"type": "basic"
			    }

I've found that when I have too many modes (e.g., more than 20 keys used as modifiers), then regular typing must be precise and carefully separated, or else I accidentally actuate a key combo. It's rather annoying, but the price I pay to get the app switcher I want. With fewer modes (6 keys used as modifiers), it seems that typing timing is more forgiving. I guess 20 possible modifier keys put more strain on the CPU so that my slightly overlapped typing was too fast for the system. With 6 modifier keys, I'm making no errors at all.

I'm experimenting with whether going with all simultaneous and no modes will give a user experience. My main concern is that fuzzy simultaneity with the way I type chords will lead to too many errors where I get multiple errors of crap. With my 6-modifier keys non-simultaneous chords, I get no errors like that at all, but I'm limited to singletons for key combos once a mode is selected. The only advantage simultaneous would offer that I can see is that chords could consist of any combination of keys, giving more possible slots, which would make an all-home row launcher possible. Do you have any comment on the advantages and disadvantages of each way of doing things?
