### ISSUE TITLE
Quitting apps

### ISSUE THREAD

**Issue by BillTribble** [tekezo/Karabiner-Elements#1274]
I managed to modify someone's script to stop left-Cmd & Q from quitting apps (too easy on my dumb Macbook keyboard) with this - 
`{
                        "description": "Remap LCommand + q to q in any app",
                        "manipulators": [
                            {
                                "conditions": [],
                                "from": {
                                    "key_code": "q",
                                    "modifiers": {
                                        "mandatory": [
                                            "left_command"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "q"
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    }`

But it would be nice to be able to use say alt+cmd+Q to quit apps. 

Can anyone give me a hint on how to add this?

**Comment by dunkarooftop** [comment]
https://pqrs.org/osx/karabiner/json.html

search "Change escape to tab with optional modifiers"

**Comment by BillTribble** [comment]
Thanks dunkarooftop. 

Gave up on Karabiner for now, due to this (fn key shortcuts not working) https://github.com/tekezo/Karabiner-Elements/issues/1276

**Comment by alexhamidi** [comment]
> Thanks dunkarooftop.
> 
> Gave up on Karabiner for now, due to this (fn key shortcuts not working) #1276

Did you ever figure this out?
