### ISSUE TITLE
Can't remap media keys on Microsoft 600 Wired Keyboard

### ISSUE THREAD

**Issue by quickreactor** [tekezo/Karabiner-Elements#1275]
As above, trying to remap play pause, volume keys etc to useful functions and it doesn't work in Karabiner. Macbook pro touchbar. Please help!

http://prntscr.com/igmh95

**Comment by Hank-Chung** [comment]
you should check to and from.

**Comment by quickreactor** [comment]
My apologies, maybe I didn't phrase it properly. I don't want media functions, I want to turn them into keys in Premiere. Hence why they are on the from section.
