### ISSUE TITLE
"simultaneous" limited to two keys

### ISSUE THREAD

**Issue by Jimmy34742** [tekezo/Karabiner-Elements#1277]
With 11.5.10, I can't get K-E to recognize three keys pressed together. Only a combination of two out of the three keypresses ever registers. Is this currently a limitation? Are chords of >2 keys planned for the future?

**Comment by tekezo** [comment]
Karabiner-Elements does not limit the number of keys.

For example, this json allows you to open Safari by tab+f+l.
```
{
    "from": {
        "modifiers": {
            "optional": [
                "any"
            ]
        },
        "simultaneous": [
            {
                "key_code": "tab"
            },
            {
                "key_code": "f"
            },
            {
                "key_code": "l"
            }
        ]
    },
    "to": [
        {
            "shell_command": "open -a Safari.app"
        }
    ],
    "type": "basic"
}
```

## Note 1
`simultaneous` requires you to press these keys while all keys are pressed.
For example:
  1. tab key_down
  2. f key_down
  3. l key_down

If you release any key before all keys are pressed, Karabiner-Elements does not modify these keys.
For example:
1. tab key_down
2. f key_down
3. tab key_up
4. l key_down

## Note 2
If you are using generic keyboard, there is a hardware limitation 2-key rollover that you cannot press specific combination of 3 keys at once.
https://en.wikipedia.org/wiki/Rollover_(key)

**Comment by Jimmy34742** [comment]
Yes, I see it works in the expected way, but I'm getting a lot of misfires with 3-key chords. For example, using the combo d-g-j to launch Safari often triggers as the combo d-j, which launches my file browser. I've tried pressing the keys carefully to ensure correct timing, but the results vary with no clear pattern. My keyboard is my MacBook 12 (2017). I don't know about its hardware limitations with respect to the rollover issue, but the 3-key combo does register sometimes, just not consistently.

**Comment by tekezo** [comment]
You should take care of the order of manipulators in the json file.
If you placed "d-j" before "d-g-j" in json, Karabiner-Elements uses the first matched rule (d-j).

## About 2-key rollover.

You can confirm the hardware limitation by press key in EventViewer.
For example, tab+q+w are not recognized generally.

Holding down `tab` and `q` key, then typing `w` key will be ignored in EventViewer.
But `tab`, `q` and `a` keys will be shown in EventViewer.
The ignored combination is the limited ones.

**Comment by Jimmy34742** [comment]
Yes, the order of manipulators was the problem. I've cleaned up my json, and everything works fine. Except for j+k+l+semicolon, which apparently can't work on my MacBook 12.
