### ISSUE TITLE
"simultaneous" can't use "to_if_held_down"

### ISSUE THREAD

**Issue by Jimmy34742** [tekezo/Karabiner-Elements#1280]
I'd like to be able to have both chords and long-pressed chords, but "simultaneous" only works with "to". When I try "to_if_held_down" and "to_if_alone", the simultaneous keypresses have no effect.

**Comment by tekezo** [comment]
Thank you for feedback!
I confirmed this issue.
I'll fix it soon, please wait.

**Comment by Jimmy34742** [comment]
The fix is tested and working in 11.6.1. Thanks for fixing it so quickly.

**Comment by tekezo** [comment]
Thank you for confirmation!
