### ISSUE TITLE
no US " pound " key in list of elements 

### ISSUE THREAD

**Issue by InnovativeIdeas** [tekezo/Karabiner-Elements#1282]
one of the  most common thing on non us keyboards is to map the US Pound sign to a dedicated key as it doesnt appear on international Mac key tops . 

but its not in the default list of key elements that can be selected in the Simple Modifications ?

**Comment by ggoofer** [comment]
You cannot change it, or keys corresponding to any of the standard "shift" characters, with a simple modification. However a complex modification is easy to write.

The key code is: shift + 3. You can find this in EventViewer. (Shift will change both left and right shifts, or use right_shift / left_shift to change only one of them.)

Here's an example, which changes all American pounds (#) to British pounds (£).

```
{
  "title": "American pound to British pound",
  "rules": [
    {
      "description": "Change shift+3 to option+3",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "3",
            "modifiers": {
              "mandatory": [
                "shift"
              ],
              "optional": [
                "caps_lock"
              ]
            }
          },
          "to": [
            {
	      "key_code": "3",
	      "modifiers": [
                "left_option"
	      ]
	    }	
          ]
        }
      ]
    }
  ]
}

```

**Comment by kokoskiwi** [comment]
> You cannot change it, or keys corresponding to any of the standard "shift" characters, with a simple modification. However a complex modification is easy to write.
> 
> The key code for "#" is: shift + 3. You can find this in EventViewer. (Actually, EventViewer would tell you "left_shift" or "right_shift"; use those to refer to a specific left or right shift key. Or you can use "shift" to refer to any shift key.)
> 
> Here's an example, which changes all American pounds (#) to British pounds (£), which is option + 3 on a Mac keyboard.
> 
> ```
> {
>   "title": "American pound to British pound",
>   "rules": [
>     {
>       "description": "Change shift+3 to option+3",
>       "manipulators": [
>         {
>           "type": "basic",
>           "from": {
>             "key_code": "3",
>             "modifiers": {
>               "mandatory": [
>                 "shift"
>               ],
>               "optional": [
>                 "caps_lock"
>               ]
>             }
>           },
>           "to": [
>             {
> 	      "key_code": "3",
> 	      "modifiers": [
>                 "left_option"
> 	      ]
> 	    }	
>           ]
>         }
>       ]
>     }
>   ]
> }
> ```

@ggoofer can you help me 
https://github.com/pqrs-org/Karabiner-Elements/issues/3691
