### ISSUE TITLE
Complex modifications priority not respected for modifier keys

### ISSUE THREAD

**Issue by justingrant** [tekezo/Karabiner-Elements#1283]
According to the manual (https://pqrs.org/osx/karabiner/json.html#complex_modifications-manipulator-priority) complex_modifications are processed in order: 
> The manipulators are evaluated from the top to the bottom and the input event is manipulated only the first matched manipulator.
>
> In other words, if there are multiple manipulators which change the same key, the manipulator placed at the top is applied and other manipulators are ignored.

This doesn't work as documented when a lower-down rule manipulates a modifier key (e.g. swapping Command and Control when using Parallels) and a higher-priority rule manipulates a non-modifier key (e.g. preventing swapping Command with Control when Command+Tab or Control+Tab are pressed). 

Is this a product bug?  If not, then the documentation for above should probably clarify that this use-case won't work. 

Here's an excerpt from rules I'm using that shows the problem. 

            "rules": [{
                "description": "Swap command and control in virtual machine/remote desktop",
                "manipulators": [{
                        "conditions": [{
                            "bundle_identifiers": [
                                "^com\\.vmware\\.fusion$",
                                "^com\\.vmware\\.horizon$",
                                "^com\\.vmware\\.view$",
                                "^com\\.parallels\\.desktop$",
                                "^com\\.parallels\\.vm$",
                                "^com\\.parallels\\.desktop\\.console$",
                                "^org\\.virtualbox\\.app\\.VirtualBoxVM$",
                                "^com\\.vmware\\.proxyApp\\.",
                                "^com\\.parallels\\.winapp\\.",
                                "^com\\.microsoft\\.rdc$",
                                "^com\\.microsoft\\.rdc\\.mac$",
                                "^com\\.microsoft\\.rdc\\.osx\\.beta$",
                                "^net\\.sf\\.cord$",
                                "^com\\.thinomenon\\.RemoteDesktopConnection$",
                                "^com\\.itap-mobile\\.qmote$",
                                "^com\\.nulana\\.remotixmac$",
                                "^com\\.p5sys\\.jump\\.mac\\.viewer$",
                                "^com\\.p5sys\\.jump\\.mac\\.viewer\\.web$",
                                "^com\\.teamviewer\\.TeamViewer$",
                                "^com\\.vmware\\.horizon$",
                                "^com\\.2X\\.Client\\.Mac$"
                            ],
                            "type": "frontmost_application_if"
                        }],
                        "from": {
                            "key_code": "tab",
                            "modifiers": {
                                "optional": [
                                    "any"
                                ]
                            }
                        },
                        "to": [{
                            "key_code": "tab"
                        }],
                        "type": "basic"
                    },
                    {
                        "conditions": [{
                            "bundle_identifiers": [
                                "^com\\.vmware\\.fusion$",
                                "^com\\.vmware\\.horizon$",
                                "^com\\.vmware\\.view$",
                                "^com\\.parallels\\.desktop$",
                                "^com\\.parallels\\.vm$",
                                "^com\\.parallels\\.desktop\\.console$",
                                "^org\\.virtualbox\\.app\\.VirtualBoxVM$",
                                "^com\\.vmware\\.proxyApp\\.",
                                "^com\\.parallels\\.winapp\\.",
                                "^com\\.microsoft\\.rdc$",
                                "^com\\.microsoft\\.rdc\\.mac$",
                                "^com\\.microsoft\\.rdc\\.osx\\.beta$",
                                "^net\\.sf\\.cord$",
                                "^com\\.thinomenon\\.RemoteDesktopConnection$",
                                "^com\\.itap-mobile\\.qmote$",
                                "^com\\.nulana\\.remotixmac$",
                                "^com\\.p5sys\\.jump\\.mac\\.viewer$",
                                "^com\\.p5sys\\.jump\\.mac\\.viewer\\.web$",
                                "^com\\.teamviewer\\.TeamViewer$",
                                "^com\\.vmware\\.horizon$",
                                "^com\\.2X\\.Client\\.Mac$"
                            ],
                            "type": "frontmost_application_if"
                        }],
                        "from": {
                            "key_code": "left_control",
                            "modifiers": {
                                "optional": [
                                    "any"
                                ]
                            }
                        },
                        "to": [{
                            "key_code": "left_command"
                        }],
                        "type": "basic"
                    },
                    {
                        "conditions": [{
                            "bundle_identifiers": [
                                "^com\\.vmware\\.fusion$",
                                "^com\\.vmware\\.horizon$",
                                "^com\\.vmware\\.view$",
                                "^com\\.parallels\\.desktop$",
                                "^com\\.parallels\\.vm$",
                                "^com\\.parallels\\.desktop\\.console$",
                                "^org\\.virtualbox\\.app\\.VirtualBoxVM$",
                                "^com\\.vmware\\.proxyApp\\.",
                                "^com\\.parallels\\.winapp\\.",
                                "^com\\.microsoft\\.rdc$",
                                "^com\\.microsoft\\.rdc\\.mac$",
                                "^com\\.microsoft\\.rdc\\.osx\\.beta$",
                                "^net\\.sf\\.cord$",
                                "^com\\.thinomenon\\.RemoteDesktopConnection$",
                                "^com\\.itap-mobile\\.qmote$",
                                "^com\\.nulana\\.remotixmac$",
                                "^com\\.p5sys\\.jump\\.mac\\.viewer$",
                                "^com\\.p5sys\\.jump\\.mac\\.viewer\\.web$",
                                "^com\\.teamviewer\\.TeamViewer$",
                                "^com\\.vmware\\.horizon$",
                                "^com\\.2X\\.Client\\.Mac$"
                            ],
                            "type": "frontmost_application_if"
                        }],
                        "from": {
                            "key_code": "right_control",
                            "modifiers": {
                                "optional": [
                                    "any"
                                ]
                            }
                        },
                        "to": [{
                            "key_code": "right_command"
                        }],
                        "type": "basic"
                    },
                    {
                        "conditions": [{
                            "bundle_identifiers": [
                                "^com\\.vmware\\.fusion$",
                                "^com\\.vmware\\.horizon$",
                                "^com\\.vmware\\.view$",
                                "^com\\.parallels\\.desktop$",
                                "^com\\.parallels\\.vm$",
                                "^com\\.parallels\\.desktop\\.console$",
                                "^org\\.virtualbox\\.app\\.VirtualBoxVM$",
                                "^com\\.vmware\\.proxyApp\\.",
                                "^com\\.parallels\\.winapp\\.",
                                "^com\\.microsoft\\.rdc$",
                                "^com\\.microsoft\\.rdc\\.mac$",
                                "^com\\.microsoft\\.rdc\\.osx\\.beta$",
                                "^net\\.sf\\.cord$",
                                "^com\\.thinomenon\\.RemoteDesktopConnection$",
                                "^com\\.itap-mobile\\.qmote$",
                                "^com\\.nulana\\.remotixmac$",
                                "^com\\.p5sys\\.jump\\.mac\\.viewer$",
                                "^com\\.p5sys\\.jump\\.mac\\.viewer\\.web$",
                                "^com\\.teamviewer\\.TeamViewer$",
                                "^com\\.vmware\\.horizon$",
                                "^com\\.2X\\.Client\\.Mac$"
                            ],
                            "type": "frontmost_application_if"
                        }],
                        "from": {
                            "key_code": "left_command",
                            "modifiers": {
                                "optional": [
                                    "any"
                                ]
                            }
                        },
                        "to": [{
                            "key_code": "left_control"
                        }],
                        "type": "basic"
                    },
                    {
                        "conditions": [{
                            "bundle_identifiers": [
                                "^com\\.vmware\\.fusion$",
                                "^com\\.vmware\\.horizon$",
                                "^com\\.vmware\\.view$",
                                "^com\\.parallels\\.desktop$",
                                "^com\\.parallels\\.vm$",
                                "^com\\.parallels\\.desktop\\.console$",
                                "^org\\.virtualbox\\.app\\.VirtualBoxVM$",
                                "^com\\.vmware\\.proxyApp\\.",
                                "^com\\.parallels\\.winapp\\.",
                                "^com\\.microsoft\\.rdc$",
                                "^com\\.microsoft\\.rdc\\.mac$",
                                "^com\\.microsoft\\.rdc\\.osx\\.beta$",
                                "^net\\.sf\\.cord$",
                                "^com\\.thinomenon\\.RemoteDesktopConnection$",
                                "^com\\.itap-mobile\\.qmote$",
                                "^com\\.nulana\\.remotixmac$",
                                "^com\\.p5sys\\.jump\\.mac\\.viewer$",
                                "^com\\.p5sys\\.jump\\.mac\\.viewer\\.web$",
                                "^com\\.teamviewer\\.TeamViewer$",
                                "^com\\.vmware\\.horizon$",
                                "^com\\.2X\\.Client\\.Mac$"
                            ],
                            "type": "frontmost_application_if"
                        }],
                        "from": {
                            "key_code": "right_command",
                            "modifiers": {
                                "optional": [
                                    "any"
                                ]
                            }
                        },
                        "to": [{
                            "key_code": "right_control"
                        }],
                        "type": "basic"
                    }
                ]
            }]
        }

**Comment by tekezo** [comment]
Karabiner-Elements is working as documented.

Karabiner-Elements search the first matched manipulator for each input events.
So, if you pressed command key, `change command to control` is applied and then
you pressed tab key, `change tab to tab` is applied.

If you want to keep command+tab, you should change control+tab to command+tab.
(And you should change shift key as lazy shift key to use command+shift+tab.)

```
    {
        "from": {
            "key_code": "tab",
            "modifiers": {
                "mandatory": [
                    "control"
                ],
                "optional": [
                    "any"
                ]
            }
        },
        "to": [
            {
                "key_code": "tab",
                "modifiers": [
                    "left_command"
                ]
            }
        ],
        "type": "basic"
    },

    {
        "from": {
            "key_code": "left_shift",
            "modifiers": {
                "optional": [
                    "any"
                ]
            }
        },
        "to": [
            {
                "key_code": "left_shift",
                "lazy": true
            }
        ],
        "type": "basic"
    },
    {
        "from": {
            "key_code": "right_shift",
            "modifiers": {
                "optional": [
                    "any"
                ]
            }
        },
        "to": [
            {
                "key_code": "right_shift",
                "lazy": true
            }
        ],
        "type": "basic"
    }
```

**Comment by justingrant** [comment]
OK now I understand. The modifiers in the "from" element are not the actual physical modifier keys being pressed, but instead could be remapped by previous manipulations. So by the time the second key (after the modifier) is pressed, the pressed-down modifier key state for the first key (e.g. Command) has already been remapped. This makes sense and makes it easy to do what I wanted to do. Thanks so much for the quick and clear explanation!

Your sample configuration works great. I did run into a weird problem after I applied it and next woke up from standby where the Enter key seemed to be stuck and was emitting endless newlines into apps. (All apps, not just the apps that my mappings were targeting.) Quitting and restarting Karabiner fixed it. I'll file another issue here in GitHub if I can get a consistent repro case. 

For others who may want to do the same thing as I did, here's the full set of rules I used to support Parallels, TeamViewer, and other VM/Remote Desktop apps, including excluding Command+Tab and Command+Spacebar from mapping: 
```
"rules": [{
    "description": "Swap command and control in VM/remote desktop, except Command+Tab and Command+Spacebar",
    "manipulators": [{
            "conditions": [{ "bundle_identifiers": ["^com\\.vmware\\.fusion$", "^com\\.vmware\\.horizon$", "^com\\.vmware\\.view$", "^com\\.parallels\\.desktop$", "^com\\.parallels\\.vm$", "^com\\.parallels\\.desktop\\.console$", "^org\\.virtualbox\\.app\\.VirtualBoxVM$", "^com\\.vmware\\.proxyApp\\.", "^com\\.parallels\\.winapp\\.", "^com\\.microsoft\\.rdc$", "^com\\.microsoft\\.rdc\\.mac$", "^com\\.microsoft\\.rdc\\.osx\\.beta$", "^net\\.sf\\.cord$", "^com\\.thinomenon\\.RemoteDesktopConnection$", "^com\\.itap-mobile\\.qmote$", "^com\\.nulana\\.remotixmac$", "^com\\.p5sys\\.jump\\.mac\\.viewer$", "^com\\.p5sys\\.jump\\.mac\\.viewer\\.web$", "^com\\.teamviewer\\.TeamViewer$", "^com\\.vmware\\.horizon$", "^com\\.2X\\.Client\\.Mac$"], "type": "frontmost_application_if" }],
            "from": {
                "key_code": "tab",
                "modifiers": {
                    "mandatory": ["control"],
                    "optional": ["any"]
                }
            },
            "to": [{
                "key_code": "tab",
                "modifiers": ["left_command"]
            }],
            "type": "basic"
        },
        {
            "conditions": [{ "bundle_identifiers": ["^com\\.vmware\\.fusion$", "^com\\.vmware\\.horizon$", "^com\\.vmware\\.view$", "^com\\.parallels\\.desktop$", "^com\\.parallels\\.vm$", "^com\\.parallels\\.desktop\\.console$", "^org\\.virtualbox\\.app\\.VirtualBoxVM$", "^com\\.vmware\\.proxyApp\\.", "^com\\.parallels\\.winapp\\.", "^com\\.microsoft\\.rdc$", "^com\\.microsoft\\.rdc\\.mac$", "^com\\.microsoft\\.rdc\\.osx\\.beta$", "^net\\.sf\\.cord$", "^com\\.thinomenon\\.RemoteDesktopConnection$", "^com\\.itap-mobile\\.qmote$", "^com\\.nulana\\.remotixmac$", "^com\\.p5sys\\.jump\\.mac\\.viewer$", "^com\\.p5sys\\.jump\\.mac\\.viewer\\.web$", "^com\\.teamviewer\\.TeamViewer$", "^com\\.vmware\\.horizon$", "^com\\.2X\\.Client\\.Mac$"], "type": "frontmost_application_if" }],
            "from": {
                "key_code": "tab",
                "modifiers": {
                    "mandatory": ["command"],
                    "optional": ["any"]
                }
            },
            "to": [{
                "key_code": "tab",
                "modifiers": ["left_control"]
            }],
            "type": "basic"
        },
        {
            "conditions": [{ "bundle_identifiers": ["^com\\.vmware\\.fusion$", "^com\\.vmware\\.horizon$", "^com\\.vmware\\.view$", "^com\\.parallels\\.desktop$", "^com\\.parallels\\.vm$", "^com\\.parallels\\.desktop\\.console$", "^org\\.virtualbox\\.app\\.VirtualBoxVM$", "^com\\.vmware\\.proxyApp\\.", "^com\\.parallels\\.winapp\\.", "^com\\.microsoft\\.rdc$", "^com\\.microsoft\\.rdc\\.mac$", "^com\\.microsoft\\.rdc\\.osx\\.beta$", "^net\\.sf\\.cord$", "^com\\.thinomenon\\.RemoteDesktopConnection$", "^com\\.itap-mobile\\.qmote$", "^com\\.nulana\\.remotixmac$", "^com\\.p5sys\\.jump\\.mac\\.viewer$", "^com\\.p5sys\\.jump\\.mac\\.viewer\\.web$", "^com\\.teamviewer\\.TeamViewer$", "^com\\.vmware\\.horizon$", "^com\\.2X\\.Client\\.Mac$"], "type": "frontmost_application_if" }],
            "from": {
                "key_code": "spacebar",
                "modifiers": {
                    "mandatory": ["control"],
                    "optional": ["any"]
                }
            },
            "to": [{
                "key_code": "spacebar",
                "modifiers": ["left_command"]
            }],
            "type": "basic"
        },
        {
            "conditions": [{ "bundle_identifiers": ["^com\\.vmware\\.fusion$", "^com\\.vmware\\.horizon$", "^com\\.vmware\\.view$", "^com\\.parallels\\.desktop$", "^com\\.parallels\\.vm$", "^com\\.parallels\\.desktop\\.console$", "^org\\.virtualbox\\.app\\.VirtualBoxVM$", "^com\\.vmware\\.proxyApp\\.", "^com\\.parallels\\.winapp\\.", "^com\\.microsoft\\.rdc$", "^com\\.microsoft\\.rdc\\.mac$", "^com\\.microsoft\\.rdc\\.osx\\.beta$", "^net\\.sf\\.cord$", "^com\\.thinomenon\\.RemoteDesktopConnection$", "^com\\.itap-mobile\\.qmote$", "^com\\.nulana\\.remotixmac$", "^com\\.p5sys\\.jump\\.mac\\.viewer$", "^com\\.p5sys\\.jump\\.mac\\.viewer\\.web$", "^com\\.teamviewer\\.TeamViewer$", "^com\\.vmware\\.horizon$", "^com\\.2X\\.Client\\.Mac$"], "type": "frontmost_application_if" }],
            "from": {
                "key_code": "spacebar",
                "modifiers": {
                    "mandatory": ["command"],
                    "optional": ["any"]
                }
            },
            "to": [{
                "key_code": "spacebar",
                "modifiers": ["left_control"]
            }],
            "type": "basic"
        },
        {
            "conditions": [{ "bundle_identifiers": ["^com\\.vmware\\.fusion$", "^com\\.vmware\\.horizon$", "^com\\.vmware\\.view$", "^com\\.parallels\\.desktop$", "^com\\.parallels\\.vm$", "^com\\.parallels\\.desktop\\.console$", "^org\\.virtualbox\\.app\\.VirtualBoxVM$", "^com\\.vmware\\.proxyApp\\.", "^com\\.parallels\\.winapp\\.", "^com\\.microsoft\\.rdc$", "^com\\.microsoft\\.rdc\\.mac$", "^com\\.microsoft\\.rdc\\.osx\\.beta$", "^net\\.sf\\.cord$", "^com\\.thinomenon\\.RemoteDesktopConnection$", "^com\\.itap-mobile\\.qmote$", "^com\\.nulana\\.remotixmac$", "^com\\.p5sys\\.jump\\.mac\\.viewer$", "^com\\.p5sys\\.jump\\.mac\\.viewer\\.web$", "^com\\.teamviewer\\.TeamViewer$", "^com\\.vmware\\.horizon$", "^com\\.2X\\.Client\\.Mac$"], "type": "frontmost_application_if" }],
            "from": {
                "key_code": "left_shift",
                "modifiers": {
                    "optional": ["any"]
                }
            },
            "to": [{
                "key_code": "left_shift",
                "lazy": true
            }],
            "type": "basic"
        },
        {
            "conditions": [{ "bundle_identifiers": ["^com\\.vmware\\.fusion$", "^com\\.vmware\\.horizon$", "^com\\.vmware\\.view$", "^com\\.parallels\\.desktop$", "^com\\.parallels\\.vm$", "^com\\.parallels\\.desktop\\.console$", "^org\\.virtualbox\\.app\\.VirtualBoxVM$", "^com\\.vmware\\.proxyApp\\.", "^com\\.parallels\\.winapp\\.", "^com\\.microsoft\\.rdc$", "^com\\.microsoft\\.rdc\\.mac$", "^com\\.microsoft\\.rdc\\.osx\\.beta$", "^net\\.sf\\.cord$", "^com\\.thinomenon\\.RemoteDesktopConnection$", "^com\\.itap-mobile\\.qmote$", "^com\\.nulana\\.remotixmac$", "^com\\.p5sys\\.jump\\.mac\\.viewer$", "^com\\.p5sys\\.jump\\.mac\\.viewer\\.web$", "^com\\.teamviewer\\.TeamViewer$", "^com\\.vmware\\.horizon$", "^com\\.2X\\.Client\\.Mac$"], "type": "frontmost_application_if" }],
            "from": {
                "key_code": "right_shift",
                "modifiers": {
                    "optional": ["any"]
                }
            },
            "to": [{
                "key_code": "right_shift",
                "lazy": true
            }],
            "type": "basic"
        },
        {
            "conditions": [{ "bundle_identifiers": ["^com\\.vmware\\.fusion$", "^com\\.vmware\\.horizon$", "^com\\.vmware\\.view$", "^com\\.parallels\\.desktop$", "^com\\.parallels\\.vm$", "^com\\.parallels\\.desktop\\.console$", "^org\\.virtualbox\\.app\\.VirtualBoxVM$", "^com\\.vmware\\.proxyApp\\.", "^com\\.parallels\\.winapp\\.", "^com\\.microsoft\\.rdc$", "^com\\.microsoft\\.rdc\\.mac$", "^com\\.microsoft\\.rdc\\.osx\\.beta$", "^net\\.sf\\.cord$", "^com\\.thinomenon\\.RemoteDesktopConnection$", "^com\\.itap-mobile\\.qmote$", "^com\\.nulana\\.remotixmac$", "^com\\.p5sys\\.jump\\.mac\\.viewer$", "^com\\.p5sys\\.jump\\.mac\\.viewer\\.web$", "^com\\.teamviewer\\.TeamViewer$", "^com\\.vmware\\.horizon$", "^com\\.2X\\.Client\\.Mac$"], "type": "frontmost_application_if" }],
            "from": {
                "key_code": "left_control",
                "modifiers": {
                    "optional": ["any"]
                }
            },
            "to": [{
                "key_code": "left_command"
            }],
            "type": "basic"
        },
        {
            "conditions": [{ "bundle_identifiers": ["^com\\.vmware\\.fusion$", "^com\\.vmware\\.horizon$", "^com\\.vmware\\.view$", "^com\\.parallels\\.desktop$", "^com\\.parallels\\.vm$", "^com\\.parallels\\.desktop\\.console$", "^org\\.virtualbox\\.app\\.VirtualBoxVM$", "^com\\.vmware\\.proxyApp\\.", "^com\\.parallels\\.winapp\\.", "^com\\.microsoft\\.rdc$", "^com\\.microsoft\\.rdc\\.mac$", "^com\\.microsoft\\.rdc\\.osx\\.beta$", "^net\\.sf\\.cord$", "^com\\.thinomenon\\.RemoteDesktopConnection$", "^com\\.itap-mobile\\.qmote$", "^com\\.nulana\\.remotixmac$", "^com\\.p5sys\\.jump\\.mac\\.viewer$", "^com\\.p5sys\\.jump\\.mac\\.viewer\\.web$", "^com\\.teamviewer\\.TeamViewer$", "^com\\.vmware\\.horizon$", "^com\\.2X\\.Client\\.Mac$"], "type": "frontmost_application_if" }],
            "from": {
                "key_code": "right_control",
                "modifiers": {
                    "optional": ["any"]
                }
            },
            "to": [{
                "key_code": "right_command"
            }],
            "type": "basic"
        },
        {
            "conditions": [{ "bundle_identifiers": ["^com\\.vmware\\.fusion$", "^com\\.vmware\\.horizon$", "^com\\.vmware\\.view$", "^com\\.parallels\\.desktop$", "^com\\.parallels\\.vm$", "^com\\.parallels\\.desktop\\.console$", "^org\\.virtualbox\\.app\\.VirtualBoxVM$", "^com\\.vmware\\.proxyApp\\.", "^com\\.parallels\\.winapp\\.", "^com\\.microsoft\\.rdc$", "^com\\.microsoft\\.rdc\\.mac$", "^com\\.microsoft\\.rdc\\.osx\\.beta$", "^net\\.sf\\.cord$", "^com\\.thinomenon\\.RemoteDesktopConnection$", "^com\\.itap-mobile\\.qmote$", "^com\\.nulana\\.remotixmac$", "^com\\.p5sys\\.jump\\.mac\\.viewer$", "^com\\.p5sys\\.jump\\.mac\\.viewer\\.web$", "^com\\.teamviewer\\.TeamViewer$", "^com\\.vmware\\.horizon$", "^com\\.2X\\.Client\\.Mac$"], "type": "frontmost_application_if" }],
            "from": {
                "key_code": "left_command",
                "modifiers": {
                    "optional": ["any"]
                }
            },
            "to": [{
                "key_code": "left_control"
            }],
            "type": "basic"
        },
        {
            "conditions": [{ "bundle_identifiers": ["^com\\.vmware\\.fusion$", "^com\\.vmware\\.horizon$", "^com\\.vmware\\.view$", "^com\\.parallels\\.desktop$", "^com\\.parallels\\.vm$", "^com\\.parallels\\.desktop\\.console$", "^org\\.virtualbox\\.app\\.VirtualBoxVM$", "^com\\.vmware\\.proxyApp\\.", "^com\\.parallels\\.winapp\\.", "^com\\.microsoft\\.rdc$", "^com\\.microsoft\\.rdc\\.mac$", "^com\\.microsoft\\.rdc\\.osx\\.beta$", "^net\\.sf\\.cord$", "^com\\.thinomenon\\.RemoteDesktopConnection$", "^com\\.itap-mobile\\.qmote$", "^com\\.nulana\\.remotixmac$", "^com\\.p5sys\\.jump\\.mac\\.viewer$", "^com\\.p5sys\\.jump\\.mac\\.viewer\\.web$", "^com\\.teamviewer\\.TeamViewer$", "^com\\.vmware\\.horizon$", "^com\\.2X\\.Client\\.Mac$"], "type": "frontmost_application_if" }],
            "from": {
                "key_code": "right_command",
                "modifiers": {
                    "optional": [
                        "any"
                    ]
                }
            },
            "to": [{
                "key_code": "right_control"
            }],
            "type": "basic"
        }
    ]
}]
```
