### ISSUE TITLE
Change Command+tab to Option+tab modifier no longer works as intended

### ISSUE THREAD

**Issue by Danielsns** [tekezo/Karabiner-Elements#1285]
Hi,

I have been using a complex modifier to swap the "Command"+"tab" and "Option"+"tab" keys, it has been working fine until Friday. When "Tab" key is released the application switcher now disappears.

When I remove the complex modifier the Application switcher remains until I release the "Command" key.

I tried to roll back to the previous version of Karabiner I was using prior to the most recent update but the issue still remains, I believe this may have been caused by an update to the Mac OS.

Below is the .json file I use for this modifier:

{
  "title": "Exchange Command+Tab (generally 'cycle through applications') and Option+Tab (generally 'cycle through tabs')",
  "rules": [
    {
      "description": "Change Command+Tab to Option+Tab",
      "manipulators": [
        {
          "from": {
            "key_code": "tab",
            "modifiers": {
              "mandatory": [
                "command"
              ],
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "tab",
              "modifiers": [
                "option"
              ]
            }
          ],
          "type": "basic"
        }
      ]
    },
    {
      "description": "Change Option+Tab to Command+Tab",
      "manipulators": [
        {
          "from": {
            "key_code": "tab",
            "modifiers": {
              "mandatory": [
                "option"
              ],
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "tab",
              "modifiers": [
                "command"
              ]
            }
          ],
          "type": "basic"
        }
      ]
    }
  ]
}

Is there a modification I can make to this file to make the OS remember the mapping until I release the option key?

EDIT: I did see a similar thread to this, but when looking at the code to fix this issue it appears to match mine line for line for the command that I want.

**Comment by Danielsns** [comment]
The problem seems to have resolved itself, not sure what could have been causing the issue, will keep you posted on the status if the issue resurfaces.

**Comment by Danielsns** [comment]
So the problem has resurfaced, it appears to be intermittent.

**Comment by dqgthb** [comment]
Yeah it seems it works for a while, and then it stops working. This is strange cuz some mappings on switching option and command still work while others do not. Quite confusing.

**Comment by dqgthb** [comment]
Solution (not sure if this is temporary or permanent):

I checked the event viewer and it turned out everytime I pressed command, karabiner-elements interpreted the keystroke as "left_gui" and option key as "left_alt". After changing all the "left_command" and "left_option" to the corresponding new keycode in all of my custom complex json files, it started to work again.
