### ISSUE TITLE
Not working on High Sierra 10.13.3

### ISSUE THREAD

**Issue by claudiofrs** [tekezo/Karabiner-Elements#1286]
My Karabiner-Elements already at the latest version (11.6.0) but it seems no alert like previous version did to change Security & Privacy settings. And now my profile won't work.

**Comment by claudiofrs** [comment]
Working after recheck beta updates on setting, now it works. Sorry for the hassle.

**Comment by opdavies** [comment]
Same for me with `10.13.5`.
