### ISSUE TITLE
fn key does not cause Touch Bar to display function keys

### ISSUE THREAD

**Issue by samholmes** [tekezo/Karabiner-Elements#1288]
I'm using version 11.6.0 and when I hold down the fn key it does not modify my macbook's touch bar to display the function keys (f1, f2, f3, etc.) which is the standard behavior for Macbook's with a Touch Bar. I know this in an issue with Karabiner Elements because when I quit Karabiner Elements, the fn key behaves in this way.

**Comment by Jimmy34742** [comment]
https://github.com/tekezo/Karabiner-Elements/issues/1281

https://github.com/tekezo/Karabiner-Elements/issues/1259

**Comment by MindTooth** [comment]
Uninstalled for now..

**Comment by cjwd** [comment]
I have this same issue, had to stop using like @MindTooth

**Comment by samholmes** [comment]
Problem appears to be resolved in 12.0.0
