### ISSUE TITLE
app_expose key_code?

### ISSUE THREAD

**Issue by vbauerster** [tekezo/Karabiner-Elements#1289]
There is a `mission_control` key_code defined, and example is shown [here](https://pqrs.org/osx/karabiner/json.html#simultaneous).
I was pretty sure, that if there is a `mission_control` defined, then there should be its counterpart `app_expose` action. But it is not defined. Is it user definable?
By `app_expose` I mean ctrl+arrow_down action.

**Comment by zhongwei-z** [comment]
@ggoofer May I ask how do I map a key to a shortcut, say, control+down_arrow?

**Comment by ggoofer** [comment]
@zhongwei-z Try mimicking this example: [Karabiner-Elements/examples/left_option_tab_to_left_command_tab.json](https://github.com/tekezo/Karabiner-Elements/blob/master/examples/left_option_tab_to_left_command_tab.json) You just have to change the keys.

Your `from` is whatever you want the shortcut to be, let's say `"key_code": "e"`. Your `to` should be `"key_code": "down_arrow"` with either `left_control` or `right_control` as the modifier. You could delete the modifier in the from. Then you would map every "e" to expose.

A more sensible choice for a shortcut might have `from` as `"key_code": "."` (i.e. period) with mandatory modifier `command`. Then command + . would trigger expose.

`command`, `control`, etc. without saying which means "left or right". You can use it as shorthand in froms but cannot use it in to's. The `to` has to say exactly what key codes to output, so you have to specify

**Comment by vbauerster** [comment]
I'm using following to trigger app_expose with <kbd>ctrl</kbd>+<kbd>⬇︎</kbd>:
```js
{
    "title": "Simultaneous chords",
    "rules": [{
        "description": "df -> app_expose",
        "manipulators": [{
            "type": "basic",
            "from": {
                "simultaneous": [{
                        "key_code": "d"
                    },
                    {
                        "key_code": "f"
                    }
                ],
                "modifiers": {
                    "optional": [
                        "any"
                    ]
                }
            },
            "to": [{
                "key_code": "down_arrow",
                "modifiers": [
                    "left_control"
                ]
            }]
        }]
    }, {
        "description": "sf -> mission_control",
        "manipulators": [{
            "type": "basic",
            "from": {
                "simultaneous": [{
                        "key_code": "s"
                    },
                    {
                        "key_code": "f"
                    }
                ],
                "modifiers": {
                    "optional": [
                        "any"
                    ]
                }
            },
            "to": [{
                "key_code": "mission_control"
            }]
        }]
    }]
}
```

**Comment by zhongwei-z** [comment]
@ggoofer @vbauerster Thanks guys, much appreciated. Works like a charm :D

**Comment by ggoofer** [comment]
I forgot you can add modifiers to the preference pane shortcut. So you can save your good keys. Make it like alt shift command option F8 (unless you're using that;)

**Comment by maverickwoo** [comment]
For the future visitor:

* The effect of "Application windows", aka App Expose, can be achieved with `mission_control` modified with `left_control`.

* The effect of "Show Desktop" can be achieved with `mission_control` modified with `left_command`.

Tested on Mojave.

**Comment by ryanknutson** [comment]
For future-future visitors, the way to do App Exposé:
```
{
  "type": "basic",
  "from": { "key_code": "3" },
  "to": [
    {
      "apple_vendor_keyboard_key_code": "mission_control",
      "modifiers": ["left_control"]
    }
  ]
}
```

for Show Desktop, just switch left_control out with left_command :)

also, for switching spaces (virtual desktops):
```
"to": [ 
    {
        "key_code": "left_arrow", 
        "modifiers": ["left_control"]
    }
],
```
just change left_arrow with right_arrow to go the other way
