### ISSUE TITLE
Microsoft Natural Keybaord 4000 F13-15

### ISSUE THREAD

**Issue by djcmike** [tekezo/Karabiner-Elements#129]
After having all my other issues fixed, which is nice, I stumpled over that I no longer can en or decrease light on my iMac using F14 and F15. Any ideas?

**Comment by talha131** [comment]
@djcmike try adding following rules

```
"f14" : "vk_consumer_brightness_down",
"f15" : "vk_consumer_brightness_up"
```

**Comment by djcmike** [comment]
Hi again :)

No that didn't work either :/

**Comment by talha131** [comment]
Are you trying Fn+F14 to decrease brightness?

**Comment by djcmike** [comment]
No, I don't have an FN key on the keyboard.

**Comment by talha131** [comment]
Please try this for me,

```json
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "non_us_backslash": "grave_accent_and_tilde",
                "grave_accent_and_tilde" : "non_us_backslash"
            },
            "fn_function_keys": {
                "f14" : "vk_consumer_brightness_down",
                "f15" : "vk_consumer_brightness_up"
            }
        }
    ]
}
```

**Comment by djcmike** [comment]
No that didn't work either :/

**Comment by talha131** [comment]
Last attempt

From https://github.com/tekezo/Karabiner-Elements/issues/68#issuecomment-248698906

> you need to define all of the fn_function_keys and you also need to give it a moment or so after restarting karabiner-elements to actually take effect. 

You can copy rules for other fn keys from [here](https://github.com/tekezo/Karabiner-Elements/issues/62#issuecomment-248691996), add all of them to your configuration, and relaunch karabiner-elements.

**Comment by djcmike** [comment]
No no luck, I am afraid :(

**Comment by tluck** [comment]
This maps works for my ps2 keyboard:

"fn_function_keys": {
    "f1":  "vk_consumer_brightness_down",
    "f2":  "vk_consumer_brightness_up",
    "f3":  "vk_mission_control",
    "f4":  "vk_launchpad",
    "f5":  "vk_consumer_illumination_down",
    "f6":  "vk_consumer_illumination_up",
    "f7":  "vk_consumer_previous",
    "f8":  "vk_consumer_play",
    "f9":  "vk_consumer_next",
    "f10": "mute",
    "f11": "volume_down",
     "f12": "volume_up"
}

**Comment by djcmike** [comment]
"f1": "vk_consumer_brightness_down",
"f2": "vk_consumer_brightness_up",
This works for me as well, but not when using "f14" and "f15" Would have been nice to move things over there, since I use my fn keys a lot in terminal...

**Comment by xpert13** [comment]
I had the same problem with F13 ("Print Screen" key on my keyboard). Then I tried to use `"print_screen": "vk_consumer_brightness_up"` rule and it works like a charm.

**Comment by CorcoranEd** [comment]
I was having trouble with F13-15 but using xpert13's advice above can set those keys now using print_screen, scroll_lock and pause keys.

**Comment by incandescentman** [comment]
What fixed this problem for me is going to Devices > Modify events from this device, and disabling a extra keyboard that was listed there and checked but that is not the one I'm using.

**Comment by decadent** [comment]
Just adding a data point: I use the same keyboard, and scroll lock and pause adjust the brightness for me out of the box, regardless of whether function keys without Fn are enabled or disabled. So the issue seems to affect users differently. I'm on El Capitan 10.11.6.
