### ISSUE TITLE
Access variables by outside script

### ISSUE THREAD

**Issue by icanswiftabit** [tekezo/Karabiner-Elements#1292]
Is it possible to read Karabiner's variables by outside script or application?

**Comment by rdewolff** [comment]
Am wondering the same. Am using Karabiner-Elements in tandem with Hammerspoon and to enable complex scenario, I'd like to be able to share variables values (ideally read and write) with Hammerspoon.

Any API or info on that???

**Comment by rdewolff** [comment]
Maybe there is another way to achieve this : am wanting to display an indicator based on a variable value. For exemple, in VIM mode, I want to show when am in Insert mode or Visual mode.
