### ISSUE TITLE
mapping to modifier key only throws error

### ISSUE THREAD

**Issue by uloco** [tekezo/Karabiner-Elements#1293]
I mapped my `caps_lock` to `fn` and want to map `fn` + `d` to `shift` only.
According to the docs, this should be possible, as `key_code` and `modifiers` are both optional in the `to_event` block

```json
{
  "type": "basic",
  "from": {
    "key_code": "d",
    "modifiers": {
      "mandatory": ["fn"],
      "optional": ["any"]
    }
  },
  "to": [{
    "modifiers": ["shift"]
  }]
}
```

This throws me the following error:
`Invalid type in to_event_definition: {"modifiers":["shift"]}`

In the end, I want to implement this beautiful extended navigation layer on `caps_lock` originally made by Øystein Bech Gadmar

![image](https://user-images.githubusercontent.com/8818340/36908728-6384c82e-1e3c-11e8-99f1-fbbf2d446ea4.png)

This was possible in the past before sierra broke everything :(

The trickiest part will be the fn + d + f + ijkl for shift + cmd + arrow navigation to select words.
Is this even possible somehow?

**Comment by ggoofer** [comment]
Try replacing shift with right_shift (or left) in your "to" event definition.

I think shift is not actually a key code, but is shorthand: shift = left_shift OR right_shift. So it will work for "from"s but not for "to"s

**Comment by uloco** [comment]
Thanks for your response. I did not know, that modifiers can be used as key_codes, too. Using `left_shift` as `key_code` works, but does not have the effect as I want it to be. Right now, it simulates a shift press but does not respect the other mappings of fn + ijkl for arrow keys, though I defined optional modifiers as any.

I want `fn + d` when pressed and hold, to behave like I would pressing and holding shift and the other mappings on fn + ijkl should still be mapped as arrow keys.

So in the end, pressing `caps_lock + d + j` should mark the selected text one character to the left (like pressing natively shift + arrow left)

The next step would be to map `caps_lock + d + f + j`  to behave like `shift + option + arrow left`.

You can look into my actual `complex_modifications.json` here:
https://gist.github.com/uloco/b15a70c8a5a91bc58972808a37e15169

**Comment by ggoofer** [comment]
The natural thing to do, which is what you seem to be thinking, is to map `from`: fn + d to what you might call a `"to while held down"` "shift". I believe this is not possible currently, at least not directly. Any `to` event happens once and for all when the `from` condition is met.

First things first.

0. you should change `caps_lock` to `fn` with a simple modification. Then refer only to `fn` thereafter.

Now the biggest issue is that "d is held down" is not one of the standard built in modifiers. There are two ways to go that I can think of. You will have to do something semi-brute force either way. 

1. _from simultaneous_ -- Every manipulator includes the complete set of keys required for the command to execute. The `from` event is the simultaneous press of d + j, and requiring that fn is active. Here is one:
```        
/* one of these for every key */
{
  "from": {
    "simultaneous": [
      {
        "key_code": "d"
      },
      {
        "key_code": "j"
      }
    ],
    "modifiers": {
      "mandatory": [
        "fn"
      ]
  },
  "to": [
    {
      "key_code": "left_arrow"
      "modifiers": [
        "left_shift"
      ]
    }
  ]
}
```

2. _define a flag_ -- Define a flag that is set to 1 when d is pressed down (and mandatory modifier fn). The flag goes to 0 when d key goes up. For the j command, your from event will be 'j' and have a condition requiring that flag = 1. Your `to` will be the same as before.
```
/* one time at the beginning */
{
  "from": {
    "key_code": "d",
  },
  "to_after_key_up": [
    {
      "set_variable": { 
        "name": "fn_d flag"
        "value": 0
      }
  ]
},          
{
  "from": {
    "key_code": "d",
    "modifiers": {
      "mandatory": [
        "fn"
      ]
    }
  },
  "to": [
    {
     "set_variable": { 
        "name": "fn_d flag"
        "value": 1
    }
  ]
},
/* one of these for every key */ 
{
  "from": {
    "key_code": "j"
  },
  "to": [
    {
      "key_code": "left_arrow"
      "modifiers": [
        "left_shift"
      ]
    }
  ],
  "conditions": [
    {
      "type": "variable_if",
      "name": "fn_d flag",
      "value": 1
    }
  ]
}
```
Here is a somewhat mor complicated example that uses this idea: [mouse_keys_mode_v4.json](https://github.com/pqrs-org/KE-complex_modifications/blob/master/docs/json/mouse_keys_mode_v4.json)
Using the flag, the order of your manipulators will probably be important. On any key event, KE looks sequentially through your entire json, looks for the first valid "from" and triggers that manipulator, and then quits.

**Comment by uloco** [comment]
Thank you very much for your detailed answer. I will try implementing it keeping this in mind. 👍
