### ISSUE TITLE
Command Backtic doesn't work anymore

### ISSUE THREAD

**Issue by Arnoud76** [tekezo/Karabiner-Elements#1296]
Hello,

I had Installed Karabiner recently, but after installation the Combination key  Cmd + `  (= "cycle through windows") doesn't work anymore ( with any program like Finder, Google Chrome, Firefox, etc.). So I uninstalled it and now the combination key works fine again. It seems like this is a bug. Of course I'd like Karabiner to work well without having this problem. Does anyone recognize this problem and more important does anyone have a solution? 

MacOs 10.13.3 High Sierra
Karabiner-Elements 11.6.0
iMac
Apple Magic Keyboard

**Comment by Cpeters1982** [comment]
Did you have any rules that were overriding the placement of ` ? Any shortcuts using that key combo?

**Comment by Arnoud76** [comment]
No, I did not have any rules that were overriding the placement of ` .No shortcuts.
