### ISSUE TITLE
Mapping Fn Key to Media Control gets lost

### ISSUE THREAD

**Issue by CandideThunder** [tekezo/Karabiner-Elements#1297]
I am using a Lenovo Keyboard, it is recognised as USB NetVista Full Width Keyboard by Karabiners. Usually, it works very well. But by some unidentified circumstances, it stops working:
* most keys work as before
* The function keys do not work: They are not recognized anymore. In the Preferences / Function keys tab, all mapping physical to key are still entered. 

Restarting Karabiner Elements does not fix it.
Restarting osx does fix it.
Any suggestions for what could cause it, and how to correct it w/o reboot?

**Comment by jmcazaux** [comment]
I am suffering the same thing.
Using Dell USB Mechanical Keyboard.
