### ISSUE TITLE
In VM / RDC?

### ISSUE THREAD

**Issue by mkleehammer** [tekezo/Karabiner-Elements#13]
Is there any support for mapping keys only in some programs?  In particular I swap the Command and Option keys, but only for remote desktops and VMs.  For those wondering why, the Command key on a Mac keyboard is where an Alt key is on a Windows keyboard.
- Command_L --> Option_L (only in virtual machine, RDC)
- Option_L --> Command_L (only in virtual machine, RDC)

I'm happy to manually create the configuration file, but I don't see a way to restrict to particular programs or classes of programs.

(Honestly, I don't know why every RDC program for Mac doesn't already offer this.  I had to switch to Jump Desktop when I upgraded to Sierra and register every Alt key I use - and I'm an emacs user so there are tons.  But it still fails a lot.)

**Comment by billstclair** [comment]
I can't speak to whether Karabiner-Elements can or will be able to have different mappings for different applications, but I found a solution that works for me in Emacs. Add the following to the (custom-set-variables ...) section in your ~/.emacs file:

   '(ns-function-modifier (quote control))

Unfortunately, I still have to find the actual control key everywhere else, so I'm eager for the modifer-click bug to be fixed, so I can make the mapping system wide.

**Comment by christopherdwhite** [comment]
You might be able to do this on [Keyboard Maestro](https://www.keyboardmaestro.com/main/) for now.

**Comment by mike-savory** [comment]
I too want to swap Command and Control when I am in a specific application. +1 for the good work so far.

Unfortunately Keyboard Maestro fails to send modifier keys to both of Microsoft's Remote Desktop Applications (and the Developer say its Microsoft's fault). The beta app (Remote Desktop Beta 8.2.26) does at least have preference for changing Command XCV to Control XCV. The latest VMWare Fusion has built in extensive preferences for key mapping.

**Comment by twilly86** [comment]
what's the status of this issue?  i need to apply key bindings to remote desktop.
