### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by thecotne** [tekezo/Karabiner-Elements#130]
<img width="605" alt="screen shot 2016-09-22 at 8 55 08 pm" src="https://cloud.githubusercontent.com/assets/1606993/18808994/151f1164-8282-11e6-88fc-f3e9ca051fad.png">

i have this in Karabiner but after updating to MacOs Sierra that does not work so
i have installed Karabiner-Elements and i need to reproduce config that is no the screenshot in new `karabiner.json` 

currently i have this 
```json
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "non_us_backslash": "grave_accent_and_tilde",
                "backquote": "left_shift",
                "fn": "left_command"
            }
        }
    ]
}
```

`backquote` mapping to `left_shift` does not work 
and `fn` to `left_command` is not exactly same as `fn+letter to command+letter`

**Comment by talha131** [comment]
> and fn to left_command is not exactly same as fn+letter to command+letter

That cannot be done until #16 is fixed.

Can you try changing

```json
"backquote": "left_shift",
```

with 

```json
"grave_accent_and_tilde" : "left_shift",
```

**Comment by thecotne** [comment]
thx `"grave_accent_and_tilde" : "left_shift",` worked
