### ISSUE TITLE
Mouse scroll_up and scroll_down to key_code in Complex Modifications.

### ISSUE THREAD

**Issue by night-codes** [tekezo/Karabiner-Elements#1300]
Safari, Google Chrome, Sublime Text and many other applications have key combinations to switching open tabs. It would be good to assign of switching to next tab to **[Control + mouse Scroll Down]** and switching to previous tab to **[Control + mouse Scroll Up]** (for example).

**Comment by DKroot** [comment]
Please, please... Accidental zooms with Crtl+Scroll on Mac drive me nuts. Even though this "feature" can be disabled in Accessibility, apps like Chrome and Excel still have misguided support. I'd love to be able to disable this.
