### ISSUE TITLE
karabiner use hjkl for arrow keys

### ISSUE THREAD

**Issue by Gcaufy** [tekezo/Karabiner-Elements#1301]
I import this [Vim Mode (rev 4.3)](https://pqrs.org/osx/karabiner/complex_modifications/)
when I use `d` as the triggered key, when I type `sdk`, `dk` will be triggered. so I have to type this word slowly.

any way to avoid this? or is there any other suggested key mapping for vim mode?

**Comment by LoMiLiMiT** [comment]
I have a similar Issue. I use "sticky A+JKLI" to "arrow up/down/left/right".
I also have "Sticky A+S" assigned as "option_L". Now when i hold "A+S" i get "option_L", but when
i press one of the keys "JKLI", then i end up pressing "option_L+JKLI"......
Whats supposed to happen is that i get "option_L+Arrow_up etc."

I think that this is a bug as this has worked with ease in the old Karabiner.

**Comment by tekezo** [comment]
`Simple Vi Mode v3 (rev 2)` with the latest beta version is more comfortable s+hjkl operation.
https://pqrs.org/osx/karabiner/complex_modifications/#personal_tekezo_simple_vi_mode

How to upgrade to the latest beta version:
![Check for beta updates](https://pqrs.org/osx/karabiner/img/karabiner-elements-check-for-updates-beta@2x.png)

**Comment by Gcaufy** [comment]
I changed the trigger key to 'tab'
