### ISSUE TITLE
Add "Recently Received in EventViewer" section to simple modification dropdown

### ISSUE THREAD

**Issue by thecodewarrior** [tekezo/Karabiner-Elements#1302]
My particular mouse (Logitech MX Revolution. Several years old) goes all the way up to `button12`, but the simple modifications screen key dropdown only shows up to `button9`. This means that in order to map the higher numbers I have to manually write a complex modifications JSON file, which is tedious and difficult to change in the future.

I can't imagine I'm the only one who has problems with trying to map keys that don't appear in the dropdown, so while simply increasing the maximum button number would work, a more diversely applicable solution would be adding an "Recently Received in EventViewer" section in the selector which shows the buttons/keys that have recently been received in EventViewer. They could be filtered to only show key codes that don't appear in the list, but I think having it show the last 10 or so unique keys/buttons would be useful in any circumstance.

**Comment by tekezo** [comment]
1. I added button10 - button32 into Simple Modifications at the latest beta version.
![Check for beta updates](https://pqrs.org/osx/karabiner/img/karabiner-elements-check-for-updates-beta@2x.png)

2. The "Recently Received in EventViewer" feature sounds good.
I'll try to add `Add to Simple Modifications` button into EventViewer.

**Comment by thecodewarrior** [comment]
Thanks!

I figured out where the JSON was after posting this and manually edited it, but I'm sure this will be useful for others as well. :)

**Comment by tekezo** [comment]
I added new button into EventViewer at the latest beta version.
![180328-0001](https://user-images.githubusercontent.com/659178/38035302-134431c6-32df-11e8-82fe-011653a2b86f.png)
