### ISSUE TITLE
ordered simultaneous groups?

### ISSUE THREAD

**Issue by Jimmy34742** [tekezo/Karabiner-Elements#1303]
For example, I'd like to be able to do the simultaneous "fjk" in strict order and also strict inverse order. But instead of typing the sequences f-j-k and k-j-f, I'd like to be able to type f-jk ('f', then simultaneous insensitive "jk") and k-jf ('k', then simultaneous insensitive "jf").

Is there presently code that will do this, or am I asking for a new feature?

**Comment by prohtex** [comment]
I'm also wondering about this. #1306

**Comment by prohtex** [comment]
https://pqrs.org/osx/karabiner/json.html#typical-complex_modifications-examples-change-right-shift-x2-to-mission-control

**Comment by Jimmy34742** [comment]
In my case, I'm not asking about using a modifier key followed by a chord of regular keys, but a chord1 of regular keys followed by a different chord2 of regular keys where the reverse--chord2 followed by chord1--can have a separate result.

**Comment by prohtex** [comment]
The linked example allows you to set a variable if a key has been pressed and then check that variable later. Not sure if that would be advanced enough for you but I've had some success with it.

**Comment by Jimmy34742** [comment]
I understand, but I would like to be able to do ordered chords without relying on setting variables.

**Comment by tekezo** [comment]
I think there is not a way to achieve the behavior for now.
Using modifiers instead of `f` key is recommended. (e.g., `shift + j,k`)
(Of course, you can change `f` key using `to_if_alone`, but `to_if_alone` does not support blocking until key_up yet.)

I'll consider to add the blocking feature into `to_if_alone`.
