### ISSUE TITLE
Many to many mapping (Key sequence trigger)

### ISSUE THREAD

**Issue by prohtex** [tekezo/Karabiner-Elements#1306]
I'm trying to do a many to many mapping. For example, pressing "A" then "B" while CMD is held down will then trigger "C" "D". Is this possible with the new karabiner.json format? While there are several examples that show **simultaneous** triggers, I don't see any that show a **key sequence**.

**Comment by prohtex** [comment]
Thank you @tekezo

https://pqrs.org/osx/karabiner/json.html#typical-complex_modifications-examples-change-right-shift-x2-to-mission-control

**Comment by man-goat** [comment]
404
