### ISSUE TITLE
Virtual keyboards ISO / ANSI are wrong

### ISSUE THREAD

**Issue by heihachi88** [tekezo/Karabiner-Elements#1308]
I have a russian keyboard (apple's default one), it has § sign next to the "1", but if i choose ISO keyboard layout, then i have ` next to the "1", but the images are right.

![image](https://user-images.githubusercontent.com/5739191/37266800-e94d3886-25e6-11e8-821e-cf3a40c7c8a0.png)

is that expected behavior? I have U.S. input source all the time.

**Comment by CedricRBR** [comment]
I have a Swiss-German Keyboard and face a similar issue. Swiss German keyboards have the § left of 1 and the ` left of z, but when running karabiner those two are exchanged. 

a simple fix is the following: 
![screenshot 2018-04-03 at 16 57 25](https://user-images.githubusercontent.com/15923683/38257215-1fb769f2-3760-11e8-9f8a-629d241814b3.JPG)
(don't mind the first row, that's something else and has nothing to do with the issue)
