### ISSUE TITLE
Shift-lock or no?

### ISSUE THREAD

**Issue by jonteamere** [tekezo/Karabiner-Elements#1312]
I'm interested in shift-lock functionality (albeit for certain applications). Is there a way with Karabiner-Elements?

Any other apps with the capability?

**Comment by nguyenhimself** [comment]
There is a pre-built rule that [allows you to exchange numbers and symbols](https://pqrs.org/osx/karabiner/complex_modifications/#exchange_numbers_and_symbols-list-group).

For extra effect, you can also manually add to that rule a "key_code": "caps_lock" to switch to typing all caps while you're at it.

**Comment by jonteamere** [comment]
I'm not sure what you mean for me to try. Would you mind clarifying? Thank
you for taking the time to help.

All the best,

Jonte Miller

**Comment by nguyenhimself** [comment]
As I understand it, what you want is:
- Press a key.
- All the number keys now outputs symbols (1 → !, 2 → @,...).
- All the letter keys now outputs UPPERCASE letters.

Correct?
Wha
