### ISSUE TITLE
f14 and f15 keys mapped to screen brightness

### ISSUE THREAD

**Issue by ccarnley7** [tekezo/Karabiner-Elements#1313]
Whenever I make a new configuration my f14 and f15 keys are mapped to the screen dim and brighten respectively. I'm just doing some simple function keys to media controls (f7-f12 for rewind, pause, fast-forward, and volume control) but leaving the rest of the function keys as function keys. They all work great except for f14 and f15. Also when I press those keys in the event viewer they aren't caught at all.

**Comment by SidIcarus** [comment]
Disable the built-in shortcuts via `System Preferences` -> `Keyboard` -> `Shortcuts` -> `Display`

<img width="745" alt="builtin_shortcuts" src="https://user-images.githubusercontent.com/3842798/38449811-96fa608a-39e2-11e8-8d3c-3ce29d78d472.png">

**Comment by SidIcarus** [comment]
No problem good sir.
I only use a `third-party` keyboard so I wouldn't have ever figured out that it doesn't display for their own device, thanks!

Also, you should close this ticket out. ^_^

**Comment by ccarnley7** [comment]
Good call. Thanks again

**Comment by conganhhcmus** [comment]
<img width="670" alt="Screen Shot 2019-09-15 at 2 00 28 AM" src="https://user-images.githubusercontent.com/38190613/64912675-ba0eb580-d75c-11e9-8c4b-20220e95693f.png">
I don't see display in image. Can anyone help me pls!!!
