### ISSUE TITLE
horizontal scroll buttons to navigate between applications

### ISSUE THREAD

**Issue by farshadjahanmanesh** [tekezo/Karabiner-Elements#1314]
is there any way to map horizontal scroll buttons to navigate between fullscreen apps?

mouse : Microsoft Sculpt Ergonomic

**Comment by mtwomey** [comment]
+1 to be able to map horizontal mouse scroll in the "from" section of Karabiner. I see I can map _to_ it (in the beta, just not _from_ it).

**Comment by wedi** [comment]
A comment to leave this ticket open. 🤓

**Comment by i1skn** [comment]
Any progress on this issue?
