### ISSUE TITLE
Karabiner-Elements reverts the Modifier Keys

### ISSUE THREAD

**Issue by nerdpad** [tekezo/Karabiner-Elements#1315]
I have my CAPS key changed to Control in the OSX Keyboard setting itself, and Karabiner overrides that to default behavior.

When Karabiner is running CAPS key works as CAPS key, and works as Control when I shutdown Karabiner (The way it was configured in the OS Modifier Keys Settings dialog).

Should Karabiner be doing this?

**Comment by tekezo** [comment]
Yes. Please change modifiers in Simple Modifications.
https://pqrs.org/osx/karabiner/document.html#event-modification-chaining
