### ISSUE TITLE
Unchecking Magic Keyboard from "Modify events from this device" blocks all keystrokes from keyboard

### ISSUE THREAD

**Issue by iryan2** [tekezo/Karabiner-Elements#1316]
<img width="978" alt="screen shot 2018-03-21 at 3 58 33 pm" src="https://user-images.githubusercontent.com/5858312/37696304-55f6dea6-2d21-11e8-896e-e618ffcbe395.png">

With the pictured setup, the computer seems to receive no keystrokes at all from the Magic Keyboard. I just want to have my Karabiner config affect my other keyboard (FILCO in screenshot), and not change the behaviour of the Magic Keyboard at all. 

Note that the other keyboard works the whole time, regardless of whether Magic Keyboard is checked or not.

**Comment by tekezo** [comment]
It's an issue of macOS side and difficult to avoid.
macOS sometimes missed a device after turning off the checkbox.

Turning off the power of magic keyboard once and turning on again might fix the issue temporarily.

**Comment by iryan2** [comment]
@tekezo Thanks for the tip, it works like you said.

In my case, I only occasionally use the Magic Keyboard, for example when a coworker uses my machine, so this temporary fix seems to resolve my problem. For that reason, I'll close this issue, but please re-open it if you prefer.
