### ISSUE TITLE
how to change "CAPS LOCK + hjkl to arrow keys" complex modification to work with CAPS LOCK + JKLI ?

### ISSUE THREAD

**Issue by whaeva** [tekezo/Karabiner-Elements#1317]
how to change "CAPS LOCK + hjkl to arrow keys" complex modification to work with CAPS LOCK + JKLI instead of HJKL keys ?

**Comment by nguyenhimself** [comment]
Open the [karabiner.json](https://pqrs.org/osx/karabiner/json.html) file and change those keys yourself?

**Comment by whaeva** [comment]
thank you! it's working :)
