### ISSUE TITLE
System Extension Blocked

### ISSUE THREAD

**Issue by jt-github** [tekezo/Karabiner-Elements#1319]
This is _not_ a Karabiner issue, but it's still an issue (with Mac OS X), and the solution is goofy, to say the least.

When installing Karabiner-Elements for the first time, the software helpfully provides a warning message that Mac OS X will block the system extension (and it does).  Because Apple has gotten smart and/or a bit overzealous about security, **it is not possible to click the "Allow" button in the Security & Privacy settings application if you have any kind of keyboard/mouse control or remote access software installed that emulates mouse clicks, etc.**  I was using ShareMouse as a software KVM, among other things.

This starts out as a slightly different issue, but the replies are what lead me to my solution:
https://discussions.apple.com/thread/8087342

Even after closing everything I could think of, it still ignored my taps on my Macbook's trackpad when trying to click on the "Allow" button (technically the button animated the click so it wasn't completely ignoring it; it was just not carrying out the action of actually allowing the extension).  I had to open Script Editor, then record a macro of me clicking on the Allow button.  For some reason, just recording that macro seemed to put things into "true native" mode and that clicked the button.  I didn't even have to play the macro back.

While the security is an improvement, there is no warning message about why the button isn't doing what you expect it to do when you click over and over on it.  Not cool, Apple (even if you are protecting me).

**Suggestion for Karabiner-Elements:** Add additional instructions (or at least a link to more information) to the existing "System Extension Blocked" warning message to help people recognize why Apple isn't letting us click that damned button!

**Comment by tekezo** [comment]
I added a link to the following page at the latest beta version.
https://pqrs.org/osx/karabiner/help.html#kext-allow-button-does-not-work

![180329-0001](https://user-images.githubusercontent.com/659178/38042690-028677fc-32f0-11e8-87c9-b8192fe4f58e.png)
