### ISSUE TITLE
Exchange command+arrows with option+arrows doesn't seem complete

### ISSUE THREAD

**Issue by Halfwalker** [tekezo/Karabiner-Elements#1320]
I really want to use ctrl-arrows to jump words in High Sierra, rather than the default option+arrows, which I prefer for other things.
Without Karabiner, the keys return as this (using cat -v) :

```
ctrl-left == ^[[1;5D
option-left == ^[[1;3D
```

Enabling that rule though produces this :

```
ctrl-left == ^[[1;3D
option-left == ^[[1;3D
```
Note that they're both the same.  It just copied option-left to ctrl-left, but didn't copy the original ctrl-left to option-left.  So they're not swapped/exchanged.

**Comment by Halfwalker** [comment]
So, is there any way to actually have this rule swap the the ctrl-arrows with option-arrows ?  I don't want to just copy one to the other, but actually **swap** them.  I don't want to lose the functionality of the ctrl-arrows ...

**Comment by jcrben** [comment]
I'm seeing something similar. I was thinking that PC-Style Control+Up/Down/Left/Right might  help but it seems not. https://pqrs.org/osx/karabiner/complex_modifications/#pc_shortcuts

**Comment by jcrben** [comment]
Bumping - this is a handy combination.
