### ISSUE TITLE
Complex mods: parameters

### ISSUE THREAD

**Issue by NoobDoesMC** [tekezo/Karabiner-Elements#1321]
What do these do

```
"parameters": {
  "basic.simultaneous_threshold_milliseconds": 50,
  "basic.to_delayed_action_delay_milliseconds": 500,
  "basic.to_if_alone_timeout_milliseconds": 1000,
  "basic.to_if_held_down_threshold_milliseconds": 500
}
```

**Comment by tekezo** [comment]
These parameters are threshold of operators.
Some parameters are described in https://pqrs.org/osx/karabiner/json.html

**Comment by mantheflan** [comment]
The webpage is "not found" and the settings are still not clear, even in the GUI:
<img width="917" alt="Capture d’écran 2021-02-16 à 10 31 40" src="https://user-images.githubusercontent.com/52001167/108044444-8d8e5580-7042-11eb-8e3b-e00bb3132152.png">
Is it possible to get an explanation (or better yet, to explain it in the app directly)?

**Comment by MuhammedZakir** [comment]
Read the methods in the doc and you will understand -- https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/. If there is some unclear part, feel free to ask. :-)
