### ISSUE TITLE
Adding simple modification from any key to eject config error

### ISSUE THREAD

**Issue by jams2** [tekezo/Karabiner-Elements#1323]
When adding a simple rule to map from one key to eject key, it seems that the rule is configured incorrectly.

The logs show:

`
[2018-03-29 10:51:00.877] [error] [grabber] complex_modifications json error: Unknown key: customer_key_code in {"customer_key_code":"eject"}
[2018-03-29 10:51:00.877] [error] [grabber] complex_modifications json error: Invalid type in to_event_definition: {"customer_key_code":"eject"}
`

For example, if I map from escape to eject, the system recognises no event from pressing escape (nothing shows in karabiner event viewer). But pressing eject shows the following event:

'
eventType:SysKeyDown      code:0xe        name:                flags:                                   misc:
eventType:SysKeyUp        code:0xe        name:                flags:                                   misc:
'

Changing the field "customer_key_code" in ~/.config/karabiner/karabiner.json to either "key_code" or "consumer_key_code" enables karabiner to recognise the event - in this example pressing escape registers the correct code `0xe`. However, under simple modifications in the gui, the rule shows up as escape mapped to a blank menu option.

**Comment by nguyenhimself** [comment]
Maybe this is beside your point, but why not just do that via the "Simple Modifications"? It seems to work for me.
