### ISSUE TITLE
Re-bind shortcut only in specific application

### ISSUE THREAD

**Issue by theonlygusti** [tekezo/Karabiner-Elements#1324]
Can I rebind shortcuts only when certain apps are focussed?

**Comment by Jimmy34742** [comment]
Do frontmost_application_if and frontmost_application_unless provide the functionality you need?

**Comment by theonlygusti** [comment]
Probably, where do I put them @Jimmy34742 ?

I am trying to re-map cmd-q to cmd-w inside of Safari and Finder

**Comment by Jimmy34742** [comment]
reference manual: https://pqrs.org/osx/karabiner/json.html

**Comment by theonlygusti** [comment]
@Jimmy34742  what's the bundle identifier for safari?

I tried com.apple.safari
