### ISSUE TITLE
Remap escape to alt-escape in safari

### ISSUE THREAD

**Issue by theonlygusti** [tekezo/Karabiner-Elements#1328]
I already have Simple Modifications' "caps_lock" to "escape" enabled.

How can I create a modification that maps _any_ escape (including if I press the capslocks key, which is now escape) to alt-escape if Safari is frontmost?

        {
          "type": "basic",
          "from": {
            "key_code": "escape"
          },
          "to": {
            "key_code": "escape",
            "modifiers": {
              "mandatory": [
                "alt"
              ]
            }
          },
          "conditions": [
            {
              "type": "frontmost_application_if",
              "bundle_identifiers": [
                "^com\\.apple\\.Safari$"
              ]
            }
          ]
        }

**Comment by nguyenhimself** [comment]
It's "Option", not "Alt"

Otherwise, your code should work.

**Comment by theonlygusti** [comment]
```
{
  "title": "Stop ESC exiting Safari full-screen",
  "rules": [
    {
      "description": "Maps ESC to ⌥ESC in Safari.",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "escape"
          },
          "to": [{
            "key_code": "escape",
            "modifiers": "option"
          }],
          "conditions": [
            {
              "type": "frontmost_application_if",
              "bundle_identifiers": [
                "^com\\.apple\\.Safari$"
              ]
            }
          ]
        }
      ]
    }
  ]
}

```
