### ISSUE TITLE
Version 11.6.0 on High Sierra 10.13.4 - after a while keyboard input is delayed considerably

### ISSUE THREAD

**Issue by jjbongio** [tekezo/Karabiner-Elements#1329]
I have an extremely simple Karabiner setup, just changing the numeric period key on an ISO keyboard to send the period character instead of the comma. 

I installed High Sierra 10.13.4, and after a couple of hours, keyboard input is delayed substantially (multiple seconds before input is echoed). Happens both on the Magic Mac keyboard and a regular ISO USB keyboard. Disabling Karabiner Elements for the keyboard fixes the problem.

**Comment by Jimmy34742** [comment]
Just a thought: try the beta and see if that makes a difference.

**Comment by jjbongio** [comment]
Thanks for the suggestion. I couldn't find where to download the beta version.

**Comment by Jimmy34742** [comment]
Does Preferences>Misc show a button on the upper righthand side that says "Check for beta updates"?

**Comment by jjbongio** [comment]
Yes, thanks. I've installed it, and I'll see what happens. The problem happened a bit of time after a reboot.

**Comment by jjbongio** [comment]
Beta is working fine. Thanks for the suggestion.
