### ISSUE TITLE
Is it possible to make ctrl+x cut line as with PC's

### ISSUE THREAD

**Issue by btech** [tekezo/Karabiner-Elements#1330]
In some PC applications, if I press ctrl+x while nothing is highlighted, the current line of text will be cut and copied to the clipboard. So if I have this text:

> Lorem ipsum dolor sit amet, \<Cursor\>consectetur adipiscing
> elit, sed do eiusmod tempor incididunt ut labore et dolore

And I hit ctrl+x, it will result in this text:

> \<Cursor\>elit, sed do eiusmod tempor incididunt ut labore et dolore

Is there a way to implement this functionality using Karabiner-Elements?

**Comment by nguyenhimself** [comment]
Correct me if I'm wrong, but I don't think there's a way to differentiate between "nothing is highlighted" and "some text is highlighted".

Probably better if you leave "Command+X" alone and map, say, "Option+X" to "Command+Right -> Command+Shift+Left -> Command+X". That will cut the whole line.
