### ISSUE TITLE
Left Shift/Caps Lock

### ISSUE THREAD

**Issue by Windedhiker** [tekezo/Karabiner-Elements#1331]
My left shift key stopped working for certain keys. 

'S' requires I use the Right Shift key
'C' requires I use the Caps lock key to "Shift" for caps

There are a few keys like this. I have not done an inventory of all the issues, but I figured I would post first in case someone has some advice.

Thanks for your time and attention.

**Comment by nguyenhimself** [comment]
Does it happen if you turn off Karabiner?

What does Karabiner-EventViewer show when you press Shift+C?

**Comment by Windedhiker** [comment]
It works if I turn off Karabiner.  If Karabiner is on, and I do a Shift C, it noted the 'c', but not the shift. Sorry for not trying turning off Karabiner earlier, but thanks for the "fix".
