### ISSUE TITLE
Karabiner private.xml converter program

### ISSUE THREAD

**Issue by durka** [tekezo/Karabiner-Elements#1332]
I wrote a program to convert old `private.xml` configs to `karabiner.json`: [karaconv](https://github.com/durka/karaconv/). It's not perfect because (1) I stopped as soon as it knew enough translate my personal `private.xml` and (2) the schema of `karabiner.json` is undocumented as far as I know.

Anyway, I thought people here might want to try it and tell me when it crashes. cf #772 #1170

**Comment by asmeurer** [comment]
The scheme is documented [here](https://pqrs.org/osx/karabiner/json.html).

**Comment by durka** [comment]
Oh, awesome! That will be useful.
