### ISSUE TITLE
Possible to require amount of time before modifier key takes effect?

### ISSUE THREAD

**Issue by mushmelty** [tekezo/Karabiner-Elements#1334]
I'm currently using the "Change spacebar to right_control if pressed with other keys (Post spacebar when pressed alone)" rule, and my typing speed seems to cause me to accidentally trigger CTRL key combinations when I don't want them to be fired. The behavior I would really like to have is to require the spacebar to be held for at least 750ms or more before it actually becomes a CTRL key, to which it then becomes responsive to additional inputs. That is to say, I want to use the spacebar as a CTRL key, but not simultaneous.

Will I have to create a new custom behavior, or can I adapt the existing rule to behave the way I want? I've adjusted all four of the Parameters, but can't separate the "simultaneous" firing.

**Comment by clark-bristol** [comment]
You may be able to achieve what you're looking for with the `to_if_held_down_threshold_milliseconds` parameter (which can be set globally and/or on a per-manipulator basis. But this kind of thing gets complicated and the software can't deliver some advanced functionality in its current form. I've had some trouble trying to use the space bar as a custom modifier when held down.

```{
    "type": "basic",
    "from": {
        "key_code": "spacebar",
    },
    "parameters": {
        "basic.to_if_held_down_threshold_milliseconds": 750
    },
...
    "to_if_alone": [
        {
            "key_code": "spacebar"
        }
    "to_if_held_down": [
        {
            "key_code": "right_control"
        }
    ]```

Good luck!
