### ISSUE TITLE
Cannot update to beta due to MacOS 10.13.4

### ISSUE THREAD

**Issue by paragbaxi** [tekezo/Karabiner-Elements#1337]
![image](https://user-images.githubusercontent.com/954865/38322966-d462c06e-37f0-11e8-8cd9-6f611270f1c4.png)

Cannot change configuration to update to beta. Also, cannot hit "Allow" button.

**Comment by rplakas** [comment]
Having the same issue.

**Comment by paragbaxi** [comment]
Restarted in safe mode enabled me to click on the Allow button (which disappeared upon clicking).
