### ISSUE TITLE
How to turn on manipulate scroll lock LED on PC Keyboard?

### ISSUE THREAD

**Issue by trung753dfx** [tekezo/Karabiner-Elements#1338]
I have a TKL PC keyboard that have 2 manipulate LED, caps and scroll lock.
I wondering when I trigger a key to do a keystoke, the LED turn on so I can know its working?
I have looking manual or searching on this, all I found is something call "**set_caps_lock_LED_state**", I have try put value like 1, 0 or true, false but its not working even in "Add Rules" window have shown the rule I modified mean the code is working.
Hope I have some answer about this. Thanks.

**Comment by carrigmore** [comment]
I think current only Caps Lock LED manipulation has been implemented, neither num lock and scroll lock LED manipulation have been implemented yet.

**Comment by Ushio-Cheng** [comment]
It is a important issue though. If I can do something like toggle Macros with a scroll lock and show the status of it use that led, that would be nice.
