### ISSUE TITLE
Cannot edit complex modification file

### ISSUE THREAD

**Issue by masuguaz** [tekezo/Karabiner-Elements#1339]
Hello, I am new to Karabiner (and also new to Mac OS...)
I use Autohotkey for Windows, and tried to edit my key modification with Karabiner.

I downloaded a sample script from the link below, and the script worked correctly.
https://github.com/YutaUme/Karabiner_Conf/blob/master/34619285.json

Then I changed some key settings (like from "fn + f" to "fn + j"), but the Karabiner didn't read the new setting file after I edited the script. 

Could anyone give me a help for the issue?

**Comment by masuguaz** [comment]
Thank you Jimmy!

Yes, I put the file into 
/Users/MyName/.config/karabiner/assets/complex_modifications

Should I put into karabiner folder directly?

**Comment by Jimmy34742** [comment]
The karabiner.json file goes in ../.config/karabiner/

I never bother with the contents of the assets folder. I suppose it's automatically handled by K-E.

**Comment by masuguaz** [comment]
When I change the title name, K-E still reads the file, but once I change a key setting like f to y, K-E never finds the file... I am wondering why....
