### ISSUE TITLE
Feature request: launch app

### ISSUE THREAD

**Issue by seanfarley** [tekezo/Karabiner-Elements#134]
A feature I'm really missing is the ability to launch an application with a keyboard shortcut

**Comment by BrianGilbert** [comment]
Try Hammerspoon http://www.hammerspoon.org/

**Comment by seanfarley** [comment]
I could also use the feature in quicksilver. My real question here is to see if @tekezo thinks this is out of scope for Karabiner-Elements or not.

**Comment by JakeSc** [comment]
Launcher Mode was an amazing feature in Karabiner, and one upon which I relied quite heavily.

This feature allows the user to switch to applications by holding `o` and pressing an associated key.
Examples:
- `o`+`x`: Launch Xcode
- `o`+`t`: Launch Terminal
- `o`+`xx`: Launch Simulator
- `o`+`c`: Launch Chrome
- `o`+`a`: Launch Activity Monitor

Is there planned support for Launcher Mode in Karabiner-Elements?

**Comment by nikitavoloboev** [comment]
This is crucial for me. Hope it is added soon.

**Comment by JakeSc** [comment]
I figured it out! I'm using Hammerspoon to recreate a "Launcher Mode". First, I instructed Karabiner-Elements to map `right_command` to `f19`, and then I built a Hammerspoon-based Launcher Mode around `f19`. I use `right-cmd + T` for Terminal, for example. See my config file here:

https://github.com/JakeSc/dotfiles/blob/master/hammerspoon/init.lua

**Comment by dunkarooftop** [comment]
Hello, @JakeSc 
  I am wondering if you can cook up something for being able to chain more then 1 character after the special modifier key like hyper + x, y or even hyper + x, y, z in hammerspoon.

much appercitaed

**Comment by bindiry** [comment]
Launcher Mode is better than any other software, It's really awesome!

**Comment by jzk** [comment]
FYI. I switched to use https://itunes.apple.com/us/app/thor/id1120999687 instead

**Comment by tekezo** [comment]
You can use `shell_command`.
https://pqrs.org/osx/karabiner/json.html#typical-complex_modifications-examples-open-alfred-when-escape-is-held-down

**Comment by lukelbd** [comment]
Just to help my fellow googlers: this is what you add to your `~/.config/karabiner/karabiner.json` file, as an entry under the `rules:` list:

```
 "rules": [
    {
        "description": "Open Google Chrome",
        "manipulators": [
                {
                    "type": "basic",
                    "from": {
                        "key_code": "g",
                        "modifiers": {
                            "mandatory": [
                                "command",
                                "control"
                            ],
                            "optional": [
                                "caps_lock"
                            ]
                        }
                    },
                "to": [
                    {
                        "shell_command": "open -a 'Google Chrome.app'"
                    }
                ]
                }
        ]
    },
```

In this case, I'm mapping `Cmd+Ctrl` to open Google Chrome. On Mac, this can also be done with [an Automator "service" script](https://apple.stackexchange.com/questions/20010/can-i-create-a-shortcut-to-open-a-specific-application-on-os-x), but I've found that is generally really laggy. Also my Keyboard Shortcut "Services" section is really buggy.

**Comment by JakeSc** [comment]
For people searching for this, I built a small utility app inspired by the awesomeness that was Launcher Mode. Check it out here: https://switchfaster.com/

Basically it uses right-command + (any other hotkey) to launch or switch to the given app. You can also switch the trigger key to use right-option as well. Let me know if you have some feedback, I'd love to hear it!

**Comment by nikitavoloboev** [comment]
I define my own launcher modes with [goku](https://github.com/yqrashawn/GokuRakuJoudo).

i.e. [here](https://github.com/nikitavoloboev/dotfiles/blob/master/karabiner/karabiner.edn#L184) is w key being used as launcher mode to launch apps.

**Comment by ZYinMD** [comment]
Not sure what the current status of this issue is. For those of you who use the shell_command solution, e.g. `open -a 'Google Chrome.app'`, it's slower than native app switching. If you use something like Keyboard Maestro to set a hotkey to switch to Chrome, you'll see the difference. 

Keyboard Maestro actually has two types of actions, "activate an app" and "open an app", and if you choose the latter for something like "open chrome", it'll show a warning and recommend you use the former "because it's faster".

I'm not sure which step in the shell_command method is slow - the shell executing a command, or the command launching an app (presumably using a different API than mouse clicking on dock), or both.
