### ISSUE TITLE
Swap "Option-Shift-2 (€)" with "Option-4 (¢)"

### ISSUE THREAD

**Issue by max-2000** [tekezo/Karabiner-Elements#1343]
Total beginner, trying to modify the new keyboard on my US Mac.

Have already installed and running the profile off the web that allows me to turn "a/u/o" into "ä/ü/ö" using the Option key. I'd now like to add a command that allows me to use "€" when pressing Option-4 and simply swap the output from "¢" to "€".

Can anyone help me with how to integrate this into the existing karabiner.json file?

Thanks for helping me absolute beginner!

**Comment by nguyenhimself** [comment]
Here:

```
{
    "description": "¢ to €",
    "manipulators": [
        {
            "from": {
                "key_code": "4",
                "modifiers": {
                    "mandatory": [
                        "option"
                    ]
                }
            },
            "to": [
                {
                    "key_code": "2",
                    "modifiers": [
                        "option",
                        "shift"
                    ]
                }
            ],
            "type": "basic"
        }
    ]
},
```

**Comment by max-2000** [comment]
@nguyenhimself thanks for the above. Now to add to the basic question, I struggle to even copy paste this at the right spot. The log always reports mistakes.

<img width="850" alt="bildschirmfoto 2018-04-09 um 21 44 28" src="https://user-images.githubusercontent.com/38187592/38519171-3a14de90-3c3f-11e8-8f17-ad1c906240a6.png">

**Comment by nguyenhimself** [comment]
Scroll a bit further down, find the closing brace to this one and paste the code there:

<img width="850" alt="38519171-3a14de90-3c3f-11e8-8f17-ad1c906240a6" src="https://user-images.githubusercontent.com/482270/38593783-526c479c-3d6d-11e8-9875-b609ebaf76f1.png">

One easy trick if you're not familiar with editing json files is adding a complex rule from the app then open the json files and replace that entire rule with your custom one.

**Comment by max-2000** [comment]
THANKS SO MUCH!

**Comment by nguyenhimself** [comment]
Gladly. BTW, you should close this issue 🙂
