### ISSUE TITLE
Version 12 breaks MS Natural Keyboard mappings

### ISSUE THREAD

**Issue by eric-fredericks-rally** [tekezo/Karabiner-Elements#1346]
I upgraded to version 12.0.0 and my MS Natural keyboard mappings stopped working. I've attached my Version 11 configuration file (profile is "MSNAT" for that keyboard), with a lot of complex mappings that I've been using over the past couple months quite successfully.

I noticed that the Devices tab of the event viewer now shows the MS Natural keyboard as an Apple keyboard with product id 65535. Two devices show up for that keyboard (which is strange). When I disconnect that keyboard, the devices both disappear. The correct vendor id is 1118 and the correct product id is 219 (from my configuration file).

```
{
        "is_keyboard": true,
        "is_pointing_device": false,
        "location_id": 20185088,
        "manufacturer": "Apple",
        "product": "Keyboard",
        "product_id": 65535,
        "registry_entry_id": 4294970941,
        "transport": "USB",
        "vendor_id": 1452
    },
    {
        "is_keyboard": true,
        "is_pointing_device": false,
        "location_id": 20185088,
        "manufacturer": "Apple",
        "product": "Keyboard",
        "product_id": 65535,
        "registry_entry_id": 4294970960,
        "transport": "USB",
        "vendor_id": 1452
    },

```

In addition, I did notice that the keys detected in the event viewer are different, so my complex modifications are basically in many cases broken and I'm not sure if there's an easy fix other than rebuilding my mappings (which is going to be time consuming).

[karabiner_json.txt](https://github.com/tekezo/Karabiner-Elements/files/1908371/karabiner_json.txt)

**Comment by tekezo** [comment]
It's strange...
Is this issue reproduced after restart your macOS?
If so, please ensure you are not using IntelliType or other drviers.

**Comment by eric-fredericks-rally** [comment]
I will check and let you know.

**Comment by eric-fredericks-rally** [comment]
@tekezo the problem was the IntelliType drivers. Thank you!
