### ISSUE TITLE
Can't map from mouse buttons

### ISSUE THREAD

**Issue by JuniorGenius** [tekezo/Karabiner-Elements#1350]
I use a MacBook Air on High Sierra and I can't make any shortcuts that map ``from`` button1 or button2. They simply do nothing. I can map ``to`` them, but not ``from``.

Not sure if it's related, but one of my devices gets ignored and is grayed out in the menu:
![image](https://user-images.githubusercontent.com/1732093/38784440-b414aa5a-40c6-11e8-97e8-d497823c9488.png)

```
[info] [console_user_server] core_configuration is updated.
[info] [grabber] Apple Internal Keyboard / Trackpad (device_id:2) is ignored.
```

Please help! I want to disable control + left mouse click on my Mac because it prevents me from being able to use left-click in video games while I'm holding the control key.

Let me know if you need any more info.

**Comment by tekezo** [comment]
Unfortunately, Karabiner-Elements cannot modify Apple Mice and Trackpads.
Other apps (e.g. BetterTouchTool) might be able to do it.

**Comment by NathanBlais** [comment]
This is still problem.

**Comment by yeralin** [comment]
In my case, my wireless mouse was disabled:
![image](https://user-images.githubusercontent.com/8620461/82383020-081a3e00-99fb-11ea-9eca-317517c7cb54.png)

But I manually modified `.config/karabiner/karabiner.json`, and set `"ignore": false` under that device. 

Now my mouse mapping are working:
![image](https://user-images.githubusercontent.com/8620461/82383097-254f0c80-99fb-11ea-8ff7-a966b45e9614.png)


Maybe we shouldn't disable devices with the same VendorID + ProductID by default?

@tekezo
