### ISSUE TITLE
Version 12のto_after_key_upの不具合

### ISSUE THREAD

**Issue by Hacci** [tekezo/Karabiner-Elements#1351]
Karabiner-Elements ver12.0.0〜
macOS 10.13.4

Karabiner-Elements ver11.6.0までは問題なかった。
ver12から仕様が変わった影響でバグが入り込んだと思われます。

分かりやすい例で説明します。
fromで左シフトケース(f + left_shift)のときに、
to_after_key_upでも同じく左シフトケース(9 + left_shift → かな入力で「ょ」)にする。
toは何でもいいのですが、比較の意味で、左シフトケース(8 + left_shift → かな入力で「ゅ」)にする。

リアルな左シフトを先にキーアップしてから、fキーをキーアップしたときに、問題が発生します。ゆっくり打鍵する時は、fキーの方を先にキーアップしますが、高速で打鍵すると、このような順番になりやすいため、この不具合は致命的です。

不具合とは、左シフトが無効になって、大文字の「よ」になってしまう。これは、リアルな左シフトのキーアップでto_after_key_upが持っているleft_shift用のフラグが初期化されてしまうからでしょう。

ちなみに、to_after_key_upで逆の右シフトケースにすれば、正しくright_shiftがkey_down、key_upされる。

このことから、同サイドのシフトを指定した時のto_after_key_upのバグということは明らかです。

これは、ver12.0.0からsimultaneousでのto_after_key_upが削除されたことによる影響でしょうか?
今回の問題は、単純なfrom、to、to_after_key_upでの動作なので、影響が大きい。

修正をお願いします。

                    {
                        "manipulators": [
                            {
                                "description": "test99",
                                "from": {
                                    "key_code": "f",
                                    "modifiers": {
                                        "mandatory": [
                                            "left_shift"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "8",
                                        "modifiers": [
                                            "left_shift"
                                        ]
                                    },
                                    {
                                        "key_code": "vk_none"
                                    }
                                ],
                                "to_after_key_up": [
                                    {
                                        "key_code": "9",
                                        "modifiers": [
                                            "left_shift"
                                        ]
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    }

**Comment by tekezo** [comment]
フィードバックありがとうございます。

v12.0.6で修正しましたので最新ベータ版をご確認ください。

![Check for beta updates](https://pqrs.org/osx/karabiner/img/karabiner-elements-check-for-updates-beta@2x.png)

**Comment by Hacci** [comment]
最新ベータ版v12.0.6をインストールして、正常に動作することを確認しました。
素早い修正ありがとうございます。

今回とは関係ないことですが、
新しい機能が加わってもなかなか使い方が分からないことがあります。
最近では、simultaneousです。
同時押下と言う意味で言えば、従来のNICOLAのようなシフトとの同時押下とどのように違うのでしょうか? simultaneousの機能でNICOLAのようなシフトケースをインプリメントするのがいいのか、それとも、シフトケースは従来の基本機能でいいのか、そこの違いを簡単に説明していただけないでしょうか? オンラインのマニュアルにそういう説明を加えていただけると助かります。

以上よろしくお願いします。
