### ISSUE TITLE
The allow button for System & Privacy is not visible.

### ISSUE THREAD

**Issue by bdryanovski** [tekezo/Karabiner-Elements#1352]
hello, 

The `allow` button is not visible:

<img width="1478" alt="screen shot 2018-04-16 at 11 38 19 am" src="https://user-images.githubusercontent.com/204564/38798708-f8fc4782-416a-11e8-8dea-f286b1c3d66e.png">

MacOS version 10.13.4.

Any ideas how to fix this issue or force Krabiner to request again the permission.
I try to remove and install it and even remove all the data that could find but the issue is still present.

**Comment by tekezo** [comment]
I guess your issue is caused by other apps such as anti-virus software which prevents from kext loading.
Are you using such apps?

**Comment by bdryanovski** [comment]
It could be, is a company machine. But I have a hard time locating the application that could prevent it. Is there any way to force kext to ask me again? Cause I had no problems the past two months using it. And one morning everything stops working.

**Comment by tekezo** [comment]
Hmm, does closing System Preferences and open it again solve this issue?

**Comment by bdryanovski** [comment]
Without me doing anything just the Permission dialog popup from nowhere and now everything is working. I did not do anything ...

**Comment by lucaswiman** [comment]
I ran into this issue on my work computer. IT had installed a management system (MobileIron) that only allowed kernel extensions approved by IT to be active. They were able to approve `G43BCU2T37` and deploy that configuration to my computer. Once I rebooted, the dialog saying I need to authorize was gone and everything worked again. If you run into this on a work-managed computer, you may want to ask them to make a similar change.
