### ISSUE TITLE
Version 12 limits my NKRO USB keyboard to 6KRO

### ISSUE THREAD

**Issue by fedde-s** [tekezo/Karabiner-Elements#1353]
I use a USB keyboard that is able to register at least 23 simultaneous keypresses (n-key rollover). Probably more, but I don't use more than 23. Since I upgraded Karabiner from 11.x.x to 12.0.0, my applications only receive exactly six letters simultaneously when I press and release more while Karabiner-Elements is running. After quitting Karabiner-Elements, everything (including Karabiner-Eventviewer) works as expected and registers the keys.

**Comment by fedde-s** [comment]
I tried beta release 12.0.3 as suggested in another issue which I thought might be related, but that did not fix it. Will try to find how I can revert to 11.x.x for now.

**Comment by fedde-s** [comment]
Reverting to 11.6.0 works around my issue for now.

**Comment by tekezo** [comment]
v12.0.4 have an issue that kext is not loaded properly on macOS 10.12.
Please use v12.0.5 (the latest beta version) if you are using macOS Sierra.

**Comment by fedde-s** [comment]
I think I was, yeah. Will try, thanks for the reply!

**Comment by fedde-s** [comment]
I can confirm that the issue is gone now that I've used that button to upgrade to 12.0.5. Thank you! 🎉
