### ISSUE TITLE
macOS 10.13.4 Security & Privacy, unable to "Allow"

### ISSUE THREAD

**Issue by oflannabhra** [tekezo/Karabiner-Elements#1355]
This looks like it is most likely an issue with 10.13.4 and not karabiner, but I'm creating this issue to track

I just upgraded to macOS 10.13.4. Karabiner-Elements was installed and working before upgrading.

After upgrading, I was once again prompted to enable the kernel extension to be allowed through System Preferences -> Security & Privacy. However, the "Allow" button does not function.

This might be creating issues for other kernel extensions, as well. I've attempted to reboot, select the "Allow" button with the built in trackpad, but no dice.

[Google Drive](https://productforums.google.com/forum/#!topic/apps/obpUHR2269I), [JAMF](https://www.jamf.com/jamf-nation/discussions/27654/system-extensions-blocked-after-upgrading-to-high-sierra-10-13-4), and more seem to be experiencing some issues as well.

The only workaround that reportedly works is to log in as another administrative account and allow the kernel extension. If anyone else runs into this issue, I recommend attempting the above linked workarounds

**Comment by whinette** [comment]
I have the same problem and haven't have MagicPrefs installed.

**Comment by jasperla** [comment]
Sonos Controller for Mac, version 8.5.1 blocked it for me.

**Comment by rtgoodwin** [comment]
Yep, Sonos Controller blocked it for me as well. Had to close it then it worked perfectly.
