### ISSUE TITLE
PC keyboard number lock doesn't work properly.

### ISSUE THREAD

**Issue by carrigmore** [tekezo/Karabiner-Elements#1359]
I have map the Num Lock key on PC keyboard to Windows number lock key, according to Event view this mapping is correct, as the key code of number lock key is 0x83 instead of 0x53 (mac number lock), but the LED of num lock doesn't light up. Also when using Cooler master Keyboard, the number area is still not working.
![screen shot 2018-04-17 at 22 58 58](https://user-images.githubusercontent.com/8460701/38900434-58f39dba-4293-11e8-842f-e950778b6aed.png)
![screen shot 2018-04-17 at 22 48 36](https://user-images.githubusercontent.com/8460701/38900085-12a79bdc-4292-11e8-9960-73d26165d6b3.png)
![screen shot 2018-04-17 at 22 49 03](https://user-images.githubusercontent.com/8460701/38900086-12ceaac4-4292-11e8-892c-013da69657aa.png)

**Comment by carrigmore** [comment]
There is led_caps_lock = kHIDUsage_LED_CapsLock, but no equivalent of "led_num_lock = kHIDUsage_LED_NumberLock" existing in the project. Does that mean it is not implemented yet or something blocked this to be implemented? The windows num lock key function is very important for compact keyboard like Cooler Master, as the number area is default to other keys. Keys cannot function as numbers key until number lock LED is on. But on Mac it can never be turn on. Previous version of Karabiner can achieve this, but not this version.

**Comment by sknull** [comment]
Still no solution for this one?

**Comment by peterjc** [comment]
See #3173
