### ISSUE TITLE
How do I remap § to ` (tilde) ?

### ISSUE THREAD

**Issue by thealgebraist** [tekezo/Karabiner-Elements#136]

**Comment by talha131** [comment]
Please read the docs https://github.com/tekezo/Karabiner-Elements/tree/master/usage#swapping-sectionparagraph--key-on-non-us-keyboards

**Comment by thealgebraist** [comment]
Thanks.

**Comment by nuc** [comment]
Since the docs have moved and users might arrive here from Google, the key name for the `§` in karabiner is `non_us_backslash`.

**Comment by Albert221** [comment]
For me it was the other way around. This is my **working** config.

![image](https://user-images.githubusercontent.com/4085280/99402614-d4589c00-28e9-11eb-9201-f0aafbdd911c.png)

**Comment by Sleepful** [comment]
`grave_accent_and_tilde` worked for me thnx

**Comment by NewestUser** [comment]
The mapping between **non_us_backslash -> grave_accent_and_tilde** did not work on version **13.1.0**.
I had to **downgrade to 12.10.0** after which it started working like a charm.
![image](https://user-images.githubusercontent.com/7418570/102014368-39bf7180-3d5e-11eb-9a75-4c9630dae6c2.png)
