### ISSUE TITLE
Disabling the Esc key on the touchbar.

### ISSUE THREAD

**Issue by jearley1** [tekezo/Karabiner-Elements#1360]
Due to some water damage, my TouchBar spazzes out randomly and toggles the various keys on it. I've managed to remove all keys on the TouchBar except the Esc key.

I saw on Karabiner a checkbox for Change Escape Key > Disable Escape Key, however, this doesn't seem to disable it.

Any hints anyone could offer to solve my issue?

Thanks!

**Comment by kartik1225** [comment]
> Due to some water damage, my TouchBar spazzes out randomly and toggles the various keys on it. I've managed to remove all keys on the TouchBar except the Esc key.
> 
> I saw on Karabiner a checkbox for Change Escape Key > Disable Escape Key, however, this doesn't seem to disable it.
> 
> Any hints anyone could offer to solve my issue?
> 
> Thanks!

I have exact same problem have you find the problem?
I want to disable the touch bar or escape key it just keeps pressing by itself.
