### ISSUE TITLE
Modifier `key_down` interrupts `simultaneous`

### ISSUE THREAD

**Issue by apm1467** [tekezo/Karabiner-Elements#1367]
For example, in Vi Mode `s + h` is mapped to `left_arrow`. In the current Vi Mode, it is possible to press `s + shift + h` to select text. So:

1. `s` key_down
2. `shift` key_down
3. `h` key_down

will be mapped to `shift + left_arrow`, which is selecting text.

However, if we want to implement the new Vi Mode using `simultaneous`, this behaviour can not be achieved.

1. `s` key_down
2. `shift` key_down
3. `h` key_down

The `shift` key_down event will interrupt `simultaneous`. So nothing will be modified. We can still press

1. `shift` key_down
2. `s` key_down
3. `h` key_down

to select text, but this is not very intuitive for me.

So I would like to ask: Is it possible to let modifier keys not interrupt `simultaneous`?

**Comment by tekezo** [comment]
I added `simultaneous_options.detect_key_down_uninterruptedly` at v12.0.7.

Please upgrade to the latest beta version:
![Check for beta updates](https://pqrs.org/osx/karabiner/img/karabiner-elements-check-for-updates-beta@2x.png)

Then put  `"detect_key_down_uninterruptedly": true` as follows.

```json
    "from": {
        "simultaneous": [
            {
                "key_code": "s"
            },
            {
                "key_code": "h"
            }
        ],
        "simultaneous_options": {
            "detect_key_down_uninterruptedly": true
        }
    }
```

**Comment by apm1467** [comment]
I've tested that. It works very well. I will push the new Vi Mode when Karabiner-Elements goes to 12.1.0.

Thank you very much.
