### ISSUE TITLE
High Sierra 10.13.4 command + shift not refering

### ISSUE THREAD

**Issue by saeed74** [tekezo/Karabiner-Elements#1368]
in mac high sierra 10.13.4
I want to use command + shift for switch between language input like windows but this simple code not working:
https://gist.github.com/vsalex/eac8c27bc7cf428ba8e19671cdb34142

I think apple not allow to use command + shift for doing some thing.
any solution?

**Comment by tekezo** [comment]
Your code works on my machine.
Can you confirm the configuration changes your left_command + left_shift on EventViewer?
