### ISSUE TITLE
Remap Slack Command Enter

### ISSUE THREAD

**Issue by SwimGeek** [tekezo/Karabiner-Elements#137]
Hi,

I'd like to remap Command+Enter when using Slack.

Can this be done with Karabiner-Elements?

Here is a config from the old Karabiner...

<root>

```
<appdef>
    <appname>SLACK</appname>
    <equal>com.tinyspeck.slackmacgap</equal>
</appdef>

<item>
    <name>Slack Customisation</name>
    <item>
        <name>Map Cmd+Enter to send, Enter to extra line</name>
        <identifier>remap.app_slack_cmd_enter</identifier>
        <only>SLACK</only>
        <autogen>
            __KeyToKey__
            KeyCode::RETURN, ModifierFlag::COMMAND_L,
            KeyCode::RETURN
        </autogen>
        <autogen>
            __KeyToKey__
            KeyCode::RETURN,
            KeyCode::RETURN, ModifierFlag::SHIFT_L
        </autogen>
    </item>
</item>
```

</root>

**Comment by talha131** [comment]
You can't do app specific mappings yet.

**Comment by STRML** [comment]
You can do this with Hammerspoon. An example: https://github.com/STRML/init/blob/master/hammerspoon/init.lua#L196

**Comment by SwimGeek** [comment]
How do I sent the RETURN / ENTER key using hs.eventtap?

**Comment by SwimGeek** [comment]
I tried using Hammerspoon, but it's fairly painful.

I guess I can wait a bit.

Is  app specific mappings reasonably high up on the development priority list?

**Comment by LucaMarconato** [comment]
Any improvement? When this feature will be back?
Thank you!

**Comment by NJAldwin** [comment]
Apologies for the bump, but is there any sort of ETA on this particular feature?

**Comment by nriley** [comment]
I ended up building this myself tonight — it's a separate daemon, with right now no documentation, but if you're sufficiently technical, here you go:

https://github.com/nriley/Karabiner-Elements-App-Profiles

If a profile is named after an app's bundle identifier, it'll automatically switch between them (and switch to the first/default profile otherwise).

**Comment by STRML** [comment]
Very cool.

This can also be done with Hammerspoon via a little bit of Lua. For instance, say we want the app to have sane channel switching keybinds:

```lua
local slackKeybinds = {
  hotkey.new({"ctrl"}, "tab", function()
    hs.eventtap.keyStroke({"alt", "shift"}, "Down")
  end),
  hotkey.new({"ctrl", "shift"}, "tab", function()
    hs.eventtap.keyStroke({"alt", "shift"}, "Up")
  end),
  hotkey.new({"cmd", "shift"}, "[", function()
    hs.eventtap.keyStroke({"alt"}, "Up")
  end),
  hotkey.new({"cmd", "shift"}, "]", function()
    hs.eventtap.keyStroke({"alt"}, "Down")
  end),
  -- Disables cmd-w entirely, which is so annoying on slack
  hotkey.new({"cmd"}, "w", function() return end)
}
local slackWatcher = hs.application.watcher.new(function(name, eventType, app)
  if eventType ~= hs.application.watcher.activated then return end
  local fnName = name == "Slack" and "enable" or "disable"
  for i, keybind in ipairs(slackKeybinds) do
    -- Remember that lua is weird, so this is the same as keybind.enable() in JS, `this` is first param
    keybind[fnName](keybind)
  end
end)
slackWatcher:start()
```

**Comment by mike-savory** [comment]
Yes, please build something like this into Karabiner-Elements!
To try your version, should I just compile and run with Xcode?
(obviously not sufficiently technical ;-)

**Comment by nriley** [comment]
There are instructions in the README; if you have questions either post here or let me know. I just did a [quick binary release](https://github.com/nriley/Karabiner-Elements-App-Profiles/releases) so you don't need Xcode.

**Comment by planetscripton** [comment]
@nriley Excellent solution. Been waiting for a simple way to switch my ctrl/cmd key when in the remote desktop beta client and Parallels ever since upgrading to Sierra. Your solution works perfectly.

**Comment by mike-savory** [comment]
@nriley Thanks for the Binary release, will try it out, @planetscripton can you share your config please

**Comment by kkuhle** [comment]
@nriley this sounds great.  Thanks for writing it up.  I am brand-new to mac and I just don't really get all of it.  I believe the plist file is a configuration file which I have attempted to modify for iterm2.  There are just some things I'm sure I'm missing.  Is there any chance we could get an example config file so that I know how to get this going?  @planetscipton if you could share yours too that would be great.  :)

**Comment by mike-savory** [comment]
Here is what I did to get it working (as far as I can recall)
Follow the link a few posts ago, and download the zipped file "Karabiner-Elements-App-Profiles.zip"
Follow the instructions in that zip file:

Copy the binary file "Karabiner-Elements-App-Profiles" to /usr/local/bin, you may need to create this folder (it seems like installing Wireshark creates this folder and installs wireshark binary links) or authenticate to copy into it.

Install the included launchd plist in ~/Library/LaunchAgents and load it
i.e.  copy the file into that location and run the command 
launchctl bootstrap gui/501 ~/Library/LaunchAgents/net.sabi.Karabiner-Elements-App-Profiles.plist 
see https://babodee.wordpress.com/2016/04/09/launchctl-2-0-syntax/
Log-out and login again to test to works

Rename one or more Karabiner Elements profiles with apps' bundle identifiers
So I have profiles named
Default Profile
com.microsoft.rdc.osx.beta
com.barebones.bbedit
com.apple.Safari

And for example in Karabiner-Elements, under the com.microsoft.rdc.osx.beta profile I have keycaps to make:
Left Command  => Left Control
Left Control  => Left Command

Hope that helps
(set KE to display the menu bar icon so you can check what profile is active as you switch apps)

**Comment by kkuhle** [comment]
@mike-savory this works great!  Thanks a lot!

I think this was especially helpful.

launchctl bootstrap gui/501 ~/Library/LaunchAgents/net.sabi.Karabiner-Elements-App-Profiles.plist

I was able to find a plist file for the app that I am doing which is iterm2.  I'm sure I will be adding some more.  Would you mind sharing what you use to get your bundle identifiers for apps?

**Comment by nriley** [comment]
@mike-savory thanks for helping out!

I use my [`launch`](https://sabi.net/nriley/software/#launch) tool to get them; in Terminal type `launch -f ` and drag an app onto the window, e.g.:

```
% launch -f /Applications/Mail.app 
/Applications/Mail.app: scriptable OS X application package 
	type: 'APPL'	creator: 'emal'
	display name: Mail
	architecture: Intel x86-64
	bundle ID: com.apple.mail
```

If you have Spotlight enabled you can also use `mdls`:

```
% mdls -name kMDItemCFBundleIdentifier /Applications/Mail.app 
kMDItemCFBundleIdentifier = "com.apple.mail"
```

**Comment by kkuhle** [comment]
@nriley  launch works well.  Thanks, and thanks for writing this up to allow per app settings!

**Comment by toonetown** [comment]
I threw together a quick homebrew formula to simplify installing.  Just install the karabiner-elements cask, then the tool that @nriley shared and add it to start up:

```bash
brew cask install karabiner-elements
brew install https://raw.githubusercontent.com/toonetown/homebrew-extras/master/Formula/karabiner-elements-app-profiles.rb
brew services start karabiner-elements-app-profiles
```

**Comment by lidraro** [comment]
This works perfectly, thank you very much for putting the work to do this. I love open source community.

**Comment by LucaMarconato** [comment]
Working perfectly, thank you!

**Comment by 3rd3** [comment]
Anything new on this?

**Comment by LucaMarconato** [comment]
Now it is a default feature

**Comment by 3rd3** [comment]
In 0.91.13? How can I use it?

**Comment by garbage914** [comment]
I am also curious as to how to use this feature on Karibiner elements. I'm not able to find it as a default feature. Could you please explain @LucaMarconato?
(I would like Karibiner elements automatically switch to one profile when I'm using Teamviewer [that switches the command and control keys] and another for all of my other applications)

**Comment by LucaMarconato** [comment]
Look at this link: https://github.com/tekezo/Karabiner-Elements/issues/808 
I have based my karabiner.json file on transamericamoon one's and it is working.

**Comment by garbage914** [comment]
@LucaMarconato: Any changes I make to the script result in it not showing up in the Complex Modifications window in Karibiner Elements. Could you please tell me how I would tweak it so that the switch between keys only gets activated when Teamviewer is the front-most window?
(as of now, I can enable the original script and the command and control keys are switched in every application)

**Comment by LucaMarconato** [comment]
You can find my configuration [https://pastebin.com/VFZZVU2q](here). Try replacing my bundle identifier with the one of TeamViewer.

**Comment by garbage914** [comment]
@LucaMarconato Thank you so much for sending that. When I replace TeamViewer for Terminal, I get a "parse" error saying there's an unexpected '"' (unexpected quotation mark) and it doesn't make the changes in Terminal. If I run it without replacing teamviewer, your script runs perfectly and all works in Terminal.

**Comment by toonetown** [comment]
@garbage914 I have found the documentation around configuration of complex modifications kind of lacking...but have somewhat been able to piece together a bunch of thoughts (and an example configuration that I use) [here](https://gist.github.com/toonetown/ec7d3e74807fcc57362dc34dd47a4570).  Maybe it will help a bit?

**Comment by nawkwan** [comment]
@toonetown I am new to the party, and want verify that your solution (["configuration"](https://gist.github.com/toonetown/ec7d3e74807fcc57362dc34dd47a4570)) does not require nriley's 3rd party daemon?

@LucaMarconato Why do you prepend a caret ('^') to the bundle_identifiers in your configuration?
e.g.,
`"bundle_identifiers": [
                                            "^org.gnu.Emacs",
                                            "^com.apple.Terminal"
                                        ],`

**Comment by nawkwan** [comment]
Does anyone know if there is a `frontmost_application_ifnot` condition type (or something to that effect) available?

**Comment by LucaMarconato** [comment]
@nawkwan try with `frontmost_application_unless`

**Comment by garbage914** [comment]
@toonetown Thank you so much for that. I actually got it working just before you sent that with this: https://forum.keyboardmaestro.com/t/switching-command-and-control-keys/7721/27?u=cinematree

Thank you to all who helped.

**Comment by quinoa42** [comment]
Hi guys, is there a way to work around with alfred? I have set to use hjkl in kindle with the `frontmost_application_if` approach, but I just found out that when such an app is in the front, the key remappings also cause typing hjkl in alfred to result as arrow keys.

**Comment by napisani** [comment]
old thread here, but i use this script i wrote to swap profiles based on the current foreground app.
This basically allows you to create a json file of bundleNames -> karabiner profile names (including a default mapping)

Hope this helps someone

https://github.com/napisani/karabiner-profile-swapper

**Comment by nriley** [comment]
Sorry you had to spend the time writing that instead of using pretty much the same thing I wrote, which you can see linked above (https://github.com/pqrs-org/Karabiner-Elements/issues/137#issuecomment-277871527), just using Swift rather than PyObjC.  These days I don't use it as I make individual modifications conditional with frontmost_application_if ([example](https://sabi.net/nriley/software/right-option-to-vt220-insert.json)).

**Comment by xinatcg** [comment]
Should use the `Complexity modification` to achieve same result, 

such as the Remote Desktop swap keys, can import the Complexity modification : https://ke-complex-modifications.pqrs.org/?q=remote%20desktop  `Virtual Machine and Remote Desktop (Microsoft or other)` works on mac~

It is based on the https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/frontmost-application/
