### ISSUE TITLE
Change Japanese keyboard to English after upgrading to version 12.0.6

### ISSUE THREAD

**Issue by Paradise0617** [tekezo/Karabiner-Elements#1373]
Hi,
Im using Macbook Pro 2016 with Japanese keyboard and before version 12.0.6, I could change the Japanese layout into standard English one. However after upgrading to version 12.0.6, I can not find way yo switch keyboard to English anymore. 
Anyone can help here? Im sure many ppl may face the same issue.
Thanks!

**Comment by tekezo** [comment]
Does not Keyboard Setup Assistant work?
https://pqrs.org/osx/karabiner/document.html#configuration-keyboard-type
