### ISSUE TITLE
How can I set Chinese input?

### ISSUE THREAD

**Issue by YOnoda** [tekezo/Karabiner-Elements#1374]
I found someone already released a file to switch Japanese and English using command key, and I want to change Japanese to Chinese (Simplified pinyin). But then after I checked the file, I wonder how I can search for `key_code` parameter for Chinese equivalent. There are two `key_code` on the file (`japanese_eisuu` and `japanese_kana`) but what is the Chinese key_code?

And how can I search for other languages such as Korean and Russian? Thanks

**Comment by YOnoda** [comment]
I forgot to add the file - https://pqrs.org/osx/karabiner/complex_modifications/#international the first item on *For Japanese*.

**Comment by apm1467** [comment]
You are probably looking for [this](https://github.com/pqrs-org/KE-complex_modifications/blob/master/docs/json/example_select_input_source.json).

`japanese_eisuu` and `japanese_kana` are the two special keys on Japanese keyboards. For other language you can select input source directly using `input_source_id`. 

In the Karabiner-EventViewer app (which is installed automatically when you install Karabiner-Elements), you can find you current `input_source_id` under the "Variables" tab.

**Comment by YOnoda** [comment]
Thanks for letting me know it. I tried it, but only found that while the keyboard icon on the top-right menubar changes to Chinese, the actual input (characters I type in) is still English...

I feel I had found a similar issue on Korean, and it also happened on the old Karabiner IIRC.
