### ISSUE TITLE
Map mouse button3+button4 to something

### ISSUE THREAD

**Issue by pranavram-n** [tekezo/Karabiner-Elements#1377]
I have a mouse with 5 buttons : the standard 3 plus two more on the side. I've successfully mapped button4 and button5 to ctrl+(left/right) to shift between spaces. The only functionality that's preventing me from moving away from the trackpad still is the ability to go back to the previous page in a browser.

Ideally, Id like to map a combination like mouse scroll button (button3) + button4 to cmd+[. Is this possible, and if so, can someone please share a sample json of the same?

Thanks

**Comment by jwanja** [comment]
I've been trying to pour over the docs today to figure out if this is possible...so far as I can tell it isn't possible to make the "to" key be a combination or sequence of keys. Please someone let us know if this isn't the case
