### ISSUE TITLE
Caps lock delay has returned after update

### ISSUE THREAD

**Issue by mnelson239** [tekezo/Karabiner-Elements#1384]
Hello!

I recently updated 12.0.7 and the delay on the caps lock key is back and I can't get it to go away.

I previously had the simple modification from caps_lock...to caps_lock setting which had removed the delay on the caps lock key. This seems to not be working after the update, however. I tried adding ""hold_down_milliseconds: 0" in the simple modification section of the json file, but no luck (not sure if that's where it's supposed to go).
I am on OS 12.13.4 (High Sierra).
Any help is greatly appreciated!

**Comment by matsaman** [comment]
Same as #1358?

**Comment by matsaman** [comment]
My understanding of the comments at that bug suggest support has merely been removed, and that hold_down_milliseconds is useful only in a peripheral way. I would expect both these bugs to be closed otherwise.

**Comment by matsaman** [comment]
Your mom is stale.
