### ISSUE TITLE
Single keypress results in lots of keypresses after installing Karabiner-Elements

### ISSUE THREAD

**Issue by ArondeParon** [tekezo/Karabiner-Elements#139]
Well, this was interesting.

I just installed Karabiner-Elements to replace Seil (which I use to remap my capslock) key. I did not change any configuration, but immediately noticed that my keyboard became completely unusable. After installing, each keypress (regardless of key) results in about 10-20 duplicate keypresses.

I tried rebooting to see if that would solve the issue, but it did not. Then I tried removing the app, but that requires me to type in my password, which is pretty much impossible in this situation. I then opened the app and used the quit function. This, finally, resolved my issue.

Some details about my setup:

Macbook Pro 15" (late 2014)
MacOS Sierra 

If there is any more information that could help solve this issue, feel free to ask.

**Comment by aristidesfl** [comment]
Possibly related: https://github.com/tekezo/Karabiner-Elements/issues/744 (only seems to happen with the capslock key)
