### ISSUE TITLE
Karabiner-Elements switches the "ºª" and "<>" keys (Spanish layout)

### ISSUE THREAD

**Issue by OMA2k** [tekezo/Karabiner-Elements#1392]
I've lately started using a Logitech K750 keyboard (PC variant) with my Mac Mini and I've found that as soon as Karabiner Elements is working, the "ªº\\" and "><" keys of my Spanish layout keyboard are switched. Is this a bug? How can I get them switched back to their original positions?

**Comment by diegofn** [comment]
Yes, I have the same problem with the karabiner 12 version. Is there any way to fix it?

**Comment by diegofn** [comment]
I downgrade to the 11.6 version and it works perfectly.

**Comment by OMA2k** [comment]
Well, downgrading can be a solution, but the point of posting here is so they can fix the problem in future versions, so we don't have to be stuck with a version which might stop working in a future OSX update, as has happened in the past.

**Comment by christo-ph** [comment]
Issue still persists (German Keyboard)

**Comment by OMA2k** [comment]
Issue still persists for me as well.

**Comment by moniquelyse** [comment]
Issue still persists macOS Monterrey Spanish Keyboard. In this case it isn't switching the keys, but copying the |° (at the left of the 1 key).

**Comment by StefanFaulhaber** [comment]
This is still persisting (german keyboard): _<>_ (left to _Y_) is mixed up with _^°_ (left to _1_)

**Comment by OMA2k** [comment]
Yes, this issue still persist to this day, so the only solution is to switch those two keys again in Karabiner Elements by adding the following to "Simple modificatons" in the Preferences window:

"grave_accent_and_tilde (`)  -->  "non_us_backslash"
"non_us_backslash"  -->  "grave_accent_and_tilde (`)

By adding those, the switched keys with be switched back to their original positions.

**Comment by lterfloth** [comment]
Any updates on this issue? Still persists for me.

**Comment by lterfloth** [comment]
Solved it, thank you very much!

**Comment by carlphilip** [comment]
Hi,
I have the same problem but the problem it is not solved by swapping and configuring the Virtual Keyboard does not work. I also tried to uninstall Karbiner and removing all the files. Still the <> keys are in the wrong position. What can i do?

**Comment by frantortosa** [comment]
"grave_accent_and_tilde (`) --> "non_us_backslash"
"non_us_backslash" --> "grave_accent_and_tilde (`)

This worked for me on:
MX Keys (Spanish),
MAC OS Monterey 12.6
Karabiner-Elements 14.10.0

Thanks @davoclavo and others proposing this.

**Comment by OMA2k** [comment]
@davoclavo : I see you copied my solution. It even contains the same little mistake I did of not closing the quotes at the end of the first "grave_accent_and_tilde", so it's clearly a copy & paste of my comment just a couple of messages above yours. I don't see the point of repeating what I said just below my comment, other than to add some fancy screenshots and adding an unnecessary second step (since that's the default value), but thanks for your contribution anyway :)

**Comment by OMA2k** [comment]
Nah, not offended, of course. Just found it odd. I guess it somewhat makes sense.
