### ISSUE TITLE
Feature: pass thru

### ISSUE THREAD

**Issue by seanfarley** [tekezo/Karabiner-Elements#140]
Another feature from Karabiner missing is the fn+esc key combo to temporarily disable Karabiner.

**Comment by SympliG0th** [comment]
I downloaded   the program just for that function and nothing else..I thought it would have been a basic one to have and without the ability to write your own complex modifications you can't even add it yourself.


This is almost a year after this post and I still can't figure out how to do this..please tell me I'm missing something!
