### ISSUE TITLE
Remap Mouse Buttons to Forward/Backwards in Browser

### ISSUE THREAD

**Issue by d0paminefiend** [tekezo/Karabiner-Elements#1403]
I want to remap Kensington Expert Wireless Trackball buttons 3 and 4 (top left and right buttons) for forward and backward in all browsers. I do not know how to use code.

**Comment by jwanja** [comment]
For the two browsers that I use, Safari and Chrome, their Back/Forward shortcuts aren't possible to recreate with KE. The workaround that I use, no guarantees it works with your setup is the following:

• Change the shortcut for Back/Forward in your browser to F18/F19.
    • Go to Preferences > Keyboard > Shortcuts > App Shortcuts
    • Add a shortcut for "Back" and "Forward" for your browser
• Remap the buttons on your mouse to F18/F19

This workaround starts falling apart if you use an application that makes use of F18/F19.
