### ISSUE TITLE
Menu bar icon is misaligned

### ISSUE THREAD

**Issue by simgust** [tekezo/Karabiner-Elements#1404]
It seems the menu bar icon is misaligned within its confines. It looks like it’s a lot closer to the left icon than the right.

<img width="241" alt="skjermbilde 2018-05-20 kl 07 52 07" src="https://user-images.githubusercontent.com/6162667/40276177-63082f8a-5c03-11e8-8459-9febaa0b73f7.png">

**Comment by tekezo** [comment]
Thank you for feedback!

I fixed this issue at v12.0.9.
You can test it with the latest beta version.

![Check for beta updates](https://pqrs.org/osx/karabiner/img/karabiner-elements-check-for-updates-beta@2x.png)

**Comment by simgust** [comment]
Looks great! :)
