### ISSUE TITLE
Use f1, f2, etc. keys as standard functional keys with external keyboard only

### ISSUE THREAD

**Issue by AmatanHead** [tekezo/Karabiner-Elements#1406]
Hello!

I'd like to configure the "use f1, f2, etc. keys as standard functional keys" setting on per-keyboard basis, i.e. pressing f1 on external keyboard sends the f1 event while pressing f1 on internal keyboard changes screen brightness. Is that possible?

**Comment by nguyenhimself** [comment]
Yeah, in the "Function Keys", you should be able to see drop down menu to choose which function keys settings for which keyboard.

**Comment by AmatanHead** [comment]
This doesn't play nicely with `fn` key.

**Comment by AmatanHead** [comment]
😞 

Actually, double 😞 because of deleted comments.

**Comment by Crymsius** [comment]
Same problem here, would be a neat feature if possible !

I tried to set it with a different profile but it seems the option is not profile-depent.
