### ISSUE TITLE
Multiple Keys Pressed

### ISSUE THREAD

**Issue by myzinsky** [tekezo/Karabiner-Elements#141]
How can I realize something like this:

option + u --> ü
option + shift + u --> Ü

Here is the configuration of the old karabiner:

``` xml
<?xml version="1.0"?>
<root>
  <item>
    <name>Myzinsky Umlaute</name>
    <appendix>Umlaute accesible with CAPSLOCK + aeiou</appendix>
    <identifier>private.myzinsky.umlaute</identifier>
    <autogen>
      --KeyToKey-- KeyCode::O, ModifierFlag::OPTION_L | VK_SHIFT | ModifierFlag::NONE,
      KeyCode::U, ModifierFlag::OPTION_L, KeyCode::O, VK_SHIFT      
    </autogen>
    <autogen>
      --KeyToKey-- KeyCode::O, ModifierFlag::OPTION_L | ModifierFlag::NONE,
      KeyCode::U, ModifierFlag::OPTION_L, KeyCode::O       
    </autogen>
    <autogen>
      --KeyToKey-- KeyCode::A, ModifierFlag::OPTION_L | VK_SHIFT | ModifierFlag::NONE,
      KeyCode::U, ModifierFlag::OPTION_L, KeyCode::A, VK_SHIFT       
    </autogen>
    <autogen>
      --KeyToKey-- KeyCode::A, ModifierFlag::OPTION_L | ModifierFlag::NONE,
      KeyCode::U, ModifierFlag::OPTION_L, KeyCode::A     
    </autogen>
    <autogen>
      --KeyToKey-- KeyCode::U, ModifierFlag::OPTION_L | VK_SHIFT | ModifierFlag::NONE, 
      KeyCode::U, ModifierFlag::OPTION_L, KeyCode::U, VK_SHIFT       
    </autogen>
    <autogen>
      --KeyToKey-- KeyCode::U, ModifierFlag::OPTION_L | ModifierFlag::NONE, 
      KeyCode::U, ModifierFlag::OPTION_L, KeyCode::U      
    </autogen>
    <autogen>-
       -KeyToKey-- KeyCode::S, ModifierFlag::OPTION_L | ModifierFlag::NONE, 
       KeyCode::S, ModifierFlag::OPTION_L 
    </autogen>
  </item>
</root>
```

**Comment by prohtex** [comment]
You can't.

**Comment by takahasix** [comment]
I rewrote "event_manimulator.hpp" for multi-key remap. If you can compile from source code, try it.
https://github.com/takahasix/Karabiner-Elements/tree/takahasix




Put ComplexKey pairs into ck2ck_ at constructor.
```cpp
// control+f -> right_arrow
ck2ck_[ComplexKey(false, false, false, false, false, true, false, krbn::key_code(9))] = ComplexKey(false, false, false, false, false, false, false, krbn::key_code::right_arrow);
                                
// control+b -> left_arrow
ck2ck_[ComplexKey(false, false, false, false, false, true, false, krbn::key_code(5))] = ComplexKey(false, false, false, false, false, false, false, krbn::key_code::left_arrow);
```


The definition of ComplexKey is here.

```cpp
        ComplexKey(bool commandLeft, bool commandRight, bool option, bool shiftLeft, bool shiftRight, bool control, bool fn, krbn::key_code key){
            commandRight_ = commandRight;
            commandLeft_ = commandLeft;
            option_ = option;
            shiftLeft_ = shiftLeft;
            shiftRight_ = shiftRight;
            control_ = control;
            fn_ = fn;
            key_ = key;
        }
```

**Comment by prohtex** [comment]
Would this work to remap modifier+key to multiple keys? For example, if I wanted to remap cmd+enter to "abc"?

**Comment by takahasix** [comment]
No. modifier+key to modifier+key only.

**Comment by matijasss** [comment]
Thanks takahasix this solved for me. I remapped cmd-arows --> option-arrows with following conf: 
ck2ck_[ComplexKey(true, false, false, false, false, false, false, krbn::key_code::right_arrow)] = ComplexKey(false, false, true, false, false, false, false, krbn::key_code::right_arrow);
ck2ck_[ComplexKey(true, false, false, false, false, false, false, krbn::key_code::left_arrow)] = ComplexKey(false, false, true, false, false, false, false, krbn::key_code::left_arrow);
ck2ck_[ComplexKey(false, false, true, false, false, false, false, krbn::key_code::right_arrow)] = ComplexKey(true, false, false, false, false, false, false, krbn::key_code::right_arrow);
ck2ck_[ComplexKey(false, false, true, false, false, false, false, krbn::key_code::left_arrow)] = ComplexKey(true, false, false, false, false, false, false, krbn::key_code::left_arrow);
ck2ck_[ComplexKey(true, false, false, true, false, false, false, krbn::key_code::right_arrow)] = ComplexKey(false, false, true, true, false, false, false, krbn::key_code::right_arrow);
ck2ck_[ComplexKey(true, false, false, true, false, false, false, krbn::key_code::left_arrow)] = ComplexKey(false, false, true, true, false, false, false, krbn::key_code::left_arrow);
ck2ck_[ComplexKey(false, false, true, true, false, false, false, krbn::key_code::right_arrow)] = ComplexKey(true, false, false, true, false, false, false, krbn::key_code::right_arrow);
ck2ck_[ComplexKey(false, false, true, true, false, false, false, krbn::key_code::left_arrow)] = ComplexKey(true, false, false, true, false, false, false, krbn::key_code::left_arrow);

**Comment by jgosmann** [comment]
Thank you, @takahasix ! This is exactly what I needed. [In my fork I rebased the changes to the current master of Karabiner-Elements.](https://github.com/jgosmann/Karabiner-Elements/tree/takahasix)

**Comment by myzinsky** [comment]
Can also something like this be done now: 

option + u --> ü
option + shift + u --> Ü

Regards

**Comment by jgosmann** [comment]
My understanding is it can only be done if the keyboard layout already has a key (or key combination) corresponding to ü/Ü. I think (but might be wrong) Karabiner only remaps the USB key codes that (mostly) correspond to physical keys, these USB key codes are mapped by Mac OS to some internal key codes which are then interpreted by the keyboard layout to produce actual output.

I've been thinking that it might be possible to map combinations like option + u to unused USB key codes (there is a large amount marked as “reserved” in the USB standard) and then edit the keyboard layout to map that key code to, for example, ü. However, at the moment I am not clear about the mapping from the USB key codes to the codes used in the keyboard layout definition.

**Comment by xxchaos** [comment]
Hi,

I have wired Apple Keyboard with Numeric Keypad.
I would like to remap:
CMD+C to right_CTRL+Fn (copy)
CMD+V to right_SHIFT+Fn (paste)
using Karabiner-Elements.
Can someone help me?

**Comment by myzinsky** [comment]
Is there something new? to get something like this:

```
option + u --> ü
option + shift + u --> Ü
```
