### ISSUE TITLE
Don't work with Max Falcon-8 on Mac OS

### ISSUE THREAD

**Issue by kvaleev** [tekezo/Karabiner-Elements#1410]
I own a [MAX Falcon-8 RGB Custom Programmable Mini Macropad Mechanical Keyboard](http://www.maxkeyboard.com/max-falcon-8-rgb-custom-programmable-mini-macropad-mechanical-keyboard-assembled.html) and connect it to my MacBook with a USB cable.

Unfortunately, as long I have Karabiner-Elements opened, it prevents my Falcon-8 from connecting; console log shows connection errors for both USB ports (I guess it's related):

```
default 23:28:12.134141 +0300   kernel  017207.361239 PRT1@14100000: AppleUSBHostPort::disconnect: persistent enumeration failures
default 23:36:54.699711 +0300   kernel  017729.928455 PRT2@14200000: AppleUSBHostPort::disconnect: persistent enumeration failures
```

_System.log_ with a search for `USB` shows nothing, which AFAIK means that USB device is not connected, and Falcon-8 is not shown on as a target device in Karabiner-Elements settings.

When I turn off Karabiner-Elements, Falcon connects and works as expected.

**Comment by jordanegstad** [comment]
did you find a solution for this, @kvaleev? i'm looking at purchasing the keypad and would like to continue using KA.

**Comment by kvaleev** [comment]
Nope, it' still doesn't work with my Falcon.

**Comment by darrenph1** [comment]
Have you tried the program Controllermate for mac?

**Comment by rwillett** [comment]
Just to add my 2c in as this is a stale thread. 

The Falcon-8 does work with Keyboard Maestro as I had it setup. Am in the process of rebuilding so may choose another program but the Falcon-8 works well.
