### ISSUE TITLE
If user doesn't have write permission to existing ~/.config folder, Karabiner will fail to work

### ISSUE THREAD

**Issue by Kvantti** [tekezo/Karabiner-Elements#1416]
**Problem:** Karabiner will install and run but fails to work. Modified keypresses do not change in output or in Eventviewer when set in Preferences. Also unable to save any configuration persistently, Karabiner will just forget anything if preferences window is closed. No indication in log as to why. Tried several times rolling back in versions, uninstalling, reinstalling, and restarting, no joy.

**Reason:** The configuration folder `~/.config` in user directory was already created by another program, in this case by `htop`, using `$HOME/.config/htop/htoprc` for saving preferences with `root` ownership. This prevents Karabiner writing settings there, but this failure is not indicated anywhere as far as I can see?

**How to test:** Run in Terminal:
`ls -la ~ | grep .config`

If you see `drwx------` and `root` or similar like this:
`drwx------   3 root     staff    102 Dec 31 18:13 .config`
– then this might be the issue.

**How to fix:** Run in Terminal:
`sudo chown YourUserName ~/.config`
– to reown the .config folder. 

Attached the log file.
[karabiner_config_folder_ownership_issue_20180523.log](https://github.com/tekezo/Karabiner-Elements/files/2031470/karabiner_config_folder_ownership_issue_20180523.log)

**Comment by feuyeux** [comment]
Let Karabiner-Elements running, firstly.
And then Open "System Preferences > Security & Privacy > Click "Allow".
My KE version is `12.1.0` and OS version is Sierra `10.13.6`

**Comment by bug5654** [comment]
feuyeux's fix worked in OSX 10.14 with KE 12.1.0

**Comment by suka233333** [comment]
I find a way to fix it. Manual  create 'share' folder in the ~/.config folder

**Comment by kookyleo** [comment]
I ran into it again on macOS 15.3

**Comment by Sudrien** [comment]
Just got this error. Sequoia 15.3.2

Here's what I came up with:

If you installed homebrew before Karabiner (or anything else that required sudo or other privilege escalation), it's possible that the ~/.config folder was created with incorrect permissions. You'll need Terminal.

> sudo ls -al ~/.config/

will show files owned by root:staff

To fix this, we will change the ~/.config and ALL the files in it to be owned by the current user. As they are currently owned by root, we have to use root to do this.

>  sudo chown -R $(whoami):staff ~/.config
