### ISSUE TITLE
Swapping section key with left shift

### ISSUE THREAD

**Issue by fez1234** [tekezo/Karabiner-Elements#142]
Hi, I'm having issues with mapping my section key with my left shift. My karabiner.json looks like this. 

`{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                “left_shift”: “non_us_backslash”
            }
        }
    ]
}`

**Comment by talha131** [comment]
First of all `“` is not same as `"`.

Secondly, you file should be like this

```json
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "non_us_backslash": "left_shift"
            }
        }
    ]
}
```
