### ISSUE TITLE
Karabiner-Elements Simple Modifications not working on OS X 10.13.4

### ISSUE THREAD

**Issue by aarellano** [tekezo/Karabiner-Elements#1422]
This morning I updated OS X to 10.13.4, and after that my Simple Modifications are not working anymore.

**Comment by jclarktennis** [comment]
@aarellano I am experiencing the same problem. I assume you closed this issue because it is now working. Could you tell me what you did to get it to work? Thanks.

**Comment by aarellano** [comment]
@jclarktennis I'm sorry, but I don't remember what I did to make it work. I can tell you that it is working now, and I'm running Karabiner-Elements version 12.1.0 and OS X 10.13.6
Hope it helps

**Comment by jclarktennis** [comment]
@aarellano Alright, thanks anyway. I suppose I'll update to 10.13.6 and see what happens.
