### ISSUE TITLE
any reliable way to remove capslock delay on macos?

### ISSUE THREAD

**Issue by Inlesco** [tekezo/Karabiner-Elements#1423]
what i've tried:

- reassigning the capslock key to 'none' in the 'modifier keys' menu in 'keyboard' settings. clicking ok. capslock didn't work anymore. went back to 'modifier keys' menu, reassigned the inactive capslock to capslock again. saved the settings by closing the menu.

however, capslock still had the delay.

- enabling slow keys and putting delay at 0

not a viable solution again as the keyrepeat rate is too slow for comfortable coding, backspace works very slow, even on the highest settings of keyrepeat.

I'm starting to hate Apple as they put such a stupid feature without a proper way to disable it. This is ridiculous...

So - is there a way to disable the capslock delay with karabiner or something else?

**Comment by Inlesco** [comment]
alright, it looks like I've may have solved the problem...

I've uninstall the Karabiner version >11.6 and installed an older one, which, in Virtual keyboard settings, has this setting for Caps lock delay in ms.

Initially, caps lock delay is set to 0.

the world is safe now.

**Comment by mnelson239** [comment]
THANK YOU!!!

**Comment by Inlesco** [comment]
Resolved as per https://github.com/tekezo/Karabiner-Elements/issues/1423#issuecomment-393060487

**Comment by jaekyeom** [comment]
Thank you for sharing your solution!
By the way, should we just stick with the older version then?
Is there any way to fix this issue in newer versions?

**Comment by rubensayshi** [comment]
@Inlesco please reopen, that's not a proper fix ...

@tekezo the capslock key delay is driving me crazy, it would be SUPER awesome ( I had to press my capslock key like 5 times to do that ) if Karabiner Elements could fix it ^_^

**Comment by jaekyeom** [comment]
@tekezo Any news/thoughts to share, please?

**Comment by tekezo** [comment]
Please follow this instruction.
https://pqrs.org/osx/karabiner/help.html#disable-caps-lock-delay

**Comment by rubensayshi** [comment]
<3 YOU ROCK https://pqrs.org/osx/karabiner/help.html#disable-caps-lock-delay works perfectly!

**Comment by jaekyeom** [comment]
@tekezo Thanks for the comment, but I think I have to stick with 11.6.0 ;)

**Comment by sampalmerbb** [comment]
FYI https://pqrs.org/osx/karabiner/help.html#disable-caps-lock-delay works but still leaves a noticeable lag when using Caps Lock. Karabiner-Elements 11.6.0 truly removes the delay.

**Comment by sampalmerbb** [comment]
> alright, it looks like I may have solved the problem...
> 
> I've uninstalled the Karabiner version >11.6.0 and installed an older one, specifically 11.6.0, which, in Virtual keyboard settings, has a special setting for Caps lock delay, measured in ms.
> 
> Initially, caps lock delay is set to 0. guess what - that's good for me!
> 
> the world is safe now.

This fix worked pretty well for me on macOS 10.14.4. But it made the Caps Lock light on the keyboard stop working, which could be annoying when typing passwords.

**Comment by bernardotaborda** [comment]
Hello.

My Karabiner 11.6.0 stopped working, therefore the CapsLock Delay stopped working too.

In the log I have this:
[2019-09-10 20:58:27.739] [warning] [grabber] virtual_hid_device_client is not connected yet. Please wait for a while.

What can I do? I can't work with this obnoxious delay.

**Comment by aoenth** [comment]
> Hello.
> 
> My Karabiner 11.6.0 stopped working, therefore the CapsLock Delay stopped working too.
> 
> In the log I have this:
> [2019-09-10 20:58:27.739] [warning] [grabber] virtual_hid_device_client is not connected yet. Please wait for a while.
> 
> What can I do? I can't work with this obnoxious delay.
> 
> EDIT: #1930 fixed it.

Thank you, this helped me. I'm using 11.6.0 on macOS 10.15.2 Catalina and it works.

**Comment by yhlai-code** [comment]
> FYI https://pqrs.org/osx/karabiner/help.html#disable-caps-lock-delay works but still leaves a noticeable lag when using Caps Lock. Karabiner-Elements 11.6.0 truly removes the delay.

This link is down. For future people stumble on this issue, the document is now on https://karabiner-elements.pqrs.org/docs/help/how-to/disable-caps-lock-delay/

**Comment by sampalmerbb** [comment]
> Thank you, this helped me. I'm using 11.6.0 on macOS 10.15.2 Catalina and it works.

@aoenth, did you have to do anything else to get it to work? When I upgraded from Mojave to Catalina 10.15.5 then Karabiner stopped working and has this error in the logs:

```text
[2020-06-10 08:38:55.481] [error] [grabber] IOHIDDeviceOpen error: kIOReturnNotPermitted (-536870174) USB Keyboard (device_id:4)
```

**Comment by aoenth** [comment]
> > Thank you, this helped me. I'm using 11.6.0 on macOS 10.15.2 Catalina and it works.
> 
> @aoenth, did you have to do anything else to get it to work? When I upgraded from Mojave to Catalina 10.15.5 then Karabiner stopped working and has this error in the logs:
> 
> ```
> [2020-06-10 08:38:55.481] [error] [grabber] IOHIDDeviceOpen error: kIOReturnNotPermitted (-536870174) USB Keyboard (device_id:4)
> ```

In addition to #1930, I just allowed the `karabiner_grabber` and `karabiner_observer` access to System Preferences > Security & Privacy > Privacy >  Input Monitoring. 
As of macOS 10.15.4, I admitted defeat to Apple and started to use shift keys instead of the Caps Lock for capitalization.

**Comment by sampalmerbb** [comment]
Thanks @aoenth! Yep it's working now after doing that. I ended up using Karabiner-Elements 12.9.0 to set-up the security settings and then downgrading back to 11.6.0: https://github.com/pqrs-org/Karabiner-Elements/issues/2319#issuecomment-641626704

**Comment by Serge-Ntumba** [comment]
It looks like the 11.5.2 update actually fixed it as mentioned in a lot of forums!
GO UPDATE!

Links:

https://forums.macrumors.com/threads/11-5-2-fixes-the-caps-lock-bug.2307280/

https://www.iphonetricks.org/macos-big-sur-11-5-2-bug-fixes-for-mac/

https://forums.macrumors.com/threads/macos-big-sur-11-5-2-20g95-is-live-whats-new.2307246/#:~:text=%234-,Fixed%20the%20Caps%20Lock%20performance%20issue%20I%20was%20experiencing.,-Reactions%3A

https://forums.macrumors.com/threads/more-big-sur-bugs.2306427/page-2#:~:text=After%20some%20brief%20testing%20I%20can%20confirm%20it%20does%20seem%20to%20have%20fixed%20the%20caps%20lock%20issue.

**Comment by aoenth** [comment]
@Serge-Ntumba After updating to 11.5.2, this issue is still not resolved. I don't think your articles are referring to the Caps Lock delay "feature", which is the main topic of this GitHub issue.

In the second article you mentioned, I quote:
> Using Caps Lock to switch between languages was very laggy in macOS 11.5.1. The issue has been fixed by this update!

Other articles seemed to only mention the Caps Lock issue or performance issue that was newly introduced in 11.5.1. The Caps Lock delay is still a "feature" that cannot be turned off.

**Comment by wokalek** [comment]
"Fix" in Karabiner is doing nothing now.

**Comment by andmckay01** [comment]
Most recent info straight from https://karabiner-elements.pqrs.org/docs/help/how-to/disable-caps-lock-delay/

"Karabiner-Elements disables the caps lock delay without any action since v13.3.0."

Simply downloading and giving Karabiner elements the proper permissions should now resolve this issue for you!

**Comment by ken830** [comment]
New Mac user here (I was assigned an M1 MacBook Pro for work 3 years ago) and noticed the caps lock delay from day one. Finally getting around to trying to fix it and stumbled across Karabiner and this thread. I have Karabiner Elements 14.13.0 installed on macOS 14.4.1 and the caps lock key still has a delay. Is there any way for me to eliminate the delay?
