### ISSUE TITLE
Allow selection of the key/key combination to be remapped by pressing it

### ISSUE THREAD

**Issue by iammeat** [tekezo/Karabiner-Elements#1425]
At the moment, remapping requires knowing the key name in the dropdown to be able to select it.  My PC keyboard has back, forward, home, mail, calculator, music, play/pause, volume down, volume up and mute keys across the top.  I'm not able to find the back, forward, home, mail or calculator keyboard keys in the list when adding a remap.

Is it possible to add a keypress detection feature where users simply tap the key or combo and have it show up for confirmation?

This would make configuration much easier, especially for keyboards that have keys which aren't in the list of Karabiner.

**Comment by abcdenis** [comment]
I think 'point and see' approach is easier than 'choose from list'.

My issue and solution:
Durgod K320 with 'menu key' on the right side of space, choosing 'PC->menu' didn't work.

Installed Key Codes from https://manytricks.com/
Press key and get:
```
Key Down
	Characters:	
	Unicode:		16 / 0x10
	Keys:		
	Key Code:	110 / 0x6e
	Modifiers:	256 / 0x100 
```
Write "key codes 110 0x6e modifier 256 0x100" in google and found this: 
https://superuser.com/questions/267604/mac-how-do-i-remap-the-context-menu-key-on-my-keyboard-to-the-command-key
'application -> right Command' mapping works but its a bit long way to achieve my goal.

**Comment by MuhammedZakir** [comment]
You can use EventViewer\* to find key codes.

\* `Karabiner-Elements menu > Launch EventViewer` or `KE-EventViewer.app`

**Comment by yuki2006** [comment]
I'd like to propose an implementation for this and get your feedback before turning it into a PR.

## Approach

Reuse the existing libkrbn HID value monitor (the same mechanism Karabiner-EventViewer uses). Add a "Capture by pressing a key" entry at the top of the existing *from*/*to* menus in Simple Modifications (and the *to* menu in Function Keys). When selected, the next momentary-switch *down* event is converted to a simple-modification JSON string via `libkrbn_get_momentary_switch_event_json_string` and passed straight to the existing update action. While capturing, the menu label shows "Press a key…", and reopening the menu offers "Stop capturing".

This keeps everything inside the existing picker (no extra buttons), needs no data conversion, and requires no libkrbn change.

## Code sketch

New `src/apps/share/swift/LibKrbn/SimpleModificationKeyCapture.swift`:

```swift
import Foundation

private func callback(
  _ deviceId: UInt64,
  _ isKeyboard: Bool,
  _ isPointingDevice: Bool,
  _ isGamePad: Bool,
  _ usagePage: Int32,
  _ usage: Int32,
  _ logicalMax: Int64,
  _ logicalMin: Int64,
  _ integerValue: Int64
) {
  // We are only interested in key/button down events.
  if integerValue == 0 {
    return
  }

  Task { @MainActor in
    // Only events that can be used as a simple modification target are acceptable.
    if !libkrbn_is_momentary_switch_event_target(usagePage, usage) {
      return
    }

    var buffer = [Int8](repeating: 0, count: 256)
    libkrbn_get_momentary_switch_event_json_string(&buffer, buffer.count, usagePage, usage)
    let jsonString = String(utf8String: buffer) ?? ""
    if jsonString.isEmpty {
      return
    }

    LibKrbn.SimpleModificationKeyCapture.shared.handleCapturedEvent(jsonString)
  }
}

extension LibKrbn {
  // Captures a single physical key/button press and reports it as a simple
  // modification JSON string (e.g. `{"key_code":"a"}`).
  @MainActor
  public class SimpleModificationKeyCapture: ObservableObject {
    public static let shared = SimpleModificationKeyCapture()

    @Published public private(set) var capturingID: String?
    private var completion: ((String) -> Void)?

    public func capturing(id: String) -> Bool {
      capturingID == id
    }

    public func start(id: String, completion: @escaping (String) -> Void) {
      stop()  // cancel any capture already in progress
      capturingID = id
      self.completion = completion
      libkrbn_enable_hid_value_monitor()
      libkrbn_register_hid_value_arrived_callback(callback)
    }

    public func stop() {
      if capturingID == nil { return }
      libkrbn_unregister_hid_value_arrived_callback(callback)
      libkrbn_disable_hid_value_monitor()
      capturingID = nil
      completion = nil
    }

    public func observed() -> Bool {
      libkrbn_hid_value_monitor_observed()
    }

    fileprivate func handleCapturedEvent(_ jsonString: String) {
      guard let completion = completion else { return }
      completion(jsonString)
      stop()
    }
  }
}
```

The capture entry added at the top of `SimpleModificationPickerView`'s menu (the picker already takes an `action: (json: String) -> Void`, so the captured json is just fed into it). A new `captureID: String` parameter identifies which picker is capturing:

```swift
@ObservedObject private var keyCapture = LibKrbn.SimpleModificationKeyCapture.shared
// ...
var body: some View {
  let capturing = keyCapture.capturing(id: captureID)

  Menu(capturing ? "Press a key…" : label) {
    Button(action: {
      if capturing {
        keyCapture.stop()
      } else {
        keyCapture.start(id: captureID, completion: action)
      }
    }, label: {
      if capturing {
        Image(systemName: "stop.circle"); Text("Stop capturing")
      } else {
        Image(systemName: "record.circle"); Text("Capture by pressing a key")
      }
    })

    Divider()

    // ... existing category/entry menu unchanged ...
  }
}
```

Callers pass a stable id (e.g. `"\(index)-from"`, `"\(index)-to"`) and stop capture on device switch / `onDisappear`.

## Status / honest caveat

It builds cleanly (Release, `-warnings-as-errors`, Swift 6) and the UI behaves as intended (the label switches to "Press a key…" on capture). However, I have **not verified the full runtime end-to-end** on my machine: a locally built, ad-hoc-signed Settings.app can't connect to the officially signed services, and the Settings app would also need its own Input Monitoring permission (today EventViewer is the one that observes HID events). So the actual "press → field is filled" path is currently unverified by me.

Questions before I open a PR:

1. Is this approach (HID value monitor inside the Settings app + a capture entry inside the picker) acceptable in principle?
2. Capture requires Input Monitoring permission for the Settings app. Should it prompt like EventViewer does (an alert guiding the user to grant it), or would you prefer a different UX?

Happy to open a PR if the direction looks good.
