### ISSUE TITLE
@ symbol?

### ISSUE THREAD

**Issue by dawnchandler** [tekezo/Karabiner-Elements#1427]
I was looking for a keycode for the @ character, but couldn't find one.

(Other names: at symbol, at sign, at character, commercial at, email, handle, arroba, arobase, amperand, ampersat, strudel.)

Am I not reading the list of keycodes (#925) clearly? 

If there isn't a keycode for @, is there some other way I can send the character, like left_shift + 2?

Thanks in advance!

**Comment by endrebak** [comment]
Open eventviewer and press the key that usually gives you @.

Example: 
<img width="878" alt="screen shot 2018-06-07 at 11 43 04" src="https://user-images.githubusercontent.com/17778898/41091921-fdd7a264-6a47-11e8-8308-44454d27dbf0.png">

For me it was called backslash. Your keyboard likely differs.

**Comment by BenjaminConant** [comment]
@dawnchandler you can reference the @ symbol by using a combination of key_code and modifier.  

```
 {
                                "type": "basic",
                                "from": {
                                    "key_code": "c",
                                    "modifiers": {
                                        "mandatory": [
                                            "control"
                                        ],
                                        "optional": [
                                            "caps_lock",
                                            "option"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "2",
                                        "modifiers": [
                                            "left_shift"
                                        ]
                                    }
                                ]
                            }
```
becuase my @ symbol is above my 2 the keycode is 2 and the modifier is left_shift.

**Comment by dawnchandler** [comment]
@BenjaminConant Thank you for the reply! I procrastinated doing this for 2 years but I finally got around to it and your solution worked. 😄

**Comment by MadPad333** [comment]
Hey guys

I try this on my Swiss Keyboard. I just want to be able to use ALT GR (right_option) + number 2 to get the @ sign (which is with right_option + G at the moment.

I'm new to Mac but was able to find the config file, where I think I need to enter the code, but the one from above did not work. So perhaps I did something wrong, or it is not for ALT GR + 2 for the @ sign. 

The second thing I have is that the <> keys ar working on my Macbook, but when I press the exact same buttons on my external keyboard I get §° instead. So I need to swith them as well.

Thanks a lot for any help.

Kind regards
Patrick

**Comment by AndyBitz** [comment]
For anyone that has issues with `@` on a German qwertz keyboard, I had to add `left_control` to the `modifiers` to make it work. Leaving it here because this was the first thing I found when trying to fix it.

```json
{
    "description": "Right Option + L → Ctrl + Option + L (for German layout @)",
    "manipulators": [
        {
            "from": {
                "key_code": "l",
                "modifiers": {
                    "mandatory": ["right_option"],
                    "optional": ["any"]
                }
            },
            "to": [
                {
                    "key_code": "l",
                    "modifiers": ["right_option", "left_control"]
                }
            ],
            "type": "basic"
        }
    ]
}
```

**Comment by ncarrerakevin** [comment]
> [@dawnchandler](https://github.com/dawnchandler) you can reference the @ symbol by using a combination of key_code and modifier.
> 
> ```
>  {
>                                 "type": "basic",
>                                 "from": {
>                                     "key_code": "c",
>                                     "modifiers": {
>                                         "mandatory": [
>                                             "control"
>                                         ],
>                                         "optional": [
>                                             "caps_lock",
>                                             "option"
>                                         ]
>                                     }
>                                 },
>                                 "to": [
>                                     {
>                                         "key_code": "2",
>                                         "modifiers": [
>                                             "left_shift"
>                                         ]
>                                     }
>                                 ]
>                             }
> ```
> 
> becuase my @ symbol is above my 2 the keycode is 2 and the modifier is left_shift.

This worked for me. Instead of usign "@", just use the combination that gives you @, like 
{
    "description": "Alt gr + Q is actually @",
    "manipulators": [
        {
            "from": {
                "key_code": "q",
                "modifiers": {
                    "mandatory": ["right_command"],
                    "optional": ["any"]
                }
            },
            "to": [
                {
                    "key_code": "@",
                    "modifiers": []
                }
            ],
            "type": "basic"
        }
    ]
}
