### ISSUE TITLE
Karabiner stopped working after update (12.10). Does not register config anymore.

### ISSUE THREAD

**Issue by endrebak** [tekezo/Karabiner-Elements#1432]
Karabiner does not register my config anymore. How do I even start to debug this?

This is what happens after I insert the json code into the karabiner config:

```
[2018-06-06 22:09:35.098] [info] [grabber] Load karabiner.json...
[2018-06-06 22:09:35.103] [info] [grabber] core_configuration is updated.
[2018-06-06 22:09:35.105] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:3) is ignored.
[2018-06-06 22:09:35.106] [info] [console_user_server] Load karabiner.json...
[2018-06-06 22:09:35.108] [info] [console_user_server] core_configuration is updated.
```

Still, none of the modified keys work.

I wonder if the new karabiner messed with some system settings, because it seems nothing I do (revert back to an old version for example) is able to fix the problem.

This is my config (long - every key is remapped): https://raw.githubusercontent.com/endrebak/karabiner_settings/master/karabiner.json

**Comment by endrebak** [comment]
Also, just clicking a button or two in the menu seems to overwrite the config I had selected with a new, default config file.

**Comment by endrebak** [comment]
Reinstalled OS and it is still not working on my completely fresh machine :/ Any pointers/help appreciated.

**Comment by tekezo** [comment]
You should remove a duplicated `complex_modifications` entry.
https://github.com/endrebak/karabiner_settings/blob/master/karabiner.json#L10-L18

**Comment by endrebak** [comment]
Ah, the old karabiner accepted it. Will try. Thanks :)

**Comment by endrebak** [comment]
You are a star! Thanks!
