### ISSUE TITLE
[error] [grabber] complex_modifications json error: modifier should be string form: ["any"]

### ISSUE THREAD

**Issue by endrebak** [tekezo/Karabiner-Elements#1433]
I had a config-file which worked well on some previous unknown version of karabiner.

Now I get the error

´´´
[error] [grabber] complex_modifications json error: modifier should be string form: ["any"]
´´´

What does it mean? How do I fix it? Google returned no clues.

Here is my config: https://github.com/endrebak/karabiner_settings/blob/master/karabiner.json

**Comment by tekezo** [comment]
The `modifiers` in `to*` must not contain `mandatory` and `optional`.
https://pqrs.org/osx/karabiner/json.html#to-event-definition

You can solve the error by removing the following lines:
https://github.com/endrebak/karabiner_settings/blob/master/karabiner.json#L3249-L3253
