### ISSUE TITLE
How to set the shortcut key mapped to delete a row (control+a k k)?

### ISSUE THREAD

**Issue by GanZhiXiong** [tekezo/Karabiner-Elements#1436]
Can Karabiner do that?
Could you please provide me with JSON? 
Thank you very much.

**Comment by michelkoga** [comment]
`            {
			"description": "control + a to delete row",
			"manipulators": [
				{
					"type": "basic",,
					"from": {
						"key_code": "a",
						"modifiers": {
							"mandatory": [
								"left_control"
							],
							"optional": [
								"caps_lock"
							]
						}
					},
					"to": [
						{
							"key_code": "delete_or_backspace",
							"modifiers": "right_command"
						}
					]
				}
			]
		},`

**Comment by GanZhiXiong** [comment]
You can only delete the string in front of the cursor. What I want to do is delete the line at the end of the line or in the line. In a nutshell, it's just control + a, k, k.

**Comment by GanZhiXiong** [comment]
What I want to do is press 'control' not to loosen, then press 'a' to loosen, then press 'k' to loosen, and finally press 'k' to loosen.
Thanks.

**Comment by biletskyy** [comment]
You can combine key combinations like this
```
"to": [
    {
        "key_code": "a",
        "modifiers": ["left_control"]
    },
    {
        "key_code": "k",
        "modifiers": ["left_control"]
    },
    {
        "key_code": "k",
        "modifiers": ["left_control"]
    }
]
```

**Comment by GanZhiXiong** [comment]
@biletskyy  thanks,You solved my problem.👍
