### ISSUE TITLE
How to change space to right command?

### ISSUE THREAD

**Issue by mcneil23** [tekezo/Karabiner-Elements#144]
I have a "stuck" space on my MBP keyboard. Karabiner helps me to remap "space" to the "right command" which is a life-saver for me.

I migrated to karabiner element after I updated MacOS Sierra.

I have tried a lot in karabiner element to realize the previous remap and got some trouble.

How to write that in the ".json" file? Thank so much for that help.

**Comment by bvankuik** [comment]
To be clear, you want to remap the spacebar to right-command?

I believe this should work.
```
{
    "profiles": [
        {
            "name": "mcneil23",
            "selected": true,
            "simple_modifications": {
                "spacebar": "right_command"
            }
        }
    ]
}

```

**Comment by mcneil23** [comment]
Thanks so much for your help.
I may have tried this already which did not work.
Is that because the space key is stuck which means it is tapped all the time?

**Comment by bvankuik** [comment]
Yeah, maybe. The above works on my MacBook Air. So I couldn't say why it's not happening in your case. Have you launched Karabiner-EventViewer and see what keys are triggered?

**Comment by mcneil23** [comment]
Yes, the space key is triggered, all the time.
But it worked on Karabiner.

**Comment by carlosvigil** [comment]
"right_command": "spacebar"
