### ISSUE TITLE
How to split karabiner.json into multiple files?

### ISSUE THREAD

**Issue by nikitavoloboev** [tekezo/Karabiner-Elements#1440]
I know that JSON does not allow linking to other JSON files as per its specification.

However I do want to be able to link to some other file or files that will get sourced from original `~/.config/karabiner/karabiner.json` config.

For example if I wanted to use @tekezo launcher generator [here](https://github.com/pqrs-org/KE-complex_modifications/blob/master/src/json/personal_tekezo_launcher_mode_v4.json.rb). I want to generate and override some file that is not `karabiner.json`. My current old Karabiner configuration is [12,000 lines of XML](https://github.com/nikitavoloboev/dotfiles/blob/master/karabiner/private.xml) which once I translate it to Elements will be in the order of 40,000 lines of JSON or even more. I want to be able to split this into multiple files.

I am also writing [my own config generator](https://github.com/nikitavoloboev/karabiner-generator) as I don't want to ever edit bare JSON and want an actual language that is suited for the task.

Thank you.

**Comment by calvinwyoung** [comment]
@nikitavoloboev Did you ever end up solving this problem? The approach I'm taking right now is to only use complex modifications, and splitting my config into multiple asset files that live in the "asset/complex_modifications" directory. Then from the UI I can import all of my rules and not have to worry about accidentally modifying the karabiner.json file via UI. Unfortunately this doesn't work if you need to change anything else in `karabiner.json`.

**Comment by calvinwyoung** [comment]
Got it, that looks like a good solution. Thank you!

**Comment by proxseas** [comment]
It would be great if it was possible to divide the config json file into smaller files. Goku looks impressive, but I don't want to introduce another tool for something so simple.
