### ISSUE TITLE
12.1.1 and 12.1.2 releases

### ISSUE THREAD

**Issue by core-code** [tekezo/Karabiner-Elements#1442]
whats up with the 12.1.1 and 12.1.2 releases? are they official? they are listed here
https://github.com/tekezo/pqrs.org/tree/master/webroot/osx/karabiner/files
but neither here
https://github.com/tekezo/Karabiner-Elements/releases 
nor on the website.

if they are beta releases, please mark them as such.

thanks

**Comment by tekezo** [comment]
x.x.1 - x.x.99 are beta releases.

You don't need to find files from github.
Release files are listed https://pqrs.org/osx/karabiner/ and 
 https://pqrs.org/osx/karabiner/history.html#history .

**Comment by carrigmore** [comment]
@tekezo will the new release include the pc number lock key mapping? thanks.
