### ISSUE TITLE
Keyboard specific modifiers are not respected

### ISSUE THREAD

**Issue by SeeThruHead** [tekezo/Karabiner-Elements#1443]
I use two keyboards regularly on my mac

One of those is a windows keyboard and requires the option and command modifiers to be swapped.

Changing the modifiers in Settings > Keyboard > Modifiers for that keyboard has no effect.
Changing the modifiers for Karabiner VirtualHIDKeyboard works. but applies to both keyboards. (Forcing me to change the settings every time i switch keyboard)

**Comment by bendur** [comment]
I'm seeing this issue as well after the MacOS 10.13.5 update, not sure if that's what did it or not.
