### ISSUE TITLE
Problem about simultaneous mode on password input dialog

### ISSUE THREAD

**Issue by tatsy-ymj** [tekezo/Karabiner-Elements#1445]
I found a problem about simultaneous option.

1. Add ["Japanese NICOLA (partial)"](https://pqrs.org/osx/karabiner/complex_modifications/example.html) and enble it.
2. Press "Kana" key.
3. Select "Lock Screen" from "Apple" menu, and put Mac to sleep.
4. Press any key to wake up Mac. Password input dialog appears.
5. Key inputs are interpreted as Romaji. For example, when I press "d" key, "te" is input.

On other password dialogs, this symptom is not occured.

**Comment by tekezo** [comment]
Thank you for feedback!

I updated Japanese NICOLA to disable it on loginwindow in this commit.

https://github.com/pqrs-org/KE-complex_modifications/commit/239245e74d08d3ac5ee941172c4c9a4f9d42eaba#diff-4fb3249cbe85fc292419716c86f94e1f

**Comment by tatsy-ymj** [comment]
Thanks!
