### ISSUE TITLE
Interference with Logitech Caps Lock notifications

### ISSUE THREAD

**Issue by haltlos** [tekezo/Karabiner-Elements#1449]
macOS version: macOS 10.13.5
Karabiner version: Karabiner-Elements 12.1.0
Your Mac hardware: Macmini6,1 (Late 2012 Mac mini)
Your keyboard hardware: Logitech K780

Logitech Options (version 6.90.109) allows for three notification settings:
![screen shot 2018-06-16 at 19 05 40](https://user-images.githubusercontent.com/4324234/41501024-b497fade-719c-11e8-8d1a-882901312f8d.png)

When Karabiner-Elements is running, the notifications for Caps Lock are suppressed. The Caps Lock key itself works, but the notifications do not appear. As soon as you quit Karabiner-Elements, the notifications appear. I have not noticed any other interference with the settings in Logitech Options. If you want more info on this issue, let me know.

**Comment by cococolaaaaa** [comment]
hey man，Im a mature. My mouse is logi G402. The notification makes me crazy. If you see , can you help me? wish you healthy.
