### ISSUE TITLE
How to disable a key?

### ISSUE THREAD

**Issue by manchoz** [tekezo/Karabiner-Elements#145]
Hi,
I would like to emulate the macOS configuration option "No Action" for modifier keys (which Karabiner Elements seems to overwrite).

How can I assign a "No Action/Null" function to a key? Is there a way to disable a key completely?

Thanks in advance!

**Comment by TroySK** [comment]
I just found this after looking in the code at https://github.com/tekezo/Karabiner-Elements/blob/master/src/share/types.hpp. Use the code "out"

This is my json file.

`{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "backslash": "out"
            }
        }
    ]
}
`

**Comment by manchoz** [comment]
Thank you, @TroySK.

**Comment by bslatkin** [comment]
@TroySK's suggestion also worked for me to disable the capslock key entirely:

```
"simple_modifications": {
    "caps_lock": "out"
}
```

Thanks!

**Comment by huangzonghao** [comment]
Just a heads up for those who also searched here: the `out` option is not available in the GUI. You got to change the configuration file at `~/.config/karabiner/karabiner.json` manually.

**Comment by mhourahine** [comment]
@huangzonghao Actually in the GUI, the 'vk_none' option seems to do the same thing.  I used it to disable my insert key:

<img width="1004" alt="Fullscreen_2_3_20__2_25_PM" src="https://user-images.githubusercontent.com/469262/73683897-1bdea600-4691-11ea-9ee0-ba6751324578.png">

**Comment by yy12490** [comment]
Hello, my internal left arrow key is pressed repeatedly automatically, and i disabled it and changed the right command key to the left key. does it do any harm to the computer if i dont go fix the hardware that makes the left arrow key act wrongly? (but i dont have any idea on which part of the hardware is broken which leads to this)
thank you so much

**Comment by andkirby** [comment]
It's not clear where I should put this "simple_modifications". Could you please provide whole config JSON?
