### ISSUE TITLE
Interaction with Logitech Options software

### ISSUE THREAD

**Issue by haltlos** [tekezo/Karabiner-Elements#1450]
macOS version: macOS 10.13.5
Karabiner version: Karabiner-Elements 12.1.0
Your Mac hardware: Macmini6,1 (Late 2012 Mac mini)
Your keyboard hardware: Logitech K780

As mentioned in #1449, Karabiner-Elements interferes with Logitech Options. This is not only about the Caps Lock key, other features are also affected. So I have opened this as a new issue.

Logitech Options has a setting to use the F-keys as standard function keys:
![image](https://user-images.githubusercontent.com/4324234/41501864-9abb674e-71ac-11e8-9bc0-ba2cd7c48de4.png)

Karabiner-Elements also has this setting, and it overrides the Logitech Options setting. This means that when Karabiner-Elements is running, its settings take prevalence. Just noting.

**Comment by haltlos** [comment]
I have to revise what I wrote. The function to toggle the F keys works only sometimes. This is probably not a bug but a conflict between the two apps which don't recognize each others settings.

**Comment by haltlos** [comment]
This is really annoying. Please remove this feature from Karabiner.

**Comment by tekezo** [comment]
You can ignore specific device:
https://pqrs.org/osx/karabiner/document.html#configuration-devices

**Comment by haltlos** [comment]
That has nothing to do with this issue. I would like to use the Logitech K780 keyboard and modify its keys with Karabiner. If this issue is not of interest to you, I have nothing more to add.

**Comment by Yuzvin** [comment]
The same issue with Logitech K850. I can't use Fn key in combination with mouse (for example, Fn + move mouse to right, Fn + click horizontal scroll key) or keyboard keys (for example, "native" Logitech Options shortcut Fn + F1). This combinations are completely ignored. After closing Karabiner shortcuts above are working.
Is it possible to do something with this?

**Comment by jongyookim** [comment]
I have the same issue with Logitech K380.
I hope there would be a way to disable overriding the function key mapping in Karabiner.

**Comment by subhead** [comment]
same annoying problem here with my g413 keyboard.

**Comment by thinkORo** [comment]
+1 for problems with Logitech K380

**Comment by mayanksha** [comment]
I can confirm I'm facing the same issue with a Logitech K380.

**Comment by ClarkKryptonite** [comment]
me too

**Comment by lingium** [comment]
Logitech K580 meets the same promlem. I also hope there would be a way to disable overriding the function key mapping in Karabiner.

**Comment by achtur** [comment]
Logitech MX Mini, same story. Logi Options is willing to allow me to reassign different functionalities to the top row keys (two new keys for "Previous" and "Next", in my case, since there are no keys for that by default) but changes are ignored due to Karabiner. And I don't want to disable it for this keyboard because I am using Karabiner to remap other keys in this same keyboard… :/

**Comment by subhead** [comment]
well after almost 4 years we can assume the devs dont care about this issue.

**Comment by efekete** [comment]
I think I solved this issue by removing fn modifiers from `~/.config/karabiner/karabiner.json`

I am talking about 

```json
"fn_function_keys": [
                {
                    "from": {
                        "key_code": "f1"
                    },
                    "to": [
                        {
                            "consumer_key_code": "display_brightness_decrement"
                        }
                    ]
                },
                {
                    "from": {
                        "key_code": "f2"
                    },
                    "to": [
                        {
                            "consumer_key_code": "display_brightness_increment"
                        }
                    ]
                },
                {
                    "from": {
                        "key_code": "f3"
                    },
                    "to": [
                        {
                            "key_code": "mission_control"
                        }
                    ]
                },
                {
                    "from": {
                        "key_code": "f4"
                    },
                    "to": [
                        {
                            "key_code": "launchpad"
                        }
                    ]
                },
                {
                    "from": {
                        "key_code": "f5"
                    },
                    "to": [
                        {
                            "key_code": "illumination_decrement"
                        }
                    ]
                },
                {
                    "from": {
                        "key_code": "f6"
                    },
                    "to": [
                        {
                            "key_code": "illumination_increment"
                        }
                    ]
                },
                {
                    "from": {
                        "key_code": "f7"
                    },
                    "to": [
                        {
                            "consumer_key_code": "rewind"
                        }
                    ]
                },
                {
                    "from": {
                        "key_code": "f8"
                    },
                    "to": [
                        {
                            "consumer_key_code": "play_or_pause"
                        }
                    ]
                },
                {
                    "from": {
                        "key_code": "f9"
                    },
                    "to": [
                        {
                            "consumer_key_code": "fast_forward"
                        }
                    ]
                },
                {
                    "from": {
                        "key_code": "f10"
                    },
                    "to": [
                        {
                            "consumer_key_code": "mute"
                        }
                    ]
                },
                {
                    "from": {
                        "key_code": "f11"
                    },
                    "to": [
                        {
                            "consumer_key_code": "volume_decrement"
                        }
                    ]
                },
                {
                    "from": {
                        "key_code": "f12"
                    },
                    "to": [
                        {
                            "consumer_key_code": "volume_increment"
                        }
                    ]
                }
            ],
            ```

**Comment by kgrossjo** [comment]
Thank you @efekete !  This did the trick!  Perhaps it's worth documenting this?

**Comment by kgrossjo** [comment]
I have now submitted this PR to document it: https://github.com/pqrs-org/pqrs.org/pull/14

Thanks again @efekete

**Comment by julianespinel** [comment]
In addition to setting the `fn_function_keys` as an empty list as suggested [here](https://karabiner-elements.pqrs.org/docs/help/troubleshooting/logitech-logi-options-plus-compatibility/), I had to enable the toggle:
> Use all F1, F2, etc. keys as standard function keys

![screenshot](https://user-images.githubusercontent.com/1284879/195906534-a5395f11-24a0-44b8-a81d-e9111be5589a.png)

**Comment by grzegorzkiselev** [comment]
Hey, guys. I think I found the solution:

1. I did that trick with [fn_modifiers](https://github.com/pqrs-org/Karabiner-Elements/issues/1450#issuecomment-1013932206) set as empty lists in Karabiner config file. You can find it in the “left menu” / “misc” / “open config folder.” Open karabiner.json and erase all the lines between [ and ]. I don’t know if it was necessary.
2. After that, you must click “Copy the current configuration to the system default configuration” in the same menu.
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/61684506/214943558-96b26275-18b4-469b-89cd-49787d29cd17.png">

3. In my case, checkboxes “Use F as standard functions keys” are disabled everywhere: in the System Preferences, Logi Options and Karabiner.

Karabiner mods and F row with Crown (I write it using Craft keyboard) are working so far. I still keep testing it.

UPD: After log-in—log-out, this trick stopped working. After I had gone through these steps one more time, it worked again. Karabiner set up fn lists again.
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/61684506/214943282-53de2fb8-38ba-4cf2-84ce-376ff3c36eed.png">

Finally, after another log-in, I just clicked “Copy the current configuration to the system default configuration,” and now it works again. It even doesn’t require restarting Karabiner and erasing fn lists.

Maybe you folks can automate this trick with Hammerspoon.

**Comment by LiberiFatali** [comment]
Two steps:
1. Exit Karabiner (Elements)
2. Set fn_function_keys as empty list:  `"fn_function_keys: []`

Run Karabiner again

**Comment by stepresearch** [comment]
I have tried all the options in this list and it doesn't seem to work with my Logi+ keyboard.  If we can't fix this I will probably need to stop using Karabiner :/

**Comment by dpeper** [comment]
None of the various workarounds worked for me either. However I just switched from Logitech Options to Logi Options+ and now everything works great. No workarounds needed.

**Comment by akavi1** [comment]
This has been working for me:
1) quit Karabiner
2) open Logi Options and check "Use all F1, F2, etc. keys as standard function keys"
3) quit Logi Options
4) open Karabiner
5) set your keys to whatever you want in Karabiner
6) stop messing with it

Unfortunately, I do need to repeat steps 1-4 every time I disconnect the keyboard

**Comment by grzegorzkiselev** [comment]
> I just switched from Logitech Options to Logi Options+ and now everything works great. No workarounds needed.

This means that you can no longer reconfigure the keys on the Craft keyboard, as Logi+ does not support it. For the same reason there is no conflict with Karabiner.
