### ISSUE TITLE
12.1.0 and 12.1.2 - Media Keys do not work, mapping does not work

### ISSUE THREAD

**Issue by methodbox** [tekezo/Karabiner-Elements#1452]
It seems like Karabiner Elements isn't really working at all in macOS 10.13.5.

It doesn't do anything after the install; the media keys on my WASD Code keyboard no longer work. Manually mapping them doesn't work, either.

I went back to a couple of previous versions and still not working, so maybe this is something with the latest High Sierra update?

**Comment by runar-rkmedia** [comment]
I'm also seeing some here, same version of macOS, tested on 12.1.0.

**Comment by ajporcino** [comment]
I've got the same problem, mac0S 10.13.5, and 12.1.0. Was working before latest macOS update (I updated 2 days ago).
