### ISSUE TITLE
Wrong button combo - Microsoft Sculpt mouse

### ISSUE THREAD

**Issue by n8udd** [tekezo/Karabiner-Elements#1455]
I've had a fairly comprehensive read over some of the issues that relate on here.

I've managed to get it so that the blue 'Windows' button launches *launchpad* ✔️

I've created a custom Complex Modification, that I _thought_ should behave like the back button in the browser ie `CMD+LEFT` but instead it's behaving like `CTRL+LEFT`.

The following is in my mouse.json file, which I've saved in `~config/karabiner/assets/complex_modifications/mouse.json`

```
{
    "title": "Custom Rules",
    "rules": [
        {
            "description": "Mouse button4 → Back",
            "manipulators": [
                {
                    "description": "Mouse back",
                    "from": {
                        "pointing_button": "button4"
                    },
                    "to": [
                        {
                            "key_code": "left_arrow",
                            "modifiers": [
                                "left_command"
                            ]
                        }
                    ],
                    "type": "basic"
                }
            ]
        }
    ]
}
```

Is anyone able to help me correct the manipulator so that it behaves as intended?

**Comment by danovia** [comment]
**How to configure your Microsoft Sculp mouse buttons in Mac?**
Pay attention that Karabiner-Elements configures the mouse as two input devices - 
1. The keyboard input device one is the blue button, that is represented as a "right command button".  I chose to configure it as "mission control" using Simple modifications -> Target device -> Microsoft 2.4Ghz Transceiver v9.0 [hit the first one that represents the keyboard input device].
Now pick the blue button (right_gui) and map it to the desired button (for example - mission control).
2. Configure the back button - https://pqrs.org/osx/karabiner/complex_modifications/#mouse_button
See the "Change button4,5 to back,forward (rev 1)" rule. [thanks @apm1467]

All set and ready to go! enjoy.
