### ISSUE TITLE
Karabiner Elements can't target only Chrome Remote Desktop

### ISSUE THREAD

**Issue by mvd7793** [tekezo/Karabiner-Elements#1464]
Hello! A while ago, I'd configured Karabiner to remap my Command and Control keys for Chrome Remote Desktop, which I use to remote into a Linux installation. 

With the move to Karabiner Elements, complex modifications can only target by Bundle ID and File Path. Unfortunately, since Chrome Remote Desktop is a Chrome app, it has the same bundle ID and file path as Chrome itself. This means I can't remap the keys just for remote desktop -- I have to remap them for all of Chrome or not at all.

Any tips for a workaround would be much appreciated! I _think_ targeting by window name would solve the problem, but I'm not certain. Let me know if there's another way I can help find a fix.

**Comment by ToastyKen** [comment]
Yeah, this is the rule I had in legacy Karabiner:
<windowname_only>Chrome_Remote_Desktop</windowname_only>

So window name support should be sufficient. I don't think that's there right now?

**Comment by ToastyKen** [comment]
Filed more general window name targeting request as issue #1518

**Comment by clemsam** [comment]
Here's a possibility how to do it, but more of an easily adaptable "example" (I suppose you view this with "Chrome"):

Open applications/utilities/scriptEditor, Cmd-N, paste this code into its window and press "right" (start script) button:

    tell application "System Events" to tell process "Chrome"
	  set frontmost to true
	  if name of front window of application "Chrome" is not "Preferences" then beep 3
	  keystroke "o" using command down
    end tell
You could "pack" such code into a "shell_script": "osascript …", use whatever app name & whatever "name of front window" and have AS do whatever shortcut you want …  

(If you "conditions" this to "Jump Desktop…" you needn't even "set frontmost".)

**Comment by 15characterlimi** [comment]
Workaround: You can use Chrome Remote Desktop's keymapping setting instead:

https://stackoverflow.com/questions/13518963/chrome-remote-desktop-keyboard-shortcut-needed

I personally have set my Karabiner-Elements to swap Ctrl vs. Command when using my external keyboard on the MacBook, and then configure Chrome Remote Desktop to map ControlLeft -> MetaLeft, and vice-versa. Works like a charm!
