### ISSUE TITLE
When Karabiner-Elements is running, Cmd-Tab doesn't work with Contexts

### ISSUE THREAD

**Issue by pbzdyl** [tekezo/Karabiner-Elements#147]
I use https://contexts.co/ to switch between windows. When I press Cmd-Tab I get Contexts window switcher. However, with Karabiner-Elements running it no longer works and standard Mac OS app switcher appears.

It was working with regular Karabiner version.

**Comment by fhendrikx** [comment]
With the latest version, I can now use cmd-tab and option-tab to bring up the switcher.

**Comment by pbzdyl** [comment]
I can confirm that with Karabiner-Elements v. 0.90.47 the issue is fixed.
