### ISSUE TITLE
Can't edit or make my own complex modifiers, and i need to replace ctrl+left click to just left click

### ISSUE THREAD

**Issue by DarkArachnid** [tekezo/Karabiner-Elements#1477]
Does anybody have a file for this action or can anyone make one? Karabiner has no options to create your own complex modifiers.

**Comment by FerretDave** [comment]
complex modifications have to be coded in a JSON file - I suggest you add one from an internet source (via "add rule" on complex modifications there is an option to 'import more rules from the internet') and see if there's one already there, and then check the docs as to how to code it.

**Comment by AtomicCoding** [comment]
@DarkArachnid I've opened a pull request to the complex modifications website that disables `Ctrl + Left Click`, it's [here](https://github.com/pqrs-org/KE-complex_modifications/pull/409).

**Comment by llamerr** [comment]
Same problem here. I think this complex modification I want to import https://superuser.com/questions/703162/shift-insert-to-paste-in-mac-os-x now the question is - where do I paste that JSON?

**Comment by AtomicCoding** [comment]
@llamerr Save the JSON under any file name to `~/.config/karabiner/assets/complex_modifications/`, when you go to add a complex modification it should show up.
