### ISSUE TITLE
Remapping Underscore (ろ) key on Japanese keyboards

### ISSUE THREAD

**Issue by soph-iest** [tekezo/Karabiner-Elements#1479]
I have it set up correctly to my keyboard, and have remapped the keys to switch between English and Kana, etc. However, it doesn't currently seem possible to rebind the underscore key (bottom right, between forward slash and right Shift). Typing it in Simple Modifications simply defaults to the 0 key, and manually editing karabiner.json to remap from '_' doesn't work either.

**Comment by jnakanojp** [comment]
"ろ" key is listed as "international1". With my Macbook Pro's internal keyboard and setting simple modification that changes international1 to a, I confirmed that typing "ろ" is acting as typing "a".

**Comment by spring-haru** [comment]
The following code works for me.

```
    {
      "description": "「ろ」(Underscore) -> Backslash",
      "manipulators": [
        {
          "type": "basic",
          "from": {
					"key_code": "international1",
					"modifiers": { "mandatory": [  ] }
				},
          "to": [
					{
					"key_code": "international3",
					"modifiers": [ "left_option" ] 
					}
              ]
        }
      ]
    },
 
```
