### ISSUE TITLE
Logging in with ARD/Screensharing to a Mac with Karabiner configured screws up the config

### ISSUE THREAD

**Issue by jby** [tekezo/Karabiner-Elements#1486]
I have a user (@jlubcke) who's using Karabiner Elements on his MacBookPro, and if I as sysadmin logs in remotely to his computer, even on a separate Virtual Desktop (i.e. not sharing his screen), his config is completely screwed up and he has to reboot to get back. Is this a known issue? If so, is there a fix?

**Comment by jnakanojp** [comment]
I have a same issue.
When I log in remotely to a separate virtual desktop of my co-worker's Mac when he use it on real desktop environment, his Karabiner-Elements seems to stop working.
However, When I log in remotely first, then he logs in to real desktop, it seems to work.
I suppose this trouble is related to a user who logs in the latest.
