### ISSUE TITLE
Eject button blocked and unseen

### ISSUE THREAD

**Issue by wfaulk** [tekezo/Karabiner-Elements#1488]
I use the Ctrl-Shift-Eject and Opt-Cmd-Eject shortcuts (as documented [here](https://support.apple.com/en-us/ht201236)) to sleep my display and Mac, respectively. With Karabiner-Elements running, these shortcuts do not work unless I tell KE not to "Modify events from this device" under the devices tab in Preferences.

In addition, when I run EventViewer, regardless of whether the device is selected, or even if KE is running, it fails to register eject keypresses.

The keyboard in question is an Apple A1243 "Apple Keyboard with Numeric Keypad". The computer is a MacBookPro14,3 (15-inch, 2017) running MacOS 10.13.5.

I am running KE v.12.1.4 after updating to the latest beta from the Preferences. Before that, I was running whatever the latest non-beta version was when I downloaded it on or about 9 July 2018. Both versions had the problem.

There are a number of issues very similar to this, but they are all closed. #89 and #96 are prominent ones.

**Comment by stevenaanen** [comment]
Have the same issue here. Eject is not registered in the EventViewer at all with an external Apple Keyboard.
