### ISSUE TITLE
Modifications not respected on macOS 10.13.6

### ISSUE THREAD

**Issue by PSalant726** [tekezo/Karabiner-Elements#1489]
KE: 12.1.0
macOS: 10.13.6

I recently updated macOS to 10.13.6. My configuration settings are still present, but the OS does not recognize or utilize them. My re-mapped external devices are now back to factory default configuration(s).

**Comment by PSalant726** [comment]
This issue seems to be resolved by updating to 12.1.4b

**Comment by jbiel** [comment]
Confirmed that 12.1.4 fixes issues with the latest High Sierra 10.13.6.

In case anyone else has issues finding the latest version ("Check for updates" doesn't download it and it doesn't appear to be tagged or available via official download page) it's here: https://github.com/tekezo/pqrs.org/tree/master/webroot/osx/karabiner/files
