### ISSUE TITLE
`keypad_enter` to `return` not working

### ISSUE THREAD

**Issue by 0x3333** [tekezo/Karabiner-Elements#149]
What I want to accomplish is, when the `enter` in keypad is pressed, an `return` is fired.

So I created the following mapping(`~/.karabiner.d/configuration/karabiner.json`):

```json
{
    "profiles": [
        {
            "name": "0x3333's Profile",
            "selected": true,
            "simple_modifications": {
                "keypad_enter": "return"
            }
        }
    ]
}
```
This mapping produces nothing, is the same as no key pressed.

When I change `return` to `return_or_enter` it works as expected.

Is this a bug or a desired feature?

**Comment by tekezo** [comment]
You should use `return_or_enter`.
