### ISSUE TITLE
Why are display_brightness_increment and display_brightness_decrement not available from keys in Simple Modifications/

### ISSUE THREAD

**Issue by studgeek** [tekezo/Karabiner-Elements#1490]
Why are display_brightness_increment and display_brightness_decrement not available a From keys in Simple Modifications? They are shown on the To side, but not the From side.

My use case is I have an external Anker bluetooth keyboard that by default provide media actions for F keys. I want to default it to being a F key. So map display_brightness_decrement to F3...

Thanks!

**Comment by mindfulsource** [comment]
I am trying to disable the touch bar's four display and keyboard brightness keys (e.g. in lock screen) and also cannot see them listed under media keys in the 'from' list.

Is there an answer to this? Are they supposed to be included?
