### ISSUE TITLE
Not working on latest mac os

### ISSUE THREAD

**Issue by lazywhite** [tekezo/Karabiner-Elements#1491]
mac: 10.13.6
k-element: 12.1.0

today I update my mac os, then k-element stop working , I fount that  in event-viewer  it distinguish command key as  "left_gui", "right_gui"

**Comment by infohou** [comment]
Yes,  I just got a K70 LUX and Karabiner-Elements works in the latest update of 10.12.6.  CKB does not find the keyboard.

Anybody know a way to set the backlighting without booting into Windows?

Thanks,
Robert

**Comment by lazywhite** [comment]
reinstall karabiner solved this problem

**Comment by samm-git** [comment]
Same for me, had to reinstall app after osx upgrade

**Comment by better365** [comment]
Not sure why, but reinstallation does solve the problem.
