### ISSUE TITLE
Remote desktop modifier keys broken

### ISSUE THREAD

**Issue by sonnius** [tekezo/Karabiner-Elements#15]
When using Microsoft remote Desktop application "Version 8.0.34 (Build 27181)" there is a problem with the modifier keys.

No modifier keys are registered within the application (Shift, Control, Windows key etc), this is true for my external and builtin keyboard. Everything works fine outside the RDP application.

My simple config:

~/.karabiner.d/configuration ❯ cat karabiner.json
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "caps_lock": "left_control",
                "left_option": "left_command",
                "left_command": "left_option"
            }
        }
    ]
}

**Comment by tekezo** [comment]
Thank you for feedback!

I fixed this issue at Karabiner-Elements v0.90.22.
Please upgrade to the latest version from "Misc > Check for updates" or 
https://pqrs.org/latest/karabiner-elements-latest.dmg

**Comment by sonnius** [comment]
Works now!

Thanks
