### ISSUE TITLE
Unload karabiner_grabber when Quitting Karabiner

### ISSUE THREAD

**Issue by iandol** [tekezo/Karabiner-Elements#1501]
Hi, when we quit Karabiner, `karabiner_grabber` remains loaded. This breaks the use of keyboard logging in MATLAB, so I have to both quit Karabiner, then `sudo launchctl unload` the `karabiner_grabber.plist`. 

Would it be possible if Karabiner could load/unload karabiner_grabber when starting and stopping?

Thanks for such an amazing utility.

**Comment by iandol** [comment]
It seems there is a new daemon `karabiner_observer` and this also interferes with MATLAB lowlevel keyboard access too, so I need to unload both manually, here are aliased commands to start and stop karabiner for the moment:

```shell
alias karabinerLoad='launchctl load /Library/LaunchAgents/org.pqrs.karabiner.karabiner_console_user_server.plist; \
sudo launchctl load /Library/LaunchDaemons/org.pqrs.karabiner.karabiner_grabber.plist; \
sudo launchctl load /Library/LaunchDaemons/org.pqrs.karabiner.karabiner_observer.plist;'
alias karabinerUnload='launchctl unload /Library/LaunchAgents/org.pqrs.karabiner.karabiner_console_user_server.plist; \
sudo launchctl unload /Library/LaunchDaemons/org.pqrs.karabiner.karabiner_grabber.plist; \
sudo launchctl unload /Library/LaunchDaemons/org.pqrs.karabiner.karabiner_observer.plist; \
sudo killall karabiner_grabber; \
sudo killall karabiner_console_user_server; \
sudo killall Karabiner-Menu; \
sudo killall Karabiner-Elements'
```

**Comment by iandol** [comment]
There is still a significant incompatibility between Karabiner and MATLAB toolboxes used for neuroscience and psychology research...

**Comment by iandol** [comment]
This is getting worse for me, now I need to also unload the kext — but often the kext fails to unload even if karabiner and all its daemons and services are fully quit...

```
alias karabinerUnload='launchctl unload -F /Library/LaunchAgents/org.pqrs.karabiner.karabiner_console_user_server.plist; \
	sudo launchctl unload -F /Library/LaunchDaemons/org.pqrs.karabiner.karabiner_grabber.plist; \
	sudo launchctl unload -F /Library/LaunchDaemons/org.pqrs.karabiner.karabiner_observer.plist; \
	sudo killall karabiner_observer; \
	sudo killall karabiner_grabber; \
	sudo killall karabiner_console_user_server; \
	sudo killall Karabiner-Menu; \
	sudo killall Karabiner-Elements; \
	sudo kextunload /Library/Application\ Support/org.pqrs/Karabiner-VirtualHIDDevice/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.v060800.kext;'
```

**Comment by iandol** [comment]
This is still a problem...

**Comment by cropse** [comment]
Well.........same issue here.

**Comment by iandol** [comment]
Hi, in recent karabiner-elements, deselecting the keyboard in the preferences:

https://pqrs.org/osx/karabiner/document.html#configuration-devices

...allows the HID keyboard driver to work without issue (MATLAB 2018b), so I think this is the best solution as we just create a profile with keyboard disabled and toggle profile as needed (no need to load/unload kexts manually).

**Comment by sidneys** [comment]
> Hi, in recent karabiner-elements, deselecting the keyboard in the preferences:
> 
> https://pqrs.org/osx/karabiner/document.html#configuration-devices
> 
> ...allows the HID keyboard driver to work without issue (MATLAB 2018b), so I think this is the best solution as we just create a profile with keyboard disabled and toggle profile as needed (no need to load/unload kexts manually).

Thank you for your work. I also encountered a similar issue, as [setlds](https://github.com/damieng/setledsmac) does not work while Karabiners driver is active. Using your proposed profile-based approach (switching to an empty profile via `karabiner_cli`), everything works flawlessly.

Cheers!
