### ISSUE TITLE
2 key assignments stopped working after macos update 10.13.6

### ISSUE THREAD

**Issue by christvee** [tekezo/Karabiner-Elements#1504]
macOS version: 10.13.6 (17G65)
Karabiner version: Karabiner-Elements 12.1.0
Your Mac hardware: MacBook Pro 15-inch, 2017, Touch Bar
Your keyboard hardware: Apple internal keyboard

After Macos update 10.13.6 karabiner-elements' 2 key assignments stopped working completely.
These were (and still are but dont work)
  Map   backslash(\)  To  delete_forward
  Map   fn            To  left_option
Any idea what to do please?
Thank you - appreciate it!

**Comment by kubudi** [comment]
+1

**Comment by kubudi** [comment]
P.S. It seems to be working fine on beta(12.1.5)

**Comment by christvee** [comment]
thank you its resolved in 12.1.5 !

**Comment by Aberrational** [comment]
@brabalan There is no beta distribution. You just compile master branch yourself. See readme for details.

**Comment by kubudi** [comment]
@brabalan open the app, go to misc, on the right you should be able to see a button named 'check for beta updates'

**Comment by brabalan** [comment]
@kubudi Great tip, thanks! And I confirm it fixed my keys.

**Comment by Aberrational** [comment]
@kubudi hehe thanks for the info, I didn't know about that feature.

**Comment by kubudi** [comment]
no worries, I found it by chance as well :)

**Comment by Spyruf** [comment]
Still having issues on 10.13.6

Tried both beta and stable, but I'm getting these errors in the log
`
[2018-07-27 20:30:12.543] [warning] [grabber] grabber_alert: system_policy_prevents_loading_kext
[2018-07-27 20:30:13.380] [info] [console_user_server] input_source_manager initialize
[2018-07-27 20:30:13.380] [info] [console_user_server] input_source_manager terminate
[2018-07-27 20:30:13.380] [warning] [console_user_server] bind: Permission denied
[2018-07-27 20:30:15.117] [warning] [observer] grabber socket is not found
`

**Comment by madorb** [comment]
I'm getting the same error as @Spyruf.
