### ISSUE TITLE
combo of (to_after_keyup + to_if_alone) : broken since 12.0

### ISSUE THREAD

**Issue by cajhin** [tekezo/Karabiner-Elements#1506]
I spent an hour looking around and fixing my old script, but it won't work.
It worked in 11.6 (flawed timeout but otherwise ok), broken in 12.0 ... 12.1.5beta.

The variable 'cl_down' should mirror CapsLock key state (0/1), with -1 for "tapped / if_alone".
Looks like "tapped -1" is alway overridden by to_after_keyup -> 0
Is it possible to fix the script?

to_if_alone is never active, the var is never -1:

            "complex_modifications": {
                "parameters": {
                    "basic.simultaneous_threshold_milliseconds": 50,
                    "basic.to_delayed_action_delay_milliseconds": 500,
                    "basic.to_if_alone_timeout_milliseconds": 1000,
                    "basic.to_if_held_down_threshold_milliseconds": 500
                },
                "rules": [
                    {
                        "description": "jjj cursor mapping",
                        "manipulators": [
                            {
                                "from": {
                                    "key_code": "caps_lock",
                                    "modifiers": {
                                        "optional": [
                                            "any"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "set_variable": {
                                            "name": "cl_down",
                                            "value": 1
                                        }
                                    }
                                ],
                                "to_after_key_up": [
                                    {
                                        "set_variable": {
                                            "name": "cl_down",
                                            "value": 0
                                        }
                                    }
                                ],
                                "to_if_alone": [
                                    {
                                        "set_variable": {
                                            "name": "cl_down",
                                            "value": -1
                                        },
                                        "hold_down_milliseconds": 100
                                    }
                                ],
                                "type": "basic"
                            },
[...]

(MacOS 10.13.5 on a 2011 MBA)

**Comment by Neilord** [comment]
Still not fixed!
