### ISSUE TITLE
 karabiner-elements does not work with MacOS High Sierra 10.13.6.

### ISSUE THREAD

**Issue by taytaytaytaytay** [tekezo/Karabiner-Elements#1508]
Karabiner Elements 12.1.5 beta
MacOS High Sierra 10.13.6
Keyboard: Real force compact

If I disable SIP in recovery mode, Karabiner Elements will work. However, when SIP is enabled, it will not work at all.

I also tried a lot of Old releases. But none of the results were the same.

Is there a good way to do it?

**Comment by cyc115** [comment]
see https://github.com/tekezo/Karabiner-Elements/issues/1504

**Comment by taytaytaytaytay** [comment]
"Karabiner Elements 12.1.5 beta" does not work with MacOS High Sierra 10.13.6.
I also tried a lot of Old releases. But none of the results were the same.
Is there a good way to do it?


Karabiner Elements 12.1.5 beta
MacOS High Sierra 10.13.6
Keyboard : Real force compact


Log---
[2018-07-28 18:04:19.502] [warning] [grabber] virtual_hid_device_client is not connected yet. Please wait for a while.
[2018-07-28 18:04:22.493] [info] [grabber] Load karabiner.json...
[2018-07-28 18:04:22.493] [info] [console_user_server] Load karabiner.json...
[2018-07-28 18:04:22.494] [info] [grabber] core_configuration is updated.
[2018-07-28 18:04:22.494] [info] [console_user_server] core_configuration is updated.
[2018-07-28 18:04:22.495] [info] [grabber] USB Receiver (device_id:2) is ignored.
[2018-07-28 18:04:22.495] [info] [grabber] USB Receiver (device_id:3) is ignored.

**Comment by ehellman** [comment]
I've got the exact same issue in 12.1.5 but using the internal keyboard.

```
[2018-07-29 17:12:10.982] [info] [grabber] Load karabiner.json...
[2018-07-29 17:12:10.982] [info] [console_user_server] Load karabiner.json...
[2018-07-29 17:12:10.983] [info] [grabber] core_configuration is updated.
[2018-07-29 17:12:10.983] [info] [console_user_server] core_configuration is updated.
[2018-07-29 17:12:10.984] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:3) is ignored.
[2018-07-29 17:12:10.984] [info] [grabber] (vendor_id:0x5ac, product_id:0x8600) (device_id:2) is ignored.
```

Mapping `non_us_backslash` to `grave_accent_and_tilde`

**Comment by geoffadams** [comment]
High Sierra 10.13.6 with Karabiner-Elements 12.1.5 causes my machine to hang at the MacOS loading screen, with the loading bar reaching 100% eventually if left long enough. There isn't any info in the `system.log` that I could find. I've left the machine in that state for upwards of an hour, and it still doesn't finish booting.

If I select "verbose mode" (Cmd+V after the loading chime on power-on) then the system boots as normal. This is strange as verbose mode loads kernel extensions as normal - it is not safe mode, and not single-user mode.

I've clearly isolated the issue on my system to the presence Karabiner-Elements. When it is installed, the system won't boot without dropping into verbose mode. When I uninstall it, the system boots as normal.

Whether this is something to do with the `org.pqrs.driver.Karabiner.VirtualHIDDevice.v060800` kernel extension or not is a little beyond my understanding, though.

**Comment by ZuBB** [comment]
thanks God and @tekezo beta version fixes this bug for me

🎆 🙇

**Comment by 1MikeMakuch** [comment]
How do we get the beta?

**Comment by jclarktennis** [comment]
@1MikeMakuch in the "Misc" tab there is a button called "Check for beta updates"

**Comment by xiaket** [comment]
link for the latest beta:

https://pqrs.org/osx/karabiner/files/Karabiner-Elements-12.1.5.dmg

**Comment by xiaket** [comment]
BTW, installing latest beta does not fix this issue for me.   :(

**Comment by madorb** [comment]
Agree with @xiaket 12.1.5 does not resolve this for me

**Comment by madorb** [comment]
From another thread: 

> I was able to fix this by going to System Preferences > Security & Privacy > Click "Allow" next to "Software from Fumihiko Takayama has been blocked"

This solved the problem for me and the beta is now working on 10.13.6

**Comment by jkclark** [comment]
@xiaket I ran `spctl kext-consent <TEAM IDENTIFIER>` and got a usage help page. I don't think that command did anything for me. Can you elaborate on it?

**Comment by Geospace** [comment]
Uninstall via KE then reboot and finally clean install of the latest beta (12.1.5) worked for me without any further manipulations.

I'm running a 2016 MBP on macOS 10.13.6.

**Comment by xiaket** [comment]
@jkclark Sorry, in my case, there's a company policy that prevents me from using a 3rd party kext so I had to enter the recovery mode and manually enable the extension, if you are not in this situation, I think you'll be able to find a prompt fix this as @madorb suggested.

And, yes, the command should be `spctl kext-consent add G43BCU2T37`. I'm terribly sorry for the inconvenience that I had caused you. I was replying at home and I haven't checked everything.   :(

**Comment by ohjoycelau** [comment]
Not working over here and tried all the solutions I can find.
[1372](https://github.com/tekezo/Karabiner-Elements/issues/1372), [1508](https://github.com/tekezo/Karabiner-Elements/issues/1508), [1365](https://github.com/tekezo/Karabiner-Elements/issues/1365), [Uninstall Guide](https://pqrs.org/osx/karabiner/help.html#installed-files)

**Backstory**
Might be affected by the fact that I recently got a new computer and set it up using the Migration Assistant. Should have transferred 1:1 but I know sometimes permissions may get lost. Had downloaded but never successfully used Karabiner Elements on previous machine.

**Current Specs**
High Sierra 10.13.4
Karabiner Elements 12.1.5 (updated to beta after reading some previous suggestions)

**Possible Indicators**
👉Among other warnings at launch, `[warning] [observer] local_datagram_client error: Connection refused` and `[warning] [grabber] virtual_hid_device_client is not connected yet.` is consistently reappearing. 
👉Uninstalling, removing all related hidden files, and re-installing, `Security and Privacy > General` does not ask for any permissions; Karabiner is able to launch anyway. It went through that step the very first time I installed (on previous machine).
👉`Change Keyboard Type` is not present in `System Preferences > Keyboard`.
👉Keyboard type is read as `40` from this [issue](https://github.com/tekezo/Karabiner-Elements/issues/1365).
👉In `System Preferences > Keyboard > Modifier Keys`, I have tried leaving as default as well as mapping to `No Action` with no change.

**Comment by kannanmavila** [comment]
I had the same issue and turned out I had to go to `identify the keyboard` in `Preferences > Keyboard` and run the wizard. Fixed the issue for me.

The option doesn't appear on `Preferences > Keyboard` anymore hence no screenshot. Sorry.

**Comment by DKroot** [comment]
I had the same issue with a clean install of v12.9.0 on High Sierra. None of the solutions here worked, but I was able to fix the issue by following the recipe from https://github.com/pqrs-org/Karabiner-Elements/issues/2079 -> https://discussions.apple.com/thread/250038463:

1. (Recovery) $ csrutil disable
2. (Normal boot) $ sudo chflags -R restricted /Library/StagedExtensions
3. (Recovery) $ csrutil enable

**Comment by nerdfiles** [comment]
"(recovery) `spctl kext-consent add G43BCU2T37`" does not work for me on 10.15.6 (19G2021) Catalina.

**Comment by ptram** [comment]
The only solution I could find was to reboot from another drive, and then copy the kext from the /Library/Staged Extensions folder of a Time Machine backup.

I had to reboot quickly in High Sierra, because the other drive was with Catalina, and tended to remove the staged kexts.
