### ISSUE TITLE
How to achieve Enter: NOT (Enter OR Return)

### ISSUE THREAD

**Issue by sickdoc** [tekezo/Karabiner-Elements#1510]
Hello, some software still interpretes the keys Enter and Return differently, which is most useful in some environments. For example, the software Mathematica (a programming environment) takes Enter to trigger some code execution. In spreadsheet applications Enter can be used to confirm an input without leaving the active field, while Return remains set to confirm an input AND move to the field below the active field (probably somewhere else, if it is MS Excel). To emulate Enter on Laptop keyboards, Mathematica uses Shift-Return. With KeyRemap4MacBook I just assigned Enter to the right Command key, as I still have no better use for a right Command key, anyhow. In Karabiner I cant find an option to map any key to Enter. Is this feature lost or hidden? Thank you and with kind regards.
(Karabiner Elements 12.1.0 on MacBook Pro 5,4 running Mac OS X 10.13.6)

**Comment by limeb** [comment]
@sickdoc you can do this internally in mathematica with out using karabiner elements.  

https://mathematica.stackexchange.com/questions/60684/switch-actions-of-shiftenter-and-enter-in-notebook-interface

**Comment by sickdoc** [comment]
Thank you for your kind response! Yes, Mathematica supports a wide range of customisation to the user interface. However, I would much prefer to use the more global kind of control Karabiner provides. I am just missing the option to set the Command_R to Enter, instead of Command_R to Return_or_Enter (which would not help in my case). Has Apple changed the key assignment in a way that does not differentiate between the Return key and the Enter key?

**Comment by Bibi** [comment]
I have the same problem: the two keys (enter and return) should be separate. Mathematica, TextMate, etc., use both keys!

Please incorporate the modification in the next build, thanks!

**Comment by sickdoc** [comment]
The same here. Please re-implement (enter) and (return) as separate keys. With best regards and thanks!

**Comment by hawkiboy** [comment]
Me too and three! Why are you marking this as stale? This issue requires a response.

**Comment by hawkiboy** [comment]
Oh, dahhhhh....                             "key_code": "keypad_enter"

**Comment by sickdoc** [comment]
Great, the issue is solved :-)
Thank you very much!
