### ISSUE TITLE
Remapping keys doesn't do anything (every action in KE has no effect)

### ISSUE THREAD

**Issue by jkclark** [tekezo/Karabiner-Elements#1511]
Hi,

First, thank you for developing and maintaining this app. I really appreciate it.

I recently got a new computer, a 2017 Macbook Pro running High Sierra 10.13.4. I am running Karabiner-Elements v. 12.1.5. No matter what I do in Karabiner-Elements, nothing happens. I have tried simply remapping 'a' to 'z', but nothing happens. My keyboard is a WASD V2 87-Key Custom Mechanical Keyboard. With my previous computer, it seemed that Karabiner-Elements worked (I was running Sierra, not sure which version exactly). Here are some screenshots of my settings:
<img width="999" alt="screen shot 2018-08-01 at 3 56 15 pm" src="https://user-images.githubusercontent.com/7968071/43545270-752a626c-95a3-11e8-8a9d-ae65c31a1f48.png">

<img width="987" alt="screen shot 2018-08-01 at 3 53 09 pm" src="https://user-images.githubusercontent.com/7968071/43545141-0d38548e-95a3-11e8-988f-9b844a5ad9fc.png">

Thank you for your help. I am at my wit's end and not sure what else I could do to try to make this work.

**Comment by Deralict** [comment]
Same here. it used to work, but at some point it stopped.
