### ISSUE TITLE
Changed from El Capitan to High Sierra and Karabiner 10 to 12

### ISSUE THREAD

**Issue by 1MikeMakuch** [tekezo/Karabiner-Elements#1512]
Ok I've tried programming my KB v10 stuff to KB v12 and I'm having no luck at all. My v10 code is below, can someone tell me how to do this in V10? Please!

<pre>
&lt;?xml version="1.0"?>gt;
&lt;root>gt;
    &lt;item>gt;
        &lt;name>gt;AAA C-, to M-b&lt;/name>gt;
        &lt;identifier>gt;private.controlCommaToMetaB&lt;/identifier>gt;
        &lt;autogen>gt;__KeyToKey__ KeyCode::COMMA, VK_CONTROL, KeyCode::B, ModifierFlag::OPTION_L&lt;/autogen>gt;
    &lt;/item>gt;
    &lt;item>gt;
        &lt;name>gt;AAA C-. to M-f&lt;/name>gt;
        &lt;identifier>gt;private.controlPeriodToMetaA&lt;/identifier>gt;
        &lt;autogen>gt;__KeyToKey__ KeyCode::DOT, VK_CONTROL, KeyCode::F, ModifierFlag::OPTION_L&lt;/autogen>gt;
    &lt;/item>gt;
&lt;/root>gt;
</pre>

I need Control+, to do escape+b

Or to option+b, what ever I can get working.

Here's what I have that doesn't work:

<pre>
    {
      "description": "Control+, to Option-b",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": ",",
            "modifiers": {
              "mandatory": [
                "left_control"
              ],
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "b",
              "modifiers": "left_option"
            }
          ]
        }
      ]
    }
</pre>

And I'm putting that at the bottom of ~/.config/karabiner/assets/complex_modifications/1533245163.json

Thanks for any clues.
Mike

**Comment by Jimmy34742** [comment]
Does writing
`"key_code": "comma"`
instead of
`"key_code": ","`
make a difference?
