### ISSUE TITLE
Feature Request: windowname_only support (window name targeting)

### ISSUE THREAD

**Issue by ToastyKen** [tekezo/Karabiner-Elements#1518]
Feature request: Support window-specific targeting in Karbiner Elements.

Old Karabiner had a tag called windowname_only, which was needed to target Chrome Remote Desktop without targeting all Chrome windows, e.g.:
`<windowname_only>Chrome_Remote_Desktop</windowname_only>`

(That specific problem is filed as issue #1464, but I'm filing this as the more general request.)

**Comment by clemsam** [comment]
Hi, Pablo,
open applications/utilities/scriptEditor, Cmd-N, paste this code into its window and press "right" (start script) button:

    tell application "System Events" to tell process "Safari"
	  set frontmost to true
	  if name of front window of application "Safari" is not "Preferences" then beep 3
	  keystroke "o" using command down
    end tell
You could "pack" such code into a "shell_script": "osascript …", use whatever app name & whatever "name of front window" and have AS do whatever shortcut you want …  

(If you "conditions" this to "Jump Desktop…" you needn't even "set frontmost".)

**Comment by clemsam** [comment]
### There are ways to swap key codes for "exclusive" windows with Karabiner Elements (using AppleScript) but they have their respective drawbacks.    

**A)** If you use an osascript-shell_command in your karabiner.json, it is very easy, reliable and fast to _swap individual keys_, e.g. "Cmd-C" to "Ctrl-C" or vice versa. Like this:

    "from": {"key_code": "o", "modifiers": {
                                  "mandatory": ["left_command"]} },
    "to": [{"shell_command": "osascript -e 'if name of window 1 ¬
    of application \"Chrome\" is \"Chrome_Remote_Desktop\" then ¬
    tell application \"System Events\" to keystroke \"o\" using ¬
    {control down}'"} ], "type": "basic"

Main drawback imho being that the osascript will _not take nor return variables._    
… which means: do this above code for every single key-swap _again and again and_ …    
    &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    
**B)** There _**IS** though a second way_ that I found, much more flexible, but that one may take some getting-used-to:

    "from": {"key_code": "left_command", "modifiers": {
                                             "optional": ["any"]} },
    "to": [{"shell_command": "osascript -e 'if name of window 1 ¬
    of application \"Chrome\" is \"Chrome_Remote_Desktop\" ¬
    then\n tell application \"System Events\" to key down ¬
    {control}\n delay 1\n tell application \"System Events\" to ¬
    key up {control}\n end if'"} ], "type": "basic"
The trick of this 2nd way is splitting "control down" to a "key down-" and a "key-up-part", inserting in between a "delay 1" to allow recognition of any additional keys you press.    
By combining the "delay 1" with "any-modifier" **_passing a variable is simulated_**.

Its problem is, you have to wait a fraction of a second (but less than a whole) for pressing the letter, and you have to release and press again both keys for subsequent shortcuts. May take some "discipline" to work but _needs only ONE "from…to"_ and is menus-"adapting" …
    &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    
**_C) … is no real "C"_** but some hints: you should "conditions" these "from…to"s to specific applications, and find out where to best place them in your karabiner.json, _AS these key-combos may prevent "normal" Cmd combinations._    
_(Hope I didn't muddle "Cmd"s & "Ctrl"s too much ;-) )_

**Comment by ToastyKen** [comment]
What's the etiquette here? Can I ping this to keep it open, as I'd still like to have it?

**Comment by entonio** [comment]
I couldn't make any of the alternatives work. I haven't had any luck with the bundle id either (unless I'm misreading the bundle id, AIUI it includes the remote desktop extension id. Nor can I get the log to show me anything.

This would really be helpful. Unfortunately, all the issues I've opened here have been 'auto closed' without a single word from the developer. It's frustrating, but what can I do?

**Comment by wagnergerald** [comment]
I would stille like to have the feature

**Comment by e-gaulue** [comment]
Any news about it. Any way to know the window name to enable/disable key modification?
