### ISSUE TITLE
emacs-mode Ctrl+A / Ctrl+E not working in MS Outlook

### ISSUE THREAD

**Issue by mkosma** [tekezo/Karabiner-Elements#1525]
macOS version: High Sierra 10.13.6
Karabiner version: 12.1.0
Your Mac hardware: Macbook pro 2013
Your keyboard hardware: built-in macbook keyboard

Some control keys (Ctrl-A and Ctrl-E) are not working in MS Office apps like Outlook.
Used to work fine in old Karabiner, then it stopped working, so I upgraded to Karabiner-Elements.
Enabled Emacs key bindings (rev 12) complex modifications package from the web, which includes the Ctrl-A/Ctrl-E bindings according to the help.

(How can I see details on what the complex mods actually do? In old Karabiner the UI was (overwhelmingly) details)

mk

**Comment by Shiu-Sakashita** [comment]
macOS version: Catalina 10.15.7
Karabiner version: 13.4.0
Your Mac hardware: Mac mini (2018)
Your keyboard hardware: 87EC-XRGB(CATEX TECH.)

Ctrl-A and Ctrl-E are not working in Microsoft Outlook for Mac 16.48 (21401102).
On Microsoft Word for Mac  16.48 (21401102), these keys are ok.
I can send some logs if you want.

**Comment by Shiu-Sakashita** [comment]
In many cases, Ctrl-A/E are work, but only in  a message body input area of new message window, does not work

**Comment by Shiu-Sakashita** [comment]
Probably, I've found a workaround.
I've load the .json file in this blog page to my karabiner element.
https://qiita.com/yohm/items/de35f3874fd0e679ccdf
