### ISSUE TITLE
Missing keys for mapping "|", "≠", "{", "}"

### ISSUE THREAD

**Issue by darkwood-studios** [tekezo/Karabiner-Elements#1527]
I'm looking for a possibility to map "|", "≠", "{", "}" to another key. I can't find them in the simple modifications.

**Comment by michelkoga** [comment]
{ is shift + [ , } is shift + ] , | is shift + \, etc.

So, if you want to change { to a , you have to build a complex modification shift + [  to a.
Read the manual for complex modifications.

**Comment by limeb** [comment]
@darkwood-studios  look up Ukulele and just change the keyboard layout.  It does quite a bit.
