### ISSUE TITLE
accented vovels in italian keyboard

### ISSUE THREAD

**Issue by paolini** [tekezo/Karabiner-Elements#1529]
I would like to remap the key "ù" of the italian keyboard. Cannot find on the dropdown menu "from key".
[https://it.wikipedia.org/wiki/File:Italian_Keyboard_layout.svg](https://it.wikipedia.org/wiki/File:Italian_Keyboard_layout.svg)

**Comment by clemsam** [comment]
Your letter ù is typed by a "deadkey" (`) plus directly following "u".
As it is "naturally" combined of two keys, you cannot simulate it with "simple" modifications – "complex" ones are needed here.

**Comment by paolini** [comment]
I have an italian keyboard where the letter ù is a single keystroke (should have mentioned before!)

https://goo.gl/images/koyq3D

**Comment by clemsam** [comment]
Okay, that makes it (possibly) even easier:
Start Karabiner Elements' **EventViewer**, press that ù key and watch its **"name"** in EventViewer. _THIS name_ is what you must find – don't look for ù …

Actually, on my German keyboard, its name is "backslash" although I SEE these letters printed on it: 
 **'**  (above) and **#** (below)

I can't explain, though, why the printed/sent key-value is NOT the one registered with EventViewer; I suspect that K-E "grabs" keys at a system level, before nationalisations take place.
