### ISSUE TITLE
Request: Separate virtual keyboard settings for different keyboards

### ISSUE THREAD

**Issue by sgronblo** [tekezo/Karabiner-Elements#1535]
MacOS version: 10.13.6
Karabiner Elements version: 

Hello. Thanks for all your hard work at making Karabiner Elements.

I use my Macbook Pro with the following layouts:
- built-in US keyboard
- external US keyboard
- external JIS keyboard

The virtual keyboard layout seems to be shared between all of them as far as I can tell. It would be great if the virtual keyboard layout was specific to a device.

Currently I have come up with the workaround of setting up one profile where the virtual keyboard is JIS and one where it is ANSI. Is there some better way to handle this?

**Comment by griffin-stewie** [comment]
I have a kind of same situation. I wish I could have this request.

**Comment by sgronblo** [comment]
I seem to remember an older version of Karabiner had a checkbox in the tray menu for changing the virtual keyboard. I just googled this issue and found my own issue from two years ago...
