### ISSUE TITLE
CMD-F2 is not working

### ISSUE THREAD

**Issue by feekApp** [tekezo/Karabiner-Elements#1537]
Hi,

After some testing I figured out that Karabiner does something strange with the key combination CMD-F2 cq CMD-F2 is not working.

I'am using 10.13.6 (17G2208) on a 13" MBP 2018 with Touch Bar and KE 12.1.0

The only remap I use is the CAPS to hyper key (default).

I use TextMate and CMD-F2 sets a bookmark. After quitting KE, bookmarks does work again. Removing KE, and al its settings and reinstall again (with NO remap set at all) does not help.

Any clue how to fix this?

== Feek

**Comment by feekApp** [comment]
Not only TextMate, but all other apps using a CMD-F1-Fx shortcut are affected.

Furthermore when quitting KE, swapping Touch Bar from Function Keys to  'Expanded Control Strip' and vv does not work any more! Restart of Mac is needed (without KW).

**Comment by dixius99** [comment]
Just a hunch, but in the Preferences, the second tab is for Function Keys. At the bottom of window is a checkbox to "Use all F1, F2, etc. keys as standard function keys". I would try changing that setting (if it is not checked, try checking it. If it is checked, try unchecking it).

**Comment by feekApp** [comment]
Hi @dixius99 thnx for the suggestion!

Although I do not use Function keys as default, just for some apps, see
![img](https://feek.d.pr/NNvm7z.jpg)

Selecting  "Use all F1,F2...keys als default..."  does solve my problem. The Touch Bar still switch to 'Expanded Control Strip' when leaving TextMate as expected behaviour!

Thnx for helping!

**Comment by feekApp** [comment]
Similar to the above issues, the key combination OPT-ESC also does not work anymore when KE is active. Quitting KE, the combination does work again.

**Comment by feekApp** [comment]
There are similar issues, see [#1638](https://github.com/tekezo/Karabiner-Elements/issues/1638)
