### ISSUE TITLE
fn+Any Fnumber to increase or decrease brightness does not work

### ISSUE THREAD

**Issue by STiXzoOR** [tekezo/Karabiner-Elements#1539]
Hi,

After i updated karabiner to the latest version, i figured out that pressing fn+F2 or any other of the Fnumber to increase or decrease brightness stopped working, although in the event viewer it's showing the correct output.

I can only map the Fnumbers for the brightness in simple modifications sections but i want to use them in combination with the fn button.

I'm using 10.13.5 on a hackintoshed laptop and i have patched my ACPI to control the brightness with the fn+F2 and fn+F3, which works by the way if i close Karabiner.

Any clue how to fix this?

**Comment by asgmeonerandom** [comment]
fuck
