### ISSUE TITLE
"Numeric Keypad" complex rule set does not work

### ISSUE THREAD

**Issue by antonkratz** [tekezo/Karabiner-Elements#1545]
I want to use the "Numeric Keypad" rule complex set.

It does not work. Other complex rule sets do work, for example the included "Change right_command+hjkl to arrow keys" does work. I want to use the "Numeric Keypad" rule complex set however.

Tested Karabiner-Elements version: 10.1.0 and 10.1.5

macOS High Sierra 10.13.6 (17G65)

**Comment by bmontana-edu** [comment]
The Numeric Keypad complex modifications `json` file still is not working nine months after #1545 was opened (opened 1 Sep 2018; closed 7 Nov 2018). It installs successfully but does not activate when enabled and hot key (CapsLock in my case) is pressed.

Karabiner-Elements v12.4.0
macOS Mojave 10.14.4
MacBook Pro (15-inch, Mid 2012)
