### ISSUE TITLE
KE Interferes with Razer Synapse

### ISSUE THREAD

**Issue by SConaway** [tekezo/Karabiner-Elements#1546]

**Comment by SConaway** [comment]
bump...

**Comment by owenzhao** [comment]
When Karabiner-Elements is enabled, Razer keyboards' lighting scheme is lost and worksin a factory default mode. Razer Synapse no longer can control the light scheme of the keyboards.

If quitting Karabiner-Elements totally by right clicking the icon in the menubar, the lighting scheme will restore and Razer Synapse can control the lighting again.

**Comment by SConaway** [comment]
Yes. Any idea on fixes KE team?

**Comment by kdbaustert** [comment]
Yeah, I'm having the same issue use to work before...

**Comment by hemanthpai** [comment]
bump

**Comment by hemanthpai** [comment]
Here's how i fixed this issue: Go to Devices tab -> Uncheck the box for "Modify events from this device" for your Razer keyboard. The lighting works for me now.

**Comment by owenzhao** [comment]
> Here's how i fixed this issue: Go to Devices tab -> Uncheck the box for "Modify events from this device" for your Razer keyboard. The lighting works for me now.

I don't quite understand your solution. It equals quitting KE for the keyboard. It is not a solution.

**Comment by SConaway** [comment]
That is a temporary workaround. Because of this problem, I don't use KE anymore. I just used it for the modifier keys anyways, so settings can handle that.
