### ISSUE TITLE
Shift + Esc not working properly in Slack with Karabiner-Elements running

### ISSUE THREAD

**Issue by jdmaldon** [tekezo/Karabiner-Elements#1547]
MacBook Pro (15-inch, 2017)
MacOS High Sierra 10.13.6 (17G65)
Processor: 3.1GHz Intel Core i7
Memory: 16 GB 2133 MHz LPDDR3
Graphics: Intel HD Graphics 630 1536 MB

Slack
Version 3.3.1 (Direct Download)

Karabiner-Elements 12.1.0

Problem:
With Slack, and Karabiner-Elements running, I can NOT use `Shift + Esc` to 'Mark All as Read'.   I have tested the `Shift` key and the `Escape` key in various other applications/scenarios, and and confirm they're working fine independently.  I have captured the keypress events in the Karabiner Event Viewer:

Generic `Shift + Esc`:
```
eventType:key_down        code:0xe1       name:left_shift      misc:
eventType:key_down        code:0x29       name:escape          misc:
eventType:key_up          code:0x29       name:escape          misc:
eventType:key_up          code:0xe1       name:left_shift      misc:
```

`Shift + Esc` in Slack:
```
eventType:key_down        code:0xe1       name:left_shift      misc:
eventType:key_down        code:0x29       name:escape          misc:
eventType:key_up          code:0x29       name:escape          misc:
eventType:key_up          code:0xe1       name:left_shift      misc:
```

Karabiner-Elements appears to be able to capture the keystrokes, but it does not seem to be making its way into Slack.   I am able to consistently reproduce this problem, and can confirm that `Shift + Esc` does work when Karabiner-Elements is not running.

Please let me know if there is any additional information I can provide to troubleshoot this issue.

**Comment by dakira** [comment]
I have the exact same problem. Shift+ESC doesn't work as a shortcut as soon as karabiner is used.

**Comment by jdmaldon** [comment]
Yeah unfortunately this but was marked stale. In the event where I really need to mark all as read, I just close out Karabiner, do the Shift+ESC, and open Karabiner again.

**Comment by Vlaaaaaaad** [comment]
Is there any way to reopen this? 

This used not to be the case and I thought Slack was at fault initially.

**Comment by Kuniwak** [comment]
I have the same problem on macOS. But my co-worker can use ⇧ + Esc on Slack with Karabiner-Elements on macOS. But his configurations are bitty large, so I could not determine what cofigurations are needed to avoid this problem.

**Comment by Kuniwak** [comment]
I could fix the problem by enabling "Modify events from this device" to the disabled keyboard.
This keyboard have been displayed as `No product name (No manufacturer name)` on Karabiner-Elements Preferences > Devices.

<img width="1112" alt="2019-01-23 16 53 23" src="https://user-images.githubusercontent.com/1124024/51591140-8feb5780-1f2f-11e9-97c3-075225e3d53c.png">

<details>
<summary>I confirmed the environment.</summary>
<dl>
<dt>Mac
<dd>MacBook Pro (15-in, 2017)
<dt>OS
<dd>macOS 10.13.6
<dt>Karabiner Elements version
<dd>12.1.0
</dl>
</details>

**Comment by christianjul** [comment]
Thank you @Kuniwak, I had this problem in other apps using shift and function keys, it solved that as well.

**Comment by gabsn** [comment]
Thanks it solved my issue with the shortcut to force quit applications.

**Comment by popov-andrey** [comment]
Thanks it worked

**Comment by h0tk3y** [comment]
Worked for me, too. I think this issue should be reopened as it may be a bug in Karabiner-Elements or at least very counter-intuitive behavior.

**Comment by Cenay** [comment]
Windows PC here and the issue remains. I can't find anything that is conflicting and it was working fine just a few days ago!
