### ISSUE TITLE
Karabiner isn't passing keystrokes on to SFML

### ISSUE THREAD

**Issue by sammyhw** [tekezo/Karabiner-Elements#155]
When Karabiner-elements is enabled keystrokes aren't passed on(?) and SFML doesn't see them as pressed.  I think the relevant source files in SFML are:

[HIDInputManager.hpp](https://github.com/SFML/SFML/blob/master/src/SFML/Window/OSX/HIDInputManager.hpp) 
[HIDInputManager.mm](https://github.com/SFML/SFML/blob/master/src/SFML/Window/OSX/HIDInputManager.mm)

Here is a code sample.  If Karabiner-Elements is enabled pressing A reports nothing.  If Karabiner-Elements is closed via the _Quit Karibiner-Elements_ at the bottom left, the keypress is reported correctly.

``` cpp
int main() {

    sf::RenderWindow window(sf::VideoMode(800, 600), "KB Help");

    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
            {
                window.close();
            }
        }

        if (sf::Keyboard::isKeyPressed(sf::Keyboard::A))
        {
            std::cout << "A key pressed" << std::endl;
        }

        window.clear(sf::Color::Black);
        window.display();
    }

    return 0;
}
```

**Comment by tekezo** [comment]
The IOKit method is exclusive. (Karabiner-Elements have to use `IOHIDDeviceOpen(kIOHIDOptionsTypeSeizeDevice)`)
We cannot avoid this issue.

**Comment by sammyhw** [comment]
Is there a way to solve it from the SFML side?

**Comment by tekezo** [comment]
Using CGEventTap in SFML is a workaround.

Example of CGEventTap usage.
https://github.com/tekezo/Karabiner-Elements/blob/master/appendix/eventtap/main.cpp
(I think using `kCGSessionEventTap` is suitable location for SFML purpose.)

There are some limitation in CGEventTap with Secure Keyboard Entry, but it is not a matter in generic applications.
https://github.com/tekezo/Karabiner-Elements/blob/master/DEVELOPMENT.md#cgeventtapcreate
