### ISSUE TITLE
How do you enable modifier flag sync?

### ISSUE THREAD

**Issue by JimRoepcke** [tekezo/Karabiner-Elements#1552]
Installed Karabiner Elements 12.1.0 today, on a 2016 MBP w/ TouchBar running 10.13.6.

I've connected two Magic Keyboards (one via USB, one via BT).

The Modifier Flag Sync feature is not working. On my other machines I haven't had to do any configuration (that I recall) to make this feature work.

Am I doing something wrong or is this feature not working anymore?

**Comment by JimRoepcke** [comment]
![image](https://user-images.githubusercontent.com/39997/45321967-e2921d00-b514-11e8-8880-da7e4251f499.png)

**Comment by tarballz** [comment]
Did you ever end up getting an answer to this? I'm having the same issue.

**Comment by JimRoepcke** [comment]
No answer yet
