### ISSUE TITLE
Moving the mouse will release the button

### ISSUE THREAD

**Issue by maxming2333** [tekezo/Karabiner-Elements#1554]
### Premise

I want to convert Option+Tab to Command+Tab

### Configuration

simple modifications：

![image](https://user-images.githubusercontent.com/8816730/45361930-17ca6800-b606-11e8-9f5f-cfa68bc71ca4.png)

Now I set the button mapping like this:

```
{
  "description": "Change Option+Tab to Command+Tab",
  "manipulators": [
    {
      "from": {
        "key_code": "tab",
        "modifiers": {
          "mandatory": [
            "option"
          ],
          "optional": [
            "any"
          ]
        }
      },
      "to": [
        {
          "key_code": "tab",
          "modifiers": [
            "command"
          ]
        }
      ],
      "type": "basic"
    }
  ]
}
```

### Problem

- When I press `Option` + `Tab`, it works fine. ✅
- When I press the `Tab` repeatedly, I can switch normally.  ✅
- When I hold down the `Option`, the interface keeps showing. ✅
- When I move the mouse (just move the mouse), the interface disappears (should be the `keyup` event sent) ❌

If you are using the original `Command` + `Tab`, moving the mouse will not release the button.

Is there any way to solve it?

**Comment by maxming2333** [comment]
When i use `Option` + `Tab`，Very normal

```
eventType:key_down        code:0xe2       name:left_alt        misc:
eventType:key_up          code:0xe2       name:left_alt        misc:
eventType:key_down        code:0xe3       name:left_gui        misc:
eventType:key_down        code:0x2b       name:tab             misc:
eventType:key_up          code:0x2b       name:tab             misc:
eventType:key_down        code:0x2b       name:tab             misc:
eventType:key_up          code:0x2b       name:tab             misc:
eventType:key_down        code:0x2b       name:tab             misc:
eventType:key_up          code:0x2b       name:tab             misc:
eventType:key_down        code:0x2b       name:tab             misc:
eventType:key_up          code:0x2b       name:tab             misc:
eventType:key_down        code:0x2b       name:tab             misc:
eventType:key_up          code:0x2b       name:tab             misc:
eventType:key_down        code:0x2b       name:tab             misc:
eventType:key_up          code:0x2b       name:tab             misc:
eventType:key_down        code:0x2b       name:tab             misc:
eventType:key_up          code:0x2b       name:tab             misc:
eventType:key_down        code:0x2b       name:tab             misc:
eventType:key_up          code:0x2b       name:tab             misc:
eventType:key_down        code:0x2b       name:tab             misc:
eventType:key_up          code:0x2b       name:tab             misc:
```
Now i moving mouse

```
eventType:key_down        code:0xe2       name:left_alt        misc:
eventType:key_up          code:0xe3       name:left_gui        misc:
```

As you can see, it is automatically sent to the `key down` and `key up` events.

But I still press the `Option` key at this time.

Then I release the `Option` button.

```
eventType:key_up          code:0xe2       name:left_alt        misc:
```

**Comment by maxming2333** [comment]
So you can be sure that moving the mouse will release the button.

**Comment by maxming2333** [comment]
@tekezo Is this a feature?

**Comment by shiwen** [comment]
+1 for this. have exactly the same key mapping and face the same problem. still looking for a solution.

**Comment by OwenCK** [comment]
Is there any way to resolve this - I am also experiencing this.

**Comment by maxming2333** [comment]
I have given up using this and instead use this https://github.com/iMasanari/cmd-eikana

**Comment by Darrel12** [comment]
I'm not very familiar with Karabiner, but would it help to specifically include mouse movement as optional within the JSON configuration rather than "any"? I would try it myself but I haven't seen the necessary string for mouse movement to set it as the optional field if there even is one.

**Comment by genesy** [comment]
I removed simple modifications and used pc shortcuts preset but it's still sending keyup  @Darrel12

**Comment by cktgh** [comment]
I came across this issue recently on version `16.0.0`, it took a bit of trial and error for me but in the end modifying the affected rules with the new [manipulator option `to_if_other_key_pressed`](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to-if-other-key-pressed/) worked.

In my case I remapped `cmd` to `option` with `cmd + tab` as exception.
Here is what worked:
```json
{
    "from": { "key_code": "left_command", "modifiers": { "optional": ["any"] } },
    "to": [ { "key_code": "left_command", "lazy": true } ],
    "to_if_held_down": [ { "key_code": "left_option" } ],
    "to_if_other_key_pressed": [
        {
            "other_keys": [ { "key_code": "tab", "modifiers": { "optional": ["any"] } } ],
            "to": [ { "key_code": "left_command" } ]
        }
    ],
    "parameters": { "basic.to_if_held_down_threshold_milliseconds": 1 },
    "type": "basic"
}
```
