### ISSUE TITLE
Remapping Microsoft Sculpt Ergonomic Mouse' Windows button

### ISSUE THREAD

**Issue by srikat** [tekezo/Karabiner-Elements#1555]
I am trying to map the windows button on Sculpt ergonomic desktop's mouse to Cmd + Space.

In the Simple Modifications tab, I can't find an option that lets me map to Cmd + Space.

![Screenshot](https://d.pr/i/L2XpJm+)

In the Complex Modifications tab, I only see options to add pre-defined rules but not create my own.

Any help is appreciated.

**Comment by RidgeSTD** [comment]
Got it work. See this [issue](https://github.com/pqrs-org/Karabiner-Elements/issues/565#issuecomment-424614748)
