### ISSUE TITLE
Comments in .json file

### ISSUE THREAD

**Issue by spring-haru** [tekezo/Karabiner-Elements#1558]
I know it is not possible to add comments in json in general. But it would be nice if it is possible especially when a config file for complex modifications gets very long. What about creating a new `name` with comments as its `value` such that it is not recognized as an error. For example, see [this link](https://stackoverflow.com/questions/244777/can-comments-be-used-in-json).

**Comment by spring-haru** [comment]
It seems ok to insert comments between `description` and `manipulator` lines.  An error is not raised. For example,

```
{
    "description": "vim style key binding",
    "_COMMENT": "This is a comment which can be useful",
    "manipulators": [
        {
             "type": "basic",
                  "from": {

```

**Comment by clemsam** [comment]
I got no problems when simply typing anywhere:  "Here is a comment...": "",

Karabiner Elements (or json s generally) seem to take this for a non understandable but ignored pair of values ...

**Comment by spring-haru** [comment]
In the following case where "_COMMENT": "...." is in the 4th line, the code does not even show up in "Add rule" in Complex Modification.

```
{
    "description": "vim style key binding",
    "manipulators": [
    "_COMMENT": "This is a comment which can be useful",
        {
             "type": "basic",
                  "from": {
```

In the following case where "_COMMENT": "...." is in the 5th line, an error is raised and indeed is ignored ( the code shows up in "Add rule").

```
{
    "description": "vim style key binding",
    "manipulators": [
        {
             "_COMMENT": "This is a comment which can be useful",
             "type": "basic",
                  "from": {
```

**Comment by braham-snyder** [comment]
related:
* #45
* #1773 

I also find comments extremely useful.

"_comment" etc. is messy -- eg does not allow for good multi-line comments, and requires escaping characters.

FWIW I'm using `watchman` plus `yq` to automatically convert a YAML file with comments in it -- HJSON or StrictYAML eg could be better, but this works fairly well. Biggest downside is keeping both the YAML and the JSON in sync when it comes to git, but I still think it's worth it.

**Comment by alok** [comment]
@tekezo Since the config file is meant for, well, *config*, comments are a feature worth having. The reason JSON doesn't have comments is because it was originally meant for data interchange, not config, and I don't think that reasoning applies here.

**Comment by roachsinai** [comment]
But enable comment like VSCode settings, we could add link to ref where we find the right answer why we add  those settings.
