### ISSUE TITLE
Help needed to configure karabiner.json file

### ISSUE THREAD

**Issue by belle-isle** [tekezo/Karabiner-Elements#1559]
Hi everyone,

I have been using Karabiner and then Karabiner Elements for several years, and it has been a great help so first I would like to thank the developer(s) very much for such a great tool.

However, I would appreciate a little help with my setup (see below), because I am encountering undesirable side effects which I have not managed to solve.

Indeed, I have a MacBook with an american keyboard, which I use to type into other languages. Because I lack accented and otherwise special character keys, I setup several key modifications, some of which I had to make up because I did not find them. An example is changing option(⌥)+a to à.

Also, to make things simpler, because the MacBook only has a backspace and doing forward delete normally requires pressing the inconvenient key combination of fn+delete, I changed the backtick(`) key in the top left to forward delete.

There are two issues I am facing :

First, I often have to type "à " (a with a grave accent, followed by a space). When typed fairly slowly, everything works fine. When typed quickly, though, and for some reason I can't manage to understand, the option(⌥)+a combination does not seem to work quickly enough before the space signal is sent. The result is "`a" ! Could someone please advise as to which parameters, if any, I could change to avoid this behavior ?

Second, I would expect that keeping the backtick(`) key down would work as if I pressed down a forward delete key, meaning the forward delete would repeat. However, nothing happens, not even a single forward delete. Once again, could you help point me in the right direction as to how I could get this key to produce the desired effect ?

Thank you very much for your help, and best regards.

For reference, here is the "rules" section of my karabiner.json file :

```
                "rules": [
                    {
                        "description": "Change equal+delete to forward_delete if these keys are pressed simultaneously.",
                        "manipulators": [
                            {
                                "from": {
                                    "modifiers": {
                                        "optional": [
                                            "any"
                                        ]
                                    },
                                    "simultaneous": [
                                        {
                                            "key_code": "equal_sign"
                                        },
                                        {
                                            "key_code": "delete_or_backspace"
                                        }
                                    ]
                                },
                                "to": [
                                    {
                                        "key_code": "delete_forward"
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    },
                    {
                        "description": "Change option+a to à",
                        "manipulators": [
                            {
                                "from": {
                                    "key_code": "a",
                                    "modifiers": {
                                        "mandatory": [
                                            "option"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "grave_accent_and_tilde",
                                        "modifiers": [
                                            "option"
                                        ]
                                    }
                                ],
                                "to_after_key_up": [
                                    {
                                        "key_code": "a"
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    },
                    {
                        "description": "Change delete_forward if grave_accent_and_tilde (backtick) is pressed alone.",
                        "manipulators": [
                            {
                                "from": {
                                    "key_code": "grave_accent_and_tilde"
                                },
                                "to_if_alone": [
                                    {
                                        "key_code": "delete_forward"
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    }
                ]
            },

```

**Comment by clemsam** [comment]
I tested only one part of your code (á) and changed its "to" to a simple:

    "to": [ 
            { "key_code": "grave_accent_and_tilde"},
            { "key_code": "a"}
          ],
This works perfectly for me – _without a "to_after_key_up"_.
Calling 2 key_codes in the same "to" is allowed ;-) …

Your last "delete_forward" works with me, transplanted into my json – but are you sure that you haven't got too many  `}    ]    }    ]    },` at the very end ?
Your code isn't complete, so I can't tell, but looks suspicious to me …

**Comment by belle-isle** [comment]
Hi clemsam and thanks for your reply.
I realized I had posted this question perhaps not in the right place, so the discussion is now going on here : https://github.com/pqrs-org/KE-complex_modifications/issues/437
Thanks for your suggestion about the "to", but this is not sufficient in my case (please see thread above). Plus the delete_forward does work, but does not repeat when pressed. Please feel free to suggest solutions in the linked thread if you have any !
