### ISSUE TITLE
Can't build on Sierra using Xcode 8

### ISSUE THREAD

**Issue by beargeek** [tekezo/Karabiner-Elements#156]
The following build commands failed:
	CompileC build/karabiner_console_user_server.build/Release/karabiner_console_user_server.build/Objects-normal/x86_64/main.o main.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
make[3]: *** [all] Error 65
make[2]: *** [all] Error 2
make[1]: *** [build] Error 2

make: *** [all] Error 99

**Comment by tekezo** [comment]
Travis CI succeeded the build on Xcode 8.
Did you put boost headers into the proper location?
https://github.com/tekezo/Karabiner-Elements#how-to-build

**Comment by beargeek** [comment]
@tekezo was right, my boost was not at 1.61 or above.
