### ISSUE TITLE
Escape on TouchBar can not be mapped

### ISSUE THREAD

**Issue by caillou** [tekezo/Karabiner-Elements#1561]
I have tried to map the `esc` key of the TouchBar, but without any success.

`Karabiner-EventViewer.app` registers the `key-up` and `key-down` events on `0x29`. But adding a mapping to it does not do anything. Escape functionality continues. Every other key can be mapped.

Tested on a 2018 MacBook Pro 13'' with `macOS 10.13.6` and `Karabiner-Elements-12.1.0`.

**Comment by tommyc38** [comment]
Did you guys try and map the escape key to another key (e.g. control left) in preferences and then try doing your karibiner mappings?  I am wanting to purchase a 15 inch MBP but won't if I can't use the control-left as both escape and modifier during long key press.

**Comment by caillou** [comment]
@tommyc38  I am not entirely sure I understand what you mean by saying the following:

> Did you guys try and map the escape key to another key (e.g. control left) in preferences

Which preferences do you mean?

**Comment by tommyc38** [comment]
The preferences in Mac OS (e.g. Keyboard System Preferences).

**Comment by caillou** [comment]
@tommyc38 Where exactly in the keyboard system preferences would I find a possibility to remap the `ESC` key?

**Comment by tommyc38** [comment]
http://osxdaily.com/2017/02/20/remap-hardware-escape-key-mac/

**Comment by caillou** [comment]
@tommyc38 If you read the article you sent, then you see that it is not possible to remap the `ECS` key, but to remap another key to `ESC`. Subtle but important difference.

**Comment by aaroncraigongithub** [comment]
I'm having the same issue on a new MacBook Pro -- I had the touchbar `esc => right_command` mapping working on an older MacBook (2016) that was also running Mojave, so not sure what has changed, if anything.

**Comment by ShangyinGao** [comment]
having the same issue. 
I want to switch `esc` and `grave_accent` just because I use a lot `esc` and want to have some physical feedback. But it failed to map `esc` to 'grave_accent'. 

Hope to get some useful answer

**Comment by jm3** [comment]
Can anyone clue me into, as mentioned in #780, how to restore ⌘-⌥-ESC when Karabiner Elements is running? That issue was auto-closed by the **stale** bot, but as far as I can see, it remains unresolved.

**Comment by ramirez** [comment]
I'm having this same issue. How come it is marked as stale?

**Comment by caillou** [comment]
This issue is still existing. How can it be re-opened?

**Comment by owst** [comment]
@caillou not sure if you're having the same issue, but my escape mapping had no effect (escape would still act as escape) on the touch-bar until I enabled both devices as per https://github.com/tekezo/Karabiner-Elements/issues/780#issuecomment-459202239

Now I have successfully mapped `caps_lock => escape` and `escape => caps_lock`

**Comment by vegerot** [comment]
**Solution**: Check "No Product Name" in "Devices" menu!

> @jm3 I didn't fix it cause it is not a bug at all. You need to check both the items listed in the "Devices" sub-table. See below
> ![snipaste_2019-01-31_11-31-28](https://user-images.githubusercontent.com/8088354/52028902-dbaf8980-254b-11e9-997c-b18a320977b5.png)
> As touch bar is recognized as a secondary keyboard, you need to make sure it is set to respond to Karabiner's manipulation.



_Originally posted by @RoadToDream in https://github.com/pqrs-org/Karabiner-Elements/issues/780#issuecomment-459202239_
