### ISSUE TITLE
left_alt vs left_option

### ISSUE THREAD

**Issue by lucbouge** [tekezo/Karabiner-Elements#1566]
MacOS High Sierra 10.13.6
Karabiner Elements 12.1.0

Dear tekezo,

Thanks for your excellent software. I used it to remap "Alt+é" to "É" on my French keyboard, thanks to experiments with Karabiner EventViewer. I join my final JSON file for your convenience. 

I was confused that the "Left Alt" key of my keyboard is display "left-alt" on EventViewer whereas it has to be denoted as "left-option" in the Elements "Complex Modification" JSON files. 

It is even more confusing as in the "Simple Modification" display, it is called "left-alt (equal to left-option)", so that I was misled to consider the two denotations as equivalent.

Wouldn't it be easier to unify the two denotations? 

Best regards,

Luc.

[uppercase.json.txt](https://github.com/tekezo/Karabiner-Elements/files/2408948/uppercase.json.txt)

**Comment by lucbouge** [comment]
MacOS version: macOS 10.13.4
Karabiner version: Karabiner-Elements 12.1.0 
Your Mac hardware: MacBook Pro
Your keyboard hardware: "Apple Internal Keyboard / Trackpad", AZERTY French keyboard

        "is_keyboard": true,
        "is_pointing_device": false,
        "location_id": 339738624,
        "manufacturer": "Apple Inc.",
        "product": "Apple Internal Keyboard / Trackpad",
        "product_id": 611,
        "registry_entry_id": 4294973624,
        "transport": "USB",
        "vendor_id": 1452

**Comment by Cybergern** [comment]
I had the same issue, EventViewer shows "left_alt" but in Karabiner you actually have to use "left_option", same problem with "left_gui" and "left_command".
