### ISSUE TITLE
PC keyboard CTRL is not working as expected on mojave

### ISSUE THREAD

**Issue by sisoje** [tekezo/Karabiner-Elements#1567]
its possible that karabiner does not work at all on mojave.
since i updated my OS Ctrl+C Ctrl+V does not work properly.

**Comment by hawflakes** [comment]
I just installed the latest version from https://pqrs.org/osx/karabiner/ after upgrading and it works for me!

**Comment by sisoje** [comment]
hm i reinstalled it and restarted my computer... seems to work thanks
