### ISSUE TITLE
Karabiner-Elements switching < and > with @ and # with AZERTY keyboard

### ISSUE THREAD

**Issue by Cubox-** [tekezo/Karabiner-Elements#157]
Hi,

My configuration file is:

```
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
            "application": "fn"
            }
        }
    ]
}
```

Everything is working fine and all the features I needed from the old Karabiner are here, however, when Karabiner-Elements is enabled, the keys giving me @ (and # with shift) and < (and > with shift) are inverted.

This only occurs with my external USB keyboard, a WASD keyboard. The internal keyboard is working fine with those two keys.
If I close Karabiner-Elements, the keys are back to their normal "default" behaviours.

Not sure if this is a bug or a "feature", but I never had this issue with the old Karabiner.
If this is not a bug, and that I can fix it with a configuration file tweak, I would be grateful if you could give me the codes for those keys.

**Comment by Cubox-** [comment]
Found what to input in configuration file to fix this behaviour:

`                "non_us_backslash": "grave_accent_and_tilde",
                "grave_accent_and_tilde" : "non_us_backslash"`

**Comment by aurelberra** [comment]
That's a good workaround. However, the bug remains: you want to be able to use both the internal keyboard and the external, USB keyboard.

I'm keeping an eye on the very active development of KE. Thanks to all contributors!

**Comment by arnaudlimbourg** [comment]
@Cubox- Thanks for this, it was driving me mad!
