### ISSUE TITLE
Caps Lock LED stop working after upgrade to macOS Mojave (10.14)

### ISSUE THREAD

**Issue by PapaGolf** [tekezo/Karabiner-Elements#1574]
macOS version: macOS Mojave (10.14)
Karabiner version: Karabiner-Elements 12.1.0
Your Mac hardware: iMac 27" Late 2012
Your keyboard hardware: Apple Magic Keyboard with Numeric Keypad

Caps Lock LED stop working after upgrade to macOS Mojave (10.14)

Led will work if I quit Karabiner

**Comment by abhinav1587** [comment]
Hi,
I am experiencing the same issue with the keyboard on a 2017 MacBook.

**Comment by a-triant** [comment]
Duplicate of #1502

**Comment by evoncken** [comment]
Upgraded MacOS from 10.13.6 to 10.14 (so no beta installed ever). Karabiner 12.1.0 was already installed. Caps Lock LED stops working while Karabiner is running.

**Comment by akacaz** [comment]
Yep. The same to me. Caps Lock LED doesn't work as long as Karabiner is running.

**Comment by masterandrey** [comment]
Just install the latest BETA version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

I had to upgrade from 12.1.55 to 12.1.56 and now it works again

**Comment by evoncken** [comment]
I just verified that the Caps Lock LED works again after upgrading to release version 12.2.0 (no need to use beta version)

Issue appears SOLVED in release 12.2.0.

**Comment by pechyonkin** [comment]
> I am experiencing the same problem with Mojave and Karabiner.

My issue was solved after updating to 12.2.0.

**Comment by PapaGolf** [comment]
Issue was solved with 12.2.0

**Comment by sathya-murali** [comment]
I have updated Karabiner from 12.4.0 to 12.5 but I still had the same issue.
Below steps worked for me 
Karabiner-Elements->Preferences->Simple Modifications and remove caps lock and re-add. Hopefully, this step should work with other Karabiner versions as well.
Karabiner v12.5.0
Mac OS Mojave 10.14.5
