### ISSUE TITLE
Activate Titlebar LAlt+letter

### ISSUE THREAD

**Issue by limeb** [tekezo/Karabiner-Elements#1575]
I really enjoy using the left alt on my pc(windows/linux) to open menu items in windows.

Is there a feasible way to get this to work?

Right now I have alt+space assigned to highlight the apple menu bar but ideally I would like to make it so that alt+letter automatically triggers "alt+space" "letter" "Enter"

I'm fairly certain the answer is yes but I haven't had enough time to mess with this yet.

**Comment by limeb** [comment]
@clemsam I would be interested to see your set up possibly.

Certainly sounds interesting.

**Comment by clemsam** [comment]
Hi, limeb, I post my example for "Tags…".
A similar example for (e.g.) "Edit" would need one more line `{"key_code": "right_arrow"}` plus an alternative for "t" according to the item – BUT maybe you only want to roll down menus and pick items "manually" by 1st-letters?  
In that case you would not need the "t"- and "return_or_enter"-part at all.

For "View" you'd need 4 lines of "right_arrow", 5 lines for "Go" and so on.
Which means: copy the entire "manipulator" (>  { "conditions":  … "basic"}, ), append it to the last one etc.
 
The whole menu-roll-down happens so fast, you won't notice any delay.  

 |   |  Finder  |  File  |  Edit  |  View | Go | Window | Help
 |
 | . . | . . . . . .|Tags |

    { "title": "Finder … ''Tags…''",
       "rules": [
          { "description": "Finder:  ''Tags…'' ",
            "manipulators": [
                    { "conditions": [
                                { "bundle_identifiers": [
                                        "^com.apple.finder" ],
                                "type": "frontmost_application_if" }
                                    ],
                      "from": { "key_code": "t",
                                "modifiers": {
                                    "mandatory": ["left_option"] }
                              },
                        "to": [ { "key_code": "f2",
	                              "modifiers": ["left_control"] },
                                { "key_code": "right_arrow"},
                                { "key_code": "right_arrow"},
                                { "key_code": "down_arrow"},
                                { "key_code": "t"},
                                { "key_code": "return_or_enter"}
                            ],
                      "type": "basic"
     }    ]    }    ]    }
