### ISSUE TITLE
Enter is not Return

### ISSUE THREAD

**Issue by fassverwaltung** [tekezo/Karabiner-Elements#1578]
I can only change for ex. the right option key (I don't use for option-function) to 
«Enter-or-Return». This is terrible, while Enter is not Return. 
It would be necessary to be able to change to Return or change to Enter. 

In older Versions, I could change the right option key to an pure «Enter». I miss that. 
In a lot of programs, Enter has not the same function as Return (Filemaker, Word, Excel...) 

This was an idea for the next release. Please build in. Thank you.

**Comment by Bibi** [comment]
I have the same problem: the two keys (enter and return) should be separate. Mathematica, TextMate, etc. all use both keys!

Please incorporate the modification in the next build, thanks!

**Comment by fassverwaltung** [comment]
> Am 07.01.2019 um 18:41 schrieb Bibi <notifications@github.com>:
> 
> I have the same problem: the two keys (enter and return) should be separate. Mathematica, TextMate, etc. all use both keys!
there are thousands with the same problem:
Enter is not return! (and the earth is not a disc)
> 
> Please incorporate the modification in the next build, thanks!
Yes, urgent!
The terrible thing is: older versions habe understood the difference betwenn Enter und Return, die newer versions have forgotten that. 
>

**Comment by hawkiboy** [comment]
Me too and three! Why are you marking this as stale? This issue requires a response.

**Comment by hawkiboy** [comment]
Oh, here is the answer:                             "key_code": "keypad_enter"
