### ISSUE TITLE
Shift to parentheses

### ISSUE THREAD

**Issue by jagot** [tekezo/Karabiner-Elements#158]
One feature I miss terribly is the mapping of a single press of the left/right shift key to ( / ). Is this possible now, or yet to come?

**Comment by iamFIREcracker** [comment]
https://github.com/tekezo/Karabiner-Elements/issues/8 contains an interesting workaround for a similar problem -- it works if you have Keyboard Maestro.

[![Left shift to left round bracket](http://s13.postimg.org/tcj2vpi5j/Screen_Shot_2016_09_26_at_8_02_22_PM.png)](http://postimg.org/image/sn0ajchlv/)

**Comment by martinklepsch** [comment]
With the new complex modifications feature that also enabled Hyper you can now also map shift to parens again! 🎉 

Here is how I did it:  https://github.com/martinklepsch/dotfiles/commit/83e4989d7ea3afb2809e74b34e77d8111136b5d8

**Comment by jagot** [comment]
That is very nice, and works very well with US keyboard layout. I switch back and forth between a few different layouts, among them Swedish which has (, ) mapped to shift + 8, 9. Is there a way of getting a parenthesis directly? It is not a big issue for me, since I use the shifts to parentheses when I program, for which I use US layout, anyway, but a more general solution would be nice.

**Comment by iamFIREcracker** [comment]
@martinklepsch did you manage to get 'complex_modifications' to work?  I did not, I add them to the json file, Karabiner-Elements shows them up in the UI, but nothing changes.

```json
                    {
                        "description": "Post ( if left_shift pressed alone",
                        "from": {
                            "key_code": "left_shift",
                            "modifiers": {
                                "optional": [
                                    "any"
                                ]
                            }
                        },
                        "to": [
                            {
                                "key_code": "left_shift",
                                "modifiers": []
                            }
                        ],
                        "to_if_alone": [
                            {
                                "key_code": "9",
                                "modifiers": [
                                    "left_shift"
                                ]
                            }
                        ],
                        "type": "basic"
                    },
                    {
                        "description": "Post ) if right_shift is pressed alone",
                        "from": {
                            "key_code": "right_shift",
                            "modifiers": {
                                "optional": [
                                    "any"
                                ]
                            }
                        },
                        "to": [
                            {
                                "key_code": "right_shift",
                                "modifiers": []
                            }
                        ],
                        "to_if_alone": [
                            {
                                "key_code": "0",
                                "modifiers": [
                                    "right_shift"
                                ]
                            }
                        ],
                        "type": "basic"
                    }
                ]
```

FWIW, I am on Karabiner-Elements v0.91.11

**Comment by iamFIREcracker** [comment]
Nevermind, mistake on my side, I got the configuration schema wrong -- I had added these to 'rules', instead of 'rules.manipulators'..

**Comment by martinklepsch** [comment]
I changed my config so that the shift to parens thing is implemented as a separate complex modification: https://github.com/martinklepsch/dotfiles/blob/6a2f4d555c763ae806cd8e875be821a52746914a/config/karabiner/karabiner.json#L16
