### ISSUE TITLE
Feature Request: CmdQUERTY Checkbox

### ISSUE THREAD

**Issue by SwingDancerMike** [tekezo/Karabiner-Elements#1580]
CmdQWERTY means Cmd-Key functions as on a QWERTY keyboard, no matter what that key is remapped to. It's a common feature on DVORAK.

While it is possible to make complex rules to do this, CmdQWERTY seems like a common use case for a remapped keyboard.

Request is an easy way to provide an easy way to enable CmdQWERTY, such as a checkbox on the "Simple Modifications" tab.

**Comment by abass** [comment]
This would be amazing to have... Wish it existed
