### ISSUE TITLE
Remapping capslock to F5

### ISSUE THREAD

**Issue by jasonl99** [tekezo/Karabiner-Elements#1583]
I do this remap as an action key for tmux (normally ctrl-b, but I use f5).   I'm using a Logitech K750 keyboard.

This worked fine for awhile, but I added a second K750 keyboard (one at home and one at the office) and they _both_ stopped working correctly.

I've done a simple remap of capslock to F5:
<img width="835" alt="screen shot 2018-10-05 at 10 02 56 am" src="https://user-images.githubusercontent.com/1554969/46539931-e0a64a00-c885-11e8-9d56-30bca461f345.png">

Here's the event viewer.  I _do not_ get a pair of key_down/key_up events on each press, rather, just a single event for each press, alternating between up and down. 
![screen shot 2018-10-05 at 9 59 56 am](https://user-images.githubusercontent.com/1554969/46539804-82796700-c885-11e8-8309-409f243d28f8.png)

I would expect each capslock keypress to generate both an up and down event.  The problem is that when it does a key_down event, it's effectively repeating the F5 key repeatedly, which wreaks havoc in tmux.

**Comment by yqrashawn** [comment]
You need to complex modification. Check the documentation. Search for “repeat”.

**Comment by jasonl99** [comment]
I tried, doesn't work.   The `caps_lock` key is not sending a `key_down`/`key_up` with each press-and-release.   It is toggling them.  So If I press `caps_lock` five times, and I look at the event viewer, get this for my five presses:

key_down
key_up
key_down
key_up
key_down

If I do the same for any other key, I get

key_down
key_up
key_down
key_up
key_down
key_up
key_down
key_up
key_down
key_up

**Comment by jasonl99** [comment]
On a hunch, I rebooted my machine, and it all just started working again with the simple modification (Capslock to F5) as described in the original report. 

Sheesh, I guess I should reboot more often!
