### ISSUE TITLE
mouse scroll wheel emulation

### ISSUE THREAD

**Issue by belm0** [tekezo/Karabiner-Elements#1586]
I'd like to open this issue again (similar issue has been auto-closed recently):

reimplement the original Karabiner's the ability to map mouse position to scroll when you have 3rd mouse button or some keyboard key pressed, etc.

![fs0i3](https://user-images.githubusercontent.com/1708631/46576971-f9dd0100-ca13-11e8-8cae-5c8e5ff15476.png)

I'm currently using a paid utility to accomplish this (and am aware of open source solutions like hammerspoon), but would love the flexibility of Karabiner-Elements supporting it natively.

I've just contributed $10 to Karabiner-Elements for supporting my crazy keyboard customizations for many years.  Thank you.

**Comment by vetermanve** [comment]
I had this required too, I had a trackball and original scroller on it terribly uncomfortable.
Team, please add this feature to new versions!

ps.
@belm0 - what paid utility solved this request for u now?

**Comment by vlad-wonderkidstudio** [comment]
Any way to add the scroll support?
