### ISSUE TITLE
Scroll Lock

### ISSUE THREAD

**Issue by entonio** [tekezo/Karabiner-Elements#1587]
I have a non-mac keyboard with backlit keys and the only way to turn them on is to have Scroll Lock on. However, since macOS has no idea what Scroll Lock is, I have to use a C program to set the correct flags on the device - https://github.com/damieng/setledsmac.

But once Karabiner-Elements is running, `setleds` is unable to read or set the flags on the physical keyboard or on Karabiner's virtual one. And since karabiner starts via `/Library/LaunchAgents`, I have no way to call `setleds` before it. So far, I've only found 2 solutions:
- run `setleds` via `/Library/LaunchAgents` as well. This is a big no-no for me, I've had serious problems before running my own agents in the master `/Library`.
- quit KE from the menu, run setleds, then run KE again. This is a chore as it has to be done manually, I've though of writing some Applescript, but it would be a very fragile script.

So, it would be great if either:
- KE could turn on Scroll Lock itself on the physical keyboard. I haven't managed to do it before. I've tried.
- KE could be made to run only as a login item, as IMO it should be anyway, then I could place setleds on the user `~/Library/...` or find some other way to run it before KE, like creating a script that would run setleds and only then KE.

**Comment by entonio** [comment]
So, this project is full of issues that get autoclosed because the developers don't even look at them? I don't think that's what autoclose was created for!

**Comment by mikel551** [comment]
It looks like the latest update addressed the capslock issue where I can use setleds to enable/disable it.  However, scroll lock  doesn't work and I would like that as well.

**Comment by whooof** [comment]
Any chance of fixing it?

**Comment by dx7** [comment]
It'd be very nice to control num lock and scroll lock LED using that setleds project. I've a very nice configuration to enable/disable the keypad (non-mac keyboard) which has used caps lock LED as num lock indicator (I do not use caps lock at all) but it's weird.
