### ISSUE TITLE
Emulating VK_LOCK_* commands

### ISSUE THREAD

**Issue by calvinwyoung** [tekezo/Karabiner-Elements#1588]
One feature I miss from the original Karabiner is the VK_LOCK_* virtual keys. Specifically, I used to use `VK_LOCK_SHIFT_L_FORCE_ON` to emulate "mark set mode" in emacs.

Is this possible to implement with the current capabilities in Karabiner-Elements? If not, what would it take to get this added?

**Comment by JSpenced** [comment]
Did you ever figure this out? I am also curious about this.
