### ISSUE TITLE
Backslash to delete not working

### ISSUE THREAD

**Issue by martinweiss** [tekezo/Karabiner-Elements#159]
I'd like to the backslash key to delete, however, I can't make it work :(

I'm sorry about the code snippet. How do I make it look nice?

> {
>     "profiles": [
>         {
>             "name": "Default profile",
>             "selected": true,
>             "simple_modifications": {
>                 "backslash": "delete"
>             }
>         }
>     ]
> }

**Comment by talha131** [comment]
Your configuration should be

```json
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "backslash": "delete_or_backspace"
            }
        }
    ]
}
```

> I'm sorry about the code snippet. How do I make it look nice?

See examples on this page https://guides.github.com/features/mastering-markdown/#examples

**Comment by martinweiss** [comment]
Hmm, something else must be wrong. It still doesn't work. I also just checked the log, and it doesn't show anything recent (last entry is from the 24th, when I installed the application). I'm not sure what to do. Any suggestions?

**Comment by martinweiss** [comment]
Alright, the problem went away when I re-installed the program. I'll close thise issue now.
