### ISSUE TITLE
vi mode not working on macOS Mojave10.14

### ISSUE THREAD

**Issue by vicxia** [tekezo/Karabiner-Elements#1593]
My system is  macOS Mojave 10.14,
keyboard is HHKB,
Karabiner-Elements version is 12.1.0， also tried Karabiner-Elements 12.1.5,
Rule is  [Vi Mode (rev 5)](https://pqrs.org/osx/karabiner/complex_modifications/#vi_mode).

My situation is that neither D nor S as trigger key,  the Vi Mode is not working,  buy the way,  the rule 'Change right_command+hjkl to arrow keys' is working well.

Thanks!

**Comment by apm1467** [comment]
Did it work for you on earlier macOS versions, e.g. High Sierra?

**Comment by Jeminaa** [comment]
Same here. It worked perfectly on High Sierra, now Vi Mode is not working on Mojave.
I'm using 2017 Macbook pro 15 inch

**Comment by davyzhang** [comment]
high sierra is ok, but no luck on Mojave

**Comment by vicxia** [comment]
> Did it work for you on earlier macOS versions, e.g. High Sierra?

It works well on High Sierra, but not on Mojave. Same as @davyzhang

**Comment by wangyingang** [comment]
Me too. Same as @vicxia @davyzhang

**Comment by paichi** [comment]
Try this
Please change your simultaneous_threshold_milliseconds setting in Karabiner-Elements → Complex Modifications → Parameters; A value between 150 and 500 is recommended for this mode

**Comment by davyzhang** [comment]
I just found my problem is that I didn't choose the keyboard devices on the preferences -> devices tab.
I don't recall when I unchecked them, but it works now like before.

**Comment by wangyingang** [comment]
> Try this
> Please change your simultaneous_threshold_milliseconds setting in Karabiner-Elements → Complex Modifications → Parameters; A value between 150 and 500 is recommended for this mode

Thanks a lot! @paichi 
300 is better for me
