### ISSUE TITLE
Some questions about custom modifier keys

### ISSUE THREAD

**Issue by ZYinMD** [tekezo/Karabiner-Elements#1594]
I've been a heavy AutoHotkey user on PC for a decade, and I'd love to switch to mac if I can replicate all my keyboard remaps, but I don't have a mac to test...

So my question is: can the following be done? If not just by Karabiner, I'm also willing to combine with Keyboard Maestro or Hammerspoon etc.

1. Something like:
when Sublime Text is the active window, pressing `1+i` will fire `Ctrl+Shift+Alt+i`
on `1` pressed alone, output `1`
on `Shift + 1`, output `!` 

2. Something like:
on pressing `; + j` / `; + k`,  output `{` / `}`
on `;` pressed alone, move to line-end and then output `;`
on `Alt + ;` just output `;` 
on `Shift + ;` output `:`

3. Something like:
on pressing `2 + d`, open ~/Dropbox in finder

4. Something like:
on pressing `left_command + c`, activate Chrome
on pressing `CapsLock + c`, fire `right_command + c`

5. As you can see, they're all about custom modifier keys. Is it different between Karabiner and Karabiner-Elements? On #831 @tekezo seemed to have mentioned it's different.

I'm sorry I probably could figure it out on my own by reading the docs, but I can't test them out because I haven't gotten a mac yet because I don't know if I can replicate my remaps yet, it's a catch 22.

Thanks so much!

**Comment by clemsam** [comment]
Hi ZYinMD, if you buy a Mac with a "modern" system it will be Karabiner _Elements._

1) is easy: K-E can do all this, but app-dependent, not window-dependent.

2) is certainly possible, but not by "Simple Modifications" – you'll have to invest some time!

3) is possible by using "shell_command": "osascript -e 'tell application \"System Events\" to tell process \"finder\" to open windows.
The osascript part actually is AppleScript, but called from Karabiner El.

4) generally handling a non-active app is "shell_command", 2nd line is easy.

5) if you know Terminal/shell commands that's a good start. For some GUI-related tasks you'd need to google/understand some AppleScript.
At first sight, K-E is just a remapper, but it can call a lot of other "helpers" as you see.

**Comment by ZYinMD** [comment]
Hi Clemsam, thanks so much!
I think I will give it a shot, and report back if I make it!
