### ISSUE TITLE
Lack of prepared settings in Elements

### ISSUE THREAD

**Issue by vr8hub** [tekezo/Karabiner-Elements#1599]
I just found out that Karabiner had been replaced with Karabiner-Elements. (Still on Sierra, where I have had no problems with Karabiner 10.x, and no notice of a newer version.)

Elements has none of the "prepared settings" (from the "Change Key" tab in Karabiner) that came with the program and could be checked to be used. I use a number of those on occasion. I've searched both here and in Google Groups, and on the Karabiner website, and can find no explanation of why those were left off, nor how to bring them forward.

Why are we having to re-invent the wheel? Why weren't those included in Elements? And how do we get them there, or at the very least the ones we use?

Thanks!

**Comment by vghero** [comment]
I encounter the same issue after upgrading to mojave and karabiner to karabiner elements. Any chance to get those prepared settings back?

**Comment by vghero** [comment]
For those  who have the same question: karabiner now requires to import the needed mappings from the web using "Complex Modifications/Add Rule/Import more rules from the internet". Then click import for the desired mappings. Done!

**Comment by vghero** [comment]
If you click on "Import more rules from the internet" as described earlier, you will be directed to this url: https://pqrs.org/osx/karabiner/complex_modifications/ where the available mappings are shown.

I'm also still lacking some functionality. There are some e.g. "for PC users" mappings, but the old version provided more, or more out-of-the-box-working, mappings as it feels.
