### ISSUE TITLE
Can the program be hidden from Cmd+Tab bar

### ISSUE THREAD

**Issue by kim0** [tekezo/Karabiner-Elements#160]
KE is working great for me on Sierra .. I wrote the json config file, and it is working well. My only problem, is that I don't want to see "KEY" icon on CMD+TAB .. is it possible to hide it ?

**Comment by talha131** [comment]
@kim0 That's strange. I am on 0.90.40 and OS X 10.12.1 Beta (16B2327e).

I can close KE window easily. It keeps working in the background. After I close the window, I do not see it in the application switcher list (⌘Command+⇥Tab).

If you want to hide it when you login to your computer, make sure you checkbox is selected in the System Preferences->Users & Groups.

<img width="431" alt="screen shot 2016-09-27 at 00 16 23" src="https://cloud.githubusercontent.com/assets/1094724/18848430/c5589502-8447-11e6-815a-fca57b4a74bc.png">

**Comment by kim0** [comment]
Thanks!

**Comment by sammarcus** [comment]
I think this would be useful to add to the readme, especially since the app cannot be quit using normal conventions from the menubar.
