### ISSUE TITLE
Profile switch shortcut

### ISSUE THREAD

**Issue by sypl** [tekezo/Karabiner-Elements#1600]
There does not appear to be a way to switch profiles via a shortcut. I know you can via the CLI, but I think it's necessary to be able to do this via shortcut. 

I always keep a 'default' profile that is unmodified in case I mess up current profile, but I had the situation whereby I stepped away from the computer and was left on the lock screen on a half-finished custom profile that lacked the keys to enter my password. Having a CLI command to switch does me no good at all in that situation.

**Comment by sypl** [comment]
I realise `shell_command` can be used for this: https://github.com/tekezo/Karabiner-Elements/issues/1029#issuecomment-338321585

**Comment by ldiunyh** [comment]
Hi Some experts here please tell me how to do it from scratch, i know nothing about coding. Or can you just please tell me what to learn in order to understand how to do it? Thanks!

**Comment by aesyondu** [comment]
When searching for `profile shortcut` in github issues, this is the first relevant issue that appears. I'd like to point out that this related issue exists and will help solve the problem problem:

Changing Profiles with shortcut https://github.com/pqrs-org/Karabiner-Elements/issues/1029

**Comment by MuhammedZakir** [comment]
@ldiunyh : Please open a seperate issue describing what you want to do and what exactly you don't understand.
