### ISSUE TITLE
Make use of f keys profile dependent

### ISSUE THREAD

**Issue by Jendker** [tekezo/Karabiner-Elements#1601]
Would it be possible to define the option to use F1, F2 etc. instead of the default function keys assigned to the profile, not as a global setting?

**Comment by Jendker** [comment]
Is this really not implemented? Seems like a basic functionality to me.

**Comment by brandondrew** [comment]
please share your modification!

**Comment by Jendker** [comment]
It was just merged to the master :) https://github.com/pqrs-org/KE-complex_modifications/pull/449

I was modifying the F buttons manually in the settings, like presented on the screenshot and then I applied the mentioned complex modification to switch F key buttons just for specific profile. I will try to do all that with just complex modification, but it may be impossible due to the modifier priorities. I will update the info here after having a closer look.
![bildschirmfoto 2018-10-30 um 09 01 03](https://user-images.githubusercontent.com/14967831/47704092-c4968e00-dc22-11e8-9f43-0b5620faa41c.png)

**Comment by zsiegel92** [comment]
I think this should be re-opened. The profiles should control behavior of function keys!

**Comment by younishd** [comment]
Totally agree! I don't see why this one setting should not be profile-dependent. It seems to defeat the purpose of the tool in this regard since setting this at a global level is already supported natively in macOS settings.

**Comment by rudironsonijr** [comment]
Any update on this feature?
