### ISSUE TITLE
Workaround for CJKV input sources switching issue

### ISSUE THREAD

**Issue by gxfxyz** [tekezo/Karabiner-Elements#1602]
As you know, the `TISSelectInputSource` input source switching API still has the bug that sometimes it will fail to switch some CJKV (Chinese, Japanese, Korean, Vietnamese) input sources (only menubar icon changed).

![screen shot 2018-10-13 at 15 24 37](https://user-images.githubusercontent.com/43481676/46910763-38d0f200-ceff-11e8-8ee5-cff76dddfa69.png)

[Kawa](https://github.com/utatti/kawa) has implemented [a workaround](https://github.com/utatti/kawa/pull/12) to solve this issue:
- Select a target input source
- If the source is CJKV
    - Switch to the first non-CJKV input source
    - Return to the target input source by sending `Select the previous input source` shortcut

I've tested Kawa, and it works great without the issue. 

Could you consider adapt this workaround to Karabiner-Elements? It would be really helpful to many CJKV users.

Thank you so much for your awesome project!

#### Related issues:

- https://github.com/tekezo/Karabiner-Elements/issues/1110
- https://github.com/tekezo/Karabiner-Elements/issues/1255
- https://github.com/tekezo/Karabiner-Elements/issues/1374

#### References:

- https://github.com/tekezo/Karabiner/issues/308#issuecomment-190693550
- https://github.com/utatti/kawa/issues/11
- https://github.com/utatti/kawa/pull/12
- https://github.com/noraesae/kawa/blob/master/kawa/InputSourceManager.swift#L60

**Comment by oklahomer** [comment]
I'm experiencing the same issue.
The good old `Cmd + Space` works good, but my Mac sometimes fails to do so when I try to switch input source with a customized shortcut I defined with Karabiner Elements. My setting goes like below:

```
                    {
                        "description": "Use left or right command key to select input source",
                        "manipulators": [
                            {
                                "from": {
                                    "key_code": "left_command",
                                    "modifiers": {
                                        "optional": [
                                            "any"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "left_command"
                                    }
                                ],
                                "to_if_alone": [
                                    {
                                        "select_input_source": {
                                            "input_source_id": "^com\\.apple\\.keylayout\\.US$"
                                        }
                                    }
                                ],
                                "type": "basic"
                            },
                            {
                                "from": {
                                    "key_code": "right_command",
                                    "modifiers": {
                                        "optional": [
                                            "any"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "right_command"
                                    }
                                ],
                                "to_if_alone": [
                                    {
                                        "select_input_source": {
                                            "input_source_id": "^com\\.google\\.inputmethod\\.Japanese\\.base$"
                                        }
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    },
```

Switching from `ja` to `en` always works; while `en` to `ja` sometimes fails even though the indicator on menubar and the variables on Karabiner ElementViewer indicate the input source is successfully switched. This behavior looks pretty much similar to the one described in https://github.com/tekezo/Karabiner/issues/308#issuecomment-190693550 as mentioned by @gxfxyz. Karabiner Elements is my favorite so it would be nice if this is somehow fixed or a workaround is found.

**Comment by gxfxyz** [comment]
Hi @oklahomer, I don't think this issue will be fixed in the near future as it's a long-existing macOS bug and [Kawa's workaround](https://github.com/utatti/kawa/pull/12) is not fully reliable.

I have similar need as you to use command keys for switching between input sources. My current workaround is:

1. Bind `F18` to "Select the previous input source" in System Preferences/Keyboard/Shortcuts/Input Sources.

![screen shot 2018-12-21 at 15 08 42](https://user-images.githubusercontent.com/43481676/50367062-5095a980-0532-11e9-8fc6-80775b8c61b9.png)

2. Let Karabiner-Elements use `F18` to change input source based on conditions:

```json
{
    "description": "Tap Command_L (⌘) → switch input source to English (F18)",
    "manipulators": [
        {
            "conditions": [
                {
                    "input_sources": [
                        {
                            "language": "en"
                        }
                    ],
                    "type": "input_source_unless"
                }
            ],
            "from": {
                "key_code": "left_command",
                "modifiers": {
                    "optional": [
                        "caps_lock"
                    ]
                }
            },
            "to": [
                {
                    "key_code": "left_command",
                    "lazy": true
                }
            ],
            "to_if_alone": [
                {
                    "key_code": "f18"
                }
            ],
            "to_if_held_down": [
                {
                    "key_code": "left_command"
                }
            ],
            "type": "basic"
        }
    ]
},
{
    "description": "Tap Command_R (⌘) → switch input source to Chinese (F18)",
    "manipulators": [
        {
            "conditions": [
                {
                    "input_sources": [
                        {
                            "language": "zh-Hans"
                        }
                    ],
                    "type": "input_source_unless"
                }
            ],
            "from": {
                "key_code": "right_command",
                "modifiers": {
                    "optional": [
                        "caps_lock"
                    ]
                }
            },
            "to": [
                {
                    "key_code": "right_command",
                    "lazy": true
                }
            ],
            "to_if_alone": [
                {
                    "key_code": "f18"
                }
            ],
            "to_if_held_down": [
                {
                    "key_code": "right_command"
                }
            ],
            "type": "basic"
        }
    ]
},
```

It only works if you only use two input sources. Despite that, this workaround is quite reliable as I've been using it for a while. Hope this may help.

**Comment by laishulu** [comment]
emacs-mac don't have such a problem

https://bitbucket.org/mituharu/emacs-mac/src/26c8fd9920db9d34ae8f78bceaec714230824dac/src/macfns.c?at=master#macfns.c

**Comment by tekezo** [comment]
Karabiner-Elements and emacs use `TISSelectInputSource` API which is the only API we can switch input source.
The `TISSelectInputSource` works properly for text area of the own app, but it does not for another process text area.
Emacs's `mac-select-input-source` does not face this problem because of such API behavior.

**Comment by YOnoda** [comment]
Anyone knows any workaround for more than two input source, in particular switching between CJKV? @gxfxyz ‘s solution works only when you use two.

**Comment by rudders2013** [comment]
> Anyone knows any workaround for more than two input source, in particular switching between CJKV? @gxfxyz ‘s solution works only when you use two.

I also met this problem last night. Luckily I find a simple solution today. 
see here: https://github.com/rudders2013/rudders2013.github.io/blob/main/A%20simple%20solution%20to%20solve%20the%20%22CJK%20input%20method%20switching%22%20problem%20in%20Karabiner

Sample above shows switching between 4 input methods(简体中文双拼/简体中文五笔/繁体中文双拼/英文切换.)

**Comment by rudders2013** [comment]
It seems just a "refresh" problem. I find a simple refreshing solution by so called "Chinese/English Switch" printed in my CapsLock Key after switching input method.

**Comment by rudders2013** [comment]
I'm not sure if the other versions of macbook have this switching feature.
<img width="664" alt="image" src="https://user-images.githubusercontent.com/4927737/171094683-be27801b-fc0c-4476-b933-6171e78119aa.png">
<img width="895" alt="image" src="https://user-images.githubusercontent.com/4927737/171095661-1e134873-4955-4f36-bc24-94348929459b.png">

Here is the detail info of mine(publish in Mainland China):
<img width="580" alt="image" src="https://user-images.githubusercontent.com/4927737/171095149-f198b389-fd4f-4868-a8dd-4d2655632668.png">

Karabiner version:
<img width="191" alt="image" src="https://user-images.githubusercontent.com/4927737/171095239-ee5f6a81-e333-4a6a-82ef-cdbac7b4e356.png">





A shake will happen in the input method icon when switching.

**Comment by epegzz** [comment]
I found a solution that works for me:

1. select your CJKV input source
2. call `Select the previous input source` via shortcut
3. post `vk_none` for 30ms

I'm using `F18` as `Select the previous input source` shortcut.

The `Select the previous input source` step does not make any sense, since we already selected the correct input source. But exactly this step is what makes it work reliably for me. 

Hope this helps! 😊

```
{
  "select_input_source": {
    "input_source_id": "^com.apple.inputmethod.VietnameseIM.VietnameseTelex$"
  }
},
{
    "key_code": "f18",
    "modifiers": []
},
{
    "hold_down_milliseconds": 30,
    "key_code": "vk_none"
}
```

**Comment by gfZeng** [comment]
I found this issue in 2017, the issue will gone if we kill the process TextInputSwitcher.
In the early version of MacOS, we can delete the APP file. but not permitted on current MacOS.
we can do this:
```sh
sudo launchctl disable gui/`EUID`/com.apple.TextInputSwitcher
sudo pkill -9 TextInputSwitcher
```

**Comment by ZYinMD** [comment]
Guys, I've found 2 perfect solutions.

### goal:
Let's say my personal goal is: 
(ajust to your own preference):
- `cmd` `j` to change to English
- `cmd` `h` to change to Chinese
- `ctrl` `space` to "switch to previous input source" (macOS default hotkey)

-----
**Solution 1:** Use condition `input_source_if` and `input_source_unless` to determine if current input source is English, switch only conditionally.
```json
{
  "description": "directly set input source with cmd-j and cmd-h",
  "manipulators": [
    {
      "type": "basic",
      "description": "cmd-j to switch to English, unless already in English",
      "conditions": [
        {
          "input_sources": [{ "language": "en" }],
          "type": "input_source_unless"
        }
      ],
      "from": {
        "key_code": "j",
        "modifiers": {
          "mandatory": ["command"]
        }
      },
      "to": [
        {
          "key_code": "spacebar",
          "modifiers": ["left_control"]
        }
      ]
    },
    {
      "type": "basic",
      "description": "cmd-h to switch to Chinese, if currently in English",
      "conditions": [
        {
          "input_sources": [{ "language": "en" }],
          "type": "input_source_if"
        }
      ],
      "from": {
        "key_code": "h",
        "modifiers": { "mandatory": ["command"] }
      },
      "to": [
        {
          "key_code": "spacebar",
          "modifiers": ["left_control"]
        }
      ]
    }
  ]
}

```

----
**Solution 2**: use `macism` from [this repo](https://github.com/laishulu/macism)

Follow instructions in readme to install:
```
brew tap laishulu/macism
brew install macism
```
Then call this tool to make the switch:
```
{
  "description": "directly set input source with cmd-j and cmd-h",
  "manipulators": [
    {
      "type": "basic",
      "from": {
        "key_code": "j",
        "modifiers": { "mandatory": ["command"] }
      },
      "to": [
        {
          "shell_command": "/opt/homebrew/bin/macism com.apple.keylayout.US"
        }
      ]
    },
    {
      "type": "basic",
      "from": {
        "key_code": "h",
        "modifiers": { "mandatory": ["command"] }
      },
      "to": [
        {
          "shell_command": "/opt/homebrew/bin/macism com.apple.inputmethod.SCIM.Shuangpin",
          "description": "this is my preferred Chinese IME, likely different from yours, you should type `macism` in terminal to see yours"
        }
      ]
    }
  ]
}

```

**Comment by mjaymeyer** [comment]
Just wanted to post another option specific to folks who have keyboards that allow macros. You can set the switch to language key in karabiner elements (e.g., command-shift-J for Japanese) and then assign a key to a macro that does Command-Shift-J, delays for 100 ms, hits Caps Lock, delays 100 ms again, then Caps Lock again. This should swap from the CJKV language back to English and then back again. The switch back should allow you to actually type in the language you selected. Still dumb that Mac hasn't fixed this but it has worked quite well for me. Still much better than Window's great decision to not allow you to remove 'Direct Input' as an option in the Japanese keyboard (if you know you know).

**Comment by xieming-databricks** [comment]
After upgrading to Tahoe, the `macism` based approach is the most reliable one from me.
