### ISSUE TITLE
Ignored device (Magic Mouse greyed out in Prefs>Devices)

### ISSUE THREAD

**Issue by tobyspark** [tekezo/Karabiner-Elements#1605]
I cannot enable my Apple Magic Mouse as a device in Karabiner Preferences > Devices. In the log, it says 

```[info] [grabber] <mouse name> (device_id:6) is ignored.```

I can't find any tractable info searching online, so I'm kinda stuck.

macOS version: 10.14
Karabiner version: 12.1.0
Your Mac hardware: MacBook Pro (15-inch, 2017)
Your keyboard hardware: Apple Magic Mouse

**Comment by JimCox-LogicDesignService** [comment]
Same problem here.  Both my Apple Trackpad and Apple Mouse are ignored with no way to change it.

From the log:  

```
[2018-11-07 09:27:24.784] [info] [console_user_server] core_configuration is updated.
[2018-11-07 09:27:24.785] [info] [grabber] #### Trackpad (device_id:2) is ignored.
[2018-11-07 09:27:24.785] [info] [grabber] #### Mouse (device_id:1) is ignored.
[2018-11-07 09:27:24.890] [info] [grabber] Apple Keyboard (device_id:3) is grabbed
```

![banners and alerts](https://user-images.githubusercontent.com/5649755/48142275-1ddd6d80-e272-11e8-97e1-ea1b7e1682be.jpg)


This prevents me from changing the useless Ctrl+LMB to just LMB (Left Mouse Button)

**Comment by denis-kosovich** [comment]
Same issue here... Any news?

**Comment by LakMoore** [comment]
I see no-one has complained of this in over a year, but I have this problem today with v12.5.0.  Anyone know what I can try to fix it?

**Comment by tobyspark** [comment]
I gave up. I suspect most people attracted to Karabiner's customisations are also attracted to custom peripherals.

**Comment by LakMoore** [comment]
I have also given up, but a solution would be used if someone clever comes along with one!

**Comment by hamidshafer** [comment]
Same problem here. Please re-open this issue.

**Comment by kiwibrew** [comment]
Hate to say it, but "me too". The only reason I need Karabiner is to get a middle mouse click from my Magic Mouse. 
<img width="1112" alt="Screenshot 2020-05-16 20 28 46" src="https://user-images.githubusercontent.com/3412790/82119798-e9763600-97b3-11ea-99ca-c05a2c5ef1d1.png">

**Comment by jonasdiemer** [comment]
Same issue here on 2019 MBP 13"

**Comment by tekezo** [comment]
Apple's pointing devices send events in a different way than HID devices, so Karabiner-Elements can't change events.
So, these devices are grayed out on GUI.

**Comment by remotecom** [comment]
I got a Macbook for work and finally decided to get a trackpad with it, then I find this issue...

I'll be returning it.

**Comment by lukigarazus** [comment]
This issue can be fixed on MacBooks by disabling the built-in keyboard when another one is connected. Worked great for my Logitech Ergo.
