### ISSUE TITLE
CapsLock Led does not work

### ISSUE THREAD

**Issue by przemekgithub** [tekezo/Karabiner-Elements#1606]
Mac OS Mojave, Karabiner-Elements 12.1.0
CapsLock Led stopped working on Apple Internal Keyboard. Capslock works fine.
It is MacBook Pro 2016. I am not sure when it stopped working, but probably after Mojave update,.
I tried to disable "manipulate led" but it didnt helped, disabling keyboard on Karabiner or shutting down karabiner helps.
I have no modifications for Caps Lock.

**Comment by przemekgithub** [comment]
It worked fine on High Sierra for sure on my laptop. 
I am not sure if it stopped on beta or on release version.

**Comment by rreese** [comment]
Works fine on my old work laptop running High Sierra 10.13.6.  I was issued a new laptop with Mojave 10.14 earlier this week.  Installed Karabiner Elements 12.1.0 on the new laptop, applied the same preference settings and caps lock does not work on the new laptop.

**Comment by Eisermann** [comment]
duplicate of https://github.com/tekezo/Karabiner-Elements/issues/1502

**Comment by przemekgithub** [comment]
Confirm, it is duplicate, I didnt found #1502 before.
Newest beta works great, it is now solved (12.1.51)
