### ISSUE TITLE
Can the Trackpad be used for Mouse Clicking Changes?

### ISSUE THREAD

**Issue by bnc2123** [tekezo/Karabiner-Elements#1607]
Originally, i was trying to solve a JSON in the complex modifications repository [here](https://github.com/pqrs-org/KE-complex_modifications/issues/444). I couldn't figure out why my JSON wasnt working but I believe I figured out the issue, and i decided to re-post it here as its probably a better fit. Turns out, my JOSN was correct, it just wasnt working on the trackpad. I plugged in a mouse and the JSON was taking effect, but it wasnt doing it on my trackpad.

So with that said, is there a setting i can change to allow me to use the trackpad in conjunction with Karabiner-Elements? Or is this just not doable?  You used to be able to do it on Karabiner, so i have no idea how to solve my issue if not. I tried using BetterTouchTool for it but i couldn't get it to work, so im really hoping there is a way around this. The change I'm trying to make is for Command+Option+left_click to become Option+middle_click in a specific program

**Comment by clemsam** [comment]
You may have noticed that Karabiner Elements warns against changing "button1" and does NOT offer a "from"-swap of it in "Simple Modifications", just a "to"-swap.

I tried from pure curiosity to exchange such a swap in the "Simple Mod" department of Karabiner.json, but this returned an [error]. Swap from button2 to button1 _works_.

Quite simply: _Karabiner Elements does not **allow** button1 to be "swapped away" …_

**Comment by bnc2123** [comment]
that sucks, ill just have to change it so it does it without the left click.  That will be a little weird, but better than nothing. Thanks for confirming this for me

**Comment by clemsam** [comment]
Well, sorry for that. I think a new version of Karabiner is being developed – maybe that one will be more "tolerant"  … good luck!
