### ISSUE TITLE
Feature request: Auto detect device and switch between profiles 

### ISSUE THREAD

**Issue by nTamura** [tekezo/Karabiner-Elements#1608]
I use two keyboards with different profiles daily. Can we get an option to auto detect which keyboard has been plugged in and switch to the profile automatically?

**Comment by clemsam** [comment]
There actually IS a differentiation possible. look at [Karabiner-Documents](https://pqrs.org/osx/karabiner/json.html):

    "manipulators": [
       { "conditions": [
            {"type": "device_if",
             "identifiers": [
                 {"vendor_id": 1111,
                   "product_id": 2222,
                   "description": "my keyboard 1"  },
        "from": { … WHATEVER KEYS …},
        "to":   [ { … WHATEVER REMAPS …} ]
        },
       {   { … LIKE ABOVE …
                 {"vendor_id": 333,
                   "product_id": 444,
                   "description": "my keyboard 2"  }
        "from": { … LIKE ABOVE …
        }
In _my opinion_ editing `~/.config/karabiner/karabiner.json` is no more difficult than editing private.xml.

**Comment by dirtytao** [comment]
You can see this example to enable device rule：
https://github.com/pqrs-org/KE-complex_modifications/blob/master/docs/json/example_device.json

**Comment by AAverin** [comment]
I find it still quite confusing.
Would it be possible to either have a nicer feature in the UI or maybe at least a documentation page, explaining how to set up auto-detection to switch between profiles?
I now have 4 profiles, 3 of them should depend on which device is now connected and the 4th is a default fallback when no external keyboards are connected. It would be great to have them work automatically
