### ISSUE TITLE
K-E Doesen't "hold" settings, disable internal keyboard doesn't work. SOLVED

### ISSUE THREAD

**Issue by andersbaero** [tekezo/Karabiner-Elements#1609]
I'm extremely attached to my mechanical keyboard, so I'm looking for a solution to disable the internal keyboard so I can use my external one.

Everbody says "use Karabiner-Elements, so easy", but I've had no luck getting it to work.

Whenever I set the internal keyboard to disable if xx device is connected, it does not do anything. No changes. The only thing it does on launch is use the virtual karabiner elements layout for input sources.

And when I reload Karabiner-Elements, the setting to disable internal keyboard is somehow removed, aka its unchecked. 

Any ideas? 

macOS version: macOS 10.14 Mojave
Karabiner version: Karabiner-Elements 12.1.0
Your Mac hardware: MacBook Pro 2012 (A1398) 15'' Retina with an i7 2.3ghz
Your keyboard hardware: HHKB

**Comment by andersbaero** [comment]
I don't know if I should feel really stupid now or not, but no, I didn't. I tried doing that and it now works flawlessly.

Why does that fix things? Before I did that all three keyboards(Internal, External, Virtual) showed up under my "keyboards" when going to Sys-pref->Keyboard->Modifier Keys ??

It works now, so thank you very much! Even though I don't understand why it wouldn't work in the first place.

**Comment by clemsam** [comment]
@andersbaero
Let's hope it will stay this way …  
sometimes I get two independent things wrong, then change one of them (= no effect), redo it, change the other (= no effect) and so on.
Good luck to you, I learned a lot from mistakes myself.

**Comment by zjwbupt** [comment]
I meet the same problem. DIsable Build-in Keyboard just remain unchecked. How did you solved it? Thanks
