### ISSUE TITLE
BT Keyboard w/ Trackpad Stopped Working after v0.90.40 

### ISSUE THREAD

**Issue by airend** [tekezo/Karabiner-Elements#161]
I have a Motorola Keyboard KZ500 that I've been using with this JSON:
```
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "application": "left_command"
            }
        }
    ]
}
```
After the v0.90.40->v0.90.42 update today, this configuration is ignored, even though EventViewer shows the same keycodes.

**Comment by airend** [comment]
I guess this works until a proper solution: https://github.com/airend/Karabiner-Elements/commit/9f72d47f4354007344833a28ad5d04f9b8739323.

**Comment by tekezo** [comment]
I believe this issue is fixed at v0.90.45.
Please confirm the latest beta version.

**Comment by airend** [comment]
Thank you, it is indeed fixed.

**Comment by airend** [comment]
Thank you, it is indeed fixed.
