### ISSUE TITLE
Mojave, karabiner survives a log off, but not a reboot.

### ISSUE THREAD

**Issue by antanisblinda** [tekezo/Karabiner-Elements#1612]
Hi. I'm using the latest karabiner 12.1.0, on latest mojave 10.14. 
I’m using a profile that disables the A button (vk_none) and that
replaces caps_lock with A (A button is stuck on my mid-2012 Air).
I installed the “current config” in system default config (multiple
times, including remove & reinstall).
In MacOS karabiner works beautifully. If I log out, at the login
prompt it works good too.

However, after a reboot or shutdown, karabiner is not working/loaded
at login prompt.

Any idea how to fix? 
thank you

**Comment by clemsam** [comment]
In Karabiner Elements' tab "Misc" there is an option
`[Copy the current configuration to the system default configuration]`
I think you _DID_ do this, didn't you?

Only question I have is, did it land in a `~/… folder` or in either `/System/Library/…` or `/Library/…` folder.  
In a `~/…`folder it would only be effective _AFTER_ you log in …

**Comment by clemsam** [comment]
I do not want to start Karabiner Elements before I log in so i won't do this myself.

BUT: your karabiner.json file is in a ~/.config/ folder so it can _NOT_ be effective before you "re-start" – `"~"`meaning: "root/user/Your_IDname/.config/. 
(Once you are started, karabiner settings will remain, even if you log-ou/-in.)

If you actually _CHECKED_ the option `[Copy the current…] ` and still K-E is not recognised that's s.th. different…

**Comment by clemsam** [comment]
Hi, you're welcome.
okay, I found its place:

 ` /Library/Application Support/org.pqrs/config/karabiner.json`
I presume you may even copy your user's karabiner.json there "manually", but of course you will be asked for your password...

**Comment by antanisblinda** [comment]
thank you for the help.
I checked back on the folder you mentioned and I already have a karabiner.json file there. md5 shows the same value for that file and the one in my .config dir. I will try to overwrite anyway and report back!

**Comment by antanisblinda** [comment]
yep, I did try to manually copy above the .json I already had in /Library/Application Support/org.pqrs/config/ , but it has not worked. At login after a reboot, karabiner is not loaded.
