### ISSUE TITLE
Enhancement: EventViewer copy paste with longer history

### ISSUE THREAD

**Issue by rayfoss** [tekezo/Karabiner-Elements#1614]
I'm trying to count how many times I press a certain key in another app, like a game. Problem is the EventViewer has a very short memory, and can't export or allow me to copy either.

This seems like something generally useful and not too difficult

Keep up the good work, I would have switched to linux if it weren't for this thing.

**Comment by yangit** [comment]
Can we bump it?
That would be a really useful feature.

**Comment by rayfoss** [comment]
595627
