### ISSUE TITLE
Feature Request: Exchange Question Mark and Slash

### ISSUE THREAD

**Issue by etnoc** [tekezo/Karabiner-Elements#1616]
Because of a disability, I try to avoid using the shift key. Since I use the question mark far more often than I use the slash, I would love to be able to swap them. The original Karabiner allowed me to do that, but that feature appears to be missing from Karabiner-Elements. Any help would be much appreciated!

**Comment by etnoc** [comment]
I should have mentioned that I am using the latest version of Mojave.

**Comment by brandondrew** [comment]
I would have expected this to be a simple matter of creating an entry under Simple Modifications, but I don't see the question mark in the last of keys available.   But perhaps it can be done with a complex modification.

**Comment by etnoc** [comment]
Yes, I think it used to be under simple modifications in the old Karabiner, but no more. And I can't find it in complex modifications either. I'm hoping that eventually this feature returns or that some industrious person writes a rule for it that can be imported.

**Comment by brandondrew** [comment]
I imagine that (unless there is some strange obstacle to listing the question mark) this is quite possibly an oversight, and might be easy to add in after poking around in the code for a little while.

**Comment by etnoc** [comment]
Is there an online tutorial that teaches one how to create an implement custom rules? I'd love to be able to do this myself, but have never done any coding.

**Comment by limeb** [comment]
Just download ukulele and create a custom keyboard layout.

**Comment by etnoc** [comment]
Thanks--I'll try it!

**Comment by etnoc** [comment]
Tried Ukelele--works great. Thanks, limeb.
