### ISSUE TITLE
per-keyboard profiles

### ISSUE THREAD

**Issue by rustyrazorblade** [tekezo/Karabiner-Elements#162]
It's not clear if it's possible to support different profiles for different keyboards.  For instance, on my Laptop I'd only like to make caps lock act as esc, but on my windows keyboard that I usually hook up I want to also swap command and option keys.  Is this possible?

**Comment by Ghazgkull** [comment]
I think there are a bunch of issues already open for this:

- https://github.com/tekezo/Karabiner-Elements/issues/138
- https://github.com/tekezo/Karabiner-Elements/issues/67
- https://github.com/tekezo/Karabiner-Elements/issues/31

**Comment by rustyrazorblade** [comment]
@Ghazgkull you're right, closing this one
