### ISSUE TITLE
Research simultaneous use (with caps_lock) #Help

### ISSUE THREAD

**Issue by ldexterldesign** [tekezo/Karabiner-Elements#1625]
Hi all,

Hope you're well

Thanks for software

I'm trying to remap some http://spectacleapp.com keyboard shortcuts but unable to get simultaneous events working:

```
{
    "type": "basic",
    "from": {
      "key_code": "caps_lock"
    },
    "to": [
      "simultaneous": [
        {
          "key_code": "left_alt"
        },
        {
          "key_code": "left_gui"
        }
      ]
    ]
  }
```

<img width="1440" alt="screen shot 2018-11-01 at 17 01 21" src="https://user-images.githubusercontent.com/1715809/47863646-0af11600-ddf8-11e8-8188-053c5af7da89.png">

When I press `caps_lock` event viewer is detecting only `left_alt` instead of both `left_alt` and `left_gui` - can anyone tell me where I'm going wrong?

If you have any issues (e.g. questions/queries) happy to help

Hope this is clear and to hear back

Yours faithfully

**Comment by ldexterldesign** [comment]
BUMP

**Comment by clemsam** [comment]
Ahem, if you look into [K-E's reference manual](https://pqrs.org/osx/karabiner/document.html) you'll realise that "simultaneous" is a **`from`**`event` , _NOT_ a **`to`**`event`…

For your code to work try s.th. like:
```
"to": [
      { "key_code": "left_alt",
       "modifiers": ["left_gui"]  }
      ]
```

**Comment by ldexterldesign** [comment]
BUMP

**Comment by ldexterldesign** [comment]
BUMP

**Comment by ldexterldesign** [comment]
BUMP
