### ISSUE TITLE
Karabiner for Redragon keyboard (Windows UK keyboards)

### ISSUE THREAD

**Issue by DanskFantom** [tekezo/Karabiner-Elements#1627]
I've got the Redragon LED gamer keyboard, the Windows UK keyboard version, working with my Mac Pro and Karabiner.  

I've mapped the keys over so the symbols on the keyboard work correctly.  You can do this by swapping the windows and left alt keys physically on the keyboard then using Karabiner to map the windows and option keys to each other.

The other key's that need mapping are:
#, ~, @, ", \, |, ¬, €, ¢, ±

Here is the json code that does that:
`

	{
	  "title": "Use Windows UK keyboard",
	  "rules": [
	 
		{
		  "description": "make TILDE work",
		  "manipulators": [
			{
			  "type": "basic",
			  "from": {
				"key_code": "backslash",
				  "modifiers": {
					"mandatory": [
						"shift"
					]
				  }
			  },
			  "to": [
				{
				  "key_code": "grave_accent_and_tilde",
				  "modifiers": [
					"shift"
				  ]
				}
			  ]
			}
		  ]
		},
  
		{
		  "description": "make @ key work",
		  "manipulators": [
			{
			  "type": "basic",
			  "from": {
				"key_code": "quote",
				  "modifiers": {
					"mandatory": [
						"shift"
					]
				  }
			  },
			  "to": [
				{
				  "key_code": "2",
				  "modifiers": [
					"shift"
				  ]
				}
			  ]
			}
		  ]
		},
  
		{
		  "description": "make SINGLE QUOTE key work",
		  "manipulators": [
			{
			  "type": "basic",
			  "from": {
				"key_code": "2",
				  "modifiers": {
					"mandatory": [
						"shift"
					]
				  }
			  },
			  "to": [
				{
				  "key_code": "quote",
				  "modifiers": [
					"shift"
				  ]
				}
			  ]
			}
		  ]
		},
  
 
		{
		  "description": "make BACKSLASH key work",
		  "manipulators": [
			{
			  "type": "basic",
			  "from": {
				"key_code": "non_us_backslash"
			  },
			  "to": [
				{
				  "key_code": "backslash"
				}
			  ]
			}
		  ]
		},

		{
		  "description": "make VERTICAL SLASH key work",
		  "manipulators": [
			{
			  "type": "basic",
			  "from": {
				"key_code": "non_us_backslash",
				  "modifiers": {
					"mandatory": [
						"shift"
					]
				  }
			  },
			  "to": [
				{
				  "key_code": "backslash",
				  "modifiers": [
					"shift"
				  ]
				}
			  ]
			}
		  ]
		},
  
		{
		  "description": "make ¬ key work",
		  "manipulators": [
			{
			  "type": "basic",
			  "from": {
				"key_code": "grave_accent_and_tilde",
				  "modifiers": {
					"mandatory": [
						"shift"
					]
				  }
			  },
			  "to": [
				{
				  "key_code": "l",
				  "modifiers": [
					"option"
				  ]
				}
			  ]
			}
		  ]
		},
	 
		{
		  "description": "map PLUS MINUS to OPTION quote",
		  "manipulators": [
			{
			  "type": "basic",
			  "from": {
				"key_code": "grave_accent_and_tilde",
				  "modifiers": {
					"mandatory": [
						"option"
					]
				  }
			  },
			  "to": [
				{
				  "key_code": "non_us_backslash",
				  "modifiers": [
					"shift"
				  ]
				}
			  ]
			}
		  ]
		},
	  
		{
		  "description": "make EURO € key work",
		  "manipulators": [
			{
			  "type": "basic",
			  "from": {
				"key_code": "2",
				  "modifiers": {
					"mandatory": [
						"option"
					]
				  }
			  },
			  "to": [
				{
				  "key_code": "4",
				  "modifiers": [
					"option"
				  ]
				}
			  ]
			}
		  ]
		},

  
		{
		  "description": "make CENTS ¢ key work",
		  "manipulators": [
			{
			  "type": "basic",
			  "from": {
				"key_code": "4",
				  "modifiers": {
					"mandatory": [
						"option"
					]
				  }
			  },
			  "to": [
				{
				  "key_code": "2",
				  "modifiers": [
					"option"
				  ]
				}
			  ]
			}
		  ]
		},
	 
	 
		{
		  "description": "make HOME key work - this modifier does NOT work on Redragon keyboard",
		  "manipulators": [
			{
			  "type": "basic",
			  "from": {
				"key_code": "home"
			  },
			  "to": [
				{
				  "key_code": "left_arrow",
				  "modifiers": [
					"fn"
				  ]
				}
			  ]
			}
		  ]
		},
	 
		{
		  "description": "make END key work - this modifier does NOT work on Redragon keyboard",
		  "manipulators": [
			{
			  "type": "basic",
			  "from": {
				"key_code": "end"
			  },
			  "to": [
				{
				  "key_code": "right_arrow",
				  "modifiers": [
					"fn"
				  ]
				}
			  ]
			}
		  ]
		},
	 
		{
		  "description": "Make hash key work",
		  "manipulators": [
			{
			  "type": "basic",
			  "from": {
				"key_code": "backslash"
			  },
			  "to": [
				{
				  "key_code": "3",
				  "modifiers": [
					"option"
				  ]
				}
			  ]
			}
		  ]
		}
	  ]
	}
`

Download the file below, rename it to redragon.json and move it to the folder ~/~/.config/karabiner/assets/complex_modifications.
[redragon.txt](https://github.com/tekezo/Karabiner-Elements/files/2545679/redragon.txt)

Then select add rule from the complex modiications tab in Karabiner and enable the mappings you want from the list.

I can't currently get the home and end buttons to work on the Redragon.  I think that's because function left arrow and function right arrow on that keyboard are used to control the LED functions on the keyboard.   Those mappings may work on other windows keyboards, I've not tried that yet.

**Comment by clemsam** [comment]
[ just a reminder: you must indent your code lines at least 4 spaces "deep" to make them hop into the code frame – I'll delete this once you didi it. ]

**Comment by DanskFantom** [comment]
Thanks clemsam - code frame updated so it displays properly.

**Comment by tonyvsuk** [comment]
Thanks so much for this, saved me a lot of time with my UK keyboard.

One change, to make tilde work, I changed the key code to "non_us_backslash".

And saved the file to .config/karabiner/assets/complex_modifications.

The ` button is still not working for me, but everything else is. Thanks.
