### ISSUE TITLE
Can you pass any variables (or keys-pressed) to a "shell_command": "osascript …" and GET a changed variable back to Karabiner Elements?

### ISSUE THREAD

**Issue by clemsam** [tekezo/Karabiner-Elements#1628]
HI, I've tried for some time to **_use osascript (-applescript) to process variables_** defined via `"set_variable": {"name": "myVar", "value": 1}`.

The best I could achieve is `"osascript ~/.config/karabiner/Some.scpt \"myVar\""` where "myVar" will exclusively be passed to Some.scpt as a string.    
This string can be processed and "returned" via "display dialog (myVar)" – but will never be returned as an actual value of the original "set_variable".    
(Btw: if you run the script in ScriptEditor –replacing "argv" with some "real" string– a value will go to the "Result" part of the split editor window.)     
**Update:**    
tested some more, found **`'\"myVar\": 97'`** is treated in-script as **`"myVar": 97`**.

I've also read about using compiled Automator scripts, used like: `"osascript open Some.app --args myVar"`. I was not able to pass anything at all –no matter how formatted– although Some.app without "--args" _DID run_ …

I at least succeeded in passing a (simulated) combination of modifier + [any key] to a Some.scpt, but only by splitting the modifier to a "key down {command}" with an inserted "delay" and a subsequent "key up {command}" part, which I posted as an answer to [#Issue 1518](https://github.com/tekezo/Karabiner-Elements/issues/1518).

My next idea, to make an osascript "trigger" another karabiner.json "manipulator" via a key combo sent by Some.scpt, did not work, since these osascript "System Events" are not registered by (and do not show in) EventViewer.    
_Maybe THERE is a lead to accomplish a reaction ?!?_

**Comment by clemsam** [comment]
I am still hoping to get some hint & help on how to pass variable _VALUES_ from a karabiner.json file to an `osa(appple)script` and –processed– back into the json file.

But in between I tinkered a little and wrote me a little helper script that in this form:    
`"shell_command": "osascript ~/.config/karabiner/Karab_vars.app '47, 11, userName'"` finds a variable with value "47" and replaces this value with "11".    
`karabiner.json` lies within `/Users/[yourName]/.config/karabiner` folder, so my helper _needs MY(your) name_ as input  …

… as this AS helper _writes **directly** into any user's personal json file._ Since Karabiner Elements "watches" this file continuously, any value is read (and effective) at once.

(Is anybody interested in this? Just an AppleScript that (re)writes to a file.)

**Comment by Richie765** [comment]
@clemsam, I'm struggling with a problem maybe you can help me with. I don't understand how I could set a variable to a value by changing karabiner.json, because as far as I can tell, that file will only set variables when certain keys are triggered.

I'm looking for a way to set a variable from outside of Karabiner so I can enable/disable a group of macros based on some external circumstance.

Do you think your solution can work for that or do you know another way of doing that?

**Comment by MichaelC001** [comment]
> I am still hoping to get some hint & help on how to pass variable _VALUES_ from a karabiner.json file to an `osa(apple)script` and –_processed_– back into the json file.
> 
> But in between I tinkered a little and wrote me a little helper script that in this form: `"shell_command": "osascript ~/.config/karabiner/Karab_vars.app '47, 11, userName'"` finds a variable with value "47" and replaces this value with "11". (Of course you can pass _**whatever values**_ you want in the form of `'xx, yy, abcdefgh'.)
> 
> `karabiner.json` lies within `/Users/[yourName]/.config/karabiner` folder, so my helper _needs MY(your) name_ as input …
> 
> … as this AS helper _writes **directly** into a user's personal json file._ Since Karabiner Elements "watches" this file continuously, any value is read (and effective) at once.
> 
> (Is anybody interested in this? Just an AppleScript that (re)writes to a file.)

With this script, do you get what you want? I am very interested in it.
