### ISSUE TITLE
[Mojave] Modifying caps_lock to escape, control key not working in Mojave

### ISSUE THREAD

**Issue by pscofield** [tekezo/Karabiner-Elements#1629]
Based on [this comment](https://github.com/tekezo/Karabiner-Elements/issues/8#issuecomment-309037790) I've set my `~/.config/karabiner/karabiner.json` file to have the following value. This configuration was working fine until today when I upgraded to MacOS Mojave from High Sierra. Do I need to make any updates here?

```
"rules": [
    {
        "manipulators": [
            {
                "description": "Change caps_lock to control when used as modifier, escape when used alone",
                "from": {
                    "key_code": "caps_lock",
                    "modifiers": {
                        "optional": [
                            "any"
                        ]
                    }
                },
                "to": [
                    {
                        "key_code": "left_control"
                    }
                ],
                "to_if_alone": [
                    {
                        "key_code": "escape"
                    }
                ],
                "type": "basic"
            }
        ]
    }
]
```

([link to complete file configuration](https://pastebin.com/gvc6HyKP))

I'm using the latest Karabiner version, and have restarted Karabiner a few times. The logs indicate that it's looking at the right json file, and I also see the rule appearing in "Karabiner-Elements Preferences".

**Comment by malloryerik** [comment]
Sam issue here, but I'd rather stay with Karabiner. Anyone have a suggestion? This is a perfect modification for vim bindings.

**Comment by jmgarnier** [comment]
It's built in now. Go to preferences and:
![image](https://user-images.githubusercontent.com/8051/48934008-a448af00-ef02-11e8-8c6c-99ccca13ba6d.png)

**Comment by pscofield** [comment]
Resolved by [malloryerik's comment](https://github.com/tekezo/Karabiner-Elements/issues/1629#issuecomment-439275444) above.
