### ISSUE TITLE
Logitech Harmony Hub not remapping (Vendor ID / Product ID are zero)

### ISSUE THREAD

**Issue by generator85** [tekezo/Karabiner-Elements#163]
Commands received from the Logitech Harmony Hub are not being remapped while the exact same commands from my keyboard are working. This was a problem before with Karabiner that could be fixed by enabling ""Allow devices which Vendor ID and Product ID are zero."

Is this something that can be enabled with Karabiner Elements?

**Comment by zhexuany** [comment]
@generator85 Have you figured anything yet?

**Comment by generator85** [comment]
I've downgraded to El Capitan due to other issues, so I'm using regular Karabiner again.

**Comment by wongjustin99** [comment]
This would be useful for remapping bluetooth keyboards with broken enter keys. 

I'm stuck in this, was able to pair with old Karabiner using this feature -- trying to find if it's available in Karabiner-Elements.

**Comment by Voleking** [comment]
Maybe your cant use "location_id" to specify device.
