### ISSUE TITLE
Karabiner 12.1.55 Beta Caps Lock LED Issues

### ISSUE THREAD

**Issue by TM1698** [tekezo/Karabiner-Elements#1630]
Ever since my Mac updated to Mojave, my Caps Lock LED stopped working altogether. I quickly figured out this was a problem to do with Karabiner, as quitting the program immediately fixed the problem and my LED lit up like normal. Unfortunately, I need Karabiner so I had to turn it back on and live without my Caps Lock indicator for a while. I decided to check out Karabiner's beta and see if it had a fix and lo and behold, the first thing in the update notes was that it fixed my exact problem. It does too, kind of, my Caps Lock LED is back in action. Unfortunately it's still buggy, and the caps lock light flicks on momentarily whenever I perform specific actions (like clicking on an address bar or opening a new application). I thought I could live with this, at least until it was fixed, but I absolutely can't. So I went into the settings and turned the LED off completely, because I knew I could stand that. Only now turning off the LED means that it's on all of the time. Doesn't flicker, but never turns off either. Incredibly annoying.

I know this is obviously a beta issue, but if anybody knows a quick fix that would be helpful. At the very least, hopefully the developers find this.

**Comment by Splaktar** [comment]
This just got fixed in `12.2.0`. Thank you!
