### ISSUE TITLE
Right command to right option stopped working 10.14.1

### ISSUE THREAD

**Issue by rafalivanoff** [tekezo/Karabiner-Elements#1632]
Above swap stopped working after update from 10.14 to 10.14.1
MBP 2018, 15"
Keys are working like w/o any modification.

**Comment by cpbotha** [comment]
My Karabiner Elements 12.1 dvorak mapping stopped working (!!!) with 10.14 to 10.14.1 upgrade.

I re-installed from a freshly downloaded 12.1 PKG, and everything is back to normal.

See if a reinstall helps in your case?

**Comment by rafalivanoff** [comment]
cpbotha, thanks A LOT! It helped!

**Comment by longthanhtran** [comment]
don't know why but your advice @cpbotha works. Thanks

**Comment by shadok123** [comment]
Yo, i have similar problem with command and option modifications .
So on what version it will be working fine?
I have Mojave

**Comment by mdawaffe** [comment]
My Simple Modifications stopped working for me after installing the latest security update (https://support.apple.com/en-us/HT209193) for MacOS High Sierra 10.13.6. It looks like it's the same update that went out for Mojave 10.4.1.

I was then (and am now) running Karabiner Elements 12.1.0.

This is what got everything working for me again:
1. Copy `~/.config/karabiner/karabiner.json` somewhere safe.
2. Uninstall Karabiner Elements
3. Restart
4. Install Karabiner Elements
5. Copy config back to `~/.config/karabiner/karabiner.json`
6. Open Karabiner Elements -> Misc -> Restart Karabiner Elements

I'm not sure if each of those steps was necessary, but, together, they worked for me.

**Comment by ibc** [comment]
@mdawaffe your steps worked for me without the need of 1. and 5.
