### ISSUE TITLE
Capturing "Caps Lock" key click from the keyboard

### ISSUE THREAD

**Issue by pelonis** [tekezo/Karabiner-Elements#1633]
Hi,

I have an old wireless Logitech keyboard. I am currently using macOS Mojave.

This is my issue. When the "Caps Lock" key is clicked on the keyboard, there is no indication either on the keyboard (with a green light or something) or on the screen.

So I don't know when the "Caps Lock" key clicked. This is very inconvenient when typing passwords because I don't know whether the caps lock is on or off.

Is there any way can I use Karabiner to solve this issue?

Please let me know.

Thank you.

**Comment by shadok123** [comment]
Check this:
Go to preferences -> devices -> and make OFF manipulate LED

**Comment by pelonis** [comment]
> Check this:
> Go to preferences -> devices -> and make OFF manipulate LED

Sorry noob here. This is the preferences of the Karabiner or Mojave?

**Comment by pelonis** [comment]
> Check this:
> Go to preferences -> devices -> and make OFF manipulate LED

I made this change, this stopped the green light on the keyboard of the MacBook Pro. But please note that I am using a wireless Logitech keyboard (external keyboard) to connect to an external monitor. This keyboard does not have any lights in the first place. Any indication must be shown on the screen (for caps lock on and off)

**Comment by shadok123** [comment]
Karabiner, but I don't have any idea when you are using external keyboard.
