### ISSUE TITLE
Lazy modifier and set_variable

### ISSUE THREAD

**Issue by pokey** [tekezo/Karabiner-Elements#1634]
I am trying to put both a `lazy` modifier and `set_variable` within `to`.  Here is the json:

```json
{
    "description": "W+J as shift",
    "from": {
        "simultaneous": [
            {"key_code": "w"},
            {"key_code": "j"}
        ],
        "simultaneous_options": {
            "key_up_when": "all"
        },
        "modifiers": {"optional": ["any"]}
    },
    "to": [
        {
            "key_code": "left_shift",
            "lazy": true
        },
        {
            "set_variable": {
                "name": "custom_shift",
                "value": 1
            }
        }
    ],
    "to_after_key_up": [
        {
            "set_variable": {
                "name": "custom_shift",
                "value": 0
            }
        }
    ],
    "type": "basic"
}
```

When I do this, the `set_variable` seems to work fine, but the `left_shift` functionality stops working.  Is this a bug?

For some context, I am using W+J instead of `shift`, but then I want to change the output of shift-3.  I tried remapping shift-3, but then this doesn't seem to work with W+J, so I was hoping to work around this using a custom variable that is only considered when you press '3'.

**Comment by clemsam** [comment]
(Is your code for pressing "3" in another manipulator that we don't get to see?)

… but generally (from reference):
`When "lazy": true, the modifier works as lazy modifier [and] does not send OWN key events until ANOTHER key is pressed together.`

I don't see ANOTHER key being pressed (in this manipulator) therefore it STAYS "lazy".

**Comment by pokey** [comment]
Thanks @clemsam 

Yes, the code for pressing "3" would be in another manipulator that checks that `custom_shift` is true.  

I'm not sure I understand your response.  When I press and hold W+J, and press another key, the other key should behave as if shift were being held.  That is my understanding of "lazy", and is how it behaves when I don't also have the `set_variable` clause.  But this is not what happens with this manipulator.  Pressing the other key just behaves like shift is not held down

Does that make sense?

**Comment by pokey** [comment]
Fwiw, this is not a blocker for me; I figured out another way forward.  I still believe it is a bug, though, so I left the issue open to track it

**Comment by clemsam** [comment]
Okay: theories are nice but testing really helps.

I confirm your observations and suggest you put the "set_variable" part _IN FRONT_ of your lazy-shift. Thus your code will work (at least: changes variable and "shifts" following "key_codes").

Obviously I can not test the "hidden" press-"3"-part…

**Comment by pokey** [comment]
Nice find.  This strikes me as a bug.  I don't see why this should be sensitive to order

**Comment by clemsam** [comment]
Yeah, I could only guess … but guessing -in hindsight- often finds explanations "plausible" just because they somehow fit in with inexplicable facts.
Anyway, order of manipulators quite often plays a role with problems in Karabiner, so I just "tested".

===========================  

I saw that you're from Palo Alto, isn't that where Apple is (or was?)? You don't happen to work there, do you?
(Sorry: just curious – I'm a boring ex-graphic "artist" -huh!- from Frankfurt, Germany.)
