### ISSUE TITLE
Remove the version number from the kernel extension id

### ISSUE THREAD

**Issue by iandol** [tekezo/Karabiner-Elements#1635]
I have a hard conflict between MATLAB HID support and Karabiner, so I have to unload/reload the deamons and kernel extension (https://github.com/tekezo/Karabiner-Elements/issues/1501).

One small annoyance it the bundle name of the kext including the version number: `org.pqrs.driver.Karabiner.VirtualHIDDevice.v061000` — it means my commands break every time the version number changes and no other kext include version numbers in the bundle id, e.g. ` at.obdev.nke.LittleSnitch` — if you need to know the version, `kextstat` returns that info.

**Comment by iandol** [comment]
This is still an issue...

**Comment by iandol** [comment]
This is still an issue…

**Comment by tekezo** [comment]
Sorry for inconvenience.

There is a reason that I append the version number to the kext.

macOS often fails to unload the kext which related keyboard driver once it used.
When the issue happened, we cannot reload the same kext until the system is rebooted.
So, I append the version number to recognized as another kext to avoid the issue.

I believe the latest Karabiner-Elements does not affect other apps while the device is unselected.
https://pqrs.org/osx/karabiner/document.html#configuration-devices
Do you still need to unload the kext with the latest Karabiner-Elements?

**Comment by iandol** [comment]
Hi, I've just tested, and you are correct, deselecting my keyboard now allows MATLAB HID code to work as expected, that is brilliant thank you!!!

I'll close this, and thank you for such wonderful software!!!!!!

**Comment by iandol** [comment]
I also closed linked issue #1501
