### ISSUE TITLE
Complex modifications and Spotlight / Alfred 

### ISSUE THREAD

**Issue by cbertoldi** [tekezo/Karabiner-Elements#1636]
I have a couple of complex modifications which are active only when the current windows belongs to a specific program. Then, when I open Spotlight or Alfred while using this program the complex modification remains active. Is it possible to correct this behavior, or is it inevitable due to how Spotlight works?

**Comment by cbertoldi** [comment]
@clemsam If Spotlight it's an app of its own, then why do the modifications remain active when I open it?
I try to clarify my example: I have some complex modifications for my IDE. If I open Spotlight, or Alfred for what it's worth, the modifications remains active even for Spotlight.
If I start Spotlight while currently using another program, let's say Firefox, those modifications are not active in the beginning so they obviously do not affect Spotlight as well.

I hope that my use case is understandable now.

**Comment by braham-snyder** [comment]
EventViewer says "Frontmost application" doesn't change when Spotlight is frontmost.

Seems this used to work in the [original Karabiner since 10.5](https://karabiner-elements.pqrs.org/docs/releasenotes/#karabiner-1050). Maybe looking at that release would help to figure out how to fix this for Elements.

**Comment by torarnv** [comment]
This is still an issue. Enter for Cmd+O in Finder results in Spotlight not being able to confirm the choice with Enter if Finder is/was the frontmost app.

**Comment by maliayas** [comment]
See a workaround: https://github.com/pqrs-org/Karabiner-Elements/issues/1982#issuecomment-2395705893
