### ISSUE TITLE
How to map 1 key to simulate holding down multiple keys?

### ISSUE THREAD

**Issue by chrisngn** [tekezo/Karabiner-Elements#1637]
For example, holding down MouseButton4 would simulate holding down Up Arrow and Right Arrow at the same time? Is this possible? 

My current implementation presses the to keys in order. For example, holding down MouseButton4 would press the Up Arrow then release it then holds the Right arrow. Any help?

```
{  
                    "type":"basic",
                    "from":{  
                        "pointing_button":"button4",
                        "modifiers":{  
                            "optional":[  
                                "any"
                            ]
                        }
                    },
                    "to": [
                		{  
                        	"key_code":"up_arrow"
                    	},
                    	{
                    		"key_code":"right_arrow"
                    	}
                    ]
}
```

**Comment by clemsam** [comment]
I don't understand what you want your rule to do: It's logically not possible to "use" two arrow keys at once.
WHAT do you expect to achieve _actually?_

**Comment by iliaskarim** [comment]
I have the same question. For example, I would like the grave_accent_and_tildekey  to simulate a simultaneous shift and grave_accent_and_tilde press. The intended result would be producing a tilde with a single keystroke.

**Comment by chrisngn** [comment]
I want to achieve something like click button4, which sends up_arrow down,
right_arrow down. And it doesn't release until I let go of button4, which
then it sends right_arrow up, up_arrow up.

**Comment by iliaskarim** [comment]
If I may interject again, isn't @chrisngn's idea to have a single key move up-right?

@clemsam thank you for your courteous response. Do you know of a way to set such a complex modification via the Karabiner-Elements GUI? 

[Documentation alludes to making rules](https://pqrs.org/osx/karabiner/document.html#configuration-complex-modifications)
> You can import predefined rules from the internet (or make your own rules).
but the option is not present anywhere, only getting rules from https://pqrs.org/osx/karabiner/complex_modifications/

**Comment by clemsam** [comment]
(I'll answer your 2nd question, as I am not quite clear what exactly the 1st refers to.)

If you want to import a rule via K-E's GUI and _NOT_ get it from the web, you got to write it yourself (easiest: duplicate & change an existing one) and simply put the text file (saved with a .json extension) into your own `[ user name ]  >  .config  >  karabiner  >  assets  >  complex_modifications` folder.

If you then open K-E, open tab "Complex Modifications", click button [+ Add rule], your new rule will be visible somewhere in the scroll area – you just have to select [Enable], it will be copied into your `karabiner  >  karabiner.json` file and be effective immediately.    
If your "rule" does _NOT_ appear in the list – something in the .json file is "broken"…

Here is code that does about what you wish:

    { "title": "Rule to get grave_accent_and_tilde with one keystroke",
      "rules": [
         { "description": "grave_accent_and_tilde with one keystroke",
          "manipulators": [ {
                    "from": { "key_code": "grave_accent_and_tilde" },
                      "to": [
                              { "key_code": "grave_accent_and_tilde",
                                "modifiers": ["left_shift"]  }],
                    "type": "basic"  }
     ]    }    ]    }

Paste this into TextEdit and save as `Any_name_you_want.json` …

**Comment by little-big-h** [comment]
I would like to re-open this ticket as I have the original problem. I am trying to map holding f12 to holding k and l (simultaneously). So, when I press down f12, I would like it to send the press down events for k and l. When I release f12, I would like it to send the release events for k and l. However, this entry:

```
{
                        "description": "f12 to kl",
                        "manipulators": [
                            {
                                "from": {
                                        "key_code": "f12"
                                },
                                "to": [
                                    {
                                        "key_code": "k"

                                    },{
                                        "key_code": "l"
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    }
```

Leads to the sequence k-down, k-up, l-down when I press f12 and l-up when I release it.

**Comment by clemsam** [comment]
Hi little-big-h,
I found a site at https://stackoverflow.com/questions/57343723/how-do-i-simulate-a-key-press-of-fn-shift-command-l-on-a-mac/57361208#57361208 that treats your problem, including MacOs' restrictions.
 The way I use AppleScript in Karabiner is via:   "to": [  {
                                        "shell_command": "osascript -e 'tell application \"System Events\" to tell process \"YourApp\"\n WhatEverScript\n end tell'"
                                    }  ]

**Comment by 8pxl** [comment]
hey @little-big-h how did you end up solving your issue?

**Comment by little-big-h** [comment]
No, frankly, I have moved away from karabiner a bit in favor of BetterTouchTool.
