### ISSUE TITLE
command + F12 is noly post F12 

### ISSUE THREAD

**Issue by CYsuncheng** [tekezo/Karabiner-Elements#1638]
command + F12 is noly post F12  in android studio

**Comment by CYsuncheng** [comment]
option + F7 also not work fine

**Comment by feekApp** [comment]
Have the same issues see issue [#1537](https://github.com/tekezo/Karabiner-Elements/issues/1537)

**Comment by deftomat** [comment]
The same issue for me opt+f12 fires only f12

**Comment by deftomat** [comment]
For me, the solution was to disable build-in Apple keyboard in "devices" tab to avoid modifying events as I only need to modify events from external keyboards.

**Comment by feekApp** [comment]
That's no solution for me. Disable build-in Apple keyboard in "devices" disables all functionality.

**Comment by dbdeveloper** [comment]
Any modifiers with F1..F12 don't work on the internal keyboard when Karabiner-Elements started (MacBook Pro 2018 15"). If it is not possible to fix this issue maybe it is possible to bypass any modifications with F1..F12 "as it is"? E.g. add a checkbox and apply rules to all keys except functional? I understand that it is an ugly hack, but without it, I have to totally disable Karabiner-Elements on the internal keyboard :(

**Comment by feekApp** [comment]
so true.
the current version of Karabiner-Elements has broken my workflow :(

**Comment by feekApp** [comment]
Some additional information. This issue is Touch Bar related. Today I needed to us an external keyboard, and using this keyboard there were no problems using CMD-Fn keys.

Switching back to the intern keyboard, problem also is back :(  

Hope you can fix this.

**Comment by yqmmm** [comment]
I'm bothered by this problem too. So sad that no developer respond to this issue. However, I did find a work-around:

 Just use this modification rule :https://pqrs.org/osx/karabiner/complex_modifications/#fn_plus_numbers_to_function_keys

It will map fn+number to function keys.

Don't have to interact with Touch Bar any more !

**Comment by feekApp** [comment]
:( too soon..... now it's broken again

**Comment by ResolverJay** [comment]
Is it a touch bar problem? Not sure if this would help, but I found this, and it solved my problem.
https://apple.stackexchange.com/a/348210

**Comment by feekApp** [comment]
Yes it is definitely a Touch Bar issue. Unfortunately @ResolverJay your suggestion is not a solution for the issue. When using the settings in [this comment](https://github.com/tekezo/Karabiner-Elements/issues/535#issuecomment-350597725) it works fine for Apps that have set the function keys as F1-F.. but for and als default setting the function keys to the default Touch Bar display. But in that case the cmd-keys are broken again for the other apps (like illustrator).

**Comment by feekApp** [comment]
OK, an other solution, seems to work for me now, in all Apps.

System settings Function keys:
![](https://feek.d.pr/dez4qA.jpg)

Activate Touch Bar in KE:
![](https://feek.d.pr/npXfU8.jpg)

Set Function Keys as default:
![](https://feek.d.pr/abznUN.jpg)

Change for only Touch Bar:
![](https://feek.d.pr/IjZN2X.jpg)

Can someone else confirm this?

== feek

**Comment by medington** [comment]
@feekApp Just enabling the "No product name.." device fixed the problem for me. Thanks!

**Comment by dbdeveloper** [comment]
It seems to me that it works! Thank you!

вт, 2 квіт. 2019 о 08:09 Mark Edington <notifications@github.com> пише:

**Comment by domq** [comment]
[@feekApp](https://github.com/tekezo/Karabiner-Elements/issues/1638#issuecomment-462635444) thanks to you I got both my Compose and my Ctrl+F9 keys back. I think I love you

**Comment by wc222** [comment]
COOL!

**Comment by wc222** [comment]
Only the second figure and the forth figure solve my problem! It's a great discovery that "No product name" is Touch Bar! Thank you.
