### ISSUE TITLE
Adobe creative software issues

### ISSUE THREAD

**Issue by azylka** [tekezo/Karabiner-Elements#164]
Holding the spacebar down and clicking/dragging should allow you to pan around a document in Adobe Creative Suite/Cloud applications.

Shift key just plain refuses to work.

Running Elements-0.90.42.

**Comment by jimmykl** [comment]
Ditto – this is a showstopper!

**Comment by talha131** [comment]
Related to #135

**Comment by Dejorr** [comment]
I have this exact same issue... spacebar (for panning), option dragging (for duplicating) and shift dragging (for constrain) are not working in Adobe CC... and it's killing my workflow. Quitting Karabiner makes them work instantly again. However I need karabiner running for my few but essential remapped keys within Adobe CC.

Not sure if this helps, but these are my adaptations (running Elements v0.90.45) :
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "caps_lock": "return_or_enter",
                "fn": "left_control",
		"left_control": "fn",
                "non_us_backslash": "delete_forward"
            }
        }
    ]
}

I don't know how to code, so this might be a stupid question; but Is there any way to get this working again by adding some lines of code to the code above?

Thanks in advanced for any support someone might be able to give!
