### ISSUE TITLE
Bug with handling mouse clicks and simultaneous modifier keys

### ISSUE THREAD

**Issue by zwegner** [tekezo/Karabiner-Elements#1643]
I believe I've found a bug where a click that occurs within the simultaneous threshold gets handled incorrectly. I have mappings that handle simultaneous shift key presses, and have increased the simultaneous threshold to 500ms. Now if I try to shift click, with the click within 500ms after the shift key down, the mouse down event loses the shift modifier, and the mouse up gets the strange "click_count: 0" data.
![karabiner-screenshot](https://user-images.githubusercontent.com/3751892/48518267-a6d64500-e82e-11e8-9cb3-980c927122db.png)

As background, I tried to remap left/right shift to left/right parentheses when pressed alone. Sometimes I'd try to hit both shifts in succession, but the second key_down would happen before the first key_up, losing both mappings in the process. I made two simultaneous mappings to handle both left-then-right and right-then-left, and increased the simultaneous threshold, since 50ms is too fast to catch this particular case (this is maybe stretching the definition of "simultaneous" further than it was intended, and there's a better way to do this...). The relevant rule from karabiner.json is below.

```
{
    "description": "Change shift to paren if pressed alone",
    "manipulators": [
        {
            "from": {
                "simultaneous": [
                    { "key_code": "left_shift" },
                    { "key_code": "right_shift" }
                ],
                "simultaneous_options": { "key_down_order": "strict" }
            },
            "to": [
                {
                    "key_code": "9",
                    "modifiers": [ "left_shift" ]
                },
                {
                    "key_code": "0",
                    "modifiers": [ "left_shift" ]
                }
            ],
            "type": "basic"
        },
        {
            "from": {
                "simultaneous": [
                    { "key_code": "right_shift" },
                    { "key_code": "left_shift" }
                ],
                "simultaneous_options": { "key_down_order": "strict" }
            },
            "to": [
                {
                    "key_code": "0",
                    "modifiers": [ "left_shift" ]
                },
                {
                    "key_code": "9",
                    "modifiers": [ "left_shift" ]
                }
            ],
            "type": "basic"
        },
        {
            "from": { "key_code": "left_shift" },
            "to": [
                { "key_code": "left_shift" }
            ],
            "to_if_alone": [
                {
                    "key_code": "9",
                    "modifiers": [ "left_shift" ]
                }
            ],
            "type": "basic"
        },
        {
            "from": { "key_code": "right_shift" },
            "to": [
                { "key_code": "right_shift" }
            ],
            "to_if_alone": [
                {
                    "key_code": "0",
                    "modifiers": [ "right_shift" ]
                }
            ],
            "type": "basic"
        }
    ]
}
```

**Comment by clemsam** [comment]
Hi!
I tried to make your json a little bit more readable, below.
Apart from that it seems to me –presuming that a "**_strict_** simultaneous" prohibits any other key!– that your rules **_DO JUST**_ what you told them to do:

1st, manipulator "1" is called by a "left_shift" and waits 500ms for a "strict" 2nd "right_shift".    
**_Therefore_** it registers your mouse click _**but properly (while waiting!) does NOT pass it on**_.    

When after the waiting time manipulator "1" is cancelled the next one in line –no.3: "shift_left" alone– comes to effect. 

Seems quite logical to me, **_NOT a bug …_**
    
    { "description": "Change shift to paren if pressed alone", "manipulators": [

    { "from": { "simultaneous": [ { "key_code": "left_shift" }, { "key_code": "right_shift" } ],         
    "simultaneous_options": { "key_down_order": "strict" } }, 
    "to": [ { "key_code": "9", "modifiers": [ "left_shift" ] }, { "key_code": "0", "modifiers": [ "left_shift" ] } ],     
    "type": "basic" }, 

    { "from": { "simultaneous": [ { "key_code": "right_shift" }, { "key_code": "left_shift" } ], 
    "simultaneous_options": { "key_down_order": "strict" } }, 
    "to": [ { "key_code": "0", "modifiers": [ "left_shift" ] }, { "key_code": "9", "modifiers": [ "left_shift" ] } ], 
    "type": "basic" }, 

    { "from": { "key_code": "left_shift" }, 
    "to": [ { "key_code": "left_shift" } ], 
    "to_if_alone": [ { "key_code": "9", "modifiers": [ "left_shift" ] } ], "type": "basic" }, 

    { "from": { "key_code": "right_shift" }, 
    "to": [ { "key_code": "right_shift" } ], 
    "to_if_alone": [ { "key_code": "0", "modifiers": [ "right_shift" ] } ], "type": "basic" } ] }

**Comment by clemsam** [comment]
You are (partly) right – so I have to change arguments but still try to keep my aim … ;-)

I tried and found in a previous question/answer that any "from"s that include a "button1" element **_are NOT executed_**.    
You may look into the dropdown menus of "Simple Modifications" or try any manipulators of your own:

"button1" **_"from"_**(!) events **_are prohibited._** In the documentation you are repeatedly warned that you should be very cautious

>  "manipulating button1 to avoid losing the left click button."

**Comment by sirdavidoff** [comment]
Just wanted to add to this since this is an issue with an otherwise excellent product that's been niggling at me. 

Correct me if I'm wrong @clemsam, but where is the 'risk of losing the left click button' here? The modification has been canceled by the button click after all. In that case couldn't Karabiner get out of the way and allow the default system behaviour (i.e. passing the modifiers through)?

I rely on Karabiner for a ton of modifications and couldn't imagine my life without it, but find myself in the unhappy situation of having to wait 500ms _every time_ I cmd-click. Since Karabiner is all about productivity improvement that feels like a shame.
