### ISSUE TITLE
adobeCCアプリケーションでの不具合

### ISSUE THREAD

**Issue by kingtosh** [tekezo/Karabiner-Elements#1644]
バージョン12.1.0より後のバージョンをインストールした状態でAdobeCCアプリケーションを使用し、テキスト入力欄にカーソルを入れると、最後に押したキー？を押しっぱなしにした状態になってしまいます（何かしないと無限に入力される）。
Karabiner-Elementsを停止して、キーボードのUSBケーブルを抜き差しすると押しっぱなしの状態が解除されて、キーボードからの入力が可能になります。

これは環境の問題でしょうか？
OSはsierra10.12.6で、Logicoolのキーボード（とそのドライバ）を使用しております。

**Comment by clemsam** [comment]
[Google translates this as:]
> If you install the later version of the software from version 12.1.0 and use the AdobeCC application to insert the card into the text input field, press the last key you pressed to make it unattended (nothing happens) ) If you stop the Carabiner-Elements and unplug the USB cable from the keyboard, the state will be released and you will be able to input from the keyboard. This is an environmental problem • The OS is sierra10.12.6 and uses Logicool's keyboard (and its driver).
