### ISSUE TITLE
Keyboard jamming after waking from sleep

### ISSUE THREAD

**Issue by wincent** [tekezo/Karabiner-Elements#1645]
Not sure if Karabiner-Elements is the cause but going to post this anyway to see if anybody has a corroborating report.

**Problem:** On waking from sleep, keyboard it jammed with some unknown key(s) repeating forever, making it impossible to enter a password and requiring a hard reset. I've seen this twice in the last few weeks. I'm currently running 12.1.53 (going to update to 12.1.56 and see if that changes anything) on macOS High Sierra (specifically, 10.13.6). I have *not* set a system-wide default configuration.

<img width="663" alt="karabiner-elements_preferences" src="https://user-images.githubusercontent.com/7074/48646972-c2864a80-e9ea-11e8-92fb-af95510f9208.png">

**Question:** Is it possible that Karabiner-Elements might be involved or do you think this is more likely to be a hardware issue? (Speaking of hardware, this is on a mid-2015 MacBook Pro, so the keyboard predates the infamous butterfly switch models in the newer MacBooks.)

I tweeted about the issue and got [one reply](https://twitter.com/galstar/status/1063527880230092803) from another Karabiner-Elements user indicating that it is at least possible that Karabiner-Elements *might* be involved.

**Comment by wincent** [comment]
And I guess relatedly, if it is possible that Karabiner-Elements is the cause, is there any additional information I can collect the next time this happens (and how?) to help get to the bottom of the issue?

**Comment by wincent** [comment]
> going to update to 12.1.56 and see if that changes anything

Just happened again now with 12.1.56.

**Comment by wincent** [comment]
Wondering if this is the same issue as #545 and #739.

**Comment by wincent** [comment]
For anybody following along with this issue, this has now happened to me at the lock-screen 8 times in the last month, requiring a hard reset each time. No idea why it suddenly got so much worse. In the preceding *year*, the machine [crashed only 3 times](https://wincent.com/snippets/1162), and only one of those times involved a jammed repeating key event.

I've concluded that Karabiner-Elements is probably not the cause but it definitely makes the issue more likely. I can confirm that quitting Karabiner-Elements makes the problem go away because, when the issue occurs in a logged-in session (not at the lock screen), I can quit Karabiner-Elements using the menu item and the key repeat stops.

I ended up making [a Hammerspoon watcher](https://github.com/wincent/wincent/blob/4876913245a62e9f46ce82eeec3ac82824dd29a0/roles/dotfiles/files/.hammerspoon/karabiner.lua) that would turn off key-repeat (requiring [a custom executable to hit a deprecated API](https://github.com/wincent/wincent/blob/4876913245a62e9f46ce82eeec3ac82824dd29a0/roles/dotfiles/support/dry/main.c)) and [disable Karabiner-Elements](https://github.com/wincent/wincent/blob/4876913245a62e9f46ce82eeec3ac82824dd29a0/roles/dotfiles/files/.zsh/bin/karabiner-kill) on sleep/lock, but unfortunately it doesn't always run quickly enough to disable it before the system goes to sleep. So, I made [a Karabiner-Elements key-binding](https://github.com/wincent/wincent/blob/4876913245a62e9f46ce82eeec3ac82824dd29a0/roles/dotfiles/support/karabiner.js#L291-L315) so that I can kill Karabiner-Elements from the lock-screen in that case. This required me to [wrap my kill-script in an AppleScript](https://github.com/wincent/wincent/commit/de8381bf54e89ac825c45034536a203c9aba1bad) because the context from which Karabiner-Elements runs `shell_command`s is unsuitable for running `launchctl` (the scripts dies silently); instead, we use `osascript` as a `shell_command` to run an AppleScript that tells the Terminal app to run the kill script. I could also have made a "sleep" or lock script and just run that manually each time, but that would require me to remember to use it and I'm too wary of human error to rely on that.

This is teetering tower of hacks upon hacks, but it seems to work. I was able to hold down a key at the lock screen, simulating the problem, and still quit Karabiner-Elements with the key combination.

**Comment by Xorkle** [comment]
Hi @wincent, are you on a macOS beta version by any chance? It seems since maybe 10.14.2 the situation has improved greatly.
I was getting exactly this, specifically on the lock screen.

I noticed in most situations I can click "switch user" and the key repeat would stop.

Since a recent beta, I'm no longer getting this issue (famous last words, eh? :))

**Comment by wincent** [comment]
No @Xorkle, still on High Sierra here (precisely because I'm trying to maximize system stability; I may not even update until Apple stops shipping security fixes for this version).

**Comment by wongjustin99** [comment]
That's a really good idea -- the bind to kill karabiner-elements. I hit the same issue, and tried to make laptop sleep to fix it. That didn't work :/ Also didn't have SSH set up so couldn't SSH in to kill karabiner-elements. ended up having to do hard reset to fix as well. 

It is much less common than it used to be for me though. I think Finder just ran away and hit some issue.

**Comment by pdobrev** [comment]
I started experiencing this a lot more often lately and always after a sleep-resume cycle. I followed @wincent's solution to bind a key to kill karabiner and will try it when it happens next time. 

Thanks for the suggestion!

**Comment by pdobrev** [comment]
OK, it just happened to me again and I was able to recover using the key binding to kill Karabiner. So the work around works.

**Comment by drypot** [comment]
The same problem here.

Mid 2012 MacBook Air, Mojave.
After sleep/awake, unknown key input repeated, can't login;

iMac 2017, Mojave.
There was no problem yet.

**Comment by Ginhing** [comment]
The same problem here. (Repeatly inputting keys while logging after sleep)

Early 2015 MBP, Mojave.

**Comment by wongjustin99** [comment]
Just upgraded to 10.12.6 and it's gotten much worse, on wake CPU goes crazy and fans spin up. Not sure if the CPU part is due to the repeated key entry or not yet.

**Comment by ky0on** [comment]
I faced the same issue. Where could I found the example of `karabiner-kill` called from @wincent's `karabiner-kill.scpt`?

**Comment by wincent** [comment]
@ky0on, I linked it above: https://github.com/wincent/wincent/blob/4876913245a62e9f46ce82eeec3ac82824dd29a0/roles/dotfiles/files/.zsh/bin/karabiner-kill

The `dry` executable it made from this: https://github.com/wincent/wincent/blob/4876913245a62e9f46ce82eeec3ac82824dd29a0/roles/dotfiles/support/dry/main.c

**Comment by russelldavis** [comment]
I have this problem as well. Lots of people commenting about it in #466 too.

**Comment by duguyipiao** [comment]
I have the same problem on Sierra 10.12.6 with Karabiner-Element 10.2.0.

**Comment by jeffrizzo** [comment]
I have encountered what appears to be the same problem, using Karabiner-Elements 12.2.0 and MacOS 10.12.6 (Sierra).  I have ALSO seen it on MacOS Mojave with Karabiner-Elements 12.2.0.

I was unsure what was causing it (I've seen it at least 10 or 15 times, all told), but most recently on the Sierra MBP I could not get the key-repeat to stop until I quit Karabiner-Elements.  (Previously, I hadn't thought to do that, and wound up rebooting the computer).  Once I restarted Karabiner-Elements, everything worked fine.

**Comment by mput** [comment]
The same problem happened for me too. Anyone find some solution?

**Comment by wincent** [comment]
I did. See above.

**Comment by mingcheng** [comment]
The same problem happened for me too, Mojave 10.14.4 with mbp 2018.

**Comment by gevro** [comment]
@wincent Your solution is problematic, because it causes karabiner.json to be reset to default. Don't know how this happened, but it happened.
There's no reason to have a hacked hack to work around this issue. The bug just needs to be fixed. It is clearly an issue with Karabiner.

**Comment by wincent** [comment]
@gevro: you must be doing something wrong. The workaround works, if implemented correctly. I've been using it for months now, and it has saved me from getting locked out at the lock screen dozens of times. I can't see how it would (or could) cause the config to be reset.

I agree with you, however, that it would be great if something could be fixed in Karabiner-Elements to address this without the need for elaborate workarounds.

**Comment by gevro** [comment]
Ok I got it to work. There was an issue in the formatting of the ke-binding provided that my version of karabiner gave errors on. This is what works for me:

 {
                        "description": "Disable Karabiner-Elements with Fn+Control+Option+Command+Z",
                        "manipulators": [
                            {
                                "from": {
                                    "key_code": "z",
                                    "modifiers": {
                                        "mandatory": [
                                            "left_control",
                                            "left_command",
                                            "left_option"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "shell_command": "osascript ~/Documents/Scripts/karabiner-restart.scpt"
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    },


I also adding these to the script so it restarts karabiner:
launchctl enable gui/"$UID"/org.pqrs.karabiner.karabiner_console_user_server
sudo launchctl load /Library/LaunchDaemons/org.pqrs.karabiner.karabiner_observer.plist
sudo launchctl load /Library/LaunchDaemons/org.pqrs.karabiner.karabiner_grabber.plist
launchctl bootstrap gui/"$UID" /Library/LaunchAgents/org.pqrs.karabiner.karabiner_console_user_server.plist

echo "Karabiner-Elements restarted"

----
Either way, this bug should be fixed.

**Comment by wincent** [comment]
Not a bad idea getting it to restart automatically. I might do the same but with a `sleep 5` just to give it some margin.

**Comment by imagine** [comment]
There may very well be a bug involving Karabiner, but I want to add that switching from the Apple Wireless Keyboard to a USB keyboard has completely eliminated my issues with repeating key events. For diagnosis, it may be helpful to hear which keyboard configuration others reproduce this on.

**Comment by yshavit** [comment]
I have a USB keyboard, but I unplug it when I go home. I think you'd happens more often after that unplug, but not exclusively after it. I'm not sure about that, though.

**Comment by telotortium** [comment]
It happens to me on the built-in keyboard of a 2018 MacBook Pro 15"

**Comment by wincent** [comment]
I am hopeful this might be fixed or at least mitigated now; see: https://github.com/tekezo/Karabiner-Elements/commit/2f31010f593b4624a4db9135ebff4b0ca5156828

And more details in this duplicate issue here: https://github.com/tekezo/Karabiner-Elements/issues/1828#issuecomment-491420873
