### ISSUE TITLE
Key D does not respond in some apps.

### ISSUE THREAD

**Issue by RoadToDream** [tekezo/Karabiner-Elements#1647]
Key D does not respond in some apps like Finder, Safari, Spotlight. While other keys are working fine. 
Keystrokes can be recognized in Karabiner-EventViewer, but cannot be inputed. Incidents will disappear after unchecking devices. Event stop Karabiner-Element can not solve the problem.

**Comment by clemsam** [comment]
Extremely hard to guess what is your problem. Hardware? 
If the problem is there no matter if K-E is running (did you "Quit" Karabiner? what do you mean with "Event stop"?) then it might be s.th. with reserved keys or MacOS system shortcuts involved …

**Comment by RoadToDream** [comment]
@clemsam My fault... "Even stop"

**Comment by RoadToDream** [comment]
@clemsam I'll check if it's related with hardware.

**Comment by clemsam** [comment]
Okay, if it's not hardware you might try some weird shortcut including "D", like shift-control-command-option-D to exclude that your attempts of e.g. Cmd-D or Ctrl-D aren't pre-assigned (maybe "passively" in some sub-sub-menu). This would disable any "repetitions" of combinations...

**Comment by RoadToDream** [comment]
Thanks for your advice!  I'll give it a try.
ps: maybe I didn't describe the problem clearly enough... Key D is not responding towards single keystroke, not a shortcut. Means Key D is only not responding when typing. 
pps: I do assign Cmd+D to "show launchpad", maybe it's the real reason.

**Comment by ylluminarious** [comment]
@RoadToDream @clemsam The exact same issue has been driving me crazy for months... did anyone figure out what was causing this or how to solve it?

**Comment by RoadToDream** [comment]
Hi @ylluminarious, I had not encountered this issue anymore for a long time. 
I guess it is solved by voiding Cmd+D as a shortcut to show launchpad. 
(Both system and Karabiner have a lot updates, so not sure if that solution is the right one.)
