### ISSUE TITLE
FN Key to command Key on ThinkPad Compact Bluetooth Keyboard with Trackpoint (Unknown) Not working

### ISSUE THREAD

**Issue by adminy** [tekezo/Karabiner-Elements#1648]
I previously was unable to remap these specific keys on windows either. The bluetooth model of this just seems to do something that all software is unable to detect the fn key being pressed. The key itself works as when you use it in combination with other keys it does it's function. Any way to make it actually work? Thank you.

**Comment by ilovebamboo** [comment]
I have the same problem. i'm keyboard DELL KM717

**Comment by ilovebamboo** [comment]
![image](https://user-images.githubusercontent.com/6214084/48930599-93ad2e80-ef2c-11e8-91e0-b02c735fe67b.png)
but don't find FN key history?

**Comment by limeb** [comment]
the fn keys on Windows computers can not be remapped except as at the bios level.

Macbook Pro's to my knowledge are the only exception in the computer world to this rule.

**Comment by ilovebamboo** [comment]
![2018-11-24 11 04 49](https://user-images.githubusercontent.com/6214084/48963921-c90f5600-efd8-11e8-85ed-906f0f50a6bc.jpg)

**Comment by limeb** [comment]
@ilovebamboo what is the picture for?  This doesn't change the circumstance.

**Comment by ilovebamboo** [comment]
i want use fn key ,let to easy spotlight function.It's easy to press the wrong key

**Comment by adminy** [comment]
@limeb actually since I have a hackintosh It should be easy to do the remapping at bios level, but I did that. It has no effect on my bluetooth keyboard.

**Comment by limeb** [comment]
@adminy no bois level for laptops.  I also have a hackintosh there is no way.
