### ISSUE TITLE
Can't find left win key on the list

### ISSUE THREAD

**Issue by jytug** [tekezo/Karabiner-Elements#1649]
I can't find a way to remap the `windows` key on my external dell keyboard to `left_option`. Is there another name for this key in `karabiner-elements`?

**Comment by grayru** [comment]
Hi.
You should look for `left_gui` — it is at the bottom of the dropdown list.

**Comment by limeb** [comment]
@iytug left command key is the windows key on a mac.

**Comment by evgpisarchik** [comment]
It's named "left_gui"

**Comment by sbowman-mitre** [comment]
Perfect! I was having the same problem. Thanks!!!

**Comment by newdimitri** [comment]
牛逼

**Comment by newdimitri** [comment]
You guys are amazing, the software is very powerful to use

**Comment by Vanra101** [comment]
Woo! Left_gui worked. Amazing program!

**Comment by Vanra101** [comment]
Also made a donation to this :)

**Comment by JoeFerrucci** [comment]
I have the Varmillo VA104C https://mechanicalkeyboards.com/products/varmilo-va104c-calculator, and I can't get the Windows Key to fire. Pressing it shows nothing in the EventViewer. Same with the right Windows Key. Has anybody encountered this?
