### ISSUE TITLE
How to stop send key_up for left_control in this settings?

### ISSUE THREAD

**Issue by wd** [tekezo/Karabiner-Elements#1650]
```
        {
          "type": "basic",
          "from": {
              "key_code": "p",
              "modifiers": {
                  "mandatory": ["control"],
                  "optional": [
                      "any"
                  ]
              }
          },
          "to": [
              {
                  "key_code": "up_arrow"
              }
          ]
        }
```

This json will map `ctrl+p` to `up_arrow`, and the key events as bellow:
```
eventType:key_down        code:0xe0       name:left_control    misc:
eventType:key_up          code:0xe0       name:left_control    misc:
eventType:key_down        code:0x52       name:up_arrow        misc:
eventType:key_up          code:0x52       name:up_arrow        misc:
```
 Is there a way that  I can stop the `left_control` `key_up` event, or make this event send after the `up_arrow` `key_up` event ?

**Comment by clemsam** [comment]
What behaviour do you want to achieve, if I may ask?
There are several options to get a delayed reaction (set & query variable / to_if_held_down / …) but K-E can not "physically" keep a key pressed in a "from"-expression.

**Comment by clemsam** [comment]
Okay, this is a special case as I don't use Alfred and can't test code.  
All I can do is paste some code that helped me when I had to "imitate" the systems "Quit app at once" behaviour that doesn't work on my external (Windows) keyboard. 

Your desired behaviour belongs into the 1st manipulator's "to:"–component _(test order of keys!)_.
Also your "up_arrow" must be invoked here.  
(If code in the "to:"-component doesn't work as desired, you may have to use the "lazy" operator, or try another "delay" action.)

The 2nd manipulator should just set a variable (named e.g.: "up_arrow pressed") to "1" _**when "left_option" is pressed**_.
Be aware that I set a "delay time" of one second to inhibit "accidental" behaviours, so you must hold your combo Left_Option–Up_arrow for over a second.  

(My code should be adapted by renaming my variable to your needs AND putting "up_arrow" in place of "escape" AND inserting your "desired combo" into the 1st "to:"-component AND deleting "left_command" from 2nd manipulator.)  
This is how it works:

    { "description": "Press 2 modifiers and a key_code 'ESC'…",
      "manipulators": [{
           "conditions": [{"name": "right_shift pressed", 
                           "type": "variable_if", "value": 1 }],
                 "from": {"key_code": "escape",
                          "modifiers": { "optional": ["any"] }
                                    },
                   "to": [{"key_code": "escape",
                           "modifiers": ["left_command", "left_option"] }],
                 "type": "basic"
                       },

                       {
                 "from": {"key_code": "left_option",
                          "modifiers": { "mandatory": ["left_command"] }
                                   },
           "parameters": {"basic.to_delayed_action_delay_milliseconds": 1000},
                   "to": [{"set_variable": {
                            "name": "right_shift pressed", "value": 1 } },
                          {"key_code": "left_option",
                           "modifiers": "left_command"}],
    "to_delayed_action": {
            "to_if_canceled": [{"set_variable": {
                                 "name": "right_shift pressed", "value": 0}}],
             "to_if_invoked": [{"set_variable": {
                                 "name": "right_shift pressed", "value": 0 }}]
                         },
                 "type": "basic"
     }   ]   },
There's a variable "right_shift pressed" that in the beginning is **_implicitly_** "0" (_NOT_ defined **_explicitly_**).

Therefore the **first manipulator** will _NOT be executed "accidentally"(= under other circumstances_, see: conditions!) though in the end _it will invoke_ the "traditional" **Cmd-Opt-ESC** …

The **second one** mainly sets the variable to "1" – if **Cmd-Opt** is pressed.  
As _ESC is pressed **after** Cmd-Opt_ manipulator 1 is executed **_NOW_**.

In the end the variable is re-set to its "passive" value of "0".
