### ISSUE TITLE
lazy modifier unconsistent

### ISSUE THREAD

**Issue by holymio** [tekezo/Karabiner-Elements#1652]
Hey, 
I am trying to accomplish following: Pressing the left_control modifier should not fire an event if pressed alone for one specific application. But pressing left_control + I/J/K/L should work and call up/left/down/right_arrow like in the event log example. Right now my script looks like this:

```javascript
{
    "description": "Disable left_control for nvalt",
    "manipulators": [
        {
            "from": {
                "key_code": "left_control",
                "modifiers": {
                    "optional": [
                        "any"
                    ]	
                }
            },
            "conditions": [
                {
                    "type": "frontmost_application_if",
                    "bundle_identifiers": [
                        "^net\\.elasticthreads\\.nv$"
                    ]
                }
            ],
            "type": "basic",
            "to": [
                {
                    "key_code": "left_control",
                    "lazy": true
                }
            ]
        }
    ]
},
```

This is part of the control_left + IJKL for arrow keys. Works perfectly.
```javascript
"manipulators": [
    {
        "from": {
            "key_code": "i",
            "modifiers": {
                "mandatory": [
                    "control"
                ],
                "optional": [
                    "any"
                ]
            }
        },
        "to": [
            {
                "key_code": "up_arrow"
            }
        ],
        "type": "basic"
    },
```

> eventType:key_down        code:0xe0       name:left_control    misc:
eventType:key_up          code:0xe0       name:left_control    misc:
eventType:key_down        code:0x50       name:left_arrow      misc:
eventType:key_up          code:0x50       name:left_arrow      misc:
eventType:key_down        code:0xe0       name:left_control    misc:
eventType:key_up          code:0xe0       name:left_control    misc:

At first it seems to be working, but after some more key presses of left_control it starts to appear in the karabiner eventviewer. Is the lazy keyword buggy? Or is my implementation of it wrong? Maybe someone knows a workaround on how to get this working.

**Comment by clemsam** [comment]
Hi! I don't see any key_code "j" in your script, so what you posted cannot be the entire thing.  
I guess you meant "lazy" to keep left_control from doing anything, but actually "lazy" tells a key to wait _for another one_ to become active.  

What you might think of is done by "vk_none" which does: nothing.

**Comment by clemsam** [comment]
It is a little hard to advise what might be wrong with your code without seeing/reading it.

The only thing to see right now is, that your manipulator will make "left_control" wait for an accompanying key to then take effect, but only if pressed while "elasticthreads\\. nv" is frontmost.

As I cannot find any "key_code: j" – _**HOW should one guess**_ what is happening at all ?!?
