### ISSUE TITLE
12.0 doesn't work with fresh High Sierra install on Mac Pro 5,1

### ISSUE THREAD

**Issue by caesarsamsi** [tekezo/Karabiner-Elements#1654]
It installs just fine, I allowed the software to run in the Security General Pane and also made sure the 2 Karabiner items were in the Accessibility list.

I created a very simple rule in the preferences app, map key a to key b and closed the preferences. That's all there is to it right? No funky 10 finger key press salute? :-)

I tested with Text edit, pressed a, and a was shown on the screen instead of b.

I so loved the plain Karabiner. For the new Karabiner Elements version, I'm lacking a keypress capture so I don't have to figure out how to write a JSON script??? I'm not at all a programmer just a plain Mac user hoping that GUIs are user friendly LOL.

Back to my problem, what now? How to troubleshoot and fix?

**Comment by caesarsamsi** [comment]
Troubleshooting this, I did not find the kernel extension installed, searched with spotlight and it isn't anywhere on disk.

During install I did not see the security warning about kernel extensions. I saw this only the first time installing K-E. Removal and reinstall doesn't show the warning.

**Comment by reatang** [comment]
I ran into the same problem. I couldn't save my configuration, and I couldn't get the Settings to work

**Comment by clemsam** [comment]
Hi, for one I wonder why you don't use version 12.**1**.  
Next look if in tab Misc "Show icon in menu bar" is checked, and in tab Devices your keyboard is selected.  

Apart from that you might try this:  in "Finder" click menu item "Go to folder" in menu  "Go to" and type `~/.config/karabiner`.  _THIS_ should open its folder if Karabiner is installed.
