### ISSUE TITLE
Add modifier keys to "Simple Modifications" GUI

### ISSUE THREAD

**Issue by emmericp** [tekezo/Karabiner-Elements#1656]
I've build this json to fix the behavior of the home/end keys on macOS:

```
{
  "title": "Fix home and end",
  "rules": [
    {
      "description": "Fix home and end",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "end"
          },
          "to": [
            {
              "key_code": "e",
              "modifiers": [
                "control"
              ]
            }
          ]
        },
        {
          "type": "basic",
          "from": {
            "key_code": "home"
          },
          "to": [
            {
              "key_code": "a",
              "modifiers": [
                "control"
              ]
            }
          ]
        }
      ]
    }
  ]
}
```

It works perfectly; I just think it would be nice if I had access to the modifier key in addition to other keys in the "Simple Modifications" view.

A new column to add an additional modifier key there would be sufficient I think.

**Comment by emmericp** [comment]
Oh, I just realized that I also need the same for shift+ctrl+a/e because the behavior is different in some applications with an explizit entry for that. Also works fine with

```
        {
          "type": "basic",
          "from": {
            "key_code": "home",
            "modifiers": {
              "mandatory": [
                "shift"
              ]
            }
          },
          "to": [
            {
              "key_code": "a",
              "modifiers": [
                "control",
                "shift"
              ]
            }
          ]
        }
```


But that makes my simple GUI proposal not as simple anymore since we'd need multiple modifier keys on both from and to :(

**Comment by clemsam** [comment]
[Just a comment: as far as I know a "full" version of Karabiner is being developed, while "Elements" is a mere interim solution.]

**Comment by kshep** [comment]
can I split a tuple like

tuple = (1,2)
from, to = tuple
