### ISSUE TITLE
Getting a Karabiner-Elements Alert with no way to close it

### ISSUE THREAD

**Issue by iOSDeveloperL** [tekezo/Karabiner-Elements#1657]
I'm getting this error message upon launching the app.

**Title** 
Karabiner-Elements Alert

**Description**
System policy prevents loading the kernel extension that is used by Karabiner-Elements. You have to allow the system software from developer "Fumihiko Takayama" in System Preferences > Security & Privacy.

When I go to the System Preferences > Security & Privacy I don't a permission request.

I've restarted the machine couple of times and it still doesn't show up. 

**OS version**
macOS High Sierra
10.13.6

**Karabiner version**
12.1.0

See attached screenshot:
<img width="1643" alt="screen shot 2018-12-03 at 11 03 07 am" src="https://user-images.githubusercontent.com/2217310/49395347-0f586980-f6eb-11e8-91d6-b70c2b9f7984.png">

**Comment by iOSDeveloperL** [comment]
yes, I did try that before I posted this thread. I gave Accessibility permission to the app inside Privacy.

**Comment by iOSDeveloperL** [comment]
this is still happening and I haven't found a solution. The link @clemsam posted describes a bug where the tap was not recognized but in my case I don't even see the permission request in Security & Privacy.

**Comment by iOSDeveloperL** [comment]
That's weird. I replied above after the last stale bot warning and it still closed the issue.

**Comment by CharlesYinchuDong-Acorns** [comment]
Same situation happened here just yesterday.
Mac OS: Mojave 10.14.6
Karabiner: 12.5.0

Haven't found any solutions yet. Here are what I tried so far:
(1) Re-install Karabiner for the latest version as well as old versions.
(2) Restart computer.
(3) Restart computer with safe mode and re-install Karabiner.

**Comment by bitbrain** [comment]
Same issue.
