### ISSUE TITLE
trying to get my enter (right_option) key back

### ISSUE THREAD

**Issue by hbankstoo** [tekezo/Karabiner-Elements#1662]
Just upgraded to Mac Sierra and the new Karabiner Elements, from Yosemite and the previous version of Karabiner. Trying to remap the right_option key to keypad_enter. Put that into Elements, but doesn't show up in EventViewer.

Help! Really want my enter key back.

**Comment by clemsam** [comment]
Your facts are rather "general". Posting your entire json file is probably not necessary:

Please open your ~/.config/karabiner/karabiner.json file with TextEdit and search for "right_option".
If TextEdit doesn't find it: Click Finder's Go-to > Go-to-folder > paste above path > right-click file > "Open with …" select TextEdit from list.

Should be among "simple_modifications". Post code containing "right_option" starting with its "from": to all of its "to": parts (best till the last bracket followed by a ",").

(Do you happen to have re-assigned anything at System-Preferences / Keyboard / right-below [x] Special keys / … ?)

**Comment by hbankstoo** [comment]
Thanks for getting back to me. The functionality seems to have reappeared, as if by magic.

And yes, I was fooling around last night, and may have inadvertently changed something in System Preferences.

But thanks again. Appreciate it.
