### ISSUE TITLE
Condition for text input state

### ISSUE THREAD

**Issue by baffalop** [tekezo/Karabiner-Elements#1663]
I'd like to map ctrl+h/j/k/l to arrow keys, but I don't want it to override the macOS emacs-ish keybindings (ctrl+h for forward-delete, ctrl+k for kill to end of line). So I would want to be able to check whether we're in a text input state. `text_input_if` and `text_input_unless`.

I imagine there must be an OS hook for that. Rocket app, for one, must be using something like that to determine when typing `:` launches it.

I imagine it would be incredibly useful for many key-mappings.

Related: https://github.com/tekezo/Karabiner-Elements/issues/1226

**Comment by clemsam** [comment]
As nobody so far has answered your request, I'd like to suggest two workarounds to you , in that firstly you "put" your "emac-ish" key bindings onto a "to_if_held_down" event definition.

If this does not work for you (holding down arrow keys is used widely to get somewhere) you might add a second modifier to "Ctrl-h/k" to achieve forward-delete or end-of-line, like e.g. "Ctrl-Shift-h/k" as (at lest on my keyboard) Ctrl and Shift are easily reached together.
These should be placed in front of your more general "Ctrl-h/j/k/l" bindings to be recognised.
