### ISSUE TITLE
focused_application_if/unless alternative to frontmost_application_if/unless?

### ISSUE THREAD

**Issue by vistuleB** [tekezo/Karabiner-Elements#1666]
There is a difference between the "frontmost" application and the currently focused one.

For example, if I am in my favorite word processor and I switch to the launchpad, that word processor remains the "frontmost" application, even though it is not focused. Same if I open a finder dialog from within the application (e.g., File -> Open).

Could Karabiner incorporate a "focused_application_if/unless" alternative to "frontmost_application_if/unless"?

**Comment by vistuleB** [comment]
I'm in High Sierra.

I understand that the File -> Open dialog is part of the app that launched it. That's OK. (Though ideally, it would be great to differentiate if the current window is a Finder window or not.)

I was more specifically talking about the launchpad, which seems to be its own app. (At least, it has its own bundle ID.) Also, launchpad is "launched" via the system, not via the app... (?)

Does UIElementInspector say anything about the launchpad?

**Comment by clemsam** [comment]
Well, just from a cursory look with/into UIElementInspector I see that **Launchpad** is a 1st-level sub "AXGroup" of "AXApplication" **Dock**.

Btw: you _CAN_ differentiate applications (' windows) in K-E by:

    "conditions": [{
            "type": "frontmost_application_if",
            "bundle_identifiers": ["^com\\.apple\\.finder$"] }]

**Comment by jimgerth** [comment]
I have the same issue with the Spotlight Search (opened via Command + Space). When e.g. in Safari, the search opens as an overlay above, but Safari remains the "frontmost_application". This is quite annoying for a remap involving Escape I only want in Safari, which makes it impossible for me to exit the Spotlight Search again without using the mouse.

Found this https://github.com/pqrs-org/Karabiner-Elements/issues/3794 related, which doesn't fix it but at least contains a work-around.
