### ISSUE TITLE
Add a switch for the rule ?

### ISSUE THREAD

**Issue by Robot-L** [tekezo/Karabiner-Elements#1669]
In Complex Modifications, i use the rule"`Change spacebar to right_shift. (Post spacebar if pressed alone)`", it works cool when i coding under the English keyboard, but when i chatting with Chinese input method, it will affect my operation.
so can you add a switch to the rule, when i press 'left-shift' the rule is work or invalid, because 'left-shift' is the key to change English/Chinese input method, i want it only works under the English input.

**Comment by clemsam** [comment]
Hi, Robot_L !
I tried to find a solution for your problem, as I find the general question of having a "switch" interesting.

This is what I came up with. As I do not use an English/Chinese keyboard I had to test this code with substituted keys – therefore I can't say if this will work.
_BUT: Please test it anyway and post your success/failure (with description)!_

You should copy and paste this code _DIRECTLY_ after `"rules": [` into your karabiner json.
_(Please try my version of "spacebar to right_shift" before using a possibly different version of yours!)_

    { "description": "Toggles conditional variable ''Engl_Chin''",
     "manipulators":[
               {"conditions":[
                             { "name": "Engl_Chin",
                               "type": "variable_if",
                               "value": 0 }
                             ],
                      "from": { "key_code": "spacebar",
                               "modifiers":{ "optional": ["any"]}
                                     },
               "to_if_alone":[
                              { "key_code": "spacebar" }],
                        "to":[
                              { "key_code": "right_shift",
                               "modifiers": ["any"] }],
                      "type": "basic"
                             },
               {"conditions":[
                             { "name": "Engl_Chin",
                               "type": "variable_if",
                               "value": 0 }
                             ],
                      "from": { "key_code": "left_shift",
                             	"modifiers":{ "optional": ["any"]}
                                     },
                        "to":[
                              { "set_variable": {
                              "name": "Engl_Chin",	
                              "value": 1 } },
                              { "key_code": "left_shift" }],
                      "type": "basic"
                             },
               {"conditions":[
                             { "name": "Engl_Chin",
                               "type": "variable_if",
                               "value": 1 }
                             ],
                      "from": { "key_code": "left_shift",
                             	"modifiers":{ "optional": ["any"]}
                                     },
                        "to":[
                              { "set_variable": {
                              "name": "Engl_Chin",
                              "value": 0 } },
                              { "key_code": "left_shift" }],
                      "type": "basic"
                             }
    ]},

**Comment by clemsam** [comment]
Oh, fine! I'm glad this helps you.
Is there anything I should (ex)change so this will work for other users, too?
Is it just to switch the variable "Engl_Chin"'s values – or did you switch the order of manipulators?

**Comment by Robot-L** [comment]
@clemsam 
No, you have implemented the method of adding a switch, i used your version and deleted the previous version.
If anyone wants to add a switch to another rule, then each rule needs to be modified like this.

**Comment by Robot-L** [comment]
@clemsam Hello,
I found a new problem, I just want to switch when I press the shift button alone, but when I enter a symbol such as "!"(shift+1), it also triggers the switch.

**Comment by Robot-L** [comment]
@clemsam  
This is exactly what I want, beautiful!
And  the "lazy"-line seems to be unnecessary, i don't know what it means but there is no difference in using it.
Thank you.
