### ISSUE TITLE
Solution for Karabiner-Elements 12.1.0 breaking after macOS 10.13.6 security update 2018-003

### ISSUE THREAD

**Issue by pezely** [tekezo/Karabiner-Elements#1671]
Apple's official security update 2018-003 for macOS 10.13.6 causes issues for Karabiner-Elements 12.1.0.

Simple fix:

1. Uninstall Karabiner-Elements
2. Reboot after security update has completed; this is in addition to the reboot required for the update itself.
3. Reinstall Karabiner-Elements as usual, and it should preserve all of your prior settings.

Observed behaviour:

- Upon installing security update 2018-003 from Apple and after the machine rebooted as part of that installation, Karabiner-Elements was failing, as indicated by my keyboard remap settings having reverted to macOS factory settings.  (my config: Fn/Control on left and Opt-as-Control on right)
- From System Preferences -> Security & Privacy -> General, there was a button prompting to re-authenticate Karabiner-Elements.
- After clicking that button, Karabiner-Elements still didn't work.
- Attempting to latest Beta version of Karabiner-Elements apparently worked... until next reboot.

**Comment by Kikangh** [comment]
Thank you for this did not understand why my keyboards where not detected anymore and Karabiner-Elements was misbehaving.

**Comment by ggascoigne** [comment]
I've had the same problem (Karabiner-Elements doesn't work after every reboot).  From the log, it appears that the kext tries to load, no error is show, but at a certain point it's clearly no longer there.

anyway, long story, short, I was able to avoid reinstalling by just reloading the kext:

```bash
$ kextstat | grep pqrs
$ sudo /sbin/kextload '/Library/Application Support/org.pqrs/Karabiner-VirtualHIDDevice/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.v061000.kext'
$ kextstat | grep pqrs
  204    0 0xffffff7f84260000 0x5000     0x5000     org.pqrs.driver.Karabiner.VirtualHIDDevice.v061000 (6.10.0) 4D004D1A-ED2F-3780-AD53-A10F286EC759 <44 6 5 3 1>
```

Hope that this helps some, it's certainly less bother than a reinstall.
