### ISSUE TITLE
Possible to downgrade to an earlier beta?

### ISSUE THREAD

**Issue by dixius99** [tekezo/Karabiner-Elements#1675]
I've been using 12.1.56 for some time with no issue. I upgraded to 12.1.57 recently and notice that the Capslock light turns on randomly, and the keyboard backlighting sometimes does not work. I'd like to go back to 12.1.56 if that's possible. I looked for a place to download old betas but couldn't find one. Any suggestions?

**Comment by BlueCrystal01** [comment]
I got the same problem with the keyboard backlight. After returning from sleep mode the keyboard backlight did not work with the newest beta version. I did a NVRAM and SMC reset but this did not help. Only downgrading to the official 12.1 version worked for me. Now the keyboard backlight works if returning from sleep mode.

**Comment by tekezo** [comment]
You can download beta files from here.
https://github.com/tekezo/pqrs.org/tree/master/webroot/osx/karabiner/files

**Comment by dixius99** [comment]
Closing, as issue #1676 is more about the backlight issue, while this was more about finding old betas.
