### ISSUE TITLE
How can I set the bundle_identifiers in this code correctly?

### ISSUE THREAD

**Issue by BlueCrystal01** [tekezo/Karabiner-Elements#1678]
I am not a programmer but I could figure this code out. Can someone please help me to set the bundle_identifiers in the right place correctly? Thank you in advance and Merry Christmas!!!

{
                        "description": "SecuritySpy: When you type Option_R twice, send full screen",
                        "manipulators": [
                            {
                                "conditions": [
                                    {
                                        "bundle_identifiers": [
                                            "^com.bensoftware.SecuritySpy"
                                        ],
                                        "type": "frontmost_application_if"
                                    },
                                    {
                                        "name": "right_option pressed",
                                        "type": "variable_if",
                                        "value": 1
                                    }
                                ],
                                "from": {
                                    "key_code": "right_option",
                                    "modifiers": {
                                        "optional": [
                                            "any"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "f",
                                        "modifiers": [
                                            "left_command"
                                        ]
                                    }
                                ],
                                "type": "basic"
                            },
                            {
                                "conditions": [
                                    {
                                        "bundle_identifiers": [
                                            "^com.bensoftware.SecuritySpy"
                                        ],
                                        "type": "frontmost_application_if"
                                    }
                                ],
                                "from": {
                                    "key_code": "right_option",
                                    "modifiers": {
                                        "optional": [
                                            "any"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "set_variable": {
                                            "name": "right_option pressed",
                                            "value": 1
                                        }
                                    },
                                    {
                                        "key_code": "right_option"
                                    }
                                ],
                                "to_delayed_action": {
                                    "to_if_canceled": [
                                        {
                                            "set_variable": {
                                                "name": "right_option pressed",
                                                "value": 0
                                            }
                                        }
                                    ],
                                    "to_if_invoked": [
                                        {
                                            "set_variable": {
                                                "name": "right_option pressed",
                                                "value": 0
                                            }
                                        }
                                    ]
                                },
                                "type": "basic"
                            }
                        ]
                    },

**Comment by BlueCrystal01** [comment]
Can anyone help me please? Thank you in advance!! :-)

**Comment by anas005** [comment]
@BlueCrystal01 
From the docs:

> You can examine application's bundle identifier in EventViewer > Frontmost Application tab


(https://pqrs.org/osx/karabiner/json.html)
