### ISSUE TITLE
Uninstalling by drag to trash doesn't work

### ISSUE THREAD

**Issue by sunapi386** [tekezo/Karabiner-Elements#168]
I had Karabiner-Elements installed, deleted from `/Applications` to the trash. But found that `karabiner_event_dispatcher` and `karabiner_console_user_server` still ran. 

Killing them causes it to restart; so it's being run by a launchd. The two launchds were in `/Library/LaunchDaemons`, deleting them were not enough. 

Finally found the uninstall file in `/Library/Application Support/org.pqrs/Karabiner-Elements`, ran that and then killing the processes were ok. They didn't respawn.

**Comment by tekezo** [comment]
Please install again and use the uninstaller.
https://github.com/tekezo/Karabiner-Elements/blob/master/usage/README.md#uninstall-karabiner-elements
