### ISSUE TITLE
Feature request: add global variable "Use_Fn_keys_as_standard_function_keys"

### ISSUE THREAD

**Issue by dbdeveloper** [tekezo/Karabiner-Elements#1682]
Now I'm working on the feature _"Use all F1, F2, etc. keys as standard function keys"_ for Satechi Slim Keyboard and now the rule works only when the checkbox  _"Use all F1..."_ is checked. If I could check this checkbox in my rule using **variable_if**, I would make a universal rule which could be switched using this checkbox.

**Comment by storkinsj** [comment]
Hi,
    I am finding that it doesn't matter if I specify using function keys as standard keys... unfortunately it is checked for all devices. I only want it for my external keyboard (which I use when programming). The mac function keys should still be used for brightness,etc. 
       Since the user interface allows a "Target Device" setting for the function keys "Tab", this was the intention. At the moment however, clicking the checkbox turns this feature on or off for every device no matter if you pick a target device or not. I am adding this comment in case the problem is related to this feature request.

**Comment by cgjosephlee** [comment]
Second this. Really need this function.

**Comment by Nowaker** [comment]
@tekezo Can you please reopen this? It's a valid feature request.
