### ISSUE TITLE
Q and feature request: how does "any": "key_code" work?

### ISSUE THREAD

**Issue by dbdeveloper** [tekezo/Karabiner-Elements#1683]
I thought to use` "any": "key_code"` to reset some variables, but it seems to me, blocks all my keyboard when I do not add any `"to":` section. I think it would be nice to have something like this:

```
{
   "description": "reset variable `my_variable` when press any keys except tab, enter and escape",
   "type": "basic",
   "from": {
     "any": "key_code",
     "except": [
          "tab", "enter", "escape"
     ],
     "modifiers": {
       "mandatory": [ ],
       "optional": [ "any" ]
     }
   },
   "to": [
     {
       "key_code": "the_same",     /* or retranslate the "from" key_code if this section is absent */
       "modifiers": [ ]
     },
     { 
        "set_variable": {
            "name": "my_variable",
            "value": 0
        }
     }
   ]
}
```

**Comment by kamykaze** [comment]
I agree...the way the "any":"key_code" works right now is kinda limited. 

I am trying to do a similar thing for remapping double hitting a key to another (eg: double space to period), but I can't do space + any key --> space + original key.

For your case, I think you need to create Tab, Enter and Escape rules to keep your variable first, then use the ANY rule to reset it. However, like I said, you'll lose those keys as you cannot send the original keycode back to "to"
