### ISSUE TITLE
ctrl left click disabled not working

### ISSUE THREAD

**Issue by tukwa** [tekezo/Karabiner-Elements#1689]
hi i added the complex modification "ctrl + left click to left click" and enabled it but it doesn't work and still right clicks. can anyone help? Mac OSX 10.13.6 Karabiner 12.1.0

**Comment by genesy** [comment]
this issue is not closed. 
`{
  "title": "Remove ctrl+left click to right click",
  "rules": [
    {
      "description": "ctrl+left click to left click",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "pointing_button": "button1",
            "modifiers": {
              "mandatory": ["control"]
            }
          },
          "to": [
            {
              "pointing_button": "button1"
            }
          ]
        }
      ]
    }
  ]
}
`
this does not work.

**Comment by p-dmitrij** [comment]
Exactly the same problem for me, MacBookPro16 with Catalina 10.15.3. Could you check it please.

**Comment by genesy** [comment]
@tekezo any ideas?

**Comment by p-dmitrij** [comment]
Just for information, I've tested both complex modifications "Remove ctrl+left click to right click" and "Disable Ctrl Click" using touch pad and left ctrl key.

**Comment by p-dmitrij** [comment]
Update: I've just noticed, that the problem occurs only when the program BetterTouchTool is working. If I quit Karabiner, then the ctr+click issues no right click. Hence works as desired. But then I loose my Karabiner bindings. If I quit BTT, the ctrl+click works as desired too, but obviously I can't use then the BTT touch bar bindings.

**Comment by ehamawy** [comment]
Still having this issue on a fresh install of Catalina and Karabiner-Elements. All other complex modifications seem to work, and I've never installed BetterTouchTool.

**Comment by DvoeglazovIlya** [comment]
So, maybe you need enable usb mouse in Karabiner Preferences screen, Devices tab. Work in Monterey.
Original answer answer https://github.com/pqrs-org/Karabiner-Elements/issues/2157#issuecomment-589997981
