### ISSUE TITLE
macOS Sierra ignoring keypresses: can't wake screen for login, can't lock/sleep computer

### ISSUE THREAD

**Issue by sunapi386** [tekezo/Karabiner-Elements#169]
*   Clicking the mouse wakes up from sleep. I uninstalled Karabiner-Elements and was able to wake computer by pressing keyboard buttons. 
*   Locking screen by control+shift+eject no longer works when Karabiner-Elements is installed.

**Comment by vrybas** [comment]
A lot of third-party apps got this issue right now. Can't turn on screen after laptop goes to sleep. Including "Flux" and "Duet Display".

**Comment by Stokestack** [comment]
Just encountered this too.

**Comment by a-triant** [comment]
Related to #64

**Comment by akohlsmith** [comment]
Seems related to #154 as well

**Comment by bazhenov** [comment]
I'm also facing this issue. Can't put display to sleep using Ctrl+Shift+Eject if KE is launched. Shortcut works as expected if KE is unloaded, though. Also there is difference in logged events in Karabiner Event Viewer.

With KE launched:

    eventType:FlagsChanged    code:0x38       name:Shift_L         flags:Shift                              misc:characters:    
    eventType:FlagsChanged    code:0x3b       name:Control_L       flags:Shift Ctrl                         misc:characters:    
    eventType:FlagsChanged    code:0x3b       name:Control_L       flags:Shift                              misc:characters:    
    eventType:FlagsChanged    code:0x38       name:Shift_L         flags:                                   misc:characters: 

With KE stopped:

    eventType:FlagsChanged    code:0x38       name:Shift_L         flags:Shift                              misc:characters:    
    eventType:FlagsChanged    code:0x3b       name:Control_L       flags:Shift Ctrl                         misc:characters:    
    eventType:SysKeyDown      code:0xe        name:                flags:Shift Ctrl                         misc:
    eventType:SysKeyUp        code:0xe        name:                flags:Shift Ctrl                         misc:

Shift_L, Ctrl_L doesn't show up in second case because system is already locked when I'm releasing Shift and Ctrl, I guess.

**Comment by tekezo** [comment]
The wake up problem is revised in the latest version.
Eject is #46
