### ISSUE TITLE
Feature request: macOS Mojave Dark mode support

### ISSUE THREAD

**Issue by wegahoba** [tekezo/Karabiner-Elements#1692]
Hi,

Fully appreciating this feature request isn't critical. But, schedule depending, macOS Mojave Dark Mode support may be nice somewhere down the line?

Thanks

**Comment by ChrisBarfod** [comment]
I'd also like this feature. Big fan of dark mode.

**Comment by hologerry** [comment]
Please add full dark mode  support.

**Comment by tekezo** [comment]
Dark Mode support has been added at Karabiner-Elements v12.6.8 (latest beta).

How to upgrade to the latest beta version:
<https://pqrs.org/osx/karabiner/document.html#check-for-updates>

**Comment by connorjs** [comment]
I found this issue when searching for a way to _toggle_ dark mode. This historical issue tracked (I believe) the app itself supporting dark mode.

I was able to toggle dark mode by using `shell_command`, so I figured I would share that here.

1. Directly edit `~/.config/karabiner/karabiner.json`
2. Add `osascript -e 'tell app \"System Events\" to tell appearance preferences to set dark mode to not dark mode'`

Example

```json
                {
                    "from": {
                        "key_code": "f5"
                    },
                    "to": [
                        {
                            "shell_command": "osascript -e 'tell app \"System Events\" to tell appearance preferences to set dark mode to not dark mode'"
                        }
                    ]
                },
```

_I used `F5` b/c it's next to the do not disturb on newest MacBook Pro and I do not use dictation. F6 would be the moon/do-not-disturb._
