### ISSUE TITLE
Can not multi-select if using left/right ⌘-key mapping

### ISSUE THREAD

**Issue by objectx** [tekezo/Karabiner-Elements#1693]
Enabling the rule
> コマンドキーを単体で押したときに、英数・かなキーを送信する。（左コマンドキーは英数、右コマンドキーはかな） (rev 2)

disallows multiple item selections (hold ⌘-key then click items).

Any workarounds?

**Comment by dyanagi** [comment]
I have found the same issue.
When I press down cmd key and hold it, and then click multiple items like files and folders, only the last item is selected.

This happens on my Macbook Pro 2014, and does NOT happen on my Macbook Air 2018. (Both are Mojave 10.14.2)

**Comment by 618116** [comment]
Try to modify ~/.config/karabiner/karabiner.json like below. It works on my Macbook pro 2012(Mojave 10.14.3 beta).
<img width="1080" alt="2019-01-07 11 49 20" src="https://user-images.githubusercontent.com/5267536/50746562-fbb49b80-1272-11e9-8770-7de3ea7357a7.png">

**Comment by objectx** [comment]
@618116 Works as expected! Thanks!

\# Mojave 10.14.2 MacBook Pro (Retina, 15-inch, Late 2013)

**Comment by toslunar** [comment]
The issue seems to be resolved by updating the rule to "コマンドキーを単体で押したときに、英数・かなキーを送信する。（左コマンドキーは英数、右コマンドキーはかな） **(rev 3)**", i.e. by
the recent commit https://github.com/pqrs-org/KE-complex_modifications/commit/4b0f235898b24d703725cfb6f66c33454e1bf07e

**Comment by dyanagi** [comment]
Thank you! I have tried the new version with both of my Macbooks, and it's been working well!
