### ISSUE TITLE
Internal keyboard is not disabled

### ISSUE THREAD

**Issue by trebor8** [tekezo/Karabiner-Elements#1696]
Hi

On macOS Mojave 10.14.2, I cannot disable the internal macbook pro keyboard.
For some reason, the internal keyboard always remains enabled.

Is this a known issue?
GitHub won't let me attach a screenshot right now.

**Comment by r-obert** [comment]
<img width="1009" alt="screenshot 2019-01-08 at 22 33 26" src="https://user-images.githubusercontent.com/8934693/50860136-6fe76000-1395-11e9-9a52-6e0e79ef9102.png">
