### ISSUE TITLE
Touch Bar keyboard should be enabled by default

### ISSUE THREAD

**Issue by studgeek** [tekezo/Karabiner-Elements#1700]
The Touch Bar keyboard (Vendor ID 1452, Product ID 34304) should be enabled by default (just like other keyboards). That will allow modified function keys in the Touch Bar to work by default. This is based on solution in https://github.com/tekezo/Karabiner-Elements/issues/535#issuecomment-350522019.

Right now users may not even know Karabiner-Elements is cause or how to fix it without a lot of searching. 

Pic of what needs to be enabled:
![karabiner-elements_preferences_and_karabiner_elements_breaks_the_touchbar_on_the_new_macbook_pros_ _issue__435_ _tekezo_karabiner-elements](https://user-images.githubusercontent.com/770765/50997034-687c9f80-14d8-11e9-8751-abd5e7aeab30.png)

**Comment by studgeek** [comment]
Also see StackOverflow post on this - https://apple.stackexchange.com/a/348210/23876

**Comment by feekApp** [comment]
Also check [this](https://github.com/tekezo/Karabiner-Elements/issues/1638#issuecomment-462635444)

**Comment by shimizukawa** [comment]
Shift+Esc doesn't work property by this issue with using Karabiner-Elements.

**Comment by uoziod** [comment]
+1. Wasted so much time before understood why combinations with function keys wasn't working

**Comment by kosiara** [comment]
To make function keys work as normal i Android Studio - apart from enabling keyboard: "No product name"  I had to go into Preferences -> Function keys and DISABLE the option: "Use all F1, F2.... as standard function keys"....

<img width="1004" alt="Screenshot 2019-06-29 at 11 09 26" src="https://user-images.githubusercontent.com/4531522/60382110-abb6d480-9a5e-11e9-9f36-9b40a794553e.png">

**Comment by Stvad** [comment]
It's still relevant

**Comment by nicolaemarasoiu** [comment]
closed.....by bot :))
