### ISSUE TITLE
System policy prevents loading the kernel extension that is used by KE

### ISSUE THREAD

**Issue by karlback** [tekezo/Karabiner-Elements#1701]
Suddenly KE gave the error in the title with no way to close, and the key mappings I had set up stopped working. In the security and privacy settings there is no "Allow" button visible. I have given KE full access under the "privacy" tab. I cannot find any info about this on the KE help page. I have tried re-installing different versions, including the latest beta, as well as older versions and done numerous reboots with no change.
Anyone else experiencing something similar? Any solution suggestions?
Screenshot: https://imgur.com/KwnxlzR
(I have also tried clicking the pad lock)

Thanks!

**Comment by pawitk** [comment]
I am also facing this problem.  This started yesterday and I have not been able to resolve it.

**Comment by karlback** [comment]
On my system it solved itself a few weeks ago, either due to an update of the OS or KE

**Comment by pawitk** [comment]
I've also noticed it fixed since I restarted my system yesterday, leading me to believe it's due to an OS update

**Comment by CharlesYinchuDong-Acorns** [comment]
Same situation happened here just yesterday. 
Mac OS: Mojave 10.14.6
Karabiner: 12.5.0

Haven't found any solutions yet. Here are what I tried so far:
(1) Re-install Karabiner for the latest version as well as old versions.
(2) Restart computer.
(3) Restart computer with safe mode and re-install Karabiner.

**Comment by wcpines** [comment]
I'm on macos v10.14.6, and have updated to 12.7.0 on KE.  

I'm unable to resolve this issue :( 

From the log (probably not helpful...)

```
[2019-09-30 10:26:42.306] [info] [kextd] KextManagerLoadKextWithURL: kOSKextReturnSystemPolicy
```

**Comment by CharlesYinchuDong-Acorns** [comment]
I found a solution in this thread #1785 - https://github.com/tekezo/Karabiner-Elements/issues/1785
You can resolve this issue by running `spctl kext-consent add G43BCU2T37` in the **recovery mode**.

**Comment by wcpines** [comment]
Going to try that approach now.  (Link to relevant comment [here](https://github.com/tekezo/Karabiner-Elements/issues/1785#issuecomment-484591680))
