### ISSUE TITLE
Use fn+delete_forward in complex modifications

### ISSUE THREAD

**Issue by eramdam** [tekezo/Karabiner-Elements#1702]
I got myself a keyboard with an actual `Delete` key on it, and wanted to map some action on `fn+delete_forward`, unfortunately Karabiner doesn't seem to detect that combinaison of keys no matter how much I try 😞 

Here's the rule in question

```json
{
      "description": "Fn+del => prev",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "delete_forward",
            "modifiers": {
              "mandatory": [
                "fn"
              ]
            }
          },
          "to": [
            {
              "key_code": "rewind"
            }
          ]
        }
      ]
},
```

Here's the full gist with all my rules + the debug info of the devices I use https://gist.github.com/eramdam/d1eed744f802b2891137c2a0722b4cf0
(the keyboard with the `delete` key is the `Keytron`).

Even the EventViewer doesn't seem to detect `Fn+Delete` when I type it.

I see that the docs (https://pqrs.org/osx/karabiner/document.html#implicit) mention an implicit behaviour of remapping Fn+Delete to `delete_forward`. Could that somehow conflict? Is there a way to disable that implicit behavior?

Happy to provide more details if needed!

**Comment by wincent** [comment]
I have the same question, about mapping `fn` + `return_or_enter`, which is also listed in the "Implicit behavior" section of the docs.

**Comment by wincent** [comment]
I found the place where the implicit bindings are created:

https://github.com/tekezo/Karabiner-Elements/blob/ccba29684e8bb2ae10d538b071b73cfaa194e2e8/src/core/grabber/include/device_grabber.hpp#L863

Wondering if I should try and make a custom build without them.

**Comment by reyafyi** [comment]
why is this closed? the issue is still present. i'm used to removing words via opt+backspace, and having it remapped to forward_delete sucks very much. option to disable or override implicit behaviour is a must have.
