### ISSUE TITLE
Remap Launchpad key on macOs keyboard to external keyboard

### ISSUE THREAD

**Issue by notrealdev** [tekezo/Karabiner-Elements#1707]
Hi, i am using Logitech external keyboard.
How to remap Launchpad key on macOs keyboard to external keyboard?
I tried it but it not working
![https://i.imgur.com/nwgAsq3.jpg](https://i.imgur.com/nwgAsq3.jpg)

**Comment by notrealdev** [comment]
Hi, any new?
In case, `key_code: launchpad` not remap to `f10`

**Comment by dvrooman** [comment]
If you go to the Function Keys tab, you can change f4 from launchpad to f10. I'm using it to change my launchpad key to f11 so it shows/hides the desktop...
