### ISSUE TITLE
コマンドキー 不能｜Menu bar items can not be moved. The command key is invalid.

### ISSUE THREAD

**Issue by sarrie666** [tekezo/Karabiner-Elements#1709]
- macOS version: 10.14.2 Mojave
- Karabiner version: 12.1.59
- Mac hardware:MacBook Pro Mid2017 13" (non Touch Bar)
- keyboard hardware:US (MBP keyboard)
- language: Japanese

Issue
**Menu bar items can not be moved while holding Command key.
If I delete the rule below, I can move the menu bar item using command key.**

I use "**Complex Modifications**" and "**Rules**" for Japanese User.
**Send alphanumeric / kana key when command key is pushed alone. (Left is alphanumeric, right is kana)**<--This text is written in Japanese.

I am sorry that my English is not good. I am writing using a translation application.
<img width="994" alt="2019-01-20 20 07 12" src="https://user-images.githubusercontent.com/46863075/51438578-56c5a400-1cf1-11e9-8af1-844d075c3114.png">

**Comment by sarrie666** [comment]
I understand the above reasons.
If I hold down the command key (while holding it down), the function of the command key will be lost.

If I drag the desktop icon while holding down the command key, it should be aligned, but "Karabiner-Elements" can not align.
The long press of the command key does not play the role of the original command key.


日本語が理解できるようでしたら、日本語で書いておきます。
Mojaveではコマンドキー を押しながらメニューバーアイテムをドラッグしても移動ができません。Karabiner-Elementsを無効にすると移動ができます。

また、Karabiner-Elementsを有効にしているとFinderでコマンドキー をプレスしたままアイコンのドラッグ整列ができません。
Karabiner-Elementsを無効にすると、コマンドキー をプレスしたままアイコンをドラッグするとグリッドに整列します。

Karabiner-Elementsはコマンドキー のdown/upで英数カナを切り替え可能ですが、
コマンドキー を押下げ続けた状態にするとコマンドキー としてOS側に機能を伝達していないようです。

**Comment by maaru** [comment]
@sarrie666 I had a same problem.
I checked keyboard event with Karabiner EventViewer, and found workarounds.
Check your `~/.config/karabiner/karabiner.json`, and remove `lazy: "true"` on your configuration.

When `lazy: "true"` is set, Karabiner-Elements handled command key event until released or pressing another key, I think it's root cause of this issue.

**Comment by sarrie666** [comment]
Hi thx maaru. 
I'm sorry to be late to notice your reply.

Your comments are accurate and great. Just my procedure may not be good. Open the `.config`folder then**karabiner.json** and `lazy: "true"`removed. But it did not change.
However, let's hope that the developer can improve this bug.

> @sarrie666 I had a same problem.
> I checked keyboard event with Karabiner EventViewer, and found workarounds.
> Check your `~/.config/karabiner/karabiner.json`, and remove `lazy: "true"` on your configuration.
> 
> When `lazy: "true"` is set, Karabiner-Elements handled command key event until released or pressing another key, I think it's root cause of this issue.

**Comment by knu** [comment]
I believe you can do this if you hold the key a bit longer.  The threshold is defined by `to_if_alone_timeout_milliseconds`, which is defaulted to 1000ms.  Try decreasing it in the Parameters tab to, say, 200.

**Comment by knu** [comment]
It works for me without changing `to_if_alone_timeout_milliseconds` at all.
You should paste your configuration here so someone could reproduce your problem for further investigation.

**Comment by sarrie666** [comment]
hi, kun.
Thank you very much.
I was able to solve it successfully by the below method.
Of course I also changed the Parameters.
https://github.com/tekezo/Karabiner-Elements/issues/1693
