### ISSUE TITLE
left_alt is actually left_option, left_gui is actually left_command

### ISSUE THREAD

**Issue by Cybergern** [tekezo/Karabiner-Elements#1714]
MacOS High Sierra 10.13.6
Karabiner Elements 12.1.0

Thank you for a wonderful piece of software, helping me keep my sanity with Nordic Mac Layout every day.

In Eventviewer, when I press my left alt key on an external PC keyboard, this shows up as "left_alt", but this does not work when writing a complex modification, you need to use "left_option", the same is true for "left_gui" and "left_command", respectively. This is confusing and unclear.

"eventType:key_down        code:0xe2       name:left_alt        misc:
eventType:key_up          code:0xe2       name:left_alt        misc:
eventType:key_down        code:0xe3       name:left_gui        misc:
eventType:key_up          code:0xe3       name:left_gui        misc:"

**Comment by fharper** [comment]
You prevented me from going insane, thanks! The EventViewer was giving me one thing, and the log was giving me errors... Thanks, it should be fixed in the documentation and the viewer.
