### ISSUE TITLE
Feature Request - add support to temporarily store information.

### ISSUE THREAD

**Issue by arturszukovs** [tekezo/Karabiner-Elements#1716]
When trying to create a script-like functionality I found out that not only you can't set value to variable at runtime, you can only set 0 or 1 to any given custom variable.

What I would like to do:
1) Store copied text into a temporary variable with 1 key.
2) Copy a second string of text into clipboard.
3) Execute script like actions, with using both the stored value and clipboard.

Currently there is no problem to create the script feature, as I already have similar modifications made, but the lack of temporarily storing information cripples multiple tasks I'd like to do.

**Comment by tenhow** [comment]
I am interested in this
