### ISSUE TITLE
How do you modify a modification?

### ISSUE THREAD

**Issue by Nxt3** [tekezo/Karabiner-Elements#1717]
{
            "description": "Change fn + I/J/K/L to Arrow Keys",
            "manipulators": [
              {
                "from": {
                  "key_code": "i",
                  "modifiers": {
                    "mandatory": ["fn"],
                    "optional": ["any"]
                  }
                },
                "to": [
                  {
                    "key_code": "up_arrow"
                  }
                ],
                "type": "basic"
              },
              {
                "from": {
                  "key_code": "j",
                  "modifiers": {
                    "mandatory": ["fn"],
                    "optional": ["any"]
                  }
                },
                "to": [
                  {
                    "key_code": "left_arrow"
                  }
                ],
                "type": "basic"
              },
              {
                "from": {
                  "key_code": "k",
                  "modifiers": {
                    "mandatory": ["fn"],
                    "optional": ["any"]
                  }
                },
                "to": [
                  {
                    "key_code": "down_arrow"
                  }
                ],
                "type": "basic"
              },
              {
                "from": {
                  "key_code": "l",
                  "modifiers": {
                    "mandatory": ["fn"],
                    "optional": ["any"]
                  }
                },
                "to": [
                  {
                    "key_code": "right_arrow"
                  }
                ],
                "type": "basic"
              }
            ]
          },
          {
            "description": "Change fn+H/quote to start/end",
            "manipulators": [
              {
                "from": {
                  "key_code": "h",
                  "modifiers": {
                    "mandatory": ["fn"],
                    "optional": ["any"]
                  }
                },
                "to": [
                  {
                    "key_code": "left_arrow",
                    "modifiers": "command"
                  }
                ],
                "type": "basic"
              },
              {
                "from": {
                  "key_code": "quote",
                  "modifiers": {
                    "mandatory": ["fn"],
                    "optional": ["any"]
                  }
                },
                "to": [
                  {
                    "key_code": "right_arrow",
                    "modifiers": "command"
                  }
                ],
                "type": "basic"
              }
            ]
          },

I have a simple modification that remaps `CAPS_LOCK` to `FN`. 

What the above does is changes `FN + I/J/K/L` to the corresponding arrow keys.

I've been trying to figure out how to do something like `FN + F + J` maps to `LEFT_ALT + LEFT_ARROW` (and the same with `FN + F + L => LEFT_ALT + RIGHT_ARROW`) but can't figure out how to do this since it's technically modifying a modification.

Is this possible to achieve?

**Comment by batthias** [comment]
You could just prepend a rule for `CAPS_LOCK + F + J`. This would be executed before the modification so it achieves what you want.

**Comment by Nxt3** [comment]
@batthias How do I prepend a rule?

**Comment by batthias** [comment]
@Nxt3 you move the complex rule for this to the top and move the rule for CapsLock underneath

**Comment by Nxt3** [comment]
I'm still not following. I've tried this before all other rules:

```
{
            "description": "Change fn+F to ALT",
            "manipulators": [
              {
                "from": {
                  "key_code": "f",
                  "modifiers": {
                    "mandatory": ["fn"],
                    "optional": ["any"]
                  }
                },
                "to": [
                  {
                    "modifiers": "left_alt"
                  }
                ],
                "type": "basic"
              }
            ]
          },
```

and it just ends up acting as if I typed `LEFT_ALT + J` which is `∆`.
