### ISSUE TITLE
REQUESTING TERMINAL CODE: Remapping Caps Lock to Delete (Backspace) and vice versa

### ISSUE THREAD

**Issue by surfingoz** [tekezo/Karabiner-Elements#172]
Hi,

I've just downloaded Karabiner Elements to remap my Caps Lock Key to my Delete (Backspace on PCs) Key, and vice versa if possible too (however, not essential), but I don't know what to type into terminal to achieve this. I can open up the .json file no problem, but I'm lost as to what to type.

Any help is much appreciated.

Thanks in advance!

Jamie.

**Comment by skarekrow** [comment]
They already have you [covered](https://github.com/tekezo/Karabiner-Elements/blob/master/examples/change_caps_lock_to_delete.json) :)

Follow their directions to open your `karabiner.json` from `~/.karabiner.d/configuration/` and just copy the text in that file.

**Comment by surfingoz** [comment]
Hi skarekrow,

Thank you so much for your help mate! Fixed my issue in two seconds :D Can't thank you enough, as I'm typing this with complete ease and _true_ functionality.

Thanks again.

Jamie.

**Comment by talha131** [comment]
@surfingoz Please close this issue, if it is resolved.
