### ISSUE TITLE
Upgrade now demands kernel extension - I am not allowed.

### ISSUE THREAD

**Issue by Hanzo-** [tekezo/Karabiner-Elements#1724]
Hi I use Karabiner on a work Mac to allow use of two keyboards to 'split' for sake of my wrists.  One of my favorite parts of Karabiner is that it required no security issues.  Today it updated and now demands a kernel extension, which I am not allowed to install.  I don't even have access to the security and privacy pane of the prefs.

Is there a way around this?  I am 10.13.6 High Sierra and could but do not need to update OS X.

**Comment by tekezo** [comment]
If you are running Google Chrome (or other apps), quit it first.
https://pqrs.org/osx/karabiner/help.html#kext-allow-button-does-not-work

**Comment by Hanzo-** [comment]
It worked, so thanks, but I also needed to con(vince) my IT dept to allow me.
