### ISSUE TITLE
12.2 does not work on 10.13.3

### ISSUE THREAD

**Issue by bradyt** [tekezo/Karabiner-Elements#1726]
No configuration took effect to keys. Went back to 12.1.90 and it still works.

**Comment by bradyt** [comment]
Something was borked, not sure what.

**Comment by bretweinraub** [comment]
I've got 12.2 on 10.13.3, and KE has stopped working on my device keyboard.   Everything works fine on the bluetooth keyboard I've got though.   Ideas?
