### ISSUE TITLE
Possible to use Karabiner for hotkey to insert text

### ISSUE THREAD

**Issue by andrewjanke** [tekezo/Karabiner-Elements#1731]
Is it possible to use Karabiner to insert text defined by a function?

For example, press Ctrl-Option-D and the ISO date is inserted "20190206-2240"

I have read the docs but I don't think shell_command will achieve what I want.

**Comment by tekezo** [comment]
You can do it with shell_command + JXA, but it is not suitable.
You should use other snippet tools.
https://github.com/JXA-Cookbook/JXA-Cookbook/wiki/System-Events

**Comment by MartinBulla** [comment]
Do I understand it correctly that Karabiner is not suitable for inserting current date time (like '2019-02-13 23:22:00'). If not, is there any easy way of doing this? 

I manage getting date with Automator:
`on run
	return short date string of (get current date)
end run`
but have no clue how to add the current time to it.

**Comment by andrewjanke** [comment]
This isn't the correct forum, but I do this in a similar way:

```
on run {input, parameters}
	
	# set thedate to (current date) as string
	set thedate to do shell script "date +%Y%m%d-%H%M"
	tell application "System Events"
		keystroke thedate
	end tell
```

Then assigning a shortcut via Keyboard in System Prefs and associated permissions for each app...  It's painful.
