### ISSUE TITLE
Karabiner-Elements 12.2.0 and sleep mode in MBP 15" 2018

### ISSUE THREAD

**Issue by AlexVanin** [tekezo/Karabiner-Elements#1734]
After `12.2.0` update I got weird bug on my 15-inch MacBook Pro 2018 (_MacOS Mojave 10.14.3_)

When I wake up laptop after a sleep (with closed lid), keyboard is often not responsive until I log in with Touch ID (I cannot type a password). Also backlight is off and it is not working even after logging back into account. After full reboot everything is fine until next sleep. 

It happens more often while laptop attached to the AC, and less often when works from battery. Don't know if it is correlated.

**Comment by bojankseneman** [comment]
I am also affected by this issue. Because the backlight is important to me so I can code in the dark I sadly had to remove Karabiner-Elements

**Comment by Johnny-Fung** [comment]
I am also currently on Karabiner v12.2 with the new Mojave updates on v10.14.3. The keyboard backlight doesnt work for me either. Device is a 2018 Macbook Pro 15 inch

**Comment by rvw** [comment]
Also see this issue: https://github.com/tekezo/Karabiner-Elements/issues/1676

**Comment by nicklasbondesson** [comment]
Duplicate of https://github.com/tekezo/Karabiner-Elements/issues/1676

**Comment by arstrube** [comment]
I have a similar issue. In my case, after upgrading to Karabiner-Elements v12.2.0, the trackpad was no longer found after sleep.  This happened consistently, and there seemed to be no fix for it other than reboot. I could't move the mouse pointer until I connected a bluetooth mouse. I downgraded to v12.1.56 and the problem seems to have gone away. I have an MBP Pro 13" running OS X 10.14.2 (Mojave).

**Comment by arstrube** [comment]
It happened with 12.1.56. The MacBook no longer finds its internal trackpad OR its internal keyboard. Fortunately, I own a Bluetooth mouse, so I didn't need to switch it off.

Now I am down to 12.0.0. The keyboard is working after sleep, but the trackpad is only half-working (it lost its capacity to recognize three-finger swipe).

**Comment by arstrube** [comment]
And it happenend with 11.6.0. Keyboard, trackpad, all gone. (I get an OS X error saying that it can't find any mouse or keyboard). I am fairly certain I was using 11.6.0 before the upgrade, so I am beginning to suspect that this problem is of a more general nature. But what? It is extremely annoying, as you can imagine.

**Comment by arstrube** [comment]
I have quit Karabiner-Elements, and the problems have disappeared.  Then Karabiner-Elements must be the culprit, right?

**Comment by arstrube** [comment]
Wrong. The problem persisted.  Eventually I realized that Virtualbox was hogging the USB controller upon wake-up. There isn't any problem with Karabiner. Cheers :-)

**Comment by Rdrdul** [comment]
I have this problem, too. If I disable Karabiner-Elements from modifying events from the keyboard in my 2018 15" MacBook Pro and then restart, the backlight works as it should. If I then re-enable K-E modifying keyboard events, it disables the backlight after I sleep the computer and then wake it up. The last time I tested this it also entirely disabled the keyboard. So K-E is undeniably the culprit.

**Comment by rdewolff** [comment]
Do you guys had a related issue like the keyboard or mouse not working at all ?

**Comment by arstrube** [comment]
Just in case -- I let me state again that my issue had nothing to do with Karabiner. Nothing at all.

It was some obscure issue with VirtualBox that occured after upgrading to a MacBook Pro 13" and OSX Mojave, which led to Virtualbox hogging an Apple USB controller (as if it were a pendrive USB controller). This results in keyboard and trackpad becoming totally unsresponsive.

It is not a Karabiner Elements issue, but a VirtualBox issue. Of course, I don't know if you guys are facing an issue of a different nature...

**Comment by poltimmer** [comment]
I have this problem too, unfortunately. Problem is present on 12.2.0, and I assume also on 12.3.0, as no fix for this is specified in changelog. Backlight doesn't work after sleep until full reboot is done. Had to downgrade to 12.1.0 to resolve this issue, but now unfortunately my capslock LED isn't working (known bug in 12.1.0)

**Comment by Rdrdul** [comment]
12.3.0 fixed it for me. Has worked as it should without problems for several days.
