### ISSUE TITLE
Key modifications don't work while CAPS LOCK is activated

### ISSUE THREAD

**Issue by seanmoriarity** [tekezo/Karabiner-Elements#1736]
When I'm typing text with the Caps Lock key activated, some Karabiner modifications stop taking effect. For example, I have the Enter key mapped to right_control when held down, and the complex modification of "j" + "right_control" to map to "delete_or_backspace".

In Karabiner Event Viewer, I can verify that holding the enter key and tapping j activates "delete_or_backspace" in the event viewer. But when I activate caps lock and type the same key combination, instead the event viewer returns "j" in the name field (and would activate the native control+j shortcut, which doesn't seem to exist).

Is there a setting that I need to activate so that my expected shortcuts still work while typing in all-caps?

It seemed that this erratic behavior stopped during the time that the CAPS LOCK indicator light wasn't working, but now that the light works again, the key modifications don't take effect while typing with CAPS LOCK activated.

**Comment by seanmoriarity** [comment]
I suspect that whatever code causes the CAPS LOCK to light up disables shortcuts from being entered while the light is active. Honestly, I would rather not have CAPS LOCK light up at all if it means that modifications can't be entered while typing in all-caps.

**Comment by Hansterdam** [comment]
I have this same issue. Before, on macOS Sierra, I had no problems. If Caps lock was on, I could still use all my short cuts, but after recently changing to macOS Mojave, this is not the case anymore. I wonder if this was introduced in version 12.2.0.

**Comment by ionstormx** [comment]
Has anyone ever found a fix to this?

**Comment by mushmelty** [comment]
I’m guessing not, and it still drives me nuts every single day. I don’t care at all if the caps lock key lights up — I just want to keep using my shortcuts.

**Comment by Hansterdam** [comment]
I updated Karabiner a couple weeks ago and now it works again. Are you guys running the latest version?

**Comment by mushmelty** [comment]
I'm using the newest version now: 12.7.0, and the caps lock still turns off all the modifiers when the light is lit.

**Comment by ionstormx** [comment]
Running the latest. Still not working.

**Comment by kn666** [comment]
{
          "from" : {
            "key_code" : "f",
            "modifiers" : {
              "optional" : [ "caps_lock" ]
            }
          },

**Comment by nonsonodavid** [comment]
ha funzionato questa modifica? io ho provato ma niente da fare

`{
"from": {
"key_code": "f",
"modifiers": {
"optional": ["caps_lock"]
}
},
