### ISSUE TITLE
Device-specific profiles

### ISSUE THREAD

**Issue by wastedepository** [tekezo/Karabiner-Elements#1738]
When I'm at my desk, I use an external keyboard and mouse. When I'm not, I use the normal internal keyboard and trackpad, and the keyboard modifications I want to use are rather different.

I would like a feature where each profile can be tied automatically to a device, and activated when that device is used. This system already exists for simple modifications, but not for complex modifications.

Note that it **is** currently possible to specify device-specific complex modifications, by indicating "device_if" or "device_unless" for each complex modification ([example](https://github.com/pqrs-org/KE-complex_modifications/blob/master/docs/json/example_device.json)). However, I'd like a system more like the one used for simple modifications, where each complex modification can be associated with specific device(s) in the GUI.

Perhaps this issue is irrelevant until there is a GUI interface for creating complex modifications -- as is, the only way to create your own complex modifications is to manually edit ~/.config/karabiner/karabiner.json ([example](https://pqrs.org/osx/karabiner/json.html)), which not actually something the program explains to the user.

Ideally, each entire profile would be associated with a group of specific devices, including the items under Complex Modifications -> Parameters.

Note that this and similar issues have been discussed several times before, but the issues keep getting closed without resolution. The most relevant issues seem to be:
https://github.com/tekezo/Karabiner-Elements/issues/792
https://github.com/tekezo/Karabiner-Elements/issues/979
https://github.com/tekezo/Karabiner-Elements/issues/1073
https://github.com/tekezo/Karabiner-Elements/pull/756

**Comment by jDally987** [comment]
Also interested in this, I'm primarily a Windows user just recently switched to mac for work; it amuses me greatly that this is still an issue that gets ignored, even years later.

From my understanding Karabiner has been one of those pretty pivotal apps for macOS for a long time, so it's pretty surprising that a user-friendliness issue like this still isn't implemented? I imagine it would be an easy fix. But then again I'm not sure if it would require a more extensive revamp of the whole JSON file-based scheme that the complex modifications are based on.

**Comment by wrinkledeth** [comment]
also interested. Any chance of this happening?

**Comment by Exolife516** [comment]
@wrinkledeth 

Use this example for a complex modification and change your devices vendor and product id from the device tab.

{
    "description": "tab to cmd+s",
    "manipulators": [
        {
            "conditions": [
                {
                    "identifiers": [
                        {
                            "product_id": 555,
                            "vendor_id": 5426
                        }
                    ],
                    "type": "device_if"
                }
            ],
            "from": {
                "key_code": "tab",
                "modifiers": {
                    "optional": [
                        "any"
                    ]
                }
            },
            "to": [
                {
                    "key_code": "s",
                    "modifiers": [
                        "command"
                    ]
                }
            ],
            "type": "basic"
        }
    ]
}
