### ISSUE TITLE
Modifications not respected on macOS 10.14.3

### ISSUE THREAD

**Issue by PSalant726** [tekezo/Karabiner-Elements#1739]
KE: 12.2.0
macOS: 10.14.3

I recently updated macOS to 10.14.3. My configuration settings are still present, but the OS does not recognize or utilize them. My re-mapped external devices are now back to factory default configuration(s), even after restarting both KE and the machine itself.

**Comment by girin-dev** [comment]
reboot ur mac, then it works well.
I don't know why it doesn't work just after updating mac 10.14.3.

**Comment by PSalant726** [comment]
It took more than one restart for me. The initial restart as part of the OS update installation did not resolve the issue, but I restarted again and it seems to work now.

**Comment by ichifish** [comment]
I had the same problem in 10.14.3. I have both Karabiner and Karabiner Elements installed and didn't realize it. Restarting didn't help, but originally I was using Karabiner, and after the second restart I opened elements. I didn't make any changes, but after opening elements the key mod started working again.
