### ISSUE TITLE
Fn key doesn't work in combo with remapped key.

### ISSUE THREAD

**Issue by Stokestack** [tekezo/Karabiner-Elements#174]
I have the Mac's "Use F1, F2.. as function keys" option on, so I can remap F12 to be Delete ("forward delete" in Apple's ignorant parlance).

But pressing fn+F12 doesn't do anything (it should be the volume-up key).

The config is below:

{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "f12": "delete_forward"
            }
        }
    ]
}

**Comment by talha131** [comment]
See the correct format here https://github.com/tekezo/Karabiner-Elements/issues/62#issuecomment-248691996

Also see this https://github.com/tekezo/Karabiner-Elements/issues/129#issuecomment-249365176

**Comment by Stokestack** [comment]
Thanks, but unfortunately that doesn't work. Volume-up now works when I hold the fn key, but forward-delete doesn't when I press F12 alone. Here's the config:

{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
				"f12": "delete_forward"
            },
            "fn_function_keys": {
                "f1":  "vk_consumer_brightness_down",
                "f2":  "vk_consumer_brightness_up",
                "f3":  "f3",
                "f4":  "f4",
                "f5":  "vk_consumer_illumination_down",
                "f6":  "vk_consumer_illumination_up",
                "f7":  "vk_consumer_previous",
                "f8":  "vk_consumer_play",
                "f9":  "vk_consumer_next",
                "f10": "mute",
                "f11": "volume_down",
                "f12": "volume_up"
            }
        }
    ]
}

**Comment by talha131** [comment]
For `fn+f12` you will have to wait for #16.

For now, you can have f12 act as either delete or volume up.

**Comment by Stokestack** [comment]
Still a problem. Have the changes for "complex" key mappings (mentioned as #16 above) not been integrated into any releases?

**Comment by Stokestack** [comment]
#16 was closed with no explanation that I can see. What's the status of the prerequisites for fixing this?

**Comment by Stokestack** [comment]
Still a major impediment. Is this simply not fixable?
