### ISSUE TITLE
Majestouch 2 Convertible Fn keys not functional (asking again)

### ISSUE THREAD

**Issue by JohnReddyZhang** [tekezo/Karabiner-Elements#1744]
I just got a Majestouch Convertible and trying out Karabiner Elements, it has the same issue as described. `F1`, `F2`, `F3`, `F5`, `F6`, `F7`, and `F8` and `F12` has manufacture built-in functions: volume up, down, mute, rewind, start/pause, stop (which Karabiner EventViewer cannot recognize), forward, sleep (cannot recognize), thus messing up with settings.

When using function setup like below (with `Use F1, F2, etc...` checked, 
<img width="1003" alt="2019-02-16 22 16 26" src="https://user-images.githubusercontent.com/15935574/52908292-83110980-3238-11e9-98ad-a17af0c77681.png"> pressing `Fn + F*` emits those volume up, down, etc events excepts the two that cannot be recognized, and pressing only function keys emits normal `F*` keys.

When unchecked, pressing only function keys emits those keys set. But pressing `Fn + F*` cannot emit `F*`. Instead emits manufacturer set keys on keys described above, and the remapped keys on other keys, I cannot get `F*` keys to work! 

This is the same issue as #590 but I did not see a solution to that... 
(P.S. This happens BOTH on MacBook Pro with or without Touch Bar)

Thank you very much!

**Comment by legrillewhat** [comment]
I, too, am having this issue. Would be really great to have Karabiner listen for Fn-key, so we could repurpose this dead key.

**Comment by JohnReddyZhang** [comment]
Hey @legrillewhat thanks for replying! I just figured out a _possible_ solution to this issue: If you are using Majestouch as well there should be DIP switch in the back. If you flip switch 4 the dead `fn` key turns into `application` key and then you could use elements to remap `application` to `fn` and it should work. At least there is no errors to me yet. Cheers!

**Comment by legrillewhat** [comment]
Hi! Thank you for this! Would the DIP switch be inside the keyboard case? I haven't had mine open yet, and there are no DIP switches on the back. IT's a Majestouch 2 Camo.

**Comment by JohnReddyZhang** [comment]
I thought DIP was available on all Majestouch 2 but I looked through the product details and unfortunately it is only there on Majestouch Convertible 2 ... Maybe you could try asking about this issue on [r/MechanicalKeyboards/](https://www.reddit.com/r/MechanicalKeyboards/), maybe they have some other solutions in regards to Majestouch 2?

**Comment by legrillewhat** [comment]
Thanks again. I just took the back+front covers off, but there were no switches of any kind.

I've been searching r/MK, and google in general, but there seems to be no answers.

I'll try asking! Thanks again for taking the time to reply. I hope Karabiner will some day have this functionality.
