### ISSUE TITLE
How can I map tab to n spaces?

### ISSUE THREAD

**Issue by abhigenie92** [tekezo/Karabiner-Elements#1745]
**How can I map a tab to 4 spaces or 2 spaces?**
The `simple modification` only allows to map tab to 1 space. 
When I try the `complex modification`, I click on `Add rule`, I only choose pre-existing rules or import some from the web. There's no option to design your own rule. On the web [link](https://pqrs.org/osx/karabiner/complex_modifications/), I can't find a rule that does what I said before.

![image](https://user-images.githubusercontent.com/12474640/52925573-caee6a00-32e6-11e9-8b13-00aa5ba39d50.png)

**Comment by ironsand** [comment]
You can add your own complex modification by following this post.
https://github.com/tekezo/Karabiner-Elements/issues/1225#issuecomment-460170227

I don't know how to write the config file, though.
