### ISSUE TITLE
Shift-click not working

### ISSUE THREAD

**Issue by gevro** [tekezo/Karabiner-Elements#1748]
Hi, This was apparently an old bug that seems to have resurfaced. Using Karabiner-elements 12.2.0 and Mojave 10.14.3, shift + mouse click doesn't work in any application.

Karabiner event viewer doesn't show activity for left or right shift even when pressed alone. Strangely, it does show shift when pressed with another keyboard key, but not with the mouse.

Quitting Karabiner fixes the problem, and event viewer then also starts showing shift as working again.

**Comment by memray** [comment]
Encountering the same problem after a recent update to 12.2.0 on Mojave 10.14.2.
Problem solved after removing "Swap Command with Ctrl". The wired thing is my "command" and "ctrl" are already swapped somehow (due to Mojave update?).

**Comment by gevro** [comment]
Anybody home?

**Comment by tekezo** [comment]
The "Swap Command with Ctrl" changes shift key to lazy modifier which is required by "Option+Tab to Command+Tab".

There are two workaround. Choose either.

1. Swap Command and Control key by Simple Modifications instead of Complex Modifications.
    https://pqrs.org/osx/karabiner/document.html#configuration-simple-modifications
2. If you are using external mouse, enable your mouse on Devices tab.
    https://pqrs.org/osx/karabiner/document.html#configuration-devices

**Comment by gevro** [comment]
The second workaround kind of works - but it seems to care in some applications if I click shift AFTER mouse click instead of BEFORE. But it should work regardless of SHIFT vs Mouse-click order.

The first workaround won't work, because my 'Swap command and control' need to be applied only to certain applications with the "bundle_identifiers".

Is there any other solution? Can simple modifications be modified in Json with "bundle_identifiers"?

**Comment by gevro** [comment]
It is actually doing something using Karabiner event viewer. It only activates shift with mouse click if shift is clicked while the mouse is MOVING. This is very strange.
This bug is easy to observe in photoshop or adobe illustrator where shift is used to move objects leaving them in the same horizontal or vertical position.

**Comment by gevro** [comment]
doing something *strange* using Karabiner event viewer.

**Comment by tekezo** [comment]
Another workaround, search `"lazy": true` in karabiner.json and replace `"lazy": false`.

before:

```json
            {
              "key_code": "left_shift",
              "lazy": true
            }
```

after:

```json
            {
              "key_code": "left_shift",
              "lazy": false
            }
```

How to modify karabiner.json:

1. Open TextEdit.
2. Press Command-O on TextEdit. File choose dialog will be opened.
3. Type ~/.config/karabiner on the file choose dialog.
4. Open karabiner.json.

**Comment by gevro** [comment]
Thanks. This fixed it. Not sure why the default is lazy: true.

**Comment by tekezo** [comment]
@gevro
Does this issue occur with empty simple/complex modifications (e.g., new profile)?
https://pqrs.org/osx/karabiner/document.html#profiles

If this issue does not occur with empty profile, I guess your current profile still changes the shift key or click events.
is there any other configurations which changes the shift key in your current configuration?

**Comment by gevro** [comment]
Actually it look like this might be a quirk of Adobe software behavior. I do not have any other shift key changes (I checked in my karabiner.json file). So I will close this issue. Thanks.
