### ISSUE TITLE
Adobe Illustrator spacebar function (hand tool) stops working.

### ISSUE THREAD

**Issue by quaritexa** [tekezo/Karabiner-Elements#175]
When Karabiner-Elements is running I can't use Hand Tool in AI. The spacebar not working.

**Comment by grod** [comment]
I have the same problem in Photoshop

**Comment by quaritexa** [comment]
Some key bindings in Hammerspoon also doesn't work.

**Comment by quaritexa** [comment]
Last version of karabiner elements works fine, without bug.
