### ISSUE TITLE
unable to remap paragraph to tilde

### ISSUE THREAD

**Issue by skyboyer** [tekezo/Karabiner-Elements#1753]
Hello. 

My "US international" layout prints paragraph character for key under ESC button. 
I'm trying to change that(so it would print tilde/grave accent).

Using "Simple Modifications" section I'm able to remap paragraph(by selecting "grave_accent_and_tilde") key to anything(say "a"). So this key is detected as "grave_accent_and_tilde" for sure.

Trying to remap "grave_accent_and_tilde" onto "grave_accent_and_tilde"still prints § on press.

Is it a bug or do I miss something?

Karabiner Elements 12.2.0
MacOS 10.13.6

**Comment by venedie** [comment]
I observe the same issue on:

Karabiner Elements 12.2.0
macOS 10.14.3

**Comment by skyboyer** [comment]
@venedie fortunately for me(and unfortunately for reproducing this issue) after rebooting(typically I just put Mac to sleep but that time it was real reboot) tilde/backtick just work even without Karabiner. Have no idea what was wrong(but it seems to be related rather to MacOS than Karabiner)

**Comment by venedie** [comment]
@skyboyer wow, the same here. Sorry for the trouble 😅
