### ISSUE TITLE
need help with touchcursor mode

### ISSUE THREAD

**Issue by LynnWalton** [tekezo/Karabiner-Elements#1755]
I would be so grateful for anyone that could help me achieve what I need to move to a new mac without losing the karabiner touchcursor mode I've grown so dependent on for my coding and elimination of my severe Repetitive Stress Issues. 

I've tried the ones available in personal rules here for karabiner-elements , and my own adaptations but am having no luck.  

The one I'm used to from Karabiner had the ability to hold down the s key while also holding down the spacebar to make your j/k/i/l/o/u etc apply the shift key so you could do selection.  Also it had the ability to hold down the a while holding the spacebar, to make the j/l move by word rather than character.  And the combination of spacebar and a and s were all available.   I can't seem to get that going.  

Also, the timing seems off. I type very fast and it seems like it is always missing what I expect and ending up placing my cursor elsewhere.  

I'm willing to pay someone who can work with  me to get a json file that achieves these things. 
Thanks,
Lynn

**Comment by lwalton-turnto** [comment]
Anybody else have a problem with the timing on touch cursor?
Are there any examples of it working with holding down a key in addition to space to have it select/highlight while moving?  
Anybody at all have time to help me with this?  Pretty, please .... for $$$$ and eternal gratitude?
Thanks,
Lynn

**Comment by nehachn** [comment]
> Anybody else have a problem with the timing on touch cursor? Are there any examples of it working with holding down a key in addition to space to have it select/highlight while moving? Anybody at all have time to help me with this? Pretty, please .... for $$$$ and eternal gratitude? Thanks, Lynn

Hi, I have similar issue where if I type fast, spaces are registered late and at improper places
