### ISSUE TITLE
Arbitrary keypresses on login screen after waking up from sleep 

### ISSUE THREAD

**Issue by arampak** [tekezo/Karabiner-Elements#1758]
With the most recent version (12.2.0) of Karabiner Elements on Mojave once in a while I get a situation when there is no way to type the password in the login screen as alongside with my typing either additional letters are constantly put in or a backspace generated that removes my typing. This is not happening every time, but once in 4-5 times. I can only do hard shutdown to get around. This was not happening with the previous version. 

As I use Karabiner to reassign a failed "Enter" button, I had to activate a system-wide configuration to have Karabiner work on login screen.

**Comment by Bibi** [comment]
Same issue has happened to me a few times.

**Comment by arampak** [comment]
Additional information that might help. I tried switching to different user and then clicking "Shut down". Attached is the screen shot of the dialog box. When I click into the password field, it gets filled in with unknown keystrokes. When I click into the name field, nothing appears, but the floating window that lets you key in the versions of "i" letters, as shown. I am even able to key in some characters (as shown), but not digits. The mouse keeps blinking however, suggesting that some keystrokes are probably being entered that do not result in any output. 
  
![img_3731](https://user-images.githubusercontent.com/6896303/53869569-ed37f580-4011-11e9-803a-69621bd341c3.jpeg)

**Comment by telotortium** [comment]
I've also had this issue several times. Today, I was able to log in, but then the issue appeared to start - the letter "r" was repeatedly typed. I was able to stop it by opening Karabiner Elements from finder and going to "Misc > Quit", at which point the keystrokes stopped being sent. Thus, I believe this issue is being caused by Karabiner Elements.

**Comment by telotortium** [comment]
Seems related to #1645 for me.

@tekezo Does the Karabiner-Elements log contain private information? (It doesn't look like it.) I can upload the log visible in the app this morning. In particular, I see this message in the log corresponding to right after I wake up:

```
[2019-03-09 08:43:46.737] [warning] [grabber] Apple Internal Keyboard / Trackpad (device_id:4295017989) is ungrabbable temporarily by a failure of accessing device.
```

**Comment by russelldavis** [comment]
@arampak this is a duplicate of #1645
