### ISSUE TITLE
How can I disable the Capslock keypress delay

### ISSUE THREAD

**Issue by mattgibson** [tekezo/Karabiner-Elements#176]
This was possible using Seil, but I can't find any configuration for it in Karabiner elements.

**Comment by tekezo** [comment]
You can decrease the caps lock delay by "No Action" configuration.
https://pqrs.org/osx/karabiner/seil.html.en#usage

(You can keep the caps lock key behavior by using Karabiner-Elements since Karabiner-Elements ignores the setting and keep your caps lock behavior.)
