### ISSUE TITLE
Karabiner-Elements  stopped working after OS upgrade

### ISSUE THREAD

**Issue by chuckfossen** [tekezo/Karabiner-Elements#1762]
I am running 10.14.3. 
I had one simple modification: application > right_command.
The preferences show the simple modifications as blank. If I re-add the modification, I see that the .config/karabiner/karabiner.json file is updated but it is not working. And if I close and reopen the preferences, the modification does not show up.
Any ideas of what could be wrong?

**Comment by chuckfossen** [comment]
It's acting like KE can write the config file but not read it.

**Comment by petromir** [comment]
@chuckfossen I have the same issue. I'm adding some complex rules but they get deleted once I close the preferences.

**Comment by chuckfossen** [comment]
I cloned the source, built and installed 12.12.2. I still have the same problem with the configuration not being saved but in my case, the key right_gui (equal to `right_command`) seems to be the default behavior now so at least I have the right command key again.

**Comment by chuckfossen** [comment]
But now the function keys are set to do brightness, mission control, etc. and I can't turn them off.

**Comment by getmoheb** [comment]
I am having this issue too. Updated to 10.14.3 this morning and none of my rules are working. Running 12.2.0

**Comment by chuckfossen** [comment]
After rebooting, KE seems to be working normally.

**Comment by petromir** [comment]
Rebooting fixed the issue for me too :)

**Comment by chuckfossen** [comment]
@getmoheb, maybe you want to reinstall and reboot. If that works, we should close this issue.

**Comment by getmoheb** [comment]
yes it worked. all good my end after a reboot. thank you!

**Comment by b-a-t** [comment]
Upgrade to 10.14.4 also required additional reboot to get things working.

**Comment by Pfiver** [comment]
Ein Reboot tut immer gut.

Solved after a reboot.
