### ISSUE TITLE
Not working in 10.12.6

### ISSUE THREAD

**Issue by Shmoo4518** [tekezo/Karabiner-Elements#1763]
I recently went from 10.11 to 10.12.6 and Karabiner isn't working at all. I simply want to make the R Option Key = Enter to no avail. Let me know if there's a workaround

**Comment by sbine** [comment]
I had the same issue after a 10.14.4 upgrade, and updating Karabiner-Elements to the latest beta version (12.2.6) fixed it for me:
![Screen Shot 2019-04-05 at 9 29 48 AM](https://user-images.githubusercontent.com/1902973/55642676-fd183600-5785-11e9-9718-7dc382f0d2fc.png)
