### ISSUE TITLE
ThinkPad Keyboard TrackPoint (mouse) is trapped

### ISSUE THREAD

**Issue by ffffwh** [tekezo/Karabiner-Elements#1769]
This is a keyboard & mouse (2-in-1) device.

I am using another app 'SteerMouse' to tweak mouse setting (curve, scrolling and button). Karabiner traps mouse events and SteerMouse fails to work.

Can it separates keyboard and mouse of this device?

**Comment by ffffwh** [comment]
<img width="500" alt="Screen Shot 2019-03-13 at 11 08 12" src="https://user-images.githubusercontent.com/41767537/54250897-74401d00-4580-11e9-9d9a-7ae83cbf3ccc.png">

Sorry for forgetting to upload the screen shot.

**Comment by kfajdsl** [comment]
Having the same issue here
