### ISSUE TITLE
Logitech G710+ G keys get disabled on Mac when PC-Style mappings is loaded

### ISSUE THREAD

**Issue by DanTheMountainMan** [tekezo/Karabiner-Elements#1775]
macOS version: macOS 10.14.3
Karabiner version: Karabiner-Elements 12.2.0
Your Mac hardware: MacBook Pro
Your keyboard hardware: Logitech G710+ Keyboard, Logitech Gaming Software 9.02.22

The 6 G-Keys do not work when Karabiner elements is active.  These are extra Macro keys that are additional on this keyboard.  The M1, M2, and M3 buttons do not switch, which control the G-Keys as a mode switcher and can make the 6 G-Keys act as 18 unique keys.  If I go to Devices, and uncheck the keyboard, the M1, M2, and M3 buttons work again as well as the G-Keys.  As soon as I check the keyboard, the G-Key functionality stops.  Please try out Karabiner Elements with the Logitech G710+ keyboard and get the G-Keys working.  It was working great on my Das Keyboard Professional, I really like the PC-Style mapping as I was a Windows user for a very long time.

**Comment by cayco** [comment]
I can confirm this still exist. One cannot use G keys and Karabiner at the same time.
