### ISSUE TITLE
Does not work with Synergy

### ISSUE THREAD

**Issue by Gibby** [tekezo/Karabiner-Elements#1776]
Does not capture events from [Synergy](https://symless.com/synergy) 

Mac Version: 10.14.3
Synergy Version: 1.10
Karabiner Version: 12.2.0

**Comment by iobus** [comment]
I am noticing this issue as well.
MacOS version: 10.15.4
Synergy version: 1.11.0
Karabiner-Elements version 12.9.0

**Comment by rjorgenson** [comment]
I am also experiencing this issue. Nothing is registered from my Synergy connected keyboard.
