### ISSUE TITLE
Windows key on external keyboard is not recognized at all by Karabiner EventViewer

### ISSUE THREAD

**Issue by PWKad** [tekezo/Karabiner-Elements#1777]
On 13" MBP Mojave 10.14.3 I could not get the external keyboard to map `opt + left arrow` to `move word back` and it wasn't working.

I opened the EventViewer after trying for a while to get this to work and realized that the event viewer does not log an event at all when the Windows key is pressed.  

Is there anything known that would prevent this?  Everything works great on the built in keyboard but something is not detecting the modifier key.

**Comment by PWKad** [comment]
Ok just tested and the Apple keyboard is also not recognizing so will debug further!

**Comment by PWKad** [comment]
In case anyone lands here this was the issue - 

https://apple.stackexchange.com/questions/159723/mac-osx-not-automatically-remapping-windows-key-to-cmd

Before changing "Use FN as F key" I hit the F12 key apparently.

**Comment by orlando** [comment]
In case anyone comes here with the same problem. Make sure you didn't enable "Game Mode" or "Disable the windows key" mode on your keyboard. Had this issue with the kinesis gaming freestyle keyboard
