### ISSUE TITLE
Key mapping for EU-Keyboards

### ISSUE THREAD

**Issue by adstek** [tekezo/Karabiner-Elements#1778]
Using 12.2.0, "§" and " "<" problem still exists from this issue https://github.com/tekezo/Karabiner-Elements/issues/229

**Comment by gustafbstrom** [comment]
Same problem here, just commented on #591.

**Comment by makla-code** [comment]
Any news on this one? Can confirm that karabiner currently works fine with external ISO keyboard but has <> and $ swapped on internal ISO keyboard.

macOS 11.11
karabiner 13.1.0

**Comment by ksuuk** [comment]
> Any news on this one? Can confirm that karabiner currently works fine with external ISO keyboard but has <> and $ swapped on internal ISO keyboard.
> 
> macOS 11.11
> karabiner 13.1.0

Doesn't work automatically, manual fix is needed - https://github.com/pqrs-org/Karabiner-Elements/issues/229#issuecomment-382703513

**Comment by vilbergs** [comment]
I've managed to work around this by changing the country code to the layout I use when switching to the internal keyboard.

I made a crude script that helps me do this faster. If you happen to run Deno, here is the install command.

deno install  --allow-read --allow-env  --allow-write https://raw.githubusercontent.com/vilbergs/cli/main/change-karabiner-country-code.ts

You can find the code for the script [here](https://github.com/vilbergs/cli). PRs are welcome to make this more flexible for different country codes.
