### ISSUE TITLE
how to get the bundle identifier of an app/program

### ISSUE THREAD

**Issue by theonlygusti** [tekezo/Karabiner-Elements#1783]
I want to use the `frontmost_application_if` condition, I need the `bundle_identifier` for this.

I don't know how to get that?

How do I find out what the bundle identifier is for e.g. Osu running inside of wine, or Minecraft (which is a Java program, so do I use Java's bundle identifier—which I don't know—or something else) etc.

The easiest method would be if there was a way to get the bundle identifier for a window on my screen.

**Comment by mtwomey** [comment]
@theonlygusti You can use the EventViewer to see it (look on the "Frontmost Application" tab.

![image](https://user-images.githubusercontent.com/7715262/54959194-54b4d700-4f26-11e9-9df0-7ce3e2a9cccd.png)

**Comment by theonlygusti** [comment]
@mtwomey 's solution worked (I didn't know the EventViewer existed, it's super helpful).
