### ISSUE TITLE
Feature request: map home button to escape

### ISSUE THREAD

**Issue by deludologist** [tekezo/Karabiner-Elements#1784]
I am using a bluetooth keyboard developed for iOS on my Macbook, which has a "home button key" instead of an escape key. Could you add this, so I can map it to escape. Thanks!

**Comment by dnicolson** [comment]
It appears that the iOS home key also known as the "consumer home" key (`kHIDUsage_Csmr_ACHome`) is not recognised by Karabiner-Elements. I attempted to make a build to include this key but was unsuccessful.

You can use [BluetoothKeyboardEnhancer](https://github.com/dnicolson/BluetoothKeyboardEnhancer/) as an alternative, you will need to remove Karabiner-Elements as it seizes control of the keyboard input.
