### ISSUE TITLE
allowing "system software from developer" not working

### ISSUE THREAD

**Issue by hovzik** [tekezo/Karabiner-Elements#1785]
got a clean (new) macbook and trying to install karabiner.
macos 10.14
karabiner 12.2.0

1. when run first time, got a "system software from developer was blocked from loading".
2. successfully allowed it (no issues with invisible or inactive "Allow" button)
3. now every time i open Karabiner it says that system policy prevents loading the kernel extension...

<img width="1000" alt="Screenshot 2019-03-21 at 15 55 48" src="https://user-images.githubusercontent.com/16950920/54761770-02f11180-4bf3-11e9-9f71-9f6d85ce40e6.png">

4. but there aren't any new messages/requests in System Preferences about blocked software / developers

<img width="668" alt="Screenshot 2019-03-21 at 15 58 28" src="https://user-images.githubusercontent.com/16950920/54761992-8448a400-4bf3-11e9-9ab8-3e535cf8d9af.png">

- i've tried resetting the Gatekeeper with `sudo spctl --reset-default` -- didn't work
- i've tried whitelisting Karabiner from Gatekeeper with `spctl --add /Applications/Karabiner-Elements.app` -- didn't work

am i stupidly missing something or is this some kind of a bug?

**EDIT:** i have also tried getting the project from git and building it on my own, but it seems it's still built with the same developer id.
or at least it still didn't ask me for "System software from developer..." permission..

**Comment by Popl7** [comment]
I have exactly the same bug. Only on my private laptop. Not om my work laptop. Latest Macos. I will check the versions. Rebooting did not help

**Comment by bldh** [comment]
I was having this issue with the same version, it seems having chrome open when you go to authorise the application prevents you from clicking the button.

Hope this helps, solution was found in link below. :)

https://pqrs.org/osx/karabiner/help.html#kext-allow-button-does-not-work

**Comment by Popl7** [comment]
Thx for the tip, but I think this is not the same issue we have.
There is no button shown.
(also Chrome is not opened op my computer)

**Comment by manuelhubacher** [comment]
I’m experiencing the same issue. After a reboot, I got the Karabiner-Elements Alert, but no button to allow karabiner. Until yesterday, karabiner was working just fine. 

I’ve tried to reinstall according to the [karabiner elements documentation](https://pqrs.org/osx/karabiner/help.html#kext-allow-button-does-not-work). Unfortunately to no avail.

**Comment by hovzik** [comment]
ok, i'm not sure what might be the problem / solution here, but my mac got updated to 10.14.4 yesterday and Karabiner *just worked* without any errors or messages or popups.

**Comment by Popl7** [comment]
I just updated my MacOS to 10.14.4 and this did not help me.

**Comment by mikowl** [comment]
Any luck @Popl7 ? I'm having the same issues as well on my work macbook (currently running 10.14.3). I've tried everything including booting in safe mode but just don't see the "System software from developer..." message and button.

**Comment by hovzik** [comment]
i'm not sure if that'll help in any way but i've been trying various "solutions" i've found on the web..
`spctl --remove --label "org.pqrs.Karabiner-Elements.Preferences"`
`spctl --remove --label "Karabiner-Elements" /Applications/Karabiner-Elements.app`
`sudo spctl --reset-default`
those are all separate commands and i've tried all of them.. though, unfortunately, i don't know which one (if any) has helped..

**Comment by Popl7** [comment]
@mikowl no, sadly not.
I get the following errors when running spctl:
> spctl --remove --label "org.pqrs.Karabiner-Elements.Preferences"
error: unknown error 99999=1869f
> spctl --remove --label "Karabiner-Elements" /Applications/Karabiner-Elements.app
/Applications/Karabiner-Elements.app: unknown error 99999=1869f

I will try a reboot and running the commands in Recovery mode

**Comment by Popl7** [comment]
I have it working by deleting:
/Library/Application Support/org.pqrs
~/Library/Application Support/Karabiner

Hopefully this also works for you?

**Comment by Popl7** [comment]
I spoke too soon. Karabiner Elements starts up now. But it does not list any devices. Key changes also have no effect.

**Comment by manuelhubacher** [comment]
@hovzik and @Popl7: thanks for the hints. As in @Popl7’s case, they didn’t work for me. The Karabiner-Elements Alert is all I get. The strange thing is that everything works just fine on my other machine (iMac, macOS 10.14.4). Any more ideas?

**Comment by manuelhubacher** [comment]
I got Karabiner-Elements working again by adding the team identifier `G43BCU2T37`. (Thanks @begatsby for the hint. See #1800.) At first,  `spctl` wouldn't save the new configurations. So I started my mac in [recovery mode](https://support.apple.com/en-us/HT201314), opened the terminal and added the team identifier in recovery mode with `spctl kext-consent add G43BCU2T37`. Maybe it helps you, @Popl7?

**Comment by Popl7** [comment]
@manuelhubacher thx for the tip. This did work for me. I can now use Karabiner Elements on this laptop too :-)

**Comment by mikowl** [comment]
Thanks @manuelhubacher - that worked for me as well.

**Comment by CharlesYinchuDong-Acorns** [comment]
@manuelhubacher Yesterday I ran into the same issue for no reason. It's been driving me nuts for a whole day. Your solution saved my day!!!!

**Comment by nerdfiles** [comment]
> I got Karabiner-Elements working again by adding the team identifier `G43BCU2T37`. (Thanks @begatsby for the hint. See #1800.) At first, `spctl` wouldn't save the new configurations. So I started my mac in [recovery mode](https://support.apple.com/en-us/HT201314), opened the terminal and added the team identifier in recovery mode with `spctl kext-consent add G43BCU2T37`. Maybe it helps you, @Popl7?

does not work for me on 
catalina 10.15.6 (19G2021) 
karabiner 13.0.0

**Comment by tekezo** [comment]
@nerdfiles `kext-consent` has no effect with Karabiner-Elements v13.0.0, because v13.0.0 does not use kext.

If `macOS Catalina Note #1` on this following page does not solve issue, please use Karabiner-Elements v12.10.0 until upgrading to Big Sur.
https://karabiner-elements.pqrs.org/docs/help/troubleshooting/driver-alert-keeps-showing-up/

**Comment by risenforces** [comment]
M1 MacBook. Monterey 12.2.1. Karabiner 14.3.0.

I'm getting this alert every time I start Karabiner:

![CleanShot 2022-02-26 at 20 07 04@2x](https://user-images.githubusercontent.com/35740512/155852194-74d8eead-2f21-45f1-b787-4098eb9cd5c7.png)

And yeah, first time I pressed "Allow" and nothing happened.

Followed the instructions, did `csrutil disable`, re-installed, re-added `karabiner_grabber` and `karabiner_observer`, etc. - no effect.

Logs:

```
[2022-02-26 20:12:15.150] [warning] [virtual_hid_device_service] driver_version_ is mismatched: Karabiner-DriverKit-VirtualHIDDeviceClient expected: 10600, actual dext: std::nullopt
[2022-02-26 20:12:15.150] [warning] [virtual_hid_device_service] driver_version_ is mismatched: Karabiner-DriverKit-VirtualHIDDeviceClient expected: 10600, actual dext: std::nullopt
[2022-02-26 20:12:16.156] [warning] [virtual_hid_device_service] driver_version_ is mismatched: Karabiner-DriverKit-VirtualHIDDeviceClient expected: 10600, actual dext: std::nullopt
[2022-02-26 20:12:16.156] [warning] [virtual_hid_device_service] driver_version_ is mismatched: Karabiner-DriverKit-VirtualHIDDeviceClient expected: 10600, actual dext: std::nullopt
[2022-02-26 20:12:17.161] [warning] [virtual_hid_device_service] driver_version_ is mismatched: Karabiner-DriverKit-VirtualHIDDeviceClient expected: 10600, actual dext: std::nullopt
[2022-02-26 20:12:17.161] [warning] [virtual_hid_device_service] driver_version_ is mismatched: Karabiner-DriverKit-VirtualHIDDeviceClient expected: 10600, actual dext: std::nullopt
```
