### ISSUE TITLE
Karabiner-Elements stuck keys

### ISSUE THREAD

**Issue by SynVisions** [tekezo/Karabiner-Elements#1789]
Karabiner-Elements will periodically (after running for an extended time, say a day or so) end up in a state where a function key (e.g. Shift), or a number key (e.g. '4') is stuck held down.

I don't understand the reasoning or what triggers this. The only rule I have in Karabiner-Elements is just to change caps_lock to esc.

Restarting Karabiner-Elements fixes it.

Recent logs:

[logs.txt](https://github.com/tekezo/Karabiner-Elements/files/3010389/logs.txt)

**Comment by mganahl** [comment]
Same issue here. Runnig Karabiner-Elements 12.2.0.

**Comment by 0legg** [comment]
Same for me, most of the time it gets stuck on login screen, so I can't even enter the password

**Comment by yshavit** [comment]
I've only ever noticed this on the login screen. It seems to only happen when the computer has gone to sleep (as opposed to just being locked).

**Comment by wincent** [comment]
Probably a duplicate of https://github.com/tekezo/Karabiner-Elements/issues/1645

**Comment by yshavit** [comment]
Yeah, that's exactly the symptom I'm seeing.

**Comment by mayqiyue** [comment]
+1

**Comment by gevro** [comment]
Me too... happening multiple times.
