### ISSUE TITLE
Trying to add Copy/Paste key mapping to match like windows PC

### ISSUE THREAD

**Issue by balajeek** [tekezo/Karabiner-Elements#179]
I edited the configuration file as mentioned in the app, and tried to put Copy mapping

{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "Control+C" : "Command_L+C"
            }
        }
    ]
}

The error shows in the console:
[console_user_server] [warning] unknown key_code:Control+C in /Users/bala/.karabiner.d/configuration/karabiner.json

**Comment by talha131** [comment]
You can't do it until #16 is fixed.
