### ISSUE TITLE
Exiting application results in non-functioning MBP keyboard

### ISSUE THREAD

**Issue by bcallaars** [tekezo/Karabiner-Elements#1791]
When I exit KE after I took my external keyboard out, KE turns off - or so it seems - my internal keyboard, and I'm left with a non-functioning keyboard.

This has already been addressed in #626 , however this issue remains closed even though the problem still exists.

It is a vanilla install of KE with no custom settings done besides remapping the application to fn key for my external keyboard.

Can you let me know what you need from me to let this debug easier?

The log file can be found here: https://gist.github.com/bcallaars/32e39e10cef5c8088ac77c95818b3f8c

One other thing to note is that even though the application has been terminated, but the event viewer is open, the event viewer will still correctly record the incoming events of the buttons pressed, but nothing is translated on the screen. Not sure if that helps.

**Comment by adamdavis40208** [comment]
A recent mojave upgrade has made this bug a lot worse for me. I have to start the app to regain keyboard, and start/quit it a few times to have a working keyboard after closing the app. Happy to help debug, though I'm new to the project.
