### ISSUE TITLE
Playing sounds when keys are pressed

### ISSUE THREAD

**Issue by bland328** [tekezo/Karabiner-Elements#1793]
The only way I know of to make a keypress result in a sound is by executing `afplay` _(or whatever alternate command)_ as a `shell_command` in my Complex Modifications JSON.

Does anyone know of a way to play a sound _and_ still remap a key?

According to https://pqrs.org/osx/karabiner/json.html#to-event-definition, I can map to `key_code` _or_ `shell_command`, but not both.

**Comment by suliveevil** [comment]
Try remap a key and use shell_command at the same time.

#!/usr/bin/ruby

```json
"from": {
		"key_code": "t"
		},
"to": [
    {
	    "key_code": "t"
    },
	{
		"shell_command": "osascript -e 'tell application \"Alfred 3\" to run trigger \"repos\" in workflow \"net.deanishe.alfred-git-repos\" with argument \"\"'"
	}
]
```

The osascript is shell command too，and you can write AppleScript in it, enjoy it!

**Comment by jeshyr** [comment]
This could usefully be added to the documentation - currently the json reference manual just says  "key_code, consumer_key_code, pointing_button, shell_command, select_input_source and set_variable are exclusive. You can specify one of them." which is super unhelpful and somewhat misleading given there's an easy workaround
