### ISSUE TITLE
How to toggle Karabiner-Elements Disable Built-in Keyboard setting？

### ISSUE THREAD

**Issue by suliveevil** [tekezo/Karabiner-Elements#1798]
I want to toggle the `Disable Built-in Keyboard ` setting so that I can use **one keyboard at a time** and switch to another at the other time(never use them both at the same time).

Thank you for helping.

<img width="1112" alt="toggle_KE_setting" src="https://user-images.githubusercontent.com/35763237/55526595-4e61f000-56c8-11e9-884b-41dddb5aa5fe.png">

**Comment by suliveevil** [comment]
Are there some defaults write org.pqrs.Karabiner-Elements.Preferences disableBuiltInKeyboard Yes thing?

**Comment by tekezo** [comment]
`disable_built_in_keyboard_if_exists` in `karabiner.json`

**Comment by suliveevil** [comment]
Thank you very much. ☺️
