### ISSUE TITLE
Use letters as modifier

### ISSUE THREAD

**Issue by emadb** [tekezo/Karabiner-Elements#1799]
I would like to use letter "a" as a modifier to use i/j/k/l as arrows (es. a + j = left_arrow).
How can I do?

I already read the issue #831 but since it is a little bit old I'm investigating in new solutions.
thx

**Comment by zheeeng** [comment]
Have the same request, old Karabiner we could use `__BlockUntilKeyUp__ KeyCode::A` to simulate this feature.

**Comment by tekezo** [comment]
#831 is most suitable way.
https://pqrs.org/osx/karabiner/json.html#virtual-modifier

**Comment by tekezo** [comment]
You can do old `__BlockUntilKeyUp__` by using `key_up_order`.

Example:
https://github.com/pqrs-org/KE-complex_modifications/blob/master/src/json/personal_tekezo_simple_vi_mode.json.rb

Generated json:
https://github.com/pqrs-org/KE-complex_modifications/blob/master/docs/json/personal_tekezo_simple_vi_mode.json

**Comment by GanZhiXiong** [comment]
@em
Have you solved this problem? I also tried [Use any key as modifier · Issue #831 · pqrs-org/Karabiner-Elements](https://github.com/pqrs-org/Karabiner-Elements/issues/831) but it has a problem , That is, when a letter is quickly pressed, the letter will not be output, such as a as a modifier key, and then quickly pressing `a + j`, it will not output `aj`
