### ISSUE TITLE
Control_L to Control_L (+ when you type Control_L only, send Escape)

### ISSUE THREAD

**Issue by adhipg** [tekezo/Karabiner-Elements#18]
Is there a way I can get a command like that above working with the new JSON format?

**Comment by bosr** [comment]
https://github.com/tekezo/Karabiner-Elements/issues/8 :)

**Comment by gnapse** [comment]
Is it possible then?

**Comment by jsrozner** [comment]
Hi, Is this being worked on?

**Comment by jsrozner** [comment]
Or, maybe this should be closed as dupe of #8?

**Comment by delphinus** [comment]
This feature is implemented in a fork #247.

**Comment by seguri** [comment]
Sorry for adding noise. Is this feature implemented or I still need to install wwwjfy/Karabiner-Elements fork?

**Comment by bosr** [comment]
It is implemented in the latest karabiner-elements. You take can take guidance from the main README.md and docs.

**Comment by stuart-warren** [comment]
See https://pqrs.org/osx/karabiner/complex_modifications/#caps_lock 👍
