### ISSUE TITLE
^ and > keys exchanged

### ISSUE THREAD

**Issue by yakitofu** [tekezo/Karabiner-Elements#1805]
I’m using Karabiner Elements 11.6.0 on a MacBook Pro Mid-2009 with El Capitan and a German keyboard layout.

I made the following changes:
backspace <—> tab and
enter <—> caps_lock
No problem here.

However, somehow Karabiner also exchanges the ^ key with the > key. I do not know why this happens or how to change it back.

Can anyone help me out with this please? :)

**Comment by pat-s** [comment]
Apparently this issue still applies - is there a workaround?

**Comment by pat-s** [comment]
A workaround is to make the following changes

<img width="466" alt="image" src="https://user-images.githubusercontent.com/8430564/81652708-71ff7a00-9434-11ea-858a-281416957ec6.png">
