### ISSUE TITLE
Is it possible to insert emoji?

### ISSUE THREAD

**Issue by nikitavoloboev** [tekezo/Karabiner-Elements#1807]
Is there a keycode(s) we can use to insert emojis so Karabiner pastes them?

**Comment by nikitavoloboev** [comment]
Perhaps this can be done with unicode?

**Comment by nikitavoloboev** [comment]
I would love to add it as a feature request @tekezo if possible.

**Comment by tekezo** [comment]
I guess it's not impossible with unicode input like old Karabiner way.
https://pqrs.org/osx/karabiner/xml.html#tips-unicode-hex-input

However, it depends key input timing, I think it wolud be better creating new keylayout.
Did you try Ukelele? https://software.sil.org/ukelele/

**Comment by eugenesvk** [comment]
Know this is old and you might know the answer, but might be helpful to others since this issue title is easier to find
FYI a solution with AppleScript via clipboard (but it preserves the existing clipboard) https://github.com/pqrs-org/Karabiner-Elements/issues/2949#issuecomment-1318516074

Ukelele is awesome, but a bit more involved solution and less flexible

**Comment by Strajk** [comment]
Thanks everybody in this thread 👏
As it comes as a first result when googling for this problem, I'll add my solution for future visitors 👀

I've used Goku + Karabiner to quickly type favorite emojis by pressing `right option key + letter`

![image](https://user-images.githubusercontent.com/697301/218063251-84a173fc-c4ca-48c4-8363-1a642a21f26d.png)

Meta code:
```
:simlayers {
    :emoji-mode { :key :right_option }

:des "Emoji mode"
    :rules [
        :emoji-mode
            [:q [:paste "❓"]]
            [:w [:paste "💸"]]
            [:e [:paste "👀"]]
```

Whole code https://github.com/Strajk/setup/blob/cc87340f521befbba591bb6b0d0eec1ec7c0da44/home/.config/karabiner.edn
