### ISSUE TITLE
Logitech Gaming Software Not Working (macOS Sierra v0.90.44)

### ISSUE THREAD

**Issue by sungjp** [tekezo/Karabiner-Elements#181]
Similar to a previous issue with Logitech Control Center devices, Logitech Gaming Software devices aren't being recognized and all of my prescribed hotkeys on my G602 Mouse aren't working. I am on the latest version 0.90.44.  
Luckily, my external keyboard allows me to remap keys at the hardware level (using WASD V3 61-key) and I can use my mouse's hotkeys at the same time without Karabiner-Elements running; but it would still be nice to have software persist my configs.

**Comment by brujoand** [comment]
Same problem with a g-402.  I'm no osx developer but given that someone could point me to the relevant code I'll be happy to get my feet wet.

**Comment by brujoand** [comment]
#132 Seems relevant

**Comment by radium-v** [comment]
Howdy,

There's a similar issue with the [SteelSeries Engine 3](https://steelseries.com/engine). Since some of the mouse buttons are exposed as a keyboard device, my side buttons stop working when Karabiner-Elements is running.

![screen shot 2016-09-30 at 10 54 25 am](https://cloud.githubusercontent.com/assets/863023/18995902/530873c0-86fc-11e6-95c2-902ab4329c7d.png)

**Comment by Phantec** [comment]
Same on v0.90.45 and v0.90.46, can I somehow ignore Logitech devices? I tried to ignore vendor id 0x46D (Logitech) but I don't know where I should add that code. That would be workaround for me for now.

**Comment by Phantec** [comment]
ok I fixed it (workaround?)

just add:
```
    auto vendorId = hid.get_vendor_id();
    if (vendorId && *vendorId == 0x46d) {
      return;
    }
```
after:
```
    auto manufacturer = hid.get_manufacturer();
    if (manufacturer && *manufacturer == "pqrs.org") {
      return;
    }
```

in 4 places in device_grabber.hpp

**Comment by markandrewj** [comment]
Hey, there has been a recent update for the Logitech gaming software [http://support.logitech.com/en_us/software/lgs](http://support.logitech.com/en_us/software/lgs). The issue of it not starting and complaining about the firmware is fixed. However I still have issues with Karabiner stopping my mouse(G502) binds from working. I have my profiles stored on my mouse, when karabiner is enables I can't use mouse left/right to switch spaces, or other mission control bindings.

**Comment by tekezo** [comment]
Karabiner-Elements v0.90.58 has Devices tab in Preferences which allows you to exclude specific devices.
Please use the latest version and exclude your Logitech devices from the list in Devices tab.

**Comment by kpapiez** [comment]
Here is a solution to the problem (most lik
<img width="834" alt="screen shot 2017-01-30 at 8 17 16 pm" src="https://cloud.githubusercontent.com/assets/11652226/22450016/73c0c878-e729-11e6-93a6-8c4f1a03ebbb.png">
ely) if you have Karabiner Elements installed.

**Comment by rodalpho** [comment]
This just came up for me again in a reinstall-- I believe it would be very helpful for Karabiner to be disabled by default for Logitech gaming mice. Certainly at least the G502 which I can confirm does not work with it.

**Comment by RhLopez** [comment]
@kpapiez wow thank you!
