### ISSUE TITLE
After updating your version, running the make-package.sh script will not succeed.

### ISSUE THREAD

**Issue by btwise** [tekezo/Karabiner-Elements#1813]
After updating your version, running the make-package.sh script will not succeed.
The following information appears at the end of the script execution:
`clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple LLVM version 10.0.1 (clang-1001.0.46.3)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /var/folders/vy/s8kym4m11lv3pn4gkm12nfk40000gn/T/main-30916c.cpp
clang: note: diagnostic msg: /var/folders/vy/s8kym4m11lv3pn4gkm12nfk40000gn/T/main-30916c.sh
clang: note: diagnostic msg: /var/folders/vy/s8kym4m11lv3pn4gkm12nfk40000gn/T/main-30916c.crash
clang: note: diagnostic msg: 

********************

** BUILD FAILED **

The following build commands failed:
	CompileC build_xcode/build/karabiner_console_user_server.build/Release/karabiner_console_user_server.build/Objects-normal/x86_64/main.o src/main.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
make[2]: *** [build_xcode] Error 65
make[1]: *** [all] Error 2
make: *** [build] Error 2`

I don't know if this is due to the xcode version or because of your code problem.How to fix this error and let the compiler execute normally

**Comment by tekezo** [comment]
This build error is caused by Xcode 10.2 bug.
You have to use Xcode 10.1 to avoid this issue :-(

**Comment by btwise** [comment]
> 此生成错误是由Xcode 10.2错误引起的。
> 你必须使用Xcode 10.1来避免这个问题:-(

My xcode10.1 has been overwritten, it is very troublesome to re-download, can you modify your code to make it compatible with higher versions of xcode?

**Comment by btwise** [comment]
> This build error is caused by Xcode 10.2 bug.
> You have to use Xcode 10.1 to avoid this issue :-(

My xcode10.1 has been overwritten, it is very troublesome to re-download, can you modify your code to make it compatible with higher versions of xcode?

**Comment by btwise** [comment]
Can you open a localized language interface, I can add a language version for our country, which is better

**Comment by tekezo** [comment]
> can you modify your code

I don't know how to avoid the Xcode issue, unfortunately.

> localized language interface

Is it localized GUI?

I don't plan the localized GUI to avoid the maintenance of message catalog.
(I also understand the importance of localization because English is not my mother tongue.
But the maintenance takes time.)

I think usage for beginner written by native language is more reasonable on this project.

**Comment by btwise** [comment]
I mean, I am giving you translation and maintenance of my language.  don't need you to spend time on translation. Every time you upgrade, I have a translated xib file that can be sent to you in the project, or you Only open localized structures, such as using localization.strings，I am going to translate it

**Comment by btwise** [comment]
![WeChat77107e1b416ae83ba117d4ed895d1e8e](https://user-images.githubusercontent.com/38809560/56115681-873a7880-5f96-11e9-9efd-a7abed8cb772.png)
I am a Chinese user.

**Comment by AlecVercruysse** [comment]
I have the same issue:

```
The following build commands failed:
	CompileC build_xcode/build/karabiner_console_user_server.build/Release/karabiner_console_user_server.build/Objects-normal/x86_64/main.o src/main.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
make[3]: *** [build_xcode] Error 65
make[2]: *** [all] Error 2
make[1]: *** [build] Error 2

make: *** [package] Error 99
```

Is there a workaround for this? I do not have enough space to download an older version of Xcode. I am also on 12.2.

**Comment by geekkun** [comment]
Same issue

**Comment by SCENEE** [comment]
Xcode 10.2 bug looks fixed in Xcode 11 beta! However I encountered a code sign error as below.
```
    /usr/bin/codesign --force --sign - --entitlements /private/var/folders/m8/csd3ys1n7dj4k3xj00sqbhrr0000gn/T/ansible.bZUZpi/src/apps/Updater/build_xcode/build/Karabiner-Elements.build/Release/Karabiner-Elements.build/Karabiner-Elements.app.xcent --timestamp=none /private/var/folders/m8/csd3ys1n7dj4k3xj00sqbhrr0000gn/T/ansible.bZUZpi/src/apps/Updater/build_xcode/build/Release/Karabiner-Elements.app
/private/var/folders/m8/csd3ys1n7dj4k3xj00sqbhrr0000gn/T/ansible.bZUZpi/src/apps/Updater/build_xcode/build/Release/Karabiner-Elements.app: code object is not signed at all
In subcomponent: /private/var/folders/m8/csd3ys1n7dj4k3xj00sqbhrr0000gn/T/ansible.bZUZpi/src/apps/Updater/build_xcode/build/Release/Karabiner-Elements.app/Contents/Frameworks/Sparkle.framework
Command /usr/bin/codesign failed with exit code 1
```
