### ISSUE TITLE
Can't import complex rules from web

### ISSUE THREAD

**Issue by eternalnewb** [tekezo/Karabiner-Elements#1814]
I'm not able to import _any_ complex rules from https://pqrs.org/osx/karabiner/complex_modifications/

When I try, Karabiner opens to show the summary of the modification set, says success, and then displays the same basic examples that ship by default. 

I've attached screenshots of this sequence. 

Any ideas of how I could troubleshoot? Any workarounds like other ways to feed karabiner the modifications? Where is this data stored on disk so I can check permissions? 

For troubleshooting I've uninstalled and reinstalled (using karabiner's internal uninstall tool), tried different browsers, and tried a wide variety of modifications from the site. 

MacOS 10.14.4 (18E226)
MacBookPro13,2
Karabiner-Elements-12.2.0

![image](https://user-images.githubusercontent.com/1920747/56152814-4d5b7900-5f7a-11e9-99f1-1204f292e001.png)
![image](https://user-images.githubusercontent.com/1920747/56152817-4f253c80-5f7a-11e9-88a2-aa071aaa1395.png)
![image](https://user-images.githubusercontent.com/1920747/56152822-50ef0000-5f7a-11e9-8df6-7298dabef501.png)

Thank you I love karabiner and can't live without it

**Comment by tekezo** [comment]
I cannot reproduce this issue.

Please confirm `~/.config/karabiner/assets/complex_modifications` is a valid directory.

You can add the rules manually by running the following command on Terminal.

```
mkdir -p ~/.config/karabiner/assets/complex_modifications
cd ~/.config/karabiner/assets/complex_modifications
curl -O https://pqrs.org/osx/karabiner/complex_modifications/json/vi_mode_arrow.json
```

**Comment by eternalnewb** [comment]
Thank you so much, you've made my week!

**Comment by ekinig** [comment]
I have the same problem. The rules don't appear on the GUI using either the manual method or the automatic one.

**Comment by tonisives** [comment]
I had the same issue. There was no karabiner folder in .config. Would it make sense to create this folder if it doesn't exist?

**Comment by gazsp** [comment]
Same issue here. Even with the folder created, I can't import any rules.

▶ ls ~/.config/karabiner/assets/complex_modifications
ultimate_macOS.json

No rules show in the UI other than the example ones.

**Comment by MuhammedZakir** [comment]
> Same issue here. Even with the folder created, I can't import any rules.
> 
> ▶ ls ~/.config/karabiner/assets/complex_modifications
> ultimate_macOS.json
> 
> No rules show in the UI other than the example ones.

The issue is probably with "Ultimate MacOS" config itself -- https://github.com/pqrs-org/KE-complex_modifications/issues/716.

**Comment by gazsp** [comment]
@MuhammedZakir Thanks for that - I appreciate the heads up. I'll check out the link.
