### ISSUE TITLE
Keyboard unresponsive after quitting KE

### ISSUE THREAD

**Issue by mganahl** [tekezo/Karabiner-Elements#1816]
reboot fixed the problem. This has now happend a few times to me.
macos Mojave 10.14.4 on machbook pro 2018 (touchbar)

**Comment by tekezo** [comment]
I believe this issue is fixed at the latest beta.

How to upgrade to the latest beta version:
<https://pqrs.org/osx/karabiner/document.html#check-for-updates>

**Comment by rdewolff** [comment]
I have the whole macbook pro keyboard and touchpad not working sometimes. Sometimes a reboot doe fix it, sometimes not. Is this a known issue as well @tekezo ?

I had to uninstall the app :(

**Comment by rdewolff** [comment]
Not fixed. Whole computer keyboard and trackpad locked !
