### ISSUE TITLE
Don't work simultaneously pressing left & right clicks.

### ISSUE THREAD

**Issue by s-show** [tekezo/Karabiner-Elements#1817]
I want to launch LaunchPad by simultaneously pressing the left and right mouse clicks.
Therefore, I set it as follows.

```
{
  "description": "Simultaneous Right & Left Click Open LaunchPad",
  "manipulators": [
    {
      "type": "basic",
      "from": {
        "simultaneous": [
          {
            "key_code": "button1"
          },
          {
            "key_code": "button2"
          }
        ],
        "simultaneous_options": {
          "key_up_when": "any"
        }
      },
      "to": [
        {
          "key_code": "vk_launchpad"
        }
      ]
    }
  ]
}
```

However, if I simultaneously press the left and right mouse clicks, LaunchPad does not launch, and instead, the right click menu is displayed.
Doesn't Karabiner-Elements support simultaneous pressing of left and right mouse clicks?

**Comment by cyneo** [comment]
Hi s-show have, you tried changing the threshold for simultaneous?

Here is a snapshot of my json where I can adjust the thresholds. Typically 100ms is enough for me to get what I need, but feel free to play around to find your preference.
{
    "global": {
        "check_for_updates_on_startup": true,
        "show_in_menu_bar": true,
        "show_profile_name_in_menu_bar": false
    },
    "profiles": [
        {
            "complex_modifications": {
                "parameters": {
                    "basic.simultaneous_threshold_milliseconds": 50,
                    "basic.to_delayed_action_delay_milliseconds": 500,
                    "basic.to_if_alone_timeout_milliseconds": 1000,
                    "basic.to_if_held_down_threshold_milliseconds": 500,
                    "mouse_motion_to_scroll.speed": 100
                },
                "rules": [

**Comment by s-show** [comment]
@cyneo.
Thank you for comment.
First of all, I was wrong. The place which should has be set as "pointing_button" had set as "key_code".
Then, I configured "basic.simultaneous threshold milliseconds" at 500ms.
However, as before, the right-click menu is displayed instead of LaunchPad.
I configured "basic.simultaneous threshold milliseconds" at 1000ms, & 200ms etc, but the results did not change. 

```
{
  "description": "Simultaneous Right & Left Click Open LaunchPad",
  "manipulators": [
    {
      "type": "basic",
      "parameters": {
        "basic.simultaneous_threshold_milliseconds": 500
      },
      "from": {
        "simultaneous": [
          {
            "pointing_button": "button1"
          },
          {
            "pointing_button": "button2"
          }
        ]
      },
      "to": [
        {
          "key_code": "vk_launchpad"
        }
      ]
    }
  ]
}
```

**Comment by tekezo** [comment]
Your manipulator works well.

Did you enable your Mouse?
https://pqrs.org/osx/karabiner/document.html#configuration-devices

Or are you using another mouse driver such as SteerMouse?
Karabiner-Elements might conflict third vendor drivers.

**Comment by s-show** [comment]
@tekezo 
Thank you for comment.
I'm using "Logicool Gaming Mouse 'G304'".
I corrected the setting of "Device" referring to the comment, and the desired operation was realized.
Thank you for your help!

![screenshot-20190425-235403](https://user-images.githubusercontent.com/20755159/56746087-7bc92780-67b6-11e9-8085-749760d29787.png)
![screenshot-20190425-235408](https://user-images.githubusercontent.com/20755159/56746095-7ff54500-67b6-11e9-8eaa-9d6f6eeffb98.png)
