### ISSUE TITLE
KE overwriting keyboard layout to previous machine after installing Time Machine backup on new computer with different layout

### ISSUE THREAD

**Issue by b-d-m-p** [tekezo/Karabiner-Elements#1818]
Hi,  

I just went from a MBP with a US keyboard to a new one with a Japanese keyboard. I imported my backup from Time Machine, and now in the new on machine if KE is on, the keyboard layout is overridden with the old US layout, even if I reset it in the System Preferences. 

How can I make KE use the new Japanese layout?

Cheers

**Comment by tekezo** [comment]
Please set keyboard type while Karabiner-Elements is running.
https://pqrs.org/osx/karabiner/document.html#configuration-keyboard-type

**Comment by b-d-m-p** [comment]
Thanks!
