### ISSUE TITLE
New Update

### ISSUE THREAD

**Issue by yaseent** [tekezo/Karabiner-Elements#1822]
Hi,

this isn't an "issue" specifically, more just some clarification that I need,

In the latest update, it provides the following for newly-added features:
key_code, consumer_key_code and pointing_button supports a number value, e.g., "from": {"key_code": 175}.

I don't quite understand how this works? I've tried out the following in my karabiner.json file:
            "name": "Default profile",
            "selected": true,
            "simple_modifications": [
                {
                    "from": {
                        "key_code": "18"
                    },
                    "to": {
                        "key_code": "19"
                    }
                }
            ]

The MacOS key code for the number 1 is 18, and for the number 2, is 19. The above does nothing. I then try from: key_code 175 to "anything else". Typing in 175 also, does nothing. So what exactly does this specific update mean?

Thank you.

**Comment by tekezo** [comment]
The number is HID Usage (You can confirm on EventViewer).
For example, number 1 is 0x1e (== 30) and number 2 is 0x1f (== 31).

The following json changes number 1 key to number 2.
(You must not quote the number.)

```json
{
    "from": {
        "key_code": 30
    },
    "to": {
        "key_code": 31
    }
}
```
