### ISSUE TITLE
Help Needed: Create new modifiers

### ISSUE THREAD

**Issue by cyneo** [tekezo/Karabiner-Elements#1823]
I would like to set spacebar as a modifier for new keybinds. This is in effect to create the same effect as TouchCursor on Windows, where I can press and hold spacebar as a modifier after a customized delay. Is there a way to do this currently? Or does this need to be a feature request?

**Comment by tekezo** [comment]
Use a variable.
https://pqrs.org/osx/karabiner/json.html#virtual-modifier

**Comment by cyneo** [comment]
Thanks for the reply tekezo. I don't quite understand how to use it. Do I put it as a separate rule in my complex modifications? or does it have to be in the same rule that i wish to use it as a virtual modifier?

**Comment by cyneo** [comment]
I got it after placing creating a condition using variable with. Thanks for the help!

**Comment by tekezo** [comment]
FYI:
Simple Vi Mode is more complex example.
It changes `s+hjkl` to arrow only when `hjkl` key is released while `s` key is pressing.
(== It does not change `s key down, h key down, s key up, h key up` sequence.)
https://pqrs.org/osx/karabiner/complex_modifications/#personal_tekezo_simple_vi_mode

Source:
https://github.com/pqrs-org/KE-complex_modifications/blob/master/src/json/personal_tekezo_simple_vi_mode.json.rb

**Comment by cyneo** [comment]
Thanks for the additional resources. I am having some performance issues with the variable implementation due to thresholds. However, your simple Vi implementation bypasses that issue and gives me the functionality that I need. Thanks for the creative implementation!
