### ISSUE TITLE
Simple modifications have no effect and don't save

### ISSUE THREAD

**Issue by drkvogel** [tekezo/Karabiner-Elements#1829]
I've been using Karabiner-Elements to map `non_us_backslash` to `escape` successfully for many months, but suddenly the mapping has disappeared. I added it again, but it has no effect, and the mapping is lost when I quit Karabiner. I have the latest update, 12.3.0. 
<img width="1567" alt="Karabiner-fail" src="https://user-images.githubusercontent.com/903230/56958854-79aef200-6b43-11e9-8439-0a96de935600.png">

**Comment by Nic008888** [comment]
Same issue, did you find a fix?
