### ISSUE TITLE
Deactivating keys on a certain device

### ISSUE THREAD

**Issue by sasa** [tekezo/Karabiner-Elements#183]
I couldn't find this in the docs or examples.

My internal keyboard's E, R, and T keys are defect. They randomly go off every couple of minutes which is very annoying :-)

Like ttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttthistttttttttttttt

With Karabiner I used to be able to do this:

```
<deviceproductdef> 
  <productname>APPLE_INTERNAL_KEYBOARD</productname> 
  <productid>0x025a</productid> 
</deviceproductdef>

<item>
  <name>Kill defect keys</name>
  <identifier>private.deviceproductdef_kill_defect_keys</identifier>
  <autogen>__KeyToKey__ KeyCode::E, KeyCode::VK_NONE</autogen>
  <autogen>__KeyToKey__ KeyCode::R, KeyCode::VK_NONE</autogen>
  <autogen>__KeyToKey__ KeyCode::T, KeyCode::VK_NONE</autogen>
  <device_only>DeviceVendor::APPLE, DeviceProduct::APPLE_INTERNAL_KEYBOARD</device_only>
</item>
```

Since 0.90.44 KE recognizes devices again. So would this be possible again?

Cheers
Saša

**Comment by chrisyip** [comment]
My MBP couldn't recognize my external keyboard, I have to do some `Simple Modifications` to make it work, however, I'm not using external keyboard all the time, for example, taking my MBP to meeting room or coffee shop.

So, if Karabiner-Elements could automatically change profiles or activate / deactivate keys base on device would help me a lot!

**Comment by tekezo** [comment]
#369
