### ISSUE TITLE
Per application settings

### ISSUE THREAD

**Issue by jonaskello** [tekezo/Karabiner-Elements#1834]
This was originally requested in #137. This issue is now closed as stale and it seems no action was taken. This issue is just a re-request of the same feature.

It was also requested in these issues: #788, #748, #636, #610, #245. All of these issues was closed as duplicates of #137 but since #137 was closed without action I guess they still all apply?.

Here is a short description of the request from #788.

> Is it already possible to define mappings that are only active for a single application? (like <only> in the old Karabiner)

**Comment by rpringadi** [comment]
It's August 2020 I was hoping this feature is implemented. Here it is, ignored, marked as stale.

**Comment by babygau** [comment]
isn't it what you want?
[application condition](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/frontmost-application/)

**Comment by rpringadi** [comment]
@babygau That's right, thanks! It works as expected!
