### ISSUE TITLE
Numlock key cannot be mapped in the Karabiner-Elements

### ISSUE THREAD

**Issue by carrigmore** [tekezo/Karabiner-Elements#1838]
Previous issue is closed as stale, but this issue still exists. PC Numlock key cannot be mapped in latest app. This cause impact keyboard cannot toggle on Numlock function.

**Comment by carrigmore** [comment]
I am using a compact keyboard, the numpad won't work correctly until set Numlock on.
In previous Karabiner version, I can use following settings to achieve this:
KeyToKey KeyCode::KEYPAD_CLEAR, KeyCode::VK_IOHIKEYBOARD_TOGGLE_NUMLOCK

This selection VK_IOHIKEYBOARD_TOGGLE_NUMLOCK doesn't seem to exist in the Karabiner-Elements.

Could you implement this to achieve the same as the existing version? this feature is really useful for users using compact keyboard, as the num pad is disabled by default, without Karabiner, the number pad cannot be used properly.

Thanks a lot.

**Comment by bhsolberg** [comment]
I have the same problem. Using an external (generic USB) keyboard with my MacBook, the keypad there remains in NumLock mode. My functional need is to turn off NumLock so that I can rather use the keypad for cursor control. I see I currently can map from "keypad_num_lock" but not *to* anything that does anything with the NumLock state so I can use the keypad as cursor control. Help, please? (Or, if there's a standard way to map the "clear" event to toggling NumLock?)

**Comment by bhsolberg** [comment]
I see that the NumLock key works properly for the external USB keyboard when in Linux or Windows in Parallels. In OSX, it has no function as using the keypad only gives the number with OSX not recognizing the NumLock key to be able to switch to using the cursor keys on the keypad. 

So, the question remains - how do we turn off NumLock for an external USB keyboard in OSX?

**Comment by iamfnd** [comment]
Having the same issue as well, the NumPad keys are basically useless without a NumLock toggle.

**Comment by imasaru** [comment]
@bhsolberg Hello!
This may help you: https://github.com/pqrs-org/KE-complex_modifications/blob/master/docs/json/numpad.json

This script enables the use of the numeric keypad as arrow keys and features a Num Lock toggle.

Find it on [Karabiner-Elements complex_modification rules](https://pqrs.org/osx/karabiner/complex_modifications/).

**Comment by bhsolberg** [comment]
I finally got to try this, and it worked fine for OSX but broke it for Parallels VM (Linux). So I have to manually enable and disable this script when switching between VM and OSX in order for this to work. Why is the script needed in the first place, why doesn't OSX recognize a keyboard with keypad/arrow keys like the Microsoft and Linux VMs do?

Thanks,

Bjorn

**Comment by sbussetti** [comment]
I know this is closed, but for @bhsolberg 's benefit, it's because MacOS has no concept of numlock really at all.  Karabiner is basically emulating turning "Mouse Keys" on and off, in MacOS terms.

**Comment by bhsolberg** [comment]
> I know this is closed, but for @bhsolberg 's benefit, it's because MacOS has no concept of numlock really at all. Karabiner is basically emulating turning "Mouse Keys" on and off, in MacOS terms.

Thank you for the clarification @sbussetti . I guess the manual workaround is what will have to suffice, then. :)

**Comment by MuhammedZakir** [comment]
> I finally got to try this, and it worked fine for OSX but broke it for Parallels VM (Linux). So I have to manually enable and disable this script when switching between VM and OSX in order for this to work. [...]

You can use `frontmost_application_unless`[1] to exclude modifications when in specific apps and `frontmost_application_if`[1] to limit modifications to specific apps.

E.g. https://github.com/pqrs-org/KE-complex_modifications/blob/a1c2d9f3aa61aba94845a101bf16b75477178a5c/public/json/alacritty.json#L18-L25 -- this limits that particular rule to Alacritty.

[1] https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/frontmost-application/

**Comment by agustinliebana** [comment]
> @bhsolberg Hello!
> This may help you: https://github.com/pqrs-org/KE-complex_modifications/blob/master/docs/json/numpad.json
> 
> This script enables the use of the numeric keypad as arrow keys and features a Num Lock toggle.
> 
> Find it on [Karabiner-Elements complex_modification rules](https://pqrs.org/osx/karabiner/complex_modifications/).

The links doesn't work anymore... Can you share again the script? 

Thanks!

**Comment by MuhammedZakir** [comment]
> > @bhsolberg Hello!
> > This may help you: https://github.com/pqrs-org/KE-complex_modifications/blob/master/docs/json/numpad.json
> > This script enables the use of the numeric keypad as arrow keys and features a Num Lock toggle.
> > Find it on [Karabiner-Elements complex_modification rules](https://pqrs.org/osx/karabiner/complex_modifications/).
> 
> The links doesn't work anymore... Can you share again the script?
> 
> Thanks!

https://github.com/pqrs-org/KE-complex_modifications/blob/master/public/json/numpad.json

**Comment by fabiocapsouza** [comment]
In my case, I wanted to map the numlock key to the toggle numlock function because my keyboard, CM QuickFire TK, has a short layout that shares the keypad buttons with the directional arrow and function buttons (home, insert, etc).
By default, the numpad is OFF, so I have access to directional buttons but no keypad buttons and there is no way to toggle the numpad. The scripts shared by @MuhammedZakir would work 100% if all numpad keys shared both a directional and a keypad button, but it is not the case: the numbers 1 and 3 do not have an associated directional button, so Karabiner does not detect any keypress and they cannot be used.

**Comment by MuhammedZakir** [comment]
@fabiocapsouza: does your keyboard not send *any* event when you press buttons `1` and `3`? That feels strange tbh.

**Comment by fabiocapsouza** [comment]
@MuhammedZakir Yeah, buttons `1` and `3` do not send any event, neither on Karabiner-EventViewer's Main tab nor Unknown Events tab.
If you look at the [keyboard](https://3rd-strike.com/wp-content/uploads/2013/06/TK1.jpg), you'll see that keypad `1` and `3` do not have associated directional functions (written in white). Maybe the keyboard filters these keypresses via hardware when numlock is off?

**Comment by MuhammedZakir** [comment]
> Maybe the keyboard filters these keypresses via hardware when numlock is off?

Most probably, yes.

**Comment by allmails888** [comment]
> In my case, I wanted to map the numlock key to the toggle numlock function because my keyboard, CM QuickFire TK, has a short layout that shares the keypad buttons with the directional arrow and function buttons (home, insert, etc). By default, the numpad is OFF, so I have access to directional buttons but no keypad buttons and there is no way to toggle the numpad. The scripts shared by @MuhammedZakir would work 100% if all numpad keys shared both a directional and a keypad button, but it is not the case: the numbers 1 and 3 do not have an associated directional button, so Karabiner does not detect any keypress and they cannot be used.

just wondering if any solution in getting the number pad working for CM QuickFire TK keyboards has emerged? tried Keypad as Arrows (windows style) complex modification but no bueno. Believe a workaround in xml worked previously. just need a json version to work with current karabiner i guess https://geekhack.org/index.php?topic=39135.msg1583652#msg1583652
