### ISSUE TITLE
MacOS wrong letter(§ insead of `)

### ISSUE THREAD

**Issue by kkseven07** [tekezo/Karabiner-Elements#1840]
How to fix it?

**Comment by dozepih** [comment]
I have almost the same issue. Wrongs fine locally but in my RDP-sessions to Windows-machines, < becomes § and > ½. This button I'm pressing is to the right of Left-Shift (Swedish keyboard). When I quit Karabiner and reconnects, every key works as expected again. Is there something I can do as a work-around for this?
