### ISSUE TITLE
Ability to rename devices

### ISSUE THREAD

**Issue by ejdanderson** [tekezo/Karabiner-Elements#1841]
It would be great if we could rename devices under the devices tab. Small QOL improvement, but when trying out 3-4+ keyboards a lot have generic names.

**Comment by notrealdev** [comment]
+1

**Comment by fhemberger** [comment]
@tekezo Any chance to get this issue reopened?

My Cherry keyboard only shows up as `No product name (No manufacturer name)`. Tried to add `product` and `manufacturer` keys to `profiles.devices.identifiers` in `karabiner.json`, but that didn't work. 🙁

**Comment by jpollak-zynga** [comment]
+1

**Comment by nikolasgd** [comment]
+1

**Comment by jrhorn424** [comment]
+1
