### ISSUE TITLE
CAPS LOCK light indicator always activated

### ISSUE THREAD

**Issue by apptechgateway** [tekezo/Karabiner-Elements#1846]
Installed latest KE v12.4.0 and a day after updated macOS to 10.14.5. I noticed the Caps Lock key indicator is always activated but the effect is the exact opposite. If Caps Lock is on the keys are in lower case but when deactivated the keys in CAPS LOCK mode. I've tried reinstalling KE but to no avail.

**Comment by twisstosin** [comment]
I have this issue, any fix? @apptechgateway ?
