### ISSUE TITLE
Keyboard is ignored temporarily until key_code "caps_lock"

### ISSUE THREAD

**Issue by InfectedG** [tekezo/Karabiner-Elements#1847]
Hi, how I can reactivate my fucking caps lock key, when I press it, KE deactivates itself

**Comment by Believerd** [comment]
Same problem!!!

**Comment by ijoseph** [comment]
The manual says this occurs due to pressing keys before KE starts. This definitely isn't my experience, though… KE has been on for days, then it starts acting up like this suddenly.

**Comment by Believerd** [comment]
> The manual says this occurs due to pressing keys before KE starts. This definitely isn't my experience, though… KE has been on for days, then it starts acting up like this suddenly.
I tried to reboot and started KE after rebooting, but the problem was still there.

**Comment by Believerd** [comment]
I tried to reboot and started KE after rebooting, but the problem was still there.

**Comment by Believerd** [comment]
I changed the CapsLock key to letter'a' and I found if I press CapsLock key then it would type 'a' for the first time, but the next time if would show the same problem upon, then routine.
