### ISSUE TITLE
virtual_hid_device_client is not connected yet with latest macOS

### ISSUE THREAD

**Issue by aliktab** [tekezo/Karabiner-Elements#1852]
After the latest mac update Karabiner is showing "virtual_hid_device_client is not connected yet. Please wait for a while." in the log and is not working. 

Karabiner 12.4.0
macOS 10.14.5 (18F132)

**Comment by ndan** [comment]
I had the same problem which was fixed by updating to 12.14.2 (beta release)

Go to Karabiner-Elements -> Misc -> "Check for beta updates"

**Comment by tekezo** [comment]
It is a macOS problem.
Restarting macOS after macOS upgrade solves this issue.
