### ISSUE TITLE
Help changing mouse buttons 4 and 5 to "Move Space" function on MacOS

### ISSUE THREAD

**Issue by STVRK** [tekezo/Karabiner-Elements#1854]
Hi All,

I'm looking to map my 3rd party mouse buttons 4 and 5 to Change Desktop Left and Change Desktop Right on MacOS. The keyboard short cut for that is CTRL-LeftArrow and CTRL-RightArrow. I didn't see these options on the simple mods list.

Thanks in advanced!

**Comment by nguyenhimself** [comment]
For mapping mouse buttons, It'd be much easier if you have the free BetterTouchTools.
In this case, you have to do extra works:

1. Open Settings.app > Keyboard > Shortcuts > Mission Control and choose keyboard shortcuts to move left or right space
2. Open Karabiner-Elements and create a complex rule that map Mouse Button 4 and 5 to the shortcuts you picked above.

Like I said, it's more laborious. I'd advise getting BetterTouchTools to exclusively customize mouse buttons and trackballs.

**Comment by toshohirasawa** [comment]
May I know any update on this topic?
I tried to assign "CTRL-LeftArrow" to button4, but it does not work.

**Comment by querkmachine** [comment]
I was also looking for a way to do this. It took some looking, but it turns out there's already a script to do it in Karabiner's own repository: https://ke-complex-modifications.pqrs.org/#mouse_buttons_4_5_desktop_switch

Rest easy, Google-searcher.

**Comment by querkmachine** [comment]
> I've imported this button remapping button4 and button5 doesn't work for me 

Does pressing Control + Left/Right arrow work? 

All Karabiner does is map the buttons to that keyboard shortcut, so if you've changed or removed that shortcut in macOS's settings then it won't do anything.

**Comment by dnsoll0908** [comment]
> I was also looking for a way to do this. It took some looking, but it turns out there's already a script to do it in Karabiner's own repository: https://ke-complex-modifications.pqrs.org/#mouse_buttons_4_5_desktop_switch
> 
> Rest easy, Google-searcher.

thank you so much
It is so better to me

**Comment by EnTonyH** [comment]
It works, but still not the same as native gesture with touchap or mouse like genius that has prepared macro. 

Bug: When you "Drag n Drop" a file, you drag a file. Change desktop with this mouse button replacement. Drop the file. Nothing happens. It act as your desktop is not active. 

Spec: Macbook Air M1.  Mouse Roccat Pro Air.

Workaround solution?
When you want to drop a file on the desktop, left click or middle click with your mouse to "active the desktop" then you can drop the file.

Visual difference:
native: 
![native](https://user-images.githubusercontent.com/37444472/200027886-f20f363c-53cc-48c7-8874-a4dde0ecee5d.jpg)

mouse macro: 
![makro](https://user-images.githubusercontent.com/37444472/200027876-7b74ae23-1bb3-4c2e-84bd-5dc48cbc967b.jpg)
