### ISSUE TITLE
EventViewer hex key codes

### ISSUE THREAD

**Issue by Pgaudreau** [tekezo/Karabiner-Elements#1855]
Hello,

I saw in the last update that now the code would be shown in decimal, instead of hex, but could there be an option in the EventViewer-Preferences to switch from one to another? (I use it in QMK firmware)

Thank you,
Philip

**Comment by tekezo** [comment]
I've added an option at v12.4.3. (latest beta version)

![Screen Shot 2019-05-23 at 15 03 27](https://user-images.githubusercontent.com/659178/58229202-00827380-7d6c-11e9-98d8-679d9ed95584.png)

How to upgrade to the latest beta version:
<https://pqrs.org/osx/karabiner/document.html#check-for-updates>

**Comment by Pgaudreau** [comment]
Awesome, works like a charm, Thanks for the quick implementation :)
