### ISSUE TITLE
12.4.0 LED on caps lock doesnt work

### ISSUE THREAD

**Issue by Cupprum** [tekezo/Karabiner-Elements#1858]
I am trying to accomplish changing caps lock to F13, but green led light next to caps lock stops shining after i add option "to key" in simple modifiaction. I am using mojave 10.14.5. Macbook pro 13' 2018. I saw that this issue should be fixed since 12.2 but it still persist on my computer, tried restarting, also installing 12.2 and 12.4 again, also tried to install it via cask, nothing works.

**Comment by joelbudgor** [comment]
I am using the latest version of Karabiner (12.5.3) on Mojave (10.14.5) running on a Macbook Pro Retina circa late 2012, and for me the problems described in other closed threads, and described above persists, and has never ceased to be an issue. I have tried all of the subsequent releases that claim to have fixed the problem. The problem persists.
