### ISSUE TITLE
Complex Modification not working on macOS Mojave 10.14.4

### ISSUE THREAD

**Issue by nekofurball** [tekezo/Karabiner-Elements#1860]
The complex modification I use (being Control+LeftClick = LeftClick) doesn't work on the latest version (and beta version) of Karabiner-Elements.

I'm using an iMac 21.5" Late 2015 model if that's any help.
Rebooting did not solve my problem either.

Any help would be really appreciated.

_EDIT_: The complex modifications only work in Karabiner itself.
Globally, it doesn't work.

**Comment by CreeperMagnet** [comment]
I am also experiencing this issue. It's quite annoying, and this seems to be the only solution I can find. 


However, in my case, the complex modifiers work nowhere. Not in Karabiner, not anywhere else. I figured this out by going to the log and attempting to control-click, and it would highlight the section, which is what right-click does, so the modifier wasn't actually working *anywhere*.
