### ISSUE TITLE
Shift disable stopped working in most cases

### ISSUE THREAD

**Issue by rcdennis** [tekezo/Karabiner-Elements#1863]
I use Karabiner Elements to disable my left shift key entirely because of water damage that makes it appear always pressed. So from the hardware side, my left shift key does not work at all. After upgrading to 12.4.0 (I don't know what I had before), the disable still works when I type but not when I click. 
For example, every webpage I open opens in a new window, and when I try to select a new place in a text box, it highlights everything between where my cursor was and where I now clicked. 
When I press my command key for anything (like copy/paste or new tab), it does not work, and I get a pop-up notification in the bottom right corner of my screen that 
```Apple Internal Keyboard / Trackpad is ignored temporarily until {"key_code":"left_shift"} is pressed again.```
If I press cmd again, the popup stays the same except switches to {"key_code":"left_gui"}.
On a third press, the popup goes away. 
The entire time the popup is there, the shift-disable does not work at all, I type in all caps, etc. 

It seems like maybe shift-command disables keyboard grabbing? 
I have pasted my relevant logs below, this exact message is repeated dozens of times and it happens whenever I press my command key (3 times):
```
[2019-05-27 15:30:44.751] [warning] [grabber] Apple Internal Keyboard / Trackpad (device_id:4294968163) is ignored temporarily until {"key_code":"left_shift"} is pressed again.
[2019-05-27 15:30:44.752] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:4294968163) is ungrabbed.

[2019-05-27 15:30:45.291] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:4294968163) is grabbed.
[2019-05-27 15:30:45.375] [warning] [grabber] Apple Internal Keyboard / Trackpad (device_id:4294968163) is ignored temporarily until {"key_code":"left_gui"} is pressed again.
[2019-05-27 15:30:45.376] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:4294968163) is ungrabbed.

[2019-05-27 15:30:46.651] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:4294968163) is grabbed.
```

The blank lines are not actually there I added them to show when they are happening, (first, second, or third press of command)

**Comment by legel** [comment]
I’m having this same issue... happened after installing Mojave, where my .json file with a simple modification for “[my shitty key]: “out” in the default profile is now creating these exact same clusterfuck messages. Any solutions?

**Comment by legel** [comment]
**SOLVED**

I'm not exactly sure if it's a single thing I did, or if it actually required all of them, but after digging through forums, and resisting the urge to throw my computer at the wall, I did the following:

1. Add "Karabiner-Elements" to System Preferences -> Security & Privacy -> Accessibility -> "Allow the apps below to control your computer" (thanks to posters [here](https://github.com/tekezo/Karabiner-Elements/issues/1581))
2. Make sure you have the latest (beta) version.  In the Karabiner-Elements Preferences section, under Misc, "Check for beta updates". At the time of writing, the version is 12.4.8.  
3. Make sure your karabiner.json file is syntactically correct! I think mine was not for a while, because I was using old syntax that a Karabiner update somewhere seems to have broken... Here is a complete working .json file that really only does one thing for me: disables my backslash key.  You can probably copy this, and change whatever key you need to replace. Make sure it goes in the correct location of `/Users/[YourUserName]/.config/karabiner/karabiner.json` 

```
{
    "global": {
        "check_for_updates_on_startup": true,
        "show_in_menu_bar": true,
        "show_profile_name_in_menu_bar": false
    },
    "profiles": [
        {
            "complex_modifications": {
                "parameters": {
                    "basic.simultaneous_threshold_milliseconds": 50,
                    "basic.to_delayed_action_delay_milliseconds": 500,
                    "basic.to_if_alone_timeout_milliseconds": 1000,
                    "basic.to_if_held_down_threshold_milliseconds": 500,
                    "mouse_motion_to_scroll.speed": 100
                },
                "rules": []
            },
            "devices": [
                {
                    "disable_built_in_keyboard_if_exists": false,
                    "fn_function_keys": [],
                    "identifiers": {
                        "is_keyboard": true,
                        "is_pointing_device": false,
                        "product_id": 656,
                        "vendor_id": 1452
                    },
                    "ignore": false,
                    "manipulate_caps_lock_led": true,
                    "simple_modifications": [
                        {
                            "from": {
                                "key_code": "backslash"
                            },
                            "to": {
                                "key_code": "out"
                            }
                        }
                    ]
                }
            ],
            "fn_function_keys": [
                {
                    "from": {
                        "key_code": "f1"
                    },
                    "to": {
                        "consumer_key_code": "display_brightness_decrement"
                    }
                },
                {
                    "from": {
                        "key_code": "f2"
                    },
                    "to": {
                        "consumer_key_code": "display_brightness_increment"
                    }
                },
                {
                    "from": {
                        "key_code": "f3"
                    },
                    "to": {
                        "key_code": "mission_control"
                    }
                },
                {
                    "from": {
                        "key_code": "f4"
                    },
                    "to": {
                        "key_code": "launchpad"
                    }
                },
                {
                    "from": {
                        "key_code": "f5"
                    },
                    "to": {
                        "key_code": "illumination_decrement"
                    }
                },
                {
                    "from": {
                        "key_code": "f6"
                    },
                    "to": {
                        "key_code": "illumination_increment"
                    }
                },
                {
                    "from": {
                        "key_code": "f7"
                    },
                    "to": {
                        "consumer_key_code": "rewind"
                    }
                },
                {
                    "from": {
                        "key_code": "f8"
                    },
                    "to": {
                        "consumer_key_code": "play_or_pause"
                    }
                },
                {
                    "from": {
                        "key_code": "f9"
                    },
                    "to": {
                        "consumer_key_code": "fastforward"
                    }
                },
                {
                    "from": {
                        "key_code": "f10"
                    },
                    "to": {
                        "consumer_key_code": "mute"
                    }
                },
                {
                    "from": {
                        "key_code": "f11"
                    },
                    "to": {
                        "consumer_key_code": "volume_decrement"
                    }
                },
                {
                    "from": {
                        "key_code": "f12"
                    },
                    "to": {
                        "consumer_key_code": "volume_increment"
                    }
                }
            ],
            "name": "Default profile",
            "parameters": {
                "delay_milliseconds_before_open_device": 1000
            },
            "selected": true,
            "simple_modifications": [
                {
                    "from": {
                        "key_code": "backslash"
                    },
                    "to": {
                        "key_code": "out"
                    }
                }
            ],
            "virtual_hid_keyboard": {
                "country_code": 0,
                "mouse_key_xy_scale": 100
            }
        }
    ]
}

```

Notice above above, as well, the `simple_modifications` replacement occurs **twice**. For me, this hits both the "For all devices" and "Apple Internal Keyboard / Trackpad (No manufacturer name)" visible under "Target Device" in the Simple Modifications tab of Karabiner-Elements Preferences.

The best thing about all the shit above? It works. No need for a new computer.

**Comment by cube7707** [comment]
> **SOLVED**
> 
> I'm not exactly sure if it's a single thing I did, or if it actually required all of them, but after digging through forums, and resisting the urge to throw my computer at the wall, I did the following:
> 
> 1. Add "Karabiner-Elements" to System Preferences -> Security & Privacy -> Accessibility -> "Allow the apps below to control your computer" (thanks to posters [here](https://github.com/tekezo/Karabiner-Elements/issues/1581))
> 2. Make sure you have the latest (beta) version.  In the Karabiner-Elements Preferences section, under Misc, "Check for beta updates". At the time of writing, the version is 12.4.8.
> 3. Make sure your karabiner.json file is syntactically correct! I think mine was not for a while, because I was using old syntax that a Karabiner update somewhere seems to have broken... Here is a complete working .json file that really only does one thing for me: disables my backslash key.  You can probably copy this, and change whatever key you need to replace. Make sure it goes in the correct location of `/Users/[YourUserName]/.config/karabiner/karabiner.json`
> 
> ```
> {
>     "global": {
>         "check_for_updates_on_startup": true,
>         "show_in_menu_bar": true,
>         "show_profile_name_in_menu_bar": false
>     },
>     "profiles": [
>         {
>             "complex_modifications": {
>                 "parameters": {
>                     "basic.simultaneous_threshold_milliseconds": 50,
>                     "basic.to_delayed_action_delay_milliseconds": 500,
>                     "basic.to_if_alone_timeout_milliseconds": 1000,
>                     "basic.to_if_held_down_threshold_milliseconds": 500,
>                     "mouse_motion_to_scroll.speed": 100
>                 },
>                 "rules": []
>             },
>             "devices": [
>                 {
>                     "disable_built_in_keyboard_if_exists": false,
>                     "fn_function_keys": [],
>                     "identifiers": {
>                         "is_keyboard": true,
>                         "is_pointing_device": false,
>                         "product_id": 656,
>                         "vendor_id": 1452
>                     },
>                     "ignore": false,
>                     "manipulate_caps_lock_led": true,
>                     "simple_modifications": [
>                         {
>                             "from": {
>                                 "key_code": "backslash"
>                             },
>                             "to": {
>                                 "key_code": "out"
>                             }
>                         }
>                     ]
>                 }
>             ],
>             "fn_function_keys": [
>                 {
>                     "from": {
>                         "key_code": "f1"
>                     },
>                     "to": {
>                         "consumer_key_code": "display_brightness_decrement"
>                     }
>                 },
>                 {
>                     "from": {
>                         "key_code": "f2"
>                     },
>                     "to": {
>                         "consumer_key_code": "display_brightness_increment"
>                     }
>                 },
>                 {
>                     "from": {
>                         "key_code": "f3"
>                     },
>                     "to": {
>                         "key_code": "mission_control"
>                     }
>                 },
>                 {
>                     "from": {
>                         "key_code": "f4"
>                     },
>                     "to": {
>                         "key_code": "launchpad"
>                     }
>                 },
>                 {
>                     "from": {
>                         "key_code": "f5"
>                     },
>                     "to": {
>                         "key_code": "illumination_decrement"
>                     }
>                 },
>                 {
>                     "from": {
>                         "key_code": "f6"
>                     },
>                     "to": {
>                         "key_code": "illumination_increment"
>                     }
>                 },
>                 {
>                     "from": {
>                         "key_code": "f7"
>                     },
>                     "to": {
>                         "consumer_key_code": "rewind"
>                     }
>                 },
>                 {
>                     "from": {
>                         "key_code": "f8"
>                     },
>                     "to": {
>                         "consumer_key_code": "play_or_pause"
>                     }
>                 },
>                 {
>                     "from": {
>                         "key_code": "f9"
>                     },
>                     "to": {
>                         "consumer_key_code": "fastforward"
>                     }
>                 },
>                 {
>                     "from": {
>                         "key_code": "f10"
>                     },
>                     "to": {
>                         "consumer_key_code": "mute"
>                     }
>                 },
>                 {
>                     "from": {
>                         "key_code": "f11"
>                     },
>                     "to": {
>                         "consumer_key_code": "volume_decrement"
>                     }
>                 },
>                 {
>                     "from": {
>                         "key_code": "f12"
>                     },
>                     "to": {
>                         "consumer_key_code": "volume_increment"
>                     }
>                 }
>             ],
>             "name": "Default profile",
>             "parameters": {
>                 "delay_milliseconds_before_open_device": 1000
>             },
>             "selected": true,
>             "simple_modifications": [
>                 {
>                     "from": {
>                         "key_code": "backslash"
>                     },
>                     "to": {
>                         "key_code": "out"
>                     }
>                 }
>             ],
>             "virtual_hid_keyboard": {
>                 "country_code": 0,
>                 "mouse_key_xy_scale": 100
>             }
>         }
>     ]
> }
> ```
> 
> Notice above above, as well, the `simple_modifications` replacement occurs **twice**. For me, this hits both the "For all devices" and "Apple Internal Keyboard / Trackpad (No manufacturer name)" visible under "Target Device" in the Simple Modifications tab of Karabiner-Elements Preferences.
> 
> The best thing about all the shit above? It works. No need for a new computer.

Thx it actually worked!!!

**Comment by cube7707** [comment]
> The best thing about all the shit above? It works. No need for a new computer.

Thx it actually worked!!!

**Comment by sharooq15** [comment]
Even now I'm facing the same issue when I click on the key-code

**Comment by yatharth** [comment]
I was having the error every time I woke my Mac from sleep, but granting the Accessibility permission seems to be have fixed it.

This issue was also mentioned:

- https://github.com/pqrs-org/Karabiner-Elements/issues/1848#issuecomment-497571910 
- https://github.com/pqrs-org/Karabiner-Elements/issues/1844#issuecomment-504284368
