### ISSUE TITLE
12.4.0 registers ANSI keys but ISO-DE is configured

### ISSUE THREAD

**Issue by alien0matic** [tekezo/Karabiner-Elements#1864]
I have everything configured to have a german ISO-DE keyboard, but the new 12.4.0 version registers the ANSI QWERTY keys as keypresses instead.
I can type just fine, but the EventViewer ist showing the wrong keys and my complex modifications on keys like Ö or Ä aren't working anymore because of this.
This started with the update to 12.4.0 and was working before.

**Comment by tekezo** [comment]
The keylayout is not Karabiner-Elements issue.

Please check the following configuration:

- macOS configuration. https://pqrs.org/osx/karabiner/document.html#configuration-keyboard-type
- Your Input Source configuration.

Note:
EventViewer shows HID usage which are not related with charactor name of input source.
The HID usage is generally the key name of QWERTY layout (which are defined by USB-HID specification.)

**Comment by alien0matic** [comment]
The configurations are correct, only thing showing the wrong keys ist the EventViewer.

If this is intended behaviour, 12.4.0 broke my complex modifications somehow.
