### ISSUE TITLE
Weird window jumping/refocus behavior after Catalina beta update

### ISSUE THREAD

**Issue by ferologics** [tekezo/Karabiner-Elements#1868]
## Diagnosis
Hey, I updated to macOS Catalina `10.15 Beta (19A471t)` and the windows seem to be jumping back and forth, kinda refocusing as if alt tab was triggered but actually staying focused on the same app.

## Symptoms
This problem takes effect after some time, not immediately after karabiner elements is launched.

## Workaround
Just kill the karabiner elements daemon/app.

**Comment by yangchenlarkin** [comment]
My Karabiner becomes invalid after Catalina beta update. Did you have this kind of problem too?

**Comment by tinyalley** [comment]
> My Karabiner becomes invalid after Catalina beta update. Did you have this kind of problem too?

Follow these steps and u can solve that.

**Comment by benwoodward** [comment]
I've experienced this issue too, didn't realise it was Karabiner though. Often it happens while typing, the focussed app loses focus for a less than a second, I don't have any keyboard input and then focus returns to the app I was using.

**Comment by jeffkillian** [comment]
I'm encounter this upon upgrading to Catalina. When I force quit all karabiner processes the problem stops.
