### ISSUE TITLE
Changing right_control to fn is not working

### ISSUE THREAD

**Issue by myhirra** [tekezo/Karabiner-Elements#1869]
![image](https://user-images.githubusercontent.com/4364150/58890691-b27f4f80-871d-11e9-9747-84722de0fe0e.png)

**Comment by aleqx** [comment]
I'm on High Sierra 10.13.6 and it works for me, but i have both mappings

![](https://i.gyazo.com/f8d208dc0e6a2efee737caf92436cbed.png)

**Comment by myhirra** [comment]
Yes, I used HHKB before , and now I'm using Poker . I'd like change the habit to HHKB , so changing right Ctrl to FN is a best way .

I tried both mappings , but failed.

**Comment by myhirra** [comment]
I gave up Poker ... Retrying another HHKB ...
