### ISSUE TITLE
Can not select a device with macOS Catalina(version10.15 Beta)

### ISSUE THREAD

**Issue by tomu28** [tekezo/Karabiner-Elements#1871]
## Symptoms:
After updating to `macOS Catalina(version 10.15 Beta)`,the device can not be selected with `Modify events from this device`,and the operation of `Karabiner-Elements` does not work.
So, I reinstalled the latest version of `Karabiner-Elements`, but this symptoms did not recover.

<img width="994" alt="karabiner" src="https://user-images.githubusercontent.com/28621480/58950457-caaca880-87c9-11e9-9578-f82294313864.png">

**Comment by jaclla** [comment]
macOS Catalina(version 10.15 Beta) 目前所有功能都失效了，作者好像还没有支持最新版本macos

**Comment by tomu28** [comment]
@jaclla 
Oh, Thank you for giving me good advice.

**Comment by FengFeng-is-me** [comment]
作者上面有给方法，把几个东西添加到系统辅助权限里面就可以了。记住不要更新最新版，据说最新版可能会导致这个方法失效！

**Comment by FengFeng-is-me** [comment]
作者上面有给方法，把几个东西添加到系统辅助权限里面就可以了。记住不要更新最新版的app，据说最新版可能会导致这个方法失效！自己搜一下issue,里头作者给了具体解决方案

**Comment by tekezo** [comment]
#1867

**Comment by mrdoorland** [comment]
<img width="1096" alt="Screen Shot 2562-07-29 at 21 50 37" src="https://user-images.githubusercontent.com/53422823/62058333-7b27ad80-b24b-11e9-84fa-9473a22a2535.png">
<img width="800" alt="Screen Shot 2562-07-29 at 21 51 37" src="https://user-images.githubusercontent.com/53422823/62058404-95fa2200-b24b-11e9-897d-85516a0ce33c.png">

<img width="1097" alt="Screen Shot 2562-07-29 at 21 50 51" src="https://user-images.githubusercontent.com/53422823/62058440-a9a58880-b24b-11e9-9bff-0bd5062aa236.png">

**Comment by tomu28** [comment]
@mrdoorland 
Thank you for explaining carefully in the image!!
It became very comfortable key input.
