### ISSUE TITLE
How to implement pause as keycode?

### ISSUE THREAD

**Issue by nikitavoloboev** [tekezo/Karabiner-Elements#1872]
I want to implement a pause function in one of my bindings without resorting to AppleScript. Does Karabiner Elements provide a way to do subsecond/second pause as KeyCode?

I searched Karabiner JSON and didn't find a way to do this. I'm sure there should be though.

**Comment by mreiche** [comment]
Is there a way to pass raw custom key codes like:
```
"to": [
                {
                    "key_code": 18
                }
            ],
```
