### ISSUE TITLE
When I press caps lock it will show key up and key down the same time.

### ISSUE THREAD

**Issue by Believerd** [tekezo/Karabiner-Elements#1874]
![Screen Shot 2019-06-07 at 10 16 27 AM](https://user-images.githubusercontent.com/30063871/59077556-a1953080-890d-11e9-8f99-d0c358e84c1e.png)

When I press 'caps lock', it will show 'key_up' and 'key_down' at the same time.
But this problem won't show up on my bluetooth keyboarder.

**Comment by 4volodin** [comment]
> ![Screen Shot 2019-06-07 at 10 16 27 AM](https://user-images.githubusercontent.com/30063871/59077556-a1953080-890d-11e9-8f99-d0c358e84c1e.png)
> 
> When I press 'caps lock', it will show 'key_up' and 'key_down' at the same time.
> But this problem won't show up on my bluetooth keyboarder.

You know I have the same issues on my  hackintosh Lenovo IdeaPad s145 and also on HP 430g5.
Have you solved the problem?
I see the developer ignores you issue.....me too, it's so bad.... 
Thanks.

**Comment by 4volodin** [comment]
Reopen the issue please, may be the developer somewhen pays attention on our issue
