### ISSUE TITLE
Press and hold key activates modifier

### ISSUE THREAD

**Issue by rkparvat** [tekezo/Karabiner-Elements#1876]
Hello: I would like to create a command where e.g. pressing A types A, but long pressing A will trigger "option+A". Can this be done, I was able to do this in the old Karabiner but not in Karabiner elements.

**Comment by ea2809** [comment]
You can do it with `to_if_held_down`.

Example in the documentation: https://pqrs.org/osx/karabiner/json.html#typical-complex_modifications-examples-open-alfred-when-escape-is-held-down

**Comment by rkparvat** [comment]
Thanks for the email. I am not familiar with coding etc. Is there a guide to do this step by step. I would want to activate “option + letter” or “option + command + letter” when the letter is held down 

Ram
