### ISSUE TITLE
Karabiner Elements incorrectly defines keyboard type

### ISSUE THREAD

**Issue by y4rr** [tekezo/Karabiner-Elements#1878]
I have an ISO Apple Magic Keyboard.
In Karabiner Event Viewer, I see this on the "Variables" tab:
    "virtual_hid_keyboard_keyboard_type": "ansi"
I see this on the "Devices" tab:
    {
        "device_id": 4295582919,
        "is_karabiner_virtual_hid_device": false,
        "is_keyboard": false,
        "is_pointing_device": false,
        "location_id": 119541611,
        "manufacturer": "Apple",
        "product": "Magic Keyboard",
        "product_id": 615,
        "serial_number": "70-f0-87-20-0f-6b",
        "transport": "Bluetooth",
        "vendor_id": 76
    },

I didn't touch any setting involved keyboard type in Karabiner or anywhere else. macOS automatically determines the correct keyboard type and there's no option for me to change it manually.

This issue is still relevant and not solved btw:
A couple of months and several updates later the problem still remains.

Why is this issue closed? This issue has NOT been resolved at all!!! :(

_Originally posted by @OMA2k in https://github.com/tekezo/Karabiner-Elements/issues/1035#issuecomment-490018162_

**Comment by AlexLeaP** [comment]
I solved it: I just randomly entered a 7 as the keyboard country code in the tab "virtual keyboard". The Mac then says my keyboard is not identified, so I click on identify; asks me to press the key next to Shift; asks me to select between ANSI, ISO or JIS, I select ISO and tadaaaa everything fine again! Hope this helps someone else as well!
