### ISSUE TITLE
Key being triggered twice on single press

### ISSUE THREAD

**Issue by martinklepsch** [tekezo/Karabiner-Elements#1879]
I use [a config](http://sprunge.us/RMYkft) that maps left shift to opening parentheses and right shift to closing parentheses. (More detail on that in #158 & #416.)

At some point Karabiner starts triggering shift multiple times on a single key press. This doesn't happen immediately after starting Karabiner and restarting Karabiner fixes it for a while.

The issue appeared relatively recently which is why I now downgraded to version **12.1.0**, I think that might fix the issue but haven't been able to fully confirm that. Will keep this issue updated. 

```
eventType:key_down        code:229        name:right_shift     misc:
eventType:key_up          code:229        name:right_shift     misc:
eventType:key_down        code:229        name:right_shift     misc:
eventType:key_down        code:39         name:0               misc:
eventType:key_up          code:39         name:0               misc:
eventType:key_up          code:229        name:right_shift     misc:
```

**Comment by tekezo** [comment]
This behavior is intended.
You can suppress the duplicated modifier by using `lazy` as follows.

```json
{
    "description": "map left shift to opening parenthesis",
    "from": {
        "key_code": "left_shift",
        "modifiers": {
            "optional": [
                "any"
            ]
        }
    },
    "to": [
        {
            "key_code": "left_shift",
            "lazy": true,
            "modifiers": []
        }
    ],
    "parameters": {
        "basic.to_if_held_down_threshold_milliseconds": 300
    },
    "to_if_held_down": [
        {
            "key_code": "left_shift"
        }
    ],
    "to_if_alone": [
        {
            "key_code": "9",
            "modifiers": [
                "left_shift"
            ]
        }
    ],
    "type": "basic"
},                            
```

**Comment by martinklepsch** [comment]
Thank you, I'm not 100% sure yet if this is fixing the issue but I'll close this issue for now and reopen if it requires further attention! Thanks!

**Comment by martinklepsch** [comment]
Unfortunately the problem is still present. Without having any actual data it seems to occur particularly often when editing text inside Emacs. My full configuration can be found here: https://github.com/martinklepsch/dotfiles/blob/311eaec01bbe23ea6a62aff838f679cfc15f704b/config/karabiner/karabiner.json

**Comment by tekezo** [comment]
There are possible two reason.

1. You held right_shift down long time. (The right_shift is fired twice when to_if_held_down_threshold_milliseconds is elapsed.)
2. You move mouse between right_shift is pressed and released.

If right_shift is fired twice by the first reason, you can suppress it by increase the threshold as follows.

```
        "basic.to_if_held_down_threshold_milliseconds": 3000
```

**Comment by martinklepsch** [comment]
I've tried increasing the threshold as you suggested but the problem persists. My impression is that it gets worse the longer Karabiner Elements is running, i.e. shortly after restarting it it's mostly fine but hours later it would insert multiple parenthesis when trying to write a single uppercase letter.

Is there any more information I could provide that would help with understanding this problem?
