### ISSUE TITLE
Enable HHKB compatible Arrow Key Mode

### ISSUE THREAD

**Issue by martinweiss** [tekezo/Karabiner-Elements#188]
How do I do this in Karabiner-Elements?

**Comment by watsoncj** [comment]
Hi @martinweiss, I've done something very similar to get Vim arrows: https://github.com/watsoncj/Karabiner-Elements/commit/5531032a309fe99e7e153cb725b9f44a19da69c0

With some minor tweaking, you can get HHKB arrows.

**Comment by tockrock** [comment]
I've got a temporary solution while the app is being worked on.
I'm still on El Capitan, but looks like it's working for now.

https://github.com/tockrock/Karabiner-Elements/tree/HHKB-compatible-arrow-key-mode

Thanks for the tip @watsoncj !

**Comment by tockrock** [comment]
With the complex modifications now available in Karabiner Elements, I've written the configuration to enable this.

So far, it's for the arrow keys, page up/down, home/end.
I've also added the configuration for the media keys (volume up/down/mute/eject)

You should be able to import it from the below.
https://pqrs.org/osx/karabiner/complex_modifications/

Hope it's useful.

@tekezo Should be ok to close this issue.
