### ISSUE TITLE
How to register own key / key code

### ISSUE THREAD

**Issue by matnowak** [tekezo/Karabiner-Elements#1880]
Hello!

I'm struggling with some problem. I want to create own key code and name it **pupa** (i.e. `'key_code': 'pupa'` and set it instead of capslock), and use **pupa** as kinda HYPER one. I've seen solutions like "set hyper as all right modification keys", but I just want to have clear/new one for my experiments. I was trying to find it somewhere on the Internet, but I didn't saw anything like that.

Is it somehow possible in Karabiner?

**Comment by ea2809** [comment]
Have you thought using variables to fake your needs ('key code')? Like a hyper...

This is an example: https://pqrs.org/osx/karabiner/json.html#typical-complex_modifications-examples-change-right-shift-x2-to-mission-control

Another example (SpaceFN): https://pqrs.org/osx/karabiner/complex_modifications/json/spacefn.json

I hope it helps...
