### ISSUE TITLE
adjust brightness key doesn't work

### ISSUE THREAD

**Issue by ssh352** [tekezo/Karabiner-Elements#1882]
I use a MacBook Pro 2015, a Real force 86u keyboard and a dell u2718q monitor.

I can't get brightness adjustment to work. Volume up down work just fine though.

when I press F1 and F2 on the keyboard, event viewer shows this
<img width="821" alt="Screen Shot 2019-06-13 at 9 23 40 AM" src="https://user-images.githubusercontent.com/41779116/59396936-66877700-8dbd-11e9-9ab1-e613c19bacf3.png">

my karabiner settings. 
<img width="1005" alt="Screen Shot 2019-06-13 at 9 22 54 AM" src="https://user-images.githubusercontent.com/41779116/59396938-67200d80-8dbd-11e9-8016-2341a2c1ec8f.png">

keyboard->shortcut->display
<img width="658" alt="Screen Shot 2019-06-13 at 9 32 25 AM" src="https://user-images.githubusercontent.com/41779116/59397174-3be9ee00-8dbe-11e9-98d7-e3b9015fd7d8.png">

![img_0](https://user-images.githubusercontent.com/41779116/59397053-d0a01c00-8dbd-11e9-82c1-b458011dbb44.jpg)

**Comment by ssh352** [comment]
this setting comes with karabiner
<img width="989" alt="Screen Shot 2019-06-13 at 9 23 08 AM" src="https://user-images.githubusercontent.com/41779116/59400107-e23af100-8dc8-11e9-8fa3-6fb9472e5ebb.png">

**Comment by segawm** [comment]
I have the same issue.
I'm using MacBook Pro, Magic Keyboard, and LG UltraFine Display that supports native brightness adjust from Mac.

If I didn't use Karabiner, I can adjust the currently using display's brightness vie brightness adjustment key (f1/f2).
But if I'm using Karabiner with default setting, I can adjust only internal display's brightness even when using external display. IOW, I cannot adjust external display's brightness.

I think it's Karabiner issue.

**Comment by adamwinn** [comment]
I have this same issue with an LG UltraFine Display too.  I can't adjust the display brightness

**Comment by MingshiGao** [comment]
I have the same issue adjusting the brightness of external display. Things work perfectly fine if I quit Karabiner.

**Comment by fishnux** [comment]
@ssh352 can you re-open this issue?

In my case brightness adjustment works if I press the control key while clicking the brightness buttons. Without Karabiner I don't need to press the control key and everything works fine. I'm using a single monitor (external).

None of my Karabiner rules are related to brightness control.

**Comment by ssh352** [comment]
I can't reopen it, it is closed by the bot. Actually a lot of issues are closed automatically by the bot without being resolved.

**Comment by artem-sokolov** [comment]
After I manually changed settings for my external keyboard (and external keyboard only) it all works as expected on my setup (MacBook Pro 16", Magic Keyboard and LG UltraFine Display):

![image](https://user-images.githubusercontent.com/623621/80868535-51336980-8c69-11ea-835b-a4ea558dfdf9.png)

(make sure it says "**apple**\_display\_brightness\_..." or just play with other brightness options in case this doesn't work for you)

**Comment by ssh352** [comment]
> After I manually changed settings for my external keyboard (and external keyboard only) it all works as expected on my setup (MacBook Pro 16", Magic Keyboard and LG UltraFine Display):
> 
> ![image](https://user-images.githubusercontent.com/623621/80868535-51336980-8c69-11ea-835b-a4ea558dfdf9.png)
> 
> (make sure it says "**apple**_display_brightness_..." or just play with other brightness options in case this doesn't work for you)

congratulations, unfortunately it still doesn't work for my external monitor, Dell U2718Q

**Comment by ssh352** [comment]
This video solved the issue for me:
[How to use Brightness Keys on External Displays in macOS Catalina](https://youtu.be/fzZJDWWvJEM )

**Comment by edgartheunready** [comment]
Ok,@artem-sokolov's answer fixed it for me. With the target devices as Apple Wireless Keyboard, I was able to set it up to change monitor brightness, but was able to let the laptop keyboard still adjust the laptop screen brightness.
