### ISSUE TITLE
The application “Karabiner-Elements” can’t be opened.

### ISSUE THREAD

**Issue by marceloboeira** [tekezo/Karabiner-Elements#1883]
### Error 
<img width="450" alt="Screen Shot 2019-06-13 at 3 17 54 PM" src="https://user-images.githubusercontent.com/1898225/59471000-77041580-8dee-11e9-9f9c-c13ff425c791.png">

I have tried installing over the website, over `brew cask`, nothing seems to work, I always get this error `The application “Karabiner-Elements” can’t be opened.`.

Does anyone know the reason for this?

### System Info

```
Operating System: macOS 10.14.5 (18F203)
```

#### Processes Running

```shell
λ ps aux | grep karabiner                                                                                                                                                              

root  79751   0.0  0.0  5057552  10312   ??  Ss    3:14PM   0:06.47 /Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_observer
root  79747   0.0  0.0  4506824   8704   ??  Ss    3:14PM   0:00.76 /Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_grabber
```

**Comment by minrockli** [comment]
I had the same issue. Temp fixed by rolling back to Karabiner-Elements 12.4.0 https://pqrs.org/osx/karabiner/history.html.

I guess sth wrong in the 12.5.0 version.

**Comment by tekezo** [comment]
I guess it caused by wrong file permission. (An execution bit is dropped by some reason.)
It solves by this command.

```shell
ls -l /Applications/Karabiner-Elements.app/Contents/MacOS/Karabiner-Elements
sudo chmod 755 /Applications/Karabiner-Elements.app/Contents/MacOS/Karabiner-Elements
```

**Comment by marceloboeira** [comment]
@tekezo interestingly enough, that file doesn't exist on my package (within .app)

**Comment by tekezo** [comment]
Is censor process (e.g., antivirus software) running on your Mac and delete files by the process?

**Comment by marceloboeira** [comment]
could be, I'll double check.
