### ISSUE TITLE
何度も伝えているのに改善されない。

### ISSUE THREAD

**Issue by sarrie666** [tekezo/Karabiner-Elements#1886]
macOS version: macOS 10.14.4
Karabiner version: Karabiner-Elements 12.5.0
My Mac hardware: MacBook Pro 13" mid 2017
My keyboard hardware: MacBook Pro 13" mid 2017(US)

左右のコマンドキーを押し下げると、英数orかなにトグルできる設定にしているが、
この設定はコマンドキーを押し下げ続ける操作(コマンドキー長押し)を受け取ってくれない。

例えば、コマンドキー を押しながらメニューバーアイテムをドラッグしても本来なら移動できるはずが移動ができません。Karabiner-Elementsを無効にすると移動(コマンドキー を押したままカーソル操作)ができます。
（High Sierraでは問題なくコマンドキー長押しが反映される。）

もう一つの例は、コマンドキーを押しながらデスクトップファイルやフォルダなどをドラッグ＆ドロップすればグリッドに沿う形で整列されるはずが、Karabiner-Elementsが冒頭の設定にしていると出来ない。
Karabiner-Elementsを無効にすると整列できます。
（High Sierraでは問題なくコマンドキー 長押しが反映される。）

現状のKarabinerでは不便なため。やむなく「⌘英かな」を利用している。
メールでのご連絡、また、こちらにトピックを立ててお伝えしております。
https://github.com/tekezo/Karabiner-Elements/issues/1709
どうか改善されますように。

**Comment by 618116** [comment]
https://github.com/tekezo/Karabiner-Elements/issues/1693
こちらを参考してみてはどうでしょう。

**Comment by sarrie666** [comment]
無事解決に至りました。本当に有難うございます。

> #1693
> こちらを参考してみてはどうでしょう。
