### ISSUE TITLE
Mappings Randomly Stop Working, Have to Reinstall

### ISSUE THREAD

**Issue by andkvo** [tekezo/Karabiner-Elements#1888]
This is a great program. I can use my Microsoft Natural Ergonomic Keyboard 4000 without the frustration of having the command and alt keys being reversed. The problem is that every couple weeks Karabiner stops working. The mappings are still there, but the keys have reverted to their original behavior. Last time it happened, I had to completely uninstall and reinstall.

**Comment by mkleehammer** [comment]
Are you on the macOS Catalina beta by any chance?  If so it would be duplicate of #1885

**Comment by andkvo** [comment]
macOS Mojave

**Comment by andkvo** [comment]
![image](https://user-images.githubusercontent.com/7608479/61459753-730e6a80-a93b-11e9-983a-b7b48776eac1.png)

**Comment by andkvo** [comment]
![image](https://user-images.githubusercontent.com/7608479/61459806-8cafb200-a93b-11e9-909a-3fb941716900.png)

**Comment by andkvo** [comment]
It hasn't stopped working in a long time. This morning I switched to another account on the computer using "Fast User Switching" and, when I came back to my usual account, it had stopped.

**Comment by andkvo** [comment]
![image](https://user-images.githubusercontent.com/7608479/61460113-19f30680-a93c-11e9-8133-1ba1cf6dea03.png)
The restart button does not help.

**Comment by andkvo** [comment]
Luckily there was a beta update available. That installation process fixed it. I wonder if we could just get a "reinstall" button as a workaround.
