### ISSUE TITLE
caps lock indicator temporarily activated on focus change

### ISSUE THREAD

**Issue by kne42** [tekezo/Karabiner-Elements#1889]
When changing focus across different applications and focus-consuming components in web pages (e.g. a search bar), the caps lock indicator will briefly be activated even though caps lock itself is not.

MacOS version: Mojave 10.14.5
Karabiner Elements version: 12.5.0

Interesting example:
1. open application 1 (e.g. chrome) on 3 different desktops
2. open application 2 (e.g. mail) on one of these desktops
3. select application 2, giving focus to it. the indicator will light up
4. using the trackpad or keyboard shortcuts, change desktops
5. changing from a desktop with application 1 focused to one with application 2 focused with cause the indicator to light up or vice versa
6. changing from an application 1 desktop to another application 1 desktop will not cause the indicator to activate
7. close application 2 so that only application 1 is open
8. changing to/from any desktop will not cause the indicator to activate

**Comment by owst** [comment]
I am also seeing this with

MacOS version: Mojave 10.14.5
Karabiner Elements version: 12.7.0

I noticed it when right-clicking on the track pad in a text-area in Chrome.

Can this issue be re-opened?
