### ISSUE TITLE
any way to disable certain keys? 

### ISSUE THREAD

**Issue by arungurung** [tekezo/Karabiner-Elements#189]
I've got left_shift and left_control damaged by water which causes these two keys to be pressed all the time. So [grabber] gives warning that 'There are keys pressed down'.

I don't need these keys so instead of remapping them wish I could disable it.

**Comment by arungurung** [comment]
would 'vk_none' help?

**Comment by LAUNCHPOD** [comment]
I"M IN THE SAME BOAT WITH THE STUCK SHIFT KEY< ANY HELP WOULD BE APPRECIATED AS I WOULD LIKE TO DISABLE BOTH SHIFT KEYS AND THEN MAKE FN THE NEW SHIFT KEY> IVE TRIED A TON OF DIFFERENT COMBOS IN ELEMENTS BUT TO NO AVAIL THANKS A TON>

**Comment by TroySK** [comment]
vk_none doesn't work. Looking at the code I figured "out" should work. This is my json config which works.

`
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "backslash": "out"
            }
        }
    ]
}
`
