### ISSUE TITLE
macOS keyboard and trackpad not working even after uninstall

### ISSUE THREAD

**Issue by rdewolff** [tekezo/Karabiner-Elements#1891]
There seems to be some major issues.
Am using macOS 10.14.5.

During usage of Karabiner Elements, I had some random internal trackpad and mousepad not working. 
External mouse and keyboard does work fine. 

Decided to remove the software to solve the issue : not working either.

Even rebooting does not work. But when I start the computer with `option` key held down, the keyboard and mouse just work fine!

I suspect this software has an issue somewhere.

Am doing a whole re-install to get my macbook pro working again 👎

**Comment by tekezo** [comment]
I guess this issue is a hardware or firmware problem.

If you faced this issue again without Karabiner-Elements,
try PRAM and NVRAM reset.
<http://support.apple.com/kb/ht1379>

**Comment by rdewolff** [comment]
You might be right. Checking with App Store Genius Bar.
