### ISSUE TITLE
menuicon invisible

### ISSUE THREAD

**Issue by janstieler** [tekezo/Karabiner-Elements#1896]
Hi,
is it possible to make the menuicon invisible?

Cheers

**Comment by ea2809** [comment]
There is an option:

<img width="1112" alt="KE_dis" src="https://user-images.githubusercontent.com/9999104/59976783-5fd0df00-95c9-11e9-99d3-a2a4771d0409.png">

**Comment by janstieler** [comment]
Thank you very much. I think I have it overread.
