### ISSUE TITLE
How to assign a right click to a key?

### ISSUE THREAD

**Issue by politicus** [tekezo/Karabiner-Elements#1899]
I looked for it but can't seem to find the RightClick option in "Simple modifications".

**Comment by ea2809** [comment]
I have tried with button2, can you try it?

**Comment by politicus** [comment]
It works. Thank you. 

With this, the right click contextual menu opens where the mouse is, not where the folder, file is selected. Which is what I was looking for.

I think I will keep using Alfred actions as the right click contextual menu has more or less the same items.  But I can launch Alfred actions via a keyboard shortcut.
