### ISSUE TITLE
How to set right_shift = command+space?

### ISSUE THREAD

**Issue by jinjian1991** [tekezo/Karabiner-Elements#19]
How to set right_shift = command+space?

**Comment by talha131** [comment]
You can't until #16 is fixed.

**Comment by oylbin** [comment]
keep on watching this.

**Comment by oylbin** [comment]
@jinjian1991 

check [this comment](https://github.com/tekezo/Karabiner-Elements/issues/16#issuecomment-249506498)

**Comment by jerryjune** [comment]
I guess you want to switch input source. But you cannot map shift to command space to do that. Following is an example to switch between  sogou input and ABC keyboard. Pay attentation to the input_source_id is for keyboard layout and input_mode_id is for some input software(for example chinese sogou). You can get this information from ~/Library/Preferences/com.apple.HIToolbox.plist
This script is modfied on these two offical examples
[example_input_source.json](https://github.com/pqrs-org/KE-complex_modifications/blob/master/docs/json/example_input_source.json)
[example_select_input_source.json](https://github.com/pqrs-org/KE-complex_modifications/blob/master/docs/json/example_select_input_source.json)
```
{
    "description": "LeftShift to Switch Input Source",
    "manipulators": [
        {
            "conditions": [
                {
                    "type": "input_source_if",
                    "input_sources": [
                        {
                            "language": "en"
                        }
                    ]
                }
            ],
            "type": "basic",
            "from": {
                "key_code": "left_shift",
                "modifiers": {
                    "optional": [
                        "any"
                    ]
                }
            },
            "to": [
                {
                    "key_code": "left_shift",
                    "lazy": true
                }
            ],
            "to_if_alone": [
                {
                    "select_input_source": {
                        "input_mode_id": "com.sogou.inputmethod.pinyin"
                    }
                }
            ]
        },
        {
            "conditions": [
                {
                    "type": "input_source_unless",
                    "input_sources": [
                        {
                            "language": "en"
                        }
                    ]
                }
            ],
            "type": "basic",
            "from": {
                "key_code": "left_shift",
                "modifiers": {
                    "optional": [
                        "any"
                    ]
                }
            },
            "to": [
                {
                    "key_code": "left_shift",
                    "lazy": true
                }
            ],
            "to_if_alone": [
                {
                    "select_input_source": {
                        "input_source_id": "com.apple.keylayout.ABC"
                    }
                }
            ]
        }
    ]
}
```

**Comment by bao3** [comment]
Thanks @jerryjune , it's great . Now I could switch input source between RIME and apple.US .

**Comment by uhayate** [comment]
@jerryjune it's great.

**Comment by oylbin** [comment]
Thanks @jerryjune .
I struggled for an hour and finally found the slightly difference between `input_source_id ` and `input_mode_id ` 😭 

I will list my config below in case it can help someone use ”U.S.“  and "Pinyin - Simplified" like me:

        {
            "description": "LeftShift to Switch Input Source",
            "manipulators": [
                {
                    "conditions": [
                        {
                            "input_sources": [
                                {
                                    "input_source_id": "com.apple.keylayout.US"
                                }
                            ],
                            "type": "input_source_unless"
                        }
                    ],
                    "from": {
                        "key_code": "left_shift",
                        "modifiers": {
                            "optional": [
                                "any"
                            ]
                        }
                    },
                    "to": [
                        {
                            "key_code": "left_shift"
                        }
                    ],
                    "to_if_alone": [
                        {
                            "select_input_source": {
                                "input_source_id": "com.apple.keylayout.US"
                            }
                        }
                    ],
                    "type": "basic"
                },
                {
                    "conditions": [
                        {
                            "input_sources": [
                                {
                                    "input_mode_id": "com.apple.inputmethod.SCIM.ITABC"
                                }
                            ],
                            "type": "input_source_unless"
                        }
                    ],
                    "from": {
                        "key_code": "left_shift",
                        "modifiers": {
                            "optional": [
                                "any"
                            ]
                        }
                    },
                    "to": [
                        {
                            "key_code": "left_shift"
                        }
                    ],
                    "to_if_alone": [
                        {
                            "select_input_source": {
                                "input_mode_id": "com.apple.inputmethod.SCIM.ITABC"
                            }
                        }
                    ],
                    "type": "basic"
                }
            ]
        }

**Comment by SYKoh** [comment]
@oylbin oh my gosh, I almost cry

before I met this issue page, I was confused by the ramdom switch of input method using ctrl+space

by following your script, I improved my script, and now it works sooo good

my script behavies: switch input method when press capslock alone, held ctrl when capslock held down

```
{
    "title": "",
    "rules": [
        {
            "description": "switch input method when press capslock alone, held ctrl when capslock held down",
            "manipulators": [
                {
                    "conditions": [
                        {
                            "input_sources": [
                                {
                                    "input_source_id": "com.apple.keylayout.ABC"
                                }
                            ],
                            "type": "input_source_unless"
                        }  
                    ],
                    "type": "basic",
                    "from": {
                        "key_code": "caps_lock"
                    },
                    "to": [
                        {
                            "key_code": "left_control",
                            "lazy": true
                        }
                    ],
                    "to_if_alone": [
                        {
                            "select_input_source": {
                                "input_source_id": "com.apple.keylayout.ABC"
                            }
                        }
                    ]
                },
                {
                    "conditions": [
                        {
                            "input_sources": [
                                {
                                    "input_source_id": "com.apple.inputmethod.SCIM.ITABC"
                                }
                            ],
                            "type": "input_source_unless"
                        }  
                    ],
                    "type": "basic",
                    "from": {
                        "key_code": "caps_lock"
                    },
                    "to": [
                        {
                            "key_code": "left_control",
                            "lazy": true
                        }
                    ],
                    "to_if_alone": [
                        {
                            "select_input_source": {
                                "input_source_id": "com.apple.inputmethod.SCIM.ITABC"
                            }
                        }
                    ]
                }
            ]
        }
    ]
}
```

and from the official doc I learned that you can found your input method now in Karabiner EventViewer  
[investigate-the-input-source-identifiers](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to/select-input-source/#investigate-the-input-source-identifiers)
