### ISSUE TITLE
Communicate with KE through API

### ISSUE THREAD

**Issue by Sebas-h** [tekezo/Karabiner-Elements#1904]
Hi,

Is it possible to communicate with KE through an API of some sorts?
My overall goal is to convert remote input to complex shortcuts (for which I would like to leverage KE).

Possible solutions I thought might work:
- Communicate with karabiner_grabber and inject events that way.
- Create own Karabiner VirtualHIDDevice to create keyboard events, which seems more difficult.

Any ideas? Thanks in advance :)

**Comment by jespertheend** [comment]
I need this as well, did you find a solution?
I want to do complex mappings that don't seem possible with the current rule system.
