### ISSUE TITLE
Mouse cursor acceleration in mouse keys mode

### ISSUE THREAD

**Issue by spieden** [tekezo/Karabiner-Elements#1907]
In Karabiner Classic the mouse pointer would accelerate the longer you held down the keys to move it. This doesn't appear to be the case in Karabiner-Elements. Also, tools for tweaking mouse acceleration at the macOS level won't work because Karabiner appears to use a series of short virtual cursor moves at the same speed.

Does this sound correct? Was the feature left out on purpose and/or is it feasible to add it back? I'd be willing to work on a patch given some guidance.

Thanks!

**Comment by snipem** [comment]
@spieden Any update on this? Have you had luck enabling it? I'm also looking for the feature and this is the only thing I found.

**Comment by borislopezaraoz** [comment]
Please reopen this issue.
Controlling the mouse with the keyboard is not very precise without acceleration.

**Comment by pavelz** [comment]
just came up on this, surprised that mouse acceleration is missing.
