### ISSUE TITLE
Can't uninstall Karabiner

### ISSUE THREAD

**Issue by nadeauhugo** [tekezo/Karabiner-Elements#1908]
HI. I use mac osx Mojave and I just installed Karabiner. I was not really in need of it, so I tried to uninstall using appcleaner and I JUST CAN'T. It seems I don't have the permission, but I use an admin account. What is going on here?

**Comment by nadeauhugo** [comment]
Of course, when I press command + i, strange behaviour appear, like there is a greyed out lock, it seems that I have the permission over the file, but obviously I don't.

**Comment by WangYuLue** [comment]
I have the same problem

**Comment by WangYuLue** [comment]
When I kill the related process, it will restart

**Comment by danbaggett** [comment]
Same. This software behaves like malware.

**Comment by nadeauhugo** [comment]
Finally, I found an option within the application that allow it to be
installed correctly. Just look for it within the application preferences.

Hugo



www.hugonadeau.com
<http://www.hugonadeau.com>
Projet Citoyen Modèle / Model citizen project
Édifice H. Nadeau pour la poésie (EH)
Conspiration H1N1 / H1N1 conspiracy
Ligue Hugo Nadeau (LHN) / Hugo Nadeau League (HNL)
Centre d'Art Caché d'Hugo pour l'Éternité (CACHE)


Le ven. 5 juil. 2019 à 11:57, danbaggett <notifications@github.com> a
écrit :

**Comment by Nic-Scopely** [comment]
I'm seeing this issue, I cannot uninstall karabiner, and I agree with a previous comment that this software behaves like malware. It should uninstall as simply as dragging the app into the trash can on MacOS.

**Comment by tekezo** [comment]
Karabiner-Elements files are installed to /Library/Application Support.
https://pqrs.org/osx/karabiner/help.html#installed-files

Thus we have to use uninstaller to uninstall these files.
https://pqrs.org/osx/karabiner/document.html#uninstall

**Comment by mbonne** [comment]
Same issue here. 

> Same. This software behaves like malware.

**Comment by tekezo** [comment]
Read this page https://karabiner-elements.pqrs.org/docs/manual/operation/uninstall/

**Comment by mbonne** [comment]
> https://pqrs.org/osx/karabiner/document.html#uninstall

Please make sure you use active links.
https://karabiner-elements.pqrs.org/docs/manual/operation/uninstall/

**Comment by mbonne** [comment]
> https://pqrs.org/osx/karabiner/document.html#uninstall

Please make sure you use active links.
https://karabiner-elements.pqrs.org/docs/manual/operation/uninstall/

by the way, uninstaller leaves behind:
/Library/LaunchAgents/org.pqrs.karabiner.agent.karabiner_grabber.plist
/Library/LaunchAgents/org.pqrs.karabiner.agent.karabiner_observer.plist
/Library/Application Support/org.pqrs

**Comment by tekezo** [comment]
It's strange... LaunchAgents files should be removed by uninstaller.

Some files are remain such as plist file.
If you want to remove them, please check the installed files list and remove it by hand.
You can remove these files without `chflags` command.
(I'm locking the Karabiner-Elements.app by `chflags` in order to ensure using uninstaller to remove these system files. Thus, other files are not locked.)
https://karabiner-elements.pqrs.org/docs/help/advanced-topics/installed-files/

**Comment by mbonne** [comment]
> It's strange... LaunchAgents files should be removed by uninstaller.
> 
> Some files are remain such as plist file.
> If you want to remove them, please check the installed files list and remove it by hand.
> You can remove these files without `chflags` command.
> (I'm locking the Karabiner-Elements.app by `chflags` in order to ensure using uninstaller to remove these system files. Thus, other files are not locked.)
> https://karabiner-elements.pqrs.org/docs/help/advanced-topics/installed-files/

Thanks for reply, I was trying to use chflags to unlock the .app before removal.
All removed now. I had installed as a test due to UAKEL approval automation for a client.

Cheers.

**Comment by XuanyuHu** [comment]
https://karabiner-elements.pqrs.org/docs/manual/operation/uninstall/

I used 
sudo '/Library/Application Support/org.pqrs/Karabiner-Elements/uninstall_core.sh' 
to uninstall the app sucessfully.

**Comment by mattbrambilla** [comment]
> Read this page https://karabiner-elements.pqrs.org/docs/manual/operation/uninstall/

This work for me!
I used CLI: 
```
bash '/Library/Application Support/org.pqrs/Karabiner-DriverKit-VirtualHIDDevice/scripts/uninstall/deactivate_driver.sh'
sudo '/Library/Application Support/org.pqrs/Karabiner-Elements/uninstall.sh'
```
