### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by benjamin-holcombe** [tekezo/Karabiner-Elements#1910]
Longtime Windows user new to macOS.  Not sure how to interpret the build failure, looking for some guidance.

Mojave 10.14.5
Xcode 10.2.1

clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /var/folders/tp/lnm8kpmn3kzbzjpnsxdxj5cm0000gp/T/main-89096f.cpp
clang: note: diagnostic msg: /var/folders/tp/lnm8kpmn3kzbzjpnsxdxj5cm0000gp/T/main-89096f.sh
clang: note: diagnostic msg: Crash backtrace is located in
clang: note: diagnostic msg: /Users/benholocombe/Library/Logs/DiagnosticReports/clang_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
clang: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
clang: note: diagnostic msg: 

********************

** BUILD FAILED **

The following build commands failed:
	CompileC build_xcode/build/karabiner_console_user_server.build/Release/karabiner_console_user_server.build/Objects-normal/x86_64/main.o src/main.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
make[3]: *** [build_xcode] Error 65
make[2]: *** [all] Error 2
make[1]: *** [build] Error 2

make: *** [package] Error 99

**Comment by tekezo** [comment]
https://github.com/tekezo/Karabiner-Elements/issues/1813#issuecomment-483135212

Xcode 10.3 beta also seems to solve this issue.
