### ISSUE TITLE
KE crash when import config

### ISSUE THREAD

**Issue by TruongQToan** [tekezo/Karabiner-Elements#1916]
I am using MacOS Mojave version 10.14.5. When I enable some complex modifications, KE crashes. Also, the mapping between Capslock and Escape and Control does not working. Also, how can I uninstall Karabiner-VirtualHIDDevice afer uninstall KE?

**Comment by michelkoga** [comment]
My Karabiner is not working too since last update. 
In the log:

[2019-07-28 21:29:16.846] [warning] [grabber] virtual_hid_device_client is not connected yet. Please wait for a while.
