### ISSUE TITLE
Shortcut to put a Mac to sleep using non-Apple keyboard

### ISSUE THREAD

**Issue by haltlos** [tekezo/Karabiner-Elements#1919]
The eject button that is present on Apple keyboards is absent on others, such as the Logitech K780, that I am using. Has anyone figured out a Karabiner modification to put the (Mac) computer to sleep?

**Comment by damlub** [comment]
Hi, If your intention is to lock the Mac from curious folks, I use Ctrl-Cmd-Q

**Comment by Diaspar4u** [comment]
sleep and lock are two different functions

**Comment by bnss** [comment]
@haltlos You've probably figured it out by now, but there is a Software function called "Sleep". I've remapped the `del` key on my Keychron K2 to do just this.

<img width="503" alt="Screenshot 2022-06-02 at 16 07 13" src="https://user-images.githubusercontent.com/17271687/171648319-5158e3e1-d555-46e2-bf3d-8d5d5fd0a5b7.png">

<img width="804" alt="Screenshot 2022-06-02 at 16 10 01" src="https://user-images.githubusercontent.com/17271687/171648652-bf37ab7d-0171-428b-baeb-9ef8242131b9.png">
