### ISSUE TITLE
Why is left_gui left_command?

### ISSUE THREAD

**Issue by Nv7-GitHub** [tekezo/Karabiner-Elements#1921]
I want to make the blue button on my Microsoft Sculpt Comfort useful on mac. But, when pressed it is called `left_gui(equal to left_command)`. Whatever I modify on it also modifies the `left_command`. How can I modify `left_gui` seperately? Thank you for the help!

**Comment by Nv7-GitHub** [comment]
Never mind, I was able to solve this problem with a complex modification. Still, I wish there was a way to do this with a simple modification.

**Comment by yoonsch217** [comment]
I faced the same situation.
And there is also a way to do this without `complex modification`.

- check MS scuplt comfort
![image](https://user-images.githubusercontent.com/41099071/98072180-c564f900-1ea8-11eb-8941-3d90b4cbc90d.png)


- select MS comfort for the target device, and set keys
![image](https://user-images.githubusercontent.com/41099071/98072247-f04f4d00-1ea8-11eb-872e-fbe8515fcd75.png)
