### ISSUE TITLE
Doesn't work after update to Mojave 10.14.6

### ISSUE THREAD

**Issue by rationality6** [tekezo/Karabiner-Elements#1925]
Do I need to check the beta version of Karabiner?

Or is there a way to reactivate this

**Comment by tiratatp** [comment]
I think mine was fixed by restarting your machine.

**Comment by rationality6** [comment]
Sorry, the problem was fixed.

Close this.

**Comment by zinuzoid** [comment]
Mine was fixed when update to beta 12.5.5
