### ISSUE TITLE
Can't remap fn on MSFT keyboard

### ISSUE THREAD

**Issue by dstrozzi** [tekezo/Karabiner-Elements#1927]
I have a Microsoft wired USB keyboard.  It very annoyingly has a blue Fn key in the bottom right of the main section of keys, i.e. between alt and ctrl, right where a normal person would want the "Super" (Windows / Command) key.  Karabiner refuses to remap it to either left command or right command.  Version 12.5.0 or beta 12.5.3.

Thoughts?

**Comment by brodygov** [comment]
You might try opening the Karabiner EventViewer to see what key code that key appears with. It might be the case that Microsoft is processing the Fn keypress locally within the keyboard and not passing it through to macOS.

**Comment by dstrozzi** [comment]
You are right!  When I hit the Fn key, eventviewer picks up nothing.  This is very annoying - why would one bother with an Fn key for an external keyboard like this?  I've only seen it for the special functions on laptops, like changing volume or screen brightness.  Ugh M$FT.

**Comment by dstrozzi** [comment]
OK I did some googling, and this is truly frustrating.  The Fn key is basically a "brick" for me.  Right where the Command key should be.  Since it seems to be processed in hardware there's no way to remap it.  The physical keyboard has only two keys with a blue symbol indicating what the Fn key does.  So even if I wanted to use the Fn keys to control volume, brightness, etc (which I don't), I have no way of knowing what key does what.

People are paid money to design this??

**Comment by rchougule** [comment]
I am facing the same issue. fn key is not picked in the EventViewer. Not able to remap the key.

**Comment by Skentavr** [comment]
Same problem - Microsoft Wired Keyboard 600 - Karabiner EventViewer not show when press Fn button.
