### ISSUE TITLE
Not working change caps_lock

### ISSUE THREAD

**Issue by buzyday** [tekezo/Karabiner-Elements#1928]
**Problem**
Not working change caps_lock to command+control+option+shift on Mojave 10.14.6 (18G84)

**Description:**

1) Settings Karabiner-Elements 
https://monosnap.com/file/kolCT8cSjJWBeHXfgXqZnSgIe3Ozd0
2) Version of Karabiner-Elements 12.5.0
3) Detection - when I press Caps lock green light shows and enable uppercase (no change by Karabiner) 

**Hope for a soon fix, thank you for nice software!)))**

**Comment by rtyshyk** [comment]
Mojave 10.14.6 
Version of Karabiner-Elements 12.5.0

Have the same, become broken right after update.

**Comment by francoiscampbell** [comment]
Same OSX version, beta 12.5.5 works

**Comment by rtyshyk** [comment]
Just updated to 12.5.5 (bot beta), works again.

**Comment by buzyday** [comment]
Yes, same beta 12.5.5 works 👍

**Comment by brodygov** [comment]
My keyboard remapping is also not working after upgrading to 10.14.6. I'd suggest changing the issue title to something like "Stops working on macOS 10.14.6" since that seems to be the common denominator here.

It's amazing how dependent I am on Karabiner-Elements to make my keyboard usable!

**Comment by joanmarcriera** [comment]
Mojave 10.14.6
Version of Karabiner-Elements 12.5.0
Update to 12.5.5 beta worked.

**Comment by brodygov** [comment]
Simply reinstalling the existing stable version (12.5.0) also restored functionality for me on latest Mojave.

Looks like other folks have experienced the same situation https://github.com/tekezo/Karabiner-Elements/issues/1930
