### ISSUE TITLE
Karabiner Stops Working Properly After Going to Sleep in Catalina

### ISSUE THREAD

**Issue by Corbot5000** [tekezo/Karabiner-Elements#1932]
macOS Catalina Beta 5
Karabiner 12.5.5

Problem: Twice now, I've returned to my laptop in the morning and Karabiner is no longer functioning properly - when I attempt to go to System Preferences > Keyboard > Modifier Keys, Karabiner VirtualHDKeyboard is no longer an option and my modifications within Karabiner no longer work. Restarting Karabiner did not solve the issue. Restarting the computer did solve the problem.

**Comment by tomredman** [comment]
Experiencing the exact same thing.

**Comment by Corbot5000** [comment]
This issue persists in Karabiner 12.5.6 as well.

**Comment by seren** [comment]
This just happened to me after installing the `macOS Mojave 10.14.6 Supplemental Update`. Both simple and complex modifications no longer functioned, even after quitting and restarting Karabiner-Elements.

Karabiner-EventViewer showed the unmodified key codes coming through, and there was nothing obvious in the MacOS Console logs.

Restarting the computer fixed this, and manually putting the computer to sleep doesn't seem to have re-triggered it. I'll post an update if it happens again.

**Comment by maxlcoder** [comment]
try 
```
sudo killall karabiner_grabber
sudo killall karabiner_observer
```
when your macOS Catalina wake up

**Comment by Corbot5000** [comment]
This issue is still present in 12.5.92 and Catalina beta 19A526h.

**Comment by anpyat** [comment]
Same here, still an issue in 12.5.92. The error log shows:
grabber client error: No buffer space available

Restarting the computer or killall karabiner_grabber / karabiner_observer solves the problem for a while.

**Comment by tekezo** [comment]
This issue is not reproducible on my machine, unfortunately.
I'll investigate the cause when I can reproduce the issue.

**Comment by anpyat** [comment]
I've attached a few screenshots in case it helps to reproduce the issue.
Macbook Pro 2018, macOS Catalina public beta 4, trying to modify the touchbar behaviour

<img width="905" alt="Screenshot 2019-08-16 at 15 08 09" src="https://user-images.githubusercontent.com/1776031/63169845-16849500-c038-11e9-9469-fa5de78250cd.png">
<img width="1112" alt="Screenshot 2019-08-16 at 15 08 28" src="https://user-images.githubusercontent.com/1776031/63169863-21d7c080-c038-11e9-84d9-cf6e77e6701c.png">
<img width="1112" alt="Screenshot 2019-08-16 at 15 08 33" src="https://user-images.githubusercontent.com/1776031/63169872-256b4780-c038-11e9-8226-9f3f93b7b2b9.png">

**Comment by tekezo** [comment]
Thank you for feedback!

I succeeded to reproduce this issue!
I'm working to fix it. Please wait for a while.

**Comment by tekezo** [comment]
I believe this issue is fixed at v12.6.2.
Please check the latest beta version.

How to upgrade to the latest beta version:
<https://pqrs.org/osx/karabiner/document.html#check-for-updates>

**Comment by tomredman** [comment]
This works for me now, thank you so much @tekezo! This is an amazing project.

**Comment by simonkuang** [comment]
> I believe this issue is fixed at v12.6.2.
> Please check the latest beta version.
> 
> How to upgrade to the latest beta version:
> https://pqrs.org/osx/karabiner/document.html#check-for-updates

But it happens at v12.9.0 again.

**Comment by pkfln** [comment]
Is there a fix planned for this?

**Comment by caecebo** [comment]
It still does not work.

**Comment by fyun89** [comment]
Same problem with 12.9.3

**Comment by Rubenstein29** [comment]
Hello, same problem for me Karabiner is no longer working even after updating to the last beta. 
I'm on Catalina 10.15.2

**Comment by chauncyf** [comment]
Same here, still not working

**Comment by Randyjp** [comment]
Same issue, restarting is the only thing that fixes it. I'm on Catalina 10.15.4

**Comment by pkfln** [comment]
@tekezo Any updates?

**Comment by mikhailtugushev** [comment]
Same here, still not working

**Comment by enelgit** [comment]
Same here, with 12.9.0 and Catalina 10.15.4

**Comment by p3ntium** [comment]
Same here, with Karabiner 12.9.0 and Catalina 10.15.4

**Comment by trbielec** [comment]
Same here. `No buffer space`. Latest release and the beta release, on Catalina. Even after killing the processes.

**Comment by jgsastre** [comment]
Same problem here. I have opened a new [Issue](https://github.com/pqrs-org/Karabiner-Elements/issues/2297)

**Comment by mattPiratt** [comment]
same here. Catalina 10.15.5

**Comment by luckyyyyy** [comment]
![image](https://user-images.githubusercontent.com/9210430/87873458-4ed4e600-c9f4-11ea-8024-12e715e4d1be.png)

**Comment by multi-io** [comment]
Seeing this in the newest version (12.10.0). killing karabiner_grabber/observer does NOT help.
