### ISSUE TITLE
Capslock turns itself off immediately

### ISSUE THREAD

**Issue by yyoon** [tekezo/Karabiner-Elements#1934]
macOS version: Mojave 10.14.5
Karabiner-Elements version: 12.5.0

Recently, I have been experiencing that whenever I try to turn on Capslock mode by pressing the key, it would immediately turn itself off. I know there's an inherent Capslock delay on macOS, but this still happens when I press the Capslock key long enough (longer than 1 sec).

Weird thing is that I can use Capslock as usual in iTerm, but I can't in most other apps (e.g. Chrome, Notes, etc.). When I quit Karabiner-Elements, this problem goes away.

Not sure if this is happening only on my side, but I'm willing to provide more information if necessary. Any help would be appreciated.

**Comment by jgclark** [comment]
What does the (separate) event viewer app show when you press the CapsLock key?

**Comment by yyoon** [comment]
It shows what's expected.
`key_down, 57, caps_lock` when I push the caps lock key, and
`key_up, 57, caps_lock` when I release the caps lock key

I don't know what changed, but now I'm noticing that if I keep the caps lock key down for long enough (1~2 seconds) then it would keep its state. Anything shorter would make it turn off immediately.
