### ISSUE TITLE
Remove confirmation for quitting the app

### ISSUE THREAD

**Issue by FeleConvo** [tekezo/Karabiner-Elements#1937]
Would it be possible to remove the quit confirmation? 

I use a lot of other apps like Spectacle, f.lux, etc. and none of those request confirmation. 

I often need to restart Karabiner when plugging and unplugging my devices and this becomes a little annoying.

Thanks a lot to the author for your effort.

**Comment by LvChengbin** [comment]
I totally agree with you, I always need to solve problems with restarting Karabiner-Elements from the date I upgraded to one version on.
I am "fighting" with this app every day now. 
But I still want to say thank you to the author.

**Comment by LvChengbin** [comment]
I totally agree with you, I always need to solve problems with restarting Karabiner-Elements from the date I upgraded to one version on.
I am "fighting" with this app every day now. 
But I still want to say thank you to the author.
