### ISSUE TITLE
Craft Keyboard Crown not working. F# keys all messed up.

### ISSUE THREAD

**Issue by christianmagill** [tekezo/Karabiner-Elements#1938]
I'm using just the basic CapsLock to Hyper/Escape from Vonng/Capslock.

When Karabiner Elements is active the crown for my Craft Keyboard stops working and my F# keys get all swapped around.

I'm unsure how to go about fixing this. Using EventViewer and Mac's Keyboard Viewer I see no events when I press any of the F# keys.

Is there a way to disable the Function Key mapping?

**Comment by christianmagill** [comment]
I was able to solve my issue by replacing the function key mapping section in karabiner.json with an empty array.

**Comment by grzegorzkiselev** [comment]
Described my solution here
https://github.com/pqrs-org/Karabiner-Elements/issues/1450#issuecomment-1405613904
