### ISSUE TITLE
double click eventType

### ISSUE THREAD

**Issue by timberlake00** [tekezo/Karabiner-Elements#1939]
i click single event when always show me each other different eventType .like this :
eventType:keyDown         code:0xb        name:b               flags:                                   misc:characters:b   	KeyCode::B
eventType:keyDown         code:0x7c       name:Right           flags:NumPad Fn                          misc:characters:    	KeyCode::CURSOR_RIGHT
eventType:keyUp           code:0xb        name:b               flags:                                   misc:characters:b   	KeyCode::B
eventType:keyUp           code:0x7c       name:Right           flags:NumPad Fn                          misc:characters:    	KeyCode::CURSOR_RIGHT

or that:
eventType:keyDown         code:0xe        name:e               flags:                                   misc:characters:e   	KeyCode::E
eventType:keyDown         code:0x31       name:Space           flags:                                   misc:characters:    	KeyCode::SPACE
eventType:keyUp           code:0xe        name:e               flags:                                   misc:characters:e   	KeyCode::E
eventType:keyUp           code:0x31       name:Space           flags:                                   misc:characters:    	KeyCode::SPACE

But, i just click b  and e - - . .....
some type has same question , what should i do? or change sth?

**Comment by timberlake00** [comment]
add plus:
i use this on MacOS Mojava 10.14.5, my keyboard is HPB, when used on Windows has never click different eventType by click single type

**Comment by tomredman** [comment]
Also getting a double event for a single click. This is a key with a modification, and the unmodified event triggers followed immediately by the modified event. However, the double event also occurs for unmodified keys. 

This is the event viewer result for **two clicks**:

```
eventType:key_down        code:226        name:left_alt        misc:
eventType:key_down        code:227        name:left_gui        misc:
eventType:key_up          code:226        name:left_alt        misc:
eventType:key_up          code:227        name:left_gui        misc:
eventType:key_down        code:230        name:right_alt       misc:
eventType:key_down        code:231        name:right_gui       misc:
eventType:key_up          code:230        name:right_alt       misc:
eventType:key_up          code:231        name:right_gui       misc:
```

**Comment by timberlake00** [comment]
thanks bro! But my question maybe is not that problem .because when i
modification some key or not ,that eventType also give me two different
result,
eventType:key_down        code:8          name:e               misc:
eventType:key_down        code:80         name:left_arrow      misc:
eventType:key_up          code:8          name:e               misc:
eventType:key_up          code:80         name:left_arrow      misc:
u can seen that, when i touch the key of "e", also turn down the key of
"left_arrow " .that's why i so confuse .maybe my keyboard is broken in macOS
anyway ,thanks a lot for u help

Tom Redman <notifications@github.com> 于2019年8月9日周五 下午10:08写道：
