### ISSUE TITLE
Disabling Caps Lock in System Preferences→Modifier Keys doesn’t work

### ISSUE THREAD

**Issue by Kwpolska** [tekezo/Karabiner-Elements#194]
When Karabiner-Elements is running, my setting from System Preferences to disable Caps Lock doesn’t work anymore. When I quit Karabiner-Elements, it works again.
![image](https://cloud.githubusercontent.com/assets/327323/18959454/833b7650-8666-11e6-8735-24796efb6e8d.png)

**Comment by talha131** [comment]
This is a known issue. There is no workaround.

https://github.com/tekezo/Karabiner-Elements/issues/9#issuecomment-248498163

You must define your configuration in Karabiner-Elements which currently does not let user disable keys #145
