### ISSUE TITLE
not working after majave 10.14.6 supplemental update

### ISSUE THREAD

**Issue by Wonderful99668** [tekezo/Karabiner-Elements#1940]
Karabiner-Elements 12.5.0 not working after installing the Mojave 10.14.6 supplemental update.
Do I need to install the beta version?

**Comment by tekezo** [comment]
Please restart your macOS.
https://pqrs.org/osx/karabiner/help.html#stopped-working-after-macos-update

**Comment by Wonderful99668** [comment]
Thx! It worked!
