### ISSUE TITLE
12.5.9 kext not loading

### ISSUE THREAD

**Issue by cksachdev** [tekezo/Karabiner-Elements#1947]
![image](https://user-images.githubusercontent.com/37770/62972720-4eba8680-be32-11e9-82f3-cfa529879941.png)

![image](https://user-images.githubusercontent.com/37770/62972738-5bd77580-be32-11e9-92a5-cb0fe37b5ca6.png)

**Comment by tekezo** [comment]
Your error code is `kOSKextReturnBootLevel`.
I guess your macOS is boot in Safe Mode.

Please boot Normal Mode in order to load the kext since any third vendor kext are not permitted in Safe Mode.
