### ISSUE TITLE
`non-us-backslash` modification stopped working after OSX update

### ISSUE THREAD

**Issue by tian-yi** [tekezo/Karabiner-Elements#1949]
I switched `non_us_backslash` to `grave_accent_and_tilde`  it was working fine until I upgraded the OSX to 10.14.6. 
Now, when I use the `non_us_backslash` key, it shows `§`. 

OS X 10.14.6
Karabiner-Elements 12.5.0

Thanks.

![Screenshot 2019-08-14 at 09 37 06](https://user-images.githubusercontent.com/1011678/63006747-21dc9280-be77-11e9-81ee-bcbb7fd79a29.png)

![Screenshot 2019-08-14 at 09 36 52](https://user-images.githubusercontent.com/1011678/63006749-21dc9280-be77-11e9-8564-76fa71f87452.png)

**Comment by lgodziejewski** [comment]
@tian-yi I had the same issue - this comment fixed it

https://github.com/tekezo/Karabiner-Elements/issues/1930#issuecomment-517684365

**Comment by tian-yi** [comment]
@lgodziejewski Thanks a mill!
Reinstall Karabiner-Elements did solved the issue.
