### ISSUE TITLE
How do I prevent Karabiner-Elements from starting with my OS?

### ISSUE THREAD

**Issue by Kwpolska** [tekezo/Karabiner-Elements#195]
I never allowed it to start with macOS, and yet it does…

**Comment by talha131** [comment]
Can you try, select Karabiner-Elements and press minus button

<img width="684" alt="screen shot 2016-09-29 at 20 55 08" src="https://cloud.githubusercontent.com/assets/1094724/18961648/22ff9f48-8687-11e6-8dd1-0eed378b34fe.png">

**Comment by Kwpolska** [comment]
It’s not visible in *Login Items*. That would be too easy.

**Comment by maletor** [comment]
I think it's /Library/LaunchAgents. Isn't macOS great?
