### ISSUE TITLE
Can't remap volume keys

### ISSUE THREAD

**Issue by svalentin** [tekezo/Karabiner-Elements#1951]
karabiner-elements 12.5.0 can't remap volume_increment and volume_decrement keys even though EventViewer can correctly observe the key down/up events for the volume keys.

I've created a complex modification that remaps "volume_increment" to "x". The rule doesn't take effect when pressing "volume_increment" key.
On the other hand, creating a complex modification that remaps "x" to "volume_increment" _does_ work. The problem is just in the "from" part.

Tested with external keyboard with media keys. All media keys are correctly captured by EventViewer. Double checked syntax and logs load the config file without errors. Tried restarting karabiner-elements.

**Comment by svalentin** [comment]
Sorry, found the problem!
The volume_increment and volume_decrement keys are not "key_codes". They are "consumer_key_codes". Changing karabiner.json to use "consumer_key_code" as the "from" works!

**Comment by conterio** [comment]
this is broken for me even if i use consumer_key_code it still just does the volume up

![image](https://github.com/user-attachments/assets/9c3099d8-2181-4bff-a317-2056e910f244)

**Comment by tekezo** [comment]
@conterio I believe your keyboard is actually sending f12 instead of volume_up, so try remapping f12 using Simple Modifications.

**Comment by BoD** [comment]
Well actually, I got it to work - the issue was that this device is seen twice:
1. once as a 'keyboard'
2. once as a 'keyboard + trackpad'

The events were received from 2. but only 1. had "Modify events" enabled in "Devices".  Enabling the other one fixed my issue.
