### ISSUE TITLE
EventVIewer should show applied modifier keys

### ISSUE THREAD

**Issue by James6M** [tekezo/Karabiner-Elements#1952]
As I understand, if a device is not being modified (unchecked in KE> Devices), then modifier keys from other devices do not apply to key presses on the unchecked device.  For example, if the Touchbar is unchecked, then the modifier keys cannot apply to the F# keys.

However, this is impossible to detect in the current EventViewer.  The sequence of key events (modifier key down, key down, key up, modifier key up) looks like the modifier key applied to the key press on the unchecked device.  An additional column, showing which modifier keys apply to each event, would clarify this.

**Comment by tekezo** [comment]
EventViewer shows modifier keys since the latest release (v12.6.0).
Please check for updates.
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by James6M** [comment]
Wicked!  Difficulty solved beautifully.
