### ISSUE TITLE
12.6.0 - is it normal that 7 agents/daemons are installed?

### ISSUE THREAD

**Issue by luckman212** [tekezo/Karabiner-Elements#1955]
Not a bug, just a question-

After updating from 12.5.0 to 12.6.0, I see there are now 4 agents and 3 daemons loaded for Karabiner. Is this correct or are some legacy and some part of the new kext? (I am on 10.14.6 btw)

![image](https://user-images.githubusercontent.com/1992842/63168267-a5c28600-c001-11e9-895a-24d72f5842a2.png)

**Comment by tekezo** [comment]
It's intended behavior.
New agents and daemon (`agent.karabiner_grabber`, `agent.karabiner_observer`, `karabiner_kextd`) are introduced in order to make Karabiner-Elements working on macOS Catalina.

**Comment by luckman212** [comment]
Ok thank you for the clarification!
