### ISSUE TITLE
Remove Karabiner permission in System Preferences after uninstalling Karabiner

### ISSUE THREAD

**Issue by carstenmehring** [tekezo/Karabiner-Elements#1959]
When starting Karabiner-elements for the first time I had to allow the start of programs from the developers of Karabiner in systems preferences.

After uninstalling Karabiner (using its built-in uninstaller) these permissions remain (I tested this by re-installing Karabiner after the uninstallation).

How can the permissions be removed?

Many thanks in advance for any help.

Best
Carsten

**Comment by tekezo** [comment]
You have to remove kext approval histories in Recovery Mode.
Please follow the instruction.
https://forums.developer.apple.com/thread/100281
