### ISSUE TITLE
After 0.90.45 system acts like I have a mouse

### ISSUE THREAD

**Issue by a3ammar** [tekezo/Karabiner-Elements#196]
I'm on a laptop that doesn't have mouse connected but the system acts like I have one (scrollbars always visible).

**Comment by talha131** [comment]
I too have the same issue.

Karabiner-Elements 0.90.45
OS X 10.12.1 Beta (16B2333a)

**Comment by tekezo** [comment]
Thank you for feedback!
I've fixed this issue at 0.90.46.

**Comment by a3ammar** [comment]
Thanks!

**Comment by sbarex** [comment]
I have the same problem with Karabiner-Elements 11.5.0 on osx 10.13.2.
