### ISSUE TITLE
How to migrate having old Karabiner configuration?

### ISSUE THREAD

**Issue by mindojo-victor** [tekezo/Karabiner-Elements#197]
I have this Karabiner configuration:
<img width="515" alt="untitled" src="https://cloud.githubusercontent.com/assets/17159503/18960886/e7927a74-8673-11e6-97a8-083294c06bee.png">

I upgraded to Sierra, and Karabiner doesn't work anymore.

I exported the configuration:

``` bash
#!/bin/sh

cli=/Applications/Karabiner.app/Contents/Library/bin/karabiner

$cli set remap.app_finder_enter2commandO 1
/bin/echo -n .
$cli set remap.app_finder_return2commandO 1
/bin/echo -n .
$cli set remap.controlArrow2optionLarrow 1
/bin/echo -n .
$cli set remap.fkeys_to_consumer_f10 1
/bin/echo -n .
$cli set remap.fnletter_to_ctrlletter 1
/bin/echo -n .
$cli set remap.KPReturn_to_Ctrl_O 1
/bin/echo -n .
$cli set remap.shiftDelete2forwarddelete_nomodifiers 1
/bin/echo -n .
$cli set remap.uk_section2backquote 1
/bin/echo -n .
$cli set repeat.initial_wait 416
/bin/echo -n .
$cli set repeat.wait 33
/bin/echo -n .
/bin/echo
```

Examples in this repo are very simple. Is there a doc with all configuration options?
How can I migrate my previous configuration?

**Comment by talha131** [comment]
You can migrate some of the options. See [Usage](https://github.com/tekezo/Karabiner-Elements/blob/master/usage/README.md)

For rest you need to wait for #16

**Comment by warvariuc** [comment]
@talha131 Is it currently possible to map Shift+Backspace to act like forward delete?

**Comment by talha131** [comment]
@warvariuc Nope. Not until #16 is added.
