### ISSUE TITLE
some apps does not recognise modification keys with karabiner enabled

### ISSUE THREAD

**Issue by Modi34** [tekezo/Karabiner-Elements#198]
this is a bit weird bug - I use some karabiner replacements while it is not ready like steer mouse and controllermate. When I enable karabiner-elements they do not recognise modifier keys (command, alt, shift, option).

gif example for steer mouse - https://drive.google.com/file/d/0B3twjDbcZ99ucVFaYlU3SEcxaVU/view?usp=drivesdk

gif example for controllerMate - https://drive.google.com/file/d/0B3twjDbcZ99uM3hHcmRyODhNN3c/view

keep up great work! hope this will be fixed some day//

**Comment by rgosain** [comment]
I've seen another example of this: in Safari, command-clicking on a link to open it in a new tab in the background doesn't work with Karabiner-Elements enabled: it opens it in the foreground as if command wasn't clicked. When Karabiner-Elements is disabled you get normal behavior.

**Comment by leshik** [comment]
Can it be somehow related to #120 ?

**Comment by ursineasylum** [comment]
Confirming that any modifier key + mouse button doesn't work for me in any program-- iTunes, Safari, Firefox, iTerm2, Finder, Photoshop CS6-- unless Karabiner-Elements is killed.
