### ISSUE TITLE
Can't figure out how to set fn + tab to toggle windows

### ISSUE THREAD

**Issue by iwebsguy** [tekezo/Karabiner-Elements#1980]
I have switched from PC to Mac for a number of reasons, however after using a PC for the previous 25+ years I have become accustom to certain keyboard shortcuts, I realize I could try to re-train myself but I don't want to go that route and still use a PC for work full time.

Attached is my current config, I have switched fn and command in the simple global settings then do a number of other PC-style changes in the advanced section. currently when I do command + tab it toggles the window, so does fn + tab, however the fn key is actually the command key. What I am trying to get to is being able to press the command key (which is the fn key virtually) and tab to toggle windows. Basically like how alt + tab would work on the PC with the key being next to the space bar. If anyone could help me here it would be much appreciated.

[karabiner.txt](https://github.com/tekezo/Karabiner-Elements/files/3587235/karabiner.txt)

**Comment by dragon788** [comment]
I'd recommend trying this awesome setting of mappings for a while and see if it helps ease your transition. 
https://github.com/rux616/karabiner-windows-mode

One thing to keep in mind is that Karabiner-Elements essentially watches for a key scan code (that a hardware keyboard emits), and then simply passes along a different code to the operating system, but some key codes are handled below the operating system or at both the system/firmware level and by the operating system (Cmd+Option+R to trigger recovery during boot for example). 

Try opening the Karabiner-EventViewer and press your Fn and Cmd keys and see which codes show up. Here are the results from pressing the Fn/Ctrl/Option/Cmd/Tab keys on my machine.

```
type:key_down        code:65538      name:fn              misc:flags: fn 
type:key_up          code:65538      name:fn              misc:
type:key_down        code:224        name:left_control    misc:flags: left_control 
type:key_up          code:224        name:left_control    misc:
type:key_down        code:226        name:left_alt        misc:flags: left_alt 
type:key_up          code:226        name:left_alt        misc:
type:key_down        code:227        name:left_gui        misc:flags: left_gui 
type:key_up          code:227        name:left_gui        misc:
type:key_down        code:43         name:tab             misc:
type:key_up          code:43         name:tab             misc:
```

**Comment by iwebsguy** [comment]
I ended up switching fn and left_control along with using some of the "pc-style" rules found in the advanced section, thanks!
