### ISSUE TITLE
Key modifier configuration remains after uninstall

### ISSUE THREAD

**Issue by Hooumeri** [tekezo/Karabiner-Elements#1989]
Using the latest version of Karabiner Elements for the purpose of modifying my left shift key to the space bar, because the space bar broke on my Macbook Pro model. I am running on a macOS Catalina Public Beta 7. After uninstalling through the Karabiner settings and rebooting my Macbook, the modification for my left shift still works - it registers as a space bar click.

I tried to re-install Karabiner and removing the modification (so that I would have a blank Karabiner configuration), and then uninstalling, but this did not work either.

**Comment by tekezo** [comment]
This issue is not related with Karabiner-Elements if you uninstalled Karabiner-Elements properly by uninstaller.
https://pqrs.org/osx/karabiner/document.html#uninstall

Please confirm another app changes your left shift key.
If you have no idea, reset PRAM and NVRAM, then boot Safe Mode by the following instructions in order to clean up your environment.

Resetting your Mac's PRAM and NVRAM
<https://support.apple.com/kb/ht1379>


Mac OS X: Starting up in Safe Mode
<https://support.apple.com/kb/ht1455>

**Comment by philipglaser** [comment]
This, and more, are still an issue. 

I am using a MacBook Pro with Mojave 10.14.6. 

What happened was: 

* I installed Karibener-Elements-12.10.0;
* I enabled the rule **change caps_lock to control if pressed with other keys, to escape if pressed alone**;
* From that point: 
  * **Caps Lock** did fire the ``esc`` event, but the combination with other keys concept did not seem to work; I think key combinations with Caps Lock just spewed symbol characters;
  * Most disturbing, the **Option** and **Command** keys were reversed;
* Simply uninstalling (yes, I used the Uninstall button, and yes I restarted the system) did not reverse this change; 
* I Reinstalled Karibiner to try to undo the changes but there were no rules enabled; 
*  I uninstalled this time using the scripts you list above and rebooted; command/option were still reversed;
* I went through the procedures described above for clearing PRAM/NVRAM and did a safe boot, removing all startup items; no luck;
* When I rebooted in normal mode, this time, I noticed that **_The Karibiner app icon was still present in the status bar_** and the app seemed to be quite alive and well; I manually quit that app and rebooted; 
* Finally, my option/command key behavior got back to normal (but see my note below).

**NOTE**: in full disclosure, I should add that at some point in this process,. in an attempt to fix this problem, I changed the Mac **Modifier** keys setting that reverses **Command** and **Option** keys, forgetting that that is the normal practice when using an external pc keyboard with a mac. Reinstating that reversal was the last step in getting things back to normal. However, the fact remains that: 
* The rule I enabled didn't seem to work; 
* Without my touching the mac **Modifier** settings, **Command/Option** were reversed; 
* The uninstall process was incomplete -- Karibiner was still there in the status bar even after uninstall, rebooting in safe mode, and rebooting again. 

Thanks for listening.

**Comment by tekezo** [comment]
@TheTaoOfPhil
I think you may have rebooted before the uninstallation was complete.
The installed files are removed after you pressed OK button on the uninstaller dialog as shown in the second image on the following page.
https://karabiner-elements.pqrs.org/docs/manual/operation/uninstall/
