### ISSUE TITLE
JIS Magic Keyboard recognized as US keyboard

### ISSUE THREAD

**Issue by tomo202jp** [tekezo/Karabiner-Elements#199]
Although I'm using JIS type keyboard (Magic keyboard model:A1644), it is recognized as US keyboard. I've looked over the Issues threads but can't find  the solution. Any clues?

**Comment by dogteacher** [comment]
Me too. with  Happy Hacking Keyboard Lite2 why dont find the solution?

**Comment by akioito** [comment]
I have the same problem with HHKB Pro. Resolved restoring the IOHIDKeyboardFilter.plugin:
https://forums.developer.apple.com/thread/64304
http://www.insanelymac.com/forum/topic/316060-pre-release-macos-sierra-10121/page-3?hl=%20iohidkeyboardfilter

**Comment by rinopo** [comment]
I had the same problem.
I mean I too have a JIS "Magic Keyboard with Numeric Keypad". (I'm not sure if it's the same problem with HHKBs.)

After I set the "Keyboard Type" in "Virtural Keyboard" to "JIS" (the default was ANSI), it seems to be working fine.

<img width="900" alt="monosnap 2017-10-19 14-08-06" src="https://user-images.githubusercontent.com/45791/31755060-f76d58fa-b4d6-11e7-9ffe-be8f3102b21c.png">
