### ISSUE TITLE
Tutorial on custom language layout switch

### ISSUE THREAD

**Issue by asm0dey** [tekezo/Karabiner-Elements#200]
Hi!

Is it possible to change layout switch shortcut to Shift+Caps Lock?
Earlier it was possible with Karabiner + Seil

**Comment by perlun** [comment]
I have the similar need. Used to have Caps Lock bound to that, but then I upgraded to S*erra which killed all of my custom mappings. 😢

**Comment by pavlo** [comment]
I second the question

**Comment by mamantoha** [comment]
It works for me

![karabiner-elements preferences 2016-10-18 22-53-54](https://cloud.githubusercontent.com/assets/61285/19494099/29b6286c-9586-11e6-8d8b-5f42e170dab2.png)

**Comment by perlun** [comment]
Works for me also now, I think this could be closed.
