### ISSUE TITLE
macOS prompts me for a Bluetooth keyboard on wake

### ISSUE THREAD

**Issue by bunnyhero** [tekezo/Karabiner-Elements#201]
This only happens when I have Karabiner-Elements installed. I do not use a Bluetooth keyboard, but when I wake my MacBook Air from sleep, I sometimes see this dialog (from Bluetooth Assistant):

![bluetooth-keyboard](https://cloud.githubusercontent.com/assets/467642/18982666/dfc6a88c-86b5-11e6-9ced-bccfd8fec276.png)

**Comment by akohlsmith** [comment]
I'm getting this too, in combination with the keyboard modifiers not working with mouse clicks (i.e. cmd-click in chrome, shift-click to select a range of files in Finder or Mail.app... I was going crazy until I remembered I was running Karabiner-Elements. :-)

A reboot fixes these issues for a little while, but it appears that these things start going wrong after the mac goes to sleep and is resumed.

**Comment by mikemimik** [comment]
@akohlsmith is there an issue open already about the keyboard modifiers not working with mouse clicks?

**Comment by akohlsmith** [comment]
It's sort of mentioned in #83, but really I think this is more related to the issues where the modifier keys just stop working altogether.

**Comment by tekezo** [comment]
I believe this issue has been fixed in the latest version.

**Comment by todkon** [comment]
This issue is still occurring actually..

**Comment by mikemimik** [comment]
I can confirm, this is still happening.

**Comment by awenner** [comment]
Can confirm it's still happening to me too.

**Comment by languitar** [comment]
Same thing here

**Comment by crumley** [comment]
This is happening for me. 0.90.64

**Comment by larpo** [comment]
Happening for me too. Can't remember if it was fixed at some point, but has been happening at least for several weeks. 0.90.66. Could someone re-open this?

**Comment by baskus** [comment]
Yes please reopen! :) @tekezo ?

**Comment by BenjaminVanRyseghem** [comment]
Still happening to me on Karabiner-Elements 11.1.0

It's quite annoying to be honest

**Comment by mmroczka** [comment]
Still happens to me as well. It's easy for me to reproduce too. All I have to do is start up my computer with Karabiner-Elements, do some editing with it, lock the computer (sending it to the lock screen) and then try to log back in. My entire keyboard is dead - but my mouse works. Only way to get back on is a reboot or connecting my bluetooth keyboard. Oddly enough, once I log in with my bluetooth keyboard, Karabiner (and actually the entire keyboard) starts working again immediately.

**Comment by IshanJawade** [comment]
Yeah, This issue is still there !
