### ISSUE TITLE
Karabiner doesn't work after update to Catalina

### ISSUE THREAD

**Issue by rt-krz** [tekezo/Karabiner-Elements#2025]
After updating to Catalina I got this message:
![image](https://user-images.githubusercontent.com/36962768/66700184-378efc80-ecee-11e9-9bd1-b1aab1b48bc4.png)

When I try to give this permissions I don't see the option to select karabiner_grabber:
![image](https://user-images.githubusercontent.com/36962768/66700192-44abeb80-ecee-11e9-8000-fef739a27dd3.png)

after that Karabiner doesn't work. (no tray element, no mapping)

**Comment by tekezo** [comment]
A dialog about karabiner_grabber is shown (may be hidden by another window).
https://pqrs.org/osx/karabiner/document.html#usage-catalina

You have to press the "Open Sysetm Preferences" button on the dialog in order to add karabiner_grabber into the list.

Please search the dialog.

**Comment by rt-krz** [comment]
After few log outs/ins I was able to see the `karabiner_grabber` on the list and could choose it.

**Comment by dzineer** [comment]
Yes, minus some windows and you will see behind the Karabiner dialog another window that you can click the open system preferences and then it will see grabber. I have the latest os, Mac OS Catalina 10.15.1.

Cheers

**Comment by yatamlite** [comment]
You can use the + button to add karabiner_grabber from this location

/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_grabber

**Comment by isokrates** [comment]
I'm having a related issue, reported here: https://github.com/pqrs-org/Karabiner-Elements/issues/1867

Apologies for the cross-posting, but I'm finding it surprisingly difficult to work without the hyper key that I have depended on for the last seven or eight years. Anyone got any tricks to get Karabiner-Elements working again in Catalina 10.15.7?
