### ISSUE TITLE
Tips of configuring a Microsoft Sculpt keyboard

### ISSUE THREAD

**Issue by paulleader** [tekezo/Karabiner-Elements#205]
Hey,

First up, thanks so much for producing Karabiner, it's great being able to use better keyboards with my mac.

I have a UK Microsoft Sculpt keyboard that I am trying to remap, but I can't work out how to remap some of the keys.

I need to swap the `@` and `"` over so that `shift-2` gives me a double quote and `shift-'` gives me a `@`. I can't work out if that is possible with Karabiner-Elements.

Also the `#` key gives me a `\`, and `shift-#` gives me '|' instead of a `~`
The `\` key gives me a `§` and `shift-\` gives me `±` instead of `|`

The backtick key in the top left works fine.

There is no key which gives me a #, I have to used cmd-3 to get that.

Any suggestions would be really appreciated.

This is the keyboard

![sculpt_keyboard](https://cloud.githubusercontent.com/assets/802745/18986560/43b2c1b6-86f5-11e6-99c0-1f9d8912fc11.jpg)

For reference here is my old Karabiner configuration script

```
/bin/echo -n .
$cli set remap.commandL2optionL 1
/bin/echo -n .
$cli set remap.commandR2optionR 1
/bin/echo -n .
$cli set remap.optionL2commandL 1
/bin/echo -n .
$cli set remap.optionrcommandr 1
/bin/echo -n .
$cli set remap.pc_application2optionR 1
/bin/echo -n .
$cli set remap.uk_backquote2backslash 1
/bin/echo -n .
$cli set remap.uk_backslash2hash 1
/bin/echo -n .
$cli set remap.uk_section2backquote_ex_vm 1
/bin/echo -n .
$cli set remap.uk_swap_at_doublequote 1
/bin/echo -n .
```

**Comment by jdelStrother** [comment]
I remapped `non_us_backslash` to `grave_accent_and_tilde`, which fixed my need to have the key to the left of 'z' produce a tilde.

Still not figured out how to remap the at-key `@` to double-quote, though.
