### ISSUE TITLE
Migration of Karabiner settings to fully support Neo Keyboard Layout

### ISSUE THREAD

**Issue by triebefx** [tekezo/Karabiner-Elements#209]
Hi,
I'm using the German [Neo Keyboard Layout](http://neo-layout.org/index_en.html), which worked fine with some Karabiner customizations until I installed Mac OS X Sierra. Now I'm trying to get the same layout working again using Karabiner Elements. My initial very simple configuration looks like this, but is still missing a lot:

``` json
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "caps_lock": "left_option"
            }
        }
    ]
}
```

Can someone please help me in getting these essential things working:
- map pressing both shift keys to caps lock
- map backspace key (the one left of return) to left_option or right_option

I would be very happy to enjoy the full Neo Layout again, including the very useful third level.

Thanks for any help, comments or advice.
Felix

**Comment by talha131** [comment]
Try

```json
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "caps_lock": "left_option",
                "delete_or_backspace": "left_option"
            }
        }
    ]
}
```

> map pressing both shift keys to caps lock

See #16

**Comment by neominik** [comment]
Duplicate of #40.

**Comment by fabyeah** [comment]
+1

**Comment by plopix2** [comment]
+1

**Comment by alteroppa** [comment]
+1
