### ISSUE TITLE
Warning bell triggered when using modifier key in some applications

### ISSUE THREAD

**Issue by TSFoster** [tekezo/Karabiner-Elements#21]
If Karabiner Elements is running, using Cmd/Opt/Ctrl/Shift (alone or as part of valid keyboard shortcut) will trigger the warning bell. I've only experienced it while Finder and Karabiner Elements are the frontmost application (doesn't seem to happen with Safari, iTerm2, Messages, iTunes and others).

I didn't notice this in the previous version of Karabiner Elements.

Karabiner Elements v0.90.25  
macOS 10.12 beta (16A313a)  
2012 15" MacBook Pro w/ Retina Display

**Comment by nethergrim** [comment]
Same issue here. MacBook pro 15" 2015 w/ Retina.

I can hear that warning bell almost every time I press Cmd button.
But thankfully, I can disable that annoying sound.
Except of that Karabiner-Elements is working great! I'm able to change input language with Caps Lock again :)

**Comment by talha131** [comment]
I have to add, I too get the bell. But when I use `⌘Command`+`⇥Tab` to switch apps, the warning bell stops in all apps.

So far I haven't figured out when does the bell start ringing again.

**Comment by tekezo** [comment]
Thank you for feedback.
The change for Microsoft Remote Desktop (#15) causes this issue.

I fixed this issue at Karabiner-Elements 0.90.29.
Please confirm it.

**Comment by talha131** [comment]
I can confirm, beeping issue has been fixed since 0.90.29. I also tried the steps reported in #27 and didn't hear any warning bell.

**Comment by TSFoster** [comment]
Yes, this is fixed for me. Closing.
