### ISSUE TITLE
Change shift states of different keys 

### ISSUE THREAD

**Issue by Tsmith18256** [tekezo/Karabiner-Elements#210]
I am trying to create the Programmer DVORAK layout in Karabiner Elements, but I don't see a way to map the keys so that you can separate what is on each key. For example, in Programmer DVORAK that tilde is in the same spot as QWERTY, but the dollar sign is the non-shift state of that key, not the backtick. 

Also, the numbers are all mapped with different symbols and it is reverse, so you have to press shift to get to the numbers.

**Comment by talha131** [comment]
I think you need #16 for it.
