### ISSUE TITLE
Application-specific mappings?

### ISSUE THREAD

**Issue by nickmcummins** [tekezo/Karabiner-Elements#212]
Is this possible with the current version? And if not, is it on the roadmap?

I started using the original Karabiner as it was suggested [on the NoMachine support forums](https://www.nomachine.com/forums/topic/how-to-config-nomachine-5-client-to-treat-cmd-key-as-ctrl-key) as a workaround for the described problem. 

I use NoMachine from a MacBook to a remote Linux machine, and it results in the Command and Control keys being flipped resulting in inconsistent behavior between which keys function as Command/Control in the local and remote machines.

**Comment by talha131** [comment]
See #137

**Comment by wincent** [comment]
Probably should be closed as a duplicate.
