### ISSUE TITLE
Four is mapped to $

### ISSUE THREAD

**Issue by patrkris** [tekezo/Karabiner-Elements#213]
Hi

When I install Karabiner Elements, suddenly the 4-key in the numbers row is mapped to $. All other number keys work fine, but not 4. I use Danish keyboard layout.

Any suggestions?

Best regards,
Patrick

**Comment by talha131** [comment]
@patrkris Please share your karabiner.json and logs.

**Comment by patrkris** [comment]
I have this in my `karabiner.json`:

```
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "caps_lock": "escape"
            }
        }
    ]
}
```
I have attached the log.

[karabiner.txt](https://github.com/tekezo/Karabiner-Elements/files/504275/karabiner.txt)

**Comment by patrkris** [comment]
It helped restarting my computer. I swear I tried that before, but for some reason it now works.
