### ISSUE TITLE
Launcher Mode

### ISSUE THREAD

**Issue by JakeSc** [tekezo/Karabiner-Elements#214]
Launcher Mode was an amazing feature in Karabiner, and one upon which I relied quite heavily.

This feature allows the user to switch to applications by holding `o` and pressing an associated key.
Examples:
- `o`+`x`: Launch Xcode
- `o`+`t`: Launch Terminal
- `o`+`xx`: Launch Simulator
- `o`+`c`: Launch Chrome
- `o`+`a`: Launch Activity Monitor

Is there planned support for Launcher Mode in Karabiner-Elements?

**Comment by talha131** [comment]
See #134 

Please close this issue.

**Comment by JakeSc** [comment]
Closing

**Comment by JakeSc** [comment]
For people searching for this, I built a small utility app inspired by the awesomeness that was Launcher Mode. Check it out here: https://switchfaster.com/
