### ISSUE TITLE
dual space key to space + ctrl config

### ISSUE THREAD

**Issue by manjuXD** [tekezo/Karabiner-Elements#215]
Hi,

I used to use Karbiner/Seil before Sierra to make space held down to behave as ctrl. spacebar behaves as space on tap (not held down).

I didn't find the config option to do this in the elements repo, is this possible in elements?

Thanks and Regards,
ManjuXD

**Comment by talha131** [comment]
Not possible yet. Please follow discussion at #8.

Kindly close this issue.

**Comment by manjuXD** [comment]
@talha131 Thanks!

**Comment by andrzejsliwa** [comment]
looks like its working now: #916
