### ISSUE TITLE
Restarting Karabiner-Elements via CLI to apply changes in JSON file

### ISSUE THREAD

**Issue by nomaed** [tekezo/Karabiner-Elements#217]
Hi,

I wrote a small tool `ksp` (https://github.com/nomaed/karabiner-profile-switch) to quickly toggle between KE profiles from CLI (it's a `node` app).

The one thing I am missing there is restarting KE after saving configuration, so it will be applied immediately.

Is there a good way to restart KE server without using GUI?

At any rate, this is a temporary solution until the official UI is out.

**Comment by cro** [comment]
I thought I read in another thread that KE watches the config file and reloads it when it changes.  Is that not the case?

**Comment by nomaed** [comment]
Not from my experience. Without restarting it, no changes take effect.

**Comment by nomaed** [comment]
Just verified it again.
No effect until the service is restarted.

**Comment by nomaed** [comment]
So after a short googling and figuring out, after updating a profile, I use `launchctl stop` and `launchctl start` on `org.pqrs.karabiner.karabiner_console_user_server` and it works perfectly :)

Closing the issue.

[kps](https://github.com/nomaed/karabiner-profile-switch) v1.0.3 is fully functional. Feel free to use it to switch between profiles while the GUI is not out.
