### ISSUE TITLE
Karabiner-Elements renders Bluetooth Mouse Unusable

### ISSUE THREAD

**Issue by RianGray** [tekezo/Karabiner-Elements#218]
On following setup:
iMac 27, Late 2012
Karabiner-Elements v0.90.45
MS Sculpt Keyboard + Logitech MX Master

Whenever Karabiner is running in the background, the Logitech mouse loses all of its features, such as additional buttons on the side, vertical scroll, and etc, IF it's connected via bluetooth. Everything works fine when it's connected via USB. Another thing I noticed is that Logitech Options (Logitech driver) doesn't pick up the mouse when Karabiner was running, even if it is connected via bluetooth. Only way for the driver to recognize the mouse as Logitech mouse is to either quit Karabiner or use USB dongle they provided.

**Comment by torsteins** [comment]
Possible duplicate: https://github.com/tekezo/Karabiner-Elements/issues/39

**Comment by RianGray** [comment]
Duplicate.

**Comment by rnbarg** [comment]
Same problem - the workaround is to turn Bluetooth on and off and the mouse will work fine.  In order to do this you have to have a 2nd mouse using USB also plugged in. Once you cycle the BT on and off the mouse works fine.
