### ISSUE TITLE
Problem with Keyboard Maestro when Karabiner is loaded

### ISSUE THREAD

**Issue by Richie765** [tekezo/Karabiner-Elements#220]
I'm using Keyboard Maestro to do the following key mappings:

```
Cmd-E -> Ctrl-Opt-E
Cmd-S -> Ctrl-Opt-S
```

I use those mappings to easily edit and save pages on Wikipedia.

However when Karabiner is loaded, the mappings don't work, without Karabiner they work fine.

Also, when I swap the mappings, they also work again.

```
Cmd-S -> Ctrl-Opt-E
Cmd-E -> Ctrl-Opt-S
```

So something strange happens when the keys are similar. I already contacted someone from Keyboard Maestro and he suggested to report the issue here.

It doesn't matter which Karabiner rules I have, the problem happens also with an empty configuration. The same macros worked fine with OS X El Capitan with the previous Karabiner.

Hopefully it can be fixed.

**Comment by jondkinney** [comment]
I notice a similar problem with the Keyboard Maestro "This Device Key" trigger. Even an empty karabiner-elements config it interferes with it, preventing Keyboard Maestro from registering presses of that device key. Maybe in my case it's expected though if Karabiner is mapping low enough for that keypress to not even look like that device key anymore. However when I use the macOS system preferences to remap caps lock to ctrl, Keyboard Maestro still registers caps lock as the "device key"...

**Comment by Richie765** [comment]
Whatever it was, my problem was solved in one of the last updates.

**Comment by Richie765** [comment]
I have the same problem as @jondkinney now. When Karabiner Elements is loaded (regardless of config), "This Device Key" triggers no longer work in Keyboard Maestro.
