### ISSUE TITLE
Keyboard layout independence?

### ISSUE THREAD

**Issue by kbd** [tekezo/Karabiner-Elements#221]
Hi, thanks so much for Karabiner and for working to update it for Sierra.

One of my frustrations with Karabiner is that because it always needs to refer to the hardware key instead of the logical key, it's impossible to configure in a way that doesn't break if I change my keyboard layout (from dvorak to qwerty, for example).

Will it be possible to configure Elements based on the logical key, like "p", and not have to map it to the hardware key for "r" if I'm using dvorak?

Thanks!

**Comment by yishanhome** [comment]
I also want
