### ISSUE TITLE
Conflict with Adobe Applications spacebar behavior

### ISSUE THREAD

**Issue by prohtex** [tekezo/Karabiner-Elements#222]
Wasted an hour this morning and trashed a whole user account trying to get to the bottom of this. For whatever reason, this version of Karabiner Elements breaks Photoshop spacebar behavior (press and hold to toggle pan tool). Using KE version 0.90.46 and PS version 20160603.r.88 x64

**Comment by princed** [comment]
Doesn't work for me in 0.90.29 as well.

**Comment by jonhurrell** [comment]
Breaks LaunchBar Modifier taps.

**Comment by notagit** [comment]
Also Illustrator, *really* annoying, have to quit Karabiner to work in Illustrator

**Comment by markandrewj** [comment]
Issue seems to resolved in newest update.

**Comment by Revod** [comment]
I have problems doing zoom, practically I can't do that but if quit the app illustrator let me use without problem
