### ISSUE TITLE
Have a plan to support multiple profile?

### ISSUE THREAD

**Issue by aniude** [tekezo/Karabiner-Elements#226]
This is the base feature with Karabiner.  because the external keyboard and internal keyboard has different layout with rules, so I have to switch with them. 
Another question is when I use the external keyboard,  I need the disable the internal keyboard.

**Comment by gerritgriebel** [comment]
I'd like the same effect as Karabiner feature "Don't remap an internal Keyboard"

**Comment by samscam** [comment]
A big +1 from me on this. I've got radically different things going on (mostly function key related) on my external vs internal keyboards.
