### ISSUE TITLE
 Space to Shift_L

### ISSUE THREAD

**Issue by jan-matthis** [tekezo/Karabiner-Elements#228]
Karabiner comes with an option "Space to Shift_L (+ when you type Space only, send Space)" which is extremely useful. It would be great if it was possible to get this working with Elements.

In Karabiner the setting used: `__KeyOverlaidModifier__ KeyCode::SPACE, KeyCode::SHIFT_L, KeyCode::SPACE`

**Comment by erwald** [comment]
To add to this, here is the full definition from Karabiner:

```xml
      <item>
        <identifier>remap.samples_BlockUntilKeyUp_with_KeyOverlaidModifier</identifier>
        <name>With KeyOverlaidModifier</name>
        <appendix>* Change the space key to the left shift key.</appendix>
        <appendix>* Send a space key event when the space key is pressed alone.</appendix>
        <appendix></appendix>
        <appendix>Input: <![CDATA[  Space down -> T down -> T up -> Space up:  ]]></appendix>
        <appendix>Output: Shift+T</appendix>
        <appendix></appendix>
        <appendix>Input: <![CDATA[  Space down -> T down -> Space up -> T up:  ]]></appendix>
        <appendix>Output: Shift, Space, T</appendix>
        <appendix></appendix>
        <autogen>
          __KeyOverlaidModifier__
          KeyCode::SPACE,
          KeyCode::SHIFT_L,
          KeyCode::SPACE,
        </autogen>
        <block>
          <modifier_only>ModifierFlag::SHIFT_L</modifier_only>
          <autogen>__BlockUntilKeyUp__ KeyCode::SPACE</autogen>
        </block>
      </item>
```

**Comment by erwald** [comment]
Perhaps https://github.com/tekezo/Karabiner-Elements/pull/247 makes this possible?

**Comment by jan-matthis** [comment]
I couldn't get it to work with #247,  probably because that uses the `FlagsChanged` event type which  `Control_L` triggers but `Space` doesn't trigger.

**Comment by jan-matthis** [comment]
This became possible as of `0.91.3`, see https://github.com/tekezo/Karabiner-Elements/issues/8#issuecomment-309037790

```
(...)
"complex_modifications": {
  "rules": [
    {
      "manipulators": [
        {
          "description": "Spacebar to left_shift (+ when you type spacebar only, send spacebar)",
          "from": {
            "key_code": "spacebar",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "left_shift"
            }
          ],
          "to_if_alone": [
          {
            "key_code": "spacebar",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          }
          ],
          "type": "basic"
        }
      ]
    }
  ]
}
(...)
```

**Comment by RuslanIsh** [comment]
Has anybody noticed a slight lag when using this modification? 
When I use spacebar as just a spacebar without pressing any other key there is a very slight but still noticeable delay before producing a whitespace. So when I type fast there could be a few cases where pressing a spacebar and then a key would register as pressing a spacebar together with the key producing a capital letter.

**Comment by tpj2018** [comment]
I am having the same issue as Ruslanish. I cant type on my normal speed with this. Ive tried changing the parameters but i guess i will have to type slower.

**Comment by erwald** [comment]
I assume you account for the fact that, when using this modification, it can only ever trigger the space bar press when you _release_ the space bar? So in this sense there will inherently be some delay before the space is registered (because it's unclear until then whether it's being used as a space or as a shift).

**Comment by RuslanIsh** [comment]
Yes, I do realize that. But the delay is quite noticeable. I did not measure it, but subjectively it is over a second, maybe two.

**Comment by wintervolcano** [comment]
Has anyone found a workaround for the issue @ruslaniv mentioned? I'm still experiencing this. If there was a way to reduce the lag between the space bar release and the next keypress.
