### ISSUE TITLE
"There isn't a keyboard connected." Popup

### ISSUE THREAD

**Issue by mattdbower** [tekezo/Karabiner-Elements#230]
<img width="635" alt="screen shot 2016-10-03 at 20 43 34" src="https://cloud.githubusercontent.com/assets/9146238/19059025/52549976-89aa-11e6-8e33-fb55e51acd38.png">
I have all of my single key to single key mappings working in Karabiner-Elements, but something in my configuration seems to trick my Mac into thinking it doesn't have a keyboard connected. Everything is working as I expect, but every time I wake my MacBook Pro from sleep I get a dialog asking me to plug in or pair a keyboard. I can simply close the message by quitting the Bluetooth Setup Assistant, but I shouldn't be seeing it at all. Below is the contents of my karabiner.json:
```json
{
  "profiles": [
    {
      "name": "Default profile",
      "selected": true,
      "simple_modifications": {
          "caps_lock": "f16"
      },
	  "fn_function_keys": {
          "f1": "vk_consumer_brightness_down",
		  "f2": "vk_consumer_brightness_up",
		  "f3": "f13",
		  "f4": "vk_launchpad",
		  "f5":  "vk_consumer_illumination_down",
		  "f6":  "vk_consumer_illumination_up",
		  "f7":  "vk_consumer_previous",
		  "f8":  "vk_consumer_play",
		  "f9":  "vk_consumer_next",
		  "f10": "mute",
		  "f11": "volume_down",
		  "f12": "volume_up"
      }
    }
  ]
}
```

**Comment by brkattk** [comment]
Duplicate to #201  ?

**Comment by mattdbower** [comment]
My bad. I looked but couldn't find anyone else reporting the same issue.
