### ISSUE TITLE
USB Mouse only works after unplugging and replugging it

### ISSUE THREAD

**Issue by ghreat** [tekezo/Karabiner-Elements#232]
It seems the detection and capture of USB devices is different if it happens at program launch compared to when Karabiner-Elements is already running.

_Things I have noticed:_
1. My mouse **always** works when Karabiner-Elements **isn't** running. 
2. My mouse **doesn't work** when Karabiner-Elements is **started with the mouse plugged in**.
3. My mouse **works fine again after unplugging and replugging it** with Karabiner-Elements running.

As this means that my mouse works fine after sleep and/or whenever it is replugged this is a very minor issue for me. More of an annoyance that I only notice on reboot and whenever Karabiner-Elements is relaunched (after autoupdates).

**Comment by dapetcu21** [comment]
I can confirm this happens with my Bluetooth mouse as well (MS Sculpt Confort)

**Comment by nanno77** [comment]
I am wondering if this isn't just mice, but other USB peripherals as well. I have been having a problem with my AudioEngine 2+ USB speakers loosing connection after a period of time, even while in use. Unplugging them and replugging usually seems to work.

**Comment by ghreat** [comment]
@nanno77 That shouldn't be an issue any longer. Under "Devices" you can select which USB devices Karabiner-Elements can modify.
