### ISSUE TITLE
Input lag/latency when using combo keys

### ISSUE THREAD

**Issue by admosity** [tekezo/Karabiner-Elements#234]
Not sure if anyone else has experienced this issue, but I seem to have lag or the modifier key doesn't register. It seems to happen when I'm typing faster and I didn't experience this when using Seil in mac 10.11.

Example: Press cmd+a, end up typing a

MacOS 10.12
Also using a poker 3 keyboard, but not sure if that affects anything.
**karabiner.json**

``` JSON
{
  "profiles": [
    {
      "name": "Default profile",
      "selected": true,
      "simple_modifications": {
        "caps_lock": "escape",
        "escape": "grave_accent_and_tilde",
        "left_command": "left_option",
        "left_option": "left_command"
      }
    }
  ]
}
```

**Comment by heyrm** [comment]
Hey, I am having many issues with my poker 3 too, have got the fn key to work?
