### ISSUE TITLE
Swap numbers to symbols 

### ISSUE THREAD

**Issue by aureliensibiril** [tekezo/Karabiner-Elements#239]
Is it possible to remap all at once the numbers to the symbols ? Like this option on the old karabiner : 

![capture d ecran 2016-10-05 a 09 19 46](https://cloud.githubusercontent.com/assets/81782/19105244/56735910-8ae1-11e6-8c74-2a17d859a6c1.png)

I tried to change them one by one but how do I find the name of the symbole key ? 

When I do : "1":"!" I got a  [warning] unknown key_code:!

**Comment by freebyte** [comment]
I would also really like to know about this

**Comment by aureliensibiril** [comment]
Any news about this ?

**Comment by chances** [comment]
Have there been any developments related to this issue?

**Comment by aureliensibiril** [comment]
Hello, it has just been solved in the beta build thanks to the "complex  modifications" feature. See https://github.com/pqrs-org/KE-complex_modifications/blob/master/src/json/exchange_numbers_and_symbols.json.erb

**Comment by anandkumar89** [comment]
I want way to toggle between numbers and symbols in same row. 

While typing latex, I rarely use numbers but passwords/excel etc need numbers.I want to toggle by long pressing `esc` between two modes. Could there be a way without using sticky keys or modifier?
