### ISSUE TITLE
Remapping Capslock to Escape and Control (CapsLock to F19)

### ISSUE THREAD

**Issue by domi91c** [tekezo/Karabiner-Elements#24]
I'm sorry if this has been answered, but is it possible with this version of Karabiner to remap CapsLock to Escape when tapped and Control when held? Or do we still have to wait for a new version of Seil for that?

**Comment by jasonlong** [comment]
@domi91c Did you find the answer to this yourself? I'm curious about this as well.

**Comment by scarfacedeb** [comment]
@domi91c @jasonlong see: https://github.com/tekezo/Karabiner-Elements/issues/8
