### ISSUE TITLE
Press Command+Q twice to Quit Application

### ISSUE THREAD

**Issue by gabrielmaldi** [tekezo/Karabiner-Elements#242]
I love the `Press Command+Q twice to Quit Application` setting in Karabiner. I just updated to macOS Sierra and now I'm trying to get the same behavior with Karabiner Elements. Is there a way to achieve this by editing `karabiner.json`? Thank you.

**Comment by mmmulani** [comment]
@tekezo おはよう！I miss this feature as well and am interested in working on it. Do you have any links to the code in old Karabiner and the new Karabiner elements that could help in making a pull request?

**Comment by raulchen** [comment]
I implemented this feature with Hammerspoon. 
https://github.com/raulchen/dotfiles/blob/master/hammerspoon/double_cmdq_to_quit.lua

**Comment by gabrielmaldi** [comment]
@raulchen Thanks! I just installed Hammerspoon and your script and it works like a charm!

Is there a way to "import" `double_cmdq_to_quit.lua` from `init.lua`? (for the time being I just copied your script into `init.lua`).

**Comment by raulchen** [comment]
@gabrielmaldi glad that this could help you. you can do `require("double_cmdq_to_quit")` in your `init.lua`

**Comment by jeremyclarke** [comment]
THANK YOU @raulchen! So this is just a totally separate solution, but glad to have found it here. 

To make it a little easier on anyone else like me who had no idea about Hammerspoon:

* Hammerspoon is an automation app, it has an unusual setup procedure but only takes a couple minutes to install: http://www.hammerspoon.org/go/
* It lets you script your macOS with a text file you open by going to the Hammerspoon menu icon and clicking OPEN CONFIG.
* You can get the "Press Command+Q twice to Quit Application" feature working by pasting @raulchen 's script into that file: https://github.com/raulchen/dotfiles/blob/master/hammerspoon/double_cmdq_to_quit.lua
* To make it active click on the Hammerspoon menu icon and choose RELOAD CONFIG. 

So far it's doing what I hoped for.

**Comment by gabrielmaldi** [comment]
@jeremyclarke I think it's better to save the script in its own file and then `require("double_cmdq_to_quit")` from Hammerspoon's config (`init.lua`). Otherwise, if you paste other scripts inside the main config file, it will become difficult to maintain. Just in case you want to update your steps 👍

**Comment by lstebner** [comment]
@jerclarke and @raulchen saving the day! this was literally the only feature i downloaded the karabiner app for, and i've been infinitely confused (and accidentally quit a billion apps) ever since karabiner just decided to not recreate this feature for no good reason. i owe you both coffee if i ever see you in the real world
