### ISSUE TITLE
internal keyboard `g` key dont work anymore

### ISSUE THREAD

**Issue by monzy613** [tekezo/Karabiner-Elements#243]
I just uninstall this karabiner elements, and I found that my internal keyboard `g` key dont work anymore.. I reinstall it again and the g work, and I then uninstall it again, well, `g` dont work again...
I try to restart my mac, I found in the login password input, I can input `g` from my internal keyboard, but when logined, it not work anymore. is there any service still running when I uninstall this app? I'm writing this issue with my external keyboard... thank u,

**Comment by monzy613** [comment]
restart again, gggggggg work well now

**Comment by DCCXI** [comment]
I have the same issue here. It's still not resolved in 0.90.68

**Comment by monzy613** [comment]
@DCCXI did u uninstall it and restart your mac? it work well for me

**Comment by kitora** [comment]
I have same issue. After I uninstalled and restarted it's not solved on 0.90.68.
