### ISSUE TITLE
Can we set device limit now?

### ISSUE THREAD

**Issue by zanderzhng** [tekezo/Karabiner-Elements#25]
want to use different profile for different devices.

**Comment by mgansler** [comment]
That's basically my only reason to use Karabiner(-Elements). My internal and external Keyboard have different layouts and I used Karabiner to change all the keys that are different.
So in short, I would be very happy to see this feature implemented, if possible at all.

**Comment by suu----** [comment]
pddg/karabiner_profile_changer: Profile change automatically for karabiner-elements in macOS Sierra. <https://github.com/pddg/karabiner_profile_changer>
let's use this

**Comment by mgansler** [comment]
If I understood it correctly the profile changer switches to a certain profile depending on what device is connected. In my case, there are always two devices connected simultaneously and I want to use both at the same time.

**Comment by tekezo** [comment]
You can ignore devices in the latest version.
