### ISSUE TITLE
Swapped ^ and < on external german windows keyboard

### ISSUE THREAD

**Issue by 0x6368** [tekezo/Karabiner-Elements#252]
When I start karabiner elements, my keys < (usually the key next to the left shift key) and ^ (usually next to the 1-key) are swapped. When I delete /Library/Preferences/com.apple.keyboardtype.plist, reboot and let the keyboard assistant identify my keyboard again, everything seems to work again, but once I start karabiner elements, these keys are swapped again.

**Comment by samscam** [comment]
I have a similar issue with my ` and § keys getting swapped on my UK external USB keyboard. The keys on the internal keyboard remain as they should.

**Comment by paulgessinger** [comment]
Same here. It's only on the external keyboard, the internal one works fine.

**Comment by 0x6368** [comment]
Duplicate of https://github.com/tekezo/Karabiner-Elements/issues/90

**Comment by paulgessinger** [comment]
But the other one is also closed...

**Comment by 0x6368** [comment]
I just found a temporary fix: https://github.com/tekezo/Karabiner-Elements/blob/master/examples/switch_grave_accent_and_tilde_and_backslash.json

**Comment by Johannes7895** [comment]
this is still happening to me - however I manually added the fix as presented by 0x6368 and that's working
