### ISSUE TITLE
KE blocks keyboard when waking up on 10.12.1 (16B2338c)

### ISSUE THREAD

**Issue by Y-knot** [tekezo/Karabiner-Elements#253]
A really strange but definite thing happens on macOS Sierra 10.12.1 public beta 3 (build 16B2338c). Given: MBA 13" mid 2012, embedded keyboard.

When trying to wake-up the laptop from sleep by pressing any key, the black sleep screen does not fade away, whatever key is being pressed. Only trackpad or the power button are able to wake the laptop up. Important notes:
a) Right after reboot, if I'm not logging in for a while letting the laptop to enter sleep mode, a key press DOES wake it up. But only the first wake-up after a reboot works so, any following does not.
b) All keystrokes I press when trying to wake the thing up, get recorded and show up in the password field as dots. 

Also, sometimes after login I get a Bluetooth Setup Assistant window that searches for a bluetooth keyboard and says that I don't have any keyboard connected. Not sure if this has something to do with the KE.

If I quit the KE everything gets to normal. Prior to PB3 of Sierra I had no such a problem. Guess Apple changed some thing in keyboard drivers for support of the future MPB's rumored touch bar.

**Comment by dlehman** [comment]
Ah ha, that's what it is! I'm experiencing these exact symptoms in Sierra 10.12 (doesn't wake up, bluetooth setup assistant comes up), but I assumed it was a bug in Sierra, didn't think it might be related to KE.

**Comment by anugupta** [comment]
I think this is the same as #64

**Comment by Y-knot** [comment]
Duly noted. Thanks!

**Comment by larpo** [comment]
Lol, I thought this was a Sierra bug /o\ Makes sense now... Good to learn also that I'm not the only one getting the bluetooth setup assistant.
