### ISSUE TITLE
Cant use shift+tab in steam

### ISSUE THREAD

**Issue by kubofonista** [tekezo/Karabiner-Elements#259]
As in title - after enabling karabiner-elements it is not possible to use shift+tab in any steam games to activate Steam Overlay.

After disabling karabiner elements it its normally possible.

**Comment by Modi34** [comment]
same bug here https://github.com/tekezo/Karabiner-Elements/issues/198

**Comment by Modi34** [comment]
and here https://github.com/tekezo/Karabiner-Elements/issues/120

**Comment by kubofonista** [comment]
Fixed in 0.90.47
