### ISSUE TITLE
Swap Key and Shift+Key functionality?

### ISSUE THREAD

**Issue by phoffer** [tekezo/Karabiner-Elements#26]
I looked through `event_manipulator.hpp` and `configuration_core.hpp`, but I didn't find anything that made me think this is possible yet. I'm just wondering if I'm missing something? 

To be clear, I'm looking for the ability to invert the actions for one specific key. i.e. the semicolon key sends a colon, and shift-semicolon sends a semicolon.

**Comment by drselump14** [comment]
would love this feature

**Comment by phoffer** [comment]
@drselump14 I've gotten this specific functionality working natively by following [these instructions](http://xahlee.info/kbd/osx_keybinding.html).

Basically, create a file `~/Library/KeyBindings/DefaultKeyBinding.dict` with the following content:
```
{
";" = ("insertText:", ":");
":" = ("insertText:", ";");
}
```

**Comment by phoffer** [comment]
This is now possible with the current version of Karabiner Elements (0.91.12). Add the following to the `complex_modifications` => `rules` => `manipulators` section of `karabiner.json`:

```json
{
    "description": "Colon",
    "from": {
        "key_code": "semicolon",
        "modifiers": {
            "optional": [
                "caps_lock"
            ]
        }
    },
    "to": [
        {
            "key_code": "semicolon",
            "modifiers": [
                "left_shift"
            ]
        }
    ],
    "type": "basic"
},
{
    "description": "Semicolon",
    "from": {
        "key_code": "semicolon",
        "modifiers": {
            "mandatory": [
                "shift"
            ],
            "optional": [
                "caps_lock"
            ]
        }
    },
    "to": [
        {
            "key_code": "semicolon"
        }
    ],
    "type": "basic"
}
```
[Here is a gist](https://gist.github.com/phoffer/68b48448361a6baa0249e01bdef273c7) with a full `karabiner.json` (it has this trick and the caps to hyper/escape)
