### ISSUE TITLE
Mouse buttons keycodes?

### ISSUE THREAD

**Issue by GhostValk** [tekezo/Karabiner-Elements#261]
Sorry if it's a bit obvious the answer, but, what are the keycodes for the mouse buttons? I've tried button1, button2, button3, etc. unsuccesfully (are already implemented?)

**Comment by graygilmore** [comment]
I've gone through the source and have been unable to figure it out. I thought I could do something like:

```
{
  "profiles": [
    {
      "name": "Default profile",
      "selected": true,
      "simple_modifications": {
        "caps_lock": "escape"
      },
      "fn_function_keys": {
        // mac function stuff
      },
      "pointing_buttons": {
        "button4": "left"
      }
    }
  ]
}
```

I feel like I'm on the right path but can't quite filter through the source to figure out where it should be (v0.90.46).

**Comment by mikefoley** [comment]
I'd love to know as well. I miss my "back" key on my mouse!

**Comment by GhostValk** [comment]
Mouse usage is key for me, i got Dashboard and Expose binded to lateral buttons of the mouse =/

**Comment by GhostValk** [comment]
Any update here?

**Comment by SaschaKrieg** [comment]
I also want to know how to map a key to a mouse button click.

**Comment by GhostValk** [comment]
It would be good to have an answer from a dev, just to know if the mouse buttons can't currently be remapped or they can be but i'm not seeing the option :s

**Comment by kurtlloyd** [comment]
I'm also hoping that mapping of keys (e.g., R-command, R-option) to mouse keys (e.g., middle-click, right-click) will be added.  That is critical for me.  It worked great in the original Karabiner.

**Comment by LunaticoCR** [comment]
+1 on this. I used to have middle button mapped to left alt which in return through BetterTouchTools would help me drag windows easily.
Hope a dev can chime in and shed some light.

**Comment by AJLivine** [comment]
+1. I understand tekezo is incredibly busy working on Karabiner, but I hope he finds some time to at least let us know if this is possible.

**Comment by sunaj** [comment]
+1 from me too - its one of primary features of Karabiner for me. Thanks for any time / energy spent on this aspect! :)

**Comment by ngtjah** [comment]
i'm a curious party

**Comment by sanderboele** [comment]
I would love to be able to map button4 to cmd-[

**Comment by luispedrofonseca** [comment]
+1

**Comment by jhimanka** [comment]
Now that MacOs provides capslock->control, the only reason to use Karabiner for me is to map left mouse button to left_control. A key issue.

**Comment by pattulus** [comment]
I'd love to see this getting a higher priority, too. I can simulate Karabiner's other features with other software, or, my Ergodox EZ, but when it comes to my 6 button mouse, I'm out of luck so far. It's my main usage for Karabiner, along with my Trackball buttons.

I'd love to use this again:

![](https://cl.ly/k9DY/Karakiner%20Mouse.png)

**Comment by piotr-tobolski** [comment]
Any news on this one? Simple mapping mouse buttons (3+) to keyboard or actions like previous/next space would be amazing. This was the only thing I used in original Karabiner.

**Comment by oin** [comment]
I got tired of waiting for this, so I wrote [Clicker](https://github.com/oin/Clicker), a little app with no user interface that translates presses/releases of a key to presses/releases of the left mouse button.
I've tested it for two months on OS X 10.11 and macOS 10.12, and it works flawlessly, even for complex mouse dragging operations.
The only downside is that it doesn't work when a password field is focused (a security limitation of the Event Tap library).

**Note that this doesn't translate mouse button presses to key presses or actions** (even though one could make it work based on similar code).

Feel free to use it and modify it until Karabiner-Elements supports keyboard key to mouse button mapping.

**Comment by LunaticoCR** [comment]
@tekezo Are you planning on implementing mouse button mapping support at some stage? Thanks!

**Comment by timbitzen** [comment]
My Google searches for how to use the scroll drag on my Logitech mouse on my MBP pointed me to karabiner Elements (which I already had installed). Bummer that it's not working. I miss my Magic Mouse, but between it and the Magic Keyboard, I had gotten tennis elbow.

**Comment by PayneJoe** [comment]
still be waiting for it

**Comment by nawkwan** [comment]
I'd love to map button4/button5 to <cmd><left_arrow>/<cmd><right_arrow>, respectively.

**Comment by nawkwan** [comment]
I'd love to map button4/button5 to <cmd>+<left_arrow>/<right_arrow>, respectively.

**Comment by nawkwan** [comment]
I'd love to map <button4>/<button5> to <cmd>+<left_arrow>/<right_arrow>, respectively.

**Comment by nawkwan** [comment]
I'd love to map [button4]/[button5] to [cmd]+<[eft_arrow]/[right_arrow], respectively.

**Comment by jimmy-biznessapps** [comment]
@nawkwan --

```
            "complex_modifications": {
                "parameters": {
                    "basic.to_if_alone_timeout_milliseconds": 1000
                },
                "rules": [
                    {
                        "manipulators": [
                            {
                                "description": "Swipe down to move left one space",
                                "from": {
                                    "pointing_button": "button4",
                                    "modifiers": {
                                        "optional": [
                                            "any"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "left_arrow",
                                        "modifiers": [
                                            "left_control"
                                        ]
                                    }
                                ],
                                "type": "basic"
                            },
                            {
                                "description": "Swipe up to move right one space",
                                "from": {
                                    "pointing_button": "button5",
                                    "modifiers": {
                                        "optional": [
                                            "any"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "right_arrow",
                                        "modifiers": [
                                            "left_control"
                                        ]
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    }
                ]
            },

```

**Comment by jimmy-biznessapps** [comment]
...but the magic sauce, in both "complex" and simple rules, is to use "pointing_button" : "button4" to refer to button4, etc. These work if you put them in the JSON, but as far as I can tell, they don't work the same in the GUI (and show up as weird-looking entries there).

**Comment by threescales** [comment]
![image](https://user-images.githubusercontent.com/15061441/30627028-51e3c91a-9e00-11e7-8661-14fb5ac70c74.png)

I think this function is cool !but it doesn't work in Karabiner-Element.

**Comment by jbwilhite** [comment]
@jimmy-biznessapps Your json isn't working for me, but if I look in the log I see:
`[2017-09-20 11:18:30.594] [info] [grabber] USB Optical Mouse (device_id:3) is ignored.`

So It doesn't look like it's going to register any pointing events.  Do you see your mouse under Devices?  I only have my keyboard and the Apple Internal Keyboard / Trackpad.

**Comment by jimmy-biznessapps** [comment]
I _do_ see my mouse under "devices." So that's probably a prerequisite for this to work.

**Comment by graygilmore** [comment]
@jimmy-biznessapps thanks for that. Unfortunately I have the similar error as above:

```
[2017-09-20 10:46:23.334] [info] [grabber] Razer DeathAdder 2013 (device_id:4) is ignored.
```

Oddly enough the mouse *does* appear under "Devices" in the GUI and I'm able to modify some of its values in the JSON config (for example, setting `"is_keyboard": false` on the mouse causes it to stop working entirely).

I'll have to return to this when I have a little more debugging time.

**Comment by spamwax** [comment]
@nawkwan My device is also ignored in Karabiner. For now to map M4 and M5 to a keystroke I am using [ControllerMate](http://www.orderedbytes.com/controllermate/) app with a custom made program.
(Sample ControllerMate programe: [M4M5.cmate.zip](https://github.com/tekezo/Karabiner-Elements/files/1346299/M4M5-to-CMD.cmate.zip))

**Comment by hanamiche** [comment]
Hello!
From the Karabiner-Elements 11.1.8 mouse was supported!
Mouse buttons 4, 5 and 6 are now available. I also moved in my environment.
I could assign Button 4 to "Back".
Thank you☺️

`                {
                    "description": "button4 → [ + command",
                    "from": {
                        "pointing_button": "button4"
                    },
                    "to": [
                        {
                            "key_code": "close_bracket",
                            "modifiers": [ 
                                "command" 
                            ]
                        }
                    ],
                    "type": "basic"
                },`

**Comment by luispedrofonseca** [comment]
@hanamiche Where do you put that? It didn't work for me if I put it under "Simple Modifications". Under "Complex Modifications" doesn't seem to have that format.

**Comment by LunaticoCR** [comment]
@luispedrofonseca I think you need to pull down a beta build.
![image](https://user-images.githubusercontent.com/2124383/31605861-610bfd9a-b25f-11e7-9cd7-7d4e425bc58a.png)

**Comment by luispedrofonseca** [comment]
@LunaticoCR Thanks, but yes, I have the latest beta. I can assign a mouse button to a key (like backspace) but I can't add the modifiers.

**Comment by hanamiche** [comment]
@luispedrofonseca Hello. I put this file under "Complex Modifications".
Could you please use the json file? [my setting json file.](https://github.com/hanamiche/karabiner-elements-mouse/blob/master/mouse.json)
The path is "~/.config/karabiner/assets/complex_modifications/mouse.json".
(I'm using Japanese keyboard, so I may need to modify "key_code".)

I also made a screen shot of the setting screen.
![screenshot](https://i.imgur.com/mEOIQ1e.png)

I hope to go well.

**Comment by luispedrofonseca** [comment]
@hanamiche That did it! Thanks for the explanation!

**Comment by hanamiche** [comment]
@luispedrofonseca Was good! Congratulations!!! 😉

**Comment by piotr-tobolski** [comment]
Works great. Now I can change spaces by tilting mouse wheel 👍

**Comment by ScottStevenson** [comment]
@piotr-tobolski How did you reference the scrollwheel tilt input? I successfully got all my mouse buttons working, but after digging through the source code I still can't determine how to reference scrollwheel::LEFT and scrollwheel::RIGHT like in the previous version!

**Comment by piotr-tobolski** [comment]
@ScottStevenson in my mouse (Logitech M325) tilting scrollwheel triggers mouse buttons 4 and 5. I am not using any 3rd party drivers or other software. I used Karabiner-EventViewer to check what events are triggered.

**Comment by ScottStevenson** [comment]
@piotr-tobolski Ah I see. I am using a Microsoft Sculpt mouse where tilting the scrollwheel outputs a "ScrollWheel" event in Karabiner-EventViewer with x and y coordinates/velocity. 

After parsing through the source I am pretty sure this can't be referenced in the configuration at this time.

**Comment by nawkwan** [comment]
@jimmy-biznessapps @hanamiche 
The magic sauce of "pointing_button", but it didn't work for me.  In fact, I've tried copying a slightly modified version ([my_mouse.json](http://codepad.org/oPT8rUU4)) of hanamiche's mouse.json settings file under i~/.config/karabiner/assets/complex_modifications/mouse.json and it didn't map correctly.  In fact, the rules didn't even show up under the Complex Modifications tab under KE's Preferences.
![KE Log](https://user-images.githubusercontent.com/4675368/32153420-d261dc20-bd00-11e7-9bae-547b157984b2.png)

![KE Complex Modifications tab](https://user-images.githubusercontent.com/4675368/32153429-ee11be22-bd00-11e7-8983-652b1aaa3dd8.png)

**Comment by hanamiche** [comment]
@nawkwan Hello. I think that ignoring the mouse when looking at the log.
Is karabiner-elements the latest beta version?
  (In my environment, it is 11.1.11)

**Comment by FatCash** [comment]
@hanamiche Thank you very much, works great! Have been waiting for mouse feature forever!

**Comment by nawkwan** [comment]
@hanamiche 
Yes, I have updated to 11.1.11.  The fact that the rules defined in your mouse.json don't even show up on the Complex Modifications tab suggests that something is wrong on my end.  Since the last post, I've taken a closer look at the Log messages and compared it to the USB hardware on my MBP and have discovered where the conflict might be.  But before I continue, I want to apologize for posting the previous screenshots of the Log and the event viewer, because they offer no insights.

This time around, I've disconnected all external USB devices from my MBP and restarted Karabiner-Elements.
![screenshot 2017-10-30 05 33 40](https://user-images.githubusercontent.com/4675368/32165073-f2ab36c0-bd37-11e7-86bd-903235378114.png)
After KE started, I inserted the mouse USB Receiver directly into my MBP.  Here you might be wondering why KE detected and registered ("grabbed") two USB receivers.  Well, that's because I have two device entries with the **same** vendor_id and product_id for the two Logitech USB receivers -- one for the keyboard, and the other one for the mouse.  (Please see lines 234 and 256 of my [karabiner.json](http://codepad.org/tcxPhPMf))  This is probably causing some confusion for KE, because it's recognizing the receiver as both for the keyboard and the mouse.

Now, what I don't understand is why the VirtualHIDPointing device is being ignored.

Here's the Devices listing:
![screenshot 2017-10-30 07 44 19](https://user-images.githubusercontent.com/4675368/32169330-72dca96a-bd46-11e7-9143-ab3da19af7d8.png)

Additionally, there are a few things I'd like to ask about putting settings json files under ~/.config/karabiner/assets/complex_modifications:

Take your [mouse.json](https://github.com/hanamiche/karabiner-elements-mouse/blob/master/mouse.json) for example:
1) Which profile(s) are the rules defined in mouse.json applied to when you stick it under the /complex_modifications directory?

2) A follow up to 1):  When you just stick that mouse.json file under the /complex_modifications directory, how does KE know what type of device are the rules for?  There's no device-related information in mouse.json; you only have rules in there.

Can someone who has pointing_buttons working please share their karabiner.json file?

**Comment by hanamiche** [comment]
@nawkwan Hello, thank you for the information.
My device list is the same Logitech. Even in my environment "USB Receiver" is the only one. 
I have not used the Logitech keyboard, so I unchecked it.
![2017-10-31 10 20 05](https://user-images.githubusercontent.com/19566233/32204197-4d0b97d8-be2b-11e7-8e84-c3855042a35c.png)

It is necessary to enable json in ~/.config/karabiner/assets/complex_modifications from the GUI.
It is merged into ~/.config/karabiner/karabiner.json and it becomes available. So I do not edit karabiner.json directly.
You can activate it for each profile. (Will it be an answer to 1.?)

I will post the procedure.
Karabiner-Elements Preferences -> Complex Modifications -> "Add rule"
![2017-10-31 10 21 29](https://user-images.githubusercontent.com/19566233/32204228-774d34de-be2b-11e7-8d7a-19399cc48348.png)


Since the rule list of the json file placed in ~/.config/karabiner/assets/complex_modifications is displayed
Enable All or, please enable.
![2017-10-31 10 21 57](https://user-images.githubusercontent.com/19566233/32204243-89b9d5e6-be2b-11e7-8323-da485be8bb68.png)

In the Enabled rules, the selected rule will be displayed and ready to use.
(merged into ~/.config/karabiner/karabiner.json)
![2017-10-31 10 22 13](https://user-images.githubusercontent.com/19566233/32204256-9233dcb2-be2b-11e7-80eb-d4912a55df3f.png)



[~/.config/karabiner/karabiner.json is up here.](https://github.com/hanamiche/karabiner-elements-mouse/blob/master/karabiner.json)

(I occasionally have Japanese but do not mind.)


I hope that it will work.

**Comment by xbjconan** [comment]
Hi @jimmy-biznessapps 
Do your json code have a modified function on the tilt and click of the scrollwheel on MS comfort sculpt mouse? If possible could you please share your json code with me/us?

Thank you

**Comment by ultimate-s** [comment]
Anybody have any idea why my Logitech G5 is ignored by Karabiner? It's not in the device list.

[2017-11-06 10:23:42.999] [info] [grabber] USB Gaming Mouse (device_id:2) is ignored.

**Comment by jimmy-biznessapps** [comment]
@xbjconan -- nope, I'm leaving that as-is.

**Comment by rodneicouto** [comment]
Can i remap Command + Left mouse click to Control + Left Arrow and Command + Right Mouse to Control + Right Arrow? Is something like this? 

      ` "manipulators": [
                {
                    "from": {
                        "pointing_button": "RIGHT",
                        "modifiers": {
                          "mandatory": [
                            "command"
                          ],
                          "optional": [
                            "any"
                          ]
                        }
                    },
                     "to": [
                        {
                          "key_code": "right_arrow",
                          "modifiers": [
                            "control"
                          ]
                        }
                      ],
                    "type": "basic"
                }
            ]`

**Comment by MrDesjardins** [comment]
For those who are looking to have the back button to their Microsoft Sculpt mouse on Mac 10.12 you can use the following configuration:

```
{
                        "manipulators": [
                            {
                                "description": "Mouse back",
                                "from": {
                                    "pointing_button": "button4"
                                },
                                "to": [
                                    {
                                        "key_code": "left_arrow",
                                        "modifiers": [
                                            "left_command"
                                        ]
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    }
``` 
Inside `/Users/YOURNAME/.config/karabiner/karabiner.json`

**Comment by connorsadlervelo** [comment]
Thanks very much for this thread, it helped me get my mouse4/5 buttons working as I like them.
Karabiner seems to have some great functionality in this area.
How do we "officially" share these excellent add ons?

**Comment by cdarsch** [comment]
For those of you using a Logitech bluetooth mouse (I have the MX Revolution), are you also using the Logitech bluetooth dongle? I lost mine so I connected via the built-in bluetooth on my mid-2011 Mac Mini. Unfortunately Karabiner isn't showing any mouse click events at all. It shows up under Devices and it's enabled (checked). Any ideas?
