### ISSUE TITLE
Holding cmd to select doesn't work anymore

### ISSUE THREAD

**Issue by dapetcu21** [tekezo/Karabiner-Elements#267]
Reproducible if you try to hold cmd, then click on an item in finder. it will deselect all the other items.

**Comment by johnie** [comment]
+1

**Comment by mafredri** [comment]
I was about to open a similar issue myself, however, when I have rebooted my MacBook, the `Mod + Click` will work for a while, and then at some point it will just stop working until I reboot again.

**Comment by dapetcu21** [comment]
I just had a similar experience. Restarting Karabiner made it work again, but at some point it stops working.

**Comment by ChristianBagley** [comment]
Had this problem too.

> I just had a similar experience. Restarting Karabiner made it work again, but at some point it stops working.
Same here.

During the process of identifying and troubleshooting, I'd restart, delete cache files, and there would be times where functionality would be restored (while Karabiner Elements was still running in background), but then functionality was lost again within minutes. Finally, I realized Karabiner was the likely culprit, and after removing it everything was fine. 

Unfortunately, the console logs didn't yield any useful information. Event viewer showed that the pressing the _CMD_ and _Shift_ keys was still being recognized, though.

**Comment by codyrobbins** [comment]
I’m having the same issue. I originally thought it was some sort of bug in Safari in macOS Sierra because holding down command wouldn’t open links in new tabs anymore, but then I realized I couldn’t select multiple files in Finder and narrowed it down to Karabiner.

**Comment by mafredri** [comment]
@codyrobbins have you updated? The 0.90.47 update improved modifiers, might have fixed the issue.

**Comment by codyrobbins** [comment]
@mafredri Ah, I just did, and yes—the issue seems to be fixed. Thanks!

**Comment by dapetcu21** [comment]
I can't test further, since the latest update [killed my mouse](https://github.com/tekezo/Karabiner-Elements/issues/279), but I'll close this and reopen if anything else comes up.

**Comment by mschae** [comment]
I'm on 0.90.48 still seeing the same issue.

**Comment by codyrobbins** [comment]
Yeah, I restarted my computer this morning and noticed that the problem is happening again, so I don’t think it was fixed. In addition, I noticed that the left option key is not working either. (I have the right option key remapped to right control, so I’m not sure if a similar problem is present with the other option key, or whether that remapping is somehow causing the problem in the first place.)

**Comment by dmdque** [comment]
I'm experiencing this issue as well. All modifiers + click are problematic, but it'll sometimes work if I click without moving the mouse. I'm only using Karabiner-Elements to map caps lock to esc.

Restarting Karabiner-Elements temporarily fixes the problem.

@dapetcu21 can we reopen this issue?

**Comment by codyrobbins** [comment]
I haven’t experienced this issue for a while now so I believe it was fixed (for me at least) in one of the intervening updates since October.
