### ISSUE TITLE
dmesg constantly produces HID Activity Tickle 

### ISSUE THREAD

**Issue by bednya** [tekezo/Karabiner-Elements#271]
Is it normal that dmesg constantly reports "HID Activity Tickle (type:0 sender:1000002ae)"?
version 0.90.47

**Comment by sgalam** [comment]
HID Activity Tickle (type:0 sender:10000094e)HID Activity Tickle (type:0 sender:10000094e)HID Activity Tickle (type:0 sender:10000094e)HID Activity Tickle (type:0 sender:10000094e)HID Activity Tickle (type:0 sender:10000094e)HID Activity Tickle (type:0 sender:10000094e)HID Activity Tickle (type:0 sender:10000094e)HID Activity Tickle (type:0 sender:10000094e)HID Activity Tickle (type:0 sender:10000094e)HID Activity Tickle (type:0 sender:10000094e)HID Activity Tickle (type:0 sender:10000094e)HID Activity Tickle (type:0 sender:10000094e)HID Activity Tickle (type:0 sender:10000094e)HID Activity Tickle (type:0 sender:10000094e)HID Activity Tickle (type:0 sender:10000094e)HID Activity Tickle (type:0 sender:10000094e)HID Activity Tickle (type:0 sender:10000094e)HID Activity Tickle (type:0 sende

the same here!

**Comment by crisidev** [comment]
Same for me, with version 0.90.92

**Comment by jairbj** [comment]
Same for me, with 0.90.92 and 0.91.4. OS X 10.12.5.

**Comment by groundnuty** [comment]
same :(

**Comment by jairbj** [comment]
I solved my problem buying another keyboard and uninstalling Karabiner.

**Comment by tekezo** [comment]
Karabiner-Elements does not output this debugging message. (macOS kernel causes the log.)

Thus, we cannot suppress the message.
Please file this issue to Apple BTS.

**Comment by crisidev** [comment]
@tekezo I would love to do it, but I need more info why this kernel log messages is triggered by karabiner. Care to give me some background on how this works?

**Comment by tekezo** [comment]
The message is from `IOHIDSystemActivityTickle`.
https://opensource.apple.com/source/IOHIDFamily/IOHIDFamily-870.50.33/IOHIDFamily/IOHIDFamilyPrivate.cpp.auto.html

And I think the method is called when HID event is posted from third party device.
(Karabiner-Elements uses the third party device driver Karabiner-VirtualHIDDevice.)
There is no workaround to avoid this message.

**Comment by paulp** [comment]
Anyone on OSX 10.13 who can update this ticket with the behavior there?

**Comment by evandrix** [comment]
*bump*
