### ISSUE TITLE
Remapping key for an external keyboard

### ISSUE THREAD

**Issue by DanielZhangQingLong** [tekezo/Karabiner-Elements#272]
Hi, I am using a Japanese version macbook pro. And I usually use a US layout keyboard.  I found karabiner elements mess them up.

**Comment by mayqiyue** [comment]
+1

**Comment by Min-Ho-Kim** [comment]
+2

**Comment by bingohuang** [comment]
+3

**Comment by kkrauss-gpsw** [comment]
👍

**Comment by maleko** [comment]
+5 I have the same issue. I'm using a Leopold FC660C and just need the external keyboard to be modified, not my macbook pro's

**Comment by dschneller** [comment]
There is two other situations in which a distinction of multiple keyboard becomes relevant:

1. Logitech Presenter -- This laserpointer/clicker acts as a keyboard, but has the shortcut keys for PowerPoint hardcoded. With the old "full" Karabiner I could remap those to work for Keynote. Naturally I would not want letters swapped around on any _other_ keyboard :)
1. I also find it very helpful to swap the Option and Command keys on an external (Windows) keyboard, so my brain does not have to negotiate with my muscle memory over which key is adjacent to the space bar on each keyboard.

**Comment by dlehman** [comment]
+1 (Would like to modify Leopold FC660M, not MacBook Pro keyboard.)

**Comment by starsy** [comment]
+N

**Comment by xdidi3r** [comment]
+1

**Comment by tdehaeze** [comment]
+1 I have a logitech K811 and the function keys are not the same. So It would be nice to remap keys just for this keyboard

**Comment by domi91c** [comment]
+1 I'm using an external mechanical keyboard and I have to remap the command and option keys every time I plug it in.
