### ISSUE TITLE
Can I  combine two keys  to mapping anther key  ?

### ISSUE THREAD

**Issue by menq** [tekezo/Karabiner-Elements#273]
I  want to use  "s + hjkl"  to map to  arrows , can it be possible ? and how ?

**Comment by howiemnet** [comment]
I think you're waiting for issue #16 to be addressed; currently not possible, but might be in the future. Hopefully in the short-term future :)

**Comment by sungjp** [comment]
No, that's a different issue; it's addressing the inverse of what @Menq is asking for. Karabiner used to have this legacy functionality, but not sure if there is a private.xml to edit anymore. This article describes the legacy funcationality: https://coolaj86.com/articles/home-row-arrow-keys-on-os-x-with-karabiner.html

**Comment by akz92** [comment]
@wwwjfy could help us, he's already done the inverse (mapping one key to multiple).

**Comment by zhaozhao** [comment]
working sample: https://pqrs.org/osx/karabiner/complex_modifications/#vi_mode
