### ISSUE TITLE
Move Karabiner config file to ~/Library/Preferences

### ISSUE THREAD

**Issue by ecausarano** [tekezo/Karabiner-Elements#275]
Hi,

it's a Mac app, no need to use ~/.<appName> conventions. The right place should be ~/Library/Preferences

**Comment by memelet** [comment]
Again, I personally like .karabiner.d. I guess it depends if you spend half your time in linux. But I would not object if it changed.

**Comment by asmeurer** [comment]
But it's not a plist any more (which is awesome by the way). Shouldn't Library/Preferences only be plist files?

**Comment by k0nserv** [comment]
Common tools that use ~/. conventions, what I could find on my machine.

+ oh-my-zsh
+ git
+ rbenv
+ bundler
+ vim
+ bash
+ npm
+ cocoapods
+ curl(netrc)
+ docker
+ jupyter notebooks
+ mitmproxy

Also most dotfiles repos and similar setups work with ~/. conventions because most tools use it

**Comment by talha131** [comment]
You should check out this open pull request and @tekezo comment on it 
https://github.com/tekezo/Karabiner-Elements/pull/114

**Comment by ecausarano** [comment]
I understand that many cross-platform applications follow the ~/.appname convention to store their own data, it's a BSD/Linux tradition. I thought that Karabiner was a Mac application so I don't see why it should go with that convention when the platform has a different one altogether.

Let's just stick to the native conventions, going against the grain of the platform may have unintended effects (iCloud based preferences sync, objections from the App Store, I don't know but why risk anything?)
