### ISSUE TITLE
Change config file format to plist

### ISSUE THREAD

**Issue by ecausarano** [tekezo/Karabiner-Elements#276]
Hi, 

It's a Mac application, it's preferable to have a configuration file in plist format. Better switch before too many users create complex configurations in JSON

**Comment by rustyrazorblade** [comment]
I've never used an application where a user had to modify plists.  From a user perspective this makes zero sense.

**Comment by ecausarano** [comment]
Obviously. Neither is editing JSON files the norm, but ATM Karabiner Elements is a WIP with no UI for exactly that kind of preferences editing. Now, before everyone starts sweating over and sharing JSON configurations why don't we move everything to plist and be done with it already?

**Comment by memelet** [comment]
Well, I personally would much rather have json.
