### ISSUE TITLE
0.90.48 killed my mouse

### ISSUE THREAD

**Issue by dapetcu21** [tekezo/Karabiner-Elements#279]
The latest update turned my bluetooth mouse into furniture. In the last version, the mouse would stop working when KE would start, but I could reconnect it and it would work. Now the mouse doesn't work the full time while KE is open.

**Comment by haukurmar** [comment]
I have the same issue, Karabiner-Elements fixed what I needed for the keyboard issues on Sierra, but I can't use it because it killed my wireless mouse.

**Comment by memelet** [comment]
Killed my mouse also. After reboot I got it back even with KE running.

**Comment by dbellizzi** [comment]
Even after rebooting, as soon as KE started up, mouse died.  When I quite KE, mouse comes back, start KE, mouse dies again.

Bluetooth Logitech MX Master

**Comment by RianGray** [comment]
I'm guessing you are having a same issue as I do. #218. There is a compiled issue thread in #39.

**Comment by rnbarg** [comment]
Same problem - the workaround is to turn Bluetooth on and off and the mouse will work fine.  In order to do this you have to have a 2nd mouse using USB also plugged in. Once you cycle the BT on and off the mouse works fine.

**Comment by SConaway** [comment]
working on 0.90.52 after mouse on/off

**Comment by rnbarg** [comment]
There is now a fix for this. Please see [](https://github.com/tekezo/Karabiner-Elements/issues/317#issuecomment-254823960 )

**Comment by dapetcu21** [comment]
@rnbarg Still nothing, sorry.

**Comment by tekezo** [comment]
Thank you for feedbacks!
I added Devices tab in Karabiner-Elements Preferences which allows you to ignore specific devices and ignore the keyboard-and-mouse combined device in default.
Please upgrade to the latest version and check the Devices tab in Preferences.

**Comment by CJSF2323** [comment]
My Logitech M705 doesn't work for ~5 seconds after switching programs. Running 0.90.64 and have disabled the device under Preferences.
