### ISSUE TITLE
What is the syntax for switching command+tab with control+tab?

### ISSUE THREAD

**Issue by afkplus** [tekezo/Karabiner-Elements#281]
I am trying to switch command+tab with control+tab and vice versa but can't find a way to do it.

**Comment by k0nserv** [comment]
You can switch ctrl to command and command to control globally like this 
![image](https://cloud.githubusercontent.com/assets/1333960/19290402/725d2ff4-9007-11e6-985f-1566ffae7257.png)

However you currently can't do so only for the specific combinations

**Comment by afkplus** [comment]
Thanks. I've already done this. The problem is, after doing this I have to press control+tab on the keyboard to switch between applications.

**Comment by k0nserv** [comment]
Was that not then intention?

**Comment by afkplus** [comment]
No, my intention was to switch Mac's keyboard layout to a Linux like layout. I've been using it with Command and Ctrl keys switched, and Command+Tab swapped with Ctrl+Tab. Since Sierra forced Karabiner to change it's own architecture, the option for swapping Command+Tab with Ctrl+Tab is not yet implemented in the UI. So I was looking for a way to do it using the JSON configuration file.

**Comment by k0nserv** [comment]
Ah okay, as far as I understand swapping command + tab with ctrl + tab is not supported yet.

**Comment by brunoimbrizi** [comment]
I found a closed issue in the Karabiner repository asking for the exact same thing: https://github.com/tekezo/Karabiner/issues/161

It would be great to know if there is a way doing the same with Karabiner Elements.

In short: map left_control to left_command and left_command to left_control but at the same time keep the physical shortcut cmd+tab to switch applications.

**Comment by jrhorn424** [comment]
I'm trying to do something similarly impossible with elements. I think the issue is that we don't have specific key combinations as virtual keys in elements.

This is what I'm trying to do (config from Karabiner):

```
<item>
  <name>Disable Command-Tab</name>
  <identifier>private.disable_command_tab</identifier>
  <autogen>
    --KeyToKey--
    KeyCode::TAB, VK_COMMAND | ModifierFlag::NONE,
    KeyCode::VK_NONE
  </autogen>
  <autogen>
    --KeyToKey--
    KeyCode::TAB, VK_COMMAND | VK_SHIFT | ModifierFlag::NONE,
    KeyCode::VK_NONE
  </autogen>
</item>
```

(For motivation as to why someone would want to do this, see: http://blog.erikphansen.com/disabling-command-tab-on-mac-os-x/)

**Comment by ikhlestov** [comment]
Hi!
At least it will be quite cool to know is it possible to perform such settings maybe not from GUI, but from raw .json file?

**Comment by l1bbcsg** [comment]
It seems this is finally possible, at least on 0.91.4:

```
"complex_modifications": {
    "rules": [
        {
            "manipulators": [
                {
                    "description": "Ctrl+Tab to Cmd+Tab",
                    "from": {
                        "key_code": "tab",
                        "modifiers": {
                            "mandatory": [
                                "left_control"
                            ],
                            "optional": [
                                "any"
                            ]
                        }
                    },
                    "to": [{
                        "key_code": "tab",
                        "modifiers": ["left_command"]
                    }],
                    "type": "basic"
                },
                {
                    "description": "Cmd+Tab to Ctrl+Tab",
                    "from": {
                        "key_code": "tab",
                        "modifiers": {
                            "mandatory": [
                                "left_command"
                            ],
                            "optional": [
                                "any"
                            ]
                        }
                    },
                    "to": [{
                        "key_code": "tab",
                        "modifiers": ["left_control"]
                    }],
                    "type": "basic"
                }
            ]
        }
    ]
},
```

At last, my fingers can know peace.

**Comment by johvo** [comment]
**Thank you this works great.** The configuration file can be found in ~/.config/karabiner/karabiner.json and you see the modification directly after saving. (In your Karabiner-Elemnts window you can see in the Log tab what's happening).

**Comment by afkplus** [comment]
Thank you @l1bbcsg!

**Comment by lynnard** [comment]
Anyone found this slightly dissatisfactory in terms of emulation of the original behavior on Mac? With this remap you cannot hold the modifier to keep the 'switcher window' up and press 'tab' or 'shift+tab' at your own pace to get to the correct app.

**Comment by afkplus** [comment]
@lynnard Yes, it is annoying for me also, but it is the best option we have for now, I guess. I'll reopen this issue. Let's see if anyone can come up with a better solution.

**Comment by lynnard** [comment]
I think what would be needed is a small program that toggles a state underneath i.e., when <custom key>+Tab is first pressed, our program (run by Karabiner) notes it down in a flag and translates **all subsequent** <custom key> down events to cmd until it is released; at which point we clear the flag so that key becomes itself again.

This is probably possible with AutoHotKey on Windows - I don't even know if this is possible with the older, more powerful version of Karabiner.

**Comment by rmgaddis** [comment]
Thank you @l1bbcsg ! In my case I wanted the PC Alt-tab functionality and the above fix works for that as well, by swapping "left_control" for "left_option." Combine this with a simple Karabiner swap of left command for left control and all three mod keys are finally working as expected.

**Comment by dvdvdmt** [comment]
> Anyone found this slightly dissatisfactory in terms of emulation of the original behavior on Mac? With this remap you cannot hold the modifier to keep the 'switcher window' up and press 'tab' or 'shift+tab' at your own pace to get to the correct app.

@lingnand 
Moreover [@l1bbcsg's solution](https://github.com/tekezo/Karabiner-Elements/issues/281#issuecomment-311623830) doesn't correctly handle pressing of the `Escape`. When you are switching between apps by using the default `Cmd+Tab` you can press `Escape` and the app switcher stops. But with this modification it will switch you to the selected app which is not correct behaviour.
I've been struggle to solve this for slightly different problem. I wanted to remap `Ctrl+Tab` behaviour in Chrome browser to the `Alt+Y` in order to delegate switching between tabs to [this extension (Popup Tab Switcher)](https://chrome.google.com/webstore/detail/popup-tab-switcher/cehdjppppegalmaffcdffkkpmoflfhkc). I solved all the problems with `Shift` and `Escape` pressings in [this modification](https://github.com/dvdvdmt/my-configs/blob/master/karabiner/Chrome_Ctrl-Tab_to_Alt-Y.json).

Here is an improved version of the macro that maps `Ctrl+Tab` to `Cmd+Tab`

```json
{
  "title": "Maps Ctrl+Tab to Cmd+Tab",
  "rules": [
    {
      "description": "Maps Ctrl+Tab to Cmd+Tab",
      "manipulators": [
        {
          "from": {
            "key_code": "tab",
            "modifiers": {
              "mandatory": [
                "left_control"
              ],
              "optional": [
                "left_shift"
              ]
            }
          },
          "to": [
            {
              "key_code": "tab",
              "modifiers": [
                "left_command"
              ]
            }
          ],
          "type": "basic"
        },
        {
          "from": {
            "key_code": "left_shift",
            "modifiers": {
              "optional": [
                "left_control"
              ]
            }
          },
          "to": [
            {
              "key_code": "left_shift",
              "lazy": true
            }
          ],
          "type": "basic"
        },
        {
          "from": {
            "key_code": "escape",
            "modifiers": {
              "mandatory": [
                "left_control"
              ],
              "optional": [
                "left_shift"
              ]
            }
          },
          "to": [
            {
              "key_code": "escape",
              "modifiers": [
                "left_command"
              ]
            }
          ],
          "type": "basic"
        }
      ]
    }
  ]
}

```

**Comment by afkplus** [comment]
@dvdvdmt This is great and thanks for sharing! One problem I found is that it somehow prevents double keypress. Some software I use have shortcuts set to double taps for certain keys. For example double tapping the shift key opens a search window. Do you have any idea how to fix that behavior?

**Comment by dvdvdmt** [comment]
@afkplus I see, this happens because of the `"lazy": true`. It seems that a slightly modified version of this macro will work in your case:

```json
{
  "title": "Maps Ctrl+Tab to Cmd+Tab",
  "rules": [
    {
      "description": "Maps Ctrl+Tab to Cmd+Tab",
      "manipulators": [
        {
          "from": {
            "key_code": "tab",
            "modifiers": {
              "mandatory": [
                "left_control"
              ],
              "optional": [
                "left_shift"
              ]
            }
          },
          "to": [
            {
              "key_code": "tab",
              "modifiers": [
                "left_command"
              ]
            }
          ],
          "type": "basic"
        },
        {
          "from": {
            "key_code": "left_shift",
            "modifiers": {
              "mandatory": [
                "left_control"
              ]
            }
          },
          "to": [
            {
              "key_code": "left_shift",
              "modifiers": [
                "left_command"
              ]
            }
          ],
          "type": "basic"
        },
        {
          "from": {
            "key_code": "escape",
            "modifiers": {
              "mandatory": [
                "left_control"
              ],
              "optional": [
                "left_shift"
              ]
            }
          },
          "to": [
            {
              "key_code": "escape",
              "modifiers": [
                "left_command"
              ]
            }
          ],
          "type": "basic"
        }
      ]
    }
  ]
}
```

**Comment by afkplus** [comment]
Looks like it works. Thanks @dvdvdmt!

**Comment by ruanima** [comment]
@dvdvdmt  how to `swap Ctrl+Tab and Cmd+Tab`, not only `Maps Ctrl+Tab to Cmd+Tab`.
I try to modify your solution , but not work. 

Thanks

**Comment by nathang21** [comment]
> @dvdvdmt how to `swap Ctrl+Tab and Cmd+Tab`, not only `Maps Ctrl+Tab to Cmd+Tab`.
> I try to modify your solution , but not work.
> 
> Thanks

I think i'm after something similar. I want to swap Command and control like a PC, and have Ctrl + Tab switch tabs (aka in chrome, or finder etc.) and Command + Tab switch windows (aka like AltTab).
This setup works for the most part, but it causes some weirdness and extra keypresses. So close, yet so far. 
![Screen Shot 2020-07-11 at 9 54 50 AM](https://user-images.githubusercontent.com/7875110/87229419-9c01e980-c35c-11ea-8989-823dd743fb97.png)

**Comment by RomanTsaregorodtsev** [comment]
To fully emulate behaviour you need to add this config, so you can hold your `alt` button and use `shift+tab` or use mouse to select application.
```
{
    "description": "Sticky Alt to Cmd Variable",
    "manipulators": [{
        "type": "basic",
        "from": {
            "key_code": "left_alt",
            "modifiers": {
                "optional": [
                    "any"
                ]
            }
        },
        "to": [{
                "set_variable": {
                    "name": "left_alt pressed",
                    "value": 1
                }
            },
            {
                "key_code": "left_command"
            }
        ],
        "to_delayed_action": {
            "to_if_invoked": [{
                "set_variable": {
                    "name": "left_alt pressed",
                    "value": 0
                }
            }],
            "to_if_canceled": [{
                "set_variable": {
                    "name": "left_alt pressed",
                    "value": 0
                }
            }]
        }
    }]
}
```

**Comment by vandemjh** [comment]
> To fully emulate behaviour you need to add this config, so you can hold your `alt` button and use `shift+tab` or use mouse to select application.
> 
> ```
> {
>     "description": "Sticky Alt to Cmd Variable",
>     "manipulators": [{
>         "type": "basic",
>         "from": {
>             "key_code": "left_alt",
>             "modifiers": {
>                 "optional": [
>                     "any"
>                 ]
>             }
>         },
>         "to": [{
>                 "set_variable": {
>                     "name": "left_alt pressed",
>                     "value": 1
>                 }
>             },
>             {
>                 "key_code": "left_command"
>             }
>         ],
>         "to_delayed_action": {
>             "to_if_invoked": [{
>                 "set_variable": {
>                     "name": "left_alt pressed",
>                     "value": 0
>                 }
>             }],
>             "to_if_canceled": [{
>                 "set_variable": {
>                     "name": "left_alt pressed",
>                     "value": 0
>                 }
>             }]
>         }
>     }]
> }
> ```

In order to use the variable in future hotkeys you'll want to swap the `to_delayed_action` and `to_if_canceled` to `to_after_key_up` like this:

```json
{
  "description": "Sticky Alt to Cmd Variable",
  "manipulators": [
    {
      "type": "basic",
      "from": {
        "key_code": "left_alt",
        "modifiers": {
          "optional": ["any"]
        }
      },
      "to": [
        {
          "set_variable": {
            "name": "left_alt pressed",
            "value": 1
          }
        },
        {
          "key_code": "left_command"
        }
      ],
      "to_after_key_up": {
        "set_variable": {
          "name": "left_alt pressed",
          "value": 0
        }
      }
    }
  ]
}
```

Otherwise the variable will be immediately set upon hitting another key after alt.

**Comment by sterlu** [comment]
Hey @RomanTsaregorodtsev and @vandemjh, could you explain how this works? I tried incorporating your snippet into dvdvdmt's solution in order for it to ignore mouse movement, but didn't succeed. The variables being set don't seem to do anything.

**Comment by vandemjh** [comment]
@sterlu What this does is convert the `left_alt` press into a `left_command` press with the side effect of setting a variable, `left_alt pressed` to 1 while `left_alt` is being pressed (and zero otherwise).  What you now do is use the variable `left_alt pressed` in future commands involving `left_alt`. For example here is what I had to open a new iTerm window with Ctrl+alt+t:
```json
{
    "description": "Control+Alt+t opens Terminal",
    "manipulators": [
        {
            "conditions": [
                {
                    "name": "left_alt pressed",
                    "type": "variable_if",
                    "value": 1
                }
            ],
            "from": {
                "key_code": "t",
                "modifiers": {
                    "mandatory": ["command"],
                    "optional": ["any"]
                }
            },
            "to": [
                {
                    "shell_command": "echo ...shell script to open iterm"
                }
            ],
            "type": "basic"
        }
    ]
}
```

**Comment by sinapis** [comment]
@vandemjh can you please explain some more? how is this different from mapping left_option to left_command?
i would like to option+tab to behave like command+tab, but still have left_option key for other stuff.
after using solution alt+tab works great, but alt is no longer option...

**Comment by vandemjh** [comment]
@sinapis This _is_ mapping `left_option` to `left_command` with the side effect of setting a variable while `left_option` is held down. What you will want to do is change your key combos to use this condition:
```javascript
// ...
"conditions": [
                {
                    "name": "left_alt pressed",
                    "type": "variable_if",
                    "value": 1
                }
            ],
// ...
```
instead of this:
```javascript
"from": {
                "key_code": "left_option",
```
That way your combo will only fire if you are holding down the `left_option` key.
Let me know if this doesn't make sense.

**Comment by adrian-v-popescu** [comment]
@vandemjh's solution is still rocking in soon to be 2023.

**Comment by NessDan** [comment]
So I wanted to mimic Windows' Control + Tab and Alt + Tab behavior completely using [AltTab](https://alt-tab-macos.netlify.app/). At the end of the day I wanted Command + Tab to cycle tabs in Chrome or Visual Studio Code and Control + Tab to cycle through the AltTab application picker.

There were some weird oddities with using Shift in all the commands, e.g. Command + Shift + Tab or Control + Shift + Tab but finally @dvdvdmt [solution](https://github.com/pqrs-org/Karabiner-Elements/issues/281#issuecomment-512135421) fixed the problem.

Here's the edits I needed to make to get everything working exactly right:

```json
          {
            "description": "Maps Ctrl+Tab to Cmd+Tab",
            "manipulators": [
              {
                "from": {
                  "key_code": "tab",
                  "modifiers": {
                    "mandatory": ["left_control"],
                    "optional": ["left_shift"]
                  }
                },
                "to": [
                  {
                    "key_code": "tab",
                    "modifiers": ["left_command"]
                  }
                ],
                "type": "basic"
              },
              {
                "from": {
                  "key_code": "left_shift",
                  "modifiers": {
                    "optional": ["left_control"]
                  }
                },
                "to": [
                  {
                    "key_code": "left_shift",
                    "lazy": true
                  }
                ],
                "type": "basic"
              }
            ]
          },
          {
            "description": "Maps Cmd+Tab to Ctrl+Tab",
            "manipulators": [
              {
                "from": {
                  "key_code": "tab",
                  "modifiers": {
                    "mandatory": ["left_command"],
                    "optional": ["left_shift"]
                  }
                },
                "to": [
                  {
                    "key_code": "tab",
                    "modifiers": ["left_control"]
                  }
                ],
                "type": "basic"
              },
              {
                "from": {
                  "key_code": "left_shift",
                  "modifiers": {
                    "optional": ["left_command"]
                  }
                },
                "to": [
                  {
                    "key_code": "left_shift",
                    "lazy": true
                  }
                ],
                "type": "basic"
              }
            ]
          }
```

**Comment by DvoeglazovIlya** [comment]
Maybe it help https://github.com/pqrs-org/Karabiner-Elements/issues/2642#issuecomment-1594632755

**Comment by DvoeglazovIlya** [comment]
I have windows keyboard. In left corner I have keys: ctrl - cmd(win) - alt
What I want:
1. Copy/paste/select all and so on shortcuts like in windows
2. Switch tabs like Ctrl+(Shift)+Tab
3. Switch apps like Alt+Tab and Shift for backward

What I did:
<details>
  <summary>Answer for 1 and 2 item</summary>
  
```
{
  "title": "Personal rules",
  "rules": [
        {
            "description": "Ctrl <=> Cmd",
            "manipulators": [
                {
                    "from": {
                        "key_code": "left_command",
                        "modifiers": {
                            "optional": [
                                "any"
                            ]
                        }
                    },
                    "to": [
                        {
                            "key_code": "left_control"
                        }
                    ],
                    "type": "basic"
                },
                {
                    "from": {
                        "key_code": "left_control",
                        "modifiers": {
                            "optional": [
                                "any"
                            ]
                        }
                    },
                    "to": [
                        {
                            "key_code": "left_command"
                        }
                    ],
                    "type": "basic"
                },
                {
                    "from": {
                        "key_code": "right_command",
                        "modifiers": {
                            "optional": [
                                "any"
                            ]
                        }
                    },
                    "to": [
                        {
                            "key_code": "right_control"
                        }
                    ],
                    "type": "basic"
                },
                {
                    "from": {
                        "key_code": "right_control",
                        "modifiers": {
                            "optional": [
                                "any"
                            ]
                        }
                    },
                    "to": [
                        {
                            "key_code": "right_command"
                        }
                    ],
                    "type": "basic"
                }
            ]
        },
        {
            "description": "Cmd+(Shift)+Tab <=> Ctrl+(Shift)+Tab",
            "manipulators": [
                {
                    "from": {
                        "key_code": "tab",
                        "modifiers": {
                            "mandatory": [
                                "command"
                            ],
                            "optional": [
                                "shift",
                                "caps_lock"
                            ]
                        }
                    },
                    "to": [
                        {
                            "key_code": "tab",
                            "modifiers": [
                                "control"
                            ]
                        }
                    ],
                    "type": "basic"
                },
                {
                    "from": {
                        "key_code": "tab",
                        "modifiers": {
                            "mandatory": [
                                "control"
                            ],
                            "optional": [
                                "shift",
                                "caps_lock"
                            ]
                        }
                    },
                    "to": [
                        {
                            "key_code": "tab",
                            "modifiers": [
                                "command"
                            ]
                        }
                    ],
                    "type": "basic"
                }
            ]
        }
    ]
}
```

<details>
  <summary>VSCode shortcuts</summary>
  
```
[
    {
        "key": "ctrl+tab",
        "command": "workbench.action.nextEditor"
    },
    {
        "key": "ctrl+shift+tab",
        "command": "workbench.action.previousEditor"
    },
    {
        "key": "cmd+`",
        "command": "workbench.action.terminal.toggleTerminal",
        "when": "terminal.active"
    },
    {
        "key": "ctrl+`",
        "command": "-workbench.action.terminal.toggleTerminal",
        "when": "terminal.active"
    }
]
```
  
</details>

But if you want to completely disable built-in macos app switcher, just use unusable key like f16:

<details>
<summary>Replace rule "Cmd+(Shift)+Tab <=> Ctrl+(Shift)+Tab" to "Cmd+(Shift)+Tab => Ctrl+(Shift)+Tab, Ctrl+(Shift)+Tab => f16"</summary>

```
{
            "description": "Cmd+(Shift)+Tab => Ctrl+(Shift)+Tab, Ctrl+(Shift)+Tab => f16",
            "manipulators": [
                {
                    "from": {
                        "key_code": "tab",
                        "modifiers": {
                            "mandatory": [
                                "command"
                            ],
                            "optional": [
                                "shift",
                                "caps_lock"
                            ]
                        }
                    },
                    "to": [
                        {
                            "key_code": "tab",
                            "modifiers": [
                                "control"
                            ]
                        }
                    ],
                    "type": "basic"
                },
                {
                    "from": {
                        "key_code": "tab",
                        "modifiers": {
                            "mandatory": [
                                "control"
                            ],
                            "optional": [
                                "shift",
                                "caps_lock"
                            ]
                        }
                    },
                    "to": [
                        {
                            "key_code": "f16"
                        }
                    ],
                    "type": "basic"
                }
            ]
        }
```
I don't use above rule ("Cmd+(Shift)+Tab => Ctrl+(Shift)+Tab, Ctrl+(Shift)+Tab => f16"), because I use yabai with skhd and replace this shortchut in skhdrc file, for example:
(More about yabai and skhd you can find here https://github.com/koekeishiya/yabai)
<details>
  
```
# Cmd+(Shift)+Tab <=> Ctrl+(Shift)+Tab
cmd - tab : yabai -m space --focus next || yabai -m space --focus first
cmd + shift - tab : yabai -m space --focus prev || yabai -m space --focus last
```
  
</details>
</details>
  
</details>

Answer for 3 item: use [AltTab](https://github.com/lwouis/alt-tab-macos)

**Comment by DvoeglazovIlya** [comment]
[raayu83](https://github.com/raayu83), no when l move mouse alttab not close

**Comment by DvoeglazovIlya** [comment]
[raayu83](https://github.com/raayu83), I use Ventura Version 13.6

**Comment by DvoeglazovIlya** [comment]
I am pc user and I dont have a real mac. I use pc hardvear. I have intel cpu.
So I use hackintosh with opencore and I disable [sip](https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection)

sip I disable, because I use yabai to remove macos animation. 
You can check it in terminal "csrutil status" see sustem settings screen 2.
Before I dont use yabai and sip was enabled, therefore I think it is not matter for karabiner.


My keyboard
[a4tech x7 g700](https://market.yandex.ru/product--igrovaia-klaviatura-a4tech-x7-g700-black-ps-2/1780735503?sku=1576058) 

I send you screnshots of my settings and all rules that I use, try to check maybe you need change some settings:

<details>
  <summary>karabiner screen</summary>

Just copy my file in folder and select all rules in karabiner app.
  
![karabiner](https://github.com/pqrs-org/Karabiner-Elements/assets/15049055/d26b6f76-7423-4a65-b4d4-a6154649d210)

</details>

<details>
  <summary>karabiner all my rules</summary>
  
[Personal rules.json](https://github.com/pqrs-org/Karabiner-Elements/files/13854109/Personal.rules.json)

</details>

<details>
  <summary>alttab</summary>
  
![alttab](https://github.com/pqrs-org/Karabiner-Elements/assets/15049055/542b3e5e-bb18-4abd-ada7-c6192f913934)


</details>

</details>

<details>
  <summary>sustem settings</summary>
  
![settings](https://github.com/pqrs-org/Karabiner-Elements/assets/15049055/d64b12b9-323f-43bc-800b-14405e160e55)

In second screen, maybe you need to select something with karabiner, maybe not
![settings 2](https://github.com/pqrs-org/Karabiner-Elements/assets/15049055/f85faf2a-727c-4b88-85d7-11a9a395022b)


</details>

Yes maybe problems because you use Somoma. I hear that Somoma add  color border if you use apps with screen capture like AltTab.
If above not work try find answer here https://github.com/lwouis/alt-tab-macos

**Comment by cktgh** [comment]
>So I wanted to mimic Windows' Control + Tab and Alt + Tab behavior completely using [AltTab](https://alt-tab-macos.netlify.app/). Effectively, I wanted Command + Tab to cycle tabs in Chrome or Visual Studio Code while Control + Tab would cycle through the AltTab application picker.
> Here's the edits I needed to make to get everything working exactly right:

@NessDan I used to have something like that as well, but there is an issue where mouse movements would send lift up events for the original modifier key even if you held the physical key down. 

In the end I had to use `to_if_other_key_pressed` to properly rebind it. If you are interested you can see my comment in the issue #1554
