### ISSUE TITLE
/bin/sh: line 0: cd: Pods: No such file or directory

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [tekezo/Karabiner-Elements#284]
Hi,

I got the following build error. Any hint?

git clean -f -x -d
./make-package.sh
make build
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
......................................................................
..................................../bin/sh: line 0: cd: Pods: No such file or directory
make[3]: *** [all] Error 1
make[2]: *** [all] Error 2
make[1]: *** [build] Error 2

make: *** [all] Error 99

Maybe "(cd Pods..." in apps/Updater/Makefile:8  is the cause. I tried "pod init", pod complains.

**Comment by HIRANO-Satoshi** [comment]
Pods directory exists in src/apps/Updater.  Why error?

**Comment by tekezo** [comment]
Thank you for feedback.

This issue happen when your working directory contains white space. (eg. `/Users/foo bar/Karabiner-Elements`)

I fixed this issue in 5af95a705072626fe3f73c67e3785c02419ec539 .

**Comment by HIRANO-Satoshi** [comment]
Unfortunately, no. 

/Users/hirano/workspace/Karabiner-Elements

**Comment by tekezo** [comment]
Did you install another `make` command in `/usr/local/bin/make`?
What's result of `make --version` command?

**Comment by HIRANO-Satoshi** [comment]
I don't have /usr/local/bin/make.

/usr/bin/make --version
GNU Make 3.81

MacOS 10.12

I no longer need to build it, since I was given a working version. Thanks.

**Comment by cartwrightian** [comment]
I'm getting the same error. No whitespace in the path.

make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0

**Comment by cartwrightian** [comment]
Changing Makefile in src/apps/Updater/ 
-       (cd Pods && xcodebuild -configuration $(CONFIGURATION) SYMROOT="$(CURDIR)/build")
+       (cd $(CURDIR)/Pods && xcodebuild -configuration $(CONFIGURATION) SYMROOT="$(CURDIR)/build")

fixes the issue for me.
