### ISSUE TITLE
change Fn to left control is not working?

### ISSUE THREAD

**Issue by abellee** [tekezo/Karabiner-Elements#285]
![image](https://cloud.githubusercontent.com/assets/707615/19301041/172a955c-9090-11e6-824e-7ac80824f500.png)
I have set the Simple Modifications like this, but it seems not work?
my keyboard is HHKB Pro 2. Please help! Thanks in advanced!

**Comment by peymankh** [comment]
@abellee Had the same problem. Reinstalling it did it for me.

**Comment by abellee** [comment]
@peymankh thanks, i'll try it!

**Comment by LittleChild** [comment]
I have the same question, I set the 'fn' to 'left_alt', it not work.
but i set the 'fn' to 'up_arrow', it work.
my keyboard is HHKB Pro 2.

**Comment by maplehsu** [comment]
Is there any solution?
