### ISSUE TITLE
Remap the Eject key?

### ISSUE THREAD

**Issue by jonohunt** [tekezo/Karabiner-Elements#286]
I'm not sure if this should be possible, but is there a way to remap the Eject key?

If so, how?

**Comment by tekezo** [comment]
You cannot do it.
https://github.com/tekezo/Karabiner-Elements#limitations

**Comment by PierBover** [comment]
It's possible (at least it worked for me) modifying `simple_modifications.json`:

https://github.com/tekezo/Karabiner-Elements/issues/46#issuecomment-352286177
