### ISSUE TITLE
macOS's ctrl + drag zoom functionality doesn't work after Karabiner-Elements's window loses focus

### ISSUE THREAD

**Issue by pindab0ter** [tekezo/Karabiner-Elements#288]
I'm using the Dvorak example profile that doesn't include any of the modifier keys. The ctrl key seems to be working fine except I can't use it to zoom the screen using ctrl+two-finger-drag.

I resolved this by adding Karabiner-Elements to the Accessibility list:
System Preferences > Security & Privacy > Accessibility

I think there should be a heads up about these kind of issues.

**Comment by pindab0ter** [comment]
Turns out I'm wrong, and adding Karabiner-Elements to the Accessibility list doesn't resolve the problem.

I can only use the zoom functionality using the ctrl key when the Karabiner-Elements application is first loaded and the window is still in focus.

Selecting a different window or closing the window results in the ctrl not working for the zoom functionality anymore. If I go back to the Karabiner-Elements window it still doesn't work. If I then quit Karabiner-Elements and start it again, it works until the window loses focus again.

**Comment by Rdrdul** [comment]
Same experience here. Ctrl + scroll doesn't zoom (nor does it work with the other key options in Accessibility; Option or Command). The key commands for zoom still work (Cmd-Opt-hyphen and Cmd-Opt-=), so Karabiner doesn't disable the zoom function, it just affects the scroll input.

**Comment by ptotheatsign** [comment]
Just wanted to chip in and say I have had this problem too on Sierra trying to do Ctrl+mouse scrolling to zoom.

**Comment by AJeezy9** [comment]
Going to chime in and say this too is troubling me. I might be an odd duck, but I utilize the zoom feature so much that I must disable Karabiner and all my associated keyboard configurations until this issue is resolved.

**Comment by Rdrdul** [comment]
@AJeezy9: I'm like you, and use the zoom feature all the time, but I also depend on the backslash being forward delete, so I'm keeping Karabiner-Elements running and trying to teach myself to use the key commands for zoom (Cmd-Opt-hyphen and Cmd-Opt-=) until the issue is resolved.

**Comment by entonio** [comment]
This is a 'me too' comment. I use ctrl-wheel a lot. It's even worse when using a program which will interpret it as in-program-zoom rather than system zoom.

**Comment by leafnode** [comment]
Same here.

**Comment by rdmendo** [comment]
+1

**Comment by tphares1** [comment]
This is a duplicate of #111.

**Comment by entonio** [comment]
See https://github.com/tekezo/Karabiner-Elements/issues/89
