### ISSUE TITLE
ステアーマウスと競合します。

### ISSUE THREAD

**Issue by kokichiru** [tekezo/Karabiner-Elements#289]
お世話になっております。
ステアーマウス5と併用しようとすると、ステアーマウスがクラッシュしてしまいます。
サポートに問い合わせたところ、「Karabiner-Elementsがマウスの制御を奪ってしまう」のが原因だそうです。
お手数ですが解決策があればご呈示願えればと思います。
よろしくお願いいたします。

使用マウス：Logicool　G700ｓ
OS：10.12

**Comment by zhexuany** [comment]
@kokichiru I think you should use English. Otherwise, except these people know Japanese, no one can really help you.

**Comment by kokichiru** [comment]
Karabiner-Elements confilict SteerMouse.
