### ISSUE TITLE
F13 remap issue

### ISSUE THREAD

**Issue by toxik** [tekezo/Karabiner-Elements#29]
Hiya,

I remapped the caps lock key to F13 and tried to use it as a iTerm2 hide/show hotkey.
In the settings dialog it looks fine as "F13", however when I press it the window doesn't show up.
Also if I'm in a terminal the capital letter "P" is printed.

Changing from "f13" in the config file to "international1" and using that as a hotkey works without any problems.

Something wrong with F13 in particular?
![screen shot 2016-09-20 at 23 50 45](https://cloud.githubusercontent.com/assets/235319/18688724/3f278816-7f8e-11e6-8792-b71766a71c1a.png)

**Comment by jonaswisplinghoff** [comment]
Hi,

I have the same problem when trying to use the capslock -> f13 mapping as a Hotkey for Alfred.

Would be great if you could look into this :)

**Comment by MatthiasWinkelmann** [comment]
Works for me with the following configuration. Make sure it's f13, not F13.

```
{
  "profiles":  [
    {
      "name": "Default profile",
      "selected": true,
      "simple_modifications": {
        "caps_lock": "f13"
      }
    }
  ]
}
```

**Comment by toxik** [comment]
I tried with the lowercase letter.
The iTerm settings recognize it but the toggling doesn't happen

**Comment by jonaswisplinghoff** [comment]
Updating to the current version fixed it for me 😊 thx!

**Comment by toxik** [comment]
Updating fixed the issue for me also, closing and thank you!
