### ISSUE TITLE
Italian keyboard, unable to exchange Backlash(\) and Less-Than(<)

### ISSUE THREAD

**Issue by maurizio-emmex** [tekezo/Karabiner-Elements#290]
On an Italian keyboard I need to exchange '\' with '<', '|' with '>' and viceversa.
How can I do it ?

Thanks,
Maurizio

**Comment by plolrt** [comment]
+1

**Comment by plolrt** [comment]
Solved with:
![image](https://cloud.githubusercontent.com/assets/4377509/19467326/e7af4db0-9510-11e6-8eb5-823ec225d243.png)

**Comment by maurizio-emmex** [comment]
Thank you for the tip. In my Mac-mini with a Microsoft keyboard I am using:

`From key: grave_accent_and_tilde (```) - To key: non_us_backslash`

`From Key: non_us_backslash - To key: grave_accent_and_tilde (```)`
