### ISSUE TITLE
Usage/setup

### ISSUE THREAD

**Issue by rosskevin** [tekezo/Karabiner-Elements#291]
I have:

- downloaded and installed the latest from the readme
- created `~/.karabiner.d/configuration/karabiner.json` based on [`examples/qwerty_to_dvorak.json`](https://github.com/tekezo/Karabiner-Elements/blob/master/examples/qwerty_to_dvorak.json)
- restarted

Is it preferred that I add it to `Login Items`?

**Comment by talha131** [comment]
If you don't add, Karabiner will not automatically start when you restart your machine. 

Other than that, it's totally up to you.
