### ISSUE TITLE
When the expected release of the key combination remaping?

### ISSUE THREAD

**Issue by Leopoldishe** [tekezo/Karabiner-Elements#292]
May be how long?
Thanks!

**Comment by cameroooon** [comment]
+1. Putting off upgrading to Sierra until this is done... but if it's not likely to get any attention soon we might need to try and source another solution—definitely not the preferred option as Karabiner is fantastic!

**Comment by derburner23** [comment]
+1 Love to remap my caps lock key to ctrl+alt+cmd for several commands, but as I see it isn't possible at the moment?

**Comment by landona** [comment]
+1 from me, too...

**Comment by rafi** [comment]
+1 for chording āla [xcape](https://github.com/alols/xcape),
e.g. _caps_lock=>escape_ (when clicked alone) _caps_lock=>shift_ (when clicked with other key)

**Comment by akohlsmith** [comment]
same here... I can't remap backtick to escape unless I can ONLY map it when it's unmodified.

**Comment by roadom** [comment]
+1。I neek HOME/END so badly.

**Comment by macbem** [comment]
+1, I'm looking forward to this feature

**Comment by valerybugakov** [comment]
same problem here, I'm in the queue :)
