### ISSUE TITLE
Remapping other letters than a-z

### ISSUE THREAD

**Issue by Mkohm** [tekezo/Karabiner-Elements#293]
Hi,

Is it in some way possible to remap other letters than a-z, for example the norwegian letters æ, ø and å? Can i do it in some way on my own using the .json file, or does this have to be implemented at some later point?

**Comment by magiconair** [comment]
§ to backtick (`) is what I need on a Dutch keyboard with US layout.

**Comment by talha131** [comment]
@magiconair It is right there in the [usage](https://github.com/tekezo/Karabiner-Elements/tree/master/usage#swapping-sectionparagraph--key-on-non-us-keyboards).

**Comment by magiconair** [comment]
@talha131 How could I miss that? RTFM :) Thanks

**Comment by ChrisRast** [comment]
Hi @Mkohm did you find how to map `æ` for example ?
I'd like to map it `{`.
Thank you.

**Comment by Mkohm** [comment]
@ChrisRast with the newest version of karabiner elements this is possible. If you look at the examples for advanced use - I am sure you will find out.
