### ISSUE TITLE
Plan for missing functionalities : 1) Mapping with keeping original one 2) Hold Command+Q

### ISSUE THREAD

**Issue by jongheekang** [tekezo/Karabiner-Elements#296]
I am a fan of two functionalities mentioned in the subject:
1) I used to map Command R to Command + Space with keeping Command available. By doing this, I could change the input method as well as using Command itself too.
2) Hold Command+Q to quit application. It makes me make less mistakes of using command+Q.

Are you planning to implement these two or there any ways to do these in karabiner elements?

Thanks for your support.

**Comment by edwardjiang7** [comment]
Yes, I am interested in #2.
