### ISSUE TITLE
Ctrl+Shit+Power Doesn't Work 

### ISSUE THREAD

**Issue by mic773** [tekezo/Karabiner-Elements#297]
The combo in the title turns off the display of a MacBook Pro. It doesn't work with Karabiner Elements installed and running. This is true regardless if the user defined any key swaps.

Any ideas?

**Comment by adizero** [comment]
I have the same problem. With Karabiner-Elements running the Ctrl+Shift+Power does not work on iMac 5K Late 2015 (even without any mappings in Karabiner-Elements).

**Comment by mic773** [comment]
It's so annoying, hopefully there's a fix.

**Comment by PiotrCzapla** [comment]
It seems to be a duplicate of #124.

**Comment by PiotrCzapla** [comment]
Or actually duplicate of this: #89

**Comment by kubofonista** [comment]
Still not working after last updates...

**Comment by mic773** [comment]
It's finally fixed with 0.90.67!!!!!!

**Comment by kubofonista** [comment]
It's not. Still not working on external Apple Bluetooth keyboard

**Comment by mic773** [comment]
I only tested on my 2015 Retina MacBook Pro.

**Comment by snej** [comment]
I'd test this, but I don't want to have to clean off my keyboard afterwards ... 💩 ⌨️
