### ISSUE TITLE
Section § key definisiton missing 

### ISSUE THREAD

**Issue by borodiychuk** [tekezo/Karabiner-Elements#30]
Key definition is missing for the Section key: § (and ± with shift), code `0x0A` in `types.hpp` so it is not possible, for example, to swap it with `grave_accent_and_tilde`.

**Comment by tekezo** [comment]
You can find the raw key code value in `get_cg_key_map` in types.hpp.

```
      map[key_code(kHIDUsage_KeyboardNonUSBackslash)] = 0xa;
```

Please use `non_us_backslash`.

**Comment by talha131** [comment]
@borodiychuk I have the same issue. This configuration works for me.

```json
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "caps_lock": "left_control",
                "non_us_backslash": "grave_accent_and_tilde",
                "left_control" : "right_option"
            }
        }
    ]
}
```

Specifically, `"non_us_backslash": "grave_accent_and_tilde"`. Also see #7

**Comment by swapab** [comment]
Even I have a MacBook with DE keyboard layout where I would like to swap the § (non_us_backslash key) with ` (tilde key)

I have done following configuration in Karabiner, but it's not having any effect.

<img width="1011" alt="screenshot 2018-11-16 at 16 52 29" src="https://user-images.githubusercontent.com/1291980/48631984-0fa0f700-e9c0-11e8-9ab5-09d41a6f162a.png">

**Comment by talha131** [comment]
@swapab posting output of Karabiner-Elements event viewer would add more information.

I have the same configuration as yours and it has been working for 2 years now.

**Comment by andrewandante** [comment]
@swapab I've just come across this, and you're not going to believe me, but switching those around (i.e. FROM grave TO backslash) fixed it for me. I've no idea why, but it seemed to work. Hope that helps.

**Comment by yanikkoval** [comment]
@andrewandante software is weird :D

**Comment by Karkunow** [comment]
@andrewandante it works!!
