### ISSUE TITLE
Can you disable logout/force logout with Karabiner Elements on Sierra?

### ISSUE THREAD

**Issue by jwboardman** [tekezo/Karabiner-Elements#300]
The only two things I use Karabiner for are to wipe out the "logout" and "force logout" keyboard shortcuts, as I found myself accidentally hitting them while coding. Is there an equivalent in Elements?

<?xml version="1.0"?>
<root>
  <item>
    <name>logout</name>
    <identifier>logout</identifier>
    <autogen>**KeyToKey** KeyCode::Q, VK_SHIFT | VK_COMMAND | ModifierFlag::NONE, KeyCode::VK_NONE</autogen>
  </item>
  <item>
    <name>forcelogout</name>
    <identifier>forcelogout</identifier>
    <autogen>**KeyToKey** KeyCode::Q, VK_SHIFT | VK_COMMAND | VK_OPTION | ModifierFlag::NONE, KeyCode::VK_NONE</autogen>
  </item>
</root>

**Comment by jwboardman** [comment]
Ugh, it pretty much destroyed the xml...hope it still makes some sense

**Comment by tekezo** [comment]
You cannot do it yet.
#369

**Comment by rdunlapSP** [comment]
Is this still the case? I'm on Mojave running a Linux VM, and haven't found a way to disable Mac's logout key combo which is causing issues for my workflow.
