### ISSUE TITLE
Some Fn Keys do Not Work on Mac OS Sierra

### ISSUE THREAD

**Issue by vallieres** [tekezo/Karabiner-Elements#301]
I've got this configuration:

`"fn_function_keys" : {
        "f1" : "vk_consumer_brightness_down",
        "f2" : "vk_consumer_brightness_up",
        "f3" : "vk_mission_control",
        "f4" : "vk_launchpad",
        "f5" : "vk_consumer_illumination_down",
        "f6" : "vk_consumer_illumination_up",
        "f7" : "vk_consumer_previous",
        "f8" : "vk_consumer_play",
        "f9" : "vk_consumer_next",
        "f10" : "mute",
        "f11" : "volume_down",
        "f12" : "volume_up"
      },`

They all work except the brightness up and down. I'm using an external keyboard, a Leopold FC660M, weirdly even the illumination keys are triggered by the keyboard does not have any back light.

**Comment by bkonkle** [comment]
I'm having the same issue. Everything else works great, but `vk_consumer_brightness_up` and `vk_consumer_brightness_down` have no effect. Mac OS Sierra 10.12.1 (16B2555), Apple Wireless Bluetooth Keyboard, Karabiner Elements version 0.90.61.

Thanks for sharing this awesome tool!

**Comment by tomredman** [comment]
FYI, I have the same issue, only for F1 & F2 for brightness -- media controls work. However, **holding left Ctrl + F1 / F2 does work for brightness** on my external keyboard.

**Comment by tomredman** [comment]
Looks like this has been fixed on 0.90.72 with the following setting:

![screen shot 2017-01-03 at 10 30 59 am](https://cloud.githubusercontent.com/assets/4225378/21612560/c29d8b24-d19f-11e6-9507-0acaf0595e8c.png)

**Comment by vallieres** [comment]
Great!!! Confirmed to be working with a Leopold FC660M ! Thanks!

**Comment by itaen** [comment]
how to register original Fn key in Mac? I use Leopold FC750R,and press Fn key doesn't have any effect(right second one of space bar).

**Comment by carlsmith** [comment]
Some keyboards have `fn` keys that only alter which codes the keyboard emits. The OS has no way of knowing when the `fn` key is pressed. The Filco MINILA works that way. There's nothing Karabiner can do.

**Comment by alin89c** [comment]
My FN button as well doesn't work (At all! ...not even on a bluetooth keyboard). Does anyone have any suggestion?
