### ISSUE TITLE
[Feature Request] Specify which keyboard to have key mapping 

### ISSUE THREAD

**Issue by starsy** [tekezo/Karabiner-Elements#303]
Kabrabiner team, you have done a great work. Here is just a feature request which IMHO is very important. 

As I have an external PC keyboard connected to my MBP, some key mappings should just apply on the external one,  otherwise the keys will be very confusing when switching over between using the internal one and external one.

Thanks!

**Comment by rafi** [comment]
+1 for preset profiles

**Comment by perlun** [comment]
Already noted in:

* #31 (talks about profiles)
* #67 (open, explains how you can do a manual workaround for now)
* #138 (open)
* #162 (closed)

What I personally _really_ liked in Karabiner was that it let you configure different bindings _per keyboard_, i.e. you wouldn't even have to use different profiles (you could just conditionalize per keyboard).

It's really sad that Apple broke Karabiner in the Sierra update. 😢

**Comment by tekezo** [comment]
Karabiner-Elements v0.90.58 has Devices tab in Preferences which allows you to choose enabled devices.

**Comment by lhanson** [comment]
This works great for me, thanks!!

**Comment by perlun** [comment]
@tekezo wrote:

> Karabiner-Elements v0.90.58 has Devices tab in Preferences which allows you to choose enabled devices.

Thanks a lot for that! But: the original requirement (as written in the initial text by @starsy) hasn't really been fulfilled:

> As I have an external PC keyboard connected to my MBP, some key mappings should just apply on the external one, otherwise the keys will be very confusing when switching over between using the internal one and external one

This is my exact requirement. I use a PC-style keyboard, where Cmd and Alt have different placement than on the builtin MBP keyboard, so I used to have a KeyRemac4MacBook setting that used different profiles for these different keyboards.

That was an incredibly useful feature. Sorry to rain on your parade, and I definitely appreciate all the hard work you (and others) are putting into this. But, this specific issue (#303) would preferably be reopened and we can then close it when the full support for keyboard-specific bindings (for individual bindings) have been implemented.

**Comment by starsy** [comment]
Per, cannot agree more with you. This is exactly what can make a difference. If Karabiner can support which key mapping to be enabled on which keyboard. 

E.g. on my internal keyboard, I always map "Right Option" to be "Forward Delete", but this mapping should not be enabled on my external keyboard as there is already a Delete key there. Meanwhile as external PC keyboard doesn't have a Fn key, so I need to map either "Right Control" or "Application" key to be Fn, this setting should not be enabled on my internal keyboard. 

So in the "Simple Modifications" Tab, if there adds a drop-down list to select which device to enable which mapping, it would be fantastic! 

Again, thanks for Karabiner team's great effort. This is just my 2%, hope it can make Karabiner better.

**Comment by perlun** [comment]
@starsy - I created a new issue for it, #399. Let's continue the discussion there.

**Comment by starsy** [comment]
@perlun @sitaktif Finally I have to DIY this for myself after a long time waiting. Made some enhancements to KBE to remove the pain of switching profiles for 2+ keyboards by supporting per-device configuration. Please take a look at [https://github.com/starsy/Karabiner-Elements](https://github.com/starsy/Karabiner-Elements) if you are interested in. The release/download link is here: [https://github.com/starsy/Karabiner-Elements/releases/tag/v1.0_merged](https://github.com/starsy/Karabiner-Elements/releases/tag/v1.0_merged) . Pull request is here: [https://github.com/tekezo/Karabiner-Elements/pull/752](https://github.com/tekezo/Karabiner-Elements/pull/752). It works pretty stably on my MBPR, I think it worths a try. Hope it can solve your problems too. Please don't hesitate to let me know if any issues or questions. 

![image](https://user-images.githubusercontent.com/1459979/26891802-dd782b52-4be8-11e7-8380-5aa0703b6fa9.png)
