### ISSUE TITLE
Japanese layout broken?

### ISSUE THREAD

**Issue by bs90** [tekezo/Karabiner-Elements#305]
- I am using Japanese layout FILCO keyboard
- After running Karabier in Sierra, my keyboard turns to English layout and I don't know how to fix :|

**Comment by baban** [comment]
You test v0.90.46 ?
I guess that it work correct.
https://github.com/tekezo/Karabiner-Elements/issues/278

**Comment by y-marui** [comment]
I want to switch yen key with backslash using karabiner-element.
But v0.90.46 doesn't recognize backslash as backslash.
And also the newest version has some problems with keyboard layout.
Is there any solution for it?

**Comment by bs90** [comment]
@baban Thank you. Worked like a charm :)
Had to edit some options manually in karabiner.json but everything OK 👍
