### ISSUE TITLE
Key codes for parenthesis and curly brackets

### ISSUE THREAD

**Issue by fent** [tekezo/Karabiner-Elements#308]
Hello,

I'd like to map other keys to these since these are too far for my short fingers, but I don't see the key codes for them in `types.hpp`. :(

**Comment by talha131** [comment]
Use `open_bracket` for `[` and `{` key.
Use `close_bracket` for `]` and `}` key.

Use `9` for `9` and `(` key.
Use `0` for `0` and `)` key.

**Comment by tekezo** [comment]
You can confirm the key name in EventViewer.
https://github.com/tekezo/Karabiner-Elements/blob/master/usage/README.md#how-to-configure-karabiner-elements
