### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by tiagocardosoweb** [tekezo/Karabiner-Elements#31]
Please, when possible add profiles, If I configure my gaming keyboard all the time I want to use macbook default keyboard I need to quit the application.

Greetings

**Comment by awinecki** [comment]
@tiagocardosoweb have a look at #67.

If you're using Alfred, you can use [Karabiner Elements Profile Switcher](https://github.com/awinecki/karabiner-elements-profile-switcher).

**Comment by sitaktif** [comment]
It's nice to have workarounds but I believe it would add a lot of value to Karabiner Elements to integrate this issue in a standalone way. Not everybody uses Alfred or is keen on setting up some crazy `.plist` agent config.

To give a rationale for that feature, here is a rather generic use-case:
- User has a laptop and an external keyboard. The keyboard is used at work, the buillt-in keyboard is used at home.
- On *all* his keyboards, user wants to use a feature that only Karabiner-Elements provides (say: Caps Lock as "escape" when short-pressed, and as Control when long-pressed - this one will probably get popular with the new Touchbar MBPs). 
- On his *external keyboard only*, user needs the option and command keys to be swapped.

This use-case is not currently covered by Karabiner Elements.

Enabling/disabling keyboards per-profile seems like an elegant and intuitive way to solve the problem of assigning different shortcuts to different keyboards.

Related issues: #31 #138 #162 #303 #488
Workarounds: #67

**Comment by awinecki** [comment]
I think it's no longer needed to use any workarounds, with the latest version of Karabiner Elements (I have **0.90.86**) you can switch profiles using tray icon actions:

<img width="215" alt="screen shot 2017-02-09 at 12 35 04" src="https://cloud.githubusercontent.com/assets/656694/22781793/7c6c0602-eec4-11e6-9593-523733f5e015.png">

Yay! 🍾 ✨

**Comment by vbauerster** [comment]
Profile switching does not work in v0.90.86. I mean when different profile is selected, it is not activated. I have to restart (quit and start over again) Karabiner Elements in order to activate the profile. I use external keyboard with different profile, and it is very inconvenient to restart KE every time I switch the profile. My [karabiner.json](https://github.com/vbauerster/dotfiles/blob/master/config/karabiner/karabiner.json)

**Comment by vbauerster** [comment]
I have opened new https://github.com/tekezo/Karabiner-Elements/issues/634

**Comment by zjunothing** [comment]
Hi  @awinecki , i know there is a tray icon and i can switch profiles using mouse. 
But i still want a way that can change my profile via keyboard. Do you have any idea? 
Thanks in advance.

**Comment by zjunothing** [comment]
I have got a  nice workaround i think.
write a script (eg. named debug-profile.sh) like 
`gsed -i '/"name": "Debug"/!b;n;c"selected": true,' ~/.config/karabiner/karabiner.json
  gsed -i '/"name": "Default"/!b;n;c"selected": false,' ~/.config/karabiner/karabiner.json
`
and a script (eg. named default-profile.sh) like:
`gsed -i '/"name": "Debug"/!b;n;c"selected": false,' ~/.config/karabiner/karabiner.json
  gsed -i '/"name": "Default"/!b;n;c"selected": true,' ~/.config/karabiner/karabiner.json
`

and if you want swith ,just run the two profile, you can surely add then in your .bashrc and make alias.

**Comment by awinecki** [comment]
@zjunothing if you're an [Alfred app](https://www.alfredapp.com/) user, you can try using my workflow: https://github.com/awinecki/karabiner-elements-profile-switcher. I haven't updated since it's possible via tray menu, but it seems to still work – just tried it :). Other than that, I think your workaround with `gsed` looks perfect, with some nice aliases that could be handy.

**Comment by starsy** [comment]
@awinecki don't you find manual switch-over awkward? i made some enhancement to original KBE to support per-device key mapping, please try this fork: https://github.com/starsy/Karabiner-Elements, usable built can be found in "release section". 

@sitaktif believe this can solve your problem totally.

Screenshot:
!(screenshot)[https://github.com/starsy/Karabiner-Elements/raw/master/Screen%20Shot.png]

**Comment by awinecki** [comment]
This looks amazing, @starsy. Thanks for doing this, I will definitely try it out. Would love to see this merged into primary KBE repo.

**Comment by AustinCDavis** [comment]
I don’t know if any of you in this thread still needed any help, but I just started using karabiner elements and wanted the same thing and just finished my functional code. I’m adding my guide and code to the issue pages that I looked at to help me solve mine.

I made it so you can cycle through profiles  by clicking the 1 button on my mouse keypad and it will pop up a small notification in the top corner of your active display telling you which profile you activated. I made a step-by-step guide with the code I used and included some notes to help. I also added notes for altering the code if you don’t have a mouse with programmable buttons and just want to use a the keyboard.

Here is my GitHub issue page:
[Issue #3878](https://github.com/pqrs-org/Karabiner-Elements/issues/3878)
