### ISSUE TITLE
Command-clicking in macOS Sierra broken

### ISSUE THREAD

**Issue by mb21** [tekezo/Karabiner-Elements#310]
I've the following in`~/.karabiner.d/configuration/karabiner.json`:

    {
      "profiles" : [
        {
          "name" : "Default profile",
          "selected" : true,
          "fn_function_keys" : {
            "f12" : "volume_up",
            "f9" : "vk_consumer_next",
            "f5" : "vk_consumer_illumination_down",
            "f10" : "mute",
            "f1" : "vk_consumer_brightness_down",
            "f6" : "vk_consumer_illumination_up",
            "f2" : "vk_consumer_brightness_up",
            "f7" : "vk_consumer_previous",
            "f11" : "volume_down",
            "f3" : "vk_mission_control",
            "f8" : "vk_consumer_play",
            "f4" : "vk_launchpad"
          },
          "simple_modifications" : {
            "caps_lock" : "escape"
          }
        }
      ]
    }

Command-clicking is intermittently broken in a few places (e.g. in Chrome command-clicking to open links in new tabs or the Chrome back button, or in the Finder clicking the icon at the top of the window, to left of the folder name). Quitting Karabiner Elements makes command-clicking work again...

**Comment by vallieres** [comment]
+1 for Option+Click and Shift+Click (selecting multiple files in finder)

**Comment by mb21** [comment]
I'm pretty sure this was fixed by upgrading Karabiner-Elements to 0.90.50...

**Comment by vallieres** [comment]
Yes, it seem to be fixing this issue. Perhaps make the Check for Update more aggressive, I installed it last week and I was already 3-4 versions behind :)

**Comment by shmup** [comment]
Googling lead me here, which was nice and helpful because I didn't even realize it was Karabiner doing this, but it makes sense. I wanted to add in (for googling sake) that this also broke shift+click to create/extend a text selection (click cursor somewhere then shift-click in another location).

The update definitely addressed this, though. Cheers.
