### ISSUE TITLE
Chinese keyboard layout broken?

### ISSUE THREAD

**Issue by sunapi386** [tekezo/Karabiner-Elements#313]
Since upgrading to Sierra, input source switching has been broken. Not sure what the problem is. Seems like some other languages work, but not Chinese. I attached a 10 second clip. Key presses show up on the Keyboard Viewer but is not handled otherwise.

https://youtu.be/dkkM9Ion20Q

**Comment by tekezo** [comment]
Is it Karabiner-Elements issue?
