### ISSUE TITLE
Karabiner breaks non-Apple keyboard

### ISSUE THREAD

**Issue by trung-huynh** [tekezo/Karabiner-Elements#314]
Hi there,

I have both keyboards, one mechanic non-Apple keyboard and another one Apple keyboard.

For Apple keyboard, I remapping caps-lock to escape and thing is fine.

For non-Apple keyboard, I remapping caps-lock to escape and swap option-command key in setup modifier key from Keyboard setting but it doesn't work.

If I quit Karabiner, setup modifier key from Keyboard work, otherwise, it doesn't work. it means modifier keyboard from Apple and Karabiner can not work together. The way it works totally difference with Seil. 

Is it a feature or an issue? I just updated to macOS Sierra and Seil doesn't work on Sierra, that's  reason why I came to Karabiner

**Comment by trung-huynh** [comment]
As far as I can tell, Karabiner should only touch to modifier key with "No Action" value, currently it changed every modifier keys even the key with "real" value

**Comment by FuzzOli87** [comment]
I'm seeing a similar effect. With an external USB keyboard the caps_lock to escape does not work at all on the USB keyboard.

**Comment by eidge** [comment]
I'm seeing an issue where clicking '<' on my usb keyboard produces '§' instead.

I've also noticed that the apple keyboard configuration cannot properly figure out which keyboard I own, since it thinks I'm clicking the native keyboard if I have Karabiner turned on.

**Comment by poberherr** [comment]
Same here - my suggestion:
* have different Karabiner configs for different keyboards
** no config for a specific keyboard

If you look at the MacOS modifier options for function keys - you can select it by individual keyboard. For me I remapped an external keyboard to get the same "haptic" as on the onboard Apple keyboard, of course then I always have to activate Karabiner or deactivate.
Choosing between differnt Keyboards and deciding if All should use the default config - OR - just specific keyboards use a config - OR - each keyboard get's its own config.

**Comment by kbaley** [comment]
I'm having the same issue. I've swapped command and option for the external keyboard only but it doesn't work. When I quit Karabiner Elements, it does. And I only want them swapped when an external keyboard is attached.

**Comment by walt-r** [comment]
Perhaps this is relevant?
https://github.com/tekezo/Karabiner-Elements/issues/9#issuecomment-248498163
In the new Karabiner-Elements, you can no longer user OS Preferences to remap the keyboard.  Instead, do ALL remapping in Karabiner-Elements.

**Comment by trung-huynh** [comment]
From my perspective it shouldn't ...

For the time being, I created my own profile for internal keyboard (Mac), external keyboard (which has Windows layout) and it can quickly switch by CLI, but I hope it would be there for temporarily and author will change his mind ;) .

**Comment by tekezo** [comment]
You can ignore specific devices in Devices tab since Karabiner-Elements 0.90.57.

**Comment by poberherr** [comment]
awesome - thanks !

**Comment by konstantinzolotarev** [comment]
But what should I use to be able to use non apple keyboard. 
Right now I'm on DasKeyboard and iMac (don't have apple keyboard at all)
And after installing karabiner elements all by keys changes to default macs keyboard. 
Default OSX keys remap also ignoring.

**Comment by poberherr** [comment]
If Karabiner Elements is started, the OSX key remaps are ignored.
You have to do the remapping then in Karabiner completely.

IMHO OS Sierra brought out an update which supports already a lot of stuff - see if you can remap it there.

**Comment by konstantinzolotarev** [comment]
@poberherr OMG really. they added Esc to modifiers keys and I'm able to modify caps lock to esc in OS. 
I spent more than a month waiting for Karabiner for this. 
Thank you very much ! You are my hero

**Comment by poberherr** [comment]
Was also surprised and just found out afterwards. :)
