### ISSUE TITLE
Karabiner-Elements confilict SteerMouse.

### ISSUE THREAD

**Issue by kokichiru** [tekezo/Karabiner-Elements#316]
Karabiner-Elements confilict SteerMouse.
I use Logicool G700s.

**Comment by kokichiru** [comment]
Error message of SteerMouse
"VID:0x46D, PID:0xC531, MID:0x0 Transport:USB"

**Comment by khmyznikov** [comment]
Logitech M535 issue:
[info] [grabber] Bluetooth Mouse M336/M337/M535 is grabbed
And then mouse doesn't work

**Comment by tekezo** [comment]
I added Devices tab in Karabiner-Elements Preferences which allows you to ignore specific devices.
Please upgrade to the latest version and ignore SteerMouse devices in Devices tab.

**Comment by khmyznikov** [comment]
@tekezo Awesome! Mouse issue is gone!

**Comment by kokichiru** [comment]
the issue is fixed.
thank you for your upgrade.

**Comment by jspiro** [comment]
I'm only seeing my keyboard in Devices, not my Evoluent mouse nor any SteerMouse. I'm getting: You need to specify this mouse to be ignored in Devices tab of Karabiner-Elements Preferences.

Halp?
