### ISSUE TITLE
Elements Install Disables Some Logitech MX Master Mouse Functionality

### ISSUE THREAD

**Issue by gcortes** [tekezo/Karabiner-Elements#317]
I installed the latest version of Karabiner Elements version 0.90.52 on my MacOS Sierra machine. The install went fine. When I tried to use my Logitech mouse, the scroll and at least some of the extra keys stopped working. When I uninstall Elements, the mouse keys worked again. I'm using the Logitech software that came with the mouse to control it.

**Comment by gamesbrainiac** [comment]
Same issue here. But right now the interface looks a lot better though.

**Comment by rnbarg** [comment]
Same problem. I have posted about this as well. 
![2016-10-17_09-17-38ddddddddddd](https://cloud.githubusercontent.com/assets/10092862/19498309/03121504-9545-11e6-8f01-77bb1328e7b6.jpg)

**Comment by gamesbrainiac** [comment]
Managed to fix the problem. Here is what you have to do:

1. Preferences > Security & Privacy
2. Add two applications to the accessibility programs:
    - Karabiner-Elements.app
    - Logitech Options.app

![Final Thingy](http://i.imgur.com/lcJKMNz.png)

**Comment by gamesbrainiac** [comment]
Just as an update. For some reason, the functionality like scroll wheel turns on and off sometimes, and I don't know why. But, disconnecting and reconnecting solves the issue.

**Comment by rnbarg** [comment]
@gamesbrainiac - I made the changes below.  I also installed the latest builds last night. Nothing has changed.  

Good:  BT Mouse is no longer is disabled when Elements is loaded. This makes testing a lot easier 
Bad: Back and forward buttons in browsers still do not work. In Chrome, there is an additional anomaly. Clicking the back button over a hover hand opens the linked content in  a new tab.

This affects both the MX Master and VX Revolution.

Preferences > Security & Privacy
Add two applications to the accessibility programs:
Karabiner-Elements.app
Logitech Options.app

**Comment by rnbarg** [comment]
I just updated to the latest version of LT options and now the Mouse is AGAIN  disabled when Elements is loaded

**Comment by gamesbrainiac** [comment]
@rnbarg I had this issue too, just turn off and turn on the mouse, and the issue is usually resolved.

**Comment by gamesbrainiac** [comment]
So this is weird, it turns out that the reasons that some of the action keys don't work for me on my logitech MX Master is because logitech options doesn't work properly. So, I just open system preferences, lock and unlock the ability to add or remove applications from accessibility, and then the mouse keys work again.

**Comment by RianGray** [comment]
Can't use Logitech MX Master on bluetooth at all on v0.90.55. Getting connect_ is null @ void. Turning it off and on again doesn't work either. #39

**Comment by RianGray** [comment]
Just tested again, managed to get the mouse to work after a reboot. Like @gamesbrainiac said, resetting it on accessibility pane also solves Logitech Options not grabbing the mouse.

**Comment by gamesbrainiac** [comment]
@RianGray I think it only stops working when you log out. I have not had problems after setting it up correctly with accessibility.

**Comment by rnbarg** [comment]
I just installed the latest update - immediately locks LT Master mouse until BT is cycled and mouse forward/back buttons don't work on all mice CT and USB. Tried all of the fixes related to "accessibility " such as "I just open system preferences, lock and unlock the ability to add or remove applications from accessibility, and then the mouse keys work again" and they do not work.

**Comment by gamesbrainiac** [comment]
@RianGray Hey man, after the latest update, I seem to be having the same problem you are having.

**Comment by gamesbrainiac** [comment]
@tekezo Hey man, is this an issue with application rights? Because if things work after we unlock the accessibility applications, then I guess it makes sense that this is not an issue with karabiner as an application but perhaps its not getting the rights it needs or something.

**Comment by RianGray** [comment]
I'm assuming this is a karabiner issue. So far most of the threads related to Bluetooth mouse mentioned it would work again with karabiner off.

**Comment by gamesbrainiac** [comment]
Well, I'll just stick to re-enabling it all the time, I guess.

**Comment by rnbarg** [comment]
IMPORTANT!!   Using a 2nd mouse I turned off BT, configured my Logitech MX Master as a USB mouse using unifying receiver in Logitech Options. I tried and then purchased "USB Overdrive 3.3" is ready for Sierra for $20 USD at http://www.usboverdrive.com/USBOverdrive/News.html   Now KElements runs fine and the mouse works great.

**Comment by gamesbrainiac** [comment]
@rnbarg I've had the same luck without USB Overdrive 3.3. I just tried it with the USB and it worked receiver and it worked.

**Comment by gamesbrainiac** [comment]
Also, works when I restart the computer without a hitch.

**Comment by tekezo** [comment]
Duplicated #84
