### ISSUE TITLE
0.90.52 on macOS 10.12 sierra - key swap not working in terminal

### ISSUE THREAD

**Issue by exponentus** [tekezo/Karabiner-Elements#318]
I've activated  a left_ctrl < > left_command, which is working consistently across all applications except the command line terminal.
Once I place the focus on the CLI, the aforementioned modifiers return to their default functions.

On OS X 10.11 there was no such glitch.

**Comment by cormacrelf** [comment]
Repro for iTerm 3.0.12, but not for the built-in Terminal; Sierra 12.1.

**Comment by tekezo** [comment]
Does this issue  still happen in the latest version?
