### ISSUE TITLE
A few essential (for me) Karabiner/Seil features

### ISSUE THREAD

**Issue by steakknife** [tekezo/Karabiner-Elements#32]
Not sure how far is development, but the primary Karabiner features I use(d) are:
- Eject to sleep display (⏏ -> Control-Shift-⏏)
- Quarter-step volume always (F11/12 -> Option-Shift-F11/12)
- Quarter-step display brightness always (F1/2 -> Option-Shift-F1/2)
- Quarter-step keyboard backlight brightness always (F5/6 -> Option-Shift-F5/6)

**Comment by tekezo** [comment]
Not yet #369
