### ISSUE TITLE
Modifier In same USB packet

### ISSUE THREAD

**Issue by Joshuaweiss** [tekezo/Karabiner-Elements#321]
The built in macOS drivers seem to resolve modifier keys first when multiple keypresses are sent in the same USB packet. Karabiner does not resolve keypresses the same way breaking onboard macros sent this way.

A keyboard macro which sends ctrl-c to karabiner resolves as:
`"c" Down, "CTRL" Down, "c" Up, "CTRL" Up`

Without karabiner the macro works so the OS must be producing either:
`"CTRL" Down, "c" Down, "c" Up, "CTRL" Up`
OR
`"CTRL" Down, "c" Down, "CTRL" Up, "c" Up`

**Comment by tekezo** [comment]
How do I reproduce this issue?

**Comment by tekezo** [comment]
#380
