### ISSUE TITLE
Wrong keyboard layout used (english, instead of german)

### ISSUE THREAD

**Issue by mojo2012** [tekezo/Karabiner-Elements#323]
I'm using cmd-^ to show/hide item2. Since I installed karabiner-elements this is not working anymore.
I have a german keyboard layout (^is left to the 1 key) and when using KE it is left to the Y key. It is swapped with the < key.
It seems KE is forcing an english keyboard. As soon as I disable KE, it works again.

**Comment by paulgessinger** [comment]
Have the same problem. There's is lots of issues with similar descriptions on here, I think the valid one is #229

**Comment by tekezo** [comment]
Please upgrade Karabiner-Elements to the latest version and then set keyboard type in Devices tab.
https://github.com/tekezo/Karabiner-Elements/tree/master/usage#set-keyboard-type
