### ISSUE TITLE
Please provide more identifiable key names

### ISSUE THREAD

**Issue by entonio** [tekezo/Karabiner-Elements#326]
I understand you use the names provided by Apple's API, but they're awful for anyone outside the US. It's just too much confusion because the names have no bearing to what's printed on the key.

If you don't mind, I suggest using a reference to nearby 'universal' keys. It may not be perfect, but I think it's an improvement. Here are the values I've been able to determine (my excuses for any errors):

```
Position    Current_Name
1 - 1   grave_accent_and_tilde
0 + 1   ?
0 + 2   ?
P + 1   open_bracket
P + 2   close_bracket
L + 1   ?
L + 2   quote
L + 3   non_us_sound
Z - 1   non_us_backslash
M + 1   ?
M + 2   ?
M + 3   slash
```

I know some keyboards have no `L + 3`, and some have a `P + 3`, but maybe those can be addressed by using synonyms?
I also know `+` and `-` are not good for use in code identifiers, but maybe `pl[us]` and `mi[nus]` can be substituted?

**Comment by edenworky** [comment]
Also, `non_us_backslash` refers to the `§` key, as far as I can tell. Which is not clear.

**Comment by entonio** [comment]
I believe this would be q very welcome improvement, but it hasn’t generated feedback. Please look into it and say something. 

No dia 04/03/2018, às 14:56, stale[bot] <notifications@github.com> escreveu:

**Comment by entonio** [comment]
Are there any plans on this? I don't think my idea is so far fetched that it doesn't deserve any reply.
