### ISSUE TITLE
Shortcut to switch between function keys and Apple keys

### ISSUE THREAD

**Issue by Kiminaka** [tekezo/Karabiner-Elements#328]
Hi, 

I am trying to find a way to switch between function keys and Apple keys. I used to use Paula to do this but it seems like it's no longer available. I had the shortcut (control + enter) to switch the keys. 
Would it be possible to do the above using Karabiner Elements? 

I use MacOS Sierra 10.12. 

Thanks!

**Comment by chrisfsmith** [comment]
I too was a Paula user and am very sad it is no longer available. I found [FNable](https://itunes.apple.com/us/app/fnable/id469617097?mt=12). Just like Paula, it automatically switches between function and Apple behavior based on the foreground app and there is a customizable hot key. 

Unfortunately FNable does not work with Karabiner-Elements. If I have both running at the same time I always get Apple behavior.

**Comment by Kiminaka** [comment]
Thanks Chris!

I'm very sad too that Paula no longer works.. But I'll try FNable!
