### ISSUE TITLE
Allow swapping keys with modifiers, e.g. hypen (dash, minus sign) to underscore and vice-versa

### ISSUE THREAD

**Issue by pckujawa** [tekezo/Karabiner-Elements#329]
In Karabiner, I remapped hyphen to underscore (shift + hyphen) and vice-versa. I don't see a way to do that in Elements. Is there? Will there be?
Thanks!
Pat

**Comment by themadsens** [comment]
METOO: 
I have Seil map caps-lock to PC-APP (or F10 or ..) and pt. uses Karabiner to map this to CTRL-B for use with tmux. IOW. Will it be possible to specify modifiers on the from/to items ?
Thanks in advance /Flemming

**Comment by talha131** [comment]
Wait for #16 to be implemented.

**Comment by phoffer** [comment]
I've been able to get this working natively by following [these instructions](http://xahlee.info/kbd/osx_keybinding.html).

Basically, create a file `~/Library/KeyBindings/DefaultKeyBinding.dict` with the following content:
```
{
"_" = ("insertText:", "-");
"-" = ("insertText:", "_");
}
```
I would expect this work for most keys.

**Comment by kemmason** [comment]
So I had the same issue, found the karabiner-elements complex_modifications github project [here](https://github.com/pqrs-org/KE-complex_modifications).  I was able to create a file that exchanges hyphen and underscore.

download this file:
https://github.com/kemmason/KE-complex_modifications/blob/master/docs/json/exchange_hyphen_and_underscore.json
put it in this directory:
`~/.config/karabiner/assets/complex_modifications/
`
then go to "Complex Modifications" in karabiner-elements preferences, and click "Add Rule" -- then "Enable" for the "Exchange hyphen and underscore" line.

I'm submitting a pull request so hopefully it'll be one of the standard downloads you can find here: https://pqrs.org/osx/karabiner/complex_modifications/

**Comment by lukelbd** [comment]
@kemmason Your script breaks when "Sticky Keys" are enabled. In this case, "shift-hyphen" will enter an underscore on the first keystroke, and only *consecutively* enter a hyphen. Basically, **** gets weird -- try it out. Is there any way to fix this?

**Comment by patkujawa-wf** [comment]
I just upgraded to Mojave and the built-in method that used to work seems to not work any more. Just me?

![image](https://user-images.githubusercontent.com/6391742/50123004-45820700-021c-11e9-83ce-ed4384b42f76.png)
