### ISSUE TITLE
Force Input Source 

### ISSUE THREAD

**Issue by noma4i** [tekezo/Karabiner-Elements#33]
How to use `VK_CHANGE_INPUTSOURCE_ENGLISH` from old Karabiner?

**Comment by noma4i** [comment]
Im trying to implement https://github.com/tekezo/Karabiner/blob/65e286b42e2c36d15683c828a8574e873ad4bfe6/src/core/server/Resources/include/checkbox/languages/russian.xml

**Comment by leshik** [comment]
I think overlaid modifiers aren't implemented yet. ;)

**Comment by noma4i** [comment]
My config to restore Force input source is:

- BetterTouchTool with triggers for `shift down -> shift up` sequence to prevent any `shift + letter` misuse.  -> remap to `{"⌘", "⌥", "⌃"}` + `[` and `]` accordingly.

- Hammerspoon to force keyboard input source:
```

**Comment by anaderi** [comment]
not sure why would I need to `shift down -> shift up sequence to prevent any shift + letter misuse`
otherwise works perfectly.
