### ISSUE TITLE
Key Request - §± 

### ISSUE THREAD

**Issue by eek** [tekezo/Karabiner-Elements#330]
Some Macbook keyboard have in the exact same place as ~ and ` the §± key. It would be great if I can modify it from the Karabiner Elements, but I can't really find it... :(

![keyboard](https://cloud.githubusercontent.com/assets/2953026/19566565/766a9526-96f3-11e6-8976-d5aef7292f94.png)

**Comment by talha131** [comment]
Read the docs https://github.com/tekezo/Karabiner-Elements/tree/master/usage#swapping-sectionparagraph--key-on-non-us-keyboards

**Comment by eek** [comment]
Thank you thank you! :D 

It's funny because I've entered the Usage file but when I've seen the UI print-screen usages I have instantly thought that I can't find my answer there. - Maybe moving that to Advanced Usage in a separate file would be way better? 😄 

Also, searched for the `§` character but Github didn't present any results :(

Thanks again!

**Comment by nuc** [comment]
Since the docs have moved and users might arrive here from Google, the key name for the `§` in karabiner is `non_us_backslash`.
