### ISSUE TITLE
how to get vi-mode

### ISSUE THREAD

**Issue by shen-liang** [tekezo/Karabiner-Elements#332]
When I used Karabiner-Elements in macOS Sierra ,  I want to control the arrow keys like vi-mode(Control_L+hjkl to Left/Down/Up/Right) , but I cant't find the item Control_L+h,Control_L+j....
please help~

**Comment by yinchuandong** [comment]
I am also looking forward to this fantastic function. Keyboard Maestro can be a temporal alternative, but the user experience is really terrible.

**Comment by tekezo** [comment]
#369
