### ISSUE TITLE
For the Schemers and LISPers: open and close bracket

### ISSUE THREAD

**Issue by samvv** [tekezo/Karabiner-Elements#333]
Hi,

Using Karabiner, I was able to map a short press of my left and right shift key to `(` and `)`, respectively. Can somebody explain to me how to do this with Karabiner-Elements, if it is possible? I have looked but I couldn't find anything; the only thing I found is mapping to `[` and `]`, but in my case that is not an option.

Thanks,
Sam

**Comment by talha131** [comment]
> map a short press of my left and right shift key to ( and )

I think you are looking for #8
