### ISSUE TITLE
Default keyboard layout is ignored and US layout is forced

### ISSUE THREAD

**Issue by vmi** [tekezo/Karabiner-Elements#335]
Hi,

I use Japanese layout keyboard.
The default keyboard layout is ignored and US layout is forced when installing Karabiner-Elements.

日本語キーボードを使用しているのですが、Karabiner-Elementsを入れると、デフォルトのキーボードレイアウトが無視され、USレイアウトになります。

**Comment by edenworky** [comment]
I think this is related: I have an international Apple keyboard and by default the backtick `` ` `` and section `§` key are swapped. In the US keyboard, `` ` `` is where `§` is and `§` doesn't have a key.

**Comment by panminxian** [comment]
この問題、私のmacbookに存在しました。

**Comment by tekezo** [comment]
Please upgrade Karabiner-Elements to the latest version and then set keyboard type in Devices tab.
https://github.com/tekezo/Karabiner-Elements/tree/master/usage#set-keyboard-type
