### ISSUE TITLE
Keep caps_lock and return_or_enter work if only one key pressed

### ISSUE THREAD

**Issue by chophi** [tekezo/Karabiner-Elements#336]
I use emacs and enjoyed remapping caps_lock and return_or_enter to ctrl when on EI Capitan and have Karabiner there, where I can keep [return] functional still as return (after remapping to ctrl) if only one key pressed, here's the function I want:

1. Use the UI configuration remap both [caps lock] and [return] to [ctrl]
2. After remapping:
    + if only [caps lock] or [return] pressed, function as original key.
    + if [caps lock] or [return] used as modifier and pressed with other keys, function as  [ctrl]

I have a workaround patch to make it work with current *Simple Modifications*:
1. cherry-pick this patch, compile and install https://gist.github.com/chophi/74fe0fbb32b829c618040ee00ae0a45f
2. remap both [caps lock] and [return] to [ctrl] in *Simple Modifications*

I hope this can help someone who has the same need.
If there will be a configure I can choose like we have in Karabiner, it would be wonderful.

**Comment by dekz** [comment]
Also heavily interested in having a Modifier/Single alternatives for the same key.

My particular use case:

* When used as a meta modifier (in combination with another key), act as ctrl.
* When used as a single keypress (no additional keypresses), act as escape.

**Comment by erwald** [comment]
I suppose https://github.com/tekezo/Karabiner-Elements/issues/228 is another use case of this. That is:

* When Space is used in combination with another key, act as Shift_L.
* When Space is used alone, act as Space.

**Comment by chophi** [comment]
Seems #247 fix this

**Comment by tger** [comment]
Very nice, thank you.

**Comment by bassu** [comment]
Well, I just tested @wwwjfy 's release and it seems to work with newly introduced `standalone_modifyers`. So I moved the `Ctrl` modifiers to the home row on default keyboard. See pull #247 for the config.
