### ISSUE TITLE
Does not work with latest update (10.12.1)

### ISSUE THREAD

**Issue by przemyslawnycz** [tekezo/Karabiner-Elements#338]
Hi,
The application does not work with the latest system update (10.12.1).

**Comment by gamesbrainiac** [comment]
Thanks for the heads up.

**Comment by atomkirk** [comment]
I updated to 10.12.1 and found the same thing. I cloned down repo and built it myself and when I re-installed what I built, it worked. Here's my build if you just want to download and install: http://d.pr/f/1iKZY/2FQxNwzi

**Comment by creatorKoo** [comment]
me, too! please fix this bug!

**Comment by chaucy** [comment]
reinstall it, it does work

**Comment by ptrkcsk** [comment]
Same problem here. A simple uninstall + reinstall worked for me.

**Comment by walt-r** [comment]
Works fine for me. Didn't even need to reinstall after the update to 10.12.1

**Comment by irliao** [comment]
Didn't need to reinstall, just needed to reopen Karabiner-Elements and remove it from Accessibility

**Comment by mix1009** [comment]
I upgraded to macOS 10.12.1(16B2657) and had similar problem.

I was able to fix the problem installing 0.90.55:
https://pqrs.org/osx/karabiner/files/Karabiner-Elements-0.90.55.dmg

Updates 0.90.56 - 0.90.60 didn't work for me.
I don't see any simple modifications or function key assignments and can't select it from UI. The settings from karabiner.json didn't seem to load properly.

**Comment by austrasien** [comment]
Hi, I'm encountering the same problem with last update (0.90.67) : Karabiner-Elements was not working at all.

Uninstalling and coming back to 0.90.50 solved the problem. Could you please fix it in next update ?

**_Device :_**
MacBook Air (13", early 2015)
CPU 1,6 GHz Intel Core i5
RAM 8 Go 1600 MHz DDR3
GPU Intel HD Graphics 6000 1536 Mo
**macOS Sierra 10.12.1 (16B2555)**
