### ISSUE TITLE
Fix for Bluetooth MX Master Configuation and Loss of Functionality

### ISSUE THREAD

**Issue by rnbarg** [tekezo/Karabiner-Elements#339]
IMPORTANT!! Using a 2nd mouse I turned off BT, configured my Logitech MX Master as a USB mouse using unifying receiver in Logitech Options. I tried and then purchased "USB Overdrive 3.3" is ready for Sierra for $20 USD at http://www.usboverdrive.com/USBOverdrive/News.html Now KElements runs fine and the mouse works great.

**Comment by gamesbrainiac** [comment]
Hey man, I'm not using USB Overdrive, i just stopped using it as a bluetooth mouse, and everything works fine.

**Comment by tekezo** [comment]
Duplicated #84
