### ISSUE TITLE
Using § section key on UK keyboard

### ISSUE THREAD

**Issue by edenworky** [tekezo/Karabiner-Elements#340]
Is there a way to map the `§` section key to something else? Additionally, so long as Karabiner-Elements is open, my `§` section key and `` ` `` backtick key are swapped before I did anything, and I can't find a way to switch them back.

**Comment by aleksandarristic** [comment]
I've swapped those two (on an international keyboard) like this (snippet of my configuration):

`      "simple_modifications" : {
        "non_us_backslash" : "grave_accent_and_tilde",
        "grave_accent_and_tilde" : "non_us_backslash"
      },
`

However, those two weren't swapped before I actually found the key "names" and did the swap. Don't know if this applies to your particular keyboard, hope it helps.

**Comment by edenworky** [comment]
Thank you so much! I managed to reverse them back. `non_us_backslash` is apparently the section key. Any clue as to how to added modifier keys? So `§` does ⌘⌥8 or whatever?

**Comment by talha131** [comment]
@edenworky You will have to wait for #16

**Comment by edenworky** [comment]
I see. Thanks! I added the unclear `non_us_backslash` name and the automatic section and backtick swapping to the relevant issues (#326 and #335 respectively). Closing this issue.
