### ISSUE TITLE
Map PC_APPLICATION to COMMAND_L

### ISSUE THREAD

**Issue by garvinhicking** [tekezo/Karabiner-Elements#341]
I basically needed Karabiner for my MS Natural Ergonomic 4000 keyboard to switch the right Windows key to the Apple Command key. Karabiner had a specific option for that.

I updated to macOS sierra and obviously Karabiner doesn't work anymore, so I tried KarabinerElements, but this doesn't seem to offer switching this, or am I doing something wrong?

I would really love help to get my COMMAND_L on the right side back. Willing to $$$ for any help :-)

**Comment by tekezo** [comment]
You can change application key to command in Karabiner-Elements.
Check your configuration.
