### ISSUE TITLE
Logitech M570 clicks become unresponsive after application switch

### ISSUE THREAD

**Issue by brodypainter** [tekezo/Karabiner-Elements#344]
On my MacBook Pro 2012 15", after switching applications, for example clicking on the desktop after having Chrome active, the M570 clicks become un-responsive for 15-20 seconds, occasionally but unreliably registering clicks. The pointer movement still works fine, and using the internal mouse once fixes the problem.

**Comment by tekezo** [comment]
Does this issue still happen in the latest version (Karabiner-Elements v0.90.59)?

**Comment by brodypainter** [comment]
Yes, Though it does seem to take less time to start working again. Down to about 5 seconds.

**Comment by CJSF2323** [comment]
I'm seeing the same issue with my Logitech M705, also working within 5 seconds or so.

**Comment by tekezo** [comment]
Could you ignore the Logitech M570 in Devices tab in Preferences?

**Comment by brodypainter** [comment]
That seems to have done it. Thanks.
