### ISSUE TITLE
Double tap shift toggle caps lock

### ISSUE THREAD

**Issue by edygar** [tekezo/Karabiner-Elements#346]
Is there anyway to set double tap shift to toggle caps lock? 

(Currently, I've a remap of my caps lock to esc, but rarely I miss the ability to toggle caps mode)

**Comment by tekezo** [comment]
#369

**Comment by nomasprime** [comment]
Hi @tekezo, I looked at the issue you referenced but can't find anything about implementing double-tap. I'd like to map double-tap left shift to ESC.

**Comment by trusktr** [comment]
So how do we do double tap on a key? #369 doesn't exactly say.

**Comment by nguyenhimself** [comment]
You can accomplish this by using variables. The docs has [an example](https://pqrs.org/osx/karabiner/json.html#typical-complex_modifications-examples-change-right-shift-x2-to-mission-control). It works well for me.

**Comment by ZhengkunWang** [comment]
I figure it out by this , double tap left shift to switch cap_lock

```
{
      "description": "double left shift to cap_lock",
      "manipulators": [
      {
        "type": "basic",
        "from": {
          "key_code": "left_shift",
          "modifiers": {
            "optional": [
              "any"
            ]
          }
        },
        "to": [
          {
            "key_code": "caps_lock"
          }
        ],
        "conditions": [
          {
            "type": "variable_if",
            "name": "left_shift pressed",
            "value": 1
          }
        ]
      },
      {
        "type": "basic",
        "from": {
          "key_code": "left_shift",
          "modifiers": {
            "optional": [
              "any"
            ]
          }
        },
        "to": [
          {
            "set_variable": {
              "name": "left_shift pressed",
              "value": 1
            }
          },
          {
            "key_code": "left_shift"
          }
        ],
        "to_delayed_action": {
          "to_if_invoked": [
            {
              "set_variable": {
                "name": "left_shift pressed",
                "value": 0
              }
            }
          ],
          "to_if_canceled": [
            {
              "set_variable": {
                "name": "left_shift pressed",
                "value": 0
              }
            }
          ]
        }
      }
    ]
  }
```

**Comment by harmtemolder** [comment]
> I figure it out by this , double tap left shift to switch cap_lock
> 
> ```
> {
>       "description": "double left shift to cap_lock",
>       "manipulators": [
>       {
>         "type": "basic",
>         "from": {
>           "key_code": "left_shift",
>           "modifiers": {
>             "optional": [
>               "any"
>             ]
>           }
>         },
>         "to": [
>           {
>             "key_code": "caps_lock"
>           }
>         ],
>         "conditions": [
>           {
>             "type": "variable_if",
>             "name": "left_shift pressed",
>             "value": 1
>           }
>         ]
>       },
>       {
>         "type": "basic",
>         "from": {
>           "key_code": "left_shift",
>           "modifiers": {
>             "optional": [
>               "any"
>             ]
>           }
>         },
>         "to": [
>           {
>             "set_variable": {
>               "name": "left_shift pressed",
>               "value": 1
>             }
>           },
>           {
>             "key_code": "left_shift"
>           }
>         ],
>         "to_delayed_action": {
>           "to_if_invoked": [
>             {
>               "set_variable": {
>                 "name": "left_shift pressed",
>                 "value": 0
>               }
>             }
>           ],
>           "to_if_canceled": [
>             {
>               "set_variable": {
>                 "name": "left_shift pressed",
>                 "value": 0
>               }
>             }
>           ]
>         }
>       }
>     ]
>   }
> ```

Just in case anyone reads this and wants to change the time in which you need to press shift the second time, you can add the [`basic.to_delayed_action_delay_milliseconds` parameter](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to-delayed-action/#parameters)

**Comment by marvdm** [comment]
@ZhengkunWang Any idea why caps lock will turn on but not off if `"modifiers": {"optional": ["any"]}` is missing?

**Comment by MuhammedZakir** [comment]
> @ZhengkunWang Any idea why caps lock will turn on but not off if `"modifiers": {"optional": ["any"]}` is missing?

Caps lock is a modifier key, along with Fn, Control, Alt, Shift and Command. So if you want use a modification even when caps lock is enabled, you will have to explicitly mention `caps_lock` or `any` in `modifiers.optional`. Else, it won't trigger. `any` means you can use it with *any* modifier keys. And, if you want a modification to work only when caps lock is enabled, add `caps_lock` in `modifiers.mandatory`. See below link for more information.

https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/from/modifiers/
> **Tip**
> If you do not include any in modifiers.optional, your manipulator does not change event if extra modifiers (modifiers which are not included in modifiers.mandatory) are pressed.

**Comment by miquecg** [comment]
I've tried with this custom rules but it doesn't work for me. When I double tap sometimes characters are deleted or in Vim for instance it escapes insert mode.

Seen this on the release notes for 14.5.0:

```
💥 Breaking changes
    The following modifier flags and manipulators are now canceled even for events from devices not grabbed by Karabiner-Elements, e.g. mouse clicks.
        sticky modifiers
        to_if_alone
        to_if_held_down
        to_delayed_action
```

**Comment by miquecg** [comment]
Nah, I've managed to fix it. There was a conflicting mapping from `caps_lock` to `esc` in the macOS settings for the Karabiner keyboard 😅

Does Karabiner supports mappings like this: one key takes over another but the original can still be mapped?

**Comment by MuhammedZakir** [comment]
> Does Karabiner supports mappings like this: one key takes over another but the original can still be mapped?

Can you give an example of what you're asking? Also, it's better to open a new issue for questions unrelated to this issue.

**Comment by miquecg** [comment]
No worries, I've realized it's just a matter of a simple mapping. It doesn't matter that other key combos are acting like caps_lock for instance to then remap caps_lock itself.

Thanks and sorry for the noise :)

**Comment by MuhammedZakir** [comment]
No problem! :-)

It maybe slightly different that what you thought; see https://karabiner-elements.pqrs.org/docs/manual/misc/event-modification-chaining/.

**Comment by tummetott** [comment]
The previous script has a potential issue. Let's consider a scenario where you intend to type a capital "J," but you accidentally press only the SHIFT key. Realizing the mistake, you press SHIFT again, followed by the "J" key correctly. In this situation, the given script would activate Caps Lock because it recognizes a double SHIFT press.

To address this, the optimal solution is to activate Caps Lock on the release of the second SHIFT key press, but only if no other key is pressed in between. This ensures that Caps Lock is activated only when intended and avoids unexpected behavior due to consecutive SHIFT key presses.

```json
{
  "description": "Double Left Shift to Capslock",
  "manipulators": [
    {
      "conditions": [
        {
          "name": "left_shift_pressed",
          "type": "variable_if",
          "value": 1
        }
      ],
      "from": {
        "key_code": "left_shift",
        "modifiers": { "optional": ["any"] }
      },
      "parameters": { "basic.to_if_alone_timeout_milliseconds": 500 },
      "to": [{ "key_code": "left_shift" }],
      "to_if_alone": [
        {
          "hold_down_milliseconds": 200,
          "key_code": "caps_lock"
        },
        {
          "set_variable": {
            "name": "left_shift_pressed",
            "value": 0
          }
        }
      ],
      "type": "basic"
    },
    {
      "from": {
        "key_code": "left_shift",
        "modifiers": { "optional": ["any"] }
      },
      "parameters": {
        "basic.to_delayed_action_delay_milliseconds": 500,
        "basic.to_if_alone_timeout_milliseconds": 500
      },
      "to": [{ "key_code": "left_shift" }],
      "to_delayed_action": {
        "to_if_canceled": [
          {
            "set_variable": {
              "name": "left_shift_pressed",
              "value": 0
            }
          }
        ],
        "to_if_invoked": [
          {
            "set_variable": {
              "name": "left_shift_pressed",
              "value": 0
            }
          }
        ]
      },
      "to_if_alone": [
        {
          "set_variable": {
            "name": "left_shift_pressed",
            "value": 1
          }
        },
        { "key_code": "left_shift" }
      ],
      "type": "basic"
    }
  ]
}
```

**Comment by yspreen** [comment]
@tummetott I tried your rule, and it doesn't work for me. I don't know if something about karabiner elements changed, or if it's my simple caps lock to tilde rule that breaks it, but tapping shift twice no matter how fast does not appear to be working. It also doesn't press tilde for that matter

**Comment by yspreen** [comment]
it was the macOS caps lock delay that messed it up. fixed with https://superuser.com/a/1858081

**Comment by yspreen** [comment]
@tomek-kr sounds like this is the first time you're using karabiner and its complex modifications. this rule certainly works. your issue might be with learning karabiner elements in general

**Comment by tomek-kr** [comment]
Thanks @yspreen, thats what it was in the end. Running smoothly now - thank you.
