### ISSUE TITLE
Disabling the keyboard in the new devices tab breaks key+mouse modifiers

### ISSUE THREAD

**Issue by SCdF** [tekezo/Karabiner-Elements#349]
Version 0.90.56

To reproduce, using command click and Chrome as an example:
 - Run the beta, and disable the keyboard you're using to test
 - Navigate somewhere in Chrome that has a link (reddit say, or this bug report!)
 - Command+Click on a link to open it in a background tab

What should happen: the link opens in a background tab
What actually happens: the link opens in the current tab

This is happening because keyboards that are disabled have any key presses ignored in the mouse-click event. Other examples would be command+click in SublimeText3 creates more text carets, and control+click simulates a right-click.

**Comment by SCdF** [comment]
More notes:
 - This breaks with just the internal keyboard attached, as well as multiple keyboards. It seems to break on any keyboard that you've disabled.

**Comment by tekezo** [comment]
Thank you for feedback.
It's an known issue and I fixed it at v0.90.57.
Please confirm the latest version.

**Comment by SCdF** [comment]
Yep awesome, works great!
