### ISSUE TITLE
Overwriting key remapping of macOS settings.

### ISSUE THREAD

**Issue by hirakujira** [tekezo/Karabiner-Elements#35]
Found an issue that Karabiner would overwrite macOS built-in key remap in default.
For example, I switched option and command key in the macOS settings, then when I open Karabiner-Elements, it would change back. So I have to use `simple_modifications` in Karabiner to switch again. However since Karabiner-Elements doesn't support remap for specific keyboard now, I have to switch between different profiles to apply correct remap file.

**Comment by talha131** [comment]
> Found an issue that Karabiner would overwrite macOS built-in key remap in default.

Please see #9. 

> We cannot avoid this issue in the new Karabiner-Elements architecture.
Please modify all modifiers in Karabiner-Elements.
