### ISSUE TITLE
Cmd + Drag won't work

### ISSUE THREAD

**Issue by liudangyi** [tekezo/Karabiner-Elements#352]
With Karabiner on, I cannot cmd-drag icons in system status bar, even if I deselected "apple interval keyboard" in devices tab in Karabiner.

**Comment by tekezo** [comment]
Thank you for feedback.
It's an known issue and I fixed it at v0.90.57.
Please confirm the latest version.

**Comment by liudangyi** [comment]
Great job! Thank you so much!
