### ISSUE TITLE
Can't use function keys when ctrl and fn are swapped

### ISSUE THREAD

**Issue by the21st** [tekezo/Karabiner-Elements#354]
Hi! Thanks so much for creating Karabiner! It really makes my life a lot easier.

I have my left ctrl swapped with fn:
![screen shot 2016-10-27 at 11 41 54](https://cloud.githubusercontent.com/assets/4610874/19762488/728f97ac-9c3a-11e6-8229-3cf5dd3c3e2d.png)

However, after one of the recent updates, the functions keys tab was added and the keys were mapped to the "media keys" by default. However, even after remmaping them back to the F-keys, pressing Fn+Fkey doesn't work:
![screenshot 2016-10-27 11 43 41](https://cloud.githubusercontent.com/assets/4610874/19762530/a2d75206-9c3a-11e6-9ebd-a0bdfe60eb50.png)

So for example, I cant change volume by pressing Fn+F11 now.

Note that this was working last week, so if I had the option to turn off Karabiner's F-keys remapping altogether, it would probably help.

Thanks!

**Comment by kron4eg** [comment]
Sounds very familiar to #353

**Comment by tekezo** [comment]
Thank you for feedback!
Karabiner-Elements v0.90.58 has an issue that ignores "Use all F1, F2, etc. keys as standard function keys" setting in System Preferences.

I've fixed this issue in v0.90.59.
Please upgrade to the latest version.
Then restore your Function Keys setting to the default and use "Use all F1, F2, etc. keys as standard function keys" setting in System Preferences.

**Comment by the21st** [comment]
I upgraded and it's working now, thanks! And thank you for the amazing work on Karabiner!
