### ISSUE TITLE
Karabiner-Elements overrides the keyboard remapping in OS X

### ISSUE THREAD

**Issue by christianbay** [tekezo/Karabiner-Elements#355]
In OS X you can rebind keys using Preferences -> Keyboard -> Modifier keys. This allow you to switch CMD and ALT for instance. I use this to swap CMD and ALT on my USB keyboard, so that it's consistent with the layout on my laptop.

The issue is that Karabiner-Elements is overriding these key re-mappings, and it has no support for different keyboards.

This never happened with Karabiner or the other iterations of this application.

**Comment by anazimok** [comment]
Is there a way to download a previous version of the binary for karabiner-elements?

**Comment by talha131** [comment]
Please @tekezo comment on this issue [here](https://github.com/tekezo/Karabiner-Elements/issues/9#issuecomment-248498163)

> We cannot avoid this issue in the new Karabiner-Elements architecture.
> Please modify all modifiers in Karabiner-Elements.

**Comment by tekezo** [comment]
Duplicated #9

**Comment by jeremiahishere** [comment]
I duplicated the problem accidentally and it continued after uninstalling the application.
