### ISSUE TITLE
Magic Keyboard: Eject button is not working with Karabiner-Elements

### ISSUE THREAD

**Issue by kvint** [tekezo/Karabiner-Elements#356]
Seems like the problem indeed related to the Apple's Magic Keyboard, since Karabiner-Elements works fine on laptop keyboard on the same (macOS 10.12) system.
EventViewer shows

with elements enabled:

- Eject = nothing
- Fn+Eject = **0xe**

without elements enabled:

- Eject = nothing
- Fn+Eject = nothing

![screen shot 2016-10-27 at 20 41 58](https://cloud.githubusercontent.com/assets/621317/19778520/d9c301de-9c85-11e6-8d8c-33d9b37a9560.png)

So with karabiner enabled shutdown (Ctrl+Option+CMD+**Eject**), reboot (Ctrl+CMD+**Eject**), sleep (Ctrl+Shift+**Eject**) hotkeys **is unusable**.
Hope it helps.

Thanks for the software.

**Comment by kurtontheway** [comment]
Same situations on my magic keyboard.

**Comment by tekezo** [comment]
#46
