### ISSUE TITLE
Inquiry re: New Devices Tab

### ISSUE THREAD

**Issue by rnbarg** [tekezo/Karabiner-Elements#357]
Please explain what it means when "Modify Events from this Device." is checked vs. not checked. Thanks.

![2016-10-27_12-10-27](https://cloud.githubusercontent.com/assets/10092862/19781557/98f4107c-9c3e-11e6-8bad-c81450fe478a.jpg)

**Comment by gamesbrainiac** [comment]
Karabiner won't affect the devices unselected.
