### ISSUE TITLE
How is this free

### ISSUE THREAD

**Issue by JBLatenight** [tekezo/Karabiner-Elements#358]
@tekezo this clearly takes a ton of time and skill to build. You are most generous for making this. Many kutos 😳

**Comment by cmsj** [comment]
@JBLatenight you can pay tekezo on the Karabiner homepage if you want to (and I think you should!) https://pqrs.org/osx/karabiner/pricing.html.en

(also I would suggest closing this issue, since it's not really a request for any work to be done :)

**Comment by tekezo** [comment]
Thanks!
