### ISSUE TITLE
Latest update ignores Mac OS Keyboard Setting

### ISSUE THREAD

**Issue by rkonopka** [tekezo/Karabiner-Elements#359]
The latest update ignores the state of of the "Use all F1, F2, etc. keys as standard function keys". I currently have this option checked, but it is not honored by Karabiner. That is, pressing F12 for example invokes the volumn_up action even though I do not have the Fn button pressed. The previous build did not have this issue. 

I do not want to change the behavior of the function keys. I want them to operate as they normally do on the Mac with the above option set. Therefore, when I am in Parallels running a Windows VM, the function keys work as expected. If I want to invoke one of the Mac specific function keys (such as Increasing the Volume), then I press and hold the Fn key and then press the F12 key.

How can this be accomplished as it was in the previous build?

Is there anyway to remove the Function Key mappings?

**Comment by NihatO** [comment]
No solution?
