### ISSUE TITLE
我的macbook键盘是日文版的键盘，在使用karabiner-elements最新版本后出现按键映射问题

### ISSUE THREAD

**Issue by panminxian** [tekezo/Karabiner-Elements#363]
比如我按shift + 2 本来应该打印出冒号，但是实际打印了@
再比如我按@键打印的是【
求教，这个问题该怎么解决？

**Comment by yishanhome** [comment]
软件：Karabiner-Elements
 （set keyboard_type (ansi, iso, jis) function implemented）
 百度云盘下载 pan.baidu.com/s/1skMGDkh

**Comment by yishanhome** [comment]
用这个编译的 https://github.com/tekezo/Karabiner-Elements/pull/362

**Comment by yishanhome** [comment]
![qq20161028-0](https://cloud.githubusercontent.com/assets/19500386/19808002/42d4ff0e-9d55-11e6-9f94-11305785a6e6.jpg)

**Comment by yishanhome** [comment]
设置参考 https://cloud.githubusercontent.com/assets/19500386/19808002/42d4ff0e-9d55-11e6-9f94-11305785a6e6.jpg

**Comment by tekezo** [comment]
Please upgrade Karabiner-Elements to the latest version and set keyboard type in Devices tab.
https://github.com/tekezo/Karabiner-Elements/tree/master/usage#set-keyboard-type

**Comment by panminxian** [comment]
感谢yishanhome和tekezo还有dcato，前几天不在，目前我已经更新到了最新版本，出现了键盘驱动的选项，当我选择jis后，该问题已经得到了解决。谢谢你们提供的优秀软件。
