### ISSUE TITLE
Mouse lost response with latest version

### ISSUE THREAD

**Issue by sumsethan** [tekezo/Karabiner-Elements#364]
Microsoft Sculpt Comfort Mouse vid0x045e pid0x07a2 lost response while I updated to 0.90.60 and check the checkbox in "Devices",no problem with last version.

**Comment by sumsethan** [comment]
And will Karabiner-elements support "eject"key modification or I
 should wait for next version of ejectnodelay ?

**Comment by sumsethan** [comment]
also with 0.90.61

**Comment by tekezo** [comment]
Please attach the log in Preferences > Logs tab.

You cannot change the eject key in Sierra.
https://github.com/tekezo/Karabiner-Elements#limitations

**Comment by sumsethan** [comment]
back to normal after a reboot.....Thanks anyway. closed
