### ISSUE TITLE
Map mouse buttons to keyboard

### ISSUE THREAD

**Issue by AJLivine** [tekezo/Karabiner-Elements#365]
I used Karabiner to map left-, middle-, and right-click to PC Scrolllock, PC Insert, and PC Delete to work with a SmartNav hands-free mouse (unable to use a regular mouse). I've been eagerly awaiting support for this in Karabiner-Elements.

I noticed pointing_button has been added to types and there's a pointing_button_manager. I don't know how to translate the code into what you need to put in karabiner.json, though. Anyone have a working example?

Thanks :)

**Comment by gcushen** [comment]
Duplicate of #261
