### ISSUE TITLE
Should we UNinstall Karabiner before INstalling Karabiner-Elements?

### ISSUE THREAD

**Issue by syberknight** [tekezo/Karabiner-Elements#367]
i had a few customizations that i've used heavily for years that's now gone with the Sierra upgrade. so i hit the Karabiner website to find we're to now use this Karabiner-Elements instead.

before i install it, do i need to uninstall the other?

thanks.

**Comment by talha131** [comment]
Karabiner is just useless on Sierra. You can keep it for referencing your old configuration as you copy them to KE little by little with every update of KE. Just set Karabiner not to relaunch on login and quit it. Or simply install it. Your choice.

**Comment by talha131** [comment]
Kindly close this issue, if your question has been answered 😄

**Comment by syberknight** [comment]
heh, sorry, i never noticed the "close" button down below before. always assumed you guys had to close issues.
thanks for the answer & thanks again for letting me know! ✌🏼
