### ISSUE TITLE
How can I swap § and £ to be ` and ~?

### ISSUE THREAD

**Issue by castus** [tekezo/Karabiner-Elements#373]
My MacBook Pro's keyboard has tilde near to ```z``` key. I want to swap it with key near to ```1``` which is the default for modern keyboards.
How can I swap ```§``` and ```£```(with Shift) to be ``` ` ``` and ```~```(with Shift) using Karabinier Elements?

**Comment by tekezo** [comment]
Read this article.
https://github.com/tekezo/Karabiner-Elements/blob/master/usage/README.md#how-to-configure-karabiner-elements

**Comment by castus** [comment]
Thank you, Karabiner-EventViewer is what I was looking for.

Summary: You need to swap ```non_us_backslash``` to ```grave_accent_and_tilde(`)```
