### ISSUE TITLE
Can't QUIT the app

### ISSUE THREAD

**Issue by syberknight** [tekezo/Karabiner-Elements#375]
made some changes then went to quit the app & got this (attached screenshot).

with Karabiner, we didn't have to have the app running (showing in the dock). is there a way to accomplish this with K-Elements?

<img width="420" alt="screen shot 2016-10-30 at 12 58 31 pm" src="https://cloud.githubusercontent.com/assets/3630609/19838593/cbd5d2be-9ea0-11e6-8639-e83987f8daa9.png">

**Comment by talha131** [comment]
Simple close the window by clicking close window button or use ⌘Command+W. KE will keep running in the background but it will not appear in the window switcher list or dock.

**Comment by syberknight** [comment]
ah! DUH, sorry 'bout that; but thanks for the reply!!
