### ISSUE TITLE
Support Sierra's Caps Lock input-switching feature

### ISSUE THREAD

**Issue by pickx** [tekezo/Karabiner-Elements#378]
Sierra has a great new feature under System Preferences -> Keyboard -> Input Sources: "Use the Caps Lock key to switch to and from ABC". Basically, short press switches input method, long press enables Caps Lock mode.

Karabiner-Elements stops this useful behavior and makes Caps Lock act like normal.

edit: for now a quick option for Karabiner to not remap Caps Lock at all would be useful, as I rely on this feature.

**Comment by tekezo** [comment]
Thank you for feedback!
It looks like a macOS issue, I try to find a workaround for this issue.

**Comment by dionorgua** [comment]
It's possible to remap Caps Lock to F19 using Karabiner-Elements and later set it as 'input source' hotkey in OS X settings

**Comment by pickx** [comment]
Good workaround for now, thanks @dionorgua. The nice thing is that when you quit Karabiner the new Caps Lock behavior is restored, so it always works as it should.
