### ISSUE TITLE
Keyboard no response with after mac wakeup from sleep

### ISSUE THREAD

**Issue by Spin0za** [tekezo/Karabiner-Elements#379]
With Karabiner-Elements on, every time the mac wakes up, the internal keyboard has no response for around half a minute. To be more accurate, it's a half minute delay in response. With K-E turned off, the keyboard works immediately. Forgot about external keyboard, but probably didn't work either. This issue keeps occurring on 10.12 and 10.12.1.

**Comment by alyssais** [comment]
I had the same problem. Updating to Karabiner-Elements 0.90.63 fixed it for me.

**Comment by Spin0za** [comment]
Not fixed for me. Only the delay of response a bit shortened.
