### ISSUE TITLE
Mapping Capslock to F10 issue

### ISSUE THREAD

**Issue by snazzybunny** [tekezo/Karabiner-Elements#381]
On Sierra, mapping capslock to F10 will mute/unmute my Macbook. I have to enable the keyboard setting "Use F1, F2, etc. keys as standard function keys" in order to make it work. Otherwise, it will mute/unmute my Macbook. This means the fkeys (f1 to F12) and the media control keys (vk_*, mute, volume up, volume down) are mapped to the same thing.

 Is there any way we could have the option to map a key to multiple keys such as fn + fkey instead of just the regular fkeys? Thanks.

**Comment by maartenvandillen** [comment]
Same problem here. I have mapped F12 to forward delete, but now fn-F12 to increase volume does not work anymore.

**Comment by rogeriochaves** [comment]
hello, I used to map capslock to F10 for tmux, and had the same problem. I've solved it by mapping to F13 instead, and tmux inteprets F13 through F24 as S-F1 through S-F12

hope this helps
