### ISSUE TITLE
How to swap ] and ё (same as § and ` in En) in the Russian layout?

### ISSUE THREAD

**Issue by eugenesvk** [tekezo/Karabiner-Elements#384]
I know from https://github.com/tekezo/Karabiner-Elements/issues/136 that there is a way to swap `§` and `~` keys in the English layout of my Apple keyboard.
However, the Russian layout (equivalent keys are `]` and `ё`) doesn't maintain this change and trying International1-9 and lang1-9 didn't help either.
Would you please add the corresponding keys for the Russian layout?
Thank you

**Comment by berlic** [comment]
I use 0.90.61 Elements with simple modification `non_use_backslash` to `grave_accent_and_tilde`.  
And remap works fine in both in US and Russian-PC layouts.

**Comment by eugenesvk** [comment]
I have the same version and it's not working, so you might have a different keyboard.

**Comment by berlic** [comment]
Just in case, info for internal MBP keyboard and external BT keyboard:
```
$ system_profiler SPSPIDataType
SPI:

    Apple Internal Keyboard / Trackpad:

      Product ID: 0x0273
      Vendor ID: 0x05ac (Apple Inc.)
      Version: 6.22
      Manufacturer: Apple Inc.
      Location ID: 0x01000000
```

```
$ system_profiler SPBluetoothDataType
Bluetooth:

      Devices (Paired, Configured, etc.):
          клавиатура:
              Major Type: Peripheral
              Minor Type: Keyboard
              Services: Apple Wireless Keyboard
              Manufacturer: Apple (0x3, 0x31C)
              Firmware Version: 0x0050
              Vendor ID: 0x05AC
              Product ID: 0x0256
              Class of Device: 0x05 0x10 0x2540
```

**Comment by sbmaxx** [comment]
I'm using microsoft sculpt ergonomic desktop. I found the way to bring back `Ё` with strange combination:
```
non_us_backslash -> grave_accent_and_tilde
grave_accent_and_tilde -> non_us_backslash
```

But now i can't use `~` and ` :(

**Comment by eugenesvk** [comment]
@sbmaxx it's **not** a strange combination, it's exactly what the [user manual](https://github.com/tekezo/Karabiner-Elements/tree/master/usage#swapping-sectionparagraph--key-on-non-us-keyboards
) suggest you do :) My issue is that it only deals with one pair of keys (different pair for different keyboards), but not the other pair since the keys can have different names in different layouts
