### ISSUE TITLE
HIDIdleTime (reported by IOHIDSystem) does not reset when using the keyboard

### ISSUE THREAD

**Issue by jawwad** [tekezo/Karabiner-Elements#385]
I run a program named ChronoMate for time tracking and it tracks my idle time for me. For example it shows me an alert when I come back from Idle asking if I want to include the idle time in my time tracking.

The issue is that when running Karabiner-Elements, macOS thinks I'm idle even when I'm typing (and so when I move my mouse again ChronoMate keeps on showing me the alert since it thought I was idle).

I tested this by running the following script: 
https://www.dssw.co.uk/blog/2015-01-21-inactivity-and-idle-time/

When typing, the idle time reported by HIDIdleTime would continue to increase:
![image](https://cloud.githubusercontent.com/assets/202240/19880782/002dfafa-a022-11e6-98d0-55674f0403ae.png)

For example here I typed "I am typing in the terminal" while the script was running:
![image](https://cloud.githubusercontent.com/assets/202240/19880865/bdd2ed36-a022-11e6-84ae-3ac4fdf7977c.png)

After moving my mouse the idle time reported by macOS would reset. For example here I moved my mouse after 20 seconds of typing:
![image](https://cloud.githubusercontent.com/assets/202240/19880798/2abcc968-a022-11e6-9856-a4dc691b9fb0.png)

When I quit Karabiner-Elements the system goes back to reporting the correct idle time and will reset to 0 as soon as I type anything.

**Comment by tekezo** [comment]
Are you using the latest version of Karabiner-Elements?

**Comment by jawwad** [comment]
I just checked for updates and it shows the "You're up-to-date!" alert. It says I'm on version 0.90.61.

**Comment by tekezo** [comment]
I confirmed this issue.
It's macOS 10.12 issue that `IOHIDPostEvent` API does not reset the idle timer.
Unfortunately, there are no workarounds in Karabiner-Elements side to avoid it.

**Comment by jawwad** [comment]
@tekezo - Thanks for looking into this so quickly! At least now I know that I just have to live with it for now since I can't live without having my caps lock key map to escape!

By the way, did you see that there is [no escape key](http://www.theverge.com/circuitbreaker/2016/10/25/13409258/apple-new-macbook-pro-no-escape-key) on the new macbooks with the touch bar? I think a lot more users are going to be using their caps lock key as escape soon.
