### ISSUE TITLE
Request: (Japanese Karabiner functionality) Command keys to En and Ja

### ISSUE THREAD

**Issue by b-d-m-p** [tekezo/Karabiner-Elements#386]
Hi, 

Thanks for making this utility—I really appreciate it. 

I use Japanese everyday and I got a Spanish keyboard, so I was using Karabiner's first option in the Japanese section, which changes, on one tap, the left command key to English and the right command key to Japanese. (I've included a screenshot.) 

![karabiner japanese](https://cloud.githubusercontent.com/assets/1300390/19881706/62a8f0b2-a04b-11e6-9ac8-2cf99b3ac80f.png)

With Karabiner-Elements, I mapped my fn key to En and my right cmd to Ja. Is there a way that I can add this specific option, which differentiates between a tap and a hold, to Karabiner-Elements? Having this would really make my work day more pleasant. 😄 

Any info you can give to point me in the right direction would be very appreciated. 

Thanks.

**Comment by htakemoto** [comment]
I am also the one waiting for this feature.

**Comment by delphinus** [comment]
You can use the feature by forked binary that can be downloaded below.

* https://github.com/wwwjfy/Karabiner-Elements/releases/
* PR #247 

My sample setting:

```json
{
    "profiles": [
        {
            "devices": [],
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "left_command": "left_command",
                "right_command": "right_command"
            },
            "standalone_modifiers": {
                "left_command": "japanese_eisuu",
                "right_command": "japanese_kana"
            }
        }
    ]
}
```

I hope to merge PR early.

**Comment by b-d-m-p** [comment]
Awesome! Thanks so much!

**Comment by b-d-m-p** [comment]
I installed your fork, but I'm not sure how to apply those settings. Could you describe the process?

**Comment by b-d-m-p** [comment]
Found it! https://github.com/tekezo/Karabiner-Elements/pull/247

**Comment by htakemoto** [comment]
It didn't work.

First, I am very confused with the config location

~/.config/karabiner/karabiner.json
~/.karabiner.d/configuration/karabiner.json

Which is the one to add our custom json?

I also tried both standalone keys 0.90.72 (with hyper key) and standalone keys 0.90.72 from the one @delphinus provided. There is no luck.
