### ISSUE TITLE
German Mac Keyboard: Faulty maps < key to ^

### ISSUE THREAD

**Issue by bpasero** [tekezo/Karabiner-Elements#390]
When I enable Karabiner Elements (latest version) with an external German apple keyboard, I see that pressing the key above Ctrl/Option ends up being the key above Caps lock

Key I press:
![image](https://cloud.githubusercontent.com/assets/900690/19900302/4fe407ba-a063-11e6-8e4b-d51f527d4e00.png)

Key ends up being:

![image](https://cloud.githubusercontent.com/assets/900690/19900328/64153b1e-a063-11e6-9480-5590df21d16a.png)

I would appreciate some help here as I need Karabiner to map Right-Command to Right-Alt 👍

**Comment by Lunardis** [comment]
Could it be that you had a problem like [this](https://www.apfeltalk.de/community/threads/und-tasten-sind-vertauscht.506966)? (link leads to a german-speaking forums)

If yes, we had the same issue. I uninstalled Karabiner Elements now and this strange issue, that these two keys swapped gone away.

The curious thing about this is, that the Keyboard-Settings under SystemSettings-App thinks that we would have these strange curious layout.

So Karabiner Elements brings OSX Sierra to think that the layout has changed. (in my eyes a huge issue)

**Comment by bpasero** [comment]
@Lunardis sounds similar, however I am not on Sierra but on El Capitan and the issue is gone as soon as I stop Karabiner Elements like this:

![image](https://cloud.githubusercontent.com/assets/900690/19905958/392d685c-a079-11e6-8d40-f9484cc0abb2.png)

**Comment by bpasero** [comment]
Oh I see, you also figured that out. I wish there was another way of binding Right-Cmd t+ Right-Alt because that is the only reason I am using Karabiner Elements.

Btw this issue is not present when using Karabiner. I have the exact same setup at work and there I do not see it. Unfortunately I am not able to use Karabiner anymore on my home Mac because of this: https://groups.google.com/forum/#!topic/osx-karabiner/K9AkhHPpHtM

**Comment by wolfwolker** [comment]
Exactly the same behaviour here with spanish-iso layout. In my case the symbols switched are º and <, the keys positions are exactly the same as @bpasero described.
Tested with an external usb apple keyboard and a wireless logitech pc keyboard, same error in both cases.
Closing karabiner elements it gets fixed

**Comment by DejanS** [comment]
it is the same with other keyboard layouts...

i swap z and y | y and z, nothing else - but after i do this also “ and <> is swapped

It is definitely Karabiner - Elements that changes this ... it can be checked in Devices tab, if i uncheck my Keyboard ... <> and ”” is back on its place (changing keyboard type is not working / solving the problem).

**Comment by DejanS** [comment]
OK solution.

![image](https://cloud.githubusercontent.com/assets/761519/20117107/6cb5d822-a5ff-11e6-9d41-a86fdc159b05.png)

works for me at the moment ...

**Comment by bpasero** [comment]
@DejanS thank you so much!!!!!!!!!!!

**Comment by wolfwolker** [comment]
It works for me too (spanish layout) thanks so much

**Comment by rodomar705** [comment]
Same here with an italian layout, thanks 👍

**Comment by jacobbarssbailey** [comment]
This is seen on both ISO and JIS layout keyboards. My JIS keyboard is getting interpreted as US, with nearly all non-alphanumeric keys sending the wrong results. As is, Karabiner Elements is entirely unusable on JIS keyboards.

**Comment by DejanS** [comment]
yes - this solution works at the moment for ISO - but I think all keyboards are seen as US ... even if you choose different keyboard and language in MAC OSX preferences...

**Comment by bytesplit** [comment]
Probably this item can be closed if you check to have your Karabiner configured like this:
Preferences > Virtual Keyboard > Keyboard Type : Set to ISO

German layout Cherry PC-keyboard and configured as such in OS. It seems that by default Karabiner makes all keyboards ANSI.

Probably related to/duplicate of #1035

**Comment by Luceres** [comment]
This works, but | is still on ALT GR ^ on German Keyboard. How can I fix that?

**Comment by bytesplit** [comment]
Hallo @Luceres, could you explain what you are trying to achieve?

- Internal or external keyboard?
- Apple or Windows-based?
- Which keys are swapped/should be swapped?

I have a Windows keyboard from Cherry attached. Key ^ symbol on keyboard is entered correctly. Same for < next to Y. Also for the Macbook internal keyboard where I actually have Karabiner disabled. Everything just perfect.

The pipe symbol | is Mac-like ALT+7 by default (works fine for me). Do you want to have it on ALT GR+< like on Windows? How about @ on ALT GR+Q? I hate it because of Cmd+Q is quit...

I had my wifes iMac swapped to behave Windows-like (so all keys react like on the Windows keyboard). Definitely possible but strange feeling for Mac-User.

**Comment by Luceres** [comment]
Hi,
 I have a german Magic Keyboard, using it for normal macOS. I had the problem with the faulty maps < key to ^ as described above and fixed that (also as described above).
But the "|" key (Alt Gr "<" on the german keyboard) is still on Alt Gr "^". How can I swap the too?

**Comment by bytesplit** [comment]
@Luceres I cannot follow your description... :/

On Mac there is no ALT and ALT GR. Both is just ALT whichever you press. To get the Unix pipe symbol "Gerader Strich" you must press ALT+7.

Actually the only rules I have active are to swap ALT/Cmd. Then Keyboard type set to ISO. No changes like DejanS as this made problems.

Works perfectly on Apple Extended Keyboard German and a PC ISO Cherry German. Exact Mac keyboard mapping.

If you do want to have Windows behaviour that is another story... ???

**Comment by supine** [comment]
My situation is similar to @Luceres 

- external MS Natural Ergo 4000
- I've set KE to use ISO
- Imported/activated the "PC-Style German Alt Gr" from https://pqrs.org/osx/karabiner/complex_modifications/#international
- Swapped left_option and left_command

Everything works "Mac-like" and "QWERTZ-like" except the pipe symbol. 

It should be ALT GR + < but instead that gets me ≤

I can type | by using ALT GR + ^ or ALT + 7 but I would rather fix it.

**Comment by uloco** [comment]
When you set your keyboard to ANSI (though it is ISO obviously) my mappings appear to be correct (tested on my Vortex Pok3r ISO German Keyboard)...

**Comment by sknull** [comment]
I recently stumbled upon this issue and found out that it is not a bug really.
In the config file found under ~/.config/karabiner/karabiner.json
you find one entry when you have imported the snippet "German PC-Style Shortcuts (Enable various Alt Gr key combinations" from the repository:
`
                            {
                                "from": {
                                    "key_code": "grave_accent_and_tilde",
                                    "modifiers": {
                                        "mandatory": [
                                            "right_option"
                                        ],
                                        "optional": [
                                            "any"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "7",
                                        "modifiers": [
                                            "left_option"
                                        ]
                                    }
                                ],
                                "type": "basic"
                            },
`

just replace the "gravatar_accent_and_tilde" by "non_us_backslash".
At least on my german cherry stream-xt this worked right away.

No luck here with the numlock.
