### ISSUE TITLE
Allow to bind caret key ^ 

### ISSUE THREAD

**Issue by bpasero** [tekezo/Karabiner-Elements#391]
I would like to bind to the key: ^ but could not find a way to do so.

**Comment by mtin79** [comment]
+1 
on the microsoft surface ergonomic keyboard the caret key is swapped with the "<" keys on a qwertz-german keyboard layout and i would change it back to the correct position with karabiner elements.

**Comment by Developer2048** [comment]
same problem here...

**Comment by themightyoarfish** [comment]
Any update here?

**Comment by alex-salnikov** [comment]
try `non_us_backslash` (worked for me - swapped it for `escape` on my MacBook), reference: https://github.com/pqrs-org/Karabiner-Elements/issues/563
