### ISSUE TITLE
Older Apple Bluetooth Keyboard (A1016), not recognized in Karabiner-Elements

### ISSUE THREAD

**Issue by jameskachan** [tekezo/Karabiner-Elements#392]
I have an older Apple Bluetooth Keyboard (White, first gen wireless) that isn't recognized properly with Karabiner-Elements running.

(I know, it's ancient, but I want a full size, apple layout wireless keyboard, with fullsize keys…to my knowledge, that doesn't exist anywhere else)

When the software runs, it doesn't recognize the Media Eject Key ⏏ and displays an incorrect keyboard layout.
—
![screenshot 2016-11-02 at 2 07 30 am](https://cloud.githubusercontent.com/assets/5762476/19918629/435eee52-a0a3-11e6-82d7-d50abd8dd25e.png)

After quitting Karabiner-Elements, the Keyboard is recognized properly. 
—
![screenshot 2016-11-02 at 2 18 36 am](https://cloud.githubusercontent.com/assets/5762476/19918630/4368862e-a0a3-11e6-93be-d6651111bd9d.png)

**Comment by Username-Bacon** [comment]
Mine too. I have same keyboard as you and it shows like this.
However on mine, before I press something on my keyboard, it shows the currect keyboard layout. 
![default](https://cloud.githubusercontent.com/assets/23311189/20292521/0c071852-ab53-11e6-9d7c-b8f8eca6fc16.jpg)
After I press something on this keyboard, it goes back to the wrong keyboard type.
![2](https://cloud.githubusercontent.com/assets/23311189/20292533/1ccb7c1e-ab53-11e6-9857-a0812d612de1.jpg)

oh and media eject key does not work too. It seems like keys with functions (eject, volume up/down) is not supported by karabiner yet

**Comment by rinopo** [comment]
The "incorrect keyboard layout / wrong keyboard type" mentioned above seems to be what is referred to as the "virtual keyboard" in Karabiner-Elements' terminology.

<img width="1012" alt="karabiner-elements preferences 2017-10-19 14-22-21" src="https://user-images.githubusercontent.com/45791/31755359-ed657e08-b4d8-11e7-9df5-ef114340171b.png">

> When the software runs, it doesn't recognize the Media Eject Key ⏏

That Karabiner-Elements cannot recognize the Eject key is a known limitation:
https://github.com/tekezo/Karabiner-Elements/blob/master/README.md#limitations

The functions keys / media keys are already supported.

Hope this helps.
