### ISSUE TITLE
Mouse has recognized like a Keyboard

### ISSUE THREAD

**Issue by fabriciomweb** [tekezo/Karabiner-Elements#393]
I need force the Mouse type like Mouse. 

This will show mouse actions on key mapping, correct? 

Thanks

![screen shot 2016-11-02 at 12 10 17](https://cloud.githubusercontent.com/assets/12531172/19932123/029bfb78-a0f6-11e6-8fda-a06fd01ccc3d.png)

**Comment by tekezo** [comment]
Your Gaming Mouse is keyboard-and-mouse combined device.
So, the keyboard part is shown in Devices tab.
Please unselect the device.
