### ISSUE TITLE
External Keyboard is killed by Karabiner :P 

### ISSUE THREAD

**Issue by manojfedx** [tekezo/Karabiner-Elements#394]
Hello! My external keyboard is suddenly dead with karabiner running! 
Really need some help here!

**Comment by jspiro** [comment]
Did you update to macOS 10.12.2? It killed mine too. I disabled it for my internal keyboard.

**Comment by spkunc** [comment]
@jspiro I confirm after updating to macOS 10.12.2 beta basically any keyboard input doesn't work with karabiner-elements enabled (version 0.90.61).

**Comment by manojfedx** [comment]
Yeah @jspiro I updated to 10.12.2 last night!

**Comment by tekezo** [comment]
#383
