### ISSUE TITLE
No keyboards running

### ISSUE THREAD

**Issue by acarravedo** [tekezo/Karabiner-Elements#395]
Hello, after installing version 0.90.61 my keyboard stopped working.

I had to disable the "Devices" tab settings to return to work, which attempt to map the modifications do not work.

![image](https://cloud.githubusercontent.com/assets/1014060/19978185/4ff8fa32-a1f6-11e6-9f46-960c173f1da9.png)

Thanks!!

**Comment by rudf0rd** [comment]
I had the same experience after I updated to the last beta (10.12.2 beta).

**Comment by mwdiers** [comment]
Dupe of #383
