### ISSUE TITLE
Unable to map vk_consumer_play, mute, etc. from a Microsoft Sculpt keyboard

### ISSUE THREAD

**Issue by alvin-a-garcia** [tekezo/Karabiner-Elements#397]
Hello, 

Thank you for developing such a useful utility.  

I've recently started using a Microsoft Sculpt keyboard and have successfully used Karabiner-Elements (and Karabiner before macOS Sierra) to map the Windows key, Alt keys, and Application key on it to behave like a Mac keyboard.  

However, I am unable to map the multimedia keys, which produce events "vk_consumer_play", "mute",    etc. to "vk_consumer_brightness_down", "vk_consumer_brightness_up", etc. so as to mimic the layout of a Mac keyboard.  I know that I can toggle the function-key toggle switch to have the keyboard output function keys when these keys are pressed and then map the function keys to these functions, but I use function keys for other uses, e.g. F11 for "Show Desktop" and F12 for "Show Dashboard".

**Comment by alvin-a-garcia** [comment]
I should clarify my comment above.  By "unable to map", I mean that when I specify the desired mappings in my `~/.karabiner.d/configuration/karabiner.json`, they seem to have no effect.

**Comment by lgarron** [comment]
Not stale, my dear stale bot! ;-)

**Comment by bland328** [comment]
@lgarron, if you are still around, you might want to take a look at [https://github.com/pqrs-org/Karabiner-Elements/issues/2052](https://github.com/pqrs-org/Karabiner-Elements/issues/2052).
