### ISSUE TITLE
xml to json config file converter

### ISSUE THREAD

**Issue by zchee** [tekezo/Karabiner-Elements#4]
Hi,

First of all, very thanks and congrats first release.
I have experience that downgraded to El Capitan because of can not use Karabiner...
I was deal by hard editing the keyboard layout(`.bundle`), but it does not need them anymore.
Thanks great works.

BTW, Karabiner-Elements seems to have not configuration file backward compatibility (right?).
I'm not troubled because my custom is few and simply remap key to key only. I'm hand-rewrite it from scratch now.

But some users would have a lot of custom.
Do you have plans to implement support of old `xml` syntax, or `xml` to `json` converter?
If not planned, I will consider to write the simple converter for karabiner specific syntax.

I'm not have C++ experience(reading only), So can contribute only in it...

Still not read the all source, If already implemented, sorry, ignore it.
I was a lot of learn macOS interface from Karabiner sources. Thanks again for great works.

**Comment by billstclair** [comment]
Yay! I have control back on my function key.

```
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "fn": "left_control"
            }
        }
    ]
}
```

**Comment by salas0316** [comment]
Great app! It saved my life.
I'd like to have a ".vimrc" or ".zshrc" like config file. e.g. "keymap arg key1 key2"
It has more readability and more friendly for general users.
User who is able to navigate to this file and modify it shows they have enough programming skill and ability.
