### ISSUE TITLE
set up?

### ISSUE THREAD

**Issue by MikhailNikolskii** [tekezo/Karabiner-Elements#400]
Guys, How to set it up? Can somebody write full manual? I used Karabiner Elements version, when it was needed to "write the keys" by my myself. I changed the ssd and now I need to set up this program again. I am downloading, installing KE and after I'm going to the application with the window of Karabiner - Elements Preferences. I want to switch Enter to the Shift_R, but it is not working. Maybe I'm doing something wrong? Please, help, because I need to work, and this program is nice, thats why I chose it. P.S. Sorry for mad skill of English language.

**Comment by tekezo** [comment]
Follow this instruction.
https://github.com/tekezo/Karabiner-Elements/blob/master/usage/README.md#how-to-configure-karabiner-elements
