### ISSUE TITLE
No devices in device tab

### ISSUE THREAD

**Issue by alexandre-g** [tekezo/Karabiner-Elements#401]
![image-z8z0i5zuus](https://cloud.githubusercontent.com/assets/9635561/20027687/443cd9ea-a366-11e6-8a11-d1be84a253dc.png)

This is on a hackintosh so using a pc keyboard. Tried a couple to no avail.

As a result I can't add any simple modifications etc. Or am I doing something wrong?

Sierra 10.12.1

**Comment by tekezo** [comment]
Could you confirm the latest version? (v0.90.63)

**Comment by alexandre-g** [comment]
Hi yes I've installed from .dmg in the link and also tried build from sources - same thing

**Comment by tekezo** [comment]
Please show me the contents of `/Library/Application Support/org.pqrs/tmp/devices.json`

**Comment by Ahg4goo9** [comment]
I have the same issue.
Here is the contents of my devices.json:
```
[
    {
        "descriptions": null,
        "identifiers": {
            "is_keyboard": true,
            "is_pointing_device": false,
            "product_id": 17,
            "vendor_id": 1130
        },
        "ignore": false,
        "is_built_in_keyboard": false
    },
    {
        "descriptions": {
            "manufacturer": "Apple Inc.",
            "product": "Apple Internal Keyboard / Trackpad"
        },
        "identifiers": {
            "is_keyboard": true,
            "is_pointing_device": false,
            "product_id": 628,
            "vendor_id": 1452
        },
        "ignore": false,
        "is_built_in_keyboard": true
    }
]
```

**Comment by alexandre-g** [comment]
and mine is:

```
[
    {
        "descriptions": null,
        "identifiers": {
            "is_keyboard": true,
            "is_pointing_device": false,
            "product_id": 16,
            "vendor_id": 2872
        },
        "ignore": false,
        "is_built_in_keyboard": false
    },
    {
        "descriptions": {
            "manufacturer": "",
            "product": "Gaming Mouse G600"
        },
        "identifiers": {
            "is_keyboard": true,
            "is_pointing_device": false,
            "product_id": 49738,
            "vendor_id": 1133
        },
        "ignore": false,
        "is_built_in_keyboard": false
    }
]
```

Logitech G600 mouse and some generic keyboard

I've cloned the drive and took it to work where I also have a G600 mouse and a razer deathstalker keyboard and it works there. The only difference apart from hardware would be the clover config, dsdt etc

**Comment by tekezo** [comment]
Thank you!
I've fixed this issue in v0.90.64.
Please upgrade to the latest version.

**Comment by Bogdanp** [comment]
I'm currently running into this same issue on a newly-purchased machine with an international keyboard:

<img width="801" alt="screen shot 2017-02-05 at 12 09 38" src="https://cloud.githubusercontent.com/assets/43347/22625338/26ecd902-eb9c-11e6-9fa7-82e9192ee1ca.png">

I'm running version 0.90.85 and `/Library/Application Support/org.pqrs/tmp/devices.json` doesn't exist.

**Comment by Bogdanp** [comment]
Installing version 0.90.66 then upgrading somehow fixed this issue.
