### ISSUE TITLE
Karabiner Prevents "Keyboard Repeat" from Working Well

### ISSUE THREAD

**Issue by 3rdMillWeb** [tekezo/Karabiner-Elements#405]
I am on the most recent MacOS: v10.12.1, with the most recent Karabiner-Elements: v0.90.61.

I have keyboard repeat at a very fast rate (in System Preferences). If I turn on Karabiner, it prevents the keyboard repeat from working well. It will only repeat 3-15 times, then stop, then I have to lift up the key and press it again. You can see that here: `http://cloud.3rdMillWeb.com/1X2P0W2s3R1y`.

And here you can see how keyboard repeat works when I Quit Karabiner-Elements: `http://cloud.3rdMillWeb.com/1p0O3W1T0x11`

**Comment by tekezo** [comment]
Could you confirm the latest version (v0.90.63)?

**Comment by xerial** [comment]
@takezo I also have a similar problem with v0.90.64 with this configuration:
![image](https://cloud.githubusercontent.com/assets/57538/20293120/60560f18-aaa8-11e6-8a72-c3599a5a0091.png)

In my case, the key repeat completely stops working even after quitting Karabinar-elements. And key repeat configuration in the system preference showed weird values: 
![image](https://cloud.githubusercontent.com/assets/57538/20293155/a09c57c6-aaa8-11e6-9156-77949ebd70ba.png)

It seems Karabinar's key repeat setting affects to the disabled keyboards:
![image](https://cloud.githubusercontent.com/assets/57538/20293191/f4b8f1a2-aaa8-11e6-9748-c0644c181f02.png)

If I turn on 'Modify events from this device', key repeat settings seems working as expected.

**Comment by 3rdMillWeb** [comment]
Sorry, I missed this somehow. A recent update fixed it. It is now just managed in System Preferences.
