### ISSUE TITLE
Keyboard no response after checking a box in "Devices"

### ISSUE THREAD

**Issue by pillowang** [tekezo/Karabiner-Elements#407]
Keyboard totally no response after checking any of those boxes.

Sierra 10.12.2 Beta

Elements 0.90.63

**Comment by gAmUssA** [comment]
same here +1

```
ProductName:	Mac OS X
ProductVersion:	10.12.2
BuildVersion:	16C32f

Elements 0.90.63
```

**Comment by oldpiano** [comment]
Me too!
I tried install previous version(0.90.60), but same, not working keyboard enabled in devices tab.

0.90.63

**Comment by tekezo** [comment]
#383
