### ISSUE TITLE
Keyboard not work at all

### ISSUE THREAD

**Issue by Polishapple** [tekezo/Karabiner-Elements#409]
My keyboard isn't working at all after update to x.63

**Comment by acarravedo** [comment]
the same!! The tab devices "kill" my keyboards and only run when disconnect all checks.

**Comment by sprig** [comment]
Same problem. I am not sure whether it is after the update to K-E or to OSX [10.12.2 Beta (16C32f)], since both happened roughly at the same time.

Are either of you @Polishapple @acarravedo on 10.12.2 Beta?

**Comment by sprig** [comment]
Ok, I'm pretty sure this is OSX - I uninstalled K-E v63 and installed v59, and the same issue persists.

**Comment by jrolfs** [comment]
Can also corroborate the macOS issue, 0.60 and other versions prevent keyboard input entirely on macOS 10.12.2 Beta (16C32f)

**Comment by tekezo** [comment]
#383
