### ISSUE TITLE
Input method switch shortcut is broken

### ISSUE THREAD

**Issue by hirakujira** [tekezo/Karabiner-Elements#41]
I just found that Karabiner-Elements breaks input method switch.
In default, macOS uses ctrl+space to switch between current and previous input method. After opening Karabiner, it doesn't work. (But long press ctrl+space to switch between all input methods still works).

This also occurs even when I don't custom anything, so I think it's a bug?
In the event viewer, I found that when Karabiner-Elements opened, it shows 4 logs in each press of cmd, opt, ctrl keys instead of 2. Maybe it's the reason.

**Comment by talha131** [comment]
I have faced the same issue. Surprising thing is,

if I change spotlight shortcut to ⌃Control+Space it works fine. This mean ⌃Control+Space only has problem when it is set to switch input source.

Also, I have set ⌃Control+⌥Option (alt)+Space to switch input source. It too does not switch the sources, unless I long press.

**Comment by hirakujira** [comment]
Yeah... actually I use `Command + space` to switch between input sources, this is broken as `Ctrl + space` for switching input sources. I think Karabiner just breaks the function of switching input source instead of the specific shortcut.

**Comment by a-triant** [comment]
I updated right now to 0.90.33 and now the input switch works, thank you!

**Comment by tekezo** [comment]
Thank you for feedback!
I've fixed this issue at v0.90.33.

Please upgrade to the latest version from "Misc > Check for updates" or 
https://pqrs.org/latest/karabiner-elements-latest.dmg
