### ISSUE TITLE
Provide an option to avoid trying to rebind any function keys.

### ISSUE THREAD

**Issue by lgarron** [tekezo/Karabiner-Elements#410]
A recent version of Karabiner-Elements introduced a "Function Keys" pane with default function key settings. For some reason, these settings do not work properly with certain external Microsoft keyboards (see #396 and #397).

<img width="912" alt="screen shot 2016-11-06 at 21 18 46" src="https://cloud.githubusercontent.com/assets/248078/20047217/dce3e020-a466-11e6-804b-6520686832ca.png">

While it would be nice to fix the functionality for those keyboards, the function keys worked just fine before the pane was introduced. Now, I have to choose between the bindings I want vs. the function keys working (note: I use several programs that rely on the function keys working).

If we could disable the function key rebinding functionality completely, that would be appreciated.

**Comment by davidrothera** [comment]
This would be an awesome addition, I want to be able to remap keys both on my internal keyboard and external one but have the Fn keys left alone.

It would be awesome to either have the option to leave Fn alone altogether or to have different mapping settings per device (just for the Fn keys)

**Comment by lgarron** [comment]
Function key behaviour seems to have changed (#396 is fixed for external keyboards, and it's probably possible to hack around it for the laptop keyboard, though #397 persists), but it would still be nice if we could say "don't change any function key behaviour at all, unless I specifically override something".

**Comment by lgarron** [comment]
Still relevant. 😔

**Comment by lgarron** [comment]
Still my top source of issues with `Karabiner-Elements` when I have it enabled!

**Comment by lgarron** [comment]
Still my major pain point with `Karabiner-Elements`!
 😔

**Comment by lgarron** [comment]
Still an issue! :-(

**Comment by lgarron** [comment]
... still an issue. :-/
