### ISSUE TITLE
fallback to function key via Fn+F*, possible?

### ISSUE THREAD

**Issue by kopurando** [tekezo/Karabiner-Elements#411]
Is it possible to bind F* key to a special function by default with fallback to function key when using Fn+F*? I.e. F10 = mute, Fn+F10 = F10? I can achieve opposite behaviour (i.e. F10 = F10, Fn+F10 = mute, see screenshot below), but not the direct one. 

Pre-Sierra Karabiner was capable of both, but with Elements I can't achieve such behaviour no matter what setting I use (system wide or elements), Fn+F* does not call a function key. 
MBP Retina 2013.

Thanks for your hard work!

![image](https://cloud.githubusercontent.com/assets/6130979/20047820/69198ada-a4ea-11e6-9e34-430283f74b24.png)

![image](https://cloud.githubusercontent.com/assets/6130979/20047759/e5018748-a4e9-11e6-968b-456b77b89a5b.png)

**Comment by Stokestack** [comment]
I have the same (or maybe the inverse) problem.

I have the OS set to treat function keys as function keys by default (meaning that you need to press Fn to access the volume and so forth). If you remap one with Karabiner, the underlying function (with the Fn key) no longer works.

**Comment by maartenvandillen** [comment]
Yes me too, I have function keys set up as function keys and want F12 to be my forward delete key and fn-F12 to behave as Volume up.

**Comment by palkoc** [comment]
Me too... This issue is here since a couple of months...

**Comment by Stokestack** [comment]
As far as I remember, this problem has existed since the rewrite (first working version on Sierra).
