### ISSUE TITLE
When built-in keyboard is re-enabled after external keyboard disconnected, it use the mapping keys of external keyboard even ignore: true is set for Built-in keyboard

### ISSUE THREAD

**Issue by nmqanh** [tekezo/Karabiner-Elements#414]
I am using the new feature to Disable Built-in keyboard when external keyboard connected, it's working flawlessly. I am also setting some mapping rules for the external keyboard and ignore that for the built-in keyboard, however after the external keyboard is disconnected, if will use the current mapping keys on the built-in keyboard even though we ignored current profile for built-in keyboard.

**Comment by wassimk** [comment]
I'm curious how you're ignoring certain mappings based on keyboard? The only way I've been able to do that is create a profile for each keyboard. Then when my external is plugged in I set `selected: false` on the intenral keyboard profile and `selected: true` on the external profile.

**Comment by nmqanh** [comment]
@wassimk I don't use any mapping keys for internal keyboard, so I only set mapping for external keyboards (ignore for internal keyboard) and turn on option disable internal keyboard when my external keyboard connected.

**Comment by fatal1tyv** [comment]
Same on my external HHKB/IKBC keyboard.

macOS 10.12.2

Thanks.
