### ISSUE TITLE
Unable to use keyboard after quitting Karabiner-Elements

### ISSUE THREAD

**Issue by wwwjfy** [tekezo/Karabiner-Elements#417]
The issue only appeared after some time of usage, that after quitting Karabiner-Elements, the keyboard didn't respond to anything pressed (in a text editor, or Karabiner-EventViewer).

What I've tried:
- uninstall Karabiner-Elements
- use `appendix/eventtap` to insert a new event tap
- list all active filters (not listen only) by `CGGetEventTapList`, and kill all of them (except Siri)

None of the above works. It looks like that only Karabiner-Elements can make the keyboard work again.
I suspect some cleanup need to be done before quitting.
I'll try to dig into the source code, but I appreciate if anyone already knows what happened.

**Comment by wwwjfy** [comment]
I don't know what happened, but a recent test seems work. Closing it.

**Comment by cknd** [comment]
I still have this issue on osx 10.12.2 (16C68), Karabiner Elements 0.90.76.

Both when I quit Karabiner Elements and when I deselect the the Apple Internal Keyboard in "Devices", no more keypresses are registered (by any application including karabiner event viewer) until I start KE again or reselect the device, respectively.

**Comment by wwwjfy** [comment]
Yes, it's still happening. The problem is gone only not long after a reboot.

**Comment by codyrobbins** [comment]
This issue has been happening for a few months now for me. Explicitly quitting Karabiner disables all keyboard input and the only way to get the keyboard working again is to start Karabiner once again.

I feel like this problem may be related to #268—if the Karabiner process is being killed after a certain amount of time on the login window then it may be different manifestations of the same thing. That problem is still happening for me with the exception of the Bluetooth setup window popping up.

**Comment by F1LT3R** [comment]
Yeah I'm still getting a dead keyboard at login as well. (after locking screen is where I see it happen)

**Comment by cihanozcelik** [comment]
I have this issue as well. Quitting Karabiner Elements disables all keyboard input.

**Comment by wwwjfy** [comment]
It seems gone. I'll reopen it if it happens again.

**Comment by joshpeng** [comment]
I am suffering from this after updating to 12.1 from 11.6. Even after multiple reinstalls and uninstalls I can't fix the keyboard without KE. Any ideas?

**Comment by luarmr** [comment]
I am having the same issue here.

**Comment by 599316527** [comment]
same issue +1

**Comment by muxcmux** [comment]
Same problem here with: 12.2.0

**Comment by nealyoung** [comment]
I'm also having the same issue with 12.4.0. Any updates on this?

**Comment by KanyunCC** [comment]
My keyboards (both the internal and the mechanical keyboard) remain dead for 2 min after quitting or opening Karabiner. But then they both start working again. Not sure if they have fixed this glitch. Version 12.10.0
