### ISSUE TITLE
swap command to option not working on macOS Sierra

### ISSUE THREAD

**Issue by sunyujia** [tekezo/Karabiner-Elements#422]
when I update MBP to macOS Sierra ,swap  left command to left option not working .

**Comment by bwaresiak** [comment]
Same for me, just for the Cmd_r to Option_r

**Comment by timothycosta** [comment]
Same thing here.  External keyboard (Mac Mini 2012).  Even installing Elements interferes with Sierra's native swap function.

**Comment by reidblomquist** [comment]
Having the same issue - bit of a show stopper.
