### ISSUE TITLE
Behavior of Alt+Arrows implicitly changed in latest version

### ISSUE THREAD

**Issue by rkonopka** [tekezo/Karabiner-Elements#423]
The latest version 0.90.64 causes the Alt+LeftArrow and Alt+RightArrow keyboard sequences to have unintended mappings. Specifically, when Karabiner-Elements is running, pressing Alt+RightArrow moves the cursor to the next word in TextEdit. If Karabiner-Elements is NOT running, the command does nothing. Alt+LeftArrow moves the cursor to the previous word.

This implicit behavior is affecting specialized keyboard commands in several applications. For example, in Microsoft Office products (e.g. Powerpoint, Word), pressing Alt+Shift+RightArrow normally increases the indent level. However, with the latest version of Karabiner-Elements, pressing Alt+Shift+RightArrow changes the selection by selecting the next word starting with the current cursor position instead of increasing the indent level.

**Comment by nem75** [comment]
With v0.90.67 I cannot reproduce this behavior. Alt+Left/Right always moves from word to word, no matter if Elements is running or not.
