### ISSUE TITLE
HHKB mac function does not work with Karabiner-Elements

### ISSUE THREAD

**Issue by divinites** [tekezo/Karabiner-Elements#424]
HHKB has its own set of Shortcut keys for Mac, e.g. Fn + A = vol_down, Fn + S = vol_UP, however, after installing Karabiner, it no more works. I have to use Fn + F10 to literally mimic the F10 function of a typical Mac Keyboard.

**Comment by michalskalski** [comment]
I have HHKB PRO2, Karabiner-Elements in version 0.90.64 and macOs 10.12.1. Shortcuts mentioned by you works for me. I'm currently using only simple modifications caps_lock to left_control and right_command to right_alt. I remember that I installed driver for this keyboard before upgrading to Sierra, not sure if it is still in use.

**Comment by divinites** [comment]
oh, I did not even notice that HHKB has a mac driver, I will try it and report here later. Thanks!

**Comment by divinites** [comment]
It works! the driver matters, Thank you very much @michalskalski ! I will close the issue now.

**Comment by zshbleaker** [comment]
Hi @divinites 

Could you please share a link of the driver? I just googled for an hour and got nothing but some webpage in Japanese :( 

Thanks a lot!

**Comment by divinites** [comment]
@zshbleaker  here you are.
https://www.pfu.fujitsu.com/hhkeyboard/downloads/HHKBProMac201609.dmg

**Comment by zshbleaker** [comment]
Thank you! 

I'm using the bluetooth version of HHKB Pro 2 under the same issue. Not sure if the driver is compatible with it.
