### ISSUE TITLE
Capture and Modify Inputs over VNC?

### ISSUE THREAD

**Issue by Kelseer** [tekezo/Karabiner-Elements#425]
Hey All,

I'm trying to use a RealVNC connection to my mac mini from a windows computer, and for some reason this makes it so that the Windows Key is the new COmmand key.  I was hoping Karabiner could help, but I guess elements requires a hardware keyboard?  Is there a way to make it work with keyboard inputs over VNC?

Thanks!

**Comment by cro** [comment]
You should be able to change the keyboard bindings from the stock Keyboard
control panel in this instance.

--cro

**Comment by Kelseer** [comment]
I had hoped so, but it does not seem to have en effect. It seems to treat the key strokes form VNC and from the physical keyboard as two different things.  Same thing happens with Chrome Remote Desktop.

**Comment by jvincent-siplay** [comment]
Same problem here, would love to see this get fixed.  The "modifier keys" setting in OSX doesn't work over VNC so it would be great if Karabiner could handle this.
