### ISSUE TITLE
Excel: F2 to edit cell?

### ISSUE THREAD

**Issue by grobbins49** [tekezo/Karabiner-Elements#427]
I appreciate your creation of Karabiner Elements to support Sierra, but would really like to see a way to get the PC-like "F2" function back when using Excel on the Mac. Looks like that's not yet part of Elements. 
Thank you!

**Comment by grobbins49** [comment]
Ah, just noticed I can do this from your "Function Keys" tab. It's working. But I noticed this key remap can no longer be restricted to only when Excel is the active app. That was important (to be able to still increase brightness when outside of Excel). Maybe I'm just missing how to do that too.

**Comment by mwdiers** [comment]
App-specific key mappings have not yet been implemented in Elements.

**Comment by maartenvandillen** [comment]
@grobbins49 I have configured this behavior in Excel using another tool. It's called BetterTouchTool. Working perfectly in Sierra.

**Comment by grobbins49** [comment]
Thank you, Maarten! I'll give it a shot.

**Comment by dsuther2** [comment]
I'm also able to get this to work by mapping the F2 key to "f2" in the dropdown.  However, is there a way to map fn+F2 to 'display_brightness_increment'?  (essentially I want to flip the meaning of F2 and fn+F2)  Thanks.

**Comment by zilboris** [comment]
Could someone please point out how to make this mapping in BetterTouchTool? Have been poking around and can't figure out how it works.

**Comment by maartenvandillen** [comment]
Although this is not the right place to discuss BetterTouchTool, you could add Excel as an application to the left and then add a shortcut F2 to it that triggers another keyboard shortcut ^U.

**Comment by zilboris** [comment]
Hi, I realise this isn't the right place and appreciate your help. I can delete my comment. Unfortunately it's still not working because I'd like the Brightness key to be the shortcut, not F2. Perhaps BetterTouchTool can't do this after all?

**Comment by mwdiers** [comment]
FYI - Current versions of Excel for Mac have sane shortcuts. F2 actually edits a cell as it should.

**Comment by zilboris** [comment]
They don't when I just press the Brightness Up key. I have to press Function Brightness key to get F2 unless I deactivate all the Mac special function keys.
I'm using Excel 2016 for Mac

You didn't have to do any of this in Karabiner. Pressing Fn to get F2 is not helpful.

**Comment by mwdiers** [comment]
Got it. I don't know if BTT can do this now, but ControllerMate can. But none of the existing solutions are as foolproof as Karabiner was. It looks like Elements is about done, so let's hope we'll see work started soon on the new version of Karabiner. And let's hope Apple doesn't completely chance the API again on 10.13.

**Comment by zilboris** [comment]
Thank you for the thorough explanation. I tried the latest version of Elements today and couldn't find this functionality there either. Fingers crossed for the update and frowns at Apple.

**Comment by handcoding** [comment]
Hi, @stale. This issue is still present.

**Comment by zilboris** [comment]
Hi, @stale <https://github.com/stale>. This issue is still present.

**Comment by zilboris** [comment]
I believe this issue is still present. I don't want to give up hope that it will be addressed.

**Comment by handcoding** [comment]
@stale: This issue is still relevant.

**Comment by clemsam** [comment]
If it's really important to you, and you only want this "F2" key _NOT to be swapped_ (or very few others):  
It is nearly as simple to edit your `~/.config/karabiner/karabiner.json` as it was to edit `Private.xml`.
Just add directly after this code: `"rules": [`

    { "manipulators": [
        {"conditions": [{ "bundle_identifiers": [
                             "^type.Excel.name" ],
                         "type": "frontmost_application_if"
                       }],
              "from": { "key_code": "f2" },
              "to": [ { "key_code": "f2" } ]
    } ] },

**_Replace "type.Excel.name" with Excel's name from "EventViewer | Frontmost App."!_**  
**_KEEP " ^ " !!!_**  

This "re-mapping" to itself may look absurd, but it prevents any following f2-remaps.

**Comment by treus** [comment]
I'm using Karabiner Elements 12.1.0 - for me the following mapping worked in `~/.config/karabiner/karabiner.json` directly after `"rules":[`:
```
{
	"description": "Change F2 to control+u in Excel",
	"manipulators": [
		{
			"conditions": [
				{
					"bundle_identifiers": [
						"com\\.microsoft\\.Excel"
					],
					"type": "frontmost_application_if"
				}
			],
			"from": {
				"key_code": "f2"
			},
			"to": [
				{
					"key_code": "u",
					"modifiers": [
						"control"
					]
				}
			],
			"type": "basic"
		}
	]
},
```

It maps F2 to control-u when Excel is the front-most application, allowing to edit a cell by pressing F2. The rule even appears in the `Complex Modifications` tab after saving the json-file.

**Comment by clemsam** [comment]
[Just deleted my older answer (in front of **treus'**) as I seemingly _DID explain_ how to constrict remapping to _certain apps_, but –as I don't use Excel– was not fully aware _WHICH "initial" remapping_ was looked for. Sorry for that …]

**Comment by zilboris** [comment]
Thank you.
