### ISSUE TITLE
, to . belgian french

### ISSUE THREAD

**Issue by TonyStarck** [tekezo/Karabiner-Elements#429]
Hello, I would like reverse the , to point on my apple numérical belgian french keyboard.
I have tried with Elements but not success.
Do you have an idea?
Thanks a lot,
Tony

**Comment by rdmendo** [comment]
+1 on my french keyboards

**Comment by lazaj** [comment]
+1 for french users

**Comment by TonyStarck** [comment]
I have found the alternative keyboard maestro but it's not free ...
