### ISSUE TITLE
Features & Config Wiki

### ISSUE THREAD

**Issue by laktak** [tekezo/Karabiner-Elements#43]
Could you create a wiki(?) that lists the features of Karabiner vs Karabiner-Elements?
- supported yes/no
- sample from the Karabiner xml
- sample on how to convert them to the new syntax

At the moment it is hard to figure out what will work with Karabiner-Elements.

**Comment by talha131** [comment]
A lot of new issues on this repository are basically help questions on how to map x to y. If we had a wiki, we could easily move all answers there for future reference.

Though there is an [examples](https://github.com/tekezo/Karabiner-Elements/tree/master/examples) directory in the source code but it seems many users don't dig into in the source tree.

So yeah, a wiki would be great.
