### ISSUE TITLE
Yet another logitech mouse thread -- click becomes cmd-click after switching tabs via mousewheel

### ISSUE THREAD

**Issue by mikeage** [tekezo/Karabiner-Elements#430]
I'm running version 0.90.64, and whenever I switch tabs using my mouse's horizontal scroll wheel (MX Master; the wheel is mapped to "Navigate Between Tabs" in Logitech Options), my mouse's left click turns into a cmd-click (right click). I've unchecked my mouse under Karabiner-Elements Preferences -> Devices, but it still occurs. Tapping CMD fixes the issue, until the next time I scroll between tabs again. 

If I shut down Karabiner-Elements, this doesn't occur, so I don't think it's (exclusively) related to Logitech Options. 

If I switch tabs using Ctrl-Tab, this does not occur.

**Comment by Mmhabig** [comment]
I just posted this same issue, I should've checked here first. I'm having this exact same issue. Used to be only when I navigated multiple tabs but now it's happening with just one.

**Comment by mikeage** [comment]
FWIW, I've switched (hopefully temporarily) from Karabiner-Elements to BetterTouchTool; my most important use case is replacing the section/plus-minus key with a backtick/tilde, and BTT lets me do that.

**Comment by Mmhabig** [comment]
For me it's swapping control and command and windows keys. Will BTT do that?

**Comment by mikeage** [comment]
Don't know; didn't try. I think so...
