### ISSUE TITLE
Ctrl getting stuck

### ISSUE THREAD

**Issue by Mmhabig** [tekezo/Karabiner-Elements#432]
I have a Logitech mouse that I use the thumb wheel to navigate from browser tab to tab (Ctrl+tab / Ctrl+shift+tab), which works fine but after installing karabiner if I use that thumb feel function ctrl gets stuck and anywhere I click it's a right click. It happens sporadically, sometimes I have to navigate many tabs fast to get stuck, other times only one tab causes this behavior.

**Comment by cbrwizard** [comment]
Reverting a Caps lock from Control to Caps Lock in Apple System Keyboard preferences helped me
