### ISSUE TITLE
remap ` on 2016 mbp + sierra

### ISSUE THREAD

**Issue by ScottYelich** [tekezo/Karabiner-Elements#433]
Hi -- not sure if this is a repeat/dupe.

karabiner doesn't work on sierra ( verified, again :-) )
karabiner-elements seems to work... somewhat:

I just want to remap ` to be escape, but leave ~ as shift-`

( 1 )  It seems that if I remap the ` key, it also takes ~ along with it.  
( 2 ) The remapping in 1 as the only setting -- seems to cause the touch bar not to work in some cases such as to change the keyback lighting values.

I also then need to have a way to get a ` ... so perhaps fn-` or ctrl-` -- but those don't seem to be possible combinations with karabiner(-elements).

**Comment by johndierks** [comment]
I'm looking to remap the `grave accent` to escape, `shift + grave accent` to tilde, and `fn + grave accent` to grave accent.

**Comment by ScottYelich** [comment]
Let me know how it goes.  I think this is going to be an increasingly desired remapping as more people get the latest MBPs.
