### ISSUE TITLE
Mapping Home/End to line (not view) equivalents?

### ISSUE THREAD

**Issue by jhihn** [tekezo/Karabiner-Elements#434]
Is it possible to map Home/End on the PC keyboard to their to the line equivalents yet? If so, how?

**Comment by KAMIKAZEUA** [comment]
Same here. For macOS this option is really needed! 

![screen shot 2016-11-21 at 14 46 04](https://cloud.githubusercontent.com/assets/3391456/20483201/7f082986-aff9-11e6-8245-0d24e61408d5.png)

**Comment by KAMIKAZEUA** [comment]
With help of comment from this isuue https://github.com/tekezo/Karabiner-Elements/issues/437 
I've configured and it works on macOS.

![screen shot 2016-11-24 at 16 32 58](https://cloud.githubusercontent.com/assets/3391456/20602036/3dacfe90-b264-11e6-80a2-3d006d506e75.png)

**Comment by PaulSlocum** [comment]
Having line-based Home and End is really critical, it's one of the primary reasons I use this app.  Currently I just have Home and End mapped to modifier keys so I don't accidentally jump to the beginning and end of documents by accident.

**Comment by pmonks** [comment]
@PaulSlocum [⌘英かな](https://ei-kana.appspot.com/) at least partially works to accomplish this on Sierra.  I have home and end remapped and am no longer cursing loudly at my monitor every 10 seconds.  What I haven't figured out yet is how to map ⌘Home and ⌘End correctly (ie. to top-of-document and end-of-document, respectively).

**Comment by thorro** [comment]
@pmonks I map ctrl+home/end to home/end to achieve same functionality

**Comment by Rep2** [comment]
cmd+left_arrow/right_arrow map to line_home/line_end
