### ISSUE TITLE
Remap ¬ to | (pipe)

### ISSUE THREAD

**Issue by DavidBabel** [tekezo/Karabiner-Elements#436]
Hey !

I'm on MacOs Sierra and i can't remap the pipe ( alt+shift+L ) on the ¬ ( alt+L ), i put this in my karabiner.json : 

```
"simple_modifications": {
    "¬": "|"
}
```

But it does not work, what im doing wrong ?
Thanks !

**Comment by nashbridges** [comment]
"simple_modifications" means that only single keycode (physical key) can be mapped to another single keycode (e.g. caps_lock to escape). Support for keycode combinations is planned, but yet not implemented.

**Comment by jdorleans** [comment]
I'd like to do similar by changing the session to pipe symbol: `"§" : "|"`.
Is there any new update that enables that?
