### ISSUE TITLE
Request: How to map one key to multikeys like old time in Karabiner?

### ISSUE THREAD

**Issue by chinanoahli** [tekezo/Karabiner-Elements#437]
In the old time I can map かな key to L_Option+L_Command+Space by putting this in the profile
```
	<item>
		<name>Modify かな</name>
		<identifier>private.KanaSwitcher</identifier>
		<appendix>Map かな to Command+Option+Space</appendix>
		<device_only>
			DeviceVendor::InternalKeyboard,
			DeviceProduct::InternalKeyboard
		</device_only>
		<autogen>
			__KeyToKey__
			KeyCode::JIS_KANA,
			KeyCode::SPACE, ModifierFlag::COMMAND_L | ModifierFlag::OPTION_L
		</autogen>
	</item>
```

Can I do this in the Karabiner-Elements now?

**Comment by delphinus** [comment]
I think it cannot. Karabiner-Elements now only supports single-to-single key mapping. I use [⌘英かな](https://ei-kana.appspot.com) for that feature.

<img width="562" alt="2016-11-23 19 15 38" src="https://cloud.githubusercontent.com/assets/1239245/20558068/bdf9de64-b1b1-11e6-9489-23e37f17b10e.png">

**Comment by KAMIKAZEUA** [comment]
Thank you! This is solve issue.. https://github.com/tekezo/Karabiner-Elements/issues/434  - lol. Use another app/

**Comment by pohkit91** [comment]
This solve for #456

**Comment by chinanoahli** [comment]
Thank you! This is solve my issue.
But I think Karabiner-Elements may not so powerful that Karabiner. :eyes:

**Comment by daviesgeek** [comment]
Ditto on ⌘英かな . The app works well, but is a little hard to use since all the menus are in Japanese. Overall a really good suggestion. I can map my shifts keys to parens no!

**Comment by daviesgeek** [comment]
Update after using the app for awhile. I had to disabled it because this app types on key *down*, rather than the old Karabiner behavior of typing on key *up*. This causes a huge issue with typing capital letter :/

**Comment by derwaldgeist** [comment]
Thanks for the hint to that Japanese program. Works way better than trying to set this up in Karabiner Elements.

**Comment by AJPoulter-Soton** [comment]
Just in case anyone else gets to this page when searching how to solve this - I note that it is now possible from within Karabiner-Elements (I'm running 11.6.0 at the time of writing) using the "complex modifications" tab - and adding the "PC-Style Shortcuts" from here: https://pqrs.org/osx/karabiner/complex_modifications/ 

![Screenshot](https://user-images.githubusercontent.com/28599916/36666656-3ad441d6-1ae3-11e8-9d13-e32cff5e28fb.png)

You can then either enable the "PC-Style Home/End" rule if you want "Cmd + Left_Arrow" / "Cmd + Right_Arrow" behaviour; or "Home key to the beginning of the line" / "End key to the end of the line" if you want Control + a / Control + e...
