### ISSUE TITLE
Swap Section (§) and Less-Than (<)

### ISSUE THREAD

**Issue by nilsi** [tekezo/Karabiner-Elements#439]
I'm using a Swedish 105 keys WASD keyboard. Everything works well beside that my Section and Less-Than keys are swapped. I found that my Section key is called "non_us_backslash" but I can't find what my Less-Than key is. Does anyone know how I could swap these two? 
Thanks for a great tool!

**Comment by nilsi** [comment]
Oh I found it! Then name for my Less-Than was grave_accent_and_tilde

**Comment by hecbecme** [comment]
Works for me!

**Comment by duckie** [comment]
Works great, but unguessable without this issue.

**Comment by angusin** [comment]
Works for me! I was struggling hard with this. Thank you so much

**Comment by themightyoarfish** [comment]
where can i read which identifier corresponds to which key?

**Comment by MuhammedZakir** [comment]
> where can i read which identifier corresponds to which key?

Have you tried Karabiner-EventViewer?

**Comment by esaruoho** [comment]
Just in case it helps, here's a screenshot for how to get this going with Finnish Apple Numeric Keyboard (FN -> Insert mapping as a bonus). 
This should really be discoverable by pressing < and > in the "From key" dropdown menu. Instead, nothing.
Thanks for posting the solution, @nilsi and @mattiasjosefsson .

<img width="842" alt="Näyttökuva 2022-6-12 kello 22 42 55" src="https://user-images.githubusercontent.com/4966687/173250477-4ff413b4-de83-4583-9cb5-648f2f936686.png">

**Comment by dbirdz** [comment]
I have no clue who to tag here but this is a bug. I have no modifications whatsoever active, and as soon as I start Karabiner Elements, it swaps these two keys. I'm working with a Swiss keyboard, so it seems EU centered.

**Comment by knutanderss** [comment]
Same bug on Norwegian layout

**Comment by LoicUV** [comment]
Same on French layout `@` and `<` are swapped, with no modifications enabled : 

<img width="1101" alt="Image" src="https://github.com/user-attachments/assets/dabf5755-1041-436e-ab26-2d01036c75b5" />

**Comment by nejmeijer** [comment]
Given that this issue has been closed by the original reporter long ago, I suggest that everybody stops commenting here, as comments under closed issues will likely not reach the developer and therefore be missed by efforts to fix it.

If you – like @dbirdz – believe you ran into a bug within KE, I suggest you search for similar _open_ issues first (Have a look at #4295, which might be related to this) and post there. If you really have a new issue that has not been reported in a currently open issue, please instead create a new issue to discuss it.

We are massively understaffed and underfunded to deal with the current backlog of issues, so we hope users can help us keep the existing issues actionable and tidy to the best of their ability too.
