### ISSUE TITLE
hidd CPU usage

### ISSUE THREAD

**Issue by taburet** [tekezo/Karabiner-Elements#44]
After installing Karabiner I noticed that `hidd` process CPU usage is between 4-6% while typing. That is a pretty high number if you consider battery life.

**Comment by tekezo** [comment]
It seems hidd has higher CPU usage on macOS Sierra regardless of Karabiner-Elements.
(I confirmed same hidd CPU usage after Karabiner-Elements has been uninstalled.)

In any case, unfortunately, there is no alternative way to grabs keyboard input events in macOS Sierra. Thus, we cannot avoid this issue.

**Comment by taburet** [comment]
Checked it w/o Karabiner-Elements, CPU usage still high. That is sad, as far as I remember hidd was not that much CPU hungry in old vanilla _OS X_.

Sorry for false alarm. Closing.
