### ISSUE TITLE
Windows style (Copy, Paste, Undo, etc...)

### ISSUE THREAD

**Issue by samboman** [tekezo/Karabiner-Elements#441]
I used Karabiner before Sierra, and the setting to add Windows-style shortcuts (both CTRL + C and CMD + C resulted in COPY)...
Is there a way to do this in Elements? If I remap CTRL to CMD, I will get a problem when I'm switching to Windows in Parallels. When I hit CTRL in Parallels it is mapped to Win-button.

Any solution?
Please advice me.. :)

**Comment by jritsema** [comment]
Nope, not yet.

For now, you can add a DefaultKeyBinding.dict text file as described [here](https://gist.github.com/jritsema/f6addd7364316e55dc8672ff14b79d31#file-defaultkeybinding-dict) but note that this works for cocoa apps (e.g., native) but not other types of apps (like electron - atom, hyper, etc).

good luck!

**Comment by adyshimony** [comment]
Is there any update on this?
