### ISSUE TITLE
karabiner element stop working

### ISSUE THREAD

**Issue by hungnl** [tekezo/Karabiner-Elements#446]
After the latest update, my Karabiner stop working on macbook pro 2015. I simply want to swap fn and control button.
Is there any way for this to work or to revert back to previous version?

**Comment by alan-tai** [comment]
Same here. The log shows this every second:
`[2016-11-28 11:45:40.058] [warning] [grabber] event_manipulator_ is not ready. Please wait for a while`

**Comment by aeantipov** [comment]
+1 https://gist.github.com/aeantipov/efc780b5a4a24cb105a20637e4b13c68

**Comment by ZeeArts** [comment]
Same here. I had to downgrade to 0.90.66.

**Comment by hungnl** [comment]
@ZeeArts: Can you tell me how to downgrade it ?

**Comment by ZeeArts** [comment]
All the time, when a new update is coming out, i save it per download. So i have the preversion on next update to can roll back. If there is an issue, i just install the older one again.

**Comment by IngoHeimbach** [comment]
I have downgraded Karabiner Elements in the following way:

1.  Get the current [boost version](http://www.boost.org/users/history/version_1_62_0.html)
    extract it and copy the `boost` directory to `/opt/local/include/boost`

2. Get the Karabiner source repository, check out an older version and compile:
```bash
git clone https://github.com/tekezo/Karabiner-Elements.git
cd Karabiner-Elements
git checkout c24b663  # commit of version 0.90.66
make
```
After that, you can remove your current installed Karabiner Elements and install the older version from the dmg file produced by the make step.

**Comment by lattenwald** [comment]
Same for me. Had CapsLock remapped to F19 and using it as a shortcut for keyboard layout switch. Downgraded to 0.90.66 for now.

**Comment by PhiloNL** [comment]
Same here

**Comment by PhiloNL** [comment]
Download previous version here:
https://pqrs.org/osx/karabiner/files/Karabiner-Elements-0.90.67.dmg

**Comment by gamesbrainiac** [comment]
I've had the same issue.

**Comment by yangbryant** [comment]
Download previous version here:
https://pqrs.org/osx/karabiner/files/Karabiner-Elements-0.90.64.dmg

**Comment by DHaacke** [comment]
Stopped working for me and my Logitech keyboard again, too. 
Back to 0.90.64 and we're cooking with gas.

**Comment by Username-Bacon** [comment]
After reinstalling Karabiner-Element using the latest installer from the main page, it seems to work fine.
Try reinstalling the most current one

**Comment by DHaacke** [comment]
I did exactly what the previous comment said (installing from the installer on the main page as opposed to upgrading), and things are working fine!

**Comment by mgol** [comment]
@Username-Bacon Your workaround works for me but only until the system restart. Then it's back & I have to reinstall again.

**Comment by Username-Bacon** [comment]
@mgol Yeah. You are right. After restarting system, it stops working again. Maybe the only answer to this bug is to either downgrade to .66 version or wait until they fix this bug.

**Comment by Username-Bacon** [comment]
@mgol Acutally, after waiting for the mac to boot completely, it started to work just fine. Maybe I was expecting too much from it and did not wait for it to fully function.

**Comment by uniquejava** [comment]
Sign, not work for my logitech K270,  all the keys on the keyboard stopped working 
If `modify events from USB device` is unchecked, all the keys start to work..

but then I cannot swap my windows and alt key(my only requirement).

Maybe I need to downgrade my mac to Capitan.

**Comment by ToastyKen** [comment]
Okay I figured out my case at least.  As per a comment in https://github.com/tekezo/Karabiner-Elements/pull/686   Karabiner started using ~/.config/karabiner to write its config in v0.90.71.

In my case, my ~/.config directory was owned by root, with no write permissions for my user.  I used:

sudo chown $USER ~/.config

and that fixed it!
