### ISSUE TITLE
The caps-lock key is wrong while the karabinder-elements is running...

### ISSUE THREAD

**Issue by wysaid** [tekezo/Karabiner-Elements#449]
It's just not working after updating to the new version.

**Comment by wysaid** [comment]
I'm using a usb keyboard for my macbook, the builtin keyboard of my macbook is OK, but the usb keyboard's caps-lock key doesn't work……

**Comment by wysaid** [comment]
……
It's OK, after reinstalling the newest version.

**Comment by ikovalisko** [comment]
For me, only downgrade to v0.90.66 helped. See #448

**Comment by pilot34** [comment]
yes, after  reinstall USB-keyboard's  "caps lock"  returns to work

**Comment by kylecrawshaw** [comment]
Maybe this should be closed as a dupe of #448? There appear to be lots of reported issues for the same reason. This may be confusing and difficult to track

**Comment by wysaid** [comment]
OMG, after a reboot the same problem came again……
Please fix this bug. Thanks.

**Comment by wysaid** [comment]
@_@ I have to downgrade, too.

**Comment by wysaid** [comment]
v0.90.66 is no more working today.
See: ![http://i.imgur.com/uMF27nn.png](http://i.imgur.com/uMF27nn.png)
It's just OK for the last few days.😅
And I have to upgrade to the newest version, but I see the issue #467 saying the same problem is still existing. Please fix~
