### ISSUE TITLE
Configuration Format

### ISSUE THREAD

**Issue by laktak** [tekezo/Karabiner-Elements#45]
Would it be possible to use [Hjson](http://hjson.org) as a configuration format instead of plain JSON?

Hjson avoids a lot of mistakes people make when editing JSON. It is also very lightweight and can be converted to JSON by a tool (so you don't have to change your config logic).

**Comment by justinmayer** [comment]
Presumably there will eventually be a user interface for configuring Karabiner Elements, so I don't think the minor JSON/HJSON differences are worth spending time on. I'd rather have @tekezo focus on higher-priority features.

**Comment by eugenesvk** [comment]
Agree, also allows to use comments (very helpful in my previous .xml file)!
and @justinmayer user interface doesn't help at all, all the custom editing is done via manually editing the file, UI is only for enabling/disabling custom keybinds. Also, given that it's a minor difference, should it not take little time to implement?

**Comment by justinmayer** [comment]
@eugenesvk: The user interface definitely helped me — I never once had to manually edit the previous XML file.

> Also, given that it's a minor difference, should it not take little time to implement?

If I had a dollar for every time someone said, "This should be easy. Should only take a few minutes."

Never works out that way.

**Comment by laktak** [comment]
@justinmayer good for you. I've been editing the private.xml config since it was still called KeyRemap4MacBook. You'd be surprised at how powerful this tool is.

**Comment by eugenesvk** [comment]
@justinmayer  
> I never once had to manually edit the previous XML file.

good for you, though I don't understand why you'd offer a solution for an issue you have no experience with. No, GUI config can't do like 90% of what Karabiner can, hence the request to make the config format more user-friendly.

Don't want to argue with your "a few minutes" strawman, will just leave it up to **tekezo** to weigh the traid-offs and decide if he could fit this format change in his development pipeline.

**Comment by talha131** [comment]
If we had hjson, the usage/purpose/explanation of example.json like [this one](https://github.com/tekezo/Karabiner-Elements/pull/97#issue-178630148) would have ended up right in the json itself.

**Comment by petonic** [comment]
I'm thinking about crufting together a scaffolding CLI pipeline that allows the use of  a template and then YAML code to make it a bit more maintainable.  I didn't like the old XML way of storing from the old Karabiner, but at least you could put comments in it.  Thoughts?
