### ISSUE TITLE
Caps Lock is ignored.

### ISSUE THREAD

**Issue by Lerg** [tekezo/Karabiner-Elements#452]
After an update, Caps Lock key stopped working. It produces no keycode. I have it set up as F19 to switch keyboard layouts.

Reinstalling and rebooting didn't help.

**Comment by max107** [comment]
stopped working after update to 90.67

**Comment by kylecrawshaw** [comment]
@max107 I'm seeing that exact same error in my logs right after the update to 90.67 as well

**Comment by zealson** [comment]
when I have updated to 0.90.67, the caps lock isn't working well any more...so I have to downgraded to the 0.90.64

**Comment by max107** [comment]
@zealson Where i can get link to 90.64?

**Comment by max107** [comment]
@tekezo where is can download 0.90.64 version?

**Comment by DHaacke** [comment]
Having the same Caps lock issue. Verified working when Karabiner unloaded. Just started with 67. Thanks!

**Comment by a-triant** [comment]
I don't have any warning in log, but my Caps Lock also stop working after computer sleep.

**Comment by tgressly** [comment]
Foud the working version here:
https://pqrs.org/osx/karabiner/files/Karabiner-Elements-0.90.64.dmg

**Comment by thymara** [comment]
MACOS Sierra 10.12.1 (16B2555) I have to force quit karabiner_grabber to get my caps lock to work. Equally interesting is that even using force quit none of the karabiner processes actually stop

**Comment by Lerg** [comment]
Updated to the new version. Caps lock is now working again.

**Comment by zealson** [comment]
It's still not working,why close this issue,I've updated to 0.90.68, on macOS Sierra  10.12.1,the caps lock feature and LED all can't working normal again,I've to downgraded to 0.90.64 second time...

**Comment by Lerg** [comment]
zealson, it's working for me, there is no issue now on my end, so it's closed. I also have the latest Sierra.

**Comment by zealson** [comment]
I'm sorry and don't know why I still be in this problem,today morning I saw your reply said it's caps lock is working,then I've updated it from 0.90.64 to 0.90.68,then I found it's not working,and the problem is always here,I also have rebooted my mac ,and caps lock feature and led can't working well with the lastest karabiner,  finally I have downgraded 0.90.64,OK,all things going on right way!

**Comment by vcraescu** [comment]
On 0.90.79 caps locks mapping doesn't work anymore. I have mapped to left-control but even so I works as caps lock.

**Comment by nathanbirrell** [comment]
Still not working for me on Sierra 0.90.92. 
@Lerg are you sure this should be closed?

**Comment by Lerg** [comment]
You can open a new issue. This should remain closed, because it's working for me, I won't be able to contribute to it.
