### ISSUE TITLE
Vi Mode coming to Elements?

### ISSUE THREAD

**Issue by JesseLeite** [tekezo/Karabiner-Elements#453]
Are any of the Vi mode features coming to elements, and if so is there a Karabiner-Elements roadmap/timeline published somewhere?

I rely on this one pretty heavily:

![](https://beemapp.s3-eu-west-1.amazonaws.com/f6c729db-43f6-4f32-8a8d-6c046299b920.jpg)

...and then I have Seil map my `CAPS` key to `Command_R`.  I realize everyone has their own preferences when it comes to Vim bindings and emulation, but that's what is so beautiful about Karabiner :)

**Comment by JesseLeite** [comment]
Does anyone know if this is possible via manually updating configuration file?

**Comment by wxmtech** [comment]
Not now, as far as I’m concerned. I still have to use another build of the app to get hyper key function.

**Comment by JesseLeite** [comment]
Found [this gist which uses a Hammerspoon script along with Karabiner-Elements] to bring my beloved Vi mode back to MacOS Sierra 😁 

It's not ideal, as it's way more config than we're used to with the old Karabiner, but works well for now.
