### ISSUE TITLE
Karabiner-Elements Stops Working After Re-boot

### ISSUE THREAD

**Issue by jinkerp** [tekezo/Karabiner-Elements#454]
After installing, Karabiner-Elements works.  But after the computer is shutdown and rebooted the next day it doesn't work.  The initial screen appears, and it'is set to start at login but it doesn't work. To get it to work, the package must be reinstalled. Any ideas on a workaround. This is on a 2016 macbook pro with Sierra.

**Comment by MikhailTNY** [comment]
This is most likely related to this issue: https://github.com/tekezo/Karabiner-Elements/issues/448

It's a bug in 67, downgrading to 66 fixes it. I had the same issue as you did.

**Comment by jinkerp** [comment]
Thanks. Will go to 66.
