### ISSUE TITLE
Ctrl+Shit+Power *still* doesn't work

### ISSUE THREAD

**Issue by kubofonista** [tekezo/Karabiner-Elements#455]
Version 0.90.67 fixed this issue on built-in keyboard.
However it is still not working with external original Apple Bluetooth Keyboard.

**Comment by zbikmarc** [comment]
Same issue here but with original usb keyboard with numeric keypad.
OS X Sierra and karabiner-elements 0.90.67

**Comment by vaxXxa** [comment]
```json
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "caps_lock": "left_control"
            },
            "standalone_keys": {
                "left_control": "escape"
            }
        }
    ]
}
```
With this config I have the same issue: can't use ctrl+shift+power or cmd+option+power

**Comment by vaxXxa** [comment]
Oops. Ctrl–Shift–Power works well, but Ctrl–Shift–Eject or Option-Command-Eject doesn't. As I see in Karabiner-EventViewer, Eject isn't tracking by Karabiner. Am I right?

**Comment by jrrs** [comment]
same.  i have a mac mini with an apple usb+numpad keyboard.  it has eject.  with K-E running, i can't Ctrl-Shift-Eject to lock screen.

Eject shows in event viewer as "SysKey(Up|Down)" "0xE" and has no Name.

is this as simple maybe as assigning a Name to the key?

**Comment by vomchik** [comment]
Ctrl–Shift–Eject doesn't work on iMac 2015!

**Comment by brianweber13** [comment]
This problem has been well documented in #46 and #89 . Can we close this issue?

**Comment by JesseLeite** [comment]
CTRL-💩 -POWER?
