### ISSUE TITLE
Unable to fully uninstall

### ISSUE THREAD

**Issue by trevorllarson** [tekezo/Karabiner-Elements#459]
I have attempted to uninstall the program, but I keep getting the "Update Available" dialog popping up every so often and I can find no reference to it on my machine.

**Comment by brkattk** [comment]
Same here

**Comment by tekezo** [comment]
Use uninstaller.
https://github.com/tekezo/Karabiner-Elements/blob/master/usage/README.md#uninstall-karabiner-elements

**Comment by trevorllarson** [comment]
That is what I used to uninstall it in the first place. I am still receiving the update prompts, and I have searched across my machine for any reference to 'karabiner' and 'elements', and can find nothing.

**Comment by deontologic** [comment]
This is a truly broken piece of software. Not only does it break on every macos update, the un-installer doesn't even work!

If it's not just a small minority experiencing these issues, there should be **explicit** warnings on your github page and website.

**Comment by trevorllarson** [comment]
I do not agree that this should be closed, as I am now looking at the only way for this program to be removed from my computer is to essentially do a fresh OS install. Not looking to whip my system, just to get one program off of it.

**Comment by tekezo** [comment]
I cannot reproduce this issue.

If reinstall Karabiner-Elements and run uninstaller does not uninstall Karabiner-Elements,
execute this command in Terminal and show me the result.

```shell
sudo '/Library/Application Support/org.pqrs/Karabiner-Elements/uninstall.sh' 
```

**Comment by trevorllarson** [comment]
![screen shot 2017-01-31 at 8 55 49 am](https://cloud.githubusercontent.com/assets/13206006/22469887/1669892a-e793-11e6-99ed-b950f950ebd1.png)

**Comment by trevorllarson** [comment]
Will keep this updated on next boot

**Comment by tekezo** [comment]
Thank you for information.
It's strange that It seems there are no error in uninstallaion.

Could you run these commands in Terminal?

```shell
ls '/Library/Application Support/org.pqrs/Karabiner-Elements'  
sudo rm -fr '/Library/Application Support/org.pqrs/Karabiner-Elements'
```

If the update dialog still pops up, I guess there are other updater remains which is not installed from package.
Did you get Karabiner-Elements source code and built it by yourself?
If so, please remove the source code.

**Comment by trevorllarson** [comment]
Ran both, first returned 'No Such File or Directory', second: no response. Will continue to keep you posted here! Thanks for keeping with this ticket.

**Comment by tekezo** [comment]
OK.
Karabiner-Elements files which are installed from package seems to uninstalled successfully by the uninstaller.

The "Update Available" dialog might be shown by another apps.

Is your popup is like this?

![170201-0001](https://cloud.githubusercontent.com/assets/659178/22496087/33bcfeba-e88a-11e6-9f16-9fb24a90dd04.png)

------

If so, open Console.app while the popup is shown, and then filter by "Karabiner-Elements".

![170201-0002](https://cloud.githubusercontent.com/assets/659178/22496164/d6ea437c-e88a-11e6-8aee-c51f86278e09.png)

------

Double-click the process to open dialog and choose "Open Files and Ports".
The first item is which you have to delete.

![170201-0003](https://cloud.githubusercontent.com/assets/659178/22496185/0d48a1fc-e88b-11e6-9cea-ef2c199af18e.png)

**Comment by tekezo** [comment]
I updated the instruction because I mistook the application name.
(Console.app -> Activity Monitor.app)

**Comment by trevorllarson** [comment]
So it does appear that upon my most recent boot that I am no longer seeing the update request. I can't say which command was the one to solve it unfortunately. Thank you for sticking with this! I really appreciate it! I apologize for being a little short with you on the subject.

**Comment by nelsonblaha** [comment]
I feel like I'm having this issue now. I messed with my left command and left arrow commands in Karabiner, and now no amount of remapping or misc/uninstall seems to restore my left arrow key. It works sporadically.

**Comment by egorvinogradov** [comment]
@tekezo Can my issue with regular Karabiner be related to ths?i Pleasetake a lookhttps://github.com/tekezo/Karabiner/issues/844

**Comment by RowanG1** [comment]
Solution: Close Karabiner by clicking the Karabiner app icon at top right of screen (Apple menu bar), and selecting "Quit". Then drag the Karabiner icons in the applications folder (in dock) to trash.

**Comment by JediLuke** [comment]
I am furious. I uninstalled this software at least a month ago, have had multiple reboots and it was still running in my status bar! This is like a malware

**Comment by fbbfnc** [comment]
I was able to solve my issue following these steps to delete remaining processes in the Activity Monitor. Karabiner is great, but seems like a malware lol

> OK.
> Karabiner-Elements files which are installed from package seems to uninstalled successfully by the uninstaller.
> 
> The "Update Available" dialog might be shown by another apps.
> 
> Is your popup is like this?
> 
> ![170201-0001](https://cloud.githubusercontent.com/assets/659178/22496087/33bcfeba-e88a-11e6-9f16-9fb24a90dd04.png)
> 
> If so, open Activity Monitor.app while the popup is shown, and then filter by "Karabiner-Elements".
> 
> ![170201-0002](https://cloud.githubusercontent.com/assets/659178/22496164/d6ea437c-e88a-11e6-8aee-c51f86278e09.png)
> 
> Double-click the process to open dialog and choose "Open Files and Ports".
> The first item is which you have to delete.
> 
> ![170201-0003](https://cloud.githubusercontent.com/assets/659178/22496185/0d48a1fc-e88b-11e6-9cea-ef2c199af18e.png)

**Comment by Vadorequest** [comment]
Running `sudo '/Library/Application Support/org.pqrs/Karabiner-Elements/uninstall.sh'` worked for me.

Note that I previously tried to remove it manually by simply moving the app to the bin and it didn't work, I also killed all Karabiner-* processes before running this command.

**Comment by brunojcm** [comment]
I had a problem here for many years, no matter what I did, this is the status:
```sh
brunojcm-macbook:~ root# kextstat | grep pqrs
  176    0 0xffffff7f84cb8000 0x7000     0x7000     org.pqrs.driver.Karabiner.VirtualHIDDevice.v040700 (4.7.0) 9E381717-2EB2-374E-974E-F102E033EE46 <52 6 5 3 1>
```

Even after following every uninstall guide I could find still:
```sh
brunojcm-macbook:~ root# find / -name '*Karabiner*' -print
/Library/StagedExtensions/Library/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.kext
/Library/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.kext
/Library/LaunchDaemons/org.pqrs.Karabiner.load.plist
```

Just ran here, after restarting in recover mode and `csrutil disable` (don't forget to enable again if you do that!):
```sh
brunojcm-macbook:~ root# kextunload /Library/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.kext
brunojcm-macbook:~ root# rm -rf /Library/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.kext
brunojcm-macbook:~ root# find / -name '*Karabiner*' -print -delete
```

I'll reboot now and it seems it's finally gone. What a journey.
