### ISSUE TITLE
Eject key is not available for mapping

### ISSUE THREAD

**Issue by martin-weiser** [tekezo/Karabiner-Elements#46]
As far as I can see I am not able to map the 'pause' key to the 'eject' key.
Previously I mapped the 'pause' key to the 'power' key for my PC keyboard to be able to lock my screen using the keyboard (control-shift-power) but this does not work (although the mapping seems to work since the 'pause' key does not produce a beep anymore).
My guess is that the new Karabiner-Elements emulates a Mac keyboard where it thinks an 'eject' key is present instead of a 'power' key so the keyboard shortcut  must be  e.g. control-shift-eject to lock the screen.
Unfortunately Karabiner-Elements does not allow 'eject' in the configuration.

Thanks for all the hard work!

**Comment by goldenlove** [comment]
same problem here... hope for support or new version update....

**Comment by tgressly** [comment]
+1

**Comment by tgressly** [comment]
Also, what I experienced is that when Karabiner Elements are running, pressing a letter key no longer selects an app in grid view of a docked folder. I think this behaviour is related to the nonresponsive eject key somehow. Hope this information helps to track down the issue.

**Comment by gmacon** [comment]
I have a Code keyboard with an "Eject" sequence when it's in Mac mode. The ctrl+shift+eject combination to lock the screen isn't working for me either, but I get this sequence in the event viewer when I hit the combination:

```
eventType:FlagsChanged    code:0x38       name:Shift_L         flags:Shift                              misc:characters:    
eventType:FlagsChanged    code:0x3b       name:Control_L       flags:Shift Ctrl                         misc:characters:    
eventType:SysKeyDown      code:0xe        name:                flags:                                   misc:
eventType:SysKeyUp        code:0xe        name:                flags:                                   misc:
eventType:FlagsChanged    code:0x38       name:Shift_L         flags:Ctrl                               misc:characters:    
eventType:FlagsChanged    code:0x3b       name:Control_L       flags:                                   misc:characters:    
```

**Comment by Username-Bacon** [comment]
So currently, there's no way to use eject key. Right?

Also volume controls on my first gen apple wireless keyboard does not work like the eject key on other apple keyboards

I guess keys that only has certain functions (like mute, eject, volume up) does not work with karabiner

**Comment by martin-weiser** [comment]
It looks like in the latest releases remapping a key to the power key does work now. At least I can map the 'pause' key to 'power' and then use 'ctrl'+'shift'+'pause' to lock my screen.
This solves the issue for me ... great work!
But as far as I can see the 'eject' key is still not available so I will leave this issue open for now.

**Comment by baskerville** [comment]
The *README* states that changing the *eject* key is not possible due to *a limitation of macOS* and yet I can remap that key with [PowerKey](https://github.com/pkamb/PowerKey)…

**Comment by chrisfsmith** [comment]
Another option for people that miss using ⇧⌃⏏ to sleep the display, you can use this [AppleScript](https://gist.github.com/chrisfsmith/1c73320ab763de61e5b70e9d56928f9a) with a utility like [FastScripts](https://red-sweater.com/fastscripts/) to map it to a global shortcut (I use ⌃⌥⌘⌫).

I have ⌃⌥⌘ mapped as hyper using https://github.com/tekezo/Karabiner-Elements/pull/170.

**Comment by reesd** [comment]
Just wanted to point out that several issues were closed and pointed here for a more basic problem than mapping eject. Karabiner Elements actually completely breaks the eject key. So it can't even be used normally anymore once Karabiner Elements is started.

**Comment by a7madgamal** [comment]
this is basically why I installed this app, this button is just useless and I wanted to do something useful with it!

**Comment by rodalpho** [comment]
The Powerkey app successfully remaps the power/eject key on Sierra. This works fine in 10.12.4. It definitely isn't impossible, although of course I don't know how Karabiner-elements works internally so this method may not be available to the developer.

Powerkey is open-source, so devs can take a look at how they did it and determine if it's applicable to Karabiner-elements also.

https://pkamb.github.io/PowerKey/

**Comment by eshill** [comment]
The Powerkey app not working on my imac

**Comment by rodalpho** [comment]
Works fine for me. I compiled it myself in Xcode.

Possibly your imac's keyboard is sending a different keycode with the eject/power key? I'm using a DAS keyboard mac edition myself.

**Comment by valbaca** [comment]
My Macbook Pro's built-in power button works, but the eject button on my Apple bluetooth wireless keyboard is **not** working while Karabiner-Elements is running. This blocks me from doing the Ctrl-Shift-Eject shortcut to turn off my monitor & lock my screen.

With Karabiner-Elements quit, Event viewer shows:

SysKeyDown 0xe
SysKeyUp 0xe

when I press the bluetooth keyboard's eject button.

**Comment by JesseLeite** [comment]
`SHIFT-CTRL-EJECT` and `ALT-CMD-EJECT` both put display/computer to sleep.  However, neither work when Karabiner-Elements is running.  I'm assuming it's related to this issue?  😞

**Comment by nriley** [comment]
Another option I discovered for control-shift-eject is to map a key to "power"; holding it down for about a second will also sleep the display.

**Comment by valbaca** [comment]
**This appears to be resolved as of 0.91.16**

Ctrl+Shift+Eject turns off the monitor
Cmd+Opt+Eject puts to sleep

Can others verify?

**Comment by brianweber13** [comment]
Works for me after Today's update

**Comment by nriley** [comment]
Verified — ⇧⌃⏏ works for me too on 0.91.16.

**Comment by JesseLeite** [comment]
Hmm.  Power button works for me on macbook keyboard, but eject key on external apple keyboard doesn't seem to work.  Am I doing something wrong?

**Comment by chrisfsmith** [comment]
@JesseLeite I see the same, works for builtin keyboard, but not external.

**Comment by leocrespo** [comment]
Where exactly is the EJECT key in this dropdown? How can one possibly map the EJECT key if it's not on the list? 

<img width="584" alt="karabiner-elements preferences 2017-09-19 at 3 32 16 pm" src="https://user-images.githubusercontent.com/1483902/30618530-ce7ee916-9d4f-11e7-8b6f-1a8b38dee603.png">

**Comment by JesseLeite** [comment]
Well firstly, the mentioned display/computer sleep combinations (Ctrl+Shift+Eject and Cmd+Opt+Eject) aren't karabiner mappings.  They work without Karabiner, but not when Karabiner is running (or at least not on an external keyboard now since a recent patch).

But as far as mapping eject, you can only map a key TO eject:

![](http://b3.ms/KkdA34pzn3Jq)

**Comment by rodalpho** [comment]
Right, this issue is _NOT_ resolved because I still cannot map the eject key on my keyboard to anything. 

Note that Powerkey (linked above) still works perfectly fine in High Sierra. I map it to F13 in Powerkey, then use that mapping elsewhere.

**Comment by useybrain** [comment]
Hi. How to map eject key on normal imac keyboard to go sleep mode (long press)? Anybody resolved this problem?

**Comment by dk0r** [comment]
For both versions `11.1.0` and `11.1.8-beta`, I have no `eject` option present under 'Media controls'. 

Late 2014 iMac
Magic keyboard (v2) 
10.13 High Sierra

**Comment by rodalpho** [comment]
We all know Powerkey works. I posted the link back in March. We want to use Karabiner to do this, that is why this issue exists.

**Comment by useybrain** [comment]
I just want to remap my eject key from imac to put sleep monitor or long press to sleep computer!

**Comment by AlexeyGara** [comment]
A simple way for enable eject key for remap is turn-off (remove):
`"not_from": true`
and turn-on (add):
`"type": "consumer_key_code"`
for eject key in **simple_modifications.json** file in application package content.

**Comment by PierBover** [comment]
Thanks @AlexeyGara that did it for my Magic Keyboard 2.

Why isn't this enabled by default? I'm going to do a PR.

**Comment by AlexeyGara** [comment]
Maybe just put it in app package
[simple_modifications.json.zip](https://github.com/tekezo/Karabiner-Elements/files/1670567/simple_modifications.json.zip)
Are you sure that you looking in Karabiner-Elements.app package?
![2018-01-28 00 40 30](https://user-images.githubusercontent.com/7922564/35476765-a18f9792-03c6-11e8-9a17-14d6edc24abf.png)

**Comment by gemedet** [comment]
@PierBover you might be able to do a PR on [this file](https://github.com/tekezo/Karabiner-Elements/blob/5b0856ea01b640da7d196485c71ee0cfb0563b48/src/apps/PreferencesWindow/PreferencesWindow/Resources/simple_modifications.json#L695).

@AlexeyGara do you get both keydown and keyup in the EventViewer for the remapped eject key?

**Comment by PierBover** [comment]
Thanks @gemedet for some reason I didn't find the file when searching the repo. PR done.

**Comment by useybrain** [comment]
> Finally it should be:
> { "name": "eject", "type": "consumer_key_code" },
 This is working. But need comand to put screen sleep and comand to put computer sleep (need two commands for diferent computers)
Thx a lot

**Comment by tltz** [comment]
I just want to DISABLE the eject key - which was available in the old version. Can't seem to get it done in Karabiner Elements.

**Comment by jams2** [comment]
Hey @tltz , try this. I can't test with the eject button (mine does nothing by default - removed optical drive), but got it to disable other keys.

In the file ~/.config/karabiner/karabiner.json, under rules, add the following:

`
{
	"description": "Disable eject key",
	"manipulators": [
		{
			"from": {
                                    "consumer_key_code": "eject",
                                    "modifiers": {
                                        "optional": [
                                            "any"
                                        ]
                                    }
			},
			"to": [
				{
					"key_code": ""
				}
			],
			"type": "basic"
		}
	]
}
`
then run:

launchctl kickstart -k gui/`id -u`/org.pqrs.karabiner.karabiner_console_user_server


The key (ha) to getting at the Eject key is to reference it with "consumer_key_code" instead of "key_code".

**Comment by tltz** [comment]
Joshua!
Thank you so much for getting this to me.
I have to apologize though I can’t figure out how to find the file you are talking about under rules. If you see the screengrab attached, I only get three options and another to import rules from the web. I can’t even enter any rules manually.
Can you let me know how to add the one you have written? Honestly if this works, I will be SOO happy!
Thanks,
T



••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
Tory Zimmerman
Videographer | Editor | Photographer
The Hospital for Sick Children | Creative Services Studio

Direct Line: 416 813 8932  Customer Service: 416 813 6682
S114-555 University Avenue, Toronto ON, M5G 1X8

**Comment by jams2** [comment]
@tltz no problem. This is easier if you're handy with the CLI but we'll avoid it as much as possible.

First you'll need to enable viewing hidden files in finder. There's a guide here:
https://ianlunn.co.uk/articles/quickly-showhide-hidden-files-mac-os-x-mavericks/ 
If the keyboard shortcut solution doesn't work, use the next option, just be sure to type the commands in the terminal exactly as given.

Then, from your home location in finder, navigate to .config/ (note the leading '.', all the previously hidden files/folders will be slightly greyed out), then the karabiner folder.

In .config/karabiner/ open up karabiner.json by right click > open with > text edit. 
Scan down to ~ line 16, where it should say '"rules": ['. 
This is a list of rules, each one identified with the outermost set of curly braces '{ }' and separated by commas. The indentation gives you a visual representation of the grouping. 
You should see whatever rules you already have configured from the GUI.

Insert a new line after `"rules": [`,
go copy the rule from https://gist.github.com/jams2/923ee8bce85e8fd5ee887611ecdc02a6
and paste it in. It should look pretty similar to the other rules already there.

Important: if you insert it as the last rule, or it is the only rule, don't put a comma after the closing curly brace `}`. If it has rules following it, add the comma `},`.

Once it's in, save and close the file. Then you'll need to restart karabiner to reload the rules, either by closing from the menu bar icon and opening again from launcher, or by typing the following into the terminal:

``launchctl kickstart -k gui/`id -u`/org.pqrs.karabiner.karabiner_console_user_server``

Hopefully that helps! If you really get stuck you can send me the file and I'll put the rule in for you (again, assuming it works as demonstrated on other keys, as I can't test disabling my eject button).

**Comment by tltz** [comment]
I am so grateful to you for trying. Thank you Joshua!
But unfortunately, even though I can get the rule to show up, the eject key is still not disabled.
It was worth a try!
I have attached the file just in case you know any other magic tricks – but honestly, just the efforts you have put forth have been enough. I appreciate you trying!
All the best,
T



••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
Tory Zimmerman
Videographer | Editor | Photographer
The Hospital for Sick Children | Creative Services Studio

Direct Line: 416 813 8932  Customer Service: 416 813 6682
S114-555 University Avenue, Toronto ON, M5G 1X8

**Comment by jams2** [comment]
@tltz I can't see attachments as you are posting to github. Try pasting the contents of your config file in a gist (github > top right corner > `+` > create new gist > save as public gist) and linking it here and I'll take a look.

**Comment by npradeepkumar** [comment]
I had the problem with the Eject key and using the Ctrl+Shift+Eject to lock my Mac using an external Apple keyboard for the longest time. Based on some of the comments in this thread, I mapped one of the function keys (F13) to the Eject key and that seems to have done the trick. I am now able to use Ctrl+Shift+F13 to lock my Mac and step out. Similarly the Cmd+Optn+F13 to put my Mac to sleep.

**Comment by wfaulk** [comment]
This issue needs to be reopened. The problem still exists for external keyboards and prevents me from using Karabiner-Elements to modify events from my external keyboard while wanting to retain the ability to use Ctrl-Shift-Eject and Cmd-Opt-Eject to sleep my display and system, respectively.

**Comment by PierBover** [comment]
I'm on a Perixx USB keyboard and the Eject key works to put the computer to sleep etc but it cannot be mapped with Karabiner Elements. The key only works when Karabiner Elements is not running which is weird.

It also doesn't appear in Karabiner Elements regardless of whether Elements is running or not.
