### ISSUE TITLE
2016 MacBook Pro Touch Bar Fn modifier broken

### ISSUE THREAD

**Issue by NathanJang** [tekezo/Karabiner-Elements#460]
I have my touch bar configured to "Expanded Control Strip" in System Preferences, and the Fn key set to "Show App Controls". This works fine without Karabiner running, but the Touch Bar does not change as expected when Karabiner is running; it just stays on the Expanded Control Strip.

```
{
    "profiles": [
        {
            "fn_function_keys": {
                "f1": "vk_consumer_brightness_down",
                "f10": "mute",
                "f11": "volume_down",
                "f12": "volume_up",
                "f2": "vk_consumer_brightness_up",
                "f3": "vk_mission_control",
                "f4": "vk_launchpad",
                "f5": "vk_consumer_illumination_down",
                "f6": "vk_consumer_illumination_up",
                "f7": "vk_consumer_previous",
                "f8": "vk_consumer_play",
                "f9": "vk_consumer_next"
            },
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "caps_lock": "delete_or_backspace"
            }
        }
    ]
}
```

The Karabiner Event Viewer correctly recognises the Fn key being pressed and released:
```
eventType:FlagsChanged    code:0x3f       name:fn              flags:Fn                                 misc:characters:    
eventType:FlagsChanged    code:0x3f       name:fn              flags:                                   misc:characters:    
```

EDIT: After my MacBook sleeps and wakes, the expected behaviour returns. However, the faulty behaviour reappears if i relaunch Karabiner.

**Comment by cs-miller** [comment]
having the same issue

**Comment by syamn** [comment]
same here

**Comment by matrinox** [comment]
Same here. And mapping fn to fn doesn't work. It wouldn't be such a big deal if there was another way to access the control strip/ app control

**Comment by epegzz** [comment]
After putting the macbook to sleep and waking it up again, the `fn` key works as intended.

**Comment by ehellman** [comment]
Worked for me too, doesn't feel like a long time fix though. Any idea why this is the case?

**Comment by jlabonski** [comment]
Confirmed here as well 15" late 2016 MBP, Karabiner-Elements 0.92.92. MacBookPro13,3. Drove me up a _wall_ this morning.

**Comment by ELLIOTTCABLE** [comment]
Some commentary in some of the clones of this thread mentions restarting Karabiner as being the source of this problem — I just want to throw out there that I see this behaviour *from startup*, without manually restarting Karabiner. (Also, it's consistently reproduced: it's not ‘sometimes’, the `fn` key *never* works as expected with the Touch Bar as long as Karabiner Elements is running, for me.)

**Comment by JPinlac** [comment]
After I switched left control and fn. The original fn key registers as a left control button press, but retains original functionality of the fn key. (Showing the f1, f2, f3, etc. keys)

**Comment by AranelSurion** [comment]
@ELLIOTTCABLE After reading @epegzz 's comment on this I immediately closed the lid, waited for 5~ seconds and opened, then Fn key started working as expected.

**Comment by ELLIOTTCABLE** [comment]
@JPinlac I can reproduce that; and that's cool, but it doesn't solve the titular issue on this page (i.e. I just tested that while fn *was not* invoking the Control Bar as it should be, and the change didn't fix it. After using the go-to-sleep, hack, though, it works as you describe — which is pretty cool!)

**Comment by derRAV3N** [comment]
Is there any permanent solution for this? I'd like to remap keys with this, but I rather not want to lock and unlock every time I restart my MacBook. Seeing that the issue seems to persist for longer than a year makes me quite hopeless.

**Comment by vasilisvg** [comment]
Same issue here with Karabiner 11.5, high sierra, MacBook Pro (15-inch, 2016)

**Comment by SergejLogis** [comment]
Same issue. Karabiner Elements 11.5.4. Putting Mac to sleep doens't work either - after wake-up FN and LEFT CTRL keys remapping ain't there anymore - FN works just as FN...

**Comment by myfluxi** [comment]
Karabiner 11.5, Macbook Pro 15 2017, switching fn + left_control leads to Touch Bar not displaying functions keys when either of the two (fn || left_control) being pressed.

**Comment by ClintEsteMadera** [comment]
clearly these guys don't give a s**t about users complaints, uninstalling...

**Comment by NathanJang** [comment]
@ClintEsteMadera that's a little harsh. This is free software and we should appreciate the work of all the contributors.

**Comment by ELLIOTTCABLE** [comment]
I mean, to be fair …

Look, I’m a software maintainer. On the one hand, I get it — we’re humans, with lives, too. But this is:

1. a particularly crucial piece of software (without it, some people’s work-lives are absolutely *crippled*),
2. with no alternatives available,
3. upon which a large number of users depend.

If there’d been any attempt from the original author to write the software in a spelunkable, self-documenting, maintainable style … then I’d agree. If there’d been any attempt to hunt down and designate a replacement maintainer … then, I’d agree. Hell, if they’d bothered to reply to one of the three(!) long threads about this issue, acknowledging it and either providing a timeline for getting to it, or explicitly wontfix’ing it so we can move on with our lives … then I’d agree!

But as it stands? A ton of us are screwed, there’s no way out of the situation short of writing custom keyboard firmware, and it’s been a running issue for a *really long time* — all while there’s active, new-feature-implementing commits happening to the software.

Just absolutely unacceptable, even for free and open-source software.

**Comment by cotfas** [comment]
@ELLIOTTCABLE It is a free software, we ca not have to much expectation, if we need better services we have to pay. In the meantime for me it works best with a solution found on the other issue opened here with the same problem. Now I have remap the FN + 12334567890 which acts as F1-F12 keys.

**Comment by tomislav** [comment]
The author doesn't own a MacBook Pro w/ Touch Bar. Fix it and submit a PR or work around it by sleeping and waking your MacBook.

**Comment by ELLIOTTCABLE** [comment]
Nope! Still an issue!

**Comment by issei-m** [comment]
Not stale.

**Comment by ELLIOTTCABLE** [comment]
nope
