### ISSUE TITLE
Built-in keyboard disabled after closing Karabiner-Elements

### ISSUE THREAD

**Issue by cgalisteo** [tekezo/Karabiner-Elements#462]
Even though I'm not disabling built-in keyboard when usb one is connected, every time I quit the application it gets disabled.
Mac-book pro Mid 2012 running macOS 10.12.1

**Comment by zhexuany** [comment]
@cgalisteo Purely out of curiosity, does current karabiner-element provides disabling internal keyboard if external keyboard is injected?

**Comment by cgalisteo** [comment]
yes it does

**Comment by gnowoel** [comment]
Confirmed. I have the same problem with the same type of machine (MacBook Pro Mid 2012 / macOS 10.12.2). The internal keyboard gets disabled once I plug in an external one. I have to unplug it and restart the machine to make the internal one functional again.
