### ISSUE TITLE
Different mappings for different applications.

### ISSUE THREAD

**Issue by stefmitropoulos** [tekezo/Karabiner-Elements#463]
Hello there!

In Karabiner I could edit the xml file to be able to map cmd and fn to alt and command respectively only when a window was active. Anyone that could help with the coding in json for this? Or any other way this is already implemented?

Thank you in advance

**Comment by laxapple** [comment]
Karabiner-Elements can't do this currently, but Keyboard Maestro and BetterTouchTool do, though they are both paid app.

**Comment by kaptsea** [comment]
Unfortunately I'm interested in using the FN and left CMD keys which do not appear in either of these apps, like they cannot handle the press. Have you tried this yourself?

**Comment by laxapple** [comment]
BetterTouchTool could distinguish left & right modifier keys. Try the "Key Sequence" trigger instead of "Shortcut"

**Comment by dsedivec** [comment]
No status change on this AFAIK, but for reference see also #212 and #137.

**Comment by wincent** [comment]
Should probably be closed as a duplicate.

**Comment by optimus1509** [comment]
guys how do i remap the escape key to delete/backspace key? This whay i have in the JSON, it used to work esrlier, but suddenly stopped working for some reason...

```
{
  "title": "Calcbot remap esc to backspace",
  "rules": [
    {
      "description": "Remap ESC to Backspace in Calcbot only",
      "manipulators": [
        {
          "from": {
            "key_code": "escape"
          },
          "to": [
            {
              "key_code": "delete_or_backspace",
              "modifiers": [
                "delete_or_backspace"
              ]
            }
          ],
          "conditions": [
            {
              "type": "frontmost_application_if",
              "bundle_identifiers": [
                "com.tapbots.CalcbotMac"
              ]
            }
          ],
          "type": "basic"
        }
      ]
    }
  ]
```
}
