### ISSUE TITLE
Caps Lock LED no more working since 0.90.67 (still on 0.90.68)

### ISSUE THREAD

**Issue by ZeeArts** [tekezo/Karabiner-Elements#467]
Since version 0.90.67 the caps lock led is no more workin.
Keybindings also no more workin. Only un- and reinstall help. Till restart of the system.
The event_manipulator issue still on 0.90.68.
I'm back again to 0.90.66
![screenshot](https://cloud.githubusercontent.com/assets/23092177/20849638/f52332aa-b8d7-11e6-97a4-2244c53c6d78.jpg)

**Comment by zealson** [comment]
I do agree!

**Comment by apveenstra** [comment]
Same problem here. After upgrading to 0.9.68 the Caps Lock key and LED are not working anymore.

**Comment by guycalledseven** [comment]
Bump! same here.
KarabinerEventViewer sees caps-lock being pressed, Apple's Show keyboard viewer shows caps-lock being clicked but caps lock does not work.

**Comment by thymara** [comment]
Weird, this worked for several days and now does not, once again stopping karabiner_grabber resolves the issue

**Comment by bcubic** [comment]
same issue here.
since last update capslock not working until quit kaeabiner-elements app

**Comment by GlenDonnelly** [comment]
Yep, same here. I can make capslock work again by for the time being, unticking 'Apple Internal Keyboard' in Devices pane in Karabiner-Elements settings.

**Comment by thymara** [comment]
Tried  unticking 'Apple Internal Keyboard' in Devices pane in Karabiner-Elements settings. While it worked as far as the caps lock light goes several of my modifications no longer worked

**Comment by RicoSky** [comment]
RESTARTING KARABINER GRABBER HELPS! as you see! :)

**Comment by ags799** [comment]
@thymara @bcubic @RicoSky Are you suggesting to kill a karabiner_grabber process? I don't have such a process running while Karabiner-Elements is running. Can you be more specific? Would be much appreciated.

**Comment by thymara** [comment]
if you use Activity Monitor and then search for "kar" it will show about 4 processes, one of which is grabber. Quick way to start Activity Monitor is to use Spotlight

**Comment by ags799** [comment]
Thanks for the quick response @thymara. I have 3 such processes: `Karabiner-Elements`, `karabiner_console_user_server`, and `karabiner_event_dispatcher`.

Everything is working as expected, except for the Caps Lock bug described here.

**Comment by thymara** [comment]
not sure why you don't have grabber, it will take someone much more knowledgeable than I am on this subject. The fact that you don't have grabber suggests a possible installation error. I was very fortunate when I discovered the [installation instructions](https://github.com/tekezo/Karabiner-Elements/blob/master/usage/README.md) which made things quite simple

**Comment by ags799** [comment]
I followed those instructions to reinstall and am now experiencing #448. By downgrading to 0.90.66 I can resolve that issue (#448) as well as this one (Caps Lock works again).

**Comment by Penderworth** [comment]
I've been hitting this as well with all my external keyboards. Pretty annoying. Looking forward to a fix. :)

**Comment by longbored** [comment]
Same issue for me as well. Quitting karabiner grabber helped, but I still look forward to a fix.

**Comment by pclott** [comment]
Same issue.   As soon as it's loaded by system, it stops working.

**Comment by gamesbrainiac** [comment]
Restarting Karabiner grabber helped! It restarts itself, just force quit it.

**Comment by nathanhugen** [comment]
I have both of the issues mentioned above.  Karabiner-Elements is preventing the Caps Lock key from working on the internal laptop keyboard.  If Karabiner is running, Caps Lock doesn't work and the LED does not turn on, although Karabiner Event Viewer detects the key press.  Also, I do not have a "grabber" process running so I cannot kill it as suggested by someone above.  I am running 0.90.68 on a MacBook Pro (15-inch, Late 2016) with Sierra 10.12.2.

**Comment by sgykfjsm** [comment]
In my case, I cannot find any process without Karabiner-Elements. So I tried re-installing. Now all works fine.

**Comment by gamesbrainiac** [comment]
Restart the karabiner grabber, that seems to work for me in version 0.9.68.

**Comment by qmmr** [comment]
Same issue here. Works after updating to latest version and restarting 👍

**Comment by trusktr** [comment]
I'm having problems with Capslock key I think. It only works when I map `right_option` to it, but only turns it on, then it stays on and I can not turn capslock off. Trying `to_if_alone` mapped back to `caps_lock` doesn't help either. Note, I've mapped `caps_lock` to `left_control`, which is why I'm trying to find a way to make Capslock functionality work. I thought I was doing something wrong, but maybe I'm not if there's actually this problem here that is interfering.
