### ISSUE TITLE
How can I modify nordic characters?

### ISSUE THREAD

**Issue by askog** [tekezo/Karabiner-Elements#469]
I run a Colemak nordic setup on my keyboard. How do I move around our local characters (i.e Ä-Å-Ö)? They are not in the list that comes built into the software.

**Comment by proProbe** [comment]
Hey @askog ! did you find a solution for this?

**Comment by askog** [comment]
@proProbe Yes, it was deceivingly simple. Just ignore the regional layer of the keyboard and treat it as a regular ANSI. Karabiner layers between the actual keystrokes and the OS interpretation of what each key represents.
