### ISSUE TITLE
How to set key repeat speed

### ISSUE THREAD

**Issue by canpoyrazoglu** [tekezo/Karabiner-Elements#47]
I've upgraded to macOS Sierra just to find out that Karabiner (which I have many mappings and speed configuration) is incompatible. I've installed Elements. How do I change the default key repeat latency? The examples are only for swapping/changing keys, or am I missing something?

**Comment by aleksandrs-ledovskis** [comment]
This isn't yet supported by Karabiner-Elements, i.e. it uses values set via macOS keyboard preferences

**Comment by canpoyrazoglu** [comment]
Okay, I've just found out http://apple.stackexchange.com/questions/10467/how-to-increase-keyboard-key-repeat-rate-on-os-x which does the job until the feature is implemented. Then I'd be happily switching back to Karabiner's implementation once it's ready. Thanks for the quick reply!
