### ISSUE TITLE
Combine keys

### ISSUE THREAD

**Issue by slovenianGooner** [tekezo/Karabiner-Elements#471]
Hi,

is it possible to do something like:

Option_R (AltGr) + 1 = ~
or 
Option_R (AltGr) + Q = \

So, basically what used to be a set of rules for standard Windows/Linux style keyboards.

**Comment by FuegoFro** [comment]
Seems like a dupe of https://github.com/tekezo/Karabiner-Elements/issues/16?

**Comment by slovenianGooner** [comment]
Seems like it, will close.
