### ISSUE TITLE
Caps Lock LED not lighting up when mapped to Esc key

### ISSUE THREAD

**Issue by juilyoon** [tekezo/Karabiner-Elements#472]
Until just recently, the green LED on the <kbd>Caps Lock</kbd> key would light up when I mapped it to the <kbd>esc</kbd> key.
For some reason it stopped working all of a sudden.

I'm on `Version 0.90.68`

**Comment by firedev** [comment]
This is incorrect I believe, the LED should always be off if you remap the CapsLock key.

**Comment by juilyoon** [comment]
@firedev Is this still the case? I've noticed recently that the LED is consistently mapped to the <kbd>Caps Lock</kbd> function when the <kbd>esc</kbd> is remapped.

**Comment by firedev** [comment]
@juilyoon It hangs sometimes and I have to restart karabiner, but mostly it's  think it is working fine for me. I am using this fork to get Esc + Ctrl on Caps Lock: https://github.com/tekezo/Karabiner-Elements/pull/247#issuecomment-286024862

**Comment by juilyoon** [comment]
This seems to have been fixed without me noticing.

Thanks @firedev
