### ISSUE TITLE
Seil-like Caps Lock to Esc and Ctrl

### ISSUE THREAD

**Issue by firedev** [tekezo/Karabiner-Elements#473]
Is is possible to map Caps Lock to act as both Esc and Ctrl as Seil could do? This becomes more important with TouchBar MacBooks.

**Comment by kbarrette** [comment]
I don't know Seil, but #247 perhaps?

**Comment by firedev** [comment]
Thanks @kbarrette exaclty what I wanted, not it is safe to get a Macbook Pro. Wish this to be merged sooner.
