### ISSUE TITLE
support DoublePressModifier to allow double tapping a key to map to another key.

### ISSUE THREAD

**Issue by gregord** [tekezo/Karabiner-Elements#474]
In my current config, I use:

`<autogen>--DoublePressModifier-- KeyCode::SHIFT_L, KeyCode::SHIFT_L, KeyCode::F19, ModifierFlag::CONTROL_L</autogen>`

This allows double tapping the Left Shift to generate the F19 keycode, modified with Left Control. (or Ctrl-F19 if you prefer)

I know this is a rather advanced use case, but is this possible now with Karabiner Elements? Is it planned?

**Comment by RuslanIsh** [comment]
Not only I'm looking forward to this but also to the ability to specify the wait time between key presses, as in:
<lastpressedphysicalkey_only>KeyCode::SHIFT_L</lastpressedphysicalkey_only>
<elapsedtimesincelastpressed_lessthan>Millisecond::RawValue::300</elapsedtimesincelastpressed_lessthan>

**Comment by shawkinaw** [comment]
I still want this feature.

**Comment by gregord** [comment]
I kinda do too, but I found hammerspoon can make it happen.

https://gist.github.com/asmagill/c38f75fff9d9ef43d1226329fc1436e4

This handles double press of ctrl.

**Comment by trusktr** [comment]
Can I make double-tap Shift toggle capslock in Karabiner Elements? It isn't clear how to do this (if even possible).
