### ISSUE TITLE
return_or_enter

### ISSUE THREAD

**Issue by edwardvanroberts** [tekezo/Karabiner-Elements#475]
Can these be separated? "Carraige return" and "enter" are two distinct functions and are used separately. Is that possible?

**Comment by YesThatAllen** [comment]
I'm having a problem making `return_or_enter` function as the normal Enter key.

It seems to work on some places, but won't dismiss dialog boxes in the same way as `fn`+`return` does

**Comment by YesThatAllen** [comment]
@edwardvanroberts `keypad_enter` is what we're looking for here, are there times you're not seeing it work?

**Comment by edwardvanroberts** [comment]
Allen-

Thank you for your response - yes, that is what I was looking for. It wasn’t very intuitive for me, but yes, that is the keystroke that I use on a daily basis - and since it isn’t on my laptop, I change my right_option to that. Thanks again.

Kyle
