### ISSUE TITLE
profile tight to device

### ISSUE THREAD

**Issue by lrusnac** [tekezo/Karabiner-Elements#478]
Is it possible to have multiple profiles active at the same time, tight to different devices?

The idea is: I have an external keyboard, so I would like to have a profile for the external keyboard and another profile for the built-in keyboard of the mac.

My solution is manually switch the selected field in the karabiner.json file every time I switch keyboard, but that is quite annoying, so I was looking for another solution, either automatic based on device or something fast in the UI, the old karabiner had a easy way to switch profiles.

**Comment by xdidi3r** [comment]
+1

**Comment by clindh** [comment]
+1

**Comment by xdidi3r** [comment]
Now my solution is switch between 2 karabiner.json by typing keyword "kb" in alfred 3.

**Comment by warmerq** [comment]
@xdidi3r , good idea !

**Comment by sgronblo** [comment]
Yes, this would be great. The old Karabiner seemed to already support it. But unfortunately some settings like the caps lock key (I think) needed to be changed manually in Seil.

**Comment by perlun** [comment]
@xdidi3r It seems like in the newer versions of Karabiner Elements, it doesn't detect changes to `karabiner.json` automagically. 😢 /cc @tekezo

**Comment by clindh** [comment]
They have moved the location of it, now in .config/karabiner/

**Comment by perlun** [comment]
@clindh 

> They have moved the location of it, now in .config/karabiner/

Yes, but even when changing this file, it still doesn't auto-pickup changes (as it used to do). I have to restart Karabiner Elements when making a change.

**Comment by clindh** [comment]
Ok. It works for me in 0.90.75 (have not tried 77 though)
I have an Automator script to toggle between two setups, coping two different files onto karabiner.jsonm and it changes instantly.

**Comment by xdidi3r** [comment]
@perlun My solution still works for me in version 0.90.79

**Comment by lrusnac** [comment]
the version 0.90.84 introduces a tab for easy selection of a profile, I think we could close the issue for now even if the profiles don't changed based on the keyboard, but it makes it easier to change them either way

**Comment by perlun** [comment]
Great @lrusnac, thanks!
