### ISSUE TITLE
how to config Control+L instead of right arrow?

### ISSUE THREAD

**Issue by abellee** [tekezo/Karabiner-Elements#48]
I just wanna change the Control+L =>Right Arrow Control+J=>Left Arrow
It had a selection in Karabiner, and how to write the karabiner.json for Karabiner-Elements?

and I did not find the karabiner.json file located the ~/.karabiner.d/configuration/
I should create it manually?

**Comment by talha131** [comment]
Yes, you have to create it manually.

> I just wanna change the Control+L =>Right Arrow Control+J=>Left Arrow

See #16

**Comment by abellee** [comment]
@talha131 so how to write the configuration for Control+L or Control+J instead of left and right arrows, just like the selection in the Karabiner

**Comment by talha131** [comment]
@abellee Multiple key strokes as one is not possible until #16 is fixed.

For now you can map single key to single key only. Say ⌃Control to ⌥Option (alt).

**Comment by cicloid** [comment]
For those interested, I added a suggestion for this functionality at https://github.com/tekezo/Karabiner-Elements/issues/103#issuecomment-250225961

**Comment by watsoncj** [comment]
I've hard-coded arrow keys as `fn + hjkl` here: 5531032a309fe99e7e153cb725b9f44a19da69c0

**Comment by pohkit91** [comment]
@watsoncj how do I modified your version to
`'cmd+left' to 'r-cmd' `
and
`'cmd+right' to 'r-option'`

I'd try modify `if (modifier_flag_manager_.pressed(krbn::modifier_flag::fn)) {` to `if (modifier_flag_manager_.pressed(krbn::modifier_flag::cmd)) {` but it's not working on my end...
