### ISSUE TITLE
Build fails, analyzer issues

### ISSUE THREAD

**Issue by cperryk** [tekezo/Karabiner-Elements#481]
Trying to build from source on OS 10.11.6, `make` is failing with the following output:

```
git clean -f -x -d
./make-package.sh
make build
......................................................................
.................................** BUILD FAILED **


The following commands produced analyzer issues:
	AnalyzeShallow libkrbn_configuration_monitor.cpp
	AnalyzeShallow libkrbn_device_monitor.cpp
	AnalyzeShallow libkrbn_system_preferences_monitor.cpp
(3 commands with analyzer issues)

The following build commands failed:
	AnalyzeShallow libkrbn_system_preferences_monitor.cpp
(1 failure)
make[4]: *** [all] Error 65
make[3]: *** [all] Error 2
make[2]: *** [all] Error 2
make[1]: *** [build] Error 2

make: *** [all] Error 99
```
I'm still seeing the error after rolling back to other versions.

**Comment by tekezo** [comment]
Confirm the requirements. I guess you did not install boost.
https://github.com/tekezo/Karabiner-Elements#how-to-build

**Comment by cperryk** [comment]
Thanks. I should have seen that. Still getting some errors and warnings in the make cmd (a few `code object is not signed at all` and a few `The following commands produced analyzer issues: AnalyzeShallow main.cpp`, but it does produce a functioning DMG and the installed program has been working as expected so far.
