### ISSUE TITLE
Esc key doesn't map to Caps lock

### ISSUE THREAD

**Issue by gkb** [tekezo/Karabiner-Elements#483]
Strangely, this used to work until last week. I'd mapped Esc to Caps lock on my keyboard. I can't figure out why it abruptly stopped working. Any help is greatly appreciated. Thanks for all the great work! Love the tool.

**Comment by rafalivanoff** [comment]
In my MBPRO retina 15 mid 2014 caps lock is not working at all.

**Comment by danawoodman** [comment]
Same issue here, just recently broke my Caps Lock => Escape mapping 😢

**Comment by danawoodman** [comment]
It appears to have broken in this commit: https://github.com/tekezo/Karabiner-Elements/commit/b9d6ee4679abef4f9ab1d722c01e7a46e7003c3c

I am getting log messages of:

```
[2016-12-12 12:20:05.027] [warning] [grabber] event_manipulator_ is not ready. (virtual_hid_device_client is not ready) Please wait for a while.
```

**Comment by danawoodman** [comment]
CC @tekezo could you revert that commit?

**Comment by sevenmaxis** [comment]
Same issue on my MBPRO 2014

**Comment by quinoa42** [comment]
Same here.

**Comment by ccsasuke** [comment]
Same here on rMB 2015
