### ISSUE TITLE
Caps Lock doesn't work when elements running

### ISSUE THREAD

**Issue by syjiangrui** [tekezo/Karabiner-Elements#485]
Caps Lock doesn't work when elements running and the system may lazy when I use Caps Lock

**Comment by RicoSky** [comment]
the same with me. Using MacBook Pro mid 2015 with wired Apple keyboard. When I start "Keyboard preview" in System Preferences I see that the system sees the keybord and react for pressing Caps Lock key.

**Comment by alvin-a-garcia** [comment]
This appears to be a duplicate of https://github.com/tekezo/Karabiner-Elements/issues/467

**Comment by RicoSky** [comment]
right. sorry!

Pozdrawiam / Best regards,
Piotr Rutkowski






Wiadomość napisana przez alvin-a-garcia <notifications@github.com> w dniu 12.12.2016, o godz. 15:11:

This appears to be a duplicate of #467 <https://github.com/tekezo/Karabiner-Elements/issues/467>
