### ISSUE TITLE
Mouse Support?

### ISSUE THREAD

**Issue by GhostValk** [tekezo/Karabiner-Elements#486]
Hi!

Is there going to be mouse support again in Karabiner? I know it has been asked before (by me, actually), but i would really love to know if there is any plan to implement it again or we will never be available to remap the mouse buttons (in my case is very very important).

Thanks in advance!

**Comment by SneakerElph** [comment]
I'd also love this. I use the side buttons on my mouse as ctrl/alt and I'd love to have that functionality back, as it makes a lot of things I do much easier. Thank you!

**Comment by GhostValk** [comment]
What i'm asking is only the devs to answer if this is going to be available again, not to put pressure, just to know.

**Comment by cyvasseq** [comment]
I am also begging for this! The ONLY reason I installed Karabiner was to add extra functionality to my mouse (otherwise the buttons are simply non-functional). Karabiner-Elements was supposed to be a short term fix until Karabiner was ported to the new OS, but it seems like Karabiner is dead, leaving only Karabiner-Elements. If there's no plans to support extra mouse buttons, are there ANY other applications that work to use the extra mouse buttons on a Windows mouse?

**Comment by stevefoxon** [comment]
I use SteerMouse. Only ever used Karabiner for Keyboard.

**Comment by ajimix** [comment]
Mouse support +1, I want to map a key of the keyboard to the mouse click :)

**Comment by GhostValk** [comment]
stevefoxon i just downloaded steer mouse and it patchs perfectly the issues in karabiner, thanks a lot!

**Comment by LunaticoCR** [comment]
+1

**Comment by mikefoley** [comment]
Sigh, I really don't want to spend $20 just to remap a mouse key. :(

Any update? Bueller?

**Comment by louisgv** [comment]
There's a major security issue with SteerMouse so I was not allowed to use it on my work machine. (So you all using it better be careful). Karabiner however is open source and for such a software that's so equivalent to being a key-logger, it is essential to see the source and modify it however we wish.

Anyhow, having mouse key support would be a very great addiction.

**Comment by AquiGorka** [comment]
I had a problem with my keyboard and had to disable the left shift key, yet everytime I click it seems as if the shift key was down.
Is there a way to disable such behavior with Karabiner?

**Comment by clarkewd** [comment]
I'd also love to see support for mapping a key to a mouse click. Right now as a workaround I've enabled "mouse keys" in the accessibility pane of system preferences ( allows you to use the numpad to move the mouse and click ) - even though I don't have a numpad I've remapped a key to keypad_5 ( click ) and at least for right now this seems to give me what I need.

**Comment by oin** [comment]
@clarkewd's solution is OK but dragging doesn't work.
To implement this in the meantime I wrote [Clicker](https://github.com/oin/Clicker), a little app with no user interface that translates presses/releases of a key to presses/releases of the left mouse button.
I've tested it for two months on OS X 10.11 and macOS 10.12, and it works flawlessly, even for complex mouse dragging operations.
The only downside is that it doesn't work when a password field is focused (a security limitation of the Event Tap library).

**Note that this doesn't translate mouse button presses to key presses or actions** (even though one could make it work based on similar code).

Feel free to use it and modify it until Karabiner-Elements supports keyboard key to mouse button mapping.

**Comment by clarkewd** [comment]
@oin - excellent work. seems to work much better than mouse keys, especially for dragging. thank you

**Comment by rattes412** [comment]
@AquiGorka did you fix that issue? having the same problem now

**Comment by AquiGorka** [comment]
Hey @rattes412, nope, never did. Had to learn to work without the mouse (which is not that bad and I do have another computer when it gets too annoying).

I did try with an external usb mouse and the problem persisted so I'm guessing it is something more complicated.

**Comment by chinchin96** [comment]
Would really love to see mouse support. Especially scrolling using D+S/F and HJKL keys. I literally would never had to take my hands off the keyboard. (Drawing/Art might be the only exception)

**Comment by incandescentman** [comment]
This worked for me:

                            "from": {
                                "key_code": "insert"
                            },
                            "to": {
                                "pointing_button": "button1"
                            }

**Comment by AquiGorka** [comment]
What does the new configuration do @incandescentman?

**Comment by lwalton-turnto** [comment]
Ditto what AquiGorka asked: Can @incandescentman explain more what abilities you get by configuring pointing_button ?  Some of us watching this thread are desparately looking for the equivalient of Karabiner's MouseKeys 2 Mode, although I know the OP was only asking about adding single key mapping. 
Thanks!
