### ISSUE TITLE
Enable/disable key mappings based on which keyboard is used

### ISSUE THREAD

**Issue by mattbeshara** [tekezo/Karabiner-Elements#488]
I have an external PC keyboard which I swap the mappings for the command and option keys on, so they match the native Mac layout. However, those mappings also effect my MacBook's built-in keyboard, which means I have to remove the settings in the JSON config file when I unplug my external keyboard to use my MacBook on the go, and add them back in when I use it at my desk with the external keyboard again.

I also have the caps lock key remapped to F19, and I want that remapping to be in effect for both keyboards, so unchecking the 'Modify events from this device' checkbox for the internal keyboard is not an effective solution.

AFAIK this wasn't an issue in the old Karabiner as the keyboard-specfic modifier key mapping in System Preferences worked, whereas in the new Karabiner those settings have to be ignored due to  changes in the OS. I'm not nearly familiar enough with the code to be able to propose a solution, and this is far more of a hassle than a bug, but it would be nice if Karabiner could handle my use case more easily.

**Comment by alexhayes** [comment]
I also have this problem.

On my MBP keyboard I'd like to swap `fn` and `control` because I find it difficult to press `control`. However this means that on my [DAS USB keyboard](http://www.daskeyboard.com/blog/its-like-candy-for-your-apple/) (which does not have a Fn key) this means that my `Ctrl` key becomes `fn` and I no longer have a `Ctrl` key.

**Comment by idan** [comment]
Argh, spent a bunch of time scratching my head before figuring exactly this out. 😢  I have an external keyboard (Microsoft Sculpt ergonomic) when I'm at my desk, it defaults to a swapped layout for option and command. The `modifier keys` system preference lets me fix that for the external keyboard without altering the builtin.

I don't know about the API internals here, is karabiner's taking control of the mappings an all-or-nothing affair? E.G. could it be made that Karabiner doesn't completely disable the per-keyboard system preference, so long as you don't attempt to remap one of those keys in Karabiner as well? All I want to do is mess with the caps lock (and media keys, at least for the external keyboard).

Of course, the ideal would be per-keyboard remappings, but I have zero idea of the amount of effort that this entails.

Thanks @tekezo for all of your hard work on Karabiner — what a useful piece of software! ❤️

**Comment by datico** [comment]
@tekezo agreed, thanks very much! Such a helpful tool.
I also have an external (bluetooth) keyboard being used on my laptop daily at my workstation, but then use my laptop keyboard when on the go. I noticed the volume, brightness, etc indicators on function keys are different between the two keyboards. I don't use these often and when I do, I tend to look for the icons.
So this is another use case for supporting different mappings depending on the keyboard being used. I'd like to map F13 and F14 to volume up and down on the external keyboard, but F11 and F12 to the same on the laptop keyboard.
Thanks!

**Comment by starsy** [comment]
@alexhayes @mattbeshara I have made some enhancements to KBE to support per device configuration within the same profile. Please check if this helps: https://github.com/tekezo/Karabiner-Elements/issues/770 Any questions please let me know.


![image](https://user-images.githubusercontent.com/1459979/26891802-dd782b52-4be8-11e7-8380-5aa0703b6fa9.png)

**Comment by alexhayes** [comment]
This can be closed now - as per https://github.com/tekezo/Karabiner-Elements/issues/488#issuecomment-306872346
