### ISSUE TITLE
Change capslock to Control when held and Escape when tapped

### ISSUE THREAD

**Issue by domi91c** [tekezo/Karabiner-Elements#489]
I'm sorry if this is a duplicate but I couldn't find a solution that worked. The most amazing thing I got out of Karabiner was the mapping in the title. Is this possible with Karabiner-Elements? If so, what do I need to put in my profile? It's empty right now; I used the user interface in Karabiner to set it up and never figured out how to write mappings without it. 

Thanks!

**Comment by delphinus** [comment]
See #247 and https://github.com/tekezo/Karabiner-Elements/pull/247#issuecomment-265033986 . But master does not support this.

**Comment by domi91c** [comment]
Awesome, it works. Thank you.
