### ISSUE TITLE
"Enable Sicky keys" setting on preference does not affect

### ISSUE THREAD

**Issue by kitora** [tekezo/Karabiner-Elements#49]
On Preference.app>Accessibility>Keyboard>Enable Sticky keys.
It does not affect when I type texts.
For example,
1. Forcus on Terminal.app
2. Press Shift key
3. Displayed translucent Shift icon on screen
4. Type any alphabet on terminal
5. Inputted lower case character
6. Shift icon still on screen

It seems that Sticky icon affects on mouse operations.

**Comment by yokoiwahiroki** [comment]
I have same problem. Previous Karabiner app and Sticky keys function worked together.
It seems Karabiner Elements app steals key signals before Sticky keys grabs them.

**Comment by kitora** [comment]
I tried new version 0.90.37.
When I typed modifier keys , no sticky icon was displayed.
Regardless of sticky setting , Karabiner-Elemements seems to disable OS sticky feature.
No sticky effect for mouse operations.

For now I stopped confusing the mismatch of key type behavior and GUI indication.

**Comment by garges** [comment]
I also have this problem. Sticky Keys doesn't work at all and doesn't display any icon if Karabiner is running. I've seen this on 0.90.37, 0.90.38, and 0.90.39. Hope it can be fixed.

**Comment by jan-matthis** [comment]
Same issue here, using version 0.90.46

**Comment by manojfedx** [comment]
I am dying here without sticky keys! Without sticky keys my Bettertouchtool is gone!
Any update yet on this @talha131 ??

**Comment by garges** [comment]
I second the comment. I'd prefer the fix of this bug over the introduction of new features. Karabiner used to do what I want, now it useless. I've tried every version as they come out, up to 10.22, but still Sticky Keys does not work if Karabiner is running. I hope it can be fixed.

**Comment by jackcouch** [comment]
Got a brand new mac book pro that is a brick to me without this (can't run anything less than Sierra and can't live w/o sticky keys and karabiner).

**Comment by kitora** [comment]
On 0.90.67, Sticky signs are displayed when I Shift/Command/Ctrl key pressed.
But there are no sticky effects still.

**Comment by kitora** [comment]
I confirmed Sticky feature works properly on 0.9.72.
Thank you!!
