### ISSUE TITLE
Can't find option to remap \| to <>

### ISSUE THREAD

**Issue by lviggiani** [tekezo/Karabiner-Elements#490]
on simple remapping menu, I can't find these keys options (macOS Sierra):
| <>
I need to remap \ to < and | to >

**Comment by dvdmarchetti** [comment]
Hi
try with these settings:
![image](https://cloud.githubusercontent.com/assets/1494034/23823775/0681c234-066a-11e7-884c-93068d58f97f.png)

**Comment by lviggiani** [comment]
It works! Super, thank'you!
