### ISSUE TITLE
Feature Request: Per App configuration

### ISSUE THREAD

**Issue by kokizzu** [tekezo/Karabiner-Elements#493]
In previous version, there are per app configuration, I believe this is really useful.

**Comment by remarks** [comment]
Agree. I need this to maintain consistent keybindings while remote logging into a Windows PC.

**Comment by gregglahti** [comment]
Ditto with RDC apps.

**Comment by max-arnold** [comment]
I relied on this feature in older Karabiner to switch locale. I used CapsLock to send Ctrl+\ to Emacs and some other keycode to all other apps.

**Comment by etiennellipse** [comment]
+1

**Comment by jixiuf** [comment]
trying hammerspoon before KE support this feature https://github.com/jixiuf/dotfiles/blob/master/mac/hammerspoon/app_bind.lua

**Comment by plam4u** [comment]
+1
For me this is a blocker.

There are apps that have keybinding configs but for the apps that do not support it, I would use Karabiner-Elements and right now I can't. I've used the previous version because of the per-app-config.
