### ISSUE TITLE
Meta key option

### ISSUE THREAD

**Issue by sachka** [tekezo/Karabiner-Elements#494]
I wanted to see if a meta option parameter for a key could be added, I'm an emacs user and I was looking for a system wide meta to left-option key settings as in older karabiner, the idea is to retain right-option as default for symbol input, while using left-option as meta.

**Comment by petonic** [comment]
Man, we all miss it, but before opening up yet another issue and killing the signal to noise ration, please read what has already been written.  If you get emacs, you can certainly adapt what is written in #489 to implement a meta key (mapping left-option to perhaps f15 or something) and then using Hammerspoon to implement the functions.

Didn't mean to rag on you, but I get the feeling that either Takayama-san is burned out from being his one man 24x7 customer service desk, or he's intensely working feature parity with legacy Karabiner (praying for the latter, but fearing the former).

I haven't see him post in a while.

**Comment by RimuruCiel-Tempest** [comment]
Is this still not possible?? It would be amazing if this were to be a feature.
