### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by bennypowers** [tekezo/Karabiner-Elements#499]
I've designed a new icon for Karabiner. You're welcome to use it.

![app](https://cloud.githubusercontent.com/assets/1466420/21297318/4845aade-c586-11e6-9446-85834cdb5f15.png)
![icon statusbar 2x](https://cloud.githubusercontent.com/assets/1466420/21297319/4b8bff0e-c586-11e6-9ff2-162998bca0cf.png)

Zip with sketch file: 
[Archive.zip](https://github.com/tekezo/Karabiner-Elements/files/659754/Archive.zip)

**Comment by iiiGerardoiii** [comment]
A karabiner would be nice.

**Comment by aristidesfl** [comment]
+1 for a karabiner. We have enough of these..


![Sublime Text](https://upload.wikimedia.org/wikipedia/en/4/4c/Sublime_Text_Logo.png)

**Comment by iiiGerardoiii** [comment]
I just made this, it's more karabiner-ish:

![karabinericon](https://cloud.githubusercontent.com/assets/6264194/22685855/8aa4ad3e-ece7-11e6-80cf-e1b38307aba9.jpg)

Thoughts?

**Comment by bennypowers** [comment]
How's that going to look in the menu bar?
