### ISSUE TITLE
fn constantly pressed

### ISSUE THREAD

**Issue by mrfoto** [tekezo/Karabiner-Elements#50]
I mapped my Caps Lock to F16 which opens Alfred.
This is my config:
```
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "caps_lock": "f16"
            }
        }
    ]
}
```

But it stopped working with the last version. Event viewer is showing this:
![screen shot 2016-09-21 at 13 43 35](https://cloud.githubusercontent.com/assets/986645/18709664/8541ce60-8001-11e6-9def-76e86e02ca43.png)

I'm not touching Fn, in fact I don't even have that key on my keyboard.

The problem is Alfred is not starting up now, and even if I go to change shortcut, it's registering it as F16 as it should. But it's not firing up and (when in finder for example) I hear a beep (like unrecognized key).

**Comment by tekezo** [comment]
Thank you for feedback!
The adding fn flag to function keys is proper modifier flag handling in OS X.

I've fixed this issue at v0.90.36.
Please upgrade to the latest version from "Misc > Check for updates" or
https://pqrs.org/latest/karabiner-elements-latest.dmg

**Comment by matthewdias** [comment]
@tekezo Not sure if this is related, but karabiner-elements is blocking the binds I have programmed to my function layer directly on my programmable keyboard.

**Comment by psu** [comment]
0.90.36 fixed the same issue for me, thanks!

**Comment by mrfoto** [comment]
Yup, works, great job @tekezo 🎉
