### ISSUE TITLE
Function keys mapping issues

### ISSUE THREAD

**Issue by peteger** [tekezo/Karabiner-Elements#503]
Hello, I am using function keys mapping to remap keyboard illumination keys to F5 and F6 (and to keep other f-keys working as standard keys, such as volume up, volume down, etc.)

This worked fine until macOS 10.12.2 update I believe. 

![image](https://cloud.githubusercontent.com/assets/7255554/21317381/2b2580c6-c605-11e6-88e8-c03906aa4658.jpg)

Is anyone else having these issues?

Thanks!

**Comment by datico** [comment]
I am also having issues with function keys. I haven't tried changing the function keys as per your screenshot, but I notice the keys do not do what they are set to in this screen, there is no option to turn off override behavior in this screen, and the "Use all F1, F2, etc. keys as standard function keys" (which toggles the same setting in OSX Preferences > Keyboard) does not work either, as per ticket #512. I am not on 10.12.2 however, but on 10.11.6.

**Comment by peteger** [comment]
Whoa, this issues seems to be fixed in the latest 0.90.76 update. 

Thanks!
