### ISSUE TITLE
Caps lock not illuminated touch bar MBP

### ISSUE THREAD

**Issue by skallick** [tekezo/Karabiner-Elements#504]
With Karabiner Elements running the caps lock functions but does not light up when engaged. Quitting karabiner elements makes it work again. New Macbook pro with touch bar, system 10.12.1.

**Comment by Wardrop** [comment]
Do you get anything under the Log tab? I get the same thing with my Dell keyboard, and see the following entry every 2 seconds or so:

`[2017-08-22 09:06:26.444] [error] [grabber] IOHIDDeviceSetValue error -536850432 for Dell Wired Multimedia Keyboard (device_id:1) @ IOReturn krbn::human_interface_device::set_caps_lock_led_state(krbn::led_state)_block_invoke`

Unplugging the keyboard and plugging it back in resolves it temporarily before it eventually stops working again.
