### ISSUE TITLE
Lock screen combo (ctrl+shift+power) does not work when ctrl is changed

### ISSUE THREAD

**Issue by elad-maimon** [tekezo/Karabiner-Elements#509]
I use Karabiner-Elements to switch between ```fn <-> ctrl```.
But now the combo ```fn+shift+power``` does not lock my computer (used to work in Karabiner).
When turning off Karabiner-Elements it does work.

**Comment by Y-knot** [comment]
That's weird because I use the same Fn to Ctrl substitution and the same combo Fn–Shift–Power locks screen just great for me. I use KE v.0.90.68 and macOS Sierra 10.12.2.

**Comment by vaxXxa** [comment]
```{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "caps_lock": "left_control"
            },
            "standalone_keys": {
                "left_control": "escape"
            }
        }
    ]
}```

With this config I have the same issue: can't use ctrl+shift+power or cmd+option+power

**Comment by Y-knot** [comment]
Well, here's my configuration that allows Fn–Shift–Power to lock the screen:
![2016-12-25 1 15 23](https://cloud.githubusercontent.com/assets/22499068/21468931/c5e2f4fc-ca3f-11e6-80ac-3cdd6393a435.png)
Though my karabiner.json looks more crowded with `devices` and `fn_function_keys` sections.

Guess the problem is sporadic, more statistics from others are needed. Maybe, a re-installation of KE will help.

**Comment by elad-maimon** [comment]
@Y-knot do you have the apple wireless keyboard?

I've reinstalled several times,  happens every time, it's not sporadic.

**Comment by Y-knot** [comment]
I use macbook air 13" and no external keyboards. 
By sporadic I meant that some people have this problem while others don't.

**Comment by vaxXxa** [comment]
Oops. Ctrl–Shift–Power works well, but Ctrl–Shift–Eject or Option-Command-Eject doesn't. As I see in Karabiner-EventViewer, Eject isn't tracking by Karabiner. Am I right?

**Comment by Y-knot** [comment]
I reckon you use the embedded keyboard together with an external one. I never tried KE in such a setup. But my guess is that whatever key (power or eject) you have on the embedded keyboard, that only key will be recognized by macOS. The other one will be matched to the 'main' one, or just discarded. You cannot have both functioning at the same time, that's my wild guess.

**Comment by elad-maimon** [comment]
I don't use the embedded keyboard. I have Mac Pro so only the external (the small Apple wireless keyboard) is in use.
I think the issue is as @vaxXxa said that KE does not track the eject key (also saw that in the event viewer).

I understand there's a limitation to remap this key due to MacOS API, but KE should bypass the key press event.

**Comment by brianweber13** [comment]
I have this problem too, but my config is to make caps-lock my escape key when pressed by itself and my ctrl key when used in a chord. (I'm using wwwjfy's fork available at https://github.com/wwwjfy/Karabiner-Elements)

Attached is my json.
[karabiner.json.txt](https://github.com/tekezo/Karabiner-Elements/files/1027301/karabiner.json.txt)

**Comment by brianweber13** [comment]
I fixed this problem by mapping a different key to eject. Escape is mapped to eject, so now I hit control-shift-escape to lock my screen.
![new Karabiner config - successfully locks screen](https://cloud.githubusercontent.com/assets/25539219/26503247/2a6e5dbe-41fd-11e7-8f67-eac90e7c897c.png)

Perhaps this has something to do with karabiner recognizing the eject key getting pressed? Any other ideas? I hope to dig around in the source code later.

**Comment by elad-maimon** [comment]
Thanks @brianweber13, it works!

**Comment by brianweber13** [comment]
This problem has been well documented in #46 and #89 . Can we close this issue?

**Comment by elad-maimon** [comment]
Those other issues are still open, so sure, can't see a reason to have it duplicated.
Thanks!
