### ISSUE TITLE
Improve ISO Keyboard Layout

### ISSUE THREAD

**Issue by guycalledseven** [tekezo/Karabiner-Elements#51]
Coming from a decades of PC usage I am **completely lost** without Karabiner on Sierra and Karabiner's "Improve ISO Keyboard Layout" I was using.

Current fix to swap section key § with ` and plus minus ± with tilde ~ is a lifesaver:

```
"non_us_backslash": "grave_accent_and_tilde"
```

But, is it possible to make rest of old ISO settings in new karabiner.json ( '\' to additional Enter, '§' to '`' and '`' to '\' )?

Thanks in advance

**Comment by gammelby** [comment]
Thanks @guycalledseven, your hint on swapping  § with \` saved me from going completely nuts after Sierra upgrade. I had no idea to look at `non_us_backslash` and the new Karabiner-Elements does not yet let you input key strokes. Thanks again :-D!
