### ISSUE TITLE
Control key gets stuck when using control key combinations

### ISSUE THREAD

**Issue by Shaolo** [tekezo/Karabiner-Elements#510]
On Sierra 10.12.3 Beta (16D12b)

I am using a Razer BlackWidow Tournament Edition Chroma plugged in via USB and an Apple Wireless keyboard connected via BT.

When using the control key and the arrow keys to change desktops, the control key will get stuck. I have verified this with the Mac OS keyboard viewer. Pressing the alt-option key will unstick the control key. The control key also appears to stick when using any control-key combination. Sometimes it sticks permanently, sometimes it sticks for one more key press.

If I disable karabine-elements by unticking the keyboards in the Devices tab, the problem goes away. No more sticking.

 The sticking is 100% reproducible using the Razer keyboard. It's not as reproducible using the Apple Wireless keyboard.

**Comment by ianmartorell** [comment]
This is happening to me too.

**Comment by ianmartorell** [comment]
Uninstalling Razer Synapse makes the problem go away.

**Comment by euroclydon37** [comment]
This is happening to me as well.
I don't want to have to uninstall Synapse, but man it's a pain.

**Comment by ianmartorell** [comment]
It is a pain, but I didn't like Synapse anyway so I got rid of it. I'm now using Karabiner Elements for my key remapping needs and SmoothMouse to adjust my Deathadder's speed, and it works great!

**Comment by euroclydon37** [comment]
Are there any options for rgb control of the keys?
I'm not crazy about their software, either. I've yet to get macros to function correctly.

**Comment by ianmartorell** [comment]
Hmm I wouldn't know since my keyboard is not Chroma, but I bumped into this the other day, which looks awesome https://github.com/felixrieseberg/razer-chroma

**Comment by euroclydon37** [comment]
Dude... thank you for that. I use both Node and this keyboard daily.

**Comment by ianmartorell** [comment]
No problem 😄
