### ISSUE TITLE
How to map Fn+j to 1, Fn+k to 2, etc., in Elements?

### ISSUE THREAD

**Issue by peterpqa** [tekezo/Karabiner-Elements#514]
All I need is the basic old Karabiner prepared setting of using the Fn key to make j k l ; be 1 2 3 - and u i o p be 4 5 6 * and so forth. In Elements Preferences, I can select Fn *OR* j as a "from key," but not Fn+j. In EventViewer, pressing and releasing Fn and j are all separate events.

Me: MacBook Pro 17" mid-2010, 78-key keyboard, Sierra 10.12.2. Also, I'm using Elements version 0.90.55 - version 0.90.68 disabled my Caps-Lock key and slowed my system way down.

Any help? I went through the Elements usage readme and all the "issues" but I couldn't find anything. Hope the answer isn't embarrassingly simple...

Thanks, Peter

**Comment by Lismont** [comment]
I'm also interested if there is any way to recreate this with Karabiner-Elements

**Comment by diegodesouza** [comment]
check @watsoncj's repo [here](https://github.com/watsoncj/Karabiner-Elements/commit/5531032a309fe99e7e153cb725b9f44a19da69c0) he has hard code `fn+hjkl` for now, this might give you an idea on how to accomplish this? maybe...
