### ISSUE TITLE
Remapping Ç key

### ISSUE THREAD

**Issue by felipej** [tekezo/Karabiner-Elements#516]
It may come in as a feature request more than a bug but for spanish users on Mac, it is very common to want to replace the Ç key (which is right next to the enter key) to enter. 

This makes the keyboard more ergonomic while also making use of the Ç key which is not used in spanish (only in portuguese).

**Comment by miniBloq** [comment]
The annoying ç key is recognized by Karabiner as a "d" when pressed, and after having detected the keyboard as an European one. How can that key be remapped? Remapping it is the only reason in my case, for using Karabiner at all.

**Comment by jmojico** [comment]
This is not fixed :(
