### ISSUE TITLE
Don't put configuration folder into $HOME

### ISSUE THREAD

**Issue by z0rc** [tekezo/Karabiner-Elements#517]
Please, for the love of god, don't put configuration into `~/.karabiner.d`. There are more appropriate locations.

We're on macOS after all, there is ` ~/Library/Application Support` that original Karabiner actually used. Or, if you're going to mimic Linux approach, then use `$XDG_CONFIG_HOME` with fallback to `~/.config`, if this env var isn't set.

**Comment by tekezo** [comment]
#114
