### ISSUE TITLE
Leftover files after running uninstall.sh

### ISSUE THREAD

**Issue by jskrzypek** [tekezo/Karabiner-Elements#518]
FYI, after running `/Library/Application Support/org.pqrs/Karabiner-Elements/uninstall.sh`, there are a couple of leftover files that were not removed:

```sh
/Library/Application Support/org.pqrs/tmp:
   karabiner_grabber_devices.json
   karabiner_grabber_receiver
```

**Comment by fafuhrmeister** [comment]
There were 18 files left over after running the uninstall, two of which can't be removed.

**Comment by fafuhrmeister** [comment]
How do we remove these? This entire experience has been frustrating.

**Comment by tekezo** [comment]
These files do not affect your system but if you want to delete them, exectute the following command on terminal.

```shell
sudo rm -rf '/Library/Application Support/org.pqrs/tmp'
```

**Comment by fafuhrmeister** [comment]
As it turns out, this does not in fact remove the files in question.
The folder with the kext file is located here:
`/Library/StagedExtensions/Library/Application Support/org.pqrs/Karabiner-VirtualHIDDevice/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.v061000.kext`
