### ISSUE TITLE
Feature Request: Disable trackpad in Terminal app

### ISSUE THREAD

**Issue by djtracy** [tekezo/Karabiner-Elements#519]
Not related to keyboard specifically, but:

New laptops have very large trackpads, & Apple's heuristics for filtering unwanted events is not up to snuff. It would be very helpful  if, for a given list of applications, the trackpad is disabled completely. This would be very useful for Terminal, iTerm2, etc, where no mouse is needed.

Trackpad can already be disabled if a mouse is detected, but that won't help for on-the-go use.

**Comment by nonissue** [comment]
I don't really see this as being within the scope/ethos of this project at all. I'm just a casual observer here and have nothing to do with the development, but I think you'd be better served by something like Better Touch Tool.
