### ISSUE TITLE
using two keyboards simultaneously, modifier keys don't carry over

### ISSUE THREAD

**Issue by xirianlight** [tekezo/Karabiner-Elements#520]
I've been using Karabiner (and now Elements) primarily so that I can use two keyboards simultaneously while typing. My current setup is a USB Apple keyboard with numeric keypad and my laptop's built-in one. The problem I'm having now, which I had a few builds ago, is that if I hold down SHIFT or COMMAND on my external keyboard and try to type a letter on my built-in, the command doesn't execute. So for example:

• Hold shift on external keyboard, type letter A on built-in keyboard, I output "a"
• Hold Command on external keyboard, press Q on built-in keyboard, the app does not quit, I output a "q"

Any thoughts on this? I deleted my karabiner.json file, no change, uninstalled/reinstalled, no change.

**Comment by fantasticsid** [comment]
Same issue, I'm on 0.90.75

Also my fn -> Ctrl mapping only works on one keyboard (external keyboard but YMMV)

**Comment by mhulse** [comment]
I was looking to have two keyboards with modifier key syncing. Anyone know if this is still an issue? I wanted to setup two keyboards for ergonomic reasons.

**Comment by mhulse** [comment]
Out of curiosity, does anyone have any thoughts on what this would take to get working with Karabiner Elements? From everything I have read, this feature worked in the previous versions.

Also, did this feature work for Elements? Or just the previous versions of Karabiner?

**Comment by xirianlight** [comment]
I've got it working now, after having to uninstall a few times (including removing all support and plist files). It's working just fine on a MBP's internal keyboard and an Apple USB keyboard with numeric keypad. Currently on 0.90.86

**Comment by mhulse** [comment]
> I've got it working now, after having to uninstall a few times (including removing all support and plist files). It's working just fine on a MBP's internal keyboard and an Apple USB keyboard with numeric keypad. Currently on 0.90.86

Interesting! I have a MS Sculpt and an Apple bluetooth keyboard.

Should it just work out of box (assuming one does not need to remove plist, etc.)? Did you have to do anything special to set this up?

Thanks for the reply @xirianlight! I really appreciate it.

(My goal is to have two Apple keyboards for a split keyboard setup for ergonomic reasons. If this works, I'm going to be ecstatic (considering the current selection of split keyboards on the marketplace is pretty limited).)

**Comment by mhulse** [comment]
Ok, wow, that does work! I am not sure what happened, but testing it again for a second time and it started working! I am don't remember if I restarted my computer or not, but it works now!!!! This is so effing cool!

Thank you @xirianlight for kicking me in right direction!

I hope this also helps the OP too. 👍

**Comment by weiweihuanghuang** [comment]
Sorry to open an old issue, but do you know if this work across multiple external keyboards ?
