### ISSUE TITLE
The virtual keyboard may break the long press key repeat function.

### ISSUE THREAD

**Issue by ITJesse** [tekezo/Karabiner-Elements#521]
It happened suddenly.
When I long press a key, it will display a alternate characters selector like this:

![image](https://cloud.githubusercontent.com/assets/3601376/21512022/7cf6321e-cceb-11e6-9c50-38322e2ac120.png)

I have followed the instructions in [this page](http://www.idownloadblog.com/2015/01/14/how-to-enable-key-repeats-on-your-mac/) but take no effect.

Finally I uninstalled the Karabiner-Elements, the long press repeat function get back.

**Comment by datico** [comment]
Interestingly, my long press is still working to show alternate characters (I recently uninstalled and reinstalled karabiner-elements to fix another issue, maybe that helped). 

However long press key repeat does not work. Seeing long-press alternate characters working, I wonder if this is just an OS issue (even though I can see key repeat settings enabled in System Prefs > Keyboard, I don't see options to enable/disable long press for accented chars, nor can imagine how Apple intended both features to work simultaneously). I don't use long press key repeat much so I hadn't noticed when this functionality went away, and if it is OSX or Karabiner perhaps.

**Comment by ITJesse** [comment]
It seems not the problem of Karabiner itself.
May caused by the  Vim plugin of VS Code, and below is the solution by its developer:

```
Mac setup

If key repeating isn't working for you, execute this in your Terminal.

defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false         # For VS Code
defaults write com.microsoft.VSCodeInsiders ApplePressAndHoldEnabled -bool false # For VS Code Insider
We also recommend going into System Preferences -> Keyboard and cranking up the Key Repeat and Delay Until Repeat settings to improve your speed.
```

But I still don't know why I can solve it by uninstall Karabiner.
BTW, I close it.
