### ISSUE TITLE
Is it possible to remap to combination keys ?

### ISSUE THREAD

**Issue by x4080** [tekezo/Karabiner-Elements#526]
For instance, home key to Cmd-Up ?

Thanks

**Comment by medopaw** [comment]
I have the same question for mapping fn+hjkl to arrow keys.

**Comment by ctrlShiftBryan** [comment]
same questions here

**Comment by Anzumana** [comment]
not sure if its possible yet. it certainly was with the old karabiner and seil.

**Comment by firedev** [comment]
Oooh Fn + HJKL would be just perfect.

**Comment by Anzumana** [comment]
check two if the pull requests that are open.
even though they are not fully done yet maybe this could provide a short term solution if you need to
