### ISSUE TITLE
No keyboard mapping at all anymore after update to 0.90.70 and reboot

### ISSUE THREAD

**Issue by vincent314** [tekezo/Karabiner-Elements#527]
Hi,

I use Karabiner-elements for 8 months now to remap my typematrix 2030 keyboard with this simple mapping to mimic standard mac keyboard :

- left-option --> left-cmd
- left-cmd --> left-option

However, this mapping is broken — and any other mapping I tested — since the update to Karabiner-element 0.90.70 and reboot. It don't stop logging these two lines :

`[2016-12-31 11:21:10.070] [warning] [grabber] event_manipulator_ is not ready. (virtual_hid_device_client is not ready) Please wait for a while.`

Macos version 10.12.2

**Comment by tekezo** [comment]
What's the result of this command in Terminal?

```
sudo kextload /Library/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.kext
```

**Comment by vincent314** [comment]
Hi, thank you for your reply ...

This command do nothing at all and return to prompt.

**Comment by vincent314** [comment]
OK, I just uninstalled / reinstalled Karabiner + reboot … works fine now. I keep that in mind for next updates. Sorry for the inconvenience, and great work anyway !

**Comment by jasongardnerlv** [comment]
Same issue here, and also resolved by reinstall and reboot.  Same Macos version and log output at @vincent314

**Comment by captainEli** [comment]
Also had to reinstall and reboot on MacOS version 10.12.2. Thanks!

**Comment by esambo** [comment]
I got it to work with 0.90.73 (and partially with 0.90.75), see https://github.com/tekezo/Karabiner-Elements/issues/448#issuecomment-271209309
