### ISSUE TITLE
Fn keys work only once then die

### ISSUE THREAD

**Issue by guycalledseven** [tekezo/Karabiner-Elements#53]
I have Apple Keyboard with Numeric Keypad - English (USA) and after starting Karabiner Elements I can press Fn keys only **ONCE**, after key performs function all Fn keys enter strange state - eg F5/F6 become brightness up/down, F3/F4 do nothing....

Eg. brightness can be set only once and then Fn keys go crazy.
If I exit Karabiner Elements, Fn keys work again.

This happens with or without config.

When they "die" event viewer give me this:
F1 - 0x3
F2 - 0x2
F3 - **nothing**
F4 - **nothing**
F5 - 0x16
F6 - 0x15
F7 - 0x12
F8 - 0x10
F9 - 0x11
F10 - 0x7
F11 - 0x1
F12 - 0x0

edit: more details. fn keys are not dead, just misplaced?

**Comment by hirakujira** [comment]
v0.90.33 works perfectly except F3 and F4 (Mission Control / Launch Pad). These two keys still dying.

**Comment by tekezo** [comment]
Thank you for feedback!
I've fixed this issue at v0.90.34.

Please upgrade to the latest version from "Misc > Check for updates" or 
https://pqrs.org/latest/karabiner-elements-latest.dmg

**Comment by guycalledseven** [comment]
@tekezo no, thank you! for awesome work.
oh and wow 0.90.36 is up!
