### ISSUE TITLE
Kinesis Keyboard Issues

### ISSUE THREAD

**Issue by ammoman** [tekezo/Karabiner-Elements#532]
The Kinesis Keyboard for Mac has copy/paste/cut etc keys. They work correctly in Sierra when Karabiner is not running (they issue a left_command then 'c').  But when Karabiner is running the 'c' is received first than the left_command, which results in replacing selected text with 'c'.

Also, this keyboard has previous, play/pause and next keys that I need to remap.  They show as Syskey 0x12, 0x10 (play_or_pause) and 0x11.  I don't see any way in Karabiner-Elements to remap these keys.

Here are the logs from the EventViewer:

When not running, pressing the Copy key:
eventType:FlagsChanged    code:0x37       name:left_command    flags:Cmd                                misc:characters:    
eventType:KeyDown         code:0x8        name:c               flags:Cmd                                misc:characters:    
eventType:FlagsChanged    code:0x37       name:left_command    flags:                                   misc:characters:    
eventType:KeyUp           code:0x8        name:c               flags:                                   misc:characters:    

When running Karabiner-Elements, pressing the Copy key:
eventType:KeyDown         code:0x8        name:c               flags:                                   misc:characters:    
eventType:FlagsChanged    code:0x37       name:left_command    flags:Cmd                                misc:characters:    
eventType:KeyUp           code:0x8        name:c               flags:Cmd                                misc:characters:    
eventType:FlagsChanged    code:0x37       name:left_command    flags:                                   misc:characters:    

Finally the previous, play/pause and next keys:
eventType:SysKeyDown      code:0x12       name:                flags:                                   misc:
eventType:SysKeyUp        code:0x12       name:                flags:                                   misc:
eventType:SysKeyDown      code:0x10       name:play_or_pause   flags:                                   misc:
eventType:SysKeyUp        code:0x10       name:play_or_pause   flags:                                   misc:
eventType:SysKeyDown      code:0x11       name:                flags:                                   misc:
eventType:SysKeyUp        code:0x11       name:                flags:                                   misc:

**Comment by ammoman** [comment]
Version 0.90.73 fixed the Copy key issues!

Now I only need the ability to map the previous, play/pause and next keys.

**Comment by jppolk** [comment]
Hello, the same thing happens to me I have a Rantopad MXX keyboard, and it has media keys under the function keys that stop working while Karabiner is running is there a way to fix it?

Here are my logs from EventViewer, there are others that dont even capture like (play pause) :
eventType:SysKeyDown      code:0x7        name:mute            flags:                                   misc:
eventType:SysKeyUp        code:0x7        name:mute            flags:                                   misc:
eventType:SysKeyDown      code:0x1        name:volume_decremen flags:                                   misc:
eventType:SysKeyUp        code:0x1        name:volume_decremen flags:                                   misc:
eventType:SysKeyDown      code:0x0        name:volume_incremen flags:                                   misc:
eventType:SysKeyUp        code:0x0        name:volume_incremen flags:                                   misc:

**Comment by ammoman** [comment]
Looks like some progress has been made on this - the media keys are now being mapped properly:

rewind, play_or_pause, fastforward

However, I haven't been able to remap these keys to their functional keys.  I tried this simple modification without any luck: (they still do their original function)

            "simple_modifications": {
                "rewind": "f5",
                "play_or_pause": "f6",
                "fastforward": "f7"
              }

**Comment by ammoman** [comment]
Downloaded the latest beta, and this simple remapping still doesn't work.  Anything I can do to help get this resolved?

**Comment by siff-duke** [comment]
I'm getting a different events on my Kinesis Freestyle2 for Mac keyboard:

When pressing copy button:

eventType:KeyDown         code:0x30       name:tab             flags:                                   misc:
eventType:KeyUp           code:0x30       name:tab             flags:                                   misc:

when pressing paste button:

eventType:KeyDown         code:0x30       name:tab             flags:                                   misc:
eventType:KeyUp           code:0x30       name:tab             flags:                                   misc:

Weird that it would send the same code. When I quit karabiner, it would work.

I'm using the Karabiner-Elements version 11.5.0
