### ISSUE TITLE
0.90.72 made the shift and ctrl keys not working in some games.

### ISSUE THREAD

**Issue by pleasenophp** [tekezo/Karabiner-Elements#533]
It's macOS Sierra 10.12.2 here and after updating to 0.90.72 the SHIFT and CTRL keys stopped working in the Bioshock Infinite. It worked perfectly for previous versions. Uninstalling the karabiner-elements makes it work again. Installing the karabiner-elements 0.90.72 again breaks it.

The only modification I use in the karabiner-elements is mapping CAPS LOCK to the F19 in "simple modifications".

**Comment by Yona-Appletree** [comment]
I have a similar issue where Cmd+Function keys don't work while Karabiner-Elements is running. I use Cmd+F9 in IntelliJ quite often, so this is a bit of a deal breaker.
