### ISSUE TITLE
Can't use (cmd|shift|option|ctrl) + Fn with MacBook Pro 2016 with Touch Bar

### ISSUE THREAD

**Issue by welladamm** [tekezo/Karabiner-Elements#535]
For example, when pressing Shift + F6, my app (WebStorm) acts as if only F6 were pressed and Shift is ignored completely.

Below is my only configuration:

![image](https://cloud.githubusercontent.com/assets/319494/21631738/f992b2be-d279-11e6-8bf9-33bc28c4778a.png)

**Comment by vjpr** [comment]
I am seeing this behaviour with other modifiers too such as cmd. It breaks a lot of keyboard shortcuts in IntelliJ for me.

On the `Function Keys` tab, I tried mapping each fn key to fn1-12 and it didn't work. Toggling the `Use standard function keys` didn't work either.

**Comment by keith-han** [comment]
I have same problem. When will be this fixed?

**Comment by dstandish** [comment]
I am seeing this as well....

**Comment by geoHeil** [comment]
Same here. But https://medium.com/@geapi/permanent-function-keys-intellij-macbook-pro-w-touchbar-d6fc78781b90 worked for me.

**Comment by chopachom** [comment]
Having the same issue as OP with exactly the same configuration. Modifier keys don't work with function keys. Karabiner-Elements version is 0.91.8 macOS Sierra 10.12.5 (16F73) MacBook Pro (15-inch, 2016)

**Comment by k--kato** [comment]
Karabiner-Elements 0.91.8
macOS Sierra 10.12.5
Touch bar

* Cmd + f7
  * Karabiner-Elements ON
    * f7 + Fn
  * Karabiner-Elements OFF
    * f7 + Cmd + Fn

**Comment by lindsaymarkward** [comment]
Same. I tried the link @geoHeil  provided, but it just showed the Fn 'keys', and their behaviour was the same, e.g. Shift+F6 causes the action F6 causes... Shift has no effect. Also tried what @dstandish said, but didn't change this.
Any solutions? I only use Karabiner to map my caps lock to back space.

**Comment by viniciusmo** [comment]
Same problem here :(

**Comment by subicura** [comment]
:+1:

**Comment by Kxrr** [comment]
Same issue here, shortcuts like `Command + F1` acting like `F1` when Karabiner-Elements is up.

**Comment by mohammedri** [comment]
Following, cause I have the same issue. Modifiers don't work.

**Comment by gAmUssA** [comment]
@tekezo do you have any ETA to look at this?

**Comment by KaHa6uc** [comment]
Same here. I have to go to Menu -> Edit -> Fill... in Photoshop instead of pressing Shift+F5. Most irritating. I had already done what @geoHeil suggested so it's not a fix - it only defines for which applications to show the function keys in the TouchBar by default.

**Comment by lindsaymarkward** [comment]
I searched (again) for an alternative solution and found a blog post about remapping keys with the `hidutil`. Since I only want to remap caps lock to delete/backspace for Colemak, I now have this working without additional software 👍 
http://homeowmorphism.com/articles/17/Remap-CapsLock-Backspace-Sierra

**Comment by kurguzov** [comment]
Thank you very much! Now I don't need to choose between touchbar and Karabiner-Elements!

**Comment by KaHa6uc** [comment]
+1 - `hidutil` fixed my problem as well. Thank you, @lindsaymarkward

**Comment by lindsaymarkward** [comment]
I might add that you should _not_ use macOS keyboard settings to change caps lock to do nothing, or this hidutil solution stops working. I guess the OS doesn't receive the key event or something.

**Comment by mbarczak** [comment]
👍  for hidutil, also solved my problem. Btw, here : https://opensource.apple.com/source/IOHIDFamily/IOHIDFamily-247/IOHIDFamily/IOHIDUsageTables.h , in section _KeyboardOrKeypad Page (0x07)_ can be found all valid usage ID’s. Helped me with _kHIDUsage_KeyboardNonUSBackslash_

**Comment by KaHa6uc** [comment]
Yes, it took me some time debugging event to realise that I can't understand how § and ± qualify as `0x64,	/* Non-US \ or | */`
Not to mention that Karabiner's keylogger reported this key as `0xa` ...

**Comment by mutantcornholio** [comment]
I think, I've got this 'fixed' by enabling this keyboard in settings:
![2017-12-10 06-09-31](https://user-images.githubusercontent.com/588262/33801604-39c32dc0-dd71-11e7-9907-1e8ef68e8f53.png)

It's probably the touchbar "keyboard" which sends keys to Mac OS. 
Can someone verify this?

**Comment by kasecato** [comment]
@mutantcornholio Plus, setting the function keys to the default Touch Bar display and use all Fn keys as as standard, it worked on my IntelliJ.
<img width="380" alt="keybord_functionkeys" src="https://user-images.githubusercontent.com/10364603/33811590-bb2e5050-de58-11e7-8fa2-867732d9aef9.png"><img width="400" alt="karabiner_useallf1f2" src="https://user-images.githubusercontent.com/10364603/33811591-bb560a32-de58-11e7-9db4-fc6a113a74e2.png">

**Comment by gAmUssA** [comment]
@kasecato @mutantcornholio doesn't work for me

**Comment by kasecato** [comment]
@gAmUssA You can check Karabiner EventViewer like below images.
- No Product Name ON (Shift + Cmd + F7)
<img width="400" alt="noproductnameon" src="https://user-images.githubusercontent.com/10364603/33865746-72b8f2e2-df36-11e7-814a-5c81ac88d9c7.png">
- No Product Name OFF (Shift + Cmd + F7)
<img width="400" alt="noproductnameoff" src="https://user-images.githubusercontent.com/10364603/33865747-72e28daa-df36-11e7-9c80-024e9abc7abf.png">

**Comment by zbstof** [comment]
Here's a gist that does what I want in hidutil:
https://gist.github.com/zbstof/6cba7d54e105cc5148c8a943d1581cad

**Comment by j-martin** [comment]
Confirming @mutantcornholio suggestion worked great! Thanks! Have some TP.

**Comment by dmk255** [comment]
confirming @mutantcornholio works as well

**Comment by welladamm** [comment]
Guys, I just found that @mutantcornholio's solution has a drawback: the two screen  brightness buttons now don't work without pressing the Fn button. Are you guys experiencing the same problem? 

Thanks!

**Comment by mutantcornholio** [comment]
Yep, nothing's appear at EventViewer when pressing those is Karabiner-Elements is launched. Otherwise, works okay.

**Comment by j-martin** [comment]
@welladamm actually yes, I just assumed it was broken for another reason. My workaround is to use the brightness slider instead.

**Comment by roryokane** [comment]
After enabling modification of the untitled keyboard as [@mutantcornholio suggests](https://github.com/tekezo/Karabiner-Elements/issues/535#issuecomment-350522019), I had to do one more change for F1 to work as normal instead of lowering the brightness. I had to *uncheck* the “Use all F1, F2, etc. keys as standard function keys” checkbox at the bottom of the Function Keys tab (the opposite of [@kasecato’s setting](https://github.com/tekezo/Karabiner-Elements/issues/535#issuecomment-350597725)). This is with my “Touch Bar shows” setting at “App Controls with Control Strip”, so that the F1 key only shows when I am already holding Fn.

**Comment by bosschaert** [comment]
While the `hidutil` approach works for some situations, I'm not sure it works for all. For example, I tend to remap the capslock key to a mouseclick. This is something I can do with Karabiner, but not with `hidutil` I think. Additionally, using `hidutil` is nowhere near as user-friendly as Karabiner. 

In the not too distant future nearly all Macbook Pro users will have a touch bar. If Karabiner doesn't work with the touchbar and key modifiers, then nearly all users won't be able to use it any more...?

I would suggest to fix this issue in Karabiner, not just close it because of inactivity.

**Comment by studgeek** [comment]
I filed #1700 as a feature request to have that keyboard enabled by default.

**Comment by GalphaXie** [comment]
> @mutantcornholio Plus, setting the function keys to the default Touch Bar display and use all Fn keys as as standard, it worked on my IntelliJ.
> <img alt="keybord_functionkeys" width="380" src="https://user-images.githubusercontent.com/10364603/33811590-bb2e5050-de58-11e7-8fa2-867732d9aef9.png"><img alt="karabiner_useallf1f2" width="400" src="https://user-images.githubusercontent.com/10364603/33811591-bb560a32-de58-11e7-9db4-fc6a113a74e2.png">

Thx, it‘s helpful for me!
