### ISSUE TITLE
0.90.72 made my right_command to right_option stop working

### ISSUE THREAD

**Issue by bpasero** [tekezo/Karabiner-Elements#536]
This worked perfectly fine before! I am on macOS 10.12.2

**Comment by scareddragon** [comment]
Same here, log tab shows this all the time:

`
[2017-01-04 10:23:02.041] [warning] [grabber] event_manipulator_ is not ready. (virtual_hid_device_client is not ready) Please wait for a while.
[2017-01-04 10:23:03.139] [warning] [grabber] event_manipulator_ is not ready. (virtual_hid_device_client is not ready) Please wait for a while.
`

**Comment by tekezo** [comment]
There is an issue that reinstall and reboot is required in some environment.
https://github.com/tekezo/Karabiner-Elements/issues/527

**Comment by thymara** [comment]
same issue as scareddragon. the solution that works for me is to force quit grabber

**Comment by bpasero** [comment]
I can confirm that a reinstallation helped!

**Comment by 80m** [comment]
Activity Monitor -> karabiner_grabber -> Force quit

**Comment by fiedl** [comment]
I've tried:

1. Activity Monitor -> karabiner_grabber -> Force quit
2. Reinstall karabiner-elements
3. Uninstall - reboot - reinstall

Only *3. Uninstall - reboot - reinstall* solved the issue for me.
