### ISSUE TITLE
Caps -> Esc regression

### ISSUE THREAD

**Issue by javigon** [tekezo/Karabiner-Elements#538]
On a Retina, 13-inch, Early 2015 caps to esc remap stopped working after the last update.

Any ideas?

Javier

**Comment by facundolaffont** [comment]
I have the same issue. MacBook Pro Retina, 15-inch, Mid 2015. All the remaps I had made are not working anymore, indeed.

**Comment by javigon** [comment]
Could you make the last stable version available for download?

Thanks

**Comment by javigon** [comment]
@facundolaffont Uninstalling and installing again worked for me. If it works for you comment and I'll close the issue.

**Comment by facundolaffont** [comment]
🙌
It worked !! First, I reinstalled Karabiner-Elements without deleting it, in order to see if it was enough to make it work, but it didn't work. So, I uninstalled the software from 'Misc' -> 'Launch Uninstaller' and then I reinstalled it, again, and it worked !

**Comment by javigon** [comment]
Cool. Same here :)

**Comment by wilsongis** [comment]
Worked for me. Thanks for posting

**Comment by mbaltrusitis** [comment]
Worked for me as well but through Homebrew.

```bash
rm -fr /usr/local/Caskroom/karabiner-elements
brew cask install karabiner-elements
```

My old configuration worked without issue.
