### ISSUE TITLE
Remap 'fn' to 'Ctrl' only for regular keys. Make it work as 'fn' for Fx keys (F1, F2, F3).

### ISSUE THREAD

**Issue by DenKoren** [tekezo/Karabiner-Elements#547]
Old Karabiner had special option for 'fn' key remap: make it work as 'ctrl' only for regular symbols (letters, numbers, etc.) but leave it work as original 'fn' with function keys (F1, F2, F3, ...). It was very useful, since if you use only english layout - you don't need to use 'fn' for regular letters, but you may need to use the button with Fx keys sometimes and it is very convenient to do it with regular 'fn' button.

**Comment by huoguangjin** [comment]
and fn+delete

**Comment by gingray** [comment]
Guys plz take a look on this issue bcz thats really important stuff. Thank you.

**Comment by msyeed** [comment]
Hoping to revive this ancient request, but I can't figure out how to restore this functionality in an elegant way.

**Comment by MartinPacker** [comment]
Globe key in iPad OS 15 is something that will inspire people to want to use Fn as a hyperkey (with the proviso the current uses of it continue to work.)

**Comment by MuhammedZakir** [comment]
For now: you can add complex modification for `fn + Fx` keys, and **below** that, add modification rule for `fn` to `Ctrl`.
