### ISSUE TITLE
Capslock Key on old Apple Keyboard (M3501)

### ISSUE THREAD

**Issue by nonissue** [tekezo/Karabiner-Elements#549]
I used to be able to use Seil / Karabiner to map the Capslock key on my Apple Extended II (M3501) to control. I physically moved the locking switch to another place, so the Capslock currently has a regular non-locking switch. With karabiner elements, I don't seem to be able to replicate this functionality. Is there a way to do it?

Edit: Previously I would bind capslock to key code 110 with seil (PC Application) and then use karabiner to bind PC Application -> Control if that makes sense. And it worked well.

Here's a link to someone else's previous karabiner version json file where they accomplished this: https://github.com/brow/dotfiles/blob/master/private.xml

There's also an overview here as well:
https://geekhack.org/index.php?topic=56813.0

Any help would be greatly appreciated.

**Comment by mweisman** [comment]
I recently upgraded my MacBook Pro to Sierra, requiring me to also move to Karabiner-Elements. As far as I can tell there is no way to use my old private.xml with elements and no way to re-impliment my private.xml (very similar to the one linked above) in the new karabiner.json config.

My muscle memory still thinking that Caps Lock is a control key is driving me nuts. Is there a bug bounty program? I'd happily chip in to have this regression fixed.

**Comment by robertofarrell** [comment]
I'm wondering if there's a solution to this as well.  Did anyone find a way to fix this?
