### ISSUE TITLE
Can give me a 「Use Japanese Keyboard as US Keyboard」 sample?

### ISSUE THREAD

**Issue by yetone** [tekezo/Karabiner-Elements#55]

**Comment by junhocho** [comment]
If you have japanese keyboard and want to remap as english keyboard:

i had this trouble, so I changed US Keyboard to UK keyboard in mac setting.
It's working for the moment .

**Comment by yetone** [comment]
@junhocho thx

**Comment by alonecong** [comment]
i want to remap english keyboard too ! who can give me the configeration in the json file .

**Comment by imcoddy** [comment]
I guess you can check #88 first, I will have a try later when I get the chance.

**Comment by junhocho** [comment]
i changed to Australian keyboard to move UK keyboard `<shift-3>` £ to #
And i share my json
```
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": { 
                "caps_lock": "left_control",  
                "japanese_kana" : "keypad_enter",
                "international1" : "grave_accent_and_tilde",
                "left_control" : "vk_mission_control"

            }
        }
    ]
}
```
`international1` means just left key of `Right-shift`
add `japanese_eisuu` if you need
i didn't change japanese yen yet

reference if you need: https://github.com/tekezo/Karabiner-Elements/blob/343e06705210b3808bcf298cbb4522564088dc6d/src/share/types.hpp

**Comment by yetone** [comment]
@junhocho thank you!

**Comment by xinmei9322** [comment]
@junhocho Thanks! By the way, do you know how to change japanese yen key? What's its name in the json file? I used to map it to backslash in the past. But now it doesn't work.

**Comment by junhocho** [comment]
international3 is yen key. Your option would be 

`"international3" : "backslash"`

**Comment by junhocho** [comment]
You can see which key stroke is mapped using Karabiner-EventViewer.
Yen key stroke is `0x5d` and is specified in the `types.hpp` line 601
> `      map[key_code(kHIDUsage_KeyboardInternational3)] = 0x5d;`

**Comment by xinmei9322** [comment]
@junhocho Thanks a lot!!! It works.
