### ISSUE TITLE
Selectively apply modifications to specified devices?

### ISSUE THREAD

**Issue by 599316527** [tekezo/Karabiner-Elements#550]
![untitled-1](https://cloud.githubusercontent.com/assets/1331413/21847319/2db7100a-d836-11e6-8635-3ff360ac32ed.jpg)

**Comment by tkil** [comment]
Could we also expose the per-application feature from Karabiner?  Dunno if this is worth a separate issue or not...

(Maybe the right answer is to wait for Karabiner to be updated once -Elements is stable, but... I'm greedy.  :-(  )

My use case is laptop + external kinesis keyboard.
internal keyboard: keys are native (other than ctrl / caps-lock swap), then use iterm2 to remap cmd to meta.
kinesis keyboard: need to swap opt and cmd to cmd and opt in most apps, but want to keep them as opt and cmd in iterm2 (so they become ctrl and meta in iterm2).

My old `private.xml` is at: https://paste.fedoraproject.org/529350/84725098/

**Comment by starsy** [comment]
@tkil @599316527 I have made some enhancements to KBE to support per device configuration within the same profile. Please check if this helps: https://github.com/tekezo/Karabiner-Elements/issues/770 Any questions please let me know.


![image](https://user-images.githubusercontent.com/1459979/26891802-dd782b52-4be8-11e7-8380-5aa0703b6fa9.png)

**Comment by tkil** [comment]
@starsy -- Thanks for the update!

Unfortunately, I don't think this will help me: I want the same device to behave differently, depending on which application I'm currently in.
