### ISSUE TITLE
KeyRepeat tab is gone

### ISSUE THREAD

**Issue by demircancelebi** [tekezo/Karabiner-Elements#551]
What's the reason behind removing the Key Repeat tab?

**Comment by tekezo** [comment]
Karabiner-Elements use virtual keyboard to post key events since v0.90.69.
(We have to use the virtual keyboard to support sticky modifiers in Accessibility features.)

Apple does not provide a way to change the key repeat rate of keyboard devices.
Thus, the key repeat configuration was vanished.

**Comment by jackzampolin** [comment]
Is there any way to re-add this feature? Something I really enjoyed!

**Comment by demircancelebi** [comment]
Hi @jackzampolin,
You can build the v0.90.68 from the source code as I did :)

**Comment by tekezo** [comment]
You can do it by `defaults` command without Karabiner-Elements.
(You have to logout and login to apply the setting.)

Example:
```
defaults write NSGlobalDomain KeyRepeat -int 10
```

**Comment by demircancelebi** [comment]
I do not know how Karabiner-Elements does it but I am able to set the KeyRepeat and InitialKeyRepeat from the Karabiner-Elements UI with a much more responsive feeling compared to editing the defaults. Is it just changing the defaults under the hood?

**Comment by aristidesfl** [comment]
`NSGlobalDomain KeyRepeat` and `NSGlobalDomain InitialKeyRepeat` don't seem to affect my system (karabiner elements currently installed) 

macOS 10.11.6
