### ISSUE TITLE
F key to volume control mapping broken

### ISSUE THREAD

**Issue by Kerry-Maxwell** [tekezo/Karabiner-Elements#552]
It seems a recent update broke my keymapping of F11 and F12 to volume controls. I can map fn+PgUp/ PgDwn to volume, but the previously functional F keys no longer work. OS X 10.12.2 , Karabiner Elements 0.90.76, WASD Mechanical keyboard.

**Comment by simo2409** [comment]
Exactly same configuration here. I noticed the problem from a couple of days (so more or less by 2 versions ago)
