### ISSUE TITLE
remap to FN broken

### ISSUE THREAD

**Issue by matteszk** [tekezo/Karabiner-Elements#557]
Before updating today, had delete_forward mapped to mac FN key. No longer works. Other keys also can not map to FN.

**Comment by jbmorgado** [comment]
I think I'm having a similar problem. On my external USB keyboard (Drevo Gramr 84) the `Fn` key press can't be seen as an event by Karabiner-EvenViewer and doesn't work in any Karabiner-Elements configuration.
