### ISSUE TITLE
Prevents double press of shift registering in RubyMine

### ISSUE THREAD

**Issue by mattgibson** [tekezo/Karabiner-Elements#56]
Without Karabiner elements, Rubymine (and other JetBrains IDEs) use a quick double press of the shift key as a shortcut to open the "search everywhere" dialogue. With Karabiner installed on OSX Sierra, this no longer works.

Is there something configurable that could sort this out?

Thanks for an awesome utility BTW.

**Comment by tekezo** [comment]
Thank you for feedback!
I believe this issue has been fixed at v0.90.33.

Please upgrade to the latest version from "Misc > Check for updates" or 
https://pqrs.org/latest/karabiner-elements-latest.dmg

**Comment by jasonm23** [comment]
@mattgibson TIL thank you

**Comment by mattgibson** [comment]
Seems to work fine now. Thanks for the super fast fix!
