### ISSUE TITLE
Discussion Forum?

### ISSUE THREAD

**Issue by DennisSchiefer** [tekezo/Karabiner-Elements#560]
I've been seeing a lot issues posted (mine included) that are not issues for Karabiner-Elements per se, but questions about how to use the tool or about remapping keys in general.

Would it make sense to open a discussion forum to redirect such posts to (unless there already is one that I am not aware of)?

**Comment by nikitavoloboev** [comment]
I would love for there to be a discussion forum for all keyboard remapping enthusiasts. Perhaps one can make one and host with [Discourse](https://github.com/discourse/discourse)? It would be really awesome to see, I think.

**Comment by supine** [comment]
https://groups.google.com/forum/#!forum/osx-karabiner
