### ISSUE TITLE
Different device

### ISSUE THREAD

**Issue by JefferyVin** [tekezo/Karabiner-Elements#562]
Hope I can use windows as option and option on my external keyboard.
and don't need to reset it while i just my MacBook pro build in keyboard.
XD

**Comment by starsy** [comment]
@JefferyVin I have made some enhancements to KBE to support per device configuration within the same profile. Please check if this helps: https://github.com/tekezo/Karabiner-Elements/issues/770 Any questions please let me know.


![image](https://user-images.githubusercontent.com/1459979/26891802-dd782b52-4be8-11e7-8380-5aa0703b6fa9.png)
