### ISSUE TITLE
Support for caret (^) and angle brackets (<, >)

### ISSUE THREAD

**Issue by JojoSc** [tekezo/Karabiner-Elements#563]
Please add support for '^' and '<' keys

**Comment by zuckschwerdt** [comment]
Look at the last example on https://github.com/tekezo/Karabiner-Elements/blob/master/usage/README.md
Swap `non_us_backslash` and `grave_accent_and_tilde`.
It doesn't work for me though. I used to swap those keys using `GERMAN_LESS_THAN` and `GERMAN_CIRCUMFLEX` in Karabiners private.xml.

**Comment by JojoSc** [comment]
`non_us_backslash` and `grave_accent_and_tilde`worked for me

**Comment by foss-** [comment]
Need to change ^° and <> key on a keyboard with german keyboard layout. When adding a simple modification, I can not see those characters in the list. Tried the suggestion from comment 3 without success. Any idea how that would be handled?

**Comment by zuckschwerdt** [comment]
Perhaps my comment was to brief. Here is the working swap for german keyboards:
```
cat ~/Library/Application\ Support/Karabiner/private.xml

<?xml version="1.0"?>
<root>
  <item>
    <name>Swap Less-Than and Circumflex</name>
    <identifier>private.swap_lessthan_and_circumflex</identifier>
    <autogen>__KeyToKey__ KeyCode::GERMAN_LESS_THAN, KeyCode::GERMAN_CIRCUMFLEX</autogen>
    <autogen>__KeyToKey__ KeyCode::GERMAN_CIRCUMFLEX, KeyCode::GERMAN_LESS_THAN</autogen>
  </item>
</root>
```

**Comment by MuhammedZakir** [comment]
@zuckschwerdt : XML configuration is used in older version. Latest versions use JSON. 

> Need to change ^° and <> key on a keyboard with german keyboard layout. When adding a simple modification, I can not see those characters in the list. Tried the suggestion from comment 3 without success. Any idea how that would be handled?

You can get key code of a key/button with EventViewer [1].

[1] Karabiner-Elements menu > `Launch EventViewer` or `Karabiner-EventViewer.app`.

**Comment by zuckschwerdt** [comment]
@MuhammedZakir how embarrassing, Karabiner works so smoothly* I totally forgot about that change. I currently use a mapping of `"from": {"key_code": "grave_accent_and_tilde"}, "to": {"key_code": "non_us_backslash"}` and `"from": {"key_code": "non_us_backslash"}, "to": {"key_code": "grave_accent_and_tilde"}`

(*) the only feature missing is the ability to read HID CONSUMER events from an alternate interface, I use a small helper to translate the media keys for that.

**Comment by MuhammedZakir** [comment]
> (*) the only feature missing is the ability to read HID CONSUMER events from an alternate interface, I use a small helper to translate the media keys for that.

@zuckschwerdt: Can you please share the script? That will be helpful! :-)

**Comment by zuckschwerdt** [comment]
> Can you please share the script?

It's just a simple C program tailored for the Microsoft Ergo 4000. It opens the alternate interface (`Page 12 (Consumer), Usage 1 (Consumer Control)`, instead of `Page 1 (Generic Desktop Controls), Usage 6 (Keyboard)`) and maps specific events. E.g. CONSUMER `0x01, 0x2e, 0x02` (ZOOM_OUT) to `tap_key(48, LCMD | LSHIFT)`. I doubt anyone else needs exactly that mapping ;)

**Comment by MuhammedZakir** [comment]
> > Can you please share the script?
> 
> It's just a simple C program tailored for the Microsoft Ergo 4000. It opens the alternate interface (`Page 12 (Consumer), Usage 1 (Consumer Control)`, instead of `Page 1 (Generic Desktop Controls), Usage 6 (Keyboard)`) and maps specific events. E.g. CONSUMER `0x01, 0x2e, 0x02` (ZOOM_OUT) to `tap_key(48, LCMD | LSHIFT)`. I doubt anyone else needs exactly that mapping ;)

Actually, I really like to look at other's code and see how they do it. 😉  Besides, I think the script may help people who are not familiar with programming; they will know where to start and how to do it. :-) Anyway, it was just to satisfy my curiosity! 😄

**Comment by matija2209** [comment]
> @zuckschwerdt : XML configuration is used in older versions. Latest versions use JSON.
> 
> > Need to change ^° and <> key on a keyboard with german keyboard layout. When adding a simple modification, I can not see those characters in the list. Tried the suggestion from comment 3 without success. Any idea how that would be handled?
> 
> You can get key code of a key/button with EventViewer [1].
> 
> [1] Karabiner-Elements menu > `Launch EventViewer` or `Karabiner-EventViewer.app`.

Unless the key physically doesn't exist on the keyboard.

**Comment by matija2209** [comment]
On Mac I and keyboard missing dedicated key I had to find workaround where you press xz to print out angled brackets. <>

`{
    "title": "Missing angle bracket key",
    "rules": [
      {
        "description": "Simultaneously XZ to print out angle brackets (modify with shift)",
        "manipulators": [
          {
            "type": "basic",
            "from": {
              "simultaneous": [
                {
                  "key_code": "x"
                },
                {
                  "key_code": "z"
                }
              ],
              "modifiers": {
                "optional": [
                  "left_shift"
                ]
              }
            },
            "to_after_key_up": [
              {
                "key_code": "non_us_backslash"
              }
            ]
          }
        ]
      }
    ]
}`

**Comment by alex-scanfetch** [comment]
For anyone in the future that is not able to get `non_us_backslash` to work, I found that the following worked for me:

```json
{
    "key_code": "6",
    "modifiers": "left_shift"
}
```

**Comment by LRSHRS** [comment]
> Need to change ^° and <> key on a keyboard with german keyboard layout. When adding a simple modification, I can not see those characters in the list. Tried the suggestion from comment 3 without success. Any idea how that would be handled?

Swap `non_us_backslash` with `grave_accent_and_tilde`  and `grave_accent_and_tilde` with `non_us_backslash`

<img width="1024" height="166" alt="Image" src="https://github.com/user-attachments/assets/39f335cd-9381-4b19-a5c2-53232a4116f2" />

I'm using the german layout too.
