### ISSUE TITLE
fn don't run correctly with touch bar on Macbook pro 2016 

### ISSUE THREAD

**Issue by itjerry** [tekezo/Karabiner-Elements#564]
the function key f1,f2.... will not show on the touch bar.
I restart my MacBook,it's useless.
it's ok after I uninstall Karabiner-Elements.

**Comment by mebibou** [comment]
yeah confirm, same problem here. Even touch ID didn't work anymore

**Comment by jrus** [comment]
This seems to be a duplicate of  #543?

**Comment by ELLIOTTCABLE** [comment]
(And originally, #460.)
