### ISSUE TITLE
Microsoft Sculpt Comfort Mouse - Help with Windows Key

### ISSUE THREAD

**Issue by peppeuz** [tekezo/Karabiner-Elements#565]
Hi all,
I use a [Microsoft Sculpt Comfort Mouse](https://www.microsoft.com/accessories/it-it/products/mice/sculpt-comfort-mouse/h3s-00002): I was able to use the Windows Key on Karabiner, but after Sierra update and Karabiner-Elements I've never been able to make it work again.

The private.xml I used on Karabiner linked below; can somebody help me?

http://pastebin.com/etUpT2y6

**Comment by nimbuscrenel** [comment]
In the exact same situation. Anyone else have some insight?

**Comment by daeho117** [comment]
Me too

**Comment by nimbuscrenel** [comment]
So, I partially got this working for very basic one-to-one key mappings. One of the things I used most with Karabiner was mapping the M$ Sculpt mouse 'Windows' button to open the OSX launchpad. Here's my working karabiner.json for that using version 0.90.88: 
`{
    "global": {
        "check_for_updates_on_startup": true,
        "show_in_menu_bar": true,
        "show_profile_name_in_menu_bar": false
    },
    "profiles": [
        {
            "devices": [
                {
                    "disable_built_in_keyboard_if_exists": false,
                    "identifiers": {
                        "is_keyboard": true,
                        "is_pointing_device": true,
                        "product_id": 1954,
                        "vendor_id": 1118
                    },
                    "ignore": false
                },
                {
                    "disable_built_in_keyboard_if_exists": false,
                    "identifiers": {
                        "is_keyboard": true,
                        "is_pointing_device": false,
                        "product_id": 610,
                        "vendor_id": 1452
                    },
                    "ignore": true
                }
            ],
            "fn_function_keys": {
                "f1": "display_brightness_decrement",
                "f10": "mute",
                "f11": "volume_decrement",
                "f12": "volume_increment",
                "f2": "display_brightness_increment",
                "f3": "mission_control",
                "f4": "launchpad",
                "f5": "illumination_decrement",
                "f6": "illumination_increment",
                "f7": "rewind",
                "f8": "play_or_pause",
                "f9": "fastforward"
            }, 
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "left_command": "vk_launchpad"
            },
            "virtual_hid_keyboard": {
                "caps_lock_delay_milliseconds": 0,
                "keyboard_type": "ansi"
            }
        }
    ]
}
`

Notice that I'm ignoring the built-in keyboard of my MacBook here, and only remapping keypresses from the Sculpt which was necessary to maintain the default functionality of my MacBook left_command key. I don't yet think it's possible to make key mappings device specific like on Karabiner. Hopefully someday soon.

Also, @peppeuz from your config it looks like you were mapping the Sculpt buttons to multiple key presses, something I also used to do with Karabiner. It looks like this isn't yet possible with Karabiner Elements, but has apparently been accomplished on a forked version by implementing "one_to_many_mappings". I'm hoping this makes it to master eventually.

**Comment by peppeuz** [comment]
Thanks @nimbuscrenel , your configuration actually works! 
I tried multiple times to do the same thing, but I used a different product_id and I couldn't manage to make it works.

Yes, with my old Karabiner configuration I was able to map the Sculpt button multiple times (and I used BetterTouchTool to even deeper customization), but your json is just perfect for my daily use.

Can you tell me more about the foked version you mentioned?

**Comment by nimbuscrenel** [comment]
@peppeuz the forked version I mentioned is detailed in this thread: https://github.com/tekezo/Karabiner-Elements/pull/247

**Comment by xbjconan** [comment]
quick question here, after using the code, the left command key on the keyboard still seem to work, How am I suppose to do the command+F combo to do the "find" function?

One more question, the Karabiner doesn't seem to recognize the "Scroll left/right " or "press Scroll" keys in the Karabiner-EventViewer. So I guess we cannot modify those either, right?

**Comment by xbjconan** [comment]
@nimbuscrenel Quick question here, after using the code, the left command key on the keyboard still seem to work, How am I suppose to do the command+F combo to do the "find" function?

One more question, the Karabiner doesn't seem to recognize the "Scroll left/right " or "press Scroll" keys in the Karabiner-EventViewer. So I guess we cannot modify those either, right?

**Comment by xbjconan** [comment]
@nimbuscrenel Quick question here, after using the code, the left command key on the keyboard still seem to work, but as the Launchpad key. Is there any way to keep this key as the normal left command function? I use command+F/S quite often with this key.

One more question, the Karabiner doesn't seem to recognize the "Scroll left/right " or "press Scroll" keys in the Karabiner-EventViewer. So I guess we cannot modify those yet and have to wait for some Karabiner updates, right?

**Comment by nimbuscrenel** [comment]
Both of my command keys function normally using the json above- not sure why yours don't. I'm using a mid-2014 MacBook Pro 15, if that makes any difference.

As for scroll wheel actions, the EventViewer appears to recognize the press scroll action as a middle-click, but you're right- left and right scroll wheel actions don't seem to generate a code or name, just some coordinates in the 'misc' column. 

I actually use BetterTouchTool for scroll wheel actions. It seems to work pretty well. For example, I have scroll-wheel left mapped to my browser 'back' button, and scroll wheel right mapped to browser 'forward'. I'd love it if this functionality made it to Karabiner in the future, but for now you may want to give BetterTouchTool a shot.

**Comment by nonoroazoro** [comment]
A year passed by, still not work, really want to uninstall karabiner-elements right now.

**Comment by RidgeSTD** [comment]
I got it work by simply remapping `right_gui` button to, in my case, `play_or_pause` button. You can map it to any other keys.

The most important thing is: **select the correct device**. Go to the device panel karabiner recognize my ergonomic keyboard **and** mouse separately. Enable the mouse and generate a mapping rule only to the mouse and you got it.

Device panel, note two recognised devices and the one in red rectangle:
<img width="993" alt="截屏2019-11-1723 24 16" src="https://user-images.githubusercontent.com/5996396/69015189-ed0a3b00-0991-11ea-9fe8-882d9693ce97.png">

Use a remapping rule on **mouse**:
<img width="996" alt="截屏2019-11-1723 24 09" src="https://user-images.githubusercontent.com/5996396/69015195-fdbab100-0991-11ea-8bc8-bda4a8cf6572.png">

My environment: MBP 2016 late + macOS Catalina 10.15.1
Karabiner-Elements 12.8.0

**Comment by Jiia** [comment]
I was having the same issue on the Microsoft Sculpt Ergonomic Desktop which includes both mouse and a keyboard.

The solution posted by @RidgeSTD worked, but I had to do the mapping **for the keyboard**, not the mouse.

**Comment by jakub-g** [comment]
Confirming the answer above for the mouse which comes as part of Microsoft Sculpt Ergonomic Desktop - on MacOS 13.6 + KE 14.12, the `Win` button for mouse can be found as `right_gui` **on keyboard**.

![image](https://github.com/pqrs-org/Karabiner-Elements/assets/1437027/f62356b9-b38d-451a-a524-7b4ee3af3c43)
