### ISSUE TITLE
Make fn key work as control key?

### ISSUE THREAD

**Issue by flaugher** [tekezo/Karabiner-Elements#569]
Do you plan to modify Karbiner Elements so that we can use the fn key as the left or right control key?  I'm using Karbiner Elements 0.90.81 on macOS Sierra 10.12.2 and I'm not able to get that mapping to work.  Thanks.

**Comment by tekezo** [comment]
It works on my machine. (MacBook Pro 2014)

**Comment by Wucasch** [comment]
I agree with @flaugher 
Since the latest update 0.90.82 it's not working anymore (it did before)
I also tried to compile an older version (0.90.76) resulting in the same issue.

**Comment by tekezo** [comment]
Attach the log messages in Preferences > Log tab.

**Comment by Wucasch** [comment]
This is so confusing!
I installed Karabiner Elements 0.90.82, then compiled 0.90.76 and now I'm back on 0.90.82 to attach the log messages.
Suprisingly everything works again as expected.
Don't know what fixed it, seems like my mac had a bad day or smth o_0

Anyway, thanks for the help and quick answer 👍

**Comment by ijoseph** [comment]
Greetings, 
Remapping `fn` appears to not work for me, _but only on my external keyboard_. It works fine on my built-in keyboard. 

I'm using version 0.91.12 on a "MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)."

I did some experimenting and looked at the logs; the following shows up after I try to set the relevant map.

```[2017-08-10 18:14:37.024] [info] [grabber] core_configuration is updated.
[2017-08-10 18:14:37.024] [info] [console_user_server] Load karabiner.json...
[2017-08-10 18:14:37.024] [info] [console_user_server] core_configuration is updated.
[2017-08-10 18:14:37.025] [info] [grabber] Isaac Joseph’s Mouse (device_id:6) is ignored.
[2017-08-10 18:14:37.025] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:5) is ignored.
[2017-08-10 18:14:37.025] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:3) is ignored.
[2017-08-10 18:14:37.025] [info] [grabber] (vendor_id:0x5ac, product_id:0x8600) (device_id:2) is ignored.
[2017-08-10 18:14:37.025] [info] [grabber] HP Link-5 Micro Receiver (device_id:1) is ignored.
```
 This is even though I have this device selected (see attached). However, this is exactly what shows up when I add a working map (one other than `fn` ↦ control), so this might not be informative.

**Comment by GLosch** [comment]
I'm experiencing the same issue as @ijoseph. Using an external keyboard, remapping the function key to something else has no effect. I'm using a Red Scarf keyboard and trying to map fn -> right_option

**Comment by SnitramDev** [comment]
Same issue here. Not able to remap fn as left ctrl key. I'm able to remap left ctrl key as fn key though.
I'm using version 12.1.0.

**Comment by Kejia** [comment]
the external keyboard's **_fn_** key seems not to trigger **_EventViewer_**.

**Comment by byrnedo** [comment]
also seeing this with fn keystrokes not showing in event viewer

**Comment by tshrjn** [comment]
The function key is not triggering the EventViewer & thus, unable to remap it.

**Comment by zecanard** [comment]
Have you tried with a Simple Modification?

**Comment by tshrjn** [comment]
@zecanard Would you please more details?

**Comment by zecanard** [comment]
If you just need to remap the `fn` key to another key, open Karabiner Elements Preferences → Simple Modifications. You can remap `fn` to another key there.

If that remap works and you need to assign `fn` to a more complex modification, according to my karabiner.json file the `key_code` for that key is just `fn`

**Comment by lchao1** [comment]
@tshrjn 
The reason is because "The operation can’t be completed because the item “Karabiner-EventViewer” is locked." (https://karabiner-elements.pqrs.org/docs/getting-started/features/)

**Comment by SVerboom** [comment]
I'm having the same issue where I can't map my fn key to any other modifier key. This problem only arises when using my external keyboard (logitech mx mini). The remapping on my internal keyboard works just fine. 

Does anyone know how to fix this?

**Comment by SVerboom** [comment]
I have the same issue where I cannot map the fn key to any other modifier key on my external keyboard. I'd like to change it to left_control. Remapping the fn key on my internal keyboard works just fine.

Does anyone have a fix for this issue? It would be highly appreciated :)

**Comment by hayate** [comment]
Currently it seems there is no fix. At the end of this documentation page: https://karabiner-elements.pqrs.org/docs/getting-started/features/
It says:
```
Karabiner-Elements cannot modify the fn key on non-Apple keyboards such as Logitech keyboards.
```
