### ISSUE TITLE
change input source while key pressed, e.g. right CMD

### ISSUE THREAD

**Issue by rualty** [tekezo/Karabiner-Elements#571]
Please implement this feature. I miss it very much :(

**Comment by alexesnsk** [comment]
+1
I did use left shift to input source 1 and right shift for input source 2. 
Now there is no such actions available.

**Comment by rualty** [comment]
@tekezo is it possible to implement this future? It was in old Karabiner. And it is the main reason why I used Karabiner.

**Comment by rualty** [comment]
@tekezo  any news on this issue?

**Comment by rualty** [comment]
@tekezo I saw in commits events on key_down, key_up. Does it means that this feature implemented?

**Comment by tekezo** [comment]
You can use `to_after_key_up` for this purpose.

Example:
https://github.com/pqrs-org/KE-complex_modifications/blob/master/docs/json/example_select_input_source.json#L55-L84

You can import this json from here:
https://pqrs.org/osx/karabiner/complex_modifications/example.html
