### ISSUE TITLE
Make Karabiner a sellable product!

### ISSUE THREAD

**Issue by scottmas** [tekezo/Karabiner-Elements#573]
My mandatory work laptop has become a worthless piece of metal without Karabiner. I desperately NEED the full power of Karabiner to get back up to full productivity. 

Why do you not SELL Karabiner? I would be willing to pay mucho money ($100? $200?) to get my productivity back pronto, and would be more than happy to pay for the stability that a product offering implies. 

Please, oh please, get Karabiner working again on Sierra!

**Comment by TsumiNa** [comment]
Also me! Everyday I click the check for updates wish to meet the new version update dialog!

**Comment by scottmas** [comment]
Any response to this? Seriously, we would love to support you in this and enable you to spend more time on karabiner. The ecosystem desperately needs a paid product with a decent level of support.

**Comment by b1az** [comment]
> The ecosystem desperately needs a paid product with a decent level of support.
👍

**Comment by MyDogTom** [comment]
https://pqrs.org/osx/karabiner/pricing.html.en

**Comment by phubert28** [comment]
If karabiner became a graphical product displaying the various specific managed keyboards (like printer drivers, for example, only beyond that), with point and click UI, it could easily be saleable! And I think SHOULD become commercial. Capitalism is the best means of providing supported products.

For me, some of the requests (application-specific settings, for example) are unrealistic. But that's for the developer(s) to decide.

**Comment by scottmas** [comment]
I have already donated, but sadly the current level of donations don't seem sufficient to enable @tekezo to work on Karabiner full time. For a paid product, with some level of support, I would easily pay $100 or something. Or even a subscription.
