### ISSUE TITLE
Modifiers (command, alt, shift) not working for function keys on TouchBar

### ISSUE THREAD

**Issue by nschum** [tekezo/Karabiner-Elements#574]
Pressing ⌘+F8 (or any other modifier) on the TouchBar creates an F8 event instead of an ⌘+F8 event.

When Karabiner-Elements is closed, it goes back to working as expected.

**Comment by bantonsson** [comment]
This is a duplicate of #535

**Comment by keith-han** [comment]
I have same problem. When will be this fixed?

**Comment by nschum** [comment]
Closing as duplicate
