### ISSUE TITLE
Add the possibility to save a profile

### ISSUE THREAD

**Issue by metmajer** [tekezo/Karabiner-Elements#575]
Hi, great piece of software and exactly what I've been looking for. As a feature request, I am asking to add a functionality to store and restore profiles. Thanks!

**Comment by orkoden** [comment]
What I do as a workaround copy the `.config/karabiner/karabiner.json` to `.config/karabiner/karabiner.json.otherconfig` and back when needed.

**Comment by walt-r** [comment]
I've taken @orkoden suggestion one further and made aliases in my `.bash_profile` file.  Then from the command line, I can switch profiles by typing the name of the user of my keyboard.

```
alias walt='cp ~/.karabiner.d/configuration/karabiner.json.walt ~/.karabiner.d/configuration/karabiner.json'
alias bo='cp ~/.karabiner.d/configuration/karabiner.json.bo ~/.karabiner.d/configuration/karabiner.json'
```

**Comment by sgronblo** [comment]
It seems this has been added in the latest version finally
