### ISSUE TITLE
Functional key is reserved to make visible touch bar

### ISSUE THREAD

**Issue by zagrebin** [tekezo/Karabiner-Elements#576]
System Preferences Configuration
Modifiers
Control key : Command
Command key : Control
Settings -> Keyboard 
Press Fn key to Show F1, F2 etc. 

I have a Karabiner-Element configuration
Fn -> Left Command
Left Command -> Fn

After these settings I expect using Ctrl as Function key. The issue here is to use Fn key to change touch bar view. OS still uses Fn key (not modified by Karabiner-Elements). I this case I cannot use Ctrl+F1, F2 etc. combinations.

**Comment by limeblack** [comment]
I wouldn't be surprised if there is no way to fix this.

**Comment by jrus** [comment]
This seems to be a duplicate of  #543.

**Comment by alexhayes** [comment]
@limeblack it appears that it does not work. Pressing `fn` always "activates" behaviour on the touchbar.

**Comment by alexhayes** [comment]
And just to clarify, #754 best describes the issue I'm having.
