### ISSUE TITLE
"application" key mapping stops working in updates after 0.90.70

### ISSUE THREAD

**Issue by ylihao** [tekezo/Karabiner-Elements#578]
Hi Developers, I have a mapping that maps the "application" key of a Windows keyboard (the key is usually to the left of the Right Control key) to the Left Command key on a Mac and it's been working well until version 0.90.70. All subsequent updates after this version simply render this mapping useless. I have to reinstall Karabiner Elements from the dmg file (Karabiner-Elements-0.90.70.dmg) to get the mapping back. 

Anyway just so that you are aware of it. Great job on the app guys, keep it up!

**Comment by themacguru** [comment]
This happened for me, too.

**Comment by litan1106** [comment]
Same issue here.
