### ISSUE TITLE
Fluor app can't change function key behavior when Karabiner-Elements is active

### ISSUE THREAD

**Issue by andrew-kennedy** [tekezo/Karabiner-Elements#579]
Using the code [here](https://github.com/Pyroh/Fluor/blob/master/Fluor/utils.m#L72), Fluor cannot be used to change function keys at all as long as Karabiner is running. I'm not sure if there is a way around this behavior, but I'd really like to be able to switch my function keys per app and also keep my key remaps.

**Comment by quozd** [comment]
Any ideas?

**Comment by jktzes** [comment]
Still notice conflicts between Fluor and Karabiner.

**Comment by larstomas** [comment]
The conflict between Fluor and Karabiner still exists.

**Comment by slavshik** [comment]
Still exists

**Comment by slavshik** [comment]
Is there any approach to avoid the conflict between Fluor and Karabiner?

**Comment by slavshik** [comment]
> Still relevant.
> 
> Maybe we can add another option 'as system' fn keys behaviour?

My solution was to remove flour and use complex modifications set up in Karabiner.

https://ke-complex-modifications.pqrs.org/#function_keys

Found here: https://github.com/Pyroh/Fluor/issues/65

**Comment by CodeMason** [comment]
Still relevant.

**Comment by amerlov** [comment]
Enabling "Use all F1, F2, etc. keys as standard function keys" in Karabiner settings -> Function Keys did the trick for me.
