### ISSUE TITLE
Is forward_delete possible?

### ISSUE THREAD

**Issue by DavidCatalano** [tekezo/Karabiner-Elements#58]
Is it possible to map right option key to forward delete? Console debug is throwing error for both Option_R and "Forward Delete" tried forward_delete as with old Karabiner to no avail.

**Comment by joostjodel** [comment]
I did exactly what you want as follows:

1) Open up a text editor and paste the following lines:

```
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "right_option": "delete_forward"
            }
        }
    ]
}
```

2) Save as: 

/Users/,Your Username>/.karabiner.d/configuration/karabiner.json

Voila!

**Comment by DavidCatalano** [comment]
Thank you! I didn't see the types.hpp file and was confused by the label changes.

**Comment by shaungrady** [comment]
@DavidCatalano Be sure to close this issue if it's fixed.

**Comment by EditorKubala** [comment]
Hi, I managed to change right option to forward delete. Would you help me how to change right command to right option? Thanks.

**Comment by talha131** [comment]
@EditorKubala see #72
