### ISSUE TITLE
all the key config does't work on version 0.90.83 with macOS sierra

### ISSUE THREAD

**Issue by itjerry** [tekezo/Karabiner-Elements#581]
when I roll back to version 0.90.82, it's ok.
but fn key doesn't work again（see my previous issue#564).

**Comment by jonathan-fantham** [comment]
Took me a while to find how to download old versions so in case anyone needs it: [0.90.82](https://pqrs.org/osx/karabiner/files/Karabiner-Elements-0.90.82.dmg)

**Comment by bpasero** [comment]
Wow this is bad, any update on this?

**Comment by nilsi** [comment]
Yepp seems my FN keys are not working anymore either.

**Comment by pasky** [comment]
I think that no mappings work in the new versions. Simple swap of paragraph and tilde keys is also broken for me with the latest version. The error log shows information about not being able to connect to the console_user_server, perhaps that process fails to start? I guess I should have grabbed that log before downgrading, sorry!

**Comment by Cpt0r** [comment]
Couldn't swap command/option and caps/backspace on `0.90.85` but `0.90.84` worked fine.

`0.90.82` worked as well but doesn't have profiles.

**Comment by jonathan-fantham** [comment]
I've just installed 0.90.86 and it seems to all work fine for me now 👍
