### ISSUE TITLE
Support for the section § key

### ISSUE THREAD

**Issue by paymonyau** [tekezo/Karabiner-Elements#582]
Support for the section § key is needed. Thousands of new macbook VIM coders across the world are remapping the caps lock key to escape.

**Comment by msaspence** [comment]
§ is supported, it is listed as `non_us_backslash`

**Comment by augusto** [comment]
@msaspence that comment was a saviour. Do you think it makes sense to clarify this in the app itself somehow?

I thought it would be trivial, but doing a tiny bit of research I found this: https://support.apple.com/en-us/HT201794 . So probably the "non us backslash" is any key on those layouts which is at the top left.

**Comment by msaspence** [comment]
Yeah for sure, I can't even remember how I found out about it now.

**Comment by hetzroni** [comment]
I agree with @augusto. This comment indeed saved my quite a lot of experimenting.
@msaspence, is there a plan to add this clarification?

**Comment by msaspence** [comment]
Sorry I'm not involved in Karabiner, I just discover the above, don't even remember how.

**Comment by hetzroni** [comment]
Well you saved me research time 👍

**Comment by bharel** [comment]
I still believe clarification can be useful.
