### ISSUE TITLE
fn key stops toggling function keys in Touchbar after 10.12.3 final

### ISSUE THREAD

**Issue by aparajita** [tekezo/Karabiner-Elements#583]
Before 10.12.3 final (including betas), pressing the fn key would toggle the Touchbar between controls and function keys. Now the fn key does nothing.

**Comment by jvdp** [comment]
Same here. Annoying too since I need the fn key to "wake up" the touchbar and Karabiner-Elements to have a proper esc key (bound to caps)...

**Comment by amir-s** [comment]
any updates on this?
I used to use this to switch fn and ctrl keys. even if you assign ctrl role to fn key, it still toggles the touchbar and no matter what key you assign fn role to, it doesn't work.

**Comment by jvdp** [comment]
I don't have this issue anymore, it seems. Though I do very frequently reboot my laptop and/or Karabiner-Elements to troubleshoot random issues with my mac.

**Comment by amir-s** [comment]
@jvdp 
I restarted my mac, now ctrl key and fn key, none of them switch the touchbar!

**Comment by hartman** [comment]
Same for me, the fn key doesn't toggle between the controls and the function keys. MacBook Pro 2016

**Comment by mickaelperrin** [comment]
Can confirm the issue sadly

**Comment by jvdp** [comment]
I've not had this issue in months, currently on version 0.90.92 and it's all working fine.

**Comment by Alexey-Yakovenko** [comment]
This issue is valid, karabiner elements 0.90.92, macOS 10.12.4.
Having the issue with touchbar multiple times every day, and quitting karabiner solves the problem.
Restarting karabiner brings the issue back.

**Comment by Alexey-Yakovenko** [comment]
More information / findings:

Some information that was already reported: touchbar gets "stuck", fn key doesn't toggle touchbar state, touch id stops working on the login screen.

I observed two new things recently:

* Previously I didn't see any pattern when this bug starts or stops, but recently observed that the bug triggers after logging in as a different user. Could be that multiple user sessions running at the same time break something
* While there's no known way to force-fix the problem (rebooting the computer, or restarting karabiner elements, doesn't help) - if I just ignore the problem and use the computer for a while, running single user session, the problem fixes itself, and then karabiner may work without a single problem for multiple days.

**Comment by Nitive** [comment]
I just discovered this problem immediately after updating to 10.12.5, Karabiner 0.90.92

**Comment by nicmar** [comment]
Remove all "fn_function_keys" sections in karabiner.json, worked for me. Same as #274

**Comment by Nitive** [comment]
> Remove all "fn_function_keys" sections in karabiner.json
Didn't work for me

**Comment by Gyong1211** [comment]
After the MacBook is woken up from sleep, the `fn` key starts to work well.
But using "Copy the current configuration to the system default configuration" on Misc tab, `sleep` and `wake up` don't fix `fn` key

**Comment by stefan-girlich** [comment]
Having the same issue since I updated today (I assume to v11.0). Removing "fn_function_keys" and restarting Karabiner has no effect.

**Comment by mts749** [comment]
Same here (fn key not working):
- MacBook Pro (15-inch, 2017)
- Sierra 10.12.6
- Karabiner-Elements 11.1.0
- "Use all F1, F2, ... as standard functions keys" option - both check on and off (didn't help).
- Deleted "fn" settings from JSON file

**Comment by elsdy** [comment]
# I got the same issue. 
the issue is that karabiner and working with fn doesn't go well together. 

I am so sad... 

1. Karabiner is necessary to convert the key of right command to the key of language switch.
2. and fn is need to use control... 

### is there no solution for it? yet?

**Comment by felimartina** [comment]
I am also having this issue. None of the provided workarounds worked!
