### ISSUE TITLE
fn/ctrl key remapping don't work with some function keys

### ISSUE THREAD

**Issue by chinhster** [tekezo/Karabiner-Elements#584]
I swapped the fn and ctrl keys but it doesn't work with some function keys.

For example, I use RDP to login to my Windows box and pressing ctrl-F5 in Visual Studio is supposed to run your application without debugging but it currently does nothing. Pressing fn-F5 behaves as if I only pressed F5 with no modifier.

However, pressing fn-F1 behaves as it should.

Removing the remapping did not restore functionality to the ctrl-function key in Visual Studio. I had to actually quit Karabiner-Elements.

I ended up checking the checkbox for Use all F1, F2, etc. keys as function keys to get around the problem but now I have to use fn key to use the special features whereas I didn't have to do this with the older version of Karabiner.

**Comment by chrisduong** [comment]
I have the same issue for K380 keyboard
