### ISSUE TITLE
Karabiner Elements breaks Media Keys on Microsoft Surface Ergonomic Keyboard

### ISSUE THREAD

**Issue by dljsjr** [tekezo/Karabiner-Elements#586]
I recently purchased the new Microsoft Surface Ergonomic Keyboard (https://www.microsoft.com/en-us/surface/accessories/surface-ergonomic-keyboard), I'm using Karabiner Elements to map Alt to Cmd and Win to Option, as for some reason this keyboard doesn't show up in Apple's keyboard pref pane as configurable.

Instead of an "Fn" modifier key that you hold down to switch between Fn and Media keys, the Surface has a toggle-able "Fn" mode key, similar to a Caps Lock sort of key.

When the "Fn" mode is activated then they register as Fn keys just fine but when the "Fn" mode is turned off, the media key functionality no longer works. They did work before installing Karabiner Elements, though.

2016 15" MacBook Pro w/ Touch Bar
macOS Sierra 10.12.2
Karabiner-Elements version 0.90.83

**Comment by mteodoro** [comment]
I'm having the same issue with this keyboard. I also noticed that the "calculator" key on the keyboard doesn't register in Karabiner-EventViewer.

MacBook Pro (Retina, 15-inch, Mid 2015)
macOS Sierra 10.12.3
Karabiner-Elements version 0.90.84

**Comment by ArtemGordinsky** [comment]
Having the exact same issue on Microsoft Ergonomic Keyboard 4000.

**Comment by evanhammer** [comment]
same

**Comment by philschoefer** [comment]
This also happens for me. I wonder if there is a way to have some sort of fallback where whatever gets returned from the keyboard can be used for mappings. Even if its some sort of bit like "0x45"

**Comment by mattstauffer** [comment]
Yah--it's not just that it doesn't work, but that it also cannot be mapped.

Uh... ok.. so i was trying to map out the behavior using Karabiner EventViewer and so I was toggling all the settings and keys a bunch of times.. and all of a sudden it started working the way I expected.

So... there's functionality in here somewhere.. but it just sporadically works. No idea what sequence of events made it work, and I'm sure it'll stop working the next time i restart my computer. But hopefully all this info helps suss out the source.

**Comment by matthewdias** [comment]
I have a similar issue with a Pok3r keyboard. None of the commands from the function layer are recognized by KE, and they do not function when KE is enabled.

**Comment by anandman** [comment]
I'm seeing this issue on the Microsoft Universal Foldable Keyboard also.

**Comment by manojpkr** [comment]
I am seeing the same issue. One of the earlier version, 34 or 55 used to work properly

**Comment by al1947** [comment]
Same issue with Microsoft Surface Ergonomic keyboard: unlocked function keys mostly work when KE is disabled, but result in no input whatsoever when KE is running. (Locked, the F1, F2, etc keys perform the standard F1, F2, etc functions regardless of whether KE is running.)

Swapping the ALT and Windows keys on a Microsoft keyboard to Mac Command and Option respectively are the priority annoyance-saver, of course. But it would be good to have the brightness, media play, and other such functions work also.

**Comment by dljsjr** [comment]
Quick update on this, I'm not sure when it happened but this seems to be fixed. Unfortunately I wasn't actively trying to reproduce this issue, I just noticed a day or two ago.

I'm not sure if this was fixed in KE or if it was fixed in High Sierra.

**Comment by offbyone** [comment]
I'm having the same issue as this, on much newer versions of the software in question:

* Microsoft Natural Ergonomic 4000 Keyboard
* 15" MBP, 2018 vintage
* macOS Mojave 10.14.6
* Karabiner Elements 12.9.0

The media bar keys do not register in Karabiner Event viewer, even when they work; the play/pause button for example, *does* what it's supposed to but doesn't generate an event in the event viewer.

**Comment by hmeine** [comment]
Same here. (Natural Ergonomic 4000 as well)

* There are a lot of extra keys that have no effect
  * nearly all of the gray/silver top row of keys, the "favorite"/star key centered below, and the the backward/forward keys at the bottom,
  * the function keys when not in function key mode (i.e. F1-F12 work, but help/undo/redo/new/open… do not),
  * and the black up/down scrolling rocker in the very center.
* "Have no effect" includes these keys not producing keycodes in the eventviewer.
* Interestingly (as others have reported as well), the media keys work (mute/vol-/vol+/play-pause), but still do not produce events. I wonder how that can be the case at all. I am quite puzzled by that.

**Comment by dioxide** [comment]
Same here. (Natural Ergonomic 4000 as well)
