### ISSUE TITLE
Disabling Left Shift doesn't work

### ISSUE THREAD

**Issue by itstuesday799** [tekezo/Karabiner-Elements#587]
hello everyone, my macbook air left shift key is stuck and so I have karabiner elements set up to remap left shift to vk_none.  The forced "capslock" is gone but all the other little things that come with a stuck left shift (browser opening new windows for all tabs, not being able to select a single file, slow animations, etc.) still exist. They sometimes, though rarely disappear until I shut down the pc/close it. I wanted to know if there is something I can do about it.
Thanks a lot :)

(MBA 2013, macos 10.12, Karabiner Elements 0.90.83)

**Comment by Niflis** [comment]
I have the same issue, actually posted a thread about it 20 minutes ago.
did you find anysolution ?
noticed that the l_shift flag is being triggered in the karabiner event viewer.
maybe it is possible to remove the flag via the son file. but not sure how it works..

**Comment by itstuesday799** [comment]
Nope, still haven't found any solution.
You mean remove the l_shift down flag from the macOS system files? might be possible though i'm not a dev. maybe one could help us out

**Comment by MKEPPP** [comment]
ANY HELP? I CANT DISABLE MY SHIFT KEY (IT GOT STUCK TWO YEARS AGO AND I USED KARABINER TO FIX IT BUT IT STOPPED WORKING TODAY (EVEN THOUGH I ALREADY HAD THE SIERRA UPDATE...WEIRD)  HENCE THE SHOUTY CAPS :)

I DOWNLOADED KARABINER ELEMENTS AND CANT FIGURE OUT HOW TO DISABLE A KEY. I FOUND THIS_https://github.com/tekezo/Karabiner-Elements/issues/145 BUT I AM NOT SURE I UNDERSTAND HOW TO GO ABOUT DOING THIS (I DONT KNOW HOW TO CODE BUT I CAN DO IT IF SOMEONE WALKS ME THROUGH IT)

THANKS FOR ANY HELP AND SORRY ABOUT MY SHOUTY CAPS!!

**Comment by Niflis** [comment]
Hi @MKEPPP
Open up Karabiner E and go in to preferences. 
on "simple modifications" put the l_shift or R_shift (depending on the faulty key) in the "from key"
and in the "to key" put "vk_none (disable this key)"

This should work for you, i'm not on my mac atm, so can't confirm that this is the correct keys/tabs but should be something like that.

but please note that even when i have this set for my l_shift i still get issues sometime and the shift is activated and i go all caps etc,
try the above and reply if it worked.

**Comment by Niflis** [comment]
found a Picture. please see attached.
<img width="802" alt="4exm5" src="https://user-images.githubusercontent.com/25751619/27956307-83c24b9a-6319-11e7-80b6-38d5890f5d5a.png">

**Comment by squaredoranges** [comment]
@itstuesday799 @Niflis did you ever find a solution? I am running into the same issue. The forced caps lock is on but the Shift flag still shows up in the event viewer for all mouse events. It's quite annoying to browse and be forced to open new windows sometimes.

**Comment by Niflis** [comment]
Well for me karabiner E stops the shift flag.
But sometimes it stops to work.
Once computer is restarted karabiner does its job and shift flag is
removed. Not sure why it stops working..




lör 15 juli 2017 kl. 18:58 skrev squaredoranges <notifications@github.com>:

**Comment by maxoubvs** [comment]
Hi ! 
@itstuesday799 @Niflis I have exactly the same issue with Karabiner E. Has anyone found a solution?

**Comment by AKate4764** [comment]
I just upgraded to Sierra today and regret it immensely because Karabiner is no longer working for my stuck shift key. Okay so here's what I somewhat figured out. Since the pressing of a shift key is the change of a flag, it being held down is that flag constantly set to "on." So since it's stuck, it's default state is "on." So while the flag is still on, the "vk_none" makes it ignore that flag when typing I suppose, but not when doing anything else. If there's some way to set the default flag to "off" then that would solve all of our problems. I'm continuing to look into a lot of the code and trying to see what I can find.

**Comment by maxoubvs** [comment]
Ok ! For me Karabiner E works, but sometimes i need to reboot my mac. Let me know if you find something ;)

**Comment by Niflis** [comment]
Same for me, the flag is turned off by Karabiner. But sometimes it get
activated again and a reboot is needed..
if we could find a way to actually turn off the flag for a specific shift
button, everything would be great 😊
ons 23 aug. 2017 kl. 08:24 skrev maxoubvs <notifications@github.com>:

**Comment by PsykikHunter** [comment]
what i did was enable it to start before login, then restart. Now the icon is NOT in the status bar, but all my modifications work and shift key is properly disabled. You can enable it to start before login in one of the windows inside the preferences panel, cant remember which. (too afraid to open karabiner to see in case it stops it working :) )

**Comment by AKate4764** [comment]
:o You're absolutely right PsykikHunter! It's under the misc tab and then you can set it as System Default Configuration. You're a life saver!

**Comment by maxoubvs** [comment]
Works for me too ! Now i don't need to reboot my MacBook,  thx a lot !!
Someone knows if Karabiner-Element works on macOS Hight Sierra? (without reboot)

**Comment by Niflis** [comment]
No idea how it works now, but they had some issues with the H Sierra beta.
But since the update is kind of a minor, with some security issues and freezing (read that somewhere) I'm going to wait with the update until I know more, 
but if anyone here tries, please report how its working.
we shiftstuckies need to watch each others backs :)

**Comment by maxoubvs** [comment]
Yesterday my Macbook was slow, i needed to reboot :(

**Comment by dimpledesign** [comment]
> Hi @MKEPPP
> Open up Karabiner E and go into preferences.
> on "simple modifications" put the l_shift or R_shift (depending on the faulty key) in the "from key"
> and in the "to key" put "vk_none (disable this key)"
> 
> This should work for you, I'm not on my mac atm, so can't confirm that this is the correct keys/tabs but should be something like that.
> 
> but please note that even when I have this set for my l_shift I still get issues sometime and the shift is activated and I go all caps etc,
> try the above and reply if it worked.




this worked for me. 
thank you!

**Comment by dimpledesign** [comment]
I have been trying to fix this issue and after spending a lot of time on the internet, I read this. It was almost my last hope. And it worked. I can work in peace again. Thank You!

**Comment by kothman** [comment]
I have this issue as well.

MacBook Air (13-inch, Early 2014), macOS Big Sur 11.7.

I'm not sure if this is related, but it works more reliably when I have my computer charging or fully charged. It seems to stop working when my computer gets low on battery, and then starts working again more frequently when plugged in.

**Comment by StarRabbit** [comment]
> what i did was enable it to start before login, then restart. Now the icon is NOT in the status bar, but all my modifications work and shift key is properly disabled. You can enable it to start before login in one of the windows inside the preferences panel, cant remember which. (too afraid to open karabiner to see in case it stops it working :) )

you are a fking genius！！！
