### ISSUE TITLE
Remapping hasn't worked well since 0.90.66 

### ISSUE THREAD

**Issue by 5Aki1** [tekezo/Karabiner-Elements#589]
Remapping fn to left control has been incredibly difficult for me since any update past 0.90.66. 

Here's the link for anyone struggling with the same thing. Anyone know why that may be?

https://pqrs.org/osx/karabiner/files/Karabiner-Elements-0.90.66.dmg

**Comment by alexhayes** [comment]
I'm also having the same issue. Can't say what version it started because I was prompted for the first time to update yesterday and then again this morning. Prior to that it was working fine. Can confirm that rolling back to 0.90.66 fixes the issue.

**Comment by brianspurling** [comment]
I was on the latest version and working fine, but noticed this morning that profiles had been introduced. The moment I set up a profile my mappings all started going screwy. Specifically, the mapping of caps_lock to a. Although after clicking around a lot I managed to get any mapping to not work!

Eventually came across this post, rolled back to 0.90.66 (which, I notice, doesn't have profiles), and everything's fine again.

**Comment by asyncsrc** [comment]
@5Aki1 just out of curiosity, how did you find that URL to version 0.90.66?  I was digging through github.com and the main pqrs.org site to no avail.  

I really appreciate you posting it.  I can concur this version works for me on MacOS Sierra as well whereas the latest version available today did not.

**Comment by 5Aki1** [comment]
@asyncsrc I looked up a line from the log and someone had posted it in a thread. I just thought I'd make it a little more accessible to people.
