### ISSUE TITLE
Causes Ctrl+Space to change keyboard layout after a delay instead of instantly.

### ISSUE THREAD

**Issue by KaHa6uc** [tekezo/Karabiner-Elements#59]
I have been using Karabiner for a while now on my MBP to replace § with `. Today I updated to macOS Sierra and migrated to Karabiner-Elements.
While fixing the § button works flawlessly, Karabiner-Elements seems to break my Ctrl+Space combination, which I use for changing keyboard layouts. While until now I used to press them briefly, now I have to keep them pressed and wait a second for the layouts toast to open to successfully change the keyboard layout.

MacBook Pro (Retina, 13-inch, Early 2015)

**Comment by a-triant** [comment]
duplicate of #41

**Comment by tekezo** [comment]
Thank you for feedback!
I've fixed this issue at v0.90.33.

Please upgrade to the latest version from "Misc > Check for updates" or 
https://pqrs.org/latest/karabiner-elements-latest.dmg

**Comment by KaHa6uc** [comment]
Apologies for the dupe and thanks for the quick reply and fix! Updated to 0.90.38 and it works fine. Thanks again!
