### ISSUE TITLE
§° and <> are swapped, why? (Swedish external Mac Keyboard)

### ISSUE THREAD

**Issue by nicmar** [tekezo/Karabiner-Elements#591]
I tried to find a similar thread here, but there were so many. 

I'm using Karabiner Elements just to swap right cmd and option, and I don't know why, but <> keys (left of z) and §° (leftof 1) are swapped when KE is running.

Do I need to rebind these keys in Karabiner Elements myself, or how do I solve it?

Why does it even change keys that I didn't ask for? :)

**Comment by jyggen** [comment]
This is the exact issue I'm facing in #229, which sadly was closed without the issue being fixed :(

**Comment by nicmar** [comment]
Thanks for the notification. I just updated to the latest version (0.90.84), and I changed in Virtual Keyboard > Keyboard Type > from ANSI to ISO, and now <> §° works correctly!

**Comment by gustafbstrom** [comment]
The ANSI/ISO menu doesn't seem to work anymore; see screenshot. Any ideas?

![image](https://user-images.githubusercontent.com/1080680/55243185-fdbd4380-523e-11e9-986a-3f7422bef142.png)

**Comment by dabaus** [comment]
This is actually a nice feature. My external keyboard is broken by default, in installing karabiner fixed the issues i have had with the § and < being flipped.

**Comment by erdemtas-et** [comment]
Hey, I got a keyboard with a Nordic layout and I have the "§" key on my keyboard and I would like to swap it with a **double quotation mark**. I couldn't find the correct option on the app which symbol is equivalent to this (§) symbol.
