### ISSUE TITLE
touch bar conflict

### ISSUE THREAD

**Issue by hh-in-zhuzhou** [tekezo/Karabiner-Elements#595]
I use 2016 Mac book pro with touch bar.  
In the "Devices" tab of Karabiner-Elements, there are two keyboards(of course one is the touch bar) , when I select both, and exchange the esc and caps lock key, it can work, but some key in the touch bar such as disable sounds、brightness cannot work.  and when turn off the switch("Devices" tab, the touch bar device), touch bar works fine.

so, my opinion is that, can I use Karabiner-Elements only to change esc key of touch bar, but not affect other keys of touch bar ? thanks very much.

**Comment by nbevan** [comment]
Same question: I would really like to disable the touch bar escape key, but when I enable “No product name, Product Type 0x8600” [touch bar] the whole touch bar is disabled (being discussed at https://discussions.apple.com/message/31380587?ac_cid=tw123456#31380587 and not everyone has this particular problem).

**Comment by nbevan** [comment]
Solved my problem: for this to work the Touch Bar needs to be set to the default: App Controls with Control Strip in System Preferences.

It would b e great if Karabiner-Elements also supported the Expanded Control Strip.

**Comment by mieky** [comment]
Can confirm, Karabiner-Elements currently seems to break the Expanded Control Strip altogether. E.g. it works fine in the "App Controls" mode but whenever I expand it, none of the controls shown actually do anything while Karabiner is running.

**Comment by pudge** [comment]
I still have the problem regardless of whether control strip is set to Expanded or the default, even with latest beta.

**Comment by jrus** [comment]
It seems to me that the touchbar actions that pop up sliders work, but the ones that are single buttons all get broken. I would recommend other users uncheck the touchbar in the devices tab of the Karabiner Elements preferences. (It shows up as _'No Product Name (No Manufacturer Name)'_ on my machine -- maybe it should instead show up as _'TouchBar (Apple)'_ or similar?) When I untick that checkbox the touchbar then works properly again.

Folks should just give up on remapping the touchbar's `esc` button to doing anything non-standard; use another key for whatever you wanted it to do.

**Comment by jrus** [comment]
Maybe this is a duplicate of #435
