### ISSUE TITLE
Target Display Mode - OSX 10.12.x (Sierra)

### ISSUE THREAD

**Issue by tasseb** [tekezo/Karabiner-Elements#596]
Hi,
Using a Logitech Keyboard K811 (easy switch), I would like to use Target Display Mode (use my iMac as a second screen for a Mac book pro).
Then I need to launch CMD + F2. Means CMD + Fn + F2 on the K811 (and doesn't work).

I installed Karabiner-Elements but did not find how to resolve this "issue" as you mentioned in the Q&A. Is there a way to do it with Karabiner-Elements or should I have to wait a Karabiner version for OSX 10.12.x ?

Thank you for your help and your useful software.

Kind regards,

**Comment by dusek** [comment]
I want to use an iMac as a display target display mode for a MacBook. The iMac has an HP (PC) keyboard connected to it. After upgrading both devices to macOS 10.14, Cmd-F2 stopped working. I remember Cmd-F2 worked previously after setting _Preferences > Functions Keys > Use all F1, F2, etc. keys as standard function keys_, but this stopped working. I tried unchecking the checkbox, tried again, checking the checkbox, try again, to no avail.

I am quite dying for the big screen, please help! :-)

**Comment by mtskf** [comment]
Same issue here!
This is critical... :(

**Comment by mikelinke** [comment]
Target display mode is the only reason I needed or wanted karabiner, and it's not working.
