### ISSUE TITLE
Can't load /Library/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.kext - authentication problems.

### ISSUE THREAD

**Issue by cayco** [tekezo/Karabiner-Elements#598]
Hi! I have installed Karabiner 0.90.66 on macOs 10.12.3.

After that Karabiner does not work. Immediately after installation Info window appear that system extension „/Library/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.kext" was installed incorrecly. 

Now in Karabiner logs I see constant flow of messages:

`[2017-01-31 15:13:47.021] [warning] [grabber] event_manipulator_ is not ready. Please wait for a while.`

After I tried to load kext by hand:
`sudo kextload /Library/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.kext`

I've got:

`/Library/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.kext` failed to load - (libkern/kext) authentication failure (file ownership/permissions); check the system/kernel logs for errors or try kextutil(8).`

on the console and

`Can't load /Library/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.kext - authentication problems. `

in macOs logs.

Any idea how to fix it? Rebooting doesn't help.

**Comment by tekezo** [comment]
This issue might be solved by revising kext file owner to root:wheel.
Please try these command in Terminal.
And please show me the results in order to diagnose the cause.

```
sudo ls -ld /Library/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.kext
sudo chown -R root:wheel /Library/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.kext
sudo killall karabiner_grabber
```

**Comment by cayco** [comment]
That was the issue and what you wrote fixed it. Thank you!
