### ISSUE TITLE
Editing "greater than" and "less than" keys

### ISSUE THREAD

**Issue by holgerhartmann** [tekezo/Karabiner-Elements#599]
HI,

where can I edit or change the "greater than" and "less than" keys? Any ideas?

Best,
Holger

**Comment by lenolib** [comment]
#439 maybe solves it for you

**Comment by holgerhartmann** [comment]
@lenolib perfect! Thanks!

**Comment by gabrielpetersson** [comment]
Tack @lenolib  ;)
