### ISSUE TITLE
modifier flags in karabiner.json

### ISSUE THREAD

**Issue by ryantuck** [tekezo/Karabiner-Elements#6]
Hi, just made the mistake of upgrading to macOS sierra! Happy you're at work on this and would love to help. 

I'm wondering how to add modifier flags to `karabiner.json` like I had in my `private.xml` file for mapping `escape` to `shift + command`:

``` xml
<?xml version="1.0"?>
<root>
    <item>
        <name>esc to command+shift</name>
        <identifier>private.esc_to_cmd_shift</identifier>
        <autogen>
            __KeyToKey__
            KeyCode::ESCAPE,
            KeyCode::SHIFT_L, ModifierFlag::COMMAND_L
        </autogen>
    </item>
</root>
```

I'm assuming it won't be under `simple_modifications`, but I can't find anywhere in the code for adding a more complex modification. Do you know when I might be able to use this functionality?

**Comment by niieani** [comment]
HI @ryantuck. I believe multi-key support hasn't yet been implemented. See the file: https://github.com/tekezo/Karabiner-Elements/blob/6f4cb0936bfd7e08042a0ebca2f797f037f3893c/src/share/configuration_core.hpp

**Comment by szkrd** [comment]
I think modifier key support is very important, it would be wonderful to have a roadmap (probably in the wiki), plus per feature donation would be really nice - unfortunately I never worked with cpp, so I'm not that much of a help in terms of actual contributions :(

**Comment by ofer987** [comment]
I feel the same way @ryantuck -- I upgraded to macOS Sierra this morning. I regret it because now my multikey bindings no longer work. Just like @szkrd I have not programmed in C++ in a long time, but hey, this is such an important thing for me then maybe I should contribute anyway.

**Comment by specious** [comment]
I also upgraded to Sierra and have no way back.

My <kbd>]</kbd> key doesn't work, so I had it remapped in `private.xml` as <kbd>Option + [</kbd>:

```xml
<?xml version="1.0"?>
<root>
  <item>
    <name>opt + [ = ]</name>
    <identifier>private.option_plus_lbracket_to_rbracket</identifier>
    <autogen>
        __KeyToKey__ KeyCode::BRACKET_LEFT, ModifierFlag::OPTION_R, KeyCode::BRACKET_RIGHT
    </autogen>
  </item>
</root>
```

For now, I decided to sacrifice my <kbd>F12</kbd> key.

**Comment by szkrd** [comment]
I don't know if it helps, but I ended up using ukelele with karabiner for now. It's not the best solution, but the custom keymap helps a lot.

**Comment by domq** [comment]
+1 on the idea to deliver a working, QWERTY-agnostic MultiKey feature through customizable modifiers.

For context: we used to do this with "old" Karabiner by [mapping a key to Ctrl-Shift-F13](https://gist.githubusercontent.com/gnarf/0d29c05b189a51894399/raw/private.xml) and applying [this `DefaultKeyBinding.dict`](http://lolengine.net/blog/2012/06/17/compose-key-on-os-x); see e.g. [this article on Think Different](http://apple.stackexchange.com/questions/31487/add-compose-key-to-os-x).

I am using Mac OS X Sierra on an actual MacBook, with French (AZERTY) keyboard. The aforementioned setup worked well for me on the same hardware and Mac OS X Yosemite. Additionally I tried the following:

- "Plain" F13 (along with a suitably de-`^$`-ified `"\UF710"` in `DefaultKeyBinding.dict`) works fine in e.g. Chrome, but not in Terminal: it spits `^[[25~` to the console instead, and I am at a loss on how to disable that in its Preferences. I figure the Ctrl+Shift part was supposed to prevent Terminal from interpreting the surrogate key (and it still does work, in the sense that Ctrl+Shift+say, RightCmd combo does work with Sierra, Terminal and an unmodified `DefaultKeyBinding.dict`)
- The [osx-compose-key approach / workaround](https://github.com/gnarf/osx-compose-key/issues/15) seems specific to the US keyboard; at least it doesn't work for me, as I *do* have a physical `non_us_backslash` key (it's my @ / # key on top left) that I don't want to sacrifice.

Thus, the ability to add modifiers to F13 is the only thing standing between me and a working, fully customizable, *and* RSI-free Compose key.

**Comment by jackcouch** [comment]
Looking forward to the return of modifier keys as well - my whole setup depends on them. I'm offering a $50 bounty on this one (sent via bitcoin). If there is a better way to do this let me know :)

**Comment by cray0000** [comment]
You can use this app in addition to Karabiner-Elements for the simple multikeys setup: [⌘英かな](https://ei-kana.appspot.com/). It's in japanese but pretty easy to figure out.

**Comment by jsalvatier** [comment]
Also rely heavily on multi-key support. I would pay money to have this. Is there a bounty system?
