### ISSUE TITLE
For HHKB Professional JP keyboard, "right-cmd" and "lang" keys are not detected

### ISSUE THREAD

**Issue by yohm** [tekezo/Karabiner-Elements#601]
I'm using HHKB Professional JP keyboard, but "right_command" and "lang1"&"lang2"(英数&かな) keys are not detected in Karabiner-EventViewer while the other keys are recognized well.

If I removed the check of "HHKB Professional JP" in [Devices]-[Modify events from this device] table, these events are detected by the event viewer. However, if I removed that check, key modifier does not work.

## environments

- macOS Sierra 10.12
- Karabiner-Elements: 0.90.84
- OS Locale: English
- Mac Pro (Mid 2012)
- keyboard: HHKB Professional JP
    - Latest driver for HHKB provided by PFU is installed.

**Comment by tekezo** [comment]
HHKB Pro JP without PFU driver works fine on my machine.
The PFU driver might be conflicted with Karabiner-Elements.

**Comment by yohm** [comment]
I uninstalled the PFU driver, but I still find the same problem.
Do you have an idea on possible causes that I can test?

**Comment by tekezo** [comment]
Did you change the DIP switches?
Please try to reset the DIP switches.

**Comment by yohm** [comment]
Macintosh mode (SW1) and swapping left alt and command (SW5) are on.
Although I turned off these two and restarted my computer, things didn't change. Event-Viewer does not show any responses against "right_command", "lang1", and "lang2".

**Comment by hioki-daichi** [comment]
@yohm
In my environments, `lang` and `right-cmd` are now detected after adding the following settings.

* For `lang1`
    * `PCキーボードの変換キー`
* For `lang2`
    * `PCキーボードの無変換キー`
* For `right-cmd`
    * `PCキーボードのかなキー`

<img width="940" alt="karabiner_element_lang_and_right_cmd_settings" src="https://cloud.githubusercontent.com/assets/5728556/22850949/7b95fab4-f057-11e6-94dc-688186f2b271.png">

<img width="914" alt="options" src="https://cloud.githubusercontent.com/assets/5728556/22851023/aab788b0-f059-11e6-9d8a-f213de13a365.png">

## environments

* macOS Sierra 10.12.3
* Karabiner-Elements: 0.90.67 (with a little patched with manual build)
* OS Locale: Japanese
* MacBook Pro (Late 2016)
* Keyboard: HHKB Professional2 Type-S JP
    * Latest driver for HHKB provided by PFU is installed.

**Comment by yohm** [comment]
@hioki-daichi Thanks! I'll try your proposal maybe during next week.

**Comment by yohm** [comment]
@hioki-daichi Following your advice, I could remap the keys as I intended.
After I reinstalled PFU devices, I remapped the keys as following. Thanks!

![image](https://cloud.githubusercontent.com/assets/718731/22912532/45bf900e-f2a9-11e6-94a9-3ddd392aaa1d.png)
![image](https://cloud.githubusercontent.com/assets/718731/22912574/793fecb2-f2a9-11e6-85da-de6c3747d420.png)
