### ISSUE TITLE
Karabiner and Typematrix keyboard

### ISSUE THREAD

**Issue by aurelberra** [tekezo/Karabiner-Elements#603]
Are there plans to port to Karabiner-Elements the features which clearly made Karabiner a boon for Typematrix users? I just started using this keyboard and I realise  how useful it would be to have these modifications back, especially the copy and paste keys on MacOS.

**Comment by aurelberra** [comment]
I would be very surprised to be the only one who uses Karabiner-Elements and a Typematrix keyboard, but there has been no answer here so far…

**Comment by alexandrenorman** [comment]
Same here, I love TM keyboards… and I miss copy-paste

**Comment by aurelberra** [comment]
Now that complex modifications have restored most of its power to Karabiner, it would be great to get this nifty keyboard improvement back!

**Comment by aurelberra** [comment]
So, no one in the active contributors knows how to access these special keys on a Typematrix keyboard? That's really disappointing, as I am not aware of any hack…

**Comment by aurelberra** [comment]
Still hoping this issue might one day be considered. I'd be happy to test, if needed.

**Comment by aurelberra** [comment]
Extremely happy to find out that [complex rules for cut, copy and paste functions on the Typematrix keyboard](https://pqrs.org/osx/karabiner/complex_modifications/#device_specific) are now available. Thanks to the developers!

I haven't managed to use them without the function key yet. If anyone has an idea, that would make the keys even more useful.
