### ISSUE TITLE
Cannot map fn key to Volume

### ISSUE THREAD

**Issue by aneemtalukder** [tekezo/Karabiner-Elements#604]
I am trying to map the function f2 key to volume decrease on my keyboard. I am currently running macOS Sierra 10.12.3. It does not seem to be working. Can you advise? Here is a screenshot of what I have done:

<img width="803" alt="screen shot 2017-02-03 at 6 26 11 pm" src="https://cloud.githubusercontent.com/assets/1292987/22612411/7ca57610-ea3e-11e6-8b1d-bf50595f956e.png">

**Comment by sn0wyfall** [comment]
Which version of Karabiner did you install?

**Comment by aneemtalukder** [comment]
I have Karabiner-Elements 0.90.85 installed, and have followed the instructions on installing the .dmg from here: https://github.com/tekezo/Karabiner-Elements/blob/master/usage/README.md

**Comment by sn0wyfall** [comment]
Seems like you should uninstall 0.90.85 and install 0.90.84. Then it would probably work, as mentioned in another issue.

**Comment by aneemtalukder** [comment]
Can you please link me to the other issue? Can't find where to download previous versions

**Comment by sn0wyfall** [comment]
Sure, [here](https://github.com/tekezo/Karabiner-Elements/issues/605) is the issue. I'm not certain myself where you can find the previous version, but this issue should most likely be fixed or a previous version rolled out soon I guess

**Comment by aneemtalukder** [comment]
Ah great thank you! Hopefully there is a fix soon!

**Comment by aneemtalukder** [comment]
fixed with next version, closing this issue
