### ISSUE TITLE
New install of 0.90.86 fails on create pid directory

### ISSUE THREAD

**Issue by mark-thomas** [tekezo/Karabiner-Elements#606]
Installing Karabiner-Elements on a machine that previously had Karabiner but never had elements, fails at launch with following Error in report: 
Process:               Karabiner-Elements [859]
Path:                  /Applications/Karabiner-Elements.app/Contents/MacOS/Karabiner-Elements
Identifier:            org.pqrs.Karabiner-Elements-Preferences-Window
Version:               0.90.86 (0.90.86)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Karabiner-Elements [859]
User ID:               501

Date/Time:             2017-02-05 13:38:47.463 -0500
OS Version:            Mac OS X 10.12.3 (16D32)
Report Version:        12
Anonymous UUID:        DE005134-8803-9FAB-2079-404ECA47C943

Time Awake Since Boot: 160 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
terminating with uncaught exception of type std::runtime_error: failed to create pid directory
abort() called

**Comment by tekezo** [comment]
It's strange.
Could you show me the result of the following commands in Terminal?

```
ls -dl ~/.local
ls -dl ~/.local/share
ls -dl ~/.local/share/karabiner 
mkdir -p  ~/.local/share/karabiner/pid
```

the last `mkdir` command might solve this issue.

**Comment by mark-thomas** [comment]
Sorry for the delay in reply: 
mark-MB:~ mark$ ls -dl ~/.local
drwxr-xr-x  3 root  staff  102 Dec  8  2015 /Users/mark/.local
mark-MB:~ mark$ ls -dl ~/.local/share
drwxr-xr-x  4 root  staff  136 May 28  2016 /Users/mark/.local/share
mark-MB:~ mark$ ls -dl ~/.local/share/karabiner
ls: /Users/mark/.local/share/karabiner: No such file or directory
mark-MB:~ mark$ mkdir -p ~/.local/share/karabiner/pid
mkdir: /Users/mark/.local/share/karabiner/pid: Permission denied
mark-MB:~ mark$ sudo mkdir -p ~/.local/share/karabiner/pid
Password:
mark-MB:~ mark$ ls -dl ~/.local/share/karabiner/pid
drwxr-xr-x  2 root  staff  68 Feb  9 20:14 /Users/mark/.local/share/karabiner/pid
mark-MB:~ mark$

Still didn't work but error changed to failed to create pid file. chmod pid to 777 and karabiner launched right up.

Thanks.

**Comment by feuyeux** [comment]
Let Karabiner-Elements running, and "System Preferences > Security & Privacy > Click "Allow".
My KE version is `12.1.0` and OS version is `Sierra 10.13.6`
