### ISSUE TITLE
Show desktop with PrtSc key

### ISSUE THREAD

**Issue by Huang-Libo** [tekezo/Karabiner-Elements#607]
I want to set PrintScreen key as _Show desktop_ key, but I can't find it in _Simple Modifications_. I had set f11 as _volume_decrement_, so I cannot use f11 to show desktop, how can I handle this problem ?

**Comment by Horttcore** [comment]
Yeah show Desktop is missing.

**Comment by prohtex** [comment]
Is it? I would love to use "Show Desktop" for a hotkey.

**Comment by ratbeard** [comment]
Me too.  Is there a way to reference https://github.com/tekezo/Karabiner-Elements/blob/667ea2253f6a7d9a60291aa508df7bba028d682a/src/share/apple_hid_usage_tables.hpp#L22 ?

**Comment by hackur** [comment]
Change the "to key" to `f11` and it will show the desktop.
