### ISSUE TITLE
System Preferences > Keyboard > Modifier Keys… doesn't work for external keyboard when Karabiner-Elements is running

### ISSUE THREAD

**Issue by marlonrichert** [tekezo/Karabiner-Elements#609]
Since I upgraded to Mac OS Sierra, System Preferences > Keyboard > Modifier Keys… no longer works for external keyboards while Karabiner-Elements is running. Instead, whatever you set for the built-in keyboard will be used for _all_ keyboards and changing the settings for an external keyboard no longer does anything.

Quitting Karabiner-Elements fixes the problem.

**Comment by andyngo** [comment]
Same. I had to add 2 items in Karabiner Elements just to get the modifier keys to work again.

![screen shot 2017-02-08 at 10 06 39 am](https://cloud.githubusercontent.com/assets/278293/22720573/8cadb652-ede6-11e6-8052-b9ca8e3babf7.png)

**Comment by egeriis** [comment]
Is it possible to do this mapping for external keyboard only?

**Comment by batizhevsky** [comment]
>  it possible to do this mapping for external keyboard only?

+ one for this. I have as external an pc keyboard and it will be nice to use Karabiner when I use it
