### ISSUE TITLE
Keep Modifier Keys separate for each keyboard

### ISSUE THREAD

**Issue by keito** [tekezo/Karabiner-Elements#61]
I use both an Apple (internal) keyboard and a Microsoft keyboard. In System Preferences -> Keyboard -> Modifier Keys, I have it set so that on the Apple keyboard it uses the default Modifier Keys, and on the Microsoft keyboard it swaps ⌘ and ⌥ (so that on both keyboards, the physical location of the ⌘ and ⌥ keys are the same). When I run Karabiner-Elements, the modifier keys are set to the same on both keyboards, so on the Microsoft keyboard, the location of the ⌘ and ⌥ keys are in the wrong place. Seil doesn't have this problem. Can it be made so the modifier keys can remain separate for each keyboard?

**Comment by eriktaubeneck** [comment]
+1 for this. even if it's just a setting in the JSON file for now.

**Comment by eriktaubeneck** [comment]
I'm sure this package is exploding with the Sierra launch today, but if anyone knows where the code in Karabiner is that creates the option for not remapping Apple keyboards, I'd be happy to *try* and contribute. (That said, I'm not a C++ expert, so no idea if I'd be successful.)

**Comment by LouisPlisso** [comment]
+1

**Comment by santosli** [comment]
+1

**Comment by volsk** [comment]
+1

**Comment by ldriscoll** [comment]
+1

**Comment by eriktaubeneck** [comment]
If you are new to this thread, please use the new voting feature at the top rather than posting a "+1" post.

**Comment by iplus26** [comment]
Having the same issue here. I uninstalled the old Karabiner.app and installed the Karabiner-Elements, then restarted my macOS and finds out that system key modifier not working. Though it was due to me uninstalling the old one but it turns out that Karabiner-Elements caused that. 

I need F1-12 remapping in Karabiner-Elements but I want to keep the key mapping separate for different keyboards (Apple's key modifier in system preferences is fine). Looking forward to updates.

**Comment by tekezo** [comment]
You can ignore devices in the latest version.

**Comment by hurrymaplelad** [comment]
@tekezo thanks for the update! Progress for sure, but still not quite right for me.

I use a Microsoft keyboard on an Apple laptop, with VIM-style keybindings. I'd like to map Caps Lock to Escape on all devices, but only swap Command  and Option with the Microsoft keyboard.

Any plans to support such a scheme?

**Comment by eriktaubeneck** [comment]
@hurrymaplelad you can accomplish this by mapping Command and Option on the Microsoft keyboard in Karabiner-Elements, and mapping Cap Locks to Escape in the macOS keyboard settings (with the "Modifier Keys..." button.)

**Comment by hurrymaplelad** [comment]
Thanks @eriktaubeneck! Didn't realize Caps Lock -> Escape was added to Modifier Keys. Works for me!
