### ISSUE TITLE
How to specify an application for the keyboard mapping

### ISSUE THREAD

**Issue by thalesco** [tekezo/Karabiner-Elements#610]
On the previous Karabiner the file private.xml located in allows to specify an application or a list of application like described in the manual:
_Add an application definition to your private.xml.
Add <appdef> to your private.xml.__ 

Is there a wait to do the same behaviour with Karabiner-Elements for example with some flag in karabiner.json file ?

**Comment by petergaultney** [comment]
this is the main thing I'm missing from Karabiner. I like to have different key mappings for when I'm working in the terminal vs normal usage, but manually swapping profiles is a pain.

**Comment by jixiuf** [comment]
try http://www.hammerspoon.org

 https://github.com/jixiuf/dotfiles/blob/master/mac/hammerspoon/app_bind.lua#L68

example: bind Ctrl-j to Down for finder 
```
local finderWindowFilter = hs.window.filter.new('Finder')
enableHotkeyForWindowsMatchingFilter(finderWindowFilter, hs.hotkey.new({"ctrl"},"J", keyCode("Down"),nil ,keyCode("Down")))
```

**Comment by petergaultney** [comment]
thanks for the link. I don't think that'll do what I want it to, because I actually swap modifier keys when switching profiles - LCtrl becomes LCmd and vice versa, since Cmd is not really useful in a terminal, but Ctrl is extremely useful, and I want the more useful modifier underneath my thumb instead of my pinky.

**Comment by LucaMarconato** [comment]
I really hope this feature will be implemented soon!

**Comment by wincent** [comment]
Probably a duplicate of #137.
