### ISSUE TITLE
Control_L only send Esc

### ISSUE THREAD

**Issue by dtothefp** [tekezo/Karabiner-Elements#611]
This was my favorite feature for VIM and I'm sad without it. Any port over for karabiner-elements?

<img width="381" alt="screen shot 2017-02-06 at 9 01 42 pm" src="https://cloud.githubusercontent.com/assets/4656726/22678511/8b71eb92-ecaf-11e6-863a-439f4dbafade.png">

**Comment by delphinus** [comment]
#247 is the fork you want

**Comment by dtothefp** [comment]
@delphinus thanks for the info, that's awesome. Sorry I'm a noob, only added Karabiner configs through the UI before. Looking through the thread of https://github.com/tekezo/Karabiner-Elements/pull/247 I see that I should edit `~/.karabiner.d/configuration/karabiner.json` but after I install the latest release https://github.com/wwwjfy/Karabiner-Elements/releases/tag/0.90.86 I don't see that file created anywhere? Should I create it or is something wrong?

**Comment by delphinus** [comment]
The place for `karabiner.json` has moved to `~/.config/karabiner/`. It has mentioned [here](https://github.com/tekezo/Karabiner-Elements/pull/247#issuecomment-269908153)

**Comment by dtothefp** [comment]
Awesome...thanks @delphinus this solved my issue. I found that I also had the regular Karabiner app installed and it was overwriting my profile in `~/.config/karabiner/`. Removing that app, and using the fork you suggested solely solved my problem
