### ISSUE TITLE
Ho Do I do this?

### ISSUE THREAD

**Issue by NRKorsakov** [tekezo/Karabiner-Elements#612]
Hi!

I'm really missing Karabiner, and am so glad this is being built!

Forgive the question, but can anyone tell me how to reprogram the help key to do something else?

I did it in Karabiner Elements, but it doesn't work.

I am using a MacAlly IKey keyboard with OS X 10.12.3

I've attached below the two Karabiner Elements windows, as well as what shows up in Event-Viewer when I hit the help key on the MacAlly keyboard

Thanks very much!!!

![untitled c](https://cloud.githubusercontent.com/assets/25620049/22707707/a7e06bb8-ed41-11e6-96a1-65f6375080ad.jpg)
![untitled a](https://cloud.githubusercontent.com/assets/25620049/22707719/b074c29c-ed41-11e6-89e9-44a545825916.jpg)
![untitled b](https://cloud.githubusercontent.com/assets/25620049/22707721/b49e591e-ed41-11e6-9c2a-3338bbda7b73.jpg)

**Comment by bcbishop** [comment]
FWIW, I've had [this same issue](https://github.com/tekezo/Karabiner-Elements/issues/566) with help key remapping not working. Replicated across several different keyboards, so it's likely not an issue with your particular configuration.
