### ISSUE TITLE
Any plans for fn + num to keypad num?

### ISSUE THREAD

**Issue by jackbrannen** [tekezo/Karabiner-Elements#613]
One feature I loved from Karabiner on macOS 10.11 was using fn + number keys to emulate the keypad keys on extended keyboards. Any plans to bring this back?

**Comment by gusaiani** [comment]
I second that.

**Comment by clayton-grey** [comment]
Thirded.

**Comment by fabiano-bastos** [comment]
I second that.

**Comment by zevlac** [comment]
Me too!

**Comment by howiemnet** [comment]
Yup - this was my single reason for using Karabiner. I raised it here: #382 but it's really a dupe of #16 (Multiple keystrokes as one). Someone's done a branch that'll handle multiple-to-multiple keypresses but it's not trunk yet. Keep watching this space, I guess

**Comment by fabiano-bastos** [comment]
news?

**Comment by katowulf** [comment]
Why is additional activity needed to keep a feature request opened? It's still a valid feature request and a popular one. Should we just submit a "me too" and "still need this" every month or two? ¯\_(ツ)_/¯
