### ISSUE TITLE
Any plans for diamond cursor? (ctrl + jkli)

### ISSUE THREAD

**Issue by jackbrannen** [tekezo/Karabiner-Elements#614]
One feature I loved from Karabiner on macOS 10.11 was using ⌃jkli as arrow keys. Any plans to bring this back?

**Comment by walt-r** [comment]
+1 for this or the more general ability to map any combination key press (e.g. "ctrl + j" maps to down arrow).

**Comment by stewartpark** [comment]
+1 for this.

**Comment by cray0000** [comment]
You can use [⌘英かな](https://ei-kana.appspot.com/) for it and for other simple multikey remaps.

**Comment by jixiuf** [comment]
with [hammerspoon](http://www.hammerspoon.org) 
you can   implements hotkey for different app
you can bind   j k h l without ctrl in  finder 
https://github.com/jixiuf/dotfiles/blob/master/mac/hammerspoon/app_bind.lua#L97
```
enableHotkeyForWindowsMatchingFilter(finderWindowFilter, hs.hotkey.new({},"J", keyCodeIfUnediabled("Down"),keyCodeIfEdiabled("j") ,keyCodeIfUnediabled("Down")))
enableHotkeyForWindowsMatchingFilter(finderWindowFilter, hs.hotkey.new({},"K", keyCodeIfUnediabled("Up"),keyCodeIfEdiabled("k") ,keyCodeIfUnediabled("Up")))
```
