### ISSUE TITLE
Problems downloading installation

### ISSUE THREAD

**Issue by jamietsao** [tekezo/Karabiner-Elements#615]
https://pqrs.org/osx/karabiner/ doesn't work.  DNS problem?

**Comment by cro** [comment]
Seems OK from where I sit:

http://www.downforeveryoneorjustme.com/pqrs.org/osx/karabiner/

**Comment by jamietsao** [comment]
Strange.  Doesn't work for me or my colleague.  Was able to hit the mirror site: http://tekezo.github.io/pqrs.org/, which had instructions to look for binaries here: https://github.com/tekezo/pqrs.org/tree/master/webroot/osx/karabiner/files

Downloaded latest "Karabiner-Elements-0.90.86.dmg".  All good now.
