### ISSUE TITLE
Exact HID layer changes in Sierra

### ISSUE THREAD

**Issue by light2yellow** [tekezo/Karabiner-Elements#617]
Hello. We are also working with keyboard events (https://github.com/mattanger/ckb-next). Unfortunately the Sierra update broke our project too. Could you please expand on those changes in `DEVELOPMENT.md` or here? What exactly has changed and what to use instead. Or give a link on something extensively describing it, we failed to find one and are kind of lost now because none of us has macOS driver writing experience.

**Comment by Cottser** [comment]
Just poking around the issues, maybe the link in https://github.com/tekezo/Karabiner-Elements/issues/678 is relevant to you?
