### ISSUE TITLE
Please make Keyboard Type per keyboard setting

### ISSUE THREAD

**Issue by dsvensson** [tekezo/Karabiner-Elements#618]
When I use the laptop keyboard I have to have karabiner set to 'ANSI', and when I'm using my external keyboard I need to have karabiner set to 'ISO'. Could karabiner perhaps remember this per keyboard?

**Comment by tekezo** [comment]
Unfortunately, it's not possible.
Please use profiles.

**Comment by fjeddy** [comment]
This is indeed possible if you just make it, so please, make it.

**Comment by raine** [comment]
Would also find this useful. For some reason I have to always select ANSI for Apple Wireless Keyboard, and ISO for Microsoft Sculpt, even though they are both ISO layout keyboards.

**Comment by raine** [comment]
There's nothing stale about this, this is a real issue.
