### ISSUE TITLE
Clear-key on numpad disabled after installing karabiner elements

### ISSUE THREAD

**Issue by tigersoul925** [tekezo/Karabiner-Elements#621]
Hi,

After installing karabiner elements, the clear-button on the numpad is disabled. It will not work and no event is produced in the eventviewer. The same thing happens to the attached usb-numpad. Is this a known issue?

Clarification: clear-button is the button to the left of the equal-key. It's normally used to clear the calculator but I use it for other purposes.

EDIT: never mind, right after writing this it seems to be working again. I do have a weird situation however with a tap on 5 on the external numpad means I get the sequence: numlock 5 numlock.

**Comment by carrigmore** [comment]
Hi I find the clear button is not working for me either. How you resolved this?

I need to use that key as windows numlock key. Or I cannot use the num pad correctly. 

Previous version I can specify <autogen>__KeyToKey__ KeyCode::KEYPAD_CLEAR, KeyCode::VK_IOHIKEYBOARD_TOGGLE_NUMLOCK</autogen>

in the private.xml file. I don't know how to achieve the same in elements? thanks.
