### ISSUE TITLE
Possible to bind keys if no other modifiers pressed?

### ISSUE THREAD

**Issue by alancwoo** [tekezo/Karabiner-Elements#622]
I was wondering if there is any way to bind a key `if no other modifiers pressed` as in the original Karabiner?

I would normally bind ` to ESC, and still have access to ~ as the modifier would allow the override.

Apologies if I've missed an existing issue somewhere, but I haven't been able to find anything on this particular issue.

**Comment by hartman** [comment]
Exact same wish here
