### ISSUE TITLE
Remap Caps->Ctrl does not work when Karabiner-Elements is running

### ISSUE THREAD

**Issue by ovikholt** [tekezo/Karabiner-Elements#628]
Using Mac's built-in remap (at Settings -> Keyboard -> "Modifier Keys..."). After starting K-E, remap is not effective anymore and Caps acts as a normal Caps again :(.

**Comment by lionel-** [comment]
The README says it's a known limitation.

**Comment by lazee** [comment]
Do that mapping inside Karabiner-Elements as well. 

![Screenshot](https://photos-5.dropbox.com/t/2/AAAbTn3RLKjQIwL6KwAE6P-MO_gqEb4aMkn_tcVNXEpE7A/12/5549544/png/32x32/3/1487534400/0/2/Skjermbilde%202017-02-19%2016.40.38.png/EOHbkwQYgEQgBygH/fUeIlJTeNDtQwO5dUmPs5KsnhppPMO0LKqvxgdyuAMk?dl=0&size=32x32&size_mode=5)

**Comment by ovikholt** [comment]
@lionel- You're absolute right. My bad for not reading properly.

@lazee Thanks a lot!  For me, this might mean the difference of returning or keeping my newly purchased 2016 MBP.
