### ISSUE TITLE
Media keys not working

### ISSUE THREAD

**Issue by shaungrady** [tekezo/Karabiner-Elements#63]
Keyboard: `Logitech G710+`
KE version: `0.90.34`

Broken keys:
- Play/Pause
- Stop
- Previous Track
- Next Track
- Mute

EventViewer doesn't show any inputs for those keys while KE is running.

**Comment by charlietran** [comment]
I was having the same issue because I was trying to bind them to my Print screen, Scroll Lock, and Pause keys on my keyboard, which previously responded to `f14, f15, f16`. However it looks like Karabiner-elements doesn't map them that way, and it works for me now that I bind them by their labeled names:

```
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "print_screen": "vk_consumer_previous",
                "scroll_lock":  "vk_consumer_play",
                "pause": "vk_consumer_next"
            }
        }
    ]
}
```

**Comment by shaungrady** [comment]
Good to know there's a workaround, but I'd like the keyboard's native media keys to act as media keys. :)

**Comment by bellwood** [comment]
I'm using a Dell Media Keyboard (TH836) and would absolutely love to see the volume knob working.

Event viewer shows nothing for this so I've been using:

F10 - mute
F11 - vol down
F12 - vol up

The other media keys work OK, just not the volume knob

**Comment by adamdehaven** [comment]
I'm using a Ducky One (which has three volume keys at the top right: mute, volume down, and volume up). I can't get them to even register when I press. They worked in regular Karabiner as `ConsumerKeyCode::VOLUME_MUTE`, `ConsumerKeyCode::VOLUME_DOWN`, `ConsumerKeyCode::VOLUME_UP`

**Comment by Sooongz** [comment]
The version 0.90.55 works well.

**Comment by incandescentman** [comment]
What fixed this problem for me is going to Devices > Modify events from this device, and disabling a extra keyboard that was listed there and checked but that is not the one I'm using.

**Comment by cwagner22** [comment]
@incandescentman Are you sure Karabiner is still enabled for your keyboard? Probably not anymore, that's why the media keys are working.

**Comment by dirkduellmann** [comment]
Same symptoms for media keys and volume knob on Logitech G610. In addition, here also the keyboard illumination key is disabled.

**Comment by HerrGrumps** [comment]
(my repo is a bit out of date just be aware) I added logging to the grabber's device_grabber::value_callback function to log usage_page and usage

for my Logitech G610 the media keys are (usage_page, usage)
12, 233/234 = volume
12, 226 mute
12, 205 play
12, 183 stop
12, 182 prev
12, 181 next


usage page 12 = kHIDPage_Consumer

the code has a case statement for kHIDPage_Consumer but it only handles usage == kHIDUsage_Csmr_ACPan, so basically all other "consumer" page events are dropped 😕 

At some point I am going to try modifying my copy here to see if I can simply "relay" these events (make the virtual KB fire these events). At this point I'm just mucking around, but if it works I'll see if I can make a PR for the fix.
