### ISSUE TITLE
Make build fails due to missing resources

### ISSUE THREAD

**Issue by EugeneAbramchuk** [tekezo/Karabiner-Elements#631]
```
In file included from /Users/eugene/gitrepo/Karabiner-Elements/src/lib/libkrbn/libkrbn_core_configuration.cpp:1:
In file included from /Users/eugene/gitrepo/Karabiner-Elements/src/share/core_configuration.hpp:4:
In file included from /Users/eugene/gitrepo/Karabiner-Elements/src/share/types.hpp:7:
/Users/eugene/gitrepo/Karabiner-Elements/src/share/system_preferences.hpp:6:10: fatal error: 'boost/optional.hpp' file not found
#include <boost/optional.hpp>
         ^

** BUILD FAILED **


The following commands produced analyzer issues:
	AnalyzeShallow libkrbn_core_configuration.cpp
(1 command with analyzer issues)

The following build commands failed:
	CompileC build/libkrbn.build/Release/libkrbn.build/Objects-normal/x86_64/libkrbn_system_preferences_monitor.o libkrbn_system_preferences_monitor.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
make[4]: *** [all] Error 65
make[3]: *** [all] Error 2
make[2]: *** [all] Error 2
make[1]: *** [build] Error 2

make: *** [all] Error 99
```

**Comment by anthony-khong** [comment]
I had the same exact problem. The build failed, because it cannot find a boost header file. Try `brew install boost`.

**Comment by madisonbullard** [comment]
@anthony-khong that worked for me, thank you

**Comment by notTag** [comment]
This worked for me as well. Thanks @anthony-khong

**Comment by yongboYX** [comment]
@anthony-khong thank you very much

**Comment by Bisgates** [comment]
Worked for me as well, thanks ; )

**Comment by exsilica** [comment]
I am curious, is it not looking for boost in its default root directory? I have boost here in `usr/local/opt/1.68.0_1/include/boost` and slinked in `opt/local/include/boost` but still return this set of errors. Based on closed issues here it looks like that is where it should be looking for boost, so I am a bit stumped.

**Comment by exsilica** [comment]
I am curious, is it not looking for boost in its default root directory? I have boost here in  `opt/local/include/boost` according to the readme and slinked in`usr/local/opt/1.68.0_1/include/boost` but still return this failure.
