### ISSUE TITLE
Das Keyboard 4C: FN key not recognized in EventViewer

### ISSUE THREAD

**Issue by cavega** [tekezo/Karabiner-Elements#632]
I've installed Karabiner-Elements on my Mac running 10.11.6 and FN key presses are not recognized in EventViewer. As such, my FN keys are not working for the default settings (i.e. F1 brightness down, etc).

The only modifications I've made in Karabiner and OS are the following:

- Simple Modifications tab
    - left_command -> left_option
    - left_option -> left_command
    - right_option -> right_command
- Devices tab
    - Marked checkbox so that Karabiner only modifies evetns for the Das Keyboard 
- Mac Keyboard Preferences
    - Marked checkbox for "_Use all F1, F2, etc. keys as standard function keys_"

**Current FN key behavior:**

- Pressing the FN key along with F1 does "mute" option (like is printed on keyboard\
- Pressing the FN key along with F2 does "volume down" option (like is printed on keyboard
- Pressing the FN key along with F3 does "volume up" option (like is printed on keyboard
- Same for other keys, pressing FN+F<number> executes the same function as if I did not have Karabiner-Elements installed.

**Expected Behavior:**

- Pressing FN+F<number> will work as described in the default "Function Keys" settings and allow me to change brightness with F1-F3, etc.

**Comment by corningsun** [comment]
I got the same problem.
I opened the **EventViewer**, and press the **FN** key, but nothing happend.

Mac os Serria 10.12.3
KeyBoard: FILCO FKBN104M/EMU2

**Comment by nguyenhimself** [comment]
Did it work for you back in the old Karabiner?

Because [the FAQ](https://pqrs.org/osx/karabiner/faq.html.en) states that Karabiner may not be able to remap the Fn key for external keyboard.

**Comment by cavega** [comment]
@nguyenhimself The old Karabiner had way too many settings and I gave up on it pretty quickly, hence why I decided to try Karabiner-Elements instead. Regarding the FN comment in the linked FAQ, I've previously read it but ignored it since it specifically mentions Logitech not DAS or any other brand. My other keyboard (WASD) FN key works fine with Elements (just had to swap fn and application functions). I'll try again the old Karabiner and see if the EventViewer register FN presses.

**Comment by benwoodward** [comment]
Has anyone found a way to get the fn button to work on a DAS? I'm using a DAS Ultimate, EventViewer doesn't recognise the fn key, but prints it's code (0x6e). Can't find a way to map this key code to 'fn'.

![image](https://user-images.githubusercontent.com/1472981/28397672-6c0a3c4c-6d46-11e7-8af2-130cb6b910d5.png)

**Comment by kiryph** [comment]
I'm also using the `daskeyboard 4c professional` and karabiner-elements 11.1.0 does not recognize the function key. Any chance that this will change?

**Comment by nguyenhimself** [comment]
@benwoodward Well this is easier. That fn key's name is shown as 'application", so you should be able to remap it as something normally. Just look for "application" way down in the dropdown menu.

![screen shot 2017-11-07 at 11 31 28 am](https://user-images.githubusercontent.com/482270/32477233-40a0c87c-c3af-11e7-8ebc-73d47dce2af9.png)

**Comment by JJPro** [comment]
I can confirm that the issue still persists in late 2022. I thought my switch has gone bad, so I soldered the switch without luck, then I suspected the PCB has gone bad, until I found this post. 
As soon as I quit Karabiner, `Fn` starts working fine.
