### ISSUE TITLE
Is this possible on macOS Sierra with Karabiner Elements? (screen)

### ISSUE THREAD

**Issue by dodvip123** [tekezo/Karabiner-Elements#635]
![aenbn](https://cloud.githubusercontent.com/assets/15620248/23339538/6a5b6f16-fc25-11e6-8e9b-97776abcdfa8.png)

**Comment by nguyenhimself** [comment]
Since I use a Logitech M570 mouse, I was just about to ask about this also.
Alternatively, is it possible to use both Karabiner and Karabiner Elements at the same time?

**Comment by mhumeSF** [comment]
@nguyenhimself from https://pqrs.org/osx/karabiner/

> Karabiner does not work on macOS Sierra at the moment.
> 
> We are developing Karabiner-Elements which provides simple key modification for macOS Sierra at first. (Karabiner-Elements works well on macOS Sierra. We are working on fixing several remaining issues.)
> 
> We'll start updating for the full featured Karabiner for Sierra after Karabiner-Elements is completed.

I'd drop Karabiner and focus on what you can get working in Karabiner-Elements, as it sounds it is laying the ground work for a fully-featured Karabiner for masOS Sierra.
