### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by DeliciousPickle** [tekezo/Karabiner-Elements#638]
Using Sierra 10.12.3.  Tried mapping L_option to L_command and L_command to L_option.  Keyboard function doesn't change at all.  Event viewer shows L_option still firing opt and L_command still firing cmd.  Also, if I quit Karabiner Elements and restart, neither of the mappings I created appear.  It seems Karabiner is not saving my mappings.

Any suggestions about how to make this work?  Is there a hidden "Save" or "Apply" button or menu choice that I'm missing?

**Comment by mhumeSF** [comment]
@DeliciousPickle I am not able to reproduce your error. Was able to remap L_option to L_command and vise versa, all on the fly without any hidden "Save" or "Apply". Can you confirm these changes are being applied to the keyboard you are using? i.e. Internal Keyboard vs Magic Keyboard

**Comment by gmoothart** [comment]
I have this problem too. New macbook pro with 10.12.4, karibiner-elements 0.90.92

**Comment by ToastyKen** [comment]
Same here. Fresh MacBook Pro with 10.12.4, Karabiner-Elements 0.90.92.  Installed, and it launches. But when I add any configs, they don't work. And when I close the config window and re-open it, anything I added is gone.  Nothing interesting in the logs. :\

**Comment by ToastyKen** [comment]
And to answer someone else, this is on a 2014 MacBook Pro with just the internal keyboard. No external peripherals at all.

**Comment by ToastyKen** [comment]
Okay I figured out my case at least.  As per a comment in https://github.com/tekezo/Karabiner-Elements/pull/686   Karabiner started using ~/.config/karabiner to write its config in v0.90.71.

In my case, my ~/.config directory was owned by root, with no write permissions for my user.  I used:

sudo chown $USER ~/.config

and that fixed it!
