### ISSUE TITLE
Nothing works ...

### ISSUE THREAD

**Issue by TonyStarck** [tekezo/Karabiner-Elements#641]
Hello,

I'm on Sierra 10.12.3 and Install Karabiner Elements v0.90.86.
When I configure map a touch "a" to "b" and quit Karabiner and reload the configuration is lost.
Is it normal?

**Comment by TonyStarck** [comment]
I have tested with version v0.90.48 and this works and save parameters.
Do you have an idea?

**Comment by ToastyKen** [comment]
Okay I figured out my case at least.  As per a comment in https://github.com/tekezo/Karabiner-Elements/pull/686   Karabiner started using ~/.config/karabiner to write its config in v0.90.71.

In my case, my ~/.config directory was owned by root, with no write permissions for my user.  I used:

sudo chown $USER ~/.config

and that fixed it!
