### ISSUE TITLE
Keypad comma period ...

### ISSUE THREAD

**Issue by TonyStarck** [tekezo/Karabiner-Elements#643]
Hello,

I want only use Karabiner elements to remplace the keypad , to the .
In karabiner elements the keypad period is : 
Why, Why, WHY !? :)

**Comment by jvdurme** [comment]
I would like to see this issue solved too. Cannot seem to change the keypad comma to a period, while in Karabiner it was possible.

**Comment by TonyStarck** [comment]
I use keyboard maestro and I have solved this problem but it's not free ...

**Comment by delucasvb** [comment]
I have the same problem. Changing Keyboard Type to ISO changes nothing. I've also tried all other symbols (which are all wrong, e.g. using semicolon outputs an 'm') without finding a dot.

**Comment by Nehon** [comment]
If it helps I managed to make it work by adding this rule to the ~/.config/karabiner/karabiner.json config file
```
{
                        "description": "keypad , to .",
                        "manipulators": [
                            {
                                "from": {
                                    "key_code": "keypad_period",
                                    "modifiers": {
                                        "optional": ["any"]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "keypad_period",
                                        "modifiers": ["left_shift"]
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    },
```

**Comment by rcsapo** [comment]
Will this also work on a QWERTZ keyboard? And where in the karabiner.json file should I insert the code? In addition, when I tried to save the file (I used TextWrangler for editing) it automatically reverted back to the original state after reopening. Any help would be much appreciated!

**Comment by JakeShelterwin** [comment]
Nehon please can you tell us where exacly in ~/.config/karabiner/karabiner.json we should put your modification? Like rcsapo said every "non official" edits reverts back when karabiner is relaunced...

**Comment by jvdurme** [comment]
It is best to make a new .json file with just that code inside instead of adding it to karabiner.json.
Make a new .json file in ~/.config/karabiner/assets/complex_modifications/
with just your code inside. That should work. That's how I did it.

**Comment by JakeShelterwin** [comment]
@jvdurme Thank you, I used atom to create the json file (although I had to change the extension after it was saved)... and I place it in the folder you said... but now I'm stuck: on karabiner complex modification nothing appear... Can you tell me each of the steps please?

**Comment by jvdurme** [comment]
Voila! Glad you got it working. :-)

**Comment by rcsapo** [comment]
Thanks for the code and instructions. To make this work on a German QWERTZ keyboard, replace "modifiers": ["left_shift"] by "modifiers": ["right_option"]

**Comment by ertoorule** [comment]
for us keyboards right shift + keypad period to comma


{
  "description": "keypad . to ,",
  "manipulators": [
    {
      "from": {
        "key_code": "keypad_period",
        "modifiers": {
          "mandatory": [
            "right_shift"
          ],
          "optional": ["any"]
        }
      },
      "to": [
        {
          "key_code": "comma",
          "modifiers": ["keypad_period"]
        }
      ],
      "type": "basic"
    }
  ]
}

**Comment by Foberski** [comment]
Hi All,

I simply want to swap these keys and this does not seems to work with the script. Im not a real scripter but when I try to get did done the , on the keypad (shift+keypad-.) it give me a >

I want to swap the keypad-. with shift-keypad-. 

I used tho use double command for this but it does not work anymore on my MacOS.
Is anybody able to do this?

**Comment by pikawika** [comment]
The following not only allows you to flip , with . but also the shift action for original . with ,



JSON file: 

```json
{
  "title": "keypad comma to period",
  "rules": [
    {
      "description": "keypad . to ,",
      "manipulators": [
        {
          "from": {
            "key_code": "keypad_period",
            "modifiers": {
              "mandatory": [
                "shift"
              ]
            }
          },
          "to": [
            {
              "key_code": "keypad_period"
            }
          ],
          "type": "basic"
        }
      ]
    },
    {
      "description": "keypad , to .",
      "manipulators": [
        {
          "from": {
            "key_code": "keypad_period"
          },
          "to": [
            {
              "key_code": "keypad_period",
              "modifiers": [
                "left_shift"
              ]
            }
          ],
          "type": "basic"
        }
      ]
    }
  ]
}
```

**Comment by bellaj** [comment]
solution was to import Keypad Period to Comma+shift (period) Belgian Keyboard
 from
https://ke-complex-modifications.pqrs.org/
