### ISSUE TITLE
Full functionality as old karabiner?

### ISSUE THREAD

**Issue by xeor** [tekezo/Karabiner-Elements#644]
Is the goal of Karabiner-Elements to be just as powerfull as the old karabiner? It seams like it is way to basic for a lot of people right now (based on the issues).

In the old karabiner, I was able to make fancy stuff, like:
```xml
<item>
    <name>Double right shift to F18</name>
    <appendix>Maps doublepressing of the right shift to a key</appendix>
    <identifier>private.rightshift_to_f18</identifier>
    <autogen>
        __DoublePressModifier__
        KeyCode::SHIFT_R,
        KeyCode::SHIFT_R,
        KeyCode::F18
    </autogen>
</item>
```

and

```xml
<item>
    <name>Right cmd to 4*meta with double tap to special character</name>
    <appendix>Maps holding right cmd to 4*meta combo, and double tapping right cmd to a special character injected by keyboard maestro.</appendix>
    <identifier>private.right_cmd_double_useful</identifier>
    <autogen>
        __KeyToKey__
        KeyCode::COMMAND_R,
        KeyCode::COMMAND_L, ModifierFlag::OPTION_L | ModifierFlag::SHIFT_L | ModifierFlag::CONTROL_L,

        Option::KEYTOKEY_DELAYED_ACTION,
        KeyCode::VK_NONE,

        Option::KEYTOKEY_DELAYED_ACTION_CANCELED_BY, KeyCode::COMMAND_R,
        KeyCode::D | ModifierFlag::OPTION_L | ModifierFlag::SHIFT_L,
        KeyCode::VK_KEYTOKEY_DELAYED_ACTION_DROP_EVENT, <!-- drop second key event -->
    </autogen>
</item>
```

If this is not in scope for karabiner-elements, please give us a heads-up so we can find another way for our muscle-memory to be happy.. :)

**Comment by LynnWalton** [comment]
I have been trying not to ask this, to avoid slowing tekezo down but it would be reassuring to know at this point if he has enough experience at this point with the new drivers to predict whether the more advanced functionality is going to be possible and we just need to be patient or whether he's learned anything that would make him feel that it will not be possible for him to implement things like the VI style keys that use space as a modifier, etc.

**Comment by quaritexa** [comment]
I tired waiting for new karabiner and switched to [Hammerspoon](http://hammerspoon.org).
I think with Hammerspoon you can implement all features old Karabiner and even more.

**Comment by LynnWalton** [comment]
quaritexa (or anyone else) ... Any chance you could provide some guidance on how to achieve something like the TouchCursor options and the MouseKeys Mode v2 in Karabiner using Hammerspoon?  And are you using Karabiner-Elements in conjunction with Hammerspoon or can you make Hammerspoon do the multi-key press stuff all on its own?  I took a look at it and I don't mind learning the language syntax, but need to have a little more of an example to build on than I saw in the getting started guide.  Thanks.

**Comment by laktak** [comment]
>  I think with Hammerspoon you can implement all features old Karabiner and even more.

Last time I looked you could not bind the left/right command/option keys separately.

**Comment by quaritexa** [comment]
[This](http://www.hammerspoon.org/docs/hs.eventtap.event.html#getKeyCode) can recognise any modifier and help to bind it.

**Comment by laktak** [comment]
@quaritexa apparently it's not trivial: https://github.com/Hammerspoon/hammerspoon/issues/1278#issuecomment-289646584

**Comment by quaritexa** [comment]
https://github.com/Hammerspoon/hammerspoon/issues/1039
