### ISSUE TITLE
Problem with OpenEmu

### ISSUE THREAD

**Issue by ghost** [tekezo/Karabiner-Elements#645]
When I'm using OpenEmu with Karabiner Elements (KE) switched on, the OpenEmu in-game controls doesn't work anymore with either my external keyboard or MBP's keyboard.

I'm only using KE for the usual mapping of F1-F12 on my external keyboard. I don't map keys like QWERTY or arrow keys.

Quitting KE solve this problem with OpenEmu. Is this a bug with KE or OpenEmu?

Specs: MBP 2012, macOS Sierra 10.12.3, external Logitech K270 keyboard

Edit: I don't have this problem when I'm using the old Karabiner in OSX El Capitan.

**Comment by sotojuan** [comment]
Same problem in Sierra when mapping Caps Lock to Escape.

**Comment by carlosvigil** [comment]
i disable KE when I use OpenEmu

**Comment by NinoScript** [comment]
I keep a profile, just for OpenEmu, where everything in the `Devices` tab is disabled. Even if this could somehow be fixed, KE seems to add a bit of lag too (noticeable in rhythm games), so I think it's better to just turn it off for OpenEmu.

**Comment by BenjaminVanRyseghem** [comment]
it looks like only modifiers are seen from OpenEmu with Karabiner-Elements running
