### ISSUE TITLE
Long-pressing swapped keys performs erratically 

### ISSUE THREAD

**Issue by EDmitry** [tekezo/Karabiner-Elements#65]
Thank you for your efforts on Karabiner!

While trying latest Elements I have noticed that when swapping the backspace key with backslash and then holding a backslash the input stutters and even hangs completely sometimes. Here are my settings:

```
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "delete_or_backspace": "backslash",
                "backslash": "delete_or_backspace"
            }
        }
    ]
}
```

**Comment by tekezo** [comment]
I've improved the key repeat handling at v0.90.36.
Could you confirm whether this issue has fixed in the latest version?

You can upgrade to the latest version from "Misc > Check for updates" or
https://pqrs.org/latest/karabiner-elements-latest.dmg

**Comment by EDmitry** [comment]
Works perfectly! Thank you!
