### ISSUE TITLE
"add item" & "add profile" buttons do nothing

### ISSUE THREAD

**Issue by walkermalling** [tekezo/Karabiner-Elements#652]
"add item" & "add profile" buttons do nothing

Karabiner-Events `0.90.89`

on macOs Sierra `10.12.3`

I also have Seil installed, which *also* has issues with Sierra, and links to this Karabiner-Elements project

**Comment by rampion** [comment]
I have the same issue; same versions of Karabiner-Events and MacOS. I used to have Seil installed, but have uninstalled it and restarted.  The issue persists.

**Comment by madcarrot** [comment]
Same issue here.

**Comment by kanczug** [comment]
I have the same problem. Just uninstalled old Karabiner as it was not working after upgrade to sierra and can not add any key to change.

**Comment by mashpie** [comment]
same here, just posting to get updates on that - still thankful for karabiner and your work on it!

**Comment by madcarrot** [comment]
Temporary solution - Fork the repo, clone your fork and revert to commit `ab39980` - that's the `0.90.88` version which "Add item" works

**Comment by Paihiwo** [comment]
Whaaaaat? :(

**Comment by muzll0dr** [comment]
I was able to fix this on my install by opening the config directory `~/.config/karabiner` and just doing a `touch karabiner.json`

**Comment by Paihiwo** [comment]
@muzll0dr thank you very much. It's WORKING! You are great!

**Comment by tekezo** [comment]
Sorry for inconvenience.
I've fixed this issue at v0.90.90.
Please upgrade Karabiner-Elements.

**Comment by kanczug** [comment]
Thx! I'm loving my Mac again ;)
Donated ;)

**Comment by mashpie** [comment]
Thx a lot! Confirmed working.
