### ISSUE TITLE
Insert Key

### ISSUE THREAD

**Issue by Wolves0208** [tekezo/Karabiner-Elements#654]
How can I get an insert key to work on a pc keyboard when remote logging in to a windows pc?

I am at a loss

Thanks

**Comment by wondernet** [comment]
It looks that it doesn't map insert correctly at this moment: in event viewer I see 'help' instead of 'insert' when I map 'insert' to a specific key.

**Comment by BirkhoffLee** [comment]
Hey - I wonder this too, how do I make this work?

**Comment by BirkhoffLee** [comment]
I figured it out - in `~/.config/karabiner/karabiner.json`, add this rule to your main profile

```json
{
    "description": "Change fn + delete to insert",
    "manipulators": [
        {
            "type": "basic",
            "from": {
                "key_code": "delete_or_backspace",
                "modifiers": {
                    "mandatory": ["fn"]
                }
            },
            "to": [
                {
                "key_code": "insert"
                } 
            ]
        }
    ]
}
```

**Comment by vlad2135** [comment]
For some reason it does not work in Citrix Receiver, and disabling "Send special keys unchanged" Receiver option does not help...
