### ISSUE TITLE
Shortcut to disable laptop keyboard?

### ISSUE THREAD

**Issue by DrChr** [tekezo/Karabiner-Elements#655]
Hi,
Sometimes my infant daughter decides to press the keys just like daddy...
I would therefore like e.g. a keyboard shortcut that disables the keyboard until the same keyboard shortcut is used. Is this feature or something equivalent available?

If not, I'd like to suggest it's added.
/Christian

**Comment by limeblack** [comment]
@DrChr to disable trackpad and keyboard temporarily you can run the following.  http://apple.stackexchange.com/questions/177147/disable-trackpad-and-keyboard-temporarily  Although it sounds like a useful feature I think it would be difficult to implement and frankly not that popular.

So yeah I'm not 100% sure what do think.

**Comment by DrChr** [comment]
Thanks, for the link. I saw similar solutions while googling this and it's good to have a link in this thread.

A major downside of that approach in my use case is that it relies on having an external keyboard connected - the idea is to disable the laptop keyboard and only use the external keyboard. Apparently some people place the external keyboard _on_top_ of the laptop keyboard.  In my case, there's no external keyboard.

I can understand that it's unclear if this feature is worth the effort. Perhaps keep this thread open for a while and hope that other people provide more use cases, in addition to kids and cats attacking the keyboard :-)

PS.
I suppose I could write a program, that I start with a keyboard shortcut, and that:
- Executes the commands as per the link to disable the keyboard
- Has a clickable button, allowing me to enable the keyboard again via the touchpad

**Comment by ebeeson** [comment]
I installed Karabiner Elements looking for exactly this feature, for the same reason.

I believe I've used an app called [Keyboard Cleaner](http://jan.prima.de/~jan/plok/archives/48-Keyboard-Cleaner.html) for this sort of thing in the past, but it doesn't seem to be maintained.

Apparently you can also configure a toggle for [Mouse Keys](https://support.apple.com/kb/PH25642?locale=en_US) that disables the trackpad and much of the keyboard. At least it leaves you with many fewer targets for small hands to interfere with, as described here: http://www.mackungfu.org/cat-proofing-a-macbook-keyboard

**Comment by moble** [comment]
I would ***really*** love this feature.  Mouse Keys is no use at all — the cat/kids can still do major damage; my ten-month old twins go about 3 seconds before hitting one of the active keys.

The only good thing about Mouse Keys is that it's really easy to turn on.  There's an option to turn it on by hitting "alt" five times in a row.  Something like that in Karabiner would be awesome.

**Comment by razum2um** [comment]
Thinking about the same in context of "kids-proof" keyboard. What about a profile where all keys are mapped to non-existing F* keys. Still don't have an idea how of how to map everything except a hotkey like '5 times alt'

**Comment by su-thomas** [comment]
> I installed Karabiner Elements looking for exactly this feature, for the same reason.
> 
> I believe I've used an app called [Keyboard Cleaner](http://jan.prima.de/~jan/plok/archives/48-Keyboard-Cleaner.html) for this sort of thing in the past, but it doesn't seem to be maintained.
> 
> Apparently you can also configure a toggle for [Mouse Keys](https://support.apple.com/kb/PH25642?locale=en_US) that disables the trackpad and much of the keyboard. At least it leaves you with many fewer targets for small hands to interfere with, as described here: http://www.mackungfu.org/cat-proofing-a-macbook-keyboard

Looks like Keyboard Cleaner was updated on 2020-03-06, works great!
You could create a Karabiner complex modification to launch the app on a shortcut.
