### ISSUE TITLE
Fn is not being recognized on external keyboard in 0.90.90

### ISSUE THREAD

**Issue by jpopadak** [tekezo/Karabiner-Elements#656]
It worked in the previous build and not it is not working. I tried it with and without the `Use all F1, F2... keys as Standard Function Keys` option.

**Comment by ajbonner** [comment]
Experiencing same issue. Basically you cannot use the function keys as function keys at the moment.

**Comment by jpopadak** [comment]
This is not working still in 0.90.92.

**Comment by drewed** [comment]
I'm also seeing this on Logitech K750.

**Comment by carlsmith** [comment]
On some keyboards (Filco MINILA for example), the function key is only seen by the keyboard itself. Obviously, if your keyboard's function key was working before, then it should work again. I just wanted to remind anyone who comes across this issue in future to be sure their keyboard has a 'real' function key.

**Comment by carlsmith** [comment]
There also seems to be some confusion over what the issue is about exactly. I think this is about the Fn key, not F1, F2 etc.

**Comment by jpopadak** [comment]
It seems to see a difference between when I am using the <kbd>Fn</kbd> and not, but it gets tripped up on when to use the proper one.

With `Use all F1, F2... keys as Standard Function Keys` option, the following shows:

| eventType | code | name | flags | misc |
|----| ----|----|----|----|
| KeyDown |0x7a | f1 | Fn | characters: |
| KeyUp | 0x7a | f1 | Fn | characters: |

But then if i use <kbd>Fn</kbd> + <kbd>F1</kbd>, nothing registers.

Then I turn off the `Use all F1, F2... keys as Standard Function Keys` option, the following shows:

| eventType | code | name | flags | misc |
|----| ----|----|----|----|
| SysKeyDown | 0x7 | mute | | |
| SysKeyUp | 0x7 | mute |  | |

But again, then if i use <kbd>Fn</kbd> + <kbd>F1</kbd>, nothing registers.

**Comment by featalion** [comment]
I ran into the same problem. What is interesting, when I quit Karabiner-Elements and launch EventViewer, then I see both F1 (`0x7a`) and Mute (`0x7`) events. `Fn` key itself doesn't produce any key code. But when I launch Karabiner-Elements, then I see only F1 or Mute events, depends on Karabiner-Elements' configuration. It makes me positive in thinking, that the root of the issue is the HID kernel extension.
