### ISSUE TITLE
Return to Control_R (+ When you type Return only, send Return)

### ISSUE THREAD

**Issue by ChipNowacek** [tekezo/Karabiner-Elements#657]
[According to Bozhidar Batsov's article](http://emacsredux.com/blog/2013/11/12/a-crazy-productivity-boost-remap-return-to-control/), the ability to map return_or_enter to right_control via `Return to Control_R (+ When you type Return only, send Return)` was apparently available in KeyRemap4MacBook. Is there some way to do it now? (I'm on Sierra)

**Comment by walt-r** [comment]
This functionality has been implemented, or work arounds found.  See these issues for more info.

https://github.com/tekezo/Karabiner-Elements/pull/247

https://github.com/tekezo/Karabiner-Elements/pull/170#issuecomment-257091685

https://github.com/tekezo/Karabiner-Elements/issues/165#issuecomment-258762846

https://github.com/tekezo/Karabiner-Elements/issues/103#issuecomment-258765038

**Comment by ChipNowacek** [comment]
Thanks. Got it working from #247 using [this release](https://github.com/wwwjfy/Karabiner-Elements/releases/tag/0.90.90) with one line in the "standalone_keys" object:

`            "simple_modifications": {`
`                "return_or_enter": "right_control"`
`            },`
`            "standalone_keys": {`
`                "return_or_enter": "return_or_enter"`
`            }`

**Comment by tarlig** [comment]
This only works in the release mentioned by ChipNowacek. If I update from versin 90.90 to the latest, then this functionality breaks. Am I wrong?
