### ISSUE TITLE
feature request: auto switch profile

### ISSUE THREAD

**Issue by Zieng** [tekezo/Karabiner-Elements#659]
feature description:
> hope to switch to a profile when you plug in a specified keyboard, and switch back to another profile when you pull out it.

why should add this feature:
> most external keyboard is for PCs, which has different keyboard layout from apple's keyboard. It's likely that users may remap some keys in external keyboard (and save the modification in a profile) to make them suitable for macOS while keep the internal keyboard unchanged (another profile without these remap modification). So it would be very convenient if karabiner-elements can auto switch the profile based on if the external keyboard is plugged in.

**Comment by daeho117** [comment]
Seconding this!

**Comment by aetherwu** [comment]
It is great to have profile in the latest version! I'd love to have auto switch too!

**Comment by ktham** [comment]
Even better is to have different profiles apply to different keyboards you specify and avoid doing any switching altogether if that is possible

**Comment by sn0wyfall** [comment]
This would be very nice.

**Comment by nklmilojevic** [comment]
+1 Much need feature. There should be keyboard specific profiles. Every time I use my Macbook's keyboard I have to manually switch profiles because the external one needed remapping.

**Comment by knu** [comment]
[My workaround](https://github.com/knu/hs-knu#example-usb-watcher-and-shell-escaping)  is to use Hammerspoon's hs.usb.watcher and call K-E's CLI to switch between profiles when an external keyboard is attached.

**Comment by nklmilojevic** [comment]
Nice workaround, it solves my problem completely because I'm already using Hammerspoon for Hyper key shortcuts. Thanks!

**Comment by crisidev** [comment]
I am using Karabiner-Elements now and it does not have anymore a command line utility to switch profile. 

If you are interested, combining this to hammerspoon is quite easy.

It is a quick and dirty python hack: https://gist.github.com/crisidev/35b214c660ead41e036ec8a9c7e29cc1

**Comment by sn0wyfall** [comment]
Is there any way to do this now? Karabiner Elements has come a long way.

**Comment by goncalossilva** [comment]
There's also [autokbisw](https://github.com/jeantil/autokbisw) but I'd really rather only use one tool. 😄
