### ISSUE TITLE
Volume Up/Down repeat.

### ISSUE THREAD

**Issue by a-triant** [tekezo/Karabiner-Elements#66]
With F11 or F12 button pressed, to decrease or increase the volume, it does not repeat the action while i'm continuously holding the button. It changes only one step, so i have to press the button multiply times.

**Comment by tekezo** [comment]
Thank you for feedback!
I've fixed this issue at v0.90.36.

Please upgrade to the latest version from "Misc > Check for updates" or 
https://pqrs.org/latest/karabiner-elements-latest.dmg
