### ISSUE TITLE
Version 0.90.91 on Sierra 10.12.3 (16D32) not working

### ISSUE THREAD

**Issue by aphex008** [tekezo/Karabiner-Elements#663]
After latest update to version 0.90.91 on Sierra 10.12.3 (16D32), log keeps showing
[2017-03-15 14:21:48.590] [info] [console_user_server] Check version...
[2017-03-15 14:21:48.590] [warning] [console_user_server] grabber socket is not found
[2017-03-15 14:21:49.592] [info] [console_user_server] Check version...
[2017-03-15 14:21:49.592] [warning] [console_user_server] grabber socket is not found

Key mappings stopped working.

**Comment by aphex008** [comment]
Computer restart/ Karabinier restart did not help.

**Comment by leipreachan** [comment]
Same as mine https://github.com/tekezo/Karabiner-Elements/issues/662
You can call Karabiner via spotlight as a temporary workaround.

**Comment by diskopo** [comment]
That workaround did not work for me. Is there a way to grab the previous build (not have to build it myself)?

**Comment by leipreachan** [comment]
sure:
https://pqrs.org/osx/karabiner/files/Karabiner-Elements-0.90.90.dmg

**Comment by diskopo** [comment]
Thank you!

**Comment by aphex008** [comment]
Thanks for the previous version. It works fine :) 
BTW, thanks for the great product guys!

**Comment by studgeek** [comment]
I had same problem on same OSX version. Reverting to 0.90.90 resolved it (happily).

**Comment by axsuul** [comment]
Had this issue as well and could be related to this: https://github.com/tekezo/Karabiner-Elements/issues/605

**Comment by RianGray** [comment]
Came here to report downgrading 0.90.90 fixed the problem.

**Comment by SConaway** [comment]
Same here. Seems to be fixed with the latest commits. Compile yourselves, it may work.

**Comment by tekezo** [comment]
Sorry for inconvenience.
I've fixed this issue at v0.90.92.
Please upgrade Karabiner-Elements.

**Comment by axsuul** [comment]
Can confirm it works now. We can probably close this issue

**Comment by tekezo** [comment]
Thank you for confirmation!
