### ISSUE TITLE
Can‘t wait for the full featured Karabiner for Sierra.

### ISSUE THREAD

**Issue by zddewe** [tekezo/Karabiner-Elements#667]
Please speed the progress of developing karabiner.please

**Comment by nguyenhimself** [comment]
This is neither a bug report nor a feature request. This page is not a forum, and this post doesn't belong here. Can't we close this already?

**Comment by carlsmith** [comment]
It's nice to see you're keen @zddewe, but this is the *issue* tracker mate.
