### ISSUE TITLE
I don't seem to be able to swap @ with " on a Standard (UK) Apple keyboard, which is all I wanted Karibiner for!

### ISSUE THREAD

**Issue by BlackHatPhil** [tekezo/Karabiner-Elements#669]
Is this to be developed?

**Comment by Linden-Ryuujin** [comment]
I'm afraid I would think this is unlikely to be supported in Karabiner-Elements. Elements is just for swapping whole keys (so in your case you'd have to swap comma with 2 which does more than you'd like I expect). The old Elements used to be able to do that sort of thing, so hopefully one day it will be possible when the new Karabiner is worked on. But It's going to be a white I would think given how long Elements has taken.

> Karabiner does not work on macOS Sierra at the moment.
>
> We are developing Karabiner-Elements which provides simple key modification for macOS Sierra at first.
> (Karabiner-Elements works well on macOS Sierra. We are working on fixing several remaining issues.)
>
> We'll start updating for the full featured Karabiner for Sierra after Karabiner-Elements is completed.

As an alternative it might be worth changing the keyboard setup via OSX - for example I've set mine up to use "British PC" (system settings>Keyboard>Input Sources)- this will swap all punctuation and symbol type keys to match their placement on a standard UK keyboard. If you're not comfortable typing without looking at the keyboard/don't know where all the punctuation keys are then it might cause more problems than it solves. On the plus side... it makes the keyboard almost incomprehensible for anyone else using my mac book!

**Comment by carlsmith** [comment]
It's a proprietary solution, and costs money, but Keyboard Maestro should be able to do this kind of thing. If you're happy scripting in Lua, HammerSpoon is an open source option that can do roughly the same things KM does.
