### ISSUE TITLE
Ctrl keys to behave like Esc when tapped

### ISSUE THREAD

**Issue by lujianmei** [tekezo/Karabiner-Elements#670]
I just wait for this functionality for available asap. This is a bit more important for vim users and spacemacs users.
Is it possible for now? How can i config it on Karabiner-Elements?
Thanks.

**Comment by walt-r** [comment]
This functionality has been implemented, or work arounds found.  See these issues for more info.

https://github.com/tekezo/Karabiner-Elements/pull/247

https://github.com/tekezo/Karabiner-Elements/pull/170#issuecomment-257091685

https://github.com/tekezo/Karabiner-Elements/issues/165#issuecomment-258762846

https://github.com/tekezo/Karabiner-Elements/issues/103#issuecomment-258765038

**Comment by IanEdington** [comment]
@walt-r It looks like all these solutions require building Karabiner-Elements from source. Is this true?

**Comment by bnordbo** [comment]
@IanEdington Yes. Karabiner-Elements is under active development, so all releases are unstable anyway. FWIW I've beeng using #247 for a couple of weeks now without any problems.

**Comment by IanEdington** [comment]
gtk, ty.

**Comment by limeblack** [comment]
I believe these are related in terms of implementation https://github.com/tekezo/Karabiner-Elements/issues/697
