### ISSUE TITLE
Logitech K810 F1-F12 and multimedia keys

### ISSUE THREAD

**Issue by andig89** [tekezo/Karabiner-Elements#671]
Simple problem - if i turn on Krabiniery, i won't able to use F1-F12 keys and multimedia keys works only with fn keys :/. If I don't use Karabiniery, I won't able to change ctrl key to alt but multimedia keys work without fn and F1-F12 works with fn key. Karabiniery doesn't recognize F1-F12 keys and in macOS i can't change only one ctrl key (right). Any suggestion?

**Comment by igs-awilliams** [comment]
+1

**Comment by jpopadak** [comment]
This is the same as #656.
