### ISSUE TITLE
Suggestion: Left and Right Mouse Click

### ISSUE THREAD

**Issue by morganwatch** [tekezo/Karabiner-Elements#672]
I miss having the ability to remap those keys.

**Comment by RustyPine** [comment]
+1 Would be a real life saver!

**Comment by LunaticoCR** [comment]
+1

**Comment by incandescentman** [comment]
This worked for me. Edit `/Users/username/.config/karabiner/karabiner.json` and add a new behavior:

                            "from": {
                                "key_code": "insert"
                            },
                            "to": {
                                "pointing_button": "button1"
                            }
