### ISSUE TITLE
Feature request: Ctrl+LeftArrow and Ctrl+RightArrow key mapping

### ISSUE THREAD

**Issue by CaspianCanuck** [tekezo/Karabiner-Elements#682]
This is not an issue but a feature request for the developer to consider adding the mapping of Ctrl+LeftArrow and Ctrl+RightArrow sequences (jump word left/right in Windows) to Mac's native Option+LeftArrow and Option+RightArrow.

**Comment by laktak** [comment]
You could try this with #696
