### ISSUE TITLE
Shortcut to switch between profiles?

### ISSUE THREAD

**Issue by jazzlw** [tekezo/Karabiner-Elements#687]
Is there any way to make a keyboard shortcut to switch between profiles in Karabiner Elements?

I use it to remap to dvorak in a java friendly way (there's a bug in java that doesn't play well with the osx keyboard remapping), and it would be really nice to be able to switch back to a normal qwerty keyboard (which is a different profile) with a keyboard shortcut.

**Comment by nguyenhimself** [comment]
Not currently, but there are a number of workarounds:
- Using [Hammerspoon](https://github.com/knu/hs-knu#example-usb-watcher-and-shell-escaping).
- Using [Alfred](https://www.alfredforum.com/topic/9927-karabiner-elements-profile-switcher/)
- Using the built-in Karabiner command line tool.
- Automate with Keyboard Maestro using either the command line tool or the Python script from that Alfred workflow.

**Comment by ldiunyh** [comment]
Hi Some experts here please tell me how to do it from scratch, i know nothing about coding. Or can you just please tell me what to learn in order to understand how to do it? Thanks!
