### ISSUE TITLE
"Duplicate profile" button

### ISSUE THREAD

**Issue by singalen** [tekezo/Karabiner-Elements#688]
I have two external keyboards (one is Apple, other is PC). The modifications I want are ALMOST the same, but differ a bit (switching Cmd and Opt; somehow it doesn't work in System Settings).
It will take long to click through all the settings in a new profile.

Can we have a "Duplicate profile" button near the "Add profile"?

**Comment by NinoScript** [comment]
I just found myself in the same situation.
Are there any guidelines for contribution? I think this is within my current abilities!

**Comment by singalen** [comment]
I ended up duplicating a configuration on a file level.
