### ISSUE TITLE
Macbook pro touchpad: Mute key disabled and inactive

### ISSUE THREAD

**Issue by jrm2194** [tekezo/Karabiner-Elements#689]
If/When Karabiner-Elements is running, the **mute key** on the **TouchBar** seems to be deactivated no matter what configuration is used (even vanilla/blank).

**Comment by jrus** [comment]
This seems to happen for me with all touchbar 'control strip' functions that are single buttons. That is, the app-specific touchbar features work as expected, and the slider functions on the control strip (like brightness and volume) work fine, but buttons like mute, Siri, mission control, play, keyboard backlight adjusters, etc. all do nothing when pressed.

**Comment by jrus** [comment]
I think this is a duplicate of #595

Just deactivate the touchbar in Karabiner prefs to make it work (note, you then won't be able to remap the `esc` button, etc.) .
<img width="899" alt="screen shot 2017-06-21 at 10 39 10 am" src="https://user-images.githubusercontent.com/83411/27398519-d4ff28b4-566e-11e7-9560-64654dce1466.png">
