### ISSUE TITLE
Budy,are you working for 10.12 now?

### ISSUE THREAD

**Issue by Fengur** [tekezo/Karabiner-Elements#694]
kara is a very nice tool for me, i have been waiting for a long time for your 10.12 version,but your site shows that it has been working for months, is there some trouble? maybe we can make some help.

**Comment by OmarDarwish** [comment]
I don't think this is what github issues are meant to be used for.

**Comment by ssteinerx** [comment]
@Fengur If you would like to contribute financially to the development of Karabiner Elements, donations can be made via https://pqrs.org/osx/karabiner/donation.html.en.
