### ISSUE TITLE
0.90.92 cannot install Sierra

### ISSUE THREAD

**Issue by pauljamescleary** [tekezo/Karabiner-Elements#695]
I tried installing 0.90.92 and the package gets stuck in Verifying

I tried to let it run for a while.  Even tried connecting to it directly with the Installer.app

Also, tried the same with brew install and it experienced the same hangup.

I am on the very latest sierra 10.12.4

**Comment by heliohead** [comment]
I just install with no problem
![screenshot 2017-04-08 17 07 20](https://cloud.githubusercontent.com/assets/675604/24832065/08763532-1c7e-11e7-9566-831f360a69b5.png)

**Comment by pauljamescleary** [comment]
Hmm, maybe it is some other dependency?  It gets completely stuck in "Verifying package" and doesn't go anywhere.
