### ISSUE TITLE
Create cmd shortcut

### ISSUE THREAD

**Issue by limeblack** [tekezo/Karabiner-Elements#697]
Could this be used to essentially activate spotlight by pressing the cmd key?

Question here http://apple.stackexchange.com/questions/280083/define-command-as-keyboard-shortcut?noredirect=1#comment352287_280083

**Comment by nguyenhimself** [comment]
FYI, as a workaround, you can achieve this (Command key → Spotlight) with BetterTouchTool, using the Key Sequence feature to capture the Command key.

![screen shot 2017-04-18 at 11 04 59 am](https://cloud.githubusercontent.com/assets/482270/25114202/1077448c-2427-11e7-8d19-618dfcc2f8a5.png)

**Comment by limeblack** [comment]
@nguyenhimself  thank you sir!!  Any idea to fix this other issue https://apple.stackexchange.com/questions/280855/changing-right-hand-command-alt-key-order-to-be-like-a-windows-keyboard
