### ISSUE TITLE
DANISH_DOLLAR missing in the keys definition

### ISSUE THREAD

**Issue by niieani** [tekezo/Karabiner-Elements#7]
In the old Karabiner I had the option to remap `§` to ` with, to make the UK keyboard behave like the US one:

```
    <item>
        <name>Put Tilda where it belongs on Apple Keyboards</name>
        <identifier>private.tilda</identifier>
        <autogen>__KeyToKey__ KeyCode::DANISH_DOLLAR, KeyCode::BACKQUOTE</autogen>
        <device_only>DeviceVendor::APPLE_COMPUTER, DeviceProduct::ANY</device_only>
    </item>
```

Unfortunately I don't see the DANISH_DOLLAR key defined in the [types](https://github.com/tekezo/Karabiner-Elements/blob/master/src/share/types.hpp#L156-L348) list. Would be really glad if this were added! Thanks.

**Comment by niieani** [comment]
OK, I found that the `0xa` key is listed now as: "non_us_backslash".

**Comment by AllanLRH** [comment]
I'm also experiencing this... how do I fix it?
@niieani, pinging you because I hope you know the answer.
I'm on a 2016 Macbook pro with a danish keyboard.

**Comment by niieani** [comment]
@AllanLRH try remapping `non_us_backslash`, at least for me it worked. Anyway I since have stopped using Karabiner and just got used to the keyboard... 🤷‍♂️ Too many issues.

**Comment by AllanLRH** [comment]
Thanks, remapping `non_us_backslash` to `grave_accent_and_tilde` worked.
