### ISSUE TITLE
Is there any reason why I can't map the (useless!) "§/±" onto the (useful!) "`/~" key?

### ISSUE THREAD

**Issue by matthewsinclair** [tekezo/Karabiner-Elements#702]
Everything else seems to work fine _except_ mapping the most useless key on a UK keyboard "§/±" onto something much more useful "`/~". 

Elements seem to think that the "§" maps onto the first item underneath the "Japanese" section in the "From key" list (sorry, my Japanese is non-existent, so I have no idea what the characters are saying). 

<img width="912" alt="screen shot 2017-04-10 at 11 21 52" src="https://cloud.githubusercontent.com/assets/311495/24857369/eb25cf5c-1ddf-11e7-9d41-7686dd6b7d27.png">

Any idea if this is something I am doing wrong, of it's a known problem? Thanks in advance.

**Comment by zuzusik** [comment]
Same question here. Tried to remap today, ended up exactly where the author of this topic.

**Comment by kenlim** [comment]
This worked for me:

![image](https://cloud.githubusercontent.com/assets/111891/25122207/fd760266-241b-11e7-8ae4-541fa2ae7bd5.png)

However, you must keep the "Virtual Keyboard" setting to Ansi. Swapping it to ISO breaks the mapping for me (Must be a bug)

**Comment by zuzusik** [comment]
@kenlim this worked for me! thank you very much!

**Comment by matthewsinclair** [comment]
Awesome! This worked for me as well. Thanks!
