### ISSUE TITLE
Simple foot pedal modifier key question

### ISSUE THREAD

**Issue by rose4018** [tekezo/Karabiner-Elements#703]
I have a pair of foot pedals which I use for command and shift (RSI issues, ugh). 

The pedals work by sending single keystrokes ("b") which I guess are intended to be remapped in software. I've always used Karabiner for this, but of course it broke in Sierra.

I've set up the same thing in Karabiner Elements, but the only way I've been able to make modifier keys work with the regular keyboard is by making the mapping apply to all devices. But then I lose my "b" key! 

Is there a solution? Or should I look elsewhere, or am I stuck trying to downgrade to get my foot pedals back?

Secondary question: The two pedals have different device IDs, but show up as a single device in the preferences menu. If we solve the original problem, I'm guessing it will still treat the two pedals as a single device. Is there a way to distinguish by USB ID in the JSON like I could in Karabiner? (I'm new to GitHub. Should I create a separate question for this?)

**Comment by nguyenhimself** [comment]
Must it be the "b" key? Can't you reprogram it to send something like "F20" instead? Is the "b" key the only thing that shows up in Karabiner-EventViewer?

Considering the target user base, I'd have thought it'd be easy to customize those pedals.

And yes, you should separate this into 2 threads. Make it easier to focus on solving each.

**Comment by rose4018** [comment]
The "b" keystroke seems to be hardcoded into the pedal. It's sold with some random Windows-only software which I'm guessing lets you configure how that keypress is interpreted, like what I did with Karabiner. I assume the users (mostly musicians, stenographers, or people who need assistive tech) aren't even meant to know it uses a "b" keystroke as the signal.

**Comment by jonathanlilly** [comment]
Hi.  I made this work.  In Karabiner, you first need to go to "Devices" and click the checkbox to the left of "No Product Name", which is the foot pedal.  Then click on "Simple Modifications", choose "No Product Name" from Target Device, and the click "Add Item".  Finally choose "From key" to be "b" and "To key" to be anything you want.  Voila!

**Comment by chrisgrieser** [comment]
for anyone else coming here from Google:
I had the same issue, until I noticed that the foot pedal has to be enabled under the "Devices" settings tab.
