### ISSUE TITLE
xpcprocess high cpu load after unplugging keyboard

### ISSUE THREAD

**Issue by bapollonio** [tekezo/Karabiner-Elements#704]
I used Karabiner - and now Karabiner-Elements - to fix the modifier keys (cmd/alt/menu) on my external Logitech usb/wireless keyboard to be more Mac-like.  After I unplugged my keyboard this afternoon to go on battery I noticed xpcprocess was using significant CPU (15-40% on 2015 rMPB).  Eventually, I thought to quit Karabiner and it immediately stopped.

**Comment by pietdevries94** [comment]
You are aware that those keys can be remapped by the system itself? Settings > Keyboard > Special Keys (bottom right)

**Comment by bapollonio** [comment]
Thank you, but I can't remap the menu key using the system settings
