### ISSUE TITLE
I don't have a /opt/local/include/boost/ directory for boost (or even /opt/)

### ISSUE THREAD

**Issue by sydneycbd** [tekezo/Karabiner-Elements#705]
Forgive me, I'm a newbie.

I have my MAC mini  able to dual boot from two internal drives Mac OS 10.11 and 10.12. 
Karabiner works perfectly on 10.11.

On 10.12 I don't have an /opt/ directory to install boost, what should I do?

<img width="533" alt="preview_11apr2017_1028pm" src="https://cloud.githubusercontent.com/assets/12984620/24909231/69418e7c-1f06-11e7-83cd-503d90b1439e.png">

**Comment by haifengkao** [comment]
`mkdir -p /opt/local/`

**Comment by sydneycbd** [comment]
Thank you kindly, although I had to ultimately use:
sudo mkdir -p /opt/local/include/boost/
