### ISSUE TITLE
Can I export/import configs between machines?

### ISSUE THREAD

**Issue by dss886** [tekezo/Karabiner-Elements#708]
Or allow syncing config file through dropbox, like the Alfred do?

**Comment by knu** [comment]
I guess you can by placing ~/Dropbox/karabiner/karabiner.json and symlinking ~/Dropbox/karabiner to ~/.config/karabiner, but if you deal with multiple profiles switching your current profile on one machine will affect others.

**Comment by dss886** [comment]
It is in ~/.config...you save my day, thx

**Comment by yuanzhaoYZ** [comment]
@knu It worked. Thank you!

**Comment by karthikbeam** [comment]
This works but not ideal. I link the json file from my backup (think dropbox) into ~/.config/karabiner/karabiner.json, but it turns out that karabiner overwrites that file (not update) every time it makes a change. so if I make a change, the link is now broken.

**Comment by karthikbeam** [comment]
This works but not ideal. I link the json file from my  backup (think dropbox) into ~/.config/karabiner/karabiner.json, but it  turns out that karabiner overwrites that file (not update) every time it  makes a change. so if I make a change, the link is now broken.

**Comment by tekezo** [comment]
Create a symlink `~/.config/karabiner` instead of `~/.config/karabiner/karabiner.json`

Example:
https://pqrs.org/osx/karabiner/document.html#configuration-file-path

**Comment by karthikbeam** [comment]
@tekezo that folder has a lot of files that I am not interested in adding to git(I store the conf in my dotfiles repo in github)

**Comment by karthikbeam** [comment]
https://github.com/tekezo/Karabiner-Elements/issues/1764

**Comment by tekezo** [comment]
@karthikbeam Create `karabiner` directory into your dotfiles repo and move karabiner.json into `karabiner/karabiner.json`, then symlink to `karabiner` directory.

**Comment by karthikbeam** [comment]
Added that and the below in my gitignore to get this working without having the other files (backups, assets) messing up my git status / history

```
karabiner/*
!karabiner/karabiner.json
```

**Comment by tekezo** [comment]
I misunderstood your desire.
I just understand that you didn't want to include `automatic_backups`.
Your gitignore is right way to do it.

**Comment by douxinchun** [comment]
I shared the whole configuration folder via git reponstory. https://github.com/douxinchun/MyMacOS/tree/master/Karabiner
