### ISSUE TITLE
fn key doesnt work on tbMBP(cant watch functional keys)

### ISSUE THREAD

**Issue by Anatoliuz** [tekezo/Karabiner-Elements#711]

**Comment by seagle0128** [comment]
Same issue with my Macbook Pro 2015 and Filco 104 red. 
fn key doesn't work well, no matter whether I check "Use F1, F2, etc. keys as standard function keys" or not.
Please check and help. Thanks!

**Comment by mikkitiger** [comment]
I confirm. When Karabiner Elements is active pressing the Fn key is not bringing the functional keys (F1-F12) on touch bar.

**Comment by jrus** [comment]
This seems to be a duplicate of #564

**Comment by ELLIOTTCABLE** [comment]
(And originally, #460.)
