### ISSUE TITLE
Apply multiple profiles for multiple keyboards at the same time

### ISSUE THREAD

**Issue by Hongbo-Miao** [tekezo/Karabiner-Elements#713]
It will be great to allow use multiple profiles for multiple keyboards at the same time. Thanks

**Comment by carlsmith** [comment]
Support for having more than one keypad would be nice. They're useful for macros and app shortcuts, but you currently have to use ones that can be programmed directly. If Karabiner let users have more than one keypad with their own profiles, we could use regular keypads and program them in software.

**Comment by Wielding** [comment]
I have a Razer Orbweaver that I can't use on my Mac because the Razer software is horrible. It does show up in the Karabiner device list.   If you could allow for programming that separately from my main keyboard you would be making many Razer Mac users very happy.

**Comment by starsy** [comment]
I have made some enhancements to KBE to support per device configuration within the same profile. Please check if this helps: https://github.com/tekezo/Karabiner-Elements/issues/770 Please let me know if any questions.

**Comment by Hongbo-Miao** [comment]
Activate

**Comment by Hongbo-Miao** [comment]
Close since duplicate with https://github.com/tekezo/Karabiner-Elements/issues/770
