### ISSUE TITLE
Any plans to support the caps+ jkli keys to arrows?

### ISSUE THREAD

**Issue by palme1337** [tekezo/Karabiner-Elements#714]
I found a workaround thankfully! http://slongwell.github.io/articles/2016-09/karabiner-workaround

But he states this is not a wholistic solution. I really miss the implementation that Karabiner provided. I would GLADly donate if this were to be implemented any time soon. 

Thanks, 
Chris

**Comment by Obversity** [comment]
I honestly won't be upgrading to Sierra until this feature is available. My productivity relies on muscle memory, and I've been using caps+ijjkl for too long now!

**Comment by ceetee** [comment]
You can also use this app https://ei-kana.appspot.com/

**Comment by Obversity** [comment]
Might look into that, thanks @ceetee!

**Comment by jottr** [comment]
@tekezo would you mind giving a status update on this issue? Would it be very involved to implement this?

**Comment by jottr** [comment]
Please reopen.

**Comment by tekezo** [comment]
Similar configuration exists: 
https://pqrs.org/osx/karabiner/complex_modifications/#vi_mode_with_caps_lock
