### ISSUE TITLE
Feature request: "Unable" modification instead of just "Removing" it

### ISSUE THREAD

**Issue by santiagobasulto** [tekezo/Karabiner-Elements#717]
Hey guys! I'm a regular user of Karabiner to map my traditional fn key to the control_l key. But for other keyboards (at work) I don't have a fn key. That means that I end up removing the rules when I get to work and then I create them again when i'm working directly on my laptop.

Is there any way to add another option instead of just "removing" the combination for "Simple Modifications". Maybe a checkbox to "enable" or "disable" them.

This is how my modifications look like: 
![image](https://cloud.githubusercontent.com/assets/872296/25336112/66d08682-28cc-11e7-897c-94ba48fce2fa.png)

**Comment by rscafi** [comment]
Can't you simply use Profiles for this?

**Comment by santiagobasulto** [comment]
Good question. I am using profiles. But that means that every time I want to make a more general change, I have to replicate it in all my profiles. Again, I am currently using profiles and it's not that bad.

**Comment by rodalpho** [comment]
Simple checkbox to enable/disable would be a nice UI improvement. 

Hardly critical as K-E is still desperately short on core features, but would be nice to have,

**Comment by carrigmore** [comment]
Hi, How could I add a map with numLock key to **VK_IOHIKEYBOARD_TOGGLE_NUMLOCK**? that option is not in the latest version.
