### ISSUE TITLE
Fn to Hyper

### ISSUE THREAD

**Issue by rafegoldberg** [tekezo/Karabiner-Elements#718]
love the original Karabiner; glad to see Sierra support coming along! still, I'm desperately missing the ability to map my `Fn` key to the "hyper" key combo (`cmd`+`ctrl`+`shift`+`alt`). I was wondering how I might accomplish something similar with Karabiner Elements, or if this feature is planned?

**Comment by okuramasafumi** [comment]
I also miss the feature to map `fn` key to `hyper` with some conditions.
@rafegoldberg You can now map `fn` to `hyper` without any special condition. A downside is that you cannot use `fn` key combined with function keys.
