### ISSUE TITLE
Numlock key cannot be mapped in the Karabiner-Elements

### ISSUE THREAD

**Issue by carrigmore** [tekezo/Karabiner-Elements#719]
I am using a compact keyboard, the numpad won't work correctly until set Numlock on.
In previous Karabiner version, I can use following settings to achieve this:
<autogen>__KeyToKey__ KeyCode::KEYPAD_CLEAR, KeyCode::**VK_IOHIKEYBOARD_TOGGLE_NUMLOCK**</autogen>

This selection **VK_IOHIKEYBOARD_TOGGLE_NUMLOCK** doesn't seem to exist in the Karabiner-Elements.

Could you implement this to achieve the same as the existing version? this feature is really useful for users using compact keyboard, as the num pad is disabled by default, without Karabiner, the number pad cannot be used properly.

Thanks a lot.

**Comment by carrigmore** [comment]
![screen shot 2017-04-27 at 22 46 52](https://cloud.githubusercontent.com/assets/8460701/25505954/18de4414-2b9c-11e7-91fe-57274e5cc676.png)
I didn't find the VK_IOHIKEYBOARD_TOGGLE_NUMLOCK in the menu. Anyone could help me? Thanks a lot

**Comment by carrigmore** [comment]
@tekezo Dear 扶美彦 様、would you have time to implement this? thanks a mill. That feature is so useful for a compact keyboard. Without mapping, the num pad cannot be used to input number. Thanks.

**Comment by carrigmore** [comment]
I find user can edit the JSON file, but for some reason cannot map a key to windows locking_num_lock. As it has "not_to" : true

   {
        "name": "locking_num_lock",
        "not_to": true
    },

**Comment by carrigmore** [comment]
The num_lock map to PC keyboard num_lock can be very important for certain users. Could any other having same issue please comment here.

**Comment by simonyangme** [comment]
I would also appreciate this feature, and would be willing to test or build this if provided some guidance

**Comment by luismeruje** [comment]
Hi guys, i had the same problem and just wanted to share my alternative solution so I could hopefully help some of you out.

Here you can find a program called setledsmac:
https://github.com/damieng/setledsmac

I have made a modified version with some minor changes. On my version, instead of having to specify if you want numlock on or off, you only have to do: "setleds num" and it will automatically change the state of numlock. I'm going to attach the altered version of setledsmac to this comment. I do not take any credit for this program as I did not make it (only altered it ever so slightl) and as such will not post it on my github page. All credit should go to @damieng.

# **Instructions:**
_Note: You will need xcode to be able to build the project_.
Download attached zip file.
Open terminal and navigate to the Source folder of setledmacs.
Run on terminal window: 

`xcodebuild -project SetLEDs.xcodeproj`
`cd build/Release`
`sudo cp setleds /usr/local/bin`

You can now run `setleds num` to change the state of your numlock, as long as you have /usr/local/bin on your PATH environment variable.

# **Making `setleds num` run when pressing numlock:**
Download Spark:
https://www.shadowlab.org/softwares/spark.php

Open spark and double-click AppleScript on the left-side.
Paste this script:
`do shell script "PATH=$PATH:/usr/local/bin
	export PATH
	setleds num"`
Click create and then click "Start Spark Daemon" at the bottom.
NumLock should now be functioning correctly.

**Comment by whitebird** [comment]
@luismeruje Thanks for the tool, however, it gives the following error output when executed:

```
SetLEDs version 0.1 - http://github.com/damieng/setledsmac
Modified by: Luís Ferreira - luismeruje@gmail.com

Segmentation fault: 11
```

**Comment by luismeruje** [comment]
Does the original setledsmac version work for you?

**Comment by damieng** [comment]
I'm also getting that error when compiling with latest tools in modified
version. Strangely works fine in the debugger.

**Comment by damieng** [comment]
Sorry, meant unmodified version.

**Comment by whitebird** [comment]
@luismeruje It does for me yes. Output after compiling and running command setleds. When I tried your program again this morning after rebooting, it worked. I unplugged and replugged my keyboard in the meantime.

**Comment by luismeruje** [comment]
I remember it happening to me once too. It was giving out a segmentation fault, and then I did the same as you, I rebooted, and I haven't had any problems since then.
As long as it doesn't happen very often I'm okay with rebooting once in a while. Sorry I can't be of more help.

**Comment by freespace** [comment]
@luismeruje thanks for the tip! Worked for me out of the gate without needing to reboot or replug my kb.

**Comment by damieng** [comment]
Rather than have a different version of setleds floating round with the same name but with different functionality I've added a new toggle mode so it can suit all.

e.g.

```bash
setleds +caps ^num
```

Will turn on the caps lock and toggle the num lock.  (You can still use `-` to turn a setting off)

**Comment by jkmaxwell** [comment]
@damieng any chance you could just attach the release version / binary on your github page for those of us w/o xcode?

**Comment by citbr** [comment]
I'd also like a precompiled binary if that is at all possible.  I don't want to have to install Xcode (at over 4 GB last time I looked) on my SSD, nor do I want to have to get an Apple Developer Account that I will never use again just for this one program.  Please?

**Comment by damieng** [comment]
Release binary up at https://github.com/damieng/setledsmac/releases/tag/0.2

**Comment by citbr** [comment]
Thank you for making the effort, but it doesn't seem to work.  Here is the output of a few runs:

```
$ ./setleds +num
SetLEDs version 0.2 - https://github.com/damieng/setledsmac

 "Karabiner VirtualHIDKeyboard"

 "Logitech Illuminated Keyboard" ?num ?caps ?scroll

Some state could not be determined. Please try running as root/sudo.
```

```
$ sudo ./setleds ^num
SetLEDs version 0.2 - https://github.com/damieng/setledsmac

 "Karabiner VirtualHIDKeyboard"

 "Logitech Illuminated Keyboard" ?num ?caps ?scroll

Some state could not be determined. Please try running as root/sudo.
```

```
$ sudo ./setleds ^num -name "Logitech*"
SetLEDs version 0.2 - https://github.com/damieng/setledsmac

 "Logitech Illuminated Keyboard" ?num ?caps ?scroll

Some state could not be determined. Please try running as root/sudo.
```

```
$ sudo ./setleds -v +num -name "Logitech*"
SetLEDs version 0.2 - https://github.com/damieng/setledsmac

 "Logitech Illuminated Keyboard" ?num ?caps ?scroll

Some state could not be determined. Please try running as root/sudo.
```

Obviously it is finding the keyboard but for some reason it cannot seem to detect the current state.  I am running MacOS High Sierra version 10.3.3.

**Comment by citbr** [comment]
Thank you for making the effort, but it doesn't seem to work.  Here is the output of a few runs:

```
$ ./setleds +num
SetLEDs version 0.2 - https://github.com/damieng/setledsmac

 "Karabiner VirtualHIDKeyboard"

 "Logitech Illuminated Keyboard" ?num ?caps ?scroll

Some state could not be determined. Please try running as root/sudo.
```

```
$ sudo ./setleds ^num
SetLEDs version 0.2 - https://github.com/damieng/setledsmac

 "Karabiner VirtualHIDKeyboard"

 "Logitech Illuminated Keyboard" ?num ?caps ?scroll

Some state could not be determined. Please try running as root/sudo.
```

```
$ sudo ./setleds ^num -name "Logitech*"
SetLEDs version 0.2 - https://github.com/damieng/setledsmac

 "Logitech Illuminated Keyboard" ?num ?caps ?scroll

Some state could not be determined. Please try running as root/sudo.
```

```
$ sudo ./setleds -v +num -name "Logitech*"
SetLEDs version 0.2 - https://github.com/damieng/setledsmac

 "Logitech Illuminated Keyboard" ?num ?caps ?scroll

Some state could not be determined. Please try running as root/sudo.
```

Obviously it is finding the keyboard but for some reason it cannot seem to detect the current state.  I am running MacOS High Sierra version 10.3.3.

**Comment by citbr** [comment]
In case it's at all helpful, this was the private xml code that would work in the former version of Karabiner - this used the alt-command-control-escape keys (hold down alt-command-control and press ESC) to toggle:

```
<?xml version="1.0"?>
<root>

 <item>
   <name>Toggle NumLock LED by holding Alt+Command+Control+Escape keys</name>
   <identifier>private.toggle_numlock_by_alt-command-control-escape</identifier>
   <autogen>
     __KeyToKey__
     KeyCode::ESCAPE, VK_COMMAND | VK_CONTROL | VK_OPTION
     __{ KeyCode::VK_IOHIKEYBOARD_TOGGLE_NUMLOCK }__
   </autogen>
 </item>

</root>
```
Unfortunately it appears there is no way to use private XML in Karabiner Elements.

**Comment by damieng** [comment]
Yes, it seems Karibiner's virtual thing is still interfering with LED state calls as documented here https://github.com/damieng/setledsmac/issues/7

**Comment by citbr** [comment]
Well that stinks.  It means I have to quit Karabiner-Elements, run setleds (which does work if K-E is not running) and then start Karabiner-Elements again.  That said, I very much appreciate that you made your program available even with this limitation.

I attempted to figure out if there was some way to run your program at bootup before K-E runs.  But however K-E is starting itself up, it's happening early enough in the bootup process that I have no idea how to get setleds to run first.  I only need it to run once, right after startup - well, maybe more than once; for some reason with my keyboard I have to use the -v option and even then it seems like sometimes I have to run it two or three times (starting with the ^num option) to get it to work.  I'm not sure why my keyboard is so stubborn, but it is.

Thank you again for your work on this, I will still use it despite the limitations, which are not your fault anyway.

**Comment by liv3010m** [comment]
Is this going to be featured natively on Karabiner-Elements?

**Comment by carrigmore** [comment]
@citbr does this work for toggle num_lock on and off on a compact keyboard like cooler master stealth? As I will need to toggle the LED lights on and off in order to use number pad or the page up/ page down insert delete etc..

**Comment by damieng** [comment]
@carrigmore setleds literally just sets the led itself. Turning on the led does not turn on the functionality.  i.e. with this you can turn on the caps lock light without actually turning on caps lock.  It's just useful if you have backlit LED keyboards that look better with all the lights on.

**Comment by carrigmore** [comment]
@damieng thanks for your kind answer, I don't know how to toggle on the functionality between the number pad and normal insert delete button.

**Comment by luismeruje** [comment]
@damieng Actually I have a Cooler Master Quick Fire TK and by simply turning the light on the functionality is also activated. I guess there's an hardware connection that toggles the alternative keyboard matrix when the light is on. However, I'm note sure that's the case with every keyboard.

**Comment by vitorio** [comment]
Hello, I also could not figure out how to enable NumLock for an external USB numeric keypad, to support the use of the arrow/pgup/pgdn keys.  I ended up having to find and install the last version of Karabiner to use the `private.xml` described here: https://apple.stackexchange.com/a/267439

**Comment by krc** [comment]
@vitorio you mean the old non-"elements" version? Does that actually work on the current Mac OS? I thought from the notes that it did not.

Also a bit sad that there seems to be no movement on this issue from the developer, and half the conversation here has turned to controlling the LED. 

Having the LED work properly is great and all, but the main issue is the num lock functionality. I'd happily take that without proper LED syncing…

**Comment by vitorio** [comment]
@krc Karabiner 10.22.0 is working fine for me, but I'm still on 10.11 El Capitan

**Comment by scriptfans** [comment]
Any update for this?

**Comment by kfkonrad** [comment]
@tekezo can you implement this or point me to where/how I might be able to implement that for you?

**Comment by scriptfans** [comment]
Any update for this?

**Comment by liv3010m** [comment]
Hi! Is there any chance for this going to be implemented? Please 🙏🏼

**Comment by carrigmore** [comment]
Please could this get re-opened

**Comment by ssh352** [comment]
I have a realforce 87u and want to use the embedded numpad via the NumLock key.

**Comment by eancuta** [comment]
I have a QuickFire TKL 6 keys and I also need Karabiner-Elements to feature the option to remap my numlock key.

**Comment by eancuta** [comment]
Side note: I downloaded KeyCastr to check what the key counts as on the keyboard. If I press NUMLK on my QuickFire TKS keyboard, KeyCastr interprets it as ESC (circle with arrow facing northwest). Likewise PRTSC, SCRLK, PAUSE are F13, F14, F15 on KeyCastr.

**Comment by rnschmidt** [comment]
I have the same problem on a realforce 23u. Any way to get this to work?
