### ISSUE TITLE
How to introduce two remappings simultaneously?

### ISSUE THREAD

**Issue by EditorKubala** [tekezo/Karabiner-Elements#72]
HI, I have already changed right command to left option, but I need to change right option to delete forward at same time. It seems that I can modify only one pair of keys. The second change overwrites the first one. Is there any workaround for that? Thx.

**Comment by seangaffney** [comment]
There's an [example of swapping keys](https://github.com/tekezo/Karabiner-Elements/blob/fd9fb7d2e60fdd13eadb023832f4d3f3cc90a34e/examples/swap_caps_lock_and_escape.json) in the examples directory.

**Comment by talha131** [comment]
Have you tried

```json
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "right_command": "left_option",
                "right_option": "delete_forward"
            }
        }
    ]
}
```

Basically you need to separate rules with a comma. If still confused, please read up on json format.
