### ISSUE TITLE
Can I define and execute my own shell scripts in Karabiner Elements?

### ISSUE THREAD

**Issue by zanglebert** [tekezo/Karabiner-Elements#721]
Hi

I don't know what I should expect to work if I'd go from Karabiner (currently working, didn't upgrade to Sierra) to Karabiner Elements. The readme doesn't seem to mention it, or I didn't know where to look  -- apologies if it's the latter.

I'm using Karabiner for one things mainly: executing shell commands and AppleScript commands, bound to global or app specific shortcuts, i.e. using commands I defined in `private.xml`.

Is the current version of  Elements able to do this, or is this one of the parts not implemented yet?

**Comment by carlsmith** [comment]
Elements is currently not able to do that. It basically just maps keys to *key functions*, as in the things a key can do, including stuff like `illumination_decrement` and `play_or_pause`.

This is pretty much every option Elements currently offers:

- Simple Modifications: Map normal keys to arbitrary key functions
- Function Keys: Map function keys (F1-12) to arbitrary key functions
- Devices: Apply modifications to specific keyboards (not currently working correctly)
- Virtual Keyboard: Set the virtual keyboards type (ANSI, ISO, JIS) and its Caps Lock Delay
- Profiles: Create multiple profiles that you can switch between
- Misc: Set automatic updates, delete Karabiner etc.
- Log: View the log

You can also open the Event Viewer from the old version.

**Comment by zanglebert** [comment]
Thanks a lot for this (high-level) summary.

Any chance this would be a good addition to the readme, in case others are wondering about this as well?

**Comment by carlsmith** [comment]
Thanks. I'm only a user, so have no control over what goes in the README, but I did write this in the hope it would answer your question, and offer a quick status report for anyone else that comes here.

**Comment by sn0wyfall** [comment]
@carlsmith Perhaps you can make a pull request

**Comment by carlsmith** [comment]
Done (#724). Thanks guys.

**Comment by carrigmore** [comment]
@carlsmith 
in old Karabiner I can map to a windows num lock key, in private.xml
<autogen>__KeyToKey__ KeyCode::KEYPAD_CLEAR, KeyCode::VK_IOHIKEYBOARD_TOGGLE_NUMLOCK</autogen>
Do you know if it is possible to achieve same in the elements? Thanks.

**Comment by carlsmith** [comment]
Yep. You can. It's easy to do just using the GUI.

Under the Simple Modifications tab, if you hit the **Add item** button, you get two drop down menus, **From key** and **To key**. In those, there's a section named **Keypad keys**, and **keypad_num_lock** is the first item. Just select that from the **From key** menu, and select whatever you want it mapped to from **To key**.

I tested just mapping it to **x**, and it worked fine. It's pretty straight forwards, but let me know if you have any trouble.

**Comment by carrigmore** [comment]
@carlsmith Thanks for your reply. The problem is the key I want to map to doesn't appear in the 'To key' column. The key is windows num lock key. It doesn't seem to exist in the 'To key' column. In previous version I can do this, and after correct mapping the LED of num_lock on my TK quick fire keyboard will light on and the numbers pad can be used to input numbers.

**Comment by carrigmore** [comment]
@carlsmith I find user can edit the JSON file, but for some reason cannot map a key to windows locking_num_lock. As it has "not_to" : true

{
"name": "locking_num_lock",
"not_to": true
},

**Comment by carlsmith** [comment]
I'm on my phone, but as far as I know, the Clear key on a Mac literally is the Numlock key. Keyboards don't know what their keys do. They just report that the key at the top left of the numpad was pressed, and the OS, based on layout software, determines what that key does, so there's no distinction between Clear and Numlock at the keyboard or driver (Karabiner) level. The legends on the keys are only a visual add that must assume a certain layout has been chosen in software. That's my understanding, but I may have totally misunderstood the issue. I'm new to this stuff.

**Comment by carlsmith** [comment]
Sorry. Just read your message again. Ignore what I just wrote. I didn't even know it was possible to toggle Numlock state on macOS, so will have to just hope someone who knows better can help you out. Presumably, the missing Numlock key in the PC submenu was just an oversight that can be added without much trouble.

**Comment by carlsmith** [comment]
Might be worth opening a new issue.

**Comment by carrigmore** [comment]
@carlsmith thanks a lot, I already created an issue.

**Comment by carrigmore** [comment]
@carlsmith in the Karabiner we can achieve this. The NumLock LED on keyboard will light up and the number pad keys can be used. This is quite useful when using a compact keyboard where number pad is used for multiple purposes (like TK quickfire, the number pad has other functions, if not toggled correctly cannot be used to input numbers)

**Comment by carlsmith** [comment]
The TK Quickfire looks really cool. I'd not seen a keyboard with that layout before. My main driver's an [ANSI MINILA][1], so I get that some of the features most people never use can be important on smaller keyboards.

It's interesting that macOS supports Numlock. There's a popular ruby script on GitHub Gist somewhere that toggles the Caps Lock and Scroll Lock LEDs on the MINILA. It'd be nice if the Scroll Lock LED indicated some other, actually useful state.

[1]: https://deskthority.net/wiki/Filco_Minila

**Comment by HRG1** [comment]
Shell commands are back in version 0.91.7. For example use "shell_command": "open '/Applications/Safari.app'" in the "to" section of the intended key combination (replacing "key_code: "x").

**Comment by smlewis** [comment]
@HRG1 That's the feature I've been waiting for!  This is glorious!

**Comment by jerguslejko** [comment]
@smlewis Could you share your solution? I am trying to map `<esc>` key to a shell command.

**Comment by smlewis** [comment]
@jerguslejko I uploaded my JSON to this repository and the other one (that lets you pull complex configs down from the GUI).  

https://github.com/pqrs-org/KE-complex_modifications/blob/master/docs/json/launch_new_Chrome_or_iTerm2_windows.json

https://github.com/tekezo/Karabiner-Elements/blob/master/examples/launch_Chrome_and_iTerm2_new_windows_keybindings.json

That JSON should get you started on your needs!  You should be able to see how to add in your complex_modification manually.  I guess you can edit it from scratch, or pull the one I put in KE-complex_modifications and copy and edit that.

**Comment by jerguslejko** [comment]
Thank you @smlewis! I managed it to work. 

For anyone wondering, I was trying to remap my `escape` key to play the _"bell"_ sound every time I hit it and at the same time, make `caps_lock` function as `escape` (preparations for the new macbook with touch bar).

<details>
<summary>Here is my `~/.config/karabiner/karabiner.json` config</summary>

```json
{
    "global": {
        "check_for_updates_on_startup": true,
        "show_in_menu_bar": true,
        "show_profile_name_in_menu_bar": false
    },
    "profiles": [
        {
            "complex_modifications": {
                "parameters": {
                    "basic.to_if_alone_timeout_milliseconds": 1000
                },
                "rules": [
                    {
                        "description": "map caps_lock to escape",
                        "manipulators": [
                            {
                                "from": {
                                    "key_code": "caps_lock"
                                },
                                "to": [
                                    {
                                        "key_code": "escape"
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    },
                    {
                        "description": "play bell sound when pressing the escape key",
                        "manipulators": [
                            {
                                "from": {
                                    "key_code": "escape"
                                },
                                "to": [
                                    {
                                        "shell_command": "osascript -e 'beep'"
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    }
                ]
            },
            "devices": [],
            "fn_function_keys": {
                "f1": "display_brightness_decrement",
                "f10": "mute",
                "f11": "volume_decrement",
                "f12": "volume_increment",
                "f2": "display_brightness_increment",
                "f3": "mission_control",
                "f4": "launchpad",
                "f5": "illumination_decrement",
                "f6": "illumination_increment",
                "f7": "rewind",
                "f8": "play_or_pause",
                "f9": "fastforward"
            },
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {},
            "virtual_hid_keyboard": {
                "caps_lock_delay_milliseconds": 0,
                "keyboard_type": "ansi"
            }
        }
    ]
}
```

</details>

**Comment by danfrincu** [comment]
I came here looking for how to execute scripts from Karabiner Elements shortcut in Sierra (like I was able to do with Karabiner in El Capitan) and having looked at the examples given by folks I wanted to add one which was of interest to me but does not work.
So what I do is take the output of a script and put it into the paste buffer, and trigger that with a shortcut. Above I've seen it was called out that you can use "shell_command" instead of "key_code" so I gave it a try with the following.

`"shell_command": "osascript -e 'do shell script \"/usr/local/bin/rt | /usr/bin/pbcopy\"'"`

It does not run when called as a shortcut, but manually running `osascript -e 'do shell script "/usr/local/bin/rt | /usr/bin/pbcopy"'` in the terminal works.

Any ideas?

**Comment by lilolbear** [comment]
@danfrincu Thanks, you gave me the bread crumbs to solve my issue.
