### ISSUE TITLE
[Feature Request] Allow Another Process to Trigger a Profile Change

### ISSUE THREAD

**Issue by carlsmith** [tekezo/Karabiner-Elements#722]
I'm using Keyboard Maestro to simulate the keystrokes that will highlight the Karabiner menu in the menu bar, and select the correct profile. It's very brittle, but works for now.

Being able to more directly tell Karabiner to switch profile, and which profile to use, would be really helpful. I would basically like my profile to change when I plug my external keyboard in.

**Comment by starsy** [comment]
Please check if this helps: https://github.com/tekezo/Karabiner-Elements/issues/770

**Comment by pvandewalle** [comment]
I'd like to swap settings by a shortcut.
