### ISSUE TITLE
"Use all F1, F2, etc. keys as standard function keys" isn't saved with profile

### ISSUE THREAD

**Issue by seansfkelley** [tekezo/Karabiner-Elements#725]
I switch between an external (PC-style) keyboard at work at the internal laptop keyboard at home. The external keyboard has dedicated media keys, so I like to use the fn keys as just fn keys, but on the internal keyboard I prefer having to use the fn key to get this behavior. When I switch profiles right now, the "Use all F1, F2, etc. keys as standard function keys" option stays so I have to switch it manually. This was unexpected, since other similar settings are persisted as part of the configuration.

**Comment by carlsmith** [comment]
I just tried this. It is really buggy, but does kind of work. I can't figure out what causes it to work or fail, but if you try playing with the setting and testing it, it will probably work with one or two tries. It still needs fixing, but that you may at least get it working the way you want for now.

**Comment by shawnadelic** [comment]
I'm having this issue as well. I haven't been able to get it to switch when switching profiles (as described by @carlsmith).

**Comment by f1yankees** [comment]
Same issue for me.  Would be great if this could get a fix!  Thanks.

**Comment by nbelisle11** [comment]
Same issue here!

**Comment by shaunbokes** [comment]
Same here.

**Comment by SCdF** [comment]
I don't know if this is possible technically, but ideally you wouldn't even need a profile: ideally it would be scoped to the keyboard. That way your external keyboard uses one setting and your internal keyboard uses another
