### ISSUE TITLE
F3 and F4 - how to map them to themselves?

### ISSUE THREAD

**Issue by incandescentman** [tekezo/Karabiner-Elements#726]
F3 and F4 aren't registering for me, and when I do `Show Keyboard Viewer`, they don't register as keypresses. Mapping them to themselves like this doesn't work. 

     "fn_function_keys": {
                "f4":  "f4"
               }

I was able to successfully remap all the function except for F3 and F4. Mapping F8 to itself did work. Just not F3 and F4. 

I checked in System > Keyboard > Shortcuts > Mission Control to verify that they are not mapped to anything else, and they are not.

When I mapped them back to Mission Control and Launchpad, they worked to do that again, but I can't get them to work for any other function.

Running OSX Sierra.

**Comment by BenSapiens** [comment]
I'm having the exact same problem.

**Comment by kAzec** [comment]
Seems that mapping to f3 is working fine now, however mapping to f4 is still a problem.

I use following complex configuration to map fn+1\~9 to f1\~f9 accordingly:

```json
{
  "type": "basic",
  "from": {
    "key_code": "1~9",
    "modifiers": {
      "mandatory": [
        "fn"
      ]
    }
  },
  "to": [{
    "key_code": "f1~f9"
  }]
}
```

When the option "use f1-9 as standard fn keys" are checked, everything works fine and fn+4(aka f4) does activate the LaunchPad. However when the option is not checked, f4 is not recognized and won't show up in the event viewer.

Version 0.91.4 on macOS 10.12.5.
