### ISSUE TITLE
Karabiner Elements kills F1, F2,

### ISSUE THREAD

**Issue by Vendrel** [tekezo/Karabiner-Elements#727]
Hi! Thanks for developing this great app! :)

I experienced that when KE runs, F1 and F2 no longer modifies brightness. However, these are definitely set in the app: decreasing/increasing brightness.

Other function keys works well.

**Comment by jkroes** [comment]
I disagree with the scope of this issue. Running Karabiner-Elements completely disables my ability to switch from standard function keys (e.g. F1) to special features (e.g. decrement brightness). In my experience, this app allows you to switch between these 2 modes, but doesn't let them coexist.
