### ISSUE TITLE
Cmd-Option-Eject doesn't make the machine sleep.

### ISSUE THREAD

**Issue by Vendrel** [tekezo/Karabiner-Elements#728]
If Karabiner Elements runs.

I actually exchanged them (Right-Cmd → Right-Option, and Right-Option → Right-Cmd), but I removed this setting to test it and there's no result, so I no longer sleep my Mac since Karabiner Elements runs. macOS 10.12.4, Hungarian localization.

<3

**Comment by phubert28** [comment]
The primary thing I need mapping for is to make Home and End go to begin
and end of line. Apparently Elements isn't close to this.

In other words, I need keystroke combination mappings to selected
(preferably any) keys, overriding their default action. And it would be
great to include F13-F19!

One example would be Shift-A-Command to F13 to open Applications.

**Comment by rodalpho** [comment]
You want to use defaultkeybindings.dict for this.

http://heisencoder.net/2008/04/fixing-up-mac-key-bindings-for-windows.html

**Comment by SpectralKH** [comment]
+1

**Comment by JesseLeite** [comment]
Same here, but with SHIFT-CTRL-EJECT, which puts displays to sleep.  Works when I quit Karabiner-Elements.  Why doesn't this work with Elements running?

**Comment by jorvi** [comment]
See https://github.com/tekezo/Karabiner-Elements/issues/46
