### ISSUE TITLE
Mouse clicks registering as secondary clicks randomly

### ISSUE THREAD

**Issue by tash-had** [tekezo/Karabiner-Elements#730]
On MacOS Sierra, I am noticing that at random times, my mouse clicks suddenly register as secondary clicks only. I can't do anything because the secondary click menu pops up everytime I click normally. Originally thought it was a hardware issue, and had my laptop checked out. But it just happened again, and the the mouse started working correctly after I "Quit" Karabiner-Elements. 

Anyone know what may be causing this?

**Comment by nolith** [comment]
Hi @tash-had I have the same exact issue, I can narrow it down to resuming from lock screen, it never happened in other situations.

It's not reproducible, but it happens more than once in a week.

**Comment by westlywright** [comment]
I am having this issue as well. I have been able narrow it down to when I unlock my computer first thing in the morning after its been closed all night. Its happened to me every day this week and the only way I am able to fix it is by rebooting. This is happening on 10.12.6 for me.
