### ISSUE TITLE
feature gap with previous Karabiner

### ISSUE THREAD

**Issue by seudut** [tekezo/Karabiner-Elements#732]
Does this support the features,  such as mapping <kbd>Caps</kbd> to <kbd>Esc</kbd> when it is pressed alone, to <kbd>Ctrl</kbd> when it is pressed together with other keys?  I don't find  such setting in the preference.
But I know the previous version of Karabiner on Mac 10.11 supports this feature.

**Comment by coaxmetal** [comment]
The feature is here but hasn't been added to docs. See this though https://github.com/tekezo/Karabiner-Elements/issues/8#issuecomment-279196849

**Comment by seudut** [comment]
Yeah, it works, sorry for the duplicated issue. I will close this. 
Thanks very much @coaxmetal
