### ISSUE TITLE
Backslash

### ISSUE THREAD

**Issue by jgirald** [tekezo/Karabiner-Elements#733]
In Karabiner there is the following option:

> Change right option key+less-than(≤) to backslah(\) key for Spanish.
> Gives you the missing key combo with Alt/Gr without the ordinals.

How can this option be set up in Karabiner-Elements?

I have a US keyboard, but use Spanish ISO layout, so the backslash key is missing.
Notice that when the layout is changed, Karabiner-Elements does not interpret the keys of the layout of the keyboard (US in my case), but the keys of the layout that is selected at the moment (Spanish ISO in my case). Therefore, when I create a "Simple modification From key <key> To Key Backslash", pressing <key> results into the key "ç" (i.e., the key of backslash in the Spanish ISO layout). Since the backslash is missing, I could not find any way to make a modification to a key that is not in the layout.

Is there any solution? Thanks!

**Comment by ayebex** [comment]
I have the same problem. Any solution found?
Cheers and thank you.

**Comment by Jo-Con-El** [comment]
Hello.  I was the one that submitted that change in the original Karabiner.  I've been wanting to fix it in Karabiner-Elements, and here it is!  I'll submit a PR whenever I have a moment so it's there for anyone.

```
{       
  "title": "Make backslash with Option + backtick on Spanish key layout.",
  "rules": [
    {     
      "description": "Make backslash with AltGr (right Option) + backtick",
      "manipulators": [
        {     
          "type": "basic",
          "from": {
            "key_code": "grave_accent_and_tilde",
            "modifiers": {
              "mandatory": [
                "option"
              ],
              "optional": [
                "any"
              ]
            } 
          },    
          "to": [
            { 
              "key_code": "non_us_backslash",
              "modifiers": [
                "right_option"
              ]
            } 
          ] 
        }   
      ]       
    }       
  ]       
}       
```
