### ISSUE TITLE
Modifier flag support

### ISSUE THREAD

**Issue by jtreminio** [tekezo/Karabiner-Elements#734]
I want to map `1` to `!` and `!` to `1`, but need to tell KE that there's a SHIFT flag.

Is this currently possible through the GUI, or can I edit the JSON config directly?

**Comment by carlsmith** [comment]
Nope. You can't currently do this in Karabiner-Elements.

Your best option would be using Ukelele to define a new keyboard layout, derived from the US one or whatever you normally use, with the actions of the number keys inverted.

Ukelele is easy to learn. It has a GUI for editing the layout, and the DMG package bundles an ebook tutorial that's pretty good. You wouldn't need to learn much about Ukelele to achieve what you're looking to do. 

Ukelele basically just simplifies editing keyboard layouts, and then you can swap your current layout for a custom one in the macOS keyboard settings, so it's clean and efficient for the type of thing you're doing.
