### ISSUE TITLE
Finder return/enter to open file

### ISSUE THREAD

**Issue by the-c0d3r** [tekezo/Karabiner-Elements#737]
One of the main reason I use karabiner is to map `return/enter` to **open** file instead of **renaming** the files. There was option to remap it in Karabiner, but I cannot find the same option in Karabiner-Elements. 

I saw that I can remap return/enter but i can only remap it to another single key. If it provides multiple key mapping, i could map it with <kbd>cmd</kbd> + <kbd>o</kbd> to open the file. But then again, there is no such option and if there is, I want it to work only on `Finder`, like how it used to be on Karabiner.

Am I overlooking some options, or this feature hasn't been implemented or will it be implemented in near future?

**Comment by mgacy** [comment]
Use `keypad_enter` as mentioned in #475

**Comment by the-c0d3r** [comment]
Thanks for your info. I tried remapping the `return_or_enter` to `keypad_enter`. But it didn't work in Finder. I still got to the renaming file option. Even though the `Event-Viewer` shows that it's been replaced by `keypad_enter`

**Comment by mgacy** [comment]
Sorry, you're right. `keypad_enter` does work as requested with Path Finder, but not with Finder. I didn't notice because I use the former.

**Comment by mithunpaul08** [comment]
Did you find one for Finder after all?

**Comment by btsai** [comment]
Try the "Finder" setting under this link:
https://pqrs.org/osx/karabiner/complex_modifications/#application_specific

**Comment by the-c0d3r** [comment]
Thanks for your comment. It actually works.

**Comment by ssw112** [comment]
> Try the "Finder" setting under this link:
> https://pqrs.org/osx/karabiner/complex_modifications/#application_specific
> 
> I modified mine to use F2 for renaming, to match Windows:
> 
> ```
>                     {
>                         "description": "Use Return as Open and Use F2 as Rename",
>                         "manipulators": [
>                             {
>                                 "conditions": [
>                                     {
>                                         "bundle_identifiers": [
>                                             "^com.apple.finder"
>                                         ],
>                                         "type": "frontmost_application_if"
>                                     }
>                                 ],
>                                 "from": {
>                                     "key_code": "f2"
>                                 },
>                                 "to": [
>                                     {
>                                         "key_code": "return_or_enter"
>                                     }
>                                 ],
>                                 "type": "basic"
>                             },
>                             {
>                                 "conditions": [
>                                     {
>                                         "bundle_identifiers": [
>                                             "^com.apple.finder"
>                                         ],
>                                         "type": "frontmost_application_if"
>                                     }
>                                 ],
>                                 "from": {
>                                     "key_code": "return_or_enter"
>                                 },
>                                 "to": [
>                                     {
>                                         "key_code": "o",
>                                         "modifiers": [
>                                             "right_command"
>                                         ]
>                                     }
>                                 ],
>                                 "type": "basic"
>                             }
>                         ]
>                     }
> ```

Hi! Could you please help me with remapping delete key to match "return to previous folder" as in Windwods? Thanks!

**Comment by dkrutsko** [comment]
> Hi! Could you please help me with remapping delete key to match "return to previous folder" as in Windwods? Thanks!

If anyone is still looking for this, this addition worked for me:

```json
                            {
                                "conditions": [
                                    {
                                        "bundle_identifiers": [
                                            "^com.apple.finder"
                                        ],
                                        "type": "frontmost_application_if"
                                    }
                                ],
                                "from": {
                                    "key_code": "delete_or_backspace"
                                },
                                "to": [
                                    {
                                        "key_code": "open_bracket",
                                        "modifiers": [
                                            "right_command"
                                        ]
                                    }
                                ],
                                "type": "basic"
                            }
```

**Comment by phrfpeixoto** [comment]
This screws up spotlight

**Comment by dede321** [comment]
agreed @phrfpeixoto 
Any solution to this?

**Comment by phrfpeixoto** [comment]
Not really. I gave up.

**Comment by qnblackcat** [comment]
> Agreed @phrfpeixoto
> 
> Any solution to this?
> 
> Open Finder, so it is the frontmost application. The rule will remap enter, because it is the frontmost application. Now trigger Spotlight. Despite active spotlight, Finder remains the frontmost application and enter will be remapped. You can type for instance "calc" and try hitting enter. It won't work, as it is remapped by the rule.

This might help: https://github.com/pqrs-org/Karabiner-Elements/issues/1982#issuecomment-2392701871
