### ISSUE TITLE
How do I remap § key?

### ISSUE THREAD

**Issue by lightninglu10** [tekezo/Karabiner-Elements#741]
Can't find a map for the § key. I have a computer with a European keyboard but want to map it into a US keyboard.

**Comment by lightninglu10** [comment]
Fixed it by changing my keyboard layout to ISO in `Virtual Keyboard`

**Comment by lightninglu10** [comment]
Fixed it by changing my keyboard layout to ISO in `Virtual Keyboard`

**Comment by stefaneg** [comment]
@lightninglu10 How did that fix the issue? Having the same issue, this does not fix it for me.
