### ISSUE TITLE
Control+PNBF to Up/Down/Left/Right

### ISSUE THREAD

**Issue by sjLambda** [tekezo/Karabiner-Elements#742]
How can I get Emacs-mode or part of that mode, such as Control+PNBF to Up/Down/Left/Right working in Karabiner-Elements? I was completely relying on Emacs-mode on Karabiner, but with elements that's not an option.

If this was tackled elsewhere, please link me there. I could not find any suitable help here.

**Comment by songsanli** [comment]
You can try [Eikana](https://github.com/iMasanari/cmd-eikana).
