### ISSUE TITLE
CapsLock sending multiple keyDown without autorepeat flag

### ISSUE THREAD

**Issue by aristidesfl** [tekezo/Karabiner-Elements#744]
Sometimes, on a single key stroke, 2 keyDown events are sent, and then 2 keyUp event are sent.
The problem is that the second keyDown event doesn't have the autorepeat flag like it should, causing 2 characters to be introduced, instead of triggering the "character accent selector". It also disrupts other tools which rely on the keyboard-repeat events.

This occurs only when remapping CapsLock to other key.
It only happens some times, depending on timing. 
It might happen when the key release matches the moment the key-repeat should start, but I'm not sure about this.

Example: 

```bash
key: capsLock | autorepeat: false | type: keyDown
key: capsLock | autorepeat: false | type: keyUp
key: capsLock | autorepeat: false | type: keyDown
key: capsLock | autorepeat: true | type: keyDown # this is ok
key: capsLock | autorepeat: true | type: keyDown # this is ok
key: capsLock | autorepeat: true | type: keyDown # this is ok
key: capsLock | autorepeat: false | type: keyUp
key: capsLock | autorepeat: false | type: keyDown
key: capsLock | autorepeat: false | type: keyUp
key: capsLock | autorepeat: false | type: keyDown
key: capsLock | autorepeat: false | type: keyUp
key: capsLock | autorepeat: false | type: keyDown
key: capsLock | autorepeat: false | type: keyDown # this should never happen
key: capsLock | autorepeat: false | type: keyUp
key: capsLock | autorepeat: false | type: keyUp # this should never happen
key: capsLock | autorepeat: false | type: keyDown
key: capsLock | autorepeat: false | type: keyUp
key: capsLock | autorepeat: false | type: keyDown
key: capsLock | autorepeat: false | type: keyUp
```

Karabiner-Elements 0.90.92 (think this didn't happen before this version)
macOs 10.124

**Comment by aristidesfl** [comment]
This doesn't seem to happen with a MacBook Air 2011, but happens with a MacBook Pro 2016.

**Comment by afdallah** [comment]
I experienced the same issue and managed to solve it by adding `repeat: false` to the `to event definition`

like so :
```json
"simple_modifications": [
 	{
        "from": {
            "key_code": "caps_lock",
        },
        "to": {
            "key_code": "escape",
            "repeat": false
        }
    },
]
```
