### ISSUE TITLE
Where to find previous releases?

### ISSUE THREAD

**Issue by franciscolourenco** [tekezo/Karabiner-Elements#745]
Where can older versions be downloaded from?

**Comment by alexilyaev** [comment]
Would be awesome if there were release tags, simplest way to do it with [npm version](https://docs.npmjs.com/cli/version).

These tags automatically show up as Releases here on the Github repo.  
And as a bonus each release automatically has a link to a zip and commit hash of that tag.

**Comment by carlsmith** [comment]
I don't have an opinion on versioning, but I don't think this project uses npm, and it's still common to find devs who don't have it installed already. Is that the only system GitHub is able to parse?

**Comment by alexilyaev** [comment]
@carlsmith I see.

We can use just simple Git Tags:  
https://help.github.com/articles/about-releases/
