### ISSUE TITLE
\ key not remapped on external keyboard

### ISSUE THREAD

**Issue by Phylu** [tekezo/Karabiner-Elements#746]
I am using an external keyboard and want to remap the / key (# on my German keyboard) to right_option. On my internal keyboard this works as expected. On my external keyboard however, the keypress is still recognized as \ instead of right_option.

Here is the Karabiner Event Viewer output without any modifier settings for pressing \ first on the internal and then on the external keyboard.
```
eventType:KeyDown         code:0x2a       name:backslash       flags:                                   misc:characters:
eventType:KeyUp           code:0x2a       name:backslash       flags:                                   misc:characters:
eventType:KeyDown         code:0x2a       name:backslash       flags:                                   misc:characters:
eventType:KeyUp           code:0x2a       name:backslash       flags:                                   misc:characters:
```

Here is the Karabiner Event Viewer with the remapping from \ to right_option set for pressing \ first on the internal and then on the external keyboard.
```
eventType:FlagsChanged    code:0x3d       name:right_option    flags:Opt                                misc:characters:
eventType:FlagsChanged    code:0x3d       name:right_option    flags:                                   misc:characters:
eventType:KeyDown         code:0x2a       name:backslash       flags:                                   misc:characters:
eventType:KeyUp           code:0x2a       name:backslash       flags:                                   misc:characters:
```

Any chance to correctly remap this key?

**Comment by Phylu** [comment]
If there is any way, I can help to sort out this issue, please let me know.

**Comment by rggjan** [comment]
I have the same problem, could also provide testing...

**Comment by Phylu** [comment]
One more piece of additional information: I have just tested an external bluetooth keyboard. On this keyboard pressing the (German) # key, the eventType is properly recognized as right_option.

**Comment by TaucherMK** [comment]
It works for me if I remap backslash_pound instead of backslash (external german keyboard).

**Comment by Phylu** [comment]
I can confirm, that remapping non_us_pound works to remap the '#' key on my external German keyboard.

Thanks @TaucherMK
