### ISSUE TITLE
Feature request - Assign profiles to applications

### ISSUE THREAD

**Issue by csghuser** [tekezo/Karabiner-Elements#748]
Firstly, thank you for this app, it is extremely useful. 

It would be very handy to be able to automatically assign a profile to an application. So that when you switch to it, the profile switches to one you have assigned. 

Not sure if it is possible, but it would be useful when using an app like virtualbox.

**Comment by wincent** [comment]
Probably a duplicate of #137.

**Comment by csghuser** [comment]
Yep, seems to be. I will close this.
