### ISSUE TITLE
± or § what is that key called? 

### ISSUE THREAD

**Issue by ismailallocator** [tekezo/Karabiner-Elements#749]
How can I select remap §  key (Alt 21 )  what is it called?

**Comment by tnokovski** [comment]
`§` is called Section, however it's `Alt + 6` on my MBP. I cannot find it in Karabiner-Elements so I believe it is missing.

**Comment by AhkrinDescol** [comment]
In Karabiner-Elements I used EventViewer to figure out what key it is; for me my MacBook considers it non_us_backslash.

**Comment by kamyarghasemlouDH** [comment]
choosing non_us_backslash worked for me.
