### ISSUE TITLE
Conflict with ControllerMate

### ISSUE THREAD

**Issue by gruntoff** [tekezo/Karabiner-Elements#75]
Karabiner-Elements conflicts with ControllerMate and doesn't allow it to connect to a keyboard. Is it a Karabiner issue or a ControllerMate issue?
<img width="440" alt="2016-09-22 0 49 38" src="https://cloud.githubusercontent.com/assets/16617167/18730388/c480ab98-805e-11e6-8448-c5050ed90bc9.png">

**Comment by tekezo** [comment]
It's a macOS Sierra limitation.
Sierra provides the only way to modify keyboard input in the hardware driver layer and it is exclusive.
So, we can run the only one input event modifier at the same time.

Please use either Karabiner-Elements or ControllerMate.
