### ISSUE TITLE
macOS sierra 10.12.4 shutdown occasionally when built-in keyboard was disabled

### ISSUE THREAD

**Issue by hustcer** [tekezo/Karabiner-Elements#750]
Thanks for the great work!

However, my macOS sierra 10.12.4 shutdown occasionally when the built-in keyboard was disabled, I even had no chance to cancel the shutdown. It happened 4 times today. It seemed to be okay when I enable the built-in keyboard. Anyone can help?

Karabiner-Elements version: 0.90.92
Keyboard: Logitech K380 with bluetooth connection.

**Comment by lucky521** [comment]
I met this issue randomly.  macOS 10.13.6.
