### ISSUE TITLE
disable sticky caps_lock

### ISSUE THREAD

**Issue by monkeydri** [tekezo/Karabiner-Elements#753]
Hi, I use the Karabiner-Elements fork from [wwwjfy](https://github.com/wwwjfy/Karabiner-Elements) so I can remap right-option to multiple modifiers keys ("left_option", "left_control", "caps_lock") :

```
            "one_to_many_mappings": {
                "right_option": [
                    "left_option",
                    "left_control",
                    "caps_lock"
                ]
            }
```

It works great except one thing : because of the sticky behaviour of the caps_lock flag, when i press right-option i will not receive last caps_lock event (down or up event depending on the state of the caps-lock flag). In other words would like the caps lock to act as a normal modifier key : when the caps lock press the key I want to receive key down and key up event.

Right now when i press right-option first time : 
left_option down, left_control down, caps_lock down, left_option up and left_control up

Next time I press right option : 
left_option down, left_control down, caps_lock up, left_option up and left_control up

I have tried to disable the caps_lock (remapping it to escape or whatever `  "simple_modifications": { "caps_lock": "escape" `), but it only affects the caps_lock key, not the caps_lock flag (I can still see the light coming on/off).

I really need your help !

**Comment by monkeydri** [comment]
Alright I did try many options in `karabiner.json` but could not get it to work so I ended up digging the code a bit and finally found the culprit : the ` void caps_lock_state_changed_callback(bool caps_lock_state)` callback in [device_grabber.hpp](https://github.com/tekezo/Karabiner-Elements/blob/b1853deb969151c4209d00703f21d8db225dc1a4/src/core/grabber/include/device_grabber.hpp) 

After a quick-and-dirty modification (commenting out the whole thing) it worked. :

```
  void caps_lock_state_changed_callback(bool caps_lock_state) {
    /*
    event_manipulator_.set_caps_lock_state(caps_lock_state);

    // Update LED.
    for (const auto& it : hids_) {
      if ((it.second)->is_grabbed()) {
        (it.second)->set_caps_lock_led_state(caps_lock_state ? krbn::led_state::on : krbn::led_state::off);
      }
    }
    */
  }
```
If you want to cherry pick it : https://github.com/monkeydri/Karabiner-Elements/commit/501b8bfb89f2fecef9e7f17c7d7dfe883aacfde5

---

For the record the steps I used to build that thing :

- `sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer`
- `brew install boost`
- `sudo mkdir -p /opt/local`
- `sudo ln -s /usr/local/Cellar/boost/1.64.0_1/include /opt/local/include`
- `git clone https://github.com/wwwjfy/Karabiner-Elements.git`
- `cd Karabiner-Elements`
- change developper identity in `codesign.sh` and developper id installer identity in `codesign-pkg.sh`
- comment out last three lines from `make-package.sh` (hdiutil bug).
- `make`

**Comment by monkeydri** [comment]
@wwwjfy any hint to point me to the right direction ? Actually I don't know if the caps_lock keypress up event is ever sent to Karabiner...

**Comment by wwwjfy** [comment]
It seems caps lock needs special handling, as you can see, the caps lock state is all over the grabber code.
Sorry I haven't read that part yet.
