### ISSUE TITLE
Media control keys of HHKB Bluetooth are unusable after installing Karabiner-Elements

### ISSUE THREAD

**Issue by zshbleaker** [tekezo/Karabiner-Elements#757]
Hi there, thanks for developing such an awesome software. 

I'm using HHKB Bluetooth keyboard(https://www.amazon.com/dp/B01DVH7C0O) and there're some media control keys on the keyboard(Fn+ a for decreasing volume e.g.). And those keys won't work after installing Karabiner-Elements.

I'm a long term user of the old Karabiner and everything works properly with the old version. Wish you could fix this.

I'll provide any useful information if needed.

**Comment by tockrock** [comment]
Have you tried this recently?
This seems to be working for me. Maybe some update solved this?

**Comment by tockrock** [comment]
ah could be an driver issue #424

**Comment by camscofie** [comment]
I worked for me, don't know how, but it came normal like other keyboard

**Comment by zshbleaker** [comment]
I just tried the latest version and didn't configure anything. The issue is still there. Pressing fn + a is even not logged in Karabiner-EventViewer.

Are you using HHKB BT with Karabiner-Elements 0.91.13 on macOS 10.12.6 and everything goes fine?

**Comment by tockrock** [comment]
@zshbleaker Do you have your keyboard setup to macOS/iOS mode?
On the bottom side of the keyboard, there is a cover that lets you access to customization switches. To be in macOS/iOS mode, you need to have SW1=OFF and SW2=ON.

http://www.pfu.fujitsu.com/hhkeyboard/bt/feature.html

Couldn't find an official English page, but it the same as the non-BT ones (you don't need driver for the BT keyboard, and the location of the switch is different)

https://elitekeyboards.com/products.php?sub=pfu_keyboards,hhkbpro2&pid=pdkb400b

**Comment by zshbleaker** [comment]
@tockrock Of course Macintosh mode is on. I've been a HHKB user for many years :(

Everything is fine if Karabiner Elements is not installed, and the issue is not with the old Karabiner either. 

Thanks for your patience :)

**Comment by tockrock** [comment]
I'm not sure what else the issue, is since I also have the HHKB BT, and it seems to be working fine for me.
I guess another thing that you might want to check is if it works when you uncheck the HHKB-BT in the Devices tab.
