### ISSUE TITLE
Combined keys?

### ISSUE THREAD

**Issue by stevejordi** [tekezo/Karabiner-Elements#759]
Hi,
It seems impossible to combine keys.
Most non US keyboards have the alt-gr key to be combined with another one.
Shouldn't it possible to alter such sequences?

Ex: 
alt-gr è gives [
alt-gr ¨ gives ]
alt-gr à gives {
alt gr $ gives }
etc

**Comment by woozong** [comment]
I second this motion 👍

**Comment by ficus** [comment]
Yeah, I'm also confused.  I just want to make the 'home' and 'end' keys work on this ANSI keyboard. Not really getting how this is a continuation of the old Karabiner.

**Comment by tyten** [comment]
Second this as well. Used to have several key combos setup for cursor control. 1:1 mapping prevents this from happening.

**Comment by stevejordi** [comment]
Would that be possible with the new Complex Modifications?
If yes, where is the doc. We can launch the web page but just download ready-to-use samples. How do we do our own?

**Comment by stevejordi** [comment]
Keep it open, this is definitely a must have.

**Comment by kimslawson** [comment]
Reopening because useful
