### ISSUE TITLE
How to remove VirtualHIDKeyboard?

### ISSUE THREAD

**Issue by jasonlong** [tekezo/Karabiner-Elements#76]
I'm doing some system debugging and have removed all traces of Karabiner-Elements from what I can tell, but I can't seem to find where macOS is getting this VirtualHIDKeyboard entry (though it seems to be from this project).

<img width="537" alt="screen shot 2016-09-21 at 10 18 23 pm" src="https://cloud.githubusercontent.com/assets/6104/18735115/61e8651c-8049-11e6-9e50-96be19922d53.png">

**Comment by jasonlong** [comment]
I've completely removed Seil from my computer, so there must be some config file somewhere.

**Comment by irliao** [comment]
this commit removes VirtualHDKeyboard kexts:
https://github.com/tekezo/Karabiner-Elements/commit/eba1476ff3b07b18df4af8a1aa65614debdad6ed

**Comment by jasonlong** [comment]
Thanks @irliao. I found those files and removed them. I'll go ahead and close this issue.
