### ISSUE TITLE
disabled shift_L but mouse events still see the shift flag

### ISSUE THREAD

**Issue by hassanformanite** [tekezo/Karabiner-Elements#760]
My mac has the left key malfunctioned to always pressed state. I used Karabiner to disable the left shift key. It has been working on the Karabiner and it is working for keyboard button events in Karabiner-Elements.
The issue is mouse events does not recognize the shift key being disabled.
Is there a quick workaround for this? I can try building the code using Xcode myself if any hints are given?

**Comment by thaisweiller** [comment]
exactly same problem here, malfunctioning key is also shift_l.

**Comment by tiagofassoni** [comment]
Just to give a +1, I also have the problem, and absolutely no idea how to solve it.

**Comment by chmandrade** [comment]
+1
Yesterday everything was working fine with the keyboard,  mouse and trackpad. Today I started having the same problem as Sunday. Mouse and trackpad not working.

**Comment by apirak** [comment]
+1
Have this issue in high sierra
