### ISSUE TITLE
Preventing sleep mode while mapping caps lock to escape

### ISSUE THREAD

**Issue by al-joshwilliams** [tekezo/Karabiner-Elements#762]
I'm using a retina 15 inch, mid 2015 MacBook Pro running macOS Sierra 10.12.4.

My computer hasn't been going to sleep at all for the past couple weeks. I finally figured out today that karabiner-elemenets (0.90.92) was triggering "PreventUserIdleSystemSleep," perhaps by "pressing" a key every second.

I had caps lock remapped to escape. When I removed that mapping, my computer started sleeping properly again.

**Comment by briemens** [comment]
I'm seeing the same issue I think, although I'm not sure if it is related to a specific key mapping.
Once the service `org.pqrs.karabiner.karabiner_grabber` is running my `hidd` process shows "Preventing sleep" as "yes".
Once I stop this karabiner service and kill hidd (to restart) my machine goes to sleep normally.
