### ISSUE TITLE
right_shift + left_shift combination

### ISSUE THREAD

**Issue by monstermac77** [tekezo/Karabiner-Elements#765]
Prior to macOS Sierra, I was able to map a simultaneous press of right shift and left shift to caps lock. This is not possible in Karabiner-Elements. I understand that this is likely the case because major changes in Sierra have necessitated a long update process to Karabiner. 

Will this eventually be possible with Karabiner on Sierra? Alternatively, is there something else I can use to achieve this functionality? 

Since I have remapped caps lock to delete, I currently have no way to trigger caps lock.

**Comment by wincent** [comment]
I got it working with [this config](https://github.com/wincent/wincent/blob/1b2321fad6eb8d7078f6c2d2962423a3f7882c2e/roles/dotfiles/files/.config/karabiner/karabiner.json#L100-L139).

**Comment by monstermac77** [comment]
@wincent, thanks so much for this. I've tried adding it to my config file, but it appears not to be working. I've never modified the config before, so I may have made a mistake or omitted a step? 

Modified ~/.config/karabiner/karabiner.json 
Here's my new config: https://pastebin.ubuntu.com/24888992/

After modifying, I quit Karabiner-Elements via the button on the GUI, and reopened it. My other remap continues to work. I'm running Karabiner-Elements version 0.90.92. 

I've also tried setting Caps Lock to "No Action" in the "Modifier Keys" of System Preferences, as I think that previously may have had an impact under Karabiner.

**Comment by wincent** [comment]
I think you'll need at least 0.91.3 for this to work.

**Comment by monstermac77** [comment]
You are absolutely right. Had to do the beta update to get support for "complex_modifications". Thank you!

For those looking for this setup: make sure you are on a version after "complex_modifications" support was added, I think it might have a couple point releases before 0.91.3 (you may need to "Check for beta updates" in "Misc"). Then, open Terminal and run: 

`open ~/.config/karabiner/karabiner.json`

And modify the file to include the lines @wincent linked to from his config. Save, quit Karabiner-Elements and reopen and you should be set.
