### ISSUE TITLE
Elements 0.91.0 not working on macOS Sierra 10.12.15

### ISSUE THREAD

**Issue by babychao** [tekezo/Karabiner-Elements#768]
After updating to Karabiner Elements **0.91.0** on macOS Sierra **10.12.5**, upon reboot, it ceased to work completely. Nothing I typed on my external USB keyboard would register unless I uncheck _Modify events from this device_ under Devices.

I had to roll back to **0.90.92** downloaded from https://pqrs.org/latest/karabiner-elements-latest.dmg before I could get my external USB keyboard working properly again.

**Comment by cmsj** [comment]
@babychao is there a release build of 0.91.0 somewhere? I could only find that 0.90.92 dmg and I was hoping to avoid installing Xcode on my little macbook :)

**Comment by setton** [comment]
Same issue as @babychao - and the rollback to 0.90.92 works, thank you for providing the workaround.

**Comment by babychao** [comment]
Yes.

Karabiner-Elements Preferences > Misc > Check for beta updates :)

**Comment by diegodesouza** [comment]
Just installed karabiner-elements and it's not working for me either. =/

**Comment by babychao** [comment]
@diegodesouza If 0.90.92 doesn't work, try the beta 0.91.0?

If it's vice versa, try to roll back to 0.90.92?

**Comment by tekezo** [comment]
Thank you for feedback!
I've fixed 0.91.0 issue in 0.91.1.

**Comment by babychao** [comment]
@tekezo Installed 0.91.1 on Sunday. I can confirm it works nicely. Thank you! :)
