### ISSUE TITLE
Built in and external usb keyboards stop working when Mac goes to sleep

### ISSUE THREAD

**Issue by guycalledseven** [tekezo/Karabiner-Elements#771]
Hi,
I am suspecting this is already reported by many users (https://github.com/tekezo/Karabiner-Elements/issues/769), however I did not find reference to 'sleep'. 

I can reproduce it anytime. MacOS 10.12.5, latest karabiner, MBP 2015

1. everything works
2. `pmset sleepnow`
3. wake up from sleep - keyboards do not work anymore. disabling Karabiner enables them.

Thanks in advance!

**Comment by rynonl** [comment]
I have this issue as well. MacOS 10.12.6, KE 11.3.0, MBP 2015. (worth noting that it's happened ever since the Sierra debacle and with multiple OS and KE versions). Keyboard is a KUL ES-87.
