### ISSUE TITLE
Convert from Karabiner config to Karabiner-Elements

### ISSUE THREAD

**Issue by allancarhart** [tekezo/Karabiner-Elements#772]
Hi, I'm sorry if this is an FAQ. My employer forced me to upgrade my Macbook to Sierra, and I'm kind of lost without the Karabiner mapping that I've come to depend on.

I have installed Karabiner-Elements.  I understand this is somewhat experimental/beta.  And I see that there are no predefined mappings ready to go as there were in Karabiner.  So my question is a few fold:
1. I still have Karabiner installed - just haven't gotten around to uninstalling it.  I have 28 keyboard mappings that I've been using.  Where is the Karabiner (NOT ELEMENTS) config persisted?  I've searched my home directory, but don't seem to see it. Is there some way to take the definition of the 28 keyboard mappings that I want, and outputting them to a config  XML/JSON?

2. Assuming the answer to the first question is 'yes' I can expect those mappings to some static file, then my next question is:  Is there any way to take the output of Karabiner and convert it so Karabiner Elements can read it?  Maybe I'm missing something, because if this is possible I'd expect it would be an obvious action that (most) everybody would want.  So the process would be published/automated.

Please let me know if I'm completely off-base, if something about my question doesn't make sense.  Thanks!

**Comment by allancarhart** [comment]
Looks as though I need to wait for Issue #16 like everybody else --
 And once that's closed, maybe there will be a more straightforward karbiner-to-elements converter.

https://github.com/tekezo/Karabiner-Elements/issues/16

**Comment by durka** [comment]
See #1332 for a start.
