### ISSUE TITLE
Shift modifier gets stuck, likely due to using Karabiner-Elements

### ISSUE THREAD

**Issue by DrChr** [tekezo/Karabiner-Elements#774]
I noticed the following issue some months after migrating to macOS Sierra, and I don't know exactly what it is that triggers it.  Typically I've noticed the symptom in Safari where it's confusing, as suddenly when clicking links, it doesn't open a new tab but instead adds the link to Safaris reading list.  Eventually I figured out that what's happening is that the "shift" modifier has become stuck in active mode.  I have verified this by running the Karabiner-EventViewer, and in the column "flags" it says "Shift" even thought neither of my shift keys are pressed.

By restarting the computer, the problem goes away. It can also go away if I quit Karabiner-Elements and restarts it, but it doesn't always work. Sometimes I end up quitting and restarting Karabiner-Elements multiple times before it works. Sometimes it seems to help to start/use Karabiner-EventViewer in between, closing it before again starting Karabiner-Elements.

Unfortunately, what triggers this issue seem a bit random. It does however seem to be happening more frequently these days.  Now the issue can reappear after having used Safari for hours or minutes. But sometimes days or a week or two can go by without the problem.

Note: I've now been running the computer _without_ Karabiner-Elements for some time and have _not_ encountered the problem, making me think the issue somehow is due to Karabiner-Elements.

I understand that the description above isn't very helpful in trying to track down the problem, so what could I do to help?   Would a copy of the logs from Karabiner-Elements help? Or something else?

Details:
- Karabiner-Elements 0.91.0 (also happened with an earlier version)
- macOS Sierra 10.12.5
- mac Book air
- Swedish keyboard laptop keyboard (no external keyboard).
- Configuration: Swap Fn-key and Ctrl-key, see configuration below:
```
{
    "global": {
        "check_for_updates_on_startup": true,
        "show_in_menu_bar": true,
        "show_profile_name_in_menu_bar": false
    },
    "profiles": [
        {
            "devices": [],
            "fn_function_keys": {
                "f1": "display_brightness_decrement",
                "f10": "mute",
                "f11": "volume_decrement",
                "f12": "volume_increment",
                "f2": "display_brightness_increment",
                "f3": "mission_control",
                "f4": "launchpad",
                "f5": "illumination_decrement",
                "f6": "illumination_increment",
                "f7": "rewind",
                "f8": "play_or_pause",
                "f9": "fastforward"
            },
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "fn": "left_control",
                "left_control": "fn"
            },
            "virtual_hid_keyboard": {
                "caps_lock_delay_milliseconds": 0,
                "keyboard_type": "ansi"
            }
        }
    ]
}
```

**Comment by ntcong** [comment]
It's the same as this issue https://github.com/tekezo/Karabiner-Elements/issues/466#issuecomment-305764484

**Comment by DrChr** [comment]
Duplicate, like ntcong said -> closing it.
