### ISSUE TITLE
Caps Locks to Modifiers Only

### ISSUE THREAD

**Issue by nfarrar** [tekezo/Karabiner-Elements#779]
I'm trying to use the newest beta version to remap my hyperkey. The behavior I'm looking for is that if I hold down caps_lock, nothing occurs until I either press another key or release the capslock key without pressing another key. There are three desired behaviors:

- while holding caps_lock, press another key: an event should be emitted for that key with the modifiers: left_control, left_option, and left_command
- while holding caps_lock, hold shift, and press another key: the same should occur, with the additional left_shift modifier
- press and release caps_lock: emit an esc key event

I was attempting to work off the configuration here: http://brettterpstra.com/2017/06/14/full-hyper-key-functionality-restored-in-sierra/, however this is specifically remapping caps_lock to left_shift, and emitting events as soon as keys are pressed, rather than treating them as true conditional modifiers. If I completely remove the "key_code" under the "to" section, nothing occurs. If I change it to an empty list, still nothing occurs. Any suggestions?

**Comment by SpectralKH** [comment]
This isn't well documented, and neither in examples, but I looked through commits and found out you can use "mandatory" instead of "optional" inside complex_modifications > rules > manipulators > from > modifiers.

This config should work:
`{
    "global": {
        "check_for_updates_on_startup": true,
        "show_in_menu_bar": false,
        "show_profile_name_in_menu_bar": false
    },
    "profiles": [
        {
            "complex_modifications": {
                "rules": [
                    {
                        "manipulators": [
                            {
                                "description": "shift+caps_lock to shift+ctrl+alt+cmd",
                                "from": {
                                    "key_code": "caps_lock",
                                    "modifiers": {
                                        "mandatory": [
                                            "left_shift"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "left_shift",
                                        "modifiers": [
                                            "left_command",
                                            "left_control",
                                            "left_option"
                                        ]
                                    }
                                ],
                                "to_if_alone": [
                                    {
                                        "key_code": "escape"
                                    }
                                ],
                                "type": "basic"
                            },
							{
                                "description": "caps_lock to ctrl+alt+cmd, caps_lock to esc",
                                "from": {
                                    "key_code": "caps_lock",
                                    "modifiers": {
                                        "optional": [
                                            "any"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "left_command",
                                        "modifiers": [
                                            "left_control",
                                            "left_option"
                                        ]
                                    }
                                ],
                                "to_if_alone": [
                                    {
                                        "key_code": "escape"
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    }
                ]
            },
            "devices": [],
            "fn_function_keys": {
                "f1": "display_brightness_decrement",
                "f10": "mute",
                "f11": "volume_decrement",
                "f12": "volume_increment",
                "f2": "display_brightness_increment",
                "f3": "mission_control",
                "f4": "launchpad",
                "f5": "illumination_decrement",
                "f6": "illumination_increment",
                "f7": "rewind",
                "f8": "play_or_pause",
                "f9": "fastforward"
            },
            "name": "Helpadude",
            "selected": true,
            "simple_modifications": {},
            "virtual_hid_keyboard": {
                "caps_lock_delay_milliseconds": 0,
                "keyboard_type": "ansi"
            }
        }
    ]
}
`
