### ISSUE TITLE
command+option+esc (⌘ ⌥ ⎋) does not open Force-Quit when Karabiner Elements is active

### ISSUE THREAD

**Issue by seishonagon** [tekezo/Karabiner-Elements#780]
I've seen one reference of this in comments a few months ago, but no other mentions. It seems that the "_Force-Quit_" shortcut is disabled when K-E is active. 

I'm using version 0.91.2, remapping my Caps-Lock key to a Hyper key, on a 2016MBP 15" with touch bar running Sierra 10.12.5

**Comment by HRG1** [comment]
This shortcut is working for me with Karabiner Elements 0.91.3, macOS 10.12.5, 2013 MBP 15". Caps-Lock is set as hyper key if used with any other key and as caps-lock if alone.

**Comment by RoadToDream** [comment]
Still exists on my computer 
Karabiner version 12.1.0
macOS version 10.13.6

**Comment by RoadToDream** [comment]
Sorry my fault. I need to check touchbar in device menu.

**Comment by jm3** [comment]
@RoadToDream were you able to fix this? I'm having the same issue.

**Comment by RoadToDream** [comment]
@jm3 I didn't fix it cause it is not a bug at all. You need to check both the items listed in the "Devices" sub-table. See below
![snipaste_2019-01-31_11-31-28](https://user-images.githubusercontent.com/8088354/52028902-dbaf8980-254b-11e9-997c-b18a320977b5.png)
As touch bar is recognized as a secondary keyboard, so you need to make sure it is set to respond to Karabiner's manipulation.

**Comment by caillou** [comment]
@tekezo could we re-open that issue, as it is not fixed yet?
