### ISSUE TITLE
to_if_alone on space bar and fn hacks

### ISSUE THREAD

**Issue by wxmtech** [tekezo/Karabiner-Elements#781]
Really good hack: to_if_alone to be space bar, and something else as hyper key modifiers.

But the thing is when use something like cmd+space to invoke spotlight, *this hack is not really butter smooth, sometimes space is changed to modifiers, which is really annoying to me.*

In addition, anyone how to hack fn key to combine it with f1-15 to be fn, and combine others to be hyper key modifiers like cmd+control+shift stuff. I did not find a way to describe f1-f15 keys to a whole.

**Comment by rafegoldberg** [comment]
This is a great question:

> anyone [know] how to hack [the] `Fn` key to combine it with `F1`-`F15`... and [still] combine others to be hyper key modifiers like cmd+control+shift?

I've been searching hi + lo for a solution

**Comment by wxmtech** [comment]
Did this a while ago. While looking for a Karabiner-Element based solution, no rules to change a hyper key when combine with other keys like f1-f15, or number, letter keys. Hope there will be in the future.

One dumb way is just assign fn -> cmd+ctrl+shift, then use other apps(Keyboard Maestro) to specifically assign cmd+ctrl+shift+f1 to reduce brightness and so on.
