### ISSUE TITLE
"thumbsense" support?

### ISSUE THREAD

**Issue by johnlindquist** [tekezo/Karabiner-Elements#782]
https://github.com/tekezo/Karabiner/blob/master/src/core/server/Resources/include/checkbox/thumbsense.xml

^As seen above, the original Karabiner supported using touching the trackpad as a modifier. Is Thumbsense possible with Elements? Is there another app that enables this behavior?

**Comment by denismaciel** [comment]
The lack of Thumbsense is the sole reason why I haven't updated my operating system until today. It's such a great feature! It would be awesome to know if Thumbsense is at least in the pipeline.

**Comment by yijia-zhan** [comment]
Any updates on this? Or rather, any updates of supporting trackpad in karabiner-element?

**Comment by yijia-zhan** [comment]
bump

**Comment by nagamine-git** [comment]
it had been supoorted! https://pqrs.org/osx/karabiner/complex_modifications/#thumbsense
