### ISSUE TITLE
Change keys to allow pressed state

### ISSUE THREAD

**Issue by jonnyijapan** [tekezo/Karabiner-Elements#783]
Normal behavior of keys in MacOS when held down is to cause a repeated up/down pattern.

Can we somehow change it to allow a pressed key (ie non released) to stay pressed when held down?

**Comment by jrus** [comment]
Usually the system gets {key down, key down, key down, ..., key down, key up} when you press and hold a key for a while and then release it.

If you want to adjust the key repeat rate or turn repeat off, you can use the Keyboard pane of system preferences.

**Comment by zapjonny** [comment]
Ok that "works", making it stop go up and down on and on.
However for some reason it does not emulate an Amiga joystick fire button presses down. 🎮
