### ISSUE TITLE
can't use in OSX 10.12.5

### ISSUE THREAD

**Issue by yuzhuxiang** [tekezo/Karabiner-Elements#784]
I'm using the latest version 0.90.92

**Comment by lahdekorpi** [comment]
Works fine for me with 10.12.5.

**Comment by garfieldnate** [comment]
Works fine for me too. You are talking about *this* project, right? Karabiner-elements, not Karabiner.

**Comment by yuzhuxiang** [comment]
I’m talking about Karabiner-elements.
the first time I do the following settings, it doesn't work.
![](https://ooo.0o0.ooo/2017/06/24/594dda8969ca8.jpg)
and when I restart this software,my settings disapperd.

**Comment by irandolph** [comment]
I have exactly the same problem. MacOS updated overnight to 10.12.5 and now it doesn't work. Key modifications disappear when I close Karabiner Elements, and they don't have any effect while the app is open. I rely on this for work – help?

**Comment by lahdekorpi** [comment]
Does this happen after reinstalling as well?

**Comment by yuzhuxiang** [comment]
reinstalling doesn't work!

**Comment by apm1467** [comment]
That seems like a permission problem.

When user creates rules in KE, KE will write these rules into the settings file `~/.config/karabiner/karabiner.json`. If this file is not writable, then nothing will work, and the rules will disappear every time you restart the app.

You may test if this file exists. If not, create this file and adjust the permission of it, and then create the rules in KE again.

```
$ touch ~/.config/karabiner/karabiner.json
$ chown $(whoami) ~/.config/karabiner/karabiner.json
```

**Comment by lahdekorpi** [comment]
Please note that the command above assumes you have an existing `~/.config/karabiner/` directory and that the permissions of that directory are correct.

**Comment by yuzhuxiang** [comment]
the file exists and the permission is right!
![](https://ooo.0o0.ooo/2017/06/29/5954629a7f489.jpg)

**Comment by apm1467** [comment]
What's the content of this file? If you write some rules directly into this file, will they work?

**Comment by yuzhuxiang** [comment]
Yesterday I updated to the beta version 0.91.4, the problem still exists.
when I do the Simple Modifications in the software, it changed in real time in the file.
when I write some rules directly into this file, still doesn't work!
```
{
    "global": {
        "check_for_updates_on_startup": true,
        "show_in_menu_bar": true,
        "show_profile_name_in_menu_bar": false
    },
    "profiles": [
        {
            "devices": [],
            "fn_function_keys": {
                "f1": "display_brightness_decrement",
                "f10": "mute",
                "f11": "volume_decrement",
                "f12": "volume_increment",
                "f2": "display_brightness_increment",
                "f3": "mission_control",
                "f4": "launchpad",
                "f5": "illumination_decrement",
                "f6": "illumination_increment",
                "f7": "rewind",
                "f8": "play_or_pause",
                "f9": "fastforward"
            },
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "caps_lock": "return_or_enter"
            },
            "virtual_hid_keyboard": {
                "caps_lock_delay_milliseconds": 0,
                "keyboard_type": "ansi"
            }
        }
    ]
}
```

**Comment by yuzhuxiang** [comment]
beta version 0.91.5 now works fine with me！

**Comment by klnvnv** [comment]
bump

same thing happens for me on 0.91.5

just remapping "right_option": "left_control"
installed it on a fresh MacBook pro 15 2014, permissions on the config file are ok, pretty much went through the same stuff @yuzhuxiang did, I have some other version working ok on the my MacBook 12 btw

**Comment by irandolph** [comment]
It now works for me too – Thank you sooooooooooo much!
