### ISSUE TITLE
to_if_alone sending events in non-deterministic order

### ISSUE THREAD

**Issue by wincent** [tekezo/Karabiner-Elements#785]
I'm using [this `to_if_alone` config](https://github.com/wincent/wincent/blob/890c52b2bccbb6fecf0d9a5c332b0d364202a17d/roles/dotfiles/files/.config/karabiner/karabiner.json#L45-L76) with a build of Karabiner-Elements from the `HEAD` of the master branch a couple of days ago (specifically commit 97d6732e3aa59f4d934395d7d822eefc43c94602) to give me "Enter" when "Enter" is pressed alone and "Control" when it is pressed together with another key.

I noticed that sometimes an "Enter" keypress produces this event log:

```
eventType:FlagsChanged    code:0x3e       name:right_control   flags:Ctrl                               misc:
eventType:KeyUp           code:0x24       name:return_or_enter flags:                                   misc:
eventType:KeyDown         code:0x24       name:return_or_enter flags:                                   misc:
eventType:FlagsChanged    code:0x3e       name:right_control   flags:                                   misc:
```

(ie. control down, then the "enter", then control up) and other times (about 50% of the time) it produces this:

```
eventType:FlagsChanged    code:0x3e       name:right_control   flags:Ctrl                               misc:
eventType:FlagsChanged    code:0x3e       name:right_control   flags:                                   misc:
eventType:KeyUp           code:0x24       name:return_or_enter flags:                                   misc:
eventType:KeyDown         code:0x24       name:return_or_enter flags:                                   misc:
```

(ie. control down then up, then the "enter"). This latter behavior is correct, I think, and the other one is not. This is noticeable in apps like Chrome in the location bar where there is a difference between Enter and Control-Enter; eg. if I type "tw" and the autocomplete suggests "https://twitter.com" (with "itter.com" selected):

<img width="131" alt="new_tab" src="https://user-images.githubusercontent.com/7074/27258058-93141d50-53a4-11e7-9e53-76c0f242b201.png">

Without Karabiner-Elements, pressing "Control-Enter" would actually navigate to "tw.com" and pressing "Enter" would navigate to "twitter.com". So, with the configuration above, pressing "Enter" goes to "tw.com" about 50% of the time and to "twitter.com" the other 50%.

This is on macOS Sierra 10.12.4 (16E195).

**Comment by wincent** [comment]
Wondering if 62767e3482a4140ad17a is relevant here. The removed code comment said "Without wait, window system sometimes reorder modifier flag event.", but the commit doesn't say why the workaround could be removed.

**Comment by wincent** [comment]
So I just reverted 62767e3482a4140ad17a1468269ae216394d9184 on top of master (dc8dfbdedfe7eedff97e976573266c92aa13613b), and I can't reproduce the problem: the events always occur in the right order.

**Comment by tekezo** [comment]
Thank you for feedback!

I confirmed this issue and reverted the change in v0.91.4.

**Comment by wincent** [comment]
Thank you!

**Comment by wincent** [comment]
Just opened #789 as a follow-up as I've discovered a couple more issues with `to_if_alone`.
