### ISSUE TITLE
Error when checking for beta updates 

### ISSUE THREAD

**Issue by rafegoldberg** [tekezo/Karabiner-Elements#786]
Trying to grab the beta build of Karabiner Elements (gotta get that hyper key) but whenever when I try to update (to the beta _or_ latest build) I get the following error:

![image](https://user-images.githubusercontent.com/886627/27261354-2b6334e6-53f6-11e7-98f2-1e69d0f35f3b.png)

Alas, I have a feeling that^ alone won't be useful for debugging. But I don't see any related output in the Logs pane, and not sure where else to look for useful info! Any help would be much appreciated.

**Comment by apm1467** [comment]
Which version are you at now? If you just uninstall and reinstall Karabiner Elements once, would that help?

**Comment by rafegoldberg** [comment]
hmm, never did figure out what was wrong... had to uninstall + restart + reinstall, but that seemed to fix it!
