### ISSUE TITLE
change other keys to power key doesn't works

### ISSUE THREAD

**Issue by micanzhang** [tekezo/Karabiner-Elements#79]
this is my karabiner.json config:

``` json
{
  "profiles": [
    {
      "name": "Default profile",
      "selected": true,
      "simple_modifications": {
        "caps_lock": "left_control",
        "pause": "power",
        "home": "power",
        "right_alt": "power",
        "application": "fn"
      }
    }
  ]
}
```

`fn` and `left_control` work well, but `power` key doesn't work

**Comment by ivanalejandro0** [comment]
Same problem here, caps->ctrl works but pause->power doesn't.

**Comment by awattar** [comment]
Same here.

**Comment by smiller171** [comment]
Have you tried using the Karabiner event viewer to see if the pause button is coming in as pause at all? Under Sierra the behavior changed on my keyboard and the OS is reading it as f15 instead of pause.

if I set `"f15" :  "power" it works (mostly)

I say mostly because opt+cmd+power stops working if Karabiner-Elements is running.

**Comment by ivanalejandro0** [comment]
Yes, you're right... the mapping seems to work, what I get for the actual power button or the mapped pause->power is `SysKeyUp` and `SysKeyDown` with code `0x6`.
**But** the shortcut `ctrl`+`shift`+`power` stops working when Karabiner-Elements is running (either on the external keyboard or the internal one), which I'd say is a different issue, right?

**Comment by smiller171** [comment]
@ivanalejandro0 yup. That's covered by #124

**Comment by ivanalejandro0** [comment]
Great! Thanks for pointing it out.
The mapping works for me then. If others having this issue can confirm with the event viewer that the mapping works there as well this can be closed :).
