### ISSUE TITLE
External keyboard frequently loses USB connection

### ISSUE THREAD

**Issue by eurobubba** [tekezo/Karabiner-Elements#791]
Not certain this is related to KE, but it did begin the same day I installed KE and used it to set up a hyper key according to Brett Terpstra's instructions. At first it only seemed to happen after a system sleep, but I just now experienced it while actively working.

OS X version: 10.12.6 beta
Karabiner version: Elements 0.91.4
Your Mac hardware: 2011 13" MacBook Pro
Your keyboard hardware: Microsoft Natural Ergonomic Keyboard 4000 v. 1.0

**Comment by jairbj** [comment]
Hi friend, I have the same problem here. I use a Dell KM632 Wireless Keyboard/Mouse combo.
My OSX is 10.12.5. I tried karabiner elements both 0.90.2 and 0.91.4 and both have the same problem.

Sometimes the mouse stops works and sometimes the keyboard stops and I need to remove and put again my USB dongle.

If I check DMESG I see a lot of HID Activity Tickle.

Without K.E. this problem doesn't happen.
