### ISSUE TITLE
No way to download latest release

### ISSUE THREAD

**Issue by max-arnold** [tekezo/Karabiner-Elements#796]
Last git version is 0.91.4, but the link to binary release https://pqrs.org/latest/karabiner-elements-latest.dmg still points to 0.90.92.

**Comment by apm1467** [comment]
Karabiner-Elements Preferences -> Misc -> Check for beta updates

**Comment by max-arnold** [comment]
Beta updates showed nothing for me, but right now the link in the README seems to be fixed and points to 0.91.5
