### ISSUE TITLE
New Fullsize Apple Magic Keyboard (2017 Wireless) not supported.

### ISSUE THREAD

**Issue by jameskachan** [tekezo/Karabiner-Elements#799]
I get some weirdness when i try using Karabiner Elements with my brand new Apple Fullsize wireless keyboard. The main issue I have noticed is the keyboard shortcut for sleep ⌘ ⌥ ⏏ doesn't work, I think the Eject key conflicts or something…

**Comment by dk0r** [comment]
See issue #46
