### ISSUE TITLE
extension does not loaded properly in 10.13 high sierra

### ISSUE THREAD

**Issue by mko-io** [tekezo/Karabiner-Elements#801]
<img width="637" alt="screen shot 2017-06-30 at 9 14 09 am" src="https://user-images.githubusercontent.com/10137567/27710666-a44385d2-5d74-11e7-979e-55759d5116d0.png">

**Comment by jostyee** [comment]
https://github.com/tekezo/Karabiner-Elements/issues/777

**Comment by mko-io** [comment]
@jostyee thanks for the link, close as duplicate
