### ISSUE TITLE
0.91.5にアップデートしたらstandalone_keysが効かなくなった

### ISSUE THREAD

**Issue by thanks2music** [tekezo/Karabiner-Elements#802]
Karabiner-Elementsをアップデートする前は以下の設定でleft_command/right_commandで英数/日本語の切り替えが出来ていましたが、0.91.5にアップデート後、効かなくなりました。私だけでしょうか？

- macOS Sierra 10.12.5
- Karabiner-Elements 0.91.5

`.config/karabiner/karabiner.json`

```
            "simple_modifications": {
                "left_command": "left_command",
                "right_command": "right_command"
            },
            "standalone_keys": {
                "left_command": "japanese_eisuu",
                "right_command": "japanese_kana"
            },
```

**Comment by ty0521-fss** [comment]
新しいこちらの機能を使うようですよ。
https://github.com/tekezo/Karabiner-Elements/tree/master/usage#how-to-use-complex-modifications
https://pqrs.org/osx/karabiner/complex_modifications/
一番下の『For Japanese （日本語環境向けの設定）』をimportすれば自分の環境では動いています。
それでもダメな場合は『⌘英かな』というアプリが使えるかと思います。

**Comment by thanks2music** [comment]
@ty0521-fss ご回答ありがとうございます、レスポンス遅くなりまして申し訳ありません...！
`⌘英かな` で一旦問題は解決されていますので本IssueはCloseいたします ![:ojigi:]( http://media.emjb.jp/img/pictograms/144866.gif )
