### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by yangwen0228** [tekezo/Karabiner-Elements#804]
It always has a daemon process karabinar-grabber running. Can't remove it. Please help me to delete it!

**Comment by jostyee** [comment]
<img width="744" alt="screen shot 2017-07-02 at 3 19 15 pm" src="https://user-images.githubusercontent.com/88564/27767958-d9e02314-5f39-11e7-82c7-4fc6f4271856.png">

**Comment by yangwen0228** [comment]
sudo '/Library/Application Support/org.pqrs/Karabiner-Elements/uninstall.sh' 
This works! Thank you!
