### ISSUE TITLE
Help getting an older version?

### ISSUE THREAD

**Issue by FatherOfAlways** [tekezo/Karabiner-Elements#806]
Hi.
I had KE v0.91.1 (or something along those lines) installed for a while. Recently, KE prompted me to update to v0.91.5, which I did. Now I'm having issues with my keyboard.
I found my backup of v0.90.92 somewhere and reverted to that for now, however, this version doesn't not support complex modifications (to my knowledge).
Where can I acquire older versions of KE (I don't know how to compile my own - I have no experience in that regard)? I've been searching the web for older versions but am unable to find anything.

**Comment by xdxdy** [comment]
https://github.com/tekezo/Karabiner-Elements/issues/809

**Comment by FatherOfAlways** [comment]
Thank you very much!
