### ISSUE TITLE
C-d in zsh / C-x C-f in Emacs

### ISSUE THREAD

**Issue by akira-okumura** [tekezo/Karabiner-Elements#813]
I use "Change Left_control + D to Forward Delete" with Karabiner-Elements 0.91.5 on Sierra. When I type Ctrl-D in zsh, it is always converted to a tilde (~).

I remember Karabiner had an option "Force change C-d to Forward Delete" but I cannot find an equivalent setting in Karabiner-Elements.

How do I invoke forward delete in zsh when the Emacs mode is used?

---
I have edited title because this problem is more critical in Emacs. As Karabiner-Elements does not have an exclusion list, C-x C-f, for example, is interpreted as C-x ***right*** in Emacs, and therefore I cannot open a file with this common key stroke.

**Comment by apm1467** [comment]
Will this help? https://blog.pilif.me/2004/10/21/delete-key-in-zsh/

`Ctrl-D` ist actually the default shortcut to Forward Delete in macOS. Even if you disable the rule "Change Left_control + D to Forward Delete" in Karabiner-Elements, `Ctrl-D` should still work as Forward Delete. Is my understanding right?

**Comment by akira-okumura** [comment]
Yes, it works. Thanks a lot!

> Is my understanding right?

Basically your are right, but there are some applications that do not accept Cocoa key bindings.

**Comment by akira-okumura** [comment]
Now then I cannot exit from a terminal with C-d when there is no characters in the current prompt. I still think an exclusion list in the Karabiner-Elements side is needed.

**Comment by akira-okumura** [comment]
Now it's been supported in 0.91.6. Thanks a lot, @tekezo !
