### ISSUE TITLE
On my german keyboard the keys for ^° and <> are switched

### ISSUE THREAD

**Issue by bitboxer** [tekezo/Karabiner-Elements#815]
I selected the "ISO" layout and added the "change caps_lock to control if pressed with other keys, to escape if pressed alone". It all works well but two keys are somehow swapped.

Above the tab on my keyboard I have the °^ key and right to the left shift key i have <>, but those are swapped now. Anything I can do to help fixing this?

**Comment by apm1467** [comment]
I do not have a german keyboard to test this, but you may try:

1. Go to "Simple Modifications" in Karabiner-Elements
2. Add two rules to swap the "grave_accent_and_tilde" key and the "non_us_backslash" key

As documented [here](https://github.com/tekezo/Karabiner-Elements/blob/master/usage/README.md#swapping-sectionparagraph--key-on-non-us-keyboards).

**Comment by bitboxer** [comment]
Ah, awesome! Thanks.
