### ISSUE TITLE
Any (speculative even) estimation on arrival of full Karabiner for Sierra?

### ISSUE THREAD

**Issue by zanglebert** [tekezo/Karabiner-Elements#817]
First, let me please say that I'm in no way complaining, or trying to bother the contributors. I'm very, very happy that Karabiner and Karabiner Elements is being worked on.

That said, I'm currently withholding upgrading to OS X Sierra because I very much rely in my workflow on the complex shortcuts of the original Karabiner. In fact, I'm witholding on buying the new MBP because of that :)

So my question basically is:

Is there any educated guess possible when development of Karabiner Elements turns into (full feature) Karabiner for Sierra? Anything like a broad range (months? years?) would be fine, I'm just trying to get an idea of the time frame.

Once more, I hope the question didn't come across as being pushy or disrespectful.

**Comment by carrigmore** [comment]
@zanglebert I would say it take at least more than 1 year for this project to complete. The whole API changed for input service on new Version of OS 10.12. Basically the whole project needs to be rebuild. 
I myself also rely on this quite a lot. You still can buy the new MBP and then downgrade the OS back to 10.11 or 10.10. This is possible and worked really well for me. I myself brought a new Mac mini and it shipped with OS 10.12. I downgraded it to 10.10 with no issues. Just need to run the date command to change the system date to late 2015, before downgrade, or it will complain (some error message like the installation file has been modified or missing) and won't allow you to proceed.

**Comment by zanglebert** [comment]
@carrigmore Thanks for the answer! 

On a related note however, I was wondering if there's a chance that the next major version of OS X will change the API again and will break the new Karabiner.

Thanks as well for the suggestion to downgrade. Right now it seems to be the best option, other than migrating away from OS X, which I'm still reluctant to do.

**Comment by nikitavoloboev** [comment]
If you do decide to migrate from OS X, I am curious is there even anything close to Karabiner out there. Aside from hacking on your own [some keyboard firmware](https://github.com/tmk/tmk_keyboard) itself. 

I mean Karabiner is [genuinely amazing](https://github.com/nikitavoloboev/dotfiles/blob/master/karabiner/private.xml) and I doubt there is anything close that really does keyboard remapping at such great level.

**Comment by EDmitry** [comment]
Isn't Karabiner Elements really close to full functionality right now? Some of the more advanced key remappings are now supported and hopefully allow some of the most critical functionality you were relying on.

**Comment by nikitavoloboev** [comment]
Can I somehow define [this block](https://github.com/nikitavoloboev/dotfiles/blob/master/karabiner/private.xml#L5853) in Karabiner Elements?

**Comment by zanglebert** [comment]
@EDmitry I wasn't aware of that. Last time I asked/checked, shell commands didn't work yet (VK_OPEN_URL_SHELL_ in old Karabiner). These make up a large portion of my commands, less than the actual key bindings.

**Comment by EDmitry** [comment]
I personally use other apps for automation since it seems to be more high-level than keys remapping. Something like Hammerspoon or Keyboard Maestro.

**Comment by zanglebert** [comment]
@EDmitry 

Hm, probably a good idea. Never thought of splitting up the workflow I had set up within Karabiner over several programs. I'll check if my definitions+bindings can be migrated to Karabiner Elements plus one of the programs you mention.

(sorry for the offtopic discussion, by the way)

**Comment by braham-snyder** [comment]
another good OS X program for running shell commands upon key presses is https://github.com/koekeishiya/khd -- I can't fully compare it to Hammerspoon since I haven't yet had a chance to test Hammerspoon, but my understanding is that khd is a bit simpler for shell commands, largely due to its narrow focus on them
