### ISSUE TITLE
karabiner_grabber large CPU consumption on macbook

### ISSUE THREAD

**Issue by unphased** [tekezo/Karabiner-Elements#819]
A few hours ago I rebooted and got an automatic update for Karabiner. I think this issue is related. 

<img width="568" alt="untitled 3" src="https://user-images.githubusercontent.com/1542910/27992215-ab8a7ae6-645c-11e7-950b-ce71d2609093.png">

**Comment by tekezo** [comment]
Is there any error log messages in `Karabiner-Elements Preferences > Log` tab?

**Comment by unphased** [comment]
There has since been another update, and I will monitor for more CPU consumption. So far it has been behaving much better (1%) today.

**Comment by saurik** [comment]
I also have a MacBook, and I'm also seeing weirdly high CPU usage for this process (15-30%). I will additionally report that hitting command-space to bring up spotlight was incredibly slow to work correctly: after hitting it over and over and over again it would eventually sort of start working, but then would stop again; as soon as I quit Karabiner and killed karabiner_grabber, it began working again normally. Before doing that, I went under the Log tab, and I had numerous "no buffer space available" error messages (and that was it: pages and pages of this one message).

"""
[2017-12-25 01:36:31.360] [warning] [console_user_server] local_datagram_client error: No buffer space available
[2017-12-25 01:36:46.459] [warning] [console_user_server] local_datagram_client error: No buffer space available
[2017-12-25 01:36:54.310] [warning] [console_user_server] local_datagram_client error: No buffer space available
[2017-12-25 01:36:56.063] [warning] [console_user_server] local_datagram_client error: No buffer space available
[2017-12-25 01:37:25.959] [warning] [console_user_server] local_datagram_client error: No buffer space available
"""

**Comment by can-I-do** [comment]
I am also having it now...

**Comment by iamtienng** [comment]
Having it now and had to kill the process. What is going on? Lucky for me that I have Via (QMK).

**Comment by kyoz** [comment]
Same here, it cause my mac running hotter than normally. (+10 *C)

**Comment by kakadais** [comment]
@tekezo Do you know why this issue just closed without further information?

**Comment by unphased** [comment]
> @tekezo Do you know why this issue just closed without further information?

Because of stalebot. I recommend making another issue. Also I suggest including information as suggested:

> Is there any error log messages in `Karabiner-Elements Preferences > Log` tab?

**Comment by zhanggang807** [comment]
virtual device are not ready??

**Comment by mrichman** [comment]
Happening to me now too.

**Comment by prodigel** [comment]
Mac mini M2 user here, karabiner_grabber was using 40%, I noticed because the youtube video playback was unusually choppy.

I did recently connect the TV via hdmi to watch a movie, I'd say I'm in the same camp as @switz, would happily provide more feedback on this as it seems to be easily reproducible.
