### ISSUE TITLE
Got my "paste" option disabled

### ISSUE THREAD

**Issue by avaranovich** [tekezo/Karabiner-Elements#820]
I have installed the latest karabiner-elements, and suddenly got the _paste_ disabled. Interestingly enough, _cut/copy_ works. I can't even past with the right mouse click anymore... Tried to kill pboard, no luck. Any pointers?

**Comment by h-nn-ng** [comment]
I'm also having a problem with the paste functionality after updating to 0.91.6 but it only occurs when using [Alfred](https://www.alfredapp.com/) snippets which didn't expand anymore.
