### ISSUE TITLE
Use any key as modifier

### ISSUE THREAD

**Issue by thomasjachmann** [tekezo/Karabiner-Elements#831]
I'm using Karabiner Elements 0.91.7 on macOS 10.12.5 on a MacBookPro13,3 (15" 2016 with touch bar).

I'd like to use the tab key as a modifier key:

* pressing tab alone just triggers a tab
* pressing tab and then pressing another key triggers something different (eg tab-c issues three key presses: t, a and b)

But I can't use the tab key as a modifier key like this (just the manipulator snippet to keep the description short):

```json
"manipulators": [
    {
        "from": {
            "key_code": "c",
            "modifiers": { "mandatory": ["tab"] }
        },
        "to": [{ "key_code": "t" }, { "key_code": "a" }, { "key_code": "b"}],
        "type": "basic"
    }
]
```

* when first pressing tab, the tab key is still passed through
* when pressing c (either in combination with tab or without), the `to` is triggered (entering the text "tab")

It would work by first mapping the tab key to a true modifier key (eg `right_control` which would be a good choice since I physically don't have it on my keyboard) and then using `right_control` instead of `tab` in the mandatory modifiers list above. The problem is: I am already using `right_control` for another key and the other modifier keys are used as well.

I see two solutions for this:
* making the use of standard keys as modifier keys possible
* allowing to define custom virtual named modifier keys just for the use within the karabiner configuration to map standard keys to and then define complex mappings for those virtual modifiers

Any other solutions/workarounds?

**Comment by thomasjachmann** [comment]
It would be even cooler being able to define modifier keys without a specific key they're being pressed with. So instead of defining rules for each of tab-h, tab-j, tab-k, tab-l, tab-c, tab-n, tab-p, ... that all should do the same (just triggering ctrl-b plus the key being pressed with tab), I could define one rule for the tab key and I then could use a placeholder for the key being pressed with tab in the `to` definition.

**Comment by apm1467** [comment]
You can for example check the implementation of the [Virtual Numeric Keypad](https://github.com/pqrs-org/KE-complex_modifications/blob/master/docs/json/numeric_keypad.json) rule in the official rule repository, which uses the left_option + fn combination as a "fake" modifier key.

**Comment by thomasjachmann** [comment]
Thanks for the hint. That might do for some use cases. I'd still like to not hijack other modifiers/modifier combinations, meaning: left_option + fn itself couldn't be used for anything else since it's already got a function by me using it as "fake" modifier key. Using virtual modifier keys (I think that worked in the old Karabiner) would not have this problem.

**Comment by tekezo** [comment]
Use `variable_if` to accomplish the virtual modifiers.
The following example uses `tab_modifier` variable as flag.

```
{
    "manipulators": [
        {
            "from": {
                "key_code": "tab"
            },
            "to": [
                {
                    "set_variable": {
                        "name": "tab_modifier",
                        "value": 1
                    }
                },
                {
                    "key_code": "tab"
                }
            ],
            "to_after_key_up": [
                {
                    "set_variable": {
                        "name": "tab_modifier",
                        "value": 0
                    }
                }
            ],
            "type": "basic"
        },
        {
            "conditions": [
                {
                    "type": "variable_if",
                    "name": "tab_modifier",
                    "value": 1
                }
            ],
            "from": {
                "key_code": "c",
                "modifiers": {
                    "mandatory": [
                        "tab"
                    ]
                }
            },
            "to": [
                {
                    "key_code": "t"
                },
                {
                    "key_code": "a"
                },
                {
                    "key_code": "b"
                }
            ],
            "type": "basic"
        }
    ]
}
```

Note:
I don't plan to support Virtual modifiers which is in old Karabiner.
Please use this variable style.

**Comment by michelkoga** [comment]
Tekezo, you are Kamisama lol

**Comment by thomasjachmann** [comment]
@tekezo That solves everything I tried to accomplish with virtual modifier keys, thank you very much. I didn't know about set_variable and to_after_key_up. I know, everything is growing rapidly at the moment and documentation could be brittle. But is there a simple list of keys that can be used in karabiner.json?

**Comment by apm1467** [comment]
@thomasjachmann https://github.com/tekezo/Karabiner-Elements/blob/master/src/apps/PreferencesWindow/PreferencesWindow/Resources/simple_modifications.json

**Comment by thomasjachmann** [comment]
@apm1467 That was quick, but unfortunately not what I was looking for. :) The use of the word "keys" was ambiguous here. I didn't meant the keys that can be used as key_codes but the keys (as in key value pair) that can be used to build complex modifications, eg to_if_alone, to_after_key_up, etc. Thanks nonetheless.

**Comment by apm1467** [comment]
@thomasjachmann Currently, there are just these three: `to`, `to_if_alone` and `to_after_key_up`.

**Comment by thomasjachmann** [comment]
@apm1467 OK, thanks. And I guess [this](https://github.com/tekezo/Karabiner-Elements/blob/50b48342d1b419aeb8807cffbf3c374314229de9/src/core/grabber/include/manipulator/details/types.hpp#L19) is the list of things I can do inside of them?

**Comment by apm1467** [comment]
@thomasjachmann I think `pointing_button` isn't coming yet. Currently, it's just possible to map to `key_code`, run `shell_command` or `set_variable`.

**Comment by babyking** [comment]
@tekezo  it has a problem in example, when holding tab then press c,  the result is:  tab,'t','a','b',  tab is superfluous!   how to fix it?

**Comment by endrebak** [comment]
I have the same problem as babyking. Using the example, holding tab and pressing a c writes a tab right after the tab is pushed so the result of `<tab>+c` is

```         
      tab
```

**Comment by xcode-manolo** [comment]
Hi @babyking  and @endrebak !!!
That's not a bug.  You only have to erase the

````        ,
               {
                    "key_code": "tab"
                }
````

from the **"to":** section.  And put it into the **"to_if_alone":** section.  The complex modification would look like this:

````{
  "title": "TAB as a POWERFUL MODIFIER LAYER",
  "rules": [
    {
      "description": "TAB as a POWERFUL MODIFIER LAYER",
      "manipulators": [
        {
            "from": {
                "key_code": "tab"
            },
            "to": [
                {
                    "set_variable": {
                        "name": "tab_modifier",
                        "value": 1
                    }
                }
            ],
            "to_after_key_up": [
                {
                    "set_variable": {
                        "name": "tab_modifier",
                        "value": 0
                    }
                }
            ],
            "to_if_alone": [
              {
                "key_code": "tab"
              }
            ],
            "type": "basic"
        },
        {
            "conditions": [
                {
                    "type": "variable_if",
                    "name": "tab_modifier",
                    "value": 1
                }
            ],
            "from": {
                "key_code": "c"
            },
            "to": [
                {
                    "key_code": "t"
                },
                {
                    "key_code": "a"
                },
                {
                    "key_code": "b"
                }
            ],
            "type": "basic"
        }
      ]
    }
  ]
}
````

Have a great day, guys !!!

😉
