### ISSUE TITLE
Mapping Spacebar + hjkl to arrow keys

### ISSUE THREAD

**Issue by prasskaly** [tekezo/Karabiner-Elements#833]
Hi,
I am trying to add a complex modification for a Spacebar + key combo (with the following code). But it fails and the keys become unusable. The become the up/down arrow keys without spacebar also. Am I missing anything ? 
Any help would be appreciated.   
                    {
                        "description": "Test",
                        "manipulators": [
                            {
                                "from": {
                                    "key_code": "j",
                                    "modifiers": {
                                        "mandatory": [ 
                                            "spacebar"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "down_arrow"
                                    }
                                ],

                                "type": "basic"
                            },
							{
                                "from": {
                                    "key_code": "k",
                                    "modifiers": {
                                        "mandatory": [
                                            "spacebar"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "up_arrow"
                                    }
                                ],
                                
                                "type": "basic"
                            } 

Thanks in Advance.

Best Regards,
PK

**Comment by apm1467** [comment]
The spacebar is not a modifier. You can check the implementation of Vi Mode in the official rule repository, which maps S + H/J/K/L as arrow keys.

**Comment by prasskaly** [comment]
Thanks for the reply. The space bar is the longest and centered key that deserves to be a modifier IMO. I was able to get the functionality I wanted by converting the spacebar to Fn key and mapping the keys accordingly.
https://github.com/tekezo/Karabiner-Elements/blob/master/examples/space_ijkl_arrows.example.json
Thanks to ipetepete and everyone in here !

Warm Regards,
PK

**Comment by huangzonghao** [comment]
Mapping `space` to `fn` and then map from there is definitely a great idea. But just wondering why we can't convert spacebar to modifier directly in karabiner? Are there any special reasons preventing us?
