### ISSUE TITLE
Make previous versions available for download

### ISSUE THREAD

**Issue by aristidesfl** [tekezo/Karabiner-Elements#835]
If users install updates and something is not working, there is currently no way to rollback.

**Comment by akira-okumura** [comment]
https://github.com/tekezo/Karabiner-Elements/commits/master/version

**Comment by aristidesfl** [comment]
@akira-okumura I meant the binaries

**Comment by tekezo** [comment]
I added a link to old releases:
https://github.com/tekezo/Karabiner-Elements#old-releases
