### ISSUE TITLE
CMD+OPT+EJECT not working

### ISSUE THREAD

**Issue by LucaMarconato** [tekezo/Karabiner-Elements#840]
I have noticed that CMD+OPT+EJECT key combination (for putting macOS to sleep) does not work anymore, I think the problem (re)appeared some versions ago (I have 0.91.8 and I am using 10.12.4 (16E195). 
About 6 months/1 years ago I remember that the problem was present and that has been fixed.

**Comment by Marx1st** [comment]
The same for CTRL + SHIFT + EJECT for locking the screen (AFAIK this has to be activated in the keychain app, first). This doesn't work any more if Karabiner Elements is running.

**Comment by techFishIO** [comment]
I believe this is due to #46. It is also documented in #89.

Work around: map a key to "eject" (in the media keys section) and use CMD+OPT+KEY to sleep.

**Comment by DennisSchwartz** [comment]
@techFishIO I can't find the "eject" key in the media keys section :/  
Any other tips?

![image](https://user-images.githubusercontent.com/2827690/28885752-e076acf6-77ae-11e7-80f9-70e621d4c37c.png)

**Comment by bluecrab22** [comment]
May be "stale," but I had the issue with Opt-Cmd-Eject (sleep) not working. Re-installed MacOS (I'm not sure that was necessary), and Uninstalled Karabiner using its uninstall feature. Functionality returned. I also tried Shift-Ctl-Eject, which also didn't work. Tested with two different model keyboards to verify. 
MacOS 10.14.4
Karabiner 12.2.0
iMac 21.5", late 2015
Apple Wired Keyboard MB110LL/A
