### ISSUE TITLE
Virtual modifiers

### ISSUE THREAD

**Issue by voodoomsr** [tekezo/Karabiner-Elements#841]
Hi guys, Im looking if I can port my private.xml from old Karabiner to Elements specification to upgrade my mac.
I don't know if the following is feasible with the current implementation

```
<autogen>__KeyToKey__ KeyCode::J , ModifierFlag::MY_HYPER, KeyCode::RawValue::0x27 | ModifierFlag::SHIFT_L</autogen>

<autogen>
	__KeyOverlaidModifier__
	KeyCode::SEMICOLON,
	KeyCode::VK_MODIFIER_MY_HYPER, ModifierFlag::SANDS2,
	KeyCode::SEMICOLON,
</autogen>
```

Basically I use my semicolon as a modifier due that it is extremely ergonomic to use it!!. With that definition I also could use the key alone and works as expected.

I will like to know if that is possible?

**Comment by thomasjachmann** [comment]
This is not a direct duplicate of #831, but having virtual modifiers is also one supposed solution there.
