### ISSUE TITLE
Support remapping Fn+numeric keys to the F keys.

### ISSUE THREAD

**Issue by dluxhu** [tekezo/Karabiner-Elements#847]
When pressing the Fn key plus the number keys (0-9 + '-' and '='), it should map to the Fn keys.

The rationale is that the touchbar Fn keys requires looking at the keyboard, which is annoying.

**Comment by bingocaller** [comment]
@dluxhu I made a [pull request](https://github.com/pqrs-org/KE-complex_modifications/pull/66) for this functionality over on [pqrs-org/KE-complex_modifications](https://github.com/pqrs-org/KE-complex_modifications); let's hope it gets approved! 🙂

In the meantime you could try adding the contents of [`fn_plus_numbers_to_function_keys.json`](https://github.com/pqrs-org/KE-complex_modifications/pull/66/files#diff-b3e8cab45caa5c1442d025fae9f5a60b) to your own `~/.config/karabiner/karabiner.json`-file.

**Comment by dluxhu** [comment]
Awesome, thanks!

**Comment by bingocaller** [comment]
@dluxhu You're welcome! Did it work as expected?

**Comment by dluxhu** [comment]
Just checked, and it does not really work. Event viewer doesn't seem to recognize them either:

eventType:FlagsChanged    code:0x3f       name:fn              flags:Fn                                 misc:
eventType:KeyDown         code:0x12       name:1               flags:Fn                                 misc:
eventType:KeyUp           code:0x12       name:1               flags:Fn                                 misc:
eventType:FlagsChanged    code:0x3f       name:fn              flags:                                   misc:
eventType:FlagsChanged    code:0x3f       name:fn              flags:Fn                                 misc:
eventType:KeyDown         code:0x13       name:2               flags:Fn                                 misc:
eventType:KeyUp           code:0x13       name:2               flags:Fn                                 misc:
eventType:FlagsChanged    code:0x3f       name:fn              flags:                                   misc:
eventType:FlagsChanged    code:0x3f       name:fn              flags:Fn                                 misc:
eventType:KeyDown         code:0x14       name:3               flags:Fn                                 misc:
eventType:KeyUp           code:0x14       name:3               flags:Fn                                 misc:
eventType:FlagsChanged    code:0x3f       name:fn              flags:                                   misc:
eventType:FlagsChanged    code:0x3f       name:fn              flags:Fn                                 misc:
eventType:KeyDown         code:0x15       name:4               flags:Fn                                 misc:
eventType:KeyUp           code:0x15       name:4               flags:Fn                                 misc:
eventType:FlagsChanged    code:0x3f       name:fn              flags:                                   misc:
eventType:FlagsChanged    code:0x3f       name:fn              flags:Fn                                 misc:
eventType:KeyDown         code:0x17       name:5               flags:Fn                                 misc:
eventType:KeyUp           code:0x17       name:5               flags:Fn                                 misc:
eventType:KeyDown         code:0x16       name:6               flags:Fn                                 misc:
eventType:KeyUp           code:0x16       name:6               flags:Fn                                 misc:
eventType:KeyDown         code:0x1a       name:7               flags:Fn                                 misc:
eventType:KeyUp           code:0x1a       name:7               flags:Fn                                 misc:
eventType:KeyDown         code:0x1c       name:8               flags:Fn                                 misc:
eventType:KeyUp           code:0x1c       name:8               flags:Fn                                 misc:
eventType:KeyDown         code:0x19       name:9               flags:Fn                                 misc:
eventType:KeyUp           code:0x19       name:9               flags:Fn                                 misc:
eventType:KeyDown         code:0x1d       name:0               flags:Fn                                 misc:
eventType:KeyUp           code:0x1d       name:0               flags:Fn                                 misc:
eventType:FlagsChanged    code:0x3f       name:fn              flags:                                   misc:

**Comment by bingocaller** [comment]
Oh dang! I'm not able to test it on my machine right now… but let me see if I can't figure out what's going on and I'll get back to you!

**Comment by bingocaller** [comment]
@dluxhu I talked to @kamykaze over on [my PR](https://github.com/pqrs-org/KE-complex_modifications/pull/66). They say it only works if you check the "Use all F1, F2, etc. keys as standard function keys" option under the Function keys tab. Maybe that's the trick?

**Comment by kamykaze** [comment]
actually, from his event viewer log, it doesn't sound like the option i mentioned is the issue. He would have seen some 'display brightness' if the option was unchecked. 

It looks like the remapping rule isn't even there. His log is consistent with me not having any mappings for Fn keys.

@dluxhu , maybe you only imported the json file from @bingocaller  but forgot to "add rule" > "enable" in order to make it active?

**Comment by dluxhu** [comment]
Hi,

I have a 2016 macbook pro, which has a control strip instead of the F keys, that's why it would be great to have this feature.

I don't have the option in the Keyboard settings for "Use all F1, F2, etc. keys as standard function keys".

I think I have the file enabled, see screenshot:

<img width="660" alt="screen shot 2017-08-02 at 9 53 11 am" src="https://user-images.githubusercontent.com/9684787/28863309-b000b9c2-7768-11e7-8a54-f48d6d8ba44c.png">

<img width="896" alt="screen shot 2017-08-02 at 9 51 28 am" src="https://user-images.githubusercontent.com/9684787/28863308-b0006a76-7768-11e7-86f4-2788b62d1d49.png">

[Here](https://pastebin.com/g3XetpWw) is my config file, I hope I pasted it into the right place. I have Karabiner Elements 0.9.12.

**Comment by kamykaze** [comment]
Please check the following options In Karabiner Elements:

![karabiner-elements preferences 2017-08-02 01-46-56](https://user-images.githubusercontent.com/224031/28866373-a47605bc-7727-11e7-8806-9baf5ef97950.png)

![karabiner-elements preferences 2017-08-02 01-47-28](https://user-images.githubusercontent.com/224031/28866397-b2123e84-7727-11e7-987f-877378b24f12.png)

Also, your karabiner.json seems to have two "rules" nested inside. It should only be one. Try this:
https://pastebin.com/GMrdPf9V

**Comment by dluxhu** [comment]
Thanks, @kamykaze  for the fixed json file, it actually works now!

**Comment by dluxhu** [comment]
Actually, by turning on the "Use all F1, F2, ... as standard function keys" feature breaks the control strip (touch bar) on the laptop, but I see there are multiple bugs reported about it already:  #460 , #595, #859 .

**Comment by bingocaller** [comment]
Should we close this issue, then? Seeing as the updated `karabiner.json` works and there are multiple other issues tracking the control strip bug.

**Comment by dluxhu** [comment]
If the pull request is accepted, I guess we can, yes.

**Comment by bingocaller** [comment]
The pull request has been accepted and [the mappings are available to import](https://pqrs.org/osx/karabiner/complex_modifications/#fn_plus_numbers_to_function_keys), so I think we're good to go! 🙂
I think the issue author (or an admin) has to be the one to close the issue; @dluxhu, will you do the honours?

**Comment by dluxhu** [comment]
Sure. 👍 Thanks for fixing!
