### ISSUE TITLE
Reloading complex modifications

### ISSUE THREAD

**Issue by carymrobbins** [tekezo/Karabiner-Elements#848]
In order to reload complex modifications, I have to open up the Karabiner-Elements GUI, remove my rule, then re-add it.  Is there a better way to do this?  Ideally, I'd like to be able to do this from a command line script or a hot key (which may be script + karabiner).

**Comment by ww7** [comment]
Any solutions for this?

**Comment by dyyybek** [comment]
Is there any solution for this?

**Comment by raine** [comment]
Would be useful.

**Comment by carymrobbins** [comment]
Resurrecting as I'm still interested in this.

**Comment by sixpetrov** [comment]
I would really like that feature, it's painful to do any change, but maybe this could help: 
https://github.com/tekezo/Karabiner-Elements/issues/217#issuecomment-250956515

**Comment by svermeulen** [comment]
Just another vote for this feature.  Having to add and remove from the UI every time a change is made to the json is really painful

**Comment by svermeulen** [comment]
I ended up creating [a hammerspoon binding](https://gist.github.com/svermeulen/996213b4c6747c8c20f5a498ca67f932) to automate the reload through the gui.  Super hacky and brittle but still a bit helpful

**Comment by et304383** [comment]
Sure would be nice to have this.

**Comment by ionstormx** [comment]
Upvote. Hoping to see this someday.

**Comment by 24khxn** [comment]
Bumping because I still have interest in this

**Comment by denolfe** [comment]
I ran into this after moving my modifications out of karabiner.json into the complex modifications directory. It would be really great if this were implemented.

Previously, I was performing this snippet in a Makefile to do the reload of karabiner.json:

```sh
launchctl stop org.pqrs.karabiner.karabiner_console_user_server
sleep 0.2
start org.pqrs.karabiner.karabiner_console_user_server
```

It doesn't appear to work for the complex modifications though.

**Comment by wookayin** [comment]
Can we have this reopened, please?

p.s. I personally don't like stalebot keeping non-resolved long-standing issues :D

**Comment by wookayin** [comment]
This worked for me (just kill Karabiner-Elements and launch it again; bring up the window to validate refreshing). Let me note here for somebody who might find this issue by Googling.

```bash
killall Karabiner-Elements; open /Applications/Karabiner-Elements.app
```

I did not have to run launchctl though.

For example, if you are managing it in VCS, you can automate deploying Karabiner configs and reloading them like:

```bash
#!/bin/bash
# Copy karabiner.json if you are managing it in VCS. Locations are YMMV. Note that Karabiner messes up symbolic links.
\cp -f ~/.dotfiles/config/karabiner/karabiner.json ~/.config/karabiner/karabiner.json
killall Karabiner-Elements; open /Applications/Karabiner-Elements.app
```

**Comment by svermeulen** [comment]
@wookayin's suggestion still doesn't work for me

Still hoping one day we'll see a way to do this.  I find it surprising that a tool built for automation would not have a way to automate something as simple as restarting it or reloading config

**Comment by et304383** [comment]
This feature would be greatly appreciated.  It's such a cumbersome way to reload we have to go through today.

**Comment by babygau** [comment]
you all should use GokuRakuJoudo to config karabiner. it's simple and make changes instantly.

**Comment by jsok** [comment]
My solution to this was to:
1. Remove the existing complex modification
2. Add Rule -> pick the one you just removed

A *reload* button next to the modification would make a lot of sense here.

**Comment by kevinjdolan** [comment]
FYI, I was able to get this to work using roughly the following python script (note: this is not exactly the script I ran, so it's not tested, ymmv):

```
def activate_config(MODIFICATION_FILE_PATH, CONFIG_PATH):
    with open(CONFIG_PATH) as f:
        config = json.loads(f.read())

    with open(MODIFICATION_FILE_PATH) as f:
        modifications = json.loads(f.read())
    
    mod_rule_descriptions = [
        rule['description'] 
        for rule 
        in modifications['rules']
    ]

    config_rules = config['profiles'][0]['complex_modifications']
    filtered_rules = [
        rule 
        for rule 
        in config_rules 
        if rule['description'] not in mod_rule_descriptions
    ]
    
    config['profiles'][0]['complex_modifications'] = (filtered_rules + modifications['rules'])
    
    with open(CONFIG_PATH, 'w') as f:
        json.dump(config, f, indent=4)
```

**Comment by asoltesz** [comment]
Workaround: I simply simply just quit Karabiner with the top-menu icon and restart it from the Dock (where I have it pinned while developing the modifications in Sublime)

**Comment by sachasmart** [comment]
I manage Karabiner rules in a `rules.ts` file

I have this npm script (`deploy`), that seems to work well:

```
  "scripts": {
    "build": "tsm rules.ts",
      ...
    "deploy": "npm run build && cp karabiner.json ~/.config/karabiner/karabiner.json && launchctl kickstart -k gui/`id -u`/org.pqrs.karabiner.karabiner_console_user_server"
  }
```

The annoying bit is I use an external keyboard and I have to reselect that keyboard to bind the shortcuts to it in the UI. 

Agreed with everyone else on this thread, a reload config button or command would be super helpful.

**Comment by temp4422** [comment]
Any one click shortcut solutions ?
