### ISSUE TITLE
Vi Mode - typing sh usually triggers left arrow

### ISSUE THREAD

**Issue by techFishIO** [tekezo/Karabiner-Elements#849]
I wanted to check to see if this is a configuration issue, or simply a limitation of the virtual keyboard's performance:

1. I can't use the Vi Mode for `S + H/J/K/L` because typing `sh` (push, dash...) almost always triggers left arrow (the flag isn't removed fast enough)
2. I notice a delay when typing, when I get to the `s` in whatever I'm typing

Wondering if this is a limitation or if I can do anything to troubleshoot/tweak either KE or Mac hardware.

**Comment by apm1467** [comment]
This is a known issue. Currently this is a limitation, but this shall be improved in future KE updates.

Mean while, there is a Vi Mode 1d rule. You can use D instead of S as the trigger key. Since there are not so many dh-, dj-, dk- and dl- words, use D instead of S will reduce the trigger errors.

**Comment by techFishIO** [comment]
@apm1467 thanks, I figured that was the case and am using D for the time being.

**Comment by eyemyth** [comment]
@apm1467 Is there somewhere we can track this issue? It's going to take some real effort on my part to overcome years of S+HJKL and I'd like to switch back to using S instead of D when possible.

**Comment by apm1467** [comment]
@eyemyth You can watch the [GitHub page of the official rule repository](https://github.com/pqrs-org/KE-complex_modifications) to get notified when any of the rules are updated. 

Or just watch [this page](https://github.com/pqrs-org/KE-complex_modifications/pull/1). If the Vi Mode gets better support for the S key, I will post there.

**Comment by apm1467** [comment]
The Vi Mode (rev 5) is available. Now the S key can be used as trigger key perfectly. It requires the newest version of Karabiner-Elements (12.1.0 or later).
