### ISSUE TITLE
What are these keys called, I need to swap places because macOS Sierra doesn't recognize keyboard

### ISSUE THREAD

**Issue by jisuo** [tekezo/Karabiner-Elements#85]
http://imgur.com/a/LE1oW

In the image are the two keys I'm talking about.

Are they some of these:

kHIDUsage_KeyboardInternational1    = 0x87, /\* International1 _/
    kHIDUsage_KeyboardInternational2    = 0x88, /_ International2 _/
    kHIDUsage_KeyboardInternational3    = 0x89, /_ International3 _/
    kHIDUsage_KeyboardInternational4    = 0x8A, /_ International4 _/
    kHIDUsage_KeyboardInternational5    = 0x8B, /_ International5 _/
    kHIDUsage_KeyboardInternational6    = 0x8C, /_ International6 _/
    kHIDUsage_KeyboardInternational7    = 0x8D, /_ International7 _/
    kHIDUsage_KeyboardInternational8    = 0x8E, /_ International8 _/
    kHIDUsage_KeyboardInternational9    = 0x8F, /_ International9 */

**Comment by talha131** [comment]
The top left one is section key. 

https://en.wikipedia.org/wiki/Section_sign
https://github.com/tekezo/Karabiner-Elements/blob/master/examples/change_section_key_to_accent_key.json

**Comment by mafredri** [comment]
I got it working on my European keyboard through looking at US keyboards and some trial-and-error:

```
"grave_accent_and_tilde": "non_us_backslash",
"non_us_backslash": "grave_accent_and_tilde",
```

**Comment by Malgin** [comment]
Yeah, unfortunately this doesn't work for me in russian-based layout. I can't map section-key to tilde, which is frustrating. Is there ideas why is that so? I've got this in carabiner, and it works fine for US-english layout:
<img width="818" alt="screen shot 2017-07-10 at 4 47 43 pm" src="https://user-images.githubusercontent.com/1384973/28021152-8c812030-658f-11e7-9b5b-1ba29a2d41a1.png">
