### ISSUE TITLE
It doesn't function properly with my bluetooth keyboard

### ISSUE THREAD

**Issue by alanlxl** [tekezo/Karabiner-Elements#852]
I'm using a bluetooth 4.0 mechanical keyboard, and I found all the modification through karabiner-elements didn't function properly. e.g., I mapped shift + esc to `~`, but when I type shift + esc ,I only get a `escape`. 

Additional information 1: this keyboard support both wired mode and wireless mode. The modification works well if it is used with the cable...

Additional information 2: the Karabiner-Eventviewer can catch the input signal when I use the keyboard in wireless mode.

The band of the keyboard is Keywalker, and the model is IFD-68

**Comment by nicolalamacchia** [comment]
Same here with a Drevo Calibur (works both wired and with bluetooth 4.0). I mapped caps lock to esc and esc to grave accent/tilde.

As an additional note I noticed that when I map caps lock to esc in the system tool and use the keyboard with bluetooth it stops working too (tested this before installing Karabiner Elements).

Maybe it's a system-level problem?

I'm using macOS Sierra 10.12.5.
