### ISSUE TITLE
Option + LeftArrow/RightArrow Bindings

### ISSUE THREAD

**Issue by carymrobbins** [tekezo/Karabiner-Elements#853]
Trying to bind <kbd>Option</kbd><kbd>←</kbd> to <kbd>Command</kbd><kbd>←</kbd> but it doesn't seem to work.  For instance, when I'm in a web browser (e.g. Chrome, FireFox), I'd expect <kbd>Option</kbd><kbd>←</kbd> to send me to the previous page as <kbd>Command</kbd><kbd>←</kbd> does, but it still seems to function as the original <kbd>Option</kbd><kbd>←</kbd> (for instance, I'm still able to move between words in a text field using it.

[Here's my config for reference](https://github.com/carymrobbins/dotfiles/blob/2a1ed402058b5900f4f0d38aa2501bad9ef40792/.config/karabiner/assets/complex_modifications/linux.json#L755-L810), in case I'm doing something wrong.

**Comment by apm1467** [comment]
In the `to` part, you must specify whether you want to map to `left_command` or `right_command`. Only write `command` won't work. This is also true for other modifier keys, e.g. `option` and `control`.

**Comment by carymrobbins** [comment]
That's odd, I have [lots of other bindings](https://github.com/carymrobbins/dotfiles/blob/2a1ed402058b5900f4f0d38aa2501bad9ef40792/.config/karabiner/assets/complex_modifications/linux.json#L7-L26) that work fine which use `command` in the `to` section.  I can confirm that it works now when targeting `right_command`.  Is this a limitation when using `option` in the `from` ?

**Comment by apm1467** [comment]
Logically speaking, it is possible to write `left_command` or `right_command` or simply `command` (which means both left and right) in the `from` section. But in the `to` section, only write `command` doesn't make sense. So it is actually odd to me that this works in some of your bindings. This may only be accidental.

It is suggested to always specify `left_command` or `right_command` in `to` sections. All example config files also do this.
