### ISSUE TITLE
to_if_alone and documentation

### ISSUE THREAD

**Issue by Pithikos** [tekezo/Karabiner-Elements#855]
Great work on this. I appreciate it as someone working on Ubuntu and Mac in parallel.

My only problem is that I can't find any tutorials or documentation that actually explain how to create the complex shortcuts, but only small snippets of code.

As an example I try to have the `command` key to launch mission controll when pressed on its own. Initially I thought that using `to_if_alone` would work but it doesn't. How do I find out what the statements available are and what they are supposed to do? I would guess for example that `from_if_alone` would exist but it doesn't. So although the tool seems really powerful and good, it becomes unusable for someone like me who wants slightly advanced control.

Cheers!

**Comment by pirj** [comment]
Save this as `.config/Karabiner/assets/complex_modifications/capslock_to_esc_and_command.json`
```
{
  "title": "Change Command",
  "rules": [
    {
      "description": "Keep Command as is if pressed with other keys, to Mission Control if pressed alone.",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "left_command",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "left_command"
            }
          ],
          "to_if_alone": [
            {
              "key_code": "f4"
            }
          ]
        }
      ]
    }
  ]
}
```

And it will be available to you. Bonus points if you update the documentation.
