### ISSUE TITLE
Fn to Expand Control Strip stops working

### ISSUE THREAD

**Issue by jason0342** [tekezo/Karabiner-Elements#859]
After updating to macOS 10.12.6, the function stops working when Karabiner-Elements is on. Nothing happens to the control strip when Fn is pressed down. It works again after quitting the app.
I've tried to remove all the modifications but the problem remains. 

Macbook Pro 2016 with touchbar 13.3"
macOS 10.12.6
Karabiner-Elements 0.91.9

**Comment by diegobit** [comment]
Same issue (same MacBook and Karabiner)
Disabling modifications for "Apple Internal Keyboard / ..." makes it work, but it makes Karabiner useless.

**Comment by cmconnelly** [comment]
+1
