### ISSUE TITLE
How to remap Control+C unless running the Terminal app.

### ISSUE THREAD

**Issue by alvaro1728** [tekezo/Karabiner-Elements#860]
Hi,

For complex modifications, I've mapped Control+C like this:

`        {
					"from": {
						"key_code": "c",
            "modifiers": { "mandatory": ["left_control"], "optional": ["any"] }
          },
					"to": [{
							"key_code": "c",
							"modifiers": ["left_command"]
					}],
					"type": "basic"
				}`

Is there a way to add an exception for when I'm inside the Terminal app?

Thanks,
Alvaro

**Comment by jvinding** [comment]
You should be able to do this:

```
{
  "from": {
    "key_code": "c",
    "modifiers": {
      "mandatory": [
        "left_control"
      ],
      "optional": [
        "any"
      ]
    }
  },
  "to": [
    {
      "key_code": "c",
      "modifiers": [
        "left_command"
      ]
    }
  ],
  "conditions": [
    {
      "type": "frontmost_application_unless",
      "bundle_identifiers": [
        "^com\\.apple\\.Terminal$"
      ]
    }
  ],
  "type": "basic"
}
```

**Comment by alvaro1728** [comment]
@jvinding Works great, thanks!
