### ISSUE TITLE
Share mappings between profiles

### ISSUE THREAD

**Issue by mohitleo9** [tekezo/Karabiner-Elements#861]
Hey,
First of all thanks a ton!! for this awesome piece of software. One of the problems that I am having is that I have two profiles (one for external keyboard and other for internal) and they share a lot of common mapping and so there is a lot of repeated code. I am wondering if there is a way to share config between profiles?

**Comment by starsy** [comment]
@mohitleo9 maybe you don't need two profiles and switching over manually, check this fork: https://github.com/starsy/Karabiner-Elements which allows you config mappings for different devices within a single profile, although it doesn't solve your sharing config issue.

**Comment by wincent** [comment]
See: https://github.com/tekezo/Karabiner-Elements/commit/fd90e595e1d8c1cf972e6694b85be294b773954c

**Comment by shinichy** [comment]
+1
I want this feature. I want to use different IDEs by each profile.

**Comment by wincent** [comment]
In addition to the `device_if`, `device_unless` config that I linked to above, you can also generate your config from a scripting language. There are a bunch of examples in https://github.com/pqrs-org/KE-complex_modifications and inspired by that I made a script to produce my own config here: https://github.com/wincent/wincent/blob/c287fd76d35adae9dcf8c1ebf7121df6e679a74f/roles/dotfiles/templates/.config/karabiner/karabiner.js (that's a 339-line script that replaces/generates a 1,073-line config).
