### ISSUE TITLE
What is the best way to change profile?

### ISSUE THREAD

**Issue by lambdalisue** [tekezo/Karabiner-Elements#863]
I'm using Karabiner-Elements 0.91.9 on macSierra

When I change profile, the key-bindings won't change until I restart (there is no "restart" command so I have to quit and start manually) Karabiner-Elements. Is this normal or am I missing some feature?

**Comment by starsy** [comment]
@lambdalisue the best way to change profile is not to change profile, check this fork: https://github.com/starsy/Karabiner-Elements which allows you config mappings for different devices within a single profile

**Comment by lambdalisue** [comment]
Well unfortunately I'm rely on the complex_modifications which the fork does not support yet.

**Comment by wincent** [comment]
Looks like the fork is no longer needed: https://github.com/tekezo/Karabiner-Elements/commit/fd90e595e1d8c1cf972e6694b85be294b773954c

**Comment by lambdalisue** [comment]
Unfortunately I noticed that `complex_modifications` doesn't work for me but https://github.com/tekezo/Karabiner-Elements/pull/247 does.

Anyway, it seems the master has the feature so I close this
