### ISSUE TITLE
Detecting Mouse scroll

### ISSUE THREAD

**Issue by prasskaly** [tekezo/Karabiner-Elements#866]
Hi,
How to detect Mouse scroll with Karabiner elements? 
I would like to have Mouse scroll Up + command key to send "command + +" key combination and Mouse scroll down + Command key  to send "command + -" to the system. 

Regards,
PK

**Comment by Ashark** [comment]
I want exactly the same. It would be convenient for both chrome and final cut.

**Comment by Ashark** [comment]
I am still interested in a solution, do not close this issue.
