### ISSUE TITLE
Remap MacBook Pro TouchID/Power button

### ISSUE THREAD

**Issue by prohtex** [tekezo/Karabiner-Elements#871]
I'm looking to remap the MacBook Pro "combo TouchID/Power button". From what I can tell remapping the power button was working in older versions of Karabiner. In K-E, when I run EventViewer and press the power button, nothing shows up. Does this mean power button support has not yet been added, or am I missing something?

**Comment by eytanhanig** [comment]
This used to work in Karabiner-Elements but stopped functioning a few months back.

**Comment by prohtex** [comment]
I'm still wondering about this

**Comment by prohtex** [comment]
Is there a code for this for Karabiner.json?

**Comment by prohtex** [comment]
Still wondering

**Comment by surjikal** [comment]
Wondering as well!
