### ISSUE TITLE
Backslash on Norwegian keyboard

### ISSUE THREAD

**Issue by tork73** [tekezo/Karabiner-Elements#873]
I want to change the key where the equal sign is on us-keyboard (´on a Norwegian keyboard) to backslash \ (which is option + Shift + 7) on my keyboard. In EventViewer it is right_oprion+right_shift+7). 

In Karabiner I did this with the following code: 

```
<?xml version="1.0"?>
<root>
	<item>
	    <name>For å få \ </name>
	    <identifier>private.swap_backslah</identifier>
	    <autogen>__KeyToKey__
		KeyCode::EQUAL,
		KeyCode::KEY_7, | ModifierFlag::SHIFT_L | ModifierFlag::OPTION_R
	    </autogen>
	</item>

</root>

```
 

![2017-07-25_19-11-00](https://user-images.githubusercontent.com/18615180/28584553-71f3fbc2-716d-11e7-8fcb-a4c8b7dd9847.png)

**Comment by kimborgen** [comment]
For people coming from google, you can import this now:
https://ke-complex-modifications.pqrs.org/#norwegian_programming
