### ISSUE TITLE
Conditional simple or complex modification based on keyboard type?

### ISSUE THREAD

**Issue by alvaro1728** [tekezo/Karabiner-Elements#874]
Hi,

I'd like to swap the Control and Fn keys, but only when I'm typing on the laptop's keyboard not my external keyboard.  So I've created two profiles ("Laptop Keyboard" and "External Keyboard").  The Laptop profile has this simple modification:

>             "simple_modifications": {
>                 "fn": "left_control",
>                 "left_control": "fn"
>             }

Ideally I would prefer not to have to keep switching profiles back and forth and to just have Karabiner Elements apply the modification based on what keyboard I'm on.  Is there a way?

Thanks,
Alvaro

**Comment by starsy** [comment]
@alvaro1728 https://github.com/starsy/Karabiner-Elements

**Comment by alvaro1728** [comment]
The latest version of Karabiner (0.91.13) allows the choosing of a target device for Simple Mods.  Thanks!
