### ISSUE TITLE
PC-style key mappings

### ISSUE THREAD

**Issue by tjahjono** [tekezo/Karabiner-Elements#875]
The old Karabiner had an entire section for PC mappings. Is there a way to use the complex modification feature to replicate some of those features, such as mapping _ctrl+home_ and _ctrl+end_ to _cmd+home_ and _cmd+end_?

**Comment by goldsphere** [comment]
Yes! looking for these options...

![old karabiner prefs](https://user-images.githubusercontent.com/10703145/29083022-f5a2cfa6-7c2c-11e7-911a-cdd52e0775ac.jpeg)
