### ISSUE TITLE
__BlockUntilKeyUp__ functionality

### ISSUE THREAD

**Issue by wincent** [tekezo/Karabiner-Elements#877]
I'd like to implement a "SpaceFN" layer (ie. while space is held down, activate another layer).

Here's a small example showing how to map Space+J to "left":

```
{
    "description": "Space + J = LEFT",
    "from": {
        "key_code": "j",
        "modifiers": {
            "mandatory": [
                "fn"
            ]
        }
    },
    "to": [
        {
            "key_code": "left_arrow"
        }
    ],
    "type": "basic"
},
{
    "description": "Space as fn",
    "from": {
        "key_code": "spacebar"
    },
    "to": [
        {
            "key_code": "fn"
        }
    ],
    "to_if_alone": [
        {
            "key_code": "spacebar"
        }
    ],
    "type": "basic"
},
```

The problem is, space is pressed very often during normal typing, so it is all too easy for this kind of set-up to produce unwanted "fn" presses instead of spacebar presses when typing fast.

With the old Karabiner, `__BlockUntilKeyUp__` took care of this quite nicely, or at least, I think it did if I understand its purpose. It basically meant, I think, that it wouldn't fire one of the layer events unless Space were pressed before another key, and released after the other key:

    # This triggers a layer event (ie. LEFT)
    Space down ---> J down ---> J up ---> Space up

    # This normal roll-over does not trigger a layer event, just SPACE then J:
    Space down ---> J down ---> Space up ---> J up

Here's the full version of the old Karabiner config: https://github.com/wincent/wincent/blob/c250a81d235bef574d3a7cf2f2bb7a585bcd9686/roles/keyboard/files/spacefn.xml

**Comment by michelkoga** [comment]
I would go like this:

**Comment by michelkoga** [comment]
```
{
            "description": "Second Layer",
            "manipulators": [
                {
                    "from": {
                        "key_code": "spacebar"
                    },
                    "to": [
                        {
                            "set_variable": {
                                "name": "another_layer",
                                "value": 1
                            }
                        }
                    ],
                    "to_if_alone": [
                        {
                            "key_code": "spacebar"
                        }
                    ],
                    "to_after_key_up": [
                        {
                            "set_variable": {
                                "name": "another_layer",
                                "value": 0
                            }
                        }
                    ],
                    "type": "basic"
                },
                {
                    "conditions": [
                        {
                            "type": "variable_if",
                            "name": "another_layer",
                            "value": 1
                        }
                    ],
                    "from": {
                        "key_code": "j",
                        "modifiers": {
                            "mandatory": [
                                "fn"
                            ]
                        }
                    },
                    "to": [
                        {
                            "key_code": "left_arrow"
                        }
                    ],
                    "type": "basic"
                },
                {
                    "conditions": ...
```

**Comment by wincent** [comment]
@michelkoga: That's much better. Thanks.

However, I still think I need an equivalent for `__BlockUntilKeyUp__`. Without this, configurations like the above don't handle rollover well. I am going to keep playing around and see if I can come up with something in terms of variables and `to_if_alone_timeout_milliseconds` perhaps, but ultimately I think I need something else.

**Comment by wincent** [comment]
The new `to_if_held_down` property allows us to get pretty close to what we would need here, but it is not quite there; given [this config](https://github.com/wincent/wincent/blob/dd9388bda62360520860cc350d4ff6904ee4af87/roles/dotfiles/files/.config/karabiner/karabiner.json#L17-L51):

```
                        "description": "SpaceFN layer",
                        "manipulators": [
                            {
                                "from": {
                                    "key_code": "spacebar",
                                    "modifiers": {
                                        "optional": [
                                            "any"
                                        ]
                                    }
                                },
                                "to_if_held_down": [
                                    {
                                        "set_variable": {
                                            "name": "SpaceFN",
                                            "value": 1
                                        }
                                    }
                                ],
                                "to_after_key_up": [
                                    {
                                        "set_variable": {
                                            "name": "SpaceFN",
                                            "value": 0
                                        }
                                    }
                                ],
                                "to": [
                                  {
                                    "key_code": "spacebar",
                                    "repeat":  false
                                  }
                                ],
                                "type": "basic"
                            },
```

We can prevent the SpaceFN layer from kicking in until the key is pressed for a while, and we can still enjoy normal rollover while typing fast. The only gotcha is that initial press of the space bar causes an immediate key-down/key-up to be sent, even if you end up just pressing and holding (ie. your intention is to enter SpaceFN mode). This is very close to being usable now, but I think we still need something like `__BlockUntilKeyUp__`.

**Comment by kbdluv** [comment]
I'm looking for something very similar: using the spacebar as **normal space** when short pressed, and as **left_control** when held down _and_ pressed with something else. (Mainly for use with Spacemacs.)

I tried many variations of configurations so far and no matter what I do I always end up tripping up on this "rollover" that you mention and issuing a **left_control+letter** when what I type fast and wish for a **SPC+letter**.

I think **__BlockUntilKeyUp__** would help, and I would also like to advocate for @jonathankau's [solution here](https://github.com/tekezo/Karabiner-Elements/issues/8#issuecomment-329637288) which would be to have a **configurable overlap/rollover threshold**. In his words, "If spacebar is only held for less than that threshold, then it will **always** be treated as a spacebar press (Even if I press another key during that initial spacebar press)." 

I'm voicing my support for both things and will open a separate issue for the latter. Many thanks for Karabiner Elements!

**Comment by ljosa** [comment]
Let me throw in here the set if heuristics that I'm using in my Linux implementation (in the Xorg input driver): http://www.ljosa.com/~ljosa/software/spacefn-xorg/

I found that simple timeouts were not enough, and that I needed to buffer other keypresses (not just space) until their intention became clear.

**Comment by tomislav** [comment]
Would the new "simultaneous" feature help with this?

https://pqrs.org/osx/karabiner/json.html#simultaneous

**Comment by wincent** [comment]
I don't think so.

**Comment by tekezo** [comment]
Yes, `simultaneous` is not the replacement of `__BlockUntilKeyUp__` yet.

**Comment by wincent** [comment]
Seems like it is now though. 😄

For example:

https://github.com/wincent/wincent/commit/8fe03134e1c5201264ed2f1e5373c8720e2019f8

**Comment by tekezo** [comment]
I updated karabiner.json Reference Manual about `simultaneous_options`. 
https://pqrs.org/osx/karabiner/json.html#simultaneous-options

**Comment by ljosa** [comment]
Thanks, @tekezo, the docs contained the crucial information that I was missing: "`simultaneous_options` is available only in the beta versions." Once I upgraded from the released 11.6.0 to the beta 11.6.6, I was able to get @wincent's config (https://github.com/wincent/wincent/commit/8fe03134e1c5201264ed2f1e5373c8720e2019f8) to work.

Once issue that I haven't been able to resolve is how to disable autorepeat for spacebar. (SpaceFn relies on this because it uses space as a modifier when held. Spacebar+b, which emits a space, should continue to autorepeat.) A manipulator like the following is effective at preventing autorepeat, but also stops @wincent's SpaceFn manipulators from working:

```json
                            {
                                "from": {
                                    "key_code": "spacebar",
                                    "modifiers": {
                                        "optional": [
                                            "any"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "spacebar",
                                        "repeat": false
                                    }
                                ],
                                "type": "basic"
                            }
```

Do you (or anyone) have a solution for that? Thanks!

**Comment by olets** [comment]
@ljosa are you still having this problem with the latest version? It's working as desired for me

**Comment by svenjacobs** [comment]
The SpaceFN configuration listed [here](https://pqrs.org/osx/karabiner/complex_modifications/) should be updated with the [fix](https://github.com/tekezo/Karabiner-Elements/issues/877#issuecomment-369083251) by @wincent.

**Comment by nimms** [comment]
I'd second sven's request.  It would have saved me a fair few hours of banging my head against the wall!

**Comment by yzhuang** [comment]
Should this issue be reopened? Seems like it is only resolved for @wincent, but everyone else is still waiting for a fix before spacefn is usable :)

**Comment by ljosa** [comment]
@yzhuang: SpaceFN works well for me with this config: https://gist.github.com/ljosa/df7a08953a050f8b49997840095d132d

**Comment by wincent** [comment]
It's definitely usable. You just need to configure it correctly. I am on phone now so I and post full example config but [this is the script](https://github.com/wincent/wincent/blob/master/roles/dotfiles/support/karabiner.js) I use to generate it.

**Comment by yzhuang** [comment]
Yup.  I was speaking for the people waiting for the complex modification repository to be updated, and advocating for a longer term fix.

For myself, I took the same route ljosa did --- I took the fix in https://github.com/wincent/wincent/commit/8fe03134e1c5201264ed2f1e5373c8720e2019f8 and modified it by hand to suite my needs.  It was quite tedious, and now I am on a forked version of the spacefn config. 

Will give the javascript generation script a try tonight.  Thanks for helping!

**Comment by onetom** [comment]
This SpaceFn thing is the only reason I'm trying out Karabiner Elements and the version I've downloaded from https://pqrs.org/osx/karabiner/complex_modifications/ has no effect; my spacebar works the same way as before.

I've also tried the _Change caps_lock to control if pressed with other keys, to escape if pressed alone._ mod. That didn't work either first, even after an upgrade to the latest (12.7.0) version.

After a reinstall, at least the capslock->ctrl/esc works, but spacefn still does not :(
I will look at the links in the last 3 comments; but I wanted to indicate that there is 1 more person how cares about this :)

(I bought a [Minidox](https://falba.tech/customize-your-keyboard/customize-your-minidox/) and soldered together my own [Troy Fletcher's Signum 3.0](http://troyfletcher.net/keyboard_sales.html), but I'm curious if I can implement at least these 2 basic layout enhancement ideas without custom keyboard firmwares for my colleagues at the company I'm working for currently)

**Comment by onetom** [comment]
After checking out @ljosa 's `karabiner.json`, I've just realised it starts with a _SpaceFn layer_ rule, which is required for the rest of the config to work.

The published SpaceFN configuration also has a similar rule, called _SpaceFN: Space enables SpaceFN mode (see: https://geekhack.org/index.php?topic=51069.0)_, which I've have not enabled, because I have not understood its relevance, but it actually works.

I have to say though, it's rather annoying that space only gets registered on release and I did not expect this side effect. I understand there is no way around it, but it's still sad... :)

Thanks everyone for their useful comments; great script @wincent !

**Comment by onetom** [comment]
After trying to use both solutions (the official one and ljosa's) I finally understood the problems you were discussing here.

The official version misbehaves during quick typing because it interprets a space-down/k-down/space-up/k-up sequence as down arrow, but at least it doesn't repeat space when held long without pressing any other key.

The ljosa version takes into account the release sequence of keys, but repeats space.

Can I turn off the space repeat somehow with a recent Karabiner-Elements version (12.7.0) without having rollover issues?

**Comment by wincent** [comment]
I already linked a working config above that suffers from none of the problems you described.
