### ISSUE TITLE
Feature Request: ANY key to set_variable

### ISSUE THREAD

**Issue by kamykaze** [tekezo/Karabiner-Elements#879]
In the complex modifications repo, some of us use the following pattern:

Hold down a TRIGGER KEY to set a variable (eg: Vi mode)
press some other keys for special function (eg: HJKL to arrow keys)
Release the TRIGGER KEY to unset the variable

While this works great, it limits the TRIGGER KEY to be defined by the author of the json file.

It would be nice if we can have a way to selecting any key (like in Simple Modifications) and make it toggle a variable.

Not sure how difficult it would be to implement, but I think it would make the complex modifications more user friendly.

**Comment by starsy** [comment]
@kamykaze you can modify the config file directly, which is under ~/.config/karabiner.json
