### ISSUE TITLE
Can't recognize alfred as com.runningwithcrayons.Alfred-3

### ISSUE THREAD

**Issue by yqrashawn** [tekezo/Karabiner-Elements#882]
So that  the frontmost condition doesn't work for alfred.

**Comment by tekezo** [comment]
It's a limitation of macOS.

You can recognize alfred by open alfred from shell_command (`open -a 'Alfred 3.app'`) instead of hot key.

**Comment by ptillemans** [comment]
@tekezo How do you mean 'recognize alfred by open ...' . How can this be used to create the condition to suppress a modification. The issue I have is that when I enable hold=Ctrl tap=Return on the return key, then Alfred shows the app option dialog instead of launching the app.

**Comment by yqrashawn** [comment]
@ptillemans I believe the limitation means app can't recognize application's hud panel.
