### ISSUE TITLE
Volume keys not working on Logitech K380

### ISSUE THREAD

**Issue by danielverdugo** [tekezo/Karabiner-Elements#883]
![screen shot 2017-07-30 at 00 40 59](https://user-images.githubusercontent.com/14822596/28748406-cf23ab26-74bf-11e7-9a95-5a68b4255509.png)
![screen shot 2017-07-30 at 00 42 05](https://user-images.githubusercontent.com/14822596/28748413-ee5f0c92-74bf-11e7-9b6a-4a2dedb96922.png)

Functions are assigned to keys, however they don't work.

**Comment by danielverdugo** [comment]
Magically, it's working now (after update).

**Comment by danielverdugo** [comment]
Volume keys are not working again. And EventViewer doesn't show any events when press them.

**Comment by aronasorman** [comment]
Can verify. It only happens when I have the Karabiner app open. When I quit the app, volume keys work again. I'm using a Logitech K800.

**Comment by sic-f** [comment]
Same here. Not working as well with a Logitech K380.

**Comment by sic-f** [comment]
As of Sept 12, 2017 after the update, this volume keys are working now (K380)
