### ISSUE TITLE
Complex Modifications - Dvorak layout - 0 mapped to 9

### ISSUE THREAD

**Issue by SquaredCircles** [tekezo/Karabiner-Elements#888]
STR

1. Open Karabiner-Elements
2. Click Complex Modifications
3. Click Add Rule
4. Click Import more rules from the Internet
5. Import rule called "Remap keys to use Dvorak keyboard layout" and enable in Karabiner-Elements
6. Open a text editor and try typing the number 890.

Expected: the string 890 should be typed.
Actual: the string 899 is typed.

**Comment by kamykaze** [comment]
Thanks for catching that. 

I created the mapping for Dvorak, but I don't actually use the layout so didn't notice it. I've pushed a fix.

Please reimport the mapping.

PS: Any issues related to complex modifications can be reported in the complex modifications repo: https://github.com/pqrs-org/KE-complex_modifications
