### ISSUE TITLE
Multi-key repeat problem

### ISSUE THREAD

**Issue by rueberger** [tekezo/Karabiner-Elements#889]
I map shift_r-> esc (meta for emacs). The other week I accidentally deleted some of karabiner settings and after my best attempt to reconstruct them my multi-key repeat behavior has changed.

Previously when I held <shift_r + n> the entire multikey was repeated to emacs and it scrolled my window nicely. Now it scrolls one step and then starts printing 'n'. 

Apologies if this is a duplicate, but I couldn't find anything with a quick google and look through what I hoped to be relevant options in karabiner. Thanks in advance for your help!

**Comment by tekezo** [comment]
The repeat behavior has been changed due to the software architecture changes between Karabiner and Karabiner-Elements.
Karabiner-Elements repeats only the last key event.

Please consider to use option+n (or another modifier which is recognized as meta in emacs) instead of esc+n.
