### ISSUE TITLE
Mixed unnecessary flag by touching Touchpad while pushing with modifier key

### ISSUE THREAD

**Issue by nobeans** [tekezo/Karabiner-Elements#891]
```
        {
            "from": {
                "key_code": "t",
                "modifiers": {
                    "mandatory": [
                        "option"
                    ]
                }
            },
            "to": [
                {
                    "key_code": "page_down"
                }
            ],
            "type": "basic"
        }
```

When you push `option+t`, key down/up event of `page_down` only with `fn` flag occurs expectedly (I confirmed by Karabiner-EventViewer.)
But if you touch a touchpad while you're pushing `option+t`, **`Opt`** flag also is on.

<img width="399" alt="option-t" src="https://user-images.githubusercontent.com/18579/28815509-91273300-76dc-11e7-9912-568fd73cb51a.png">

Why does `Opt` flag become on?

After you changes the modifier key of `from` to `control` like this,

```
        {
            "from": {
                "key_code": "t",
                "modifiers": {
                    "mandatory": [
                        "control"  // <----- changed from "option"
                    ]
                }
            },
            "to": [
                {
                    "key_code": "page_down"
                }
            ],
            "type": "basic"
        }
```

**`Ctrl`** flags is on.

<img width="329" alt="ctrl-t" src="https://user-images.githubusercontent.com/18579/28815508-91272f22-76dc-11e7-8367-08a17653df7f.png">

**Comment by nobeans** [comment]
The issue occurs on Macbook Pro 2016 Touchbar 15-inch.

However, when I've confirmed on Macbook Pro Late 2013 15-inch, it wasn't reproduced.

**Comment by tksys** [comment]
try the v11.0.3.
It may have been fixed.

**Comment by nobeans** [comment]
I've made sure at latest v11.1.0. It works well so far.
