### ISSUE TITLE
Cursor jumps with emacs keybindings sometimes

### ISSUE THREAD

**Issue by ky0on** [tekezo/Karabiner-Elements#893]
Cursor jumps to the end of line when keep pressing Control+f.
![ke](https://user-images.githubusercontent.com/3929986/28825389-f15a99e6-7700-11e7-8c99-067939026449.gif)

I'm using
- Karabiner-Elements 0.91.12 (with configuration from [Emacs key bindings (rev 6)](https://pqrs.org/osx/karabiner/complex_modifications/))
- macOS Sierra 10.12.5

**Comment by ky0on** [comment]
Merged to #932

**Comment by tksys** [comment]
try the v11.0.3.
It may have been fixed.
