### ISSUE TITLE
Complex rule import fails silently

### ISSUE THREAD

**Issue by pedrospdc** [tekezo/Karabiner-Elements#895]
I'm trying to write some custom complex rules for my setup. When trying to import them Karabiner says "Rules imported successfully"  but then they never show up.

My rules *seem*  to be valid as they go through the program validation and parsing (the rule description shows up properly). I tried to manually copy them to ~/.config/karabiner/assets/complex_modifications and they still don't show up.

Here's a recording of the issue: ![complexbug](https://user-images.githubusercontent.com/1450630/28870625-45352fa6-7781-11e7-8f28-9555ccf04f48.gif)

Here's my Gist: https://gist.github.com/pedrospdc/4b994594258d83055a815bbdb7a87cdc
I'm currently running 0.91.12. I tried with the stable version and it had the same effect.

**Comment by jvinding** [comment]
Remove the comma (`,`) at the end of line 44

**Comment by bingocaller** [comment]
The comma is (probably) the reason why the import fails, but it would be nice to know why it fails silently.

**Comment by jpurnell** [comment]
I have a similar issue, laid out in this gist…any idea why this fails silently?

[https://gist.github.com/jpurnell/3c3147f945b980bbb527a2f844df0be5](https://gist.github.com/jpurnell/3c3147f945b980bbb527a2f844df0be5)

**Comment by pedrospdc** [comment]
@jpurnell run your config through this validator and it gives you the error: 
https://jsonlint.com/

**Comment by 1ak31sha** [comment]
i am experiencing the same thing. i only import rules from webbrowser. this is a fresh install on a loaner computer - mac pro 2017. let me know what other info to provide. i used these same rules no issue on previous mac pro 2017
