### ISSUE TITLE
Notification Center "key" missing

### ISSUE THREAD

**Issue by jeffhatz** [tekezo/Karabiner-Elements#899]
I'm trying to mat F4 to open Notification Center, but the "key" is missing so I can't. I have it set in System Preferences, but that doesn't do anything. In Karabiner, I tried setting F4 to be vk_none so the SysPref setting will open Notification Center, but that didn't do anything.

Can a notification_center item please be added to the "Media controls"?

**Comment by Fironet** [comment]
A workaround I've found is to set a hotkey for 'Show Notification Center' in the System Preferences>Keyboard>Shortcuts, then map the desired first-layer function key to it.

Eg: Set 'Show Notification Center' to `F4` then in Karabiner>Function Keys set `F4` to `F4`.

**Comment by Fironet** [comment]
On the one hand I can see that this repo has a ton of created issues which I suppose is the reason for the 'stale' bot, but the process of auto closing issues just due to lack of further activity (comments?) runs counter to how most recommendations I've seen about issue reporting, that is, to post relevant replies and not bump issues with +1s and such. Also lack of activity doesn't necessarily mean lack of a relevant submission or feature request.

Perhaps a way of mitigating the number of issues created would be to create a user support forum? As browsing though some of the pages here various issues are just questions, while some are duplicates of a common request (eg: how to map a button to an app that isn't currently supported, similar to this issue's request).

**Comment by iamtodor** [comment]
also wondering why there is no such option as `notification center`. the issue also relates to https://github.com/pqrs-org/Karabiner-Elements/issues/2044
it's stale for no reason. 
could you please take a look here? @tekezo @josephmilla @talha131 
<img width="858" alt="image" src="https://user-images.githubusercontent.com/12586108/179490138-1c04c089-de2c-4801-aa2f-e961ed569c5c.png">

**Comment by 4volodin** [comment]
{
                        "description": "right option x2 => f11 show notification centre",
                        "manipulators": [
                            {
                                "conditions": [
                                    {
                                        "name": "right_option pressed",
                                        "type": "variable_if",
                                        "value": 1
                                    }
                                ],
                                "from": {
                                    "key_code": "right_option",
                                    "modifiers": {
                                        "optional": ["any"]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "f11"
                                    }
                                ],
                                "type": "basic"
                            },
                            {
                                "from": {
                                    "key_code": "right_option",
                                    "modifiers": {
                                        "optional": ["any"]
                                    }
                                },
                                "to": [
                                    {
                                        "set_variable": {
                                            "name": "right_option pressed",
                                            "value": 1
                                        }
                                    },
                                    {
                                        "key_code": "right_option"
                                    }
                                ],
                                "to_delayed_action": {
                                    "to_if_canceled": [
                                        {
                                            "set_variable": {
                                                "name": "right_option pressed",
                                                "value": 0
                                            }
                                        }
                                    ],
                                    "to_if_invoked": [
                                        {
                                            "set_variable": {
                                                "name": "right_option pressed",
                                                "value": 0
                                            }
                                        }
                                    ]
                                },
                                "type": "basic"
                            }
                        ]
                    },

and then assign f11 to  show notification centre in System Preferences - Keyboard - Missions Control
