### ISSUE TITLE
option/command 'Modifier Keys...' configuration ignored

### ISSUE THREAD

**Issue by sheigel** [tekezo/Karabiner-Elements#9]
I have a Razer Blackwidow keyboard that has a windows keyboard layout. For it I have configured from the 'Modifier Keys...' section of the keyboard settings to have the 'option' and 'command' keys switched.
When Karabiner-Elements is active this configuration is disregarded. This didn't happen for the old Karabiner.

**Comment by mkleehammer** [comment]
I noticed this with Caps Lock and Control swapped.  

Also, it persisted after I closed Elements also - I had to unload the extension completely (I forget which), which surprised me.

**Comment by novuscy** [comment]
Same here.

I swapped CMD and OPT keys on a external keyboard, when I hit the CMD key, it shows Opt and Cmd flags at the same time in the Karabiner EventViewer.

**Comment by tekezo** [comment]
We cannot avoid this issue in the new Karabiner-Elements architecture.
Please modify all modifiers in Karabiner-Elements.

**Comment by gillesruppert** [comment]
@tekezo I am using the laptop keyboard at home and a mechanical keyboard with PC layout at work. Is there a way of automatically switching configs depending on the keyboard that is used?

**Comment by hubez** [comment]
+1 @gillesruppert

I use a PC keyboard at a desk, and then the laptop keyboard while mobile, so I am hoping Karabiner-Elements will be able to recognize which keyboard I'm using because I can't get them to align for the alt and cmd keys without constantly editing the Karbiner-Elements config file whenever I switch.

**Comment by gillesruppert** [comment]
For what's it's worth, I have 2 different `karabiner.json` files and have an Alfred trigger that runs a bash script that swaps them automatically. You could also just have this on your desktop and double-click or integrate with launchd.
```
#! /bin/bash
mv ~/.karabiner.d/configuration/karabiner.json ~/.karabiner.d/karabiner.json_temp
mv ~/.karabiner.d/karabiner.json ~/.karabiner.d/configuration/karabiner.json
mv ~/.karabiner.d/karabiner.json_temp ~/.karabiner.d/karabiner.json

killall karabiner_console_user_server
say "Keyboard swapped"
```

**Comment by PiotrCzapla** [comment]
it is somehow related to the issue that the "change keyboard type" does not work anymore after starting karabiner-elements: 
#90

**Comment by yacoob** [comment]
For anyone arriving here for a relatively common cmd/option swap, here's the relevant bit:

```json
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "left_option": "left_command",
                "right_option": "right_command",
                "left_command": "left_option",
                "right_command": "right_option"
            }
        }
    ]
}
```

**Comment by bugeats** [comment]
Is there a way to scope the configuration to a particular hardware keyboard? Can this be done with the existing "profiles" structure? 

I too use an external PC keyboard that needs a different config from the internal keyboard.

**Comment by dansomething** [comment]
@bugeats You might want to check out the karabiner-profile-switch project. It has been working great for me.
see: https://github.com/nomaed/karabiner-profile-switch

And there might be a way to automate the switch with something like ControlPane, but I haven't tried it yet.
See: http://www.controlplaneapp.com/

**Comment by purge** [comment]
I use ControlPane to automate my switch - just a shell script that `cp -f
external_keyboard.json karabiner.json` or `cp -f internal_keyboard.json
karabiner.json` when it passes the USB hardware check for keyboard.

**Comment by TonyCr46** [comment]
I'm having this problem 2 1/2 years after the last post. Has anybody found a fix?

**Comment by tophee** [comment]
I used to have my option- and command-keys switched in MacOS settings but now I switched back to default. However, when I activate Karabiner, it switches them back even though I don't have a single modification enabled. In my mind, Karabiner shouldn't do anything when there is no modification. What am I missing? (And how do I disable this invisible modification?)

**Comment by NN---** [comment]
Karabiner should handle this. Current situation is either using the correct keys in internal and external keyboards but without Karabiner, or use Karabiner and swap mode everytime you use different keyboard.

**Comment by tekezo** [comment]
@NN--- You can choose the target device.

![target device](https://karabiner-elements.pqrs.org/docs/manual/configuration/configure-simple-modifications/images/karabiner-elements-simple-modifications-1@2x.png)

https://karabiner-elements.pqrs.org/docs/manual/configuration/configure-simple-modifications/
