### ISSUE TITLE
Karabiner-Elements breaks international keyboard and OS X keyboard type detection

### ISSUE THREAD

**Issue by notagit** [tekezo/Karabiner-Elements#90]
After running Karabiner-Elements my non_us_backslash key is doing wrong symbols and can't figure out how to fix it (if at all possible). Estonian keyboard. It should do < > | symbols.

Also with Karabiner-Elements running I can't make OS X detect my keyboard type in keyboard settings.

**Comment by ejoebstl** [comment]
I just wanted to file the same report, except for german layout. 

The "change keyboard type" dialogue does no longer recognise an external keyboard as external, so you will never be able to detect the correct keyboard type, leading to a broken layout. 

Also, changes to the modifier keys done in the keyboard settings do not work. 

I'd change the keys using Karabiner-Elements, but I have no way of knowing which key codes the keys "^" and "<" are.

**Comment by pyrmont** [comment]
I'm on a Japanese keyboard and suffering a similar issue. It wasn't occurring for me when I initially downloaded Karabiner-Elements yesterday so I wonder if this is a bug introduced in the a recent update.

The issue specifically is that the keyboard is functioning as a stock U.S. layout. So, for example, the ampersand (@), which on a Japanese keyboard sits immediately to the right of the P-key, is instead the shift-alternate of the 2-key.

As not all the punctuation key codes are [defined in the `types.hpp` file](https://github.com/tekezo/Karabiner-Elements/blob/master/src/share/types.hpp#L189-L381), it's not possible to fix this by reassigning all the keys manually.

**Comment by tsabat** [comment]
keyboard type detection broken for me, too.  

Also when using a MS keyboard and you've remapped alt and command (to handle the windows key) via the Keyboard preferences pane, that remapping is dropped.

**Comment by ejoebstl** [comment]
@tsabat Is it by chance the MS Sculpt ergonomic keyboard?

**Comment by tsabat** [comment]
Nope, the Natural Ergonomic Keyboard 4000, but the same problem exists for
the Kinesis Freestyle 2 that I just switched to.

**Comment by notagit** [comment]
still broken in 0.90.40 :/ have to roll back to el capitan

**Comment by szkrd** [comment]
Same here with Hungarian. I'd like to switch "í" with "0", but this is not possible with the simple modifications afaik.

**Comment by ds-clearago** [comment]
Not quite sure why this issue is closed, since imho the bug is still open. But I could also temporarily fix this issue's main symptom on my external DE apple keyboard with a simple modification switching the grave_accent_and_tilde and non_us_backlash keys with each other as suggested by 0x6368 in https://github.com/tekezo/Karabiner-Elements/issues/252

**Comment by idleherb** [comment]
This issue is still open in 14.4.0, workaround as described above fixes the issue for me though.

**Comment by pascal-kuschkowitz** [comment]
I still face the same issue.
I configured and loaded a custom keyboard with <>| next to `left shift`. Karabiner breaks these.
