### ISSUE TITLE
0x72 not working as fn-key

### ISSUE THREAD

**Issue by delook** [tekezo/Karabiner-Elements#900]
I tried to assign fn key functionality to key 0x72 ("help" says Karabiner Event Viewer), but it does not work for my wasd ISO 124 keyboard on macOS Sierra 10.12.6 (can't use f-keys as F1-F12 while pressing fn/help).
`"simple_modifications": {"help": "fn"}`
Use all F1, F2, etc. as standard keys is not activated.
Thank you for any help!

**Comment by danaliv** [comment]
Changing 0x72 to anything doesn't seem to work. I tried to assign it to `volume_increment` but the event viewer still records it as `help`. (I'm also using a WASD keyboard.)

**Comment by bencart** [comment]
Had this problem too, use "insert" instead of "help" on the simple mapping which actually maps to 0x72.

**Comment by danaliv** [comment]
Sure enough, that does the trick. Thanks @bencart!
