### ISSUE TITLE
Complex mapping for Meta key functionality

### ISSUE THREAD

**Issue by jammi** [tekezo/Karabiner-Elements#901]
I'd like to know how to implement a meta key (for Terminal and X11) like the one in the old Karabiner. Specifically, I want the physical left control key to produce esc + other key / other key combo strokes (except when modifier keys are presesd alone) for as long as it's held down. If possible, only to be active in certain apps, like Terminal, and have some alternative function in "normal" apps.

**Comment by jammi** [comment]
Is it stale though? I did some clumsy replication of it with a lot of conditionals, but haven't followed up on newer features.

**Comment by hsribei** [comment]
I'm also trying to figure out how to do this, as https://github.com/jwilm/alacritty/issues/62 hasn't been solved yet.
