### ISSUE TITLE
Modifier flag changed too early after release

### ISSUE THREAD

**Issue by nschum** [tekezo/Karabiner-Elements#903]
Using the Emacs Key Bindings rule, the modifier flag is sometimes (randomly) changed too early, leading to a incorrect KeyUp event.

For example: Before each of these screenshots I've pressed Ctrl+N (pressing Ctrl, pressing N, releasing N, releasing Ctrl).

as expected:
![screen shot 2017-08-03 at 21 25 39](https://user-images.githubusercontent.com/81999/28939740-9fe80114-7892-11e7-834e-71fabc985f6c.png)

incorrect:
![screen shot 2017-08-03 at 21 25 13](https://user-images.githubusercontent.com/81999/28939733-9ba4544a-7892-11e7-80b7-79fbca5e0287.png)

**Comment by tksys** [comment]
try the v11.0.3.
It may have been fixed.
