### ISSUE TITLE
Lost karabiner.json

### ISSUE THREAD

**Issue by simo2409** [tekezo/Karabiner-Elements#908]
I just updated both OSX (to 10.12.6) and karabiner elements (to 0.91.12) and I I noticed modifications didn't work anymore.
In karabiner's preferences I saw everything empty (as I was just installed karabiner for the first time), no modifications, no profiles, etc.

After recovering old karabiner.json from a backup it seems working without problem, no idea why it happened

Just let you know

**Comment by YayC** [comment]
I just updated to 11.6.0, and it over-wrote my previous karabiner.json (with custom complex modifications)
