### ISSUE TITLE
How to add Complex Mods?

### ISSUE THREAD

**Issue by F1LT3R** [tekezo/Karabiner-Elements#911]
How can I add a complex mod from a JSON file on my Desktop? (OS X)

I can't figure this out...

- Looked in the docs
- Look in here on Github.
- Could not find anything in the app.
- I tried to add a button on a web page to load the JSON file from a Github Gist, it still would not work. `Unsupported URL`

**Comment by ktaragorn** [comment]
@F1LT3R Take a look at this project. https://github.com/pqrs-org/KE-complex_modifications If your json is correctly formatted, you can use the method suggested there for "Local testing"

**Comment by F1LT3R** [comment]
Thanks @ktaragorn I will check this out.

**Comment by F1LT3R** [comment]
This worked perfectly, thanks @ktaragorn !
