### ISSUE TITLE
$HOME on Non-Root Volume Produces Invalid User Error and Config Load Failure

### ISSUE THREAD

**Issue by Nostrilomo** [tekezo/Karabiner-Elements#912]
If the user's home directory is on a non-root volume (macOS 10.12.6), then root cannot read the metadata on $HOME/.config/karabiner/karabiner.json, and so a console message is logged that the configuration is from an invalid user.  Here is what the owner looks like when listed as root:

    # ls -alh karabiner.json
    -rw-r--r-- 1 _unknown _unknown 2.1K Aug 10 18:11 karabiner.json

This causes the configuration not to be loaded.  When running the same config as a user on the same machine, but with $HOME on the root volume, the config loads fine.  Here's how the owner looks from root for that config file:

    # ls -alh karabiner.json
    -rw-r--r-- 1 admin staff 1.8K Aug 10 18:29 karabiner.json

The workaround I have found is to install the config as global from the root-home user.

**Comment by tekezo** [comment]
You have to enable owner ship to the external volume.
https://apple.stackexchange.com/questions/53215/change-ignore-ownership-on-this-volume-from-the-command-line-for-mac-os-x-volu

**Comment by Nostrilomo** [comment]
That seemed to do the trick.  I also needed to chown the files to myself.  Thank you very much for the tip.
