### ISSUE TITLE
SteelSeries 6GV2 fn key not detected

### ISSUE THREAD

**Issue by wassimseif** [tekezo/Karabiner-Elements#913]
Hello Everyone 
I have the SteelSeries 6gv2 I would like to use it on a mac. Everything went great except when I would try to map the `fn` key to left alt. 
![screen shot 2017-08-11 at 7 39 58 am](https://user-images.githubusercontent.com/7282773/29201603-59bea054-7e68-11e7-9728-97281fff3cb7.png)
Karabiner event viewer doesn't even detect this key pressed. I know It's working so it's not a hardware problem. When I try to map the `fn` key to another key, this doesn't affect anything. Is there a way I could do this?

**Comment by michelkoga** [comment]
I believe your fn key manipulates the keys inside the keyboard, therefore can't be detected by any software.

**Comment by wassimseif** [comment]
Ahh okay so its a hardware thing
