### ISSUE TITLE
A keyboard called RK61 does not recognize the fn key

### ISSUE THREAD

**Issue by isongwei** [tekezo/Karabiner-Elements#917]
A keyboard called RK61 does not recognize the fn key

**Comment by sandy1108** [comment]
the same

**Comment by carlsmith** [comment]
Many keyboards handle their function keys internally, modifying what happens when other keys are pressed. In that case, the OS has no way of knowing when the function key is pressed.

**Comment by isongwei** [comment]
OK , Thank you for your reply

**Comment by sandy1108** [comment]
Maybe You are Right, carlsmith.  It seems like that the RK61 function key is handled internally by RK61 Keyboard.
