### ISSUE TITLE
Change Key Number?

### ISSUE THREAD

**Issue by mhulse** [tekezo/Karabiner-Elements#919]
In Karabiner, I used this option to improve my Blender/laptop experience:

![](https://user-images.githubusercontent.com/218624/29349916-168c933e-8211-11e7-9ad3-3312eda531e6.png)

Just curious how to emulate this setting in Karabiner-Elements?

Thanks!

**Comment by mhulse** [comment]
So, looking to emulate:

1. Fn+1, Fn+2, ...... Fn+9, Fn+0 to KeyPad Numbers
1. Fn+Symbols (.+-=/) to KeyPad Symbols
1. Fn+Shift+Delete to KeyPad Clear

Is this possible with Karabiner Elements? If it is possible, I don't mind doing legwork to figure it out. Mostly just curious if it's even doable.

This feature was sooooo useful (when I used the original Karabiner) when working with Blender on a Mac laptop.

**Comment by jvinding** [comment]
look at #127

**Comment by mhulse** [comment]
> look at #127

Doh! Thanks! I totally missed that.

You rock @jvinding, thanks!
