### ISSUE TITLE
Keyboard stops working completely, need to quit to get it working again.

### ISSUE THREAD

**Issue by sixcircuit** [tekezo/Karabiner-Elements#922]
I have a bluetooth keyboard for my laptop, if I get out of range of the bluetooth, it stops working obviously but the built in keyboard on my laptop stops working as well. This didn't use to be the case. I can quit Karabiner-Elements and my built in keyboard starts working again, or I can turn off bluetooth, which also fixes the issue. It's not a show stopper, but it might indicate an underlying problem. I'm running 0.91.13.

Thanks for the great software!

I keep getting this in the log:

IOHIDDeviceSetValue error -536870184 for Magic Keyboard (device_id:24) @ IOReturn krbn::human_interface_device::set_caps_lock_led_state(krbn::led_state)_block_invoke
[2017-08-16 11:12:49.902] [info] [grabber] Magic Keyboard (device_id:24) is grabbed
[2017-08-16 11:12:54.903] [error] [grabber] IOHIDDeviceSetValue error -536870184 for Magic Keyboard (device_id:24) @ IOReturn krbn::human_interface_device::set_caps_lock_led_state(krbn::led_state)_block_invoke

**Comment by caglar10ur** [comment]
Seen in #619
