### ISSUE TITLE
Mouse click please?

### ISSUE THREAD

**Issue by sargentpilcher** [tekezo/Karabiner-Elements#924]
Hello all, I really love this app karabiner, and it has helped me so much! I recently upgraded to Sierra, and now lost the functionality I had with karabiner. The setup that helps me FLY on the Mac, is changing my right command button to a left mouse click, and my right option key to a right mouse click. Karabiner elements though it seems does not support mouse click functionality at the moment. I'm sure others would appreciate this feature as well. I know you guys are hard at work, so I'll be grateful when it does finally get released! Keep up the great work!

**Comment by mullikine** [comment]
This is the only reason I use karabiner too. Holding out for this feature.
Right command button => left click
Right option button => right click

**Comment by sargentpilcher** [comment]
Lol that’s EXACTLY what I use it for! I feel like I can fly on a laptop with that setup. Kindred computer spirits lol.

**Comment by petonic** [comment]
It's not so tough if you use something like BetterTouchTool in concert with Karabiner. Try that, if you haven't.  It's like a couple of bucks.

**Comment by incandescentman** [comment]
This worked for me:

                            "from": {
                                "key_code": "insert"
                            },
                            "to": {
                                "pointing_button": "button1"
                            }

**Comment by mullikine** [comment]
Thank you incandescentman!
Just to spread the gospel, this is what worked for me!
/Users/username/.config/karabiner/karabiner.json
`{
    "global": {
        "check_for_updates_on_startup": true,
        "show_in_menu_bar": true,
        "show_profile_name_in_menu_bar": false
    },
    "profiles": [
        {
            "simple_modifications": [
            {
                "from": {
                    "key_code": "right_option"
                },
                "to": {
                    "pointing_button": "button2"
                }
            },
            {
                "from": {
                    "key_code": "right_command"
                },
                "to": {
                    "pointing_button": "button1"
                }
            },`

**Comment by uveexed** [comment]
where do i  type this code to get my 5 button to left click?

**Comment by uveexed** [comment]
anyone?

**Comment by tekezo** [comment]
You can do it in Simple Modifications.
https://pqrs.org/osx/karabiner/help.html#mouse-button

**Comment by jarrettyeo** [comment]
> "pointing_button": "button2"

Just wanted to leave a note that `button2` as suggested by @mullikine right clicks where your mouse pointer is at.

If you are looking to open a context menu at where your text cursor is (just like on Windows), you need to remap to <kbd>shift</kbd> + <kbd>f10</kbd> instead, for example:

```json
"from": {
    "key_code": "right_option"
},
"to": [
    {
        "key_code": "f10",
        "modifiers": [
            "left_shift"
        ]
    }
],
```

**Comment by michal-michalak** [comment]
@jarrettyeo

Could you elaborate on that? ⬆️ It doesn't work for me. Which app were you testing on that karabiner modification?
