### ISSUE TITLE
list of key codes and modifiers

### ISSUE THREAD

**Issue by talarari** [tekezo/Karabiner-Elements#925]
is there a list of all possible keycodes and modifiers somewhere? i looked and couldnt find it anywhere.

thanks

**Comment by michelkoga** [comment]
[
    {
        "category": "Modifier keys"
    },
    {
        "name": "caps_lock"
    },
    {
        "name": "left_control"
    },
    {
        "name": "left_shift"
    },
    {
        "name": "left_option"
    },
    {
        "name": "left_command"
    },
    {
        "name": "right_control"
    },
    {
        "name": "right_shift"
    },
    {
        "name": "right_option"
    },
    {
        "name": "right_command"
    },
    {
        "name": "fn"
    },
    {
        "category": "Controls and symbols"
    },
    {
        "name": "return_or_enter"
    },
    {
        "name": "escape"
    },
    {
        "name": "delete_or_backspace"
    },
    {
        "name": "delete_forward"
    },
    {
        "name": "tab"
    },
    {
        "name": "spacebar"
    },
    {
        "name": "hyphen",
        "label": "hyphen (-)"
    },
    {
        "name": "equal_sign",
        "label": "equal_sign (=)"
    },
    {
        "name": "open_bracket",
        "label": "open_bracket ["
    },
    {
        "name": "close_bracket",
        "label": "close_bracket ]"
    },
    {
        "name": "backslash",
        "label": "backslash (\\)"
    },
    {
        "name": "non_us_pound"
    },
    {
        "name": "semicolon",
        "label": "semicolon (;)"
    },
    {
        "name": "quote",
        "label": "quote (')"
    },
    {
        "name": "grave_accent_and_tilde",
        "label": "grave_accent_and_tilde (`)"
    },
    {
        "name": "comma",
        "label": "comma (,)"
    },
    {
        "name": "period",
        "label": "period (.)"
    },
    {
        "name": "slash",
        "label": "slash (/)"
    },
    {
        "name": "non_us_backslash"
    },
    {
        "category": "Arrow keys"
    },
    {
        "name": "up_arrow"
    },
    {
        "name": "down_arrow"
    },
    {
        "name": "left_arrow"
    },
    {
        "name": "right_arrow"
    },
    {
        "name": "page_up"
    },
    {
        "name": "page_down"
    },
    {
        "name": "home"
    },
    {
        "name": "end"
    },
    {
        "category": "Letter keys"
    },
    {
        "name": "a"
    },
    {
        "name": "b"
    },
    {
        "name": "c"
    },
    {
        "name": "d"
    },
    {
        "name": "e"
    },
    {
        "name": "f"
    },
    {
        "name": "g"
    },
    {
        "name": "h"
    },
    {
        "name": "i"
    },
    {
        "name": "j"
    },
    {
        "name": "k"
    },
    {
        "name": "l"
    },
    {
        "name": "m"
    },
    {
        "name": "n"
    },
    {
        "name": "o"
    },
    {
        "name": "p"
    },
    {
        "name": "q"
    },
    {
        "name": "r"
    },
    {
        "name": "s"
    },
    {
        "name": "t"
    },
    {
        "name": "u"
    },
    {
        "name": "v"
    },
    {
        "name": "w"
    },
    {
        "name": "x"
    },
    {
        "name": "y"
    },
    {
        "name": "z"
    },
    {
        "category": "Number keys"
    },
    {
        "name": "1"
    },
    {
        "name": "2"
    },
    {
        "name": "3"
    },
    {
        "name": "4"
    },
    {
        "name": "5"
    },
    {
        "name": "6"
    },
    {
        "name": "7"
    },
    {
        "name": "8"
    },
    {
        "name": "9"
    },
    {
        "name": "0"
    },
    {
        "category": "Function keys"
    },
    {
        "name": "f1"
    },
    {
        "name": "f2"
    },
    {
        "name": "f3"
    },
    {
        "name": "f4"
    },
    {
        "name": "f5"
    },
    {
        "name": "f6"
    },
    {
        "name": "f7"
    },
    {
        "name": "f8"
    },
    {
        "name": "f9"
    },
    {
        "name": "f10"
    },
    {
        "name": "f11"
    },
    {
        "name": "f12"
    },
    {
        "name": "f13"
    },
    {
        "name": "f14"
    },
    {
        "name": "f15"
    },
    {
        "name": "f16"
    },
    {
        "name": "f17"
    },
    {
        "name": "f18"
    },
    {
        "name": "f19"
    },
    {
        "name": "f20"
    },
    {
        "name": "f21",
        "not_to": true
    },
    {
        "name": "f22",
        "not_to": true
    },
    {
        "name": "f23",
        "not_to": true
    },
    {
        "name": "f24",
        "not_to": true
    },
    {
        "category": "Media controls"
    },
    {
        "name": "display_brightness_decrement",
        "not_from": true
    },
    {
        "name": "display_brightness_increment",
        "not_from": true
    },
    {
        "name": "mission_control",
        "not_from": true
    },
    {
        "name": "launchpad",
        "not_from": true
    },
    {
        "name": "dashboard",
        "not_from": true
    },
    {
        "name": "illumination_decrement",
        "not_from": true
    },
    {
        "name": "illumination_increment",
        "not_from": true
    },
    {
        "name": "rewind",
        "not_from": true
    },
    {
        "name": "play_or_pause",
        "not_from": true
    },
    {
        "name": "fastforward",
        "not_from": true
    },
    {
        "name": "mute"
    },
    {
        "name": "volume_decrement"
    },
    {
        "name": "volume_increment"
    },
    {
        "name": "eject",
        "not_from": true
    },
    {
        "name": "apple_display_brightness_decrement",
        "not_from": true
    },
    {
        "name": "apple_display_brightness_increment",
        "not_from": true
    },
    {
        "name": "apple_top_case_display_brightness_decrement",
        "not_from": true
    },
    {
        "name": "apple_top_case_display_brightness_increment",
        "not_from": true
    },
    {
        "category": "Keypad keys"
    },
    {
        "name": "keypad_num_lock"
    },
    {
        "name": "keypad_slash"
    },
    {
        "name": "keypad_asterisk"
    },
    {
        "name": "keypad_hyphen"
    },
    {
        "name": "keypad_plus"
    },
    {
        "name": "keypad_enter"
    },
    {
        "name": "keypad_1"
    },
    {
        "name": "keypad_2"
    },
    {
        "name": "keypad_3"
    },
    {
        "name": "keypad_4"
    },
    {
        "name": "keypad_5"
    },
    {
        "name": "keypad_6"
    },
    {
        "name": "keypad_7"
    },
    {
        "name": "keypad_8"
    },
    {
        "name": "keypad_9"
    },
    {
        "name": "keypad_0"
    },
    {
        "name": "keypad_period"
    },
    {
        "name": "keypad_equal_sign"
    },
    {
        "name": "keypad_comma"
    },
    {
        "category": "Virtual Keys"
    },
    {
        "name": "vk_none",
        "label": "vk_none (disable this key)",
        "not_from": true
    },
    {
        "category": "Keys in pc keyboards"
    },
    {
        "name": "print_screen"
    },
    {
        "name": "scroll_lock"
    },
    {
        "name": "pause"
    },
    {
        "name": "insert"
    },
    {
        "name": "application"
    },
    {
        "name": "help"
    },
    {
        "name": "power"
    },
    {
        "name": "execute",
        "not_to": true
    },
    {
        "name": "menu",
        "not_to": true
    },
    {
        "name": "select",
        "not_to": true
    },
    {
        "name": "stop",
        "not_to": true
    },
    {
        "name": "again",
        "not_to": true
    },
    {
        "name": "undo",
        "not_to": true
    },
    {
        "name": "cut",
        "not_to": true
    },
    {
        "name": "copy",
        "not_to": true
    },
    {
        "name": "paste",
        "not_to": true
    },
    {
        "name": "find",
        "not_to": true
    },
    {
        "category": "International keys"
    },
    {
        "name": "international1"
    },
    {
        "name": "international2",
        "not_to": true
    },
    {
        "name": "international3"
    },
    {
        "name": "international4",
        "not_to": true
    },
    {
        "name": "international5",
        "not_to": true
    },
    {
        "name": "international6",
        "not_to": true
    },
    {
        "name": "international7",
        "not_to": true
    },
    {
        "name": "international8",
        "not_to": true
    },
    {
        "name": "international9",
        "not_to": true
    },
    {
        "name": "lang1"
    },
    {
        "name": "lang2"
    },
    {
        "name": "lang3",
        "not_to": true
    },
    {
        "name": "lang4",
        "not_to": true
    },
    {
        "name": "lang5",
        "not_to": true
    },
    {
        "name": "lang6",
        "not_to": true
    },
    {
        "name": "lang7",
        "not_to": true
    },
    {
        "name": "lang8",
        "not_to": true
    },
    {
        "name": "lang9",
        "not_to": true
    },
    {
        "category": "Japanese"
    },
    {
        "name": "japanese_eisuu",
        "label": "英数キー"
    },
    {
        "name": "japanese_kana",
        "label": "かなキー"
    },
    {
        "name": "japanese_pc_nfer",
        "label": "PCキーボードの無変換キー",
        "not_to": true
    },
    {
        "name": "japanese_pc_xfer",
        "label": "PCキーボードの変換キー",
        "not_to": true
    },
    {
        "name": "japanese_pc_katakana",
        "label": "PCキーボードのかなキー",
        "not_to": true
    },
    {
        "category": "Others"
    },
    {
        "name": "keypad_equal_sign_as400",
        "not_to": true
    },
    {
        "name": "locking_caps_lock",
        "not_to": true
    },
    {
        "name": "locking_num_lock",
        "not_to": true
    },
    {
        "name": "locking_scroll_lock",
        "not_to": true
    },
    {
        "name": "alternate_erase",
        "not_to": true
    },
    {
        "name": "sys_req_or_attention",
        "not_to": true
    },
    {
        "name": "cancel",
        "not_to": true
    },
    {
        "name": "clear",
        "not_to": true
    },
    {
        "name": "prior",
        "not_to": true
    },
    {
        "name": "return",
        "label": "rarely used return (HID usage 0x9e)",
        "not_to": true
    },
    {
        "name": "separator",
        "not_to": true
    },
    {
        "name": "out",
        "not_to": true
    },
    {
        "name": "oper",
        "not_to": true
    },
    {
        "name": "clear_or_again",
        "not_to": true
    },
    {
        "name": "cr_sel_or_props",
        "not_to": true
    },
    {
        "name": "ex_sel",
        "not_to": true
    },
    {
        "name": "left_alt",
        "label": "left_alt (equal to `left_option`)"
    },
    {
        "name": "left_gui",
        "label": "left_gui (equal to `left_command`)"
    },
    {
        "name": "right_alt",
        "label": "right_alt (equal to `right_option`)"
    },
    {
        "name": "right_gui",
        "label": "right_gui (equal to `right_command`)"
    },
    {
        "name": "vk_consumer_brightness_down",
        "label": "vk_consumer_brightness_down (equal to `display_brightness_decrement`)",
        "not_from": true
    },
    {
        "name": "vk_consumer_brightness_up",
        "label": "vk_consumer_brightness_up (equal to `display_brightness_increment`)",
        "not_from": true
    },
    {
        "name": "vk_mission_control",
        "label": "vk_mission_control (equal to `mission_control`)",
        "not_from": true
    },
    {
        "name": "vk_launchpad",
        "label": "vk_launchpad (equal to `launchpad`)",
        "not_from": true
    },
    {
        "name": "vk_dashboard",
        "label": "vk_dashboard (equal to `dashboard`)",
        "not_from": true
    },
    {
        "name": "vk_consumer_illumination_down",
        "label": "vk_consumer_illumination_down (equal to `illumination_decrement`)",
        "not_from": true
    },
    {
        "name": "vk_consumer_illumination_up",
        "label": "vk_consumer_illumination_up (equal to `illumination_increment`)",
        "not_from": true
    },
    {
        "name": "vk_consumer_previous",
        "label": "vk_consumer_previous (equal to `rewind`)",
        "not_from": true
    },
    {
        "name": "vk_consumer_play",
        "label": "vk_consumer_play (equal to `play`)",
        "not_from": true
    },
    {
        "name": "vk_consumer_next",
        "label": "vk_consumer_next (equal to `fastforward`)",
        "not_from": true
    },
    {
        "name": "volume_down",
        "label": "volume_down (equal to `volume_decrement`)"
    },
    {
        "name": "volume_up",
        "label": "volume_up (equal to `volume_increment`)"
    }
]

**Comment by talarari** [comment]
thanks! converted to yml for readability
```
---
- category: Modifier keys
- name: caps_lock
- name: left_control
- name: left_shift
- name: left_option
- name: left_command
- name: right_control
- name: right_shift
- name: right_option
- name: right_command
- name: fn
- category: Controls and symbols
- name: return_or_enter
- name: escape
- name: delete_or_backspace
- name: delete_forward
- name: tab
- name: spacebar
- name: hyphen
  label: hyphen (-)
- name: equal_sign
  label: equal_sign (=)
- name: open_bracket
  label: open_bracket [
- name: close_bracket
  label: close_bracket ]
- name: backslash
  label: backslash (\)
- name: non_us_pound
- name: semicolon
  label: semicolon (;)
- name: quote
  label: quote (')
- name: grave_accent_and_tilde
  label: grave_accent_and_tilde ()
- name: comma
  label: comma (,)
- name: period
  label: period (.)
- name: slash
  label: slash (/)
- name: non_us_backslash
- category: Arrow keys
- name: up_arrow
- name: down_arrow
- name: left_arrow
- name: right_arrow
- name: page_up
- name: page_down
- name: home
- name: end
- category: Letter keys
- name: a
- name: b
- name: c
- name: d
- name: e
- name: f
- name: g
- name: h
- name: i
- name: j
- name: k
- name: l
- name: m
- name: n
- name: o
- name: p
- name: q
- name: r
- name: s
- name: t
- name: u
- name: v
- name: w
- name: x
- name: y
- name: z
- category: Number keys
- name: '1'
- name: '2'
- name: '3'
- name: '4'
- name: '5'
- name: '6'
- name: '7'
- name: '8'
- name: '9'
- name: '0'
- category: Function keys
- name: f1
- name: f2
- name: f3
- name: f4
- name: f5
- name: f6
- name: f7
- name: f8
- name: f9
- name: f10
- name: f11
- name: f12
- name: f13
- name: f14
- name: f15
- name: f16
- name: f17
- name: f18
- name: f19
- name: f20
- name: f21
  not_to: true
- name: f22
  not_to: true
- name: f23
  not_to: true
- name: f24
  not_to: true
- category: Media controls
- name: display_brightness_decrement
  not_from: true
- name: display_brightness_increment
  not_from: true
- name: mission_control
  not_from: true
- name: launchpad
  not_from: true
- name: dashboard
  not_from: true
- name: illumination_decrement
  not_from: true
- name: illumination_increment
  not_from: true
- name: rewind
  not_from: true
- name: play_or_pause
  not_from: true
- name: fastforward
  not_from: true
- name: mute
- name: volume_decrement
- name: volume_increment
- name: eject
  not_from: true
- name: apple_display_brightness_decrement
  not_from: true
- name: apple_display_brightness_increment
  not_from: true
- name: apple_top_case_display_brightness_decrement
  not_from: true
- name: apple_top_case_display_brightness_increment
  not_from: true
- category: Keypad keys
- name: keypad_num_lock
- name: keypad_slash
- name: keypad_asterisk
- name: keypad_hyphen
- name: keypad_plus
- name: keypad_enter
- name: keypad_1
- name: keypad_2
- name: keypad_3
- name: keypad_4
- name: keypad_5
- name: keypad_6
- name: keypad_7
- name: keypad_8
- name: keypad_9
- name: keypad_0
- name: keypad_period
- name: keypad_equal_sign
- name: keypad_comma
- category: Virtual Keys
- name: vk_none
  label: vk_none (disable this key)
  not_from: true
- category: Keys in pc keyboards
- name: print_screen
- name: scroll_lock
- name: pause
- name: insert
- name: application
- name: help
- name: power
- name: execute
  not_to: true
- name: menu
  not_to: true
- name: select
  not_to: true
- name: stop
  not_to: true
- name: again
  not_to: true
- name: undo
  not_to: true
- name: cut
  not_to: true
- name: copy
  not_to: true
- name: paste
  not_to: true
- name: find
  not_to: true
- category: International keys
- name: international1
- name: international2
  not_to: true
- name: international3
- name: international4
  not_to: true
- name: international5
  not_to: true
- name: international6
  not_to: true
- name: international7
  not_to: true
- name: international8
  not_to: true
- name: international9
  not_to: true
- name: lang1
- name: lang2
- name: lang3
  not_to: true
- name: lang4
  not_to: true
- name: lang5
  not_to: true
- name: lang6
  not_to: true
- name: lang7
  not_to: true
- name: lang8
  not_to: true
- name: lang9
  not_to: true
- category: Japanese
- name: japanese_eisuu
  label: 英数キー
- name: japanese_kana
  label: かなキー
- name: japanese_pc_nfer
  label: PCキーボードの無変換キー
  not_to: true
- name: japanese_pc_xfer
  label: PCキーボードの変換キー
  not_to: true
- name: japanese_pc_katakana
  label: PCキーボードのかなキー
  not_to: true
- category: Others
- name: keypad_equal_sign_as400
  not_to: true
- name: locking_caps_lock
  not_to: true
- name: locking_num_lock
  not_to: true
- name: locking_scroll_lock
  not_to: true
- name: alternate_erase
  not_to: true
- name: sys_req_or_attention
  not_to: true
- name: cancel
  not_to: true
- name: clear
  not_to: true
- name: prior
  not_to: true
- name: return
  label: rarely used return (HID usage 0x9e)
  not_to: true
- name: separator
  not_to: true
- name: out
  not_to: true
- name: oper
  not_to: true
- name: clear_or_again
  not_to: true
- name: cr_sel_or_props
  not_to: true
- name: ex_sel
  not_to: true
- name: left_alt
  label: left_alt (equal toleft_option)
- name: left_gui
  label: left_gui (equal toleft_command)
- name: right_alt
  label: right_alt (equal toright_option)
- name: right_gui
  label: right_gui (equal toright_command)
- name: vk_consumer_brightness_down
  label: vk_consumer_brightness_down (equal todisplay_brightness_decrement)
  not_from: true
- name: vk_consumer_brightness_up
  label: vk_consumer_brightness_up (equal todisplay_brightness_increment)
  not_from: true
- name: vk_mission_control
  label: vk_mission_control (equal tomission_control)
  not_from: true
- name: vk_launchpad
  label: vk_launchpad (equal tolaunchpad)
  not_from: true
- name: vk_dashboard
  label: vk_dashboard (equal todashboard)
  not_from: true
- name: vk_consumer_illumination_down
  label: vk_consumer_illumination_down (equal toillumination_decrement)
  not_from: true
- name: vk_consumer_illumination_up
  label: vk_consumer_illumination_up (equal toillumination_increment)
  not_from: true
- name: vk_consumer_previous
  label: vk_consumer_previous (equal torewind)
  not_from: true
- name: vk_consumer_play
  label: vk_consumer_play (equal toplay)
  not_from: true
- name: vk_consumer_next
  label: vk_consumer_next (equal tofastforward)
  not_from: true
- name: volume_down
  label: volume_down (equal tovolume_decrement)
- name: volume_up
  label: volume_up (equal tovolume_increment`)

```

**Comment by theonlygusti** [comment]
What's the difference between a label and a name?

**Comment by theonlygusti** [comment]
In my json I want to make a mapping, <kbd>esc</kbd> to <kbd>cmd</kbd><kbd>.</kbd>

```json
"from": {
  key_code": "escape"
},
"to": [{
  "key_code": "period",
  "modifiers": "right_command"
}]
```

**Comment by rdewolff** [comment]
That should be in the main docs!

**Comment by nikitavoloboev** [comment]
What is underscore (_)? I can't find it here.

**Comment by nikitavoloboev** [comment]
Also is it possible to change keyboard brightness? 

Something like `keyboard_brightess_increment` and `keyboard_brightess_decrement`.

**Comment by Zamiell** [comment]
@tekezo Can you add the key code listing to the main documentation please?

**Comment by brentgreeff** [comment]
I am searching for days and cannot find how to map from [right_command] to dollar ($) or (#)
literal characters don't work.

                  `{
                        "description": "Right command alone generates $.",
                        "manipulators": [
                            {
                                "from": {
                                    "key_code": "right_command",
                                    "modifiers": {
                                        "optional": [
                                            "any"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "right_command"
                                    }
                                ],
                                "to_if_alone": [
                                    {
                                        "key_code": "$"
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    }`

**Comment by brentgreeff** [comment]
> I am searching for days and cannot find how to map from [right_command] to dollar ($) or (#)

I got it

                  `{
                        "description": "Right command alone generates $.",
                        "manipulators": [
                            {
                                "from": {
                                    "key_code": "right_command",
                                    "modifiers": {
                                        "optional": [
                                            "any"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "right_command"
                                    }
                                ],
                                "to_if_alone": [
                                    {
										"key_code": "4",
										"modifiers": "left_shift"
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    }`

**Comment by kakulukia** [comment]
Im missing the key codes for "(" and ")" .. it could be dome via shift and 9/0, but that only applies to an English keyboard and will be different with other layouts. So is there a generic name i could use?

**Comment by fantomac** [comment]
Hello, I'm searching for < keycode.
Thanks

**Comment by nikitavoloboev** [comment]
it is comma with left_shift modifier.

**Comment by fantomac** [comment]
Thanks !  Very fast reply  👍

**Comment by dux** [comment]
I want to covert every key stroke of "§" with "`", and I don't know how to write a config. I do not know key code for "§"

Is there in a config something like a exact key, not a `key_code`?

**Comment by Kickeskov** [comment]
@dux you can use `non_us_backslash` and map it to `grave_accent_and_tidle` to fix this. The eventviewer is also useful for this (at least the source key).

**Comment by dux** [comment]
@Kickeskov thx!

**Comment by avatar-lavventura** [comment]
> [
> {
> "category": "Modifier keys"
> },
> {
> "name": "caps_lock"
> },
> {
> "name": "left_control"
> },
> {
> "name": "left_shift"
> },
> {
> "name": "left_option"
> },
> {
> "name": "left_command"
> },
> {
> "name": "right_control"
> },
> {
> "name": "right_shift"
> },
> {
> "name": "right_option"
> },
> {
> "name": "right_command"
> },
> {
> "name": "fn"
> },
> {
> "category": "Controls and symbols"
> },
> {
> "name": "return_or_enter"
> },
> {
> "name": "escape"
> },
> {
> "name": "delete_or_backspace"
> },
> {
> "name": "delete_forward"
> },
> {
> "name": "tab"
> },
> {
> "name": "spacebar"
> },
> {
> "name": "hyphen",
> "label": "hyphen (-)"
> },
> {
> "name": "equal_sign",
> "label": "equal_sign (=)"
> },
> {
> "name": "open_bracket",
> "label": "open_bracket ["
> },
> {
> "name": "close_bracket",
> "label": "close_bracket ]"
> },
> {
> "name": "backslash",
> "label": "backslash (\)"
> },
> {
> "name": "non_us_pound"
> },
> {
> "name": "semicolon",
> "label": "semicolon (;)"
> },
> {
> "name": "quote",
> "label": "quote (')"
> },
> {
> "name": "grave_accent_and_tilde",
> "label": "grave_accent_and_tilde (`)" }, { "name": "comma", "label": "comma (,)" }, { "name": "period", "label": "period (.)" }, { "name": "slash", "label": "slash (/)" }, { "name": "non_us_backslash" }, { "category": "Arrow keys" }, { "name": "up_arrow" }, { "name": "down_arrow" }, { "name": "left_arrow" }, { "name": "right_arrow" }, { "name": "page_up" }, { "name": "page_down" }, { "name": "home" }, { "name": "end" }, { "category": "Letter keys" }, { "name": "a" }, { "name": "b" }, { "name": "c" }, { "name": "d" }, { "name": "e" }, { "name": "f" }, { "name": "g" }, { "name": "h" }, { "name": "i" }, { "name": "j" }, { "name": "k" }, { "name": "l" }, { "name": "m" }, { "name": "n" }, { "name": "o" }, { "name": "p" }, { "name": "q" }, { "name": "r" }, { "name": "s" }, { "name": "t" }, { "name": "u" }, { "name": "v" }, { "name": "w" }, { "name": "x" }, { "name": "y" }, { "name": "z" }, { "category": "Number keys" }, { "name": "1" }, { "name": "2" }, { "name": "3" }, { "name": "4" }, { "name": "5" }, { "name": "6" }, { "name": "7" }, { "name": "8" }, { "name": "9" }, { "name": "0" }, { "category": "Function keys" }, { "name": "f1" }, { "name": "f2" }, { "name": "f3" }, { "name": "f4" }, { "name": "f5" }, { "name": "f6" }, { "name": "f7" }, { "name": "f8" }, { "name": "f9" }, { "name": "f10" }, { "name": "f11" }, { "name": "f12" }, { "name": "f13" }, { "name": "f14" }, { "name": "f15" }, { "name": "f16" }, { "name": "f17" }, { "name": "f18" }, { "name": "f19" }, { "name": "f20" }, { "name": "f21", "not_to": true }, { "name": "f22", "not_to": true }, { "name": "f23", "not_to": true }, { "name": "f24", "not_to": true }, { "category": "Media controls" }, { "name": "display_brightness_decrement", "not_from": true }, { "name": "display_brightness_increment", "not_from": true }, { "name": "mission_control", "not_from": true }, { "name": "launchpad", "not_from": true }, { "name": "dashboard", "not_from": true }, { "name": "illumination_decrement", "not_from": true }, { "name": "illumination_increment", "not_from": true }, { "name": "rewind", "not_from": true }, { "name": "play_or_pause", "not_from": true }, { "name": "fastforward", "not_from": true }, { "name": "mute" }, { "name": "volume_decrement" }, { "name": "volume_increment" }, { "name": "eject", "not_from": true }, { "name": "apple_display_brightness_decrement", "not_from": true }, { "name": "apple_display_brightness_increment", "not_from": true }, { "name": "apple_top_case_display_brightness_decrement", "not_from": true }, { "name": "apple_top_case_display_brightness_increment", "not_from": true }, { "category": "Keypad keys" }, { "name": "keypad_num_lock" }, { "name": "keypad_slash" }, { "name": "keypad_asterisk" }, { "name": "keypad_hyphen" }, { "name": "keypad_plus" }, { "name": "keypad_enter" }, { "name": "keypad_1" }, { "name": "keypad_2" }, { "name": "keypad_3" }, { "name": "keypad_4" }, { "name": "keypad_5" }, { "name": "keypad_6" }, { "name": "keypad_7" }, { "name": "keypad_8" }, { "name": "keypad_9" }, { "name": "keypad_0" }, { "name": "keypad_period" }, { "name": "keypad_equal_sign" }, { "name": "keypad_comma" }, { "category": "Virtual Keys" }, { "name": "vk_none", "label": "vk_none (disable this key)", "not_from": true }, { "category": "Keys in pc keyboards" }, { "name": "print_screen" }, { "name": "scroll_lock" }, { "name": "pause" }, { "name": "insert" }, { "name": "application" }, { "name": "help" }, { "name": "power" }, { "name": "execute", "not_to": true }, { "name": "menu", "not_to": true }, { "name": "select", "not_to": true }, { "name": "stop", "not_to": true }, { "name": "again", "not_to": true }, { "name": "undo", "not_to": true }, { "name": "cut", "not_to": true }, { "name": "copy", "not_to": true }, { "name": "paste", "not_to": true }, { "name": "find", "not_to": true }, { "category": "International keys" }, { "name": "international1" }, { "name": "international2", "not_to": true }, { "name": "international3" }, { "name": "international4", "not_to": true }, { "name": "international5", "not_to": true }, { "name": "international6", "not_to": true }, { "name": "international7", "not_to": true }, { "name": "international8", "not_to": true }, { "name": "international9", "not_to": true }, { "name": "lang1" }, { "name": "lang2" }, { "name": "lang3", "not_to": true }, { "name": "lang4", "not_to": true }, { "name": "lang5", "not_to": true }, { "name": "lang6", "not_to": true }, { "name": "lang7", "not_to": true }, { "name": "lang8", "not_to": true }, { "name": "lang9", "not_to": true }, { "category": "Japanese" }, { "name": "japanese_eisuu", "label": "英数キー" }, { "name": "japanese_kana", "label": "かなキー" }, { "name": "japanese_pc_nfer", "label": "PCキーボードの無変換キー", "not_to": true }, { "name": "japanese_pc_xfer", "label": "PCキーボードの変換キー", "not_to": true }, { "name": "japanese_pc_katakana", "label": "PCキーボードのかなキー", "not_to": true }, { "category": "Others" }, { "name": "keypad_equal_sign_as400", "not_to": true }, { "name": "locking_caps_lock", "not_to": true }, { "name": "locking_num_lock", "not_to": true }, { "name": "locking_scroll_lock", "not_to": true }, { "name": "alternate_erase", "not_to": true }, { "name": "sys_req_or_attention", "not_to": true }, { "name": "cancel", "not_to": true }, { "name": "clear", "not_to": true }, { "name": "prior", "not_to": true }, { "name": "return", "label": "rarely used return (HID usage 0x9e)", "not_to": true }, { "name": "separator", "not_to": true }, { "name": "out", "not_to": true }, { "name": "oper", "not_to": true }, { "name": "clear_or_again", "not_to": true }, { "name": "cr_sel_or_props", "not_to": true }, { "name": "ex_sel", "not_to": true }, { "name": "left_alt", "label": "left_alt (equal to `left_option`)" }, { "name": "left_gui", "label": "left_gui (equal to `left_command`)" }, { "name": "right_alt", "label": "right_alt (equal to `right_option`)" }, { "name": "right_gui", "label": "right_gui (equal to `right_command`)" }, { "name": "vk_consumer_brightness_down", "label": "vk_consumer_brightness_down (equal to `display_brightness_decrement`)", "not_from": true }, { "name": "vk_consumer_brightness_up", "label": "vk_consumer_brightness_up (equal to `display_brightness_increment`)", "not_from": true }, { "name": "vk_mission_control", "label": "vk_mission_control (equal to `mission_control`)", "not_from": true }, { "name": "vk_launchpad", "label": "vk_launchpad (equal to `launchpad`)", "not_from": true }, { "name": "vk_dashboard", "label": "vk_dashboard (equal to `dashboard`)", "not_from": true }, { "name": "vk_consumer_illumination_down", "label": "vk_consumer_illumination_down (equal to `illumination_decrement`)", "not_from": true }, { "name": "vk_consumer_illumination_up", "label": "vk_consumer_illumination_up (equal to `illumination_increment`)", "not_from": true }, { "name": "vk_consumer_previous", "label": "vk_consumer_previous (equal to `rewind`)", "not_from": true }, { "name": "vk_consumer_play", "label": "vk_consumer_play (equal to `play`)", "not_from": true }, { "name": "vk_consumer_next", "label": "vk_consumer_next (equal to `fastforward`)", "not_from": true }, { "name": "volume_down", "label": "volume_down (equal to `volume_decrement`)" }, { "name": "volume_up", "label": "volume_up (equal to `volume_increment`)"
> }
> ]

I couldn't find questionmark(`?`)

**Comment by nikitavoloboev** [comment]
> I couldn't find questionmark(`?`)

It's `slash` with `left_shift` modifier

**Comment by avatar-lavventura** [comment]
I have following setup, where it actually shows double-column (`:`)

```
                            {
				"conditions": [
                                    {
					"input_sources": [
                                            {
						"language": "tr"
                                            }
					],
					"type": "input_source_if"
                                    }
				],
				"from": {
                                    "key_code": "slash",
                                    "modifiers": {
					"mandatory": [
                                            "left_shift"
				        ]
                                    }
				},
				"to": [
                                    {
					"key_code": "slash",
					"modifiers": [
                                            "left_shift"
				     	]:
				    }
				],
				"type": "basic"
                            }
```

**Comment by hafdon** [comment]
how come "`right_gui" and "left_gui" can correspond to "right_command" and "left_command", respectively? ? (I found that the genesy.github.io encodes them this way, but it was a surprise)

**Comment by ecerulm** [comment]
@hafdon, not the right place to ask.  I answered that question of stackoverflow https://stackoverflow.com/q/70032237/90580

**Comment by shakyevan444** [comment]
any key code for Þ

**Comment by naserowaimer** [comment]
Hi every one, thanks for your help..
What is the key_code of Globe in mac, I know I can use fn instead, but there are a lot pre-biuld system shortcuts using globe key. how can I remap fn into globe key?
When the modify events karabiner on, i cant use fn as globe key.
