### ISSUE TITLE
Is it possible to create launcher mode in Karabiner Elements? 

### ISSUE THREAD

**Issue by nikitavoloboev** [tekezo/Karabiner-Elements#926]
In Karabiner you could do this :

```XML
<item>
    <name>make comma a modifier</name>
    <identifier>private.launcher_mode_open_apps_v72</identifier>

    <!-- condition: turn on launcher mode only when the trigger key is pressed without other keys. -->
    <pressingphysicalkeys_lessthan>2</pressingphysicalkeys_lessthan>
    <modifier_not>
      ModifierFlag::COMMAND_L,
      ModifierFlag::COMMAND_R,
      ModifierFlag::CONTROL_L,
      ModifierFlag::CONTROL_R,
      ModifierFlag::FN,
      ModifierFlag::OPTION_L,
      ModifierFlag::OPTION_R,
      ModifierFlag::SHIFT_L,
      ModifierFlag::SHIFT_R,
    </modifier_not>

    <autogen>
      __KeyOverlaidModifier__
      KeyCode::COMMA,

      <!--
          Use notsave.launcher_mode_v2 in order to be higher priority.
          Use ModifierFlag::MY_LAUNCHER_MODE for __DropAllKeys__.
      -->
      @begin
      KeyCode::VK_CONFIG_SYNC_KEYDOWNUP_notsave_private_launcher_mode_v72, ModifierFlag::MY_LAUNCHER_MODE,
      @end

      @begin
      KeyCode::COMMA,
      @end
    </autogen>
  </item>

  <item hidden="true">
    <identifier vk_config="true">notsave.private_launcher_mode_v72</identifier>

    <autogen>
      __BlockUntilKeyUp__ KeyCode::COMMA,
    </autogen>

        <autogen>
      __KeyToKey__
      KeyCode::A,
      KeyCode::1, ModifierFlag::SHIFT_L
		</autogen>

  </item>
```

And then you can add more autogen _KeyToKey__ below it to map more things to the comma key.

Is this possible to do in Karabiner Elements?

Thank you.

**Comment by cwagner22** [comment]
Here is an example of my launcher, hope it helps.

```
{
    "description": "Launcher Mode",
    "manipulators": [
        {
            "type": "basic",
            "from": {
                "key_code": "w"
            },
            "to": [
                {
                    "set_variable": {
                        "name": "launcher_mode",
                        "value": 1
                    }
                }
            ],
            "to_after_key_up": [
                {
                    "set_variable": {
                        "name": "launcher_mode",
                        "value": 0
                    }
                }
            ],
            "to_if_alone": [
                {
                    "key_code": "w"
                }
            ]
        },
        {
            "conditions": [
                {
                    "name": "launcher_mode",
                    "type": "variable_if",
                    "value": 1
                }
            ],
            "from": {
                "key_code": "e"
            },
            "to": [
                {
                    "shell_command": "open '/Applications/MindNode.app'"
                }
            ],
            "type": "basic"
        }
    ]
},
```

You can even run Keyboard Maestro macros this way. FYI it should also be possible to do that with Hammerspoon.

**Comment by nikitavoloboev** [comment]
Wow. That's amazing. 

So then if I press and hold w key, then press e, it will open MindNode right? How would I add more keys to the w key? How would that look?

One thing I've been thinking is that this JSON gets extremely large with all of its braces.

If this actually works, and once you can bind simultaneous keypresses with mouse mode (and scrolling), Karabiner Elements would be complete for me. 💛

**Comment by cwagner22** [comment]
Yeah. Just add an object to the array:
```
        {
            "conditions": [
                {
                    "name": "launcher_mode",
                    "type": "variable_if",
                    "value": 1
                }
            ],
            "from": {
                "key_code": "r"
            },
            "to": [
                {
                    "shell_command": "...'"
                }
            ],
            "type": "basic"
        }
```

It doesn't look too bad compared to the old xml file imho. I'm still trying it out but I think it's neat. I got inspired by all the materials you have shared 😉
You can also configure modifiers easily if you look at the doc, without having to create new conditions objects.

**Comment by nikitavoloboev** [comment]
What is the value attribute here?

**Comment by cwagner22** [comment]
It's basically a boolean to set and check if the launcher is enabled or not. 
A few examples here: https://github.com/pqrs-org/KE-complex_modifications/tree/master/src/json

**Comment by LoMiLiMiT** [comment]
@cwagner22 I tried to use the launcher mode to map "Tab+q" to "Cmd+Tab" and "Tab+w" to "Cmd+Shift+Tab". However it doesn't work this way and i don't know why. The Application launcher appears no problem, but gets stuck after releasing the keys. Any ideas why?
I even tried to change the "Mu Mode" example, which brings me to the same issue.

```
    {
    "description": "Launcher Mode",
    "manipulators": [
        {
            "type": "basic",
            "from": {
                "key_code": "tab"
            },
            "to": [
                {
                    "set_variable": {
                        "name": "launcher_modev7",
                        "value": 1
                    }
                }
            ],
            "to_if_alone": [
                {
                    "key_code": "tab"
                }
            ],
            "to_after_key_up": [
                {
                    "set_variable": {
                        "name": "launcher_modev7",
                        "value": 0
                    }
                }
            ]
        },
        {
            "conditions": [
                {
                    "name": "launcher_modev7",
                    "type": "variable_if",
                    "value": 1
                }
            ],
            "from": {
                "key_code": "q"
            },
            "to": [
            {
              "key_code": "tab",
              "modifiers": [
                "left_command",
                "left_shift"
              ]
            }
          ],
            "type": "basic"
        },
	{
            "conditions": [
                {
                    "name": "launcher_modev7",
                    "type": "variable_if",
                    "value": 1
                }
            ],
            "from": {
                "key_code": "w"
            },
            "to": [
            {
              "key_code": "tab",
              "modifiers": [
                "left_command"
              ]
            }
          ],
            "type": "basic"
        }
    ]
},

```

**Comment by cwagner22** [comment]
Yeah I tried your example and have the same issue, no idea why... 
Without the launcher mode it's working, like that: https://github.com/pqrs-org/KE-complex_modifications/blob/master/docs/json/application_window_tab_switch_with_right_cmd_hjklsemiquote.json (first example). But for tab+q I guess you need the launcher.

Pretty sure you can do that with hammerspoon, but it's more complicated. If you find a way let me know.

**Comment by Jimmy34742** [comment]
I'm trying to switch to apps via a single longpress. I don't know javascript very well, but I have the following code in the json file that mostly works:
 
    {
      "description": "Launch MyApp return_or_enter is held.",
      "manipulators": [
        {
          "from": {
            "key_code": "return_or_enter",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
        "shell_command": "open '/Applications/MyApp.app'"
            }
          ],
          "to_if_alone": [
              {
           "key_code": "return_or_enter"
            }
          ],
          "type": "basic"
        }
      ]
    },
 
Longpressing the return key switches to MyApp, and there is no occurrence of a return character, which is all correct behavior. But when I tap the return key I get both the return *and* it switches to MyApp. When just doing a key tap, shouldn't the code only execute the to_if_alone branch and not the shell_command in the to-branch? I'm guessing I'm missing something simple, but I'm a newbie coding javascript and could use some help.

**Comment by massens** [comment]
@cwagner22 Thanks very much for the tip, very useful! I had problems while writing and and the apps where launching by error. I solved by changing `to` to `to_if_held_down` and setting `"basic.to_if_held_down_threshold_milliseconds": 100`.

Here you have the code: 


            "complex_modifications": {
                "parameters": {
                    "basic.to_delayed_action_delay_milliseconds": 500,
                    "basic.to_if_alone_timeout_milliseconds": 800,
                    "basic.to_if_held_down_threshold_milliseconds": 100
                },
                "rules": [
                    {
                        "description": "Launcher Mode",
                        "manipulators": [
                            {
                                "from": {
                                    "key_code": "o"
                                },
                                "to_if_held_down": [
                                    {
                                        "set_variable": {
                                            "name": "launcher_mode",
                                            "value": 1
                                        }
                                    }
                                ],
                                "to_after_key_up": [
                                    {
                                        "set_variable": {
                                            "name": "launcher_mode",
                                            "value": 0
                                        }
                                    }
                                ],
                                "to_if_alone": [
                                    {
                                        "key_code": "o"
                                    }
                                ],
                                "type": "basic"
                            },
                            {
                                "conditions": [
                                    {
                                        "name": "launcher_mode",
                                        "type": "variable_if",
                                        "value": 1
                                    }
                                ],
                                "from": {
                                    "key_code": "r"
                                },
                                "to": [
                                    {
                                        "shell_command": "open '/Applications/Crispgtg.app'"
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    }
                ]
            },

**Comment by cwagner22** [comment]
@massens I think that's indeed a better solution, thanks.
So this avoids triggering the launcher mode if the launcher key is held for less than 100ms, which happens when you type fast and press the second key before the launcher key is released. 

However in your example if you'd press the "r" key during this time period (<100ms) that means you would expect to have the letters "o" and then "r" printed but unfortunately the "o" key will be ignored so only "r" will be printed.
It's the same issue in my example, if you press the second key before releasing the launcher key then the launcher key won't be printed. That's the way `to_if_alone` works.

But it's still an improvement.

**Comment by cwagner22** [comment]
@Jimmy34742 I think the events in `to` are always fired. Maybe launch the command in `to_if_held_down` with `repeat` set to false? Also set  `to_if_held_down_threshold_milliseconds` to the value you want. Look at the doc.
If that doesn't work there is also `to_delayed_action` but the only example I see if for double tap, not long press.

**Comment by nikitavoloboev** [comment]
Btw guys, I wanted to ask. Do you know if you can define variables in Karabiner?

For example I want to define a variable that calls an Applescript code similar to how you could do this in old Karabiner:

```Bash
<vkopenurldef>
<name>KeyCode::VK_OPEN_URL_KM_RERUN_CMD_ITERM</name>
<url type="shell">
osascript -e '
tell application "Keyboard Maestro Engine"
do script "Capitalise word"
end tell
'
</url>
</vkopenurldef>
```

**Comment by cwagner22** [comment]
@nikitavoloboev Not that I know of, sorry. Tekezo seems to generate the json config file in [erb templates](https://github.com/pqrs-org/KE-complex_modifications/tree/master/src/json) but it's probably much easier to add the commands inline...

**Comment by Jimmy34742** [comment]
@cwagner22 Thanks, I forgot about this old question. Longpress has since become achievable using a to_if_alone followed by a to_if_held_down.

**Comment by xvrdm** [comment]
@cwagner22 Do you know how this could be properly written inline? I tried this without success:

```
"to": [
  {
    "shell command": "osascript -e 'tell application \"Keyboard Maestro Engine\"\n do script \"open: Safari\" \n end tell'"
  }
],
```

Thanks a lot to all for brainstorming on this issue!

**Comment by cwagner22** [comment]
@xvrdm This is working for me:
```
   "to": [
        {
            "shell_command": "osascript -e 'tell application \"Keyboard Maestro Engine\" to do script \"91ADF247-2210-4743-8628-14D3DE0B94E3\"'"
        }
    ],
```

**Comment by xvrdm** [comment]
I totally did! (+ I did not know about this applescript inline syntax) thanks!!!

**Comment by nikitavoloboev** [comment]
Hey @xvrdm 

Are you by chance using my KM macros I shared in [my macOS](https://github.com/nikitavoloboev/my-mac-os)? Just curious. 🙂

**Comment by xvrdm** [comment]
Hey @nikitavoloboev I haven't seen the actual macros but I am definitely trying to reproduce what I think you are doing! So far, on the KM side, it is as simple as an "Activate <application>".

**Comment by tekezo** [comment]
You can use `simultaneous_options.key_down_order` and `simultaneous_options.key_up_order` to achieve old `__BlockUntilKeyUp__` behavior since Karabiner-Elements latest beta version.

![Check for beta updates](https://pqrs.org/osx/karabiner/img/karabiner-elements-check-for-updates-beta@2x.png)

# json 

The example json (Personal rules (@tekezo) Launcher Mode v4):
https://github.com/pqrs-org/KE-complex_modifications/blob/master/docs/json/personal_tekezo_launcher_mode_v4.json

# json generator

The json generator:
https://github.com/pqrs-org/KE-complex_modifications/blob/master/src/json/personal_tekezo_launcher_mode_v4.json.rb

You can change the trigger key to comma by editing this line:
https://github.com/pqrs-org/KE-complex_modifications/blob/master/src/json/personal_tekezo_launcher_mode_v4.json.rb#L11

These are launcher definitions:
https://github.com/pqrs-org/KE-complex_modifications/blob/master/src/json/personal_tekezo_launcher_mode_v4.json.rb#L24-L39

# Document of `simultaneous_options`

https://pqrs.org/osx/karabiner/json.html#simultaneous-options

**Comment by ricardomoral** [comment]
Guys I’m trying to configure the launcher so I can invoke apps pressing <a letter> + <cmd> + <shift> and for this I’m trying to setup two mandatory modifiers (CMD+SHIFT). But it’s not working. Do you know if it’s possible to request two mandatory modifiers in the “modifiers” clause?

**Comment by Jimmy34742** [comment]
Perhaps post your code?

**Comment by JakeSc** [comment]
I used to love the built-in launcher mode in Karabiner until it was removed. For folks still interested in this, I built a small utility app to simulate the launcher behavior. Check it out here: https://switchfaster.com/
