### ISSUE TITLE
Map § key to escape.

### ISSUE THREAD

**Issue by adamszeptycki** [tekezo/Karabiner-Elements#931]
Hey,
I find myself lacking physical escape button on new MacBook Pro.
It's confusing to use escape button on touch bar, but right below that there is a button I don't use at all: § (and +/- sign).
Is there a way to map that key to escape?

**Comment by rambaut** [comment]
Not really an issue but that key is called 'non_us_backslash' in the Controls and Symbols section. You can also disable the 'esc' on the touch bar by mapping it to 'vk_none'.

**Comment by adamszeptycki** [comment]
Sweet!
Thanks it works :)

**Comment by martinwoodward** [comment]
Thanks all. For the benefit of others, this is how I set up this configuration.  I did it for the specific keyboards in case I plug in an external keyboard I still want my muscle memory to work.

Bind ESC to § on British MacBookPro keyboard
![image](https://user-images.githubusercontent.com/856858/30227573-1632b840-94d2-11e7-81c5-10384e563899.png)

Disable the ESC key on the touchbar on the MacBookPro
![image](https://user-images.githubusercontent.com/856858/30227556-0520f472-94d2-11e7-8cc4-9a97552b9009.png)

When the devices are:
![image](https://user-images.githubusercontent.com/856858/30227583-21b21d0a-94d2-11e7-8e85-d74c4d86f1b3.png)

Thanks to everyone who helped make his happen and [Christopher Mills for sending me here](https://twitter.com/millscj01/status/906230896788955138)

**Comment by rambaut** [comment]
I found that when I mapped non_us_backslash to escape, my grave accent/tilde key was mapping to the paragraph sign (the § symbol on the non_us_backslash key). So in addition I had to map 'grave_accent_and_tilde' to non_us_backslash:

<img width="1012" alt="untitled 3" src="https://user-images.githubusercontent.com/686405/30239758-1524c964-955b-11e7-8e31-6968b233ac6f.png">

**Comment by rambaut** [comment]
And after doing the mapping, the 'fn' key was no longer bringing up the function keys on the touch bar. Another issue comment pointed out that putting the computer to sleep and waking fixes this problem (seemingly permanently).

**Comment by kalinchernev** [comment]
Had the same issue and it came down to what keyboard is selected. Selecting and `ANSI` virtual keyboard instead of `ISO` as the actual, the mapping works ok without having the swapping between tilde and new paragraph key.

I made a short [blog post](https://kalinchernev.github.io/escaping-macbook-pro-touchbar) if you're like me, and still interested in the details of the longer-than-expected research on a simple key mapping thingy.

**Comment by bkarakashev** [comment]
'esc' on the touch bar by mapping it to 'vk_none' didn't work for me. after doing this ESC is still working on the touch bar :(

**Comment by kalinchernev** [comment]
@bkarakashev This part is pretty important https://kalinchernev.github.io/escaping-macbook-pro-touchbar#what-worked-for-me be extra careful about your hardware keyboard. Try the different options, sometimes the choice what you have to take is not obvious.

**Comment by LVC-TestAccount-1** [comment]
@bkarakashev that worked for me, esc icon on Touch Bar is still showing but it doesn't work anymore. No accidental hits anymore ;)

**Comment by AAverin** [comment]
Any way to map Ctrl+Esc to non_us_backslash? I got a 60% keyboard and there is no key for non_us_backslash. There is Esc though, but I don't want it to stop working. At the same time, I need a way to type non_us_backslash somehow.
Any ideas? Didn't find anything in complex modifications

**Comment by MRFabbio** [comment]
I want to disable with vk_none this key: §. What is it name for my keyboard? 
![Schermata 2021-04-02 alle 21 22 22](https://user-images.githubusercontent.com/81828499/113447242-bce20180-93f9-11eb-93eb-f43f2ae2347c.png)
