### ISSUE TITLE
Modifier flags during key repeat is invalid. (Problems with Trackpad)

### ISSUE THREAD

**Issue by tksys** [tekezo/Karabiner-Elements#932]
# Environment
- MacBook Pro (15-inch, 2017)
- macOS Sierra 10.12.6
- Karabiner-Elements 11.0.2

# Related issues
https://github.com/tekezo/Karabiner-Elements/issues/903
https://github.com/tekezo/Karabiner-Elements/issues/893
https://github.com/tekezo/Karabiner-Elements/issues/891

# Details
Using Emacs Key bindings [control + keys] (rev 6)
Key repeat behaves incorrectly.
This problem Ctrl + arrow key is pressed and the cursor Jump to the end of line-end line.

It is a problem frequently occurring when using Emacs key binding in Karabiner-Elements.
If you touch Trackpad even a little, the key binding will be incorrect.
(Ctrlkey's flag will be raised)

While using Emacs key binding, normally you press and hold Ctrl + F, Ctrl + B, etc. The left and right cursor keys will repeat, but due to this problem Ctrl + cursor key is pressed and the cursor Jump to the end of line-end line.

If you use a MacBook with a larger Trackpad after the MacBook Pro 2016, you just touch the Trackpad even if you place your hand at the normal home position.

# Cause
When touching the trackpad, a Ctrl flag is generated.

# Reproduction procedure
1. Simple Modifications
    From Key:caps_lock  ->  To Key:left_control
2. Using Emacs Key bindings [control + keys] (rev 6)
3. Hold to caps lock key.(remapped to control key)
4. Hold to F key
5. right_arrow key is repeated
6. Touch TrackPad(Even by touching with the palm without tapping or clicking)
    Ctrl flag is generated. [Ctrl+right_arrow] is repeated.

**Comment by nschum** [comment]
I'm seeing this, too. Kudos for finding the relation to the trackpad. It looked completely random to me.

**Comment by ky0on** [comment]
This still happens in Version 11.0.1.

> NEWS.md
> Version 11.0.1
> Fixed an issue that modifier flags state is not changed properly in pointing device events from Apple trackpads.

**Comment by tksys** [comment]
It has occurred in 11.0.2 as well.

**Comment by tekezo** [comment]
Thank you for feedback!

This issue is strongly related with macOS key repeat behavior, thus we need to handle events scrupulously

I believe this issue has been gone in v11.0.3.
Please try the latest beta version.
https://pqrs.org/osx/karabiner/document.html#check-for-updates

**Comment by ky0on** [comment]
Now it works! Thanks a lot @tekezo:smile:

**Comment by tksys** [comment]
Great！！
Thank you tekezo!! 😄

I tried v11.0.3.
This problem seems to be solved.

I will continue validation for a while.
If the problem does not occur, close the issue.

I can not think of living without karabiner.
Thank you for taking the time away.
A little, I donated!

**Comment by tksys** [comment]
confirmed the fix.
Thank you @tekezo.
