### ISSUE TITLE
The 'fn' key doesn't bring up function keys on touch bar when 'esc' button is remapped.

### ISSUE THREAD

**Issue by rambaut** [tekezo/Karabiner-Elements#933]
I remapped 'esc' to 'vk_none' on the touch bar (Target Device: "No product name (No manufacturer name)"). Doing this means pressing the 'fn' key doesn't change the touch bar to show function keys.

Disabling the Apple Internal Keyboard under 'Devices' does restore this functionality but it means I can't map any normal keyboard keys.

**Comment by tomislav** [comment]
Sleep and wake your MacBook and it should work again.

**Comment by rambaut** [comment]
That works. Thanks.
