### ISSUE TITLE
is it possible to change IKBC's fn key? 

### ISSUE THREAD

**Issue by cissusnar** [tekezo/Karabiner-Elements#935]
IKBC's fn key can't detect in 'Karabiner EventViewer', but I really want to change it.

**Comment by liub3** [comment]
Latest version could detect FN key, however not able to swap FN and CAPS.

**Comment by cissusnar** [comment]
I've been updated to latest version of karabiner, but it still can't detect IKBC's FN key
I'm using IKBC Model-C87, I think this keyboard's FN key is not a common key, it will not send key event to the operating system.

**Comment by Symbolk** [comment]
Same for me, with Karabiner lateset 13.10 in 2021. Guess fn is hard-coded in the keyboard, but the official does not provide software to code it.
