### ISSUE TITLE
Log file filling up with errors

### ISSUE THREAD

**Issue by jasonology** [tekezo/Karabiner-Elements#936]
I have reinstalled Karabiner Elements 0.91.13 on OSX 10.12.6 to fix an issue where the config files weren’t sticking. Now I see an infinite stream of this in the Log:
` [error] [grabber] IOConnectCallStructMethod error: kIOReturnError (-536870212) @ bool krbn::virtual_hid_device_client::call_method(std::function<IOReturn ()>)`

**Comment by valrus** [comment]
I had this too and was able to stop it by disabling several devices of unknown provenance (I don't know what any of the unchecked devices in the screenshot are supposed to be, as I only have one connected keyboard) in the preferences. Maybe try that?
![karabiner_devices](https://user-images.githubusercontent.com/343665/29650154-d6e071d6-884d-11e7-8e8d-1a53d2e2543c.jpg)

**Comment by jasonology** [comment]
I restarted and it went away. No more overflowing log file.

**Comment by jasonology** [comment]
I just updated to .16 and because the Complex Modifications (read: Hyper Key) weren’t sticking again, and my console is still filling with

`[[2017-09-12 14:42:12.996] [error] [grabber] IOConnectCallStructMethod error: kIOReturnError (-536870212) @ bool krbn::virtual_hid_device_client::call_method(std::function<IOReturn ()>)`
