### ISSUE TITLE
modifiers ( ⇧, ⌘, etc) are ignored with conjunction with touchbar fn keys in apps

### ISSUE THREAD

**Issue by gAmUssA** [tekezo/Karabiner-Elements#937]
steps to reproduce

1. get intellij idea based editor https://www.jetbrains.com/idea/download/#section=mac 
2. show fn keys always for intellij 
![keyboard 2017-08-22 10-06-09](https://user-images.githubusercontent.com/433085/29569603-fb7790b0-8721-11e7-9e1f-3dfdd32eb224.png)
3. start karabiner-elements
4. intellij shortcuts like ⌘⇧F12 (restore windows / hide windows) or ⇧+F6 (rename) aren't working 

was able to confirm with @jbaruch @bulenkov 

p.s. when karabiner-elements is on, I can't set modifiers in keyboard shortcut applet of System Preferences ->Keyboard
![keyboard 2017-08-22 10-13-39](https://user-images.githubusercontent.com/433085/29569831-b52b3b1a-8722-11e7-8613-27fc3031dfce.png)

**Comment by bantonsson** [comment]
This is a duplicate of #535

**Comment by gAmUssA** [comment]
closing duplicate
