### ISSUE TITLE
Strange random behaviour

### ISSUE THREAD

**Issue by simo2409** [tekezo/Karabiner-Elements#938]
Today I booted my mac (osx 10.12.6) and clicking on every link in chrome it acted like I had command pressed (opening the link in a new tab), I restarted chrome many times without solving the issue.

Then I tried to restart karabiner elements (0.91.13) and it solved the problem. No changes were made in last days to karabiner elements config and during the problem EventViewer didn't show anything pressed (and pressing command key EventViewer showed correctly events).

No idea why this happened and how to reproduce it, just let you know.

The problem appeared only using the external USB keyboard, not the mbp's one (wasd keyboard with italian layout)

**Comment by quintrino** [comment]
I'm guessing this is a Duplicate of #466
