### ISSUE TITLE
[Question] - Is there a easier and more readable way to write complex modifications?

### ISSUE THREAD

**Issue by AlexVKO** [tekezo/Karabiner-Elements#942]
hey Guys, thanks for the awesome contribution.

Is there a easier and more readable way to write complex modifiers?

This json file is becoming huuuuge, and it's very easy to have a file with 2000+ lines...

**Comment by thomasjachmann** [comment]
Since I use a lot of custom modifier keys for the whole keyboard, mine's quite long as well. In #832, I asked about wildcards. Maybe you could upvote that ticket somehow if this would solve your problem as well. If enough users care about it, this might become a feature request worth handling.

**Comment by AlexVKO** [comment]
hey @thomasjachmann I managed by doing a transpiler... I will make it open source soon.

it follows some examples

```ruby

@description = "Application Mode"

@manipulators = []

@manipulators << when_press('left_control').activate_mode!('application_mode')

{
  h: 'Google Chrome',
  j: 'Sublime Text',
  k: 'Slack',
  l: 'iTerm'
}.map do |key, application_name|
  @manipulators << when_press(key).open_appliation!(application_name)
                                   .if_mode('application_mode', is: true)
end

``` 

``` 
@description = "Home Arrows Mode"

@manipulators = []

@manipulators << when_press('d').activate_mode!('home_arrows_mode')

{
   h: 'left_arrow' ,
   j: 'down_arrow' ,
   k: 'up_arrow'   ,
   l: 'right_arrow'
}.map do |from, to|
  @manipulators << when_press(from).trigger!(to)
                                   .if_mode('home_arrows_mode', is: true)

  @manipulators << when_press(from, 'left_command').trigger!(to, 'left_command')
                                                   .if_mode('home_arrows_mode', is: true)
end
```

**Comment by thomasjachmann** [comment]
@AlexVKO Great, let me know when it is published.
