### ISSUE TITLE
caps_lock+spacebar+6,y,h,n isn't work

### ISSUE THREAD

**Issue by iwuwu** [tekezo/Karabiner-Elements#947]
In my Macbook Pro, I want to set caps_lock to left_control, and spacebar to left_shift (use complex modifiactions) , for other keys it works fine, but left_control+left_shift (physically,caps_lock+spacebar) + 6 or y or h or n isn't work. actually there is no any event in eventviewer.
I did a lot of test, it sames like whatever you set your caps_lock and spacebar is (fn,command,option or whatever), the system just do not response to caps_lock+spacebar+6yhn, Maybe it's a hardware issue?

**Comment by vitmy0000** [comment]
I have more or less the same issue.
However, I just found out this is a Apple keyboard bug.
Just quit Karabiner, in any text input area, hold caps_lock+spacebar.
6, y, h, n won't print any letter.

**Comment by Voleking** [comment]
same issue here. 
`MacBook Pro  (Retina,13-inch, Early 2015)`
`macOS 10.13.2`
