### ISSUE TITLE
How to fire a different shell script on keyup/keydown

### ISSUE THREAD

**Issue by programmerq** [tekezo/Karabiner-Elements#948]
My goal is to get push-to-talk functionality implemented for the conferencing software I use. I've got a complex modification working, but I'd like to make it send mute/unmute on keyup/keydown on a single key rather than rely on two separate keys. Is there a way to detect these inside the complex modifications functionality?

    {
      "title": "Mute/Unmute Zoom",
      "rules": [
        {
          "description": "Mute or unmute zoom with keys",
          "manipulators": [
            {
              "type": "basic",
              "from": {
                "key_code": "f13"
              },
              "to": [
                {
                  "shell_command": "osascript /Users/jefferya/Documents/unmute.scpt"
                }
              ]
            },
            {
              "type": "basic",
              "from": {
                "key_code": "f14"
              },
              "to": [
                {
                  "shell_command": "osascript /Users/jefferya/Documents/mute.scpt"
                }
              ]
            }
          ]
        }
      ]
    }

**Comment by thomasjachmann** [comment]
This should do it:

```
{
    "title": "Mute/Unmute Zoom",
    "rules": [
        {
            "description": "Mute or unmute zoom with keys",
            "manipulators": [
                "type": "basic",
                "from": {
                    "key_code": "f13"
                },
                "to": [
                    {
                        "shell_command": "osascript /Users/jefferya/Documents/unmute.scpt"
                    }
                ],
                "to_after_key_up": [
                    {
                        "shell_command": "osascript /Users/jefferya/Documents/mute.scpt"
                    }
                ]
            ]
        }
    ]
}
```
