### ISSUE TITLE
Comma to period on AZERTY keyboard

### ISSUE THREAD

**Issue by arnoutaertgeerts** [tekezo/Karabiner-Elements#951]
I have an AZERTY keyboard and I'm unable to change a _comma_ to a _period_. I did find out using Eventviewer that Karabiner thinks I have a US keyboard but there is **no key which directly produces a period**.

Would this be possible using Karabiner elements as it is now? If I'm able to convert a single key stroke to a combination (SHIFT + comma) I think it could work.

**Comment by NinoDLC** [comment]
Same problem here (AZERTY on mac), I would like to remap the pad comma to a dot but I didn't find any solutions :(

**Comment by NinoDLC** [comment]
@arnoutaertgeerts I finally found this, it works !!https://github.com/tekezo/Karabiner-Elements/issues/643#issuecomment-324328443

**Comment by BorisGUNTHER** [comment]
Hi,
Do you have an update about this bug / request ? It would be very helpful to get it fixed.
Regards

**Comment by JakeShelterwin** [comment]
@NinoDLC Thank you for sharing that solution but please can you tell us where to place the edits inside the ~/.config/karabiner/karabiner.json file? Every modification I make revert back as soon as karabiner is relaunced...
