### ISSUE TITLE
Complex Modifications Randomly Stop Working

### ISSUE THREAD

**Issue by activelogic** [tekezo/Karabiner-Elements#952]
Hello, I'm having an issue on multiple macs running Sierra where my Complex Modifications will suddenly stop working.  Sometimes disabling the modifications for a few seconds then re-enabling them fixes the issue and some other times turning the device off for a few seconds, then turning it back on fixes the issue.

Any idea what might be causing this?

**Comment by activelogic** [comment]
This is actually due to caps lock being on.  Not sure why complex modifications stop working when caps lock is on.

**Comment by michelkoga** [comment]
You have to set caps_lock as a optional modifier, like this:
```
"from": {
   "key_code": "a",
   "modifiers": {
      "optional": "caps_lock"
    }
},
```
