### ISSUE TITLE
How to find out the input source id?

### ISSUE THREAD

**Issue by nawkwan** [tekezo/Karabiner-Elements#958]
The Input Source ID can be found in Karabiner's Event Viewer ([described here](https://pqrs.org/osx/karabiner/xml.html.en#inputsourceid)).
This information is missing in Karabiner-Elements' Event Viewer.  In fact, all Input Source info are missing.
![Missing Input Source Info](https://user-images.githubusercontent.com/4675368/29954128-8adcbe64-8ea3-11e7-8dc1-d5ba19f4c21c.png)

**Comment by nguyenhimself** [comment]
One workaround: Are you trying to get the ids of external USB keyboards/mice? If so, you can get them from the command line with 

`ioreg -p IOUSB`

I save that as an alias for quick access:

`alias usb="ioreg -p IOUSB"`

**Comment by RuslanIsh** [comment]
@nguyenhimself Not the ID of a device but ID of an input source as English Language layout or sat French. 
I need that too.

**Comment by tekezo** [comment]
You can investigate input source information in `EventViewer > Variables` tab with Karabiner-Elements latest beta version.

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates
