### ISSUE TITLE
set_variable ordering matters for creating chords

### ISSUE THREAD

**Issue by stifynsemons** [tekezo/Karabiner-Elements#960]
I have been using Karabiner to turn a standard MBP keyboard into a chorded one (t and h, or "th" produce "the ", "ut" produces "update ", "tu" produces "through", etc., with about 1500 words defined with the help of some Perl scripting) and have realized that the set_variable of Karabiner-Elements allows a much more elegant solution than Karabiner had. In essence, each key can trigger a variable, which can invoke a sub-map (layer). There is a lot of potential in the syntax (congratulations Tekezo), and so I started testing examples to see how far I could get, and ran into trouble:

The snippet below supports "an" = "and ", and "at" = "at ", and "th"= "the ", but fails to support "ta"="that ". (Note "th" means press "t" then "h" in Karabiner, with the simulataneous key press feature; here it means hold down t until you press h. I'm can't really tell the difference). 

If the order of the "A" and "T" sections are swapped, then "at" fails and "ta" works. The point of the test was to check mirrored chords, which do not seem to work. This is not a big loss in the short term, as I think only a small fraction of pair chords are mirrors. Next to check triplet chords :-)

		{   "description": "Set A layer", "type": "basic",
		    "from": { "key_code": "a" }, "to_if_alone": [ { "key_code": "a" } ],
		    "to": [ { "set_variable": { "name": "seq_a", "value": 1 } } ],
		    "to_after_key_up": [ { "set_variable": { "name": "seq_a", "value": 0 } } ] },
		{   "conditions": [ { "type" : "variable_if", "name": "seq_a", "value": 1 } ], "from": { "key_code": "n" },		    
		    "type": "basic", "to": [ { "key_code": "a" }, { "key_code": "n"}, { "key_code": "d" }, { "key_code": "spacebar" } ] },
		{   "conditions": [ { "type" : "variable_if", "name": "seq_a", "value": 1 } ], "from": { "key_code": "t" },	    
		    "type": "basic", "to": [ { "key_code": "a" }, { "key_code": "t"}, { "key_code": "spacebar" } ] },

		{   "description": "Set T layer", "type": "basic",
		    "from": { "key_code": "t" }, "to_if_alone": [ { "key_code": "t" } ],
		    "to": [ { "set_variable": { "name": "seq_t", "value": 1 } } ],
		    "to_after_key_up": [ { "set_variable": { "name": "seq_t", "value": 0 } } ] },
		{   "conditions": [ { "type" : "variable_if", "name": "seq_t", "value": 1 } ], "from": { "key_code": "a" },		    
		    "type": "basic", "to": [ { "key_code": "t" }, { "key_code": "h"}, { "key_code": "a" }, { "key_code": "t" }, { "key_code": "spacebar" } ] },
		{   "conditions": [ { "type" : "variable_if", "name": "seq_t", "value": 1 } ], "from": { "key_code": "h" },	    
		    "type": "basic", "to": [ { "key_code": "t" }, { "key_code": "h"}, { "key_code": "e" }, { "key_code": "spacebar" } ] },

**Comment by stifynsemons** [comment]
It seems to be more complicated. Moving just the Set T layer group to before the "at" definition breaks the "at" definition as well.

And yet ... when I add Set AL (triplets work!) and the definitions of "alm"="almost " and "aly"="always " everything works (and, at, almost, always, the, and that). This may be closed soon ...

Stephen Simmons

**Comment by stifynsemons** [comment]
Work-around/solution:

When you have a chord, (e.g. xy) where the 2nd key is the first key of another chord (e.g. yz), and you define the layer/variable for the first chord (x) after the layer/variable for the second chord (y), it will not work unless you define the layer/variable for y with a condition that x is not set.

For a keyboard with 63 keys, this may get awkward for paired chords. Imagine dozens of conditions for each of the more common keys, just to eliminate the conflicts. For triplet or quadruplet chords, it will be even worse.

I'd like to change this to an enhancement request to ease this issue. Some suggestions:

- a condition that specifies that no other variables are set. I think this is too broad, as this would make chording incompatible with the other uses of variables.
- a way to make one variable the logical combination of others. In this way, repeated complex conditions can be avoided.

Stephen Simmons

**Comment by stifynsemons** [comment]
code to generate pair and triplet chords from simple list now uploaded to https://github.com/stifynsemons/ke-chording

Seems to work reliably with over one hundred entries, but does not work for chords with touchbar and a few other special cases.

Stephen Simmons

**Comment by petonic** [comment]
Wow, Stephen.  That's impressive work and well thought out.  Thanks for making it and sharing it.

**Comment by stifynsemons** [comment]
Thanks; it was a collection of patches for Karabiner, but since I had to re-write it for Karabiner-Elements, and Tekezo came up with a much more streamlined way to handle multiple key-presses, it seemed appropriate to start with a cleaner architecture.

It will take some time for it to reach the maturity of the unpublished Karabiner version, and there is still some tinkering with the default chord assignments (the document and chord list and code are progressing in parallel).

Stephen Simmons
