### ISSUE TITLE
capslock makes my complex modification not working

### ISSUE THREAD

**Issue by LucaMarconato** [tekezo/Karabiner-Elements#964]
I work with a simple comple complex modification ( :) ) which switch the left option with a right control and the left command with a right option in my MacBook Pro.

[Here](https://pastebin.com/VFZZVU2q) there is my configuration file.

I noticed that when caps lock is activated my complex modification does not work anymore. Is this a bug or a feature?
I think it is a bug, but maybe I will be able to create a workaround creating a custom complex modification for the case in which caps lock is activated.

**Comment by activelogic** [comment]
@LucaMarconato - I am having the exact same issue, but thought the cause was something else.  Thanks for pointing out that caps lock being on is what is causing my complex modifications to stop working.  This was causing me all kinds of headaches trying to figure out why this was happening.  Thanks!

**Comment by michelkoga** [comment]
Try this:

```
                                "from": {
                                    "key_code": "right_option",
                                   "modifiers": {
                                              "optional": [
                                              "caps_lock"
                                   ]
                                },
                                "to": [
                                    {
                                        "key_code": "right_control"
                                    }
                                ],
```

**Comment by LucaMarconato** [comment]
Thank you, I will try. However I noticed that also SHIFT is causing the complex modification to break.
For instance I have a shortcut that requires me to press OPT+SHIFT+D. 
If I press, in the order, RIGHT_OPT+SHIFT+D, the complex modification is working, if I press SHIFT+RIGHT_OPT+D, the complex modification breaks.
So when I type fast, since I cannot control the order so much, my complex modification does not work.

**Comment by michelkoga** [comment]
For shift, you have to specify, "right_shift" , "left_shift".
If you want all your modifiers to be usable, use "any"

```
"from": {
    "key_code": "right_option",
     "modifiers": {
          "optional":  "any"
       }
 },
 "to": [
 {
          "key_code": "right_control"
  }
   ],
```
