### ISSUE TITLE
EventView cannot detect the fn key event from logitech K380

### ISSUE THREAD

**Issue by taingmeng** [tekezo/Karabiner-Elements#966]
I was looking for a way to swap K380 ctrl and fn key. With Karabiner-Elements, I can change the ctrl to fn key. However, I can't change fn to ctrl. Apparently, Karabiner is not able to detect the fn key event from K380. When I press fn key on K380, EventViewer does not show the fn key event. When I press fn key on my Macbook, EventViewer can show the fn key event.

**Comment by danielweck** [comment]
Same "problem" here, I am not able to swap the FUNCTION and CONTROL keys on my Logitech K380. Although to be fair, there's nothing Karabiner can do if the keyboard hardware does not send the `fn` code when the key is pressed on its own :(

**Comment by danielweck** [comment]
By the way, duplicate issue: https://github.com/tekezo/Karabiner-Elements/issues/999

**Comment by SarahMSteinman** [comment]
Having the same issue with this keyboard https://www.xvxchannel.com/home/main/product.html?id=54 it's the XVX MK61
