### ISSUE TITLE
Is there an importable rule or .json file for fn+jkluio to 123456?

### ISSUE THREAD

**Issue by peterpqa** [tekezo/Karabiner-Elements#968]
I searched the issues, but couldn't find anything directly on point. Apologies if it's a duplicate.

The imported rule for "Numeric Keypad Mode [Tab as trigger key]" is working okay, but the key mapping is strange. Is there an importable rule for the original Karabiner's fn+jkluio to 123456, etc.? Or has someone written a karabiner.json file for that? Or is there a reason that "fn" cannot be used as a trigger key in Karabiner-Elements?

If not, I'm tempted to try editing karabiner.json myself, but I'm a rank amateur. I'd rather not reinvent the wheel, and who knows what havoc I may wreak. Thanks.

**Comment by jvinding** [comment]
See #127

**Comment by peterpqa** [comment]
Yup, there was #127, near the bottom of the list when I searched issues for "fn  numeric". I just missed it. Apologies for clogging the issue list with another dupe. I think I've come up with a .json file that enables fn+jkl; to 123- etc., with p=+, 0=* (I'm using it now). See #127.
