### ISSUE TITLE
Can't find signing identity

### ISSUE THREAD

**Issue by camscofie** [tekezo/Karabiner-Elements#969]
# I am using Hackintosh, it could be the reason that it couldn't find my signing identity

![screenshot 2017-09-06 07 23 52](https://user-images.githubusercontent.com/18118996/30095801-216bfc70-92d5-11e7-9832-f31eea8ade13.png)

## is there anything that i can do?

**Comment by epegzz** [comment]
I am getting the same error, yet I have no problems creating and installing the image. Do you encounter issues?

**Comment by camscofie** [comment]
not yet, I think for me it is because its Hackintosh's problem, cuz it's not a real Mac, motherboard and so on are different so it couldn't be recognised.
