### ISSUE TITLE
Mapping PC Keyboard Home/End to "Home"/"End"

### ISSUE THREAD

**Issue by chrisngn** [tekezo/Karabiner-Elements#970]
The behavior of the Home/End buttons from an external keyboard is not moving to the cursor to the beginning/end of line. Karabiner-EventView is reporting the Home key as Fn+Home and the End key as Fn+End. How can I improve my rule so that it will work?

```
{
    "title": "Home / End on External Keyboard",
    "rules": [
        {
            "description": "Change Home to Command + Left Arrow",
            "manipulators": [
                {
                    "type": "basic",
                    "from": {
                        "key_code": "home",
                        "modifiers": {
                            "mandatory": ["fn"]
                        }
                    },
                    "to": [
                        {
                            "key_code": "left_arrow",
                            "modifiers": ["right_command"]
                        }
                    ]
                }
            ]
        },
        {
            "description": "Change End to Command + Right Arrow",
            "manipulators": [
                {
                    "type": "basic",
                    "from": {
                        "key_code": "end",
                        "modifiers": {
                            "mandatory": ["fn"]
                        }
                    },
                    "to": [
                        {
                            "key_code": "right_arrow",
                            "modifiers": ["right_command"]
                        }
                    ]
                }
            ]
        }
    ]
}
```

**Comment by chrisngn** [comment]
Home/End can move to the cursor to the beginning/end of line by changing `"mandatory"` to `"optional`. However, I ran new into a new issue, where Shift + Home & Shift + End were not behaving as expected. I came up with this fix, but it seems messy. Can anyone improve on it?

```
{
    "title": "Home / End on External Keyboard",
    "rules": [
        {
            "description": "Change Home to [Command + Left Arrow]",
            "manipulators": [
                {
                    "type": "basic",
                    "from": {
                        "key_code": "home",
                        "modifiers": {
                            "optional": ["fn"]
                        }
                    },
                    "to": [
                        {
                            "key_code": "left_arrow",
                            "modifiers": ["right_command"]
                        }
                    ]
                }
            ]
        },
        {
            "description": "Change End to [Command + Right Arrow]",
            "manipulators": [
                {
                    "type": "basic",
                    "from": {
                        "key_code": "end",
                        "modifiers": {
                            "optional": ["fn"]
                        }
                    },
                    "to": [
                        {
                            "key_code": "right_arrow",
                            "modifiers": ["right_command"]
                        }
                    ]
                }
            ]
        },
        {
            "description": "Change [Shift + Home] to [Shift + Command + Left Arrow]",
            "manipulators": [
                {
                    "type": "basic",
                    "from": {
                        "key_code": "home",
                        "modifiers": {
                            "optional": ["fn"],
                            "mandatory": ["left_shift"]
                        }
                    },
                    "to": [
                        {
                            "key_code": "left_arrow",
                            "modifiers": ["right_shift", "right_command"]
                        }
                    ]
                }
            ]
        },
        {
            "description": "Change [Shift + Home] to [Shift + Command + Left Arrow]",
            "manipulators": [
                {
                    "type": "basic",
                    "from": {
                        "key_code": "end",
                        "modifiers": {
                            "optional": ["fn"],
                            "mandatory": ["left_shift"]
                        }
                    },
                    "to": [
                        {
                            "key_code": "right_arrow",
                            "modifiers": ["right_shift", "right_command"]
                        }
                    ]
                }
            ]
        }
    ]
}
```

**Comment by Gaulomatic** [comment]
I came along with this, I don't know if it is less messy to you - but it works for me so far:

`{
  "title": "PC Style",
  "rules": [
    {
      "description": "Home / End (except VS Code, iTerm, Terminal and vim)",
      "manipulators": [

        {
          "type": "basic",
          "from": {
            "key_code": "home"
          },
          "to": [
            {
              "key_code": "left_arrow",
              "modifiers": [
                "left_command"
              ]
            }
          ],
          "conditions": [
            {
              "type": "frontmost_application_unless",
              "bundle_identifiers": [
                "^org\\.vim\\.",
                "^com.googlecode.iterm2",
                "^com.microsoft.VSCode",
                "^com.apple.Terminal"
              ]
            }
          ]
        },

        {
          "type": "basic",
          "from": {
            "key_code": "home",
            "modifiers": {
              "mandatory": [
                "left_shift"
              ]
            }
          },
          "to": [
            {
              "key_code": "left_arrow",
              "modifiers": [
                "left_command",
                "left_shift"
              ]
            }
          ],
          "conditions": [
            {
              "type": "frontmost_application_unless",
              "bundle_identifiers": [
                "^org\\.vim\\.",
                "^com.googlecode.iterm2",
                "^com.microsoft.VSCode",
                "^com.apple.Terminal"
              ]
            }
          ]
        },



        {
          "type": "basic",
          "from": {
            "key_code": "end"
          },
          "to": [
            {
              "key_code": "right_arrow",
              "modifiers": [
                "left_command"
              ]
            }
          ],
          "conditions": [
            {
              "type": "frontmost_application_unless",
              "bundle_identifiers": [
                "^org\\.vim\\.",
                "^com.googlecode.iterm2",
                "^com.microsoft.VSCode",
                "^com.apple.Terminal"
              ]
            }
          ]
        },

        {
          "type": "basic",
          "from": {
            "key_code": "end",
            "modifiers": {
              "mandatory": [
                "left_shift"
              ]
            }
          },
          "to": [
            {
              "key_code": "right_arrow",
              "modifiers": [
                "left_command",
                "left_shift"
              ]
            }
          ],
          "conditions": [
            {
              "type": "frontmost_application_unless",
              "bundle_identifiers": [
                "^org\\.vim\\.",
                "^com.googlecode.iterm2",
                "^com.microsoft.VSCode",
                "^com.apple.Terminal"
              ]
            }
          ]
        }

      ]
    },



    {
      "description": "Home / End (Terminal)",
      "manipulators": [

        {
          "type": "basic",
          "from": {
            "key_code": "home"
          },
          "to": [
            {
              "key_code": "left_arrow",
              "modifiers": [
                "left_shift",
                "fn"
              ]
            }
          ],
          "conditions": [
            {
              "type": "frontmost_application_if",
              "bundle_identifiers": [
                "^com.apple.Terminal"
              ]
            }
          ]
        },



        {
          "type": "basic",
          "from": {
            "key_code": "end"
          },
          "to": [
            {
              "key_code": "right_arrow",
              "modifiers": [
                "left_shift",
                "fn"
              ]
            }
          ],
          "conditions": [
            {
              "type": "frontmost_application_if",
              "bundle_identifiers": [
                "^com.apple.Terminal"
              ]
            }
          ]
        }

      ]
    }
  ]
}
`

**Comment by chrisngn** [comment]
You added some things I didn't think of. Thank you.

**Comment by AndrewMagerman** [comment]
Gaulomatic, you're a hero. Much better than the Cmd-A and Cmd-E which comes as a standard.

**Comment by Leo7654** [comment]
New syntax

```
{

      "description": "Home / End (except VS Code, iTerm, Terminal and vim)",
      "manipulators": [

        {
          "type": "basic",
          "from": {
            "key_code": "home"
          },
          "to": [
            {
              "key_code": "left_arrow",
              "modifiers": [
                "left_command"
              ]
            }
          ],
          "conditions": [
            {
              "type": "frontmost_application_unless",
              "bundle_identifiers": [
                "^org\\.vim\\.",
                "^com.googlecode.iterm2",
                "^com.microsoft.VSCode",
                "^com.apple.Terminal"
              ]
            }
          ]
        },

        {
          "type": "basic",
          "from": {
            "key_code": "home",
            "modifiers": {
              "mandatory": [
                "left_shift"
              ]
            }
          },
          "to": [
            {
              "key_code": "left_arrow",
              "modifiers": [
                "left_command",
                "left_shift"
              ]
            }
          ],
          "conditions": [
            {
              "type": "frontmost_application_unless",
              "bundle_identifiers": [
                "^org\\.vim\\.",
                "^com.googlecode.iterm2",
                "^com.microsoft.VSCode",
                "^com.apple.Terminal"
              ]
            }
          ]
        },



        {
          "type": "basic",
          "from": {
            "key_code": "end"
          },
          "to": [
            {
              "key_code": "right_arrow",
              "modifiers": [
                "left_command"
              ]
            }
          ],
          "conditions": [
            {
              "type": "frontmost_application_unless",
              "bundle_identifiers": [
                "^org\\.vim\\.",
                "^com.googlecode.iterm2",
                "^com.microsoft.VSCode",
                "^com.apple.Terminal"
              ]
            }
          ]
        },

        {
          "type": "basic",
          "from": {
            "key_code": "end",
            "modifiers": {
              "mandatory": [
                "left_shift"
              ]
            }
          },
          "to": [
            {
              "key_code": "right_arrow",
              "modifiers": [
                "left_command",
                "left_shift"
              ]
            }
          ],
          "conditions": [
            {
              "type": "frontmost_application_unless",
              "bundle_identifiers": [
                "^org\\.vim\\.",
                "^com.googlecode.iterm2",
                "^com.microsoft.VSCode",
                "^com.apple.Terminal"
              ]
            }
          ]
        }

      ]
    }
```

```

    {
      "description": "Home / End (Terminal)",
      "manipulators": [

        {
          "type": "basic",
          "from": {
            "key_code": "home"
          },
          "to": [
            {
              "key_code": "left_arrow",
              "modifiers": [
                "left_shift",
                "fn"
              ]
            }
          ],
          "conditions": [
            {
              "type": "frontmost_application_if",
              "bundle_identifiers": [
                "^com.apple.Terminal"
              ]
            }
          ]
        },



        {
          "type": "basic",
          "from": {
            "key_code": "end"
          },
          "to": [
            {
              "key_code": "right_arrow",
              "modifiers": [
                "left_shift",
                "fn"
              ]
            }
          ],
          "conditions": [
            {
              "type": "frontmost_application_if",
              "bundle_identifiers": [
                "^com.apple.Terminal"
              ]
            }
          ]
        }

      ]
   
}
```
