### ISSUE TITLE
Sticky Trigger Key

### ISSUE THREAD

**Issue by chrisngn** [tekezo/Karabiner-Elements#971]
The VI style arrows requires you to press [trigger key] + hjkl. Is there anyway to only press the trigger key once? To turn off the trigger key, just press it again.

**Comment by rcmdnk** [comment]
I made **Vim emulation** with Karabiner-Elements, which can be imported from:
[complex_modifications rules by rcmdnk](https://rcmdnk.com/KE-complex_modifications/)

You can change to normal mode by pressing `ESC`, and move by hjkl only,
then turn back to insert mode (i.e. OS's normal bahavior) by pressing `i`.
You can also use `jk` to toggle the mode.

**Comment by rcmdnk** [comment]
Maybe something like this?

[numlock.json](https://gist.github.com/rcmdnk/18a3880429e7560ef1ba1e2dbcdb0da5)

I don't have keyboard with numlock, so it uses `escape` to switch on (1-9 to F1-F9).
In addition, I don't have keypad so they are normal `1` to `9`.

You can replace `escape` to `keypad_num_lock` and such `"key_code": "1"` to `"key_code": "keypad_1"`.

I think Karabiner-Elements can't check numlock status,
so if you use num lock key in above example, it may make confusion of numlock status,
as it uses period to switch off.

**Comment by chrisngn** [comment]
Thanks a lot for the sample and explanation! Can understand it now.

**Comment by chrisngn** [comment]
I found a way to make it shorter, so that it does not require 2 extra blocks to work with Shift.

```
"manipulators": [
                {
                    "type": "basic",
                    "from": {
                        "key_code": "home",
                        "modifiers": {
                            "optional": ["fn", "shift"]
                        }
                    },
                    "to": [
                        {
                            "key_code": "left_arrow",
                            "modifiers": ["command"]
                        }
                    ]
                },
                {
                    "type": "basic",
                    "from": {
                        "key_code": "end",
                        "modifiers": {
                            "optional": ["fn", "shift"]
                        }
                    },
                    "to": [
                        {
                            "key_code": "right_arrow",
                            "modifiers": ["command"]
                        }
                    ]
                }
            ]
```
