### ISSUE TITLE
Karabiner's <uielementroles> 

### ISSUE THREAD

**Issue by oniatsu** [tekezo/Karabiner-Elements#975]
Is Karabiner's `<uielementroles>` supported?
The function is very effective. If the function will be supported, Karabiner-Elements will be much powerful.

**Comment by honsa** [comment]
Any news on that? Still searching for a solution...

**Comment by Vayn** [comment]
`uielementrole_only` is still missing.

**Comment by honsa** [comment]
Depending on what you need, may variables can solve the issue

[Karabiner: variable_if, variable_unless](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/variable/)

**Comment by hardkrash** [comment]
Use case that I am looking for: Fix MS Excel text motions of beginning and end of line in a text cell.

I don't see how a variable can implement this.

A Karabiner XML example of what I am looking for is here.
https://gist.github.com/handcoding/224a5d81ce9fe111b436902cba2b0577

```
	<item>
		<name>Excel: Command+Left and Command+Right to move within cells</name>
		<appendix>For some reason, Excel wants you to use Home (and presumably End) to move to the beginning or end of a line within a cell, which is bogus.</appendix>
		<appendix>This also remaps Command+Up and Command+Down so that they move the cursor to the top or bottom of the current cell.</appendix>
		<identifier>private.excel_fix_command_arrow_keys</identifier>
		<only>EXCEL</only>

		<uielementrole_only>AXTextArea, AXTextField</uielementrole_only>

		<!-- You don’t really want Command+Left and Command+Right to be overridden all the time since that normally allows you to navigate via data regions: http://www.adventuresincre.com/6-indispensable-key-strokes-for-moving-around-excel-fast/ -->

		<!-- Command+Left and Command+Right to move within cells in Excel -->
		<autogen>
			__KeyToKey__
			KeyCode::CURSOR_LEFT, ModifierFlag::COMMAND_L,
			KeyCode::HOME
		</autogen>
		<autogen>
			__KeyToKey__
			KeyCode::CURSOR_RIGHT, ModifierFlag::COMMAND_L,
			KeyCode::END
		</autogen>

		<!-- Command+Up and Command+Down to move to the top/bottom of the cell within Excel -->
		<autogen>
			__KeyToKey__
			KeyCode::CURSOR_UP, ModifierFlag::COMMAND_L,
			KeyCode::HOME, ModifierFlag::COMMAND_L
		</autogen>
		<autogen>
			__KeyToKey__
			KeyCode::CURSOR_DOWN, ModifierFlag::COMMAND_L,
			KeyCode::END, ModifierFlag::COMMAND_L
		</autogen>
	</item>
```

**Comment by oniatsu** [comment]
I am using a substituted solution.

1. Catch a typed key on Karabiner-Elements.
2. Send the key value to a Hammerspoon script.
3. [Hammerspoon checks a UI Element role](https://www.hammerspoon.org/docs/hs.uielement.html#role) on the focused UI element.
4. If the UI Elemnet is the one you defined, the specific function will be occured.
