### ISSUE TITLE
Add customizations without losing the GUI

### ISSUE THREAD

**Issue by brandondrew** [tekezo/Karabiner-Elements#976]
Since (as far as I can tell) 

1. the only way to add our own configurations is to manually edit karabiner.json, and
2. the Karabiner Elements GUI also edits karabiner.json,

it would appear that adding new configurations through the GUI would overwrite anything we put in there manually.  

If this is _not_ the case, it would be helpful to document that fact.  

If this _is_ the case, it would be very helpful to allow us to add `.json` files to some location in our Karabiner config folder and have them automatically added into `karabiner.json` along with the GUI-generated settings. 

Thanks!

**Comment by brandondrew** [comment]
Is it possible to get a confirmation one way or the other?  Will customizations made in the GUI overwrite files added manually?  Vice versa?  Is there any way to merge them?

**Comment by brandondrew** [comment]
❔

**Comment by brandondrew** [comment]
Is it possible to get a response on this?

**Comment by brandondrew** [comment]
Why no reply?

**Comment by clemsam** [comment]
You can place your code manually as a "My_name_whatever.json" into K-E's ~/.config/karabiner/assets/complex_modifications/ folder but you need a "title"…-etc. code particle in front, that you can paste from other "Complex Modifications" in this folder.

While Karabiner Elements is open I get a warning from K-E, if I make changes in karabiner.json, asking if I want to include them while saving K-E …

**Comment by brandondrew** [comment]
@clemsam Thanks! That was very helpful!
