### ISSUE TITLE
Suggestion: Adding a simpler (and more logical) way to define device-specific complex modifications

### ISSUE THREAD

**Issue by nawkwan** [tekezo/Karabiner-Elements#979]
As of 0.91.13, device-specific complex modifications can be defined by using the `device_if` or `device_unless` condition types as shown [here](https://github.com/pqrs-org/KE-complex_modifications/blob/master/docs/json/example_device.json).  While you can define device-specific simple modifications in a device object, currently, `complex_modifications` key:value settings are only recognized on the root level of a profile.
(i.e.,`"profiles": [ { "complex_modifications": { ... } } ]`)

For example, the following will not work: 
```
"devices": [
  {
    "disable_built_in_keyboard_if_exists": false,
    "fn_function_keys": {},
    "identifiers": {
      "is_keyboard": true,
      "is_pointing_device": false,
      "product_id": 50475,
      "vendor_id": 1133
    },
    "ignore": false,
    "simple_modifications": {},
    "complex_modifications": { ... } 
  }
]
```
_The ellipsis (...) is not literal, i.e., the actual JSON for the complex modification(s) is left out._

Adding `complex_modifications` support in device objects seems logical, and makes for a more convenient way to add device-specific complex modifications.  Please add this support in the next release.

**Comment by humblehacker** [comment]
I would like to keep this request alive.  I have to remember to manually switch profiles every time I take my laptop away from my desk.  I miss this feature from the old Karabiner.

**Comment by wrinkledeth** [comment]
Also interested, any chance of this happening?
