### ISSUE TITLE
How to restore the default configuration?

### ISSUE THREAD

**Issue by bsburns** [tekezo/Karabiner-Elements#980]
I changed a bunch of Fn key mappings and then realized I did it for all keyboards. I would like to blow away my changes so that I can start fresh again.  Uninstalling Karabiner-elements did not reset the configuration:( When I install fresh again, It still has my changes:( Surely there is an easy way to just restore it back to its default state.

**Comment by adriaanzon** [comment]
You can remove the configuration file located at ~/.config/karabiner/karabiner.json
