### ISSUE TITLE
Function key stopped working with touch bar when Karabiner is active

### ISSUE THREAD

**Issue by brunoedig** [tekezo/Karabiner-Elements#983]
Here's my setup:

MacBook pro with touch bar

Settings > Keyboard
Touch bar shows: App Controls
Press fn key to: Show Control Strip

If I have it like that and I activate karabiner for my keyboard, the function key no longer shows the control strip (nor fn buttons if I change to that for that matter)

Version 0.91.16

Thanks

**Comment by tape88** [comment]
with same issue here after I checked and unchecked some checkboxes in devices tab.

**Comment by maxcolenco** [comment]
I have the same issue.

**Comment by brunoedig** [comment]
Still doesn't work :( I can't use Karabiner at all

**Comment by maxcolenco** [comment]
The issue is present also in version 11.3.0 on MacOS 10.13.1
The sleep trick helps though.

**Comment by brunoedig** [comment]
Sleep trick? What is that?

**Comment by maxcolenco** [comment]
@brunoedig Read a [comment](https://github.com/tekezo/Karabiner-Elements/issues/435#issuecomment-338757603) describing that.

Also there’re several threads with this issue. Still no fix though.

**Comment by HRG1** [comment]
It is a nuisance that needs to be addressed after account log in and if Karabiner-Elements is updated.
In addition to the sleep/wake cycle the same effect is achieved if an authentication dialog is triggered and canceled. Try to drag a font from /Library/Fonts into the trash or use command-delete and cancel the upcoming dialog.

**Comment by brunoedig** [comment]
The cancelling dialog din't work for me. But the sleep cycle thing did. Thanks

**Comment by backslash112** [comment]
Hey guys, please check the solution at #535, works for me.
