### ISSUE TITLE
Use fkeys as function keys for non-apple keyboards?

### ISSUE THREAD

**Issue by jclark-dot-org** [tekezo/Karabiner-Elements#986]
I have an external keyboard (Kanex bluetooth), and the built in option "Use all F1, F2, etc. keys as standard function keys" doesn't have any affect on this keyboard.  In Karabiner 10.x, I could get the desired effect by enabling a series of options under "Change Functional Key (Brightness, Volume, ...)"; I think the plist settings were "remap.consumer_to_fkeys_f1", etc.  Is there any way to do this with Elements?

While I'd like to fix all Fkeys, F1 is of special importance to me, as I need to use CMD-F1 in one of my apps; without the change I need to use CMD-FN-F1.  If I forgot the FN key, they system enables monitor-mirror mode, which really screws up my 3 monitor system :)  The event viewer shows two events when I press CMD-F1:

    eventType:FlagsChanged    code:0x37       name:left_command    flags:Cmd                                misc:
    eventType:SysKeyDown      code:0x3        name:display_brightness_decr...   flags:Cmd                                misc:

I can't find any way to remap "display brighness decrement", or to map all consumer keys to F keys.

**Comment by iKarith** [comment]
I'd like to advocate for this as well.  I have a Logitech K780 keyboard which puts itself into "mac mode" when it detects macOS.  In mac mode, fn-up and fn-dn control screen brightness and there is no support pgup and pgdn.  In PC mode the keyboard sends pgup/pgdn as expected.

I don't use this on an iMac, and I don't change screen brightness all that often even when I do.  I really need those keys in the terminal.  Naturally logitech has about zero interest in fixing this, so I turn to Karabiner.

**Comment by waplet** [comment]
Agree, 
Simple "from" list does not contain display_brightness_increment, although "to" key list contains it.

**Comment by jclark-dot-org** [comment]
This isn't stale, it simply isn't resolved.  Considering that I only ever used original Karibiner to control my F-Keys, it's a major issue for me.  Please do not close.

**Comment by jclark-dot-org** [comment]
Still not stale, still not resolved.  This is a daily source of issues for me.

**Comment by waplet** [comment]
is there actual problem behind it? or can we just pull request?

**Comment by waplet** [comment]
I didn't get into details, but if i recall updating just configs didn't work, or i just have adapted to existing usage of app :/

**Comment by jclark-dot-org** [comment]
Still not stale, still not resolved.  Even though this has been open for over a year with no action, I continue to hold out hope that this will be fixed.  F keys are such a major requirement for developer tools.

**Comment by mellson** [comment]
I have the same problem with an external USB keyboard
