### ISSUE TITLE
Teamspeak 3 Hotkeys interfering

### ISSUE THREAD

**Issue by fttx** [tekezo/Karabiner-Elements#990]
Since the last update (0.91.16) TeamSpeak 3 shortcuts doesn't work anymore.
Teamspeak settings page:
![image](https://user-images.githubusercontent.com/5663423/30521874-6e48b63c-9bc7-11e7-8557-78e2b917e275.png)

Teamspeak doesn't see any keypress. 
If i uncheck my keyboard from the karabiner-elements "modify events from this device" list, the global keypress events are passed again to Teamspeak. Is there any workaround?

**Comment by bearpig** [comment]
Seeing the same problem here.
Any ideas?

**Comment by fttx** [comment]
I don't know, it fixes itself after the computer is on for a couple of hours.
Do you have issues with other applications? I've noticed it only with TeamSpeak

**Comment by bearpig** [comment]
Only noticed it in Teamspeak...
Weirdly it's fine for the onboard keyboard (macbook pro) but not for the external USB keyboard.

**Comment by fttx** [comment]
Same thing for me, i've a Logitech K270

**Comment by AlexeyPopov** [comment]
I have the same issue.
Only Teamspeak hotkeys doesn't work.

**Comment by fttx** [comment]
The issue persists

**Comment by fttx** [comment]
Still not resolved
