### ISSUE TITLE
Doesn't run on 13'' MacBook Pro 2016 

### ISSUE THREAD

**Issue by qydxyx** [tekezo/Karabiner-Elements#991]
I am using macOS 10.12.6 and I tried a couple of versions of Karabiner Elements including the latest and some old versions but every time when I launch the app, it shows only "Karabiner-Elements quit unexpectedly". But for my iMac, which is running the same version of macOS, works smoothly.

**Comment by qydxyx** [comment]
Finally, I found the answer. If you have the same issue, try to change the "Sharing & Permissions" settings in your User info to "Read & Write" instead of "Read Only". Save the change by hitting "Apply to enclosed items". Then execute the following command in your terminal:

diskutil resetUserPermissions / `id -u`

And you are done!
Hope this could help.

**Comment by shalgrim** [comment]
Where should I change the sharing & permissions settings? On the Applications folder in Finder?

And I am getting an error message about the incorrect number of parameters when I to run diskutil

**Comment by qydxyx** [comment]
The "Sharing & Permissions" is at the bottom of the info panel of your home folder. You can find it in the sidebar of Finder.

**Comment by shalgrim** [comment]
Home folder. Okay. I see it on every folder, so I didn't know if it had to be a specific one. Thanks. But I'm already `Read & Write`.

And then when I try to run the `diskutil` command I get:

```
Scotts-MacBook-Pro:~ scott$ diskutil resetUserPermissions / id -u
Incorrect number of parameters
Usage:  diskutil resetUserPermissions MountPoint|DiskIdentifier|DeviceNode UID
Reset the permissions of a user home directory.
Ownership of the affected disk is required.
```

**Comment by qydxyx** [comment]
May be you should check the original solution to see if you miss any steps:
https://support.apple.com/en-us/HT203538

**Comment by shalgrim** [comment]
Thanks! That link did it.

The command might be better formatted as `diskutil resetUserPermissions / `id -u``

**Comment by qydxyx** [comment]
My bad. Glad you fixed it!
