### ISSUE TITLE
Question: How to for input source to English when click Esc in specific apps?

### ISSUE THREAD

**Issue by jostyee** [tekezo/Karabiner-Elements#994]
I'd like to Switch to English input when click Esc in apps like MacVim, so I don't need to do it manually to use Vim's command mode.

In Karabiner we have [`vkchangeinputsourcedef`](https://webcache.googleusercontent.com/search?q=cache:eR3rkFIsf5wJ:https://pqrs.org/osx/karabiner/xml.html.en+&cd=1&hl=en&ct=clnk&gl=us&client=safari) to help, but I don't know how to get the same function in Karabiner-Elements.

**Comment by ww7** [comment]
I use for example:
` "shell_command": "open -a ~/Applications/bin/changeInput --args 'English (typography)'"
`
Bin's are [here](https://www.dropbox.com/sh/u12co4lmq57zumy/AACGK9WkKFwUloPy8SYsj2JXa?dl=0)

changeInput and changeInput2 are same, now i lost in memory why two versions I have
https://github.com/CraigWilliams/ChangeInput

issw from [vim-xkbswitch](https://github.com/vovkasm/input-source-switcher)

**Comment by ww7** [comment]
I need _vkchangeinputsourcedef_ in Karabiner-Elements too.

Now I use
`"shell_command": "open -a ~/Applications/bin/changeInput --args 'English (typography)'"
`
Bin's [here](https://www.dropbox.com/sh/u12co4lmq57zumy/AACGK9WkKFwUloPy8SYsj2JXa?dl=0)

**changeInput**
https://github.com/CraigWilliams/ChangeInput
https://gist.github.com/amitu/2146751

Alternatively **issw** from vim-xkbswitch 
https://github.com/vovkasm/input-source-switcher

In high CPU load this workflow sometimes is laggy

**Comment by TimLeaf** [comment]
https://github.com/CraigWilliams/ChangeInput
How to get the name(arg) of input source?
I try it on Chinese Pinyin, It said Chinese (Pinyin) not available.
and it can't get name of Google Japanese Input tools.

**Comment by dstd** [comment]
@TimLeaf just switch into the input source you wanted and run `changeInput` without arguments, it will show you the name of it

**Comment by TimLeaf** [comment]
@dstd Thanks for your reply.
I try it, but it doesn't work.
$ changeInput
Pinyin
$ changeInput Pinyin
Pinyin not available

**Comment by dstd** [comment]
@TimLeaf try to use `changeInput "Pinyin - Simplified"` (or Traditional, depending on your layout). I believe it's changeInput's issue https://github.com/CraigWilliams/ChangeInput/issues/1

**Comment by TimLeaf** [comment]
@dstd I got it! Thanks very much!

**Comment by ww7** [comment]
@tekezo @dstd 
Any chance for pull "set_inputsource" feature in master branch?

**Comment by ww7** [comment]
Version 11.2 will provide feature for changing keyboard layout's (input sources)
[NEWS 11.2 beta](https://github.com/tekezo/Karabiner-Elements/blob/94bf0b67a41a7db9d8b083ea1728b84b4bb076b6/NEWS.md)
