### ISSUE TITLE
Sticky keys break to + to_if_alone

### ISSUE THREAD

**Issue by snarfed** [tekezo/Karabiner-Elements#996]
first off, you all have made awesome progress on karabiner elements. i'm finally switching to it permanently. thank you for all your hard work!

i noticed recently that turning on mac os x's sticky keys breaks the _Post left_ctrl when return_or_enter is hold_ complex modification in https://pqrs.org/osx/karabiner/complex_modifications/json/caps_and_return_to_ctrl.json . when sticky keys is on, pressing return seems to activate both `to ... right_control` _and_ `to_if_alone ... return_or_enter`, so the effect is `control + return`. ideally sticky keys wouldn't affect the return key.

thanks in advance!

**Comment by snarfed** [comment]
this bug is still present in 11.6.0.

**Comment by tekezo** [comment]
Cancel sticky key in `to_if_alone`.

```json
"to_if_alone": [
    {
        "key_code": "left_control"
    },
    {
        "key_code": "left_control"
    },
    {
        "key_code": "return_or_enter"
    }
],
```

**Comment by snarfed** [comment]
thank you!

**Comment by snarfed** [comment]
really? every two months?
