### ISSUE TITLE
FN key of Logitech K380 not read by Karabiner-Elements

### ISSUE THREAD

**Issue by gsapu** [tekezo/Karabiner-Elements#999]
Using Logitech K380 (bluetooth keyboard), trying to swap the FN and CTRL keys in bottom left, to reflect what's on the standard english mac keyboard.

Pressing CTRL works fine, and I've mapped it to FN successfully. Now hitting left_ctrl + backspace, acts as 'delete'.

Pressing FN in EventsViewer shows nothing. I tried mapping it (FN -> CTRL), and no change.
The key itself works. I can hit FN+Backspace, and it acts as 'delete'.

I now have two FN keys and no CTRL.

Ideas how to solve?

**Comment by cmsj** [comment]
Was this working in a previous version of Karabiner? I wonder if maybe the keyboard doesn't send an Fn event, and does the modifications locally

**Comment by nguyenhimself** [comment]
I think most if not all non-Apple-keyboard Fn keys deeply integrate with the hardware and do not send any keystroke event.

Some keyboards, especially mechanical ones, come with custom softwares that lets you customize the Fn key, but I don't think Karabiner can help here.

**Comment by danielweck** [comment]
Same here, I am not able to swap the FUNCTION and CONTROL keys on my Logitech K380. Although as mentioned above, Karabiner probably can't do anything if the keyboard hardware does not send the `fn` code when the key is pressed on its own :(

By the way, duplicate issue: https://github.com/tekezo/Karabiner-Elements/issues/966

**Comment by zomerfeld** [comment]
same problem...

**Comment by cmsj** [comment]
I think @nguyenhimself has the answer here - if the keyboard isn't sending an event, there's not going to be anything KE can do.

**Comment by weiweihuanghuang** [comment]
I have this issue too.

**Comment by wendyliga** [comment]
sad to know that, can we add event based on keyboard press ?

**Comment by suiluj** [comment]
i have a logitech k380 and tried to swap the fn key and ctrl key too. same exact problem.

does someone here have a solution in the mean time? i would be really happy. at the moment i have to remember the wrong order of the keys and this create confusion when switching between laptop and k380 keyboards. really bad support from logitech that you cannot change this behaviour :/

**Comment by hieu-v** [comment]
Hi all, has anyone found a way to swap fn and ctrl or change fn to ctrl yet ?

**Comment by zacariah** [comment]
Hi all, 
Anyone got a workaround for this? By sending a mock event at the keypress or something? I'm seeing this on a Dell keyboard

**Comment by ridhoperdana** [comment]
any solution for this one? just recently bought the K380 keyboard not knowing the FN key cannot be remapping.

**Comment by otobrglez** [comment]
Same problem on Logitech G513. Right FN key doesn't emit anything or event viewer doesn't show.

**Comment by hieu-v** [comment]
At first I was annoyed with the Logitech keyboard and wanted to change the position of the Ctrl and Fn keys, but after a few months of use, I started to get used to that key position. Now I feel normal and can use a macbook keyboard or logitech keyboard without problems. 😆

**Comment by berkayakcay** [comment]
Hi, is there any technical explanation about not detecting  fn key on Logitech keyboards.

**Comment by weiweihuanghuang** [comment]
I've since learned most keyboards' Fn keys are hardware level and do not send a scan code so there isn't a workaround. Apple is in the minority when it comes to how it's Fn keys work

**Comment by simonswiss** [comment]
> At first I was annoyed with the Logitech keyboard and wanted to change the position of the Ctrl and Fn keys, but after a few months of use, I started to get used to that key position. Now I feel normal and can use a macbook keyboard or logitech keyboard without problems. 😆

Looks like this is the fix I will have to go through for this issue! 😅

**Comment by glebsap** [comment]
Given that I have both a macbook and the Logitech keyboard, and switching
between them always had me pushing the wrong keys (fn / ctrl) - I simply
ended up buying a new apple keyboard and throwing out the Logitech keyboard.

**Comment by ssh352** [comment]
same issue on Realforce R2

**Comment by IgorFobia** [comment]
Same problem here

**Comment by jdetoro91** [comment]
Same problem here!!!!!!1

**Comment by suleymantaspinar** [comment]
Same problem here

**Comment by iahu** [comment]
bad news

**Comment by MuhammedZakir** [comment]
Before commenting here, do check if macOS is able to detect `fn` key. You can use a on-screen keyboard to verify it.

Repeating:
> I've since learned most keyboards' Fn keys **are hardware level and do not send a scan code** so there isn't a workaround. Apple is in the minority when it comes to how it's Fn keys work

**Comment by jearton** [comment]
same problem with RK987

**Comment by ycjcl868** [comment]
same problem with Logitech K380

**Comment by DHL0911** [comment]
same problem with Samsung keyboard

**Comment by hmars-t** [comment]
same problem with Logitech K380

**Comment by Henry-Hong** [comment]
same issue with K380.

**Comment by stevencjyu** [comment]
Same issue with Aibo LY-ENKB06N

**Comment by jamylak** [comment]
ahhh just realised this for G915 TKL

**Comment by viaSeunghyun** [comment]
If you know that a keyboard is a collection of many sensors, it's impossible to solve the lack of signal from a sensor with SW. Everyone needs to know and understand this.

**Comment by JihedMrouki** [comment]
same issue here as for 2025, the on screen keybaord doesnt detect the fn key ( globe key ) on my k380s keyboard, so its a hardware issue not software related..

**Comment by Chris-He01** [comment]
damn, sad to see this cannot be solved. k380 should be designed better.
